### PR TITLE
[iOS] TapGestureRecognizer should not fire when view is not enabled

### LINKED ISSUE #18995: TapGestureRecognizer disregards parent's IsEnabled status on iOS and Catalyst.
### Description

A TapGestureRecognizer will not obey the IsEnabled status of its parent on iOS and Catalyst. It will register touch actions and trigger its Tapped method. Do not happen on Android. Not tested on Windows.

### Steps to Reproduce

1. Clone the attached repo
2. Build and Run on iOS Simulator or Catalyst

The "Click me too" button (composed by a Grid, a BoxView and  a Label) under the normal Button should not be clickable, but it is.

### Link to public reproduction project repository

https://github.com/derlidio/TapGestureBug.git

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 17, macOS Sonoma 14.1.1 (23B81)

### Did you find any workaround?

No workaround besides checking for the control IsEnabled state on it's Tapped method.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Redth**
### Description of Change

On Android we check if the control is enabled or not for sending the touch event in the gesture manager: https://github.com/dotnet/maui/blob/79695fbb7ba6517a334c795ecf0a1d6358ef309a/src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Android.cs#L66

We were not doing the same thing on iOS.  This takes a similar approach now as android does.

### Issues Fixed

Fixes #18995

### CODE REVIEW

**Review by PureWeen — DISMISSED** [review]

File: src/Controls/tests/TestCases/Elements/TapGestureGallery.cs [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+				IsEnabled = false, // Disabled
+				HeightRequest = 100,
+				WidthRequest = 200,
+				BackgroundColor = Microsoft.Maui.Graphics.Colors.Bisque,
+				Children = { new Label { Text = "DisabledTapSurface", AutomationId = "DisabledTapSurface" } }
+			};
+
+			// Wire up the tap gesture recognizer, it should never fire
+			var disabledTapRecognizer = new TapGestureRecognizer();
+			disabledTapRecognizer.Tapped += (sender, args) => { disabledTapResults.Text = "Success"; };
```
Comment (mattleibow) [inline src/Controls/tests/TestCases/Elements/TapGestureGallery.cs:43]: Maybe this should be "Failed"? Then the test can be Text != Failed?

**Review by mattleibow — APPROVED** [review]
