### PR TITLE
Fix null handling in UpdateIndicatorLayout method (#22361)

### LINKED ISSUE #22361: IndicatorLayout isn't being correctly cleared out when bindable property is set to null
https://github.com/dotnet/maui/blob/39f90eeb9866940117d5501f8b864498b9db0c88/src/Controls/src/Core/IndicatorView/IndicatorView.cs#L155-L159

**Meaningless code found inside the indicatorView.cs file**

**IndicatorView.IndicatorLayout is already null, still use as to convert to IndicatorStackLayout**

### PR DESCRIPTION
**Pull request by kubaflo**
Fixes https://github.com/dotnet/maui/issues/22361

### CODE REVIEW

File: src/Controls/src/Core/IndicatorView/IndicatorView.cs [hunk 1]
```diff
@@ -152,7 +152,7 @@ static void UpdateIndicatorLayout(IndicatorView indicatorView, object newValue)
 			{
 				indicatorView.IndicatorLayout = new IndicatorStackLayout(indicatorView) { Spacing = DefaultPadding };
 			}
-			else if (indicatorView.IndicatorLayout == null)
+			else if (indicatorView.IndicatorLayout != null)
```
Comment (PureWeen) [inline src/Controls/src/Core/IndicatorView/IndicatorView.cs:155]:
```suggestion
			else if (indicatorView.IndicatorLayout is not null)
```

Can you add a unit test as well?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/IndicatorView/IndicatorView.cs (hunk 1 above)
Comment (kubaflo) [reply src/Controls/src/Core/IndicatorView/IndicatorView.cs:155]: sure

**Review by rmarinho — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]
