### PR TITLE
[iOS, Android] Fix for Incorrect Orientation in HEIC and JPG Images During Resize

### LINKED ISSUE #23832: Some HEIC photos is upside down after using PlatformImage.Resize
### Description

In iOS and macOS, HEIC is common format for photos. 
Some HEIC photos is upside down after using PlatformImage.Resize
But PlatformImage.Downsize no problem.

### Steps to Reproduce

See sample project:
Simulator Screenshot - iPhone 15 - 2024-07-25 at 23 41 53

### Link to public reproduction project repository

https://github.com/bycreal/PlatformImageResizeIssue

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 17, macOS 14

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by HarishwaranVijayakumar**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue Details

- In GraphicsView, Some Images with format like HEIC and JPG, are rendered upside down after using in platform.resize and canvas.draw.

### Root Cause of the issue

- iOS Platform: When used in the resize and draw methods, the image is rendered on the canvas without respecting its orientation, resulting in it appearing upside down.
- Android Platform: When converting a stream to a bitmap, the image metadata is not preserved; the resulting bitmap contains only the pixel data in a matrix form.

### Description of Change

- iOS Platform: Modified `PlatformImage.FromStream` to normalize the orientation of images by calling `NormalizeOrientation` on the loaded `UIImage`. This ensures the image is displayed with the correct orientation.
- Android Platform: Updated `PlatformImage.FromStream` to read EXIF orientation metadata and apply necessary rotations to HEIC and JPG images using a new helper method, `RotateBitmap`. This ensures images are displayed with the correct orientation. 

### Issues Fixed
Fixes #23832 

### Tested the behavior in the following platforms
 
- [x] Windows
- [x] Android
- [x] iOS
- [x] Mac

### Output
 
| Before Fix | After Fix |
|----------|----------|
|  |  |
|  |  |

### CODE REVIEW

File: src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs [hunk 1]
```diff
@@ -149,8 +151,63 @@ public IImage ToPlatformImage()
...
+					matrix.PostRotate(270);
+					break;
+				case 8: // Rotate 270
+					matrix.PostRotate(270);
+					break;
+				default:
+					return bitmap;
+			}
+			var rotated = Bitmap.CreateBitmap(bitmap, 0, 0, bitmap.Width, bitmap.Height, matrix, true);
+			bitmap.Dispose();
```
Comment (MartyIX) [inline src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs:245]: Could you please explain why this is here?

Comment (HarishwaranVijayakumar) [reply src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs:245]: @MartyIX, This code handles image orientation correction on Android, specifically for formats like HEIC and JPG that include orientation metadata. It ensures the resulting bitmap is always oriented upright.

Comment (MartyIX) [reply src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs:245]: Right, but why is it necessary to have the `bitmap.Dispose()` call right here?

Comment (HarishwaranVijayakumar) [reply src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs:245]: @MartyIX, When we use Bitmap.CreateBitmap() with a transformation matrix, it creates a new bitmap object. The original bitmap is no longer needed after the rotated/flipped version is created. Calling bitmap.Dispose() releases the native memory held by the original bitmap, preventing memory leaks—especially important on Android, where bitmaps can consume significant memory.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Error compiling the `Controls.TestCases.HostApp.csproj`:
```
CSC : error CS1566: Error reading resource 'Controls.TestCases.HostApp.Resources.Images.img_0111.heic' -- 'Could not find file '/Users/builder/azdo/_work/1/s/src/Controls/tests/TestCases.HostApp/Resources/Images/img_0111.heic'.' [/Users/builder/azdo/_work/1/s/src/Controls/tests/TestCases.HostApp/Controls.TestCases.HostApp.csproj::TargetFramework=net9.0-android]
    4 Error(s)
```

**Comment by HarishwaranVijayakumar** [comment]
@jsuarezruiz, I have modified the image location, Please let me know if you have any concerns.

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23832.cs [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+	}
+
+	public override string Issue => "Some HEIC photos is upside down after using PlatformImage.Resize";
+
+	[Test]
+	[Category(UITestCategories.GraphicsView)]
+	public void HEICImageShouldNotRenderUpsideDown()
+	{
+		App.WaitForElement("DrawableLabel");
+		VerifyScreenshot();
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23832.cs:21]: Pending snapshots, already available in the latest build.
image

Could you commit the images?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23832.cs (hunk 2 above)
Comment (HarishwaranVijayakumar) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23832.cs:21]: @jsuarezruiz, I have committed the images except for Windows, as the Windows image is not as expected. I’ve attached the image for reference.

HEICImageShouldNotRenderUpsideDown

File: src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs [hunk 3]
```diff
@@ -149,8 +151,70 @@ public IImage ToPlatformImage()
 
 		public static IImage FromStream(Stream stream, ImageFormat formatHint = ImageFormat.Png)
 		{
-			var bitmap = BitmapFactory.DecodeStream(stream);
+			// Use original stream if it's seekable, else copy to memory stream
+			var seekableStream = stream.CanSeek ? stream : new MemoryStream();
```
Comment (jsuarezruiz) [inline src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs]: The `MemoryStream` is never disposed. Use a using statement.

File: src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs [hunk 4]
```diff
@@ -149,8 +151,70 @@ public IImage ToPlatformImage()
 
 		public static IImage FromStream(Stream stream, ImageFormat formatHint = ImageFormat.Png)
 		{
-			var bitmap = BitmapFactory.DecodeStream(stream);
+			// Use original stream if it's seekable, else copy to memory stream
```
Comment (jsuarezruiz) [inline src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs]: Here, can check first if the original stream is seekable, and in that case, avoid to copy to the new stream.
```
// Use original stream if seekable, otherwise copy to memory stream
if (stream.CanSeek)
```

File: src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs [hunk 5]
```diff
@@ -149,8 +151,70 @@ public IImage ToPlatformImage()
...
+				case 2: // Flip horizontal
+					matrix.PreScale(-1, 1);
+					break;
+				case 3: // Rotate 180
+					matrix.PostRotate(180);
+					break;
+				case 4: // Flip vertical
+					matrix.PreScale(1, -1);
+					break;
+				case 5: // Transpose (flip vertical + rotate 90)
```
Comment (jsuarezruiz) [inline src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs:226]: 👍 comments

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs (hunk 3 above)
Comment (HarishwaranVijayakumar) [reply src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs]: @jsuarezruiz, As suggested modified the fix

File: src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs (hunk 4 above)
Comment (HarishwaranVijayakumar) [reply src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs]: @jsuarezruiz, As suggested modified the fix

**Comment by kubaflo** [comment]
@HarishwaranVijayakumar could you please update iOS snapshot?

**Review by kubaflo — DISMISSED** [review]

**Comment by kubaflo** [comment]
@HarishwaranVijayakumar looks good! Can you lease verify if anything from the AI Summary makes sense?

**Comment by HarishwaranVijayakumar** [comment]
> @HarishwaranVijayakumar looks good! Can you lease verify if anything from the AI Summary makes sense?

@kubaflo, Addressed the valid concerns as suggested.

**Review by kubaflo — DISMISSED** [review]

**Review by kubaflo — APPROVED** [review]

**Comment by kubaflo** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong> — <a href="https://github.com/dotnet/maui/commit/78286cb106c0ff05ab0c6b666e335b1c1dc2d1e5"><code>78286cb</code></a> · <strong>Restrict the test on windows</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

**Issue:** #23832 - Some HEIC photos is upside down after using PlatformImage.Resize
**PR:** #29769 - [iOS, Android] Fix for Incorrect Orientation in HEIC and JPG Images During Resize
**Platforms Affected:** iOS, Android (issue originally reported for iOS/macOS, PR extends to Android)
**Files Changed:** 2 implementation, 5 test (+ 3 snapshot images + 1 HEIC test asset)

### Key Findings
- **Root cause (iOS):** `UIImage.LoadFromData` preserves EXIF orientation metadata but doesn't apply it visually. The image pixel data is correct but the UIImage orientation flag isn't normalized, causing it to render upside-down.
- **Root cause (Android):** `BitmapFactory.DecodeStream` strips EXIF metadata and returns only raw pixel data without rotation applied.
- **iOS fix:** Single-line change in `PlatformImage.FromStream` — wraps the returned `UIImage` with `NormalizeOrientation(disposeOriginal: true)`. The `NormalizeOrientation` extension already existed in `UIImageExtensions.cs` and handles all UIImageOrientation cases.
- **Android fix:** New `CreateImageFromSeekableStream` private method that reads EXIF orientation via `ExifInterface` (API 24+), decodes the bitmap, then applies rotation via a `RotateBitmap` helper. Handles non-seekable streams by copying to a MemoryStream first.
- **Tests:** UI test via `GraphicsView` + `IDrawable` rendering an HEIC image, verified with `VerifyScreenshot()`. Test is gated to non-Windows platforms (`#if TEST_FAILS_ON_WINDOWS`).

### Concerns Identified from Code Review Comments
1. **ExifInterface not disposed (Android)** - `new ExifInterface(seekableStream)` is never disposed, potential memory leak. (Copilot reviewer flagged, author appears to have addressed some suggestions)
2. **Null check missing for UIImage (iOS)** - `UIImage.LoadFromData(data)` can return null for invalid data; calling `.NormalizeOrientation()` on null would throw `NullReferenceException`.
3. **Test coverage** - Test only verifies HEIC; JPG with EXIF orientation not tested. Also tests `DrawImage` but not `Resize` which is the originally reported API.

### Prior Agent Reviews
The PR has label `s/agent-reviewed` and `s/agent-suggestions-implemented`, indicating prior agent review has been completed. The `s/agent-fix-pr-picked` label is also present. Some suggestions from copilot-pull-request-reviewer were implemented.

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #29769 | iOS: NormalizeOrientation on load; Android: EXIF+RotateBitmap | ⏳ PENDING (Gate) | `PlatformImage.cs` (iOS + Android) | Missing null check on iOS; ExifInterface not disposed on Android |

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

### Gate Result: ✅ PASSED

**Platform:** iOS
**Mode:** Full Verification

- Tests FAIL without fix: ✅
- Tests PASS with fix: ✅

**Fix files verified:**
- `src/Graphics/src/Graphics/Platforms/iOS/PlatformImage.cs`
- `src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs`

The test `HEICImageShouldNotRenderUpsideDown` (Issue23832) correctly:
1. FAILS when the fix is reverted (bug is reproduced)
2. PASSES when the fix is applied

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| 1 | try-fix (claude-opus-4.6-1m) | CGBitmapContext + CGAffineTransform per EXIF case in FromStream PASS | 2 files (+93 UIImageExtensions, +1/-1 PlatformImage) | Verbose; explicit per-case transforms | | 
| 2 | try-fix (claude-sonnet-4.6) | Canvas-level fix in PlatformCanvas. UIImage.Draw for non-Up orientation PASS | 1 file (PlatformCanvas.cs +26) | Fixes draw time, not load time; more complex | | DrawImage 
| 3 | try-fix (gpt-5.3-codex) | Normalize inside PlatformImage.Resize()  FAIL | 1 file | Too  test uses DrawImage path |narrow only | 
| 4 | try-fix (gemini-3-pro-preview) | CoreImage CIImage.CreateByApplyingOrientation + CIContext render PASS | 1 file (UIImageExtensions.cs) | Modern GPU path; adds CoreImage dependency | | 
| 5 | try-fix (claude-opus-4.6-1m) | CGImageSource thumbnail + CreateThumbnailWithTransform=true (ImageIO decode-time PASS | 1 file (PlatformImage.cs +43/-2) | Cleanest: decode-time correction, no post-decode context |) | 
| PR | PR #29769 | iOS: NormalizeOrientation(disposeOriginal:true) via UIGraphicsImageRenderer; Android: EXIF+RotateBitmap PASSED (Gate) | 2 platform files | Simple 1-line iOS change; uses existing extension | | 

### Cross-Pollination
| Model | Round | New Ideas? | Details |
|-------|-------|------------|---------|
| claude-opus-4.6-1m | 2 | Yes | CGImageSource thumbnail with transform (ImageIO) |
| claude-sonnet-4.6 | 2 | Yes | CGImageSource + strip orientation metadata before UIImage |
| gpt-5.3-codex | 2 | Yes | ImageIO thumbnail decode with orientation transform |
| gemini-3-pro-preview | 2 | Yes | CGImageSource + CreateThumbnailWithTransform |
| claude-sonnet-4.6 | 3 | No | All strategies covered |

**Exhausted:** Yes
**Selected Fix:** PR # The PR's fix is the simplest and most maintainable. One-line change in `FromStream` leveraging the pre-existing `NormalizeOrientation` extension. Alternative approaches are all valid but more complex or add new framework dependencies.29769

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

## ✅ Final Recommendation: APPROVE

### Phase Status
| Phase | Status | Notes |
|---|---|---|
| Pre-Flight | ✅ COMPLETE | Issue #23832, 2 impl files + 5 test files, iOS + Android |
| Gate | ✅ PASSED | iOS — HEICImageShouldNotRenderUpsideDown FAILS without fix, PASSES with fix |
| Try-Fix | ✅ COMPLETE | 5 attempts (4 PASS, 1 FAIL); cross-pollination exhausted after round 3 |
| Report | ✅ COMPLETE | |

### Summary

PR #29769 fixes a real bug where HEIC and JPG images with EXIF orientation metadata render upside-down after loading via `PlatformImage.FromStream`. The fix is correct, well-structured, and verified by a UI test with visual snapshot. Five independent alternative approaches were explored — all passing ones are more complex or add dependencies. The PR's approach is the simplest correct fix.

**Selected Fix:** PR #29769's fix
**Try-Fix Result:** `s/agent-fix-pr-picked`

### Root Cause

- **iOS:** `UIImage.LoadFromData` carries the EXIF orientation flag as metadata (`UIImage.Orientation`) but does not normalize the pixel data. When drawn via CoreGraphics (`CGContext.DrawImage` uses `CGImage` which ignores orientation), the image renders without the expected rotation.
- **Android:** `BitmapFactory.DecodeStream` strips all EXIF metadata and returns raw pixel data without applying orientation. The resulting Bitmap contains only unrotated pixels.

### Fix Quality

**iOS fix (excellent):**
- Single-line change in `FromStream`: `image.NormalizeOrientation(disposeOriginal: true)`
- Leverages existing `UIImageExtensions.NormalizeOrientation` using `UIGraphicsImageRenderer`
- `disposeOriginal: true` correctly disposes the intermediate UIImage to avoid memory leak (this suggestion from copilot reviewer was already implemented)
- The `NormalizeOrientation` is a no-op when orientation is already `.Up` (efficient for normal images)

**iOS fix — remaining concern:**
- ⚠️ **No null check** for `UIImage.LoadFromData(data)` return value. If `data` is null or malformed, `image` will be null and `image.NormalizeOrientation()` will throw `NullReferenceException`. The original code had the same issue, so this is pre-existing, but the PR is a good opportunity to add `if (image == null) return null;`

**Android fix (good, minor issues):**
- Correctly reads EXIF orientation via `ExifInterface` (API 24+ only, with appropriate fallback)
- Handles non-seekable streams by copying to `MemoryStream` first (suggested by reviewer, already addressed)
- `MemoryStream` correctly wrapped in `using` (addressed)
- Comprehensive EXIF orientation handling for all 8 EXIF cases in `RotateBitmap`
- `Matrix` and original `bitmap` disposed after transformation (avoids memory leaks)
- ⚠️ **`ExifInterface` not disposed** — `new ExifInterface(seekableStream)` creates a native Java object that should be disposed. Should use `using var exif = new ExifInterface(seekableStream);`

**Tests (adequate):**
- UI test verifies correct rendering via `VerifyScreenshot()` — appropriate for a visual rendering bug
- Snapshots committed for iOS, Android, and Mac
- Test is correctly excluded from Windows (`#if TEST_FAILS_ON_WINDOWS`) since HEIC crashes on Windows CI
- ⚠️ Test only covers HEIC format; JPG with EXIF orientation is not tested (mentioned in PR but no test)
- ⚠️ Test doesn't exercise `Resize()` path specifically (original issue was with `Resize`), only `DrawImage`

### Try-Fix Comparison

| Approach | Complexity | Dependencies | Result |
|----------|------------|--------------|--------|
| **PR: NormalizeOrientation (UIGraphicsImageRenderer)** | Minimal (1 line) | UIKit (existing) | ✅ PASS |
| Attempt 1: CGBitmapContext + per-case CGAffineTransform | High (+93 lines) | CoreGraphics | ✅ PASS |
| Attempt 2: Canvas-level UIImage.Draw intercept | Medium (+26 lines, canvas layer) | UIKit | ✅ PASS |
| Attempt 4: CoreImage CIImage pipeline | Medium (+20 lines) | CoreImage (new) | ✅ PASS |
| Attempt 5: CGImageSource thumbnail decode-time | Medium (+43 lines) | ImageIO (new) | ✅ PASS |

The PR's approach wins on simplicity — reuses existing code, minimal diff.

### Suggested Improvements (non-blocking)

1. **Dispose `ExifInterface` on Android** (minor memory leak):
   ```csharp
   using var exif = new ExifInterface(seekableStream);
   ```

2. **Null check for UIImage on iOS** (prevents NRE on invalid data):
   ```csharp
   var image = UIImage.LoadFromData(data);
   if (image == null)
       return null;
   return new PlatformImage(image.NormalizeOrientation(disposeOriginal: true));
   ```

Both are minor quality improvements; the core fix is sound and ready to merge.

</details>

---

</details>



<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

# PR #29769 Finalization Review

**PR:** [#29769 - [iOS, Android] Fix for Incorrect Orientation in HEIC and JPG Images During Resize](https://github.com/dotnet/maui/pull/29769)
**Author:** @HarishwaranVijayakumar
**Status:** Open (Approved by @kubaflo on 2026-02-18, blocked by CI)
**Issues Fixed:** Fixes #23832

---

## Phase 1: Title & Description

### ⚠️ Title: Needs Minor Update

**Current:** `[iOS, Android] Fix for Incorrect Orientation in HEIC and JPG Images During Resize`

**Recommended:** `[iOS, Android] PlatformImage: Fix EXIF orientation for HEIC/JPG images`

**Reason:** "During Resize" is misleading — the fix is in `PlatformImage.FromStream` (the loading step), not in a resize-specific code path. The bug manifests during rendering of any operation (including resize), but the root cause is EXIF orientation not being applied when loading. The recommended title better captures the component (`PlatformImage`) and the nature of the fix (EXIF orientation).

---

### ✅ Description: Good — Keep with Minor Additions

**Quality Assessment:**

| Dimension | Assessment |
|-----------|------------|
| Structure | ✅ Clear sections (Root Cause, Description of Change, Issues Fixed) |
| Technical depth | ✅ Platform-by-platform breakdown, specific method names |
| Accuracy | ✅ Matches actual diff |
| Completeness | ✅ Platforms tested, before/after screenshots |
| NOTE block | ✅ Present at top |

**Action:** Keep existing description as-is. Optionally add one detail about the Android API 24+ guard (see below).

**Optional Enhancement** — add under "Description of Change → Android Platform":

> - Android API 24 (Android 7.0) or higher is required for `ExifInterface` stream constructor. On older API levels, images are decoded without EXIF correction as a fallback, preserving existing behavior.

---

## Phase 2: Code Review

### 🔴 Critical Issues

**1. `ExifInterface` not disposed (Android)**
- **File:** `src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs`, line 186
- **Problem:** `var exif = new ExifInterface(seekableStream)` — `ExifInterface` extends `Java.Lang.Object` and holds native resources. It is never disposed, causing a resource leak on every image load.
- **Recommendation:**
  ```csharp
  using var exif = new ExifInterface(seekableStream);
  var orientation = exif.GetAttributeInt(ExifInterface.TagOrientation, 1);
  ```

**2. `BitmapFactory.DecodeStream` null not handled (Android)**
- **File:** `src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs`, lines 189, 200
- **Problem:** `BitmapFactory.DecodeStream` returns `null` if the stream cannot be decoded (corrupted/unsupported format). Neither call site checks for null before passing to `RotateBitmap` or `new PlatformImage(bitmap)`. This will cause a `NullReferenceException` at `bitmap.Width` inside `RotateBitmap`, or later when the PlatformImage is used.
- **Recommendation:**
  ```csharp
  bitmap = BitmapFactory.DecodeStream(seekableStream);
  if (bitmap is null)
      return null; // or throw a meaningful exception
  ```

**3. Original bitmap not disposed if `Bitmap.CreateBitmap` throws (Android)**
- **File:** `src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs`, `RotateBitmap` method (~line 243)
- **Problem:** `bitmap.Dispose()` is only called on the happy path after `Bitmap.CreateBitmap` succeeds. If `CreateBitmap` throws, the original `bitmap` is leaked.
- **Recommendation:** Use try/finally:
  ```csharp
  Bitmap rotated;
  try
  {
      rotated = Bitmap.CreateBitmap(bitmap, 0, 0, bitmap.Width, bitmap.Height, matrix, true);
  }
  finally
  {
      matrix.Dispose();
      bitmap.Dispose();
  }
  return rotated;
  ```

---

### 🟡 Suggestions

**4. Broad `catch (Exception)` swallows all errors silently**
- **File:** `src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs`, line 196
- **Problem:** `catch (Exception)` catches everything including `OutOfMemoryException` and `ThreadAbortException`. The fallback silently drops EXIF orientation correction with no indication of failure.
- **Recommendation:** Narrow to expected exceptions and add debug logging:
  ```csharp
  catch (IOException ex)
  {
      System.Diagnostics.Debug.WriteLine($"Failed to read EXIF orientation: {ex.Message}");
      seekableStream.Position = 0;
      bitmap = BitmapFactory.DecodeStream(seekableStream);
  }
  ```

**5. `RotateBitmap` missing explicit `private` access modifier**
- **File:** `src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs`, line 211
- **Problem:** `static Bitmap RotateBitmap(...)` defaults to `private` in C# but is inconsistent with the explicit `private static` used on `CreateImageFromSeekableStream`. While functionally equivalent, explicit modifiers improve readability.
- **Recommendation:** Change to `private static Bitmap RotateBitmap(...)`.

**6. `IImage` not disposed in `Issue23832_Drawable.Draw`**
- **File:** `src/Controls/tests/TestCases.HostApp/Issues/Issue23832.cs`, line ~43
- **Problem:** `image = PlatformImage.FromStream(stream)` creates an `IImage` that implements `IDisposable`, but it is never disposed. This leaks the underlying platform bitmap on every draw call.
- **Recommendation:**
  ```csharp
  using Stream stream = assembly.GetManifestResourceStream("...");
  using IImage image = PlatformImage.FromStream(stream);
  if (image is not null)
      canvas.DrawImage(image, 0, 0, 300, 300);
  ```
  Note: the `stream` is already disposed correctly; the `image` disposal is what's missing.

**7. Missing newline at end of new test files**
- **Files:** `src/Controls/tests/TestCases.HostApp/Issues/Issue23832.cs`, `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23832.cs`
- Both files end with `\\ No newline at end of file` in the diff. Convention in MAUI is to include a final newline.

---

### ✅ Looks Good

- **iOS fix is clean and minimal** — single-line change using the existing, well-tested `NormalizeOrientation` extension method from `UIImageExtensions.cs`, which correctly handles all UIImage orientations via `UIGraphicsImageRenderer`.
- **All 8 EXIF orientations handled** in `RotateBitmap` — covers the full EXIF specification (1=normal, 2=flip-h, 3=rotate-180, 4=flip-v, 5=transpose, 6=rotate-90, 7=transverse, 8=rotate-270).
- **Stream handling** — non-seekable streams are correctly buffered via `MemoryStream` before EXIF reading, since `ExifInterface` requires a seekable stream.
- **API level guard** — `OperatingSystem.IsAndroidVersionAtLeast(24)` correctly prevents use of the stream-based `ExifInterface` constructor (added in API 24) on older devices.
- **`Matrix` is disposed** correctly in the happy path within `RotateBitmap`.
- **Test snapshot images** added for Android, iOS, and Mac, enabling screenshot-based regression detection.
- **Test category** `UITestCategories.GraphicsView` is appropriate for the test scenario.
- **Before/after screenshots** in PR description clearly demonstrate the visual fix.

---

## Summary

| Area | Status |
|------|--------|
| Title | ⚠️ Minor update recommended ("During Resize" is misleading) |
| Description | ✅ Good — keep with optional API-level note |
| NOTE block | ✅ Present |
| iOS code | ✅ Clean single-line fix |
| Android code | 🔴 3 critical issues: ExifInterface leak, null bitmap, exception in RotateBitmap |
| Android code (style) | 🟡 Broad catch, missing private modifier |
| Test code | 🟡 IImage not disposed in Drawable |
| Test files | 🟡 Missing final newline |

**Verdict:** The fix addresses the right root cause and the iOS change is solid. The Android implementation has resource management issues (ExifInterface leak, potential null bitmap NRE, bitmap disposal in exception path) that should be addressed before merge.

</details>

**Review by kubaflo — APPROVED** [review]
