### PR TITLE
Fix -[iOS] - CarouselView Throws ArgumentOutOfRangeException Immediately on Application Launch in CV2

### LINKED ISSUE #29308: [iOS] - CarouselView Throws ArgumentOutOfRangeException Immediately on Application Launch in CV2
### Description

Description:
When launching the CarouselViewPositionVisibility application, an ArgumentOutOfRangeException is thrown immediately.
This issue occurs only on Cv2.
Note: While fixing this issue enable the test case from HostApp: CarouselViewPositionVisibility.

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Style-Type" content="text/css">
</head>
<body>
<p class="p1"><br></p>

Expected Output | Actual Output
-- | --
<video src="https://github.com/user-attachments/assets/ebece05f-ad30-434f-9541-449ed11321f8" /> | Image
</body>
</html>

### Steps to Reproduce

- Open the CarouselViewPositionVisibility solution
- Build the solution
- Run the application
- Observe that the application immediately crashes with ArgumentOutOfRangeException

[CarouselViewPositionVisibility.zip](https://github.com/user-attachments/files/20012849/CarouselViewPositionVisibility.zip)

**Expected Behavior**
- The application should launch successfully showing the CarouselView with the bound items collection, allowing the user to swipe to position 2 and test the visibility toggling functionality.

**Actual Behavior**
- The application crashes immediately on launch with ArgumentOutOfRangeException, preventing any user interaction.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.60 SR6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iPhone 18.0

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by SuthiYuvaraj**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue Description:
When using CarouselView2 with ItemsSource set to List<int> and Loop enabled, an ArgumentOutOfRangeException is thrown.

### Root Cause:
When using CarouselView with a List<int> and looping enabled, the SelectLayout method in CarouselViewHandler2 is invoked. In this scenario, the loop count is incorrectly calculated as 9 for an ItemsSource with a count of 3. Ideally, the loop count should be 5 to simulate proper looping behavior. While LoopListSource2 correctly handles this adjustment, the default implementation uses LoopListSource, which works as expected for CarouselView1 but not for CarouselViewHandler2.

### Description of Change:
Reviewed the page count and looping logic in SelectLayout. Since LoopListSource2 provides the correct scroll index, the implementation was updated to use LoopListSource2 for consistent and accurate behavior.

### Issues Fixed
Fixes #29308 

### Tested the behaviour in the following platforms
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Note: 
As of now, the test cases are running with `CarouselView1` in CI. However, they will be enabled for `CarouselView2` through the upcoming PRs. 
#29283 
#29315

Once those are merged, I will proceed with updating the tests to use `CarouselView2`.

### Output Screenshot
Before Issue Fix | After Issue Fix |
|----------|----------|
|<video width="250" height="150" alt="Before Fix" src="https://github.com/user-attachments/assets/692b9112-782a-4378-b190-a54619acd750">|<video width="250" height="150" alt="After Fix" src="https://github.com/user-attachments/assets/cf6c70da-f474-4ae8-bef3-ee0a09e98039">|

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items2/iOS/ItemsSourceFactory2.cs [hunk 1]
```diff
@@ -22,7 +22,7 @@ public static ILoopItemsViewSource CreateForCarouselView(IEnumerable itemsSource
 			IList _ when itemsSource is INotifyCollectionChanged => new LoopObservableItemsSource2(itemsSource as IList, collectionViewController, loop),
 			IEnumerable _ when itemsSource is INotifyCollectionChanged => new LoopObservableItemsSource2(itemsSource as IEnumerable, collectionViewController, loop),
 			IEnumerable<object> generic => new LoopListSource2(generic, loop),
-			_ => new LoopListSource(itemsSource, loop),
+			_ => new LoopListSource2(itemsSource, loop),
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items2/iOS/ItemsSourceFactory2.cs:25]: Could you include a related test?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Handlers/Items2/iOS/ItemsSourceFactory2.cs (hunk 1 above)
Comment (SuthiYuvaraj) [reply src/Controls/src/Core/Handlers/Items2/iOS/ItemsSourceFactory2.cs:25]: Hi @jsuarezruiz, As of now, the test cases are running with CarouselView1 in CI. Once this (#[29315](https://github.com/dotnet/maui/pull/29315) ) PR got merged, I will replace the `CarouselView1` to `CarouselView2`

**Review by jsuarezruiz — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]
