### PR TITLE
[iOS] Fix for Shell custom FlyoutIcon display problem

### LINKED ISSUE #25920: .NET MAUI set AppShell custom FlyoutIcon displayed problem
### Description

.NET Maui project (.NET 8, .NET 9) try to set custom hamburger icon. After app compiled, it is displayed as:
- Android - white icon, no matter that original icon color is f.e. blue color,
- iOS - display custom hamburger icon, but space for custom icon is very wide and title view goes very far to right.

Moreover set hamburger color works only for iOS. It is not working on Android. Details in steps to reproduce.

### Steps to Reproduce

1. Create sample .NET project
2. Set any custom icon (png/svg) at AppShell.xaml:
`FlyoutIcon="hamburger_icon.svg"`
3. Set hamburger icon color at AppShell.xaml:
Shell.ForegroundColor="{StaticResource LightRedColor}

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, iOS

### Affected platform versions

_No response_

### Did you find any workaround?

No workaround

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Tamilarasan-Paranthaman**
### Root Cause of the issue 

- The custom image size is too large, causing it to render in the center and leaving extra space on the left.
 
### Description of Change

- I resized the custom image to match the hamburger size using the UIGraphics concept and implemented caching to prevent redundant image rendering.
 
**Reference for icon size:** https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs#L450

### Issues Fixed

Fixes #25920

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Screenshot

**iOS**

| Before Issue Fix | After Issue Fix |
|----------|----------|
|  |  |

### CODE REVIEW

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs [hunk 1]
```diff
@@ -336,7 +336,7 @@ void UpdateLeftToolbarItems()
 
 				if (image != null)
 				{
-					icon = result?.Value;
+					icon = ResizeImage(result?.Value, new CGSize(23f, 23f));
```
[the remark this answers is not in the document]
Comment (Tamilarasan-Paranthaman) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs:339]: > Is iOS the only one that doesn't resize? Is this size correct under all the screen options? (@2x etc) https://developer.apple.com/design/human-interface-guidelines/toolbars

@jsuarezruiz, I have tested the icon under all device screen options, and it works properly on all devices. The size I am using for the custom icon is based on the default Hamburger icon size. Please refer to the code below for your reference
 
**Reference for icon size:** 

https://github.com/dotnet/maui/blob/c363191b8e41dbd9eabf4760295d5d4f7466abdf/src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs#L495

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25920.cs [hunk 2]
```diff
@@ -0,0 +1,27 @@
+#if !WINDOWS
+// In Windows, the foreground color is not applied to the custom icon, 
+// so as of now, the test is not applicable for Windows.
```
[the remark this answers is not in the document]
Comment (Tamilarasan-Paranthaman) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25920.cs]: > Windows is the only one having a different behavior, right? Could you open a new issue and include the link in the comment.

@jsuarezruiz, the new issue for the Windows platform has been logged and I have added a comment. Could you please check and provide your concerns if any?

https://github.com/dotnet/maui/blob/c363191b8e41dbd9eabf4760295d5d4f7466abdf/src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25920.cs#L2

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs [hunk 3]
```diff
@@ -382,6 +382,51 @@ void UpdateLeftToolbarItems()
...
+			using (NSData imageData = image.AsPNG())
+			{
+				using (var sha256 = System.Security.Cryptography.SHA256.Create())
+				{
+					byte[] hashBytes = sha256.ComputeHash(imageData.ToArray());
+					return Convert.ToBase64String(hashBytes);
+				}
+			}
+		}
+		UIImage ResizeImage(UIImage sourceImage, CGSize targetSize)
```
Comment (mattleibow) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs:398]: This creates a new image with new data, and potentially wastes memory. I feel like we have this problem solved somewhere before that just scales the image. Let me see...

Comment (mattleibow) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs:398]: This place: https://github.com/dotnet/maui/blob/af94a2246539089d8ec82944d4b0c2afee383de4/src/Controls/src/Core/Button/Button.iOS.cs#L433-L449

I think we can maybe extract this into some helper class, maybe an extension for UIImage?

Comment (mattleibow) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs:398]: Also, we probably want to preserve aspect ratio, the code `sourceImage.Draw(new CGRect(0, 0, targetSize.Width, targetSize.Height));` will stretch in this PR. So the scaling way we have in button is probably safer.

Comment (Tamilarasan-Paranthaman) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs]: @mattleibow, Thank you for the suggestion. I have moved the ResizeImageSource method from Button.iOS to the UIImageExtensions class. I applied the same logic in the ShellPageRendererTracker for the custom FlyoutIcon and also updated the button related code. Could you please review these changes and let me know if you have any concerns?

**Review by PureWeen — CHANGES_REQUESTED** [review]
Can you split the android change out from this PR? 

I think the resizing parts of this for the iOS Icon is going to need a little bit deeper of an analysis. 

Like, I'm curious if users have an icon that's 30x30, or just slightly bigger than 40x40 if we want to resize. 


Playing with the sandbox here's a few sizes

I don't know if we can force an opinion here on the size of that icon for users. If this is an issue in our template we should generate an image at the size it should be

30x30
image

23x23
image

40x40
image

**Comment by Ahamed-Ali** [comment]
> Can you split the android change out from this PR?
> 
> I think the resizing parts of this for the iOS Icon is going to need a little bit deeper of an analysis.
> 
> Like, I'm curious if users have an icon that's 30x30, or just slightly bigger than 40x40 if we want to resize.
> 
> Playing with the sandbox here's a few sizes
> 
> I don't know if we can force an opinion here on the size of that icon for users. If this is an issue in our template we should generate an image at the size it should be
> 
> 30x30 image
> 
> 23x23 image
> 
> 40x40 image

Hi @PureWeen , I have created a separate PR [27502](https://github.com/dotnet/maui/pull/27502)  for Android changes. Please review it and share your concerns.

File: src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs [hunk 4]
```diff
@@ -25,6 +26,24 @@ public static UIImage ScaleImage(this UIImage target, float maxWidth, float maxH
 			return ScaleImage(target, new CGSize(targetWidth, targetHeight), disposeOriginal);
 		}
 
+		internal static UIImage ResizeImageSource(this UIImage sourceImage, nfloat maxWidth, nfloat maxHeight, CGSize originalImageSize, bool shouldScaleUp = false)
+		{
+			if (sourceImage is null || sourceImage.CGImage is null)
```
Comment (jsuarezruiz) [inline src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs:31]: Can use the null-conditional operator to simplify the check:
`if (sourceImage?.CGImage is null)`

File: src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs [hunk 5]
```diff
@@ -25,6 +26,24 @@ public static UIImage ScaleImage(this UIImage target, float maxWidth, float maxH
...
+			maxHeight = (nfloat)Math.Min(maxHeight, originalImageSize.Height);
+
+			var sourceSize = sourceImage.Size;
+
+			float maxResizeFactor = (float)Math.Min(maxWidth / sourceSize.Width, maxHeight / sourceSize.Height);
+
+			if (maxResizeFactor > 1 && !shouldScaleUp)
+				return sourceImage;
+
+			return UIImage.FromImage(sourceImage.CGImage, sourceImage.CurrentScale / maxResizeFactor, sourceImage.Orientation);
```
Comment (jsuarezruiz) [inline src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs:44]: `UIImage.FromImage` creates a new instance of UIImage with the specified parameters. Could modify the implementation to just transform the current one?

```
internal static UIImage ResizeImageSource(this UIImage sourceImage, nfloat maxWidth, nfloat maxHeight, CGSize originalImageSize, bool shouldScaleUp = false)
{
	if (sourceImage?.CGImage is null)
		return null;

	maxWidth = (nfloat)Math.Min(maxWidth, originalImageSize.Width);
	maxHeight = (nfloat)Math.Min(maxHeight, originalImageSize.Height);

	var sourceSize = sourceImage.Size;
	var maxResizeFactor = (nfloat)Math.Min(maxWidth / sourceSize.Width, maxHeight / sourceSize.Height);

	if (maxResizeFactor > 1 && !shouldScaleUp)
		return sourceImage;

	var newSize = new CGSize(sourceSize.Width * maxResizeFactor, sourceSize.Height * maxResizeFactor);

	UIGraphics.BeginImageContextWithOptions(newSize, false, 0.0f);
	sourceImage.Draw(new CGRect(0, 0, newSize.Width, newSize.Height));
	var resizedImage = UIGraphics.GetImageFromCurrentImageContext();
	UIGraphics.EndImageContext();

	return resizedImage;
}
```

This approach uses the image context to resize the image, should be more efficient than creating a new instance.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

**Comment by jsuarezruiz** [comment]
@PureWeen Should these changes be a Platform Specific similar to https://github.com/dotnet/maui/pull/28046? In that case, should target to the `net10.0` branch?

File: src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs (hunk 5 above)
Comment (Tamilarasan-Paranthaman) [reply src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs:44]: @jsuarezruiz, previously, I used a similar drawing code without scaling in this PR. As per @mattleibow   
suggestion, I utilized the ResizeImageSource method from Button.iOS and have now moved it to the UIImageExtensions class as discussed. 
 
Do I need to modify the existing code as you suggested?  
 
please check the previous discussion and share the details: 
https://github.com/dotnet/maui/pull/26016#discussion_r1871770914

**Review by PureWeen — CHANGES_REQUESTED** [review]
@Tamilarasan-Paranthaman can you integrate @kubaflo 's changes into your PR? 

https://github.com/dotnet/maui/pull/29095

Move this to net10.0 and make it so users can disable this behavior behind an AppContext Switch

**Comment by Tamilarasan-Paranthaman** [comment]
> @Tamilarasan-Paranthaman can you integrate @kubaflo 's changes into your PR?
> 
> #29095
> 
> Move this to net10.0 and make it so users can disable this behavior behind an AppContext Switch

@PureWeen, I have included the AppContext switch change from PR #29095 to this PR, along with the existing resizing code changes. Additionally, I have added the FlyoutPageTest from PR #29095 and retargeted the branch to .NET 10.

File: .github/ISSUE_TEMPLATE/bug-report.yml [hunk 6]
```diff
@@ -219,4 +219,4 @@ body:
   - type: markdown
     attributes:
       value: |
-        By opening the issue you agree to follow this project's [Code of Conduct](https://github.com/dotnet/maui/blob/main/.github/CODE_OF_CONDUCT.md)
+        By opening the issue you agree to follow this project's [Code of Conduct](https://github.com/dotnet/maui/blob/main/.github/CODE_OF_CONDUCT.md)
```
Comment (rmarinho) [inline .github/ISSUE_TEMPLATE/bug-report.yml:175]: why is it changing this file?

File: .github/copilot-instructions.md [hunk 7]
```diff
@@ -197,4 +197,4 @@ Always put that at the top, without the block quotes. Without it, the users will
 
 ---
 
-**Note for Future Updates:** This document should be expanded as new development patterns, tools, or workflows are discovered. Add sections for specific scenarios, debugging techniques, or tooling as they become relevant to the development process.
+**Note for Future Updates:** This document should be expanded as new development patterns, tools, or workflows are discovered. Add sections for specific scenarios, debugging techniques, or tooling as they become relevant to the development process.
```
Comment (rmarinho) [inline .github/copilot-instructions.md:276]: why is it changing this file?

File: src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs (hunk 5 above)
Comment (rmarinho) [reply src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs:46]: yeah for now we can just keep this as is, but maybe create a issue to in another PR try refactor the code to what @jsuarezruiz  says

File: src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs [hunk 8]
```diff
@@ -960,12 +961,24 @@ internal static void SetFlyoutLeftBarButton(UIViewController containerController
...
-				if (icon != null)
+				var originalImageSize = result?.Value?.Size ?? CGSize.Empty;
+				// Referred from the default hamburger size 
+				var defaultIconHeight = 23f;
+				var defaultIconWidth = 23f;
+				var buffer = 0.1;
+				// if the image is bigger than the default available size, resize it
+				if (icon is not null)
 				{
+					bool enableResizing = !AppContext.TryGetSwitch("iOSDisableFlyoutIconAutoResizing", out bool disableResizing) || !disableResizing;
```
Comment (rmarinho) [inline src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs]: After taking with @mattleibow  and @PureWeen we decided we don t need to add the switch flag, we can just fix the issue without having to keep the old behaviour.

**Review by rmarinho — CHANGES_REQUESTED** [review]
Sorry lets rebase and remove iOSDisableFlyoutIconAutoResizing switch

File: .github/ISSUE_TEMPLATE/bug-report.yml (hunk 6 above)
Comment (Tamilarasan-Paranthaman) [reply .github/ISSUE_TEMPLATE/bug-report.yml:175]: While rebasing this branch, it appears that this file was changed, but I didn’t make any modifications to it.

File: src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs (hunk 8 above)
Comment (Tamilarasan-Paranthaman) [reply src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs]: @rmarinho, I have removed the iOSDisableFlyoutIconAutoResizing switch and retained the resizing logic.

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs [hunk 9]
```diff
@@ -415,9 +416,20 @@ void UpdateLeftToolbarItems()
 
 				UIImage? icon = null;
 
-				if (image != null)
+				if (image is not null)
 				{
 					icon = result?.Value;
+					var originalImageSize = icon?.Size ?? CGSize.Empty;
+					// Referred from the default hamburger size 
+					var defaultIconHeight = 23f;
```
Comment (rmarinho) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs:424]: can we add a comment where do we get this value from? Apple docs?

File: src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs (hunk 4 above)
Comment (rmarinho) [inline src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs]:
```suggestion
			if (sourceImage?.CGImage is null)
```

File: .github/ISSUE_TEMPLATE/bug-report.yml (hunk 6 above)
Comment (rmarinho) [reply .github/ISSUE_TEMPLATE/bug-report.yml:175]: its adding spaces instead of tabs

**Review by rmarinho — COMMENTED** [review]
Address some review feedback and suggestions

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs (hunk 9 above)
Comment (Tamilarasan-Paranthaman) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs:424]: Since I could not find official Apple documentation, I used the [default hamburger](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs#L470) size as a reference

File: src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs (hunk 4 above)
Comment (Tamilarasan-Paranthaman) [reply src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs]: I have optimized the code

**Comment by Tamilarasan-Paranthaman** [comment]
> its adding spaces instead of tabs

@rmarinho, Even though I copied the file content from the base branch to my branch and there were no actual changes to push, it's showing as a difference only in the PR, even though there are no real changes locally.

**Comment by rmarinho** [comment]
I saw some issues that I don t think are related to this PR, but seems .svg doesn t work as icon source, and changing the image to avatar.png produce this. 

Simulator Screenshot - iPhone Xs (iOS 18 0) - created by XHarness - 2025-07-24 at 17 19 10

**Comment by rmarinho** [comment]
And cover1.jpg 

Simulator Screenshot - iPhone Xs (iOS 18 0) - created by XHarness - 2025-07-24 at 17 22 55

**Review by rmarinho — APPROVED** [review]
I saw some issues, but they also reproduce on main, the size/resize of the icon works well this this PR .
