### PR TITLE
Fixed Custom Drawable does not support binding

### LINKED ISSUE #20991: Custom IDrawable control does not databind to a model property when used inside a CollectionView ItemTemplate
### Description

The issue I'm having is with databinding a custom drawn control, where the model property isn't binding to the Drawable control property.

Please see attached github sample project. It is a simple project based off the Xaminals demo.

The project has a List of Theatre classes each of which has one public property Name. The List is bound to a CollectionView in TheatresPage.xaml which has two bound controls to demo the binding issue. 
 + A label which binds to the TheatreName property of the Theatre object. This binds and renders correctly. 
 + A drawable control which is created and renders correctly but the control's Name property doesn't bind to the model's TheatreName property.

```
<CollectionView.ItemTemplate>
    <DataTemplate>
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="40" />
                <RowDefinition Height="40" />
            </Grid.RowDefinitions>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="100" />
                <ColumnDefinition Width="*" />
            </Grid.ColumnDefinitions>
            
            <Label Grid.Row="0" Grid.Column="0" Text="Label Text: " TextColor="Red" />
            <Label Grid.Row="0" Grid.Column="1" Text="{Binding TheatreName}" TextColor="Red" />
            
            <Label Grid.Row="1" Grid.Column="0" Text="Drawable: " />
            <GraphicsView Grid.Row="1" Grid.Column="1" HorizontalOptions="Fill" HeightRequest="40">
                <GraphicsView.Drawable>
                    <controls:TheatrePanel Name="{Binding TheatreName}" />
                </GraphicsView.Drawable>
            </GraphicsView>
        </Grid>
    </DataTemplate>
</CollectionView.ItemTemplate>
```

My custom drawn control is as below. It's built off BindableObject with a BindableProperty using the correct naming convention
```
public partial class TheatrePanel : BindableObject, IDrawable
{
    public static readonly BindableProperty NameProperty = BindableProperty.Create(nameof(Name), typeof(string), typeof(TheatrePanel));

    public string Name
    {
        get => (string)GetValue(NameProperty);
        set => SetValue(NameProperty, value);
    }

    public void Draw(ICanvas canvas, RectF dirtyRect)
    {
        canvas.FontColor = Colors.Black;
        canvas.FontSize = 14;
        canvas.Font = Microsoft.Maui.Graphics.Font.Default;

        canvas.DrawString($"Bound Item Value >> {Name}", 0, 0, 400, 38, HorizontalAlignment.Left, VerticalAlignment.Top);
    }
}
```

Demo app output. As you can see, the Label in red binds correctly but the Drawable in black renders but hasn't bound.

image

### Steps to Reproduce

Please run the demo github project attached

### Link to public reproduction project repository

https://github.com/neilwarland/MAUI-IDrawable-DataBinding/tree/main

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by NirmalKumarYuvaraj**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause
The BindingContext of the GraphicsView is not propagated to the Drawable object.

### Description of Change
* Added an override for `OnBindingContextChanged` in `GraphicsView` to ensure that the `BindingContext` of the `Drawable` object is updated when the `BindingContext` of the `GraphicsView` changes. 

### Public API Updates:
* Updated the `PublicAPI.Unshipped.txt` files across various platforms (e.g., Android, iOS, macOS, Tizen, Windows, .NET Standard) to include the new `OnBindingContextChanged` override for `GraphicsView`. 

### Test Additions:
* Added a new manual test case (`Issue20991`) to validate that custom `IDrawable` controls correctly support data binding. This test includes a `GraphicsView` with a bound `Drawable` object and a label describing the expected behavior.
* Added an automated test for `Issue20991` to verify that the `GraphicsView`'s `Drawable` binding works as expected. The test uses Appium and NUnit to check for the presence of the label and validate the behavior via a screenshot. 

### Issues Fixed

Fixes #20991

### CODE REVIEW

**Review by rmarinho — CHANGES_REQUESTED** [review]
I think we want use  `BindableObject.SetInheritedBindingContext`

File: src/Controls/src/Core/GraphicsView/GraphicsView.cs [hunk 1]
```diff
@@ -42,6 +42,15 @@ public void Invalidate()
...
 		void IGraphicsView.StartInteraction(PointF[] points) => StartInteraction?.Invoke(this, new TouchEventArgs(points, true));
+
+		protected override void OnBindingContextChanged()
+		{
+			base.OnBindingContextChanged();
+			if (Drawable is BindableObject bindable)
+			{
+				bindable.BindingContext = BindingContext;
+			}
+		}
```
Comment (bhavanesh2001) [inline src/Controls/src/Core/GraphicsView/GraphicsView.cs:53]: What if the Drawable itself is changed at runtime? I guess the BindingContext will not be set for the newly assigned Drawable.

**Comment by NirmalKumarYuvaraj** [comment]
> I think we want use `BindableObject.SetInheritedBindingContext`

@rmarinho , i have updated the code changes. please let me know if you have any concerns

File: src/Controls/src/Core/GraphicsView/GraphicsView.cs (hunk 1 above)
Comment (NirmalKumarYuvaraj) [reply src/Controls/src/Core/GraphicsView/GraphicsView.cs:66]: @bhavanesh2001 , Yes, Thanks for pointing it out. I have updated the code changes to support binding for new assigned drawable.

**Comment by jsuarezruiz** [comment]
@NirmalKumarYuvaraj Could you rebase and fix the conflicts? Thanks in advance.

**Comment by NirmalKumarYuvaraj** [comment]
> @NirmalKumarYuvaraj Could you rebase and fix the conflicts? Thanks in advance.

@jsuarezruiz , i have rebased the branch. Please let me know if you have any concern.

**Review by kubaflo — CHANGES_REQUESTED** [review]
Could you please resolve conflicts?

**Review by kubaflo — CHANGES_REQUESTED** [review]
Could you please review the AI's summary?

**Comment by NirmalKumarYuvaraj** [comment]
@kubaflo , I think AI summary did not run completely. The gate failed due to broken pipeline "Android build progressed successfully, but deployment to the emulator failed with ADB0010 / Broken pipe (32) during package installation.". So all the attempts in TRY-FIX have failed.

**Review by kubaflo — CHANGES_REQUESTED** [review]
Hi! Could you please review the ai's summary again - it should be completed this time :)

**Comment by NirmalKumarYuvaraj** [comment]
@kubaflo , The AI summary is incomplete. The gate is failed without any additional information. I ran the tests locally. It passed.
image
