### PR TITLE
[Android] Fix issues clipping content in Border

### LINKED ISSUE #7448: Border.Stroke Shape is not fully displayed
### Description

Hello, I have a border with EllipseGeometry that is not fully displayed

Repro
https://github.com/HausBJB/MauiApp2.git

this fix was already there and then the following happened #6851

Ok because this change
https://github.com/dotnet/maui/pull/6851/commits/f0cf10d285e09cb8900ac8e1bfbd1cd18b49df74

flew out again with this one

https://github.com/dotnet/maui/commit/b8727a40b18bd12a8707af146e19b8be87e86086

main
https://github.com/dotnet/maui/blob/main/src/Core/src/Graphics/MauiDrawable.Android.cs
image

### Steps to Reproduce

1. Create new MauiApp
2. Add XAML code in MainPage 
3. Run App

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #7460: Image Clipping issues in Border
### Description

1) Images are not Clipped correctly as expected in Android but in windows it looks like perfect

In Android 
ImageClippingAndroid

In Windows
ImageClippingWindows

Expected Behavior : Images clipped inside the border in Android

### Steps to Reproduce

1.UnZip the below project
[BorderClipImage.zip](https://github.com/dotnet/maui/files/8768588/BorderClipImage.zip)

2.Run the Project to see the output difference

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9

### Did you find any workaround?

NA

### Relevant log output

```shell
NA
```

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

 Fix issues clipping content in Border on Android.  This definitely didn't work before https://github.com/dotnet/maui/pull/6851 and after remove platform-specific density calculations from the cross-platfor layer here https://github.com/dotnet/maui/commit/e50621cd91d64f778627ba4f5956269523781d89, the issue is back. This PR include changes to maintain the density stuff at platform level but fix the clipping issues.

Screenshot_1653475967

```
<StackLayout>
    <Label 
        Text="Issue 7448 (Using Ellipse)"/>
    <Border 
        WidthRequest="150"
        HeightRequest="150"
        Stroke="#C49B33"
        StrokeThickness="4"
        Background="#2B0B98"
        HorizontalOptions="Center">
        <Border.StrokeShape>
            <Ellipse />
        </Border.StrokeShape>
        <Label Text=".N"
           VerticalOptions="Center"
           HorizontalOptions="Center"
           TextColor="White"
           FontSize="18"
           FontAttributes="Bold" />
    </Border>
    <Label 
        Text="Issue 7448 (Using EllipseGeometry)"/>
    <Border 
        WidthRequest="150"
        HeightRequest="150"
        Stroke="#C49B33"
        StrokeThickness="4"
        Background="#2B0B98"
        HorizontalOptions="Center">
        <Border.StrokeShape>
            <EllipseGeometry RadiusX="71" RadiusY="71" Center="75,75"/>
        </Border.StrokeShape>
        <Label Text=".N"
           VerticalOptions="Center"
           HorizontalOptions="Center"
           TextColor="White"
           FontSize="18"
           FontAttributes="Bold" />
    </Border>
    <Label 
        Text="Issue 7460"/>
    <Border 
        VerticalOptions="Center" HorizontalOptions="Center"
        HeightRequest="150" WidthRequest="150" Stroke="red" 
        StrokeThickness="6">
        <Border.StrokeShape>
            <RoundRectangle CornerRadius="100"/>
        </Border.StrokeShape>
        <Border.Content>
            <Grid>
                <Image Source="oasis.jpg" Aspect="AspectFill"  />
            </Grid>
        </Border.Content>
    </Border>
</StackLayout>
```

### Issues Fixed

Fixes #7448 
Fixes #7460

### CODE REVIEW

File: src/Controls/src/Core/Shapes/EllipseGeometry.cs [hunk 1]
```diff
@@ -56,8 +56,8 @@ public double RadiusY
 		/// <include file="../../../docs/Microsoft.Maui.Controls.Shapes/EllipseGeometry.xml" path="//Member[@MemberName='AppendPath']/Docs" />
 		public override void AppendPath(PathF path)
 		{
-			var centerX = (float)RadiusX;
-			var centerY = (float)RadiusY;
+			var centerX = (float)Center.X;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Shapes/EllipseGeometry.cs:59]: :astonished:

File: src/Core/src/Platform/Android/ContentViewGroup.cs [hunk 2]
```diff
@@ -109,7 +109,7 @@ void ClipChild(Canvas? canvas)
 
 			float density = Context.GetDisplayDensity();
 
-			float strokeThickness = (float)Clip.StrokeThickness;
+			float strokeThickness = (float)(Clip.StrokeThickness * density);
 			float offset = strokeThickness / 2;
 			float w = (canvas.Width / density) - strokeThickness;
 			float h = (canvas.Height / density) - strokeThickness;
```
Comment (campersau) [inline src/Core/src/Platform/Android/ContentViewGroup.cs:115]: Is this correct? `strokeThickness` is now multiplied by `density` but `canvas.Width` / `canvas.Height` is divided by `density`.

Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/ContentViewGroup.cs:115]: We apply a Scale by density after this.

**Review by Redth — APPROVED** [review]

**Comment by HausBJB** [comment]
This error persists

6.0.400 (Service Release 1)

**Comment by Ahamed-Ali** [comment]
This https://github.com/dotnet/maui/issues/7460 issue still remains in Android

Unzip the below Project 
[BorderClipImage.zip](https://github.com/dotnet/maui/files/9216849/BorderClipImage.zip)

**Screenshots**

See the clipping issues in Android

In Android 
image
In Windows
image

File: src/Controls/src/Core/Shapes/EllipseGeometry.cs (hunk 1 above)
Comment (Ahamed-Ali) [reply src/Controls/src/Core/Shapes/EllipseGeometry.cs:59]: This https://github.com/dotnet/maui/issues/7460 issue still remains in Android

Unzip the below Project 
[BorderClipImage.zip](https://github.com/dotnet/maui/files/9216849/BorderClipImage.zip)

**Screenshots**

See the clipping issues in Android

In Android 
image
In Windows
image
