### PR TITLE
Fix Android ListView header / footer gone (#12312)

### LINKED ISSUE #12312: [Android] Listview Header content disappears while scrolling
### Description

Normal Listview with multiple items the header content disappears when scrolled.
NET 6 Latest -> Android 

### Steps to Reproduce

[testsample.zip](https://github.com/dotnet/maui/files/10311386/testsample.zip)

### Link to public reproduction project repository

test sample attached

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

VS2022 preview

### Did you find any workaround?

No workaround.

Not sure how basic functionality like header is broken in MAUI. :(

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ooikengsiang**
### Description of Change
Fix incorrect layout value cause header / footer in ListView on Android gone missing / disappear when scrolling.

### Issues Fixed
Fixes #12312

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewRenderer.cs [hunk 1]
```diff
@@ -592,6 +589,7 @@ protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
 					return;
 				}
 
+				_child.PlatformView.Layout(0, 0, widthMeasureSpec, heightMeasureSpec);
```
Comment (hartez) [inline src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewRenderer.cs:592]: This cannot possibly work; `widthMeasureSpec` and `heightMeasureSpec` are not integer values for width and height. They are logically ORed with the measureSpec mode. Trying to use them as values for Right and Bottom will give you hugely negative values in many cases.

Also, calling Layout during OnMeasure makes no sense; the values you'd use for Layout don't exist yet because you haven't measured the View.

**Review by hartez — CHANGES_REQUESTED** [review]
This can't possibly work. And testing it against the original repro project, it doesn't work.

File: src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewRenderer.cs (hunk 1 above)
Comment (hartez) [reply src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewRenderer.cs:592]: I think you are correct that the implementation of `OnLayout` was wrong - instead of 

```csharp
_child.PlatformView.Layout(l, t, r, b);
```

it should probably be 

```csharp
_child.PlatformView.Layout(0, 0, r - l, b - t);
```

and `OnMeasure` should be left as it was.

Comment (ooikengsiang) [reply src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewRenderer.cs]: You are right. The new layout calculation do fix the problem. I have just tested it. Update the code now.

File: src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewRenderer.cs [hunk 2]
```diff
@@ -576,12 +576,7 @@ public IPlatformViewHandler Child
 
 			protected override void OnLayout(bool changed, int l, int t, int r, int b)
 			{
-				if (_child?.PlatformView == null)
-				{
-					return;
-				}
-
-				_child.PlatformView.Layout(l, t, r, b);
+				_child.PlatformView.Layout(0, 0, r - l, b - t);
```
Comment (hartez) [inline src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewRenderer.cs:579]: Is it safe to remove the null check?

**Review by hartez — CHANGES_REQUESTED** [review]
The new code looks fine, but I'm wondering if it's safe to remove the null check.

File: src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewRenderer.cs (hunk 2 above)
Comment (ooikengsiang) [reply src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewRenderer.cs:584]: My bad, added back.

**Review by hartez — APPROVED** [review]

**Comment by jfversluis** [comment]
Adding backport/suggested label on this one. Had been requested by a customer.

**Comment by taranveerjohal** [comment]
Is this Possibly fixed with surety? I am still having issue with Header and footer being miscalculated at scroll? :(

I can provide the required Sample, if needed.
