### PR TITLE
[Windows] Fix issues invalidating the Background of some controls

### LINKED ISSUE #12749: Picker and Switch BackgroundColor properties are not updated from ViewModel
### Description

I have created simple ContentPage. Using MVVM pattern I am changing color property in ViewModel. Entry BackgroundColor seems to be working fine, where Picker BackgroundColor is not updated until pages are switched. Also for example Switch color is updated only on mouse hover.

https://user-images.githubusercontent.com/72302395/213172063-1496f715-32b0-4d16-811b-10de90d63f6f.mp4

There are might be other controls with same issues. Not tested them all. Are there BindableProperty's missing for some of controls?

### Steps to Reproduce

Here is an example of my controls on ContentPage:

```
    <Switch IsToggled="{Binding IsCounted}" OnColor="{Binding SColor}"></Switch>

    <Entry Text="{Binding ValueS}" BackgroundColor="{Binding SColor}"></Entry>

    <Picker ItemsSource="{Binding PColors}" SelectedItem="{Binding SelectedColor}" 
            ItemDisplayBinding="{Binding ColorName}" BackgroundColor="{Binding SColor}" 
            Background="{Binding SColor}"></Picker>
```

Here are ViewModel properties:

```
private Color sColor;
public Color SColor
{
  get => this.sColor;
  set
  {
    this.sColor = value;
    this.OnPropertyChanged();
  }
}

private ColorModel selectedColor;
public ColorModel SelectedColor
{
  get => this.selectedColor;
  set
  {
    this.selectedColor = value;
    this.OnPropertyChanged();
  }
}
```

and ColorModel.cs

```
  public class ColorModel
  {
    public string ColorName { get; set; }
    public string ColorHex { get; set; }
  }
```

### Link to public reproduction project repository

https://github.com/vadimffe/ControlsBackgroundColorIssue

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix issues invalidating the Background of some Windows controls.

fix-brush-windows

### Issues Fixed

Fixes #12749

### CODE REVIEW

File: src/Core/src/Platform/Windows/FrameworkElementExtensions.cs [hunk 1]
```diff
@@ -155,6 +155,8 @@ internal static void TryUpdateResource(this FrameworkElement element, object new
 				if (rd?.ContainsKey(key) ?? false)
 					rd[key] = newValue;
 			}
+
+			element?.RefreshThemeResources();
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Windows/FrameworkElementExtensions.cs:159]: This and similar changes is the main change that fixes the issue.

**Review by rmarinho — APPROVED** [review]
