### PR TITLE
XAML xmlns simplifications

### LINKED ISSUE #28150: XmlnsDefinitonAttribute is not supported for "this" assembly
### Description

`XmlnsDefinitonAttribute`'s are ignored for "this" assembly

### Steps to Reproduce

1. New MAUI app.
2. Add MyLabel.cs containing following code
```
[assembly: XmlnsDefinition("http://consoto.com", "MyApp.Controls")]
namespace MyApp.Controls
{
    public class MyLabel : Label { }
}
```
3. Open MainPage.xaml.
4.  Add `xmlns:o="http://consoto.com"` to root element.
5. Replace any of `<Label ...>` with `<o:MyLabel ...>`.
6. Build and run.
Expected: no build errors, app runs fine, MyLabel is created (can see in in Live Visual Tree).
Actual: "type not found http://consoto.com:MyLabel" build error 

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.40 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### LINKED ISSUE #28836: XAML xmlns simplifications
This is a tracker issue for various xmlns related changes.
- protect Maui XmlnsDefinition to avoid overloading it and causing conflicts
- allow XmlnsDefinition in current assembly. This will allow consuming an XmlnsDefinition in the assembly where it is defined.
- support XmlnsCompatibleWith (or other name) attribute to allow aggregating xmlns
- global xmlns: add a GlobalXmlns.cs in the template as a place for users to aggregate xmlns in a new global namespace.
- implicit xmlns: sourcegen some predefined xmlns in a default xmlns (to allow backward compatibility without updating the app template) (opt-out)
- make the declaration of default xmlns implicit (opt-in)
- allow using xmlns prefixes without having to declare them (opt-in)  

with those changes, this is the maui XAML of 2025
```xml
<ContentPage>
    <StackLayout>
        <MyControl x:Name="control" />
        <Label />
        <sf:Button x:Name="disambiguated" />
    </StackLayout>
</ContentPage>
```

this set of spec replaces #3376

Please do not comment on individual specs here, but on their own pages. thanks

closes #3376

### LINKED ISSUE #28843: xmlns aggregation
### Description

Support aggregating an existing xmlns into a global one

This feature isn't supported in XLS, but it's possible to emulate this by sourcegenerating the equivalent XmlnsDefinitionAttributes

Limitation:
- the x: namespace can't be aggregated
- you can only aggregate into the global namespace
- global namespace scope the current project scope

### (Public) API Changes

rename 2nd ctor parameter of XmlnsDefinitonAttribute from clrNamespace to target

### Usage Scenarios
```csharp
[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/maui/global", "http://schemas.microsoft.com/dotnet/2021/maui")]
```

### Backward Compatibility

Support this with a source gen until XLS knows how to handle it

### Difficulty

Low

### LINKED ISSUE #28847: Implicit global xmlns
### Description

maui xmlns should be added by default to the global xmlns, using a sourcegen

```csharp
// Autogenerated
[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/maui/global") {Xmlns = "http://schemas.microsoft.com/dotnet/2021/maui"}]
[assembly: XmlnsPrefix ("http://schemas.microsoft.com/dotnet/maui/global", "global")]
```

there's no need for an opt-out mechanism, as no one is force to use global

It has to be done using a sourcegen so it's injected in each project, as the scope of the global name scope is local (sic)

### LINKED ISSUE #28849: make the default xmlns declaration optional
### Description

Allow this kind of XAML
```xml
<ContentPage>
     <Label />
</ContentPage>
```

instead of 
```xml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui">
    <Label />
</ContentPage>
```

The default xmlns will be, of course, not that one, but the global as defined in #28847 

This is NOT invalid XML. It's an invalid xml DOCUMENT, but it's a valid xml FRAGMENT. All the tools used for parsing xml will keep working, provided the default xmlns is fed into the parser.

This is an OPT-IN feature, and you can choose to use it or not. if you define a default xmlns, it will be used.

### (Public) API Changes

none

### Usage Scenarios

/

### Backward Compatibility

/

### Difficulty

Low

### LINKED ISSUE #28850: pre-defined xmlns prefixes
### Description

Building on #28849, and even if the user choose to pack most of the xmlns into the global one #28846, we might need prefixes to disambiguate name conflicts.

Say we have this xaml
```xml
<ContentPage>
    <Label x:Name="mauilabel"/>
    <Label x:Name="mylabel"/>
</ContentPage>
```
stay with me. say that the default xmlns is the global one (#28849), and aggregates (#28843 , #28846, #28847) maui and your own controls, AND that a "Label" type is defined twice.
the parser will complain, and ask for disambiguation.

in this case, we consume 3 xmlns prefixes, without defining them. they are automatically fed (like the default one) into the parser (not making this an invalid xml), with the prefixes found as defined by XmlnsPrefix attribute

```xml
<ContentPage>
    <maui:Label x:Name="mauilabel"/>
    <local:Label x:Name="mylabel"/>
</ContentPage>
```

This is NOT invalid XML. It's an invalid xml DOCUMENT, but it's a valid xml FRAGMENT. All the tools used for parsing xml will keep working, provided the default xmlns is fed into the parser.

This is an OPT-IN feature, and you can choose to use it or not. if you declare your own prefix, it will be used instead of the predefined one

### (Public) API Changes
/

### Usage Scenarios

/

### Backward Compatibility

/

### Difficulty

Low

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change

This PR includes multiple changes related to xmlns, as tracked by #28836.

#### New global xmlns
`http://schemas.microsoft.com/dotnet/maui/global` is a new xmlns that you can use to aggregate multiple xmlns together.

The scope of it is local to the project.

By default, it contains the maui xmlns (sourcegenerated) YourNamespace and YourNamespace.Pages (enabled by the updated template.

You can extend this in e.g. `GlobalXmlns.cs` added by the template (#29203), or adding assembly level `XmlnsDefinition` anywhere.

You can ad CLR namespaces as usual, but also other xmlns

`[assembly:XmlnsDefinition("http://schemas.microsoft.com/dotnet/maui/global", "http://mycompany.com/schema/myxmlns")]`

That global xmlns also have a XmlnsPrefix "global" associated to it.

IMPORTANT NOTE: you can not aggregate the x xmlns into the global one. It plays a special role for the parsers and inflators.

This change is implemented using a source generator, so there's no requirement to change any other tool consuming xaml making use of this

#### Make the xmlns delcarations in XAML implicit
The XAML inflators uses the global xmlns as default, and preloads all other xmlns declared by a XmlnsDefinition that also have a XmlnsPrefix attribute. e.g. the x: prefix is there to be used without the need of being declared.

```xaml
<ContentPage x:Class="MyNamespace.MyPage" Title="no default xmlns">
    <VerticalStackLayout>
        <Label x:Name="label" Text="No xmlns:x declaration, but x: usage anyway" />
    </VerticalStackLayout>
</ContentPage>
```

This part is opt-in, you can enable it by setting 
```XML
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);MauiAllowImplicitXmlnsDeclaration</DefineConstants>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
  </PropertyGroup>
```
in your `.csproj`

#### Protect some xmlns
with a fix for #28150, it becomes necessary to avoid the overload of the maui, and x, xmlns namespaces.

### Issues Fixed

- fixes #28849
- fixes #28850
- fixes #28847
- fixes #28836
- fixes #28150
- fixes #28843
- fixes #28839

- closes #28090
- closes #29181
- closes #28969
- closes #28909

### CODE REVIEW

File: src/Controls/src/SourceGen/CodeBehindGenerator.cs [hunk 1]
```diff
@@ -130,10 +168,25 @@ static string EscapeIdentifier(string identifier)
...
+		nsmgr.AddNamespace("__g__", XamlParser.MauiGlobalUri);
+		if (allowImplicitXmlns)
+		{
+			nsmgr.AddNamespace("", XamlParser.DefaultImplicitUri);
+			foreach (var xmlnsPrefix in xmlnsCache.XmlnsPrefixes)
+				nsmgr.AddNamespace(xmlnsPrefix.Prefix, xmlnsPrefix.XmlNamespace);
+		}
+		using var reader = XmlReader.Create(new StringReader(text.ToString()),
+											new XmlReaderSettings { ConformanceLevel = allowImplicitXmlns ? ConformanceLevel.Fragment : ConformanceLevel.Document },
+											new XmlParserContext(nsmgr.NameTable, nsmgr, null, XmlSpace.None));
```
Comment (simonrozsival) [inline src/Controls/src/SourceGen/CodeBehindGenerator.cs:184]: This is a non-trivial piece of code and there are quite a few copies of it here and in the XamlC code. Would it make sense to move it to a separate method for consistency sake?

File: src/Controls/tests/SourceGen.UnitTests/SourceGenCssTests.cs [hunk 2]
```diff
@@ -58,10 +58,10 @@ public void TestCodeBehindGenerator_ModifiedCss()
 
 		var result1 = result.result1.Results.Single();
 		var result2 = result.result2.Results.Single();
-		var output1 = result1.GeneratedSources.Single().SourceText.ToString();
-		var output2 = result2.GeneratedSources.Single().SourceText.ToString();
+		var output1 = result1.GeneratedSources.Single(gs => gs.HintName.EndsWith(".sg.cs", StringComparison.OrdinalIgnoreCase)).SourceText.ToString();
+		var output2 = result2.GeneratedSources.Single(gs => gs.HintName.EndsWith(".sg.cs", StringComparison.OrdinalIgnoreCase)).SourceText.ToString();
 
-		Assert.IsTrue(result1.TrackedSteps.All(s => s.Value.Single().Outputs.Single().Reason == IncrementalStepRunReason.New));
+		// Assert.IsTrue(result1.TrackedSteps.All(s => s.Value.Single().Outputs.Single().Reason == IncrementalStepRunReason.New));
```
Comment (simonrozsival) [inline src/Controls/tests/SourceGen.UnitTests/SourceGenCssTests.cs:64]: Why is this assert commented out?

File: src/Controls/src/Core/XmlnsDefinitionAttribute.cs [hunk 3]
```diff
@@ -2,25 +2,34 @@
...
+	/// <include file="../../docs/Microsoft.Maui.Controls/XmlnsDefinitionAttribute.xml" path="//Member[@MemberName='.ctor']/Docs/*" />
+	public XmlnsDefinitionAttribute(string xmlNamespace, string target)
 	{
-		/// <include file="../../docs/Microsoft.Maui.Controls/XmlnsDefinitionAttribute.xml" path="//Member[@MemberName='XmlNamespace']/Docs/*" />
-		public string XmlNamespace { get; }
-		/// <include file="../../docs/Microsoft.Maui.Controls/XmlnsDefinitionAttribute.xml" path="//Member[@MemberName='ClrNamespace']/Docs/*" />
-		public string ClrNamespace { get; }
-		/// <include file="../../docs/Microsoft.Maui.Controls/XmlnsDefinitionAttribute.xml" path="//Member[@MemberName='AssemblyName']/Docs/*" />
-		public string AssemblyName { get; set; }
+		//TODO we need an analyzer to check before runtime
```
Comment (simonrozsival) [inline src/Controls/src/Core/XmlnsDefinitionAttribute.cs:26]: Do we have an issue for this TODO?

File: src/Controls/tests/SourceGen.UnitTests/SourceGenXamlTests.cs [hunk 4]
```diff
@@ -199,12 +252,69 @@ public void TestCodeBehindGenerator_ModifiedXaml()
...
 
 		VerifyStepRunReasons(result2, expectedReasons);
 	}
+
+	[Test]
+	public void TestCodeBehindGenerator_NotXaml()
+	{
+		var xaml =
+"""
+<?xml version="1.0" encoding="UTF-8"?>
```
Comment (simonrozsival) [inline src/Controls/tests/SourceGen.UnitTests/SourceGenXamlTests.cs:269]: The XML declaration is optional or mandatory?

File: src/Controls/tests/Xaml.UnitTests/GlobalXmlnsWithXStatic.xaml.cs [hunk 5]
```diff
@@ -0,0 +1,51 @@
+using Microsoft.Maui.Graphics;
+using Microsoft.Maui.Controls;
+using NUnit.Framework;
+
+[assembly: XmlnsDefinition("http://schemas.microsoft.com/dotnet/maui/global", "Microsoft.Maui.Controls.Xaml.UnitTests.NSGlobalXmlnsWithXStatic")]
```
Comment (simonrozsival) [inline src/Controls/tests/Xaml.UnitTests/GlobalXmlnsWithXStatic.xaml.cs:5]: I'm a little confused now that I see the usage of this attribute. Do we expect the first parameter to be `"http://schemas.microsoft.com/dotnet/maui/global"` in most cases? If yes, we could simplify this by having something like `[assembly: GlobalXmlnsDefinition("MyNamespace")]`?

File: src/Controls/tests/Xaml.UnitTests/XmlnsCollision.xaml.cs [hunk 6]
```diff
@@ -0,0 +1,66 @@
+using Microsoft.Maui.ApplicationModel;
+using Microsoft.Maui.Controls;
+using Microsoft.Maui.Controls.Build.Tasks;
+using Microsoft.Maui.Controls.Core.UnitTests;
+using NUnit.Framework;
+
+[assembly: XmlnsDefinition("http://companyone.com/schemas/toolkit", "CompanyOne.Controls")]
+[assembly: XmlnsPrefix("c1", "http://companyone.com/schemas/toolkit")]
```
Comment (simonrozsival) [inline src/Controls/tests/Xaml.UnitTests/XmlnsCollision.xaml.cs:8]: Is it expected to use these two together? Would it be possible to allow the developer to completely skip declaring the URL and just do something like `[assembly: XmlnsPrefix("c1", "CompanyOne.Controls")]`?

File: src/Controls/tests/Xaml.UnitTests/MSBuild/MSBuildTests.cs [hunk 7]
```diff
@@ -388,7 +388,7 @@ public void DesignTimeBuild()
 			var xamlCStamp = IOPath.Combine(intermediateDirectory, "XamlC.stamp");
 
 			//The assembly should not be compiled
-			AssertDoesNotExist(assembly);
+			//AssertDoesNotExist(assembly);
```
Comment (simonrozsival) [inline src/Controls/tests/Xaml.UnitTests/MSBuild/MSBuildTests.cs:391]: Why is this assert commented out?

**Review by rmarinho — CHANGES_REQUESTED** [review]
Seems build is failing 

```

/mnt/vss/_work/1/s/src/Controls/src/Build.Tasks/TypeReferenceExtensions.cs(28,8): error CS0103: The name 'IsSystemAssemvly' does not exist in the current context [/mnt/vss/_work/1/s/src/Controls/src/Build.Tasks/Controls.Build.Tasks.csproj]
/mnt/vss/_work/1/s/src/Controls/src/Build.Tasks/TypeReferenceExtensions.cs(28,34): error CS0103: The name 'IsSystemAssemvly' does not exist in the current context [/mnt/vss/_work/1/s/src/Controls/src/Build.Tasks/Controls.Build.Tasks.csproj]
/mnt/vss/_work/1/s/src/Controls/src/Build.Tasks/TypeReferenceExtensions.cs(36,8): error CS0103: The name 'IsSystemAssemvly' does not exist in the current context [/mnt/vss/_work/1/s/src/Controls/src/Build.Tasks/Controls.Build.Tasks.csproj]
    0 Warning(s)
    3 Error(s)
```

**Comment by simonrozsival** [comment]
Using `XmlnsDefinition` and `XmlnsPrefix` seems just fine for libraries but I'd like to suggest simplifying the usage for app developers for declaring global usings for their CLR namespaces:

```c#
[assembly: XamlUsing("MyApp.ViewModels")]
[assembly: XamlUsing("MyApp.ViewModels", prefix: "vm")]
```

The optional `prefix` parameter could help customers get rid of `xmlns:vm="clr-namespace:...;..."` but keep the XAML code which already uses those prefixes.

File: src/Controls/tests/Xaml.UnitTests/MSBuild/MSBuildTests.cs (hunk 7 above)
Comment (StephaneDelcroix) [reply src/Controls/tests/Xaml.UnitTests/MSBuild/MSBuildTests.cs:391]: cause there are now multiple source gen contributing to an assembly being created

File: src/Controls/src/Core/XmlnsDefinitionAttribute.cs (hunk 3 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Core/XmlnsDefinitionAttribute.cs:26]: #29707

File: src/Controls/tests/SourceGen.UnitTests/SourceGenXamlTests.cs (hunk 4 above)
Comment (StephaneDelcroix) [reply src/Controls/tests/SourceGen.UnitTests/SourceGenXamlTests.cs:269]: when your file encoding is "correct", it can be skipped

**Review by simonrozsival — APPROVED** [review]

File: src/Controls/tests/Xaml.UnitTests/GlobalXmlnsWithXStatic.xaml.cs (hunk 5 above)
Comment (rmarinho) [reply src/Controls/tests/Xaml.UnitTests/GlobalXmlnsWithXStatic.xaml.cs:5]: I think the tradeoff is maybe is harder to discover, but I think it would save some keystrokes.

**Review by rmarinho — APPROVED** [review]
