### PR TITLE
[iOS] Span's TapGestureRecognizer not working if text is truncated - UITest

### LINKED ISSUE #21837: Span's TapGestureRecognizer not working if text is truncated
### Description

Consider a Label with FormattedText and a TapGestureRecognizer attached to one of its Spans. The TapGestureRecognizer does not execute the Command if the Label's text is truncated, either as a result of limiting `MaxLines` and the available width or by limiting both, width and height.

This bug affects the app on **Windows**, but not on Android. Other platforms are untested.

Tested versions:
- 8.0.20 (bug present)
- 8.0.10 (bug present)

### Steps to Reproduce

1. Check out the attached reprodution repo and start the app on Windows.
2. Click the highlighted Labels.
3. Observe that only Labels whose text is fully visible will execute the command (i.e. update the counter).

### Link to public reproduction project repository

https://github.com/Veilenus/FormattedTextGestureRecognizerBug

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

_No response_

### Did you find any workaround?

Unfortunately, no. A hacky one might be considered if the Label's `FontSize` and `LineHeight` are statically known, thus allowing to wrap the Label in a Layout of choice and limiting the latter's `HeightRequest` instead of the Label`s `MaxLines`.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Windows is not working either, but I have no machine to work on it
Fixes https://github.com/dotnet/maui/issues/21837

|Before|After|
|--|--|
|<video src="https://github.com/dotnet/maui/assets/42434498/68196bda-9dca-472a-8f44-7ef5acd42cc7" width="300px"/>|<video src="https://github.com/dotnet/maui/assets/42434498/7a3be163-81b3-4cf7-a641-1cb9f05651fe" width="300px"/>|

### CODE REVIEW

File: src/Controls/tests/UITests/Tests/Issues/Issue21837.cs [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+		[Test]
+		public void TapsShouldBeCorrectlyRecognized()
+		{
+			int numberOfTappableLabels = 11;
+
+			_ = App.WaitForElement("label1");
+
+			for (int i = 0; i < numberOfTappableLabels; i++)
+				App.Click($"label{i + 1}");
```
Comment (jsuarezruiz) [inline src/Controls/tests/UITests/Tests/Issues/Issue21837.cs:23]: This test is failing on Android:

```
System.NullReferenceException : Object reference not set to an instance of an object.

 at UITest.Appium.HelperExtensions.Click(IUIElement element) in /Users/builder/azdo/_work/2/s/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 144
   at UITest.Appium.HelperExtensions.Click(IApp app, String element) in /Users/builder/azdo/_work/2/s/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 34
   at Microsoft.Maui.AppiumTests.Issues.Issue21837.TapsShouldBeCorrectlyRecognized() in /Users/builder/azdo/_work/2/s/src/Controls/tests/UITests/Tests/Issues/Issue21837.cs:line 23
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

Comment (kubaflo) [reply src/Controls/tests/UITests/Tests/Issues/Issue21837.cs:23]: Can we please try once again?

Comment (jsuarezruiz) [reply src/Controls/tests/UITests/Tests/Issues/Issue21837.cs:23]: Sure!, running the build again now.

File: src/Controls/src/Core/Platform/iOS/Extensions/FormattedStringExtensions.cs [hunk 2]
```diff
@@ -184,7 +184,7 @@ internal static void RecalculateSpanPositions(this UILabel control, Label elemen
 				var yaxis = startRect.Top;
 				var lineHeights = new List<double>();
 
-				while ((endRect.Bottom - yaxis) > 0.001)
+				while ((Math.Max(endRect.Bottom, finalSize.Bottom) - yaxis) > 0.001)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/iOS/Extensions/FormattedStringExtensions.cs:187]: The existing `InitialFormattedTextMatchesText` test is failing on macOS. Could you try the changes on Catalyst?

```
System.OutOfMemoryException : Out of memory
at System.Collections.Generic.List`1[[System.Double, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].set_Capacity(Int32 value)
   at System.Collections.Generic.List`1[[System.Double, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Grow(Int32 capacity)
   at System.Collections.Generic.List`1[[System.Double, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddWithResize(Double item)
   at Microsoft.Maui.Controls.Platform.FormattedStringExtensions.RecalculateSpanPositions(UILabel control, Label element) in /Users/builder/azdo/_work/2/s/src/Controls/src/Core/Platform/iOS/Extensions/FormattedStringExtensions.cs:line 202
   at Microsoft.Maui.Controls.Label.RecalculateSpanPositions() in /Users/builder/azdo/_work/2/s/src/Controls/src/Core/Label/Label.iOS.cs:line 61
   at Microsoft.Maui.Controls.Label.ArrangeOverride(Rect bounds) in /Users/builder/azdo/_work/2/s/src/Controls/src/Core/Label/Label.iOS.cs:line 15
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds) in /Users/builder/azdo/_work/2/s/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1834
   at Microsoft.Maui.DeviceTests.HandlerTestBasement.InitializeViewHandler(IElement element, IElementHandler handler, IMauiContext mauiContext) in /Users/builder/azdo/_work/2/s/src/Core/tests/DeviceTests.Shared/HandlerTests/HandlerTestBasement.cs:line 136
   at Microsoft.Maui.DeviceTests.HandlerTestBasement.CreateHandler[LabelHandler,LabelHandler](IElement element, IMauiContext mauiContext) in /Users/builder/azdo/_work/2/s/src/Core/tests/DeviceTests.Shared/HandlerTests/HandlerTestBasement.cs:line 166
   at Microsoft.Maui.DeviceTests.HandlerTestBasement.CreateHandler[LabelHandler](IElement view, IMauiContext mauiContext) in /Users/builder/azdo/_work/2/s/src/Core/tests/DeviceTests.Shared/HandlerTests/HandlerTestBasement.cs:line 90
   at Microsoft.Maui.DeviceTests.ControlsHandlerTestBase.CreateHandler[LabelHandler](IElement view) in /Users/builder/azdo/_work/2/s/src/Controls/tests/DeviceTests/ControlsHandlerTestBase.cs:line 44
   at Microsoft.Maui.DeviceTests.LabelTests.<>c__DisplayClass17_0.<<InitialFormattedTextMatchesText>b__0>d.MoveNext() in /Users/builder/azdo/_work/2/s/src/Controls/tests/DeviceTests/Elements/Label/LabelTests.cs:line 472
--- End of stack trace from previous location ---
   at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass3_0.<<DispatchAsync>b__0>d.MoveNext() in /Users/builder/azdo/_work/2/s/src/Core/src/Dispatching/DispatcherExtensions.cs:line 88
--- End of stack trace from previous location ---
   at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass2_0`1.<<DispatchAsync>b__0>d[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in /Users/builder/azdo/_work/2/s/src/Core/src/Dispatching/DispatcherExtensions.cs:line 67
--- End of stack trace from previous location ---
   at Microsoft.Maui.DeviceTests.LabelTests.InitialFormattedTextMatchesText(Double fontSize) in /Users/builder/azdo/_work/2/s/src/Controls/tests/DeviceTests/Elements/Label/LabelTests.cs:line 470
--- End of stack trace from previous location ---
```

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Platform/iOS/Extensions/FormattedStringExtensions.cs (hunk 2 above)
Comment (kubaflo) [reply src/Controls/src/Core/Platform/iOS/Extensions/FormattedStringExtensions.cs]: @jsuarezruiz should work now

**Review by jsuarezruiz — DISMISSED** [review]

**Review by tj-devel709 — CHANGES_REQUESTED** [review]
I think this is in the right direction and definitely when there is truncation, this is not working correctly because it is looking for the rect around the last character but that character is not rendered and get an empty rect.

The issue I see with using the finalSize.Bottom is when we have a frame that is longer than the span we'd like, there is extra space being added to the 'hitbox' area of the span that we do not want.



https://github.com/user-attachments/assets/d06e582c-88d1-44d8-be99-92c7ddb85886

```xaml
<Label AutomationId="label7" HorizontalOptions="Start" MaxLines="5" BackgroundColor="LightGoldenrodYellow" WidthRequest="200" HeightRequest="400">
            <Label.FormattedText>
                <FormattedString>
                    <Span Text="Only our MaxLines differ. Otherwise we're the same. Please tap us!">
                        <Span.GestureRecognizers>
                            <TapGestureRecognizer Command="{Binding TapCommand}" />
                        </Span.GestureRecognizers>
                    </Span>
                </FormattedString>
            </Label.FormattedText>
        </Label>
```

This is a great idea though and maybe it can be tweaked to find a good middle ground

**Comment by tj-devel709** [comment]
Perhaps something like a check if the endRect is the empty rect and the startRect is not the empty rect, then maybe that is enough to assume there is truncation going on and we can use the finalSize?

**Comment by kubaflo** [comment]
Hi @tj-devel709 I've rebased and the issue seems to be fixed. So maybe just merge the UI test I've added and close this bug?

**Review by mattleibow — APPROVED** [review]
