### PR TITLE
[Testing] Split off HandlerDoesNotLeak.DatePicker into its own UI test

### LINKED ISSUE #24147: [Testing] HandlerDoesNotLeak.DatePicker
### Description

HandlerDoesNotLeak.DatePicker fails a lot. 

We setup a general structure [here](https://github.com/dotnet/maui/pull/23784) for testing memory leaks. We could move this test (or all of them) over to appium, which should have a more accurate run pattern. 

For now we could just move this one and make a note in the device tests.

### PR DESCRIPTION
**Pull request by dustin-wojciechowski**
### Description of Change

Split off HandlerDoesNotLeak.DatePicker into its own UI test.

### Issues Fixed
fixes #24147

### CODE REVIEW

File: src/Controls/tests/DeviceTests/Memory/MemoryTests.cs [hunk 1]
```diff
@@ -132,7 +132,6 @@ await CreateHandlerAndAddToWindow(new Window(navPage), async () =>
 	[InlineData(typeof(CarouselView))]
 	[InlineData(typeof(ContentView))]
 	[InlineData(typeof(CheckBox))]
-	[InlineData(typeof(DatePicker))]
```
Comment (PureWeen) [inline src/Controls/tests/DeviceTests/Memory/MemoryTests.cs:135]: Instead of deleting this can you add a comment here

// This test was moved to MemoryTests.cs inside Appium

File: src/Controls/tests/TestCases.HostApp/Issues/Issue24147.cs [hunk 2]
```diff
@@ -0,0 +1,20 @@
+namespace Maui.Controls.Sample.Issues
+{
+	[Issue(IssueTracker.Github, 24174, "DatePicker does not leak", PlatformAffected.All)]
+	public class Issue24174 : NavigationPage
+	{
+		public Issue24174() 
+		{
+            this.RunMemoryTest(() =>
```
Comment (PureWeen) [inline src/Controls/tests/TestCases.HostApp/Issues/Issue24147.cs:8]: Can we look at generalizing this test a bit more?

I think we're going to start moving a few of these from device tests to here and it'd probably be good not to have them spread out.

I'm thinking

- rename this to MemoryTests.cs
- Add an entry box and a button
- the test can now uses testcases to enter text and click the button for which test to run

**Review by PureWeen — CHANGES_REQUESTED** [review]

**Review by jonathanpeppers — COMMENTED** [review]
If we introduce a leak, what does the test failure look like? I'm not certain the test is "the same", if you revert this commit does it fail?

* https://github.com/dotnet/maui/commit/39c144b5a7173023084dd8f259c3815248f3de43

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/MemoryTests.cs [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+
+		[Test]
+		[Category(UITestCategories.WebView)]
+		public void WebViewDoesNotLeak()
+		{
+			App.WaitForElement("DataTypeEntry");
+			App.EnterText("DataTypeEntry", "WebView");
+			App.Tap("RunMemoryTestButton");
+			App.AssertMemoryTest();
+		}
```
Comment (jonathanpeppers) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/MemoryTests.cs:34]: Can these be parameterized to a `[Theory]` if only one line is different, the string "WebView" vs "DatePicker"?

File: src/Controls/tests/TestCases.HostApp/Issues/Issue22972.cs [hunk 4]
```diff
@@ -1,20 +0,0 @@
-using Microsoft.Maui.Controls;
-
-namespace Maui.Controls.Sample.Issues
-{
-	[Issue(IssueTracker.Github, 22972, "Win platform WebView cannot be release after its parent window get close")]
-	public class Issue22972 : NavigationPage
-	{
-		public Issue22972() 
-		{
-            this.RunMemoryTest(() =>
```
Comment (PureWeen) [inline src/Controls/tests/TestCases.HostApp/Issues/Issue22972.cs:10]: I think leaving this test is fine

It's testing a somewhat slightly different scenario

**Review by PureWeen — APPROVED** [review]

**Comment by PureWeen** [comment]
I'm going to go ahead and merge this for now

I realize we have some left over changes on here but we're getting a lot of failures right now on CI

We can adjust any findings in a follow up PR that will be incoming soon.
