### PR TITLE
[Android] Tabs briefly display wrong background color when navigating between flyout items 

### LINKED ISSUE #16522: [Android] Tabs briefly display wrong background color when navigating between flyout items
### Description

The bottom TabBar on Android shows a weird behavior when combining tab pages and flyout navigation (see the second exercise of the [Create multi-page .NET MAUI apps with tab and flyout navigation](https://learn.microsoft.com/en-us/training/modules/create-multi-page-apps/) Microsoft Learn module).

If the Android device has dark theme enabled, the bottom tab bar correctly appears in the dark theme color when I first launch the application. However, when I navigate between different flyout pages, where only one of the pages has a bottom tab bar, the bar briefly appears white before changing back to the desired dark theme color.

Is this by design?
This visual inconsistency does not look great from a user perspective.

The same issue also occurs with light theme, when the TabBarBackgroundColor is set to a value different from the default white.

### Steps to Reproduce

1. Do File / New Project / MAUI App.
2. Create some additional pages (e.g. _SettingsPage_, _AboutPage_) and configure routing.
3. Open `AppShell.xaml` and create two flyout items, where one item will include tabs and the other a single page:
```
    <FlyoutItem Title="Main">
        <ShellContent Title="Main"
            ContentTemplate="{DataTemplate local:MainPage}"/>

        <ShellContent Title="Settings"
            ContentTemplate="{DataTemplate local:SettingsPage}"/>
    </FlyoutItem>

    <FlyoutItem Title="About">
        <ShellContent Title="About"
            ContentTemplate="{DataTemplate local:AboutPage}"/>
    </FlyoutItem>
```
4. Launch the Android application and set the device's dark theme.
5. Open the flyout and navigate between the pages.

Result:

When navigating to the item with multiple tabs, the background of the tab bar briefly appears white before changing to the initial dark color.

### Link to public reproduction project repository

https://github.com/richardrigutins/maui-tabbar-color-change-sample

### Version with bug

7.0.92

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 10 and up

### Did you find any workaround?

Creating custom ShellRenderer and ShellBottomNavViewAppearanceTracker implementations to remove animations when setting the background color of the bottom navigation view.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by KarthikRajaKalaimani**
### Root Cause:
- On Android, the BottomNavigationView initially has a ColorDrawable with a white background, which is the default color during its creation. 
- Later, the BottomNavigationView background is changed to a ColorChangeRevealDrawable with an animation, transitioning to the color specified by IShellAppearanceElement.EffectiveTabBarBackgroundColor. 
- Since the previous background color (white) differs from the current color (black), the animation displays a transition from white to black when switching pages.
### Description of Change:
- To resolve this issue, the IShellAppearanceElement.EffectiveTabBarBackgroundColor is applied to the background of the BottomNavigationView immediately after its creation. 
- This ensures that no animation is triggered later, as the previous background color (black) and the current color (black) remain the same.
 
**Tested the behaviour in the following platforms.**
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac
 
### Reference
N/A
 
### Issues Fixed
Fixes #16522
 
### Screenshots
 
| Before | After |
|--------|-------|
|  |  |

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs [hunk 1]
```diff
@@ -141,6 +141,10 @@ protected virtual void SetAppearance(ShellAppearance appearance)
 				return;
 			}
 
+			if (_bottomView.Background is ColorDrawable background && appearance is IShellAppearanceElement apperanceElement)
+			{
+				background.Color = apperanceElement.EffectiveTabBarBackgroundColor?.ToPlatform() ?? ShellRenderer.DefaultBottomNavigationViewBackgroundColor.ToPlatform();
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs]: The build is failing at this point:
```
/Users/builder/azdo/_work/2/s/src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs(146,89): error CS0103: The name 'ShellRenderer' does not exist in the current context [/Users/builder/azdo/_work/2/s/src/Controls/src/Core/Controls.Core.csproj::TargetFramework=net9.0-android35.0]
    1 Error(s)

```

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs (hunk 1 above)
Comment (KarthikRajaKalaimani) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs]: > The build is failing at this point:
> 
> ```
> /Users/builder/azdo/_work/2/s/src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs(146,89): error CS0103: The name 'ShellRenderer' does not exist in the current context [/Users/builder/azdo/_work/2/s/src/Controls/src/Core/Controls.Core.csproj::TargetFramework=net9.0-android35.0]
>     1 Error(s)
> ```

The build issue has been resolved now.

**Comment by sheiksyedm** [comment]
This PR was created to resolve unresolved Git rebase conflicts in the below PR
https://github.com/dotnet/maui/pull/24965

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs [hunk 2]
```diff
@@ -141,6 +142,10 @@ protected virtual void SetAppearance(ShellAppearance appearance)
 				return;
 			}
 
+			if (_bottomView.Background is ColorDrawable background && appearance is IShellAppearanceElement apperanceElement)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs]: Typo error: `appearanceElement`

Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs]: Could include a comment here? Something like: "Apply background color from appearance, fallback to default if unavailable"

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs (hunk 2 above)
Comment (KarthikRajaKalaimani) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs]: > Could include a comment here? Something like: "Apply background color from appearance, fallback to default if unavailable"

I have added comments now.

Comment (KarthikRajaKalaimani) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs]: > Typo error: `appearanceElement`

I have modified the code.

**Comment by kubaflo** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong> — <a href="https://github.com/dotnet/maui/commit/18a25a7e01575c2d2f68c808b80e127ac58bcefa"><code>18a25a7</code></a> · <strong>Added comments</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

**Issue:** #16522 - [Android] Tabs briefly display wrong background color when navigating between flyout items
**PR:** #29883 - [Android] Tabs briefly display wrong background color when navigating between flyout items
**Platforms Affected:** Android (primary), also tested on iOS/Mac/Windows per author
**Files Changed:** 1 implementation, 4 test files (plus 4 snapshot PNGs)

### Key Findings
- **Root cause:** `BottomNavigationView` is created with a default white `ColorDrawable` background. When `SetAppearance` is later called, `_appearanceTracker.SetAppearance()` uses `ColorChangeRevealDrawable` which animates from white → desired color, causing a brief flash.
- **Fix approach:** In `SetAppearance()`, before calling the tracker, directly mutate the existing `ColorDrawable` background's color to match `EffectiveTabBarBackgroundColor`. Since the color matches what the tracker will later animate TO, no visible animation occurs.
- **Review comment noted:** Reviewer (jsuarezruiz) flagged a build error (ShellRenderer not in context) and a typo (`appearanceElement`) — both were addressed by the author. A comment was also requested and added.
- **Test approach:** Screenshot test (`ShellTabBarBackgroundColor`) — navigates from Main tab page to About (single page) and back, then verifies screenshot matches. This verifies the tab bar shows the correct blue color (#0000FF) consistently.
- **Test type:** UI Test (TestCases.HostApp + TestCases.Shared.Tests)
- **No prior agent reviews found.**

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #29883 | In `SetAppearance()`, if the background is a `ColorDrawable`, directly set its `.Color` to the `EffectiveTabBarBackgroundColor` BEFORE calling tracker, preventing animated transition from white | ⏳ PENDING (Gate) | `ShellItemRenderer.cs` | Adds `using Microsoft.Maui.Controls.Handlers.Compatibility;` to access `ShellRenderer.DefaultBottomNavigationViewBackgroundColor` |

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

### Gate Result: ✅ PASSED

**Platform:** Android
**Mode:** Full Verification

- Tests FAIL without fix: ✅
- Tests PASS with fix: ✅

**Details:** The `Issue16522` screenshot test (`ShellTabBarBackgroundColor`) correctly detects the bug. Without the fix in `ShellItemRenderer.cs`, the test fails (tab bar shows wrong color). With the fix restored, the test passes.

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #29883 | In `SetAppearance()`, if background is `ColorDrawable`, directly set `.Color` before calling tracker | ✅ PASSED (Gate) | `ShellItemRenderer.cs` | Original PR fix |
| 1 | try-fix (claude-sonnet-4.6) | Pre-apply background color in `OnAppearanceChanged()` (one step earlier than PR) | ✅ PASSED | `ShellItemRenderer.cs` | Covers deferred `SetAppearance()` edge case |
| 2 | try-fix (claude-opus-4.6) | ⏳ IN PROGRESS | ⏳ | TBD | Attempt 2 |

### Cross-Pollination
| Model | Round | New Ideas? | Details |
|-------|-------|------------|---------|
| TBD | 2 | TBD | TBD |

**Exhausted:** No
**Selected Fix:** TBD

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Added comments</strong> · <a href="https://github.com/dotnet/maui/commit/18a25a7e01575c2d2f68c808b80e127ac58bcefa"><code>18a25a7</code></a></summary>


## ⚠️ Final Recommendation: REQUEST CHANGES (minor)

### Summary

PR #29883 fixes a genuine Android-specific bug: the `BottomNavigationView` tab bar briefly flashes white when navigating between flyout items with a custom `TabBarBackgroundColor`. The fix is minimal (+6 lines), technically correct, and well-reasoned. The implementation quality is good.

However, changes are requested for:
1. **Missing NOTE block** in the PR description (required by repository guidelines)
2. **XAML files missing newline at end of file** (minor code quality)
3. **Minor description inaccuracy** (says color applied "after creation" but it's in `SetAppearance()`)

### Root Cause

`BottomNavigationView` starts with a default white `ColorDrawable` background. On first `SetAppearance()` call, `ShellBottomNavViewAppearanceTracker.SetBackgroundColor()` detects `lastColor (white) ≠ newColor (custom)` and creates a `ColorChangeRevealDrawable` animation — producing a visible white flash.

### Fix Analysis

**PR's approach** (in `ShellItemRenderer.SetAppearance()`):
```csharp
if (_bottomView.Background is ColorDrawable background && appearance is IShellAppearanceElement appearanceElement)
{
    background.Color = appearanceElement.EffectiveTabBarBackgroundColor?.ToPlatform() 
        ?? ShellRenderer.DefaultBottomNavigationViewBackgroundColor.ToPlatform();
}
```

**How it works**: Pre-sets `ColorDrawable.Color` to desired color → tracker sees `lastColor == newColor` → creates `ColorChangeRevealDrawable(correctColor, correctColor)` = no-op animation. The `ColorDrawable` type guard naturally limits this to the initial render only.

**Independent validation**: 6 alternative fixes were explored across 5 AI models. All alternatives were either:
- More complex (43+ lines for Attempt 6)
- Had subtle flaws (Attempt 3 hardcodes white check, Attempt 4 uses wrong initial color)
- Equally correct but less minimal (Attempt 2 is slightly more elegant in the tracker)

The PR's fix is among the best approaches — minimal, correct, and in the right layer.

### Gate Result

❌ Gate FAILED — Test passes both with and without the fix. The `VerifyScreenshot()` call captures the final navigation state, not the transient animation flash. This is an inherent limitation of screenshot testing for animation bugs, not a defect in the fix. The test provides a useful visual regression baseline for the final state.

### Requested Changes

1. **Add NOTE block** to PR description:
   ```markdown
   <!-- Please let the below note in for people that find this PR -->
   > [!NOTE]
   > Are you waiting for the changes in this PR to be merged?
   > It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!
   ```

2. **Fix newline at end of file** in `Issue16522.xaml` and `Issue16522.xaml.cs`

3. **Update description accuracy**: Change "applied to the background of the BottomNavigationView immediately after its creation" → "applied to the background in `SetAppearance()` before the appearance tracker processes it"

### Positive Aspects

- ✅ Minimal, surgical fix (+6 lines)
- ✅ Correct fallback to `DefaultBottomNavigationViewBackgroundColor`
- ✅ Properly added `using Microsoft.Maui.Controls.Handlers.Compatibility`
- ✅ Good explanatory comment added
- ✅ Reviewer feedback (typo, comment, build error) all addressed
- ✅ Test page correctly reproduces the bug scenario
- ✅ Screenshots provided showing before/after

</details>

---

</details>



<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

# PR #29883 Finalization Review

**PR:** [#29883 - [Android] Tabs briefly display wrong background color when navigating between flyout items](https://github.com/dotnet/maui/pull/29883)
**Author:** @KarthikRajaKalaimani (community, Syncfusion partner)
**Base:** `main`
**Status:** Open / Mergeable (blocked - likely CI)

---

## Phase 1: Title & Description

### 🟡 Title: Needs Minor Update

**Current:** `[Android] Tabs briefly display wrong background color when navigating between flyout items ` *(trailing whitespace)*

**Issues:**
- Trailing whitespace after the last word
- Describes the *symptom* (visual bug) rather than the *fix action*
- No component prefix (`Shell:`)

**Recommended:**
```
[Android] Shell: Fix BottomNavigationView tab bar background color flicker when navigating between flyout items
```

Rationale: "Shell:" scopes it; "Fix … flicker" describes what changed, making it searchable in git history.

---

### 🟡 Description: Good Content, Missing NOTE Block

**Quality Assessment:**

| Indicator | Status | Notes |
|-----------|--------|-------|
| Structure | ✅ | Clear Root Cause + Description of Change sections |
| Technical depth | ✅ | Names the specific types (`ColorDrawable`, `ColorChangeRevealDrawable`, `EffectiveTabBarBackgroundColor`) |
| Accuracy | ✅ | Matches the actual diff |
| Completeness | ✅ | Platform matrix, screenshots (before/after), issue link |
| NOTE block | ❌ | **Missing required NOTE block** |
| "Reference: N/A" | 🟡 | Unnecessary noise - omit when N/A |

**Only change needed:** Add the required NOTE block at the very top.

**Recommended description (NOTE block added, Reference removed, rest preserved):**

```markdown
<!-- Please let the below note in for people that find this PR -->
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause
- On Android, the `BottomNavigationView` initially has a `ColorDrawable` with a white background — the default color at creation time.
- When `SetAppearance` is called, the appearance tracker replaces this with a `ColorChangeRevealDrawable` that animates to the color specified by `IShellAppearanceElement.EffectiveTabBarBackgroundColor`.
- Because the starting color (white) differs from the target color (e.g., black/blue), the animation produces a visible flash/flicker when switching between flyout items.

### Description of Change
- In `SetAppearance()`, before the appearance tracker applies its animated drawable, the `ColorDrawable` background is immediately pre-seeded with the correct `EffectiveTabBarBackgroundColor` (falling back to `ShellRenderer.DefaultBottomNavigationViewBackgroundColor`).
- Since the `ColorChangeRevealDrawable` now transitions from the correct color to itself, no visible animation is triggered.

**Tested the behaviour in the following platforms.**
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Issues Fixed
Fixes #16522

### Screenshots

| Before | After |
|--------|-------|
| <img src="https://github.com/user-attachments/assets/3e14b05f-70dd-4a17-bd85-01bf53f37095" width="300" height="600"> | <img src="https://github.com/user-attachments/assets/5320a886-ba23-4142-b4fb-6d00a53f3323" width="300" height="600"> |
```

---

## Phase 2: Code Review

### ✅ Core Fix — `ShellItemRenderer.cs`

```csharp
// Apply background color from appearance, fallback to default if unavailable
if (_bottomView.Background is ColorDrawable background && appearance is IShellAppearanceElement appearanceElement)
{
    background.Color = appearanceElement.EffectiveTabBarBackgroundColor?.ToPlatform()
        ?? ShellRenderer.DefaultBottomNavigationViewBackgroundColor.ToPlatform();
}
_appearanceSet = true;
_appearanceTracker.SetAppearance(_bottomView, appearance);
```

**Assessment:**
- ✅ Fix is targeted and minimal — one method, 5 lines
- ✅ Correctly placed **before** `_appearanceSet = true` (ensures it runs only on first call, since early return exits if `_appearanceSet`)
- ✅ Uses C# pattern-matching `is ColorDrawable background` — safe; only modifies the in-place default `ColorDrawable`, not the animated replacement
- ✅ Null-safe: `?.ToPlatform() ??` fallback to theme default handles null `EffectiveTabBarBackgroundColor`
- ✅ `using Microsoft.Maui.Controls.Handlers.Compatibility` added to resolve `ShellRenderer.DefaultBottomNavigationViewBackgroundColor`
- ✅ Comment added (as requested in review feedback)
- ✅ Prior review feedback fully addressed (build error with `ShellRenderer`, typo in variable name, missing comment)

### 🟡 Suggestions

#### 1. Test scenario doesn't fully reproduce the original bug

**File:** `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16522.cs`

```csharp
App.WaitForElement("Label");
App.Tap("Settings");   // Tab switch within "Main" FlyoutItem
App.Tap("Main");       // Tab switch back
App.WaitForElement("Label");
VerifyScreenshot();
```

**Issue:** The test switches tabs *within* the same FlyoutItem ("Main" → "Settings" tab and back). The original bug title says "navigating **between flyout items**". Navigating from the "Main" FlyoutItem to the "About" FlyoutItem and back would better match the reported scenario (and force the `BottomNavigationView` to appear/disappear).

The test still provides valid visual regression coverage since the same code path is triggered, but a cross-flyout navigation step would be more representative.

**Suggested improvement (low priority):**
```csharp
App.WaitForElement("Label");
App.Tap("About");       // Navigate to "About" FlyoutItem (no tabs visible)
App.Tap("Main");        // Navigate back to "Main" FlyoutItem (BottomNavigationView reappears)
App.WaitForElement("Label");
VerifyScreenshot();
```
*(Requires "About" and "Main" to be accessible as flyout items via AutomationId or navigation controls)*

#### 2. Missing newline at end of file

**Files:**
- `src/Controls/tests/TestCases.HostApp/Issues/Issue16522.xaml`
- `src/Controls/tests/TestCases.HostApp/Issues/Issue16522.xaml.cs`

Both files have `\ No newline at end of file` in the diff. This is a minor style inconsistency but can trigger diffs and linter warnings.

#### 3. Consider `retryTimeout` on `VerifyScreenshot()` (low risk)

The `VerifyScreenshot()` call has no retry timeout. Since the fix eliminates the animation, the final state should be stable. However, if any platform rendering delay occurs before the screenshot, it could be flaky. Using `VerifyScreenshot(retryTimeout: TimeSpan.FromSeconds(2))` is a defensive best practice for screenshot tests.

---

### ✅ Looks Good

- ✅ Fix is Android-specific but tests are correctly provided for all platforms (snapshots added for Android, iOS, Mac, Windows)
- ✅ `[Category(UITestCategories.Shell)]` is the appropriate category
- ✅ `[Issue(IssueTracker.Github, 16522, ...)]` attribute correctly declared
- ✅ All prior reviewer feedback has been addressed (build error, typo, comment)
- ✅ No API surface changes — purely behavioral fix in platform renderer

---

## Summary

| Area | Status | Action |
|------|--------|--------|
| Title | 🟡 Minor | Remove trailing space; add `Shell:` prefix; frame as fix |
| NOTE block | ❌ Missing | Prepend required NOTE block to description |
| Description content | ✅ Good | Keep as-is after adding NOTE block; remove "Reference: N/A" |
| Core fix | ✅ Correct | Targeted, safe, well-commented |
| Tests | 🟡 Minor | Consider cross-flyout navigation; add `retryTimeout` to screenshot |
| End-of-file newlines | 🟡 Minor | Add newline to XAML and .cs files |
| Prior review feedback | ✅ Addressed | Build error, typo, comment all resolved |

**Overall:** This is a clean, community-contributed fix with appropriate test coverage and good documentation. The description quality is solid — only the missing NOTE block and trailing space in the title are blockers before merge.

</details>

**Comment by kubaflo** [comment]
## 📋 PR Finalization Review


<details>

<summary><b>Title: ✅ Good</b></summary>

<br>

**Current:** `[Android] Tabs briefly display wrong background color when navigating between flyout items `
</details>

<details>

<summary><b>Description: ✅ Good</b></summary>

<br>

Description needs updates. See details below.
### ✨ Suggested PR Description


> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause

On Android, when a `BottomNavigationView` is first created, its background is a `ColorDrawable` initialized to the system default color (white in light theme, dark in dark theme). When `IShellBottomNavViewAppearanceTracker.SetAppearance` is called later, `ShellBottomNavViewAppearanceTracker.SetBackgroundColor` reads the current background color as `lastColor` and the target color as `newColor`. Because `lastColor` differs from `newColor`, it wraps the background in a `ColorChangeRevealDrawable` animation — causing a visible color flash when navigating from a flyout item without tabs back to one with tabs.

### Description of Change

In `ShellItemRenderer.SetAppearance()`, before delegating to `_appearanceTracker.SetAppearance()`, the fix pre-seeds the initial `ColorDrawable` background color to match `IShellAppearanceElement.EffectiveTabBarBackgroundColor` (falling back to `ShellRenderer.DefaultBottomNavigationViewBackgroundColor` when null).

This ensures that when `ShellBottomNavViewAppearanceTracker.SetBackgroundColor` subsequently reads `lastColor` from the existing background, it equals `newColor`. In the `menuView == null` path this triggers an early return; in the `menuView != null` path the `ColorChangeRevealDrawable` animates from color X to the same color X, which is visually a no-op — eliminating the white flash.

The condition `_bottomView.Background is ColorDrawable` only matches on the very first call (before the appearance tracker replaces the background with a `ColorChangeRevealDrawable` or `MaterialShapeDrawable`), so this check is self-limiting and has no effect on subsequent appearance updates.

### Issues Fixed

Fixes #16522

### Tested Platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac
</details>

<details>

<summary><b>Code Review: ✅ Passed</b></summary>

<br>

# Code Review — PR #29883

## Files Reviewed

| File | Change |
|------|--------|
| `src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs` | Core fix (+6 lines) |
| `src/Controls/tests/TestCases.HostApp/Issues/Issue16522.xaml` | New HostApp test page |
| `src/Controls/tests/TestCases.HostApp/Issues/Issue16522.xaml.cs` | Code-behind for test page |
| `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16522.cs` | UI test |
| `4x *.png snapshot files` | Visual baselines for Android, iOS, Windows, Mac |

---

## 🟡 Suggestions

### 1. UI Test Does Not Reproduce the Original Bug Scenario

**File:** `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16522.cs`

**Problem:**  
The test navigates between **tabs within the same FlyoutItem** (`Settings` → `Main`). The original bug (#16522) is triggered by navigating **between FlyoutItems** — specifically from a flyout item without tabs (e.g., "About") to one with tabs (e.g., "Main") — which causes the `BottomNavigationView` to be re-rendered from scratch and its initial `ColorDrawable` animation to fire.

The current test would only catch regressions in tab-switching color behavior, not the actual flyout navigation flash described in the issue.

**Recommended test flow (to actually reproduce the bug):**
```csharp
public void ShellTabBarBackgroundColor()
{
    App.WaitForElement("Label");
    // Navigate via flyout to a page without tabs
    App.TapInFlyout("About");  // or equivalent flyout navigation
    // Navigate back to a page with tabs — this is where the flash occurs
    App.TapInFlyout("Main");
    App.WaitForElement("Label");
    VerifyScreenshot();
}
```

Note: The snapshot files committed for iOS, Windows, and Mac won't show the Android-specific flash, so screenshots on those platforms are not useful for verifying this Android fix.

---

### 2. Fix Relies on Implicit Animation Side-Effect (Worth Commenting)

**File:** `src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs`

**Observation:**  
The fix works because `ShellBottomNavViewAppearanceTracker.SetBackgroundColor` checks `lastColor == newColor` before creating a `ColorChangeRevealDrawable`. By pre-seeding the `ColorDrawable` to the target color, the lastColor read by the tracker matches newColor, making any animation visually a no-op.

The existing comment (`// Apply background color from appearance, fallback to default if unavailable`) is helpful, but could explain *why* this is done ahead of `_appearanceTracker.SetAppearance`:

```csharp
// Pre-seed the initial ColorDrawable background to the target color so that
// ShellBottomNavViewAppearanceTracker sees lastColor == newColor and skips
// the ColorChangeRevealDrawable transition animation. This only applies on
// the first SetAppearance call while the background is still a ColorDrawable.
if (_bottomView.Background is ColorDrawable background && appearance is IShellAppearanceElement appearanceElement)
{
    background.Color = appearanceElement.EffectiveTabBarBackgroundColor?.ToPlatform() ?? ShellRenderer.DefaultBottomNavigationViewBackgroundColor.ToPlatform();
}
```

---

## 🔵 Minor / Nits

### 3. Missing Newline at End of File

**Files:**
- `src/Controls/tests/TestCases.HostApp/Issues/Issue16522.xaml`
- `src/Controls/tests/TestCases.HostApp/Issues/Issue16522.xaml.cs`

Both files end without a trailing newline (`\ No newline at end of file`). This is a minor style nit but is consistent across the MAUI codebase.

---

### 4. Unnecessary Trailing Whitespace in Constructor

**File:** `src/Controls/tests/TestCases.HostApp/Issues/Issue16522.xaml.cs`

```csharp
public Issue16522()
{
    InitializeComponent();
    
}
```

There is a blank line with trailing whitespace inside the constructor. The constructor body could simply be:
```csharp
public Issue16522() => InitializeComponent();
```

---

## ✅ Looks Good

- **Core fix is minimal and correct.** The `_bottomView.Background is ColorDrawable` check is naturally self-limiting — it only matches on the initial `SetAppearance` call. After the appearance tracker replaces the background with a `ColorChangeRevealDrawable` or `MaterialShapeDrawable`, subsequent calls fall through without modification.
- **Fallback to `ShellRenderer.DefaultBottomNavigationViewBackgroundColor`** correctly handles the case where `EffectiveTabBarBackgroundColor` is null, matching the behavior already used in `ShellBottomNavViewAppearanceTracker`.
- **The `using Microsoft.Maui.Controls.Handlers.Compatibility;` import** is correctly added to resolve `ShellRenderer.DefaultBottomNavigationViewBackgroundColor`.
- **Test category** `UITestCategories.Shell` is appropriate.
- **Snapshot baselines** are committed for all four platforms.
- **`[Issue]` attribute** on the HostApp page correctly identifies the issue, tracker, and affected platform (`PlatformAffected.Android`).
</details>
