### PR TITLE
[X] CSS specificity

### LINKED ISSUE #18980: Order of priority between Styles.xaml and custom css has changed in .net 8
### Description

After upgrading our project to .net 8 all of our custom css defined in a .css file and applied to a page/component is being overridden by the Style.xaml file.  If the control exists in the Styles.xaml file then any css is ignored.  If I remove the control type from the Styles.xaml file then the css works correctly.

### Steps to Reproduce

1. Create file -> new maui project
2. Create Styles.css in /Resources/Styles
3. Add record `.test{ background-color: yellow;}` to Styles.css
4. Add StyleSheetExtension to MainPage.xaml
5. Add new button with basic config and StyleClass="test"
6. Run project and button will be default maui color
7. Remove the Styles.xaml from the resource dictionary in App.xaml and re run the project, button will be yellow.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Windows

### Affected platform versions

Only tested on Windows 10

### Did you find any workaround?

No no work around found 

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change

Implement CSS specificity

### Issues Fixed

- fixes #18980

### CODE REVIEW

**Comment by albyrock87** [comment]
Even if this won't create merge conflicts on https://github.com/dotnet/maui/pull/17756 , it will create issues there once merged.

So please, until we're waiting for that PR to be merged in 9.0, can you at least notify about these kind of changes (once merged) in that PR? This way I can keep it up to date.

Thanks

**Comment by maestro-oc** [comment]
Do you know when we can expect this PR to be merged in?

**Comment by mattleibow** [comment]
Another one of your PRs @StephaneDelcroix that we have not yet merged. Is this still ready to merge or, after the other specificity changes, does this need updates?

**Comment by StephaneDelcroix** [comment]
@mattleibow it's ready

File: src/Controls/src/Core/StyleSheets/Style.cs [hunk 1]
```diff
@@ -71,15 +71,14 @@ public void Apply(VisualElement styleable, bool inheriting = false)
 				if (property == null)
 					continue;
 				if (string.Equals(decl.Value, "initial", StringComparison.OrdinalIgnoreCase))
-					//FIXME
-					styleable.ClearValue(property, new SetterSpecificity(SetterSpecificity.StyleImplicit, 0, 0, 0));
+					styleable.SetValue(property, property.DefaultValue, new SetterSpecificity(SetterSpecificity.StyleImplicit, (byte)selectorSpecificity.Id, (byte)selectorSpecificity.Class, (byte)selectorSpecificity.Type));
```
Comment (jfversluis) [inline src/Controls/src/Core/StyleSheets/Style.cs:74]: cast to byte? Or just 0, 0, 0?

File: src/Controls/src/Core/StyleSheets/Style.cs [hunk 2]
```diff
@@ -71,15 +71,14 @@ public void Apply(VisualElement styleable, bool inheriting = false)
...
-					styleable.ClearValue(property, new SetterSpecificity(SetterSpecificity.StyleImplicit, 0, 0, 0));
+					styleable.SetValue(property, property.DefaultValue, new SetterSpecificity(SetterSpecificity.StyleImplicit, (byte)selectorSpecificity.Id, (byte)selectorSpecificity.Class, (byte)selectorSpecificity.Type));					
 				else
 				{
 					object value;
 					if (!convertedValues.TryGetValue(decl, out value))
 						convertedValues[decl] = (value = Convert(styleable, decl.Value, property));
 					//FIXME: compute distance
-					styleable.SetValue(property, value, new SetterSpecificity(SetterSpecificity.StyleImplicit, 0, 0, 0));
+					styleable.SetValue(property, value, new SetterSpecificity(SetterSpecificity.StyleImplicit, (byte)selectorSpecificity.Id, (byte)selectorSpecificity.Class, (byte)selectorSpecificity.Type));
```
Comment (jfversluis) [inline src/Controls/src/Core/StyleSheets/Style.cs:81]: cast to byte? Or just 0, 0, 0?

**Review by jfversluis — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]
