### PR TITLE
Measure Images in FlexLayout at full size

### LINKED ISSUE #4080: [Windows] FlexLayout not wrapping correctly
### Description

FlexLayout not wrapping correctly
image

### Steps to Reproduce

1. Download [FlexLayoutDemos.zip](https://github.com/dotnet/maui/files/7853774/FlexLayoutDemos.zip)
2. Launch the App on Android and navigate to the sample "Photo Wrapping"

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change

Force FlexLayout image measurement to measure images at full size to preserve legacy behavior.

### Issues Fixed

Fixes #4080

### CODE REVIEW

File: src/Controls/src/Core/Layout/FlexLayout.cs [hunk 1]
```diff
@@ -471,19 +471,46 @@ void InitItemProperties(IView view, Flex.Item item)
 			}
 		}
 
+#pragma warning disable RS0016 // Add public types and members to the declared API
```
Comment (rmarinho) [inline src/Controls/src/Core/Layout/FlexLayout.cs:474]: isn't this just going around the reason we added the analizer? shouldn't this fix go to main/net7 ?

**Comment by rmarinho** [comment]
Can we add a test for this?

**Comment by hartez** [comment]
> Can we add a test for this?

Sure, done.

File: src/Controls/src/Core/Layout/FlexLayout.cs (hunk 1 above)
Comment (rmarinho) [reply src/Controls/src/Core/Layout/FlexLayout.cs:477]: maybe a `TODO: Remove on NET7`
