### PR TITLE
ScrollView's Gradient Background - UITest

### LINKED ISSUE #24016: ScrollView's Background as LinearGradientBrush behavior is different iOS vs Android
### Description

See repro.

Screenshot 2024-08-05 alle 16 43 48

In iOS when you have a Background set to a(n horizontal) ScrollView and you scroll it the background is not fixed to the page and scrolls with its content.

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

https://github.com/inimirpaz/maui_issues/tree/scrollview_background_issue

### Version with bug

8.0.71 SR7.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/24016

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/0b3c2c40-3ab5-4054-ac84-a6355bd80681" width="300px"/>|<video src="https://github.com/user-attachments/assets/71456cb3-9adb-4c2b-a685-31e274e855f1" width="300px"/>|

### CODE REVIEW

File: src/Core/src/Handlers/ScrollView/ScrollViewHandler.cs [hunk 1]
```diff
@@ -24,6 +24,7 @@ public partial class ScrollViewHandler : IScrollViewHandler
 			[nameof(IScrollView.Orientation)] = MapOrientation,
 #if __IOS__
```
Comment (jsuarezruiz) [inline src/Core/src/Handlers/ScrollView/ScrollViewHandler.cs:25]: Should be?

`#if __IOS__ && MACCATALYST`

File: src/Controls/tests/TestCases.HostApp/Issues/Issue24061.xaml [hunk 2]
```diff
@@ -0,0 +1,41 @@
+﻿<?xml version="1.0" encoding="utf-8" ?>
+<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
+             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
+             x:Class="Maui.Controls.Sample.Issues.Issue24061"
+             xmlns:ns="clr-namespace:Maui.Controls.Sample.Issues">
+    <ScrollView Orientation="Horizontal"
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.HostApp/Issues/Issue24061.xaml:6]: Could be nice if can include for example, a Button, and tapping it add/remove the gradient background. In this way, we can validate changes at runtime.

Comment (kubaflo) [reply src/Controls/tests/TestCases.HostApp/Issues/Issue24061.xaml]: Sure!

Comment (kubaflo) [reply src/Controls/tests/TestCases.HostApp/Issues/Issue24061.xaml]: Done

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24061.cs [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+		public void ScrollViewGradientBackgroundShouldWorkWithScrollView()
+		{
+			App.WaitForElement("Item2");
+			App.SwipeRightToLeft("Item2", 0.99);
+
+			VerifyScreenshot("ScrollViewGradientBackground");
+			App.Click("button");
+			VerifyScreenshot("ScrollViewWithoutGradientBackground");
+			App.Click("button");
+			VerifyScreenshot("ScrollViewGradientBackground");
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24061.cs:26]: There are pending snapshots. Are available on the latest build.
image

Could you commit them?

**Review by jsuarezruiz — DISMISSED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24061.cs (hunk 3 above)
Comment (kubaflo) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24061.cs:26]: Could you please /azp again? I need one more screenshot :)

**Comment by kubaflo** [comment]
@jsuarezruiz thanks! I have all the snapshots now :)

**Comment by kubaflo** [comment]
@jsuarezruiz the issue seems to be fixed by another PR. So, let's maybe just keep the UITest

**Review by mattleibow — APPROVED** [review]
