### PR TITLE
CollectionView - Recycle DataTemplates when using template selector

### LINKED ISSUE #11272: CollectionView virtualization does not work when using a DataTemplateSelector
### Description

CollectionView virtualization does not work when using a DataTemplateSelector.
Both on android and ios.
Both on xamarin-forms and dotnet-maui.

I think this is a serious performance issue.
I've already reported this issue [here](https://github.com/xamarin/Xamarin.Forms/issues/13045#issuecomment-1254779257) with full details.
Could anybody help ?

### Steps to Reproduce

1. Run app from the repro project (either xamarin forms or maui, both for ios and android)
2. Click on the Add button
3. Scroll down/up a bit, and observe the increase of counters.
4. Compare the performance of different collection types on each tab.

### Link to public reproduction project repository

...

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

All

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Redth**
### Description of Change

For Android and iOS we were using a single value for the 'view/cell' item type in the platform adapter/source.  If you were using a data template selector, and returned different data templates, whenever a recycled view/cell's data template didn't match the data template it needed to display for the new/recycled context, the whole view tree of that template would be recreated.

This PR ensures we have a unique view/cell type for every different DataTemplate.Type that might be returned by the template selector so that when a view/cell is recycled it should always be reused for the same DataTemplate it was created for, and so the view hierarchy won't be recreated.

### Issues Fixed

 - fixes #11272

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs [hunk 1]
```diff
@@ -134,6 +134,9 @@ public override void UpdateItemsSource()
 
 		protected override UICollectionViewDelegateFlowLayout CreateDelegator() => new CarouselViewDelegator(ItemsViewLayout, this);
 
+#if NET8_0_OR_GREATER
+		[Obsolete("Use DetermineCellReuseId(NSIndexPath indexPath) instead.")]
+#endif
 		protected override string DetermineCellReuseId()
```
Comment (mattleibow) [inline src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs:140]: Does it matter that this code is not running anymore? Or maybe I missed something?

File: src/Controls/src/Core/Handlers/Items/Android/Adapters/ItemsViewAdapter.cs [hunk 2]
```diff
@@ -95,7 +96,16 @@ public override int GetItemViewType(int position)
 		{
 			if (_usingItemTemplate)
 			{
-				return ItemViewType.TemplatedItem;
+				// If we're using a template selector, using the 
+				// selected DataTemplate's 'Type'
+				// and get the hashcode to get a reasonably unique
+				// value for the DataTemplate for us to recycle
+				// all views using this DataTemplate with
+				return _itemTemplateSelector?
```
Comment (hartez) [inline src/Controls/src/Core/Handlers/Items/Android/Adapters/ItemsViewAdapter.cs:104]: Until you make OnCreateViewHolder and OnBindViewHolder aware of the `viewType` integers you're generating, none of this is going to have any effect. 

GetHashCode for the value is a little... icky. Technically it will work, because even if the multiple template types end up having the same hash code, TemplatedItemViewHolder will catch it during Bind and fix it up. 

Actually, it's going to fail pretty spectacularly if the hash code happens to collide with one of the known view types in ItemViewType. E.g., if your CV has a templated header, and if the hash code happens to be 43 for your ItemTemplate, you're going to get items that look like your header. 

So at the very least, you need to shift the hash code result out of the range of stuff in ItemViewType. But even then, you're always at risk of hash code collisions between data templates causing the same template thrash that you're trying to avoid.

**Review by hartez — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs (hunk 1 above)
Comment (hartez) [reply src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs:140]: It's using the alternate version of the method, so no; it doesn't matter.

File: src/Controls/src/Core/Handlers/Items/Android/Adapters/ItemsViewAdapter.cs [hunk 3]
```diff
@@ -87,25 +87,36 @@ public override RecyclerView.ViewHolder OnCreateViewHolder(ViewGroup parent, int
...
+			{
+				return new TemplatedItemViewHolder(itemContentView, dataTemplate, IsSelectionEnabled(parent, viewType));
+			}
+
 			return new TemplatedItemViewHolder(itemContentView, ItemsView.ItemTemplate, IsSelectionEnabled(parent, viewType));
 		}
 
 		public override int ItemCount => ItemsSource.Count;
 
+		System.Collections.Generic.Dictionary<int, DataTemplate> viewTypeDataTemplates = new();
```
Comment (hartez) [inline src/Controls/src/Core/Handlers/Items/Android/Adapters/ItemsViewAdapter.cs:101]:
```suggestion
		System.Collections.Generic.Dictionary<int, DataTemplate> _viewTypeDataTemplates = new();
```

**Review by hartez — CHANGES_REQUESTED** [review]
Looks fine in theory, minor naming nit.

File: src/Controls/src/Core/Handlers/Items/Android/Adapters/ItemsViewAdapter.cs [hunk 4]
```diff
@@ -86,16 +87,36 @@ public override RecyclerView.ViewHolder OnCreateViewHolder(ViewGroup parent, int
 
 			var itemContentView = _createItemContentView.Invoke(ItemsView, context);
 
+			// See if our cached templates have a match
+			if (viewTypeDataTemplates.TryGetValue(viewType, out var dataTemplate))
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items/Android/Adapters/ItemsViewAdapter.cs:91]:
```suggestion
			if (_viewTypeDataTemplates.TryGetValue(viewType, out var dataTemplate))
```

File: src/Controls/src/Core/Handlers/Items/Android/Adapters/ItemsViewAdapter.cs [hunk 5]
```diff
@@ -86,16 +87,36 @@ public override RecyclerView.ViewHolder OnCreateViewHolder(ViewGroup parent, int
...
+					return ItemViewType.TemplatedItem;
+
+				var item = ItemsSource?.GetItem(position);
+
+				var template = _itemTemplateSelector?.SelectTemplate(item, ItemsView);
+				var id = template?.Id ?? ItemViewType.TemplatedItem;
+
+				// Cache the data template for future use
+				if (!viewTypeDataTemplates.ContainsKey(id))
+					viewTypeDataTemplates.Add(id, template);
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items/Android/Adapters/ItemsViewAdapter.cs:117]:
```suggestion
				if (!_viewTypeDataTemplates.ContainsKey(id))
					_viewTypeDataTemplates.Add(id, template);
```

File: src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs [hunk 6]
```diff
@@ -337,6 +339,41 @@ protected virtual void CacheCellAttributes(NSIndexPath indexPath, CGSize size)
...
+			if (ItemsView.ItemTemplate != null)
+			{
+				var item = ItemsSource[indexPath];
+
+				var dataTemplate = ItemsView.ItemTemplate.SelectDataTemplate(item, ItemsView);
+
+				var cellOrientation = ItemsViewLayout.ScrollDirection == UICollectionViewScrollDirection.Vertical ? "v" : "h";
+				var cellType = ItemsViewLayout.ScrollDirection == UICollectionViewScrollDirection.Vertical ? typeof(VerticalCell) : typeof(HorizontalCell);
+
+				var reuseId = $"_maui_{cellOrientation}_{dataTemplate.Type.GetHashCode()}";
```
[the remark this answers is not in the document]
Comment (Redth) [reply src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs]: Yep good catch, fixed!

**Comment by Vroomer** [comment]
@Redth Hello, can you confirm whether this PR fixes https://github.com/dotnet/maui/issues/12988 as well?

**Review by hartez — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]
