### PR TITLE
Trigger remeasure when constraints on CV changes

### LINKED ISSUE #21967: CollectionView causes invalid measurements on Android rotation
### Description

See attached githib for repo project.

When running the attached Android app on a simulator. The page initially looks correct. (Click Load)

image

After rotation however, the second row is displayed incorrectly.

image

In addition, in the debug output you can see some incorrect measure values of 390451572 x 390451572

image

And sometimes, after rotation, the app gets caught in a continuous Measure / Layout sequence that only stops when you rotate back to the original orientation.

Using Nightly - 8.0.40-nightly.10515

### Steps to Reproduce

- Run repo project on Android.
- Click Load button.
- Rotate device.
- Scroll tiles up slightly to see second row.
- Observe broken layout.
- (In debugger) Observe random measure calls of 390451572 x 390451572

### Link to public reproduction project repository

https://github.com/jump32/maui-app-collection-view-issue

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

It is possible that switching the Collection View to `ItemSizingStrategy="MeasureAllItems"`.

Possible. But highly undesirable.

### Relevant log output

```shell
Measure 184.36363636363637 x ∞
Measure 184.36363636363637 x ∞
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
Measure 390451572 x 390451572
Measure 390451572 x 390451572
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
Measure 390451572 x 390451572
Measure 390451572 x 390451572
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
Measure 184.36363636363637 x ∞
Measure 184.36363636363637 x ∞
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
Measure 390451572 x 390451572
Measure 390451572 x 390451572
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
Measure 390451572 x 390451572
Measure 390451572 x 390451572
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
Measure 184.36363636363637 x ∞
Measure 184.36363636363637 x ∞
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
Measure 390451572 x 390451572
Measure 390451572 x 390451572
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
Measure 390451572 x 390451572
Measure 390451572 x 390451572
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
Measure 184.36363636363637 x ∞
Measure 184.36363636363637 x ∞
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
Measure 390451572 x 390451572
Measure 390451572 x 390451572
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
Measure 390451572 x 390451572
Measure 390451572 x 390451572
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
Measure 389.45454545454544 x ∞
Measure 389.45454545454544 x ∞
ArrangeChildren {X=0 Y=0 Width=389.45454545454544 Height=584.3636363636364}
ArrangeChildren {X=0 Y=0 Width=389.45454545454544 Height=584.3636363636364}
Measure 389.45454545454544 x ∞
Measure 389.45454545454544 x ∞
ArrangeChildren {X=0 Y=0 Width=389.45454545454544 Height=584.3636363636364}
ArrangeChildren {X=0 Y=0 Width=389.45454545454544 Height=584.3636363636364}
Measure 390451572 x 390451572
Measure 390451572 x 390451572
ArrangeChildren {X=0 Y=0 Width=184.36363636363637 Height=276.72727272727275}
ArrangeChildren {X=0 Y=0 Width=184.72727272727272 Height=276.72727272727275}
```

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

When the constraints of a RecyclerView change, the items don't get recreated so we have to re-evaluate the cached sizes being used to measure each of the items. The way the code was setup it would only set the static size once and then reuse that no matter what the change are. 

My current overall thinking here is that `ItemSizingStrategy` is somewhat pointless on android as it relates to performance. The only reason to use it would be if you want the first item to set the measure for the rest of your cells.  Generally, if you want the best performance, and you want all the cells to be the same size, then just set a specific height/width on your cells.

For example, if you just remove all of our custom measuring code inside ItemContentView and just rely on the "LayoutParams" to size the elements it all measures naturally.   

I think there are some additional issues related to messages getting propagated to the handlers
https://github.com/dotnet/maui/issues/22271

But we'll look at that as part of SR6

### Issues Fixed

Fixes #21967

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/Android/ItemContentView.cs [hunk 1]
```diff
@@ -127,8 +149,7 @@ protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
 				pixelHeight = (int)this.ToPixels(measure.Height);
 			}
 
-			_reportMeasure?.Invoke(new Size(pixelWidth, pixelHeight));
-			_reportMeasure = null; // Make sure we only report back the measure once
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/Android/ItemContentView.cs:131]: We can't really set this to null because if the constraints on the CV change we need to report a new measure.

File: src/Controls/samples/Controls.Sample.UITests/Issues/Issue21967.xaml.cs [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+					text = Enumerable.Range(0,1000).Select(x => x.ToString()).Aggregate((x, y) => x + " " + y);
+				}
+				return new Data(text, x);
+			})
+			.ToList();
+
+		
+        button.Clicked += (_, _) =>
+        {
+            if (cv.WidthRequest == 200)
```
Comment (jsuarezruiz) [inline src/Controls/samples/Controls.Sample.UITests/Issues/Issue21967.xaml.cs:34]: Could we update the sample to use the Page Width? In this way, we can validate with an UITest the UI rotating the device.

**Review by jsuarezruiz — COMMENTED** [review]
Debugging, the output call my attention:
issue-21967-perf-II

Should not being in this loop without interact with the UI (like, scrolling etc). Taking a look to the HWUI rendering:
issue-21967-perf

**Comment by jsuarezruiz** [comment]
> Debugging, the output call my attention: issue-21967-perf-II [ issue-21967-perf-II ](https://private-user-images.githubusercontent.com/6755973/328837812-7c52ed6a-d713-427f-bfdc-783cef6be65a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjIxMDMsIm5iZiI6MTcxNTE2MTgwMywicGF0aCI6Ii82NzU1OTczLzMyODgzNzgxMi03YzUyZWQ2YS1kNzEzLTQyN2YtYmZkYy03ODNjZWY2YmU2NWEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMDk1MDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQ4OWRkNzI1NTQ1ZjExYzgzN2UwODI5OGJlNWZlN2Q3NDQ0MTc4MjkyYzU0YjgyMWM3Mzg5ZGI3ZmQxNzczYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.64d-MLNT74bHaWkOuMbPRwK5Rl2xBwgC76RPDU0RjrA) [ ](https://private-user-images.githubusercontent.com/6755973/328837812-7c52ed6a-d713-427f-bfdc-783cef6be65a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjIxMDMsIm5iZiI6MTcxNTE2MTgwMywicGF0aCI6Ii82NzU1OTczLzMyODgzNzgxMi03YzUyZWQ2YS1kNzEzLTQyN2YtYmZkYy03ODNjZWY2YmU2NWEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMDk1MDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQ4OWRkNzI1NTQ1ZjExYzgzN2UwODI5OGJlNWZlN2Q3NDQ0MTc4MjkyYzU0YjgyMWM3Mzg5ZGI3ZmQxNzczYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.64d-MLNT74bHaWkOuMbPRwK5Rl2xBwgC76RPDU0RjrA)
> 
> Should not being in this loop without interact with the UI (like, scrolling etc). Taking a look to the HWUI rendering: issue-21967-perf [ issue-21967-perf ](https://private-user-images.githubusercontent.com/6755973/328838153-ead2a6f3-48bd-435f-8246-c46c69cabf2d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjIxMDMsIm5iZiI6MTcxNTE2MTgwMywicGF0aCI6Ii82NzU1OTczLzMyODgzODE1My1lYWQyYTZmMy00OGJkLTQzNWYtODI0Ni1jNDZjNjljYWJmMmQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMDk1MDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjBjOTE1YWRjNzJkZDE2MTgzYzU5OWU3ZmEzYTQ5ZThhZDc0ODkyNTJlMGM1OThmZWE3NTUxNjNmMDZmOTgyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P_DjpEZKtlkCX7C7eWISo9HhsDIDHN-ocr_3CtuQGFs) [ ](https://private-user-images.githubusercontent.com/6755973/328838153-ead2a6f3-48bd-435f-8246-c46c69cabf2d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjIxMDMsIm5iZiI6MTcxNTE2MTgwMywicGF0aCI6Ii82NzU1OTczLzMyODgzODE1My1lYWQyYTZmMy00OGJkLTQzNWYtODI0Ni1jNDZjNjljYWJmMmQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMDk1MDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjBjOTE1YWRjNzJkZDE2MTgzYzU5OWU3ZmEzYTQ5ZThhZDc0ODkyNTJlMGM1OThmZWE3NTUxNjNmMDZmOTgyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P_DjpEZKtlkCX7C7eWISo9HhsDIDHN-ocr_3CtuQGFs)

Ok, have done more tests and can reproduce the same without the changes. So, we can create a new issue and review this problem in another PR.

File: src/Controls/samples/Controls.Sample.UITests/Issues/Issue21967.xaml.cs (hunk 2 above)
Comment (PureWeen) [reply src/Controls/samples/Controls.Sample.UITests/Issues/Issue21967.xaml.cs:34]: Yea, that's caused by this unfortunately
https://github.com/dotnet/maui/issues/22271

**Review by jsuarezruiz — APPROVED** [review]
