### PR TITLE
[XSG] support full-page XHR

### LINKED ISSUE #32192: [XSG] full-page Xaml HotReload doesn't work
see
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2612330
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2611192

Full-page XHR (Xaml HotReload) is hooked to the runtime inflator. XSG bypass that. if a full page XHR is triggered, we should fall back to runtime inflation for that page.

the fallback code should only be present if diagnostics are enabled

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change

if XHR provides a replaced xaml, fallback to runtime inflation

- fixes #32192

### CODE REVIEW

**Review by simonrozsival — COMMENTED** [review]
I'd like to see one extra test that will verify that we don't generate `InitializeComponentRuntime` + that preamble of `InitializeComponent` for XSG with diagnostics disabled. Just to make sure we don't regress at some point and don't emit unnecessary code in Release builds.

File: src/Controls/src/SourceGen/InitializeComponentCodeWriter.cs [hunk 1]
```diff
@@ -93,6 +93,26 @@ PrePost newblock() =>
...
 				{
+					if (xamlItem.ProjectItem.EnableDiagnostics)
+                    {
+						codeWriter.WriteLine(
+$$"""
+// Fallback to Runtime inflation if the page was updated by HotReload
+		var rlr = global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceProvider2?.Invoke(new global::Microsoft.Maui.Controls.Internals.ResourceLoader.ResourceLoadingQuery
+		{
+			AssemblyName = typeof({{rootType.ToFQDisplayString()}}).Assembly.GetName(),
+			ResourcePath = global::Microsoft.Maui.Controls.Xaml.XamlResourceIdAttribute.GetPathForType(typeof({{rootType.ToFQDisplayString()}})),
```
Comment (StephaneDelcroix) [inline src/Controls/src/SourceGen/InitializeComponentCodeWriter.cs]: GetPathForType is internal

**Review by simonrozsival — APPROVED** [review]
