### PR TITLE
Fix VoiceOver doesnot announces the State of the ComboBox 

### LINKED ISSUE #30899: Voice over is not announcing role as combo box and state as collapsed for "Project" combobox:A11y_.NET maui_user can creat a tak_Screen reader
**Please do not close this bug. This bug should only be closed by Trusted Tester after verification.**
"[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier."

## GitHub Tags
#A11yTCS; #A11yMAS; #WCAG4.1.2; #ScreeReader; #BM_.NETMaui_Mac_JUL2025; #DesktopApp; #Device; #FTP; #A11ySev1; #.NET MAUI SDKs; #Mac; #VoiceOver;

## Environment Details:
Application: Developer Balance (.NET Maui)
MAC
M2

## Repro Steps:

1. Turn on Voiceover
2. Install and open the Developer Balance app
3. Press Control + Option + Right arrow key to navigate "Add task" button and press  Control + Option + space key.
4. Press Control + Option + Right arrow key to navigate "Project" combo box and press  Control + Option + space key to expand.
5. Observe the issue 

## Actual Result:
When navigate to "Project" combo box using Control + Option + Right arrow, voice over is not announcing the role as combo box and state as collapsed.

**Note:**
Same issue repro with "Category" combo box present in create a project page

## Expected Result:
When navigate to "Project" combo box using Control + Option + Right arrow voice hover should announce role as combo box , name as project and state as collapsed.

## User Impact:
Screen user will not get the correct control type and state of the control. 

## Attachment

https://github.com/user-attachments/assets/cb3e2a0c-38be-49f9-a7ba-3d41924001f1

### Similar issue

https://github.com/user-attachments/assets/242f25f8-0462-430f-aa2b-b24b507837a7

### PR DESCRIPTION
**Pull request by SuthiYuvaraj**
### Issue Description:

VoiceOver does not read the ComboBox State correctly,  In the sample, the ComboBox behavior is implemented using SfTextInputLayout with a Picker. However, I have already implemented the semantic properties for picker , it was overriden by SfTextInputLayout,  the expectation is for VoiceOver to recognise and announce it as a ComboBox state.

### Description of change :
Update SemanticProperties using property changed on IsOpen property in picker to achieve the expected output.

> Note:
net9.0 PR - https://github.com/dotnet/maui-samples/pull/651

### Issues Fixed
Fixes [#30899 ](https://github.com/dotnet/maui/issues/30899)

### Tested the behaviour in the following platforms
- [ ] Android
- [ ] Windows
- [ ] iOS
- [x] Mac

### CODE REVIEW

File: src/Templates/src/templates/maui-mobile/PageModels/ProjectDetailPageModel.cs [hunk 1]
```diff
@@ -177,6 +180,18 @@ private async Task TaskCompleted(ProjectTask task)
 		OnPropertyChanged(nameof(HasCompletedTasks));
 	}
 
+	partial void  OnIsCategoryPickerExpandedChanged(bool value)
+	{
+		if (value)
+		{
+			SemanticScreenReader.Announce("State Expanded");
```
Comment (jsuarezruiz) [inline src/Templates/src/templates/maui-mobile/PageModels/ProjectDetailPageModel.cs]: The current announcements "State Expanded" and "State Collapsed" lack context about what was expanded/collapsed.

Comment (jsuarezruiz) [inline src/Templates/src/templates/maui-mobile/PageModels/ProjectDetailPageModel.cs]: Hard-coded English strings "State Expanded" won't be localized for non-English users. Could include localized resources?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Templates/src/templates/maui-mobile/PageModels/ProjectDetailPageModel.cs (hunk 1 above)
Comment (SuthiYuvaraj) [reply src/Templates/src/templates/maui-mobile/PageModels/ProjectDetailPageModel.cs]: @jsuarezruiz, I checked through the MAUI project templates, and it looks like all existing uses of SemanticProperties and SemanticScreenReader use English text directly, without localisation resources. I’ve followed that same approach here to stay consistent with the current template pattern.

Comment (SuthiYuvaraj) [reply src/Templates/src/templates/maui-mobile/PageModels/ProjectDetailPageModel.cs]: Hi @jsuarezruiz,I’ve updated the SemanticScreenReader with the responsible category. Please review the changes and let me know if you have any feedback or concerns.

File: src/Templates/src/templates/maui-mobile/PageModels/TaskDetailPageModel.cs [hunk 2]
```diff
@@ -118,6 +121,18 @@ public bool CanDelete
 		}
 	}
 
+	partial void OnIsProjectPickerExpandedChanged(bool value)
+	{
+		if (value)
+		{
+			SemanticScreenReader.Announce("Project ComboBox, State Expanded");
```
Comment (jsuarezruiz) [inline src/Templates/src/templates/maui-mobile/PageModels/TaskDetailPageModel.cs:128]: Should/could be a localized text?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Templates/src/templates/maui-mobile/PageModels/TaskDetailPageModel.cs (hunk 2 above)
Comment (SuthiYuvaraj) [reply src/Templates/src/templates/maui-mobile/PageModels/TaskDetailPageModel.cs:128]: @jsuarezruiz,  I checked the MAUI project templates and found that SemanticProperties and SemanticScreenReader consistently use direct English strings without localisation. To stay aligned with that pattern, I have followed the same approach here.

**Review by kubaflo — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]
