### PR TITLE
Fix issue using FillRule with Paths

### LINKED ISSUE #14461: FillRule.EvenOdd not working for shapes
### Description

According to this example/documentation

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/shapes/fillrules?view=net-maui-7.0

it should be straight forward making a composite shape with a ring inside another ring... I have copied the exact same code, and it simply displays a big circle... I believe there is a bug here.

### Steps to Reproduce

Put the following code into any page:

<Path Stroke="Black"
      Fill="#CCCCFF"
      Aspect="Uniform"
      HorizontalOptions="Start">
    <Path.Data>
        
        <GeometryGroup>
            <EllipseGeometry RadiusX="50"
                             RadiusY="50"
                             Center="75,75" />
            <EllipseGeometry RadiusX="70"
                             RadiusY="70"
                             Center="75,75" />
            <EllipseGeometry RadiusX="100"
                             RadiusY="100"
                             Center="75,75" />
            <EllipseGeometry RadiusX="120"
                             RadiusY="120"
                             Center="75,75" />
        </GeometryGroup>
    </Path.Data>
</Path>

And a playin circle is drawn, and not the expected ring inside a ring...

### Link to public reproduction project repository

none... but tjek out example...

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

### Affected platform versions

iPhone 14 Pro Max iOS 16.4, Mac Ventura, Samsung 21FE Android 13

### Did you find any workaround?

Nope...

### Relevant log output

```shell
None...
```

### LINKED ISSUE #15431: The EvenOdd FillRule  failed in the wraping space
### Description

I use the official example and run the code as it is. Draw several nested circle paths and set the `FillRule` to `EvenOdd`  get a rendering of a whole circle  like this

image

The official example is here:
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/shapes/fillrules?view=net-maui-7.0

### Steps to Reproduce

1. Clone the repository to local (https://github.com/dotnet/maui-samples/)

2. Open the ShapesDemos solution  and run to an Android device

3. check the `path geometry demos` page, it's

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android, Windows

### Affected platform versions

Android 11 ， windows sdk 10.19041

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix issue using the **FillRule** property with Paths.

Before
image

After
image

To test the changes, launch the .NET MAUI Gallery and navigate to the Path samples. Then, check the composite shape result.
image

### Issues Fixed

Fixes #14461 
Fixes #15431

### CODE REVIEW

**Comment by rachelkang** [comment]
Note for reviewers: the sample is located at Controls > Shapes > More samples > Path Gallery

**Review by rachelkang — CHANGES_REQUESTED** [review]
Looks great, as described, on Windows and Android, but unfortunately not on iOS. The Composite shape, overlapping rectangles, and multiple line segments shapes are all completely filled/solid with no negative spaces.

image

**Comment by jsuarezruiz** [comment]
> Looks great, as described, on Windows and Android, but unfortunately not on iOS. The Composite shape, overlapping rectangles, and multiple line segments shapes are all completely filled/solid with no negative spaces.
> 
> image

Fixed. Could you try again?
Captura de pantalla 2023-04-14 a las 12 02 10

File: src/Controls/src/Core/Platform/ShapeExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,26 @@
+﻿using Microsoft.Maui.Controls.Shapes;
+using Microsoft.Maui.Graphics;
+
+namespace Microsoft.Maui.Controls.Platform
+{
+	internal static class ShapeExtensions
+	{
+		internal static WindingMode GetPathWindingMode(this IDrawable drawable, IShapeView shapeView)
+		{
+			if (drawable is not ShapeDrawable || shapeView is null || shapeView.Shape is not Path path)
```
Comment (rachelkang) [inline src/Controls/src/Core/Platform/ShapeExtensions.cs:10]: did you mean `shapeView is not null`?

```suggestion
			if (drawable is not ShapeDrawable || shapeView is not null || shapeView.Shape is not Path path)
```

File: src/Controls/src/Core/Platform/iOS/ShapeViewExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+namespace Microsoft.Maui.Controls.Platform
+{
+	public static class ShapesExtensions
+	{
+		public static void UpdatePath(this PlatformGraphicsView platformView, IShapeView shapeView)
+		{
+			var shapeDrawable = new ShapeDrawable(shapeView);
+
+			var windowMode = shapeDrawable.GetPathWindingMode(shapeView);
+			shapeDrawable.UpdateWindingMode(windowMode);
```
Comment (rachelkang) [inline src/Controls/src/Core/Platform/iOS/ShapeViewExtensions.cs:13]:
```suggestion
			var windingMode = shapeDrawable.GetPathWindingMode(shapeView);
			shapeDrawable.UpdateWindingMode(windingMode);
```

File: src/Controls/src/Core/Platform/Windows/ShapesExtensions.cs [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+namespace Microsoft.Maui.Controls.Platform
+{
+	public static class ShapesExtensions
+	{
+		public static void UpdatePath(this W2DGraphicsView platformView, IShapeView shapeView)
+		{
+			var shapeDrawable = new ShapeDrawable(shapeView);
+
+			var windowMode = shapeDrawable.GetPathWindingMode(shapeView);
+			shapeDrawable.UpdateWindingMode(windowMode);
```
Comment (rachelkang) [inline src/Controls/src/Core/Platform/Windows/ShapesExtensions.cs:13]:
```suggestion
			var windingMode = shapeDrawable.GetPathWindingMode(shapeView);
			shapeDrawable.UpdateWindingMode(windingMode);
```

**Review by rachelkang — CHANGES_REQUESTED** [review]
iOS rendering LGTM too now! Just a couple small comments

File: src/Controls/src/Core/Platform/iOS/ShapeViewExtensions.cs (hunk 2 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Platform/iOS/ShapeViewExtensions.cs]: Oops, changed!

File: src/Controls/src/Core/Platform/ShapeExtensions.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Platform/ShapeExtensions.cs:10]: Is the correct value. Is the drawable is not a Shape, or ShapeView is null, return the default WindingMode.

File: src/Controls/src/Core/Platform/ShapeExtensions.cs [hunk 4]
```diff
@@ -7,7 +7,7 @@ internal static class ShapeExtensions
 	{
 		internal static WindingMode GetPathWindingMode(this IDrawable drawable, IShapeView shapeView)
 		{
-			if (drawable is not ShapeDrawable || shapeView is null || shapeView.Shape is not Path path)
+			if (drawable is not ShapeDrawable || shapeView is null || shapeView?.Shape is not Path path)
```
Comment (rachelkang) [inline src/Controls/src/Core/Platform/ShapeExtensions.cs:10]: Is the `?` needed? My understanding is that if it reaches the last condition, it's because it passed the previous condition which is the null check; so when it reaches the last condition, we know the shapeView there is not null. Is there something I'm misunderstanding?

Comment (jsuarezruiz) [reply src/Controls/src/Core/Platform/ShapeExtensions.cs]: Is not, removed.

**Review by rachelkang — APPROVED** [review]
