### PR TITLE
Don't call AppActions.SetAsync if no AppActions have been registered.

### LINKED ISSUE #5388: `ConfigureEssentials` called `AppActions.SetAsync` even if the app doesn't use App Actions feature
### Description

Created a new maui app and use ConfigureEssentials but didn't use app action feature, then tried `dotnet trace` found _some slower ms_ startup on speedscope

2420de99f5b94b69945eca8387be2436

It seems `AppActions.SetAsync` is called even if the app doesn't use app action feature https://github.com/dotnet/maui/blob/d71a9b3b1c79c07950b35b93920e8b62d3bd2383/src/Core/src/Hosting/EssentialsMauiAppBuilderExtensions.cs#L138-L147

Some other consideration maybe let developer call `AppActions.SetAsync` themselves, just like from Xamarin.Essentials App Actions (https://docs.microsoft.com/en-us/xamarin/essentials/app-actions?tabs=android)

### Steps to Reproduce

1. Create new project
2. Add essentials `ConfigureEssentials`
3. Check if `AppActions.SetAsync` is called even if the app doesn't use app action feature

Here is the result from speedscope
[c6333204d4f64b98872856281b0de284.json.zip](https://github.com/dotnet/maui/files/8287490/c6333204d4f64b98872856281b0de284.json.zip)

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10 (maybe others too)

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by eerhardt**
This was showing up in startup profiles of apps that use essentials.

I also moved the async logic into a separate method so the whole async state machine doesn't need to be used when there are no AppActions.

Fix #5388

### CODE REVIEW

**Review by jonathanpeppers — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]

File: src/Core/src/Hosting/EssentialsMauiAppBuilderExtensions.cs [hunk 1]
```diff
@@ -158,10 +166,12 @@ void HandleOnAppAction(object? sender, AppActionEventArgs e)
 
 		class EssentialsBuilder : IEssentialsBuilder
 		{
-			internal readonly List<AppAction> AppActions = new List<AppAction>();
+			private List<AppAction>? _appActions;
```
Comment (rmarinho) [inline src/Core/src/Hosting/EssentialsMauiAppBuilderExtensions.cs:169]: we don't really use private in our code style , not important, but just a reminder for future pr's

Comment (rmarinho) [inline src/Core/src/Hosting/EssentialsMauiAppBuilderExtensions.cs:169]:
```suggestion
		List<AppAction>? _appActions;
```
