### PR TITLE
[Windows] Fixed Unstable order of Flyout Items with conditional visibility 

### LINKED ISSUE #23834: Unstable order of FlyoutItems with conditional visibility
### Description

The order of the menu items on WinUI can differ from iOS/Android when binding IsVisible

### Steps to Reproduce

1. create app with FlyoutItems
2. make some of them having IsVisible bound to viewmodel bool variable (set to false)
```<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MauiApp1.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiApp1"
    Shell.FlyoutBehavior="Flyout"
    Title="MauiApp1">
    
    <FlyoutItem FlyoutDisplayOptions="AsSingleItem"
                Title="First">

        <ShellContent Title="Foo"
                      ContentTemplate="{DataTemplate local:MainPage}">
        </ShellContent>
    </FlyoutItem>
    
    <FlyoutItem FlyoutDisplayOptions="AsSingleItem"
                Title="Second">

        <ShellContent Title="Foo"
                      ContentTemplate="{DataTemplate local:MainPage}"
                      IsVisible="{Binding ShowSecondMenuItem}">
        </ShellContent>
    </FlyoutItem>
    
    <FlyoutItem FlyoutDisplayOptions="AsSingleItem"
                Title="Third">

        <ShellContent Title="Foo"
                      ContentTemplate="{DataTemplate local:MainPage}">
        </ShellContent>
    </FlyoutItem>
</Shell>
```
3. invert this variable value on some point (like a button click)
```
        private void OnCounterClicked(object sender, EventArgs e)
        {
            WhateverModel.Instance.ShowSecondMenuItem = !WhateverModel.Instance.ShowSecondMenuItem;
        }
```
4. FlyoutItem appears as last menu item
grafik

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SubhikshaSf4851**
### Root Cause: 
When the visibility of a Flyout item is changed, the UpdateMenuItemSource method simply adds the item to the end, resulting in the original order of the Flyout items being mismatched.
### Description of change:
Instead of adding the item, I have retrieved its original position and inserted it back into the Flyout items accordingly, which results the original order being maintained.
### Tested the behavior in the following platforms:
- [x] Windows
- [x] Android
- [x] iOS
- [x] Mac
### Issue Fixed:
Fixes #23834 

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/00f478d5-14a0-429d-946c-df423927a17a"> | <video src="https://github.com/user-attachments/assets/254148cc-4b09-4427-b583-0f102e76678a"> |

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs [hunk 1]
```diff
@@ -123,19 +123,31 @@ internal void UpdateMenuItemSource()
...
+				for (int index = 0; index < newItems.Count; index++)
 				{
-					if (!FlyoutItems.Contains(item))
+					var item = newItems[index];
+					var flyoutItemIndex = FlyoutItems.IndexOf(item);
+
+					if (flyoutItemIndex == -1)
 					{
-						FlyoutItems.Add(item);
+						if (index < FlyoutItems.Count)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs:133]: Store `FlyoutItems.Count` in a variable to minimize repeated property accesses.

File: src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs [hunk 2]
```diff
@@ -123,19 +123,31 @@ internal void UpdateMenuItemSource()
...
 				var newItems = IterateItems(newGrouping).ToList();
 
-				foreach (var item in newItems)
+				for (int index = 0; index < newItems.Count; index++)
 				{
-					if (!FlyoutItems.Contains(item))
+					var item = newItems[index];
+					var flyoutItemIndex = FlyoutItems.IndexOf(item);
+
+					if (flyoutItemIndex == -1)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs:131]: Not big performance differences, but can simplify this using `Contains`:

```
if (!FlyoutItems.Contains(item))
    {
        // Use Insert when within bounds, otherwise Add
        if (index < count)
        {
            FlyoutItems.Insert(index, item);
        }
        else
        {
            FlyoutItems.Add(item);
        }
    }
```

NOTE: count is a variable with the `FlyoutItems.Count `value.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23834.cs [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+	public override string Issue => "Flyout Item misbehavior";
+
+	[Test]
+	[Category(UITestCategories.FlyoutPage)]
+	public void Issue23834FlyoutMisbehavior()
+	{
+		App.WaitForElement("button");
+		App.Tap("button");
+		App.ShowFlyout();
+		VerifyScreenshot();
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23834.cs:19]: Pending snapshots.

Comment (jsuarezruiz) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23834.cs:19]: Snapshots already available in the latest build:

For example:
image

File: src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs (hunk 1 above)
Comment (SubhikshaSf4851) [reply src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs]: I have updated the changes per your suggestion.

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23834.cs (hunk 3 above)
Comment (SubhikshaSf4851) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23834.cs:19]: I have committed the pending snapshots

**Comment by bronteq** [comment]
@jsuarezruiz friendly ping, is it possible to merge in the next inflight round this pr? It seems ready.
My company is hitting the bug solved by this pr, then I saw that pr https://github.com/dotnet/maui/pull/28977 about Shell Flyout was merged.

**Comment by bronteq** [comment]
@jsuarezruiz friendly ping, is it possible to merge this pr in the next inflight round?

File: src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs [hunk 4]
```diff
@@ -122,20 +122,33 @@ internal void UpdateMenuItemSource()
 			{
 				_flyoutGrouping = newGrouping;
 				var newItems = IterateItems(newGrouping).ToList();
+				var itemsCount = FlyoutItems.Count;
 
-				foreach (var item in newItems)
+				for (int index = 0; index < newItems.Count; index++)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs:128]: Usually cannot expect to have a big collection here, but use the Contains with the two nested for loops have a big performance impact. Ideally we could kept it simple, but it should have the best possible behavior in all situations.

Comment (jsuarezruiz) [reply src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs:128]: Let's use a HashSet here.

File: src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs [hunk 5]
```diff
@@ -122,20 +122,33 @@ internal void UpdateMenuItemSource()
 			{
 				_flyoutGrouping = newGrouping;
 				var newItems = IterateItems(newGrouping).ToList();
+				var itemsCount = FlyoutItems.Count;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs]: This count becomes stale after Insert operations.

File: src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs [hunk 6]
```diff
@@ -122,20 +122,33 @@ internal void UpdateMenuItemSource()
...
 
-				foreach (var item in newItems)
+				for (int index = 0; index < newItems.Count; index++)
 				{
+					var item = newItems[index];
+
 					if (!FlyoutItems.Contains(item))
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs]: The performance degrades quadratically with collection size, for example, 100 items = 100,000 operations instead of 100.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs (hunk 6 above)
Comment (SubhikshaSf4851) [reply src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs]: @jsuarezruiz I've addressed the performance concern by using HashSet. Kindly let me know if you have any suggestions

File: src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs (hunk 5 above)
Comment (SubhikshaSf4851) [reply src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs]: @jsuarezruiz I have used FlyoutItems Count directly.

File: src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs (hunk 4 above)
Comment (SubhikshaSf4851) [reply src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs:128]: @jsuarezruiz I have used HashSet as per your suggestion

**Comment by bronteq** [comment]
@jsuarezruiz friendly ping

**Comment by bronteq** [comment]
@jsuarezruiz @PureWeen friendly ping

**Comment by bronteq** [comment]
@PureWeen @jfversluis friendly ping, this should be ready to merge

**Comment by jfversluis** [comment]
@bronteq did you download the artifacts and verified this fixes your issue?

**Comment by bronteq** [comment]
> @bronteq did you download the artifacts and verified this fixes your issue?

@jfversluis i followed this https://github.com/dotnet/maui/wiki/Testing-PR-Builds but i do not find nuget folder in the artifacts, probably because MAUI-public was not executed

I also tried this https://github.com/dotnet/maui/wiki/Nightly-Builds but i think that nightlies do not contain not merged PRs, this has the wrong behavior

**Comment by jfversluis** [comment]
@bronteq you're totally right, my bad! Triggered that one now, please let me know :)

**Comment by bronteq** [comment]
@jfversluis thank you so much, i can confirm that this PR solves the issue

**Review by jfversluis — APPROVED** [review]
