### PR TITLE
Translucent and Transparent NavigationBar on iOS

### LINKED ISSUE #17022: Can only ignore iOS Safe Area when navigation bar is hidden
### Description

Porting an Xamarin.Forms app to .NET MAUI, I found that the old safe area code doesn't work as expected in .NET MAUI. I found the recommendation to use `IgnoreSafeArea="True"` on the layout, however this didn't do anything until...
 
I did a repro in a blank app and hid the navigation bar. 

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="PlayItSUnsafe.MainPage"
             xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
             ios:Page.UseSafeArea="False"
             BackgroundColor="Red"
             Shell.NavBarIsVisible="False"
             >


        <Grid Background="#333333"
            IgnoreSafeArea="True"
            RowDefinitions="300,*"
            >
            <BoxView Grid.Row="0"
                BackgroundColor="MediumPurple"
                />
            
            <Image Source="dotnet_bot.png" />

            <Label Text="Hello, world!" Grid.Row="1"
            TextColor="White"
                HorizontalOptions="Center"
                VerticalOptions="Center" />
        </Grid>

</ContentPage>
```

[PlayItUnsafe.zip](https://github.com/dotnet/maui/files/12448689/PlayItUnsafe.zip)
Screenshot 2023-08-27 at 2 36 29 PM

This AppDelegate code should (used to) make the nav bar bg transparent to create this look.

```sharp
public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
    {
        base.FinishedLaunching(application, launchOptions);
            
        UINavigationBar.Appearance.SetBackgroundImage(new UIImage(), UIBarMetrics.Default);
        UINavigationBar.Appearance.ShadowImage = new UIImage();
        UINavigationBar.Appearance.BackgroundColor = UIColor.Clear;
        UINavigationBar.Appearance.TintColor = UIColor.White;
        UINavigationBar.Appearance.BarTintColor = UIColor.Clear;
        UINavigationBar.Appearance.Translucent = true;

        return true;
    }
```

The SmartHotel360 app uses FlyoutPage and the sample repro uses Shell. Both should work.

### Steps to Reproduce

run the sample from the zip and/or the repo linked. Show/hide the navigation bar. In both cases the content should be at the very top of the device screen, not at the bottom of the nav bar.

### Link to public reproduction project repository

https://github.com/davidortinau/SmartHotel360-Mobile/blob/upgrade-step-1/Source/SmartHotel.Clients/SmartHotel.Clients.iOS/AppDelegate.cs

### Version with bug

8.0.0-preview.7.8842
Also tested latest 7.0

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

16.4

### Did you find any workaround?

Not without abandoning the existing implementation with ToolbarItem and flyout menu button etc.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tj-devel709**
## Description of Change

On MAUI iOS, there are some issues with trying to create transparent and translucent UINavigationBars that were possible in Xamarin.Forms. With the changes in this PR, it is now possible to get the super cool styling of a transparent and translucent navbar on NavigationPage, Shell, and FlyoutPage. Because iOS 15 made some changes to the UINavigationBar, there were some differences in the code depending in the iOS version and I will provide screenshots from iOS 11.0 and iOS 17.0.

For the following examples, please note that `IgnoreSafeArea="True"`is set on the top-level grid in the contentpage.

### NavigationPage

When enabling transparency and translucent for the UINavigationBar in a NavigationPage, you'll want to make the NavigationPage's `BarBackgroundColor = Colors.Transparent` as well as calling `yourNavigationPage.On<iOS>().EnableTranslucentNavigationBar()` and `yourNavigationPage.On<iOS>().SetHideNavigationBarSeparator(true)`

<details>
<summary>

#### NavigationPage Images and Code Sample (click me!) 

</summary>

| iOS 17.0 | iOS 11.0 |
| -- | -- |
|  |  

**MainPage.xaml:**
```xaml
    <ContentPage
        xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        x:Class="Maui.Controls.Sample.MainPage"
        xmlns:local="clr-namespace:Maui.Controls.Sample"
        xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
        Title="Home"
        >
        <Grid IgnoreSafeArea="True" Background="#333333" RowDefinitions="300,*">
            <BoxView Grid.Row="0" Background="yellow" />
            <Image Source="dotnet_bot.png" />
            <Label Text="Hello, world!" Grid.Row="1"
                    TextColor="White"
                    HorizontalOptions="Center"
                    VerticalOptions="Center" />
        </Grid>
    </ContentPage>
```

**MauiProgram.cs**
```cs
    class App : Microsoft.Maui.Controls.Application
        {
            protected override Window CreateWindow(IActivationState activationState)
            {
                var navPage = new Microsoft.Maui.Controls.NavigationPage(new MainPage())
                {
                    BarBackgroundColor = Colors.Transparent,
                };
                navPage.On<iOS>().EnableTranslucentNavigationBar();
                navPage.On<iOS>().SetHideNavigationBarSeparator(true);
                return new Window(navPage);
            }
        }
```

</details> 

---

### FlyoutPage

Similar to the NavigationPage example above, you'll want to make the NavigationPage's `BarBackgroundColor = Colors.Transparent` as well as calling `yourNavigationPage.On<iOS>().EnableTranslucentNavigationBar()` and `yourNavigationPage.On<iOS>().SetHideNavigationBarSeparator(true)`. You will then set this navigationPage to the 'Detail' property of the FlyoutPage.

<details>
<summary>

#### FlyoutPage Images and Code Sample (click me!) 

</summary>

| iOS 17.0 | iOS 11.0 |
| -- | -- |
|  |  

**MainPage.xaml:**
```xaml
    <ContentPage
        xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        x:Class="Maui.Controls.Sample.MainPage"
        xmlns:local="clr-namespace:Maui.Controls.Sample"
        xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
        Title="Home"
        >
        <Grid IgnoreSafeArea="True" Background="#333333" RowDefinitions="300,*">
            <BoxView Grid.Row="0" Background="yellow" />
            <Image Source="dotnet_bot.png" />
            <Label Text="Hello, world!" Grid.Row="1"
                    TextColor="White"
                    HorizontalOptions="Center"
                    VerticalOptions="Center" />
        </Grid>
    </ContentPage>
```

**SandboxFlyout.cs**
```cs
using System;
using Microsoft.Maui.Controls;
using Microsoft.Maui.Controls.PlatformConfiguration;
using Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;
using Microsoft.Maui.Graphics;
namespace Maui.Controls.Sample
{
    public partial class SandboxFlyout : Microsoft.Maui.Controls.FlyoutPage
    {
        public SandboxFlyout()
        {
            InitializeComponent();
            var mainPage = new MainPage();
            var navigationPage = new Microsoft.Maui.Controls.NavigationPage(mainPage);
            navigationPage.BarBackgroundColor = Colors.Transparent;
            navigationPage.On<iOS>().SetHideNavigationBarSeparator(true);
            navigationPage.On<iOS>().EnableTranslucentNavigationBar();
            Flyout = new FlyPage();
            Detail = navigationPage;
        }
    }
}
```

</details> 

---

### Shell

Shell is a little different than the NavigationPage and Flyout Page. Because there is not an existing public property to set for Translucence, if you set `Shell.NavBarIsVisible="True"` and `Shell.BackgroundColor="Transparent"`, the Shell's navigationBar will now become transparent and translucent. 

<details>
<summary>

#### Shell Images and Code Sample (click me!) 

</summary>

| iOS 17.0 | iOS 11.0 |
| -- | -- |
|  |  

**MainPage.xaml:**
```xaml
<ContentPage
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Maui.Controls.Sample.MainPage"
    xmlns:local="clr-namespace:Maui.Controls.Sample"
    xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
    Title="Home"
    Shell.NavBarIsVisible="True"
    Shell.BackgroundColor="Transparent"
    >
    <Grid IgnoreSafeArea="True" Background="#333333" RowDefinitions="300,*">
        <BoxView Grid.Row="0" Background="yellow" />
        <Image Source="dotnet_bot.png" />
        <Label Text="Hello, world!" Grid.Row="1"
                TextColor="White"
                HorizontalOptions="Center"
                VerticalOptions="Center" />
    </Grid>
</ContentPage>
```

</details> 

---

## Testing
I added a UITest that adds a transparent and translucent UINavigationBar with the NavigationPage inside the Appium UITests below:

| UITest | 
| -- | 
| <video width="300" src="https://github.com/dotnet/maui/assets/50846373/703bf889-63c3-4eca-aed9-0ebf95cd0561"> 

### Issues Fixed

Fixes #17022

### CODE REVIEW

**Comment by AlleSchonWeg** [comment]
Hi @tj-devel709,
there are some problems with translucent and safe area : https://github.com/dotnet/maui/issues/9053 
Will this problems also be adressed?

**Comment by tj-devel709** [comment]
> Hi @tj-devel709, there are some problems with translucent and safe area : #9053 Will this problems also be adressed?

Hello @AlleSchonWeg! I would say that this PR probably does not affect the Large Titles transitions in the issue above but rather being able to have have visible content behind the UINavigationBar.

**Comment by AlleSchonWeg** [comment]
Okay,
this pull request reminded me of the linked issue. The combination of safe area, translucent, large tiles and LV/CV results in scrolling and snapping issues.

**Comment by davidortinau** [comment]
Before and after. Looking like what I expect!

Simulator Screenshot - iPhone 15 Pro - 2023-12-13 at 15 02 18
Simulator Screenshot - iPhone 15 Pro - 2023-12-13 at 14 56 21

File: src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs [hunk 1]
```diff
@@ -714,6 +720,24 @@ void UpdateBarBackground()
...
+		{
+			if (OperatingSystem.IsIOSVersionAtLeast(13) || OperatingSystem.IsMacCatalystVersionAtLeast(13))
+			{
+				var navBar = new UINavigationBarAppearance();
+				navBar.ConfigureWithTransparentBackground();
+				NavigationBar.CompactAppearance = NavigationBar.StandardAppearance = NavigationBar.ScrollEdgeAppearance = navBar;
+			}
+			else
+			{
+				NavigationBar.SetBackgroundImage(new UIImage(), UIBarMetrics.Default);
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs:733]: Can we consolidate this code with the same code in shell? It seems like it's pretty much the same?

File: src/Controls/samples/Controls.Sample.UITests/Issues/Issue17022.xaml.cs [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+{
+	Color _initialBarBackgroundColor;
+	bool _initialTranslucent;
+
+	public Issue17022()
+	{
+		InitializeComponent();
+	}
+
+	protected override void OnAppearing()
```
Comment (PureWeen) [inline src/Controls/samples/Controls.Sample.UITests/Issues/Issue17022.xaml.cs:21]: For this test can we push a test page modally? 

So push a NavigationPage modally and do the validation against that? This way we aren't modifying the test runner chrome?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs [hunk 3]
```diff
@@ -730,14 +730,19 @@ void ApplyTransparentBarBackground()
...
-				NavigationBar.BackgroundColor = UIColor.Clear;
-				NavigationBar.TintColor = UIColor.Clear;
-				NavigationBar.BarTintColor = UIColor.Clear;
+				SetTransparentNavigationBar (NavigationBar);
 			}		
 		}
 
+		internal static void SetTransparentNavigationBar (UINavigationBar navigationBar)
+		{
+			// navigationBar.SetBackgroundImage(new UIImage(), UIBarMetrics.Default);
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs]: should this still be commented out?

File: src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs [hunk 4]
```diff
@@ -730,14 +730,19 @@ void ApplyTransparentBarBackground()
...
-				NavigationBar.SetBackgroundImage(new UIImage(), UIBarMetrics.Default);
-				NavigationBar.ShadowImage = new UIImage();
-				NavigationBar.BackgroundColor = UIColor.Clear;
-				NavigationBar.TintColor = UIColor.Clear;
-				NavigationBar.BarTintColor = UIColor.Clear;
+				SetTransparentNavigationBar (NavigationBar);
 			}		
 		}
 
+		internal static void SetTransparentNavigationBar (UINavigationBar navigationBar)
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs:737]: can we move this to `NavigationPageExtensions`? 

Also can we move all the code related to setting the navbar into the Extentions method?

I think the iOS15+ code could also live inside the same method and then inside that method it does an operating system check?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs (hunk 4 above)
Comment (tj-devel709) [reply src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs]: I moved the non-iOS15 code to the NavigationPageExtensions. I'm not sure if moving the ios 15 code there works too well. The iOS 15 code uses the UINavigationBarAppearance and the older code uses UINavigationBar. I could do an overload but since there are other things that get set in the iOS 15 check and the code for the iOS 15 stuff is only a one-liner, I'm not sure if that'd be too helpful. What do you think?

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellNavBarAppearanceTracker.cs [hunk 5]
```diff
@@ -115,6 +122,16 @@ void UpdateiOS15NavigationBarAppearance(UINavigationController controller, Shell
 			if (titleColor != null)
 				navigationBarAppearance.TitleTextAttributes = new UIStringAttributes() { ForegroundColor = titleColor.ToPlatform() };
 
+			// if the BackgroundColor is set to transparent, let's apply translucence as well
+			// since we cannot call this directly in .NET 8
+			if (appearance.BackgroundColor == Colors.Transparent)
+			{
+				// save the shadow image
+				_defaultNavBarShadowImage = navBar.ShadowImage;
+				navigationBarAppearance.ConfigureWithTransparentBackground();
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellNavBarAppearanceTracker.cs:131]: from the description of ConfigureWithTransparentBackground it seems like you'd only call that if there's no alpha value

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/tests/UITests/snapshots/ios/Issue17022TestNewFlyoutPageGridTranslucentButton.png
Comment (jsuarezruiz) [inline src/Controls/tests/UITests/snapshots/ios/Issue17022TestNewFlyoutPageGridTranslucentButton.png:1]: Have the snapshots been generated on the server or locally? Must be generated on the CI server.

Comment (tj-devel709) [reply src/Controls/tests/UITests/snapshots/ios/Issue17022TestNewFlyoutPageGridTranslucentButton.png:1]: I generated the screenshots locally and moved them from the snapshot-diff to the snapshot directory. Are they different from the CI?

**Review by PureWeen — APPROVED** [review]

**Comment by Cybrosys** [comment]
Is it possible to achieve the same on Android, the layout doesn't extend in under the NavigationBar?
