### PR TITLE
[iOS] RadioButton throws CGContextSetLineWidth - Fix

### LINKED ISSUE #25273: RadioButtonGroup/RadioButton throw CGContextSetLineWidth error on iOS 18.0/18.1.
### Description

MACOS Sequoia (Version 15.0)
XCode : 16.0 (16A242d)
.NET MAUI 8.0 (.NET Maui workload listed versions:)
maui-ios         Manifext Version: 8.0.82/8.0.100   Installation Source: SDK 8.0.400
maui-android Manifext Version: 8.0.82/8.0.100   Installation Source: SDK 8.0.400
maui               Manifext Version: 8.0.82/8.0.100   Installation Source: SDK 8.0.400

(XAML code in page)
	<HorizontalStackLayout  RadioButtonGroup.GroupName="grp1" RadioButtonGroup.SelectedValue="{Binding grp1ans}">
		<RadioButton x:Name="grp1pass" Content="Pass" Value="Pass" />
		<RadioButton x:Name="grp1fail"   Content="Fail" Value="Fail" />
	</HorizontalStackLayout>

Compile and run on iOS (iPAD 10th Gen Emulator with iOS 18.0 and Physical iPAD with 18.0 and 18.1 throw errors) - you will notice errors in the Debug output log

When you navigate to the page with the above XAML snippet, iOS throws one error per each <RadioButton> element you have in the group to the  Debug.Output (ex.)
<timestamp/process omitted>... [Unknown process name] CGContextSetLineWidth: invalid line width: negative values are not allowed.
<timestamp/process omitted>... [Unknown process name] CGContextSetLineWidth: invalid line width: negative values are not allowed.

### Steps to Reproduce

1. Create sample -  .net maui project dotnet new maui -o mauisample
2. Add the snippet to the MainPage.xaml
     
...   
     <HorizontalStackLayout  RadioButtonGroup.GroupName="grp1" RadioButtonGroup.SelectedValue="{Binding grp1ans}">
		<RadioButton x:Name="grp1pass" Content="Pass" Value="Pass" />
		<RadioButton x:Name="grp1fail"   Content="Fail" Value="Fail" />
	</HorizontalStackLayout>
...

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18/ iOS 18.1 on iPAD and Emulator iPAD 10th Generation

### Did you find any workaround?

No workaround found.

### Relevant log output

<timestamp/process omitted>... [Unknown process name] CGContextSetLineWidth: invalid line width: negative values are not allowed.
<timestamp/process omitted>... [Unknown process name] CGContextSetLineWidth: invalid line width: negative values are not allowed.

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

The error occurred because the default value for Border.StrokeThickness was set to -1. Instead of changing this default to 0, I implemented a converter that ensures Border.StrokeThickness never receives negative values.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/25273

|Before|
|----|
|Screenshot 2024-10-26 at 15 19 01|

### CODE REVIEW

File: src/Controls/src/Core/RadioButton/RadioButton.cs [hunk 1]
```diff
@@ -459,7 +459,7 @@ static View BuildDefaultTemplate()
 
 			border.SetBinding(Border.StrokeProperty, static (RadioButton rb) => rb.BorderColor, source: RelativeBindingSource.TemplatedParent);
 			border.SetBinding(Border.StrokeShapeProperty, static (RadioButton rb) => rb.CornerRadius, source: RelativeBindingSource.TemplatedParent, converter: new CornerRadiusToShape());
-			border.SetBinding(Border.StrokeThicknessProperty, static (RadioButton rb) => rb.BorderWidth, source: RelativeBindingSource.TemplatedParent);
+			border.SetBinding(Border.StrokeThicknessProperty, static (RadioButton rb) => rb.BorderWidth, source: RelativeBindingSource.TemplatedParent, converter: new NonNegativeValueConverter());
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/RadioButton/RadioButton.cs:462]: Could you include a comment here explaining why use the converter (because default StrokeThickness value is -1)?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/RadioButton/RadioButton.cs (hunk 1 above)
Comment (kubaflo) [reply src/Controls/src/Core/RadioButton/RadioButton.cs:464]: Good idea. Done

**Review by jsuarezruiz — DISMISSED** [review]

File: src/Controls/src/Core/RadioButton/RadioButton.cs [hunk 2]
```diff
@@ -459,7 +459,9 @@ static View BuildDefaultTemplate()
 
 			border.SetBinding(Border.StrokeProperty, static (RadioButton rb) => rb.BorderColor, source: RelativeBindingSource.TemplatedParent);
 			border.SetBinding(Border.StrokeShapeProperty, static (RadioButton rb) => rb.CornerRadius, source: RelativeBindingSource.TemplatedParent, converter: new CornerRadiusToShape());
-			border.SetBinding(Border.StrokeThicknessProperty, static (RadioButton rb) => rb.BorderWidth, source: RelativeBindingSource.TemplatedParent);
+
+			// NonNegativeValueConverter ensures that StrokeThickness remains non-negative as the default value of -1 triggers a CGContextSetLineWidth error on iOS.
+			border.SetBinding(Border.StrokeThicknessProperty, static (RadioButton rb) => rb.BorderWidth, source: RelativeBindingSource.TemplatedParent, converter: new NonNegativeValueConverter());
```
Comment (PureWeen) [inline src/Controls/src/Core/RadioButton/RadioButton.cs:464]: Can this be fixed inside the Border control? 

So the border control could also check if this value is getting set to -1? 
This fix feels isolated to only fixes RB's use of Border vs border as a larger use case

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/RadioButton/RadioButton.cs (hunk 2 above)
Comment (kubaflo) [reply src/Controls/src/Core/RadioButton/RadioButton.cs]: done

**Review by PureWeen — APPROVED** [review]
