### PR TITLE
Fix for #5523 MauiWebView not loading local files on Windows

### LINKED ISSUE #5523: Html from Local File in Windows
### Description

Hello, local files are not displayed under windows. If you work like described in the documentation, local files are displayed in Android, but not in windows.

### Steps to Reproduce

Try it like described in the documentation

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Latest Win 11

### Did you find any workaround?

no

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by breenbob**
### Description of Change

Modified the MauiWebView control on Windows to map the Application AppX install directory to a virtual folder using the WebView2.CoreWebView.SetVirtualHostNameToFolderMapping method.

The existing implementation used the "ms-appx-web:///" URI scheme, which according to these issues is not being implemented in WebView2 for WinUI3.
https://github.com/microsoft/microsoft-ui-xaml/issues/1967
https://github.com/MicrosoftEdge/WebView2Feedback/issues/37

### Issues Fixed

- Maui WebView on Windows won't load local HTML files marked with Build action "MauiAsset". For me, the Maui GA release never loads even a simple HTML file via this method, and I have tested extensively on multiple Windows machines.

Fixes #5523

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=7672) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=7672) before we can accept your contribution.<br/><br/>:x: breenbob [sign now](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=7672)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/maui?pullRequest=7672) it.</sub>

**Comment by breenbob** [comment]
For the record I have noticed a related issue in WebView2 that still prevents this from working in all scenarios. In WinUI3 I've found that a complex client-side app will somtimes fail to load properly, no errors in console or failed network requests, but it behaves as those it has failed to load files being fetched via xhr requests.

After doing some digging, I discovered that this issue is resolved if you install Edge from the Beta channel, so I assume a fix for that is in the pipeline in WebView2 package and will be released in next cycle. I think what I've implemented here is independent of that and this shouldn't prevent it being merged?

**Comment by breenbob** [comment]
Noticed on original issue @jsuarezruiz added an [example](https://github.com/dotnet/maui/pull/5539/commits/d2de291403b9bbd54a54644bfaf1381059dc9370) of loading a local MauiAsset file that does work on Windows. Whilst this works, it requires code in the page codebehind to fetch the asset file contents and load as a string into the WebView. This PR would allow local files to work with no code required from the user, keeping it consistent with the other platforms.

**Comment by mattleibow** [comment]
I think so as the Package type will throw.

This can easily be tested by setting the WindowsPackageType to None and editing the commandName value in the launchSettings.json from msixPackage to project.

**Comment by breenbob** [comment]
Thanks @mattleibow & @Redth. I will make the changes and push another commit for review.

**Comment by breenbob** [comment]
@mattleibow Is there a way to check at runtime if the current Application is packaged or unpackaged? e.g. will this work?
```csharp
if (Package.Current == null)
{  //use AppContext.BaseDirectory }
```

**Comment by mattleibow** [comment]
That will throw an exception, so you catch that.

We do this in essentials: https://github.com/dotnet/maui/blob/main/src/Essentials/src/AppInfo/AppInfo.uwp.cs#L46-L64

**Comment by breenbob** [comment]
OK have made the changes for Unpackaged app support and successfully tested in both packaged/unpackaged samples. To test, I hijacked the credits page on the TestRunner project to show a local sample HTML page from /Resources/Raw folder, set as MauiAsset.
devenv_Tw0i9NnGGm
```xml
  <ItemGroup>
    ...
    <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
```
I also removed the Navigating event, as for some reason this was cancelling navigation and trying to open the URI provided in the external browser in the codebehind. This means the regular credits.html embedded resource in dotnet maui/main never loads, by the way.
image

Packaged app:
image
image

Unpackaged app:
image
image

Had some trouble getting the Unpackaged app to run following steps at your link as kept running into [this issue](https://github.com/microsoft/microsoft-ui-xaml/issues/7199) but finally got it work with the following configuration using an X64 build configuration (as can't run Any CPU in self contained mode):
```xml
  <PropertyGroup Condition="$(TargetFramework.Contains('-windows'))">
    <WindowsPackageType>None</WindowsPackageType>
    <AppxPackage>false</AppxPackage>
    <PublishAppxPackage>false</PublishAppxPackage>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
  </PropertyGroup>
```
@mattleibow can you review, please?

**Comment by mattleibow** [comment]
Come thing is iffy with this PR. Billions of changes.

I am wondering where it is supposed to go and maybe a merge happened from a wrong branch?

**Comment by breenbob** [comment]
@mattleibow Have tidied it up. I had done a rebase onto main and force pushed - force of habit - but didn't realise there was already a merge commit in there.

File: src/Core/src/Platform/Windows/MauiWebView.cs [hunk 1]
```diff
@@ -55,6 +67,14 @@ public async void LoadHtml(string? html, string? baseUrl)
 
 				await EnsureCoreWebView2Async();
 
+				if (mapBaseDirectory)
+				{
+					CoreWebView2.SetVirtualHostNameToFolderMapping(
+						LocalHostName,
+						ApplicationPath,
+						Web.WebView2.Core.CoreWebView2HostResourceAccessKind.Allow);
```
Comment (Eilon) [inline src/Core/src/Platform/Windows/MauiWebView.cs:75]: I think there is a potential security problem here.

Consider this scenario:

1. App uses MAUI WebView and calls `LoadHtml("some html blah blah", baseUrl: null);`
2. This causes MAUI to load the specified HTML, and enable local file mapping for the app, thus enabling the WebView to load arbitrary files from within the app contents. This part is pretty much fine, because it's generally assumed that if you're loading HTML yourself, you know what's in it, and that it's considered sanitized and safe
3. Later, the app calls some `Navigate` API on the WebView, causing the WebView to go to some other URL (say, `https://malware.example.com`
4. But because the mapping is still enabled, I believe this could cause the malicious site to load arbitrary content from within the app. I'm not sure what access the malicious site would have to the contents of what it loaded, but it could potentially cause unintended things to be invoked.

So, I think this change needs to be aware of navigation events and that the access/mapping be changed when the WebView navigates away from one of the "safe" locations.

**Review by Eilon — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Windows/MauiWebView.cs (hunk 1 above)
Comment (breenbob) [reply src/Core/src/Platform/Windows/MauiWebView.cs:75]: Fair point. I'll change it to hook into Navigation events, check target URL for the local hostname OnNavigating, and call CoreWebView2.ClearVirtualHostNameToFolderMapping(..) if attempting to navigate to any other URL. I guess I will need to re-enable that mapping on any attempt to navigate _back_ to the local host URL, too.

Comment (Eilon) [reply src/Core/src/Platform/Windows/MauiWebView.cs:75]: @breenbob yeah I think some logic like that would fix this. Thanks!

**Comment by MollsAndHersh** [comment]
@breenbob Quick question: will your fix also allow local .mp4 files to be loaded into a <video src="myvideo.mp4"></video> tags?  right now, I get nothing when trying to do this no matter where I put the .mp4 file into any standard location (ie: /resources/raw or /resources or /resources/assets, etc.) and setting file to use "mauiAsset".  Thoughts?  Basically what I've ended up doing is to loadup the webview with content I grab using the file system via stream reader into a HtmlWebViewSource... that html code has the referenced <video> element set the src="myvideo.mp4".  Unfortunately, I get nothing into the video player.

File: src/Core/src/Platform/Windows/MauiWebView.cs (hunk 1 above)
Comment (breenbob) [reply src/Core/src/Platform/Windows/MauiWebView.cs:95]: OK, have added this and tested. Looks like a) it works and b) it was needed.

To test I created a sample web page that I hosted somewhere, with the following body:
```html
<body>
    <h3>Test Page</h3>
    <p>I am a remote page.</p>
	<iframe src="https://appdir/simple.html" height="200" width="300" title="App Dir"></iframe>
    <br />
    <a href="https://appdir/simple.html">Link back</a>
</body>
```

I added a link to this URL to my simple.html test page.

With the code changes applied, my test page loads fine, as before. I click the link to the external site, that loads fine, but the iframe pointing to local appdir simple html file fails to load:
image

Good so far. I click the link to take me back to https://appdir/simple.html (i.e. so I am navigating forwards, not using back button) and it works fine.

I am conscious that there are potentially multiple calls to Map the virtual hostname now, as it is done in LoadUrl/Html and in NavigationStarted, but it doesn't seem to cause any issue, and unmapping once still unmaps. I had tried to track its status with a boolean flag but got a bit unwieldy, and WebView2 has no method to check what hosts are mapped.

Only peculiar thing I noticed, as you can see in this gif, is that when navigating _back_ both the NavigationFailed and NavigationSucceeded events fire in the `WebViewHandler.Windows.cs`. Failed first, with host name unknown, then succeeded. Actual navigation works fine.
devenv_yMvWWWanve

Out of curisoity, I tried loading the external page with the call to ClearVirtualHostNameToFolderMapping in NavigationStarted commented out, just to see, and the iframe is now able to load the appdir simple html page:
image

So clearing the virtual host mapping is 100% necessary. Hopefully good to go now?

**Comment by breenbob** [comment]
> @breenbob Quick question: will your fix also allow local .mp4 files to be loaded into `<video src="myvideo.mp4"></video>` tags? At the moment, I get nothing when trying to do this no matter where I put the .mp4 file into any standard location (ie: /resources/raw or /resources or /resources/assets, etc.) and setting file to use "mauiAsset". Thoughts? Basically what I've ended up doing is to loadup the webview with content I grab using the file system via stream reader into a HtmlWebViewSource... that html code has the referenced `<video>` element set the src="myvideo.mp4". Unfortunately, I get nothing into the video player.

@MollsAndHersh Yes this PR should allow that to succeed, provided the HTML file that is trying to load the video is also local, not just the video file itself. Also important is that the local HTML page doesn't have a <base /> element pointing to some other URL, as existing code in MauiWebView checks for this and won't map the app install directory for serving files if it finds it.

As I understand it, anything with MauiAsset set on its Build Action will copy to the root of the app directory on compilation, and so could be loaded in the WebView with a relative URL after this PR goes in. What you have to be careful with is if you have a folder structure for your files. If so, you should really use the /Resources/Raw folder to maintain that folder structure, by ensuring this entry is in your Maui app csproj:
```xml
<ItemGroup>
    <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
```
This copies anything from /Raw folder to the app installation root directory, but maintains the subfolder structure.

This PR has been tagged for SR2 release which has a target completion date of Wednesday, so with any luck, will be available soon!

File: src/Core/src/Platform/Windows/MauiWebView.cs [hunk 2]
```diff
@@ -1,15 +1,39 @@
...
+					CoreWebView2.ClearVirtualHostNameToFolderMapping(LocalHostName);
+				}
+			};
+		}
+
 		WebView2? _internalWebView;
 
-		const string LocalScheme = "ms-appx-web:///";
+		// Arbitrary local host name for virtual folder mapping
+		const string LocalHostName = "appdir";
```
Comment (Eilon) [inline src/Core/src/Platform/Windows/MauiWebView.cs:35]: I wonder if you wanted to add some more "Defense In Depth", you could have the local hostname be _random_, meaning that even if for some reason the hostname mapping was still present, no one would know what it was.

This is similar to what Chromium-based browsers (Chrome, Edge) do for extensions:

screenshot of randomized browser extension URL

You could have the hostname be something like `appdir_[50 random digits]`, and generated when the control loads.

I assume there's no reason for the app to ever care what the hostname is statically, right? If so, this behavior could go very far in mitigating any potential problems.

Comment (breenbob) [reply src/Core/src/Platform/Windows/MauiWebView.cs:35]: Hmm... I am curious what the default behaviour is on Android & iOS for this. Will run same test as above on those platforms to see...

In terms of whether the hostname needs to be constant, I don't believe it does. Even if for some reason someone needed it to be, they could just add a handler in their own app code anyway (as I have done temporarily to work around this issue), as you can map more than one virtual hostname in the WebView2. If they load an absolute URL the built-in mapping won't even kick in either.

But I'm happy to make these changes if you think it's necessary and will make this airtight.

Comment (Eilon) [reply src/Core/src/Platform/Windows/MauiWebView.cs:35]: Yeah good question about what do the other webviews do. They probably offer very little protection. Let's skip this idea for now and just stick with what you have.

**Review by Eilon — APPROVED** [review]
Pretty sure this looks good, but I'm not an expert on MAUI's WebView.

@rmarinho / @Redth - any concern about getting this PR in for SR2 for our partner?

**Review by mattleibow — APPROVED** [review]

**Comment by MollsAndHersh** [comment]
Thanks for getting back so quickly to me Bob.  I'm excited to try this out :)  I'm wondering exactly "how" I pull down the latest changes into my project so I get the new updated WebView code?  Do I just grab the newest Maui on a Nuget feed?  Should I just install the latest Visual Studio preview?  (Currently I'm on Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.3.0 Preview 2.0.)  

Or do I use Maui-Check?  

I'm sorta lost on the correct way forward.  Can you provide me any clues?  

Thanks.

**Comment by veikkoeeva** [comment]
Looking at the PR comments regarding security, would it be possible to modify the files locally and so consequently make the application load this modified file? That is, I wonder how the files are stored in the systems and signed in a way or another.

I know this is a more general question. I'm in fact trying to find documentation regarding this on:

1. Application stores files, any files.
2. Files distributed along the project, as here.

I would've actually asked about the same thing as @Eilon hadn't it been asked already. :)
