### PR TITLE
[MacCatalyst] Fix crash using Slider using Mac UIDeviceFamily

### LINKED ISSUE #8715: Catalyst app under Mac idiom crashes on start when using slider control
### Description

When attempting to use the Mac idiom by switching the UIDeviceFamily from 2 to 6 in the Info.plist in the Platforms/MacCatalyst folder you are unable to use the slider control. Attempting to include the slider control results in an Objective-C error being thrown.

### Steps to Reproduce

1. Create a new MAUI app in Visual Studio for Mac preview.
2. Open `Platforms/MacCatalyst/Info.plist` and change the `UIDeviceFamily` entry that reads 2, to 6
3. Open `MainPage.xaml` and add `<Slider></Slider>` after the last `<Button>` in the `<VerticalStackLayout>`
4. Run the application. Should receive error as included below in Relevant log output.

Project included.
[IdiomSliderRepro.zip](https://github.com/dotnet/maui/files/9103860/IdiomSliderRepro.zip)

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 12.4

### Did you find any workaround?

No.

### Relevant log output

```shell
Objective-C exception thrown.  Name: _UICatalystUnsupportedMacIdiomBehavior Reason: setMaximumTrackTintColor: is not supported on UISlider when running Catalyst apps in the Mac idiom. See UIBehavioralStyle for possible alternatives.
```

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix crash using Slider using Mac UIDeviceFamily.

### Issues Fixed

Fixes #8715

### CODE REVIEW

File: src/Core/src/Platform/iOS/SliderExtensions.cs [hunk 1]
```diff
@@ -31,7 +31,10 @@ public static void UpdateMinimumTrackColor(this UISlider uiSlider, ISlider slide
 		public static void UpdateMaximumTrackColor(this UISlider uiSlider, ISlider slider)
 		{
 			if (slider.MaximumTrackColor != null)
-				uiSlider.MaximumTrackTintColor = slider.MaximumTrackColor.ToPlatform();
+			{
+				if (uiSlider.TraitCollection.UserInterfaceIdiom != UIUserInterfaceIdiom.Mac)
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/SliderExtensions.cs:35]: `setMaximumTrackTintColor` is not supported on UISlider running on Catalyst.

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
Since this is a crash, should this be against net6.0?

**Comment by jsuarezruiz** [comment]
> Since this is a crash, should this be against net6.0?

You are right, changed the target branch.

**Review by rmarinho — APPROVED** [review]
