### PR TITLE
Fix for CollectionView with RefreshView when ObservableCollection<T>.Clear() throws System.ArgumentOutOfRangeException

### LINKED ISSUE #23868: ObservableCollection<T>.Clear() throws System.ArgumentOutOfRangeException
### Description

On iOS only (Android works without issue), ObservableCollection<T>.Clear() throws System.ArgumentOutOfRangeException in one specific scenario.  See **Steps to Reproduce** for details.

### Steps to Reproduce

There seem to be a few different ways to reproduce this issue:

**WAY 1** 
1. When the app opens use the refresh pulldown to load the initial monkeys
2. Tap the Clear button and you'll see the exception message in an alert
Note: I note that if you load the initial monkeys via the Get Monkeys button, the issue does not happen when I tap the Clear button.

**WAY 2**
1. When the app opens use the refresh pulldown to load the initial monkeys
2. Tap the Get Monkeys button to re-load the monkeys and you'll see the exception message in an alert

**WAY 3**
1. When the app opens use the Get Monkeys button to load the initial monkeys
2. Use the refresh pulldown to re-load the monkeys and you'll see the exception message in an alert

### Link to public reproduction project repository

https://github.com/tele-bird/mauipoc

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

happens on my iOS 17.5 and 17.4 sims, haven't tried on a real device

### Did you find any workaround?

I found no workaround

### Relevant log output

```shell
at System.Collections.Generic.List`1[[MonkeyFinder.Model.Monkey, MonkeyFinder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 index)\n   at System.Collections.ObjectModel.Collection`1[[MonkeyFinder.Model.Monkey, MonkeyFinder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].System.Collections.IList.get_Item(Int32 index)\n   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.ElementAt(Int32 index)\n   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.get_Item(Int32 index)\n   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.get_Item(NSIndexPath indexPath)\n   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetSizeForItem(NSIndexPath indexPath)\n   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewDelegator`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.ReorderableItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetSizeForItem(UICollectionView collectionView, UICollectionViewLayout layout, NSIndexPath indexPath)\n   at UIKit.UIScrollView.set_ContentOffset(CGPoint value) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UIScrollView.g.cs:line 563\n   at Microsoft.Maui.Controls.Handlers.Items.StructuredItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].UpdateHeaderFooterPosition()\n   at Microsoft.Maui.Controls.Handlers.Items.StructuredItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].HandleFormsElementMeasureInvalidated(VisualElement formsElement)\n   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnFormsElementMeasureInvalidated(Object sender, EventArgs e)\n   at Microsoft.Maui.Controls.VisualElement.InvalidateMeasureInternal(InvalidationTrigger trigger)\n   at Microsoft.Maui.Controls.VisualElement.OnIsVisibleChanged(Boolean oldValue, Boolean newValue)\n   at Microsoft.Maui.Controls.VisualElement.<>c.<.cctor>b__426_6(BindableObject bindable, Object oldvalue, Object newvalue)\n   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)\n   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)\n   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity)\n   at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget)\n   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__50_0()\n   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)\n   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.PropertyChanged(Object sender, PropertyChangedEventArgs args)\n   at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)\n   at System.Collections.ObjectModel.ObservableCollection`1[[MonkeyFinder.Model.Monkey, MonkeyFinder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnPropertyChanged(PropertyChangedEventArgs e)\n   at System.Collections.ObjectModel.ObservableCollection`1[[MonkeyFinder.Model.Monkey, MonkeyFinder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCountPropertyChanged()\n   at System.Collections.ObjectModel.ObservableCollection`1[[MonkeyFinder.Model.Monkey, MonkeyFinder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ClearItems()\n   at System.Collections.ObjectModel.Collection`1[[MonkeyFinder.Model.Monkey, MonkeyFinder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Clear()\n   at MonkeyFinder.ViewModel.MonkeysViewModel.ClearMonkeys() in /Users/phadley/Projects/GitHub/tele-bird/mauipoc2/mauipoc/MonkeyFinder/ViewModel/MonkeysViewModel.cs:line 98
```

### PR DESCRIPTION
**Pull request by SuthiYuvaraj**
### Root Cause:
The issue arises because the `UICollectionView`'s internal `_itemSource` becomes empty during pull-to-refresh, even though the `ItemsSource` in the controller still holds a valid count. This discrepancy causes an invalid state, where the `GetSizeForItem` method tries to access an index that no longer exists, resulting in a `System.ArgumentOutOfRangeException`. The issue was further compounded by the fact that `GetSizeForItem` was being called before the `CollectionChanged` event was triggered. This occurs because the `ContentOffset` is set during the pull-to-refresh operation, which prematurely triggers layout recalculations, leading to an invalid state.
 
### Description of Change:
The change ensures the `ElementAt` method safely accesses elements by validating the index with `(index >= 0 && index < list.Count)`. Using a ternary operator, it immediately returns the item or `-1` for invalid indices, preventing `System.ArgumentOutOfRangeException` and simplifying the logic for better reliability.

### Issues Fixed
Fixes #23868 

### Tested the behaviour in the following platforms
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac
 
###Output Video
Before Issue Fix | After Issue Fix |
|----------|----------|
|<video width="300" height="600" alt="Before Fix video" src="https://github.com/user-attachments/assets/a331f745-fa76-4318-9079-c384b3b00ec1">|<video width="300" height="600" alt="After Fix video" src="https://github.com/user-attachments/assets/6bf167ee-7c2a-4d20-bd29-e3d25b86199f">|

### CODE REVIEW

**Review by PureWeen — CHANGES_REQUESTED** [review]
Can you add the following test to this PR?

https://github.com/dotnet/maui/blob/0a96700f9cf9d28f59a54170c3ba2192974c783c/src/Compatibility/ControlGallery/src/Issues.Shared/Issue7678.cs#L22

When you copy the test over can you make sure to put it inside the XFIssue folder?

image


It looks like the ObservableItemSource changes were made in the following PR https://github.com/xamarin/Xamarin.Forms/pull/7711 and I worry that the fixes here are reverting those fixes a bit.

**Comment by praveenkumarkarunanithi** [comment]
> Can you add the following test to this PR?
> 
> https://github.com/dotnet/maui/blob/0a96700f9cf9d28f59a54170c3ba2192974c783c/src/Compatibility/ControlGallery/src/Issues.Shared/Issue7678.cs#L22
> 
> When you copy the test over can you make sure to put it inside the XFIssue folder?
> 
> image
> 
> It looks like the ObservableItemSource changes were made in the following PR [xamarin/Xamarin.Forms#7711](https://github.com/xamarin/Xamarin.Forms/pull/7711) and I worry that the fixes here are reverting those fixes a bit.

@PureWeen Regarding the changes to ObservableItemSource, I’d like to clarify that our fix now ensures functionality without modifying the Count property directly. Instead, we’ve implemented proper index validation to prevent exceptions when the list is empty or the index is out of range. This approach preserves the integrity of the existing logic and aligns with the previous changes introduced in PR [xamarin/Xamarin.Forms#7711](https://github.com/xamarin/Xamarin.Forms/pull/7711).
Additionally, we ensured the Issue7678 test case works as expected with the fix.

File: src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs [hunk 1]
```diff
@@ -279,7 +279,7 @@ internal int ItemsCount()
 		internal object ElementAt(int index)
 		{
 			if (_itemsSource is IList list)
-				return list[index];
+				return (index >= 0 && index < list.Count) ? list[index] : -1;
```
Comment (mattleibow) [inline src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs:282]: This is the `ElementAt` call, so should return the object or null, not -1 (index).

I also see further down it is also returning -1, which is also quite wrong.

I think this code was copied from the `IndexOf` method below. 

But also, if we are getting here, there is something else wrong - the collection view is rendering a non-existent item? How did it get to this point?

Comment (praveenkumarkarunanithi) [reply src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs]: @mattleibow You are correct. Previously, we returned -1 based on the existing else part value. Now, we have changed the return value from -1 to null. Returning null is a more appropriate approach when a requested item does not exist in the ElementAt method. Please let us know if you have any concerns or additional feedback regarding this change.

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
@PureWeen Should something still be done with your comment about putting things in the XFIssue folder?

**Review by PureWeen — APPROVED** [review]

**Comment by PureWeen** [comment]
@mattleibow we're good

Another issue/pr was created to cover that case
