### PR TITLE
Correctly propagate BindingContext to Border StrokeShape

### LINKED ISSUE #13699: CornerRadius on Border in .net 7
### Description

CornerRadius is not binding to Self for Border control.
This works on .net 6, and it use to work on .net 7 with Visual Studio 2022 17.3. I noticed the change in Visual Studio 2022 17.4.5

### Steps to Reproduce

Put in a border with this as the style:
```
                <Style x:Key="BorderStyle" TargetType="Border">
			<Setter Property="StrokeThickness" Value="5"/> 
			<Setter Property="StrokeShape">
				<RoundRectangle>
					<RoundRectangle.CornerRadius>
						<Binding Path="Height" Source="{RelativeSource Self}"/>
					</RoundRectangle.CornerRadius>
				</RoundRectangle>
			</Setter>
		</Style>
```

### Link to public reproduction project repository

none yet

### Version with bug

7.0 (current)

### Last version that worked well

6.0.312

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

no

### Relevant log output

_No response_

### LINKED ISSUE #13988: Border does not change rendering when modifying StrokeShape properties
### Description

XAML Hot Reload does not work when editing properties of Border.StrokeShape object, e.g. changing corner radius.

### Steps to Reproduce

1. New MAUI app.
2. Open MainPage.xaml and replace content of ContentPage element with
```
  <VerticalStackLayout>
    <Border x:Name="MyBorder" WidthRequest="400" HeightRequest="200"  HorizontalOptions="Start"
        Background="Yellow" Stroke="Red" StrokeThickness="2" Margin="4">
                <Border.StrokeShape>
                    <RoundRectangle CornerRadius="10" />
                </Border.StrokeShape>
      <Label x:Name="Txt" HeightRequest="30" HorizontalOptions="Start" Margin="10,2"/>
    </Border>
    <Button Text="Increase CornerRadius" Clicked="OnIncreaseCornerRadius" Margin="4" HorizontalOptions="Start" />
    <Button Text="Decrease CornerRadius" Clicked="OnDecreaseCornerRadius" Margin="4" HorizontalOptions="Start" />
  </VerticalStackLayout>
```
3. Open MainPage.xaml.cs and replace implementation with
```
public partial class MainPage : ContentPage
{
    public MainPage() => InitializeComponent();
    private void OnIncreaseCornerRadius(object sender, EventArgs e) => ChangeCornerRadius(10);
    private void OnDecreaseCornerRadius(object sender, EventArgs e) => ChangeCornerRadius(-10);
    private void ChangeCornerRadius(double delta)
    {
        RoundRectangle rr = (RoundRectangle)this.MyBorder.StrokeShape;
        double radius = Math.Max(0, rr.CornerRadius.TopLeft + delta);
        rr.CornerRadius = new CornerRadius(radius);
        this.Txt.Text = $"Border.StrokeShape is RoundRectangle with {radius} radius";
    }
}
```
4. Build and run
5. Click on "increase" and "decrease" buttons few times
**Expected**: rendering of border corners changes reflecting  new CornerRadius
**Actual**: rendering of border corners does not change

### Link to public reproduction project repository

n/a

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Win 22H2

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

This PR apply changes to correctly propagate the Border BindingContext to the StrokeShape.

Added a new sample in the Gallery where the Border StrokeShape bind the CornerRadius to the Border Width.
image
And unit test.
image

### Issues Fixed

Fixes #13699 
Fixes #13988

### CODE REVIEW

**Review by dustin-wojciechowski — APPROVED** [review]

File: src/Controls/src/Core/Border.cs [hunk 1]
```diff
@@ -37,7 +42,41 @@ public Thickness Padding
...
+						(bindable as Border)?.NotifyStrokeShapeChanges();
+				});
+
+		void NotifyStrokeShapeChanges()
+		{
+			var strokeShape = StrokeShape;
+
+			if (strokeShape is VisualElement visualElement)
+			{
+				SetInheritedBindingContext(visualElement, BindingContext);
```
[the remark this answers is not in the document]
Comment (mattleibow) [reply src/Controls/src/Core/Border.cs:63]: Do we need Parent AND SetInheritedBindingContext? Does not setting Parent automatically set the binding context? I am not sure, so just checking... Does the order matter?

File: src/Controls/src/Core/Border.cs [hunk 2]
```diff
@@ -224,5 +263,38 @@ void OnStrokeDashArrayChanged(object? sender, NotifyCollectionChangedEventArgs e
 		{
 			Handler?.UpdateValue(nameof(IBorderStroke.StrokeDashPattern));
 		}
+
+		class WeakStrokeShapeChangedProxy : WeakEventProxy<VisualElement, EventHandler>
```
Comment (mattleibow) [inline src/Controls/src/Core/Border.cs:267]: @jonathanpeppers Is this the right type and way to sue? Is there a more magical one that does not need a new type?

If there is no type now, is it possible to make one as I am sure I have seen a bunch of these "simple" proxies.

**Review by mattleibow — COMMENTED** [review]
Nice! Just got a question on the propagation and the use of the new proxy types.

File: src/Core/tests/UnitTests/Views/BorderTests.cs [hunk 3]
```diff
@@ -29,6 +30,23 @@ public void TestBorderPropagateBindingContext()
...
+			{
+				BindingContext = context
+			};
+
+			var strokeShape = new Rectangle();
+
+			parent.StrokeShape = strokeShape;
+
+			Assert.Same(context, ((Rectangle)parent.StrokeShape).BindingContext);
+		}
```
Comment (jonathanpeppers) [inline src/Core/tests/UnitTests/Views/BorderTests.cs:48]: This needs a test proving there is no memory leak now.

File: src/Controls/src/Core/Border.cs (hunk 2 above)
Comment (jonathanpeppers) [reply src/Controls/src/Core/Border.cs:267]: We should add a generic `WeakPropertyChangedProxy` like this one for `INotifyCollectionChanged`:

https://github.com/dotnet/maui/blob/57e186d16df649524d13def2220df62f700fa9b4/src/Controls/src/Core/Internals/WeakEventProxy.cs#L64

I didn't do that in my recent PRs, because they were subscribing to multiple custom events like `InvalidateGradientRequested`, etc.

We should make a generic proxy type for `INotifyPropertyChanged.PropertyChanged` that can be reused everywhere. Also  check if there are places to go ahead and use it.

**Review by jonathanpeppers — CHANGES_REQUESTED** [review]

File: src/Core/tests/UnitTests/Views/BorderTests.cs (hunk 3 above)
Comment (jonathanpeppers) [reply src/Core/tests/UnitTests/Views/BorderTests.cs:48]: This one had a good example: https://github.com/dotnet/maui/pull/13806

https://github.com/dotnet/maui/blob/9e5785a3c65f04ea7114b0c8c8e174c745045441/src/Controls/tests/Core.UnitTests/VisualElementTests.cs#L147-L160

We make sure that the `Clip` (the publisher) doesn't hold onto the `VisualElement` (the subscriber).

I would start adding one of these every time you see `+=`.

File: src/Controls/src/Core/Border.cs (hunk 2 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Border.cs]: Created a generic `WeakNotifyPropertyChangedProxy`.

File: src/Core/tests/UnitTests/Views/BorderTests.cs [hunk 4]
```diff
@@ -29,6 +32,55 @@ public void TestBorderPropagateBindingContext()
...
+		{
+			var strokeShape = (Shape)Activator.CreateInstance(type);
+			var reference = new WeakReference(new Border { StrokeShape = strokeShape });
+
+			await Task.Yield();
+			GC.Collect();
+			GC.WaitForPendingFinalizers();
+
+			Assert.False(reference.IsAlive, "Border should not be alive!");
+		}
```
Comment (jonathanpeppers) [inline src/Core/tests/UnitTests/Views/BorderTests.cs:82]: We should figure out why this is failing, I think it means we introduced a memory leak?

Reviewing the code I think something needs to unset this call:
```csharp
SetInheritedBindingContext(visualElement, BindingContext);
```

For example:

https://github.com/dotnet/maui/blob/917f4497a7df1416a57814e5945b8bb284211c3b/src/Controls/src/Core/VisualElement.cs#L310

File: src/Controls/src/Core/Border.cs (hunk 2 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Border.cs]: Also added some unit tests to validate the property changes and dispose the references. The Border stays alive after unsubscribe the proxy. So, need to review it, something else (apart from the brushes) keep the reference.

Comment (jonathanpeppers) [reply src/Controls/src/Core/Border.cs]: I think the problem might be: https://github.com/dotnet/maui/pull/13793#discussion_r1135598987

File: src/Core/tests/UnitTests/Views/BorderTests.cs (hunk 4 above)
Comment (jsuarezruiz) [reply src/Core/tests/UnitTests/Views/BorderTests.cs:100]: Found the leak, setting the Parent. Applying some changes.

**Review by jonathanpeppers — APPROVED** [review]

**Comment by jsuarezruiz** [comment]
Added sample to validate #13988
fix-13988

**Review by mandel-macaque — APPROVED** [review]

File: src/Controls/src/Core/Border.cs [hunk 5]
```diff
@@ -37,10 +49,86 @@ public Thickness Padding
...
+			}
+		}
 
 		public static readonly BindableProperty StrokeProperty =
-			BindableProperty.Create(nameof(Stroke), typeof(Brush), typeof(Border), null);
+			BindableProperty.Create(nameof(Stroke), typeof(Brush), typeof(Border), null,
+				propertyChanging: (bindable, oldvalue, newvalue) =>
+				{
+					if (newvalue is not null)
+						(bindable as Border)?.StopNotifyingStrokeChanges();
```
Comment (mattleibow) [inline src/Controls/src/Core/Border.cs:95]: Same here, nothing ever unsubs.

File: src/Controls/src/Core/Internals/WeakEventProxy.cs [hunk 6]
```diff
@@ -152,4 +152,4 @@ public override void Unsubscribe()
 			base.Unsubscribe();
 		}
 	}
-}
\ No newline at end of file
+}
```
Comment (mattleibow) [inline src/Controls/src/Core/Internals/WeakEventProxy.cs:155]: Can we revert this whitespace change?

File: src/Controls/src/Core/Border.cs [hunk 7]
```diff
@@ -37,10 +49,86 @@ public Thickness Padding
 		}
 
 		public static readonly BindableProperty StrokeShapeProperty =
-			BindableProperty.Create(nameof(StrokeShape), typeof(IShape), typeof(Border), new Rectangle());
+			BindableProperty.Create(nameof(StrokeShape), typeof(IShape), typeof(Border), new Rectangle(),
+				propertyChanging: (bindable, oldvalue, newvalue) =>
+				{
+					if (newvalue is not null)
+						(bindable as Border)?.StopNotifyingStrokeShapeChanges();
```
[the remark this answers is not in the document]
Comment (jonathanpeppers) [reply src/Controls/src/Core/Border.cs:56]: If this is wrong, can we add a test for this?
