### PR TITLE
[Android] Action mode menu doesn't disappear when switch on another tab - fix

### LINKED ISSUE #19831: Menu item is not disappear when switch on another tab
### Description

I have Flyout item with 2 Tabs. In Both Tab I created List View with Menu Items.
I Hold on list ITem and See context menu with menu items.
Now I click on second Tab
Menu Items are still showing

### Steps to Reproduce

Use attached repository.
1. Open App and long press any list Item to see context menu
2. click on second tab header and see second tab with own list items but with context menu opened in Top Bar

### Link to public reproduction project repository

https://github.com/andreykoniukh/MAuiManu

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 34

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/19831

|Before|After|
|--|--|
|<video src="https://github.com/dotnet/maui/assets/42434498/c99feb0c-802c-426b-bb3f-7b892187aaa9" width="300px"/>|<video src="https://github.com/dotnet/maui/assets/42434498/a606c034-ca90-4856-85a7-e2f4483e6e1f" width="300px"/>|

### CODE REVIEW

**Review by dustin-wojciechowski — DISMISSED** [review]

File: src/Controls/tests/UITests/Tests/Issues/Issue19831.cs [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+	{
+		this.IgnoreIfPlatforms(new TestDevice[] { TestDevice.iOS, TestDevice.Mac, TestDevice.Windows });
+
+		var rect = App.WaitForElement("Item1").GetRect();
+		var app = App as AppiumApp;
+
+		if (app is null)
+			return;
+
+		var actions = new TouchAction(app.Driver);
```
Comment (jsuarezruiz) [inline src/Controls/tests/UITests/Tests/Issues/Issue19831.cs:28]: This test requires changes, we are using now the latest appium version where TouchAction is deprecated. Must use `ActionSequence`. Can find several samples in the repo. Let me know if need help or want me to update it.
```
D:\a\_work\1\s\src\Controls\tests\UITests\Tests\Issues\Issue19831.cs(28,21): error CS0618: 'TouchAction' is obsolete: 'TouchAction is deprecated, please use W3C actions instead: http://appium.io/docs/en/commands/interactions/actions/' [D:\a\_work\1\s\src\Controls\tests\UITests\Controls.AppiumTests.csproj::TargetFramework=net8.0]
    1 Error(s)
```

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/UITests/Tests/Issues/Issue19831.cs (hunk 1 above)
Comment (kubaflo) [reply src/Controls/tests/UITests/Tests/Issues/Issue19831.cs]: Done!

File: src/Controls/tests/UITests/Tests/Issues/Issue19831.cs [hunk 2]
```diff
@@ -20,16 +21,29 @@ public void ActionModeMenuShouldNotBeVisibleAfterSwitchingTab()
 		this.IgnoreIfPlatforms(new TestDevice[] { TestDevice.iOS, TestDevice.Mac, TestDevice.Windows });
 
 		var rect = App.WaitForElement("Item1").GetRect();
-		var app = App as AppiumApp;
+	
+		PerformLongPress(rect);
```
Comment (PureWeen) [inline src/Controls/tests/UITests/Tests/Issues/Issue19831.cs:25]: Can you move this into `AppiumTouchActions` and setup an extension method inside `AppiumApp` so this is reuseable?

Comment (jsuarezruiz) [reply src/Controls/tests/UITests/Tests/Issues/Issue19831.cs]: Let me do it.

**Review by jsuarezruiz — APPROVED** [review]
