### PR TITLE
[iOS] Fix deselect item on CollectionView

### LINKED ISSUE #26187: [MAUI] Select items traces are preserved
### Description

[MAUI] 
Affected case: All test cases

### Steps to Reproduce

1. Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to iOS or MacCatalyst.
2. Click any categories EG: "C RefreshView "-> C1 or others.
3. Back to C1 you will see the C1 display gray
4. Back to categories, you will see the "C RefreshView" show gray too.

Actual Behavior:
Image
Expected Behavior:
Selection trace disappears and should not be retained
Image

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

Microsoft.Maui.Controls: 9.0.20-ci.main.24577.4
### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Microsoft.Maui.Controls: 9.0.20-ci.main.24573.3

### Affected platforms

iOS, macOS

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

We fixed the selection with "CollectionView SelectedItem binding on iOS" https://github.com/dotnet/maui/pull/25555 , but seems that introduced a regression where clearing the item was not working. 

BY calling the clear state also with. `PerformBatchUpdates`  after the layout is done seems to fix the issue. 

### Issues Fixed

Fixes #26187

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs [hunk 1]
```diff
@@ -55,7 +55,10 @@ internal void ClearSelection()
 
 			foreach (var index in selectedItemIndexes)
 			{
-				CollectionView.DeselectItem(index, true);
+				CollectionView.PerformBatchUpdates(null, _ =>
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs:58]: Should we just move the entire foreach loop into "PerformBatchUpdates? 

Also. I think this code won't quite work if selectedItemIndexes has multiple values because the index will keep changing since it's not locally captured.

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs (hunk 1 above)
Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs:58]: good call, let me improve that . This was really needed, was more when it was set to null, but I wanted to fix all uses of `CollectionView.DeselectItem`

Comment (PureWeen) [reply src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs:58]: I think this one still needs to be fixed yea?

The CV2 handler path was fixed but not this one.

Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs]: Yap ups!

**Comment by PureWeen** [comment]
- failing lanes are unrelated to these changes
