### PR TITLE
Enforce Width/Height for ContentView on Android

### LINKED ISSUE #4164: [Android] HeightRequest, WidthRequest, MinimumWidthRequest and MinimumHeightRequest are not respected by Contentview
### Description

When HeightRequest, WidthRequest, MinimumWidthRequest or MinimumHeightRequest are directly set to a ContentView the control does not respect them. Please, check the attached images that demonstrate how the control looks in iOS and how in Android when the above properties are set:

### iOS
Simulator Screen Shot - iPhone 8 - 2022-01-17 at 15 33 16

### **Android**
Screenshot 2022-01-17 at 15 35 23

[HelloMaui.zip](https://github.com/dotnet/maui/files/7882637/HelloMaui.zip)
 

### Steps to Reproduce

1. Open the attached project and run it.
2. Notice how the ContentView look on Android when HeightRequest, WidthRequest, MinimumWidthRequest and MinimumHeightRequest are set.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hartez**
ContentView on Android was sizing itself to its Content even when explicit Width/Height were provided. These changes make the backing control enforce the explicit and minimum Width/Height values.

These changes also make the backing view for Layouts respect explicit and minimum Width/Height values.

Fixes #4164

### CODE REVIEW

File: src/Core/tests/DeviceTests/Stubs/LayoutManagerStub.cs [hunk 1]
```diff
@@ -12,7 +12,7 @@ public Size ArrangeChildren(Rect bounds)
 
 		public Size Measure(double widthConstraint, double heightConstraint)
 		{
-			return new Size(widthConstraint, heightConstraint);
+			return new Size(widthConstraint - 1, heightConstraint - 1);
```
Comment (hartez) [inline src/Core/tests/DeviceTests/Stubs/LayoutManagerStub.cs:15]: The -1's here are just to keep the stub layout manager from accidentally making the Layout's explicit height/width tests from passing.

**Review by Redth — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]
