### PR TITLE
Revert #24222 and simply use `invalidate` instead of `postInvalidate`

### LINKED ISSUE #24882: [regression/8.0.99-ci.net8.24472.1] Invalidate Shadow Issue: VisualElement.Shadow property change no longer invalidates platform shadow
### Description

Changes to a control's "shadow property" or changes to the shadow's properties directly no longer invalidate the platforms shadow.

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.70 SR7

### Affected platforms

Android

### Affected platform versions

Android - All

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by albyrock87**
### Description of Change

#24222 broke reaction to shadow / clip changes.

This PR brings back the original code while replacing `postInvalidate` with `invalidate` to avoid countless scheduled invalidations considering that MAUI only operates on platform views through the main thread.

You can see more details in the issue's comments.

While CI regenerates the `aar`, we should commit the new `aar` once this is merged, or as part of this PR.
I've not included it for security reasons.

### Issues Fixed

Fixes #24882

### CODE REVIEW

**Comment by rmarinho** [comment]
cc @jonathanpeppers

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformContentViewGroup.java [hunk 1]
```diff
@@ -28,13 +28,12 @@ public PlatformContentViewGroup(Context context, AttributeSet attrs, int defStyl
 
     /**
      * Set by C#, determining if we need to call getClipPath()
+     * Intentionally invalidates the view in case clip changed
      * @param hasClip
      */
     protected final void setHasClip(boolean hasClip) {
-        if (this.hasClip != hasClip) {
```
Comment (jonathanpeppers) [inline src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformContentViewGroup.java:34]: Why do we remove the `if`? If the value for `hasClip` hasn't changed, why does it need to run `invalidate()`?

Does it actually need to be called in a different place in the stack? In .NET MAUI's C# layer, perhaps it would _know_ what changed?

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformWrapperView.java [hunk 2]
```diff
@@ -20,13 +20,12 @@ public PlatformWrapperView(Context context) {
 
     /**
      * Set by C#, determining if we need to call drawShadow()
+     * Intentionally invalidates the view in case shadow definition changed
      * @param hasShadow
      */
     protected final void setHasShadow(boolean hasShadow) {
-        if (this.hasShadow != hasShadow) {
```
Comment (jonathanpeppers) [inline src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformWrapperView.java:26]: Same question here.

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformContentViewGroup.java (hunk 1 above)
Comment (albyrock87) [reply src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformContentViewGroup.java:34]: @jonathanpeppers I've just done what you asked: revert your PR and use `invalidate` instead of `postInvalidate`.

That said:
- setting a boolean field value has very likely no impact on performance
- this method is being called from the C# layer when the `Clip` changes, that's why we always need to invalidate
  - calling it from C# would cause two JNI roundtrips for nothing

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformWrapperView.java (hunk 2 above)
Comment (albyrock87) [reply src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformWrapperView.java:26]: Same answer here :D

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformContentViewGroup.java (hunk 1 above)
Comment (jonathanpeppers) [reply src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformContentViewGroup.java:34]: > setting a boolean field value has very likely no impact on performance

Setting the field isn't the question, but the fact that `invalidate()` is called. Why do we need call `invalidate()` if `true` is set to `true`? or `false` set to `false`?

Comment (albyrock87) [reply src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformContentViewGroup.java:34]: Because the clip path or the shadow details like color, radius,... have changed.

Comment (albyrock87) [reply src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformContentViewGroup.java:34]: we should call these methods something like `invalidateShadow(bool willDrawShadow)`

Comment (jonathanpeppers) [reply src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformContentViewGroup.java:34]: If the clip path or shadow changes, should those be the things that call `invalidate()`?

**Review by jonathanpeppers — DISMISSED** [review]
If this fixes a new issue, changing `postInvalidate()` -> `invalidate()` will solve the performance issue from earlier.

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformContentViewGroup.java (hunk 1 above)
Comment (albyrock87) [reply src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformContentViewGroup.java:34]: The reason to not move `invalidate` call there is just to avoid two round trips on JNI. So this is just a naming problem in my opinion.

**Review by jsuarezruiz — DISMISSED** [review]

**Comment by jsuarezruiz** [comment]
LGTM, will include the new aar as part of this PR. Waiting build to complete.

**Review by PureWeen — APPROVED** [review]
