### PR TITLE
[C] Propagate Resource changes to Background

### LINKED ISSUE #13570: Referencing a dynamic color in a DataTrigger does not work.
### Description

When I define a Data Templateo change a color based and use either a DynamicResource to a color or a StaticResource to a Brush that itself uses a DynamicResource to a color, the color is not changed when I change the application's theme.

The Syles.Triggers is defined as follows: 
```
<Style.Triggers>
    <DataTrigger TargetType="Ellipse"
                Binding="{Binding IsChecked}"
                Value="True"
                >
        <Setter Property="StrokeThickness"
            Value="5"/>
        <Setter Property="Stroke"
            Value="{StaticResource RadioButtonCheckedBrush}"/>
    </DataTrigger>

    <DataTrigger TargetType="Ellipse"
                Binding="{Binding IsChecked}"
                Value="False"
                >
        <Setter Property="StrokeThickness"
            Value="2"/>
        <Setter Property="Stroke"
            Value="{StaticResource RadioButtonUncheckedBrush}"/>
    </DataTrigger>
</Style.Triggers>

```

The application's theme is changed as follows:
```
if (theme != _activeTheme)
{
    App.Trace(this, nameof(SetTheme), "ActiveTheme:{0}", theme);
    _activeTheme = theme;
    Application.Current.Resources.MergedDictionaries.Clear();
    Application.Current.Resources.MergedDictionaries.Add
    (   
        theme == AppTheme.Light ? LightTheme : DarkTheme
    );
}
```

### Steps to Reproduce

1: Create a Maui App, delete colors.xaml and styles.xaml
2: Implemented support for theme changing.
3: Define Colors for 'Checked' and 'Unchecked' in the Dark and Light theme xaml files.
4; Define associated Brushes in app.xaml.
5: Define a view model, MainPageViewModel and add a bool IsChecked property.  Raised a PropertyChanged event when the value changes.
6: Add a checkbox to the main page and bind it to an IsChecked property on the view model.
7: Add radio buttons or a Picker to allow changing the theme between Unspecified, Dark, Light.
8: Add an Ellipse to the main page and define a style that sets Stroke based on the IsChecked property.  Also define StrokeThickness to the DataTrigger to provide a secondary visual cue.

In the repro, I have defined the Ellipse examples followed by multiple Radio button groups:
RadioButton with control template
RadioButton with just a style
Custom RadioGroup with a style
Custom RadioGroup with a control template.

The 2 Ellipses should have the following colors based on Theme:
Fill: Dynamic Color
   Dark:- Checked=Crimson, Unchecked=AntiqueWhite, Fill=PrimaryBackgroundBrush
   Light: Checked=Blue, Unchecked=Green, Fill=PrimaryBackgroundBrush
Fill: Transparent 
   Dark:- Checked=Crimson, Unchecked=AntiqueWhite, Fill=Transparent
   Light: Checked=Blue, Unchecked=Green, Fill=Transparent

Use any of these to change the app's theme.
System - uses the system them - change the system them in the platform's Settings to see the issue
Dark - uses DarkTheme.xaml
Light - uses LightTheme.xaml

As you toggle through the various theme options, you will see the Ellipse control stop changing the stroke color when the theme changes.  I've confirmed via tracing propertyChanging and/or propertyChanged handlers, that the does not update via the DataTrigger.  

Also note that the Ellipse defined with a dynamic color, doesn't reliably update the fill color when the theme changes but does update when the checked state changes. I can't tell if this is an issue with my binding or the Ellipse shape itself. 

The custom RadioGroup/RadioItem controls works both the DataTrigger problem  and the Ellipse Fill problems as follows:

DataTrigger: remove the color from the DataTrigger and updating it explicitly in its propertyChanged handlers. See RadioItem.CheckColorProperty, UncheckedColorProperty, IsCheckedProperty, and UpdateCheckColor in RadioItem.cs. 
Ellipse Fill: Creates a custom drawable that only draws background and stroke; ignoring Fill.

Note that RequestedThemeChanged is not working on iOS with my implementation.  Toggling between Light/Dark on the sample app does illustrate the both the DataTrigger and Fill issues.

### Link to public reproduction project repository

https://github.com/DanTravison/ThemeSelector

### Version with bug

7.0.59/7.0.100

### Last version that worked well

Unknown

### Affected platforms

Android, Windows

### Affected platform versions

Android 30.0, Windows 10.0.17763.0, Pixel 5 Emulator 13.0/API 33, IPad Pro iOS 16.3, Galaxy Note 10+ Android 12,/API 31

### Did you find any workaround?

The only workaround I've found is to encapsulate the Ellipse in a parent control (RadioItem.cs), define the desired BindableProperty elements on the parent control and update the Ellipse's colors in code in the propertyChanged handlers of the related parent control properties.

### Relevant log output

_No response_

### LINKED ISSUE #18545: [regression/8.0.0] DynamicResource not working with gradients when switching themes at runtime
### Description

When using a DynamicResource to change colors between light and dark mode in a gradient - .NET 8 no longer works. This worked fine in .NET7. The background stays on the light theme version the whole time.

```
<Border.Background>
                    <LinearGradientBrush EndPoint="0,1">
                        <GradientStop Offset="0.1" Color="{DynamicResource GradientColorStart}" />
                        <GradientStop Offset="1.0" Color="{DynamicResource GradientColorEnd}" />
                    </LinearGradientBrush>
</Border.Background>
```

### Steps to Reproduce

1. Download repo
2. Press button and see issue - in dark mode the border should be purple and orange gradient.

### Link to public reproduction project repository

https://github.com/Zack-G-I-T/DynamicResourceNet8

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

Using AppThemeBinding with Light and Dark, but our current app has two theme files for Light and Dark Theme so we use the same color names for both files. It will be very tedious to add "Dark" version to all the colours.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change

[C] Propagate Resource changes to VE.Background. Do that also for VE.Shadow, Border.Stroke, Shape.Fill and Stroke

### Issues Fixed

- fixes #18545
- fixes #13570

### CODE REVIEW

File: src/Controls/src/Core/Border/Border.cs [hunk 1]
```diff
@@ -109,6 +109,9 @@ void NotifyStrokeChanges()
 				_strokeChanged ??= (sender, e) => OnPropertyChanged(nameof(Stroke));
 				_strokeProxy ??= new();
 				_strokeProxy.Subscribe(stroke, _strokeChanged);
+
+				OnParentResourcesChanged(this.GetMergedResources());
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Border/Border.cs:113]: Could we include a XAML Test covering these changes?

**Comment by gabsamples6** [comment]
Hi there, is there a chance to make a nightly build soon? thank you

**Review by jsuarezruiz — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]
