### PR TITLE
Title doesn't visible when set IsVisible to true of ShellContent

### LINKED ISSUE #19496: Setting Shell.FlyoutWidth causes problems on WinUI with changed values in binding context
### Description

I have an app, kind of like a webshop, where the number of items in the basket is shown as a badge in the left menu, which is a row of tiles in a MAUI Shell with flyout behaviour = 'Locked'. On Android and iOS, if the number of items changes, that is reflected in the menu. On WinUI, the label just seems to disappear, until I resize the window, then it comes back. I could nail it down to setting the Shell's FlyoutWidth.

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Change AppShell.xaml:
```
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MauiApp2.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiApp2"
    x:DataType="local:AppShell"
    x:Name="Shell"
    FlyoutBehavior="Locked"
    FlyoutBackgroundColor="Gray"
    FlyoutWidth="85"
    Title="MauiApp2">

    <Shell.Resources>
        <DataTemplate x:Key="CheckoutTemplate" x:DataType="FlyoutItem">
            <Label Text="{Binding Path=BindingContext.Counter, Source={x:Reference Name=Shell}}"
                   TextColor="White" />
        </DataTemplate>
    </Shell.Resources>

    <FlyoutItem Title="Home" Shell.ItemTemplate="{StaticResource CheckoutTemplate}">
        <ShellContent        
            ContentTemplate="{DataTemplate local:MainPage}"
            Route="MainPage" />
    </FlyoutItem>
</Shell>
```
3. Change the contents of the `AppShell` class:
```
        public AppShell() {
            BindingContext = this;
            InitializeComponent();
        }

        private int _counter;
        public int Counter { get => _counter; set { _counter = value; OnPropertyChanged(); } }
```
4. Add this line at the end of the MainPage.OnCounterClicked() method:
```
((AppShell)Shell.Current).Counter = count;
```
5. Run the app on Android and observe that clicking the button will update the menu item. On Windows, it initially shows a zero; after clicking, the label dissappears.
6. This does not happen when you remove the line `FlyoutWidth="85"` from AppShell.xaml

Windows:
winui0
winui1
Android:
android1

### Link to public reproduction project repository

https://github.com/Glorfindel83/MAUIBugReports/tree/main/WindowsShellFlyoutWidth

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Windows

### Affected platform versions

Windows 11 Pro, 22H2

### LINKED ISSUE #19783: ShellContent IsVisible="True" Does not display Title
### Description

The issue i have that at startup i must make invisible item 'Profile'. and after successful login in AppShell.xmal.cs i watch property change and trying to make visible 'Profile'. and it works except that Title="Profile" is not visible. It is blank. When guess and click on it, it brings proper template.

### Steps to Reproduce

!. Create Maui app. In AppShell.xaml add Flyout ShellContent Item like this:
<ShellContent x:Name="Profile"
              IsEnabled="True"
              Title="Profile" 
              ContentTemplate="{DataTemplate views:Profile}" />
and Button: 
 <Button x:Name="btnLogin" Text="Login" TextColor ="White" Clicked="btnLogin_Clicked" BorderColor="Green" BorderWidth="2" Margin="0,10"> 
</Button>
2.  in AppShell.xaml.cs after  InitializeComponent(); i set Profile.IsVisible =falce;
3. in Login Button control.:
private void btnLogin_Clicked(object sender, EventArgs e)
{
Profile.IsVisible =true;
  }

NOTE: it makes Profile Item visible, but Title="Profile" not. so that ShellContent item  is blank and i have to guess. where is it. Not sure how to make visible entire item.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

NO

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by NirmalKumarYuvaraj**
### Issue Details:
Title doesn't visible when set IsVisible to true of ShellContent on button click.
 
### Root Cause:
Without calling base.MeasureOverride, the ShellFlyoutItemView (or its content) was not measured properly by the layout system. As a result, it was  not sized at all, causing it to be invisible in the view.

### Description of Change:
Added a call to base.MeasureOverride(availableSize) to ensure that the internal measurement logic provided by the base class is executed before measuring the custom view.
 
**Tested the behavior in the following platforms.**
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac
 
### Issues Fixed:
 
Fixes #19783
Fixes #19496
 
### Screenshots
| Before Issue Fix | After Issue Fix |
|--|--|
|<image src="https://github.com/user-attachments/assets/c25718a2-8c35-41e1-b674-9e157be22b37">|<image src="https://github.com/user-attachments/assets/ac2d17c9-c018-4cae-bc7c-1613cf0f4e26">|

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Shell/Windows/ShellFlyoutItemView.cs [hunk 1]
```diff
@@ -117,7 +117,7 @@ void ShellElementPropertyChanged(object sender, PropertyChangedEventArgs e)
 						fe.Visibility = WVisibility.Visible;
 					}
 				}
-
+				base.MeasureOverride(availableSize);
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Shell/Windows/ShellFlyoutItemView.cs:120]: @Foda This reminds me of something you were looking at recently?

Comment (Foda) [reply src/Controls/src/Core/Handlers/Shell/Windows/ShellFlyoutItemView.cs:120]: Yeah, similar to https://github.com/dotnet/maui/pull/25479

I'm curious if we should just have remove the measure override. I don't really see the point of it

**Review by PureWeen — CHANGES_REQUESTED** [review]
@NirmalKumarYuvaraj can you look at just pulling @Foda 's PR into this one?

https://github.com/dotnet/maui/pull/25479

Since you've added tests here and we can see if that also resolves the issue?

Also, can you confirm if this also fixes
https://github.com/dotnet/maui/issues/19496

**Review by Foda — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]

**Comment by PureWeen** [comment]
- failing test unrelated
