### PR TITLE
[Blazor] Initial support for configuring the underlying Web view settings

### LINKED ISSUE #5512: BlazorWebView's AllowSingleSignOnUsingOSPrimaryAccount defaults to false
### Description

This is to follow up on https://github.com/dotnet/maui/pull/5086#issuecomment-1073140745

WebView2 has this setting that controls whether AAD single-sign-on can be used within the webview. It's hard to think of a reason why developers would *not* want this to be possible, and in fact, the WebView2 team says [see here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2240#issuecomment-1061017391):

> I believe this is "False" by default because it was "False" when we created the API and we didn't want to create app compatibility problems with a feature suddenly turning on. It can also be surprising to devs and users to be using a control and already be signed in without user action. There shouldn't be downsides to using this API. Thanks!

Given that this only defaults to false for back-compat, and we don't have a back-compat requirement since we haven't shipped the first stable version yet, shouldn't we have it default to true in `BlazorWebView`? This would streamline the SSO dev experience. Moreover, if we don't do this, then we probably do have to add some API for it since there's no known way to set it to true manually currently.

**UPDATE: My guess is what we really should do is ensure that, for all platforms, there's a way to configure the `CoreWebView2Environment` arbitrarily at the right point during initialization. We're not going to be able to keep up with all the different possible options there are, or might arise in the future.**

### Steps to Reproduce

.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by javiercn**
### Description of Change

Adds an event that can be used to configure the underlying platform Web View implementation settings. The initial commit covers Windows, with Mac and Android to be added later on if needed

### Issues Fixed

Fixes #5512

### CODE REVIEW

File: src/BlazorWebView/src/Maui/IBlazorWebView.cs [hunk 1]
```diff
@@ -31,6 +31,12 @@ public interface IBlazorWebView : IView
 		/// </summary>
 		event EventHandler<UrlLoadingEventArgs>? UrlLoading;
 
+		/// <summary>
+		/// Allows customizing how links are opened.
+		/// By default, opens internal links in the webview and external links in an external app.
+		/// </summary>
```
Comment (Eilon) [inline src/BlazorWebView/src/Maui/IBlazorWebView.cs:37]: Wrong comment.

File: src/BlazorWebView/src/Wpf/BlazorWebView.cs [hunk 2]
```diff
@@ -57,6 +57,15 @@ public class BlazorWebView : Control, IAsyncDisposable
 			name: nameof(UrlLoading),
 			propertyType: typeof(EventHandler<UrlLoadingEventArgs>),
 			ownerType: typeof(BlazorWebView));
+
+		/// <summary>
+		/// The backing store for the <see cref="UrlLoading"/> property.
```
Comment (Eilon) [inline src/BlazorWebView/src/Wpf/BlazorWebView.cs:62]: Fix comment

File: src/BlazorWebView/src/Wpf/BlazorWebView.cs [hunk 3]
```diff
@@ -117,6 +126,16 @@ public EventHandler<UrlLoadingEventArgs> UrlLoading
 			set => SetValue(UrlLoadingProperty, value);
 		}
 
+		/// <summary>
+		/// Allows customizing how links are opened.
```
Comment (Eilon) [inline src/BlazorWebView/src/Wpf/BlazorWebView.cs:130]: Fix comment

**Review by Eilon — COMMENTED** [review]
Preliminary approval. Code looks great, exactly like what we discussed. Just a few wrong comments, and then waiting for non-Windows implementation.

File: src/BlazorWebView/src/Maui/IBlazorWebView.cs (hunk 1 above)
Comment (javiercn) [reply src/BlazorWebView/src/Maui/IBlazorWebView.cs:36]: done

**Comment by javiercn** [comment]
@Eilon 🆙 📅

File: src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs [hunk 4]
```diff
@@ -99,6 +99,10 @@ private void StartWebViewCoreIfPossible()
 				VirtualView.JSComponents,
 				hostPageRelativePath);
 
+			var args = new BlazorWebViewInitializingEventArgs();
+			((BlazorWebView)VirtualView).NotifyBlazorWebViewInitializing(args);
+			args.OnWebViewInitialized?.Invoke(PlatformView);
```
Comment (Eilon) [inline src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs:104]: I was about to say that it's sad that for Android we don't give any special settings access. It seems on Android we pre-set the settings "very early" so there's nothing to give here. But reading the Android WebView docs, it seems likely that the user can set the settings directly on the WebView we provide here to update settings after it's been created.

E.g. these properties on the settings all seem to be settable once it's running: https://developer.android.com/reference/android/webkit/WebSettings

But, I haven't tried it. I also can't think of any reasonable alternative if this somehow isn't the case.

File: src/BlazorWebView/src/SharedSource/BlazorWebViewInitializingEventArgs.cs [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+		/// </summary>
+		public CoreWebView2EnvironmentOptions EnvironmentOptions { get; set; }
+#endif
+
+#if WINDOWS
+		/// <summary>
+		/// Gets or sets a function that will be invoked once the web view has been initialized with
+		/// the default values to allow further configuring additional options.
+		/// </summary>
+		public Action<WebView2Control> OnWebViewInitialized { get; set; }
```
Comment (Eilon) [inline src/BlazorWebView/src/SharedSource/BlazorWebViewInitializingEventArgs.cs:48]: The more I look at this, I feel it's weird to have an event on an event args. Why not have two events, one for before, and one for after? Especially for platforms like Android where there is no "before" at all. You have to hook it up just to set up an after event, and then put your real code in the after event. I would have InitializINGEventArgs and InitializEDEventArgs with matching events. For some platforms the args might be quite empty for now (because there's no args to provide), but in the future of course we might add something. So that way the events are consistent on all platforms, even though the event args are quite different (which is already the case in this PR, which I think is totally fine).

**Review by Eilon — CHANGES_REQUESTED** [review]

File: src/BlazorWebView/src/SharedSource/BlazorWebViewInitializingEventArgs.cs (hunk 5 above)
Comment (javiercn) [reply src/BlazorWebView/src/SharedSource/BlazorWebViewInitializingEventArgs.cs:48]: That's fair, I don't feel strongly about it, so I think I'll change it for a pair of events.

File: src/Templates/src/templates/maui-blazor/MauiProgram.cs [hunk 6]
```diff
@@ -16,9 +16,11 @@ public static MauiApp CreateMauiApp()
 			});
 
 		builder.Services.AddMauiBlazorWebView();
+//-:cnd:noEmit
 #if DEBUG
 		builder.Services.AddBlazorWebViewDeveloperTools();
 #endif
+//+:cnd:noEmit
```
Comment (javiercn) [inline src/Templates/src/templates/maui-blazor/MauiProgram.cs:23]: This change is unrelated but I found it when I was testing something else using the Blazor template. The two additions prevent the directives from being processed by the templating engine.

File: src/BlazorWebView/src/SharedSource/BlazorWebViewInitializingEventArgs.cs (hunk 5 above)
Comment (javiercn) [reply src/BlazorWebView/src/SharedSource/BlazorWebViewInitializingEventArgs.cs]: Switch to using 2 separate events

File: src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs [hunk 7]
```diff
@@ -99,6 +99,12 @@ private void StartWebViewCoreIfPossible()
 				VirtualView.JSComponents,
 				hostPageRelativePath);
 
+			((BlazorWebView)VirtualView).NotifyBlazorWebViewInitializing(new BlazorWebViewInitializingEventArgs());
```
Comment (javiercn) [inline src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs:102]: There's no much point in us firing this event, but it would be weird if we didn't. I don't think there's anything a user can do for Android here as there is no context passed in.

Comment (Eilon) [reply src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs:102]: I definitely think we should raise the event consistently on every platform. The user might just have their own startup code they want to run "at that time" even if it's not related to the BlazorWebView implementation. Plus, in the future we might have something to pass in here.

File: src/BlazorWebView/src/Maui/IBlazorWebView.cs [hunk 8]
```diff
@@ -31,6 +31,16 @@ public interface IBlazorWebView : IView
 		/// </summary>
 		event EventHandler<UrlLoadingEventArgs>? UrlLoading;
 
+		/// <summary>
+		/// Allows customizing the web view configuration before it is created.
```
Comment (Eilon) [inline src/BlazorWebView/src/Maui/IBlazorWebView.cs:35]:
```suggestion
		/// Raised before the web view is initialized. On some platforms this enables customizing the web view configuration.
```

File: src/BlazorWebView/src/Maui/IBlazorWebView.cs [hunk 9]
```diff
@@ -31,6 +31,16 @@ public interface IBlazorWebView : IView
...
+		/// </summary>
+		event EventHandler<BlazorWebViewInitializingEventArgs>? BlazorWebViewInitializing;
+
+		/// <summary>
+		/// Allows customizing the web view configuration after it has been created but before any component has been rendered.
```
Comment (Eilon) [inline src/BlazorWebView/src/Maui/IBlazorWebView.cs:40]:
```suggestion
		/// Raised after the web view is initialized but before any component has been rendered. The event arguments provide the instance of the platform-specific web view control.
```

File: src/BlazorWebView/src/SharedSource/BlazorWebViewInitializedEventArgs.cs [hunk 10]
```diff
@@ -0,0 +1,46 @@
...
+	/// <summary>
+	/// Allows configuring the underlying web view after it has been initialized.
+	/// </summary>
+	public partial class BlazorWebViewInitializedEventArgs : EventArgs
+	{
+#nullable disable
+#if WINDOWS
+		/// <summary>
+		/// Gets or sets a function that will be invoked once the web view has been initialized with
+		/// the default values to allow further configuring additional options.
```
Comment (Eilon) [inline src/BlazorWebView/src/SharedSource/BlazorWebViewInitializedEventArgs.cs:29]:
```suggestion
		/// Gets the <see cref="WebView2Control"/> instance that was initialized.
```

File: src/BlazorWebView/src/SharedSource/BlazorWebViewInitializedEventArgs.cs [hunk 11]
```diff
@@ -0,0 +1,46 @@
...
+		/// </summary>
+		public WebView2Control WebView { get; internal set; }
+#elif ANDROID
+		/// <summary>
+		/// Gets or sets a function that will be invoked once the web view has been initialized with
+		/// the default values to allow further configuring additional options.
```
Comment (Eilon) [inline src/BlazorWebView/src/SharedSource/BlazorWebViewInitializedEventArgs.cs:35]:
```suggestion
		/// Gets the <see cref="AWebView"/> instance that was initialized.
```

File: src/BlazorWebView/src/SharedSource/BlazorWebViewInitializedEventArgs.cs [hunk 12]
```diff
@@ -0,0 +1,46 @@
...
+		/// </summary>
+		public AWebView WebView { get; internal set; }
+#elif MACCATALYST || IOS
+		/// <summary>
+		/// Gets or sets a function that will be invoked once the web view has been initialized with
```
Comment (Eilon) [inline src/BlazorWebView/src/SharedSource/BlazorWebViewInitializedEventArgs.cs:40]:
```suggestion
		/// Gets the <see cref="WKWebView"/> instance that was initialized.
```

File: src/BlazorWebView/src/SharedSource/BlazorWebViewInitializedEventArgs.cs [hunk 13]
```diff
@@ -0,0 +1,46 @@
...
+#elif IOS || MACCATALYST
+using WebKit;
+#endif
+
+namespace Microsoft.AspNetCore.Components.WebView
+{
+	/// <summary>
+	/// Allows configuring the underlying web view after it has been initialized.
+	/// </summary>
+	public partial class BlazorWebViewInitializedEventArgs : EventArgs
```
Comment (Eilon) [inline src/BlazorWebView/src/SharedSource/BlazorWebViewInitializedEventArgs.cs:23]:
```suggestion
	public class BlazorWebViewInitializedEventArgs : EventArgs
```

File: src/BlazorWebView/src/SharedSource/BlazorWebViewInitializedEventArgs.cs [hunk 14]
```diff
@@ -0,0 +1,46 @@
...
+	{
+#nullable disable
+#if WINDOWS
+		/// <summary>
+		/// Gets or sets a function that will be invoked once the web view has been initialized with
+		/// the default values to allow further configuring additional options.
+		/// </summary>
+		public WebView2Control WebView { get; internal set; }
```
Comment (Eilon) [inline src/BlazorWebView/src/SharedSource/BlazorWebViewInitializedEventArgs.cs:31]: Not a fan that the setter is internal. That means no one else can create a meaningful instance of this args type. While surely not common, it would mean you couldn't easily write a unit test for your event handler because you can't construct this event args.

Could we add ctor's for each of these? (Yes, I know it's not pretty to have 1 new constructor for each, but I think it's the right thing to do.)

File: src/BlazorWebView/src/SharedSource/BlazorWebViewInitializingEventArgs.cs [hunk 15]
```diff
@@ -0,0 +1,48 @@
...
+#elif IOS || MACCATALYST
+using WebKit;
+#endif
+
+namespace Microsoft.AspNetCore.Components.WebView
+{
+	/// <summary>
+	/// Allows configuring the underlying web view when the application is initializing.
+	/// </summary>
+	public partial class BlazorWebViewInitializingEventArgs : EventArgs
```
Comment (Eilon) [inline src/BlazorWebView/src/SharedSource/BlazorWebViewInitializingEventArgs.cs:22]:
```suggestion
	public class BlazorWebViewInitializingEventArgs : EventArgs
```

File: src/BlazorWebView/src/SharedSource/BlazorWebViewInitializingEventArgs.cs [hunk 16]
```diff
@@ -0,0 +1,48 @@
...
+		public string UserDataFolder { get; set; }
+
+		/// <summary>
+		/// Gets or sets the environment options for the <see cref="WebView2Control"/>.
+		/// </summary>
+		public CoreWebView2EnvironmentOptions EnvironmentOptions { get; set; }
+
+#elif MACCATALYST || IOS
+		/// <summary>
+		/// Gets or sets the configuration web view configuration.
```
Comment (Eilon) [inline src/BlazorWebView/src/SharedSource/BlazorWebViewInitializingEventArgs.cs:43]: Fix comment. Not sure what you intended.

File: src/BlazorWebView/src/Wpf/BlazorWebView.cs [hunk 17]
```diff
@@ -57,6 +57,23 @@ public class BlazorWebView : Control, IAsyncDisposable
 			name: nameof(UrlLoading),
 			propertyType: typeof(EventHandler<UrlLoadingEventArgs>),
 			ownerType: typeof(BlazorWebView));
+
+		/// <summary>
+		/// The backing store for the <see cref="BlazorWebViewInitializing"/> property.
```
Comment (Eilon) [inline src/BlazorWebView/src/Wpf/BlazorWebView.cs:62]:
```suggestion
		/// The backing store for the <see cref="BlazorWebViewInitializing"/> event.
```

File: src/BlazorWebView/src/Wpf/BlazorWebView.cs [hunk 18]
```diff
@@ -57,6 +57,23 @@ public class BlazorWebView : Control, IAsyncDisposable
...
+		/// </summary>
+		public static readonly DependencyProperty BlazorWebViewInitializingProperty = DependencyProperty.Register(
+			name: nameof(BlazorWebViewInitializing),
+			propertyType: typeof(EventHandler<BlazorWebViewInitializingEventArgs>),
+			ownerType: typeof(BlazorWebView));
+
+		/// <summary>
+		/// The backing store for the <see cref="BlazorWebViewInitialized"/> property.
```
Comment (Eilon) [inline src/BlazorWebView/src/Wpf/BlazorWebView.cs:70]:
```suggestion
		/// The backing store for the <see cref="BlazorWebViewInitialized"/> event.
```

And since you're here, can you fix the doc comment for the UrlLoading backing event too?

**Review by Eilon — CHANGES_REQUESTED** [review]

File: src/BlazorWebView/src/SharedSource/BlazorWebViewInitializingEventArgs.cs (hunk 16 above)
Comment (javiercn) [reply src/BlazorWebView/src/SharedSource/BlazorWebViewInitializingEventArgs.cs:43]:
```suggestion
		/// Gets or sets the web view <see cref="WKWebViewConfiguration"/>.
```

File: src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs (hunk 7 above)
Comment (javiercn) [reply src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs:102]: That sounds good, I'll leave it as is then so that we can add stuff in the future if needed.

File: src/BlazorWebView/src/SharedSource/BlazorWebViewInitializedEventArgs.cs (hunk 14 above)
Comment (javiercn) [reply src/BlazorWebView/src/SharedSource/BlazorWebViewInitializedEventArgs.cs:30]: Could we add the constructor once we need it?

I'm skeptical of people writing unit tests involving this component and I would like to see a concrete scenario first.

Comment (Eilon) [reply src/BlazorWebView/src/SharedSource/BlazorWebViewInitializedEventArgs.cs:30]: I think this is an anti-pattern but I don't have any other strong argument for it. It's very odd to have a type no one can construct. I won't block on this.

**Review by Eilon — APPROVED** [review]
