### PR TITLE
[iOS] Fix Entry Next Keyboard Button Finds Next TextField 

### LINKED ISSUE #11702: [iOS] Entry field Enter does not always move to next field
### Description

We fix this behavior for [`Android`](https://github.com/dotnet/maui/pull/11386) but iOS doesn't provide anything out of the box for this. With `XF` this was added into `iOS` after we implemented `TabIndex` so it was just piggy backing off of `TabIndex`. The problem with `TabIndex` is that it completely broke accessibility if you used it anywhere in your entire app, so we need to find an approach here that's less of a sledgehammer. 

### Steps to Reproduce

- Add two entries to a `VerticalStackLayout`
- Set the "ReturnType" to "Next" 

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

Call focus yourself after `Completed` has fired. 

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tj-devel709**
### Description of Change

This PR ports over some of the IQKeyboardManager code found [here](https://github.com/hackiftekhar/IQKeyboardManager/tree/09d22c087732b02d4fb594c7bb61502bf7bb2378) that was written in Swift. With these changes, on iOS, if we are inside an Entry control that has the 'ReturnType' as 'Next', we will go to the next available Entry, Editor, or SearchBar that is eligable (Enabled/Editable, not transparent, not hiddlen, and not inside a UIAlertView).

Small demo here:

https://user-images.githubusercontent.com/50846373/210608115-c23be175-0ff2-4185-b1b0-94b4f2f1223e.mov

Xaml for the demo [here](https://gist.github.com/tj-devel709/fec633893417632f50c28cb2982751fc).

Thanks for the pointers @PureWeen!

A [spec](https://github.com/dotnet/maui/issues/12968) that contains ideas for providing a Visual Ordering in the future for iOS, bringing this Logical ordering sort to Android, and a way for customers to decide which type of ordering they would prefer.

### Issues Fixed

Fixes #11702

### CODE REVIEW

File: src/Core/src/Platform/iOS/KeyboardAutoManager.cs [hunk 1]
```diff
@@ -0,0 +1,140 @@
...
+		while (curView.Superview is not null)
+		{
+			curView = curView.Superview;
+		}
+
+		return curView;
+	}
+
+	// Find all of the eligible UITextFields and UITextViews inside this view
+	internal static List<UIView> GetDeepResponderViews(UIView view)
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/KeyboardAutoManager.cs:52]: One thing to note for folks reviewing this PR.  The implementation in XF was similar-ish. Whenever you hit "Next" it would build the entire TabIndex tree from every element on the screen. So, this hierarchical search isn't super different than what we were doing in XF.

Comment (PureWeen) [reply src/Core/src/Platform/iOS/KeyboardAutoManager.cs:75]: For .NET8 we are but this is a big complaint area right now for .NET7 and people migrating for Forms 

So, we will most likely backport a portion of this for .NET7 and then the API for .NET8 is to make it configurable

File: src/Core/src/Platform/iOS/KeyboardAutoManager.cs [hunk 2]
```diff
@@ -0,0 +1,162 @@
...
+			if (alertViewController is UIAlertController)
+				return true;
+
+			alertViewController = alertViewController.NextResponder as UIViewController;
+		}
+
+		return false;
+	}
+
+	static UIViewController? GetViewController(this UIView view)
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/KeyboardAutoManager.cs:133]: Can you move this to https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/iOS/ViewExtensions.cs and just make it internal there? This way we can have it for reuse other places.

File: src/Core/src/Platform/iOS/KeyboardAutoManager.cs [hunk 3]
```diff
@@ -0,0 +1,162 @@
...
+	{
+		if (view is UITextField field && field.ReturnKeyType == UIReturnKeyType.Next)
+			return true;
+		else if (view is UITextView)
+			return true;
+
+		return false;
+	}
+
+	static UIView? GetContainerViewController(this UIViewController controller)
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/KeyboardAutoManager.cs:46]: Can you move this one as well to https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/iOS/ViewExtensions.cs ? And then make it take a generic for the type it's searching for?

File: src/Core/src/Platform/iOS/KeyboardAutoManager.cs [hunk 4]
```diff
@@ -0,0 +1,162 @@
...
+		else if (view is UITextField field)
+			isFirstResponder = field.Enabled;
+
+		return !isFirstResponder ? false :
+			!view.Hidden
+			&& view.Alpha != 0f
+			&& !view.IsAlertViewTextField();
+	}
+
+	static bool IsAlertViewTextField(this UIView view)
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/KeyboardAutoManager.cs:118]: Do we have a scenario where this check is currently relevant? 

I realize it's in the original Swift but if we don't have a use case where this check is being flexed then I think we leave it out? 

Maybe we can just comment out the check on line 115 with a comment to the original code?

File: src/Core/src/Platform/iOS/KeyboardAutoManager.cs [hunk 5]
```diff
@@ -0,0 +1,162 @@
...
+	// you can provide a topView argument or it will try to find the ContainerViewController
+	internal static void GoToNextResponderOrResign(UIView view, UIView? topView = null)
+	{
+		if (!view.CheckIfEligible())
+		{
+			view.ResignFirstResponder();
+			return;
+		}
+
+		var targetSuperview = topView ?? view.GetViewController()?.GetContainerViewController();
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/KeyboardAutoManager.cs:24]: These two calls feel slightly redundant. 

If we make `GetViewController` take a generic type for what type of `VC` is being searched for would that let us only have the one method? 

I realize `GetContainerViewController` is returning the actual `View` but I think it's fine to just pull that off the `VC` here

File: src/Core/src/Handlers/Entry/EntryHandler.iOS.cs [hunk 6]
```diff
@@ -122,9 +123,7 @@ public static void MapFormatting(IEntryHandler handler, IEntry entry)
 
 		protected virtual bool OnShouldReturn(UITextField view)
 		{
-			view.ResignFirstResponder();
-
-			// TODO: Focus next View
+			KeyboardAutoManager.GoToNextResponderOrResign(view);
```
Comment (PureWeen) [inline src/Core/src/Handlers/Entry/EntryHandler.iOS.cs:126]: Does it make sense to also add this to `EntryCellRenderer` ? 

image

File: src/Core/src/Platform/iOS/KeyboardAutoManager.cs [hunk 7]
```diff
@@ -0,0 +1,162 @@
...
+	internal static List<UIView> GetDeepResponderViews(UIView view)
+	{
+		var textItems = view.GetResponderViews();
+
+		textItems.Sort(new ResponderSorter());
+
+		return textItems;
+	}
+
+	static List<UIView> GetResponderViews(this UIView view)
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/KeyboardAutoManager.cs:84]: What are your thoughts on making the search for the `Next` field part of the recursion here instead of collecting up all the fields? 

I feel like `GetDeepResponderViews` and `MoveToNextField` could be condensed. 

We know the location of the field we're starting at so when we call `GetDeepResponderViews` we can pick and choose through winners and losers as we search through the fields.  

That might also yield a general search method instead of something specific to this scenario. 

I waffle between 
- Good idea?
- Do we really need to over engineer this, plus that's not really possible because of....?

File: src/Core/src/Platform/iOS/KeyboardAutoManager.cs (hunk 4 above)
Comment (tj-devel709) [reply src/Core/src/Platform/iOS/KeyboardAutoManager.cs:118]: Yeah I didn't really see this being that useful in our code so I can def comment it out!

File: src/Core/src/Platform/iOS/KeyboardAutoManager.cs (hunk 5 above)
Comment (tj-devel709) [reply src/Core/src/Platform/iOS/KeyboardAutoManager.cs:24]: The difference I see is that one uses superviews and the other uses NextResponder (which I guess are pretty similar), but putting them together seems to work!

File: src/Core/src/Handlers/Entry/EntryHandler.iOS.cs (hunk 6 above)
Comment (tj-devel709) [reply src/Core/src/Handlers/Entry/EntryHandler.iOS.cs:126]: Okay added with some modification and seems to be working well! I'll post a new video at the top of the PR with a tableview

File: src/Core/src/Platform/iOS/KeyboardAutoManager.cs [hunk 8]
```diff
@@ -0,0 +1,44 @@
...
+			return;
+		}
+
+		var nextField = view.FindNextView(superview, new Type[] { typeof(UITextView), typeof(UITextField) });
+		view.ChangeFocusedView(nextField);
+	}
+
+	static bool CheckIfEligible(this UIView view, bool isUnchangeableReturnKey)
+	{
+		// have isUnchangeableReturnKey flag since EntryCells do not have a public property to change ReturnKeyType
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/KeyboardAutoManager.cs:36]: I don't think we need to special case the `EntryCells` here. If at some point we add `ReturnType` or if the user changes the return type themselves then it'll just opt in with the normal flow.

File: src/Core/src/Platform/iOS/ViewExtensions.cs [hunk 9]
```diff
@@ -698,5 +698,115 @@ internal static void UpdateLayerBorder(this CoreAnimation.CALayer layer, IButton
...
+			{
+				nextResponder = nextResponder.NextResponder;
+
+				if (nextResponder is T viewController)
+					return viewController;
+			}
+			return null;
+		}
+
+		internal static UIView? FindNextView(this UIView view, UIView superView, Type[] requestedTypes)
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/ViewExtensions.cs:715]: Instead of a specific array of types here can we just do a `Func<UIView, bool>`  and let the caller define the conditional for a match? 

I think that would avoid the need for the type checks and simplify overall.

File: src/Core/src/Platform/iOS/ViewExtensions.cs [hunk 10]
```diff
@@ -698,5 +698,115 @@ internal static void UpdateLayerBorder(this CoreAnimation.CALayer layer, IButton
...
+				return null;
+
+			// calculate the original CGRect parameters once here instead of multiple times later
+			var originalRect = view.ConvertRectToView(view.Bounds, null);
+
+			var nextField = superView.SearchBestNextView(originalRect, null, requestedTypes);
+			return nextField;
+		}
+
+		static UIView? SearchBestNextView(this UIView view, CGRect originalRect, UIView? currentBest, Type[] requestedTypes)
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/ViewExtensions.cs:727]: Can we also call this one `FindNextView` ?

File: src/Core/src/Platform/iOS/ViewExtensions.cs [hunk 11]
```diff
@@ -698,5 +698,115 @@ internal static void UpdateLayerBorder(this CoreAnimation.CALayer layer, IButton
 			if (stroke.CornerRadius >= 0)
 				layer.CornerRadius = stroke.CornerRadius;
 		}
+
+		internal static UIViewController? GetViewController<T>(this UIView view) where T : UIViewController
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/ViewExtensions.cs:702]: Thoughts on `FindViewController`? `Get` feels like you'd only want the immediate VS for a particular View.  `SearchViewController`/ `FindFirstviewController`?

File: src/Core/src/Platform/iOS/ViewExtensions.cs [hunk 12]
```diff
@@ -698,5 +698,115 @@ internal static void UpdateLayerBorder(this CoreAnimation.CALayer layer, IButton
...
+			newBest = newView;
+
+			if (originalRect.Top < newViewRect.Top &&
+				(currentBestRect is null || newViewRect.Top < cbrValue.Top))
+			{
+				return true;
+			}
+
+			else if (originalRect.Top == newViewRect.Top &&
+					 originalRect.Left < newViewRect.Left &&
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/ViewExtensions.cs:774]: I think we'll need to account for RTL scenarios here as well.

**Comment by tj-devel709** [comment]
@PureWeen Here's an example of the RightToLeft scenario as well as the looping back to first entry!

https://user-images.githubusercontent.com/50846373/213410725-d6ddbe99-d06c-4d85-825e-2248b64ada5b.mov

File: src/Core/src/Platform/iOS/ViewExtensions.cs [hunk 13]
```diff
@@ -698,5 +698,124 @@ internal static void UpdateLayerBorder(this CoreAnimation.CALayer layer, IButton
...
+				nextResponder = nextResponder.NextResponder;
+
+				if (nextResponder is T responder)
+					return responder;
+			}
+			return null;
+		}
+
+		// static field to hold value when propagating back out the recursion
+		static bool IsRtl = false;
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/ViewExtensions.cs:716]: Is it not possible to make the a variable in the "root" FindNextView and then have a ref parameter in the other methods. Static fields with temporary state is often a cause of random issues if something goes wrong.

Not sure if this works, but thinking like this:

```cs
internal static UIView? FindNextView(this UIView view, UIView superView, Func<UIView, bool> isValidType)
{
  var isRtl = false;
  var nextField = superView.FindNextView(originalRect, null, isValidType, ref isRtl);
  return nextField;
}

static UIView? FindNextView(this UIView view, CGRect originalRect, UIView? currentBest, Func<UIView, bool> isValidType, ref bool isRtl)
{
  isRtl |= view.SemanticContentAttribute == UISemanticContentAttribute.ForceRightToLeft;
  // ...
      if (TryFindNewBestView(originalRect, currentBest, child, out var newBest, ref isRtl))
  // ...
  return currentBest;
}

static bool TryFindNewBestView(CGRect originalRect, UIView? currentBest, UIView newView, out UIView newBest, ref bool isRtl)
{
  // ...
}
```

Also, this appears to not support a stack, so if I go into a RTL and then back out, the value is permanently set? I am thinking of a layout like this:

```xaml
<Stack IsRtl="false">
  <Stack IsRtl="true">
    <Entry/>
    <Entry/>
  </Stack>
  <Stack>
    <Entry/>
    <Entry/>
  </Stack>
</Stack>
```

Comment (tj-devel709) [reply src/Core/src/Platform/iOS/ViewExtensions.cs:716]: Yeah this is something that has been rough haha. I'm not too familiar with the UISemanticContentAttribute.ForceRightToLeft and did not think about the above situation. The issue I was having with the IsRtl lied in propogating back up from the recursive FindNextView and how the TryFindNewBestView compares the views based on the IsRtl. I will keep looking at this and perhaps need to change some of the logic of how I compare the NewBestView when coming back out the recursion

Comment (mattleibow) [reply src/Core/src/Platform/iOS/ViewExtensions.cs:716]: If it is never un-set, does this mean the next time around it starts as RTL?

Comment (tj-devel709) [reply src/Core/src/Platform/iOS/ViewExtensions.cs:716]: The ref worked well though for keeping the same functionality though! Thanks!

**Comment by tj-devel709** [comment]
I have created an issue here: https://github.com/dotnet/maui/issues/12968
that I will also include in the description of this PR.

The issue is a spec that contains ideas for providing a Visual Ordering in the future for iOS, bringing this Logical ordering sort to Android, and a way for customers to decide which type of ordering they would prefer.

**Comment by tj-devel709** [comment]
Here is an example of the next keyboard press respecting interlocked RightToLeft and LeftToRight FlowDirections

https://user-images.githubusercontent.com/50846373/215188581-7935fe66-d477-4018-ae48-61e9885deb8e.mov

File: src/Core/src/Platform/iOS/ViewExtensions.cs (hunk 13 above)
Comment (tj-devel709) [reply src/Core/src/Platform/iOS/ViewExtensions.cs]: @mattleibow things are now being sorted by Logical order and I posted a video below showing that it handles RightToLeft and LeftToRight well now. I also added some unit tests regarding that as well!

**Review by mattleibow — APPROVED** [review]
Nice PR, much cleaner and love the test. So many cases, so many ways to prevent me breaking something in the future :)

**Review by rmarinho — APPROVED** [review]

File: src/Core/src/Platform/iOS/ViewExtensions.cs [hunk 14]
```diff
@@ -698,5 +698,66 @@ internal static void UpdateLayerBorder(this CoreAnimation.CALayer layer, IButton
...
+					return responder;
+			}
+			return null;
+		}
+
+		internal static UIView? FindNextView(this UIView view, UIView superView, Func<UIView, bool> isValidType)
+		{
+			var passedOriginal = false;
+
+			var nextView = superView.FindNextView(view, ref passedOriginal, isValidType);
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/ViewExtensions.cs:719]: Instead of always starting at the top level view and searching down to find your place can we start the search from where we are at and search out? This way we aren't always traversing the entire view stack?

**Review by PureWeen — CHANGES_REQUESTED** [review]

**Review by PureWeen — APPROVED** [review]
https://github.com/dotnet/maui/issues/13147
