### PR TITLE
Always use dot separators in XAML SG converters

### LINKED ISSUE #31142: [.NET10-preview7]  XAML Source Generator - Grid Error + Warnings
### Description

Using .net10 Preview 7 , and enabling XAML Source Generator, there is an error with Grids

`<Grid RowDefinitions="25,*,1.25"/>`

Results in the following build error: 
`'GridLength' does not contain a constructor that takes 3 arguments`

There is also a warning: `'SimpleValueTargetProvider.SimpleValueTargetProvider(object[], object, INameScope[], bool)' is obsolete: 'Use the other ctor'`

I have here a minimal sample, but when running in a Real project, this produces a gazillion warnings.

### Steps to Reproduce

1. Create new .net MAUI App - .net 10 preview 7
2. Enable Xaml Source Generators
3. Declare a simple Grid with multiple rows / Columns
4. Build error + warnings

### Link to public reproduction project repository

https://github.com/bcaceiro/net9-repros/tree/main/Maui10Preview7

### Version with bug

10.0.0-preview.6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

10.0.0-preview.6

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

Disable the XAML Source Generator

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by jfversluis**
We did parse the values with invariant culture, but didn't take that into account when writing the values. This could cause decimal/double values to be written with comma's, which in turn causes invalid syntax. This change makes sure that we always use the dot separator.

Fixes #31142

### CODE REVIEW

**Review by StephaneDelcroix — DISMISSED** [review]

File: src/Controls/tests/SourceGen.UnitTests/KnownTypeConvertersTests.cs [hunk 1]
```diff
@@ -0,0 +1,309 @@
...
+		public void GridLengthTypeConverter_StarValues_ProducesConsistentOutput_AcrossCultures(string cultureName, string gridLengthValue)
+		{
+			var originalCulture = CultureInfo.CurrentCulture;
+			var originalUICulture = CultureInfo.CurrentUICulture;
+			
+			try
+			{
+				// Set both current and UI cultures to test locale
+				CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo(cultureName);
+				CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo(cultureName);
```
Comment (simonrozsival) [inline src/Controls/tests/SourceGen.UnitTests/KnownTypeConvertersTests.cs]: I'm never sure if changing these properties can affect other tests running in parallel or not. Do these change only the current thread culture? If it's just the current thread, does it propagate to the source generator (does it use other threads internally?). If it's a global proparty, maybe we should make these tests non-parallelizable?

File: src/Controls/src/SourceGen/GeneratorHelpers.cs [hunk 2]
```diff
@@ -398,4 +398,31 @@ static void SimplifyOnPlatform(XmlNode node, string? targetFramework, XmlNamespa
...
+	}
+
+	/// <summary>
+	/// Formats a numeric value as a culture-independent C# literal with quote strings enabled.
+	/// Uses SymbolDisplay.FormatPrimitive to ensure proper handling of special values like NaN and Infinity.
+	/// </summary>
+	public static string FormatInvariantWithQuotes(double value)
+	{
+		return SymbolDisplay.FormatPrimitive(value, true, false);
+	}
```
Comment (StephaneDelcroix) [inline src/Controls/src/SourceGen/GeneratorHelpers.cs]: multiple things here....
1/ I wouldn't add FormatInvariant helpers, I would instead name the boolean parameters in the invocation
2/ If you insist on providing helpers, they should accept an object as value (like FormatPriomitive), and the withQuotes should be an optional parameter

File: src/Controls/tests/SourceGen.UnitTests/KnownTypeConvertersTests.cs (hunk 1 above)
Comment (StephaneDelcroix) [reply src/Controls/tests/SourceGen.UnitTests/KnownTypeConvertersTests.cs]: other tests are doing 
```
System.Threading.Thread.CurrentThread.CurrentCulture = ...;
```

File: src/Controls/tests/SourceGen.UnitTests/KnownTypeConvertersTests.cs [hunk 3]
```diff
@@ -0,0 +1,309 @@
...
+				// The generated code should use period as decimal separator (culture-invariant)
+				// and should contain the GridLength constructor with Star unit type
+				Assert.That(generated, Does.Contain($"new global::Microsoft.Maui.GridLength({numericPart}, global::Microsoft.Maui.GridUnitType.Star)"),
+					$"Generated code should contain culture-invariant GridLength with value {numericPart}. Generated code: {generated}");
+			}
+			finally
+			{
+				// Restore original cultures
+				CultureInfo.CurrentCulture = originalCulture;
+				CultureInfo.CurrentUICulture = originalUICulture;
```
Comment (StephaneDelcroix) [inline src/Controls/tests/SourceGen.UnitTests/KnownTypeConvertersTests.cs]: this should be down in a TearDown

File: src/Controls/tests/SourceGen.UnitTests/KnownTypeConvertersTests.cs [hunk 4]
```diff
@@ -0,0 +1,309 @@
...
+	{
+		[TestCase("en-US", "1.5*")]
+		[TestCase("fr-FR", "2.5*")]
+		[TestCase("de-DE", "3.14*")]
+		[TestCase("es-ES", "0.75*")]
+		[TestCase("ru-RU", "1.414*")]
+		public void GridLengthTypeConverter_StarValues_ProducesConsistentOutput_AcrossCultures(string cultureName, string gridLengthValue)
+		{
+			var originalCulture = CultureInfo.CurrentCulture;
+			var originalUICulture = CultureInfo.CurrentUICulture;
```
Comment (StephaneDelcroix) [inline src/Controls/tests/SourceGen.UnitTests/KnownTypeConvertersTests.cs]: this should be done in a SetUp

**Review by StephaneDelcroix — CHANGES_REQUESTED** [review]

File: src/Controls/src/SourceGen/GeneratorHelpers.cs (hunk 2 above)
Comment (jfversluis) [reply src/Controls/src/SourceGen/GeneratorHelpers.cs]: Kept the helper method. We're probably never going to use the third parameter and having that everywhere, including the parameter name seems a bit excessive. Addressed the rest of the feedback though, thanks!

File: src/Controls/tests/SourceGen.UnitTests/KnownTypeConvertersTests.cs (hunk 1 above)
Comment (jfversluis) [reply src/Controls/tests/SourceGen.UnitTests/KnownTypeConvertersTests.cs]: Made it non-parallelizable just in case, and using the API Stephane proposed.

**Review by simonrozsival — APPROVED** [review]

File: src/Controls/src/SourceGen/GeneratorHelpers.cs [hunk 5]
```diff
@@ -398,4 +398,19 @@ static void SimplifyOnPlatform(XmlNode node, string? targetFramework, XmlNamespa
...
+	/// Uses SymbolDisplay.FormatPrimitive to ensure proper handling of special values like NaN and Infinity
+	/// but also numeric types and makes sure they are formatted correctly.
+	/// </summary>
+	/// <param name="value">The value to format</param>
+	/// <param name="quoted">Whether to include quotes around the formatted value</param>
+	/// <returns>A culture-independent string representation suitable for source generation</returns>
+	public static string FormatInvariant(object value, bool quoted = false)
+	{
+		return SymbolDisplay.FormatPrimitive(value, quoteStrings: quoted, useHexadecimalNumbers: false);
+	}
```
Comment (StephaneDelcroix) [inline src/Controls/src/SourceGen/GeneratorHelpers.cs:413]:
```suggestion
	extension(SymbolDisplay)
	{
		public static string FormatPrimitive(object value, bool quotedStrings = false) => SymbolDisplay.FormatPrimitive(value, quotedStrings, false);
	}
```
