### PR TITLE
[Android] Avoid to update Shell Toolbar colors if already disposed the Tracker

### LINKED ISSUE #12460: NullReferenceException in `ShellToolbarAppearanceTracker.SetColors` on Android
### Description

Had 3 reports of crashes in this method from two devices, on Android 9 and 10, via AppCenter

Here's the code in question:
https://github.com/dotnet/maui/blob/a3b135fec871c0863fa61de6a3ea637d0dd1bf49/src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarAppearanceTracker.cs#L34-L39

Is the MAUI library using nullable types? If not, there's no verification that `_shellContext` is not null when the object is constructed. And if it's at all possible to be accessed after being disposed, that would also produce this exception.

Even if `_shellContext` is not null, is `.Shell`, or `.Shell.Toolbar` guaranteed to not be null?

### Steps to Reproduce

Unknown

### Link to public reproduction project repository

n/a

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9-10

### Did you find any workaround?

_No response_

### Relevant log output

```shell
Full stack trace:

Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarAppearanceTracker.SetColors(Toolbar toolbar, IShellToolbarTracker toolbarTracker, Color foreground, Color background, Color title)
Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarAppearanceTracker.SetAppearance(Toolbar toolbar, IShellToolbarTracker toolbarTracker, ShellAppearance appearance)
Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.SetAppearance(ShellAppearance appearance)
Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.Microsoft.Maui.Controls.IAppearanceObserver.OnAppearanceChanged(ShellAppearance appearance)
Microsoft.Maui.Controls.Shell.Microsoft.Maui.Controls.IShellController.AppearanceChanged(Element source, Boolean appearanceSet)
Microsoft.Maui.Controls.ShellSection.SendAppearanceChanged()
Microsoft.Maui.Controls.ShellSection.UpdateDisplayedPage()
Microsoft.Maui.Controls.ShellSection.OnVisibleChildAdded(Element child)
Microsoft.Maui.Controls.ShellSection.OnChildAdded(Element child)
Microsoft.Maui.Controls.BaseShellItem.AddLogicalChild(Element element)
Microsoft.Maui.Controls.ShellSection.AddPage(Page page)
Microsoft.Maui.Controls.ShellSection.OnPushAsync(Page page, Boolean animated)
Microsoft.Maui.Controls.ShellSection.PushStackOfPages(List`1 pages, Nullable`1 animate)
Microsoft.Maui.Controls.ShellSection.GoToAsync(ShellNavigationRequest request, ShellRouteParameters queryData, IServiceProvider services, Nullable`1 animate, Boolean isRelativePopping)
Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest)
```
```

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Avoid to update Shell Toolbar colors if already disposed the AppareanceTracker.

### Issues Fixed

Fixes #12460

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarAppearanceTracker.cs [hunk 1]
```diff
@@ -33,9 +33,17 @@ public virtual void ResetAppearance(AToolbar toolbar, IShellToolbarTracker toolb
...
 		{
-			_shellContext.Shell.Toolbar.BarTextColor = title ?? ShellRenderer.DefaultTitleColor;
-			_shellContext.Shell.Toolbar.BarBackground = new SolidColorBrush(background ?? ShellRenderer.DefaultBackgroundColor);
-			_shellContext.Shell.Toolbar.IconColor = foreground ?? ShellRenderer.DefaultForegroundColor;
+			if (_disposed)
+				return;
+
+			Toolbar shellToolbar = _shellContext.Shell.Toolbar;
+
+			if (shellToolbar == null)
```
Comment (mandel-macaque) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarAppearanceTracker.cs:41]:
```suggestion
			if (shellToolbar is null)
```

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarAppearanceTracker.cs [hunk 2]
```diff
@@ -33,9 +33,17 @@ public virtual void ResetAppearance(AToolbar toolbar, IShellToolbarTracker toolb
...
+				return;
+
+			shellToolbar.BarTextColor = title ?? ShellRenderer.DefaultTitleColor;
+			shellToolbar.BarBackground = new SolidColorBrush(background ?? ShellRenderer.DefaultBackgroundColor);
+			shellToolbar.IconColor = foreground ?? ShellRenderer.DefaultForegroundColor;
```
Comment (mandel-macaque) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarAppearanceTracker.cs:46]: Nice use of ??

**Review by mandel-macaque — APPROVED** [review]
Minor comment.

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarAppearanceTracker.cs (hunk 2 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarAppearanceTracker.cs:46]: ❤️

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarAppearanceTracker.cs [hunk 3]
```diff
@@ -33,9 +33,17 @@ public virtual void ResetAppearance(AToolbar toolbar, IShellToolbarTracker toolb
 
 		protected virtual void SetColors(AToolbar toolbar, IShellToolbarTracker toolbarTracker, Color foreground, Color background, Color title)
 		{
-			_shellContext.Shell.Toolbar.BarTextColor = title ?? ShellRenderer.DefaultTitleColor;
-			_shellContext.Shell.Toolbar.BarBackground = new SolidColorBrush(background ?? ShellRenderer.DefaultBackgroundColor);
-			_shellContext.Shell.Toolbar.IconColor = foreground ?? ShellRenderer.DefaultForegroundColor;
+			if (_disposed)
+				return;
+
+			Toolbar shellToolbar = _shellContext.Shell.Toolbar;
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarAppearanceTracker.cs:39]:
```suggestion
			Toolbar shellToolbar = _shellContext?.Shell?.Toolbar;
```

**Review by PureWeen — APPROVED** [review]
