### PR TITLE
[iOS] Add templated cells as children of the CollectionView2

### LINKED ISSUE #26066: CollectionViewHandler2 RelativeSource binding to AncestorType not working
### Description

Using RelativeSource binding AncestorType doesn't seem to work using CollectionViewHandler2

### Steps to Reproduce

1. Add a collecitonview to a page, and bind a property in the itemtemplate to the PageModel using RelativeBinding source of AncestorType:

```xaml
<CollectionView.ItemTemplate>
    <DataTemplate>
        <StackLayout Padding="10">
            <Label Text="{Binding .}" />
            <Button
                Command="{Binding ShowDialogCommand, Source={x:RelativeSource AncestorType={x:Type pm:RelativeSourceBindingPageModel}}}"
                CommandParameter="{Binding .}"
                Text="Show Dialog" />
        </StackLayout>
    </DataTemplate>
</CollectionView.ItemTemplate>
```

2. Enable CollectionViewHandler2:

```cs
#if IOS || MACCATALYST
            builder.ConfigureMauiHandlers(handlers =>
            {
                handlers.AddHandler<Microsoft.Maui.Controls.CollectionView, Microsoft.Maui.Controls.Handlers.Items2.CollectionViewHandler2>();
                handlers.AddHandler<Microsoft.Maui.Controls.CarouselView, Microsoft.Maui.Controls.Handlers.Items2.CarouselViewHandler2>();
            });
#endif
```

3. run the app on iOS and you will see that the binding simply doesn't work 
4. disabling CollectionViewHandler2 resolves the issue

_**See the RelativeSourceBindingPage in the attached reproduction repository**_
CollectionViewHandler2Bugs/Pages/RelativeSourceBindingPage.xaml

### Link to public reproduction project repository

https://github.com/rysbilinski/CollectionViewHandler2Bugs

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

If you use the normal CollectionViewHandler then the binding works as expected

```cs
 builder
                .UseMauiApp<App>().ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                })
                .UseMauiCommunityToolkit();
//#if IOS || MACCATALYST
//            builder.ConfigureMauiHandlers(handlers =>
//            {
//                handlers.AddHandler<Microsoft.Maui.Controls.CollectionView, Microsoft.Maui.Controls.Handlers.Items2.CollectionViewHandler2>();
//                handlers.AddHandler<Microsoft.Maui.Controls.CarouselView, Microsoft.Maui.Controls.Handlers.Items2.CarouselViewHandler2>();
//            });
//#endif
```

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

When porting to the new implementation we forgot to move add the inflated templates as a children of the ItemsView.

This pull request includes several changes to improve the functionality and maintainability of the `ItemsViewController2` and `TemplatedCell2` classes, as well as adding a new test case for a specific issue.  Also does some cleanup

Codebase simplification:

* [`src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs`](diffhunk://#diff-dcaa555cd62425342259680af963c19dc908ab24491c229d751caf3c056eeca7L214-L290): Removed unused methods `InvalidateMeasureIfContentSizeChanged`, `GetSize`, and `ConstrainItemsToBounds`. Also removed a debug `Console.WriteLine` statement from `DetermineCellReuseId` and updated `UpdateView` to properly disconnect handlers and dispose of views. [[1]](diffhunk://#diff-dcaa555cd62425342259680af963c19dc908ab24491c229d751caf3c056eeca7L214-L290) [[2]](diffhunk://#diff-dcaa555cd62425342259680af963c19dc908ab24491c229d751caf3c056eeca7L373) [[3]](diffhunk://#diff-dcaa555cd62425342259680af963c19dc908ab24491c229d751caf3c056eeca7L411-R334)

Enhancements to binding logic:

* [`src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs`](diffhunk://#diff-617eb1f606ac3f05750380c858c3fbef7b80cba5fc556bc3f53bf6b792380978R67): Updated the `Unbind` method to remove logical children and refactored the `Bind` method to use a helper method `BindVirtualView` for better code organization and clarity. [[1]](diffhunk://#diff-617eb1f606ac3f05750380c858c3fbef7b80cba5fc556bc3f53bf6b792380978R67) [[2]](diffhunk://#diff-617eb1f606ac3f05750380c858c3fbef7b80cba5fc556bc3f53bf6b792380978L109-R145)

New test case:

* `src/Controls/tests/TestCases.HostApp/Issues/Issue26066.xaml` and `src/Controls/tests/TestCases.HostApp/Issues/Issue26066.xaml.cs`: Added a new test case to address Issue 26066, which involves testing the `CollectionViewHandler2` with `RelativeSource` binding to `AncestorType`. [[1]](diffhunk://#diff-efb8508abc878ed9dee7cfc5fc5948ed37c969105aa83a9b1f892af2f825b617R1-R42) [[2]](diffhunk://#diff-84bb7f309b1e9ddf195f354c915e1e80d073d5d06ed60c8313796fc29570fb18R1-R42)
* [`src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26066.cs`](diffhunk://#diff-35e2cfc839047627602556d9a99b3e6be67b9b74a7a6d893f132eaf98d9d6601R1-R23): Added a corresponding test method to verify that `CollectionView2` can find the ancestor type and handle the binding correctly.

### Issues Fixed

Fixes #26066

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs [hunk 1]
```diff
@@ -410,7 +410,7 @@ internal void UpdateView(object view, DataTemplate viewTemplate, ref UIView uiVi
 
 				uiView?.Dispose();
 				uiView = null;
-
+				formsElement?.Handler?.DisconnectHandler();
```
Comment (mattleibow) [inline src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs:413]: Do we need the dispose above? doesn't the disconnect do it? And also, @PureWeen said dispose is the evil path to crashes.

File: src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs [hunk 2]
```diff
@@ -107,49 +108,42 @@ public override void PrepareForReuse()
...
-			{
-				view.SetValueFromRenderer(BindableObject.BindingContextProperty, bindingContext);
-			}
+			var virtualView = template.CreateContent(bindingContext, itemsView) as View;
+			BindVirtualView(virtualView, bindingContext, itemsView, true);
 		}
 
 		public void Bind(View virtualView, ItemsView itemsView)
+		{
+			BindVirtualView(virtualView, itemsView.BindingContext, itemsView, false);
```
Comment (mattleibow) [inline src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs:117]: Is this `itemsView.BindingContext` correct? Will that be bindng an item to the whole VS and not the item object?

Comment (mattleibow) [reply src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs:117]: I suppose that is what the existing code was doing, but just checking to see if the OG code was correct.

Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs:117]: Yeah this is for the Headers, so basically if you don t give a template and just give a plain headerView or footerview. I just refactored the code here

File: src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs [hunk 3]
```diff
@@ -107,49 +108,42 @@ public override void PrepareForReuse()
...
+		}
+
+		private void BindVirtualView(View virtualView, object bindingContext, ItemsView itemsView, bool needsContainer)
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs:120]: drop private hahahah

File: src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs (hunk 1 above)
Comment (PureWeen) [reply src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs:413]: We should remove the `Dispose`

We never want to call `Dispose` on anything. 
We should also make sure all the code that's inside any `Dispose` methods related to CV get moved to a disconnect path

Comment (PureWeen) [reply src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs:413]: https://github.com/dotnet/maui/issues/26134

Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs:412]: We can try move the Dipose calls all in another PR for #26134

**Review by Redth — APPROVED** [review]
