### PR TITLE
[Android] - Fix inconsistent footer scrolling when EmptyView is a string in CollectionView

### LINKED ISSUE #28765: [Android] Inconsistent footer scrolling in CollectionView when EmptyView as string
### Description

When using a Header and Footer Template in a CollectionView on Android, the footer becomes scrollable when EmptyView is used as string. However, on other platforms, the footer remains properly positioned within the view.

Expected Behavior:

The footer should remain fixed within the view when EmptyView is displayed, consistent across all platforms.

https://github.com/user-attachments/assets/64f13583-bf13-4e2d-b221-412b112df0b4

Actual Behavior:

On Android, the footer becomes scrollable when EmptyView is shown.

On other platforms, the footer remains fixed within the view, as expected.

### Steps to Reproduce

1. Run the attached sample.
2. See the footer template is not visible in view.
3. When collection view is scrolled footer template is visible.

[EmptyViewSample.zip](https://github.com/user-attachments/files/19569309/EmptyViewSample.zip)

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.50 SR5

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

_No response_

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by prakashKannanSf3972**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause

- When the `EmptyView` is defined as a string, it occupies the entire parent space without considering header and footer dimensions, causing overlaps or forcing the footer into a scrollable area.

### Description of Change

- Enhanced layout logic to account for `Header` and `Footer` measurements when the `EmptyView` is specified as a string. This ensures the `EmptyView` no longer occupies the entire available space indiscriminately and allows the `Footer` to remain properly anchored, preserving the correct layout.
- Enhanced `UpdateHeaderFooterHeight` to handle string-based content by creating a `Label` for measurement, ensuring accurate height calculations for header and footer items.

### Issues Fixed

Fixes #28765

**Tested the behaviour in the following platforms**

- [x] Android
- [x]  Windows
- [x]  iOS
- [x] Mac

### Output

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/b50ed50f-ad65-44ca-8a18-7eefe90e4e4b">| <video src="https://github.com/user-attachments/assets/46ca66bd-e53f-4a5e-b7c9-72d36f2a2fc6">|

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/Android/Adapters/EmptyViewAdapter.cs [hunk 1]
```diff
@@ -319,6 +319,14 @@ void UpdateHeaderFooterHeight(object item, bool isHeader)
 				size = content.Measure(double.PositiveInfinity, double.PositiveInfinity);
 			}
 
+			if (item is string text)
+			{
+				Label label = new Label { Text = text };
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items/Android/Adapters/EmptyViewAdapter.cs:324]: Doesn t it need a parent to get layout correctly ?

File: src/Controls/src/Core/Handlers/Items/Android/SimpleViewHolder.cs [hunk 2]
```diff
@@ -27,19 +27,19 @@ public void Recycle(ItemsView itemsView)
...
-			var textView = new TextView(context) { Text = text };
-
 			if (fill)
 			{
-				var layoutParams = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MatchParent,
-					ViewGroup.LayoutParams.MatchParent);
-				textView.LayoutParameters = layoutParams;
+				// When displaying an EmptyView with Header and Footer, we need to account for the Header and Footer sizes in layout calculations.
+				// This prevents the EmptyView from occupying the full remaining space. 
+				Label label = new Label() { Text = text, VerticalOptions = LayoutOptions.Center, HorizontalOptions = LayoutOptions.Center };
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items/Android/SimpleViewHolder.cs:36]: I wonder if this should center the text horizontally

**Review by rmarinho — DISMISSED** [review]

**Review by PureWeen — APPROVED** [review]

File: src/Controls/src/Core/Handlers/Items/Android/Adapters/EmptyViewAdapter.cs (hunk 1 above)
Comment (prakashKannanSf3972) [reply src/Controls/src/Core/Handlers/Items/Android/Adapters/EmptyViewAdapter.cs:324]: In this case, assigning a parent is not required, as the `Label` is used solely for measuring the size of the string-based content. It's not intended to be rendered or added to the visual tree—just to obtain the necessary size for calculating `header` or `footer` heights.
