### PR TITLE
remove Dispose call on ShellItemRenderer

### LINKED ISSUE #27889: Shell flyout throws an exception on Android if there's a FragmentLifecycle.Callback
### Description

IF you navigate between flyouts using shell, and have registered a FragmentCallback (For android) your app will crash with 

Image

### Steps to Reproduce

Run the sample here:
- https://github.com/pictos/maui/tree/pj/shellItemRenderer-dialog-issue

### Link to public reproduction project repository

https://github.com/pictos/maui/tree/pj/shellItemRenderer-dialog-issue

### Version with bug

9.0.40 SR4

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by pictos**
### Description of Change

Remove the `Dispose` call that happens during `OnDestroy` lifecycle. If user has added a `FragmentManager.FragmentLifecycleCallbacks` the `Fragment`, that represents the `ShellItem` will be disposed too earlier causing in an app crash. Removing the `Dipose` call will make sure that the `Fragment` lives long enough to pass to all lifecycle methods.

### Issues Fixed

Fixes #27889

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellRenderer.cs [hunk 1]
```diff
@@ -245,7 +244,6 @@ void OnDestroyed(object sender, EventArgs args)
 			{
 				previousView.Destroyed -= OnDestroyed;
 
-				previousView.Dispose();
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellRenderer.cs:248]: I'm thinking

1) make destroy internal but call it disconnect
2) call disconnect here instead of dispose
3) inside dispose still call disconnect

We should still keep that path open but not trigger it ourselves

Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellRenderer.cs:248]: Chatted with @pictos on discord

This is fine
The destroy code is already called from inside "ShellItemRenderer"

**Review by rmarinho — APPROVED** [review]

**Comment by pictos** [comment]
can we remove the label `needs-author-input`?
