### PR TITLE
[Android] Fix gestures in Label Spans

### LINKED ISSUE #4734: Gestures don't work on Label Spans
### Description

I added a gesture to a label span and tapped it. Nothing is happening on Windows. Cannot test Android bc it doesn't render the span.

Platforms:

- [x] Android https://github.com/dotnet/maui/pull/14410
- [x] iOS https://github.com/dotnet/maui/pull/15544
- [x] Mac Catalyst https://github.com/dotnet/maui/pull/15544
- [ ] Windows https://github.com/dotnet/maui/pull/17731

### Steps to Reproduce

Run this:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ControlGallery.Pages.LabelPage"
             Shell.FlyoutBehavior="Disabled"
             >

    <ContentPage.Content>
        <ScrollView>
            <StackLayout Padding="{OnPlatform iOS='30,60,30,30', Default='30'}">

                <Label LineBreakMode="NoWrap" LineHeight="1.4">
                    <Label.FormattedText>
                        <FormattedString>
                            <Span Text="Font name: Default &#10;"/>
                            <Span Text="Version: 1.00  &#10;"/>
                            <Span Text="Digitally Signed, TrueType Outlines &#10;"/>
                            <Span Text="abcdefghijklmnopqrstuvwxyz "/>
                            <Span Text="abcdefghijklmnopqrstuvwxyz &#10;" TextTransform="Uppercase"/>
                            <Span Text="1234567890.:,;'+-*/=  &#10;"/>
                            <Span Text="12 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="12"/>
                            <Span Text="18 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="18"/>
                            <Span Text="24 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="24"/>
                            <Span Text="36 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="36"/>
                            <Span Text="48 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="48"/>
                            <Span Text="60 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="60"/>
                            <Span Text="72 The quick brown fox jumps over the lazy dog. 1234567890 " FontSize="72" >
                                <Span.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding TapCommand}" CommandParameter="https://google.com" />
                                </Span.GestureRecognizers>
                            </Span>
                        </FormattedString>
                    </Label.FormattedText>                    
                </Label>
            </StackLayout>
        </ScrollView>

    </ContentPage.Content>
</ContentPage>
```

```csharp
using System.Windows.Input;

namespace ControlGallery.Pages;

public partial class LabelPage : ContentPage
{
    public ICommand TapCommand => new Command<string>(async (url) => await Launcher.OpenAsync(url));

    public LabelPage()
    {
        InitializeComponent();
        BindingContext = this;
    }
}

```

image

Screenshot_1645061133

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

All

### Did you find any workaround?

No workaround

### Relevant log output

_No response_

### LINKED ISSUE #8004: TapGestureRecognizer does not work in label's span
### Description

In the following xaml, tap does't work and react to the finger tap.

            <Label>
                <Label.FormattedText>
                    <FormattedString>
                        <Span Text="Alternatively, click " />
                        <Span Text="here"
                  TextColor="Blue" FontSize="24"
                  TextDecorations="Underline">
                            <Span.GestureRecognizers>
                                <TapGestureRecognizer Command="{Binding TapCommand}"
                                          CommandParameter="https://docs.microsoft.com/dotnet/maui/" />
                            </Span.GestureRecognizers>
                        </Span>
                        <Span Text=" to view .NET MAUI documentation." />
                    </FormattedString>
                </Label.FormattedText>
            </Label>

### Steps to Reproduce

create an maui app
add label and some span
add TapGestureRecognizer 

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 10、windows sdk 10.0.19041.0

### Did you find any workaround?

no workaround. but TapGestureRecognizer  in label works like the following xaml:
            <Label Text="here"
                  TextColor="Blue" FontSize="24"
                  TextDecorations="Underline">
                <Label.GestureRecognizers>
                    <TapGestureRecognizer Command="{Binding TapCommand}"
                                          CommandParameter="https://docs.microsoft.com/dotnet/maui/" />
                </Label.GestureRecognizers>
            </Label>

### Relevant log output

```shell
no
```

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix gestures in Label Spans on **Android**.

To test/validate the changes, open the .NET MAUI Gallery and navigate to the Label page. Tap the Span with the text "Click Me". If the Span changes the TextColor, is working as expected.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/4734
Fixes https://github.com/dotnet/maui/issues/8004

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

File: src/Controls/src/Core/Region.cs [hunk 1]
```diff
@@ -26,6 +27,12 @@ public struct Region : IEquatable<Region>
 			_inflation = inflation;
 		}
 
+		internal static Region FromRectangles(IEnumerable<Rect> rectangles)
```
Comment (mattleibow) [inline src/Controls/src/Core/Region.cs:30]: Should this rather be a new ctor that takes IEnumerable? Is there a reason for the list-only approach?

File: src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs [hunk 2]
```diff
@@ -180,42 +177,47 @@ public static void RecalculateSpanPositions(this TextView textView, Label elemen
 				var startSpan = spans[0];
 				var endSpan = spans[spans.Length - 1];
 
-				var startSpanOffset = spannableString.GetSpanStart(startSpan);
```
Comment (mattleibow) [inline src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs:183]: There is a lot of changes with variable names that makes this a harder diff to read. Is this needed or can we revert to make it easier and better for backporting?

File: src/Controls/src/Core/Region.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Region.cs:30]: Yes, it would be possible but it would have to be public and would require changes to the public APIs of all supported platforms.

**Comment by rmarinho** [comment]
Can we add a device test for this ?

**Comment by jsuarezruiz** [comment]
> Can we add a device test for this ?

Mnn, without a UI Test can validate if the PlatformView contains GestureRecognizers etc but cannot validate exactly the same scenario from the sample.

File: src/Controls/src/Core/HandlerImpl/Label/Label.Android.cs [hunk 3]
```diff
@@ -76,13 +76,12 @@ void OnLayoutChanged(object sender, LayoutChangedEventArgs args)
...
 
-				if (platformView == null || virtualView == null)
+				if (platformView is null || virtualView is null)
 					return;
 
-				SpannableString spannableString = null;
-
-				if (virtualView.FormattedText != null)
-					spannableString = virtualView.ToSpannableString();
+				FormattedString formattedText = virtualView.FormattedText ?? virtualView.Text;
```
Comment (mattleibow) [inline src/Controls/src/Core/HandlerImpl/Label/Label.Android.cs:82]: My PR that is currently causing the merge conflict on this one fixed the issue where the measure was happening for plain text labels. Not sure if this is still needed.

File: src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs [hunk 4]
```diff
@@ -133,31 +133,28 @@ public static SpannableString ToSpannableString(this Label label)
...
 
-#pragma warning disable CA1416
-			var strlen = spannableString.Length();
-#pragma warning restore CA1416
+			var padding = element.Padding;
+			var padLeft = (int)textView.Context.ToPixels(padding.Left);
+			var padTop = (int)textView.Context.ToPixels(padding.Top);
 
-			for (int i = 0; i < strlen; i = next)
+			for (int i = 0; i < spannableString.Length(); i = next)
```
Comment (mattleibow) [inline src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs:157]: I think the length is extracted as it is quite expensive to get as it has to cross the JNI bridge.

**Review by mattleibow — COMMENTED** [review]
Is it possible to add tests? Not sure if there is a way to get the regions in tests, or maybe this is just a wait for UI tests to tap the screen.

File: src/Controls/src/Core/HandlerImpl/Label/Label.Android.cs (hunk 3 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/HandlerImpl/Label/Label.Android.cs]: Checked and resolved the conflict.

File: src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs (hunk 4 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs]: Yeah, good point. Reverted this change.

File: src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Android.cs [hunk 5]
```diff
@@ -176,10 +176,11 @@ void SetupGestures()
 				return;
 
 			var platformView = Control;
+
 			if (platformView == null)
 				return;
 
-			if (View.GestureRecognizers.Count == 0)
+			if (View.GestureController.CompositeGestureRecognizers.Count == 0)
```
Comment (mattleibow) [inline src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Android.cs:183]: @PureWeen is this correct?

File: src/Controls/src/Core/Region.cs (hunk 1 above)
Comment (mattleibow) [reply src/Controls/src/Core/Region.cs:30]: Maybe this should be public for main/net8 and internal for net7 since we can no longer use the lines to work?

**Review by mattleibow — APPROVED** [review]

**Comment by MetalKid** [comment]
This appears fixed on Android, but not for iOS?

**Comment by Obvious1992** [comment]
> This appears fixed on Android, but not for iOS?
This is the iOs related PR https://github.com/dotnet/maui/pull/15544
