### PR TITLE
[iOS] Fix for Flyout title is not broken over multiple lines when you rotate your screen. 

### LINKED ISSUE #15154: iOS Flyout title is not broken over multiple lines when you rotate your screen
### Description

https://github.com/dotnet/maui/assets/108216731/6ddb45f1-0949-485d-a34f-3c5ebf2e2b77

### Steps to Reproduce

Use ShellContent Flyout with long title

### Link to public reproduction project repository

*

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4.1

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by BagavathiPerumal**
### Root cause

The issue originated from missing Auto Layout constraints in the UIContainerCell implementation. Without explicit constraints anchoring the platform view to its container edges, the view failed to properly resize during orientation changes. This constraint deficiency prevented iOS from accurately calculating available width when transitioning to landscape mode, causing text content to be cropped rather than wrapped appropriately.

### Description of Issue Fix

The fix ensures proper layout by applying Auto Layout constraints that correctly position the platformView within its parent container, accounting for the specified margin values. By setting TranslatesAutoresizingMaskIntoConstraints to false, the platformView is aligned using explicit constraints on all edges (leading, trailing, top, and bottom) relative to the ContentView. This approach ensures the platformView respects its margins and resizes appropriately during orientation changes.

This ensures that any text elements within the view have the correct width information to wrap text appropriately in both portrait and landscape orientations.

Tested the behavior in the following platforms.
 
- [x] Windows
- [x] Mac
- [x] iOS
- [x] Android

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/15154

### Output

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="270" height="600"  src="https://github.com/user-attachments/assets/202ad28e-ec9c-446e-a290-6adf0215d502"> | <video width="270" height="600"  src="https://github.com/user-attachments/assets/5cfaf591-16d2-43cb-abf3-a1d27d7d98c3"> |

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/UIContainerCell.cs [hunk 1]
```diff
@@ -31,6 +31,13 @@ internal UIContainerCell(string cellId, View view, Shell shell, object context)
 			var platformView = view.ToPlatform();
 			ContentView.AddSubview(platformView);
 			platformView.AccessibilityTraits |= UIAccessibilityTrait.Button;
+			platformView.TranslatesAutoresizingMaskIntoConstraints = false;
+
+			var margin = view.Margin;
+			platformView.LeadingAnchor.ConstraintEqualTo(ContentView.LeadingAnchor, (nfloat)margin.Left).Active = true;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/UIContainerCell.cs:37]: Can you create a `NSLayoutConstraint[]` with all the constraints and then use the method `NSLayoutConstraint.ActivateConstraints(constraints);` to active all of them at once? Is more efficient than  individually.

File: src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ShouldFlyoutTextWrapsInLandscape.png
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ShouldFlyoutTextWrapsInLandscape.png:1]: Is this snapshot correct? Seems that the first item, the selected one, is clipped.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ShouldFlyoutTextWrapsInLandscape.png
Comment (BagavathiPerumal) [reply src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ShouldFlyoutTextWrapsInLandscape.png:1]: @jsuarezruiz, This appearance is consistent with the snapshots generated by the CI pipeline. When the device is in horizontal orientation, the CI system appears to crop the top region of iOS snapshots. As a result, similar cropping can be observed across other related test cases. For your reference, please refer to the attached snapshot link.
 
https://github.com/dotnet/maui/blob/main/src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/BorderBackgroundSizeUpdatesWhenRotatingScreen.png

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/UIContainerCell.cs (hunk 1 above)
Comment (BagavathiPerumal) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/UIContainerCell.cs]: @jsuarezruiz, I have updated the code based on your suggestion. Could you please share your concerns on this.

**Review by jsuarezruiz — APPROVED** [review]
