### PR TITLE
[iOS, Android, Windows] TextTransform Property Does Not Apply at Runtime When TextType="Html" Is Set on Label - fix

### LINKED ISSUE #29673: TextTransform Property Does Not Apply at Runtime When TextType="Html" Is Set on Label
### Description

When using the .NET MAUI Label control with TextType="Html" property, the TextTransform property does not take effect when changed during runtime. This behavior is inconsistent with the Label in plain text mode where text transformation changes are applied .

https://github.com/user-attachments/assets/8df87ae6-3abe-4b04-8720-df1a67e3d0ec

### Steps to Reproduce

1. Run the attached sample [FormattedTextPropertiesSample 3.zip](https://github.com/user-attachments/files/20441489/FormattedTextPropertiesSample.3.zip)
2. Observe the default Label with TextType set to "Plain"
3. Select a transformation option (e.g., "Uppercase") from the TextTransform radio button group
4. Observe that the text transformation is applied correctly to plain text 
5. Switch TextType to "Html" using the radio button
6. Select a transformation option (e.g., "Lowercase") from the TextTransform radio button group
7. Observe that text transformation does not update in the Label's HTML rendered text during runtime

Expected Behavior
The TextTransform property of the Label control should take effect immediately when changed during runtime, regardless of whether the Label's TextType is set to Text or Html.

Actual Behavior
When the Label's TextType is set to Html, changes to the TextTransform property made during runtime are not reflected in the rendered text.  

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/29673

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/d6682255-a19c-4acd-9f49-ea6eeb688403" width="300px"/>|<video src="https://github.com/user-attachments/assets/0ccf9e9a-59e0-4c3e-b96b-84d2c3d1dee6" width="300px"/>|

I was curious how the text would behave if we used something like:

`"<b>HTML <span style=\"text-transform:uppercase\">Lorem ipsum dolor sit amet</span>, consectetur adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus</b>";`

It turned out that the label property was overridden by the CSS style, which I believe is the correct and expected behavior. This applies to iOS, where the text-transform: uppercase style works as intended. However, on Android, the <span style="text-transform:uppercase"> has no effect — the text remains unchanged.

### CODE REVIEW

**Comment by mattleibow** [comment]
FYI https://github.com/dotnet/maui/pull/29685

File: src/Core/src/Platform/Android/TextViewExtensions.cs [hunk 1]
```diff
@@ -29,6 +28,12 @@ public static void UpdateTextHtml(this TextView textView, ILabel label)
 #pragma warning restore CS0618 // Type or member is obsolete
 		}
 
+		public static void UpdateTextHtml(this TextView textView, ILabel label)
```
Comment (mattleibow) [inline src/Core/src/Platform/Android/TextViewExtensions.cs:31]: Could you move this up so the diff doesn't look like a method was changed.

**Review by mattleibow — CHANGES_REQUESTED** [review]
Looks good.

This probably can do with just a device test as there is not a feature in the OS so the actual text is different.

Just a nit on the public method looking like it has changed.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Looking good but, could include a test?

**Comment by kubaflo** [comment]
> Looking good but, could include a test?

added

**Review by mattleibow — DISMISSED** [review]

**Comment by PureWeen** [comment]
@kubaflo can you rebase when you get a chance
