### PR TITLE
[Android,iOS] Fix Selection on CollectionView and VSM color changes for Layouts

### LINKED ISSUE #4108: [Android] CollectionView selection color not working
### Description

CollectionView selection color using **VisualState** not working

```
<Style TargetType="Grid">
    <Setter Property="VisualStateManager.VisualStateGroups">
        <VisualStateGroupList>
            <VisualStateGroup x:Name="CommonStates">
                <VisualState x:Name="Normal" />
                <VisualState x:Name="Selected">
                    <VisualState.Setters>
                        <Setter Property="BackgroundColor" 
                                Value="LightSkyBlue" />
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
        </VisualStateGroupList>
    </Setter>
</Style>
```

### Steps to Reproduce

1. Download [CollectionViewDemos.zip](https://github.com/dotnet/maui/files/7861241/CollectionViewDemos.zip)
2. Launch the App and navigate to the sample "Vertical list (Selection Color)".

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #7053: On Android CollectionView selection and scroll not working properly
### Description

Depending on how one encapsulates the CollectionView, scroll and selection fails.
If layed out with a simple [Content = collectionView;] in a ContentPage, the items scroll, but selection stops or offset once the list is scrolled away from the first page.
If layed out with a [new VerticalStackLayout { Children = { collectionView } };], the list does not scroll anymore.
A video provided here shows the issue.

https://github.com/hbraasch/CollectionViewScrollTester/blob/master/AnotherCollectionViewProblem.mp4

A reproduction project here recreates the issue:

https://github.com/hbraasch/CollectionViewScrollTester.git

### Steps to Reproduce

1. Run the application as provided
2. Select an item, then scroll the page, then try to select again. Notice the selection fail.
3. Click on the [Stack] menu item, the page will refresh (the way the [Content] is setup changed).
4. Try to scroll, it does not scroll anymore.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 - API 31, Android 11 - API 31

### Did you find any workaround?

None

### Relevant log output

_No response_

### LINKED ISSUE #7391: The style of is CollectionView selected item incorrect
### Description

The style of  is CollectionView  selected item incorrect.

https://user-images.githubusercontent.com/15171204/169652865-fe454f13-39c3-4931-8343-1e2f4c697206.mp4

[MauiAppCollectionViewVisualStateGroups.zip](https://github.com/dotnet/maui/files/8747654/MauiAppCollectionViewVisualStateGroups.zip)

### Steps to Reproduce

1. Download the attached project file
2. Run with Android

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 10

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

- Reverts #6249 using a better fix. 
- Aligns the usage of VSM with what happens on Windows. 

Basically if a user changed the layout color to Green on a selected state, when getting back to the Normal state the color would not be applied, this was working fine on Windos because windows [was setting the background to null. ](https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Windows/ControlExtensions.cs#L37) on iOS and Android we were ignoring when the color was set back to null, this fixes te issue. 

To test use the gallery, go to Controls/CollectionView/Selection Galleries/

Test different selection modes on Selection Modes page, and test also Visual states page

### Issues Fixed

Fixes #4108
Fixes #7053
Fixes #7391 (by reverting #6249)

### CODE REVIEW

File: src/Controls/src/Core/Platform/Android/Extensions/RecyclerViewExtensions.cs [hunk 1]
```diff
@@ -11,8 +11,8 @@ public static class RecyclerViewExtensions
 		public static void UpdateSelection(this RecyclerView recyclerView, SelectableItemsView selectableItemsView)
 		{
 			var mode = selectableItemsView.SelectionMode;
-
-			var adapter = (recyclerView.GetAdapter() as SelectableItemsViewAdapter<SelectableItemsView, IItemsViewSource>);
+			//TODO: on NET7 implement a ISelectableItemsViewAdapter interface on the adapter
+			var adapter = recyclerView.GetAdapter() as ReorderableItemsViewAdapter<ReorderableItemsView, IGroupableItemsViewSource>;
```
Comment (rmarinho) [inline src/Controls/src/Core/Platform/Android/Extensions/RecyclerViewExtensions.cs:15]: this cast was failing, and that's why clearing selection wasn't working. We need to find a better way to fix this cast, for example implement a Interface on the SelectableItemsViewAdapter

**Review by jsuarezruiz — COMMENTED** [review]
fix-7689

File: src/Core/src/Platform/Android/ViewExtensions.cs [hunk 2]
```diff
@@ -193,6 +193,10 @@ public static void UpdateBackground(this AView platformView, Paint? background)
 						platformView.Background = drawable;
 				}
 			}
+			else if(platformView is LayoutViewGroup)
+			{
+				platformView.Background = null;
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/ViewExtensions.cs:198]: Seeing these changes in Android and iOS, is something similar necessary in Windows?

**Review by jsuarezruiz — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
Just for future reference, the reason we need to skip on null paints is because it will go ahead and clear all platform backgrounds because we don't support default values. Windows "works" because it was a slightly lucky platform.

But, when the user sets a Background = null, we should not be doing nothing. Like, how is the user supposed to clear a background?

Instead, null should do something - clear the background.

If the user did not set a value, then we should do nothing. 

Related to:
 - https://github.com/dotnet/maui/issues/7803
 - https://github.com/dotnet/maui/issues/4356
