### PR TITLE
[iOS] RTL column mirroring in UICollectionView - fix

### LINKED ISSUE #32359: [iOS] FlowDirection="RightToLeft" issue in CollectionView version 9.0.120
### Description

Starting version 9.0.120

[iOS] FlowDirection="RightToLeft" not applied to CollectionView Header and not applied to ItemTemplate when using ItemsLayout =”VerticalGrid, columns > 1” 

IOS:

https://github.com/user-attachments/assets/e485e339-71e6-41f0-a01f-17a557e4e2f2

Android (working correctly):

https://github.com/user-attachments/assets/5bf4cd74-aa4e-463a-89c5-c8901e62021d

### Steps to Reproduce

version 9.0.120

Add FlowDirection =”RightToLeft” on ContentPage 

Add ItemsLayout="VerticalGrid, 4" on CollectionView

### Link to public reproduction project repository

https://github.com/Minaakram36/CollectionView-IOS-Issue-Sample-Project

### Version with bug

9.0.120 SR12

### Is this a regression from previous behavior?

previous versions had a lot of issues related to RTL in iOS that was fixed in this versions except for this issue

### Last version that worked well

_No response_

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Description of Change

Explicitly sets the semantic content attribute on the native UICollectionView to ensure compositional layouts mirror columns correctly in right-to-left (RTL) scenarios. This addresses an issue where the platform view's semantic attribute does not propagate to native children not backed by IView.

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/fb0784f5-7c7f-4b15-b2ab-ccdb2a7b8833" width="300px"></video>|<video src="https://github.com/user-attachments/assets/74a5180e-e7f5-45fc-bb88-ceb329fb2e4a" width="300px"></video>|

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/32359

### CODE REVIEW

**Comment by kubaflo** [comment]
@copilot please write a UI test for this PR based on this issue https://github.com/dotnet/maui/issues/32359

File: src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs [hunk 1]
```diff
@@ -312,6 +312,29 @@ public virtual void UpdateFlowDirection()
...
+						desiredAttr = UISemanticContentAttribute.ForceRightToLeft;
+						break;
+					case FlowDirection.MatchParent:
+						// Let it inherit from the parent view we just updated
+						desiredAttr = UISemanticContentAttribute.Unspecified;
+						break;
+				}
+
+				if (CollectionView.SemanticContentAttribute != desiredAttr)
+				{
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs]: Compositional and flow layouts may not re-query attributes immediately, requires to force a layout pass?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Could include an UITest to check that after switching to RTL: first column is right‑anchored?

**Review by PureWeen — APPROVED** [review]
