### PR TITLE
[iOS] Trigger OnNavigatedTo method when hide the nav bar and using swipe

### LINKED ISSUE #27143: Not trigger OnNavigatedTo method when hide the navi bar and using swipe back on iOS
### Description

Given mainpage hided the navigation bar, and user go to the second page,
when user try to swipe back to main page,
then code could not trigger the OnNavigatedTo method

https://github.com/user-attachments/assets/8efc4147-0507-4be3-90a2-db2f1c8d3bc6

### Steps to Reproduce

Click the "Go" button on MainPage
Swipe back to MainPage from SecondPage

### Link to public reproduction project repository

https://github.com/jingliancui/OnNavigatedToSwipeBackIssue

### Version with bug

9.0.30 SR3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

No

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/27143
Supersedes https://github.com/dotnet/maui/pull/27186

### CODE REVIEW

**Review by rmarinho — CHANGES_REQUESTED** [review]
Build is failing
```
/mnt/vss/_work/1/s/src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27143.cs(22,8): error CS1061: 'IApp' does not contain a definition for 'InteractivePopGesture' and no accessible extension method 'InteractivePopGesture' accepting a first argument of type 'IApp' could be found (are you missing a using directive or an assembly reference?) [/mnt/vss/_work/1/s/src/Controls/tests/TestCases.Android.Tests/Controls.TestCases.Android.Tests.csproj]
```

File: src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs [hunk 1]
```diff
@@ -241,11 +241,29 @@ public override void ViewDidLoad()
...
+
+			public GestureDelegate(Func<bool> shouldPop)
+			{
+				_shouldPop = shouldPop;
+			}
+
+			public override bool ShouldBegin(UIGestureRecognizer recognizer)
+			{
+				_shouldPop();
+				return true;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs:263]: Should be?
`return _shouldPop();`

**Comment by jingliancui** [comment]
hi @PureWeen 
may I know if this pr can be released in net10 GA please?

**Review by StephaneDelcroix — COMMENTED** [review]
## Multi-Model Consensus Review (5 models: claude-opus-4.6 ×2, claude-sonnet-4.6, gemini-3-pro-preview, gpt-5.3-codex)

### CI Status: ✅ Passing

### Consensus Findings (2+ models agreed)

🔴 **CRITICAL** `NavigationRenderer.cs:~244` -- `GestureDelegate.ShouldBegin()` **always returns `true`**. The lambda `() => _uiRequestedPop = true` is a `Func<bool>` where the assignment expression evaluates to `true`. This enables swipe-to-go-back even on the **root page** of the navigation stack. On iOS, triggering an interactive pop on the root `UINavigationController` with no page to pop to is a well-known cause of UI freeze (the controller enters a broken state where all gestures stop working). **Must add a guard**: return `false` when `ViewControllers.Length <= 1`.

🟡 **MODERATE** `NavigationRenderer.cs:~244` -- `_uiRequestedPop` is set to `true` in `ShouldBegin` (which fires when the gesture *starts*), not when it completes. If the user starts a swipe but cancels it (doesn't drag far enough), the flag is permanently `true`, corrupting the pop-tracking state for subsequent navigation events.

🟡 **MODERATE** -- Side-effect mutation (`_uiRequestedPop = true`) embedded inside a `Func<bool>` named `_shouldPop` is semantically misleading. The delegate appears to query state but actually mutates it while always returning `true`. Consider separating the flag-setting from the return value.

### Test Coverage
✅ Tests for Issue27143 included. Minor note: test uses `#if IOS || ANDROID` but the fix is iOS-only.

### Verdict: ⚠️ Request Changes
Good approach but has a critical root-page freeze risk. Specific asks:
1. Guard `ShouldBegin` with `ViewControllers?.Length > 1` check
2. Consider resetting `_uiRequestedPop` when gesture is cancelled (via `ShouldRecognizeSimultaneously` or gesture state observer)

**Review by StephaneDelcroix — COMMENTED** [review]
## Multi-Model Consensus Review (5 models: claude-opus-4.6 ×2, claude-sonnet-4.6, gemini-3-pro-preview, gpt-5.3-codex)

### CI Status: ✅ Passing

### Consensus Findings (2+ models agreed)

🔴 **CRITICAL** `NavigationRenderer.cs:~244` -- `GestureDelegate.ShouldBegin()` **always returns `true`**. The lambda `() => _uiRequestedPop = true` is a `Func<bool>` where the assignment expression evaluates to `true`. This enables swipe-to-go-back even on the **root page** of the navigation stack. On iOS, triggering an interactive pop on the root `UINavigationController` with no page to pop to is a well-known cause of UI freeze (the controller enters a broken state where all gestures stop working). **Must add a guard**: return `false` when `ViewControllers.Length <= 1`.

🟡 **MODERATE** `NavigationRenderer.cs:~244` -- `_uiRequestedPop` is set to `true` in `ShouldBegin` (which fires when the gesture *starts*), not when it completes. If the user starts a swipe but cancels it (doesn't drag far enough), the flag is permanently `true`, corrupting the pop-tracking state for subsequent navigation events.

🟡 **MODERATE** -- Side-effect mutation (`_uiRequestedPop = true`) embedded inside a `Func<bool>` named `_shouldPop` is semantically misleading. The delegate appears to query state but actually mutates it while always returning `true`. Consider separating the flag-setting from the return value.

### Test Coverage
✅ Tests for Issue27143 included. Minor note: test uses `#if IOS || ANDROID` but the fix is iOS-only.

### Verdict: ⚠️ Request Changes
Good approach but has a critical root-page freeze risk. Specific asks:
1. Guard `ShouldBegin` with `ViewControllers?.Length > 1` check
2. Consider resetting `_uiRequestedPop` when gesture is cancelled (via `ShouldRecognizeSimultaneously` or gesture state observer)
