### PR TITLE
Propagate semantic properties from FlyoutItem

### LINKED ISSUE #9066: The name property of an element should not contain class names like 'Microsoft.*.*' or 'Windows.*.*' as these are not usually information.
GitHubTags:
#.NET MAUI; #A11ySev2; #A11yAuto; #AI4D; #A11yMAS; #A11yTCS; #Benchmark; #DesktopApp; #Win11; #WCAG4.2.1; #GH_.NETMAUI_Win32_Jul2022; #Object Information​; #A11yeDAD;

### Description

The name property of an element should not contain class names like 'Microsoft.*.*' or 'Windows.*.*' as these are not usually information.

### Steps to Reproduce

1. Download the Zip file "pipeline-ui-maui-windows-1.0.0.1.zip" [https://github.com/NPavie/pipeline-ui-maui/releases/download/prototyp-v1/pipeline-ui-maui-windows-1.0.0.1.zip](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNPavie%2Fpipeline-ui-maui%2Freleases%2Fdownload%2Fprototyp-v1%2Fpipeline-ui-maui-windows-1.0.0.1.zip&data=05%7C01%7Cv-karanmore%40microsoft.com%7C9ede9d1f3bd94832f69b08da70c0255f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637946267837269549%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oq2mgje0beuTFasZdyvgf4hN8xLX2dyB903t%2Byejnbs%3D&reserved=0). 
2. Extract the "pipeline-ui-maui-windows-1.0.0.1.zip" file.
3. open the extracted file and navigate till "pipeline-ui-maui.exe" and press enter.
4. the New Job screen will open.
5. Start Accessibility insight for Desktop and see results.
The name property of an element should not contain class names like 'Microsoft ' or 'Windows ' as these are not usually information

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 Enterprise Version 21H2 OS build 22000.795

### Did you find any workaround?

_No response_

### Relevant log output

```shell
The name property of an element should be contain class names like 'Microsoft.*.*' or 'Windows.*.*' as these are not usually information.
```

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

- Propagate any `SemanticProperties` set to the templated `Grid` created inside the FlyoutItems. 
- Fix a few spots on WinUI where it would Tab to empty content. I've disabled the TabStop for the templated content controls used to render the flyoutitems and the flyout footer. This way it now tabs directly to the actual content. By default the Navigation items on the WinUI NavigationView can be navigated via arrow keys not by tab. 
  -  One thing to note here is that navigating via tab/arrow keys is broken on WinUI if you do it with a debugger [attached](https://github.com/microsoft/microsoft-ui-xaml/issues/2521#issuecomment-655209746). So, after you've launched your code stop the debugger and then re-launch the app to test

### Issues Fixed
Fixes #9066

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellFlyoutRecyclerAdapter.cs [hunk 1]
```diff
@@ -281,8 +279,6 @@ public Element Element
 					if (_element != null)
 					{
 						_shell.AddLogicalChild(View);
-						AutomationPropertiesProvider.AccessibilitySettingsChanged(_itemView, value);
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellFlyoutRecyclerAdapter.cs:284]: This is now propagated through `SemanticProperties` bindings

**Review by rachelkang — CHANGES_REQUESTED** [review]
As shared offline, the current behavior I'm noticing is as follows:
* Narrator announces invisible/nonexistent images for each of the flyout items
* Narrator reads the flyout item text twice - both on the item, and the text label itself
* Keyboard navigation doesn't work as expected

That being said, the core issue is indeed fixed! The flyout item text is read aloud for how it's shown on the UI, and not based on the name of the control behind the scenes

**Comment by PureWeen** [comment]
@rachelkang should be fixed can you try again?

**Review by rachelkang — APPROVED** [review]
