### PR TITLE
iOS TabbedPage and NavigationPage measuring fixes

### LINKED ISSUE #3906: [iOS] Convert NavigationRenderer to an implementation IViewHandler
### Description

Change NavigationRenderer over to implementing IViewHandler instead of IVisualElementRenderer

### (Public) API Changes

No Changes

### Usage Scenarios

Base NavigationRenderer  off IViewHandler 

### Backward Compatibility

Possible API compatibility with previous renderer so that users can use existing custom renderer

### Difficulty

Low

### LINKED ISSUE #3907: [iOS] Convert PhoneFlyoutPageRenderer to an implementation IViewHandler
### Description

- Change PhoneFlyoutPageRenderer  over to implementing IViewHandler instead of IVisualElementRenderer
- Just use the PhoneFlyoutPageRenderer for both iPads/iPhones. This is currently what Shell does. Reasoning here https://github.com/xamarin/Xamarin.Forms/issues/2017#issuecomment-554466816 

### (Public) API Changes

No Changes

### Usage Scenarios

Base PhoneFlyoutPageRenderer  off IViewHandler

### Backward Compatibility

Possible API compatibility with previous renderer so that users can use existing custom renderer

### Difficulty

Low

### LINKED ISSUE #3908: [iOS] Convert TabbedRenderer to an implementation of IViewHandler
### Description

Change TabbedRenderer  over to implementing IViewHandler instead of IVisualElementRenderer

### (Public) API Changes

No Changes

### Usage Scenarios

Base TabbedRenderer  off IViewHandler

### Backward Compatibility

Possible API compatibility with previous renderer so that users can use existing custom renderer

### Difficulty

Low

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change ###

Rework all the measuring/layout code for the iOS TabbedRenderer and NavigationRenderer to follow the layout rules of .NET MAUI

- Added code to all platforms `TabbedHandler`s and `NavigationHandler`s so that the `Frame` on the xplat control gets set
- Added code to `ContentPage.impl.cs` so it's `Frame` always gets set
- Copied over large titles sample
  - It seems like this is working based on the rules of the sample. @rmarinho ?
  - This also involved some fixes to ListViewRenderer to fix some issues with the header/footer not rendering 
  - If you find issues with large titles please just log a bug

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the WinUI, Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

File: src/Compatibility/Core/src/Handlers/NavigationPage/iOS/NavigationRenderer.cs [hunk 1]
```diff
@@ -480,7 +470,7 @@ void ValidateNavbarExists(Page newCurrentPage)
 			//if the last time we did ViewDidLayoutSubviews we had other value for _hasNavigationBar
 			//we will need to relayout. This is because Current is updated async of the layout happening
 			if (_hasNavigationBar != NavigationPage.GetHasNavigationBar(newCurrentPage))
-				ViewDidLayoutSubviews();
+				View.InvalidateMeasure(Element);
```
Comment (PureWeen) [inline src/Compatibility/Core/src/Handlers/NavigationPage/iOS/NavigationRenderer.cs:473]: call `ViewDidLayoutSubviews` yourself doesn't seem like the best idea.  I've tested hiding and showing the navbar a few different ways and invalidating the measure seems to do the job

File: src/Compatibility/Core/src/Handlers/NavigationPage/iOS/NavigationRenderer.cs [hunk 2]
```diff
@@ -159,9 +162,9 @@ public override void ViewDidDisappear(bool animated)
 			PageController.SendDisappearing();
 		}
 
-		public override void ViewDidLayoutSubviews()
+		public override void ViewWillLayoutSubviews()
```
Comment (PureWeen) [inline src/Compatibility/Core/src/Handlers/NavigationPage/iOS/NavigationRenderer.cs:165]: I moved pretty much all of  this `Frame` code into the `ParentingViewController`. The `ParentingViewController` knows what size frame it wants based on the offset from the navbar so it seemed to work better in the flow of things to set offsets in there

File: src/Controls/src/Core/HandlerImpl/ContentPage.Impl.cs [hunk 3]
```diff
@@ -31,6 +31,7 @@ Size IContentView.CrossPlatformMeasure(double widthConstraint, double heightCons
 
 		Size IContentView.CrossPlatformArrange(Rectangle bounds)
 		{
+			Frame = bounds;
```
Comment (PureWeen) [inline src/Controls/src/Core/HandlerImpl/ContentPage.Impl.cs:34]: Without this the Frame of the ContentPage never gets set

File: src/Controls/src/Core/HandlerImpl/NavigationPage/NavigationPage.Impl.cs [hunk 4]
```diff
@@ -33,26 +33,10 @@ public partial class NavigationPage : INavigationView, IToolbarElement
...
 		{
-			if (Content is IView view)
-			{
-				_ = view.Measure(widthConstraint, heightConstraint);
-			}
-
-			return new Size(widthConstraint, heightConstraint);
-		}
-
-		protected override Size ArrangeOverride(Rectangle bounds)
```
Comment (PureWeen) [inline src/Controls/src/Core/HandlerImpl/NavigationPage/NavigationPage.Impl.cs:46]: AFAICT this code was never getting called. Maybe this was just here for legacy shimmed navigation pages? This code was causing issues on iOS because it kept trying to measure the page as large as the NavigationPage. I realize the fix for this is to use `PageContainerArea` but I don't think we really need to use `PageContainerArea`. Each platform just sets the platform size of the pages and then from there everything seems to propagate up to the xplat code successfully

Comment (hartez) [reply src/Controls/src/Core/HandlerImpl/NavigationPage/NavigationPage.Impl.cs:46]: I think you're correct that this was just for making the shimmed stuff work.

**Review by hartez — APPROVED** [review]
Looks fine; if any of it causes problems, we'll know soon enough :)
