### PR TITLE
Correctly render Shape Background (and BackgroundColor)

### LINKED ISSUE #5974: Setting BackgroundColor from code doesn't do anything for Shapes
### Description

As the title says. It doesn't work from Xaml either:

```xml
<Ellipse  WidthRequest="150" HeightRequest="50" StrokeThickness="10" Stroke="Green"  BackgroundColor="Blue"/>
```

### Steps to Reproduce

Use the hit testing tool from #5892 (Samples app) and click on the Ellipse or the RoundedRectangle.

### Affected platforms

Android, Windows

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Correctly render Shape Background (and BackgroundColor).

image

To test the changes, navigate to the Shapes samples in the .NET MAUI Gallery. In the Aspect sample every shape (Path) use a gray BackgroundColor.

### Issues Fixed

Fixes #5974

### CODE REVIEW

File: src/Core/tests/DeviceTests/Handlers/ShapeView/ShapeViewHandlerTests.cs [hunk 1]
```diff
@@ -2,18 +2,40 @@
...
 namespace Microsoft.Maui.DeviceTests
 {
 	[Category(TestCategory.ShapeView)]
 	public partial class ShapeViewHandlerTests : HandlerTestBase<ShapeViewHandler, ShapeViewStub>
 	{
+		[Theory(DisplayName = "Shape Background Initializes Correctly")]
+		[InlineData(0xFF0000)]
+		[InlineData(0x00FF00)]
+		[InlineData(0x0000FF)]
+		public async Task BackgroundInitializesCorrectly(uint color)
```
Comment (jsuarezruiz) [inline src/Core/tests/DeviceTests/Handlers/ShapeView/ShapeViewHandlerTests.cs:16]: Updated the PR to include a device test.

**Review by mattleibow — APPROVED** [review]
