### PR TITLE
Fix ImageConverter

### LINKED ISSUE #5452: Toolbar Icons missing on Windows
### Description

Opening up a NavigationPage with a child having ToolBarItems specified only shows icons if they are used elsewhere on the page (for example in an IconButton). For example if you use the XAML below on Windows the X and Z icons show up, but Y does not (all 3 show up on Android).
```
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="Letter X" IconImageSource="{StaticResource GlyphX}"/>
        <ToolbarItem Text="Letter Y" IconImageSource="{StaticResource GlyphY}"/>
        <ToolbarItem Text="Letter Z" IconImageSource="{StaticResource GlyphZ}"/>
    </ContentPage.ToolbarItems>

    <VerticalStackLayout>
        <ImageButton Source="{StaticResource GlyphX}" HorizontalOptions="Center"/>
        <!--<ImageButton Source="{StaticResource GlyphY}" HorizontalOptions="Center"/>-->
        <ImageButton Source="{StaticResource GlyphZ}" HorizontalOptions="Center"/>
    </VerticalStackLayout>

```
If you uncomment the 'Y' Imagebutton, the 'Y' icon will show up in the toolbar.

### Steps to Reproduce

1. Unzip the project from [MAUIToolBar.zip](https://github.com/dotnet/maui/files/8311920/MAUIToolBar.zip)
2. Compile and run it on Android and Windows, you should get the result illustrated below.
3. Note the missing 'Y' icon in the tool bar on the Windows version.

MAUIToolBar

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10 

### Did you find any workaround?

Yes, it turns out the icon shows up if it is declared on the page - it does not need to actually be shown, so you can set IsVisible false on the item that uses the Icon on the page and the icon will still show in the tool bar.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by cshung**
### Description of Change

We accidentally changed the `ImageConverter` in https://github.com/dotnet/maui/commit/5e8e41a691d0c8b8ca759c182e6ae89ea3d5c3a3 such that it no longer converts a MAUI ImageSource to a Windows ImageSource.

A Windows ImageSource is required because it is bind to the `Source` of a Windows Image [here](https://github.com/dotnet/maui/blob/d497f0a1eafe5269b0d0b956667c7e393bf29696/src/Controls/src/Core/HandlerImpl/Toolbar/Toolbar.Windows.cs#L52).

This change fixed the ImageConverter so it performs the correct conversion, now it works to show all 3 icons.

### Issues Fixed

Fixes #5452

### CODE REVIEW

File: src/Controls/src/Core/Platform/Windows/ImageConverter.cs [hunk 1]
```diff
@@ -8,9 +9,16 @@ public class ImageConverter : Microsoft.UI.Xaml.Data.IValueConverter
...
+			ImageSource source = value as ImageSource;
+			if (source == null)
+			{
+				return null;
+			}
+
+			IMauiContext context = source.FindMauiContext(true);
+			IImageSourceServiceProvider imageSourceServiceProvider = context.Services.GetRequiredService<IImageSourceServiceProvider>();
+			IImageSourceService imageSourceService = imageSourceServiceProvider.GetImageSourceService(source);
+			return imageSourceService.GetImageSourceAsync(source).Result;
```
Comment (PureWeen) [inline src/Controls/src/Core/Platform/Windows/ImageConverter.cs:21]: Previously we were using this extension method to return the value from here "safely"

https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Platform.UAP/ImageConverter.cs#L12

should we go back to that?
https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Core/Internals/AsyncValue.cs#L95

`.result` is always scary

**Review by PureWeen — APPROVED** [review]

**Review by Redth — APPROVED** [review]
