### PR TITLE
[Windows] Fix Border corners clipping issue

### LINKED ISSUE #9129: Clipping an Image with a Border has a gap on Windows
### Description

XAML is

```
    <Grid BackgroundColor="Blue">
        <Grid.RowDefinitions>
            <!-- label, search -->
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>
        <HorizontalStackLayout Grid.Row="0" Margin="20">
            <!-- meal all -->
            <Border Stroke="LightGray" StrokeThickness="3">
                <Border.StrokeShape>
                    <RoundRectangle CornerRadius="20" />
                </Border.StrokeShape>
                <VerticalStackLayout BackgroundColor="#f0f0f0">
                    <Image Aspect="AspectFill" HeightRequest="100" Source="meal_all.jpg" WidthRequest="100" />
                    <Label HorizontalTextAlignment="Center" Margin="0,5" Text="All" />
                </VerticalStackLayout>
            </Border>
            <!-- meal noodle -->
            <Border Stroke="LightGray" StrokeThickness="3">
                <Border.StrokeShape>
                    <RoundRectangle CornerRadius="20" />
                </Border.StrokeShape>
                <Grid BackgroundColor="#f0f0f0">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                    </Grid.RowDefinitions>
                    <Image Grid.Row="0" Aspect="AspectFill" HeightRequest="100" Source="meal_noodle.jpg" WidthRequest="100" />
                    <Label Grid.Row="1" HorizontalTextAlignment="Center" Margin="0,5" Text="Noodle" />
                </Grid>
            </Border>
            <!-- meal rice -->
            <Border Stroke="LightGray" StrokeThickness="3">
                <Border.StrokeShape>
                    <RoundRectangle CornerRadius="20" />
                </Border.StrokeShape>
                <VerticalStackLayout BackgroundColor="#f0f0f0">
                    <Image Aspect="AspectFill" HeightRequest="100" Source="meal_rice.jpg" WidthRequest="100" />
                    <Label HorizontalTextAlignment="Center" Margin="0,5" Text="Rice" />
                </VerticalStackLayout>
            </Border>
        </HorizontalStackLayout>
    </Grid>
```

Android API 30 is okay

image

Window 10 has gap

image

### Public API Changes

.

### Intended Use-Case

please reduce gap within Border

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix Border corners clipping mistake on Windows. Checking [x](https://github.com/dotnet/maui/pull/14402) I realized that the changes applied in https://github.com/dotnet/maui/pull/10964 in Android and iOS were not in Windows.

We was clipping using the Border shape. That is correct in many cases but not always. Using a RoundRectangle, the Corner Radius value is not the same in the inner or outer. We want in this case user the inner value.
image

Before
border-changes-before
Notice the internal white space between the content and the border.

After
border-changes-after

Fix #9129

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

File: src/Core/src/Platform/Windows/ContentPanel.cs [hunk 1]
```diff
@@ -96,18 +96,21 @@ public void UpdateBackground(Paint? background)
 			_borderPath.UpdateBackground(background);
 		}
 
-		public void UpdateBorderShape(IShape borderShape)
+		public void UpdateBorderStroke(IBorderStroke borderStroke)
```
Comment (hartez) [inline src/Core/src/Platform/Windows/ContentPanel.cs:99]: This is a breaking change (changing the name of the public method). Maybe `UpdateBorderStroke` should be `internal`, and `UpdateBorderShape` should remain, but do nothing and be marked obsolete.

**Review by hartez — DISMISSED** [review]

File: src/Core/src/Platform/Windows/ContentPanel.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Windows/ContentPanel.cs]: Updated to avoid the breaking change.

File: src/Core/src/Platform/Windows/ContentPanel.cs [hunk 2]
```diff
@@ -97,18 +97,32 @@ public void UpdateBackground(Paint? background)
...
 		}
 
+		[Obsolete("Use Microsoft.Maui.Platform.UpdateBorderStroke instead")]
 		public void UpdateBorderShape(IShape borderShape)
 		{
-			_borderShape = borderShape;
+			if (borderShape is null || _borderPath is null)
+				return;
+
+			_borderPath.UpdateBorderShape(borderShape, ActualWidth, ActualHeight);
```
Comment (rmarinho) [inline src/Core/src/Platform/Windows/ContentPanel.cs:106]: I would refactor this to a private method so it can be called from here and `UpdateBorderStroke`

File: src/Core/src/Platform/Windows/ContentPanel.cs [hunk 3]
```diff
@@ -97,18 +97,32 @@ public void UpdateBackground(Paint? background)
...
+			UpdateContent();
+			UpdateClip(borderShape);
+		}
+		
+		internal void UpdateBorderStroke(IBorderStroke borderStroke)
```
Comment (rmarinho) [inline src/Core/src/Platform/Windows/ContentPanel.cs:111]: I think this can be public on net8 no @hartez ? or else the Obsolete comment will not make sense since this is internal users can't call it

File: src/Core/src/PublicAPI/net-windows/PublicAPI.Shipped.txt [hunk 4]
```diff
@@ -1551,7 +1551,6 @@ Microsoft.Maui.Platform.ColorExtensions
 Microsoft.Maui.Platform.ContentPanel
 Microsoft.Maui.Platform.ContentPanel.ContentPanel() -> void
 Microsoft.Maui.Platform.ContentPanel.UpdateBackground(Microsoft.Maui.Graphics.Paint? background) -> void
-Microsoft.Maui.Platform.ContentPanel.UpdateBorderShape(Microsoft.Maui.Graphics.IShape! borderShape) -> void
```
Comment (rmarinho) [inline src/Core/src/PublicAPI/net-windows/PublicAPI.Shipped.txt:1554]: This is wrong no? we are adding and removing?

**Review by rmarinho — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Windows/ContentPanel.cs (hunk 2 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Windows/ContentPanel.cs:106]: Nice suggestion, created.

File: src/Core/src/PublicAPI/net-windows/PublicAPI.Shipped.txt (hunk 4 above)
Comment (jsuarezruiz) [reply src/Core/src/PublicAPI/net-windows/PublicAPI.Shipped.txt]: Right, fixed.

**Review by rmarinho — CHANGES_REQUESTED** [review]
I was testing the gallery and seems some calculations are still wrong when we have content inside, we can see this using the gallery

-Go to the Border Playground
- Set Border Shape as Rectangle
- Set a solid Border
- Increase the Border Width to around 15 
- You can see the text gets clipped

Screenshot 2023-06-22 at 16 53 24

here's how it looks on Android, seems ok:

Screenshot_1687448718

**Comment by jsuarezruiz** [comment]
Applied changes to fix the issue detected by Rui:
fix-border-sizing

**Comment by jsuarezruiz** [comment]
Added device tests:
image

**Review by rmarinho — APPROVED** [review]
