### PR TITLE
[macOS] Fix crash using Shell SearchHandler on Catalyst

### LINKED ISSUE #11823: [Scenario Days 02 Dec] Crash trying to use SearchHandler
### Description

Crash trying to use SearchHandler.

`Object reference not set to an instance of an object.`

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/scenariodays-120222/tree/main/src/ScenarioDays.Sample2
2. Launch the App on Android.
3. Use the Searcher from the header.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/scenariodays-120222/tree/main/src/ScenarioDays.Sample2

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Ventura

### Did you find any workaround?

_No response_

### Relevant log output

```shell
at Microsoft.Maui.Controls.ViewExtensions.GetParentsPath(Element self)+MoveNext()
   at Microsoft.Maui.Controls.ViewExtensions.FindMauiContext(Element element, Boolean fallbackToAppMauiContext)
   at Microsoft.Maui.Controls.Platform.Compatibility.UIContainerCell..ctor(String cellId, View view, Shell shell, Object context)
   at Microsoft.Maui.Controls.Platform.Compatibility.UIContainerCell..ctor(String cellId, View view)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSearchResultsRenderer.GetCell(UITableView tableView, NSIndexPath indexPath)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at ScenarioDays.Sample2.Program.Main(String[] args) in /Users/javiersuarezruiz/Projects/ScenarioDays.Sample2/ScenarioDays.Sample2/Platforms/MacCatalyst/Program.cs:line 13
```

### LINKED ISSUE #13470: SearchHandler doesn’t show results on iOS
### Description

SearchHandler shows always white space with binding and crashes after setting ItemsSource manually. 

### Steps to Reproduce

1. Set binding for ItemsSource
2. Update binding property

or

Set a list to ItemsSource

### Link to public reproduction project repository

—-

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iPadOS 16.2

### Did you find any workaround?

_No response_

### Relevant log output

```shell
"Object reference not set to an instance of an object."

" at Microsoft.Maui.Controls.ViewExtensions.GetParentsPath(Element self)+MoveNext()\n at Microsoft.Maui.Controls.ViewExtensions.FindMauiContext(Element element, Boolean fallbackToAppMauiContext)\n at Microsoft.Maui.Controls.Platform.Compatibility.UIContainerCell..ctor(String cellId, View view, Shell shell, Object context)\n at Microsoft.Maui.Controls.Platform.Compatibility.UIContainerCell..ctor(String cellId, View view)\n at Microsoft.Maui.Controls.Platform.Compatibility.ShellSearchResultsRenderer.GetCell(UITableView tableView, NSIndexPath indexPath)\n at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)\n at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)\n at {Project}.Program.Main(String[] args) in {project path}\\Platforms\\iOS\\Program.cs:line 13"
```

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix crash using Shell SearchHandler on Catalyst. 

This PR include changes to avoid get the Shell MauiContext (could be null here) and use the View MauiContext directly. 

### Issues Fixed

Fixes #11823 
Fixes #13470

### CODE REVIEW

**Comment by rmarinho** [comment]
@jsuarezruiz seems tests are crashing on iOS , I merged main and still fail, so can you please check if its related with the change? thanks

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz seems tests are crashing on iOS , I merged main and still fail, so can you please check if its related with the change? thanks

Reviewed, the build is now passing.

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/UIContainerCell.cs [hunk 1]
```diff
@@ -24,7 +24,7 @@ internal UIContainerCell(string cellId, View view, Shell shell, object context)
 
 			if (_renderer == null)
 			{
-				_renderer = (IPlatformViewHandler)view.ToHandler(shell.FindMauiContext());
+				_renderer = (IPlatformViewHandler)view.ToHandler(shell != null ? shell.FindMauiContext() : view.FindMauiContext());
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/UIContainerCell.cs:27]: I think these should be reversed. Things should probably try for the `MauiContext` that's closes in the hierarchy first

```suggestion
				_renderer = (IPlatformViewHandler)view.ToHandler(view.FindMauiContext() ?? shell.FindMauiContext());
```

can we add a test? Do you by chance know why shell is null here? Is the error here further up in the code? Like, the bug here is that shell null not that we need to use view.FindMauiContext?

Comment (jsuarezruiz) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/UIContainerCell.cs:28]: I have added a device test but it only validates that there are no problems creating the SearchHandler. However, the crash occurs when creating the list of search bar suggestions that is created by tapping and typing. Without a UI Test I think we cannot validate this scenario.

File: src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Android.cs [hunk 2]
```diff
@@ -259,6 +259,30 @@ public async Task SwappingOutAndroidContextDoesntCrash()
 			}, mauiContextStub2);
 		}
 
+		[Fact]
+		public async Task SearchHandlerRendersCorrectly()
```
Comment (PureWeen) [inline src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Android.cs:263]: Does this test need to be moved? The code change is on iOS but this test will only run on Android

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Android.cs (hunk 2 above)
Comment (jsuarezruiz) [reply src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Android.cs]: Right, moved the test to run it in all the platforms.

**Review by PureWeen — APPROVED** [review]

**Review by Redth — APPROVED** [review]

**Comment by espenrl** [comment]
@jsuarezruiz  I'm having this issue on iOS .NET 7. Would love a backport.
