### PR TITLE
[iOS] Fix wrong gray color using transparent in iOS gradients

### LINKED ISSUE #14766: Linear Gradients constantly have a grey hue in .net Maui on iOS
### Description

Setting a gradient brush causes a persistent grey hue to be present in the view where the brush is set to the background (see image).
Simulator Screen Shot - iPad (9th generation) - 2023-04-25 at 11 53 53

### Steps to Reproduce

I started a basic sample project with this as the following code as the MainPage (no other changes to the project).  I've also tried commenting out all the default styles and colors, but that doesn't seem to change anything either.   This occurs on iPads running in release mode and debug mode, and in the simulator.

```cs
public class MainPage : ContentPage
{
	public MainPage()
	{
        var contentGrid = new Grid
        {
            HorizontalOptions = LayoutOptions.Center,
            VerticalOptions = LayoutOptions.Center,
            BackgroundColor = Colors.WhiteSmoke,
            WidthRequest = 500,
            HeightRequest = 500,
            RowDefinitions =
            {
                new RowDefinition { Height = GridLength.Star },
                new RowDefinition { Height = 100 }
            }
        };

        var boxView = new BoxView
        {
            HorizontalOptions = LayoutOptions.Fill,
            VerticalOptions = LayoutOptions.Fill,
            Color = Colors.Transparent,
            Background = new LinearGradientBrush
            {
                StartPoint = new Point(0, 0),
                EndPoint = new Point(0, 1),
                GradientStops = new GradientStopCollection
                {
                    new(Colors.Transparent, 0.1f),
                    new(Colors.White, 1f)
                }
            }
        };

        contentGrid.Add(boxView, 0, 1);

        Content = new Grid
        {
            HorizontalOptions = LayoutOptions.Fill,
            VerticalOptions = LayoutOptions.Fill,

            Children =
            {
                contentGrid
            }
        };
	}
}
```

### Link to public reproduction project repository

https://github.com/BECInc/LinearGradientSample

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

iOS

### Affected platform versions

iOS 16.2

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #17366: [regression/8.0.0] LinearGradient from transparent to white is getting gray at the bottom
### Description

I use a ContentView with a Background Image and stacked on top a LinearGradientBrush like this:

```xaml
<Grid RowDefinitions="Auto">

    <!-- BackgroundImage and LinearGradient -->
    <Image x:Name="BackgroundImage" Grid.Row="0"  Source="radiant_gradient.png" Aspect="AspectFill" />
    <Grid BackgroundColor="Transparent"  Grid.Row="0">
        <Grid.Background>
            <LinearGradientBrush EndPoint="0,1">
                <GradientStop Color="Transparent" Offset="0.1" />
                <GradientStop Color="White" Offset="1.0" />
            </LinearGradientBrush>
        </Grid.Background>
    </Grid>
    
</Grid>
```

grafik

<br/>
<br/>

**BackgroundImage without LinearGradientBrush**:

grafik

<br/>
<br/>

**BrackgroundImage displayed with correct LinearGradientBrush on Android**:

grafik

<br/>
<br/>
<br/>

**Problem:** 

In **Visual Studio 2022 17.8 - Preview 1** with **.NET 8.0** the LinearGradientBrush is getting **gray at the Bottom** instead of being white as expected (see SCreenshots above and attached sample application)

This used to work in .NET 7.0 

### Steps to Reproduce

- Visual Studio 2022 17.8 - Preview 1
- .NET 8.0
- Launch sample application with iPhone 14 iOS 16.2 Simulator (or any other iOS-Simulator)
- If you can see the wrong LinearGradientBrush effect when application was started fine, otherwise switch to View2 and back to View1 and you will see it as in the screenshots above

### Link to public reproduction project repository

https://github.com/MAUIoxo/LinearGradientBrushApp_17366

### Version with bug

8.0.100-rc.1.23455.8
8.0.100-preview.7.23376.3  (coming with VS 2022 17.8)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

No workaround available
Tried with StackLayout instead of Grid in BackgroundImageView.xaml, but without effect

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix wrong gray color using transparent in iOS gradients.

Simulator Screenshot - iPhone 15 - 2023-09-27 at 12 29 30

If the GradientStop color is transparent, use the next one Color with Alpha 0. In other case, the effect is not correct because use a Clear default color and can see a black color in the gradient from one to other color.
More info: https://betterprogramming.pub/the-proper-way-of-creating-a-transparent-gradient-layer-in-ios-b082daa866b1

To test the changes can use the added sample to the Frame sample in the .NET MAUI Gallery.
image

### Issues Fixed

Fixes #17366
Fixes #14766

### CODE REVIEW

File: src/Controls/src/Core/Platform/iOS/Extensions/BrushExtensions.cs [hunk 1]
```diff
@@ -251,6 +251,31 @@ static NSNumber[] GetCAGradientLayerLocations(List<GradientStop> gradientStops)
 			}
 		}
 
+		static CGColor[] GetCAGradientLayerColors(List<GradientStop> gradientStops)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/iOS/Extensions/BrushExtensions.cs:254]: Are mostly pending changes from https://github.com/xamarin/Xamarin.Forms/pull/13401

Comment (mattleibow) [reply src/Controls/src/Core/Platform/iOS/Extensions/BrushExtensions.cs:254]: Should this rather be a reference to the code in Core? Instead of a duplicate? Might be possible if the method was internal.

File: src/Core/src/Graphics/PaintExtensions.iOS.cs [hunk 2]
```diff
@@ -165,5 +165,30 @@ static NSNumber[] GetCAGradientLayerLocations(List<PaintGradientStop> gradientSt
...
+				return new CGColor[0];
+
+			CGColor[] colors = new CGColor[gradientStops.Count];
+
+			int index = 0;
+			foreach (var gradientStop in gradientStops)
+			{
+				if (gradientStop.Color == Colors.Transparent)
+				{
+					var color = gradientStops[index == 0 ? index + 1 : index - 1].Color;
```
Comment (mattleibow) [inline src/Core/src/Graphics/PaintExtensions.iOS.cs:181]: What happens if there are multiple transparent together? trans at 0, trans at 0.3 and then red at 1? Also, what happens if the transparent is between two colors? red, trans, green.

nit: this feels like a for loop instead of foreach. I personally don't like the rando index variable outside the loop. But I am also just weird.

Comment (jsuarezruiz) [reply src/Core/src/Graphics/PaintExtensions.iOS.cs:181]: Added a new sample and a new Device Test to validate that case:
image

**Comment by jsuarezruiz** [comment]
Received request from Customer Services and Support team, could we get another review?. Thanks in advance.

**Review by rmarinho — APPROVED** [review]
