### PR TITLE
Call disconnect on previous handler with Shell

### LINKED ISSUE #6732: Switching language on Android results in a crash while navigating if resource manager used (i18n)
### Description

Hello,

I have a MAUI app with 2 resources (ResourceManager), one FR, one EN.

It works really well with the package Microsoft.Extensions.Localization : I'm able to load the correct translation based on the user culture. I can navigate between pages, everything works great.

But if I switch the main language in Android's settings, I go back to the app (was in background while I changed the settings), I try to navigate to a new page to see if the translations are fine, it crashes. (I don't expect live changes when changing my language but at least, while navigating to a new page, I expect the correct translations to be found)

Here is the error 
Java.Lang.IllegalArgumentException: 'No view found for id 0x1 (unknown) for fragment ShellItemRenderer{dd448d5} (e47cc305-1d52-4c02-9754-e65f4ffa09df id=0x1)'

No callstack, only external code

### Steps to Reproduce

Create an app (I use AppShell) with 2 pages.

Add 2 resources to the project and a dependence Microsoft.Extensions.Localization package.
Don't forget to register the dependencie: builder.Services.AddLocalization();
Create a couple of key/values.

Launch the app on Android. See it works.

Go to Android settings, switch from english to the language you added in your 2nd resx.

Go back to the app, try to navigate.

Boom

Couldn't test on Windows as you have to log off to change the language.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

Not yet

### Relevant log output

```shell
[enpharma.mobil] Invalid ID 0x00000001.
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.MY_APP_BUNDLEID_WAS_SET_HERE, PID: 29817
[AndroidRuntime] java.lang.IllegalArgumentException: No view found for id 0x1 (unknown) for fragment ShellItemRenderer{dd448d5} (e47cc305-1d52-4c02-9754-e65f4ffa09df id=0x1)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:873)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:193)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6669)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
**Java.Lang.IllegalArgumentException:** 'No view found for id 0x1 (unknown) for fragment ShellItemRenderer{dd448d5} (e47cc305-1d52-4c02-9754-e65f4ffa09df id=0x1)'
```

### LINKED ISSUE #7940: AppShell crashed on Android with "No view found for id 0x1 (unknown) for fragment ShellItemRenderer..."
### Description

I'm working on an android app using MAUI GA and encounter an annoying error of  "java.lang.IllegalArgumentException: No view found for id 0x1 (unknown) for fragment ShellItemRenderer..." w/o a fix. I have spent a couple of days debugging and searching but no solution found. To a point that I have to believe this must be a MAUI AppShell bug. I have created a repository on github of the simple MAUI project in case anyone wants to check.  

https://github.com/jzhao8402/MauiApp1

The project is actual a barebone AppShell project with only two flyout items for a Login Page and a About Page.  But it's good enough to reproduce the problem. I'm able to re-produce the bug on both the android emulator and physical devices. Not sure if I missed any critical thing to make this simple shell working properly. Any help or hint would be appreciated. I'm frustrated because I need to build my faith to go with .Net MAUI. On top of this one, I'm also struggling with the Google Firebase push notification, android alert sound. None of these is out of box of MAUI. 

### Steps to Reproduce

1. Launch the app, it'll work well on freshly start and you can use the flyout menu to switch the pages back and forth.
2. Use the android back button to "close" the app.
3. Tap the app icon to relaunch the app, or use the android history button to find the app in the stack and bring it back; the app will display the last page before you closed the app.
4. Use the flyout menu to switch the page, the app will crash instantly with the following error:
Java.Lang.IllegalArgumentException: 'No view found for id 0x1 (unknown) for fragment ShellItemRenderer

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 21 & up

### Did you find any workaround?

Not yet.  

### Relevant log output

```shell
[nyname.mauiapp] Invalid ID 0x00000001.
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.companyname.mauiapp1, PID: 17697
[AndroidRuntime] java.lang.IllegalArgumentException: No view found for id 0x1 (unknown) for fragment ShellItemRenderer{5a58e67} (8afe0b23-ef5c-4497-802e-ae781435f2f3 id=0x1)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:938)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:223)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7656)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
**Java.Lang.IllegalArgumentException:** 'No view found for id 0x1 (unknown) for fragment ShellItemRenderer{5a58e67} (8afe0b23-ef5c-4497-802e-ae781435f2f3 id=0x1)'
```

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

When swapping in a new handler for shell call disconnect on the previous handler so that the xplat events don't trigger operations on the old set of handlers. There's a larger issue here where I think we need to call `SetVirtualView(null)` on the previous handler.  Something not quite as involved as calling "Disconnect". 
https://github.com/dotnet/maui/issues/8456

### Testing notes

To test this 
- fire up a shell app
- go into developer settings on android and select the option to always destroy activities

### Issues Fixed

Fixes #7940

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
> ### Description of Change
> When swapping in a new handler for shell call disconnect on the previous handler so that the xplat events don't trigger operations on the old set of handlers. There's a larger issue here where I think we need to call `SetVirtualView(null)` on the previous handler. Something not quite as involved as calling "Disconnect". #8456
> 
> ### Testing notes
> To test this
> 
> * fire up a shell app
> * go into developer settings on android and select the option to always destroy activities
> 
> ### Issues Fixed
> Fixes #7940

I think I have found something similar with the WebView on Windows. Get a crash closing a Window with a WebView, mostly because doing that we are not invoking the Disconnect method. Will send a PR with changes but definitely I think this apply to the rest.

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellRenderer.cs [hunk 1]
```diff
@@ -345,6 +346,31 @@ void IElementHandler.Invoke(string command, object args)
...
+			if (_disposed)
+				return;
+
+			_disposed = true;
+
+			Element.PropertyChanged -= OnElementPropertyChanged;
+			Element.SizeChanged -= OnElementSizeChanged;
+			((IShellController)Element).RemoveAppearanceObserver(this);
+
+			// This cast is necessary because IShellFlyoutRenderer doesn't implement IDisposable
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellRenderer.cs:358]: Can we include a comment to implement `IDisposable` on net7?

**Review by jsuarezruiz — APPROVED** [review]

**Comment by rmarinho** [comment]
```
D:\a\_work\1\s\src\Controls\tests\DeviceTests\HandlerTestBase.cs(205,12): error CS1501: No overload for method 'SetupWindowForTests' takes 3 arguments [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj]
D:\a\_work\1\s\src\Controls\tests\DeviceTests\HandlerTestBase.cs(205,12): error CS1501: No overload for method 'SetupWindowForTests' takes 3 arguments [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj]
D:\a\_work\1\s\src\Controls\tests\DeviceTests\HandlerTestBase.cs(205,12): error CS1501: No overload for method 'SetupWindowForTests' takes 3 arguments [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj]
```

**Comment by PureWeen** [comment]
@rmarinho fixed!

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellRenderer.cs (hunk 1 above)
Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellRenderer.cs]: This comment was incorrectly copied from the source code. We don't need it to implement IDisposable here. The only point of this check really is if a user has supplied a custom type here then we default back to IDisposable vs IDisconnect

**Comment by jzhao8402** [comment]
When the fix will be available?
