### PR TITLE
[Windows] Fix crash when navigating pages

### LINKED ISSUE #22790: WinRt exception when page navigated
### Description

When the app navigate between two pages randomly crashes.
In the second page my app is trying to deserialize a json file to runtime create the UI.

### Steps to Reproduce

1. Run the sample
2. Navigate for a while from "MainPage" to "Page2"
3. Watch the app crash

To speed up the process I've used a tool for automatic clicking ([https://tinytask.net/download.html])

### Link to public reproduction project repository

https://github.com/davide-cavallini/WinRtExceptionTest

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

Didn't find a specific workaround, but calling Task.Sleep(n) before navigation seems to reduce the frequency of exception happening.

### Relevant log output

```shell
'WinRtExceptionTest.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Collections.Immutable.dll'. 
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IContentPresenterMethods.set_Content(IObjectReference _obj, Object value)
   at Microsoft.Maui.Platform.StackNavigationManager.OnNavigated(Object sender, NavigationEventArgs e)
   at ABI.Microsoft.UI.Xaml.Navigation.NavigatedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IFrameMethods.GoBack(IObjectReference _obj, NavigationTransitionInfo transitionInfoOverride)
   at Microsoft.Maui.Platform.StackNavigationManager.NavigateTo(NavigationRequest args)
   at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args)
   at Microsoft.Maui.Controls.Handlers.ShellSectionHandler.SyncNavigationStack(Boolean animated, NavigationRequestedEventArgs e)
   at Microsoft.Maui.Controls.ShellSection.OnPopAsync(Boolean animated)
   at Microsoft.Maui.Controls.ShellSection.GoToAsync(ShellNavigationRequest request, ShellRouteParameters queryData, IServiceProvider services, Nullable`1 animate, Boolean isRelativePopping)
   at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass3_0.<<DispatchAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass2_0`1.<<DispatchAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest)
   at WinRtExceptionTest.Page2.<AddContainer>b__4_0()
```

### PR DESCRIPTION
**Pull request by Foda**
### Description of Change

Fixes a long-standing crash when navigating pages:

1. Manually clear the `ContentPresenter.Content` property.

When navigating pages it was discovered that the `Content` property of the `ContentPresenter` sometimes was not being detached from the parent `ContentPresenter` (the `ContentPresenter` itself does detach from the Page). A workaround for this was to manually clear the `Content` property.

**The actual cause of this bug:** I suspect that something causing the lifecycle tracking to be messed up. I'm still not sure what this is, but for now this will help our customers more than nothing.

## Workaround

The following can be used as a workaround. Place it in the `Loaded` event for your `AppShell`:

```csharp
private void AppShell_Loaded(object? sender, EventArgs e)
{
    Loaded -= AppShell_Loaded;

#if WINDOWS
    if (Handler != null && Handler.PlatformView is ShellView shellView &&
        shellView.Content is MauiNavigationView nv &&
        nv.Content is Microsoft.UI.Xaml.Controls.Frame frame)
    {
        frame.Navigating += (s, e) =>
        {
            if (frame.Content is Microsoft.UI.Xaml.Controls.Page page)
            {
                page.Unloaded += PageUnloaded;

                void PageUnloaded(object sender, Microsoft.UI.Xaml.RoutedEventArgs e)
                {
                    page.Unloaded -= PageUnloaded;
                    if (page.Content is Microsoft.UI.Xaml.Controls.ContentPresenter presenter)
                    {
                        presenter.Content = null;
                    }
                };
            }
        };
    }
#endif
}
```

### Issues Fixed

Fixes #22790 #18441 #22131

### CODE REVIEW

File: src/Core/src/Platform/Windows/StackNavigationManager.cs [hunk 1]
```diff
@@ -156,31 +154,41 @@ void OnNavigated(object sender, UI.Xaml.Navigation.NavigationEventArgs e)
...
 			if (page.Content == null)
 			{
-				presenter = new ContentPresenter()
+				presenter = new ContentControl()
 				{
 					HorizontalAlignment = UI.Xaml.HorizontalAlignment.Stretch,
 					VerticalAlignment = UI.Xaml.VerticalAlignment.Stretch
 				};
 
+				// It's possible that the unloaded event didn't happen yet, so force clear the content
```
Comment (Foda) [inline src/Core/src/Platform/Windows/StackNavigationManager.cs:167]: Note: we don't just run this by default because when the transition is animated the page flashes blank.

**Review by rmarinho — COMMENTED** [review]
Should we also clear/set to null  `_previousContent` on Disconnect ?

**Comment by BaY1251** [comment]
There are similar issues on the Android platform #18331.

**Review by rmarinho — APPROVED** [review]

**Comment by AwsomeCode** [comment]
Hi @Foda
Can you please check this https://github.com/dotnet/maui/issues/26214

**Comment by YamazakiAoi** [comment]
Hi @Foda .
I had a similar problem when I used a NavigationPage instead of a Shell.
Would your fix work for a NavigationPage that doesn't use a Shell or AppShell?
