### PR TITLE
[Android] Fix SwipeView not swiping using Label as direct content

### LINKED ISSUE #6154: Swipe not working when SwipeView is used as base element
### Description

If `SwipeView` is used as base element in a view, and this view is used in a ```DataTemplate``` source in a `CollectionView` swipe doesn't work, at least on Android (it triggers a [crash on Windows](https://github.com/dotnet/maui/issues/6153)).

[Demo project](https://github.com/pekspro/MauiIssues/tree/SwipeNotSupportedAsBaseInView)

### Steps to Reproduce

1. Create a new Maui application.
2. Add ItemView.xaml:

``` XAML
    <SwipeView 
                 xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                 x:Class="MauiIssues.ItemView"
                 HeightRequest="80"        
        >

        <SwipeView.LeftItems>
            <SwipeItems>
                <SwipeItem Text="Favorite" BackgroundColor="LightGreen" />
                <SwipeItem Text="Delete" BackgroundColor="LightPink" />
            </SwipeItems>
        </SwipeView.LeftItems>

        <Label Text="Swipe me!" />
    </SwipeView>
```
3. Add ItemView.cs:
``` C#
    namespace MauiIssues
    {
        public partial class ItemView 
        {
            public ItemView()
            {
                InitializeComponent();
            }
        }
    }
```
4: Add `CollectionView` on MainPage:
``` XAML
    <CollectionView 
                x:Name="ItemsList"
                ItemSizingStrategy="MeasureFirstItem"
                >
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <r:ItemView />
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
```
5: Initialize the list in the constructor:
``` C#
	namespace MauiIssues;

	public partial class MainPage : ContentPage
	{
		public MainPage()
		{
			InitializeComponent();

			ItemsList.ItemsSource = new string[] { "Hello", "World" }; 
		}
	}
```

Run the application on Android and try to swipe.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10, I was *not* able test on other platforms

### Did you find any workaround?

Use `SwipeView` directly in the `DataTemplate` instead, like in this issue https://github.com/dotnet/maui/issues/6153.

### Relevant log output

_No response_

### LINKED ISSUE #14805: SwipeView does not work on Android
### Description

I set a swipe view in a ContentPage. It works on iOS but not on Android.

### Steps to Reproduce

Run the reproduction project on Android and try to open the swipeview.

### Link to public reproduction project repository

https://github.com/HobDev/MauiBugs/tree/SwipeViewIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

None

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix Android SwipeView not swiping using Label as Content.

fix-14805

### Issues Fixed

Fixes #14805
Fixes #6154

### CODE REVIEW

File: src/Core/src/Platform/Android/MauiSwipeView.cs [hunk 1]
```diff
@@ -115,31 +115,36 @@ bool ShouldInterceptTouch(MotionEvent? e)
...
+			if (viewGroup is not null)
 			{
-				var child = viewGroup.GetChildAt(i);
+				int x = (int)(_initialPoint.X * _density);
+				int y = (int)(_initialPoint.Y * _density);
+
+				bool isHorizontal = swipeDirection == SwipeDirection.Left || swipeDirection == SwipeDirection.Right;
 
-				if (child != null && IsViewInBounds(child, x, y))
+				for (int i = 0; i < viewGroup.ChildCount; i++)
```
Comment (mandel-macaque) [inline src/Core/src/Platform/Android/MauiSwipeView.cs:130]: 'i' is just used to access the index, why don't we use a foreach in the collection? If we are worried about the performance of foreach vs for, we have bigger problems.

File: src/Core/src/Platform/Android/MauiSwipeView.cs [hunk 2]
```diff
@@ -115,31 +115,36 @@ bool ShouldInterceptTouch(MotionEvent? e)
...
+						if (child is RecyclerView recyclerView)
+							return ShouldInterceptScrollChildrenTouch(recyclerView, isHorizontal);
 
-					if (child is AWebView webView)
-						return ShouldInterceptScrollChildrenTouch(webView, isHorizontal);
+						if (child is NestedScrollView scrollView)
+							return ShouldInterceptScrollChildrenTouch(scrollView, isHorizontal);
+
+						if (child is AWebView webView)
+							return ShouldInterceptScrollChildrenTouch(webView, isHorizontal);
```
Comment (mandel-macaque) [inline src/Core/src/Platform/Android/MauiSwipeView.cs:146]: Would be a lot nicer with a switch on the type via an expression.

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Android/MauiSwipeView.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/MauiSwipeView.cs:130]: Is mostly used to get the child using the `GetChildAt` method.

File: src/Core/src/Platform/Android/MauiSwipeView.cs (hunk 2 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/MauiSwipeView.cs]: Changed.

**Review by rachelkang — COMMENTED** [review]
Confirmed this fixes the issue!

small comment following Manuel's feedback

**Comment by jsuarezruiz** [comment]
> Confirmed this fixes the issue!
> 
> small comment following Manuel's feedback

We are using i to get every child here https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Android/MauiSwipeView.cs#L128
Can modify it, to use the GetChildrenOfType extension method for example, but internally is doing the same.

**Comment by jsuarezruiz** [comment]
> > Confirmed this fixes the issue!
> > small comment following Manuel's feedback
> 
> We are using i to get every child here https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Android/MauiSwipeView.cs#L128 Can modify it, to use the GetChildrenOfType extension method for example, but internally is doing the same.

@rachelkang Thoughts?

**Comment by rachelkang** [comment]
ah ok, I thought there might've been a `viewGroup.Children` of some sort, but I guess not. in that case, I'm fine with either. will re-review now

**Review by rachelkang — APPROVED** [review]

**Comment by jsuarezruiz** [comment]
Added another sample to validate #6154:
issue-6154

**Review by jfversluis — APPROVED** [review]

**Comment by Eilon** [comment]
Aside from 1 un-resolved comment is this PR good to merge? Or can we merge right now? Any reason not to?

**Review by mandel-macaque — APPROVED** [review]
