### PR TITLE
[Windows] Prevent image from covering text in buttons if the image is too big

### LINKED ISSUE #21513: [Windows] Images should not cover text if they're too big inside a button
### Description

Images inside buttons that are too big and scaled down should not cover the text in Buttons on Windows:

Actual:
image

Expected (Android):
image

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.0-preview.1.9973

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Foda**
### Description of Change

Prevent image from covering text in buttons if the image is too big to fit.

Before:
image

After:
image

### Issues Fixed

Fixes #21513

### CODE REVIEW

File: src/Controls/tests/UITests/Tests/Issues/Issue21513.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+		public Issue21513(TestDevice device)
+			: base(device)
+		{ }
+
+		public override string Issue => "Buttons with images don't cover text";
+
+		[Test]
+		public void Issue21513Test()
+		{
+			this.IgnoreIfPlatforms(new [] { TestDevice.Mac, TestDevice.iOS, TestDevice.Android });
```
Comment (PureWeen) [inline src/Controls/tests/UITests/Tests/Issues/Issue21513.cs:18]: Can you also run this on android and generate the images there? Hopefully they are the same and we don't have to fix anything on android

**Review by PureWeen — CHANGES_REQUESTED** [review]
It looks like this breaks line break 

```XAML
 <VerticalStackLayout>
     <Button ImageSource="dotnet_bot.png" LineBreakMode="WordWrap" Text="awiohe fiawefhawifh awiuefh awiuefh wiauefh iawefhawiuefh awiuefh awiuefh awiufh awuiefh wiauefh wuiaefh awiuefh "></Button>
 </VerticalStackLayout>
 ```
image


here's main
image

**Review by jsuarezruiz — DISMISSED** [review]
LGTM. Tested with different fonts, font sizes, character spacing etc.
issue-21513

**Review by PureWeen — APPROVED** [review]
