### PR TITLE
[ios] fix memory leak with `Page` + `Layout`

### LINKED ISSUE #13520: Every MAUI Page generates a Memory Leak on iOS and macCatalyst
### Description

On iOS and maccatalyst the finalizers are never called and I cannot understand if the page leaks or not.

I know that we use the interpretor (don't know if this could be the problem) but I would expect that at some point the instances that I have in memory should be cleaned.

Btw: How do we profile memory allocations in MAUI on iOS and maccatalyst? Xamarin. Profiler does not work for the MAUI applications.
I looked here:
https://github.com/dotnet/maui/wiki/Profiling-.NET-MAUI-Apps
but what I saw is how you profile startup not the memory allocations.

Any guidance on how to profile memory allocations on iOS, maccatalyst and Android?

### Steps to Reproduce

1.Create a new MAUI project
2.Add a SecondPage and register with AppShell
3. For debugging add the finalizer on the SecondPage : ~SecondPage()
4. On MainPage add an toolbar item where you manually call GC.Collect()

Navigating back an forth and pressing the button that does garbage collector the finalizer is never called on iOS and maccatalyst (on Android the Finalizer it is called) so I don't understand if the page leak or not.

### Link to public reproduction project repository

https://github.com/danardelean/MauiTestFinalizer

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16.3.1,  macOS Ventura 13.2.1

### Did you find any workaround?

NO

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Further fixes #13520

7d0af63c did not appear to be a complete fix for #13520, as when I retested the customer sample, I found I needed to remove a `VerticalStackLayout` for the problem to go away.

I could reproduce the issue in a test by doing:

    var page = new ContentPage { Title = "Page 2", Content = new VerticalStackLayout { new Label() } };

After lots of debugging, I found the underlying issue was that `MauiView` on iOS held a reference to the cross-platform `IView`.

After changing the backing field for this to be a `WeakReference<IView>` the above problem appears to be solved.

I also removed `LayoutView.CrossplatformArrange/Measure` as we can just use the `View` property directly instead.

### CODE REVIEW

File: src/Core/src/Platform/iOS/LayoutView.cs [hunk 1]
```diff
@@ -68,9 +74,6 @@ public override void WillRemoveSubview(UIView uiview)
 			Superview?.SetNeedsLayout();
 		}
 
-		internal Func<double, double, Size>? CrossPlatformMeasure { get; set; }
-		internal Func<Rect, Size>? CrossPlatformArrange { get; set; }
```
Comment (jonathanpeppers) [inline src/Core/src/Platform/iOS/LayoutView.cs:72]: I removed these, because you can just call `View.CrossPlatformMeasure()` directly.

Otherwise we might need to unset them in places, like in 7d0af63c8a31f2924bd124a9beccdeadb4648b6a.

Comment (hartez) [reply src/Core/src/Platform/iOS/LayoutView.cs:72]: > I removed these, because you can just call `View.CrossPlatformMeasure()` directly.

The design intent here was for the handlers to be able to directly modify the xplat measure/arrange methods directly when necessary. It's not currently used on iOS (mostly for accidental historical reasons), but the other platforms _do_ make use of it. The intent was to keep the designs symmetric on all the platforms. 

(The main place you can see this at work in the Android and Windows ScrollViewHandlers.)

So I'd rather not remove these. Or, if there's a compelling memory-leak reason to remove them, we'll need to work out a way to inject custom xplat measure/arrange methods from the handlers.

**Comment by hartez** [comment]
> After lots of debugging, I found the underlying issue was that `MauiView` on iOS held a reference to the cross-platform `IView`.

Why is the `MauiView` still around? What's holding a reference to it? I'm not clear on why the `MauiView` itself can't be collected along with the View (the VerticalStackLayout?) that it's referencing.

**Comment by jonathanpeppers** [comment]
> Why is the MauiView still around?

The `*.gcdump` file I'm able to [get from Mono](https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/tracing.md#how-to-get-gc-memory-dumps) just says `MauiView > Other Roots`. I can make a new one tomorrow and share it here. [`Other Roots`](https://github.com/filipnavara/mono-gcdump#all-gc-roots-are-reported-as-other-roots) is probably a `GCHandle` that is holding it until its Objective-C refcount is 0. In 7d0af63c8a31f2924bd124a9beccdeadb4648b6a, calling `RemoveFromSuperview()` fixed a similar issue.

It may be that we are still leaking `MauiView`'s all the time -- and this is only slightly better in that `Page`'s on iOS can go away now. When removing `CrossplatformArrange/Measure` and making `View` weak, the `MauiView` no longer holds onto the cross-platform `IView`.

I believe there could be some core problem here that isn't understood. But I've not been able to reproduce a real issue here: https://github.com/jonathanpeppers/MemoryLeaksOniOS

File: src/Core/src/Platform/iOS/LayoutView.cs (hunk 1 above)
Comment (jonathanpeppers) [reply src/Core/src/Platform/iOS/LayoutView.cs:72]: > The design intent here was for the handlers to be able to directly modify the xplat measure/arrange methods directly when necessary.

Is this design documented? So other people will know about it?

> Or, if there's a compelling memory-leak reason to remove them, we'll need to work out a way to inject custom xplat measure/arrange methods from the handlers.

The leak appears to return if I put them back. It makes the shell & navigation `DoNotLeak` tests fail. Will share a `*.gcdump` file tomorrow.

Comment (hartez) [reply src/Core/src/Platform/iOS/LayoutView.cs:72]: > Is this design documented? So other people will know about it?

Clearly not well enough, if at all. 🙂

**Comment by jonathanpeppers** [comment]
I've been doing more testing and I think this is what was going on:

1. `VerticalStackLayout` -> `LayoutHandler` : MAUI views hold a strong reference to handlers
  a. *NOTE: `VerticalStackLayout.Parent.Parent` is a `ContentPage`*
3. `LayoutHandler` -> `LayoutView`: handlers hold a strong reference to native view
4. `LayoutView` -> `VerticalStackLayout`:  `LayoutView` held a strong reference to the MAUI view due to `CrossplatformLayout/Arrange` and the `View` property.

I made no. 3 a weak reference, and this appears to break the cycle and all of the above can go away... Note that cycles are only a problem for `NSObject` subclasses -- there is not an issue like this with plain C# objects or Android `Java.Lang.Object` subclasses.

I just retested with the fix in place, and I don't see `VerticalStackLayout`, `LayoutHandler`, or `LayoutView` staying around from the page I'm testing.

**Comment by jonathanpeppers** [comment]
@hartez do you have any other concerns here?

**Review by hartez — APPROVED** [review]
