### PR TITLE
[Windows] Fixed BackButton visibility issue when switching tabs without NavigationPage

### LINKED ISSUE #14689: TabbedPage: WinUI: Back-button persists when swapping to a Tab that does not have a NavigationPage.
### Description

Given a `TabbedPage` with Children, where 
- at least one Tab *does not* have a NavigationPage
- at least one Tab *does* have a NavigationPage

If a back button is shown for the `CurrentPage`, then swapping to a Tab that does not have a `NavigationPage` does not remove the back button.

Notes:
Swapping to a Tab that does have a `NavigationPage` correctly updates the back-button depending on whether the current `NavigationPage` requires it.

### Steps to Reproduce

1. Create a new MAUI app.
1. Replace the contents of App.xaml.cs with this:
```csharp
public partial class App : Application
{
    public App()
    {
        InitializeComponent();

        var tabbedPage = new TabbedPage();
        tabbedPage.Children.Add(new ContentPage() { Title = "No Nav root" });
        tabbedPage.Children.Add(new NavigationPage(new NavContentPage()){ Title = "Has Nav root" });
        tabbedPage.Children.Add(new NavigationPage(new NavContentPage()){ Title = "Has Nav root" });
        MainPage = tabbedPage;
    }

    public class NavContentPage : ContentPage
    {
        public NavContentPage()
        {
            var button = new Button() { Text = "Push a page", VerticalOptions = LayoutOptions.Start };
            button.Clicked += (s, e) => { this.Navigation.PushAsync(new NavContentPage()); };
            Content = button;
        }
    }
}
```
1. Run it on Windows.
1. Swap to either the second or third Tab.
2. Click the button
3. The back button appears. This is correct.
image
  

4. Swap to the first Tab. 
5. The back-button remains. This is the bug. 
image

### Link to public reproduction project repository

https://github.com/Keflon/TabbedPageNavBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Latest

### Did you find any workaround?

No.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Vignesh-SF3580**
### Issue Detail
The back button visibility was not updating correctly when the page did not have a NavigationPage.
 
### Root Cause
The back button visibility was being updated only when the parent was a NavigationPage. As a result, it did not update properly when there was no NavigationPage.
 
### Description of Change
Only the toolbar visibility was updated when the page did not have a NavigationPage. Now, the back button visibility is also updated along with the toolbar visibility to resolve the issue.

### Tested the behavior in the following platforms
 
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/14689

### Screenshots

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="300" height="600"  src="https://github.com/user-attachments/assets/ca9da1b8-8f46-4bac-aa0f-f38972ef5c48"> | <video width="300" height="600"  src="https://github.com/user-attachments/assets/4a495254-8aec-48a8-9fc7-ed65b0b16183">) |

### CODE REVIEW

File: src/Controls/src/Core/Platform/Windows/Extensions/ToolbarExtensions.cs [hunk 1]
```diff
@@ -13,6 +13,7 @@ internal static class ToolbarExtensions
 		public static void UpdateIsVisible(this MauiToolbar platformToolbar, Toolbar toolbar)
 		{
 			platformToolbar.Visibility = (toolbar.IsVisible) ? UI.Xaml.Visibility.Visible : UI.Xaml.Visibility.Collapsed;
+			UpdateBackButtonVisiblity(platformToolbar, toolbar);
```
[the remark this answers is not in the document]
Comment (jsuarezruiz) [reply src/Controls/src/Core/Platform/Windows/Extensions/ToolbarExtensions.cs]: The AI is correct, could you fix the typographical error?

File: src/Controls/src/Core/Platform/Windows/Extensions/ToolbarExtensions.cs [hunk 2]
```diff
@@ -84,5 +84,10 @@ public static void UpdateToolbarDynamicOverflowEnabled(this MauiToolbar platform
 
 			platformToolbar.CommandBar.IsDynamicOverflowEnabled = toolbar.DynamicOverflowEnabled;
 		}
+
+		private static void UpdateBackButtonVisibility(MauiToolbar platformToolbar, Toolbar toolbar)
+		{
+			platformToolbar.IsBackButtonVisible = toolbar.BackButtonVisible ? NavigationViewBackButtonVisible.Visible : NavigationViewBackButtonVisible.Collapsed;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Windows/Extensions/ToolbarExtensions.cs:90]: Can apply a small change to improve the readability by formatting the ternary operation across multiple lines:

```
platformToolbar.IsBackButtonVisible = 
        toolbar.BackButtonVisible 
            ? NavigationViewBackButtonVisible.Visible 
            : NavigationViewBackButtonVisible.Collapsed;
```

Comment (Vignesh-SF3580) [reply src/Controls/src/Core/Platform/Windows/Extensions/ToolbarExtensions.cs]: @jsuarezruiz I have updated the codes based on your feedback. Could you please review and let me know if you have any further concerns?

**Review by jsuarezruiz — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]
