### PR TITLE
[Core] Implement BackgroundImageSource in PageHandler

### LINKED ISSUE #2966: [Bug] Unable to set image as ContentPage BackgroundImageSource
### Description

I'm setting the bot image to the background of the page, but nothing appears.

image

### Basic Information

- Version with issue: 9.1843

### LINKED ISSUE #4773: Can't get BackgroundImage of ContentPage
### Description

Can't Get BackgroundImage of ContentPage, although I set it in XAML  `BackgroundImageSource="background.svg"` and C# `BackgroundImageSource = "background.svg";`.  background.svg is an svg image in the `Resources\Images\` folder. 

[BugSample.zip](https://github.com/dotnet/maui/files/8096334/BugSample.zip)

### Steps to Reproduce

Run the repo project. 

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15.2, Android 11

### Did you find any workaround?

There was a workaround in Xamarin.Forms by settings First Child of a top level Grid as an Image.  But this does not work in Maui.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Implement **BackgroundImageSource** in PageHandler.

- fixes #2966 
- fixes #4773
 
### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)

#### Does this PR touch anything that might affect accessibility?
- No

### CODE REVIEW

File: src/Core/src/Core/IPage.cs [hunk 1]
```diff
@@ -0,0 +1,12 @@
+﻿namespace Microsoft.Maui
+{   /// <summary>
+	/// Represents a .NET MAUI Page.
+	/// </summary>
+	public interface IPage : IContentView
```
Comment (PureWeen) [inline src/Core/src/Core/IPage.cs:5]: I don't think we want to create an `IPage` for this. Can we follow the same route as we do for things like `ITitledElement`?  I feel like the interface for the background image needs to be more interesting then just having the `IImageSource` as well. Perhaps we use something like

`interface IViewBackgroundImagePart : IImageSourcePart` because then that makes it more compatible with other ImageLoading structures

You can then just instantiate a

```C#
		public ImageSourcePartLoader SourceLoader =>
			_imageSourcePartLoader ??= new ImageSourcePartLoader(this, () => VirtualView, OnSetImageSource);
```

And use that to handle all the loading behavior. 

At that point the mapper could possibly even just be on ViewHandler and thus a generalized BackgroundImage for native views is born

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Core/IPage.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Core/src/Core/IPage.cs]: Removed `IPage` and implemented `IViewBackgroundImagePart`. Also added a ContentPage Gallery sample where easily test this scenario.

Comment (jsuarezruiz) [reply src/Core/src/Core/IPage.cs]: @PureWeen Could you review the PR again?. Thnx!

File: src/Core/src/Handlers/Page/PageHandler.Android.cs [hunk 2]
```diff
@@ -1,14 +1,20 @@
...
 {
 	public partial class PageHandler : ContentViewHandler
 	{
-		//Graphics.Color? DefaultBackgroundColor;
-
 		public static void MapTitle(IPageHandler handler, IContentView page)
 		{
 		}
+
+		public static void MapBackgroundImageSource(IPageHandler handler, IContentView page)
```
Comment (PureWeen) [inline src/Core/src/Handlers/Page/PageHandler.Android.cs:9]: Can we move all of this up into ViewHandler? 

The extension methods all seem to work against UIView/Android.View/Panel

WinUI is the only one that has kind of a specific type but could probably just use pattern matching to look through the types that accept a background. 

This way anyone could annotate any view with `IViewBackgroundImagePart` and then in controls we will only implement `IViewBackgroundImagePart` at the page level

**Review by PureWeen — DISMISSED** [review]

File: src/Core/src/Core/IViewBackgroundImagePart.cs [hunk 3]
```diff
@@ -0,0 +1,7 @@
+﻿namespace Microsoft.Maui
+{
+	public interface IViewBackgroundImagePart : IImageSourcePart
```
Comment (mattleibow) [inline src/Core/src/Core/IViewBackgroundImagePart.cs:3]: Why do we need this type? Can't we just implement the interface directly on the Page type?

Comment (PureWeen) [reply src/Core/src/Core/IViewBackgroundImagePart.cs:3]: We don't have a Page Type. We have `IContentView` so we could do it on `IContentView` 

But it's just the idea of having lots of little interfaces that provide a specific behavior. In theory any UIView/AView/FrameworkElement can have a BackgroundImage

**Comment by mattleibow** [comment]
I think we have the potential to make a big improvement it IView supports a background image. Not sure how this will work with IImage having both an image and a background image. This is not really possible with interfaces because it will be the same interface type.

_SHould_ IImage support both a background image and an image. I am thinking it is 2 separate concepts, like a centered image that is animating, nd then a background gradient? This is probably the same with IImageButton.

Maybe background should be a brush/paint actually? In fact, this is already a thing. I am wondering if Page.BackgroundImage should translate into `Page.Background => new ImagePaint(BackgroundImage)` at a controls level, and then our implementation just works?

**Review by mattleibow — CHANGES_REQUESTED** [review]
This should be on IView.

**Comment by jsuarezruiz** [comment]
@mattleibow, @PureWeen Thanks so much for teh feedback, is a great idea!. Moved the UpdateBackgroundImage extension methods to ViewExtensions. In that way, any view implementing IViewBackgroundImagePart  could have a background image.

**Review by Redth — APPROVED** [review]

**Comment by mattleibow** [comment]
I have an idea to actually use ImageBrush and Background instead of exposing new properties. Maybe under the hood we split it up since maui graphics doesn't use image sources.

So we can do what we do with Background/BackgroundColor and basically have this:

```cs
IImageSource IImageSourcePart.Source
{
	get
	{
		if (Background is ImageBrush imageBrush && !imageBrush.IsEmpty)
			return imageBrush.ImageSource;
		return BackgroundImageSource;
	}
}
```

```cs
﻿namespace Microsoft.Maui.Controls
{
	[System.ComponentModel.TypeConverter(typeof(BrushTypeConverter))]
	public class ImageBrush : Brush
	{
		public ImageBrush()
		{
		}

		public ImageBrush(ImageSource imageSource)
		{
			ImageSource = imageSource;
		}

		public override bool IsEmpty =>
			ImageSource?.IsEmpty ?? true;

		public static readonly BindableProperty ImageSourceProperty = BindableProperty.Create(
			nameof(ImageSource), typeof(ImageSource), typeof(ImageBrush), default(ImageSource));

		public virtual ImageSource ImageSource
		{
			get => (ImageSource)GetValue(ImageSourceProperty);
			set => SetValue(ImageSourceProperty, value);
		}

		public override bool Equals(object obj) =>
			obj is ImageBrush dest && ImageSource == dest.ImageSource;

		public override int GetHashCode() =>
			-1234567890 + ImageSource.GetHashCode();
	}
}
```

**Review by mattleibow — APPROVED** [review]
ImageBrush is for net7

**Review by mattleibow — APPROVED** [review]
