### PR TITLE
[Catalyst] Fix brushes in Frame

### LINKED ISSUE #7261: [MacCatalyst] [Scenario Day] Brushes not working in Frame
### Description

Brushes not working in Frame.

Captura de Pantalla 2022-05-17 a las 17 33 19

### Steps to Reproduce

1. Download https://github.com/davidbritch/dotnet-maui-samples/tree/main/UserInterface/BrushesDemos
2. Launch the app on macOS.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 12.3.1

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #8108: Frame.Background LinearGradientBrush not working on maccatalyst
### Description

On windows, the following XAML creates a rounded corner frame with a linear gradient in windows; however, on maccatalyst the gradient does not appear and the frame stays white:

```
 <Frame BorderColor="Black" CornerRadius="20" HasShadow="False" Padding="8"  >
                <Frame.Background>
                    <LinearGradientBrush EndPoint="1,0">
                        <GradientStop Color="#B92748" Offset="0.1" />
                        <GradientStop Color="#DB3EB1" Offset="1.0" />
                    </LinearGradientBrush>
                </Frame.Background>
                     <VerticalStackLayout 
                        Spacing="25" 
                        Padding="30,0" 
                        VerticalOptions="Center">

                        <Image
                            Source="dotnet_bot.png"
                            SemanticProperties.Description="Cute dot net bot waving hi to you!"
                            HeightRequest="200"
                            HorizontalOptions="Center" />
                
                        <Label 
                            Text="Hello, World!"
                            SemanticProperties.HeadingLevel="Level1"
                            FontSize="32"
                            HorizontalOptions="Center" />
            
                        <Label 
                            Text="Welcome to .NET Multi-platform App UI"
                            SemanticProperties.HeadingLevel="Level2"
                            SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                            FontSize="18"
                            HorizontalOptions="Center" />

                        <Button 
                            x:Name="CounterBtn"
                            Text="Click me"
                            SemanticProperties.Hint="Counts the number of times you click"
                            Clicked="OnCounterClicked"
                            HorizontalOptions="Center" />

                    </VerticalStackLayout>
            </Frame>
```

Screenshot 2022-06-16 at 13 13 22

### Steps to Reproduce

surround the vanilla 'dotnet new maui' waving bot with a Frame as above

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

MacOS 15.4

### Did you find any workaround?

not a workaround but changing the BorderColor while the app is running and after a hot reload the gradient background appears but after a restart of the application the gradient reverts to white

### Relevant log output

_No response_

### LINKED ISSUE #8402: Gradient not appearing on iOS
### Description

I implemented my own design on XAML using Android, with normal background and LinearGradientBrush, and when I tested on iOS I get this visual inconsistency 
image

### Steps to Reproduce

1. Create NET MAUI App 
2. Replace MainPage to this XAML 
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
             ios:Page.UseSafeArea="True"
             Shell.NavBarIsVisible="False"
             x:Class="GenerationApp.MainPage">

    <Grid RowDefinitions="Auto,3*,*,*">
        <Grid Margin="{OnPlatform Android='-20,-20,0,0', iOS='-40,-20,0,0'}">
            <Image Source="deporte" HeightRequest="{OnPlatform Android='600', iOS='600'}"/>
        </Grid>
        <Grid Grid.Row="1" HorizontalOptions="FillAndExpand" BackgroundColor="Transparent"
              Margin="{OnPlatform Android='0,-180,0,-100', iOS='0,-80,0,-1'}">
            <Frame BorderColor="transparent">
                <Frame.Background>
                    <LinearGradientBrush StartPoint="1,0" EndPoint="1,1">
                        <GradientStop Offset=".5" Color="Transparent"/>
                        <GradientStop Offset=".1" Color="{StaticResource GenOrange}"/>
                        <GradientStop Offset=".1" Color="{StaticResource GenOrange}"/>
                        <GradientStop Offset=".1" Color="{StaticResource GenOrange}"/>
                        <GradientStop Offset=".1" Color="{StaticResource GenOrange}"/>
                        <GradientStop Offset=".1" Color="{StaticResource GenOrange}"/>
                    </LinearGradientBrush>
                </Frame.Background>
            </Frame>
            <Grid HeightRequest="210" WidthRequest="210" HorizontalOptions="Center">
                <Image x:Name="logo_gen" Source="logo_generations_bluedark" HeightRequest="200"  
                       WidthRequest="200" HorizontalOptions="Center" VerticalOptions="Center"
                       Margin="0,-180,0,0"/>
            </Grid>
        </Grid>
        <StackLayout Grid.Row="3" Margin="0,-200,0,10" VerticalOptions="CenterAndExpand"
                     HorizontalOptions="FillAndExpand" Spacing="10">
            <Label Text="Lorem Ipsum dolor" TextColor="White" HorizontalOptions="CenterAndExpand" />
            <Label Text="consectetuer adlplsicing ellit." TextColor="White" HorizontalOptions="CenterAndExpand" />
            <Border StrokeThickness="2" StrokeShape="Rectangle" Margin="30,0,30,0" BackgroundColor="{StaticResource GenDark}" >
                <Button Text="SIGN UP NOW" TextColor="White" BorderWidth="0" HorizontalOptions="FillAndExpand" 
                        BackgroundColor="Transparent" BorderColor="Transparent" Command="{Binding GoToRegisterPage}"/>
            </Border>
        </StackLayout>
        <StackLayout Grid.Row="4" VerticalOptions="FillAndExpand">
            <FlexLayout Direction="Column">
                <BoxView HorizontalOptions="FillAndExpand" HeightRequest=".1" Color="White"/>
            </FlexLayout>
            <Button Text="LOGIN" TextColor="White" BackgroundColor="Transparent" BorderColor="Transparent" 
                    BorderWidth="0" Command="{Binding GoToLoginPage}"/>
        </StackLayout>
    </Grid>
</ContentPage>
3. Run App

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android  12, iOS 15

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #9854: Gradient not loading on iOS
### Description

Sorry, got on more problem with the gradient or possibly the frame in iOS. On initial loading the app the background is white instead of drawing the expected coloured backgroun. Android seems not to have this issue. Other controls seem fine (label, buttons, images etc).

### Steps to Reproduce

I start with frame/gradient:

```XAML
<Frame>
    <Frame.Background>
        <LinearGradientBrush EndPoint="0,1">
            <GradientStop Color="Yellow" 
                                  Offset="1.0" />
            <GradientStop Color="Blue" 
                                  Offset="0.1" />
        </LinearGradientBrush>
    </Frame.Background>
</Frame>
```

When I load this on iOS simulator and device, it shows a white screen (other controls like labels are showing fine). If I bring it to the background, look at the home screen and then bring it back, then it draws my background (my gradient in this case). 

### Link to public reproduction project repository

n/a

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

latest iOS (15.5), both simulator and device

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Brushes were not rendering on the Frame in Catalyst. The issue is that we weren't updating the size of the Layer used to draw the gradient when resizing the UIView.

Captura de Pantalla 2022-06-10 a las 12 06 33

### Issues Fixed

Fixes #7261 
Fixes #8108
Fixes #8402
FIxes #9854

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs [hunk 1]
```diff
@@ -126,7 +126,10 @@ public virtual void SetupLayer()
 		public override void LayoutSubviews()
 		{
 			if (_previousSize != Bounds.Size)
+			{
 				SetNeedsDisplay();
+				this.UpdateBackgroundLayer();
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs:131]: I'm getting a little bit lost on this PR.

We have a call [here](https://github.com/dotnet/maui/blob/21a4caf5e27f5debd0a0d4498eca556b7eeaef29/src/Core/src/Handlers/View/ViewHandler.iOS.cs#L10) that's supposed to update the background layer. But that calls `UpdateBackgroundLayerFrame` where as this calls `UpdateBackgroundLayer`. It seems like the `controls` layer generally needs a call into `UpdateBackgroundLayer` and that this isn't specific to just the `FrameRenderer`.  To fix this should we instead add a mapping addition at the controls layer to `Frame` that calls `UpgradeBackgroundLayer`?

**Review by PureWeen — CHANGES_REQUESTED** [review]

**Comment by hermben** [comment]
As a workaround, you can replace Frame with ContentView to see if it also works for you:
Example code:

```
<ContentView
                HeightRequest="120"
                HorizontalOptions="FillAndExpand"
                Margin="-2"
                Padding="20, 45, 20, 0">
            <ContentView.Background>
                <LinearGradientBrush>
                    <GradientStop Color="#00A7B5" Offset="0.1" />
                    <GradientStop Color="#721474" Offset="1.0" />
                </LinearGradientBrush>
            </ContentView.Background>
</ContentView>
```

If you need border, border radius and shadow, you can combine **ContentView** with **Border** and **Shadow** MAUI elements.

File: src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs:137]: Is similar. This PR apply changes to update the Frame background layer with size changes. Because the Frame continue using a Renderer, the changes are applied directly to the Renderer code.

**Review by hartez — APPROVED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs (hunk 1 above)
Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs:137]: Hmm, the `Frame` on iOS no longer uses this renderer. 

Frame on iOS uses this 

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs#L9

Which uses the handler-based renderer. 
This render is only used if the user adds `Frame` as a compatibility renderer.

Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs:137]: This code is using the handler based `VisualElementRenderer` though it's not a compatibility renderer so it's based on `IVEH`

Should this code go inside this class? 

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Compatibility/Handlers/iOS/VisualElementRenderer.cs#L10

The old renderer had it and it seems like it didn't get copied over?

image

File: src/Compatibility/Core/src/iOS/Renderers/FrameRenderer.cs [hunk 2]
```diff
@@ -133,7 +133,10 @@ public virtual void SetupLayer()
 		public override void LayoutSubviews()
 		{
 			if (_previousSize != Bounds.Size)
+			{
 				SetNeedsDisplay();
+				this.UpdateBackgroundLayer();
```
Comment (PureWeen) [inline src/Compatibility/Core/src/iOS/Renderers/FrameRenderer.cs:138]: If you're modifying the compatibility renderer should this call get moved up to here?

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Compatibility/Handlers/iOS/VisualElementRenderer.cs#L10

**Review by PureWeen — APPROVED** [review]
The fixes here look good for `Frame`

@jsuarezruiz if you think we should create an additional issue/fix around my comments please do so.
