### PR TITLE
Connect gestures LifeCycle to Container and Window

### LINKED ISSUE #12116: Triggering a change with the ContainerView results in incorrect things
### Description

Some aspects of the view, such as Gestures on Android (and maybe iOS if this is merged: #12108), are attached to the container view. As a result, when the container view is removed the whole gesture set is missing.

### Steps to Reproduce

1. File | New | Maui app (I lie, I used the sandbox app)
2. Paste this code:
    ```cs

	var stack = new VerticalStackLayout();

	var view1 = new Label
	{
		Text = "Started with NO container",
		// no shadow
		GestureRecognizers = { new TapGestureRecognizer { Command = new Command(() => Debug.WriteLine("view 1")) } }
	};
	stack.Add(view1);

	var view2 = new Label
	{
		Text = "Started WITH a container",
		Shadow = new Shadow(),
		GestureRecognizers = { new TapGestureRecognizer { Command = new Command(() => Debug.WriteLine("view 2")) } }
	};
	stack.Add(view2);

	var view3 = new Image
	{
		Source = ImageSource.FromFile("dotnet_bot.png"),
		WidthRequest = 80,
		HeightRequest = 80,
		// no background
		GestureRecognizers = { new TapGestureRecognizer { Command = new Command(() => Debug.WriteLine("view 3")) } }
	};
	stack.Add(view3);

	var view4 = new Image
	{
		Source = ImageSource.FromFile("dotnet_bot.png"),
		WidthRequest = 80,
		HeightRequest = 80,
		Background = new SolidColorBrush(Colors.Red),
		GestureRecognizers = { new TapGestureRecognizer { Command = new Command(() => Debug.WriteLine("view 4")) } }
	};
	stack.Add(view4);

	var btn = new Button
	{
		BackgroundColor = Colors.Orange,
		Text = "OK",
		Command = new Command(() =>
		{
			view1.Shadow = new Shadow(); // causes a container view to be added
			view2.Shadow = null; // causes the container view to be removed
			view3.Background = new SolidColorBrush(Colors.Red); // causes a container view to be added
			view4.Background = null; // causes the container view to be removed
		})
	};
	stack.Add(btn);

	Content = stack;
    ```
3. Tap the labels and observe both log to the console
4. Tap the button
5. Observe that only the first label logs

> NOTE: there is a bug on iOS where setting the background to null does not actually remove the background... (https://github.com/dotnet/maui/issues/12117) so for now replace with `Shadow` and you get the same issue.

This is because in the first case, a container was added and the gestures are still attached to the label. In the second case, the gestures were attached to the container that is now removed from the view hierarchy.

Even if this was perfect, I am not sure how this plays with controls that respond to taps - for example buttons. Will attaching gestures stop normal button things? If so, will it change when it is on the container? Is this a valid case of a button and a tap gesture on that button? Should adding a gesture trigger a new container?

In a perfect world, we have 2 behaviours - with and without containers!

### Link to public reproduction project repository

:)

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

- Only instantiate and setup gestures if a window has been set on a `VisualElement`. This way, when the `View` is removed from the visual tree the platform gestures all get removed. This should help some with memory leaks.
- When the `ContainerView` property mapper runs we now re-evaluate the gestures to see if we need to apply them to a new view

I moved the `GestureManager` behavior to `GesturePlatformManagers` so that I could just move all the `Gesture` handling out of `VisualElement` and into a separate class to help simplify `VisualElement` up a bit. 

I added some internal interfaces that map to `Controls` view properties which let me write some better unit tests. 

### Issues Fixed

Fixes #12116

### CODE REVIEW

File: src/Controls/src/Core/Properties/AssemblyInfo.cs [hunk 1]
```diff
@@ -53,6 +53,8 @@
 [assembly: InternalsVisibleTo("CommunityToolkit.Maui.Markup")]
 [assembly: InternalsVisibleTo("CommunityToolkit.Maui.Markup.UnitTests")]
 
+[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
```
Comment (PureWeen) [inline src/Controls/src/Core/Properties/AssemblyInfo.cs:56]: Is this OK? I had to do this to make it so `NSubstitue` would work

File: src/Controls/src/Core/HandlerImpl/View/View.Impl.cs [hunk 2]
```diff
@@ -5,31 +5,19 @@
 namespace Microsoft.Maui.Controls
 {
 	/// <include file="../../../../docs/Microsoft.Maui.Controls/View.xml" path="Type[@FullName='Microsoft.Maui.Controls.View']/Docs/*" />
-	public partial class View : IView, IPropertyMapperView, IHotReloadableView
+	public partial class View : IView, IPropertyMapperView, IHotReloadableView, IControlsView
```
Comment (PureWeen) [inline src/Controls/src/Core/HandlerImpl/View/View.Impl.cs:8]: These interfaces are internal which shouldn't break ABI?

File: src/Controls/src/Core/Properties/AssemblyInfo.cs (hunk 1 above)
Comment (hartez) [reply src/Controls/src/Core/Properties/AssemblyInfo.cs:56]: Are you subbing for internal interfaces?

Comment (PureWeen) [reply src/Controls/src/Core/Properties/AssemblyInfo.cs:56]: Yea, it's substituting for the `IControlsView` that I added in this PR. I could see us making `IControlsView` public for NET8. 

I just wasn't sure if having this IVT on our released binaries would be a bad move. 

https://github.com/dotnet/maui/pull/12259/files#diff-59f9b98a863b084d3fcfc59e478166aa991104ce8d2dd1eb05af8d9cc20b018eR14

File: src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Android.cs [hunk 3]
```diff
@@ -25,10 +25,12 @@ class GestureManager : IDisposable
 		protected virtual VisualElement? Element => _handler?.VirtualView as VisualElement;
 
 		View? View => Element as View;
+		AView? _control;
 
-		public GestureManager(IViewHandler handler)
+		public GesturePlatformManager(IViewHandler handler)
 		{
 			_handler = handler;
+			_control = _handler.ToPlatform();
```
Comment (mattleibow) [inline src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Android.cs:33]: Should this be a weak reference like ios?

File: src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Windows.cs [hunk 4]
```diff
@@ -30,7 +30,7 @@ class GestureManager : IDisposable
 		bool _wasPanGestureStartedSent;
 		bool _wasPinchGestureStartedSent;
 
-		public GestureManager(IViewHandler handler)
+		public GesturePlatformManager(IViewHandler handler)
```
Comment (mattleibow) [inline src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Windows.cs:33]: Should windows also use ToPlatform instead of PlatformView? like 45

File: src/Controls/src/Core/View.cs [hunk 5]
```diff
@@ -83,6 +84,7 @@ static void OnMarginBottomPropertyChanged(BindableObject bindable, object oldVal
 
 		protected internal View()
 		{
+			_gestureManager = new GestureManager(this);
```
Comment (mattleibow) [inline src/Controls/src/Core/View.cs:87]: This also happens in OnHandlerChangedCore and OnHandlerChangingCore in the View.Impl.cs. Does that matter?

File: src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Windows.cs (hunk 4 above)
Comment (PureWeen) [reply src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Windows.cs:33]: Not sure

The Windows Gestures were specifically designed to separate these two out. 

https://github.com/xamarin/Xamarin.Forms/blob/d998887f135622704254d4cfeaa000f5b915e64d/Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs#L759-L766

So, the `Container` was the `VisualElementRenderer` and the `Control` was the inner control.

I'm not sure if that same requirement translates to our containers or not.  It looks like it was a way to implement `PreventGestureBubbling`. 

image

So, the `Container` would eat the event and stop it from passing through. It looks like this was implemented to try and make all the platforms act the same https://github.com/xamarin/Xamarin.Forms/pull/842. 

I'm guessing this no longer works like it did on Forms and I'm not really sure if we want it to. I'd say we create an issue to investigate, and I assume this will get addressed once issues related to InputTransparent or other scenarios come into focus

File: src/Controls/src/Core/View.cs (hunk 5 above)
Comment (PureWeen) [reply src/Controls/src/Core/View.cs:87]: does it? I'm not finding the code you're referring to

image

Comment (mattleibow) [reply src/Controls/src/Core/View.cs:87]: No idea what I was looking at...

**Review by mattleibow — APPROVED** [review]
OK, this looks good to me.

File: src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Windows.cs (hunk 4 above)
Comment (PureWeen) [reply src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Windows.cs:33]: https://github.com/dotnet/maui/issues/12828
