### PR TITLE
[XC] Fix x:DataType resolution for BindingContext

### LINKED ISSUE #21434: Compile-time binding of BindingContext should use the inherited x:DataType
### Description

Consider a XAML element which specifies both a `BindingContext` that uses a binding from its inherited `BindingContext`, and another dependency property using a `Binding`:

- Without specifying `x:DataType` on the element, both bindings are compiled as if they refer to the inherited binding context data type
- When specifying `x:DataType` on the element, both bindings are compiled as if they refer to the newly-specified type

What you actually want is for the binding in `BindingContext` to be resolved against the inherited `BindingContext` data type, and all *other* bindings to be resolved against either the newly-specified `x:DataType` or (better) against the compile-time type of the new `BindingContext`.

### Steps to Reproduce

1. Create a new MAUI app called `ContextAndType` (or adjust the `clr-namespace` in the examples to match whatever you choose)
2. Remove all the code in MainPage.xaml.cs other than the constructor
3. Create a `ParentViewModel.cs` file containing:

```csharp
namespace ContextAndType;

public class ParentViewModel
{
    public string Text => "ParentText";
    public ChildViewModel Child { get; } = new ChildViewModel();
}

public class ChildViewModel
{
    public string Text => "ChildText";
    public string Text2 => "ChildText2";
}
```

Now we can experiment...

**Dynamic bindings**

Edit MainPage.xaml to:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:ContextAndType"
             x:Class="ContextAndType.MainPage">
    <ContentPage.BindingContext>
        <local:ParentViewModel />
    </ContentPage.BindingContext>

    <VerticalStackLayout>
        <Label Text="{Binding Text}" />
        <Label BindingContext="{Binding Child}" Text="{Binding Text}" />
    </VerticalStackLayout>

</ContentPage>
```

Note that this has no `x:DataType` specified, so the bindings are dynamic.

Run the code (I ran it on my local Android device, in the debugger, as well as on my Windows box - I don't know if Debug/Release makes any difference).

Result: Labels of "ParentText" then "ChildText"

In other words, the bindings are behaving as I'd expect:
- The first `Label` has `Text` bound to `ParentViewModel.Text`
- The second `Label` has `BindingContext` is bound to `ParentViewModel.Child`
- The second `Label` has `Text` bound to `ChildViewModel.Text`

There are three warnings of "Binding could be compiled if x:DataType is specified."

**Compiled bindings (1)**

Just add `x:DataType` of `local:ParentViewModel` to the root element:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:ContextAndType"
             x:Class="ContextAndType.MainPage"
             x:DataType="local:ParentViewModel">
    <ContentPage.BindingContext>
        <local:ParentViewModel />
    </ContentPage.BindingContext>

    <VerticalStackLayout>
        <Label Text="{Binding Text}" />
        <Label BindingContext="{Binding Child}" Text="{Binding Text}" />
    </VerticalStackLayout>
</ContentPage>
```

This still compiles, and runs with the same output. (Note that the `Text` property exists in both `ParentViewModel` and `ChildViewModel`, which is - I believe - why it compiles. Given what comes later though, I'm surprised it doesn't fail at execution time.)

**Compiled bindings (2)**

Change the second label to use the `Text2` property:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:ContextAndType"
             x:Class="ContextAndType.MainPage"
             x:DataType="local:ParentViewModel">
    <ContentPage.BindingContext>
        <local:ParentViewModel />
    </ContentPage.BindingContext>

    <VerticalStackLayout>
        <Label Text="{Binding Text}" />
        <Label BindingContext="{Binding Child}" Text="{Binding Text2}" />
    </VerticalStackLayout>
</ContentPage>
```

Result: Compile-time failure:

> XFC0045 Binding: Property "Text2" not found on "ContextAndType.ParentViewModel".

**Compiled bindings (3)**

Okay, let's be clear and specify that the type of the `BindingContext` for the second label is expected to be `ChildViewModel`, by adding `x:DataType` to it:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:ContextAndType"
             x:Class="ContextAndType.MainPage"
             x:DataType="local:ParentViewModel">
    <ContentPage.BindingContext>
        <local:ParentViewModel />
    </ContentPage.BindingContext>

    <VerticalStackLayout>
        <Label Text="{Binding Text}" />
        <Label BindingContext="{Binding Child}" Text="{Binding Text2}" x:DataType="local:ChildViewModel" />
    </VerticalStackLayout>
</ContentPage>
```

Result: Compile-time failure:

> XFC0045 Binding: Property "Child" not found on "ContextAndType.ChildViewModel".

**Compiled bindings (4)**

I've found a workaround: specify the source of the `BindingContext` `Binding`:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:ContextAndType"
             x:Class="ContextAndType.MainPage"
             x:DataType="local:ParentViewModel">
    <ContentPage.BindingContext>
        <local:ParentViewModel />
    </ContentPage.BindingContext>

    <VerticalStackLayout>
        <Label Text="{Binding Text}" />
        <Label BindingContext="{Binding Child, Source={RelativeSource AncestorType={x:Type local:ParentViewModel}}}"
               Text="{Binding Text2}" x:DataType="local:ChildViewModel" />
    </VerticalStackLayout>
</ContentPage>
```

Result: Labels of "ParentText" then "ChildText2".

So this works - but it feels clunky to have to specify it.

### Link to public reproduction project repository

https://github.com/jskeet/DemoCode/tree/main/MauiBugDemos/ContextAndType

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

_No response_

### Did you find any workaround?

1) Specifying the Source for the Binding in the BindingContext
2) Using dynamic bindings

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by simonrozsival**
### Description of Change

There is a difference between how dynamic bindings are applied and how XamlC compiles bindings when it comes to the `BindingContext` property. While the dynamic bindings use the inherited context for the `BindingContext` property, XamlC doesn't. This PR aligns the behaviors.

### Issues Fixed

Fixes #21434

/cc @StephaneDelcroix

### CODE REVIEW

File: src/Controls/tests/Xaml.UnitTests/Issues/Maui21434.cs [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+
+public class ParentViewModel21434
+{
+    public string Text => "ParentText";
+    public ChildViewModel21434 Child { get; } = new();
+}
+
+public class ChildViewModel21434
+{
+    public string Text => "ChildText";
```
Comment (StephaneDelcroix) [inline src/Controls/tests/Xaml.UnitTests/Issues/Maui21434.cs:53]: use a different property name than the one on the parent, to see if there's a compilation error (should not)

File: src/Controls/tests/Xaml.UnitTests/Issues/Maui21434.xaml [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+                    xmlns:local="clr-namespace:Microsoft.Maui.Controls.Xaml.UnitTests"
+                    x:Class="Microsoft.Maui.Controls.Xaml.UnitTests.Maui21434"
+                    x:DataType="local:ParentViewModel21434">
+    <ContentPage.BindingContext>
+        <local:ParentViewModel21434 />
+    </ContentPage.BindingContext>
+
+    <VerticalStackLayout>
+        <Label Text="{Binding Text}" x:Name="ParentTextLabel" />
+        <Label BindingContext="{Binding Child}" Text="{Binding Text}" x:DataType="local:ChildViewModel21434" x:Name="ChildTextLabel" />
```
Comment (StephaneDelcroix) [inline src/Controls/tests/Xaml.UnitTests/Issues/Maui21434.xaml:13]: could we be even smarter, and infer the x:DataType of the label ? not in all cases, but in this one it looks like we could...

**Review by StephaneDelcroix — APPROVED** [review]

File: src/Controls/tests/Xaml.UnitTests/Issues/Maui21434.xaml (hunk 2 above)
Comment (simonrozsival) [reply src/Controls/tests/Xaml.UnitTests/Issues/Maui21434.xaml:13]: I think we could, I opened a new issue so that we can discuss all the cases when we could infer x:DataTypes (https://github.com/dotnet/maui/issues/21834)

**Review by rmarinho — APPROVED** [review]

**Comment by rmarinho** [comment]
Do we need to backport this one to sr4 ?

**Comment by simonrozsival** [comment]
@rmarinho I don't think it is that urgent (there is a workaround), but it is not up to me to decide 😄

**Comment by PureWeen** [comment]
> @rmarinho I don't think it is that urgent (there is a workaround), but it is not up to me to decide 😄

I don't think so. This was also broken in 8.0.7 so don't need to rush it into SR4. It'll be out with the May release.
