### PR TITLE
[iOS] Fix crash with a hidden CarouselView

### LINKED ISSUE #13031: CarouselView crashes on iOS when outer view IsVisible is set to false
### Description

When using a CarouselView inside another layout whose visibility is set to not visible, this causes a crash on iOS with the following exception message (see log output)

### Steps to Reproduce

1. Create a new Maui project
2. Place a CarouselView with some items in its ItemsSource inside a VerticalStackLayout
3. Set IsVisible="False" on the Vertical layout

Expected outcome: Carousel shows
Actual outcome: Crash on page load on iOS

### Link to public reproduction project repository

https://github.com/dk-mushiyoke/MauiCarouselCrashRepro

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.2 simulator and device

### Did you find any workaround?

Not setting the outer layout to IsVisible="False" in xaml, but set it at a later point

### Relevant log output

```shell
ObjCRuntime.ObjCException
  Message=Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Negative sizes are not supported by flow layout. Collection view: <UICollectionView: 0x7fe391dc6a00; frame = (0 0; 0 220); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x600003e7f0c0>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x6000035da3c0>; contentOffset: {0, 0}; contentSize: {0, 0}; adjustedContentInset: {0, 0, 0, 0}; layout: <Microsoft_Maui_Controls_Handlers_Items_CarouselViewLayout: 0x7fe38b7a3930>; dataSource: <Microsoft_Maui_Controls_Handlers_Items_CarouselViewController: 0x7fe38b7a7c20>>
Native stack trace:
	0   CoreFoundation                      0x00007ff8004288ab __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80004dba3 objc_exception_throw + 48
	2   Foundation                          0x00007ff800b870cc _userInfoForFileAndLine + 0
	3   UIKitCore                           0x000000011ab19814 -[UICollectionViewFlowLayout _getSizingInfosWithExistingSizingDictionary:] + 2609
	4   UIKitCore                           0x000000011ab1ade6 -[UICollectionViewFlowLayout _fetchItemsInfoForRect:] + 228
	5   UIKitCore                           0x000000011ab14374 -[UICollectionViewFlowLayout collectionViewContentSize] + 48
	6   libxamarin-dotnet-debug.dylib       0x0000000106c2349c xamarin_dyn_objc_msgSendSuper + 220
	7   ???                                 0x0000000106752ca7 0x0 + 4403309735
	8   libmonosgen-2.0.dylib               0x00000001073ea43a ves_pinvoke_method + 474
	9   libmonosgen-2.0.dylib               0x00000001073dc6cc interp_exec_method + 3692
	10  libmonosgen-2.0.dylib               0x00000001073d9e93 interp_runtime_invoke + 259
	11  libmonosgen-2.0.dylib               0x00000001071fee68 mono_runtime_invoke_checked + 136
	12  libmonosgen-2.0.dylib               0x0000000107202ade mono_runtime_invoke + 142
	13  libxamarin-dotnet-debug.dylib       0x0000000106c1a6b0 xamarin_invoke_trampoline + 6320
	14  libxamarin-dotnet-debug.dylib       0x0000000106c22019 xamarin_arch_trampoline + 105
	15  libxamarin-dotnet-debug.dylib       0x0000000106c231fe xamarin_x86_64_common_trampoline + 118
	16  UIKitCore                           0x000000011ab0bfc4 -[UICollectionViewData _prepareToLoadData] + 172
	17  UIKitCore                           0x000000011ab0cf47 -[UICollectionViewData validateLayoutInRect:] + 51
	18  UIKitCore                           0x000000011aac3b4f -[UICollectionView layoutSubviews] + 258
	19  UIKitCore                           0x000000011bbed59f -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2305
	20  QuartzCore                          0x00007ff80898b02c _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 526
	21  QuartzCore                          0x00007ff8089965b9 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
	22  QuartzCore                          0x00007ff8088a7b0c _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 626
	23  QuartzCore                          0x00007ff8088df69b _ZN2CA11Transaction6commitEv + 735
	24  UIKitCore                           0x000000011b5daaa4 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 34
	25  CoreFoundation                      0x00007ff800387dd9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	26  CoreFoundation                      0x00007ff800387592 __CFRunLoopDoBlocks + 406
	27  CoreFoundation                      0x00007ff800381e38 __CFRunLoopRun + 948
	28  CoreFoundation                      0x00007ff8003816a7 CFRunLoopRunSpecific + 560
	29  GraphicsServices                    0x00007ff809cb128a GSEventRunModal + 139
	30  UIKitCore                           0x000000011b5baad3 -[UIApplication _run] + 994
	31  UIKitCore                           0x000000011b5bf9ef UIApplicationMain + 123
	32  libxamarin-dotnet-debug.dylib       0x0000000106bdda5a xamarin_UIApplicationMain + 58
	33  libmonosgen-2.0.dylib               0x00000001073eb609 do_icall + 345
	34  libmonosgen-2.0.dylib               0x00000001073ea113 do_icall_wrapper + 291
	35  libmonosgen-2.0.dylib               0x00000001073dc52c interp_exec_method + 3276
	36  libmonosgen-2.0.dylib               0x00000001073d9e93 interp_runtime_invoke + 259
	37  libmonosgen-2.0.dylib               0x00000001071fee68 mono_runtime_invoke_checked + 136
	38  libmonosgen-2.0.dylib               0x0000000107206e7c do_exec_main_checked + 92
	39  libmonosgen-2.0.dylib               0x0000000107335ec2 mono_jit_exec + 354
	40  libxamarin-dotnet-debug.dylib       0x0000000106c21e77 xamarin_main + 1927
	41  MauiApp3                            0x0000000106211f64 main + 68
	42  dyld                                0x00000001068bb2bf start_sim + 10
	43  ???                                 0x000000011433f310 0x0 + 4633916176

  Source=<unknown>
  StackTrace:
   at UIKit.UICollectionViewLayout.get_CollectionViewContentSize()
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewLayout.TrackOffsetAdjustment()
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewLayout.PrepareLayout()
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiApp3.Program.Main(String[] args) in C:\Users\dkong\Repo\random\MauiApp3\Platforms\iOS\Program.cs:line 13
```

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix crash with a hidden CarouselView on iOS.

### Issues Fixed

Fixes #13031

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/iOS/CarouselViewLayout.cs [hunk 1]
```diff
@@ -20,9 +20,9 @@ public CarouselViewLayout(ItemsLayout itemsLayout, CarouselView carouselView) :
 
 		public override void ConstrainTo(CGSize size)
 		{
-			//TODO: Should we scale the items 
-			var width = size.Width - _carouselView.PeekAreaInsets.Left - _carouselView.PeekAreaInsets.Right;
-			var height = size.Height - _carouselView.PeekAreaInsets.Top - _carouselView.PeekAreaInsets.Bottom;
+			// TODO: Should we scale the items 
+			var width = size.Width != 0 ? size.Width - _carouselView.PeekAreaInsets.Left - _carouselView.PeekAreaInsets.Right : 0;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items/iOS/CarouselViewLayout.cs:24]: With the Container hidden, the size is zero, and in this case by subtracting PeekAreaInsets we had a negative item size that caused the exception.

The question is, if the CarouselView is hidden, should these calculations be avoided?

**Review by rmarinho — APPROVED** [review]

File: src/Controls/src/Core/Handlers/Items/iOS/CarouselViewLayout.cs (hunk 1 above)
Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items/iOS/CarouselViewLayout.cs:24]: I think is fine.
