### PR TITLE
[ios] fix memory leak in RadioButton

### LINKED ISSUE #20023: RadioButton is not currently being Garbage Collected
### Description

Breaking out remaining work for: https://github.com/dotnet/maui/issues/18365

Add tests to ensure that RadioButton is GC.

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Context: https://github.com/heyThorsten/GCTest
Fixes: https://github.com/dotnet/maui/issues/20023

In testing the above sample, a page with a `RadioButton` has a memory leak due to the usage of `Border.StrokeShape`.

There was also a slight "rabbit" hole, where we thought there was also an issue with `GestureRecognizers`. But this was not the case in a real app (just unit tests):

* https://github.com/dotnet/maui/pull/21089

It turns out that when `GestureRecognizers` are used in `MemoryTests`, they will leak if there is no `Window` involved.

Instead of using `MemoryTests` like I would traditionally, we should instead use `NavigationPageTests.DoesNotLeak()`. I can reproduce the problem with `RadioButton` *and* a `Window` exists in the test.

## Underlying issue ##

It appears that `Border.StrokeShape` does not use the same pattern as other properties like `Border.Stroke`:

* On set: `SetInheritedBindingContext(visualElement, BindingContext);`
* On unset: `SetInheritedBindingContext(visualElement, null);`

It instead used:

* On set: `AddLogicalChild(visualElement);`
* On unset: `RemoveLogicalChild(visualElement);`

6136a8ad that introduced these does not mention why one was used over another. I am unsure if this will cause a problem, but it fixes the leak.

### CODE REVIEW

File: src/Controls/src/Core/Border/Border.cs [hunk 1]
```diff
@@ -64,7 +64,7 @@ void NotifyStrokeShapeChanges()
 
 			if (strokeShape is VisualElement visualElement)
 			{
-				AddLogicalChild(visualElement);
+				SetInheritedBindingContext(visualElement, BindingContext);
```
Comment (jonathanpeppers) [inline src/Controls/src/Core/Border/Border.cs:67]: @PureWeen maybe you remember if there is something this change would break? This makes `Border.StrokeShape` and `Border.Stroke` the same now.

Comment (PureWeen) [reply src/Controls/src/Core/Border/Border.cs:67]: This should be fine

Prior to converting this to `AddLogicalChild` we were already setting the parent
https://github.com/dotnet/maui/blame/cd7a0e021d99be3ef8c7d83437fb66f5080cd5af/src/Controls/src/Core/Border/Border.cs#L67-L68

Which is why I converted it over to `AddLogicalChild` during that big push

Stephanes changes with these changes should make this all work alright

Comment (PureWeen) [reply src/Controls/src/Core/Border/Border.cs:67]: do we need to copy the concept with parent resource propagation that's part of stroke?

https://github.com/dotnet/maui/blob/2a7abf457f6091edd113251b92d177e26da0f652/src/Controls/src/Core/Border/Border.cs#L113-L114

Comment (jonathanpeppers) [reply src/Controls/src/Core/Border/Border.cs:67]: For `Stroke`, I guess you could have a `GradientBrush` that uses a `{StaticResource}` for a color inside. That seems like it would be required.

For `StrokeShape`, I guess you can do the exact thing for something like a `double` value on some shape, so I'll make the properties the same.

File: src/Controls/src/Core/Border/Border.cs [hunk 2]
```diff
@@ -64,10 +64,13 @@ void NotifyStrokeShapeChanges()
```
Comment (PureWeen) [inline src/Controls/src/Core/Border/Border.cs:64]: Should the code that calls stop notify have this if statement?

https://github.com/dotnet/maui/blame/e3a38e231c5412831c8a968948fe0f92a1115a32/src/Controls/src/Core/Border/Border.cs#L51-L58

It seems like it should just always call stop notifying no matter what.

Comment (jonathanpeppers) [reply src/Controls/src/Core/Border/Border.cs:64]: I think both properties have a slight issue:
```
--if (newvalue is not null)
++if (oldvalue is not null)
	(bindable as Border)?.StopNotifyingStrokeShapeChanges();
```
I guess they were always this way, so I pushed this change.

**Review by PureWeen — APPROVED** [review]
