### PR TITLE
If needed, put WebView2 user data dir under LocalApplicationData. Fixes #4151

### LINKED ISSUE #4151: Application with BlazorWebView doesn't work when installed in Program Files folder
### Description

I have tried the sample app from the repository https://github.com/dotnet/maui/tree/main/src/BlazorWebView/samples/BlazorWinFormsApp
It works correctly in debug and when I install it in a normal directory, for example, c:\test, but when I install it in programfiles it gives an access denied error. 

Following the thread at https://github.com/MicrosoftEdge/WebView2Feedback/issues/297
I have tried to configure the UserDataFolder but then it gives the following error both in debug and installed

_"WebView2 was already initialized with a different CoreWebView2Environment. Check to see if the Source property was already set or EnsureCoreWebView2Async was previously called with different values"_

### Steps to Reproduce

1. Clone https://github.com/dotnet/maui/tree/main/src/BlazorWebView/samples/BlazorWinFormsApp
2. Install in Program Files folder
3. Access Denied error when running application
4. Add

 			CoreWebView2Environment env;
			CoreWebView2CreationProperties wv = new();
			wv.UserDataFolder = Path.GetTempPath() + "BlazorWebViewUserData";
			env = CoreWebView2Environment.CreateAsync(userDataFolder: wv.UserDataFolder).Result;	
			blazorWebView1.WebView.EnsureCoreWebView2Async(env);
before:

			blazorWebView1.HostPage = @"wwwroot\index.html";
			blazorWebView1.Services = services1.BuildServiceProvider();
			blazorWebView1.RootComponents.Add<Main>("#app");
			blazorWebView1.RootComponents.RegisterForJavaScript<MyDynamicComponent>("my-dynamic-root-component");

5. Error: WebView2 was already initialized with a different CoreWebView2Environment. Check to see if the Source property was already set or EnsureCoreWebView2Async was previously called with different values

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
This addresses #4151 for WinForms and WPF. @javiercn, I don't know whether the WinUI issue https://github.com/dotnet/maui/issues/5024 is the same thing or different, but if it turns out to be the same thing (Dan suspects not), you can easily make use of the logic I'm adding here.

Rather than relocate it in all cases, I've made it prefer to keep the default location if the application has write permission. This helps to keep things self-contained during development and not litter the developer's hard disk with temporary directories in LocalAppData.

### CODE REVIEW

File: src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs [hunk 1]
```diff
@@ -125,7 +127,7 @@ public class WebView2WebViewManager : WebViewManager
 		/// <param name="jsComponents">Describes configuration for adding, removing, and updating root components from JavaScript code.</param>
 		/// <param name="hostPageRelativePath">Path to the host page within the <paramref name="fileProvider"/>.</param>
 		/// <param name="blazorWebViewHandler">The <see cref="BlazorWebViewHandler" />.</param>
-		public WebView2WebViewManager(
```
Comment (SteveSandersonMS) [inline src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs:128]: I made the two constructors internal because I'm not aware of a reason for them to be public. It's used across all the supported platforms via shared source.

If I'm wrong, I'm happy to change this back. However we've changed the parameter list several times now, so it suggests we'll keep changing it in the future, and maintaining back-compat if it's a public API could become very messy.

**Comment by javiercn** [comment]
@SteveSandersonMS how are you creating the "installer". Shouldn't that set write permissions for the directory based on which user is writing to the folder?

I vaguely remember discussing this with Eilon, and I believe the default should be to put data on the user profile directory. Keep in mind that multiple users might use the same installed program, and we don't want them getting data from other users.

**Comment by SteveSandersonMS** [comment]
> how are you creating the "installer". Shouldn't that set write permissions for the directory based on which user is writing to the folder?

Writing to anything under program files requires elevation. The application is generally not going to be run with elevation, so it won't be able to write to the directory it's installed into.

> I believe the default should be to put data on the user profile directory

That is what will happen with this change. LocalAppData is within a user account.

> I think we should optimize here for the expected deployment experience and not the development experience

I'm optimizing for both. Why not?

File: src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs [hunk 2]
```diff
@@ -309,6 +315,54 @@ private void ApplyDefaultWebViewSettings(BlazorWebViewDeveloperTools devTools)
...
+
+#if WEBVIEW2_WINFORMS || WEBVIEW2_WPF
+		private static string GetUserDataFolderOverride()
+		{
+			if (Assembly.GetEntryAssembly() is { } mainAssembly)
+			{
+				// Where possible, and especially in development, we prefer not to override the WebView2 default behavior of creating
+				// its user data directory in the application folder. This helps to avoid littering the developer's user profile directory
+				// if they are repeatedly creating test applications.
+				if (!string.IsNullOrEmpty(mainAssembly.Location)
```
Comment (javiercn) [inline src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs:327]: FYI, this will break with single file deployments (PublishSingleFile)

**Review by javiercn — APPROVED** [review]

File: src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs [hunk 3]
```diff
@@ -309,6 +315,54 @@ private void ApplyDefaultWebViewSettings(BlazorWebViewDeveloperTools devTools)
...
+			}
+
+			try
+			{
+				var path = Path.Combine(withinDirectory, Guid.NewGuid().ToString());
+				var dirInfo = Directory.CreateDirectory(path);
+				Directory.Delete(path, false);
+				return true;
+			}
+			catch (Exception)
```
Comment (Eilon) [inline src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs:360]: I don't like shipping code that expects exceptions. I'd rather pick a better default location and avoid this.

**Review by Eilon — CHANGES_REQUESTED** [review]

**Comment by SteveSandersonMS** [comment]
OK let's try to summarize the tradeoff we're making. I think there are two concrete concerns being expressed in the CR comments above:

 1. This is hard to customize
 2. This relies on catching an exception

For 1, that doesn't really concern me because there is already a predefined customization mechanism provided by WebView2. You can either set an env var, or a registry key, telling it where to put the user data and it will use that in preference over anything set by our code here. We don't need to create yet another layer of customizability - all we need to do is establish a default behavior that isn't broken, which this approach does. So I'm discounting this concern.

For 2, I do agree the exception is unpleasant. Normally the most objective problem it causes is if you have a debugger attached as you might be stopping on first-chance exceptions. In this case that's rarely going to matter because in development this won't throw, and in prod you'd rarely have a debugger attached during app launch. However it's still not delightful to be doing this.

The opposite side of the balance is the dev experience. Eilon asks "is this a problem" and it's subjective. One concrete bit of data is that my LocalAppData directory currently contains a grand total of 47 app folders, whereas my VS `source\repos` dir regularly gets into the hundreds. If each of the latter left behind a LocalAppData directory, the app junk would completely dominate. Each of them is ~24MB, so it wouldn't be surprising to have 2GB+ of these junk folders which you couldn't easily clean up because you'd have to go through the list one by one to avoid deleting good app dirs. I guess we *could* partially solve this by a further subdirectory convention like LocalAppData\BlazorHybrid\YourAppName.

So I think that's the truth of it: we trade off making it harder for devs to manage left-behind junk against catching an exception.

I don't have any reason to make a big fight over this so if you're both committed to favouring leaving junk over catching exceptions, then I'm OK with going that way.

**Comment by SteveSandersonMS** [comment]
If the use of exception-catching can be avoided by using `System.IO.FileSystem.AccessControl` instead, will you still have objections?

**Comment by Eilon** [comment]
> If the use of exception-catching can be avoided by using `System.IO.FileSystem.AccessControl` instead, will you still have objections?

I have a bad feeling that using that API would not be reliable at all. Does it actually compute _effective_ ACLs on a file system object as opposed to just the ACLs on the object itself? Also, I thought that even admins have to elevate to write to certain folders, even if they have access based on ACLs? (Not sure about that.)

I'm not a huge fan of littering, either. But I think it's more important to have the "best code" (subjective, I know) on production apps.

I think it's best if we get together to discuss. Hopefully we can find a compromise where we are all _equally unhappy_ with the solution 😁

**Comment by SteveSandersonMS** [comment]
OK, after discussion, the logic here now uses the LocalAppData location in all cases, even if we could write inside the app folder. This is primarily so developers don't have to reason about why it might be in different places based on different conditions.

We've kept the `.WebView2` suffix to minimize the risk of clashes with unrelated use of LocalAppData folders, especially if the developer has their own logic for creating/destroying a folder at `%LocalAppData%\MyApplicationName`.

**Review by Eilon — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS is this ready to be merged?

**Comment by SteveSandersonMS** [comment]
Yes, was just waiting for the build. I should have used automerge.
