### PR TITLE
Fix layout and safe area on FlyoutPage

### LINKED ISSUE #6408: FlyoutPage issues on macOS
### Description

I use a FlyoutPage to contains a ContentPage(gray area, named MainWindow), have 2 issues when run on macOS:

**1. The Bottom edge of App is higher than ContentPage's about 40 pixels (see fig. below)**

image
  So I have to expand the bottom edge by dragging to show ContentPage completely, see fig below:
image

**2. ContentPage, inside of LayoutPage, cant't resizing automatically by resizing App border.**
   see fig. below and the gray area is ContentPage:
image

note: I attached project zip file and hope can help you.

[MyFlyoutApp.zip](https://github.com/dotnet/maui/files/8539124/MyFlyoutApp.zip)

### Steps to Reproduce

1. Create a MAUI project base on 6.0.202;
2. Create a NavigationPage and then assign it to MainPage in App.xaml.cs;
3. Change MainPage's parent Class from ContentPage to FlyoutPage;
4. Create a ContentPage named 'MainWindow' and add it into MainPage( type of FlyoutPage) as DetailPage;
5. Build and run the app;

### Version with bug

Preview 14

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Version 12.0.1

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

- Change Catalyst so that "UseSafeArea" is true by default. On Catalyst the SafeArea is the title bar so if you don't account for it the content just vanishes behind the title bar. For example, currently if you just put a ContentPage on the screen with a label the label will just vanish behind the titlebar.
- fix the check inside PhoneFlyoutPageRenderer so it checks the correct properties to figure out if it should call layout with the new size

### Issues Fixed

Fixes #6408

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs [hunk 1]
```diff
@@ -87,8 +87,8 @@ public void SetElement(VisualElement element)
 
 			_clickOffView = new UIView();
 			_clickOffView.BackgroundColor = new Color(0, 0, 0, 0).ToPlatform();
-			Presented = ((FlyoutPage)element).IsPresented;
 			_viewHandlerWrapper.SetVirtualView(element, OnElementChanged, false);
+			Presented = ((FlyoutPage)element).IsPresented;
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs:91]: This fixes an NRE caused by setting `Presented` before the `_viewHandlerWrapper` has been set.

File: src/Controls/src/Core/PlatformConfiguration/iOSSpecific/Page.cs [hunk 2]
```diff
@@ -71,7 +71,13 @@ public static UIStatusBarAnimation PreferredStatusBarUpdateAnimation(this IPlatf
 		}
 
 		/// <include file="../../../../docs/Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific/Page.xml" path="//Member[@MemberName='UseSafeAreaProperty']/Docs/*" />
-		public static readonly BindableProperty UseSafeAreaProperty = BindableProperty.Create("UseSafeArea", typeof(bool), typeof(Page), false);
+		public static readonly BindableProperty UseSafeAreaProperty = BindableProperty.Create("UseSafeArea", typeof(bool), typeof(Page),
```
Comment (PureWeen) [inline src/Controls/src/Core/PlatformConfiguration/iOSSpecific/Page.cs:74]: Part of me thinks we should just make this true by default on `iOS` also. It seems like not wanting to account for the safe area is the odd one out.

File: src/Core/src/Platform/iOS/ViewExtensions.cs [hunk 3]
```diff
@@ -594,29 +594,48 @@ internal static IDisposable OnLoaded(this UIView uiView, Action action)
 			}
 
 			Dictionary<NSString, NSObject> observers = new Dictionary<NSString, NSObject>();
-			ActionDisposable? disposable = new ActionDisposable(() =>
+			ActionDisposable? disposable = null;
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/ViewExtensions.cs:597]: The modifications here all were necessary to fix `FlyoutPage` so it would fire `Loaded`. The Unit Tests use `Loaded` to know when to proceed with the tests.

File: src/Controls/src/Core/PlatformConfiguration/iOSSpecific/Page.cs (hunk 2 above)
Comment (rmarinho) [reply src/Controls/src/Core/PlatformConfiguration/iOSSpecific/Page.cs:74]: yeah i agree think before was different because it was a "new" feature and we didn't want to break existing apps.

Comment (PureWeen) [reply src/Controls/src/Core/PlatformConfiguration/iOSSpecific/Page.cs]: Chatted with @davidortinau about this one a bit as well and he's all for just defaulting this to `true`

**Review by hartez — APPROVED** [review]
