### PR TITLE
[Android] Fixed back button icon selection logic in ShellToolbarTracker

### LINKED ISSUE #32050: IconOverride in Shell.BackButtonBehavior does not work.
### Description

The IconOverride property does not seem to function with stack layout, I tried many different images but the arrow stays the same default arrow or there's only white space.

### Steps to Reproduce

1. Create new default MAUI project
2.  Create new XAML content page and register the routing
3. Give the new page the following code between  <Shell.BackButtonBehavior>

        <BackButtonBehavior IconOverride="arrow.jpg" Command="{Binding BackCommand}"/>
(Image can be anything)

4. Go to the main page and change the button function to go to the new page via GoToAsync
5.  The default arrow to go back to the previous page is still there

### Link to public reproduction project repository

https://github.com/PXLSascha/BUGTEST

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

Android

### Affected platform versions

Android 15.0 - API 35

### Did you find any workaround?

No

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Description of Change

Updates the logic for selecting the back button icon to use the IconOverride property when FlyoutBehavior is not Flyout. This ensures the correct icon is displayed based on the current behavior.

Regressing PR: https://github.com/dotnet/maui/pull/29637

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/32050

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs [hunk 1]
```diff
@@ -412,8 +412,7 @@ protected virtual async void UpdateLeftBarButtonItem(Context context, AToolbar t
 			var command = backButtonHandler.GetPropertyIfSet<ICommand>(BackButtonBehavior.CommandProperty, null);
 			var backButtonVisibleFromBehavior = backButtonHandler.GetPropertyIfSet(BackButtonBehavior.IsVisibleProperty, true);
 			bool isEnabled = _shell.Toolbar.BackButtonEnabled;
-			//Add the FlyoutIcon only if the FlyoutBehavior is Flyout
-			var image = _flyoutBehavior == FlyoutBehavior.Flyout ? GetFlyoutIcon(backButtonHandler, page) : null;
+			var image = _flyoutBehavior == FlyoutBehavior.Flyout ? GetFlyoutIcon(backButtonHandler, page) : backButtonHandler.GetPropertyIfSet<ImageSource>(BackButtonBehavior.IconOverrideProperty, null);
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs:419]: Can you include a related UITest? Let me know if can help with it.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs (hunk 1 above)
Comment (kubaflo) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs:419]: Sure! Test added

**Comment by kubaflo** [comment]
# Review Feedback: PR #32080 - Fix IconOverride in Shell.BackButtonBehavior

## Summary

PR #32080 correctly fixes the regression where `BackButtonBehavior.IconOverride` was ignored on Android when `FlyoutBehavior` is not `Flyout`. The fix is minimal, focused, and addresses the root cause identified in PR #29637.

**Recommendation**: ✅ **Approve with minor test improvements**

---

## Code Review

### Core Fix Analysis

**File**: `src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs`

**Change** (Line 415):
```csharp
// Before (regressed in PR #29637):
var image = _flyoutBehavior == FlyoutBehavior.Flyout ? GetFlyoutIcon(backButtonHandler, page) : null;

// After (this PR):
var image = _flyoutBehavior == FlyoutBehavior.Flyout ? GetFlyoutIcon(backButtonHandler, page) : backButtonHandler.GetPropertyIfSet<ImageSource>(BackButtonBehavior.IconOverrideProperty, null);
```

**Why it works**:
- `GetFlyoutIcon()` (line 368) already checks `IconOverride` FIRST, then falls back to `FlyoutIcon`
- When `FlyoutBehavior == Flyout`: Uses `GetFlyoutIcon()` which tries IconOverride → FlyoutIcon
- When `FlyoutBehavior != Flyout`: Directly retrieves IconOverride (no FlyoutIcon fallback needed)
- The regression occurred because the else branch was changed to `null`, completely ignoring IconOverride

**Edge cases considered**:
- ✅ IconOverride with Flyout behavior → Still works (uses GetFlyoutIcon)
- ✅ IconOverride without Flyout behavior → Fixed by this PR
- ✅ No IconOverride set → Returns null (correct default behavior)
- ✅ Multiple navigation levels → IconOverride is per-page, so works correctly

**Code Quality**:
- ✅ Minimal change (single line)
- ✅ No performance impact
- ✅ Follows existing patterns
- ✅ Proper null handling

---

## Test Coverage Review

### UI Tests Added

**Files**:
- `src/Controls/tests/TestCases.HostApp/Issues/Issue32050.xaml`
- `src/Controls/tests/TestCases.HostApp/Issues/Issue32050.xaml.cs`
- `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue32050.cs`

**Test Structure**: ✅ Follows established patterns
- Shell-based test page with navigation to subpage
- Subpage sets `BackButtonBehavior.IconOverride = "coffee.png"`
- Appium test waits for element and captures screenshot

### Issues Found in Tests

#### 🔴 Critical Issue #1: Wrong Platform Attribute

**Location**: `src/Controls/tests/TestCases.HostApp/Issues/Issue32050.xaml.cs` line 3

**Current**:
```csharp
[Issue(IssueTracker.Github, 32050, "IconOverride in Shell.BackButtonBehavior does not work.", PlatformAffected.iOS)]
```

**Should be**:
```csharp
[Issue(IssueTracker.Github, 32050, "IconOverride in Shell.BackButtonBehavior does not work.", PlatformAffected.Android)]
```

**Why**: 
- The fix is in Android-specific code (`ShellToolbarTracker.Android.cs`)
- Issue #32050 reports Android platform
- Using `PlatformAffected.iOS` will cause the test to run on wrong platform

#### 🟡 Suggestion #1: Wrong Test Category

**Location**: `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue32050.cs` line 16

**Current**:
```csharp
[Category(UITestCategories.TitleView)]
```

**Should be**:
```csharp
[Category(UITestCategories.Shell)]
```

**Why**:
- This tests Shell back button behavior, not TitleView
- Using wrong category makes test harder to find and may skip it in Shell-specific test runs
- Check `UITestCategories.cs` for available categories

#### 💡 Suggestion #2: Test Coverage

**Current approach**: Screenshot-only verification

**Enhancement opportunity**:
- Screenshot verification is appropriate for icon appearance
- Consider adding programmatic check if icon element is present (if Appium exposes it)
- Current approach is acceptable for this fix

---

## Testing

### Manual Testing (Checkpoint Required)

❌ **Unable to test on Android**: No Android SDK/emulator available in current environment

**Testing checkpoint created**:
- ✅ Test code prepared in Sandbox app
- ✅ Test approach validated
- ⏸️ **Requires Android device/emulator** to complete validation

### Recommended Testing Steps

1. **Test WITHOUT PR** (verify bug exists):
   ```bash
   # Checkout version before fix
   git checkout 8b0b8be8 -- src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs
   
   # Build and deploy
   dotnet build src/Controls/samples/Controls.Sample.Sandbox/Maui.Controls.Sample.Sandbox.csproj -f net10.0-android -t:Run
   
   # Navigate to second page
   # Expected: Back button shows default arrow (BUG)
   ```

2. **Test WITH PR** (verify fix works):
   ```bash
   # Restore PR version
   git checkout pr-32080 -- src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs
   
   # Build and deploy
   dotnet build src/Controls/samples/Controls.Sample.Sandbox/Maui.Controls.Sample.Sandbox.csproj -f net10.0-android -t:Run
   
   # Navigate to second page
   # Expected: Back button shows custom icon (FIXED)
   ```

---

## Security Review

✅ No security concerns:
- Changes only affect icon selection logic
- No user input handling
- No external data access
- No new dependencies

---

## Breaking Changes

✅ No breaking changes:
- Restores previous behavior (fixes regression)
- No API changes
- No behavioral changes for other scenarios

---

## Documentation

✅ Adequate:
- PR description clearly explains the issue and fix
- Code comment removed (was outdated)
- No XML doc changes needed (internal implementation)

---

## Issues to Address

### Must Fix Before Merge

1. ✅ **Core fix**: Correct and complete
2. 🔴 **Platform attribute**: Change `PlatformAffected.iOS` to `PlatformAffected.Android` in Issue32050.xaml.cs

### Should Fix (Recommended)

3. 🟡 **Test category**: Change `UITestCategories.TitleView` to `UITestCategories.Shell` in Issue32050.cs

### Optional Improvements

4. 💡 Consider adding comment explaining the ternary logic for future maintainers:
   ```csharp
   // When Flyout behavior is active, GetFlyoutIcon checks IconOverride then FlyoutIcon
   // Otherwise, just use IconOverride directly (no FlyoutIcon fallback)
   var image = _flyoutBehavior == FlyoutBehavior.Flyout ? GetFlyoutIcon(backButtonHandler, page) : backButtonHandler.GetPropertyIfSet<ImageSource>(BackButtonBehavior.IconOverrideProperty, null);
   ```

---

## Approval Checklist

- [x] Code solves the stated problem correctly
- [x] Minimal, focused changes
- [x] No breaking changes
- [x] Appropriate test coverage exists
- [x] No security concerns
- [x] Follows .NET MAUI conventions
- [ ] Platform attribute needs correction (blocking)
- [ ] Test category should be updated (recommended)
- [ ] Manual Android testing needed (cannot complete in current environment)

---

## Final Recommendation

**Status**: ✅ **Approve with required changes**

**Required changes**:
1. Fix platform attribute: `PlatformAffected.iOS` → `PlatformAffected.Android`

**Recommended changes**:
2. Update test category: `UITestCategories.TitleView` → `UITestCategories.Shell`

**Manual testing**: Should be performed on Android device/emulator before final merge to visually confirm the icon appears correctly.

---

## Review Metadata

- **Reviewer**: @copilot (PR Review Agent)
- **Review Date**: 2025-11-20
- **PR Number**: #32080
- **Issue Number**: #32050
- **Platforms Tested**: None (Android SDK unavailable in environment)
- **Test Approach**: Code review + test design validation

**Comment by Larhei** [comment]
Is there any plan when this is merged and public available?
