### PR TITLE
[iOS] Fix UI loop when setting ContentInset

### LINKED ISSUE #20294: [iOS] CollectionView containing a Footer and a Border with StrokeThickness set to decimal value crashes on scroll
### Description

If CollectionView has the following:

1. Enough item elements to be scrollable (vertically)
2. <CollectionView.Footer> element. I have just a content view of a certain height. 
```
        <CollectionView.Footer>
            <ContentView HeightRequest="100"></ContentView>
        </CollectionView.Footer>
```
4. Each item contains a Border with StrokeThickness set to a decimal value (0.6 for instance)
```
        <CollectionView.ItemTemplate>
            <DataTemplate x:DataType="x:String">
                <Border StrokeThickness="0.6">
                    <Label
                        Text="{Binding}"
                        FontSize="20"/>
                </Border>
            </DataTemplate>
        </CollectionView.ItemTemplate>
```

then when you scroll up and then down the app crashes becasue of 
> Fatal error: <UICollectionView 0x28398dec0> is stuck in its recursive layout loop.

Full code is linked below. 

This occurs only in iOS and maui version 8.0.6

```
	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.6" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.6" />
	</ItemGroup>

```

https://github.com/dotnet/maui/assets/36049508/03682b61-a589-4810-b985-9642daf2a40e

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

https://github.com/MichaelShapiro/MauiBugs/tree/master

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

I found three options to choose from:

1. Downgrading to maui 8.0.3

2. Getting rid of the CollectionView Footer
 
3. Using only whole number for the StrokeThickness value, such as 1

### Relevant log output

```shell
UIKitCore/_UICollectionViewFeedbackLoopDebugger.swift:87: Fatal error: <UICollectionView 0x28398dec0> is stuck in its recursive layout loop. This can happen when self-sizing views do not return consistent sizes, or the collection views frame/bounds/contentOffset is being constantly adjusted. To debug this issue, check the Console app for logs in the "UICollectionViewFeedbackLoopDebugger" category.
Collection view: <UICollectionView: 0x1109f7e00; frame = (0 0; 355 704); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x28392b060>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x2832611a0>; contentOffset: {0, 375.5}; contentSize: {355, 1252}; adjustedContentInset: {0, 0, 100, 0}; layout: <Microsoft_Maui_Controls_Handlers_Items_ListViewLayout: 0x10be4a940>; dataSource: <Microsoft_Maui_Controls_Handlers_Items_ReorderableItemsViewController_1: 0x10bfd1400>>

The app has been terminated.
```

### LINKED ISSUE #20320: [iOS] Grouped CollectionView with a Footer stutters under MAUI 8.0.6
### Description

After updating to MAUI 8.0.6, CollectionView with Footer and IsGrouped="True" stutters and lags when scrolling. Stuttering is so significant that renders the use of such CollectionView impractical.

This can be related to #20294 

This is MAUI 8.0.6 - performance is degraded

https://github.com/dotnet/maui/assets/36049508/130cfcc0-e68a-4827-927a-b1e6bf593a51

This is MAUI 8.0.3 - performance is normal

https://github.com/dotnet/maui/assets/36049508/d0bb22c8-2d4b-4341-8eba-cb8d8ab3fb1e   

### Steps to Reproduce

Open repo in the link below. Start CollectionViewFooter project.

### Link to public reproduction project repository

https://github.com/MichaelShapiro/MauiBugs

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.3

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

Two options:

1. Downgrade back to MAUI 8.0.3
2. Remove Footer from the CollectionView

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

Seems that we are always firing the bonds change even If they don't change, for example when the Bounds are similar when using CloseTo we should treat as the Bounds didn't change, but the code was always returning true there.

This issue also happens because when we use a footer we also set insets to the CollectionView that cause the Bounds event to change 

Fixes #20294 
Fixes #20320

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs [hunk 1]
```diff
@@ -133,16 +133,18 @@ internal void UpdateSubview(object view, DataTemplate viewTemplate, nint viewTag
 			}
 
 			if (formsElement != null)
+			{
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs:136]: These changes  on this file is just small cleanup and seems we need braces now :)

**Review by jsuarezruiz — DISMISSED** [review]

**Review by mattleibow — DISMISSED** [review]

**Review by PureWeen — APPROVED** [review]

**Comment by PureWeen** [comment]
Test failures aren't related to this PR

this PR only touches iOS and the failures are known flakey areas on Android/Windows
