### PR TITLE
[iOS] Pasting long text when the editor has a max length

### LINKED ISSUE #17783: [ManualMauiTests] Pasting long test when the editor has a max length does nothing
### Description

Pasting some long text into the editor does nothing. Shorter text works.

I would have expected the text just to be cropped.

### Steps to Reproduce

1. Clone ManualMauiTests
2. Run
3. Go to D | D3
4. Paste some long text in the editor
5. Observe nothing happens

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS, I was *not* able test on other platforms

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/17783

|Android (current)|
|--|
|<video src="https://github.com/user-attachments/assets/d22139b4-e4bf-458c-8e27-f1e324fd99ca" width="300px"/>|

|iOS (current)|iOS(fixed)|
|--|--|
|<video src="https://github.com/user-attachments/assets/68d74da0-afef-4908-80ce-e5f16566209b" width="300px"/>|<video src="https://github.com/user-attachments/assets/37a4d007-e7f4-4c0e-9356-0e052aa129af" width="300px"/>|

### CODE REVIEW

File: src/Core/src/Core/Extensions/ITextInputExtensions.cs [hunk 1]
```diff
@@ -39,7 +39,13 @@ public static bool TextWithinMaxLength(this ITextInput textInput, string? text,
 
 			var newLength = currLength + addLength - remLength;
 
-			return newLength <= textInput.MaxLength;
+			var shouldChange = newLength <= textInput.MaxLength;
```
Comment (jsuarezruiz) [inline src/Core/src/Core/Extensions/ITextInputExtensions.cs:42]: Could include a related UITest?

**Comment by kubaflo** [comment]
@jsuarezruiz I've added a UI Test

**Comment by baaaaif** [comment]
What is it that this correction is not reviewed and merged? Assigned to the wrong reviewers? How is the process defined that some good, simple and small corrections do not end up in any SR Milestone and are not given any attention?

Just out of interest :)

**Comment by ronanj2** [comment]
Hi @rachelkang,
Do you know when this fix will be merged and released?

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17783.cs [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+		[Test]
+		[Category(UITestCategories.Editor)]
+		[Category(UITestCategories.Entry)]
+		public void TextShouldBeCut()
+		{
+			App.WaitForElement("PasteToEntryButton");
+			App.Click("PasteToEntryButton");
+			App.Click("PasteToEditorButton");
+			var entryText = App.FindElement("Entry").GetText;
+			var editorText = App.FindElement("Editor").GetText;
```
Comment (jfversluis) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17783.cs]:
```suggestion
			var entryText = App.FindElement("Entry").GetText();
			var editorText = App.FindElement("Editor").GetText();
```

**Review by jfversluis — APPROVED** [review]
