### PR TITLE
[Reverted] ToolbarItem behavior with ImageSource iOS - fix

### LINKED ISSUE #28822: ToolbarItem behavior with ImageSource iOS
### Description

For a while now ive had a pure white icon on my very clearly not pure white image if I used it as an IconImageSource for my ToolbarItem.
After trying to do things with styling and custom renderers I fixed this for shell pages but for regular NavigationPages this was still broken.

I found that if I added images through the old xcassets method that then the images are not pure white.

Included is a repository with a reproduction. Altough here the icon is black. Think some styling i have makes my icon white.
A basic maui template with 2 images added. one to the Resources/Images folder and included as MauiImage
and one added as an old school xcassets in iOS/Platforms.
The main page has two toolbars. one uses the image from xcassets. the other from resources/images.

Image

### Steps to Reproduce

Repro included

### Link to public reproduction project repository

https://github.com/Gekidoku/IconsTest

### Version with bug

9.0.50 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions, Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

Adding items as Xcassets does work. Though this is not desireable.

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
### Reverted

https://github.com/dotnet/maui/pull/31112

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/28822

|Before|After|
|--|--|
|||

### CODE REVIEW

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

**Review by rmarinho — APPROVED** [review]

File: src/Controls/src/Core/Compatibility/iOS/Extensions/ToolbarItemExtensions.cs [hunk 1]
```diff
@@ -112,7 +112,9 @@ void UpdateIconAndStyle(ToolbarItem item)
 					}
 					item.IconImageSource.LoadImage(mauiContext, result =>
 					{
-						Image = result?.Value;
+						Image = item.IconImageSource is not FontImageSource
+							? result?.Value.ImageWithRenderingMode(UIImageRenderingMode.AlwaysOriginal)
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/iOS/Extensions/ToolbarItemExtensions.cs:116]: Can we add the color to the "ToUIBarButtonItem" call?

Or maybe we can add a bool that will indicate whether to toggle between the different rendering modes based on if BarTextColor is set?

That way the behavior should be pretty much the same as before
