### PR TITLE
[iOS] - Resolved Proper Rendering of Dynamic Header/Footer Updates in CV2

### LINKED ISSUE #28504: Header/Footer Template and View Synchronization Issue in .NET MAUI CollectionView (CV2)
### Description

There is an unintended synchronization between the HeaderTemplate/FooterTemplate and Header/Footer views in .NET MAUI CollectionView(CV2). When setting a header or footer template, the corresponding header/footer view is also updated, and vice versa. These properties should function independently.

 
https://github.com/user-attachments/assets/201dbef9-3b61-4d0b-ba33-9676bceddbc9 

https://github.com/user-attachments/assets/8a990210-5832-49a2-8b46-d71997950bec

### Steps to Reproduce

1. Launch the Application on  iOS and Catalyst [GroupingSample.zip](https://github.com/user-attachments/files/19364468/GroupingSample.zip)

2. Select HeaderTemplate for the CollectionView.
3. Then Select none for HeaderTemplate (set to null).
4. Then, select Header View and observe that the header view is not updated—it only displays the HeaderTemplate. The same issue occurs with the Footer.
5.  Re-Run the application.
6. Now , first select the Header View for the CollectionView.
7. Then select none for Header (set to null).
8. Then, select HeaderTemplate and observe that the header template is not updated correctly—it only displays the Header View. This issue also occurs with the Footer.

Expected Behavior:

- The HeaderTemplate and Header view should remain independent.

- The FooterTemplate and Footer view should remain independent.

- Changing one property should not automatically update the other.

Actual Behavior:

Header/Footer properties are updated when selecting HeaderTemplate/Footer Template, and Header/Footer Template are updated when selecting Header/Footer view causing unintended behavior.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.50 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

iOS, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### LINKED ISSUE #28509: GroupHeaderTemplate and GroupFooterTemplate Not Displaying in CollectionView(CV2)
### Description

In CollectionView2, the GroupHeaderTemplate and GroupFooterTemplate are not displayed when IsGrouped is set to true and a GroupedList is assigned as the ItemsSource. The expected behavior is that the group header and footer should be visible when templates are set, but they do not appear.

https://github.com/user-attachments/assets/c64fc97c-f9c9-425b-abf4-a6e697b92fb0

https://github.com/user-attachments/assets/65715cf5-4e6d-4bbd-b08c-d601444051fb

### Steps to Reproduce

1. Launch the Application iOS and Catalyst  [GroupingSample2.zip](https://github.com/user-attachments/files/19342439/GroupingSample2.zip)
2. Set ItemsSource to Grouped List.
3. Set IsGrouped to True.
4. Select GroupHeaderTemplate.
5. Observe that the group header  template is not displayed.
6. Select GroupFooterTemplate.
7. Observe that the group Footer template is not displayed.

Expected Behavior:
The group header template and group footer template should be visible when IsGrouped is true and a grouped ItemsSource is assigned.

Actual Behavior:
The GroupHeaderTemplate and GroupFooterTemplate do not appear in the UI.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.50 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

iOS, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by prakashKannanSf3972**
### Issue Details:
 
- When the Group Header/Footer Template is not initially set and is later assigned at runtime, the CollectionView does not properly update to reflect the new Group Header/Footer content.

- When the Header or Footer of a CollectionView is initially set and later updated dynamically with a new DataTemplate or object, the UI does not correctly reflect the updated value.
 
### Root Cause:

The PlatformHandler retains the handler for the initial Header/Footer view even after it is dynamically replaced. As a result:
- The old view remains in the UI hierarchy.
- The new view is not properly added to the ItemsView.

### Description of Change

- Mapped GroupHeaderTemplate and GroupFooterTemplate in the handler to trigger a layout update, ensuring the CollectionView dynamically reflects template changes.

- This update enhances the handling of dynamic CollectionView header and footer updates by ensuring proper cleanup of previous view references. When the header or footer content is changed, the previous handler is nullified, the old view is removed from the UI hierarchy, and binding contexts are cleared. These improvements ensure that the new content is rendered correctly without retaining outdated references.

**Tested the behaviour in the following platforms**

- [ ] Android
- [x]  Windows
- [x]  iOS
- [x] Mac

### Issues Fixed

Fixes #28509 
Fixes #28504 

### Output

| Before| After|
|--|--|
| <video src="https://github.com/user-attachments/assets/08e5bcfd-2167-4ac5-80be-4b341e999fa8"> | <video src="https://github.com/user-attachments/assets/f87e68a4-f172-4649-82ee-97b3a03ef534"> |

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs [hunk 1]
```diff
@@ -40,6 +40,7 @@ public event EventHandler<LayoutAttributesChangedEventArgs2> LayoutAttributesCha
 		Size _cachedConstraints;
 
 		internal bool MeasureInvalidated => _measureInvalidated;
+		internal bool isHeaderOrFooterChanged = false;
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs:43]: Why is this added? What do we use it for?

**Comment by rmarinho** [comment]
Please retarget the inflight branch

File: src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs (hunk 1 above)
Comment (prakashKannanSf3972) [reply src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs:43]: @rmarinho,

Since both the header and footer are handled as cell types along with regular `ItemTemplate` cells, the binding logic is shared for both item cells and header/footer cells within the same function. However, when only the header or footer values change, there is no need to recycle the content of templated item cells by cleaning up old views and creating new ones.
 
The introduced flag helps identify such scenarios and ensures that effectively avoiding redundant validation and view recycling for templated item cells and preventing any negative impact on performance, specifically during header or footer updates.

**Comment by prakashKannanSf3972** [comment]
> Please retarget the inflight branch

I have retargeted to the inflight branch.

File: src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs:43]: Can include a small comment in the code explaining that's used to avoiding redundant validation?

Comment (prakashKannanSf3972) [reply src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs:45]: Thanks @jsuarezruiz, Added a comment to clarify its role in avoiding unnecessary validation when only the header/footer changes.

**Review by rmarinho — APPROVED** [review]
