### PR TITLE
[CollectionView] Crash occurs when switching CollectionView.IsVisible right after setting ItemsSource 

### LINKED ISSUE #28162: [CollectionView]Crash occurs when switching CollectionView.IsVisible right after setting ItemsSource
### Description

When switching the visibility of CollectionView (i.e., toggling IsVisible), a crash occurs if the ItemsSource has just been set. This issue seems to be related to the timing between updating the ItemsSource and changing the visibility of the CollectionView.

### Steps to Reproduce

1. Set ItemsSource to a collection of items.
2. Immediately toggle the IsVisible property of the CollectionView.
3. The application crashes.

### Link to public reproduction project repository

https://github.com/maonaoda/MauiBugs/tree/Bug/28162-visibility-to-childs

### Version with bug

Nightly / CI build (Please specify exact version)
https://github.com/dotnet/maui/pull/20154

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

9.0.40 SR4

### Affected platforms

I was *not* able test on other platforms, iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

The error occurs because the children's collection is modified while iterating over it. To fix this, we should iterate over a snapshot of the collection instead of the collection itself. The crash happened only on iOS and only when ItemSource is ObservableCollection

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/28162

```xaml
<VerticalStackLayout>
    <Button Text="Toggle visibility"
            Clicked="Button_Clicked"/>
    <CollectionView IsVisible="True"
                    HorizontalOptions="Center"
                    VerticalOptions="Center"
                    x:Name="CollectionView">
        <CollectionView.Header>
            <ContentView HeightRequest="50"
                            BackgroundColor="Green"/>
        </CollectionView.Header>
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <Border StrokeShape="RoundRectangle 10"
                        Padding="20"
                        Stroke="Red">
                    <Label HorizontalOptions="Center"
                            VerticalOptions="Center"
                            Text="{Binding .}"/>
                </Border>
            </DataTemplate>
        </CollectionView.ItemTemplate>
        <CollectionView.Footer>
            <ContentView HeightRequest="50"
                            BackgroundColor="Green"/>
        </CollectionView.Footer>
    </CollectionView>
</VerticalStackLayout>
```

```c#
private void Button_Clicked(object sender, EventArgs e)
{
	CollectionView.IsVisible = !CollectionView.IsVisible;
	CollectionView.ItemsSource = new ObservableCollection<string> { "Item 1", "Item 2", "Item 3" };
}
```

### CODE REVIEW

File: src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs [hunk 1]
```diff
@@ -26,10 +27,16 @@ internal static void PropagatePropertyChanged(string propertyName, Element eleme
 			if (propertyName == null || propertyName == Shell.NavBarIsVisibleProperty.PropertyName)
 				BaseShellItem.PropagateFromParent(Shell.NavBarIsVisibleProperty, element);
 
-			foreach (var child in children)
+			var childList = children as IReadOnlyList<IVisualTreeElement>;
+			if (childList is not null)
```
[the remark this answers is not in the document]
Comment (jsuarezruiz) [reply src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:31]: Yes, can use pattern matching to combine the null check and type casting in a single step.

File: src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs [hunk 2]
```diff
@@ -26,10 +27,16 @@ internal static void PropagatePropertyChanged(string propertyName, Element eleme
...
 			{
-				if (child is IPropertyPropagationController view)
-					view.PropagatePropertyChanged(propertyName);
+				for (int i = 0; i < childList.Count; i++)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:33]: Also, can use the OfType method to filter and cast elements in a single step.

Something like:

```
if (children is IReadOnlyList<IVisualTreeElement> childList)
{
    foreach (var child in childList.OfType<IPropertyPropagationController>())
    {
        child.PropagatePropertyChanged(propertyName);
    }
}
```

**Review by jsuarezruiz — DISMISSED** [review]
Could we include a test using the sample from https://github.com/dotnet/maui/issues/28162?

File: src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (kubaflo) [reply src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:31]: Thanks!

File: src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs (hunk 2 above)
Comment (kubaflo) [reply src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:33]: I like it

Comment (kubaflo) [reply src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:33]: We need to add `.ToList()` though

childList.OfType<IPropertyPropagationController>()`.ToList()`

Comment (kubaflo) [reply src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs]: @MartyIX yea I think it will be better when it comes to perf right?

```c#
if (children is IReadOnlyList<IVisualTreeElement> childList)
			{
				for (int i = 0; i < childList.Count; i++)
				{
					if (childList[i] is IPropertyPropagationController view)
					{
						view.PropagatePropertyChanged(propertyName);
					}
				}
			}
```

Comment (kubaflo) [reply src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:33]: @PureWeen also told me to use the for loop, so let's stick with it

File: src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs [hunk 3]
```diff
@@ -26,10 +28,12 @@ internal static void PropagatePropertyChanged(string propertyName, Element eleme
 			if (propertyName == null || propertyName == Shell.NavBarIsVisibleProperty.PropertyName)
 				BaseShellItem.PropagateFromParent(Shell.NavBarIsVisibleProperty, element);
 
-			foreach (var child in children)
+			foreach (var child in children.ToList())
```
Comment (pictos) [inline src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:31]: I would say it's better to use `ToArray` if it's just readonly operation, since the compiler will do some optimizations for arrays.


```suggestion
			foreach (var child in children.ToArray())
```

Comment (kubaflo) [reply src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs]: Good idea!

**Review by PureWeen — APPROVED** [review]

**Comment by jdarwood007** [comment]
I am experiencing this issue as well.  I see this has been merged.  Which release should I expect to see this land in? I see the milestone, but I don't see information on what the milestone ties into releases I expect to see in visual studio.
