### PR TITLE
[Android] Fix crash using SearchHandler on Shell 

### LINKED ISSUE #2923: [Bug][Android] SearchHandlerAppearanceTracker throws a Null Reference exception
### Description
The shell SearchHandlerAppearanceTracker will throw a null reference exception in its constructor at `DefaultTextColors = _editText.TextColors;`. The issue is that the ShellSearchView uses AppCompatAutoCompleteTextView which inherits from AutoCompleteTextView which inherits from EditText and not AppCompatEditText, causing `GetChildrenOfType<AppCompatEditText>()` to fail.

### Steps to Reproduce
1. Add ```<Shell.SearchHandler>
    <SearchHandler />
</Shell.SearchHandler>``` to any page while using Shell.
### Expected Behavior
Show a shell SearchBar on the page.
### Actual Behavior
Crash from null reference exception.
### Basic Information
- Version with issue:
- Last known good version:
- IDE: Visual Studio 2022 Preview 5.0
- Platform Target Frameworks:
  - Android: 11.0
- Affected Devices: Pixel 2 emulator with default values.

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Fix NRE crash using SearchHandler on Shell. 

ShellSearchView uses AppCompatAutoCompleteTextView which inherits from AutoCompleteTextView which inherits from EditText and not AppCompatEditText. Applied changes to use EditText in `SearchHandlerAppearanceTracker  `instead AppCompatEditText.

- fixes #2923 

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)

#### Does this PR touch anything that might affect accessibility?
- No

### CODE REVIEW

File: src/Controls/src/Core/Platform/Android/Shell/SearchHandlerAppearanceTracker.cs [hunk 1]
```diff
@@ -42,7 +33,7 @@ public SearchHandlerAppearanceTracker(IShellSearchView searchView, IShellContext
 			_control = searchView.View;
 			_searchHandler.PropertyChanged += SearchHandlerPropertyChanged;
 			_searchHandler.FocusChangeRequested += SearchHandlerFocusChangeRequested;
-			_editText = (_control as ViewGroup).GetChildrenOfType<AppCompatEditText>().FirstOrDefault();
+			_editText = (_control as ViewGroup).GetChildrenOfType<EditText>().FirstOrDefault();
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/Shell/SearchHandlerAppearanceTracker.cs:36]: THIS is the important change!

Comment (PureWeen) [reply src/Controls/src/Core/Platform/Android/Shell/SearchHandlerAppearanceTracker.cs:36]: can we leverage the extension methods we have for SearchView here as an alternative to setting things here?

https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Android/SearchViewExtensions.cs#L19

Comment (rmarinho) [reply src/Controls/src/Core/Platform/Android/Shell/SearchHandlerAppearanceTracker.cs:36]: not that easy, since it's not a ISearchBar and IView , but with a bigger refactor could be done in other PR

**Review by rmarinho — APPROVED** [review]
