### PR TITLE
[Testing] Add legacy CollectionView UITests

### LINKED ISSUE #19050: [UITEST] CollectionView Enable Legacy Tests
Below are all the (legacy) UI tests identified as being a part of the tests that cover `CollectionView` and have been disabled at this time. These should al be reenabled by checking if the test (still) fails and if yes, fix it one way or the other.

Note that there might be more tests associated to this area that haven't been properly identified yet. Feel free to also include those and please add them here.

**iOS**

- [x] CollectionViewBindingErrorsShouldBeZero (src\Compatibility\ControlGallery\src\Issues.Shared\CollectionViewBindingErrors.xaml.cs)
- [x] ItemsFromViewModelShouldBeSelected (src\Compatibility\ControlGallery\src\Issues.Shared\CollectionViewBoundMultiSelection.cs)
- [x] CollectionViewItemsSourceTypesDisplayAndDontCrash (src\Compatibility\ControlGallery\src\Issues.Shared\CollectionViewItemsSourceTypes.cs)
- [x] KeepScrollOffset (src\Compatibility\ControlGallery\src\Issues.Shared\CollectionViewItemsUpdatingScrollMode.cs)
- [x] KeepLastItemInView(src\Compatibility\ControlGallery\src\Issues.Shared\CollectionViewItemsUpdatingScrollMode.cs)
- [ ] CollectionViewItemsLayoutUpdate (src\Compatibility\ControlGallery\src\Issues.Shared\Issue5354.xaml.cs)
- [x] ClearingGroupedCollectionViewShouldNotCrash (src\Compatibility\ControlGallery\src\Issues.Shared\Issue8899.cs)
- [x] EmptyViewShouldNotCrash (src\Compatibility\ControlGallery\src\Issues.Shared\Issue9196.xaml.cs)
- [x] InitiallyInvisbleCollectionViewSurvivesiOSLayoutNonsense(src\Compatibility\ControlGallery\src\Issues.Shared\Issue12714.cs)
- [x] CollectionViewShouldSourceShouldResetWhileInvisible (src\Compatibility\ControlGallery\src\Issues.Shared\Issue13126_2.cs)
- [x] CollectionViewShouldSourceShouldUpdateWhileInvisible (src\Compatibility\ControlGallery\src\Issues.Shared\Issue13126.cs)
- [x] CollectionShouldInvalidateOnVisibilityChange (src\Compatibility\ControlGallery\src\Issues.Shared\Issue13203.cs)
- [x] VisitAndUpdateItemsSource (src\Compatibility\ControlGallery\src\UITests.Shared\Tests\CollectionViewUITests.cs)

**Android**

- [x] SelectionShouldUpdateBinding (src\Compatibility\ControlGallery\src\Issues.Shared\CollectionViewBoundSingleSelection.cs)
- [ ] CollectionViewInfiniteScroll (src\Compatibility\ControlGallery\src\Issues.Shared\Github5623.xaml.cs)
- [x] AddingItemToUnviewedCollectionViewShouldNotCrash (src\Compatibility\ControlGallery\src\Issues.Shared\Issue7700.cs)
- [x] AddingGroupToUnviewedGroupedCollectionViewShouldNotCrash (src\Compatibility\ControlGallery\src\Issues.Shared\Issue7700.cs)

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Add legacy CollectionView UITests.

image

Fixes https://github.com/dotnet/maui/issues/19050

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
The failing Windows Device Test seems unrelated with the changes in this PR (UI Tests): 
image

File: src/Core/src/Attributes/PortTestAttribute.cs [hunk 1]
```diff
@@ -0,0 +1,21 @@
+﻿#nullable enable
+using System;
+
+namespace Microsoft.Maui
+{
+	[AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
+	public class PortTestAttribute : Attribute
```
Comment (PureWeen) [inline src/Core/src/Attributes/PortTestAttribute.cs:7]: Can we use the `MovedToAppium` attribute? That one also inherits from Ignore which is useful because we don't want to run this in the compatibility runner anymore

**Review by PureWeen — CHANGES_REQUESTED** [review]

**Comment by jsuarezruiz** [comment]
Waiting macOS tests, should be green soon.
image

File: src/Controls/tests/UITests/Controls.AppiumTests.csproj [hunk 2]
```diff
@@ -21,6 +21,22 @@
     <DefineConstants Condition=" '$(ExtraDefineConstants)' != '' ">$(DefineConstants);$(ExtraDefineConstants)</DefineConstants>
   </PropertyGroup>
 
+  <PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
+    <DefineConstants>$(DefineConstants);ANDROID</DefineConstants>
+  </PropertyGroup>
```
Comment (mattleibow) [inline src/Controls/tests/UITests/Controls.AppiumTests.csproj:26]: Let's wait for the split appium tests to merge this one

**Review by mattleibow — DISMISSED** [review]

**Review by PureWeen — APPROVED** [review]
