### PR TITLE
[Android] Correctly clear text tapping the clear button on Entry

### LINKED ISSUE #17453: [regression/7.0.0] Entry clear button doesn't work under Android 13 + NET 7.0
### Description

Entry clear button doesn't work in .NET 7.0 again. If change project type to .NET 6 clear button works as expected.

The same code works as expected under iOS 16.4.

Previous issue is: https://github.com/dotnet/maui/issues/9954

Screenshot_1695042972

### Steps to Reproduce

1. Create new default MAUI project
2. Paste code `<Entry Text="Simple text" ClearButtonVisibility="WhileEditing"  />` in MainPage.xaml
3. Launch project
4. Click entry and click clear button

Expected result:
Text is cleared in the entry

Actual result:
Text in the entry remains unchanged

### Link to public reproduction project repository

https://github.com/alexsmi-noveo/ClearButtonIssue

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #18803: [Android] Entry clear button requires tap to the right of appearance
### Description

When an Entry has a parent with left padding, clicking the entry clear button does not work.  The button needs to be clicked to the right of its appearance.  This is only happening on Android.

### Steps to Reproduce

The following will reproduce the problem:

```
  <Border HeightRequest="45"
          Padding="15,0,0,0">
    <Entry ClearButtonVisibility="WhileEditing" />
  </Border>
```

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Correctly clear text tapping the clear button on Android Entry.
fix-17453

### Issues Fixed

Fixes #17453 
Fixes #18803

### CODE REVIEW

File: src/Core/src/Platform/Android/EditTextExtensions.cs [hunk 1]
```diff
@@ -362,7 +363,7 @@ internal static bool HandleClearButtonTouched(this EditText? platformView, Touch
 			if (buttonWidth <= 0)
 				return false;
 
-			var x = motionEvent.GetX();
+			var x = motionEvent.RawX;
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/EditTextExtensions.cs:366]: This is the main change.

Comment (hartez) [reply src/Core/src/Platform/Android/EditTextExtensions.cs:366]: Gonna need an explanation of how this doesn't regress to the problem from #9954, then.

**Review by hartez — CHANGES_REQUESTED** [review]
This needs to verify that it doesn't regress to #9954.

**Comment by samhouts** [comment]
Need to target main

File: src/Core/src/Platform/Android/EditTextExtensions.cs (hunk 1 above)
Comment (hartez) [reply src/Core/src/Platform/Android/EditTextExtensions.cs:357]: That commit was made for a reason; `RawX` is the wrong property to use here. Changing it back will re-break #9954. 

Here's a change that will fix both: https://github.com/dotnet/maui/tree/fix-17453-2
Grab those changes and turn the sandbox page into a UI test.

**Review by hartez — CHANGES_REQUESTED** [review]
This fix will regress an earlier issue.

**Review by hartez — APPROVED** [review]
