### PR TITLE
Fixed ScrollView Orientation Neither issue

### LINKED ISSUE #18418: [Android] ScrollView Orientation=Neither not working
### Description

Setting `ScrollView` Orientation option to `Neither` seems not to have effect on Android.

### Steps to Reproduce

1. Set this as the content of a `ContentPage`

```xaml
<ScrollView
    Orientation="Neither">
    <ContentView
        HeightRequest="2000">
        <Label
            Text="Hello world!"
            VerticalTextAlignment="End" />
    </ContentView>
</ScrollView>
```

Expected result: I shouldn't be able to scroll and see the Hello World label.
Actual result: I can scroll until I see the Hello World label.

### Link to public reproduction project repository

https://github.com/Riccardo11/MauiIssues/tree/main/ScrollViewOrientationNeither

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13. Didn't test other Android versions.

### Did you find any workaround?

Setting `IsEnabled` attribute to false seems to do something similar to the expected behavior.

```xaml
<ScrollView IsEnabled="False">
```

### Relevant log output

_No response_

### LINKED ISSUE #27140: ScrollView Remains Scrollable Despite ScrollOrientation.Neither Setting on Windows Platform
### Description

The ScrollView control in the Issue2680ScrollView implementation exhibits inconsistent behavior specifically on the Windows platform. When the application initializes, the ScrollView is designed to start in a non-scrollable state (ScrollOrientation.Neither) and should only become scrollable when a toggle button is clicked. However, on Windows ,The ScrollView begins in a scrollable state despite being explicitly set to ScrollOrientation.Neither.
Note: While fixing this issue enable the test case from HostApp: Issue2680ScrollView.
<video src="https://github.com/user-attachments/assets/754dbb19-0bc3-4c48-b6f1-07266c50de37" />

### Steps to Reproduce

- [Issue2680.zip](https://github.com/user-attachments/files/18423209/Issue2680.zip)
- Run the application on Windows
- Note that content is scrollable despite initial ScrollOrientation.Neither setting

**Expected Behavior**
- Initial state: ScrollView should not be scrollable (Orientation = ScrollOrientation.Neither)
- After button click: ScrollView should become scrollable (Orientation = ScrollOrientation.Vertical)

**Actual Behavior**
- Initial state: ScrollView is vertically scrollable on Windows

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.30 SR3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Vignesh-SF3580**
### Issue Detail
Scrolling remains enabled in a ScrollView, even when Orientation is Neither.

### Root Cause
The implementation does not correctly disable scrolling or adjust scrollbar visibility when ScrollOrientation is set to Neither.

### Description of Change
Added logic to disable both horizontal and vertical scrolling, when ScrollOrientation is set to Neither.

### Tested the behavior in the following platforms
 
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Issues Fixed
 
Fixes https://github.com/dotnet/maui/issues/18418
Fixes https://github.com/dotnet/maui/issues/27140

### Screenshots

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="300" height="600"  src="https://github.com/user-attachments/assets/65377d03-5987-4275-9a70-4facbace4ac5"> | <video width="300" height="600"  src="https://github.com/user-attachments/assets/6a03e135-2cc5-4cf4-9a65-90e48dcc94d5">) |

### CODE REVIEW

File: src/Core/src/Platform/Windows/ScrollViewerExtensions.cs [hunk 1]
```diff
@@ -17,37 +17,46 @@ public static WScrollBarVisibility ToWindowsScrollBarVisibility(this ScrollBarVi
 		}
 
 		public static void UpdateScrollBarVisibility(this ScrollViewer scrollViewer, ScrollOrientation orientation,
-			ScrollBarVisibility horizontalScrollBarVisibility)
+			ScrollBarVisibility scrollBarVisibility)
```
Comment (jfversluis) [inline src/Core/src/Platform/Windows/ScrollViewerExtensions.cs:20]:
```suggestion
			ScrollBarVisibility horizontalScrollBarVisibility)
```

File: src/Core/src/PublicAPI/net-windows/PublicAPI.Shipped.txt [hunk 2]
```diff
@@ -2838,7 +2838,7 @@ static Microsoft.Maui.Platform.RadioButtonExtensions.UpdateStrokeThickness(this
 static Microsoft.Maui.Platform.RadioButtonExtensions.UpdateTextColor(this Microsoft.UI.Xaml.Controls.RadioButton! platformRadioButton, Microsoft.Maui.ITextStyle! button) -> void
 static Microsoft.Maui.Platform.ScrollViewerExtensions.ToWindowsScrollBarVisibility(this Microsoft.Maui.ScrollBarVisibility visibility) -> Microsoft.UI.Xaml.Controls.ScrollBarVisibility
 static Microsoft.Maui.Platform.ScrollViewerExtensions.UpdateContent(this Microsoft.UI.Xaml.Controls.ScrollViewer! scrollViewer, Microsoft.Maui.IView? content, Microsoft.Maui.IMauiContext! context) -> void
-static Microsoft.Maui.Platform.ScrollViewerExtensions.UpdateScrollBarVisibility(this Microsoft.UI.Xaml.Controls.ScrollViewer! scrollViewer, Microsoft.Maui.ScrollOrientation orientation, Microsoft.Maui.ScrollBarVisibility horizontalScrollBarVisibility) -> void
+static Microsoft.Maui.Platform.ScrollViewerExtensions.UpdateScrollBarVisibility(this Microsoft.UI.Xaml.Controls.ScrollViewer! scrollViewer, Microsoft.Maui.ScrollOrientation orientation, Microsoft.Maui.ScrollBarVisibility scrollBarVisibility) -> void
```
Comment (jfversluis) [inline src/Core/src/PublicAPI/net-windows/PublicAPI.Shipped.txt:2841]:
```suggestion
static Microsoft.Maui.Platform.ScrollViewerExtensions.UpdateScrollBarVisibility(this Microsoft.UI.Xaml.Controls.ScrollViewer! scrollViewer, Microsoft.Maui.ScrollOrientation orientation, Microsoft.Maui.ScrollBarVisibility horizontalScrollBarVisibility) -> void
```

**Review by jfversluis — COMMENTED** [review]
I think technically not _really_ a breaking change, but lets not risk it

File: src/Core/src/Platform/Windows/ScrollViewerExtensions.cs [hunk 3]
```diff
@@ -19,35 +19,44 @@ public static WScrollBarVisibility ToWindowsScrollBarVisibility(this ScrollBarVi
...
+				{
+					ScrollOrientation.Horizontal or ScrollOrientation.Both => scrollBarVisibility.ToWindowsScrollBarVisibility(),
+					_ => WScrollBarVisibility.Disabled,
+				};
 
-			// Note that the Orientation setting of "Neither" is covered by the measurement code (the size of the content is limited
-			// so that no scrolling is possible) and the xplat scrolling code (the ScrollTo methods are disabled when Orientation=Neither)
+				scrollViewer.VerticalScrollBarVisibility = orientation switch
+				{
+					ScrollOrientation.Vertical or ScrollOrientation.Both => scrollBarVisibility.ToWindowsScrollBarVisibility(),
```
Comment (jfversluis) [inline src/Core/src/Platform/Windows/ScrollViewerExtensions.cs:56]:
```suggestion
					ScrollOrientation.Vertical or ScrollOrientation.Both => horizontalScrollBarVisibility.ToWindowsScrollBarVisibility(),
```

File: src/Core/src/Platform/Windows/ScrollViewerExtensions.cs [hunk 4]
```diff
@@ -19,35 +19,44 @@ public static WScrollBarVisibility ToWindowsScrollBarVisibility(this ScrollBarVi
...
-			};
-
-			// TODO ezhart 2021-07-08 RE: the note below - do we actually need to be accounting for Neither in the measurement code?
-			// Could we just disable the scroll bars entirely?
-			// Accounting for Neither in the xplat measurement code is a leftover from Forms, it may be easier to do that on the native side here.
+				// If the user _has_ set a horizontal scroll bar visibility preference, then convert that preference to the native equivalent
+				// if the orientation allows for it
+				scrollViewer.HorizontalScrollBarVisibility = orientation switch
+				{
+					ScrollOrientation.Horizontal or ScrollOrientation.Both => scrollBarVisibility.ToWindowsScrollBarVisibility(),
```
Comment (jfversluis) [inline src/Core/src/Platform/Windows/ScrollViewerExtensions.cs:50]:
```suggestion
					ScrollOrientation.Horizontal or ScrollOrientation.Both => horizontalScrollBarVisibility.ToWindowsScrollBarVisibility(),
```

File: src/Core/src/Platform/Windows/ScrollViewerExtensions.cs [hunk 5]
```diff
@@ -19,35 +19,44 @@ public static WScrollBarVisibility ToWindowsScrollBarVisibility(this ScrollBarVi
...
 			ScrollBarVisibility horizontalScrollBarVisibility)
 		{
-			if (horizontalScrollBarVisibility == ScrollBarVisibility.Default)
+			if (orientation == ScrollOrientation.Neither)
+			{
+				scrollViewer.HorizontalScrollBarVisibility = scrollViewer.VerticalScrollBarVisibility = WScrollBarVisibility.Disabled;
+				return;
+			}
+
+			if (scrollBarVisibility == ScrollBarVisibility.Default)
```
Comment (jfversluis) [inline src/Core/src/Platform/Windows/ScrollViewerExtensions.cs:28]:
```suggestion
			if (horizontalScrollBarVisibility == ScrollBarVisibility.Default)
```

**Review by jfversluis — COMMENTED** [review]
Oops, need to rename the references to this too of course

**Review by rmarinho — APPROVED** [review]
