### PR TITLE
Remove validation exceptions Slider min/max values

### LINKED ISSUE #6305: Slider Minimum crashes the app
### Description

Setting the minimum value of Slider crashes the app

### Steps to Reproduce

1. Create new MAUI app.
2. Add slider to the Main page
```xml
<Slider Minimum="1" Maximum="20" Value="{Binding Value}" />
```
3. Start app.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

19041

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change

This PR removes the validation of the `Slider.Minimum` and `Slider.Maximum`. Effectively this means we remove the requirement to specify `Minimum` and `Maximum` in a certain order in XAML. Users are now responsible for setting the right values. If that doesn't happen (e.g. `Minimum` is bigger than `Maximum`) weird behavior might occur (which will be the platforms behavior), but the app will not crash.

I left the exception for the constructor in place as this is still some kind of safeguard and doesn't stand in the way of what we're trying to fix here.

### Issues Fixed

Fixes #6305

### CODE REVIEW

File: src/Controls/src/Core/Slider.cs [hunk 1]
```diff
@@ -9,31 +8,23 @@ namespace Microsoft.Maui.Controls
 	public partial class Slider : View, ISliderController, IElementConfiguration<Slider>
 	{
 		/// <include file="../../docs/Microsoft.Maui.Controls/Slider.xml" path="//Member[@MemberName='MinimumProperty']/Docs" />
-		public static readonly BindableProperty MinimumProperty = BindableProperty.Create("Minimum", typeof(double), typeof(Slider), 0d, validateValue: (bindable, value) =>
-		{
-			var slider = (Slider)bindable;
-			return (double)value < slider.Maximum;
-		}, coerceValue: (bindable, value) =>
+		public static readonly BindableProperty MinimumProperty = BindableProperty.Create(nameof(Minimum), typeof(double), typeof(Slider), 0d, coerceValue: (bindable, value) =>
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Slider.cs:11]: If we remove the validations here, sould we include in the handlers a check for nonsensical states when any of the properties are updated? (avoid errors,  settings zeros etc)

Comment (jfversluis) [reply src/Controls/src/Core/Slider.cs:11]: I think the only scenario that gets you in trouble right now is when you set the `Minimum` to more than the `Maximum`. From what I tested the thumb will just get stuck. And that is just the default behavior then for that platform. So if I was a iOS or Android developer and I were to do that, I would end up with the same thing. Should we then get in the middle and do something else?

The problem is then, again, the order of things. If we are going to make checks like: minimum is more than maximum and them we make minimum equal to maximum and your setting one before the other, you again end up with behavior you might not want and that is dependant on the order of declaration.

File: src/Controls/tests/Core.UnitTests/SliderUnitTests.cs [hunk 2]
```diff
@@ -59,14 +59,14 @@ public void TestMaxValueClamp()
 		public void TestInvalidMaxValue()
 		{
 			var slider = new Slider();
-			Assert.Throws<ArgumentException>(() => slider.Maximum = slider.Minimum - 1);
+			Assert.DoesNotThrow(() => slider.Maximum = slider.Minimum - 1);
```
[the remark this answers is not in the document]
Comment (jfversluis) [reply src/Controls/tests/Core.UnitTests/SliderUnitTests.cs:62]: Yeah I guess I could add some more tests also for negatives and such

File: src/Controls/src/Core/Slider.cs (hunk 1 above)
Comment (hartez) [reply src/Controls/src/Core/Slider.cs:11]: Can we just have the mapping method set the platform min/max/value to zero if the values aren't valid? Then all the platforms do something consistent when the values don't make sense, and the order doesn't matter.

Comment (Redth) [reply src/Controls/src/Core/Slider.cs:11]: I'm inclined not to do this, as the way the handlers are structured, if we want to update everything to 0 when one change is invalid, we may cause the UI to 'skip/jump' by changing the values temporarily until the next property change happens and brings in a set of 'valid' values again.

I think what this branch has now is probably reasonable enough.  It doesn't seem to crash any of the platforms so far (still have iOS to validate).

**Review by Redth — APPROVED** [review]

File: src/Core/src/Platform/iOS/SliderExtensions.cs [hunk 3]
```diff
@@ -33,7 +33,7 @@ public static void UpdateMaximumTrackColor(this UISlider uiSlider, ISlider slide
 			if (slider.MaximumTrackColor != null)
 			{
 				if (uiSlider.TraitCollection.UserInterfaceIdiom != UIUserInterfaceIdiom.Mac)
-					uiSlider.MaximumTrackTintColor = slider.MinimumTrackColor.ToPlatform();
+					uiSlider.MaximumTrackTintColor = slider.MaximumTrackColor.ToPlatform();
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/SliderExtensions.cs:36]: Nice!

**Review by jsuarezruiz — APPROVED** [review]
