### PR TITLE
[android] fix memory leak with `CarouselView`

### LINKED ISSUE #17726: Memory leak with CarouselView
### Description

On android with `net8-rc.1`, when navigating to a page containing a `CarouselView` and then back, the memory usage grows.
For comparison, no memory leak when navigating to a page containing a `CollectionView` with the same `ItemsSource` and `ItemTemplate`.

### Steps to Reproduce

1. Open repro project
2. On the first tab, tap on `Go` button, it will navigate to a page with a `CollectionView`.
3. Go back to the main page. Repeat a few times. Observe memory usage with dotnet-gcdump. It is stable.
4. On the second tab, tap on `Go` button, it will navigate to a page with a `CarouselView`.
5. Go back to the main page. Repeat a few times. Observe memory usage with dotnet-gcdump. It is slowly increasing.
6. Alternatively, open the attached gcdump files I've captured when showing the `CarouselView` page a few times. Between the first (memory-20.gcdump) and second (memory-24.gcdump), the memory usage increases quite a lot (the page is really simple).

[gcdump.zip](https://github.com/dotnet/maui/files/12753203/gcdump.zip)

Screenshot 2023-09-28 172824

### Link to public reproduction project repository

https://github.com/tranb3r/Issues/tree/main/MauiAppCarouselViewLeak

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 34

### Did you find any workaround?

No workaround

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Fixes: https://github.com/dotnet/maui/issues/17726
Related: https://github.com/dotnet/maui/issues/18365

Adding `CarouselView` to a page and navigating away from it keeps the page alive forever on Android. I was able to reproduce this in a test.

It took me a while to actually track this one down, but the problem boils down to `MauiCarouselRecyclerView` doing:

    _carouselViewLayoutListener = new CarouselViewwOnGlobalLayoutListener();
    _carouselViewLayoutListener.LayoutReady += LayoutReady;
    ViewTreeObserver.AddOnGlobalLayoutListener(_carouselViewLayoutListener);

The `ViewTreeObserver` lives longer than the page, and so:

* `ViewTreeObserver` -> `CarouselViewwOnGlobalLayoutListener`
* `event LayoutReady` -> `MauiCarouselRecyclerView`
* `MauiCarouselRecyclerView` -> `CarouselView`
* `CarouselView` -> `Parent.Parent.Parent.*` -> `Page`

Thus the `Page` lives forever.

If we remove the `LayoutReady` event, instead:

* `CarouselViewwOnGlobalLayoutListener` saves `MauiCarouselRecyclerView` in a weak reference.

* It can just call `LayoutReady()` directly.

* `MauiCarouselRecyclerView` is able to be GC'd now.

* `MauiCarouselRecyclerView.Dispose()` already appropriately will call `ClearLayoutListener()`

* Lastly, `ViewTreeObserver?.RemoveOnGlobalLayoutListener(_carouselViewLayoutListener)`

With these changes, the test passes and I don't think anything will leak now. :)

Other changes:

* I fixed the typo in `CarouselViewwOnGlobalLayoutListener`.
* I sorted the type names in the test alphabetically.

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs [hunk 1]
```diff
@@ -594,14 +591,23 @@ protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
 
 			base.OnMeasure(widthMeasureSpec, heightMeasureSpec);
 		}
-	}
 
-	class CarouselViewwOnGlobalLayoutListener : Java.Lang.Object, ViewTreeObserver.IOnGlobalLayoutListener
-	{
-		public EventHandler<EventArgs> LayoutReady;
-		public void OnGlobalLayout()
+		class CarouselViewOnGlobalLayoutListener : Java.Lang.Object, ViewTreeObserver.IOnGlobalLayoutListener
```
Comment (jonathanpeppers) [inline src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs:595]: I made this a nested private class, so it could access the `LayoutReady` private method.

**Review by rmarinho — APPROVED** [review]
