### PR TITLE
[Windows] Fixed Shell flyout menu's current page indicator doesn't update when using routes

### LINKED ISSUE #32219: The Shell flyout menu's current page indicator doesn't update when using routes (//) that clear the navigation stack
### Description

The Shell flyout menu's current page indicator doesn't update when using routes that start with `//` prefix, that clear the navigation stack.

In the sample solution, **Logout** is a menu item that navigates to the Login page. Clicking the **Login** button then redirects to the Events page via the **//home** route, effectively clearing the navigation stack.

Once back to the Home page, open the flyout menu, the current page indicator still points to the Logout menu item.

Now update the MAUI NuGet package to `9.0.111`, the earlier version, it works fine.

### Steps to Reproduce

1. Clone the sample solution
2. Set Windows as the target platform
3. Run the application
4. Open the Shell flyout menu
5. Note the current page indicator
6. Click on the Logout menu item (redirects to the Login page)
7. Now click on the Login action button (redirects to the Calendar page)
8. Again, open the Shell flyout menu
9. Now check the current page indicator, which is incorrect
10. Update the MAUI NuGet package to the **9.0.111**, the earlier version (Refer to **Directory.Packages.props** file in the root)
11. Restore, build, run, and repeat the above steps

### Link to public reproduction project repository

https://github.com/egvijayanand/maui-issue-32219

### Version with bug

9.0.120 SR12

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.111 SR11.1

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Tamilarasan-Paranthaman**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause of the Issue

- A System.ArgumentException occurred when changing the FlyoutLayoutBehavior at runtime. This issue was caused by a workaround that had been added earlier to handle another WinUI issue. Since the latest WinUI version has already resolved that underlying problem, the workaround was no longer necessary and was therefore removed in the regression PR https://github.com/dotnet/maui/pull/31491.

- This change resolved the System.ArgumentException that occurred when changing the FlyoutLayoutBehavior at runtime.

- However, after this update, a new issue appeared where the selection was not properly updated in the Flyout items.

- It seems to be a WinUI issue that occurs when setting the same PaneDisplayMode at runtime while navigating through a button click and updating both the PaneDisplayMode and the selected item simultaneously.

- Maybe related to https://github.com/microsoft/microsoft-ui-xaml/issues/9812

### Description of Change

- Updated the logic to modify the PaneDisplayMode only when the new value differs from the current one. This change resolves both the newly reported issue and the one addressed in the regression PR.

### Regression PR

- https://github.com/dotnet/maui/pull/31491

### Issues Fixed

Fixes #32219

### Tested the behaviour in the following platforms

- [x] Windows
- [x] iOS
- [x] Android
- [x] Mac

### Screenshot

| Before Fix | After Fix |
|----------|----------|
| <video  src="https://github.com/user-attachments/assets/6dbba4d6-f72a-4d60-a67b-6030d2b5f4c6"> | <video  src="https://github.com/user-attachments/assets/77d1be66-d36e-4b82-aeb2-882be5ce3656"> |

### CODE REVIEW

File: src/Core/src/Platform/Windows/MauiNavigationView.cs [hunk 1]
```diff
@@ -180,7 +180,12 @@ internal void UpdatePaneDisplayModeFromFlyoutBehavior(FlyoutBehavior flyoutBehav
 			{
 				case FlyoutBehavior.Flyout:
 					IsPaneToggleButtonVisible = true;
-					PaneDisplayMode = NavigationViewPaneDisplayMode.LeftMinimal;
+					// Updating the same PaneDisplayMode at the runtime causes selection related issues
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Windows/MauiNavigationView.cs]: Could expand the comment to include more details, like the link to the original issue?

```
// WinUI bug: Setting PaneDisplayMode to the same value during navigation
// causes the selected item indicator to not update correctly.
// Workaround: Only set PaneDisplayMode when the value actually changes.
// Related: https://github.com/microsoft/microsoft-ui-xaml/issues/9812
```

Comment (Tamilarasan-Paranthaman) [reply src/Core/src/Platform/Windows/MauiNavigationView.cs]: yes, I have updated it.

**Review by PureWeen — APPROVED** [review]
