### PR TITLE
Avoid recomputing bindings multiple times and bind BindingContext first

### LINKED ISSUE #10806: Bindings are executed twice
### Description

It appears that XAML bindings are being executed twice in certain circumstances. I've got several different situations in my MAUI application where this appears to be happening. At the moment I can only reproduce the following in a greatly simplified situation.

If I place a binding at the top of a Page definition, all the bindings on that page will we executed 2 times. 
It also appears that any IValueConverter attached to the binding is executed AFTER the lower bindings are applied the 1st time.

Thus if we have the following code:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:converters="clr-namespace:MauiBugz.Converters"
             xmlns:views="clr-namespace:MauiBugz.Views"
             BindingContext="{Binding Property, Mode=OneTime, Converter={x:Static converters:CountingConverter.Instance}, ConverterParameter='TopOfPage'}"
             x:Class="MauiBugz.Views.IssueView"
             Title="IssueView">

    <VerticalStackLayout>

        <ContentView
            BindingContext="{Binding Property, Mode=OneTime, Converter={x:Static converters:CountingConverter.Instance}, ConverterParameter='OneLevelDown'}"/>

        <ContentView
            BindingContext="{Binding Property, Mode=OneTime, Converter={x:Static converters:CountingConverter.Instance}, ConverterParameter='CustomContent'}"/>

    </VerticalStackLayout>
    
</ContentPage>
```
We will see the following progression:

```
[DOTNET] IssueViewModel Get Property
[DOTNET] OneLevelDown converter has been executed 1 times. Value: Data_A
[DOTNET] IssueViewModel Get Property
[DOTNET] CustomContent converter has been executed 1 times. Value: Data_A
[DOTNET] IssueViewModel Get Property
[DOTNET] TopOfPage converter has been executed 1 times. Value: Data_A          <<<<<<<<<<<<<< 
[DOTNET] ConvertedData_A Get Property
[DOTNET] OneLevelDown converter has been executed 2 times. Value: Data_B
[DOTNET] ConvertedData_A Get Property
[DOTNET] CustomContent converter has been executed 2 times. Value: Data_B
```
Note that `TopOfPage converter` is executed after all the lower bindings have been presented with the VM applied to the page.  They were never to see the VM, they were to receive `ConvertedData` objects that were derived from the `Data` object returned from the `VM.Property` getter. (As you see in the 2nd half of the console output.)

### Steps to Reproduce

1. Clone the Repro
2. Select the button for the Issue
3. View the Console output.

NOTE: This issue is a bit tedious to illustrate via output as Bindings are relatively verbose processes with several steps. I've implemented the following in an attempt to help track the issue via console output.

`CountingConverter` is an `IValueConverter` implementation with the following:
- Static `Instance` property that returns a unique/new converter for each access. (Each binding has it's own instance)
- `ConverterParameter` is expected to be a string "name" to uniquely identify each converter.
- Designed to count each time it's executed and prints it's name, the count, and the value and it's provided to the Console. 
- Takes a `Data` object in, and returns a `ConvertedData` object.

The initial ViewModel, `Data`, and `ConvertedData` all share the same `Property` property to simplify coding down the XAML tree. 
-  The getter creates a new `Data` object on first access.

`Data` and `ConvertedData` get a new designation character when they are created to make each unique.

### Link to public reproduction project repository

https://github.com/bakerhillpins/Issues/tree/NetMauiIssue10806

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

It appears that if you insert ContentView between your actual XAML and the Page (effectively wrapping your view) and move the TopOfPage binding down to that wrapper ContentView, the bindings are only executed once. 

The Caveat here is that I'm actually using this workaround in my larger application, however, I'm still seeing the issue and have not been able to determine why at the moment.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by albyrock87**
### Description of Change

The two unit tests shows the expectation we all have about bindings:
- eventual `BindingContext` binding should apply before any property binding
- `Binding` should happen only once upon binding context inheritance

#### Before

| Method                                          | Mean     | Error   | StdDev  | Gen0     | Gen1    | Gen2    | Allocated |
|------------------------------------------------ |---------:|--------:|--------:|---------:|--------:|--------:|----------:|
| SetProperty                                     | 892.2 us | 7.64 us | 6.77 us |        - |       - |       - |     873 B |
| ApplyProperty ViaBindingContextInheritance       | 379.7 us | 3.94 us | 3.49 us |  76.6602 | 38.0859 |  3.9063 |  644003 B |
| ApplyBindingContext ViaBindingContextInheritance | 775.7 us | 8.05 us | 7.13 us | 109.3750 | 54.6875 | 11.7188 |  919289 B |

#### After

| Method                                          | Mean     | Error   | StdDev  | Gen0    | Gen1    | Allocated |
|------------------------------------------------ |---------:|--------:|--------:|--------:|--------:|----------:|
| SetProperty                                     | 868.0 us | 1.00 us | 0.83 us |       - |       - |     873 B |
| ApplyProperty ViaBindingContextInheritance       | 309.0 us | 0.54 us | 0.50 us | 72.7539 | 36.1328 |  612000 B |
| ApplyBindingContext ViaBindingContextInheritance | 497.6 us | 1.23 us | 1.15 us | 93.7500 | 46.8750 |  784881 B |

### Issues Fixed

Fixes #10806

### CODE REVIEW

File: src/Controls/src/Core/BindableObject.cs [hunk 1]
```diff
@@ -355,20 +355,33 @@ public static void SetInheritedBindingContext(BindableObject bindable, object va
...
-
-			bindable.ApplyBindings(skipBindingContext: false, fromBindingContextChanged: true);
-			bindable.OnBindingContextChanged();
 		}
 
 		/// <summary>
 		/// Applies all the current bindings to <see cref="BindingContext" />.
 		/// </summary>
-		protected void ApplyBindings() => ApplyBindings(skipBindingContext: false, fromBindingContextChanged: false);
+		protected void ApplyBindings()
```
Comment (albyrock87) [inline src/Controls/src/Core/BindableObject.cs:372]: This method appears unused, shall we `[Obsolete]` it?

**Review by StephaneDelcroix — CHANGES_REQUESTED** [review]
this looks good. and if it's green, well, go

**Review by StephaneDelcroix — APPROVED** [review]

**Comment by rmarinho** [comment]
@albyrock87  @StephaneDelcroix  this test seem to be failing when merging main to net9.0 https://dev.azure.com/xamarin/public/_build/results?buildId=123788&view=ms.vss-test-web.build-test-results-tab&runId=3145016&resultId=102857&paneView=debug

**Comment by albyrock87** [comment]
@rmarinho looking at your PR, I see a lot of changes in `BindableObject` are missing.
https://github.com/dotnet/maui/pull/24553/files#diff-ebb14ec14b8baeffdd7b0ae40ffc8bf0e8944f76fdea50fcbc737fb142bfb44a
Maybe a mistake solving merge conflicts?
