### PR TITLE
[iOS] Fix issues setting Shell TabBar appearance

### LINKED ISSUE #16551: Custom color for selected bottom tabbar in Shell not working.
### Description

Hey. I am setting within my Shell xaml object TabBarTitleColor to red.
It renders ok on Android, but fails on ios (refer to screenshot). Anyone encounter this? 
image

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

iOS portion of the following PR
https://github.com/dotnet/maui/pull/15447

#### Priority of how the colors are applied.

The APIs available to us are fairly limiting in scope. Ideally, we would make this all work through the VSM and just use two APIs (IconColor/TitleColor) but for now we are just making these APIs consistent between the platforms. 

The three properties users have to influence the `TabItem` coloring are: `TabBarUnselectedColor`, `TabBarTitleColor`, and `TabBarForegroundColor`

- If the user only sets `Shell.TabBarTitleColor` that will color the `Title` and `Icon` of the selected item. I realize this is a bit weird for TitleColor to change `Icon` color but this is currently how Android works and it's not really worth breaking this until we just introduce new APIs.
- If `Shell.TabBarTitleColor` is not set then the `TitleColor` will match the `TabBarForegroundColor`
- If `TabBarForegroundColor` is set and `TabBarUnselectedColor` isn't set then `TabBarForegroundColor` will be the color used for the text/icon of the selected TabItem
- If `TabBarUnselectedColor` is the only thing set then that will be used for the text/icon color on the unselected Tab Item. 

#### Examples
- `TabBarTitleColor`: Green
  - Selected Icon is Green, Selected Text is Green, Unselected item matches system colors
-  `TabBarForegroundColor`: Blue
  - Selected Icon is Blue, Selected Text is Blue, Unselected item matches system colors
-  `TabBarForegroundColor`: Blue, `TabBarTitleColor`: Green
  - Selected Icon is Blue, Selected Text is Green, Unselected item matches system colors
-  `Shell.ForegroundColor`: Blue, `TabBarTitleColor`: Green (ForegroundColor propagates to TabBarForegroundColor).
  - Selected Icon is Blue, Selected Text is Green, Unselected item matches system colors
-  `TabBarForegroundColor`: Blue, `TabBarTitleColor`: Green, `TabBarUnselectedColor`: Pink
  - Selected Icon is Blue, Selected Text is Green, Unselected text and Icon is `Pink`

#### Breaking changes
- Shell.ForegroundColor and Shell.TabBarForeGroundColor will now affect the android tab colors. If a user has `ForegroundColor` set, then the `tab` will match according to that color.
  

Fixes (partially) #6718
Fixes #16551

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/SafeShellTabBarAppearanceTracker.cs [hunk 1]
```diff
@@ -71,32 +71,48 @@ void UpdateiOS15TabBarAppearance(UITabBarController controller, ShellAppearance
...
 			var tabBar = controller.TabBar;
 
-			if (backgroundColor != null)
+			if (backgroundColor is not null && backgroundColor.IsNotDefault())
 				tabBar.BarTintColor = backgroundColor.ToPlatform();
-			if (titleColor.IsDefault != null)
-				tabBar.TintColor = titleColor.ToPlatform();
-			if (unselectedColor.IsDefault != null)
+
+			if (unselectedColor.IsDefault != null && unselectedColor.IsNotDefault())
```
Comment (jfversluis) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/SafeShellTabBarAppearanceTracker.cs:104]:
```suggestion
			if (unselectedColor.IsDefault is not null && unselectedColor.IsNotDefault())
```

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/SafeShellTabBarAppearanceTracker.cs [hunk 2]
```diff
@@ -71,32 +71,48 @@ void UpdateiOS15TabBarAppearance(UITabBarController controller, ShellAppearance
...
+			{
 				tabBar.UnselectedItemTintColor = unselectedColor.ToPlatform();
+				UITabBarItem.Appearance.SetTitleTextAttributes(new UIStringAttributes { ForegroundColor = unselectedColor.ToPlatform() }, UIControlState.Normal);
+			}
+
+			if (titleColor.IsDefault != null && titleColor.IsNotDefault() ||
+				foregroundColor.IsDefault != null && foregroundColor.IsNotDefault())
```
Comment (jfversluis) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/SafeShellTabBarAppearanceTracker.cs:111]:
```suggestion
			if (titleColor.IsDefault is not null && titleColor.IsNotDefault() ||
				foregroundColor.IsDefault is not null && foregroundColor.IsNotDefault())
```

**Review by jfversluis — DISMISSED** [review]
Agreed that there is some weirdness in how the API works, but love the detailed explanation. Something we need to fix down the road with improved/new APIs.

Already pinged @davidbritch to maybe make things a bit more clearer through documentation.

Added a couple of nits to be more consistent with the use of `!= null` vs `is not null`, otherwise I thinks looks good

**Review by jfversluis — APPROVED** [review]
