### PR TITLE
Disconnect property changes from all pages when TabbedPage set to null

### LINKED ISSUE #18457: Forgot to remove PropertyChanged in TabbedPageManager of Element`s InternalChildren, which caused NRE
### Description

Bug is Here :
https://github.com/dotnet/maui/blob/c745e23c755d1d04e1b4325dea16fce8b9a4a98d/src/Controls/src/Core/Platform/Android/TabbedPageManager.cs#L119

Element will be null and cause NRE

image
image

### Steps to Reproduce

1. Return the app to the background from the TabbedPage
2. Reopen the App
3. Respond to page changes

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by maonaoda**
### Issues Fixed

Fixes #18457

### CODE REVIEW

**Comment by maonaoda** [comment]
This issue prevents me from resetting the tab's icon, can it be merged soon?

File: src/Controls/src/Core/Platform/Android/TabbedPageManager.cs [hunk 1]
```diff
@@ -116,6 +116,7 @@ internal void SetElement(TabbedPage tabbedPage)
 
 			if (Element != null)
 			{
+				Element.InternalChildren.ForEach(page => TeardownPage(page as Page));
```
Comment (PureWeen) [inline src/Controls/src/Core/Platform/Android/TabbedPageManager.cs:119]: Is this needed because the same TabbedPage gets passed in twice?

Comment (maonaoda) [reply src/Controls/src/Core/Platform/Android/TabbedPageManager.cs:119]: When you return to the desktop through the system's return button and reopen it, the Element will be set to null through the DisconnectHandler, and then the Element will be reset again. Since the previous InternalChildren's Event has not been released, there is no doubt that the InternalChildren's event will be executed multiple times.

**Comment by PureWeen** [comment]
Makes sense

It'd be ideal to get a test together for this one
My thinking is that we can use device tests or appium to remove the TabbedPage and then add the same one back in. 


Let me know if you want to try a hand at adding testing.
We have a doc here that needs a little bit of updating
https://github.com/dotnet/maui/blob/main/docs/design/UITesting.md

Otherwise @jsuarezruiz @jfversluis can take a look.

**Review by PureWeen — APPROVED** [review]

**Review by emaf — APPROVED** [review]
