### PR TITLE
WinUI navigation view

### LINKED ISSUE #2435: [Bug] [WinUI] Navigation Page has no back button.
### Description
Using Maui `6.0.100-rc.2.1642`

https://user-images.githubusercontent.com/898335/132734718-4107aac4-a54e-4ad8-b4f0-ceac30d3742f.mp4

The back button is missing on Navigation Pages for WinUI. I have no way to go back to a previous page unless I do it myself programmatically.

### Steps to Reproduce

Create an app that uses a navigation page. On WinUI, there should be a back button in the title bar that will let you go back to a page. But it doesn't appear.

### LINKED ISSUE #2450: [Bug] [WinUI] NavigationBar does not disappear when HasNavigationBar set to false.
image

### Description

If you wrap a page in a NavigationPage, and try setting HasNavigationBar to false, the bar still appears when the app is run on WinUI. It does disappear on iOS and Android.

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change ###

- Convert to using `Frame` based stack navigation
  - Xamarin.Forms just swapped out the content of the root panel for navigation. Using `Frame` let's us plug into the more expected way to do navigation
- Set our root container to a `NavigationView`
  -  This is a little bit heavy for a single `Page` but it allows for us have things like AppBars without a NavigationPage. The tricky thing here is that the `NavigationHandler` itself isn't a `NavigationView` it's just a `Frame`. At any point if you insert a NavigationPage into your xplat hierarchy then we have to make the root view a `NavigationView` so that we get an `AppBar` and a `BackButton`. If this causes way too many issues for apps with no `NavigationPages` then we can look at optimizing.
  - With UWP we were using the BackButton inside the StatusBar but WinUI desktop has no status bar so we are instead going to use a `NavigationView` which is the recommended approach on `WinUI`

### Additions made ###
- Adds IWindow.BackButtonPressed. This is used by the global back button on windows, hardware button android, and nowhere on iOS but if someone wanted to they could call it on iOS
- WindowManager - This is the top level manager for a window on a MauiContext. Any child can get access to this to affect changes on the root appbar or other elements. (This may just move to the WindowHandler in the future)
- NavigationManager - This is used to handle navigation at each root where the user has added a NavigationPage. In a later PR we will have ScopedContext's with NavigationManagers (like we have on Android) which allows children to access the navigation manager seeing over it.

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

File: src/Controls/src/Core/Page.cs [hunk 1]
```diff
@@ -279,16 +279,17 @@ protected virtual bool OnBackButtonPressed()
 			if (RealParent is BaseShellItem || RealParent is Shell)
 				return false;
 
-			var application = RealParent as Window;
-			if (application == null || this == application.Page)
+
+			var window = RealParent as Window;
```
Comment (PureWeen) [inline src/Controls/src/Core/Page.cs:283]: Renamed for clarity. No behavior change

File: src/Controls/src/Core/Platform/Android/ImageSourceLoader.cs [hunk 2]
```diff
@@ -12,56 +12,10 @@ namespace Microsoft.Maui.Controls.Platform
 {
 	class ImageSourceLoader : IImageSourcePart
 	{
-		public IImageSource Source
```
Comment (PureWeen) [inline src/Controls/src/Core/Platform/Android/ImageSourceLoader.cs:15]: These all have just been moved into a shared class so all platforms can use this class

File: src/Controls/src/Core/Platform/ImageSourceLoader.cs [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+using NativeView = Android.Graphics.Drawable.Drawable;
+#elif WINDOWS
+using NativeView = Microsoft.UI.Xaml.Media.ImageSource;
+#elif NETSTANDARD || (NET6_0 && !IOS && !ANDROID)
+using NativeView = System.Object;
+#endif
+
+namespace Microsoft.Maui.Controls.Platform
+{
+	partial class ImageSourceLoader : IImageSourcePart
```
Comment (PureWeen) [inline src/Controls/src/Core/Platform/ImageSourceLoader.cs:16]: This is all just copied code so that other platforms can use it

File: src/Controls/src/Core/Handlers/NavigationPage/NavigationPageHandler.Windows.cs [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+				[Page.TitleProperty.PropertyName] = MapTitle,
+				[NavigationPage.CurrentPageProperty.PropertyName] = MapCurrentPage,
+				[NavigationPage.BarBackgroundColorProperty.PropertyName] = MapBarBackground,
+				[NavigationPage.BarBackgroundProperty.PropertyName] = MapBarBackground,
+				[PlatformConfiguration.WindowsSpecific.Page.ToolbarPlacementProperty.PropertyName] = MapToolbarPlacement,
+				[PlatformConfiguration.WindowsSpecific.Page.ToolbarDynamicOverflowEnabledProperty.PropertyName] = MapToolbarDynamicOverflowEnabled,
+			};
+
+		// TODO MAUI: break these out into extension methods
+		public static void MapBarBackground(NavigationPageHandler arg1, NavigationPage arg2)
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/NavigationPage/NavigationPageHandler.Windows.cs:29]: Can't we give better names here?

File: src/Controls/src/Core/Platform/ImageSourceLoader.cs [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+		{
+			IsLoading = isLoading;
+		}
+
+		public static Task<IImageSourceServiceResult<NativeView>> GetImageAsync(IImageSource imageSource, IMauiContext mauiContext)
+		{
+			if (imageSource == null)
+				return Task.FromResult<IImageSourceServiceResult<NativeView>>(new ImageSourceServiceResult(null));
+
+			var services = mauiContext.Services;
```
Comment (rmarinho) [inline src/Controls/src/Core/Platform/ImageSourceLoader.cs:43]: can we cache these calls?

File: src/Core/src/Handlers/NavigationPage/NavigationViewHandler.Windows.cs [hunk 6]
```diff
@@ -1,738 +1,46 @@
...
 using Microsoft.UI.Xaml;
+using Microsoft.UI.Xaml.Controls;
+using Microsoft.UI.Xaml.Media.Animation;
 
 namespace Microsoft.Maui.Handlers
 {
-	internal partial class NavigationViewHandler :
-		ViewHandler<INavigationView, FrameworkElement>
+	public partial class NavigationViewHandler :
+		ViewHandler<INavigationView, NavigationFrame>
```
Comment (rmarinho) [inline src/Core/src/Handlers/NavigationPage/NavigationViewHandler.Windows.cs:13]: Can't this be Frame ?

Comment (PureWeen) [reply src/Core/src/Handlers/NavigationPage/NavigationViewHandler.Windows.cs:13]: https://github.com/dotnet/maui/pull/2551/files#diff-0f779c9331c0bb59305c07a8c6ea0a02d6e0df8a46332931c5f3bb8739f3bf3cR7

File: src/Core/src/Platform/Windows/NavigationManager.cs [hunk 7]
```diff
@@ -0,0 +1,139 @@
...
+			=> _currentPage ?? throw new InvalidOperationException("CurrentPage cannot be null");
+		public NavigationFrame NavigationFrame =>
+			_navigationFrame ?? throw new InvalidOperationException("NavigationFrame Null");
+
+		public NavigationManager(IMauiContext mauiContext)
+		{
+			_mauiContext = mauiContext;
+		}
+
+		public virtual void Connect(IView navigationView, NavigationFrame navigationFrame)
```
Comment (rmarinho) [inline src/Core/src/Platform/Windows/NavigationManager.cs:31]: Don't we wan't a DIsconnect to unsubscribe `_navigationFrame.Navigated `

File: src/Core/src/Platform/Windows/NavigationManager.cs [hunk 8]
```diff
@@ -0,0 +1,139 @@
...
+				NavigationView?.NavigationFinished(NavigationStack);
+				return;
+			}
+
+
+			NavigationTransitionInfo? transition = null;
+
+			if (animated)
+			{
+				transition = new SlideNavigationTransitionInfo()
```
Comment (rmarinho) [inline src/Core/src/Platform/Windows/NavigationManager.cs:70]: Can we make this something like 

`public virtual NavigationTransitionInfo GetNavigationTransition()`

File: src/Core/src/Platform/Windows/WindowManager.cs [hunk 9]
```diff
@@ -0,0 +1,41 @@
+﻿using System;
+using System.Collections.Generic;
+using System.Text;
+using Microsoft.Maui.Graphics;
+using Microsoft.UI.Xaml;
+using Microsoft.UI.Xaml.Controls;
+
+namespace Microsoft.Maui
+{
+	public class WindowManager
```
Comment (rmarinho) [inline src/Core/src/Platform/Windows/WindowManager.cs:10]: Do we want this public already?

File: src/Core/src/Platform/Windows/WindowManager.cs [hunk 10]
```diff
@@ -0,0 +1,41 @@
...
+		}
+
+		void OnBackRequested(NavigationView sender, NavigationViewBackRequestedEventArgs args)
+		{
+			_window?.BackButtonPressed();
+		}
+
+		public FrameworkElement RootView => _navigationView;
+
+		public virtual void Connect(IWindow window)
```
Comment (rmarinho) [inline src/Core/src/Platform/Windows/WindowManager.cs:31]: Should this have a Disconnect ?

File: src/Controls/src/Core/Handlers/NavigationPage/NavigationPageHandler.Windows.cs (hunk 4 above)
Comment (PureWeen) [reply src/Controls/src/Core/Handlers/NavigationPage/NavigationPageHandler.Windows.cs]: 👍

File: src/Controls/src/Core/Platform/ImageSourceLoader.cs (hunk 5 above)
Comment (PureWeen) [reply src/Controls/src/Core/Platform/ImageSourceLoader.cs:43]: These are all static methods. We don't have anywhere in this context to cache anything.

File: src/Core/src/Handlers/NavigationPage/NavigationViewHandler.Windows.cs (hunk 6 above)
Comment (rmarinho) [reply src/Core/src/Handlers/NavigationPage/NavigationViewHandler.Windows.cs:13]: Right, but we can cast it when we use it , and just have Frame here no ?

File: src/Core/src/Platform/Windows/NavigationManager.cs (hunk 7 above)
Comment (PureWeen) [reply src/Core/src/Platform/Windows/NavigationManager.cs:31]: 👍

File: src/Core/src/Platform/Windows/WindowManager.cs (hunk 10 above)
Comment (PureWeen) [reply src/Core/src/Platform/Windows/WindowManager.cs:31]: 👍

File: src/Core/src/Platform/Windows/NavigationManager.cs (hunk 8 above)
Comment (PureWeen) [reply src/Core/src/Platform/Windows/NavigationManager.cs:79]: 👍

File: src/Core/src/Platform/Windows/WindowManager.cs (hunk 9 above)
Comment (PureWeen) [reply src/Core/src/Platform/Windows/WindowManager.cs:10]: Yea, might as well make it public now so users can play with it and give feedback

File: src/Core/src/Handlers/NavigationPage/NavigationViewHandler.Windows.cs (hunk 6 above)
Comment (PureWeen) [reply src/Core/src/Handlers/NavigationPage/NavigationViewHandler.Windows.cs]: Check it out now 🔥🔥🔥🔥🔥🔥

File: src/Core/src/Platform/Windows/NavigationManager.cs (hunk 8 above)
Comment (PureWeen) [reply src/Core/src/Platform/Windows/NavigationManager.cs]: The animations only ever animate with a slide left animation :-/ 

I think we need to switch to Connected Animations
https://github.com/dotnet/maui/issues/2604

File: src/Core/src/Platform/MauiContext.Windows.cs [hunk 11]
```diff
@@ -4,12 +4,16 @@ namespace Microsoft.Maui
 {
 	public partial class MauiContext
 	{
+		WindowManager? _windowManager;
 		public MauiContext(IServiceProvider services, UI.Xaml.Window window)
 			: this(services)
 		{
 			Window = window ?? throw new ArgumentNullException(nameof(window));
+			_windowManager = new WindowManager(this);
```
Comment (rmarinho) [inline src/Core/src/Platform/MauiContext.Windows.cs:12]: Should this be get from services in the future?

**Review by rmarinho — APPROVED** [review]

**Comment by rmarinho** [comment]
Great work, tested a couple of pages seems to work fine.
