### PR TITLE
Fix Label Multilinetruncation (MaxLines / LineBreakMode)

### LINKED ISSUE #14125: [regression/7.0.0] Label Multilinetruncation (MaxLines / LineBreakMode)
### Description

Hi, I have run into issue where using MaxLines and  LineBreakMode didn't work. 

code of the label:
` new Label()
        {
            MaxLines = 2,
            LineBreakMode = LineBreakMode.TailTruncation,
        }
          .Font(family: MediumFont)
          .FontSize(16.AsSize());
 `

When used, label truncated on the first line.

Per this Git https://github.com/dotnet/maui/pull/5093 the issue have been fixed. We are using version 7.0.52 where it should already work as it has been fixed somewhere in Maui 6.

This workaround worked:
https://github.com/dotnet/maui/discussions/5492#discussioncomment-4681884

### Steps to Reproduce

Create label with MaxLines=2, LineBreakMode=LineBreakMode.TailTruncation

Fill label with string longer than 2 lines.

### Link to public reproduction project repository

n/a

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

both latest os of Iphone and Android

### Did you find any workaround?

https://github.com/dotnet/maui/discussions/5492#discussioncomment-4681884

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

| Android | iOS | Windows |
| :-: | :-: | :-: |
| issue-13981-droid | ios | issue-13981-win |

Summary:
- The Button does not have the MaxLines property, it always stays with a single line and doing the tail truncation.
- With a Label, if the maximum number of lines is not specified, when establishing the LineBreakMode.TailTruncation the maximum number of lines used is 1, and tail truncation is applied.
- If MaxLines and LineBreakMode are established in the Label, both options are applied.

### Issues Fixed

Fixes #14125

### CODE REVIEW

File: src/Controls/src/Core/Platform/Android/Extensions/TextViewExtensions.cs [hunk 1]
```diff
@@ -67,12 +68,11 @@ internal static void SetLineBreakMode(this TextView textView, LineBreakMode line
 					break;
 				case LineBreakMode.TailTruncation:
 
-					// Leaving this in for now to preserve existing behavior
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/Extensions/TextViewExtensions.cs:70]: The existing behavior is different from Xamarin.Forms.
issue-13981-forms

In this PR we apply changes to only force the single line with the Button because has no MaxLines property.

**Review by mattleibow — COMMENTED** [review]
Are there any tests we can add for these changes?

**Comment by jsuarezruiz** [comment]
> Are there any tests we can add for these changes?

Sure.
image

**Review by jfversluis — DISMISSED** [review]

**Comment by EmanterolaDN** [comment]
One little step closer... Please someone who can merge it... 🙏

**Review by rachelkang — DISMISSED** [review]
This branch currently fails to build - will re-review when it's fixed!

I'm getting the following on `dotnet build Microsoft.Maui.BuildTasks.slnf` only on this branch:
```
C:\Users\rachelkang\maui\src\Controls\src\Core\Label\Label.iOS.cs(51,71): error CS0246: The type or namespace na
me 'Action<,>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\rachel
kang\maui\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-maccatalyst]
C:\Users\rachelkang\maui\src\Controls\src\Core\Label\Label.iOS.cs(43,70): error CS0246: The type or namespace na
me 'Action<,>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\rachel
kang\maui\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-maccatalyst]
C:\Users\rachelkang\maui\src\Controls\src\Core\Label\Label.iOS.cs(59,65): error CS0246: The type or namespace na
me 'Action<,>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\rachel
kang\maui\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-maccatalyst]
C:\Users\rachelkang\maui\src\Controls\src\Core\Label\Label.iOS.cs(67,59): error CS0246: The type or namespace na
me 'Action<,>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\rachel
kang\maui\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-maccatalyst]
C:\Users\rachelkang\maui\src\Controls\src\Core\Label\Label.iOS.cs(82,64): error CS0246: The type or namespace na
me 'Action<,>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\rachel
kang\maui\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-maccatalyst]
C:\Users\rachelkang\maui\src\Controls\src\Core\Label\Label.iOS.cs(51,71): error CS0246: The type or namespace na
me 'Action<,>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\rachel
kang\maui\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-ios]
C:\Users\rachelkang\maui\src\Controls\src\Core\Label\Label.iOS.cs(43,70): error CS0246: The type or namespace na
me 'Action<,>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\rachel
kang\maui\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-ios]
C:\Users\rachelkang\maui\src\Controls\src\Core\Label\Label.iOS.cs(59,65): error CS0246: The type or namespace na
me 'Action<,>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\rachel
kang\maui\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-ios]
C:\Users\rachelkang\maui\src\Controls\src\Core\Label\Label.iOS.cs(67,59): error CS0246: The type or namespace na
me 'Action<,>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\rachel
kang\maui\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-ios]
C:\Users\rachelkang\maui\src\Controls\src\Core\Label\Label.iOS.cs(82,64): error CS0246: The type or namespace na
me 'Action<,>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\rachel
kang\maui\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-ios]
    59 Warning(s)
    10 Error(s)
```

File: src/Controls/src/Core/Platform/Android/Extensions/TextViewExtensions.cs [hunk 2]
```diff
@@ -31,14 +32,21 @@ public static void UpdateLineBreakMode(this TextView textView, Label label)
...
 			if (!maxLines.HasValue || maxLines <= 0)
-				maxLines = int.MaxValue;
+			{
+				// Without setting the MaxLines property, to equalize behaviors across platforms
+				// we set the max to 1.
+				if (lineBreakMode == LineBreakMode.TailTruncation)
+					maxLines = 1;
+				else
+					maxLines = int.MaxValue;
+			}
```
Comment (mattleibow) [inline src/Controls/src/Core/Platform/Android/Extensions/TextViewExtensions.cs:49]: Maybe we should leave this as is and move this _after_ the switch. We are setting 1 in many places so it feels better to rather isolates the 1 to the switches. And then we cleanup after the fact.

Comment (mattleibow) [reply src/Controls/src/Core/Platform/Android/Extensions/TextViewExtensions.cs:49]: At the setting, we could do:

```cs
textView.SetMaxLines(maxLines ?? int.MaxValue);
```

File: src/Controls/src/Core/Platform/iOS/Extensions/TextExtensions.cs [hunk 3]
```diff
@@ -72,8 +72,14 @@ public static void UpdateMaxLines(this UILabel platformLabel, Label label)
...
 			int maxLines = label.MaxLines;
+
 			if (maxLines < 0)
-				maxLines = 0;
+			{
+				if (label.LineBreakMode == LineBreakMode.TailTruncation)
+					maxLines = 1;
+				else
+					maxLines = 0;
+			}
```
Comment (mattleibow) [inline src/Controls/src/Core/Platform/iOS/Extensions/TextExtensions.cs:82]: Do we need to do this? We already set to 1 in the switch.

File: src/Controls/src/Core/Platform/Windows/Extensions/TextBlockExtensions.cs [hunk 4]
```diff
@@ -99,6 +64,46 @@ public static void UpdateDetectReadingOrderFromContent(this TextBlock platformCo
 				platformControl.SetTextReadingOrder(label.OnThisPlatform().GetDetectReadingOrderFromContent());
 		}
 
+		internal static void SetLineBreakMode(this TextBlock textBlock, LineBreakMode lineBreakMode, int? maxLines = null)
```
Comment (mattleibow) [inline src/Controls/src/Core/Platform/Windows/Extensions/TextBlockExtensions.cs:67]: Do we need to add this method and mix the max lines and line break? I know the other platforms need it, but Widows is a bit better in this area?

File: src/Controls/src/Core/Platform/iOS/Extensions/TextExtensions.cs (hunk 3 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Platform/iOS/Extensions/TextExtensions.cs:82]: Moved to the switch.

File: src/Controls/src/Core/Platform/Windows/Extensions/TextBlockExtensions.cs (hunk 4 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Platform/Windows/Extensions/TextBlockExtensions.cs:67]: Yeah, both properties are related so like in other platforms we have a method to manage everything in the same place.

**Comment by samhouts** [comment]
Tests are failing?

**Comment by samhouts** [comment]
Please test changes against https://github.com/dotnet/maui/issues/18059, too. Thanks!

**Comment by jsuarezruiz** [comment]
> Please test changes against #18059, too. Thanks!

Added a specific device test to validate that case.

**Review by mattleibow — DISMISSED** [review]

**Review by mattleibow — DISMISSED** [review]

**Review by mattleibow — APPROVED** [review]

**Review by jfversluis — APPROVED** [review]
