### PR TITLE
[iOS]Fix: FlyoutPage memory leak

### LINKED ISSUE #21206: [Testing] Crash popping FlyoutPage
### Description

Crash passing the test Bugzilla31255 https://github.com/dotnet/maui/blob/a648f0846940dea155723f0235bb2cb9143d3e74/src/Compatibility/ControlGallery/src/Issues.Shared/Bugzilla31255.cs#L17
issue-bz31255

### Steps to Reproduce

1. Create a sample using https://github.com/dotnet/maui/blob/a648f0846940dea155723f0235bb2cb9143d3e74/src/Compatibility/ControlGallery/src/Issues.Shared/Bugzilla31255.cs#L17
2. Launch the App on Android.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.0-preview.1.9973

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by bhavanesh2001**
### Description of Change

While enabling the UITest `Bugzilla31255Test`, which pushes a `FlyoutPage` modally and then pops it, I encountered a memory leak on iOS. The `FlyoutPage` instance was not being collected even after the modal pop.

Originally, the test case was also causing a crash because `Flyout` and `Detail` were being set to instances of `Page`, which is not supported. I updated them to use `ContentPage`, which resolved the crash.

The memory leak was caused by the renderer holding a strong reference to the virtual view (`_element`), which prevented the `FlyoutPage` from being garbage collected. 

I also added a device test that reproduces the same modal flow and asserts that the page is collected by the GC. While this device test covers the same scenario as the UITest, I’ve kept both for now.

If you'd prefer to remove the UITest and rely only on the device test, let me know.

<table>
  <tr>
<th>Before Fix</th>
<th>After Fix</th>
</tr>
<tr>
<td>

Screenshot 2025-04-02 at 9 17 03 PM

</td>
<td>

Screenshot 2025-04-02 at 9 19 11 PM

</td>
</tr>
</table>

### Issues Fixed 

Fixes #21206

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs [hunk 1]
```diff
@@ -269,9 +270,7 @@ protected override void Dispose(bool disposing)
 				}
 
 				EmptyContainers();
-
-				Page.SendDisappearing();
```
Comment (bhavanesh2001) [inline src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs:273]: this shouldn't be here. We are already calling this above
https://github.com/dotnet/maui/blob/8ee00e00f603cd8a420a3467daddaf3935c8c587/src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs#L132

Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs:273]: Does it matter if we just leave it?

Comment (bhavanesh2001) [reply src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs:273]: @PureWeen Without the PR changes, since we’re inside `Dispose`, the wrapper’s Element will be null at this point — so `Page` falls back to the strongly referenced _element:

https://github.com/dotnet/maui/blob/8ee00e00f603cd8a420a3467daddaf3935c8c587/src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs#L78

With the PR changes, `_element` is resolved through a weak reference, so keeping the `SendDisappearing()` call here won’t make a difference

Let me know if you think I should still keep the call.

File: src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs [hunk 2]
```diff
@@ -17,7 +17,8 @@ public class PhoneFlyoutPageRenderer : UIViewController, IPlatformViewHandler
 	{
 		UIView _clickOffView;
 		UIViewController _detailController;
-		VisualElement _element;
+		WeakReference<VisualElement> element;
+		VisualElement _element => element?.GetTargetOrDefault();
```
Comment (jonathanpeppers) [inline src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs:21]: Can you instead do:
```suggestion
		WeakReference<VisualElement> _element;
```
Which also follows the naming guidelines by using `_` prefixed names.

It also makes it more clear how many times `_element.TryGetTarget()` is accessed. This is several times slower than accessing a plain field because it goes through a "GC handle" to find the object.

Comment (bhavanesh2001) [reply src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs]: @jonathanpeppers Done. Thanks for the suggestion.

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31255.cs [hunk 3]
```diff
@@ -14,15 +13,14 @@ public Bugzilla31255(TestDevice testDevice) : base(testDevice)
...
-		[Ignore("The sample is crashing. More information: https://github.com/dotnet/maui/issues/21206")]
 		[Category(UITestCategories.Navigation)]
 		[Category(UITestCategories.Compatibility)]
-		public async Task Bugzilla31255Test()
+		public void Bugzilla31255Test()
 		{
 			App.Screenshot("I am at Bugzilla 31255");
-			await Task.Delay(5000);
-			App.WaitForNoElement("Page1. But Page2 IsAlive = False");
+			Thread.Sleep(5000);
```
Comment (jonathanpeppers) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31255.cs:21]: This test is probably going to be flaky as-is (possible to fail at some percentage), best results are to do something like these other tests:

https://github.com/dotnet/maui/blob/dad356b535cf025ce5f99017cb235030ea9ea095/src/Controls/tests/Core.UnitTests/WeakEventProxyTests.cs#L25-L27

@PureWeen is there a helper method for this in the UITests project?

Comment (bhavanesh2001) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31255.cs:21]: @jonathanpeppers  checking for memory leaks in a UI test isn’t really ideal and not something we typically do. That’s exactly why I added a device test that covers the same modal `FlyoutPage` scenario.

I’ve still kept the UI test for now just because it was already there and passing with the fix, but I think we can safely remove it if we’re good with the device test coverage.

**Comment by bhavanesh2001** [comment]
The UI test is passing, but the device test failed on Android and Windows. It seems the issue was with the test itself, so I’ve modified it accordingly.
Screenshot 2025-04-04 at 7 16 40 PM
Screenshot 2025-04-04 at 7 17 03 PM
@jsuarezruiz

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31255.cs (hunk 3 above)
Comment (PureWeen) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31255.cs:21]: This is what we do in other UITests

https://github.com/dotnet/maui/blob/61abc89a8d09f55903e7c5ae588d423cbbb90817/src/Controls/tests/TestCases.Shared.Tests/UtilExtensions.cs#L61

I don't know if we need the thread sleep. The timeout for WaitForElement is nice because it works based on a retry so it'll quit earlier if found

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31255.cs [hunk 4]
```diff
@@ -14,15 +13,12 @@ public Bugzilla31255(TestDevice testDevice) : base(testDevice)
...
-		[Ignore("The sample is crashing. More information: https://github.com/dotnet/maui/issues/21206")]
 		[Category(UITestCategories.Navigation)]
 		[Category(UITestCategories.Compatibility)]
-		public async Task Bugzilla31255Test()
+		public void Bugzilla31255Test()
 		{
 			App.Screenshot("I am at Bugzilla 31255");
-			await Task.Delay(5000);
-			App.WaitForNoElement("Page1. But Page2 IsAlive = False");
+			App.AssertMemoryTest();
```
Comment (PureWeen) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31255.cs:21]: Love it!

**Review by PureWeen — DISMISSED** [review]

**Review by PureWeen — APPROVED** [review]
