### PR TITLE
Setup legacy mappers

### LINKED ISSUE #18059: [regression/8.0.0-preview.7.8842] Labels with max lines and linebreakmode not working even with adding handler workaround
### Description

Adding a label with LineBreakMode="TailTruncation" and MaxLines="2" makes the label only show on one line. Even adding the workaround handler (which fixed this issue in Net7) does not help anymore. I have attached a sample repo showing this - the last label should show on two lines.

### Steps to Reproduce

1. Get repo and see bottom label - it should be on two lines.

### Link to public reproduction project repository

https://github.com/Zack-G-I-T/LabelBugNet8

### Version with bug

[8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

[8.0.0-preview.6.8686](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.6.8686)

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

Update code to use the new mapper:

```
 public static void AllowMultiLineTruncation()
 {
     static void UpdateMaxLines(Microsoft.Maui.Handlers.LabelHandler handler, ILabel label)
     {
         var textView = handler.PlatformView;
         if (label is Label controlsLabel
             && textView.Ellipsize == TextUtils.TruncateAt.End && controlsLabel.MaxLines != -1)
         {
             textView.SetMaxLines(controlsLabel.MaxLines);
         }
     };

     LabelHandler.Mapper.AppendToMapping(
        nameof(Label.LineBreakMode), (h, v) => UpdateMaxLines((LabelHandler)h, v));

     LabelHandler.Mapper.AppendToMapping(
       nameof(Label.MaxLines), (h, v) => UpdateMaxLines((LabelHandler)h, v));
 }
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

 We obsoleted the `ControlsMappers` because they were causing issues when the application was AOT'd https://github.com/dotnet/maui/pull/13836. This change disconnected the controls mappers completely from the core mappers, which meant that if someone was wiring into these their code would stop executing.
 
 This PR takes a minimal approach to proxy mapper modifications from the `ControlsMapper` to the `Core` mappers in order to not break users when they update to NET8.

If someone is wiring into the `ControlsMappers` inside `MauiProgram` before any of the builder extension methods are called their code still won't run. That path was already unreliable and broken with AOT.

### Issues Fixed
Fixes #18059

### CODE REVIEW

File: src/Core/src/PropertyMapper.cs [hunk 1]
```diff
@@ -121,6 +132,42 @@ public virtual IEnumerable<string> GetKeys()
...
+		}
+
+		PropertyMapper? _overrideMapper;
+
+		[Obsolete]
+		internal PropertyMapper? OverrideMapper
+		{
+			get
+			{
+				if (_overrideMapper is not null && _overrideMapper.Keys.Count > 0)
```
Comment (PureWeen) [inline src/Core/src/PropertyMapper.cs:153]: Only trigger the override mapper if the user has added something to it, otherwise we just fallback to normal behavior

**Review by hartez — APPROVED** [review]
