### PR TITLE
[Android] BackgroundColor for GraphicsView

### LINKED ISSUE #19568: GraphicsView does not change the Background/BackgroundColor on Android
### Description

Background and BackgroundColor does not work on Android with GraphicsView

| iOS | Android |
| --- | --- |
| |  |

### Steps to Reproduce

- Create a new project
- Add a GraphicsView to your XAML
- Change Background or BackgroundColor property and it will work on iOS but not on Android

### Link to public reproduction project repository

https://github.com/FreakyAli/Maui.FreakyEffects/tree/grahpicsViewBug

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/19568

|Before|After|
|--|--|
|||

### CODE REVIEW

File: src/Core/src/Platform/Android/GraphicsViewExtensions.cs [hunk 1]
```diff
@@ -8,5 +9,10 @@ public static void UpdateDrawable(this PlatformGraphicsView PlatformGraphicsView
 		{
 			PlatformGraphicsView.Drawable = graphicsView.Drawable;
 		}
+
+		internal static void UpdateBackground(this PlatformGraphicsView PlatformGraphicsView, IGraphicsView graphicsView)
+		{
+			PlatformGraphicsView.BackgroundColor = graphicsView.Background?.ToColor() ?? Colors.White;
```
Comment (mattleibow) [inline src/Core/src/Platform/Android/GraphicsViewExtensions.cs:15]: White or Transparent? What was it before if you don't set a color? What is the "default" color?

**Review by mattleibow — COMMENTED** [review]
Looks correct, just wondering why this is just on android and also what should a "null" color be?

File: src/Core/src/Platform/Android/GraphicsViewExtensions.cs (hunk 1 above)
Comment (kubaflo) [reply src/Core/src/Platform/Android/GraphicsViewExtensions.cs:15]: Yea, my bad... The default was, so I shouldn't have changed it to white😅

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

**Comment by kubaflo** [comment]
I had a feeling this pr: https://github.com/dotnet/maui/pull/26368 would fix it, but it didn't

**Review by jfversluis — APPROVED** [review]
