### PR TITLE
[Windows] Fix FontImageSource resize behavior

### LINKED ISSUE #20648: Add more tests for Images on buttons
There is a fair bit of code being removed, so I am a bit worried. Could you add a test as well for buttons/images that do not have a width or height? Basically, an auto-sized button based on the image size. Maybe even a plain button. Not sur if those tests exist, so might be OK if they do. We have the concept of buttons with text and I am sure there was a PR to do things.

_Originally posted by @mattleibow in https://github.com/dotnet/maui/pull/17159#discussion_r1491536140_

CC @foda

### LINKED ISSUE #21202: [Windows] Button font image source incorrectly sized on 8.0.10 when specifying a button HeightRequest
### Description

From version 8.0.10, using a font image source on a button image source is incorrectly resizing its content when a heightrequest is set on the button, resulting in the UI having different sized elements and the font image itself looking blurry (and increasingly blurrier depending on how small you had set the size for the font image source).

[Note: version 8.0.10 is missing from the list of versions in this bug form, which is why I had to select "other". edit: now manually changed to 8.0.10].

### Steps to Reproduce

1. add the following xaml to any page
 ```
<Button
                FontSize="18.75"
                HeightRequest="60"
                HorizontalOptions="Fill"
                Text="Button with height request set"
                TextTransform="Uppercase">
                <Button.ImageSource>
                    <FontImageSource Glyph="A" />
                </Button.ImageSource>
            </Button>
            <Button
                FontSize="18.75"
                HorizontalOptions="Fill"
                Text="Button without height request"
                TextTransform="Uppercase">
                <Button.ImageSource>
                    <FontImageSource Glyph="A" />
                </Button.ImageSource>
            </Button>
```

2. Expected:
image
3. Observed:
image

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.10

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.7 SR2

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

Using MinimumHeightRequest instead of HeightRequest stops this issue.
image

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Foda**
### Description of Change

Images should always set their size to the size of `FontImageSource`/`CanvasImageSource` as this is established behavior for Maui/Xamarin.

#### Image + Button Resize Rules

* Images should always set their size to the size of `FontImageSource`/`CanvasImageSource` regardless of if they're in a button or not
* If you don't set the size of the button then the button should grow to fit the image/content size
* If you set the size of the button the image should stretch to fit the available space, unless it's a `FontImageSource`/`CanvasImageSource`
* If you set the size of the button and the image then no resizing should happen
* If you set the size of the image, it should not resize

### Issues Fixed

Fixes #21202
Fixes #20648

### CODE REVIEW

File: src/Core/src/Platform/Windows/ButtonExtensions.cs [hunk 1]
```diff
@@ -159,10 +160,18 @@ public static void UpdateImageSource(this Button platformButton, WImageSource? n
...
 				nativeImage.Stretch = UI.Xaml.Media.Stretch.Uniform;
 				nativeImage.Source = nativeImageSource;
 
+				// If we're a CanvasImageSource (font image source), we need to explicitly set the image height
+				// to the desired size of the font, otherwise it will be stretched to the available space
+				if (nativeImage.Source is CanvasImageSource canvas)
+				{
+					nativeImage.Width = canvas.Size.Width;
+					nativeImage.Height = canvas.Size.Height;
+				}
```
Comment (mattleibow) [inline src/Core/src/Platform/Windows/ButtonExtensions.cs:173]: I feel like I reviewed a PR weeks ago that removed all the measuring code here - from normal images and things.

File: src/Controls/samples/Controls.Sample.UITests/Issues/Issue18242.xaml [hunk 2]
```diff
@@ -3,36 +3,82 @@
 			 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
 			 x:Class="Maui.Controls.Sample.Issues.Issue18242"
 			 Title="Issue 18242">
```
Comment (mattleibow) [inline src/Controls/samples/Controls.Sample.UITests/Issues/Issue18242.xaml:5]: Maybe this should be a new page? I just finished up the Android fixes and if there are 2 columns this page will be too narrow and cramped for a good test on android/ios

File: src/Controls/samples/Controls.Sample.UITests/Controls.Sample.UITests.csproj [hunk 3]
```diff
@@ -48,6 +48,10 @@
     <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#FFFFFF" BaseSize="168,208" />
   </ItemGroup>
 
+  <ItemGroup>
+    <EmbeddedResource Include="Resources\Fonts\OpenSans-Regular.ttf" />
```
Comment (mattleibow) [inline src/Controls/samples/Controls.Sample.UITests/Controls.Sample.UITests.csproj:52]: Maybe this should just be `<MauiFont>` ?

File: src/Core/src/Platform/Windows/ButtonExtensions.cs (hunk 1 above)
Comment (mattleibow) [reply src/Core/src/Platform/Windows/ButtonExtensions.cs:173]: This commit: https://github.com/dotnet/maui/commit/7dff6eb55b85ae50bc9e0ce90778981b913e34e1#diff-e34feff8430d43e27f52abff099ba347b41628f6bde6a68e12f8b618722c59c9

Should this rather have been implemented differently instead of just being removed?

Comment (Foda) [reply src/Core/src/Platform/Windows/ButtonExtensions.cs:173]: Yeah, you did 🥲. I misunderstood the behavior of how `FontImageSource` scales-to-fit the available space, which differs from how images in buttons scale-to-fit.

File: src/Controls/samples/Controls.Sample.UITests/Issues/Issue18242.xaml (hunk 2 above)
Comment (Foda) [reply src/Controls/samples/Controls.Sample.UITests/Issues/Issue18242.xaml:5]: Yeah, that's probably a good idea.

File: src/Controls/samples/Controls.Sample.UITests/Controls.Sample.UITests.csproj (hunk 3 above)
Comment (Foda) [reply src/Controls/samples/Controls.Sample.UITests/Controls.Sample.UITests.csproj:52]: Non-packaged app fonts won't work if they're set to `MauiFont`

Comment (mattleibow) [reply src/Controls/samples/Controls.Sample.UITests/Controls.Sample.UITests.csproj:52]: should be fixed now - we merged the win2d updates.

But it is fine if we want this to run on older branches.

**Review by mattleibow — DISMISSED** [review]

**Review by PureWeen — APPROVED** [review]

**Comment by PureWeen** [comment]
UI Tests all passed.
Failing Device tests are unrelated
