### PR TITLE
Fix publishing WPF/WinForms Blazor apps with MSIX

### LINKED ISSUE #3275: [Bug] wwwroot is not included when using blazor + WPF + MSIX for Windows Store
### Steps to Reproduce

1. Pull https://github.com/jorgearteiro/BlazorDesktopWPF
2. Add "Windows Application Packaging project" for BlazorDesktopWPF
3. Create a bundle
4. Check the bundle file you will see the wwwroot is not included and the app will not be able to start

### Expected Behavior
All razor resourcces should be included when MSIX bundling

### PR DESCRIPTION
**Pull request by Eilon**
Two parts to this fix:
1. Make sure static assets are located relative to the running app (and not the current directory)
2. Update targets to ensure static assets are available prior to publish

Fixes #3275

@SteveSandersonMS / @pranavkm - can one of you review while @javiercn is out? I can gladly walk you through this change. It mostly boils down to copying logic from the existing publish target to a new target for MSIX/WAP published apps.

### CODE REVIEW

**Comment by Eilon** [comment]
Oh, also everything is duplicate because it's the same change for WPF and for WinForms.

**Comment by Eilon** [comment]
@SteveSandersonMS - could I get a quick review on this? The code part of the change is I think fairly straightforward: don't use CurrentDirectory to resolve paths; use the assembly startup path instead. The MSBuild stuff might not be your cup of Yorkshire Tea, but it's essentially copying what we did for ClickOnce publishing to do the equivalent logic for FileSystem publishing (used by MSIX).

File: src/BlazorWebView/src/WindowsForms/BlazorWebView.cs [hunk 1]
```diff
@@ -147,11 +148,22 @@ private void StartWebViewCoreIfPossible()
 
 			// We assume the host page is always in the root of the content directory, because it's
 			// unclear there's any other use case. We can add more options later if so.
-			var contentRootDir = Path.GetDirectoryName(Path.GetFullPath(HostPage));
-			var hostPageRelativePath = Path.GetRelativePath(contentRootDir, HostPage);
+			string appRootDir;
+			var entryAssemblyLocation = Assembly.GetEntryAssembly()?.Location;
+			if (!string.IsNullOrEmpty(entryAssemblyLocation))
```
Comment (SteveSandersonMS) [inline src/BlazorWebView/src/WindowsForms/BlazorWebView.cs:153]: It might be handy to have a comment here about in what case `Assembly.GetEntryAssembly()?.Location` might not be set. Is this for something specific like Android where the assemblies are loaded in a special way?

Comment (SteveSandersonMS) [reply src/BlazorWebView/src/WindowsForms/BlazorWebView.cs:153]: Oh actually this is WinForms so I guess not Android! Is it specifically with MSIX that the entry assembly has no location?

**Review by SteveSandersonMS — APPROVED** [review]
Cool!

File: src/BlazorWebView/src/WindowsForms/BlazorWebView.cs (hunk 1 above)
Comment (Eilon) [reply src/BlazorWebView/src/WindowsForms/BlazorWebView.cs:153]: Good point; I don't know of any case where it would be null in WinForms/WPF, so it's more of a "try to handle nulls gracefully" thing.

Comment (pranavkm) [reply src/BlazorWebView/src/WindowsForms/BlazorWebView.cs:153]: I think Assembly.Location is null for single file exes. IIRC, something in the build (analyzer / trimmer / sdk) complains if you use that API.

**Comment by agc93** [comment]
Should this fix be available in preview 11? I can't see it in the release notes, and I'm still getting errors with missing content roots when MSIX packaging using Preview 11

**Comment by Eilon** [comment]
@agc93 yes I believe it should be in preview 11. I see that the missing targets are now in the NuGet package, and that was part of the fix. Can you log a new bug with details on how to reproduce the issue? BTW one common issue is that the main app's CSPROJ __must__ use the Razor SDK and not just the .NET SDK. So check your CSPROJ file first.

**Comment by agc93** [comment]
Thanks @Eilon for the confirmation! I've created #3866 with a repro that hopefully helps with it.

Also, yes, I've updated the SDK in the `csproj`, thanks for the tip!
