### PR TITLE
[Windows] Fix template check for item recycle

### LINKED ISSUE #12988: DataTemplateSelector on CollectionView is completely broken - templates don't match BindingContext
### Description

Items in CollectionView utilizing DataTemplateSelector get often assigned to wrong DataTemplate. It appears to be a problem related to recycling views. While first items are usually displayed with correct DataTemplate, once the recycling kicks in the DataTemplates are mismatched. It's a serious issue as it makes the DataTemplateSelector unusable without any workaround. The problem was observed on Windows. Other platforms were not tested.

It might be the same problem as https://github.com/dotnet/maui/issues/11272. There is also a related PR to this issue right now https://github.com/dotnet/maui/pull/12011, but both the issue and PR mention only Android and iOS and the description of the problem is different. In my case the views get recycled, but incorrectly.

I made a sample showing list of colors to visualize the problem. Each row consists of two colors - one color assigned by DataTemplate and the other assigned by BindingContext.

Screenshot 2023-01-30 000442

### Steps to Reproduce

1. Load the repository and run the app.
2. Scroll the CollectionView to trigger virtualization.
3. Notice mismatched colors. Left half is the color assigned by DataTemplate, right half is color from BindingContext. Differences in numbers can help identify recycled views.

### Link to public reproduction project repository

https://github.com/Vroomer/MAUI-CollectionView-DataTemplateSelector-Bug.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.22621

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #20842: CollectionView view DataTemplateSelector takes random layout when scroll on Windows
### Description

DataTemplateSelector is broken on the latest 8.0.7 version on Windows.
First, we reproduced it on our project, but it was easy to reproduce on a sample maui project, see videos below.
https://github.com/dotnet/maui-samples/tree/main/8.0/Fundamentals/DataTemplateDemos

So before the update of Microsoft.Maui.Controls nuget package to 8.0.7, DataTemplateSelector works without any issues. You can see the video below, test project uses green and red templates depending on birthdate(> 1980 or < 1980).

https://github.com/dotnet/maui/assets/102372354/484f7f1d-1abe-46a6-ad18-7ebec61fccc0

After updating nuget package and rebuilding the same solution take a random layout when scroll:

https://github.com/dotnet/maui/assets/102372354/6509b0d9-1eef-402e-9bd7-8d8fd9654b5e

It's a blocker for us as we need to update because of the performance improvements, but we cannot as the update breaks DataTemplateSelector. Please let us know if there are any workarounds.

### Steps to Reproduce

1. Update Microsoft.Maui.Controls nuget package to 8.0.7
2. Open the project with DataTemplateSelector
3. Try to scroll items and check if collectionview uses correct layout

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.6 SR1

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Foda**
### Description of Change

* Fix template check for item recycle
* Ifdef `UseMauiMaps` for Windows in sandbox app

### Issues Fixed

Fixes #20842
Fixes #12988

### CODE REVIEW

**Review by jfversluis — DISMISSED** [review]

File: src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs [hunk 1]
```diff
@@ -163,12 +163,19 @@ internal void Realize()
 				return;
 			}
 
+			// If the template is a DataTemplateSelector, we need to get the actual DataTemplate to use
+			// for our recycle check below
+			if (formsTemplate is DataTemplateSelector dataTemplateSelector)
```
Comment (jfversluis) [inline src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs:168]: nit: I guess we technically might want to rename it to not-Forms? 😬

Comment (PureWeen) [inline src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs:168]: Can we use this extension method that should probably be internal?

https://github.com/dotnet/maui/blob/eb9666b5ed558f4bc6a5d7956c84e160e49c3a30/src/Controls/src/Core/DataTemplateExtensions.cs#L11-L18

iOS uses this extension method to realize its templates as well

**Review by jfversluis — APPROVED** [review]

**Comment by PureWeen** [comment]
Failing test unrelated

**Comment by PureWeen** [comment]
failing test unrelated
