### PR TITLE
Fix Blazor Hybrid page reloading

### LINKED ISSUE #5136: BlazorWebView inside Android can't be reloaded
### Description

On other platforms, it's perfectly valid for the Blazor Hybrid application to reload, e.g. because of:

 * The developer explicitly triggering a reload
 * Or, some auth flow causing a reload
 * Or, the yellow error bar's "Reload" link being clicked

... and the application should come back to life and continue working. However, on Android, the page fails to reload.

### Steps to Reproduce

1. Create a Blazor Hybrid application
2. In one of your pages, add `<a href="javascript:location.reload()">Reload</a>`
   * This needs to be a non-root page. For example, the page at `/counter`, and *not* the homepage at `/`.
4. Run it in the Android Emulator
5. Click the reload link you just added

Expected: page should reload
Actual:

image

(In place of "navigation", you will see the URL of your page, e.g., "counter")

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30, probably others too

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by MackinnonBuck**
### Description of Change

This PR resolves an issue where non-root pages cannot be loaded on some platforms in Blazor Hybrid applications. This behavior was initially observed in Android, but I was able to reproduce it in WinUI. It may be worthwhile to also check if the buggy reloading behavior exists in iOS.

### Issues Fixed

This PR fixes page reloading issues for both WinUI and Android platforms.

Fixes #5136

### CODE REVIEW

File: src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs [hunk 1]
```diff
@@ -87,7 +87,10 @@ protected override async Task HandleWebResourceRequest(CoreWebView2WebResourceRe
 				if (new Uri(AppOrigin).IsBaseOf(uri))
 				{
 					var relativePath = new Uri(AppOrigin).MakeRelativeUri(uri).ToString();
-					if (allowFallbackOnHostPage && string.IsNullOrEmpty(relativePath))
+
+					// If the path does not end in a file extension (or is empty), it's most likely referring to a page,
+					// in which case we should allow falling back on the host page.
+					if (allowFallbackOnHostPage && !Path.HasExtension(relativePath))
```
Comment (TanayParikh) [inline src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs:93]: Given this change is in the Maui Windows WebViewManager, do we have to make an equivalent change in WPF/WinForms?

File: src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs [hunk 2]
```diff
@@ -127,56 +114,75 @@ private void RunBlazorStartupScripts(AWebView view)
...
 		}
 
+		private static bool IsAppOriginPageUri(string? requestUriString)
+		{
+			if (string.IsNullOrEmpty(requestUriString))
+			{
+				return false;
+			}
+
+			var appBaseUri = new Uri(AppOrigin);
```
Comment (Eilon) [inline src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs:174]: Consider adding a field like this at the top of the class and then using it in this method:

```c#
		private static readonly Uri AppOriginUri = new Uri(AppOrigin);
```

Because this can't change during app execution.

File: src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs [hunk 3]
```diff
@@ -108,7 +95,7 @@ public override void OnPageFinished(AWebView? view, string? url)
 			base.OnPageFinished(view, url);
 
 			// TODO: How do we know this runs only once?
-			if (view != null && url == AppOrigin)
+			if (view != null && IsAppOriginPageUri(url))
```
Comment (TanayParikh) [inline src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs:98]: Is this `TODO` relevant now that due to the reload mechanism this _can_ run more than once?

**Comment by Eilon** [comment]
Is the gist of the problem here that if the user is on the homepage and didn't navigate, it's fine, because the URL is still at the app root. But if the user navigated to let's say `/counter` then the original logic fails because the string `/counter` isn't empty? So this change allows any URL in the App to be navigated to as long as it doesn't have an extension?

File: src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs [hunk 4]
```diff
@@ -127,56 +114,75 @@ private void RunBlazorStartupScripts(AWebView view)
...
+			var appBaseUri = new Uri(AppOrigin);
+			var requestUri = new Uri(requestUriString);
+
+			if (!appBaseUri.IsBaseOf(requestUri))
+			{
+				return false;
+			}
+
+			// If the path does not end in a file extension, it's most likely referring to a page.
+			return !Path.HasExtension(requestUriString);
```
Comment (TanayParikh) [inline src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs:183]: Do we have to get the relative uri first?

```c#
var relativePath = new Uri(AppOrigin).MakeRelativeUri(requestUri).ToString()
```

Also, is the extension check sufficient? What if it's `0.0.0.0/index.html`?

**Comment by MackinnonBuck** [comment]
@Eilon yes, precisely.

File: src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs (hunk 3 above)
Comment (MackinnonBuck) [reply src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs:98]: I may be mistaken, but I think this TODO was referring to the case described here: https://github.com/dotnet/maui/blob/29e841af968ec2999fa6f1294169f964d024f4a6/src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs#L119-L125

I believe this new change is separate from that scenario.

Comment (TanayParikh) [reply src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs:98]: Ah okay, thanks for clarifying!

File: src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs (hunk 4 above)
Comment (MackinnonBuck) [reply src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs:183]: @Eilon do you think it would be worth it to special-case the host page path and treat it as a navigation request, or is that overkill?

File: src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs (hunk 1 above)
Comment (MackinnonBuck) [reply src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs:93]: WPF and WinForms don't appear to have the bug that this PR fixes.

File: src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs (hunk 4 above)
Comment (Eilon) [reply src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs:183]: Hmm I don't consider supporting direct navigation to `index.html` important. I kind of see the name `index.html` as an implementation detail because you can't have a file with no name to be at `/`, so we had to name it _something_, but we don't need you to use the name at any other time 😄

File: src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs (hunk 1 above)
Comment (Eilon) [reply src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs:93]: Hmm that does seem a bit odd. WebView2 doesn't differ much between the platforms so I wonder what would cause this?

Comment (MackinnonBuck) [reply src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs:93]: @Eilon It appears the WinUI implementation is different than the implementation shared by WinForms and WPF: https://github.com/dotnet/maui/blob/0448305bc2ef0dd81aec4c7940b3860a26df8293/src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs#L222-L227
https://github.com/dotnet/maui/blob/0448305bc2ef0dd81aec4c7940b3860a26df8293/src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs#L240-L242

Since the WinUI implementation uses a `NullFileProvider`, the fallback logic in [`StaticContentProvider`](https://github.com/dotnet/aspnetcore/blob/54a7109eade9ce07eae452d4702a791638584f22/src/Components/WebView/WebView/src/StaticContentProvider.cs#L68) doesn't work as it does for WinForms and WPF. The logic in `WinUIWebViewManager` that goes through WebUI storage had more restrictive criteria than `StaticContentProvider` when deciding whether to fall back on the host page, which is the source of the bug.

The Android scenario was actually a totally different bug - `Blazor.Start()` wasn't being called when the request URI didn't precisely match the app origin (so this broke things for non-root pages).

**Review by Eilon — APPROVED** [review]
