### PR TITLE
[core] WeakEventManager.RemoveEventHandler() should clear subscriptions

### LINKED ISSUE #9162: ListView/CollectionView memory leak under Windows
### Description

A simple repro  (see link below) demonstrates a ListView/CollectionView memory leak under Windows. 
Each time the ItemSource gets updated with the exact same list, the app memory usage increases.
The repro is a simplification, normally the ListView/CollectionView  gets filled through a binding. However the repro still demonstrates the same problem.

See this video for a demonstration:

https://user-images.githubusercontent.com/7484186/182551821-e686710b-300f-4dbc-b1e0-7650f187216b.mp4

I'm a VS Community user so do not have access to the Xamarin Profiler to see if the problem also exists in Android and iOS. 

### Steps to Reproduce

1. Open the app from the repro in VS: https://github.com/hbraasch/ListViewMemoryTester.git
2. Set the platform to [Windows] and run
3. Click on the refresh button in the toolbar, see how the memory usage increases
4. Click on the [Click to launch [CollectionView] page] button, which launches the page based on a CollectionView
5.  Click on the refresh button in the toolbar, see how the memory usage also increases

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041.0

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Context: https://github.com/dotnet/maui/issues/12039
Context: https://github.com/Vroomer/MAUI-master-detail-memory-leak
Context: https://github.com/symbiogenesis/Maui.DataGrid/tree/memory-leak

fixes #9162

Reviewing memory snapshots in the above apps, sometimes I would see new `WeakEventManager+Subscription` objects be created and never go away.

I noticed the `WeakEventManager.RemoveEventHandler()` method did not remove any `Subscription` entries that it encountered were no longer alive.

I could reproduce this problem in a test, and improved an existing test to check this collection is cleared appropriately:

    readonly Dictionary<string, List<Subscription>> _eventHandlers = new();

### CODE REVIEW

File: src/Core/src/WeakEventManager.cs [hunk 1]
```diff
@@ -125,15 +125,23 @@ void RemoveEventHandler(string eventName, object? handlerTarget, MemberInfo meth
...
 				return;
 
-			for (int n = subscriptions.Count; n > 0; n--)
+			for (int n = subscriptions.Count - 1; n >= 0; n--)
 			{
-				Subscription current = subscriptions[n - 1];
+				Subscription current = subscriptions[n];
 
-				if (current.Subscriber?.Target != handlerTarget || current.Handler.Name != methodInfo.Name)
+				if (current.Subscriber != null && !current.Subscriber.IsAlive)
```
Comment (mandel-macaque) [inline src/Core/src/WeakEventManager.cs:132]:
```suggestion
				if (current.Subscriber is not null && !current.Subscriber.IsAlive)
```
@PureWeen has an extension method for isAlive that already check it is not null, could it be used here?

**Review by mandel-macaque — APPROVED** [review]
+1 but I would wait for @PureWeen to comment.

File: src/Core/src/WeakEventManager.cs (hunk 1 above)
Comment (jonathanpeppers) [reply src/Core/src/WeakEventManager.cs:132]: Is it this one?

https://github.com/dotnet/maui/blob/236a60aad7188652ad43f9523979b26f5a2790fc/src/Controls/src/Core/WeakReferenceExtensions.cs#L8

In this case, we don't really need the generic version, as it is an `object` that looks like it can also be null.

I think `static` events can have a null `handlerTarget` here:

```csharp
if (current.Subscriber?.Target == handlerTarget && current.Handler.Name == methodInfo.Name)
```

**Review by jsuarezruiz — APPROVED** [review]
