### PR TITLE
Fix for button cornerradius 0 on android

### LINKED ISSUE #18090: Button CornerRadius is not working with BackgroundColor
### Description

image

image

I set CornerRadius and set BackgroundColor. CornerRadius was not working
Set BackgroundColor, CornerRadius Setting is not working.

### Steps to Reproduce

1. Just set CornerRadius and set BackgroundColor in XAML

### Link to public reproduction project repository

_No response_

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13, Android 11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #18807: .NET 8 MAUI Ignores Button.CornerRadius = '0' on Android device
### Description

Buttons with CornerRadius of 0 do not have sharp corners.

### Steps to Reproduce

- Create a new .Net MAUI app targeting .net 8.0
- In MainPage.xaml.cs add a corner radius of 0 to the button
```
<Button
    CornerRadius="0"
    x:Name="CounterBtn"
    Text="Click me" 
    SemanticProperties.Hint="Counts the number of times you click"
    Clicked="OnCounterClicked"
    HorizontalOptions="Fill" />
```
- Look at the button, it should have sharp corners but it doesn't, CornerRadius of 1 has sharper corners.

Windows behaves correctly.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #19421: Button on .NET8 not considering CornerRadius="0"
### Description

On MAUI the Button from Microsoft.Maui.Controls is not considering the CornerRadius when using .NET8 Android.  On .NET7 it seems to work fine.

### Steps to Reproduce

1.) Create sample MAUI App 
2.) Set Button CornerRadius="0" and run on Android Device
3.) CornerRadius is ignored.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13

### Did you find any workaround?

No.

MauiButtonNet8CornerRadius

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by WdeBruin**
## Issue:
Cornerradius was ignored when equal to 0 on Android.

## Reason:
- The ButtonHandler.Android uses extension method UpdateCornerRadius in ButtonExtensions.
- If the platformView.Background is of type BorderDrawable, it calls UpdateBorderDrawable
- In that method it checks on > 0 instead of >= 0
- This is not an issue for iOS, because this > 0 check is only in Android in the specific path that reaches UpdateBorderDrawable.

## Fix:
- Set the check for applying CornerRadius to >= 0 instead of > 0, specifically in this path for Android

### Issues Fixed
Fixes #18807 
Fixes #18090
Fixed #19052 
Fixes #19421

### CODE REVIEW

**Comment by WdeBruin** [comment]
When will this be reviewed? @hartez  @mattleibow

**Review by hartez — DISMISSED** [review]

**Comment by WdeBruin** [comment]
It still needs a device test I suppose, that is in progress

**Comment by jfversluis** [comment]
@WdeBruin feel free to ping me when you get it done!

File: src/Core/src/Platform/Android/ButtonExtensions.cs [hunk 1]
```diff
@@ -96,7 +96,7 @@ internal static void UpdateBorderDrawable(this MaterialButton platformView, IBut
 				if (button.StrokeThickness > 0)
 					mauiDrawable.SetBorderWidth(button.StrokeThickness);
```
Comment (mattleibow) [inline src/Core/src/Platform/Android/ButtonExtensions.cs:97]: Does this also need to be changed? Sure, this PR is not meant for both because of the issue, but maybe both can be fixed at the same time? Not sure if you observed strange things with borders?

If you would like to keep these 2 things separate, the that is good. I'll just create an issue so we don't miss it.

**Review by mattleibow — DISMISSED** [review]
Thanks for the PR.I think I saw this and thought it was the same PR and wondered where my comments went :)

Just marking this as needs changes so we don't merge this too quickly. It is just waiting on your tests. Shout if we made the test code to weird 😆

File: src/Core/src/Platform/Android/ButtonExtensions.cs (hunk 1 above)
Comment (hartez) [reply src/Core/src/Platform/Android/ButtonExtensions.cs:97]: One problem at a time, man.

Comment (WdeBruin) [reply src/Core/src/Platform/Android/ButtonExtensions.cs:97]: I noticed this as well, but didn't find an issue related to it. So I am unsure if strange things happen here, to be checked.

**Comment by WdeBruin** [comment]
Added a test @jfversluis 
Did take some time to figure out the device tests, and get it working. Is there a guide for this?

On the test itself, two things to consider: 
- Using CornerRadius type instead of one integer, so we can check all corners seperately. 
- I use reflection to check the private value _cornerRadius on the Drawable. It is used to draw a Path with vectors, a curve with several small steps (in PathF). The other approach would be to check the vector path with an expected path, but that is difficult to read/understand.

**Review by jfversluis — APPROVED** [review]

**Comment by DawidBester** [comment]
Corner radius fix was working in 8.0.6-nightly.9876, but no longer working in 8.0.6 for Android. 

I thought the github Merged label and the fact that the fix was part of nightly build meant it will be included in the next SR? 

8.0.6-nightly.9876 screenshot

image

8.0.6 Screenshot

image

Code for above: https://github.com/DawidBester/ButtonCornersTest
