### PR TITLE
Blazor Hybrid Android Prevent Repeated Blazor Instantiation

### LINKED ISSUE #5850: Repeatedly going to "/" in MAUI app on Android shows an info/error in the logs
1. Create new MAUI Blazor app in VS Windows
2. Launch in Android emulator
3. Keep clicking the title of the app (e.g. `MauiApp123`) (or go to the hamburger menu and click Home)

In the VS Debug Output window you'll see tons of these messages:

```
[chromium] [INFO:CONSOLE(1)] "Uncaught SyntaxError: Identifier 'channel' has already been declared", source: https://0.0.0.0/ (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught (in promise) Error: Blazor has already started.", source: https://0.0.0.0/_framework/blazor.webview.js (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught SyntaxError: Identifier 'channel' has already been declared", source: https://0.0.0.0/ (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught (in promise) Error: Blazor has already started.", source: https://0.0.0.0/_framework/blazor.webview.js (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught SyntaxError: Identifier 'channel' has already been declared", source: https://0.0.0.0/ (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught (in promise) Error: Blazor has already started.", source: https://0.0.0.0/_framework/blazor.webview.js (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught SyntaxError: Identifier 'channel' has already been declared", source: https://0.0.0.0/ (1)
[chromium] [INFO:CONSOLE(1)] "Uncaught (in promise) Error: Blazor has already started.", source: https://0.0.0.0/_framework/blazor.webview.js (1)
```

So it looks like it's trying to start Blazor every time you navigate to `/` even though we never "left" Blazor. It's important that we re-start Blazor if the BlazorWebView wasn't already running it (e.g. you navigated away, despite our warnings to tell you not to). But perhaps we need to guard against trying to restart it if it's already running.

Note: This does seem harmless, but it also seems wrong. I don't want to pollute the output windows with things that _look_ bad, even if perhaps they are innocuous.

### LINKED ISSUE #6002: Remaining Todo items in Android WebKitWebViewClient
There are a couple of potentially important "todo" comments left in `WebKitWebViewClient.cs`:

```cs
// TODO: How do we know this runs only once?
```

```cs
// TODO: we need to protect against double initialization because the
// OnPageFinished event refires after the app is brought back from the 
// foreground and the webview is brought back into view, without it actually
// getting reloaded.
```

### PR DESCRIPTION
**Pull request by TanayParikh**
Fixes: https://github.com/dotnet/maui/issues/6002
Fixes: https://github.com/dotnet/maui/issues/5850

### CODE REVIEW

File: src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs [hunk 1]
```diff
@@ -177,16 +182,16 @@ protected override void Dispose(bool disposing)
 
 		private class JavaScriptValueCallback : Java.Lang.Object, IValueCallback
 		{
-			private readonly Action _callback;
+			private readonly Action<Java.Lang.Object?> _callback;
 
-			public JavaScriptValueCallback(Action callback!!)
+			public JavaScriptValueCallback(Action<Java.Lang.Object?> callback!!)
```
Comment (TanayParikh) [inline src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs:187]: This is inline with the API:

- https://developer.android.com/reference/android/webkit/WebView?hl=en
- https://developer.android.com/reference/android/webkit/ValueCallback
- https://docs.microsoft.com/en-us/dotnet/api/?view=xamarin-android-sdk-12
- https://docs.microsoft.com/en-us/dotnet/api/android.webkit.ivaluecallback?view=xamarin-android-sdk-12

**Review by Eilon — APPROVED** [review]

File: src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs [hunk 2]
```diff
@@ -107,14 +106,19 @@ public override void OnPageFinished(AWebView? view, string? url)
...
-			// TODO: we need to protect against double initialization because the
-			// OnPageFinished event refires after the app is brought back from the 
-			// foreground and the webview is brought back into view, without it actually
-			// getting reloaded.
-
-
-			// Set up JS ports
+			// Confirm Blazor hasn't already initialized
 			view.EvaluateJavascript(@"
+				(function() { return typeof(window.__BlazorStarted); })();
```
Comment (TanayParikh) [inline src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs:111]: Ideally we'd use the `started` property, but it's lost to minification: 
https://cs.github.com/dotnet/aspnetcore/blob/d4e09edefac2978b114030d55eefde22361accfd/src/Components/Web.JS/src/Boot.WebView.ts?q=Blazor+has+already+started#L12

**Comment by TanayParikh** [comment]
Setting to auto-merge to get this in for RC3, please let me know if anyone has any additional feedback and I'll be happy to address it separately.
