### PR TITLE
[Windows] Implement gestures on Spans

### LINKED ISSUE #4734: Gestures don't work on Label Spans
### Description

I added a gesture to a label span and tapped it. Nothing is happening on Windows. Cannot test Android bc it doesn't render the span.

Platforms:

- [x] Android https://github.com/dotnet/maui/pull/14410
- [x] iOS https://github.com/dotnet/maui/pull/15544
- [x] Mac Catalyst https://github.com/dotnet/maui/pull/15544
- [ ] Windows https://github.com/dotnet/maui/pull/17731

### Steps to Reproduce

Run this:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ControlGallery.Pages.LabelPage"
             Shell.FlyoutBehavior="Disabled"
             >

    <ContentPage.Content>
        <ScrollView>
            <StackLayout Padding="{OnPlatform iOS='30,60,30,30', Default='30'}">

                <Label LineBreakMode="NoWrap" LineHeight="1.4">
                    <Label.FormattedText>
                        <FormattedString>
                            <Span Text="Font name: Default &#10;"/>
                            <Span Text="Version: 1.00  &#10;"/>
                            <Span Text="Digitally Signed, TrueType Outlines &#10;"/>
                            <Span Text="abcdefghijklmnopqrstuvwxyz "/>
                            <Span Text="abcdefghijklmnopqrstuvwxyz &#10;" TextTransform="Uppercase"/>
                            <Span Text="1234567890.:,;'+-*/=  &#10;"/>
                            <Span Text="12 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="12"/>
                            <Span Text="18 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="18"/>
                            <Span Text="24 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="24"/>
                            <Span Text="36 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="36"/>
                            <Span Text="48 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="48"/>
                            <Span Text="60 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="60"/>
                            <Span Text="72 The quick brown fox jumps over the lazy dog. 1234567890 " FontSize="72" >
                                <Span.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding TapCommand}" CommandParameter="https://google.com" />
                                </Span.GestureRecognizers>
                            </Span>
                        </FormattedString>
                    </Label.FormattedText>                    
                </Label>
            </StackLayout>
        </ScrollView>

    </ContentPage.Content>
</ContentPage>
```

```csharp
using System.Windows.Input;

namespace ControlGallery.Pages;

public partial class LabelPage : ContentPage
{
    public ICommand TapCommand => new Command<string>(async (url) => await Launcher.OpenAsync(url));

    public LabelPage()
    {
        InitializeComponent();
        BindingContext = this;
    }
}

```

image

Screenshot_1645061133

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

All

### Did you find any workaround?

No workaround

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Implement gestures on Windows Spans.

### Issues Fixed

 - Fixes #4734

### CODE REVIEW

File: src/Controls/src/Core/Platform/Windows/Extensions/FormattedStringExtensions.cs [hunk 1]
```diff
@@ -127,5 +130,56 @@ public static void UpdateInlines(this TextBlock textBlock, Label label)
...
+			if (labelWidth <= 0 || control.Height <= 0)
+				return;
+
+			for (int i = 0; i < element.FormattedText.Spans.Count; i++)
+			{
+				var span = element.FormattedText.Spans[i];
+
+				var inline = control.Inlines.ElementAt(i);
+
+				// TODO: Alternatives?. GetCharacterRect always return an empty Rect
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Windows/Extensions/FormattedStringExtensions.cs:149]: Here we have the pending key to complete the implementation. We need, as in other platforms, to calculate the bounding box of each Span to have the region that can detect the gesture.

Ideally, the GetCharacterRect method should be able to provide us with the Rect that borders a TextPointer. However, this always returns us an empty Rect.

Comment (jsuarezruiz) [reply src/Controls/src/Core/Platform/Windows/Extensions/FormattedStringExtensions.cs:149]: @PureWeen Could we get feedback from the WinUI Team?

**Comment by samhouts** [comment]
failing checks

File: src/Controls/src/Core/Label/Label.Windows.cs [hunk 2]
```diff
@@ -1,12 +1,44 @@
...
 using Microsoft.Maui.Controls.Platform;
+using Microsoft.UI.Xaml.Controls;
 
 namespace Microsoft.Maui.Controls
 {
 	public partial class Label
 	{
-		public static void MapDetectReadingOrderFromContent(LabelHandler handler, Label label) => MapDetectReadingOrderFromContent((ILabelHandler)handler, label);
-		public static void MapText(LabelHandler handler, Label label) => MapText((ILabelHandler)handler, label);
+		TextBlock _textBlock;
```
Comment (mattleibow) [inline src/Controls/src/Core/Label/Label.Windows.cs:10]: Why use this field? The handler is a `LabelHandler` and is always a `TextBlock`. In fact, `ILabelHandler` is a `TextBlock` too.

File: src/Controls/src/Core/Platform/Windows/Extensions/FormattedStringExtensions.cs (hunk 1 above)
Comment (mattleibow) [reply src/Controls/src/Core/Platform/Windows/Extensions/FormattedStringExtensions.cs:149]: I wonder if this is only set once the label is on screen/loaded/template applied?

**Comment by mattleibow** [comment]
Rebased and did some tests, seems to work locally.

**Review by mattleibow — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]
