### PR TITLE
[Windows] Fix Picker alignment issues

### LINKED ISSUE #6391: Picker width on Windows not filling container
### Description

When placing a Picker control inside a grid, it does not resize to fill the grid cell on Windows like it does on Android.

### Steps to Reproduce

[Maui Picker Width.zip](https://github.com/dotnet/maui/files/8535278/Maui.Picker.Width.zip)
Place a picker control inside a grid -- added backgroundcolors and a margin to show relative sizes.
On Android, it shows the Picker fills the cell; on Windows it shows the Picker as a minimal size inside the larger(blue) cell.
`
    <Grid ColumnDefinitions="*,*,*" RowDefinitions="*,*,*"  >
        <Grid Grid.Column="1" Grid.Row="1"  BackgroundColor="Blue">
        <Picker SelectedItem="Baboon" BackgroundColor="Green" Margin="3">
            <Picker.Items>
                <x:String>Baboon</x:String>
                <x:String>Capuchin Monkey</x:String>
            </Picker.Items>
        </Picker>
        </Grid>
    </Grid>`

picker size android
picker size

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Did you find any workaround?

setting width and height manually

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix Windows Picker alignment issues.

fix-picker-layout

To validate the changes can use the added Picker sample to the .NET MAUI Gallery o the added device tests.
### Issues Fixed

Fixes #6391

### CODE REVIEW

File: src/Controls/src/Core/HandlerImpl/Picker/Picker.cs [hunk 1]
```diff
@@ -7,6 +7,9 @@ public partial class Picker
 		{
 #if IOS
 			[PlatformConfiguration.iOSSpecific.Picker.UpdateModeProperty.PropertyName] = MapUpdateMode,
+#elif WINDOWS
+			[nameof(Picker.HorizontalOptions)] = MapHorizontalOptions,
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/HandlerImpl/Picker/Picker.cs:11]: It is a Draft because I am reviewing why this is necessary in the case of the Picker in Windows.

File: src/Controls/samples/Controls.Sample/Pages/Controls/PickerPage.xaml.cs [hunk 2]
```diff
@@ -112,6 +115,54 @@ void UpdatePickerBindingContext()
...
+					AlignmentPicker.VerticalOptions = LayoutOptions.End;
+					break;
+				case 3:
+					AlignmentPicker.VerticalOptions = LayoutOptions.Fill;
+					break;
+			}
+
+			if (_verticalOptionsIndex == 4)
+				_verticalOptionsIndex = 0;
+		}
```
Comment (mandel-macaque) [inline src/Controls/samples/Controls.Sample/Pages/Controls/PickerPage.xaml.cs:165]: Maybe move the switch to a share method since they are the same?
```suggestion
       static LayoutOptions LayoutFromIndex (int index) => index switch
       {
              0 => LayoutOptions.Start,
              1 => LayoutOptions.Center,
              2 => LayoutOptions.End,
              3 => LayoutOptions.Fill,
              _ => throw new ArgumentOutOfRangeException(nameof(index)),
       }
		void OnUpdateHorizontalOptionsClicked(object sender, EventArgs e)
		{
			AlignmentPicker.HorizontalOptions = LayoutFromIndex (_horizontalOptionsIndex);
			_horizontalOptionsIndex++;

			if (_horizontalOptionsIndex == 4)
				_horizontalOptionsIndex = 0;
		}

		void OnUpdateVerticalOptionsClicked(object sender, EventArgs e)
		{
			_verticalOptionsIndex++;
			AlignmentPicker.VerticalOptions =  LayoutFromIndex (_verticalOptionsIndex);
			
			if (_verticalOptionsIndex == 4)
				_verticalOptionsIndex = 0;
		}
```

Also I have noticed that the ++ on the _horizontal index is after the switch, and the vertical one before the switch, is this intended? Cause it looks to me that before the switch is not what we want, but I might be mistaken.

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

File: src/Controls/samples/Controls.Sample/Pages/Controls/PickerPage.xaml.cs (hunk 2 above)
Comment (jsuarezruiz) [reply src/Controls/samples/Controls.Sample/Pages/Controls/PickerPage.xaml.cs]: Created a shared method and fixed a mistake.

File: src/Controls/samples/Controls.Sample/Pages/Controls/PickerPage.xaml.cs [hunk 3]
```diff
@@ -112,6 +115,42 @@ void UpdatePickerBindingContext()
...
+
+		void OnUpdateVerticalOptionsClicked(object sender, EventArgs e)
+		{
+			AlignmentPicker.VerticalOptions = GetLayoutOptions(_verticalOptionsIndex);
+
+			_verticalOptionsIndex++;
+
+			if (_verticalOptionsIndex == 4)
+				_verticalOptionsIndex = 0;
+		}
```
Comment (mandel-macaque) [inline src/Controls/samples/Controls.Sample/Pages/Controls/PickerPage.xaml.cs:137]: We can improve things an little more with a method that doe the logic to update an index via a ref parameter:

```suggestion
       void UpdateIndex (ref int index) {
           index++;
           if (index == 4)
               index = 0;
       }
       
		void OnUpdateHorizontalOptionsClicked(object sender, EventArgs e)
		{
			AlignmentPicker.HorizontalOptions = GetLayoutOptions(_horizontalOptionsIndex);
            UpdateIndex(_horizontalOptionsIndex);
		}

		void OnUpdateVerticalOptionsClicked(object sender, EventArgs e)
		{
			AlignmentPicker.VerticalOptions = GetLayoutOptions(_verticalOptionsIndex);
			UpdateIndex(_verticalOptionsIndex);
		}
```

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

File: src/Controls/samples/Controls.Sample/Pages/Controls/PickerPage.xaml.cs (hunk 3 above)
Comment (mandel-macaque) [reply src/Controls/samples/Controls.Sample/Pages/Controls/PickerPage.xaml.cs:137]: Github, thanks for messing the indentation...

**Review by mandel-macaque — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]

**Comment by Inrego** [comment]
The same issue seems to apply to DatePicker and TimePicker

**Comment by HelenMamalaki** [comment]
Setting HorizontalOptions on a Picker doesn't make it FillandExpand - it just stays the normal size it is - the Issue  #6391 has been marked as Closed due to this commit - so there is no MAUI issue to follow for updates. Am I missing something?
image
