### PR TITLE
MauiScrollView resets ContentOffset on first layout pass - fix

### LINKED ISSUE #30147: MauiScrollView resets ContentOffset on first layout pass in 9.0.80
### Description

https://github.com/dotnet/maui/pull/29469 made a change to the MauiScrollView on iOS that results in the X ContentOffset being set to zero the first time LayoutSubviews is called when the layout orientation is Left-to-Right. It looks like a subsequent PR (https://github.com/dotnet/maui/pull/29735) tried to address some issues caused by the first PR by fixing the Y ContentOffset, but the X ContentOffset still gets reset to 0.

I have a custom view that uses the MauiScrollView for horizontal scrolling, and this change causes issues when I try to set an initial X Scroll value.

I am not sure of the reason for setting the ContentOffset when the layout is Left-To-Right. If it must be reset, then _previousEffectiveUserInterfaceLayoutDirection should probably be initialized to EffectiveUserInterfaceLayoutDirection when MauiScrollView is created (before LayoutSubviews is called).

### Steps to Reproduce

If you look at MauiScrollView.LayoutSubviews, you can see that _previousEffectiveUserInterfaceLayoutDirection is not initialized, resulting in ContentOffset being reset the first time LayoutSubviews is called.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.80 SR8

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.70 SR7

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

No

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Description of Change

@mjo151 could you please verify if this PR fixes your issue, since you did not provide your repro so that I can test it
https://github.com/dotnet/maui/wiki/Testing-PR-Builds

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/30147

### CODE REVIEW

File: src/Core/src/Platform/iOS/MauiScrollView.cs [hunk 1]
```diff
@@ -64,7 +64,7 @@ public override void LayoutSubviews()
 						crossPlatformLayout.CrossPlatformArrange(new Rect(new Point(-horizontalOffset, 0), crossPlatformBounds));
 						ContentOffset = new CGPoint(horizontalOffset, 0);
 					}
-					else
+					else if (_previousEffectiveUserInterfaceLayoutDirection is not null)
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/MauiScrollView.cs]: @mjo151 If you try this, could you share a repro sample? Would like to include a related test.

Comment (mjo151) [reply src/Core/src/Platform/iOS/MauiScrollView.cs]: I tested the build from this PR and it appears to fix the issue. I will see if I can create a simple repo sample.

**Review by rmarinho — APPROVED** [review]

**Comment by rmarinho** [comment]
@PureWeen  do we want to backdoor this one?

**Comment by PureWeen** [comment]
- failing tests unrelated

**Comment by PureWeen** [comment]
> @PureWeen do we want to backdoor this one?

AFAICT the scenario is a bit edge case that regressed
So we'll just make sure to get it in SR9 and not risk backporting
