### PR TITLE
[Testing] Fix flaky ShapeUpdatesBrushCorrectly test

### LINKED ISSUE #18991: [testing] The test ShapeUpdatesBrushCorrectly sometimes fails on iOS
### Description

Sometimes this test is failing in different versions from 16.4, 15.4 or 14.5 . Some links below
rerun normally makes it work

Shape Updates brush Correctly(color: 4278190335)

https://dev.azure.com/xamarin/public/_build/results?buildId=102149&view=ms.vss-test-web.build-test-results-tab&runId=2324367&resultId=100075&paneView=debug

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8721527&view=ms.vss-test-web.build-test-results-tab&runId=89221709&resultId=100049&paneView=debug

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell
Assert.NotNull() Failure: Value is null
```

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Changes in a test to avoid intermittent fails.

### Issues Fixed

- Fixes https://github.com/dotnet/maui/issues/18991

### CODE REVIEW

File: src/Controls/tests/DeviceTests/Elements/Shape/ShapeTests.cs [hunk 1]
```diff
@@ -73,8 +74,10 @@ public async Task ShapeUpdatesBrushCorrectly(uint color)
 
 			await InvokeOnMainThreadAsync(async () =>
 			{
-				await CreateHandlerAndAddToWindow<LineHandler>(line, (handler) =>
+				await CreateHandlerAndAddToWindow<LineHandler>(line, async (handler) =>
 				{
+					await Task.Delay(100);
```
Comment (PureWeen) [inline src/Controls/tests/DeviceTests/Elements/Shape/ShapeTests.cs:79]: Can we somehow use AssertionExtentions.Wait?

**Review by PureWeen — DISMISSED** [review]

File: src/Controls/tests/DeviceTests/Elements/Shape/ShapeTests.cs (hunk 1 above)
Comment (rmarinho) [reply src/Controls/tests/DeviceTests/Elements/Shape/ShapeTests.cs:79]: Let+s just copy and have the duplicate code for now?

Comment (jsuarezruiz) [reply src/Controls/tests/DeviceTests/Elements/Shape/ShapeTests.cs]: Applied changes to use `AssertionExtensions.Wait`

**Review by rmarinho — APPROVED** [review]
