### PR TITLE
[iOS] Fix Flyout icon visibility when popping page using PopAsync or PopToRootAsync

### LINKED ISSUE #21828: Flyout Button Disappears
### Description

The flyout button disappears on iOS if you navigate backward to a new root page.

Basically, this will cause the flyout button to disappear:
```cs
_navigationPage.Navigation.InsertPageBefore(new ContentPage(), _currentRootPage);
await _navigationPage.Navigation.PopAsync();
```

### Steps to Reproduce

1. Checkout the public reproduction project repository below
1. Open the MauiBugs.sln and run the FlyoutBug.csproj on iOS
2. Click the "Demo Bug" button
3. Observe that the flyout button is missing

### Link to public reproduction project repository

https://github.com/AceCoderLaura/MauiBugs

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.8.2

### Did you find any workaround?

None currently, but working on it and will post here if I find one.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Vignesh-SF3580**
### Issue Detail
When the user inserts a page before the root and then pops the current page using PopAsync (or pops to root using PopToRootAsync), the flyout hamburger icon is not visible on iOS after the navigation completes.

### Root Cause
UpdateLeftBarButtonItem (which sets the flyout hamburger icon on the ParentingViewController) was only called in the RemovePage method. The programmatic pop paths — OnPopViewAsync, OnPopToRoot, and the native-swipe-back path via UpdateFormsInnerNavigation — did not call it. After a pop that results in a new root page, the flyout button was never refreshed.

### Description of Change
Extracted the flyout-button-refresh logic from RemovePage into a new private helper:

```
void UpdateFlyoutMenuButton(Page pageBeingRemoved = null)
{
    var parentingViewController = GetParentingViewController();
    parentingViewController?.UpdateLeftBarButtonItem(pageBeingRemoved);
}
```
Then called UpdateFlyoutMenuButton() at the end of:

- OnPopViewAsync — programmatic PopAsync()
- OnPopToRoot — programmatic PopToRootAsync()
- UpdateFormsInnerNavigation — native back-button (swipe) pop

RemovePage was refactored to use the same helper (no behavior change).

**File changed:** src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs

**Reference:** https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs#L693

### Tested the behavior in the following platforms
 
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Issues Fixed
 
Fixes https://github.com/dotnet/maui/issues/21828

### Screenshots

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="300" height="600"  src="https://github.com/user-attachments/assets/7afc9d80-3d98-4f73-a124-dcc06c5e6d1c"> | <video width="300" height="600"  src="https://github.com/user-attachments/assets/7d59f508-9760-44bb-9889-4bd4fcca9353">) |

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs [hunk 1]
```diff
@@ -111,8 +111,7 @@ public override void DidRotate(UIInterfaceOrientation fromInterfaceOrientation)
 
 			View.SetNeedsLayout();
 
-			var parentingViewController = GetParentingViewController();
-			parentingViewController?.UpdateLeftBarButtonItem();
+			UpdateFlyoutMenuButton();
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs]: .NET MAUI supports iOS 12.2 or higher is required, and this  is not called in 9.0+. Should not be necessary.

Comment (Vignesh-SF3580) [reply src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs]: @jsuarezruiz I’ve made the changes based on your suggestions. Let me know if you have any further feedback.

**Comment by kubaflo** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>added ios26 snap.</strong> · <a href="https://github.com/dotnet/maui/commit/d87e60be1c62262d55763321137fe51091b943d8"><code>d87e60b</code></a></summary>

---

**Issue:** #21828 - Flyout Button Disappears after InsertPageBefore + PopAsync
**PR:** #29779 - [iOS] Fix Flyout icon visibility when popping page using PopAsync or PopToRootAsync
**Platforms Affected:** iOS (primary), MacCatalyst (secondary)
**Labels:** platform/ios, area-controls-flyout, community ✨, partner/syncfusion

### Issue Summary

On iOS, when navigating back to a new root page using `InsertPageBefore` + `PopAsync`, the flyout hamburger button disappears from the navigation bar. This is a regression from Xamarin.Forms. The issue affects iOS 12+ (and MacCatalyst), but NOT Android or Windows.

**Root Cause (from PR):** The `RemovePage` method was calling `UpdateLeftBarButtonItem` to refresh the flyout icon, but the pop operations (`OnPopViewAsync`, `OnPopToRoot`, and `UpdateFormsInnerNavigation`) did not have equivalent calls.

### Fix Approach (PR)

The PR introduces a helper method `UpdateFlyoutMenuButton(Page pageBeingRemoved = null)` in `NavigationRenderer.cs` that wraps:
```csharp
var parentingViewController = GetParentingViewController();
parentingViewController?.UpdateLeftBarButtonItem(pageBeingRemoved);
```

This method is then called:
1. In `OnPopToRoot` after `UpdateToolBarVisible()`
2. In `OnPopViewAsync` after `UpdateToolBarVisible()`
3. In `UpdateFormsInnerNavigation` after removing the page
4. Refactored in `RemovePage` to use the new helper (DRY improvement)

### Files Changed

**Fix Files:** 1 implementation file
- `src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs` (+11, -2)

**Test Files:** 2 test files + 4 snapshot PNGs
- `src/Controls/tests/TestCases.HostApp/Issues/Issue21828.cs` (+64, new)
- `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21828.cs` (+23, new)
- Snapshots for android, ios, ios-26, mac, windows

### Reviewer Feedback

| File:Line | Reviewer Says | Author Says | Status |
|-----------|---------------|-------------|--------|
| NavigationRenderer.cs:114 | Copilot: Add inline comment for `UpdateFlyoutMenuButton` | Author applied changes | ✅ Applied |
| NavigationRenderer.cs:114 | jsuarezruiz: iOS 12.2+ is required, comment about deprecated method not needed | Author applied changes | ✅ Applied |

### Prior Agent Reviews
None found.

### Edge Cases (from issue comments)
- Workaround found: Setting `Flyout.IconImageSource` to a new ImageSource re-renders the button (user workaround)
- Verified: Bug reproduces on iOS 17.2 and MacCatalyst, NOT on Android 14 or Windows 11

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #29779 | Add `UpdateFlyoutMenuButton()` helper, call after pop operations in NavigationRenderer | ⏳ PENDING (Gate) | `NavigationRenderer.cs` (+11, -2) | Original PR |

</details>

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>added ios26 snap.</strong> · <a href="https://github.com/dotnet/maui/commit/d87e60be1c62262d55763321137fe51091b943d8"><code>d87e60b</code></a></summary>

---

**Result:** ✅ PASSED
**Platform:** ios
**Mode:** Full Verification

- Tests FAIL without fix ✅
- Tests PASS with fix ✅

**Test Filter:** Issue21828
**Base Branch:** main
**Merge Base:** 2f22928c

**Fix Files Detected:**
- `src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs`

**Details:**
- Run 1 (WITHOUT fix): Tests FAILED as expected (bug is present)
- Run 2 (WITH fix): Tests PASSED as expected (fix works correctly)

</details>

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>added ios26 snap.</strong> · <a href="https://github.com/dotnet/maui/commit/d87e60be1c62262d55763321137fe51091b943d8"><code>d87e60b</code></a></summary>

---

### Fix Candidates

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #29779 | New `UpdateFlyoutMenuButton()` helper called from `OnPopToRoot`, `OnPopViewAsync`, `UpdateFormsInnerNavigation`; refactors `RemovePage` | ✅ PASS (Gate) | `NavigationRenderer.cs` (+11, -2) | Original PR |
| 1 | try-fix | `pvc.UpdateLeftBarButtonItem()` in `MauiNavigationDelegate.DidShowViewController` | ✅ PASS | `NavigationRenderer.cs` (+1) | Most minimal; fires on push too (benign) |
| 2 | try-fix | `UpdateLeftBarButtonItem()` in `ParentingViewController.ViewWillAppear` | ✅ PASS | `NavigationRenderer.cs` (+6) | iOS lifecycle pattern; fires on any VC appear |
| 3 | try-fix | Update new top VC inside `ParentingViewController.Disconnect()` | ✅ PASS | `NavigationRenderer.cs` (+10) | Teardown-side fix; slightly indirect |
| 4 | try-fix | `pvc.UpdateLeftBarButtonItem()` in `MauiNavigationDelegate.WillShowViewController` | ✅ PASS | `NavigationRenderer.cs` (+3) | Pre-show delegate; similar to Attempt 1 |
| 5 | try-fix | `UpdateLeftBarButtonItem()` in `DidPopItem` delegate method | ✅ PASS | `NavigationRenderer.cs` (+1) | Native bar delegate hook; clean single-line |
| 6 | try-fix | Proactive pre-config of LeftBarButtonItem in `InsertPageBefore` by cloning existing button | ✅ PASS | `NavigationRenderer.cs` (+33, -1) | Complex; only covers InsertPageBefore→Pop pattern |
| 7 | try-fix | `LeftItemsSupplementBackButton = true` persistent button approach | ❌ FAIL | `NavigationRenderer.cs` | Compile error (test infra baseline issue; approach untestable) |
| 8 | try-fix | Override `PopViewController`/`PopToRootViewController` to call `UpdateLeftBarButtonItem()` | ❌ FAIL | `NavigationRenderer.cs` | 0.77% screenshot diff - timing issue, update fires before UIKit finishes |
| 9 | try-fix | Override `ViewDidLayoutSubviews()` in `NavigationRenderer` | ✅ PASS | `NavigationRenderer.cs` (+6), `PublicAPI.Unshipped.txt` (+1) | Requires public API change; called too frequently |

### Cross-Pollination Summary

| Round | Model | Response |
|-------|-------|----------|
| Round 1 | claude-sonnet-4.6 | NO NEW IDEAS |
| Round 1 | claude-opus-4.6 | NEW IDEA: proactive InsertPageBefore config → became Attempt 6 |
| Round 1 | gpt-5.2 | NEW IDEA: override PopViewController → became Attempt 8 |
| Round 1 | gpt-5.3-codex | NEW IDEA: LeftItemsSupplementBackButton → became Attempt 7 |
| Round 1 | gemini-3-pro-preview | NEW IDEA: ViewDidLayoutSubviews override → became Attempt 9 |
| Round 2 | claude-sonnet-4.6 | NEW IDEA: KVO on UINavigationBar.topItem (complex/fragile - not pursued) |
| Round 2 | claude-opus-4.6 | NEW IDEA: override setViewControllers (similar to failed Attempt 8 timing-wise - not pursued) |
| Round 2 | gpt-5.2 | NEW IDEA: KVO-based observer on navigation bar (complex/fragile - not pursued) |
| Round 2 | gpt-5.3-codex | NEW IDEA: "dirty" flag + full UINavigationItem rebuild (more complex - not pursued) |
| Round 2 | gemini-3-pro-preview | NEW IDEA: Subscribe to NavigationPage.Popped in PhoneFlyoutPageRenderer (different class - not pursued) |

**Exhausted:** Yes (remaining ideas are all more complex and architecturally riskier than existing passing solutions)

### Selection Analysis

**PR's fix is the best approach** because:
1. **Targeted**: Only adds update calls precisely at the three pop-operation paths that were missing them
2. **DRY refactoring**: Consolidates the `GetParentingViewController()?.UpdateLeftBarButtonItem()` pattern into a reusable helper, improving `RemovePage` too
3. **No unnecessary side effects**: Unlike Attempt 1/2 (fire on push/any-appear) or Attempt 9 (fires every layout pass)
4. **No public API changes**: Unlike Attempt 9 which requires `PublicAPI.Unshipped.txt` modification
5. **Explicit and self-documenting**: Clear intent from the call sites about why the update is needed

**Attempt 1** (`DidShowViewController` +1 line) is the best **alternative** - minimal and elegant - but the PR's fix is more precise and the reviewer (jsuarezruiz) has already approved the approach direction.

**Selected Fix:** PR's fix — most targeted, no side effects, follows existing code patterns, already validated by Gate and reviewer feedback

</details>

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>added ios26 snap.</strong> · <a href="https://github.com/dotnet/maui/commit/d87e60be1c62262d55763321137fe51091b943d8"><code>d87e60b</code></a></summary>

---

## ✅ Final Recommendation: APPROVE

### Summary

PR #29779 fixes a regression where the flyout hamburger button disappears on iOS when navigating back to a new root page via `InsertPageBefore` + `PopAsync`. The fix is clean, targeted, and correctly patterns after the existing `RemovePage` behavior. Tests were verified: FAIL without fix, PASS with fix. The agent explored 9 independent alternative fixes and could not find a clearly better approach — the PR's fix is the most explicit and targeted solution.

### Root Cause

In `NavigationRenderer.cs` (iOS), the `RemovePage` method already called `GetParentingViewController()?.UpdateLeftBarButtonItem()` to refresh the flyout icon after stack mutations. However, three pop-related paths were missing equivalent calls:

1. `OnPopViewAsync` — handles `PopAsync()`
2. `OnPopToRoot` — handles `PopToRootAsync()`
3. `UpdateFormsInnerNavigation` — handles UI-initiated pops (back button gestures)

When `InsertPageBefore(newPage, currentRoot)` + `PopAsync()` is called, the inserted page becomes root, but the flyout button update was never triggered — leaving the icon missing.

### Fix Quality

**Approach:** The PR introduces a private `UpdateFlyoutMenuButton(Page pageBeingRemoved = null)` helper that wraps the pattern, then calls it from all three missing pop paths. It also refactors `RemovePage` to use this helper (DRY improvement).

**Assessment:** ✅ Excellent — minimal, targeted, and follows existing code conventions.

### Code Review

**✅ Looks Good:**
- Helper method `UpdateFlyoutMenuButton` correctly abstracts the `GetParentingViewController()?.UpdateLeftBarButtonItem(pageBeingRemoved)` pattern
- All three missing call sites are covered: `OnPopToRoot`, `OnPopViewAsync`, `UpdateFormsInnerNavigation`
- `RemovePage` refactored to use the helper — consistent and DRY
- Test host app uses C# (preferred) with descriptive `AutomationId` values
- Test uses `UITestCategories.FlyoutPage` category — appropriate
- Test correctly covers the exact reproduction pattern from the issue

**🟡 Minor Issues (non-blocking):**
- `Issue21828.cs` (Shared.Tests) is missing a trailing newline at end of file
- The NOTE block is missing from the PR description (see Title & Description section below)
- `[Issue]` attribute has `PlatformAffected.iOS` — technically correct (this is an iOS NavigationRenderer) but the issue was also verified on MacCatalyst; acceptable as-is since the fix is in iOS-specific code

**No critical issues found.**

### Try-Fix Exploration

The agent ran 9 alternative fix approaches. 7 passed, 2 failed:

| # | Approach | Result | Verdict |
|---|----------|--------|---------|
| 1 | `pvc.UpdateLeftBarButtonItem()` in `DidShowViewController` (+1 line) | ✅ PASS | Elegant but fires on push too |
| 2 | `UpdateLeftBarButtonItem()` in `ParentingViewController.ViewWillAppear` | ✅ PASS | Fires on any appear, not just pop |
| 3 | Update new top VC in `ParentingViewController.Disconnect()` | ✅ PASS | Teardown-side, slightly indirect |
| 4 | `pvc.UpdateLeftBarButtonItem()` in `WillShowViewController` | ✅ PASS | Similar to #1 (pre-show) |
| 5 | `UpdateLeftBarButtonItem()` in `DidPopItem` | ✅ PASS | Bar delegate hook, clean |
| 6 | Proactive clone of button in `InsertPageBefore` | ✅ PASS | Only covers this one pattern |
| 7 | `LeftItemsSupplementBackButton = true` | ❌ FAIL | Compile error (test infra issue) |
| 8 | Override `PopViewController`/`PopToRootViewController` | ❌ FAIL | 0.77% screenshot diff — timing too early |
| 9 | Override `ViewDidLayoutSubviews()` | ✅ PASS | Requires public API entry — unnecessary overhead |

**Selected Fix:** PR's fix — most targeted, explicit, no side effects, follows existing pattern, no public API changes.

### Title & Description Review

**Title:** `[iOS] Fix Flyout icon visibility when popping page using PopAsync or PopToRootAsync`
**Assessment:** ✅ Accurate and descriptive. Acceptable.

**Description:** Has good structure (Issue Detail, Root Cause, Description of Change, platforms tested, screenshots).
**Required addition:** The NOTE block is missing at the top. Add:

```markdown
<!-- Please let the below note in for people that find this PR -->
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!
```

### Gate Result

- ✅ Tests FAIL without fix (bug confirmed)  
- ✅ Tests PASS with fix (fix confirmed)  
- Platform: iOS | Filter: Issue21828

</details>

</details>

---

</details>

**Comment by kubaflo** [comment]
## 📋 PR Finalization Review


<details>

<summary><b>Title: ✅ Good</b></summary>

<br>

**Current:** `[iOS] Fix Flyout icon visibility when popping page using PopAsync or PopToRootAsync`
</details>

<details>

<summary><b>Description: ✅ Good</b></summary>

<br>

Description needs updates. See details below.
### ✨ Suggested PR Description


> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue Detail

When the user inserts a page before the root and then pops the current page using `PopAsync` (or pops to root using `PopToRootAsync`), the flyout hamburger icon is not visible on iOS after the navigation completes.

### Root Cause

`UpdateLeftBarButtonItem` (which sets the flyout hamburger icon on the `ParentingViewController`) was only called in the `RemovePage` method. The programmatic pop paths — `OnPopViewAsync`, `OnPopToRoot`, and the native-swipe-back path via `UpdateFormsInnerNavigation` — did not call it. After a pop that results in a new root page, the flyout button was never refreshed.

### Description of Change

Extracted the flyout-button-refresh logic from `RemovePage` into a new private helper:

```csharp
void UpdateFlyoutMenuButton(Page pageBeingRemoved = null)
{
    var parentingViewController = GetParentingViewController();
    parentingViewController?.UpdateLeftBarButtonItem(pageBeingRemoved);
}
```

Then called `UpdateFlyoutMenuButton()` at the end of:
- `OnPopViewAsync` — programmatic `PopAsync()`
- `OnPopToRoot` — programmatic `PopToRootAsync()`
- `UpdateFormsInnerNavigation` — native back-button (swipe) pop

`RemovePage` was refactored to use the same helper (no behavior change).

**File changed:** `src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs`

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/21828

### Tested the behavior in the following platforms

- [x] iOS ✅ (primary fix platform)
- [x] Mac ✅ (MacCatalyst shares iOS NavigationRenderer)
- [x] Android (UI test snapshot added; fix code is iOS-specific)
- [x] Windows (UI test snapshot added; fix code is iOS-specific)

### Screenshots

| Before Issue Fix | After Issue Fix |
|----------|----------|
| *(Flyout icon missing)* | *(Flyout icon visible — see snapshot in `TestCases.iOS.Tests/snapshots/ios/FlyoutIconRemainsVisible.png`)* |
</details>

<details>

<summary><b>Code Review: ⚠️ Issues Found</b></summary>

<br>

# Code Review — PR #29779

**File reviewed:** `src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs`  
**Test files reviewed:** `Issue21828.cs` (HostApp + Shared.Tests)

---

## ✅ Looks Good

- **Clean abstraction** — Extracting the flyout-button logic into `UpdateFlyoutMenuButton()` is a textbook refactor: reduces duplication, makes the intent explicit, and makes future call sites easier to add.
- **Consistent default parameter** — `Page pageBeingRemoved = null` mirrors the pattern already used in `UpdateLeftBarButtonItem`, making the helper easy to call in contexts where no page is explicitly removed (e.g. pop operations).
- **`RemovePage` refactor is safe** — The call `UpdateFlyoutMenuButton(page)` passes the removed page through, matching the original two-liner behavior exactly.
- **Test coverage** — A UI test (`FlyoutIconRemainsVisible`) covers the exact reported repro scenario (`InsertPageBefore` + `PopAsync`). Snapshots added for iOS (both `ios` and `ios-26` environments), Mac, Android, and Windows.
- **`[Category(UITestCategories.FlyoutPage)]`** is appropriate for this test.

---

## 🟡 Suggestions

### 1. `UpdateFormsInnerNavigation`: call placement could cause double-update

**Context:**  
`UpdateFormsInnerNavigation` is the handler for native (swipe) back-button pops. The new `UpdateFlyoutMenuButton()` call is placed inside the `if (Element.Navigation.NavigationStack.Contains(pageBeingRemoved))` block:

```csharp
if (Element.Navigation.NavigationStack.Contains(pageBeingRemoved))
{
    await (NavPage as INavigationPageController)?.RemoveAsyncInner(pageBeingRemoved, false, true);
    UpdateFlyoutMenuButton();   // <-- added here
    ...
}
```

However, the native swipe-back also triggers `OnPopViewAsync` (which now also calls `UpdateFlyoutMenuButton()`). Whether `UpdateFormsInnerNavigation` is called depends on `_ignorePopCall`. The guard at line 1018–1019 (`if (_ignorePopCall) return;`) prevents this from running during programmatic pops, so for swipe pops only `UpdateFormsInnerNavigation` is called. For programmatic pops only `OnPopViewAsync`/`OnPopToRoot` fire. There is **no double-call risk** in normal flows.

**Verdict:** No bug — just worth noting for reviewers who might wonder about double-calls.

### 2. Missing newline at end of test file

**File:** `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21828.cs`  
The diff ends with `\ No newline at end of file`. This is a style nit but is inconsistent with other test files in the repository.

**Recommendation:** Add a newline at the end of the file.

### 3. HostApp `[Issue]` attribute lists `PlatformAffected.iOS` but test runs on all platforms

```csharp
[Issue(IssueTracker.Github, 21828, "...", PlatformAffected.iOS)]
```

The bug is iOS-specific, so `PlatformAffected.iOS` is correct for the *issue*. However, the UI test runs (and has snapshots) on Android, Windows, and Mac as well. This is not a bug — the `PlatformAffected` attribute describes the bug's affected platform, not the test's run scope — but it may surprise maintainers who see snapshots for Android/Windows. No change needed, just worth noting.

---

## 🔴 Critical Issues

None.

---

## Summary

| Severity | Count | Notes |
|----------|-------|-------|
| 🔴 Critical | 0 | — |
| 🟡 Suggestion | 2 | Missing newline; double-call analysis (no bug) |
| ✅ Good | 4 | Clean refactor, good tests, correct use of default parameter |
</details>

**Comment by Vignesh-SF3580** [comment]
> ## 📋 PR Finalization Review
> Title: ✅ Good
> 
> **Current:** `[iOS] Fix Flyout icon visibility when popping page using PopAsync or PopToRootAsync`
> 
> Description: ✅ Good
> 
> Description needs updates. See details below.
> 
> ### ✨ Suggested PR Description
> > [!NOTE]
> > Are you waiting for the changes in this PR to be merged?
> > It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!
> 
> ### Issue Detail
> When the user inserts a page before the root and then pops the current page using `PopAsync` (or pops to root using `PopToRootAsync`), the flyout hamburger icon is not visible on iOS after the navigation completes.
> 
> ### Root Cause
> `UpdateLeftBarButtonItem` (which sets the flyout hamburger icon on the `ParentingViewController`) was only called in the `RemovePage` method. The programmatic pop paths — `OnPopViewAsync`, `OnPopToRoot`, and the native-swipe-back path via `UpdateFormsInnerNavigation` — did not call it. After a pop that results in a new root page, the flyout button was never refreshed.
> 
> ### Description of Change
> Extracted the flyout-button-refresh logic from `RemovePage` into a new private helper:
> 
> ```cs
> void UpdateFlyoutMenuButton(Page pageBeingRemoved = null)
> {
>     var parentingViewController = GetParentingViewController();
>     parentingViewController?.UpdateLeftBarButtonItem(pageBeingRemoved);
> }
> ```
> 
> Then called `UpdateFlyoutMenuButton()` at the end of:
> 
> * `OnPopViewAsync` — programmatic `PopAsync()`
> * `OnPopToRoot` — programmatic `PopToRootAsync()`
> * `UpdateFormsInnerNavigation` — native back-button (swipe) pop
> 
> `RemovePage` was refactored to use the same helper (no behavior change).
> 
> **File changed:** `src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs`
> 
> ### Issues Fixed
> Fixes #21828
> 
> ### Tested the behavior in the following platforms
> * [x]  iOS ✅ (primary fix platform)
> * [x]  Mac ✅ (MacCatalyst shares iOS NavigationRenderer)
> * [x]  Android (UI test snapshot added; fix code is iOS-specific)
> * [x]  Windows (UI test snapshot added; fix code is iOS-specific)
> 
> ### Screenshots
> Before Issue Fix	After Issue Fix
> _(Flyout icon missing)_	_(Flyout icon visible — see snapshot in `TestCases.iOS.Tests/snapshots/ios/FlyoutIconRemainsVisible.png`)_
> Code Review: ⚠️ Issues Found

There are no major concerns in the AI summary.

**Review by kubaflo — APPROVED** [review]
