### PR TITLE
[iOS] Fix memory leak in CarouselViewHandler2

### LINKED ISSUE #29677: CarouselViewHandler2 causes a memory leak
### Description

While enabling memory tests for CV2 here #29638, I discovered that CarouselViewHandler2 is leaking. This issue does not appear to be caused by the same problem as the one we are trying to fix here #29638 

To test this check the changes i made in #29638 in `MemoryTest.cs`

Image

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by bhavanesh2001**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Description of Change

`CarouselViewHandler2` sets a `VisibleItemsInvalidationHandler` on the `NSCollectionLayoutSection` during layout construction. This handler captures strong references to `VirtualView` and `Controller`, causing a memory leak.

Updated the handler to use WeakReference's. Moved Layout creation to `LayoutFacotry`

<table>
  <tr>
<th>Befor fix</th>
<th>After fix</th>
</tr>
<tr>
<td>

Image

</td>
<td>

Screenshot 2025-05-29 at 12 56 59 AM

</td>
</tr>
</table>

### Issues Fixed

Fixes #29677

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs [hunk 1]
```diff
@@ -261,6 +263,134 @@ public static UICollectionViewLayout CreateHorizontalGrid(GridItemsLayout gridIt
 			gridItemsLayout.Span);
 
 
+#nullable disable
```
Comment (bhavanesh2001) [inline src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs:266]: Added #nullable disable locally to CreateCarouselLayout since it reuses logic from `CarouselViewHandler2.ios.cs`, where nullability is disabled at the file level. Didn’t want to apply it across all of `LayoutFactory2`, so just scoped it here.
 My brain doesn’t have any brighter ideas than this.

**Review by rmarinho — DISMISSED** [review]

**Review by rmarinho — DISMISSED** [review]

**Comment by sheiksyedm** [comment]
The CarouselView tests failed on CI due to the changes introduced by this PR. Setting the FlowDirection to either LeftToRight or RightToLeft on CarouselView is now failing.
https://dev.azure.com/xamarin/public/_build/results?buildId=143228&view=ms.vss-test-web.build-test-results-tab
fyi: @bhavanesh2001

**Comment by bhavanesh2001** [comment]
@sheiksyedm  Thanks for letting me know.  #29784 should fix the failures
