### PR TITLE
[ios/catalyst] fix memory leaks in ListView

### LINKED ISSUE #20025: ListView is not currently being Garbage Collected
### Description

Breaking out remaining work for: https://github.com/dotnet/maui/issues/18365

Add tests to ensure that ListView is GC'd.

### Link to public reproduction project repository

https://github.com/heyThorsten/GCTest

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Fixes: https://github.com/dotnet/maui/issues/20025

I could reproduce the leak here, pretty easily with changes to `MemoryTests`.

`ListView` has several cycles that prevent garbage collection from happening:

* `FormsUITableViewController` has `ListView _list`
  * `FormsUITableViewController` -> `ListView` -> `ListViewRenderer` -> `FormsUITableViewController`

* `ListViewDataSource` has `UITableView _uiTableView`
  * `ListViewDataSource` -> `UITableView` -> `ListViewDataSource`

* `ListViewDataSource` has `FormsUITableViewController _uiTableViewController`
  * `ListViewDataSource` -> `FormsUITableViewController` -> `UITableView` -> `ListViewDataSource`

* `ListViewDataSource` has `protected ListView List`
  * `ListViewDataSource` -> `ListView` -> `ListViewRenderer` -> `FormsUITableViewController` -> `UITableView` -> `ListViewDataSource`

I changed the above fields to all be `WeakReference<T>` and the leaks went away.

### CODE REVIEW

File: src/Controls/tests/DeviceTests/Memory/MemoryTests.cs [hunk 1]
```diff
@@ -78,6 +79,7 @@ void SetupBuilder()
 	[InlineData(typeof(ImageButton))]
 	[InlineData(typeof(IndicatorView))]
 	[InlineData(typeof(Label))]
+	[InlineData(typeof(ListView))]
```
Comment (jonathanpeppers) [inline src/Controls/tests/DeviceTests/Memory/MemoryTests.cs:82]: I think this new test fails on Android, so will investigate.

**Review by rmarinho — APPROVED** [review]
