### PR TITLE
[Windows] Avoid Carousel changes the current position when window is resized

### LINKED ISSUE #22000: [Windows] Carousel changes the current position when window is resized
### Description

On Windows while resizing the window, the carousel changes the current position

### Steps to Reproduce

1. (Windows) Add a carousel with some images in it.
2. Resize the window
3. The carousel changes the current position while resizing.
Expected behavior: The carousel should keep the same item displayed while resizing.

### Link to public reproduction project repository

https://github.com/flesarradu/CarouselImageTest

### Version with bug

8.0.14 SR3.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Avoid Carousel changes the current position when window is resized. 

The problem is that, every time we change the size of the CarouselView (due to window size change, change in layouts, etc.) we are: reloading the ItemsSource, making adjustments to snap, making adjustments to center CurrentItem, etc. This has an important impact on performance in addition to being able (as you can see in the gif below) to change and set an incorrect CurrentItem.

Before
issue-22000
After
fix-22000

### Issues Fixed

Fixes #22000 
Fixes (partially) #18559
Related with https://github.com/dotnet/maui/issues/18014 (the issue contains more than one specific problem)

### CODE REVIEW

File: src/Controls/tests/UITests/Tests/Issues/Issue22000.cs [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+	{
+		public Issue22000(TestDevice device) : base(device) { }
+
+		public override string Issue => "[Windows] Carousel changes the current position when window is resized";
+
+		[Test]
+		[Category(UITestCategories.CarouselView)]
+		public void ResizeCarouselViewKeepsIndex()
+		{
+			this.IgnoreIfPlatforms(new TestDevice[] { TestDevice.Android, TestDevice.iOS, TestDevice.Mac });
```
Comment (PureWeen) [inline src/Controls/tests/UITests/Tests/Issues/Issue22000.cs:17]: Is this test relevant on all platforms?
Wondering if we should run for everyone?

File: src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Windows.cs [hunk 2]
```diff
@@ -548,10 +549,31 @@ void Resize(Size newSize)
...
+			UpdateSnapPointsAlignment();
+			UpdateCarouselViewInitialPosition();
+		}
+
+		void InvalidateItemSize()
+		{
+			foreach (var item in ListViewBase.GetChildren<ItemContentControl>())
+			{
+				item.ItemHeight = GetItemHeight();
+				item.ItemWidth = GetItemWidth();
```
Comment (Foda) [inline src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Windows.cs:574]: It's beyond the scope of this PR, but I wonder why this logic isn't in the layout/measure pass. You'd think that item width + height is just calculated based on horizontal/vertical modes

File: src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Windows.cs [hunk 3]
```diff
@@ -548,10 +549,31 @@ void Resize(Size newSize)
...
+			UpdateSnapPointsType();
+			UpdateSnapPointsAlignment();
+			UpdateCarouselViewInitialPosition();
+		}
+
+		void InvalidateItemSize()
+		{
+			foreach (var item in ListViewBase.GetChildren<ItemContentControl>())
+			{
+				item.ItemHeight = GetItemHeight();
```
Comment (Foda) [inline src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Windows.cs:573]: `GetItemHeight` and `GetItemWidth` should be moved out of the `foreach` since they only need calculation once.

**Review by Foda — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Windows.cs (hunk 3 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Windows.cs]: Good suggestion. Changed.

File: src/Controls/tests/UITests/Tests/Issues/Issue22000.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Controls/tests/UITests/Tests/Issues/Issue22000.cs]: Yeah, could be interesting for all the platforms. Applied changes.

**Review by Foda — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]
