### PR TITLE
[Android] Fix usage of SimpleViewHolder on COllectionView Header and Footer

### LINKED ISSUE #5332: CollectionView with Header or Footer throws: The specified child already has a parent. You must call removeView() on the child's parent first
### Description

The initial situation is a simple page with a CollectionView and a Button. 

I press the button and inside a ViewModel i add a new item to the ObservableCollection, which is bound to the ItemsSource of the CollectionView.

If i have no CollectionView.Header or CollectionView.Footer defined, everything works as expected.

If i add a Header or Footer to the CollectionView the same scenario throws the following exception:
Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'

### Steps to Reproduce

1. Create a page with a CollectionView and a Button.
2. Create a ViewModel with an ObservableCollection as ItemsSource for the CollectionView and an IAsyncCommand handler for the button and bind them to the UI.
3. Add a new item to the ObservableCollection, when the button is pressed.
4. Test different scenarios:
   * CollectionView without Header and Footer (o.k.)
   * CollectionView with Header (error)
   * CollectionView with Footer (error)

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Physical device with Android 11

### Did you find any workaround?

_No response_

### Relevant log output

```shell
Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'
```

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

Our previous implementation on Forms was creating always a new native element before adding it to SimpleViewHolder, but now we reuse the handler so we need to remove it first from the old ItemContentView before adding it to our new ItemContentView

### Issues Fixed

Fixes #5332

### CODE REVIEW

**Review by Redth — APPROVED** [review]

File: src/Controls/src/Core/Handlers/Items/Android/ItemContentView.cs [hunk 1]
```diff
@@ -26,6 +26,8 @@ internal void RealizeContent(View view, ItemsView itemsView)
 		{
 			Content = CreateHandler(view, itemsView);
 			var platformView = Content.ContainerView ?? Content.PlatformView;
```
Comment (mattleibow) [inline src/Controls/src/Core/Handlers/Items/Android/ItemContentView.cs:28]: Should this be ToPlatform()?

**Review by jsuarezruiz — APPROVED** [review]

**Review by hartez — APPROVED** [review]
