### PR TITLE
[iOS] Observable collection events not firing in the correct order with  CollectionView.BeginInvokeOnMainThread

### LINKED ISSUE #4756: Crash on IOS adding items to an ObservableCollection after Render
### Description

I am getting a crash in IOS when adding items to an observable collection after the observable collection has been displayed in a CollectionView. I have an observable collection that has a binding to the CollectionView. When I try to clear the observable collection and then add new items the app crashes in IOS but works fine for Android.

### Steps to Reproduce

I am not entirely sure of how you repro this, it does happen consistently in my app but there is a complex series of events first. I will attempt to put together a simple example to repro this. For now here is the code I believe to cause the crash and the stack trace from the output after the crash ocurrs.

```
public ObservableCollection<TItem> Items { get; set; } = new ObservableCollection<TItem>();

      public void Load()
      {
          Items.Clear();
          if(updateManyHandler != null)
          {
              foreach(var item in updateManyHandler())
              {
                  Items.Add(item);
              }
          }

          if (updateHandler != null)
          {
              Item = updateHandler(Id);
              Items.Add(Item);

              PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Item)));
          }

          LoadPartnerAdvert();

          IsLoading = false;
      }
```

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 12

### Affected platforms

iOS

### Affected platform versions

iPadIOS 15

### Did you find any workaround?

Not yet

### Relevant log output

```shell
2022-02-17 14:29:40.878 Xamarin.PreBuilt.iOS[3837:3357137] *** Assertion failure in -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:collectionViewAnimator:], UICollectionView.m:8456

[0:] An error occurred: 'Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: attempt to insert item 0 into section 0, but there are only 0 items in section 0 after the update
Native stack trace:
	0   CoreFoundation                      0x0000000184a22060 B2D21CFD-378C-36D5-BAF7-3F70599CFEFC + 626784
	1   libobjc.A.dylib                     0x000000019d096f54 objc_exception_throw + 60
	2   Foundation                          0x00000001862db6cc D59C6975-5AF2-37BC-93BE-43B80B4293A5 + 1246924
	3   UIKitCore                           0x000000018721b65c 8388EB03-002B-3B35-A78A-6A022894292E + 4114012
	4   UIKitCore                           0x00000001874c4574 8388EB03-002B-3B35-A78A-6A022894292E + 6903156
	5   UIKitCore                           0x0000000186edb6e4 8388EB03-002B-3B35-A78A-6A022894292E + 706276
	6   Xamarin.PreBuilt.iOS                0x0000000102b8540c Xamarin.PreBuilt.iOS + 87052
	7   Xamarin.PreBuilt.iOS                0x0000000102ea5e4c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2112228
	8   Xamarin.PreBuilt.iOS                0x0000000102e9b438 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2068688
	9   Xamarin.PreBuilt.iOS                0x0000000102e98ffc _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2059412
	10  Xamarin.PreBuilt.iOS                0x0000000102b854c8 Xamarin.PreBuilt.iOS + 87240
	11  libdispatch.dylib                   0x0000000184694660 A5CBAAB3-E389-3548-BAAC-FAB18411B94A + 18016
	12  libdispatch.dylib                   0x00000001846a2b60 _dispatch_main_queue_callback_4CF + 944
	13  CoreFoundation                      0x00000001849dacd4 B2D21CFD-378C-36D5-BAF7-3F70599CFEFC + 335060
	14  CoreFoundation                      0x0000000184994eac B2D21CFD-378C-36D5-BAF7-3F70599CFEFC + 48812
	15  CoreFoundation                      0x00000001849a83b8 CFRunLoopRunSpecific + 600
	16  GraphicsServices                    0x00000001a033838c GSEventRunModal + 164
	17  UIKitCore                           0x00000001873486a8 8388EB03-002B-3B35-A78A-6A022894292E + 5346984
	18  UIKitCore                           0x00000001870c77f4 UIApplicationMain + 2092
	19  Xamarin.PreBuilt.iOS                0x0000000102ea692c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2115012
	20  Xamarin.PreBuilt.iOS                0x0000000102ea5b34 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2111436
	21  Xamarin.PreBuilt.iOS                0x0000000102e9b33c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2068436
	22  Xamarin.PreBuilt.iOS                0x0000000102e9983c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2061524
	23  Xamarin.PreBuilt.iOS                0x0000000102e6bb38 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1873872
	24  Xamarin.PreBuilt.iOS                0x0000000102db73d4 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1134700
	25  Xamarin.PreBuilt.iOS                0x0000000102dbe2e0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1163128
	26  Xamarin.PreBuilt.iOS                0x0000000102d7e74c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 902116
	27  Xamarin.PreBuilt.iOS                0x0000000102d89008 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 945312
	28  Xamarin.PreBuilt.iOS                0x0000000102ea692c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2115012
	29  Xamarin.PreBuilt.iOS                0x0000000102ea5b34 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2111436
	30  Xamarin.PreBuilt.iOS                0x0000000102e9b33c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2068436
	31  Xamarin.PreBuilt.iOS                0x0000000102e9983c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2061524
	32  Xamarin.PreBuilt.iOS                0x0000000102e6bb38 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1873872
	33  Xamarin.PreBuilt.iOS                0x0000000102db73d4 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1134700
	34  Xamarin.PreBuilt.iOS                0x0000000102dbcddc _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1157748
	35  Xamarin.PreBuilt.iOS                0x0000000102e708f4 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1893772
	36  Xamarin.PreBuilt.iOS                0x0000000102bc6800 xamarin_get_original_working_directory_path + 3672
	37  Xamarin.PreBuilt.iOS                0x0000000102eda5dc _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2327156
	38  dyld                                0x000000010325da24 start + 520
'. Callstack: '   at ObjCRuntime.Runtime.ThrowNSException(IntPtr ns_exception)
   at ObjCRuntime.Runtime.throw_ns_exception(IntPtr exc)
   at UIKit.UICollectionView.InsertItems(NSIndexPath[] indexPaths)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.<>c__DisplayClass36_0.<Add>b__0()
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.Update(Action update, NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.Add(NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.CollectionChanged(NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.CollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1[[MWC.BL.Speaker, MWC.Core.MD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[MWC.BL.Speaker, MWC.Core.MD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
   at System.Collections.ObjectModel.ObservableCollection`1[[MWC.BL.Speaker, MWC.Core.MD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InsertItem(Int32 index, Speaker item)
   at System.Collections.ObjectModel.Collection`1[[MWC.BL.Speaker, MWC.Core.MD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Add(Speaker item)
   at WordAlive.ViewModels.EventDataModel`1[[MWC.BL.Speaker, MWC.Core.MD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Load() in D:\ofilms.visualstudio.com\Repos\WordAliveApp\Trunk\WordAlive\ViewModels\EventDataModel.cs:line 121
   at WordAlive.ViewModels.EventDataModel`1[[MWC.BL.Speaker, MWC.Core.MD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<UpdateManager_UpdateFinished>b__19_0() in D:\ofilms.visualstudio.com\Repos\WordAliveApp\Trunk\WordAlive\ViewModels\EventDataModel.cs:line 92
   at Microsoft.Maui.Dispatching.Dispatcher.<>c__DisplayClass7_0.<DispatchImplementation>b__0()
   at CoreFoundation.DispatchQueue.static_dispatcher_to_managed(IntPtr context)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at WordAlive.Program.Main(String[] args) in D:\ofilms.visualstudio.com\Repos\WordAliveApp\Trunk\WordAlive\Platforms\iOS\Program.cs:line 13
--- End of stack trace from previous location ---
   at UIKit.UICollectionView.InsertItems(NSIndexPath[] indexPaths)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.<>c__DisplayClass36_0.<Add>b__0()
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.Update(Action update, NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.Add(NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.CollectionChanged(NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.CollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1[[MWC.BL.Speaker, MWC.Core.MD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[MWC.BL.Speaker, MWC.Core.MD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
   at System.Collections.ObjectModel.ObservableCollection`1[[MWC.BL.Speaker, MWC.Core.MD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InsertItem(Int32 index, Speaker item)
   at System.Collections.ObjectModel.Collection`1[[MWC.BL.Speaker, MWC.Core.MD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Add(Speaker item)
   at WordAlive.ViewModels.EventDataModel`1[[MWC.BL.Speaker, MWC.Core.MD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Load() in D:\ofilms.visualstudio.com\Repos\WordAliveApp\Trunk\WordAlive\ViewModels\EventDataModel.cs:line 121
   at WordAlive.ViewModels.EventDataModel`1[[MWC.BL.Speaker, MWC.Core.MD, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<UpdateManager_UpdateFinished>b__19_0() in D:\ofilms.visualstudio.com\Repos\WordAliveApp\Trunk\WordAlive\ViewModels\EventDataModel.cs:line 92
   at Microsoft.Maui.Dispatching.Dispatcher.<>c__DisplayClass7_0.<DispatchImplementation>b__0()
   at CoreFoundation.DispatchQueue.static_dispatcher_to_managed(IntPtr context)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at WordAlive.Program.Main(String[] args) in D:\ofilms.visualstudio.com\Repos\WordAliveApp\Trunk\WordAlive\Platforms\iOS\Program.cs:line 13
--- End of stack trace from previous location ---
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at WordAlive.Program.Main(String[] args) in D:\ofilms.visualstudio.com\Repos\WordAliveApp\Trunk\WordAlive\Platforms\iOS\Program.cs:line 13
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)'
The app has been terminated.
```

### LINKED ISSUE #6134: iOS Crash on populating CollectionView with data
### Description

When I load data into collectionview i get a crash .. working fin on Android/Windows.

See Final Folder in https://github.com/dotnet-presentations/dotnet-maui-workshop

### Steps to Reproduce

Load Final Folder in https://github.com/dotnet-presentations/dotnet-maui-workshop

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #6484: Issues with collection view displaying only first item and scrolling crashes app
### Description

Open and run Final folder in https://github.com/dotnet-presentations/dotnet-maui-workshop
Run on macOS catalyst and then load data and try to scroll and app will crash

### Steps to Reproduce

Open and run Final folder in https://github.com/dotnet-presentations/dotnet-maui-workshop
Run on macOS catalyst and then load data and try to scroll and app will crash

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS

### Did you find any workaround?

None

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

There's also a strange issue where the CollectionChanged events are not firing in the exact order on the platform side. seems they are batching. This seems to be when we load data in a different thread and then marshal for the native thread, so we remove that and used the maui  `ApplicationModel.MainThread.BeginInvokeOnMainThread`

### Issues Fixed

Fixes #4756
Fixes #6134
Fixes #6484

### CODE REVIEW

**Review by Redth — APPROVED** [review]

**Comment by jamesmontemagno** [comment]
@Redth  @rmarinho can you also verify if it fixes -> https://github.com/dotnet/maui/issues/6484

**Review by Redth — APPROVED** [review]

File: src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs [hunk 1]
```diff
@@ -231,6 +229,9 @@ public virtual void UpdateFlowDirection()
 
 		public override nint NumberOfSections(UICollectionView collectionView)
 		{
+			if(ItemsSource == null)
```
Comment (hartez) [inline src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs:232]: This shouldn't be happening - if the binding to ItemsSource is null, the ItemsSource here should be the EmptySource. And you can't skip the CheckForEmptySource() check; it will break the EmptyView.

File: src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs [hunk 2]
```diff
@@ -136,18 +136,22 @@ void CollectionChanged(NotifyCollectionChangedEventArgs args)
...
 
-		void Reload()
+		void Reload(bool isDoingReset = false)
 		{
 			var args = new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset);
 
-			Count = ItemsCount();
+			//there could be cases where the Reset event doesn't fire before we start adding items if done from a different thread
+			if (isDoingReset)
+				Count = 0;
```
Comment (hartez) [inline src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs:152]: "Reset" doesn't mean there are zero items in the collection - it means the contents of the collection have changed dramatically (i.e., a lot).

**Review by hartez — CHANGES_REQUESTED** [review]
I'm fairly certain that this PR breaks EmptyView, and it's not clear _how_ it fixes the problems with Clear/Add.

File: src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs (hunk 2 above)
Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs:152]: Oh good catch

File: src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs (hunk 1 above)
Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs:232]: This happen because Mapper didn't run yet, i can change this . We were using Mapper, and also creating when VIewLoad the ItemsSource.. removing from ViewLoad makes it break here for example

File: src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs (hunk 2 above)
Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs:152]: It fixes the issue, because Count is now correct. Right now when getting Reset event when this code was grabbing the Count it was already 13 because items were added .

File: src/Controls/samples/Controls.Sample/Pages/Controls/CollectionViewGalleries/ItemsSourceGenerator.cs [hunk 3]
```diff
@@ -156,14 +156,19 @@ void GenerateMultiTestObservableCollection()
...
 			if (int.TryParse(_entry.Text, out int count))
 			{
 				var items = new ObservableCollection<CollectionViewGalleryTestItem>();
 				_cv.ItemsSource = items;
 				Dispatcher.StartTimer(TimeSpan.FromSeconds(1), () =>
 				{
+					//this test a issue with events firing out of order on IOS Obs Source
+					if(resetBeforeAddItems)
+					{
+						items.Clear();
```
Comment (rmarinho) [inline src/Controls/samples/Controls.Sample/Pages/Controls/CollectionViewGalleries/ItemsSourceGenerator.cs:170]: @hartez  Basic when this happens it doesn't fire the CollectionChange (reset) on the other side

File: src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs [hunk 4]
```diff
@@ -136,6 +136,7 @@ public override void ViewDidLoad()
 
 			if (!(OperatingSystem.IsIOSVersionAtLeast(11) || OperatingSystem.IsTvOSVersionAtLeast(11)))
 				AutomaticallyAdjustsScrollViewInsets = false;
+      }
```
Comment (Redth) [inline src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs:139]: @rmarinho bad merge?

Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs:139]: yap

Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs]: Fixed

**Comment by IndexOutOfLimit** [comment]
May I know when this will be released.
