### PR TITLE
[Windows] Fix Shadow positions issues

### LINKED ISSUE #13944: Shadow not displaying properly in Border
### Description

I'm trying to add a `<Shadow>` to a border and there are a couple of issues that I'm encountering.

1. If the border is transparent (i.e doesn't BorderBackground set) the border will not display a shadow in Windows or will display a grey rectangle on Android
<details>
<summary> Screenshots </summary>

image
image

</details>

2. If the border has variable height and width using Minimum/Maximum width requests, the border will render completely off in Windows and will not move if the window is resized. Moreover, if I were to resize my screen, the shadow will sometimes update but it will not move with the border I'm manipulating. On Android the shadow will just display in the same fashion as in point 1

<details>
<summary> Screenshots </summary>

image
image

</details>

### Steps to Reproduce

1. Create a new Maui Project
2. Add these lines: 
```
    <ScrollView>
        <Border Stroke="Green"
                    StrokeThickness="1"
                    BackgroundColor="White"
                    MaximumHeightRequest="400"
                    MaximumWidthRequest="500"
                    MinimumHeightRequest="300"
                    MinimumWidthRequest="400">
                <Border.Shadow>
                    <Shadow Brush="Black"
                        Radius="40"
                        Opacity="0.8"/>
                </Border.Shadow>
        </Border>
    </ScrollView>
```
3. Build and run the project
4. Remove the `BackgroundColor` property in Windows and the border will disappear

### Link to public reproduction project repository

https://github.com/jknaudt21/MauiIssues

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 11, Android API 33

### Did you find any workaround?

One can add a determined `HeightRequest` and `WidthRequest` to the border to minimize the errors in Windows. I haven't found a workaround in Android.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix Shadow positions issues under some scenarios (with some Views). With this PR the shadow is invalidated after resize the shadow host or under other conditions like resizing the Window.
 
fix-13944

Can validate the changes with the added sample in the Shadows section from the .NET MAUI Gallery.

_NOTE: Is still a draft because I'm validating other issue using Transparent colors in the host._

### Issues Fixed

Fixes #13944

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Have done tests validating the behavior with a Transparent background in the Host, and the Shadow is rendering now
image

File: src/Core/src/Platform/Windows/WrapperView.cs [hunk 1]
```diff
@@ -245,22 +234,31 @@ void UpdateShadow()
...
 
-					float height = (float)_shadowHostSize.Height;
+				float height = (float)_shadowHostSize.Height;
 
-					if (height <= 0)
-						height = (float)frameworkElement.ActualHeight;
+				if (height <= 0)
+					height = (float)frameworkElement.ActualHeight;
 
+				if (_shadowVisual != null)
```
Comment (mandel-macaque) [inline src/Core/src/Platform/Windows/WrapperView.cs:249]:
```suggestion
				if (_shadowVisual is not null)
```

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]
