### PR TITLE
CarouselView fix measure for CarouselView.Loop

### LINKED ISSUE #4082: [Android] CarouselView infinite loading loop when height or width are unbounded
### Description

Trying to navigate to a page with a CollectionView freeze the App until crash:

```
[.ControlGaller] Explicit concurrent copying GC freed 886(65KB) AllocSpace objects, 0(0B) LOS objects, 47% free, 26MB/50MB, paused 730us total 94.683ms
[.ControlGaller] Explicit concurrent copying GC freed 886(50KB) AllocSpace objects, 0(0B) LOS objects, 47% free, 26MB/50MB, paused 881us total 123.270ms
[.ControlGaller] Explicit concurrent copying GC freed 886(64KB) AllocSpace objects, 0(0B) LOS objects, 47% free, 26MB/50MB, paused 968us total 101.780ms
[.ControlGaller] Explicit concurrent copying GC freed 886(51KB) AllocSpace objects, 0(0B) LOS objects, 47% free, 26MB/50MB, paused 665us total 96.196ms
[.ControlGaller] Explicit concurrent copying GC freed 839(55KB) AllocSpace objects, 0(0B) LOS objects, 47% free, 26MB/50MB, paused 746us total 93.642ms
[.ControlGaller] Explicit concurrent copying GC freed 845(58KB) AllocSpace objects, 0(0B) LOS objects, 46% free, 27MB/51MB, paused 892us total 136.831ms
[.ControlGaller] Explicit concurrent copying GC freed 886(65KB) AllocSpace objects, 0(0B) LOS objects, 46% free, 27MB/51MB, paused 744us total 93.234ms
[.ControlGaller] Explicit concurrent copying GC freed 886(64KB) AllocSpace objects, 0(0B) LOS objects, 46% free, 27MB/51MB, paused 710us total 108.543ms
[.ControlGaller] Explicit concurrent copying GC freed 886(50KB) AllocSpace objects, 0(0B) LOS objects, 46% free, 27MB/51MB, paused 712us total 106.430ms
[.ControlGaller] WaitForGcToComplete blocked HeapTrim on Explicit for 64.098ms
[.ControlGaller] Explicit concurrent copying GC freed 886(64KB) AllocSpace objects, 0(0B) LOS objects, 46% free, 27MB/51MB, paused 961us total 104.197ms
[.ControlGaller] Explicit concurrent copying GC freed 886(51KB) AllocSpace objects, 0(0B) LOS objects, 46% free, 27MB/51MB, paused 1.095ms total 115.805ms
[.ControlGaller] Explicit concurrent copying GC freed 872(51KB) AllocSpace objects, 0(0B) LOS objects, 46% free, 28MB/52MB, paused 1.675ms total 175.706ms
[.ControlGaller] Explicit concurrent copying GC freed 814(62KB) AllocSpace objects, 0(0B) LOS objects, 46% free, 28MB/52MB, paused 732us total 101ms
[libc] Requested dump for tid 16605 (.ControlGallery)
[.ControlGaller] Explicit concurrent copying GC freed 884(65KB) AllocSpace objects, 0(0B) LOS objects, 45% free, 28MB/52MB, paused 819us total 259.824ms
[.ControlGaller] Explicit concurrent copying GC freed 887(112KB) AllocSpace objects, 0(0B) LOS objects, 45% free, 28MB/52MB, paused 904us total 169.633ms
[.ControlGaller] Explicit concurrent copying GC freed 891(81KB) AllocSpace objects, 0(0B) LOS objects, 45% free, 28MB/52MB, paused 1.318ms total 174.304ms
[.ControlGaller] JNI critical lock held for 20.936ms on Thread[1,tid=16605,Runnable,Thread*=0x7b632908c7b0,peer=0x7159bb18,"main"]
[.ControlGaller] Explicit concurrent copying GC freed 885(48KB) AllocSpace objects, 0(0B) LOS objects, 45% free, 28MB/52MB, paused 746us total 120.843ms
```

### Steps to Reproduce

1. Download [ControlGallery.zip](https://github.com/dotnet/maui/files/7854034/ControlGallery.zip)
2. Try to navigate to the "CarouselView sample".

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

 If the height or width are unbounded and the user is set to Loop then the CarouselView tries to create and measure all 16384 items that we virtualize.  Looping works by setting item count to 16384 so if the  CarV has infinite room it'll generate all 16384 items. This PR attempts to detect that condition and then just forces to the CarV to measure with one item and then uses that for the WxH.

There are also various fixes that seemed needed as it related to contraints/px/dp interactions.

I think this PR also breaks margins when set on Items but I'm not too sure how to account for Margins here and make it all work.

- You can test the looping fix just with the first gallery in CarouselViewGallery. That gallery just has 3 items with looping turned on. If you try to load it against this [PR](https://github.com/dotnet/maui/pull/3343) it just locks up trying to load 16384 rows

### Issues Fixed

Fixes #4082

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/Android/Adapters/EmptyViewAdapter.cs [hunk 1]
```diff
@@ -273,12 +273,12 @@ bool IsEmpty(int position)
 		int GetHeight(ViewGroup parent)
 		{
 			var headerFooterHeight = parent.Context.ToPixels(_headerHeight + _footerHeight);
-			return Math.Abs((int)(parent.Height - headerFooterHeight));
+			return Math.Abs((int)(parent.MeasuredHeight - headerFooterHeight));
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/Android/Adapters/EmptyViewAdapter.cs:276]: I don't think `Height` is ever right in these cases

File: src/Controls/src/Core/Handlers/Items/Android/Adapters/EmptyViewAdapter.cs [hunk 2]
```diff
@@ -273,12 +273,12 @@ bool IsEmpty(int position)
...
 		}
 
 		int GetWidth(ViewGroup parent)
 		{
-			return parent.Width;
+			return parent.MeasuredWidth;
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/Android/Adapters/EmptyViewAdapter.cs:281]: I don't think `Height` is ever right in these cases

File: src/Controls/src/Core/Handlers/Items/Android/SimpleViewHolder.cs [hunk 3]
```diff
@@ -42,7 +42,7 @@ public static SimpleViewHolder FromText(string text, Context context, bool fill
 			return new SimpleViewHolder(textView, null);
 		}
 
-		public static SimpleViewHolder FromFormsView(View formsView, Context context, Func<int> width, Func<int> height, ItemsView container)
+		public static SimpleViewHolder FromFormsView(View formsView, Context context, Func<double> width, Func<double> height, ItemsView container)
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/Android/SimpleViewHolder.cs:45]: These Func calls are returning the android pixel sizes so it's easier to work in doubles for things like double.positiveinfinity

File: src/Controls/src/Core/Handlers/Items/Android/SizedItemContentView.cs [hunk 4]
```diff
@@ -23,13 +24,31 @@ protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
...
+
+			if (Content.VirtualView.Handler is IPlatformViewHandler pvh)
+			{
+				var widthSpec = Context.CreateMeasureSpec(targetWidth, 
+					double.IsInfinity(targetWidth) ? double.NaN : targetWidth
+					, targetWidth);
+				var heightSpec = Context.CreateMeasureSpec(targetHeight, double.IsInfinity(targetHeight) ? double.NaN : targetHeight
+					, targetHeight);
+
+				pvh.PlatformView.Measure(widthSpec, heightSpec);
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/Android/SizedItemContentView.cs:47]: Things always seem to work better if you just call platform measure instead of trying to call `IView.Measure`.  If I change this to `IView.Measure` then things like `Frame` stop measuring correctly.

Though I don't think this mechanism of calling takes into account `Margins`. Not sure how to make all of that play together.

File: src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Android.cs [hunk 5]
```diff
@@ -53,25 +54,40 @@ public override Size GetDesiredSize(double widthConstraint, double heightConstra
 		{
 			_widthConstraint = widthConstraint;
 			_heightConstraint = heightConstraint;
+
+			if (!double.IsInfinity(_widthConstraint))
+				_widthConstraint = Context.ToPixels(_widthConstraint);
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Android.cs:59]: Constraints come in on `GetDesiredSize` as DP not Pixels

File: src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Android.cs [hunk 6]
```diff
@@ -53,25 +54,40 @@ public override Size GetDesiredSize(double widthConstraint, double heightConstra
...
+			if (!double.IsInfinity(_heightConstraint))
+				_heightConstraint = Context.ToPixels(_heightConstraint);
+
 			return base.GetDesiredSize(widthConstraint, heightConstraint);
 		}
 
-		int GetItemWidth()
+		public override void PlatformArrange(Rect frame)
+		{
+			_widthConstraint = Context.ToPixels(frame.Width);
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Android.cs:69]: If the `GetDesiredSize` call was using infinite then these will set the contraints to the arrived at values

File: src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Android.cs [hunk 7]
```diff
@@ -53,25 +54,40 @@ public override Size GetDesiredSize(double widthConstraint, double heightConstra
...
+		}
+
+		double GetItemWidth()
 		{
-			var itemWidth = (int)Context?.ToPixels(_widthConstraint);
+			var itemWidth = _widthConstraint;
 
 			if ((PlatformView as IMauiRecyclerView<CarouselView>)?.ItemsLayout is LinearItemsLayout listItemsLayout && listItemsLayout.Orientation == ItemsLayoutOrientation.Horizontal)
-				itemWidth = (int)(PlatformView.Width - Context?.ToPixels(VirtualView.PeekAreaInsets.Left) - Context?.ToPixels(VirtualView.PeekAreaInsets.Right) - Context?.ToPixels(listItemsLayout.ItemSpacing));
+				itemWidth = (int)(PlatformView.MeasuredWidth - Context?.ToPixels(VirtualView.PeekAreaInsets.Left) - Context?.ToPixels(VirtualView.PeekAreaInsets.Right) - Context?.ToPixels(listItemsLayout.ItemSpacing));
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Android.cs:80]: I don't think `Width` is ever correct.

File: src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs [hunk 8]
```diff
@@ -540,6 +540,87 @@ void ClearLayoutListener()
...
+		protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
+		{
+			if (Carousel.Loop)
+			{
+				// If the height or width are unbounded and the user is set to
+				// Loop then we can't just do an infinite measure.
+				// Looping works by setting item count to 16384 so if the 
+				// CarV has infinite room it'll generate all 16384 items.
+				// This code forces the adapter to just measure the first item
+				// And then that measure is used for the WxH of the CarouselView
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs:572]: ?

File: src/Controls/src/Core/Handlers/Items/Android/Adapters/EmptyViewAdapter.cs (hunk 1 above)
Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items/Android/Adapters/EmptyViewAdapter.cs:276]: yeah i did the same change on iOS

File: src/Controls/src/Core/Handlers/Items/Android/SizedItemContentView.cs (hunk 4 above)
Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items/Android/SizedItemContentView.cs:47]: @hartez  ?

**Review by rmarinho — APPROVED** [review]

File: src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs [hunk 9]
```diff
@@ -282,6 +282,10 @@ void UpdateItemDecoration()
 
 		void UpdateInitialPosition()
 		{
+			//if we don't have any items don't update position
+			if (ItemsViewAdapter.ItemsSource.Count == 0)
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs:286]: Small fix to update initial position in mappers land

File: src/Controls/src/Core/Handlers/Items/Android/SizedItemContentView.cs [hunk 10]
```diff
@@ -23,13 +24,31 @@ protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
...
-			(Content.VirtualView as View).Measure(Context.FromPixels(targetWidth), Context.FromPixels(targetHeight),
-				MeasureFlags.IncludeMargins);
+			if (!double.IsInfinity(targetWidth))
+				targetWidth = (int)Context.FromPixels(targetWidth);
 
-			SetMeasuredDimension(targetWidth, targetHeight);
+			if (!double.IsInfinity(targetHeight))
+				targetHeight = (int)Context.FromPixels(targetHeight);
+
+			//_ = (Content.VirtualView as IView)
```
Comment (hartez) [inline src/Controls/src/Core/Handlers/Items/Android/SizedItemContentView.cs:36]: Drop the commented code if this is intentional.

File: src/Controls/src/Core/Handlers/Items/Android/SizedItemContentView.cs (hunk 4 above)
Comment (hartez) [reply src/Controls/src/Core/Handlers/Items/Android/SizedItemContentView.cs:47]: Anything that was still using MeasureFlags.IncludeMargins is suspect anyway. This is probably fine. If it's not, we'll fix it in post.

**Review by hartez — CHANGES_REQUESTED** [review]
Fix the commented code stuff and then I think it's fine.
