### PR TITLE
Made MaxLength property consistent across all platforms

### LINKED ISSUE #678: [Bug] The Entry.MaxLength value is inconsistent
### Description

Previously in Forms, it seems that a MaxLength of < 0 would just crash. And 0 meant no text at all.

In MAUI, especially for Comet, we can make this consistent and also not crash. One way would be to make < 0 mean all text, 0 mean no text (debatable) and > 0 mean clip text.

### Steps to Reproduce

Windows:
1. Set MaxLength to -1 and run Windows

iOS / Android:
1. Set MaxLength to -1, 0, and 1
2. Observe different things on different OS

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### PR DESCRIPTION
**Pull request by rachelkang**
### Description of Change

MaxLength property is now consistent across Windows, Android, and iOS for Entry, Editor, and SearchBar! yayyyy :)

MaxLength=-1 behaves as MaxLength=int.MaxValue
MaxLength=0 fields cannot be typed into
MaxLength>0 limits and trims text to the assigned value

### Issues Fixed
Fixes #678

### CODE REVIEW

File: src/Core/src/Platform/Windows/TextBoxExtensions.cs [hunk 1]
```diff
@@ -128,6 +128,9 @@ public static void UpdateMaxLength(this TextBox textBox, ITextInput textInput)
 		{
 			var maxLength = textInput.MaxLength;
 
+			if (maxLength == 0)
+				textBox.IsReadOnly = true;
```
Comment (mattleibow) [inline src/Core/src/Platform/Windows/TextBoxExtensions.cs:132]: What happens if I set MaxLength to 0 nd then back to 10? Does it re-enable?

File: src/Core/src/Platform/Windows/SearchBarExtensions.cs [hunk 2]
```diff
@@ -94,15 +94,23 @@ public static void UpdateVerticalTextAlignment(this AutoSuggestBox platformContr
 
 		public static void UpdateMaxLength(this AutoSuggestBox platformControl, ISearchBar searchBar)
 		{
+			var maxLength = searchBar.MaxLength;
+
+			if (maxLength == -1)
+				maxLength = int.MaxValue;
+
+			if (maxLength == 0)
+				MauiAutoSuggestBox.SetIsReadOnly(platformControl, true);
```
Comment (mattleibow) [inline src/Core/src/Platform/Windows/SearchBarExtensions.cs:103]: Same as the text box below, does it re-enable after reverting MaxLength?

File: src/Core/src/Platform/Windows/TextBoxExtensions.cs (hunk 1 above)
Comment (mattleibow) [inline src/Core/src/Platform/Windows/TextBoxExtensions.cs:132]: What happens if I set MaxLength to 0 nd then back to 10? Does it re-enable?

File: src/Core/src/Platform/Windows/SearchBarExtensions.cs [hunk 3]
```diff
@@ -94,15 +94,23 @@ public static void UpdateVerticalTextAlignment(this AutoSuggestBox platformContr
...
-				platformControl.Text = currentControlText.Substring(0, searchBar.MaxLength);
+			if (currentControlText.Length > maxLength)
+				platformControl.Text = currentControlText.Substring(0, maxLength);
 		}
-		
+
 		public static void UpdateIsReadOnly(this AutoSuggestBox platformControl, ISearchBar searchBar)
 		{
-			platformControl.IsEnabled = searchBar.IsReadOnly;
+			MauiAutoSuggestBox.SetIsReadOnly(platformControl, searchBar.IsReadOnly);
```
Comment (mattleibow) [inline src/Core/src/Platform/Windows/SearchBarExtensions.cs:113]: If I set IsReadonly=False and MaxLength to 0 and then it gets disabled, can I re-enable by just setting IsReadOnly=True? Should IsReadonly reall be a combination of `searchBar.IsReadOnly && MaxLength > 0`.

Same with the TextBox below.

**Review by mattleibow — COMMENTED** [review]
Nice!

Just got some questions on how changing the properties affect the others. Maybe we can add a test for this case where toggling the two around does not inadvertently change values.

**Comment by Redth** [comment]
Tested iOS/MacCatalyst, working as expected, lgtm on those platforms!

File: src/Core/src/Platform/Windows/SearchBarExtensions.cs (hunk 3 above)
Comment (rachelkang) [reply src/Core/src/Platform/Windows/SearchBarExtensions.cs:113]: good point, will check on those and add tests!

**Comment by rachelkang** [comment]
AFAICT failing tests are unrelated

**Comment by rachelkang** [comment]
Windows SearchBar MaxLength will need some more time https://github.com/dotnet/maui/issues/5669

File: src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs [hunk 4]
```diff
@@ -70,5 +70,22 @@ public async Task TextTransformUpdated(string text, TextTransform transform, str
...
+			editor.MaxLength = 0;
+
+			await InvokeOnMainThreadAsync(() =>
+			{
+				var handler = CreateHandler<EditorHandler>(editor);
+				var platformControl = GetPlatformControl(handler);
+				editor.MaxLength = 10;
+#if WINDOWS
+				Assert.False(platformControl.IsReadOnly);
+#endif
```
Comment (mattleibow) [inline src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs:87]: Why only windows?

File: src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs [hunk 5]
```diff
@@ -70,5 +70,22 @@ public async Task TextTransformUpdated(string text, TextTransform transform, str
...
+		public async Task MaxLengthIsReadOnlyValueTest()
+		{
+			Editor editor = new Editor();
+			editor.MaxLength = 0;
+
+			await InvokeOnMainThreadAsync(() =>
+			{
+				var handler = CreateHandler<EditorHandler>(editor);
+				var platformControl = GetPlatformControl(handler);
+				editor.MaxLength = 10;
```
Comment (mattleibow) [inline src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs:84]: Maybe you also need to check that it _is_ read only before changing the max length.

Comment (mattleibow) [reply src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs:84]: Also, this test can run when you set max length to 0, and then set IsReadOnly to false and then back to true. That should still not re-enable the editor.

Comment (mattleibow) [inline src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs:84]: Maybe you also need to check that it is read only before changing the max length.

File: src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs [hunk 6]
```diff
@@ -70,5 +70,22 @@ public async Task TextTransformUpdated(string text, TextTransform transform, str
...
+		[Fact]
+		public async Task MaxLengthIsReadOnlyValueTest()
+		{
+			Editor editor = new Editor();
+			editor.MaxLength = 0;
+
+			await InvokeOnMainThreadAsync(() =>
+			{
+				var handler = CreateHandler<EditorHandler>(editor);
+				var platformControl = GetPlatformControl(handler);
```
Comment (mattleibow) [inline src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs:83]: Also, this test can run when you set max length to 0, and then set IsReadOnly to false and then back to true. That should still not re-enable the editor.

File: src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs (hunk 4 above)
Comment (mattleibow) [inline src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs:87]: Why only windows?

**Review by mattleibow — COMMENTED** [review]
Just a few questions to make sure we are testing the combinations of properties.

File: src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs (hunk 5 above)
Comment (rachelkang) [reply src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs:84]: can do!

File: src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs (hunk 4 above)
Comment (rachelkang) [reply src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs:87]: We can make it IsReadOnly for all platforms if we want for consistency - but I didn't do this on Android and iOS because it wasn't necessary.

The reason we added the IsReadOnly logic to Windows is because when MaxLength > 0, it still allows you to type more text into the box. On Android and iOS, when MaxLength > 0, you can't type anything into the box even if IsReadOnly=false

File: src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs (hunk 6 above)
Comment (rachelkang) [reply src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs:83]: good point, will be sure to add that test case too!

**Review by mattleibow — APPROVED** [review]
