### PR TITLE
[iOS] Crash upon resuming the app - fix

### LINKED ISSUE #21948: Crash upon resuming the app 'window was already activated'
### Description

when we minimize the app and then restore it, we get a 'window was already activated' crash.

```
System.InvalidOperationException: 'Window was already activated'
   at Microsoft.Maui.Controls.Window.Microsoft.Maui.IWindow.Activated()
   at Microsoft.Maui.LifecycleEvents.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__2_3(UIApplication app)
   at Microsoft.Maui.MauiUIApplicationDelegate.<>c__DisplayClass14_0.<OnActivated>b__0(OnActivated del)
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[OnActivated](IServiceProvider services, Action`1 action)
   at Microsoft.Maui.MauiUIApplicationDelegate.OnActivated(UIApplication application)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at MyProject.Platforms.iOS.Program.Main(String[] args) in C:\siren\SES\MyProject\Platforms\iOS\Program.cs:line 12
```

This takes place when we are showing a popup page, and then close this popup page (with a slight delay) and immediately minimize the app then restore it.
Please see the repro project and follow the repro steps.

### Steps to Reproduce

1. open a popup page (press the "Open Popup Page 1" button)
2. close the popup page and minimized the app (press the "Close popup page after a 2 seconds delay" button and immediately minimize the app)
3. restore the app

### Link to public reproduction project repository

https://github.com/ESO-ST/WebViewCrashMidLoad/tree/WindowWasAlreadyActivatedCrash
https://github.com/dotnet/maui/tree/fix_21948

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

no

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/21948

|Before|After|
|--|--|
|<video src="https://github.com/dotnet/maui/assets/42434498/b7526edf-34de-4cb9-891a-91e681bc2924" width="300px"/>|<video src="https://github.com/dotnet/maui/assets/42434498/c9ec1515-6006-4d86-96f6-ea228f456c7a" width="300px"/>|

### CODE REVIEW

File: src/Core/src/Platform/iOS/UIApplicationExtensions.cs [hunk 1]
```diff
@@ -44,8 +44,39 @@ internal static UIEdgeInsets GetSafeAreaInsetsForWindow(this UIApplication appli
...
+            {
+                // If there's only one window to return then just return that window
+                var windows = IPlatformApplication.Current?.Application?.Windows ?? Array.Empty<IWindow>();
+
+                if (windows.Count == 1)
+                    return windows[0];
+
+                if (OperatingSystem.IsIOSVersionAtLeast(15))
+                {
+                    foreach(var windowScene in application.ConnectedScenes)
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/UIApplicationExtensions.cs:59]: I'm wondering if we can just reduce all this code down to just this foreach statement for APIs > 13+

```C#
public static IWindow? GetWindow(this UIApplication application)
        {
            // If there's only one window to return then just return that window
			var windows = IPlatformApplication.Current?.Application?.Windows ?? Array.Empty<IWindow>();

			if (windows.Count == 1)
				return windows[0];

			if (OperatingSystem.IsIOSVersionAtLeast(13))
			{
				foreach(var windowScene in application.ConnectedScenes)
				{
					if (windowScene is UIWindowScene uiWindowScene)
					{
						if(uiWindowScene.Windows.Length == 1 && uiWindowScene.Windows[0].GetWindow() is IWindow window)
						{
							return window;
						}
					}
				}
			}
			else
			{
				if(application.Windows.Length == 1)
					return application.Windows[0].GetWindow();
			}

            return application.GetKeyWindow().GetWindow();
        }
        
```

File: src/Controls/tests/TestCases.HostApp/Issues/Issue23360.xaml.cs [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+            var uIWindow = new UIWindow();
+            var keyWindow = (this.Window.Handler.PlatformView as UIWindow);
+            if (keyWindow?.WindowLevel == UIWindowLevel.Normal)
+                keyWindow.WindowLevel = -1;
+
+            var page = new ContentPage();
+            this.AddLogicalChild(page);
+            var handler = page.ToHandler(this.Handler.MauiContext);
+
+            uIWindow.RootViewController = new UIViewController();
```
Comment (PureWeen) [inline src/Controls/tests/TestCases.HostApp/Issues/Issue23360.xaml.cs:41]: We'll need to if/def this code for iOS

**Review by PureWeen — APPROVED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23360.cs [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+{
+	public class Issue21948 : _IssuesUITest
+	{
+		public Issue21948(TestDevice device) : base(device) { }
+
+		public override string Issue => "Crash upon resuming the app 'window was already activated'";
+
+		[Test]
+		[Category(UITestCategories.Window)]
+		public void OpenAlertWithModals()
```
Comment (PureWeen) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23360.cs:16]: This is failing on catalyst. Is this test and scenario relevant on catalyst?

**Review by PureWeen — CHANGES_REQUESTED** [review]

**Review by PureWeen — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]

**Comment by PureWeen** [comment]
Failing tests unrelated
