### PR TITLE
[Window] Fix transforms being offset by 0.5x0.5

### LINKED ISSUE #17694: WinUI - Circle view not rotating from center
### Description

When loading a graphics view with circle fill and on rotation It gets hovered on bottom control. When loading a rect this is fine, but a circle must rotate within the bounds.

### Steps to Reproduce

Please refer the attached sample -
[MauiApp1.zip](https://github.com/dotnet/maui/files/12739015/MauiApp1.zip)

### Link to public reproduction project repository

_No response_

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

### Did you find any workaround?

No.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Foda**
### Description of Change

This PR fixes rotations being offset by 0.5 px in each direction. The [property `CenterX` and `CenterY` are not normalized (0.0 - 1.0)](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.compositetransform.centerx?view=windows-app-sdk-1.4#microsoft-ui-xaml-media-compositetransform-centerx), therefore, setting them offset the transform. Additionally, we already set the `RenderTransformOrigin` a few lines up.

https://github.com/dotnet/maui/assets/890772/2398eaa6-e504-4fd4-baf2-612826efbde3

### Issues Fixed

Fixes #17694

### CODE REVIEW

**Review by jsuarezruiz — COMMENTED** [review]
Could we add an UITest with the example from the video where a button is pressed, an Ellipse is rotated and after finishing the animation verify the Ellipse position? It can be done easily using the `VerifyScreenshot `method. Example: https://github.com/dotnet/maui/blob/792f1f88e5b4cc2d7e61535d0755935125c197fa/src/Controls/tests/UITests/Tests/BorderUITests.cs#L37

**Comment by rmarinho** [comment]
And needs rebase too please

**Comment by Foda** [comment]
> Could we add an UITest with the example from the video where a button is pressed, an Ellipse is rotated and after finishing the animation verify the Ellipse position? It can be done easily using the `VerifyScreenshot `method. Example:
> 
> https://github.com/dotnet/maui/blob/792f1f88e5b4cc2d7e61535d0755935125c197fa/src/Controls/tests/UITests/Tests/BorderUITests.cs#L37

Added!

File: src/Core/src/Platform/Windows/TransformationExtensions.cs [hunk 1]
```diff
@@ -51,8 +51,6 @@ public static void UpdateTransformation(this FrameworkElement frameworkElement,
 				{
 					frameworkElement.RenderTransform = new CompositeTransform
 					{
-						CenterX = anchorX,
-						CenterY = anchorY,
```
Comment (mattleibow) [inline src/Core/src/Platform/Windows/TransformationExtensions.cs:55]: What happens if you do want the offset? Like a rotation about a different point on the element?

File: src/Controls/samples/Controls.Sample.UITests/Issues/Issue17694.cs [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+				WidthRequest = 50,
+				Drawable = new CircleDraw()
+			};
+
+			var button = new Button()
+			{
+				AutomationId = "Spin",
+				Text = "Spin",
+			};
+			button.Clicked += async (s, e) =>
```
Comment (mattleibow) [inline src/Controls/samples/Controls.Sample.UITests/Issues/Issue17694.cs:23]: The animation is nice to have humans check, but for CI maybe we can have a button so go to a specific rotation? And then capture that?

File: src/Core/src/Platform/Windows/TransformationExtensions.cs (hunk 1 above)
Comment (Foda) [reply src/Core/src/Platform/Windows/TransformationExtensions.cs:55]: That's already set in the above code on line 21:
`frameworkElement.RenderTransformOrigin = new global::Windows.Foundation.Point(anchorX, anchorY);`

File: src/Controls/samples/Controls.Sample.UITests/Issues/Issue17694.cs (hunk 2 above)
Comment (Foda) [reply src/Controls/samples/Controls.Sample.UITests/Issues/Issue17694.cs]: Oops, yeah lemme change that to just set the `Rotation` property

**Review by mattleibow — DISMISSED** [review]

**Review by jsuarezruiz — DISMISSED** [review]

File: src/Controls/tests/UITests/Tests/Issues/Issue17694.cs [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+				TestDevice.Mac,
+				TestDevice.Android
+			});
+
+			App.WaitForElement("Spin");
+
+			// 1. Click button
+			App.Click("Spin");
+
+			VerifyScreenshot();
```
Comment (jsuarezruiz) [inline src/Controls/tests/UITests/Tests/Issues/Issue17694.cs:30]: The added test is failing. I think we need to wait a little bit before verify the screenshot to avoid possible problems with the animation still running.
image
`Snapshot different than baseline: Issue17694Test.png (4.40% difference)`

Comment (Foda) [reply src/Controls/tests/UITests/Tests/Issues/Issue17694.cs:30]: Ah, and the mica background I think is causing issues

**Review by mattleibow — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]
