### PR TITLE
[Android] Fixed Material controls themeing issue

### LINKED ISSUE #13356: Java.Lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponent.
### Description

Hello. I'm trying to open a popup on button click. But something went wrong and I get the following exception:
Screenshot 2023-02-15 at 16 10 15
Screenshot 2023-02-15 at 16 11 29

### Steps to Reproduce

1. Run the application from the repository.
2. Click the 'Show me' button on the MainPage and you can see the exception.

if you replace the Button with the Label, the application works fine.
https://github.com/JaneySprings/MauiAndroidMaterialBug/blob/438e4b223e6e0ae9b9515ce6e791281edba402b8/MainPage.xaml.cs#L14

### Link to public reproduction project repository

https://github.com/JaneySprings/MauiAndroidMaterialBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

29

### Did you find any workaround?

If you replace the Button with a Label, it will work.

### Relevant log output

```shell
Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(Jni
ObjectReference instance, JniObjectReference type, JniMethodinfo method, JniArgumentValue* args) in /Users/runner/work/1/s/amarin-android/external/ Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 12324\n at
Java.Interop.JniPeerMembers.JnilnstanceMethods.FinishCreateInstance(Stri ng constructorSignature, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/ Java.Interop/Java.Interop/JniPeerMembers.JnilnstanceMethods.cs:line174\n at Google.Android.Material.Button.MaterialButton.ctor(Context context) in / Users/runner/work/1/s/generated/com.google.android.material.material/obj/ Release/net6.0-android/generated/src/
Google.Android.Material. Button.Materia|Button.cs:line 385\n at
Microsoft.Maui.Platform.MauiMaterialButton..ctor(Context context) in D:|al I work||1\|s\|src||Corel|src||Platform||Android\|MauiMaterialButton.cs:line...
```

### PR DESCRIPTION
**Pull request by NirmalKumarYuvaraj**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root cause
The problem is that the `MauiMaterialButton` style has a parent of `Widget.MaterialComponents.Button.UnelevatedButton`, which requires the application theme to be based on Theme.MaterialComponents. However, the `MauiMaterialButton` constructor is wrapping the context with just the button style, not ensuring the proper theme hierarchy.

### Description of change

* This pull request addresses an issue where certain Material components on Android require a specific app theme (`Theme.MaterialComponent`) to avoid runtime exceptions. It introduces a new `MauiMaterialContextThemeWrapper` to ensure the correct theme is applied to Material components and adds test cases to validate the changes. 

### Fix for Material Component Theme Issue:

* `src/Core/src/Platform/Android/MauiMaterialContextThemeWrapper.cs`: Added `MauiMaterialContextThemeWrapper` class to wrap the Android context with the appropriate Material theme (`Resource.Style.Maui_MainTheme_Base`). This ensures Material components use the correct theme.

* `src/Core/src/Handlers/CheckBox/CheckBoxHandler.Android.cs` : Updated `CheckBoxHandler` to use `MauiMaterialContextThemeWrapper.Create(Context)` when creating `MaterialCheckBox`, ensuring the correct theme is applied.

* `src/Core/src/Platform/Android/MauiMaterialButton.cs` : Modified `MauiMaterialButton` to use `MauiMaterialContextThemeWrapper.Create(context)` for all constructors, ensuring consistent theme application for Material buttons.

#### Reference
https://github.com/dotnet/maui/blob/aac65571c9c8cc2a0b0d78fd6c460477c1720fb5/src/Compatibility/Material/src/Android/MaterialButtonRenderer.cs#L42-L43

https://github.com/dotnet/maui/blob/main/src/Compatibility/Material/src/Android/MaterialContextThemeWrapper.cs

Validated the behaviour in the following platforms

- [x] Android
- [ ] Windows
- [ ] iOS
- [ ] Mac

### Issues Fixed

Fixes #13356

### Output
| Before| After|
|--|--|
| image | <video src="https://github.com/user-attachments/assets/255c0664-cb71-46c2-a3ec-d5d6c290a5cf"> |

### CODE REVIEW

File: src/Core/src/Platform/Android/MauiMaterialContextThemeWrapper.cs [hunk 1]
```diff
@@ -0,0 +1,26 @@
+using Android.Content;
+using Android.Views;
+
+namespace Microsoft.Maui.Platform;
+
+internal class MauiMaterialContextThemeWrapper : ContextThemeWrapper
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/MauiMaterialContextThemeWrapper.cs:6]: Each call wraps the context in a new `ContextThemeWrapper`. This is lightweight but worth monitoring if frequently recreated during inflation.

**Review by jsuarezruiz — APPROVED** [review]
