### PR TITLE
Fix RTL in AbsoluteLayout

### LINKED ISSUE #6540: RTL is not working in AbsoluteLayout
### Description

Setting FlowDirection as RightToLeft has no effect when using AbsoluteLayout in Android platform. Works fine with WinUI.
[MauiApp6.zip](https://github.com/dotnet/maui/files/8572199/MauiApp6.zip)

MAUI:
Screenshot_1651064557

XAMARIN:
Screenshot_1651064683

### Steps to Reproduce

Run the attached sample

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

ANDROID 12

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rachelkang**
### Description of Change

Fix RTL in AbsoluteLayout. Now, setting RTL on AbsoluteLayout will actually right-align its children. Yay!
Thank you EZ for all the layout knowledge and help

### Issues Fixed

Fixes #6540

### CODE REVIEW

File: src/Core/src/Layouts/AbsoluteLayoutManager.cs [hunk 1]
```diff
@@ -60,11 +60,17 @@ public override Size ArrangeChildren(Rect bounds)
...
+			double top = padding.Top + bounds.Top;
+			double left = padding.Left + bounds.Left;
+			double right = bounds.Right - padding.Right;
 			double availableWidth = bounds.Width - padding.HorizontalThickness;
 			double availableHeight = bounds.Height - padding.VerticalThickness;
 
+			bool leftToRight = AbsoluteLayout.ShouldArrangeLeftToRight();
+
+			// Figure out where we're starting from (the left edge of the padded area, or the right edge)
+			double xPosition = leftToRight ? padding.Left + bounds.Left : bounds.Right - padding.Right;
```
Comment (samhouts) [inline src/Core/src/Layouts/AbsoluteLayoutManager.cs:72]: Does it make sense to reuse `left` and `right` here, since they seem to match?

File: src/Core/tests/UnitTests/Layouts/AbsoluteLayoutManagerTests.cs [hunk 2]
```diff
@@ -445,5 +445,47 @@ public void ChildMeasureRespectsProportionalBounds()
...
+			var childBounds = new Rect(10, 0, 100, 100);
+			SetLayoutBounds(abs, child, childBounds);
+
+			abs.FlowDirection.Returns(FlowDirection.RightToLeft);
+
+			var manager = new AbsoluteLayoutManager(abs);
+			var measuredSize = manager.Measure(double.PositiveInfinity, 100);
+			manager.ArrangeChildren(new Rect(Point.Zero, measuredSize));
+
+			// We expect that the view hould be arranged on the right
```
Comment (samhouts) [inline src/Core/tests/UnitTests/Layouts/AbsoluteLayoutManagerTests.cs:485]:
```suggestion
			// We expect that the view should be arranged on the right
```

Comment (samhouts) [reply src/Core/tests/UnitTests/Layouts/AbsoluteLayoutManagerTests.cs:485]: phew, glad I was here.
TheOfficeMichaelScottGIF

File: src/Core/src/Layouts/AbsoluteLayoutManager.cs (hunk 1 above)
Comment (rachelkang) [reply src/Core/src/Layouts/AbsoluteLayoutManager.cs]: definitely, thanks for catching that!

File: src/Core/tests/UnitTests/Layouts/AbsoluteLayoutManagerTests.cs (hunk 2 above)
Comment (rachelkang) [reply src/Core/tests/UnitTests/Layouts/AbsoluteLayoutManagerTests.cs]: fixed, thank you! 😂

File: src/Core/src/Layouts/AbsoluteLayoutManager.cs [hunk 3]
```diff
@@ -60,11 +60,17 @@ public override Size ArrangeChildren(Rect bounds)
...
+			double top = padding.Top + bounds.Top;
+			double left = padding.Left + bounds.Left;
+			double right = bounds.Right - padding.Right;
 			double availableWidth = bounds.Width - padding.HorizontalThickness;
 			double availableHeight = bounds.Height - padding.VerticalThickness;
 
+			bool leftToRight = AbsoluteLayout.ShouldArrangeLeftToRight();
+
+			// Figure out where we're starting from (the left edge of the padded area, or the right edge)
+			double xPosition = leftToRight ? left : right;
```
Comment (hartez) [inline src/Core/src/Layouts/AbsoluteLayoutManager.cs:72]: Does this value ever get used?

**Review by hartez — CHANGES_REQUESTED** [review]
Remove the xPosition value if it's not needed. Otherwise, looks good!

File: src/Core/src/Layouts/AbsoluteLayoutManager.cs (hunk 3 above)
Comment (rachelkang) [reply src/Core/src/Layouts/AbsoluteLayoutManager.cs]: oops, not anymore! Removed

**Review by hartez — APPROVED** [review]
