### PR TITLE
[Windows] Fix titlebar not persisting when page is swapped

### LINKED ISSUE #27170: [Version 9.0.30] Window.TitleBar is set to null after changing Window.Page at runtime
### Description

If I change the Page property in the created Window the TitleBar is reset and nullified. 

### Steps to Reproduce

Create .net maui app 
Create a Window and create TitleBar 
Set the Page property.

after initialization and the window is created try to change the Page and assign it to another Page.

The TitleBar will disappear

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.30 SR3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.22 SR2.2

### Affected platforms

Windows

### Affected platform versions

1000.26100.36.0

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Foda**
### Description of Change

* Fix titlebar not being transferred when page is swapped
* Fix titlebar leaking when replaced
* 
### Issues Fixed

Fixes #27170

### CODE REVIEW

File: src/Controls/src/Core/TitleBar/TitleBar.cs [hunk 1]
```diff
@@ -256,6 +256,16 @@ public TitleBar()
 			}
 		}
 
+		internal void Cleanup()
```
Comment (PureWeen) [inline src/Controls/src/Core/TitleBar/TitleBar.cs:259]: Can we include a unit test for this one? 

Just inside the Controls.Unit test project?

**Review by PureWeen — CHANGES_REQUESTED** [review]

**Review by PureWeen — CHANGES_REQUESTED** [review]
Playing with this it seems like the TitleBar still disappears? 

tested in the sandbox 

```C#
return new Window(new NavigationPage(new MainPage()))
{
	TitleBar = new TitleBar
	{
		BackgroundColor = Colors.Red,
		ForegroundColor = Colors.White,
		Subtitle = "Subtitle",
	}
};
```

Then in MainPage I swapped out the Page on Window

```XAML
  <VerticalStackLayout>
    <Button Text="me" Clicked="Button_Clicked"></Button>
  </VerticalStackLayout>
```

```C#
	private void Button_Clicked(object sender, EventArgs e)
	{

		this.Window.Page = new MainPage();

    }
```

The TitleBar seems to reset when the page is swapped

**Comment by PureWeen** [comment]
> Playing with this it seems like the TitleBar still disappears?
> 
> tested in the sandbox
> 
> ```cs
> return new Window(new NavigationPage(new MainPage()))
> {
> 	TitleBar = new TitleBar
> 	{
> 		BackgroundColor = Colors.Red,
> 		ForegroundColor = Colors.White,
> 		Subtitle = "Subtitle",
> 	}
> };
> ```
> 
> Then in MainPage I swapped out the Page on Window
> 
> ```
>   <VerticalStackLayout>
>     <Button Text="me" Clicked="Button_Clicked"></Button>
>   </VerticalStackLayout>
> ```
> 
> ```cs
> 	private void Button_Clicked(object sender, EventArgs e)
> 	{
> 
> 		this.Window.Page = new MainPage();
> 
>     }
> ```
> 
> The TitleBar seems to reset when the page is swapped

Nevermind.....
I messed up the branch I was testing on and it didn't have your changes

File: src/Core/src/Platform/Windows/NavigationRootManager.cs [hunk 2]
```diff
@@ -120,7 +146,6 @@ public virtual void Disconnect()
 			}
       
 			SetToolbar(null);
-			SetTitleBar(null, null);
```
Comment (PureWeen) [inline src/Core/src/Platform/Windows/NavigationRootManager.cs:123]: Can we add this call up into the WindowHandler.Disconnect code? 

I think it's still useful to set the TitleBar to null if the handler itself is being disconnected

so we can add it here
image

after the disconnect call

**Review by PureWeen — CHANGES_REQUESTED** [review]

**Review by PureWeen — APPROVED** [review]
