### PR TITLE
Fix iOS/macOS Images not cropped inside of a Frame #6580

### LINKED ISSUE #6580: iOS/macOS Images not cropped inside of a Frame
### Description

Screen Shot 2022-04-27 at 7 03 50 PM

Take https://github.com/dotnet-presentations/dotnet-maui-workshop/tree/main/Finish and run on iOS or mac catalyst

```
                <Frame
                    Grid.RowSpan="2"
                    Grid.Column="1"
                    Margin="0,80,0,0"
                    HeightRequest="160"
                    WidthRequest="160"
                    HorizontalOptions="Center" 
                    Padding="0"
                    CornerRadius="80">
                    <Image
                        Aspect="AspectFill"
                        HeightRequest="160"
                        HorizontalOptions="Center"
                        VerticalOptions="Center"
                        Source="{Binding Monkey.Image}"
                        WidthRequest="160"/>
                </Frame>
```

This should crop like it does on Android/Windows. 

### Steps to Reproduce

See above^

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

All

### Did you find any workaround?

Have to set 

           IsClippedToBounds="True"

This should be consistent though between all platforms

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tj-devel709**
### Description of Change

An image inside a frame on iOS/catalyst would not be clipped to the parent frame as it would on android or windows. This PR makes the default value of Frame.IsClippedToBounds equal to true if it is not set by the user. 

### Issues Fixed

Fixes #6580

### Example
Code to generate the below: https://gist.github.com/tj-devel709/62359798cc3b1b86a81cdb7b57f8ac40

### CODE REVIEW

File: src/Controls/src/Core/BindableObject.cs [hunk 1]
```diff
@@ -589,7 +589,24 @@ BindablePropertyContext CreateAndAddContext(BindableProperty property)
...
 		[MethodImpl(MethodImplOptions.AggressiveInlining)]
-		internal BindablePropertyContext GetContext(BindableProperty property) => _properties.TryGetValue(property, out var result) ? result : null;
+		internal BindablePropertyContext GetContext(BindableProperty property)
+		{
+			var isValueFound = _properties.TryGetValue(property, out var result);
+
+			if (isValueFound)
+				return result;
+
+			// Some properties may not be found due to the dictionary's BindableProperty class key
```
Comment (tj-devel709) [inline src/Controls/src/Core/BindableObject.cs:599]: So I added this here because it seemed that the 'IsClippedToBounds' property that I was looking for inside the _properties dictionary did exist in there, but it was not registered in the TryGetValue call.

The _properties dictionary uses the class BindableProperty for the key and *from what I can tell* it was not finding the property for some reason. I thought about overriding the GetHashCode and Equals methods in the BindableProperty Class but that would be a public facing change and I was not 100% sure if that is what is going on here.

Please let me know if this change is not wanted!

An example of properties found in this foreach loop that were not found by `_properties.TryGetValue(property, out var result)`: 
* ImplicitStyle
* Text
* IsClippedToBounds

Comment (tj-devel709) [reply src/Controls/src/Core/BindableObject.cs:599]: Looks like this caused some other tests to fail so I will just apply it to the IsClippedToBounds property / explore this a little more

File: src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs [hunk 2]
```diff
@@ -120,7 +120,7 @@ public virtual void SetupLayer()
 
 			_actualView.Layer.RasterizationScale = UIScreen.MainScreen.Scale;
 			_actualView.Layer.ShouldRasterize = true;
-			_actualView.Layer.MasksToBounds = Element.IsClippedToBounds;
+			_actualView.Layer.MasksToBounds = Element.IsSet(Controls.Compatibility.Layout.IsClippedToBoundsProperty) ? Element.IsClippedToBounds : true;
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs:123]: It looks like Android has almost the same logic

image

can we consolidate these two calls into an extension method? 

Maybe something like this? 

`bool IsClippedBounds(this Layout layout)`

Also, I didn't see this section on Windows which is curious :-) 
I don't think we should hold up this PR on Windows but I'm wondering why this code isn't on the windows `FrameREnderer`

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs (hunk 2 above)
Comment (tj-devel709) [reply src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs]: Thanks for pointing that out! I didn't notice that! 
I updated the PR to use an extension method for android and ios and will take a further look into windows

**Review by PureWeen — APPROVED** [review]
