### PR TITLE
[iOS] Shell toolbar items

### LINKED ISSUE #18946: Icons in the Shell TitleView and Shell Toolbar items not displayed in iOS
### Description

I am adding icons in the title view and toolbar items, however these arent displayed in iOS but in Android

image

I have attached the github repo for the same to reproduce and also ve

### Steps to Reproduce

1. Create a new .Net MAUI app
2. Add TitleView and ToolbarItems in appshell.xaml
3. with some text and dummy image.

Run the application in iOS simulator

### Link to public reproduction project repository

https://github.com/sabrigo/IconNotShowingIniOS

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15 and up

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

Enabled displaying toolbar items declared in the  `<Shell.ToolbarItems>`

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/18946

|Before|After|
|--|--|
|||

### CODE REVIEW

File: src/Controls/tests/UITests/Tests/Issues/Issue18946.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+	{
+		public override string Issue => "[iOS] Shell Toolbar items not displayed";
+
+		public Issue18946(TestDevice device) : base(device)
+		{}
+
+		[Test]
+		public void ToolbarItemsShouldBeVisible()
+		{
+			this.IgnoreIfPlatforms(new TestDevice[] { TestDevice.Android, TestDevice.Mac, TestDevice.Windows });
```
Comment (jsuarezruiz) [inline src/Controls/tests/UITests/Tests/Issues/Issue18946.cs:17]: Could we enabled the tests for the test of platforms?

Comment (kubaflo) [reply src/Controls/tests/UITests/Tests/Issues/Issue18946.cs]: Sure. Done!

**Comment by carlosxjose** [comment]
When could be this ready to test with nightly builds... ?

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18946.cs [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+	{
+		public override string Issue => "Shell Toolbar items not displayed";
+
+		public Issue18946(TestDevice device) : base(device)
+		{ }
+
+		[Test]
+		public void ToolbarItemsShouldBeVisible()
+		{
+			var label = App.WaitForElement("label");
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18946.cs:18]: The test is failing.

Comment (kubaflo) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18946.cs]: I think it should work now :) I changed it to verify the screenshot because Appium couldn't find the Android toolbar item even though it works

Screenshot_1718131226

**Comment by sabrigo** [comment]
When could be this ready for release?

**Comment by sabrigo** [comment]
@jfversluis / @StephaneDelcroix  any idea when this will be ready?

**Review by jfversluis — APPROVED** [review]

**Comment by sabrigo** [comment]
Is the fix going to be in .NET 9 and not in .NET 8

**Comment by kubaflo** [comment]
@sabrigo yes, the fix will be only in .NET 9

**Comment by sabrigo** [comment]
Can this fix be pushed to .net 8 as well? as .NET 8 is still LTS, shouldn't be covered there as well. Plus, I raised this issue on .NET 8
