### PR TITLE
[XSG] make sure RD are properly inflated, and loaded

### LINKED ISSUE #31571: .NET10-rc1 - XamlSourceGen - Partial method XXX.InitializeComponent()' must have an implementation part because it has accessibility modifiers.
### Description

Using the latest .NET10-rc1 , and trying out the xaml source gen in a new .net MAUI app, I have these errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS8795	Partial method '__Type08BAD333D93A1098.InitializeComponent()' must have an implementation part because it has accessibility modifiers.	Maui10Preview7 (net10.0-android)	C:\P\net9-repros\Maui10Preview7\obj\Debug\net10.0-android\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\Resources_Styles_Colors.xaml.sg.cs	26	
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS8795	Partial method '__Type3F0379CBCFA4A406.InitializeComponent()' must have an implementation part because it has accessibility modifiers.	Maui10Preview7 (net10.0-android)	C:\P\net9-repros\Maui10Preview7\obj\Debug\net10.0-android\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\Resources_Styles_Styles.xaml.sg.cs	26	

```

where the culprits are the Colors.xml files and Styles.xml files ( default )

In order to enable the source gen I applied this:

`<MauiXamlInflator>SourceGen</MauiXamlInflator>`

On my .csproj

### Steps to Reproduce

1. Clone  https://github.com/bcaceiro/net9-repros/tree/main/Maui10Preview7
2. Build
3. See errors

### Link to public reproduction project repository

https://github.com/bcaceiro/net9-repros/tree/main/Maui10Preview7

### Version with bug

10.0.0-rc.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

Not using the feature :)))))

### Relevant log output

```shell

1>------ Build started: Project: Maui10Preview7, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\10.0.100-rc.1.25451.107\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(345,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>Including assemblies for Hot Reload support
1>C:\P\net9-repros\Maui10Preview7\obj\Debug\net10.0-android\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\Resources_Styles_Colors.xaml.sg.cs(26,24,26,43): error CS8795: Partial method '__Type08BAD333D93A1098.InitializeComponent()' must have an implementation part because it has accessibility modifiers.
1>C:\P\net9-repros\Maui10Preview7\obj\Debug\net10.0-android\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\Resources_Styles_Styles.xaml.sg.cs(26,24,26,43): error CS8795: Partial method '__Type3F0379CBCFA4A406.InitializeComponent()' must have an implementation part because it has accessibility modifiers.
1>Done building project "Maui10Preview7.csproj" -- FAILED.
```

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
this fixes the latest known failing test with XSG. 🎉

- fixes #31571

### CODE REVIEW

File: src/Controls/src/SourceGen/InitializeComponentCodeWriter.cs [hunk 1]
```diff
@@ -68,7 +68,9 @@ PrePost newblock() =>
 			if (rootType == null)
 				goto exit;
 
-			var genSwitch = compilation.AssemblyName == "Microsoft.Maui.Controls.Xaml.UnitTests";
+			var generatedDefaultCtor = rootType.Constructors.Any(c => c.Parameters.Length == 0 && c.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, compilation.GetTypeByMetadataName("System.CodeDom.Compiler.GeneratedCodeAttribute"))));
```
Comment (jsuarezruiz) [inline src/Controls/src/SourceGen/InitializeComponentCodeWriter.cs]: Can see this build error:
`C:\a\_work\1\s\src\Controls\tests\Xaml.UnitTests\Generated\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\AppResources_Colors.sgen.xaml.sg.cs(22,24): error CS8795: Partial method '__TypeAEDE0005D2B9C933.InitializeComponent()' must have an implementation part because it has accessibility modifiers. [C:\a\_work\1\s\src\Controls\tests\Xaml.UnitTests\Controls.Xaml.UnitTests.csproj]
`
Transient or related error?

Comment (StephaneDelcroix) [reply src/Controls/src/SourceGen/InitializeComponentCodeWriter.cs]: related

Comment (StephaneDelcroix) [reply src/Controls/src/SourceGen/InitializeComponentCodeWriter.cs]: trying to find a different heuristic

**Review by simonrozsival — APPROVED** [review]
LGTM
