### PR TITLE
[Android] Fix Entry decoration using a custom Background

### LINKED ISSUE #6207: [Android] Setting the background color on entry changes the underline color as well
```C#
new Entry(){ Placeholder = "PlacheHolder", BackgroundColor = Colors.White, TextColor = Colors.Black, PlaceholderColor = new Color(0, 0, 0, 97) }
new Entry(){ Placeholder = "PlacheHolder" },
```

image

### LINKED ISSUE #8067: Entry decoration on Android not correct.
### Description

I am developing a form with Entry boxes. I am trying to make sure the UI experience is identical (or as close as possible) between windows and mobile. I get no element decoration in Android. I have had to change my code I've included below somewhat to get a clear demonstration as I am also trying to get the layout inside a frame which, IMHO, has NEVER worked. See my comments on the following issue: **Content inside a Frame layout is not visible. #7139**

Here is the Android layout. Notice no Entry element decoration...

AndroidFrame

Here is the same code rendered on Windows:

WindowsFrame

There is a faint outline of the control in windows whereas on Android it is completely missing. This will totally confuse a user... I realize this is probably a styling issue, but since you provide Styles.xaml in a new Maui project, I am expecting the controls to behave in similar fashion **ON ALL PLATFORMS** out of the box!

### Steps to Reproduce

1. Create a File -> New for a Maui application.
2. Enter the code provided.
3. Observe......

ViewModel:

```
using CommunityToolkit.Mvvm.ComponentModel;

namespace MauiApp1;

public partial class MainViewModel : ObservableObject {
	public MainViewModel () {
		Terms = "By clicking Agree & Join, you agree to the Moby User Agreement and Privacy Policy.";
	}

	[ObservableProperty]
	public string terms;
	[ObservableProperty]
	private string emailAddress;
	[ObservableProperty]
	private string name;
	[ObservableProperty]
	private string password;
	[ObservableProperty]
	private string passwordConfirmation;
}
```

Xaml:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
	xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	xmlns:local="clr-namespace:MauiApp1"
	x:Class="MauiApp1.MainPage"
	x:DataType="local:MainViewModel"
	Padding="10">
	<Grid>
			<VerticalStackLayout
				MaximumWidthRequest="370"
				Spacing="5">
				<Frame
					Background="{StaticResource MobyBlue}"
					BorderColor="{StaticResource MobyBlue}"
					CornerRadius="8">
					<HorizontalStackLayout
						HorizontalOptions="Center"
						Spacing="3">
						<Image
							Grid.Column="0"
							HeightRequest="36"
							SemanticProperties.Description="Moby application logo"
							Source="moby_logo.png"
							WidthRequest="48" />
						<Label
							Grid.Column="1"
							Margin="10,0,0,0"
							FontFamily="SegoeUiSemibold"
							FontSize="28"
							Text="Moby Sign Up"
							TextColor="White"
							VerticalOptions="Center" />
					</HorizontalStackLayout>
				</Frame>
				<VerticalStackLayout
					HorizontalOptions="Center"
					Margin="0,10,0,0"
					Spacing="3">
					<Label
						Text="Name:" />
					<Entry
						Margin="0,2"
						Placeholder="Enter your name"
						Text="{Binding Name}" />
					<Label
						Text="Email Address:" />
					<Entry
						Margin="0,2"
						Placeholder="Enter your name"
						Text="{Binding Name}" />
					<Label
						Text="Password:" />
					<Entry
						IsPassword="True"
						Margin="0,2"
						Placeholder="Enter your password"
						Text="{Binding Password}" />
					<Label
						Text="Confirm Password:" />
					<Entry
						IsPassword="True"
						Margin="0,2"
						Placeholder="Confirm your password"
						Text="{Binding PasswordConfirmation}" />
					<Label
						FontSize="10"
						HorizontalTextAlignment="Center"
						Margin="10"
						Text="{Binding Terms}" />
					<Button
						Text="Agree &amp; Join" />
					<HorizontalStackLayout
						Margin="0,10,0,0"
						Spacing="5">
						<Label
							Text="Already a Moby member?"
							VerticalTextAlignment="Center" />
						<Button
							Text="Sign In" />
					</HorizontalStackLayout>
				</VerticalStackLayout>
			</VerticalStackLayout>
	</Grid>
</ContentPage>

```

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 12.0 - API 31 (emulator), Windows (net6.0-windows10.0.19041.0)

### Did you find any workaround?

NO...... :-(

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix Entry decoration (underline) on Android using a custom Background.

Screenshot_1656082474

### Issues Fixed

Fixes #8067 
Fixes #6207

### CODE REVIEW

File: src/Core/src/Platform/Android/ViewExtensions.cs [hunk 1]
```diff
@@ -199,6 +203,39 @@ public static void UpdateBackground(this AView platformView, Paint? background)
...
+			if (!paint.IsNullOrEmpty())
+			{
+				// Remove previous background gradient if any
+				if (platformView.Background is MauiDrawable mauiDrawable)
+				{
+					platformView.Background = null;
+					mauiDrawable.Dispose();
+				}
+
+				if (keepPreviousDrawable)
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/ViewExtensions.cs:220]: Is there any reason to not just make this how the default behavior works? The current behavior seems like a bug (especially coming from XF) so I think we can just make this how it works and we don't need an overload. Ideally we'd add an API so users could just set the underline color

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Android/ViewExtensions.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/ViewExtensions.cs:216]: No good reasons, inherited behavior from Xamarin.Forms. @Redth What do you think about this?, should we replace the default behavior?

Comment (hartez) [reply src/Core/src/Platform/Android/ViewExtensions.cs:216]: XF does _not_ change the underline color when the background color changes. However, I believe that's because the Entry in XF is based on `VisualElementRenderer`, so the background being changed is actually the wrapper.

**Review by PureWeen — APPROVED** [review]
