### PR TITLE
[controls] fix memory leak in `VisualElement.Background`

### LINKED ISSUE #12344: VisualElement Background/Shadow `Notify` code creates a strong relationship between the brush and the element
### Description

Overall, we need to create a generalized strategy for handling `Brush` changes. There are 5 or 6 places where we use brushes but currently `Background` and `Shape` are the only ones that have some notification code. 

Currently this is the code we have for `Background` but it's problematic. 

https://github.com/dotnet/maui/blob/cd5dd03f22a590b08ea86bfa127624d645e4979b/src/Controls/src/Core/VisualElement.cs#L246-L268

- The first low hanging fruit issue here is that the `Parent` property probably shouldn't get set for every single type of brush. For example, right now if you have the following code

```C#
new TabbedPage()
{
     Title = "Tabbed Page",
     Background = SolidColorBrush.Green
};
```

That brush is an ImmutableBrush that will be reused everywhere that `SolidColorBrush.Green` is being used. 

This can cause undesirable side effects because an element that's no longer on the screen might be set as the `Parent` of `SolidColorBrush`.  This can cause events to propagate up from the brush to the element that's no longer on the screen. I saw this when running the iOS device tests. Whenever I ran a test for a second time it was causing a threading exception because the previous `TabbedPage` was set as parent on the `ImmutableBrush` which would then propagate up to the previous test run. 

We can easily cover `ImmutableBrush` cases. 

- The second part here that I'm not sure about is if `VisualElement` should subscribe to the `PropertyChanged` event and if `Parent` should be set on any of the Brushes. Since brushes can be reused (StaticResource) this seems like it will cause undesirable behavior. I think we need a different weaker pattern here for propagating brush changes up.

### LINKED ISSUE #13557: CollectionView Windows Memory Leak, Android Laggy scrolling
### Description

I noticed huge memory leak in my app, but seems this is widely spread issue, as it is easy to reproduce even in Monkey Finder
https://github.com/dotnet-presentations/dotnet-maui-workshop.git 

image

Also, scrolling performance is bad on Samsung Galaxy S20 Ultra (12GB RAM) if Data Tepmplate contains Frame, without wrapping with a Grid. (I mean fixing Memory leak on Windows, ruins scrolling performance (by potentional memory) on Android)

### Steps to Reproduce

1. Run Monkey finder on Windows, in release build, [link](https://github.com/dotnet-presentations/dotnet-maui-workshop.git)
2. Click Get Monkeys and see, how memory usage increases up to infinity

### Link to public reproduction project repository

https://github.com/dotnet-presentations/dotnet-maui-workshop.git

### Version with bug

7.0 (current)

### Last version that worked well

-----

### Affected platforms

Android, Windows

### Affected platform versions

Android 9, 12; Windows 11

### Did you find any workaround?

Workaround for Windows memory leak is simple. Remove Grid, that wraps Frame
image

Using this fix for Windows works fine
image
But reduces scrolling performance on Android, and may be causing memory leak (I can not check it for sure)

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Fixes #12344
Fixes #13557
Context: https://github.com/dotnet-presentations/dotnet-maui-workshop

While testing the `Monkey Finder` sample, I found the following scenario causes an issue:

1. Declare a `{StaticResource}` `Brush` at the `Application` level, with a lifetime of the entire application.

2. Set `Background` on an item in a `CollectionView`, `ListView`, etc.

3. Scroll a lot, navigate away, etc.

4. The `Brush` will hold onto any `View`'s indefinitely.

The core problem here being `VisualElement` does:

```cs
    void NotifyBackgroundChanges()
    {
        if (Background is ImmutableBrush)
            return;

        if (Background != null)
        {
            Background.Parent = this;
            Background.PropertyChanged += OnBackgroundChanged;

            if (Background is GradientBrush gradientBrush)
                gradientBrush.InvalidateGradientBrushRequested += InvalidateGradientBrushRequested;
        }
    }
```
If no user code sets `Background` to `null`, these events remain subscribed.

To fix this:

1. Create a `WeakNotifyCollectionChangedProxy` type for event subscription.

2. Don't set `Background.Parent = this`

## General Cleanup ##

Through doing other fixes related to memory leaks & C# events, we've started to gain a collection of `WeakEventProxy`-related types.

I created some core `internal` types to be reused:

* `abstract WeakEventProxy<TSource, TEventHandler>`
* `WeakNotifyCollectionChangedProxy`

The following classes now make use of these new shared types:

* `BindingExpression`
* `BindableLayout`
* `ListProxy`
* `VisualElement`

This should hopefully reduce mistakes and reuse code in this area.

## Concerns ##

Since, we are no longer doing:

    Background.Parent = this;

This is certainly a behavior change. It is now replaced with:

    SetInheritedBindingContext(Background, BindingContext);

I had to update one unit test that was asserting `Background.Parent`, which can assert `Background.BindingContext` instead.

As such, this change is definitely sketchy and I wouldn't backport to .NET 7 immediately. We might test it out in a .NET 8 preview first.

### CODE REVIEW

File: src/Controls/tests/Core.UnitTests/BrushUnitTests.cs [hunk 1]
```diff
@@ -84,7 +84,6 @@ public void TestBrushParent()
 
 			parent.Background = linearGradientBrush;
 
-			Assert.Same(parent, parent.Background.Parent);
 			Assert.Same(context, parent.Background.BindingContext);
```
Comment (jonathanpeppers) [inline src/Controls/tests/Core.UnitTests/BrushUnitTests.cs:87]: This is a behavior change that we don't set `Background.Parent` anymore.

However, `Background.BindingContext` is set, so you should be able to use `{Binding}` such as:

```xml
<Label>
  <Label.Background>
    <SolidColorBrush Color="{Binding Foo}" />
  </Label.Background>
</Label>
```

And the `Label`'s `BindingContext` should pass on to the `SolidColorBrush`.

File: src/Controls/src/Core/Internals/MaybeNullWhenAttribute.cs [hunk 2]
```diff
@@ -0,0 +1,152 @@
...
+	[AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, Inherited = false)]
+	internal sealed class AllowNullAttribute : Attribute { }
+
+	/// <summary>Specifies that null is disallowed as an input even if the corresponding type allows it.</summary>
+	[AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, Inherited = false)]
+	internal sealed class DisallowNullAttribute : Attribute { }
+
+	/// <summary>Specifies that an output may be null even if the corresponding type disallows it.</summary>
+	[AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property | AttributeTargets.ReturnValue, Inherited = false)]
+	internal sealed class MaybeNullAttribute : Attribute { }
```
Comment (jonathanpeppers) [inline src/Controls/src/Core/Internals/MaybeNullWhenAttribute.cs:23]: I got this from:

https://source.dot.net/#Microsoft.Build.Framework/NullableAttributes.cs,68093cc4b5713519

So we can use these NRT annotations in a `netstandard2.0` library.

**Review by StephaneDelcroix — APPROVED** [review]

File: src/Controls/tests/Core.UnitTests/BrushUnitTests.cs (hunk 1 above)
Comment (mattleibow) [reply src/Controls/tests/Core.UnitTests/BrushUnitTests.cs:87]: Yeah, this was always interesting as a single brush can be used for multiple views. Is there anything that needs access to the brush/stroke's parent? If there is, then this is really interesting as who wins? Last one? First one?

File: src/Controls/src/Core/Internals/MaybeNullWhenAttribute.cs (hunk 2 above)
Comment (mattleibow) [reply src/Controls/src/Core/Internals/MaybeNullWhenAttribute.cs:23]: We did bad things in essentials:

```cs
#if !NETSTANDARD
		[return: NotNullIfNotNull("defaultValue")]
#endif
```

One day this can all go away and we use net6/7 everywhere.

File: src/Controls/tests/Core.UnitTests/BrushUnitTests.cs (hunk 1 above)
Comment (mattleibow) [reply src/Controls/tests/Core.UnitTests/BrushUnitTests.cs:87]: I am also wondering about that binding context... If I set one brush on 2 views, is it just going to overwrite the BC to the last one? Maybe that is just how it works?

**Comment by mattleibow** [comment]
Looks good to me, but maybe a third @PureWeen can hit the merge if there are no weirdos in here?

File: src/Controls/src/Core/VisualElement.cs [hunk 3]
```diff
@@ -249,44 +250,78 @@ static void OnTransformChanged(BindableObject bindable, object oldValue, object
...
 				return;
 
-			if (Background != null)
+			if (background != null)
 			{
-				Background.Parent = this;
-				Background.PropertyChanged += OnBackgroundChanged;
-
-				if (Background is GradientBrush gradientBrush)
-					gradientBrush.InvalidateGradientBrushRequested += InvalidateGradientBrushRequested;
```
Comment (mattleibow) [inline src/Controls/src/Core/VisualElement.cs:263]: What happened to this event?

File: src/Controls/src/Core/VisualElement.cs [hunk 4]
```diff
@@ -249,44 +250,78 @@ static void OnTransformChanged(BindableObject bindable, object oldValue, object
...
+				{
+					s.PropertyChanged -= OnBackgroundChanged;
+
+					if (s is GradientBrush g)
+						g.PropertyChanged -= OnBackgroundChanged;
+				}
+
+				source.PropertyChanged += OnBackgroundChanged;
+				if (source is GradientBrush gradientBrush)
+					gradientBrush.PropertyChanged += OnBackgroundChanged;
```
Comment (mattleibow) [inline src/Controls/src/Core/VisualElement.cs:309]: This appears to be a double subscription? Should this have been the other event? If so, maybe we don't need the generic property event if this is a gradient?

**Review by mattleibow — COMMENTED** [review]
Just spotted something, not sure if I am missing it or it is a thing...

File: src/Controls/src/Core/VisualElement.cs (hunk 4 above)
Comment (jonathanpeppers) [reply src/Controls/src/Core/VisualElement.cs]: `InvalidateGradientBrushRequested` looks to be fired when `CollectionChanged` fires from `GradientStopCollection`.

**Review by mattleibow — APPROVED** [review]
