### PR TITLE
[iOS/MacCatalyst] Fix: Setting SelectedItem Programmatically and Then Immediately Setting ItemsSource to Null Causes a Crash

### LINKED ISSUE #29937: [iOS/MacCatalyst] Setting SelectedItem Programmatically and Then Immediately Setting ItemsSource to Null Causes a Crash
### Description

In an iOS and MacCatalyst, programmatically setting the `SelectedItem` property of a `CollectionView` to a valid item and then immediately setting the`ItemsSource` property to `null` results in a crash (`ObjCRuntime.ObjCException`)

### Steps to Reproduce

1. Create a CollectionView in an iOS or MacCatalyst app with a valid ItemsSource.
2. Programmatically set the SelectedItem to an item from the ItemsSource.
3. Immediately set the ItemsSource to null.
4. Observe the application crash.

### Link to public reproduction project repository

https://github.com/bhavanesh2001/maui-bugs/tree/collectionview_crash_2

### Version with bug

9.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell
An unhandled exception of type 'ObjCRuntime.ObjCException' occurred in Microsoft.MacCatalyst.dll
   at ObjCRuntime.Messaging.void_objc_msgSendSuper_NativeHandle_bool_UIntPtr(IntPtr receiver, IntPtr selector, NativeHandle arg1, Byte arg2, UIntPtr arg3)
   at UIKit.UICollectionView.SelectItem(NSIndexPath indexPath, Boolean animated, UICollectionViewScrollPosition scrollPosition)
   at Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewController`1.<>c__DisplayClass4_0.<SelectItem>b__0(Boolean _) in
```

### PR DESCRIPTION
**Pull request by bhavanesh2001**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Description of Change
Fixes a crash  in iOS/MacCatalyst when setting `SelectedItem` in a `CollectionView` and then nullifying `ItemsSource`. The issue was due to a race condition.

In `PerformBatchUpdates`, verified ItemsSource reference, recalculated selectedItem index, and validated item before calling `CollectionView.SelectItem`.

### Issues Fixed

Fixes #29937

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs [hunk 1]
```diff
@@ -45,23 +45,38 @@ public override void ItemDeselected(UICollectionView collectionView, NSIndexPath
 		// Called by Forms to mark an item selected 
 		internal void SelectItem(object selectedItem)
 		{
-			if (ItemsView?.ItemsSource is null)
-			{
-				return;
-			}
-
+			var originalSource = ItemsView.ItemsSource;
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs]: It's probably excessive but can we set this via pattern matching just to keep the null check in place?

File: src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs [hunk 2]
```diff
@@ -57,6 +57,26 @@ internal void SelectItem(object selectedItem)
 				// Ensure the selected index is updated after the collection view's items generation is completed
 				CollectionView.PerformBatchUpdates(null, _ =>
 				{
+					// Exit if the ItemsSource reference no longer matches the one captured at invocation.
+					if (!ReferenceEquals(ItemsView.ItemsSource, originalSource))
```
Comment (sheiksyedm) [inline src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs:67]: @bhavanesh2001  This issues could likely be resolved by using UICollectionView native calls instead of relying on 3+ managed method calls with object comparisons. I hope below fix will handle the edge cases where the item source is null or index position is removed or changed after the batch updates call. 

@PureWeen What do you think?

image

Comment (bhavanesh2001) [reply src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs:67]: I think native index path validity doesn’t guarantee the item hasn’t changed. When items are inserted, removed, or reordered, the index might still exist but point to a different item. The managed checks avoid that by making sure the data source and the selected item still match before applying the selection.

File: src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs [hunk 3]
```diff
@@ -57,6 +57,26 @@ internal void SelectItem(object selectedItem)
...
+					{
+						return;
+					}
+
+					// Recalculate the index for the selectedItem now that the collection may have changed.(Adding, deleting etc..)
+					var updatedIndex = GetIndexForItem(selectedItem);
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs:73]: I think we need an additional check in here to see if `DisposeItemsSource();` has been called

I'm working on getting
https://github.com/dotnet/maui/pull/29281

Green on the net10 branch and I'm noticing that the navigation to CollectionView Gallery is crashing

The fix on this PR almost works but the problem is is that the handlers gets "Disconnected"

image

Which sets the ItemSource property on the Controller to an EmptySource

Which causes this line to crash

Which I think would also be fixed by your round trip fixes :-/

**Review by PureWeen — CHANGES_REQUESTED** [review]

**Review by PureWeen — APPROVED** [review]
Great stuff as always @bhavanesh2001 !!!
