### PR TITLE
[.NET10] Obsolete Page.IsBusy API

### LINKED ISSUE #29925: [iOS, Windows] Busy Indicator fails to appear when Page.IsBusy is set to true
### Description

On both iOS and Windows platforms, setting Page.IsBusy = true does not result in the display of a busy/loading indicator, unlike on Android where the indicator is shown as expected.

### Steps to Reproduce

1. Create a new MAUI ContentPage.
2. Set IsBusy = true in a button click.
3. Run the app on iOS or Windows.
4. Observe that no busy indicator appears.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">

    <StackLayout>
        <Label Text="Welcome to .NET MAUI!"
               Margin="0, 20"
               FontSize="24"
               VerticalOptions="Center"
               HorizontalOptions="Center"/>

        <Button Text="Set IsBusy to true"
                x:Name="IsBusyButton"
                Margin="0,20"
                VerticalOptions="Center"
                HorizontalOptions="Center"
                Clicked="Button_SetIsBusy"/>
    </StackLayout>

</ContentPage>

```

```C#
public partial class MainPage : ContentPage
{

	public MainPage()
	{
		InitializeComponent();
	}

	void Button_SetIsBusy(object sender, EventArgs e)
	{
		IsBusy = !IsBusy;
		IsBusyButton.Text = IsBusy ? "Set IsBusy to false" : "Set IsBusy to true";
	}
}
```

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.70 SR7

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Tamilarasan-Paranthaman**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Description of Change

- I have marked the Page.IsBusy API as [Obsolete] in .NET 10 and added a message indicating that it will be removed in .NET 11.

### Issues Fixed

Fixes #30155

### CODE REVIEW

**Review by PureWeen — CHANGES_REQUESTED** [review]
@Tamilarasan-Paranthaman I think we're going to go the direction of obsoleting this API 

Can you obsolete the Page.IsBusy API in NET10 and just indicate that we are going to remove it in NET11

**Comment by Tamilarasan-Paranthaman** [comment]
> @Tamilarasan-Paranthaman I think we're going to go the direction of obsoleting this API
> 
> Can you obsolete the Page.IsBusy API in NET10 and just indicate that we are going to remove it in NET11

@PureWeen, I have marked the `Page.IsBusy` API as obsolete and added a message indicating that it will be removed in `.NET 11`. I have updated the target branch to .NET 10.

File: src/Controls/src/Core/Page/Page.cs [hunk 1]
```diff
@@ -655,13 +657,15 @@ public void SendAppearing()
 
 			_hasAppeared = true;
 
+#pragma warning disable CS0618 // TODO: Remove this API in .NET 11.
```
Comment (mattleibow) [inline src/Controls/src/Core/Page/Page.cs]: This should be a github issue with a link in the source.

File: src/Controls/src/Core/Page/Page.cs [hunk 2]
```diff
@@ -56,6 +56,7 @@ public partial class Page : VisualElement, ILayout, IPageController, IElementCon
 		public static readonly BindableProperty BackgroundImageSourceProperty = BindableProperty.Create(nameof(BackgroundImageSource), typeof(ImageSource), typeof(Page), default(ImageSource));
 
 		/// <summary>Bindable property for <see cref="IsBusy"/>.</summary>
+		[Obsolete("Page.IsBusy has been deprecated and will be removed in .NET 11")]
```
Comment (mattleibow) [inline src/Controls/src/Core/Page/Page.cs:59]: @davidortinau do we need to put links to docs in here? Maybe an aka.ms/maui/deprecations/isbusy and then we say why in a gh issue or something? Or link to release notes. The aka can be changed once the notes are created.

File: src/Controls/src/Core/Page/Page.cs [hunk 3]
```diff
@@ -684,8 +688,10 @@ public void SendDisappearing()
 
 			_hasAppeared = false;
 
+#pragma warning disable CS0618 // TODO: Remove this API in .NET 11.
```
Comment (mattleibow) [inline src/Controls/src/Core/Page/Page.cs]: Link to issue for removal.

File: src/Controls/src/Core/Page/Page.cs [hunk 4]
```diff
@@ -746,7 +752,9 @@ void OnPageBusyChanged()
 		{
 			if (!_hasAppeared)
 				return;
+#pragma warning disable CS0618 // TODO: Remove this API in .NET 11.
```
Comment (mattleibow) [inline src/Controls/src/Core/Page/Page.cs]: Link to issue

**Review by mattleibow — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Page/Page.cs (hunk 3 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Page/Page.cs]: Agree, create one if not exists.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Need to update the PageTests. With the changes we have a build error:
```
C:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\Page\PageTests.cs(90,4): error CS0618: 'Page.IsBusy' is obsolete: 'Page.IsBusy has been deprecated and will be removed in .NET 11' [C:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net10.0-windows10.0.19041.0]
C:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\Page\PageTests.cs(90,4): error CS0618: 'Page.IsBusy' is obsolete: 'Page.IsBusy has been deprecated and will be removed in .NET 11' [C:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net10.0-android]
C:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\Page\PageTests.cs(90,4): error CS0618: 'Page.IsBusy' is obsolete: 'Page.IsBusy has been deprecated and will be removed in .NET 11' [C:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net10.0-windows10.0.20348.0]
    3 Error(s)
```

File: src/Controls/src/Core/Page/Page.cs (hunk 3 above)
Comment (Tamilarasan-Paranthaman) [reply src/Controls/src/Core/Page/Page.cs]: @mattleibow / @jsuarezruiz, I have created a new issue report https://github.com/dotnet/maui/issues/30155 for this and linked it.

File: src/Controls/src/Core/Page/Page.cs (hunk 1 above)
Comment (Tamilarasan-Paranthaman) [reply src/Controls/src/Core/Page/Page.cs]: Done

File: src/Controls/src/Core/Page/Page.cs (hunk 4 above)
Comment (Tamilarasan-Paranthaman) [reply src/Controls/src/Core/Page/Page.cs]: Done

**Comment by Tamilarasan-Paranthaman** [comment]
> Need to update the PageTests. With the changes we have a build error:
> 
> ```
> C:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\Page\PageTests.cs(90,4): error CS0618: 'Page.IsBusy' is obsolete: 'Page.IsBusy has been deprecated and will be removed in .NET 11' [C:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net10.0-windows10.0.19041.0]
> C:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\Page\PageTests.cs(90,4): error CS0618: 'Page.IsBusy' is obsolete: 'Page.IsBusy has been deprecated and will be removed in .NET 11' [C:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net10.0-android]
> C:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\Page\PageTests.cs(90,4): error CS0618: 'Page.IsBusy' is obsolete: 'Page.IsBusy has been deprecated and will be removed in .NET 11' [C:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net10.0-windows10.0.20348.0]
>     3 Error(s)
> ```

@jsuarezruiz, the build error has been resolved.

**Review by PureWeen — CHANGES_REQUESTED** [review]
can you rebase this PR ? We need some of the newer commits on net10.0 so this will run

**Comment by Tamilarasan-Paranthaman** [comment]
> can you rebase this PR ? We need some of the newer commits on net10.0 so this will run

@PureWeen, The PR has been rebased.

File: src/Controls/src/Core/Page/Page.cs [hunk 5]
```diff
@@ -655,13 +657,15 @@ public void SendAppearing()
 
 			_hasAppeared = true;
 
+#pragma warning disable CS0618 // TODO: Remove this API in .NET 11. Issue Link: https://github.com/dotnet/maui/issues/30155
 			if (IsBusy)
 			{
 				if (IsPlatformEnabled)
 					Window.AlertManager.RequestPageBusy(this, true);
 				else
 					_pendingActions.Add(() => Window.AlertManager.RequestPageBusy(this, true));
```
Comment (mattleibow) [inline src/Controls/src/Core/Page/Page.cs:666]: This RequestPageBusy should also be obsolete since it is the thing that does the work.

We also need to make sure we didn't make it public in the last release when we did the alert manager and messaging center changes.

**Review by mattleibow — CHANGES_REQUESTED** [review]

**Comment by mattleibow** [comment]
Sorry to the request changes so late. No idea how I missed the method

File: src/Controls/src/Core/Page/Page.cs (hunk 5 above)
Comment (Tamilarasan-Paranthaman) [reply src/Controls/src/Core/Page/Page.cs:666]: @mattleibow, #27888 (AlertManager PR) has been merged, and I have already rebased this PR. Since [AlertManager](https://github.com/dotnet/maui/blob/fe7e229cdf61eda6a7e2d963ae468a32ff96d9ea/src/Controls/src/Core/Platform/AlertManager/AlertManager.cs#L7) is an internal class in `Microsoft.Maui.Controls.Platform`, `RequestPageBusy` is not publicly exposed. Should we still mark it as obsolete?

Comment (mattleibow) [reply src/Controls/src/Core/Page/Page.cs:666]: I think so. Having the alert manager have a feature that we are removing does not make sense.

Comment (Tamilarasan-Paranthaman) [reply src/Controls/src/Core/Page/Page.cs:666]: @mattleibow, okay, I have marked the RequestPageBusy method as obsolete.

**Review by rmarinho — DISMISSED** [review]

**Review by mattleibow — CHANGES_REQUESTED** [review]
The `RequestPageBusy` on `IAlertManagerSubscription` also needs to be obsolete - and all implementing things. This should be viral to not only help us remove it, but prevent accidental usage.

**Comment by Tamilarasan-Paranthaman** [comment]
> RequestPageBusy

@mattleibow, I have now marked the `OnPageBusy` method in `IAlertManagerSubscription` and its implementation in `AlertRequestHelper` as obsolete. The `RequestPageBusy` in `AlertManager` was already updated earlier. Could you please check and let me know if I missed anything? Thanks

File: src/Controls/src/Core/Platform/AlertManager/AlertManager.Windows.cs [hunk 6]
```diff
@@ -32,6 +32,7 @@ internal AlertRequestHelper(Window virtualView, UI.Xaml.Window platformView)
 
 			public UI.Xaml.Window PlatformView { get; }
 
+			// TODO: This method is obsolete in .NET 10 and will be removed in .NET11.
```
Comment (rmarinho) [inline src/Controls/src/Core/Platform/AlertManager/AlertManager.Windows.cs:35]: Why dont add ?

```
[Obsolete("This method is obsolete in .NET 10 and will be removed in .NET11.")]
```

Comment (Tamilarasan-Paranthaman) [reply src/Controls/src/Core/Platform/AlertManager/AlertManager.Windows.cs:35]: @rmarinho, I have already marked this method as `Obsolete` in the shared class (**[AlertRequestHelper](https://github.com/dotnet/maui/blob/9be40fbae67e9de433e550bc8072c27a90e79c80/src/Controls/src/Core/Platform/AlertManager/AlertManager.cs#L89)**), where the partial method is declared. If I also add Obsolete in the platform-specific implementation, it results in a `duplicate attribute error`, which is why I added a comment instead.

Could you please confirm if it’s acceptable to mark this method as Obsolete in the shared declaration, or should it be applied only in the platform-specific implementation instead?

**Review by rmarinho — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]
