### PR TITLE
Wire up scene life cycle events

### LINKED ISSUE #9476: Missing LifeCycle events for SceneDelegate on iOS and MacCatalyst
### Description

# MauiSceneLifecycleRepro 

## Sample Code : https://github.com/xamcat/MauiSceneLifecycleRepro

Looking at Apple's [UISceneDelegate Documentation](https://developer.apple.com/documentation/uikit/uiscenedelegate) and comparing it to current .NET MAUI implementation of [MAUISceneDelegate](https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/iOS/MauiUISceneDelegate.cs), there are a few missing UISceneDelegate Lifecycle events. 

## Expected Behavior

All Life Cycle events for SceneDelegate to fire :

- scene(_:willConnectTo:options:)

-  sceneDidDisconnect(_:)

- sceneDidBecomeActive(_:)
	
- sceneWillResignActive(_:)
	
- sceneWillEnterForeground(_:)
	
- sceneDidEnterBackground(_:)

- sceneWilLConnect(_:)

## Current Behavior

Only 2 of the implemented life cycle events work,

- WillConnect
	
- DidDisconnect

other life cycle events do not fire. 

### Steps to Reproduce

1. Open attached Reproduction sample
2. Start Debugging MacCatalyst TargetFramework
3. Click on "Open new Window" button in the sample
4. Check Application Output window

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 13 and up

### Did you find any workaround?

No workarounds found yet.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

When we added scenes we didn't add the relevant life cycle hooks related to scenes. This means that most of the xplat window events on iOS currently aren't firing

### Issues Fixed

Fixes #9476 

#### Maui.Core

```C#
namespace Microsoft.Maui.LifecycleEvents
{
	public static class iOSLifecycle
	{
		// Scene
		public delegate void SceneWillEnterForeground(UIScene scene);
		public delegate void SceneOnActivated(UIScene scene);
		public delegate void SceneOnResignActivation(UIScene scene);
		public delegate void SceneDidEnterBackground(UIScene scene);
		public delegate bool SceneOpenUrl(UIScene scene, NSSet<UIOpenUrlContext> urlContexts);
		public delegate bool SceneContinueUserActivity(UIScene scene, NSUserActivity userActivity);
		public delegate void SceneWillContinueUserActivity(UIScene scene, string userActivityType);
		public delegate void SceneDidFailToContinueUserActivity(UIScene scene, string userActivityType, NSError error);
		public delegate void SceneDidUpdateUserActivity(UIScene scene, NSUserActivity userActivity);
		public delegate void SceneRestoreInteractionState(UIScene scene, NSUserActivity stateRestorationActivity);
	}
}
```
```C#
namespace Microsoft.Maui
{
	[System.Runtime.Versioning.SupportedOSPlatform("ios13.0")]
	[System.Runtime.Versioning.SupportedOSPlatform("tvos13.0")]
	public class MauiUISceneDelegate : UIResponder, IUIWindowSceneDelegate
	{
		[Export("sceneWillEnterForeground:")]
		public virtual void WillEnterForeground(UIScene scene);

		[Export("sceneDidBecomeActive:")]
		public virtual void OnActivated(UIScene scene);

		[Export("sceneWillResignActive:")]
		public virtual void OnResignActivation(UIScene scene);

		[Export("sceneDidEnterBackground:")]
		public virtual void DidEnterBackground(UIScene scene) ;

		[Export("scene:openURLContexts:")]
		public virtual bool OpenUrl(UIScene scene, NSSet<UIOpenUrlContext> urlContexts);

		[Export("scene:continueUserActivity:")]
		public virtual bool ContinueUserActivity(UIScene scene, NSUserActivity userActivity);

		[Export("scene:willContinueUserActivityWithType:")]
		public void WillContinueUserActivity(UIScene scene, string userActivityType);

		[Export("scene:didFailToContinueUserActivityWithType:error:")]
		public void DidFailToContinueUserActivity(UIScene scene, string userActivityType, NSError error);


		[Export("scene:didUpdateUserActivity:")]
		public void DidUpdateUserActivity(UIScene scene, NSUserActivity userActivity);

		[Export("scene:restoreInteractionStateWithUserActivity:")]
		public void RestoreInteractionState(UIScene scene, NSUserActivity stateRestorationActivity);
```

### CODE REVIEW

**Review by jsuarezruiz — APPROVED** [review]

File: src/Core/src/Platform/iOS/UIApplicationExtensions.cs [hunk 1]
```diff
@@ -72,6 +72,11 @@ internal static UIEdgeInsets GetSafeAreaInsetsForWindow(this UIApplication appli
 			}
 #pragma warning restore CA1416
 
+			if (!OperatingSystem.IsIOSVersionAtLeast(13))
+				return null;
+			else if (windowScene.Delegate is MauiUISceneDelegate sd)
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/UIApplicationExtensions.cs:77]: I think you can cast to `IUIWindowSceneDelegate` instead as that is where the window property comes from.

Comment (PureWeen) [reply src/Core/src/Platform/iOS/UIApplicationExtensions.cs]: Nice! Updated all the code to use `IUIWindowSceneDelegate.GetWindow()` instead

**Review by mattleibow — APPROVED** [review]
