### PR TITLE
[iOS][CV2] Fix CollectionView renders large empty space at bottom of view

### LINKED ISSUE #17799: [iOS] [MacCatalyst] CollectionView renders large empty space at bottom of view
### Description

Scrolling to the bottom of a CollectionView reveals a large empty space:

image

### Steps to Reproduce

1. Run recipeSearch repo on rc2
2. Deploy to iPhone 14 Pro Max simulator
3. Click on "Breakfast" button
4. Scroll to the bottom of the CollectionView

I have seen this issue in the past, and think it may? have been fixed. If it was fixed, then this is a regression, because I'm seeing it again. Needs to be validated. 

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, MacCatalyst

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #33201: [iOS/Mac] CollectionView2 EmptyView takes up large horizontal space even when the content is small
### Description

While testing the issues, I found that in CollectionView2 in both iOS and Mac, it takes large horizontal space

### CollectionView 1
Image

### CollectionView2
Image

### Steps to Reproduce

Repro the issue using the below one in hostapp
https://github.com/dotnet/maui/blob/main/src/Controls/tests/TestCases.HostApp/Issues/Issue27229.xaml

### Link to public reproduction project repository

https://github.com/dotnet/maui/blob/main/src/Controls/tests/TestCases.HostApp/Issues/Issue27229.xaml

### Version with bug

10.0.20

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 18, Mac 26

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by devanathan-vaithiyanathan**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue Details
In CV2, when there are no items, the CollectionView becomes horizontally scrollable. This issue is not seen in CV1.

### Description of Change

Overrode CollectionViewContentSize to return CGSize.Empty when no items are present, preventing unwanted scrolling.

### Issues Fixed

Fixes #17799 
Fixes #33201

### Regarding Test case
For this case, it's not possible to write a test because the scrollbar does not appear during initial loading. It only becomes visible when a scroll action is performed, and even then, it remains visible only for a few seconds.

**Tested the behavior in the following platforms.**
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

| Before  | After  |
|---------|--------|
| **iOS**<br> <video src="https://github.com/user-attachments/assets/b40d9b89-c5d7-41f0-bd26-0510f2a0547f" width="300" height="600"> | **iOS**<br> <video src="https://github.com/user-attachments/assets/5aaba964-6999-43eb-88d8-43e95deca353" width="300" height="600"> |

### CODE REVIEW

**Review by PureWeen — CHANGES_REQUESTED** [review]
Can you add a uitest?

**Comment by devanathan-vaithiyanathan** [comment]
> Can you add a uitest?

@PureWeen,  This issue occurs only when a CollectionView with no items is able to scroll horizontally. It's not feasible to write a test because the scrollbar does not appear during the initial load. It only becomes visible after a scroll action and remains visible for only a few seconds.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
The changes impact some tests 
image
Mostly, slightly moved header in all these tests. Could you review it?

**Comment by devanathan-vaithiyanathan** [comment]
> The changes impact some tests image Mostly, slightly moved header in all these tests. Could you review it?

@jsuarezruiz , Thanks for the review!  Yes, the failures were due to my earlier fix. I’ve modified the fix and now all the tests are passing.

File: src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs [hunk 1]
```diff
@@ -462,6 +467,39 @@ public override CGPoint TargetContentOffset(CGPoint proposedContentOffset, CGPoi
...
 		}
 
+		public override CGSize CollectionViewContentSize
+		{
+			get
+			{
+				if (CollectionView != null)
+				{
+					var numberOfSections = CollectionView.NumberOfSections();
+					for (nint section = 0; section < numberOfSections; section++)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs]: This loops through all sections every time ContentSize is accessed. Can add Caching to prevent repeated calculations?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
About creating a tests. Can you try the following?

- Create a sample where reproduce the Issue.
- Include a Label where update the scroll `HorizontalOffset` value based on the CollectionView `Scrolled` event.
- Create a test where can check that value.

**Comment by devanathan-vaithiyanathan** [comment]
> About creating a tests. Can you try the following?
> 
> * Create a sample where reproduce the Issue.
> * Include a Label where update the scroll `HorizontalOffset` value based on the CollectionView `Scrolled` event.
> * Create a test where can check that value.

@jsuarezruiz , 
Thanks for the suggestion. I tried implementing the approach, but the test isn’t feasible in this case since the issue only occurs when CollectionView.ItemsSource is null. In that state, scrolling is possible but the Scrolled event doesn’t get triggered, so the suggested approach doesn’t work.

File: src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs (hunk 1 above)
Comment (devanathan-vaithiyanathan) [reply src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs]: @jsuarezruiz ,
The content caching approach was breaking some existing behavior. I’ve modified the fix to remove the loop through sections. Now, if the section contains items, it returns the base ContentSize; otherwise, it returns CGSize.Empty.

**Comment by jsuarezruiz** [comment]
@devanathan-vaithiyanathan Could you rebase and fix the conflict?

**Review by jsuarezruiz — COMMENTED** [review]
@devanathan-vaithiyanathan Could you fix the conflicts? Thanks in advance.

**Comment by devanathan-vaithiyanathan** [comment]
> @devanathan-vaithiyanathan Could you fix the conflicts? Thanks in advance.

@jsuarezruiz , I've resolved the branch conflicts

**Comment by rmarinho** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Update LayoutFactory2.cs</strong> · <a href="https://github.com/dotnet/maui/commit/9700f578feea468117eee74d88b448ca5b53b53e"><code>9700f57</code></a></summary>

---

**Issue:** #17799 - [iOS/MacCatalyst] CollectionView renders large empty space at bottom of view
**Related:** #33201 - [iOS/Mac] CollectionView2 EmptyView takes up large horizontal space even when the content is small
**Platforms Affected:** iOS, MacCatalyst (Items2 handler only)
**Files Changed:** 1 implementation file (`src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs`)
**Milestone:** .NET 10 SR5

### Summary

PR #31215 fixes CollectionView2 on iOS/MacCatalyst displaying large empty/scrollable space when `ItemsSource` is null or empty. Two linked issues:
- **#17799**: Large empty space at the bottom of a vertical CollectionView
- **#33201**: CollectionView2 EmptyView takes large horizontal space

### Root Cause (from PR)

In CV2 (Items2 handler), `UICollectionViewCompositionalLayout.CollectionViewContentSize` returns a non-zero size even when there are no items, causing UIKit to reserve scrollable space for non-existent content.

### Fix Approach

Override `CollectionViewContentSize` in `CustomUICollectionViewCompositionalLayout` to return `CGSize.Empty` when:
- No global headers/footers
- No group headers/footers  
- First section has no items

To provide `_groupingInfo` and `_headerFooterInfo` to the override, added two parameters to the `CustomUICollectionViewCompositionalLayout` constructor.

### PR Discussion Summary

| Topic | Detail |
|-------|--------|
| Test requests | @PureWeen and @jsuarezruiz requested UI test |
| Author response | Tests not feasible: scrollbar only shows after manual scroll and disappears after a few seconds; `Scrolled` event doesn't fire when ItemsSource is null |
| Implementation evolution | Initial loop-through-sections → simplified to first-section check per @jsuarezruiz feedback |
| Existing test impact | Initial fix caused minor header position shifts in existing tests; revised fix passes all tests |
| Conflicts | Author rebased twice per reviewer requests |

### Code Review Thread

| File:Line | Reviewer | Comment | Resolution |
|-----------|----------|---------|------------|
| LayoutFactory2.cs | @jsuarezruiz | Loop through sections on every ContentSize access - add caching? | ✅ RESOLVED: Simplified to first-section check only |

### Related Test Files

- `Issue27229.cs` test exists but is **disabled** (wrapped in `#if TEST_FAILS_ON_ANDROID && TEST_FAILS_ON_IOS && TEST_FAILS_ON_CATALYST`) with comment explicitly citing Issue #33201 as the reason for disabling
- No dedicated test files for issues #17799 or #33201

### Fix Candidates

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #31215 | Override CollectionViewContentSize to return CGSize.Empty when no items present; pass groupingInfo/headerFooterInfo to constructor | ⏳ PENDING (Gate) | `LayoutFactory2.cs` (+34/-3) | Original PR - iOS/MacCatalyst Items2 handler only |

</details>

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Update LayoutFactory2.cs</strong> · <a href="https://github.com/dotnet/maui/commit/9700f578feea468117eee74d88b448ca5b53b53e"><code>9700f57</code></a></summary>

---

**Result:** ⚠️ SKIPPED (No active automated tests)
**Platform:** iOS (specified)
**Mode:** Full Verification (attempted)

### Finding

No dedicated test files exist for issues #17799 or #33201.

**Related test found but disabled:**
- `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27229.cs`
- This test is wrapped in `#if TEST_FAILS_ON_ANDROID && TEST_FAILS_ON_IOS && TEST_FAILS_ON_CATALYST`
- The comment inside explicitly cites Issue #33201 as the reason for disabling
- The `TEST_FAILS_ON_*` symbols are **never defined** anywhere in the build system, making this test impossible to compile
- This is effectively a "commented-out" test for the exact bug this PR fixes

### Why Gate Could Not Run

- Fix files present: `LayoutFactory2.cs` (+34/-3)
- Test files in PR: **None**
- Active tests for this issue: **None**
- The only related test (Issue27229) is disabled via a never-true `#if` condition

### Impact on Review

Cannot empirically verify:
- ❌ Tests fail without fix
- ❌ Tests pass with fix
- ❌ try-fix alternatives cannot be validated

### Important Observation

**The PR should re-enable Issue27229 as part of this fix.** The test was disabled specifically because of Issue #33201 (which this PR fixes). After this PR is merged, `Issue27229.cs` should compile and pass. The PR author should:
1. Remove the `#if TEST_FAILS_ON_ANDROID && TEST_FAILS_ON_IOS && TEST_FAILS_ON_CATALYST` wrapper from `Issue27229.cs`
2. Verify the test passes with the fix applied
3. Verify the test fails without the fix applied

</details>

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Update LayoutFactory2.cs</strong> · <a href="https://github.com/dotnet/maui/commit/9700f578feea468117eee74d88b448ca5b53b53e"><code>9700f57</code></a></summary>

---

### Fix Candidates

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #31215 | Override CollectionViewContentSize to return CGSize.Empty when no items present | ⚠️ SKIPPED (No tests) | `LayoutFactory2.cs` (+34/-3) | Only candidate - cannot validate without tests |

**Exhausted:** N/A - try-fix exploration skipped
**Selected Fix:** PR's fix (only available candidate; cannot empirically validate alternatives without tests)

### Reason for Skipping try-fix

Gate was skipped (no active automated tests exist). try-fix requires automated tests to empirically validate alternative approaches. Without tests, cannot compare fix candidates with measurable results.

### Manual Code Assessment

The PR's fix logic is sound:
1. Returns `CGSize.Empty` only when CollectionView exists, no headers/footers, and first section has no items
2. Passes `groupingInfo` and `headerFooterInfo` to constructor for the override
3. Both list and grid layout constructors updated
4. Low risk: only affects empty-state scenario

</details>

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Update LayoutFactory2.cs</strong> · <a href="https://github.com/dotnet/maui/commit/9700f578feea468117eee74d88b448ca5b53b53e"><code>9700f57</code></a></summary>

---

## ⚠️ Final Recommendation: REQUEST CHANGES

### Summary

PR #31215 fixes CollectionView2 on iOS/MacCatalyst displaying unwanted empty/scrollable space when no items are present. The fix is technically sound, but the PR is missing an important action: **re-enabling the Issue27229 test that was disabled specifically because of this bug**.

### Root Cause

**Problem:** CollectionView2 on iOS creates a large scrollable empty space when `ItemsSource` is null or empty.

**Technical Cause:** `UICollectionViewCompositionalLayout.CollectionViewContentSize` returns non-zero content size even when the CollectionView has no items, causing UIKit to reserve scrollable space.

**Fix:** Override `CollectionViewContentSize` in `CustomUICollectionViewCompositionalLayout` to return `CGSize.Empty` when no items exist and no headers/footers are configured. Constructor updated to receive `groupingInfo` and `headerFooterInfo` to support the override.

### Fix Quality

**Implementation assessment:**
- ✅ Correct location: Items2/iOS handler (active iOS/MacCatalyst handler)  
- ✅ Sound logic: checks headers/footers before returning empty
- ✅ Null-safe: proper `?.` operator usage
- ✅ Both list and grid layout constructors updated correctly
- ✅ Low risk: only affects empty-state scenario
- ⚠️ Minor indentation issue at line 580 (second line of `&&` condition has inconsistent indent - cosmetic only, run `dotnet format`)

**Potential edge case concern:**
The fix checks only `NumberOfItemsInSection(0)` (first section). In a grouped CollectionView where the first group/section is empty but subsequent groups have items, this could incorrectly return `CGSize.Empty`. However:
- The reviewer (@jsuarezruiz) explicitly requested this simplification from the original loop-through-sections
- The primary bug scenario (empty ItemsSource) is correctly handled
- This edge case (empty first group with items in other groups) is unusual and not reported in the linked issues

### Gate Status: ⚠️ SKIPPED

No dedicated tests exist for issues #17799 or #33201.

**Critical finding:** `Issue27229.cs` is directly related to this PR but was disabled with a never-true `#if` condition:

```
#if TEST_FAILS_ON_ANDROID && TEST_FAILS_ON_IOS && TEST_FAILS_ON_CATALYST
```

The comment inside explicitly states: *"In iOS and Mac, https://github.com/dotnet/maui/issues/33201 takes large horizontal spacing on collectionView2."*

The `TEST_FAILS_ON_*` symbols are **never defined** in the build system — this is an effective "comment-out" of the test. With this PR's fix, `Issue27229` should now pass on iOS/MacCatalyst.

### Requested Changes

1. **Re-enable Issue27229 test** — Remove the `#if TEST_FAILS_ON_ANDROID && TEST_FAILS_ON_IOS && TEST_FAILS_ON_CATALYST` wrapper from `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27229.cs`. This test was disabled specifically because of Issue #33201, which this PR fixes. Re-enabling it provides automated regression coverage.

2. *(Optional)* Run `dotnet format` to fix minor indentation inconsistency at line 580 of `LayoutFactory2.cs`.

### Alternative Exploration

**Status:** ⚠️ Skipped — no tests available for empirical validation.

Cannot compare fix candidates without automated test verification. Code quality review only.

### Platform Notes

- Fix applies to iOS/MacCatalyst only (Items2 handler)
- Android/Windows use different handler implementations (not affected)
- Author verified fix manually on iOS, MacCatalyst, Android, Windows

</details>

</details>

---

</details>




<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

---

<details>

<summary><b>Title: ✅ Good</b></summary>

<br>

**Current:** `[iOS][CV2] Fix CollectionView renders large empty space at bottom of view`
</details>

<details>

<summary><b>Description: ⚠️ Needs Update</b></summary>

<br>

1. The file is in `Items2/iOS/LayoutFactory2.cs`, which applies to **both iOS and MacCatalyst**. Both issues #17799 and #33201 call out macOS/Mac Catalyst as affected. The title should include `[Mac]`.
2. Issue #33201 describes horizontal space (EmptyView), not just space "at bottom". The fix is more precisely about preventing scrollable empty space when no items are present.
### ✨ Suggested PR Description


> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause

`UICollectionViewCompositionalLayout` (used exclusively in CV2 / Items2) reports a non-zero `CollectionViewContentSize` even when no items are present. This causes the CollectionView to appear scrollable and display a large empty area when the item source is empty. CV1 does not have this issue because it uses a different layout mechanism that does not exhibit this behavior.

### Description of Change

Overrides `CollectionViewContentSize` in `CustomUICollectionViewCompositionalLayout` to return `CGSize.Empty` when:
- The `CollectionView` has no items in section 0, **and**
- There are no global headers/footers (`LayoutHeaderFooterInfo`), **and**
- There are no group-level headers/footers (`LayoutGroupingInfo`)

To support the header/footer check, the `CustomUICollectionViewCompositionalLayout` constructor was updated to accept `LayoutGroupingInfo?` and `LayoutHeaderFooterInfo?` parameters. Both `CreateListLayout` and `CreateGridLayout` were updated accordingly.

### Key Technical Details

**Modified class:** `CustomUICollectionViewCompositionalLayout` (private, in `LayoutFactory2.cs`)

- Constructor now accepts `LayoutGroupingInfo?` and `LayoutHeaderFooterInfo?` to allow the layout to inspect header/footer configuration at content-size computation time.
- `CollectionViewContentSize` override returns `CGSize.Empty` only when no items are present AND no headers/footers exist. This guards against incorrectly suppressing the content size for layouts with decorative or structural supplementary views.

**File:** `src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs`

This is a CV2 (CollectionView v2) fix only. CV1 (`Items/`) is unaffected.

### Regarding Tests

It is not possible to write an automated UI test for this case: the scrollbar does not appear during initial loading; it only becomes visible when a scroll action is performed, and even then it remains visible only for a few seconds.

### Issues Fixed

Fixes #17799
Fixes #33201

### Platforms Tested

- [ ] Android *(not applicable — fix is iOS/MacCatalyst CV2 only)*
- [ ] Windows *(not applicable — fix is iOS/MacCatalyst CV2 only)*
- [x] iOS
- [x] Mac
</details>

<details>

<summary><b>Code Review: ⚠️ Issues Found</b></summary>

<br>

# Code Review — PR #31215

**File:** `src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs`

---

## 🔴 Critical Issues

### Multi-Section Bug: Only Section 0 Is Checked for Items

**Location:** `CollectionViewContentSize` override, lines ~579–583

**Code:**
```csharp
if (CollectionView.NumberOfSections() > 0 &&
    CollectionView.NumberOfItemsInSection(0) > 0)
{
    return base.CollectionViewContentSize;
}

return CGSize.Empty;
```

**Problem:** The check only looks at section 0. If a multi-section CollectionView has:
- Section 0: 0 items
- Section 1: 5 items

…the condition `NumberOfItemsInSection(0) > 0` is `false`, so the code returns `CGSize.Empty` even though the collection is not empty. This would cause the content area to collapse and items in section 1+ to not be visible/scrollable.

This scenario can arise with grouped CollectionViews where the first group has no items but later groups do.

**Recommendation:** Loop through all sections to check if any has items:

```csharp
nint totalItems = 0;
nint sectionCount = CollectionView.NumberOfSections();
for (nint i = 0; i < sectionCount; i++)
    totalItems += CollectionView.NumberOfItemsInSection(i);

if (totalItems > 0)
{
    return base.CollectionViewContentSize;
}

return CGSize.Empty;
```

---

## 🟡 Suggestions

### Indentation Inconsistency (Line 580)

**Code (from diff):**
```csharp
				if (CollectionView.NumberOfSections() > 0 &&
			CollectionView.NumberOfItemsInSection(0) > 0)
```

The continuation line `CollectionView.NumberOfItemsInSection(0) > 0)` is under-indented (3 tabs instead of 4, not aligned with the condition it continues). This is a minor formatting issue but is inconsistent with the surrounding code style.

**Recommended:**
```csharp
				if (CollectionView.NumberOfSections() > 0 &&
					CollectionView.NumberOfItemsInSection(0) > 0)
```

### Platforms Tested in Description

Android and Windows are checked in the PR description's "Platforms Tested" table, but the change is entirely within `Items2/iOS/LayoutFactory2.cs`, which only applies to iOS and MacCatalyst. The checked platforms should be corrected to iOS and Mac only to avoid misleading reviewers.

---

## ✅ Looks Good

- **Header/footer guard is correct**: Checking both `_headerFooterInfo` (global) and `_groupingInfo` (group-level) before returning `CGSize.Empty` prevents the fix from breaking layouts that use supplementary views. This is the right defensive pattern.
- **Null-safety**: The `CollectionView != null` guard before any calls is appropriate, with a fallback to `base.CollectionViewContentSize`.
- **Constructor change is clean**: Adding `groupingInfo` and `headerFooterInfo` before the `sectionProvider` and `configuration` parameters on the internal private class is acceptable. The two call sites were correctly updated.
- **Minimal scope**: The fix is isolated to CV2 (`Items2/`) and does not touch CV1 (`Items/`), which is the correct scope.
</details>

---

</details>

**Review by kubaflo — CHANGES_REQUESTED** [review]
@devanathan-vaithiyanathan could you please add tests?

**Comment by devanathan-vaithiyanathan** [comment]
> For this case, it's not possible to write a test because the scrollbar does not appear during initial loading. It only becomes visible when a scroll action is performed, and even then, it remains visible only for a few seconds.

@kubaflo, For this case, it's not possible to write a test because the scrollbar does not appear during initial loading. It only becomes visible when a scroll action is performed, and even then, it remains visible only for a few seconds.

**Comment by kubaflo** [comment]
@devanathan-vaithiyanathan okay I see. Thanks for explanation!

**Review by kubaflo — APPROVED** [review]

**Review by kubaflo — CHANGES_REQUESTED** [review]
Could you please add a test?

**Comment by devanathan-vaithiyanathan** [comment]
> For this case, it's not possible to write a test because the scrollbar does not appear during initial loading. It only becomes visible when a scroll action is performed, and even then, it remains visible only for a few seconds.

@kubaflo, For this case, it's not possible to write a test because the scrollbar does not appear during initial loading. It only becomes visible when a scroll action is performed, and even then, it remains visible only for a few seconds.
