### PR TITLE
Force parent invalidation on Margin and LayoutOptions changes

### LINKED ISSUE #4145: [Windows] Margin on children of VerticalStackLayout doesn't work without resizing window
### Description

When I change the margin to the label for count it doesn't hot reload, or it does but the UI doesn't respond until I resize the window.

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp20.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}">

    <ScrollView>
        <VerticalStackLayout 
              Padding="{OnPlatform iOS='30,60,30,30', Default='30'}">

            <Label 
                Text="Hello, World!"
                
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32"
                HorizontalOptions="Center" />

            <Label 
                Text="Welcome to .NET Multi-platform App UI"
                SemanticProperties.HeadingLevel="Level1"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                FontSize="18"
                HorizontalOptions="Center" />

            <Label Margin="0,20,0,0"
                Text="Current count: 0"
                FontSize="18"
                FontAttributes="Bold"
                x:Name="CounterLabel"
                HorizontalOptions="Center" />

            <Button 
                Text="Click me"
                FontAttributes="Bold"
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Center" />

            <Image 
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                WidthRequest="250"
                HeightRequest="310"
                HorizontalOptions="Center" />

        </VerticalStackLayout>
    </ScrollView>
</ContentPage>
```

image

After resizing the window, the label moves, but the rest of the children don't reposition as expected.

image

Hiding the button (which does work via HR), reveals the label did move.

image

### Steps to Reproduce

Do the stuff I just said :)

Android works as expected.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Win11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change

LayoutOptions and Margins effectively require a re-layout of the parent layout (if one exists) when they change. On some platforms, a layout request on the immediately affected control is sufficient, but others may have optimizations which defeat our need to update the layout when these properties change.

This change bumps the invalidation to the parent when LayoutOptions or Margins change.

### Issues Fixed

Fixes #4145

### CODE REVIEW

File: src/Controls/src/Core/VisualElement.cs [hunk 1]
```diff
@@ -701,7 +701,7 @@ public bool IsPlatformEnabled
 
 				_isPlatformEnabled = value;
 				if (value && IsPlatformStateConsistent)
-					InvalidateMeasureInternal(InvalidationTrigger.RendererReady);
+					//InvalidateMeasureInternal(InvalidationTrigger.RendererReady);
```
Comment (mattleibow) [inline src/Controls/src/Core/VisualElement.cs:704]: Is this intentional? It seems that the flow is now different with the if block controlling the InvalidateStateTriggers when it would hav always run?

**Comment by mattleibow** [comment]
I managed to create a test that can check for this. Screen captures and all. So is this UI testing now? :)

File: src/Controls/tests/DeviceTests/Elements/Layout/LayoutTests.cs [hunk 2]
```diff
@@ -92,5 +90,64 @@ public async Task CascadeInputTransparentAppliesOnInit(bool inputTransparent, bo
...
+				var updatingHandler = CreateHandler<LayoutHandler>(updatingLayout);
+				var updatingBitmap = await updatingHandler.PlatformView.AttachAndRun(() =>
+				{
+					updatingLabel.HorizontalOptions = layoutOptions;
+
+					return updatingHandler.PlatformView.ToBitmap();
+				});
+
+				await initialBitmap.AssertEqual(updatingBitmap);
+			});
```
Comment (mattleibow) [inline src/Controls/tests/DeviceTests/Elements/Layout/LayoutTests.cs:132]: Bitmap comparison tests are great. Might need a fuzzer at some point, but for now if the test is running both UIs for comparison, then is should be exactly the same. Also works great on Android. Not so much iOS yet #6832

**Review by mattleibow — CHANGES_REQUESTED** [review]
Going to move to red because I feel so sus about that comment and the sudden change of flow.

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
Now why are the test failing? The ran green for me :(

**Comment by mattleibow** [comment]
They seemed to have stopped working locally too. :(

**Comment by mattleibow** [comment]
Disabling the Android test for now as well. Windows still runs fine, and this PR was for Windows - and it fails without this fix too.

Need to re-evaluate the whole attach and run concept to make sure it actually performs as the real world.
