### PR TITLE
[iOS/Mac] Fixed the Border Rendering issues in CollectionViewHandler2

### LINKED ISSUE #27608: Items' shapes are sometimes rendered incorrectly using CollectionView2Handler
### Description

CollectionView items are regularly rendered incorrectly when using the CollectionViewHandler2 on iOS/Mac.

In the following images, all items should be of identical shape.

### RoundedRectangle example

Image

### Polygon example

Image

### Steps to Reproduce

1. Clone <https://github.com/rabuckley/CollectionBorderRender>.
2. Build and run on iOS/Mac device/simulator.
3. Scroll CollectionView until one of the items shown is incorrectly rendered.

### Link to public reproduction project repository

https://github.com/rabuckley/CollectionBorderRender

### Version with bug

9.0.30 SR3

### Affected platforms

iOS, macOS

### Did you find any workaround?

No.

### PR DESCRIPTION
**Pull request by Ahamed-Ali**
### Root Cause of the issue

- The Virtual View is not `arranged` in `TemplatedCell2`, causing some items to render improperly while scrolling in cv2. 

### Description of Change

- Properly `arranged` the `Virtual View` prevents border shape deformation during scrolling and ensures correct rendering in cv2. 

### Same Changes of PR merged into Main

#28225 Since the same changes in this PR were already merged into the main branch in LayoutSubviews, I have kept only the test. 

### Issues Fixed

Fixes #27608 

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

#### Polygon 
| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/1bb13cbc-bce4-4bc2-88cb-fb54fbf020fe"> | <video src="https://github.com/user-attachments/assets/b5aa0f7c-4431-4df3-8f3e-577d900a6929"> |

#### RoundRectangle 
| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/bbe22b82-fd42-4a44-90e4-000e64bc21d2"> | <video src="https://github.com/user-attachments/assets/52b8abf9-555c-4d74-9768-9d469d034ac8"> |

### CODE REVIEW

File: src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs [hunk 1]
```diff
@@ -10,6 +10,7 @@
 using Microsoft.Maui.Controls;
 using Microsoft.Maui.Controls.Handlers.Compatibility;
 using Microsoft.Maui.Controls.Handlers.Items;
+using Microsoft.Maui.Controls.Handlers.Items2;
```
Comment (jsuarezruiz) [inline src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:13]: The build is facing:

```
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.cs(13,40): error CS0234: The type or namespace name 'Items2' does not exist in the namespace 'Microsoft.Maui.Controls.Handlers' (are you missing an assembly reference?) [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net9.0-windows10.0.20348.0]
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.cs(13,40): error CS0234: The type or namespace name 'Items2' does not exist in the namespace 'Microsoft.Maui.Controls.Handlers' (are you missing an assembly reference?) [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net9.0-windows10.0.19041.0]
D:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.cs(13,40): error CS0234: The type or namespace name 'Items2' does not exist in the namespace 'Microsoft.Maui.Controls.Handlers' (are you missing an assembly reference?) [D:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net9.0-android]
    9023 Warning(s)
    3 Error(s)
```

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs (hunk 1 above)
Comment (Ahamed-Ali) [reply src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:14]: Due to `Microsoft.Maui.Controls.Handlers.Items2` not being available for Android and Windows, a build error occurred. I have now added a condition to resolve it. Could you please check? @jsuarezruiz

**Review by jsuarezruiz — COMMENTED** [review]
@Ahamed-Ali  Could you rebase and fix the conflict? Thanks in advance.

**Comment by Ahamed-Ali** [comment]
Since the same changes in this PR were already merged into the main branch in LayoutSubViews by this [#28225](https://github.com/dotnet/maui/pull/28225), I have kept only the test. @PureWeen / @rmarinho / @jsuarezruiz

File: src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt [hunk 2]
```diff
@@ -345,4 +345,4 @@ virtual Microsoft.Maui.Controls.Handlers.Items2.ItemsViewDelegator2<TItemsView,
 virtual Microsoft.Maui.Controls.Handlers.Items2.ItemsViewHandler2<TItemsView>.UpdateLayout() -> void
 *REMOVED*override Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer.SetNeedsLayout() -> void
 *REMOVED*override Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer.MovedToWindow() -> void
-override Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer<TElement>.MovedToWindow() -> void
\ No newline at end of file
+override Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer<TElement>.MovedToWindow() -> void
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt:348]: Can revert this unnecessary change?

File: src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.iOS.cs [hunk 3]
```diff
@@ -52,6 +57,59 @@ public CollectionViewStringGroup(string header, IEnumerable<string> data) : base
...
+				ItemsLayout = new GridItemsLayout(ItemsLayoutOrientation.Horizontal)
+				{
+					HorizontalItemSpacing = 50
+				}
+			};
+
+			await CreateHandlerAndAddToWindow<CollectionViewHandler2>(collectionView, handler =>
+			{
+				// Get the first cell's content
+				var firstCellContent = collectionView.GetVisualTreeDescendants().OfType<Border>().FirstOrDefault();
```
Comment (jsuarezruiz) [inline src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.iOS.cs:104]: `Assert.That(firstCellContent, Is.Not.Null);`

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt (hunk 2 above)
Comment (Ahamed-Ali) [reply src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt:348]: This is not a change. The same code is only appearing as a change in this PR. When I removed the unshipped code of my fix, this appeared in the PR, and I am unable to remove it. @jsuarezruiz

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Could you fix the build errors?

```
C:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.iOS.cs(19,7): error CS0105: The using directive for 'Microsoft.Maui.Handlers' appeared previously in this namespace [C:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net9.0-ios]
C:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.iOS.cs(19,7): error CS0105: The using directive for 'Microsoft.Maui.Handlers' appeared previously in this namespace [C:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net9.0-maccatalyst]
    2 Error(s)
```

**Comment by Ahamed-Ali** [comment]
> Could you fix the build errors?
> 
> ```
> C:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.iOS.cs(19,7): error CS0105: The using directive for 'Microsoft.Maui.Handlers' appeared previously in this namespace [C:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net9.0-ios]
> C:\a\_work\1\s\src\Controls\tests\DeviceTests\Elements\CollectionView\CollectionViewTests.iOS.cs(19,7): error CS0105: The using directive for 'Microsoft.Maui.Handlers' appeared previously in this namespace [C:\a\_work\1\s\src\Controls\tests\DeviceTests\Controls.DeviceTests.csproj::TargetFramework=net9.0-maccatalyst]
>     2 Error(s)
> ```

The build errors occurred because the same namespace was used twice. I have now resolved the errors. @jsuarezruiz

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt [hunk 4]
```diff
@@ -346,4 +346,4 @@ virtual Microsoft.Maui.Controls.Handlers.Items2.ItemsViewDelegator2<TItemsView,
...
```
[the remark this answers is not in the document]
Comment (Ahamed-Ali) [reply src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt:349]: This is not a change. The same code is only appearing as a change in this PR. When I removed the unshipped code of my fix, this appeared in the PR, and I am unable to remove it. @jsuarezruiz

**Review by mattleibow — APPROVED** [review]
