### PR TITLE
[Android] SearchBar does not update colors on theme change - fix

### LINKED ISSUE #25153: Theme issue on Search bar control in .NET MAUI
### Description

When changing the theme from dark to light or light to dark, the search bar control does not update according to the theme changes.

For example, after switching from the dark theme to the light theme, the search bar's underline and search icon remain the same color, failing to adjust to the new theme.

A video demonstration is provided below.

https://github.com/user-attachments/assets/0206a0a4-4b89-4534-8e71-5cd740841b3a

### Steps to Reproduce

Please get the below repo to reproduce the issue

### Link to public reproduction project repository

https://github.com/Ahamed-Ali/SearchBarTheme

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #30600: [Android] SearchBar does not update colors on theme change in .NET MAUI
### Description

On Android, when changing the app theme at runtime (e.g., from light to dark or dark to light), the SearchBar does not update its visual elements to reflect the new theme. Specifically, the following components retain their old styling:

Search icon (magnifying glass)
* Cancel (clear) button
* Placeholder text color
* Entered text color

This leads to visual inconsistencies, especially when switching from dark to light mode or vice versa, where text/icons may become invisible or unreadable.

<video src="https://github.com/user-attachments/assets/bb1f9831-236a-41d8-ab7f-f7713c5e99b9"></video>

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.82 SR8.2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/30600
Fixes https://github.com/dotnet/maui/issues/25153

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/d08182a2-cf54-4f96-9886-aa98ce14bdcd" width="300px"></video>|<video src="https://github.com/user-attachments/assets/d712a876-1ad9-41dd-b864-54bd272a65eb" width="300px"></video>|

### CODE REVIEW

File: src/Controls/src/Core/SearchBar/SearchBar.cs [hunk 1]
```diff
@@ -115,6 +116,28 @@ public SearchBar()
...
 		}
 
+		private protected override void OnHandlerChangingCore(HandlerChangingEventArgs args)
+		{
+			base.OnHandlerChangingCore(args);
+
+			if (Application.Current == null)
+				return;
+
+			if (args.NewHandler == null)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/SearchBar/SearchBar.cs]: You're only unsubscribing when `NewHandler` is null, but you should unsubscribe whenever there's an `OldHandler`.

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue30601.cs [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+
+	public override string Issue => "[Android] SearchBar does not update colors on theme change";
+
+	[Test]
+	[Category(UITestCategories.SearchBar)]
+	public void SearchbarColorsShouldUpdate()
+	{
+		App.WaitForElement("changeThemeButton");
+		App.Tap("changeThemeButton");
+		VerifyScreenshot();
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue30601.cs:19]: Pending snapshots, running a build.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue30601.cs (hunk 2 above)
Comment (kubaflo) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue30601.cs:19]: done

**Comment by jfversluis** [comment]
@kubaflo any comments on the Copilot review?

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue30601.cs [hunk 3]
```diff
@@ -0,0 +1,23 @@
+﻿#if TEST_FAILS_ON_CATALYST || TEST_FAILS_ON_IOS // There's a separate PR for this issue on iOS and Catalyst https://github.com/dotnet/maui/pull/30597
```
[the remark this answers is not in the document]
Comment (jfversluis) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue30601.cs]: This PR is actually merged now, so lets try it.

Comment (jfversluis) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue30601.cs]:
```suggestion
```

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue30601.cs [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+	[Test]
+	[Category(UITestCategories.SearchBar)]
+	public void SearchbarColorsShouldUpdate()
+	{
+		App.WaitForElement("changeThemeButton");
+		App.Tap("changeThemeButton");
+		VerifyScreenshot();
+	}
+}
+#endif
```
Comment (jfversluis) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue30601.cs]:
```suggestion
```

File: src/Core/src/Platform/Android/SearchViewExtensions.cs [hunk 5]
```diff
@@ -108,12 +127,12 @@ public static void UpdateCancelButtonColor(this SearchView searchView, ISearchBa
...
-				if (image != null && image.Drawable != null)
+				if (image is not null && image.Drawable is Drawable drawable)
 				{
-					if (searchBar.CancelButtonColor != null)
-						image.Drawable.SetColorFilter(searchBar.CancelButtonColor, FilterMode.SrcIn);
-					else
-						image.Drawable.ClearColorFilter();
+					if (searchBar.CancelButtonColor is not null)
+						drawable.SetColorFilter(searchBar.CancelButtonColor, FilterMode.SrcIn);
+					else if (TryGetDefaultStateColor(searchView,Android.Resource.Attribute.TextColorPrimary, out var color))
```
Comment (jfversluis) [inline src/Core/src/Platform/Android/SearchViewExtensions.cs]:
```suggestion
					else if (TryGetDefaultStateColor(searchView, Android.Resource.Attribute.TextColorPrimary, out var color))
```

**Review by jfversluis — APPROVED** [review]
