### PR TITLE
Just trigger SizeChanged when Window size changes

### LINKED ISSUE #17991: Window.SizeChanged fired moving MainWindow
### Description

When you create a brand new Maui project and subscribe a MainWindow SizeChanged event, always you move Window, SizeChanged event is fired.

SizeChangedIssue

Investigating on Maui repository I saw that `IWindow.FrameChanged` invoked `SizeChanged` event every time.

### Steps to Reproduce

1. Create a dotnet Maui project
2. Subscribe to Window.SizeChanged
3. Move window
4. SizeChanged event will be fired

### Link to public reproduction project repository

_No response_

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #21306: [macOS] Crash in multi-window mode in the Controls.sample project
### Description

Setting window size crashes the MAUI application.

### Steps to Reproduce

Compile and run `Controls.Sample` project:

```bash
cd src/Controls/samples/Controls.Sample
dotnet build -t:run --configuration Debug -p:RuntimeIdentifier=maccatalyst-arm64 --framework net8.0-maccatalyst
```

In the app, navigate to Core -> Multi-Window and click `Set window size to 700x500` and the application crashes.

### Link to public reproduction project repository

_No response_

### Version with bug

Nightly / CI build (93940d6f931a54bce074f8dfd2013440e0827cf3). 

However, I can see something similar in my MAUI app as well but reproducing the issue in the Controls.Sample project is easiest so I reported it this way.

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Apple Mac M1 Sonoma 14.4

### Did you find any workaround?

No.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by pictos**
### Issues Fixed

Fixes #17991
Fixes #21306

### CODE REVIEW

**Comment by Giviruk** [comment]
This is my first PR, I will try to fix the errors as soon as possible

File: src/Controls/src/Core/Window/Window.cs [hunk 1]
```diff
@@ -229,10 +230,13 @@ void IWindow.FrameChanged(Rect frame)
 			{
 				SetPropertyChanged(XProperty, nameof(X), x, frame.X);
 				SetPropertyChanged(YProperty, nameof(Y), y, frame.Y);
-				SetPropertyChanged(WidthProperty, nameof(Width), width, frame.Width);
-				SetPropertyChanged(HeightProperty, nameof(Height), height, frame.Height);
 
-				SizeChanged?.Invoke(this, EventArgs.Empty);
+				if (width != frame.Width || height != frame.Height)
+				{
+					SetPropertyChanged(WidthProperty, nameof(Width), width, frame.Width);
```
Comment (PureWeen) [inline src/Controls/src/Core/Window/Window.cs:236]: I wonder if there's something similar to what I'm doing here

https://github.com/dotnet/maui/pull/22347/files#diff-5461d9c00748c889dd799eaf32389b419ec8bb26cf1b417496d49d3863d00cc8R1945-R1957

That we should also do. 
Like, if this is being called from the `Handler` we should really propagate these changes back to the handler. Ideally when these properties are set via this path it won't propagate back to the handler right?

Comment (pictos) [reply src/Controls/src/Core/Window/Window.cs:236]: Not sure if I follow... Are you saying (1 or 2?):

1. This change will prevent the Handler to know when these value changes
2. The previous implementation didn't report to Handler when the value changes and would be good to implement on this PR

The only change I made was to not trigger the SizeChanged event when the Window is moved (X, Y changes), is there a specific event that should be trigger when the Window is moved?

Comment (PureWeen) [reply src/Controls/src/Core/Window/Window.cs:236]: Basically it's what's captured in the comment here

https://github.com/dotnet/maui/issues/21306#issuecomment-2007580475

`void IWindow.FrameChanged(Rect frame)` isn't called to move the window. The point of this method is for the platform to inform the xplat code that the window itself has moved. So, basically what happens now is

User changes dims of window interactively => this calls IWindow.FramChanged => This fires MapHeight/MapWidth on handler (This shouldn't happen because we don't need to inform the handler of anything)

or

User programmatically sets Window.Height => this calls [MapHeight](https://github.com/dotnet/maui/blob/0a0be96497d0a9c4ea273b1d5c445eb574846bca/src/Core/src/Handlers/Window/WindowHandler.Windows.cs#L106) => [Which calls UpdateSize on the platform window](https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Windows/WindowExtensions.cs#L93) => Which will then fire a [window changed event](https://github.com/dotnet/maui/blob/0a0be96497d0a9c4ea273b1d5c445eb574846bca/src/Core/src/Handlers/Window/WindowHandler.Windows.cs#L196) => Which then calls IWindow.SetFrame => Which then calls `MapHeight`

File: src/Controls/src/Core/Element/Element.cs [hunk 2]
```diff
@@ -567,11 +567,17 @@ protected virtual void OnParentSet()
 
 		/// <summary>Method that is called when a bound property is changed.</summary>
 		/// <param name="propertyName">The name of the bound property that changed.</param>
-		protected override void OnPropertyChanged([CallerMemberName] string propertyName = null)
+		protected override void OnPropertyChanged([CallerMemberName] string propertyName = null) =>
+			OnPropertyChanged(propertyName, true);
+
+		internal void OnPropertyChanged(string propertyName = null, bool propagateToHandler = true)
```
Comment (PureWeen) [inline src/Controls/src/Core/Element/Element.cs:573]:
```suggestion
		internal void OnPropertyChanged([CallerMemberName] string propertyName = null, bool propagateToHandler = true)
```

File: src/Controls/src/Core/Window/Window.cs [hunk 3]
```diff
@@ -246,12 +252,12 @@ void SetPropertyChanging(BindableProperty property, string name, double oldValue
 			}
 
 			[MethodImpl(MethodImplOptions.AggressiveInlining)]
-			void SetPropertyChanged(BindableProperty property, string name, double oldValue, double newValue)
+			void SetPropertyChanged(BindableProperty property, string name, double oldValue, double newValue, bool shouldPropagateToHandler = true)
```
Comment (PureWeen) [inline src/Controls/src/Core/Window/Window.cs:255]:
```suggestion
			void SetPropertyChanged(BindableProperty property, string name, double oldValue, double newValue)
```

File: src/Controls/src/Core/Window/Window.cs [hunk 4]
```diff
@@ -246,12 +252,12 @@ void SetPropertyChanging(BindableProperty property, string name, double oldValue
...
 			{
 				if (oldValue == newValue)
 					return;
 
-				OnPropertyChanged(name);
+				OnPropertyChanged(name, shouldPropagateToHandler);
```
Comment (PureWeen) [inline src/Controls/src/Core/Window/Window.cs:260]:
```suggestion
				OnPropertyChanged(name);
```

File: src/Controls/src/Core/Window/Window.cs [hunk 5]
```diff
@@ -199,7 +200,7 @@ public double MinimumHeight
 		}
 
 		int _batchFrameUpdate = 0;
-
+		bool disableHandlerUpdate;
```
Comment (PureWeen) [inline src/Controls/src/Core/Window/Window.cs:203]: I chatted with @mattleibow about this one a bit, and I think my suggestions are somewhat just digging us into a deeper hole here :-)

I think we've been trying to fix this issue the wrong way for some time now and need to revert this entire method back to what it originally looked like here

https://github.com/dotnet/maui/pull/4942/files#diff-07d5a2c0b5069d448623e88d890e41bc2c21e12f99bd01f1349903a332d4130cR202-R222

And then change this method 
```C#
private protected override void UpdateHandlerValue(string property)
		{
			if (disableHandlerUpdate)
				return;

			base.UpdateHandlerValue(property);
		}
```

to

```C#
private protected override void UpdateHandlerValue(string property)
		{
			if (_batchFrameUpdate > 0)
				return;

			base.UpdateHandlerValue(property);
		}
```

**Comment by pictos** [comment]
Looks like the error are unrelated with my changes, from logs I could see something about Cake

**Review by PureWeen — APPROVED** [review]

**Comment by mattleibow** [comment]
@MartyIX  it did not it seems. I added a comment to the issue with a tiny bit more detail, but yeah, we need to fix this sooner rather than later.

**Comment by malsabi** [comment]
In SR6 .NET 8 CollectionView SizeChanged is not executing after this fix I guess. It was working fine on SR5. Is there a way to detect when the CollectionView size is changed ?

**Comment by mattleibow** [comment]
@malsabi could you file a regression issue? Then we can go this ASAP.

**Comment by malsabi** [comment]
@mattleibow Here you go https://github.com/dotnet/maui/issues/23029

**Comment by mattleibow** [comment]
Thanks, I will have a look.
