### PR TITLE
[Android] Fix for disabled Picker prevents the parent container's GestureRecognizer from being triggered

### LINKED ISSUE #22565: [Android] Disabled Picker view intercepts GestureRecognizer of parent container
### Description

For some reason if I have a disabled `Picker` inside a `Grid` I cannot use GestureRecognizer attached to `Grid` (parent container) with Android, it does not fire if I click directly on Picker, so I assume it intercepts with Picker built-in click listener.
In attached screenshot I painted `Grid` to Red color, and `Picker` to Gray, and GestureRecognizer is only hit if I click on a Red area.
android
In this example the Grid's GestureRecognizer points to existing method to update the counter and text on the button.

The expected behaviour in short - I should see updated text on a button whenever I click Red or Gray area (parent Grid or Picker view itself), however it does not work on Android. I can trigger GestureRecognizer attached method only if I click *directly* on Grid (Red area).
Everything works as expected on iOS, the button is updated if I click on any area (Grid or Picker)

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Open `MainPage.xaml` and add a grid with *disabled* picker before `Button` from initial template. Add a `GestureRecognizer` to `Grid` poiniting to existing method `OnCounterClicked`. The file will look like
````xaml
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">
    <ScrollView>
        <VerticalStackLayout Padding="30,0"
                             Spacing="25">
            <Image Source="dotnet_bot.png"
                   HeightRequest="185"
                   Aspect="AspectFit"
                   SemanticProperties.Description="dot net bot in a race car number eight" />
            <Label Text="Hello, World!"
                   Style="{StaticResource Headline}"
                   SemanticProperties.HeadingLevel="Level1" />
            <Label Text="Welcome to &#xA;.NET Multi-platform App UI"
                   Style="{StaticResource SubHeadline}"
                   SemanticProperties.HeadingLevel="Level2"
                   SemanticProperties.Description="Welcome to dot net Multi platform App U I" />

            <Grid Padding="20"
                  BackgroundColor="DarkRed"
                  HorizontalOptions="FillAndExpand"
                  VerticalOptions="FillAndExpand">
                <Picker BackgroundColor="Gray"
                        IsEnabled="False"
                        VerticalOptions="CenterAndExpand" />
                <Grid.GestureRecognizers>
                    <TapGestureRecognizer Tapped="OnCounterClicked" />
                </Grid.GestureRecognizers>
            </Grid>

            <Button x:Name="CounterBtn"
                    Text="Click me"
                    SemanticProperties.Hint="Counts the number of times you click"
                    Clicked="OnCounterClicked"
                    HorizontalOptions="Fill" />
        </VerticalStackLayout>
    </ScrollView>
</ContentPage>
````
3) Click on Picker (Gray area), expected result - button's text is changed with updated counter value.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 34

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SyedAbdulAzeemSF4852**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue Details

- Disabled Picker view intercepts GestureRecognizer of parent container.

### Root Cause

- The touch event is triggered regardless of whether the picker is enabled or disabled. As a result, the base class OnTouchEvent is called and returns true, indicating that the touch event has been handled. This behavior prevents the parent tap gesture recognizer from being triggered.

### Description of Change

- Updated the OnTouchEvent method to return false if the Picker is disabled, ensuring that touch events are not intercepted by the Picker in this state.

### Reference :
https://github.com/dotnet/maui/blob/9894e0f8c1fb39a2f71a2ad642ff7c83bbe9031e/src/Core/src/Platform/Android/MauiScrollView.cs#L156-L165

### Issues Fixed
Fixes #22565 

### Validated the behaviour in the following platforms

- [x] Windows
- [x] Android
- [x] iOS
- [x] Mac

### Output
| Before | After |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/518eadce-55a6-4a42-9238-054de8ab4fb5"> | <video src="https://github.com/user-attachments/assets/fc06a418-e175-443e-b7aa-632e9c46f12f"> |

### CODE REVIEW

**Review by bhavanesh2001 — CHANGES_REQUESTED** [review]
🚩

File: src/Core/src/Platform/Android/MauiPicker.cs [hunk 1]
```diff
@@ -18,6 +18,11 @@ public MauiPicker(Context context) : base(context)
 
 		public override bool OnTouchEvent(MotionEvent? e)
 		{
+			if (!Enabled)
+			{
+				return false;
```
Comment (bhavanesh2001) [inline src/Core/src/Platform/Android/MauiPicker.cs]: -  Returning `false` here means we're interfering with touch event propagation — this is never a good idea, especially since this is a View at platform-level.

- Regarding the issue being addressed in [#22565](https://github.com/your-repo/your-project/issues/22565): the display part of the Picker is essentially an `AppCompatEditText`. If you replace the Picker with an `Entry` (which is also an `AppCompatEditText`), the touch still won’t pass to the parent container. In other words, `AppCompatEditText` consumes touch events by default — regardless of whether it's enabled or not.

- Even with the current implementation, if the Picker is enabled, touch doesn't pass through to the parent — it just opens the Picker.

Comment (SyedAbdulAzeemSF4852) [reply src/Core/src/Platform/Android/MauiPicker.cs]: @bhavanesh2001 , I have just modified the fix on this scenario.

**Review by bhavanesh2001 — CHANGES_REQUESTED** [review]
@SyedAbdulAzeemSF4852 Thanks for the changes.

But, here are a few things I failed to clarify earlier.

Sadly, We currently don’t have clarity on whether a touch should or shouldn’t pass through the control to a parent container.

As far as I can tell, this is the default(current) behavior on Android:

- If the control in question is one that expects touch input (e.g., `Entry`, `Editor`, `Picker`, `Button`, etc.), then the touch will not pass to the parent container, regardless of whether it is enabled or not.
- If the control does **not** expect touch input (e.g., `Label`, `Image`, etc.), then the touch will pass through to the parent container.

Now, regarding the `Picker`: since it expects touch input, my concern is whether we really need to go out of our way and implement a separate mapper for `IsEnabled` just to fix the issue in question, even though that seems to be the default behavior already.

@PureWeen thoughts??

**Review by jsuarezruiz — COMMENTED** [review]
@SyedAbdulAzeemSF4852  Could you rebase and fix the current conflict?

**Comment by SyedAbdulAzeemSF4852** [comment]
> @SyedAbdulAzeemSF4852 Could you rebase and fix the current conflict?

@jsuarezruiz, I have rebased and resolved the conflicts.

**Review by kubaflo — APPROVED** [review]
