### PR TITLE
[Shell] Fixes for Shell issues with iOS and Mac

### LINKED ISSUE #7260: [MacCatalyst] [Scenario Day] Crash using Shell
### Description

Crash using Xaminals Shell sample.
Captura de Pantalla 2022-05-17 a las 17 37 23

### Steps to Reproduce

1. Download https://github.com/davidbritch/dotnet-maui-samples/tree/main/Fundamentals/Shell
2. Launch the App in macOS.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 12.3.1

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SotoiGhost**
### Description of Change

* .jpg files do not contain a context; let's use the Shell context when an image does not have one
* The accessory view of the Search bar was trying to change its flow direction when `null`, that does not seem right

### Issues Fixed

Fixes #7260

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutContentRenderer.cs [hunk 1]
```diff
@@ -261,7 +261,7 @@ void UpdateFlyoutBgImageAsync()
 				return;
 			}
 
-			imageSource.LoadImage(imageSource.FindMauiContext(), result =>
+			imageSource.LoadImage(imageSource.FindMauiContext(true), result =>
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutContentRenderer.cs:264]: I think we can use _shellContext.Shell.FindMauiContext() here and that'll work

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutContentRenderer.cs (hunk 1 above)
Comment (SotoiGhost) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutContentRenderer.cs:264]: I thought that too, but I wasn't sure what was the best context to use there

Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutContentRenderer.cs:264]: yea the Image that's being pulled here is a property on shell so it's at the right level.

**Review by PureWeen — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]
