### PR TITLE
[Windows] Fix issues updating Background colors (animation) in some controls

### LINKED ISSUE #3506: BackgroundColor Animation not working on certain controls on Windows
### Description

When creating an Animation that animates the transition of the `BackgroundColor`, there seem to be some controls on Windows that don't animate and don't update. On other platforms the animation shows as expected.
Observed it on `Button` and `BoxView` (but haven't checked 'all' controls).

See [repro](https://github.com/PieEatingNinjas/ReproAnimationWindowsBug).

### Steps to Reproduce

1. Create new MAUI project
2. Update csproj file 
Uncomment Windows TargetFramework
`<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>`
Update Windows Packages
```
<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
	<!-- Required - WinUI does not yet have buildTransitive for everything -->
	<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0-preview3" />
	<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.0.0.29-preview3" />
</ItemGroup>
```
3. Add some controls to MainPage with a backgroundcolor
```
<Label x:Name="lbl"
    Text="Hello, World!"
    Grid.Row="0"
    FontSize="32"
    BackgroundColor="Red"
    HorizontalOptions="Center" />

<BoxView x:Name="box" 
    HeightRequest="100"
    WidthRequest="100"
    Grid.Row="1"
    BackgroundColor="Red"
    HorizontalOptions="Center" />

<Grid x:Name="grid" 
    HeightRequest="100"
    WidthRequest="100"
    Grid.Row="2"
    BackgroundColor="Red"
    HorizontalOptions="Center" />

<Button x:Name="btn"
    Text="this is a button"
    Grid.Row="3"
    BackgroundColor="Red"
    HorizontalOptions="Center" />

<Button 
    Text="Click me"
    FontAttributes="Bold"
    Grid.Row="4"
    Clicked="OnClicked"
    HorizontalOptions="Center" />
```
4. In the OnClicked method, Animate the backgroundcolor (adding Blue) of the different items
```
private void OnClicked(object sender, EventArgs e)
{
    Animate(lbl);
    Animate(box);
    Animate(grid);
    Animate(btn);
}

private void Animate(VisualElement element)
{
    new Animation
    {
        { 0, 1, new (v => element.BackgroundColor = 
        new Color(element.BackgroundColor.Red, element.BackgroundColor.Green,
        (float)v, element.BackgroundColor.Alpha),
            element.BackgroundColor.Blue, 1) }
    }
    .Commit(element, "test", 16, 250, Easing.Linear, (d, b) => { });
}
```
5. The BackgroundColor of BoxView and Button don't get updated on Windows, the Grid and Label do get updated as expected.

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

 Fix issues updating Background colors (animation) in some controls.

issue-3506

- fixes #3506 
- 
### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)

#### Does this PR touch anything that might affect accessibility?
- No

### CODE REVIEW

File: src/Core/src/Platform/Windows/ButtonExtensions.cs [hunk 1]
```diff
@@ -83,25 +83,36 @@ public static void UpdateBackground(this Button nativeButton, IButton button)
...
 			if (brush is null)
 			{
+				// Windows.Foundation.UniversalApiContract < 5
 				nativeButton.Resources.Remove("ButtonForeground");
 				nativeButton.Resources.Remove("ButtonForegroundPointerOver");
 				nativeButton.Resources.Remove("ButtonForegroundPressed");
 				nativeButton.Resources.Remove("ButtonForegroundDisabled");
+
+				// Windows.Foundation.UniversalApiContract >= 5
+				nativeButton.ClearValue(Button.BackgroundProperty);
```
Comment (Redth) [inline src/Core/src/Platform/Windows/ButtonExtensions.cs:104]: Is this intended to be BackgroundProperty?

**Review by Redth — APPROVED** [review]
