### PR TITLE
[net10.0] Fix SafeArea management on iOS

### LINKED ISSUE #24246: [iOS] SafeArea arrange insets are currently insetting based on an incorrect Bounds
### Description

The problem we found is that the `MauiView` returns a size from `SizeThatFits` that doesn't include the `SafeAreaInsets`. The arrange pass insets its `Bounds` and passes this value to `CrossPlatformArrange` but the `Bounds` being used is the size of the children not including the `SafeAreaInsets` which means the bounds used for arranging is wrong. 

You can see from the screenshots below that the `VSL` surrounding the the entry gets arranged incorrectly

### Comparison

Given the following `XAML`

```XAML
<ContentPage
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Maui.Controls.Sample.MainPage"
    xmlns:local="clr-namespace:Maui.Controls.Sample"
    xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
    ios:Page.UseSafeArea="false"
    >
    <VerticalStackLayout x:Name="layout" Background="Purple" IgnoreSafeArea="False" VerticalOptions="Start" IsClippedToBounds="True" >
        <Entry x:Name="label" Background="Green" Text="Hello there"></Entry>
    </VerticalStackLayout>
</ContentPage>
```

#### Before

image

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

Regarding the `MauiScrollView` one, the fix simply checks whether the `MauiScrollView` lives inside another `UIScrollView`.
In such case we can give for granted that the ancestor one is properly accounting for safe area.

Regarding safe area, the main problem is that MAUI was measuring the content without accounting for the safe area.

This PR makes the `SizeThatFits` smarter by accounting for safe area adjustments:
1. Cache safe area thickness
1. Reduce constraints by safe area thickness
2. Measure
3. Add safe area thickness back to measured size

Then when arranging we can simply adjust for safe area using the cached thickness.

We only need to pay attention when the `SafeAreaInsets` change and trigger an invalidation of the ancestors.

### Issues Fixed

Fixes #27715
Fixes #24246

### CODE REVIEW

File: src/Core/src/Platform/iOS/MauiScrollView.cs [hunk 1]
```diff
@@ -26,8 +32,49 @@ public class MauiScrollView : UIScrollView, IUIViewLifeCycleEvents, ICrossPlatfo
...
+
 		public override void LayoutSubviews()
 		{
+			if (CrossPlatformLayout is null)
+			{
+				base.LayoutSubviews();
+				return;
+			}
+
+			if (!ValidateSafeArea())
```
Comment (rmarinho) [inline src/Core/src/Platform/iOS/MauiScrollView.cs:166]: I wonder this check will have some performance impact.. Will look up the tree and all.. can we cache this in some way?

File: src/Core/src/Platform/iOS/MauiView.cs [hunk 2]
```diff
@@ -148,6 +193,34 @@ public override void LayoutSubviews()
 			CrossPlatformArrange(bounds);
 		}
 
+		bool ValidateSafeArea()
```
Comment (rmarinho) [inline src/Core/src/Platform/iOS/MauiView.cs:343]: Can this be shared with MauiScrollView?

File: src/Core/src/Platform/iOS/MauiScrollView.cs (hunk 1 above)
Comment (PureWeen) [reply src/Core/src/Platform/iOS/MauiScrollView.cs:166]: What tree does it look up? It just checks to see if safe area changed and if it has then it invalidates constraints 

Whenever sizing changes on iOS we have to propagate up the tree ourselves

File: src/Core/src/Platform/iOS/MauiView.cs (hunk 2 above)
Comment (PureWeen) [reply src/Core/src/Platform/iOS/MauiView.cs:343]: Theoretically it could be now but once we start implementing the per edge safearea this method is going to look very different for scrollview compared to UIView

File: src/Core/src/Platform/iOS/MauiScrollView.cs [hunk 3]
```diff
@@ -1,33 +1,169 @@
...
+
+		/// <summary>
+		/// Determines whether this scroll view should respond to safe area changes.
+		/// Returns false if this scroll view is nested within another scroll view,
+		/// as nested scroll views should not apply their own safe area adjustments.
+		/// </summary>
+		/// <returns>True if this scroll view should apply safe area adjustments, false otherwise.</returns>
+		bool RespondsToSafeArea()
+		{
+			return !(_scrollViewDescendant ??= Superview.GetParentOfType<UIScrollView>() is not null);
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/MauiScrollView.cs:118]: In the MaiuView, we got code like this:

```
return (_respondsToSafeArea = RespondsToSelector(new Selector("safeAreaInsets"))).Value;
```

Should this also check to see if the OS supports it, or is this not needed since this was iOS 11+. Should we remove from maui view and then drop that whole check?

File: src/Core/src/Platform/iOS/MauiView.cs [hunk 4]
```diff
@@ -7,106 +7,258 @@
...
+				return false;
+			}
+
 			if (_respondsToSafeArea.HasValue)
+			{
 				return _respondsToSafeArea.Value;
-			return (bool)(_respondsToSafeArea = RespondsToSelector(new Selector("safeAreaInsets")));
+			}
+
+			return (_respondsToSafeArea = RespondsToSelector(new Selector("safeAreaInsets"))).Value;
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/MauiView.cs]: From the top, is this needed? Should it also go in the ScrollView or should we delete? This is iOS 11+ and MacCat 13.1+.

**Review by mattleibow — DISMISSED** [review]
LGTM

**Review by mattleibow — APPROVED** [review]

File: src/Core/src/Platform/iOS/MauiView.cs [hunk 5]
```diff
@@ -7,106 +7,253 @@
...
+	/// and MAUI's cross-platform layout system.
+	/// </summary>
 	public abstract class MauiView : UIView, ICrossPlatformLayoutBacking, IVisualTreeElementProvidable, IUIViewLifeCycleEvents, IPlatformMeasureInvalidationController
 	{
-		bool _invalidateParentWhenMovedToWindow;
+		/// <summary>
+		/// Cached result of whether the current iOS version supports safe area insets.
+		/// This is determined once and reused across all MauiView instances for performance.
+		/// </summary>
 		static bool? _respondsToSafeArea;
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/MauiView.cs]:
```suggestion
```

**Review by mattleibow — CHANGES_REQUESTED** [review]

**Review by mattleibow — DISMISSED** [review]

File: src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue16918Test.png
Comment (PureWeen) [inline src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue16918Test.png:1]: One change in this PR is how content is centered when it's smaller than the scrollable area. In that scenario, the content is now centered **between the safe area insets**, which results in a small shift—about 5 pixels in this case. I'm having trouble getting all the layout systems to cooperate smoothly.

The tricky part is that our child views implicitly handle `SafeAreaInsets`, while `UIScrollView` introduces its own **automatic** behaviors as the `contentSize` grows or shrinks.

The core issue I've been chasing is a layout loop that occurs when the content is around **770dp tall**. At that size, `UIScrollView` enters a state where the child view starts reporting non-zero `SafeAreaInsets`. This causes the child to expand to **814dp**. Now that the child is larger than the scroll view’s bounds, the scroll view absorbs the safe area insets and moves them into its `AdjustedContentInset`, which in turn resets the child’s `SafeAreaInsets` to zero.

With no safe area insets, the child shrinks back to 770dp, which causes the scroll view to reapply the insets, and the cycle repeats—resulting in a layout loop.

This PR resolves that by disabling safe area handling on child views within scroll views. That works well in most cases, except when you're intentionally trying to center content.

This is also a behavior specific to `ContentInsetAdjustmentBehavior.Automatic`.

Once the `SafeAreaEdges` PR is merged, developers will be able to set `SafeAreaEdges="None"` on a scroll view to disable this behavior and take full control over how safe areas are handled which will then fully center.

I will revisit this change once we merge this PR and the new properties here https://github.com/dotnet/maui/pull/30337 because that PR will light up a few more features for developers so they can control how SafeAreas are interpreted on the SV

File: src/Core/src/Platform/iOS/MauiScrollView.cs [hunk 6]
```diff
@@ -1,33 +1,173 @@
...
+		/// Called by iOS when the safe area insets change (e.g., device rotation, notch visibility).
+		/// This method marks the safe area as invalidated. Note that UIKit automatically calls
+		/// LayoutSubviews immediately after this method.
+		/// </summary>
+		public override void SafeAreaInsetsDidChange()
+		{
+			// Note: UIKit invokes LayoutSubviews right after this method
+			base.SafeAreaInsetsDidChange();
+
+			_safeAreaInvalidated = true;
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/MauiScrollView.cs:148]: Could update one of the added UITests to rotate the device? Must trigger `SafeAreaInsetsDidChange`  re-layout the content correctly.

File: src/Controls/tests/TestCases.HostApp/Issues/Issue24246.xaml [hunk 7]
```diff
@@ -0,0 +1,11 @@
+<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
+             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
+             x:Class="Maui.Controls.Sample.Issues.Issue24246"
+             Title="Issue24246"
+             xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
+             ios:Page.UseSafeArea="false">
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.HostApp/Issues/Issue24246.xaml:6]: Could we validate that can update the ios:Page.UseSafeArea property at runtime? Like tapping a Button.

File: src/Core/src/Platform/iOS/MauiView.cs [hunk 8]
```diff
@@ -7,106 +7,270 @@
...
+			// This makes sense for non-scrolling scenarios, but creates a problem: if a child view's height increases due to safe area,
+			// it can push ContentSize over the Bounds, causing AdjustedContentInset to become non-zero and SafeAreaInsets on the child to reset to zero.
+			// This can result in a loop of invalidations as the layout toggles between these states (child applies safe area, triggers scrollview to adjust, which removes safe area from child, and so on).
+			//
+			// To prevent this, we ignore safe area calculations on child views when they are inside a scroll view.
+			// The scrollview itself is responsible for applying the correct insets, and child views should not apply additional safe area logic.
+			//
+			// For more details and implementation specifics, see MauiScrollView.cs, which contains the logic for safe area management
+			// within scroll views and explains how this interacts with the overall layout system.
+			_scrollViewDescendant = Superview.GetParentOfType<UIScrollView>() is null;
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/MauiView.cs:119]: `Superview.GetParentOfType<UIScrollView>()` walks up the view hierarchy tree from this view finding UIScrollView. This happens every time safe area is validated but also during layout operations (`LayoutSubViews`). 
Can we cache the result and only recalculates when the view hierarchy changes? (can use `MovedToSuperview`)

Comment (PureWeen) [reply src/Core/src/Platform/iOS/MauiView.cs:119]: This value already is cached

image

And it's reset here
image

File: src/Controls/tests/TestCases.HostApp/Issues/Issue24246.xaml (hunk 7 above)
Comment (PureWeen) [reply src/Controls/tests/TestCases.HostApp/Issues/Issue24246.xaml:6]: We have an issue here "Issue3809" 

image


That sets and unsets this value to make sure that it works

We can task SF with generating more tests around this, especially for NET10 as we roll these features in

File: src/Core/src/Platform/iOS/MauiScrollView.cs (hunk 6 above)
Comment (PureWeen) [reply src/Core/src/Platform/iOS/MauiScrollView.cs:148]: yea! if the rest of this PR seems alright 

Let's merge this for now and I'll have SF add it in or I will just add it to this PR
https://github.com/dotnet/maui/pull/30337

Which will be incoming!!

We already have a number of tests that perform orientation and visual checks so I'm fairly confident about this
But an added test would be helpful

File: src/Core/src/Platform/iOS/SafeAreaPadding.cs [hunk 9]
```diff
@@ -0,0 +1,46 @@
...
+	public double VerticalThickness { get; } = Top + Bottom;
+
+	public CGRect InsetRect(CGRect bounds)
+	{
+		if (IsEmpty)
+		{
+			return bounds;
+		}
+
+		return new CGRect(
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/SafeAreaPadding.cs:22]: Here, could we include a validation to prevent negative dimensions when padding exceeds bounds? (technically possible, although it probably wouldn't happen).

File: src/Core/src/Platform/iOS/MauiView.cs [hunk 10]
```diff
@@ -148,6 +335,44 @@ public override void LayoutSubviews()
...
+			_safeAreaInvalidated = false;
+
+			// Store the information about the safe area for developers to use
+			if (View is ISafeAreaView2 safeAreaPage)
+			{
+				safeAreaPage.SafeAreaInsets = SafeAreaInsets.ToThickness();
+			}
+
+			var oldSafeArea = _safeArea;
+			_safeArea = SafeAreaInsets.ToSafeAreaInsets();
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/MauiView.cs:361]: Noticed iOS can trigger multiple times with same values, we could only process if actually changed to avoid redundant calculations.

**Review by jsuarezruiz — APPROVED** [review]

File: src/Core/src/Platform/iOS/SafeAreaPadding.cs (hunk 9 above)
Comment (PureWeen) [reply src/Core/src/Platform/iOS/SafeAreaPadding.cs:22]: Will resolve on https://github.com/dotnet/maui/pull/30337

File: src/Core/src/Platform/iOS/MauiView.cs (hunk 10 above)
Comment (PureWeen) [reply src/Core/src/Platform/iOS/MauiView.cs:361]: will resolve on https://github.com/dotnet/maui/pull/30337
