### PR TITLE
Fix crash if users only sets selected color on android bottom tabs

### LINKED ISSUE #19299: Android - Setting only SelectedTabColor on TabbedPage causes System.NullReferenceException
### Description

Setting `TabbedPage` property `SelectedTabColor`, either by code or XAML, causes `NullReferenceException` on Android when `UnselectedTabColor` is not present. 

On iOS it works properly.

### Steps to Reproduce

1. Create a TabbedPage.
2. Set the `SelectedTabColor` in either the XAML or in code for the TabbedPage

### Link to public reproduction project repository

https://github.com/Asfiroth/MauiTabbedPageIssue

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 33

### Did you find any workaround?

_No response_

### Relevant log output

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Graphics.Platform.GraphicsExtensions.AsColor(Color target) in D:\a\_work\1\s\src\Graphics\src\Graphics\Platforms\Android\GraphicsExtensions.cs:line 28
   at Microsoft.Maui.Platform.ColorExtensions.ToPlatform(Color self) in D:\a\_work\1\s\src\Core\src\Platform\Android\ColorExtensions.cs:line 14
   at Microsoft.Maui.Controls.Handlers.TabbedPageManager.GetItemIconTintColorState() in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\TabbedPageManager.cs:line 624
   at Microsoft.Maui.Controls.Handlers.TabbedPageManager.UpdateItemIconColor() in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\TabbedPageManager.cs:line 670
   at Microsoft.Maui.Controls.Handlers.TabbedPageManager.UpdateTabItemStyle() in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\TabbedPageManager.cs:line 702
   at Microsoft.Maui.Controls.TabbedPage.MapBarTextColor(ITabbedViewHandler handler, TabbedPage view) in D:\a\_work\1\s\src\Controls\src\Core\TabbedPage\TabbedPage.Android.cs:line 64
   at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass2_0`2[[Microsoft.Maui.Controls.TabbedPage, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ITabbedViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ReplaceMapping>b__0(ITabbedViewHandler h, TabbedPage v, Action`2 p) in D:\a\_work\1\s\src\Core\src\PropertyMapperExtensions.cs:line 66
   at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass1_0`2[[Microsoft.Maui.Controls.TabbedPage, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ITabbedViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ModifyMapping>g__newMethod|0(IElementHandler handler, IElement view) in D:\a\_work\1\s\src\Core\src\PropertyMapperExtensions.cs:line 46
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.ITabbedView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ITabbedViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 172
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 47
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 82
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 79
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ITabbedView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 53
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ITabbedView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 56
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 921
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 863
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 2031
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 96
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 127
   at Microsoft.Maui.Platform.ScopedFragment.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\Navigation\ScopedFragment.cs:line 32
   at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_inflater, IntPtr native_container, IntPtr native_savedInstanceState) in C:\a\_work\1\s\generated\androidx.fragment.fragment\obj\Release\net6.0-android\generated\src\AndroidX.Fragment.App.Fragment.cs:line 2031
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 367
```

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

When setting just the selected color we weren't account for the user not setting the default color. This PR extracts the default color from the styles and then uses that for the default color

### Issues Fixed

Fixes #19299

### CODE REVIEW

File: src/Controls/src/Core/Platform/Android/TabbedPageManager.cs [hunk 1]
```diff
@@ -622,7 +625,42 @@ protected virtual ColorStateList GetItemIconTintColorState()
...
+					}
+					else
+					{
+						// These are the defaults currently set inside android
+						// It's very unlikely we'll hit this path because the 
+						// NavigationBarView_itemIconTint should always resolve
+						// But just in case, we'll just hard code to some defaults
+						// instead of leaving the application in a broken state
+						if(IsDarkTheme)
+							defaultColor = new Color(1, 1, 1, 0.6f).ToPlatform();
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/TabbedPageManager.cs:654]: Instead of hardcoding, can we recover default values from resources?

Comment (PureWeen) [reply src/Controls/src/Core/Platform/Android/TabbedPageManager.cs:654]: That's what the code above this is doing. This is fallback code if for some reason we fail to retrieve the defaults from the resources

**Review by jfversluis — APPROVED** [review]

**Comment by PureWeen** [comment]
Failing tests unrelated
