### PR TITLE
[Android] Span line height fix

### LINKED ISSUE #19592: Span LineHeight Wrong on Android
### Description

When using a generic `Label` with a `Span`, the `LineHeight` seems to be exponentially applied or something on Android.

I understand that there are platform differences, but this behavior simply doesn't work and isn't usable. Is there something I'm misunderstanding or missing?

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">
    <Grid x:Name="contentGrid">
        <Label LineBreakMode="WordWrap">
            <Label.FormattedText>
                <FormattedString>
                    <Span LineHeight="1.15">Outside, the church's garden was a haven of tranquility, where nature and spirituality intertwined harmoniously. Flowers bloomed in vibrant hues, each petal seemingly capturing a prayer or hope of the visitors who walked among them. The garden, lovingly tended by members of the congregation, reflected the church's commitment to nurturing not just the soul, but also the beauty of the world around it. It was a place where people of all walks of life could find solace, inspiration, and a sense of belonging within the embrace of the church's community.</Span>
                </FormattedString>
            </Label.FormattedText>
        </Label>
    </Grid>
</ContentPage>
```

image

When the `LineHeight` is removed:
image

### Xamarin 
In Xamarin, this works as intended:
image

### Steps to Reproduce

1. Pull the reproduction project
2. Run and see 

Or
1. Paste the following XAML into a new MAUI project:
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">
    <Grid x:Name="contentGrid">
        <Label LineBreakMode="WordWrap">
            <Label.FormattedText>
                <FormattedString>
                    <Span LineHeight="1.15">Outside, the church's garden was a haven of tranquility, where nature and spirituality intertwined harmoniously. Flowers bloomed in vibrant hues, each petal seemingly capturing a prayer or hope of the visitors who walked among them. The garden, lovingly tended by members of the congregation, reflected the church's commitment to nurturing not just the soul, but also the beauty of the world around it. It was a place where people of all walks of life could find solace, inspiration, and a sense of belonging within the embrace of the church's community.</Span>
                </FormattedString>
            </Label.FormattedText>
        </Label>
    </Grid>
</ContentPage>
```

### Link to public reproduction project repository

https://github.com/bradencohen/MauiRepros

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

Nope, but any ideas would be **super** appreciated.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

 The `fm.Top` value was constantly increasing so that the height of each line grew progressively. Instead, the line height should be adjusted based on the initial top value of font metrics

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/19592

|Before|After|
|---|---|
|||

### CODE REVIEW

File: src/Controls/tests/UITests/Tests/Issues/Issue19592.cs [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+		public void SpanLineHeightShouldNotGrowProgressively()
+		{
+			this.IgnoreIfPlatforms(new TestDevice[] { TestDevice.iOS, TestDevice.Mac, TestDevice.Windows });
+
+			_ = App.WaitForElement("label");
+
+			// The line height should be the same for each line
+			// of the paragraph, 1.5 and 2.5 respectively,
+			// as opposed to progressively growing
+			App.Screenshot();
```
Comment (jsuarezruiz) [inline src/Controls/tests/UITests/Tests/Issues/Issue19592.cs:25]: Could we use here `App.VerifyScreenshot`? This will generate a snapshot to compare it with a reference one.

**Review by jsuarezruiz — COMMENTED** [review]
The test `NativeFormattedStringContainsSpan `seems to be failing with the changes
`Java.Lang.NullPointerException : Attempt to read from field 'float android.util.DisplayMetrics.scaledDensity' on a null object reference`

**Comment by kubaflo** [comment]
> NativeFormattedStringContainsSpan

Fixed

File: src/Controls/tests/UITests/Tests/Issues/Issue19592.cs (hunk 1 above)
Comment (kubaflo) [reply src/Controls/tests/UITests/Tests/Issues/Issue19592.cs]: Done

**Comment by kubaflo** [comment]
@jsuarezruiz I have fixed the falling test

File: src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs [hunk 2]
```diff
@@ -64,6 +64,12 @@ public static SpannableString ToSpannableString(this Label label)
 
 			var builder = new StringBuilder();
 
+			var fontMetrics = context?.Resources?.DisplayMetrics != null ? new Paint()
+			{
+				TextSize = TypedValue.ApplyDimension(ComplexUnitType.Sp, (float)defaultFontSize, context.Resources.DisplayMetrics)
```
Comment (jonathanpeppers) [inline src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs:69]: This line looks like it would throw if `context.Resources` returned `null`.

File: src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs [hunk 3]
```diff
@@ -64,6 +64,12 @@ public static SpannableString ToSpannableString(this Label label)
...
+			}.GetFontMetrics()
+			: null;
```
Comment (jonathanpeppers) [inline src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs:71]: Could we write this code in Java, it looks like it interops between C# and Java a lot. I've seen some past issue complaining about Android FormattedString performance like:

* https://github.com/dotnet/maui/issues/14222

So we'd make a version of this method that returns "Font metrics" instead of "Window metrics":

https://github.com/dotnet/maui/blob/ad28b65309edbfa3be0e01480662ee5cb013b5d4/src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformInterop.java#L581-L592

File: src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs (hunk 2 above)
Comment (kubaflo) [reply src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs:69]: #I'm not sure why it would throw🤔
The only place that `fontMetrics` is  here https://github.com/dotnet/maui/blob/24d404991a5b7246dc05be856effea1ca0f3bf25/src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs#L110 and there's a null check

File: src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs (hunk 3 above)
Comment (kubaflo) [reply src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs:71]: Yes, that would be beneficial, but I'm not sure how to write this code in JAVA and how to use it in MAUI

Comment (jonathanpeppers) [reply src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs:71]: If you add a method in this file, it will magically appear on the `PlatformInterop` static class, you can call from C# like:
```
//signature
public static Rect GetCurrentWindowMetrics(Activity activity);

//usage
var rect = PlatformInterop.GetCurrentWindowMetrics(myActivity);
```

Comment (kubaflo) [reply src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs]: Thank you! I pushed a new commit with this functionality

Comment (jonathanpeppers) [reply src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs]: I made one small change, but it seems like this should be ready if we fix up the screenshot.

**Review by jonathanpeppers — DISMISSED** [review]
This looks good to me if the new test & screenshot work. 👍

**Review by jsuarezruiz — DISMISSED** [review]

**Review by jonathanpeppers — APPROVED** [review]
Fixed the merge conflict.

**Review by PureWeen — APPROVED** [review]

**Comment by PureWeen** [comment]
Not sure why UI Tests aren't triggering
Manual run here
https://dev.azure.com/xamarin/public/_build/results?buildId=112277&view=results
