### PR TITLE
[Windows] Fix CarouselView not showing new items

### LINKED ISSUE #17830: [Windows] New CarouselView item doesn't render unless Window is resized
### Description

When a new item is added to a CarouselView, the CarouselView does not reflect the updated collection until the window is resized.

### Steps to Reproduce

1. Run recipeSearch repo on rc2
2. Deploy to Windows machine
3. Click on "My Recipes" tab
4. Click "New" button in upper right corner
5. Type anything into Recipe Name field
6. Click "Save"
7. Scroll CarouselView and notice new item is not present
8. Resize window
9. Scroll CarouselView again and notice new item now appears

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Foda**
### Description of Change

Fix CarouselView not showing new items. This was caused by the inner list of `LoopableCollectionView` not propagating the `VectorChanged` event

### Issues Fixed

Fixes #17830 #22417

### CODE REVIEW

File: src/Controls/src/Core/Platform/Windows/CollectionView/LoopableCollectionView.cs [hunk 1]
```diff
@@ -22,6 +22,7 @@ internal class LoopableCollectionView : ICollectionView
 		public LoopableCollectionView(ICollectionView @internal)
 		{
 			_internal = @internal;
+			_internal.VectorChanged += OnItemsVectorChanged;
```
Comment (PureWeen) [inline src/Controls/src/Core/Platform/Windows/CollectionView/LoopableCollectionView.cs:25]: Do we need to unsubscribe from this? Will the internal `ICollectionView` survive the lifetime of this class?

**Review by rmarinho — APPROVED** [review]
