### PR TITLE
[Anndroid] Fix crash using Shadows with CollectionView items 

### LINKED ISSUE #5402: IllegalStateException when setting shadow to a DataTemplate in a CollectionView
### Description

Upgraded to Preview 14 today and this piece of code no longer works.

````
<CollectionView Grid.Row="4" ItemsSource="{Binding Items}">
    <CollectionView.ItemTemplate>
        <DataTemplate>
            <ImageButton
                Grid.Row="4"
                Aspect="AspectFit"
                HeightRequest="310"
                HorizontalOptions="Center"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                Source="{Binding}"
                WidthRequest="250">
                <ImageButton.Style>
                    <Style TargetType="ImageButton">
                        <Setter Property="Shadow">
                            <Setter.Value>
                                <Shadow Brush="black" Opacity="20" />
                            </Setter.Value>
                        </Setter>
                        <Style.Triggers>
                             <DataTrigger
                                Binding="{Binding IsSelected}"
                                TargetType="ImageButton"
                                Value="true">
                                <Setter Property="Shadow">
                                    <Setter.Value>
                                        <Shadow
                                            Brush="white"
                                            Opacity="0.50"
                                            Radius="25" />
                                    </Setter.Value>
                                </Setter>
                            </DataTrigger>
                        </Style.Triggers>
                    </Style>
                </ImageButton.Style>
            </ImageButton>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
````

### Steps to Reproduce

1. Create a .NET MAUI App (non-blazor)
2. Replace the Image XAML with the code from the description
3.  Do the following in MainPage code behind
- Add Microsoft.Toolkit.Mvvm via Nuget
- Add a IsSelected property
````
private bool _isSelected = false;
public bool IsSelected
{
    get => _isSelected;
    set
    {
        _isSelected = value;
        OnPropertyChanged();
    }
}
````
- Add a new function (note, not required for this bug, but here to trigger the style when the bug is fixed):
````
[ICommand]
private void Test(object t)
{
    IsSelected = !IsSelected;
}
````
- Update the constructor:
````
public MainPage()
{
    InitializeComponent(); 
    BindingContext = this;
}
````
4. Run the application
5. Notice the unhandled exception

image

### Version with bug

Preview 14 (current)

### Last version that worked well

Preview 13

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Tested and failed on both A11 and A12

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix crash using Shadows with CollectionView items in Android. 
image

When using shadows on Android, the WrapperView was used, so the PlatformView already had a parent. This PR adds changes to ItemContentView to use the correct native view (ContainerView or PlatformView). 

### Issues Fixed

Fixes #5402

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/Android/ItemContentView.cs [hunk 1]
```diff
@@ -26,7 +25,8 @@ public ItemContentView(Context context) : base(context)
 		internal void RealizeContent(View view, ItemsView itemsView)
 		{
 			Content = CreateHandler(view, itemsView);
-			AddView(Content.PlatformView);
+			var platformView = Content.ContainerView ?? Content.PlatformView;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items/Android/ItemContentView.cs:28]: This is the main change fixing the issue.

**Review by Redth — APPROVED** [review]
