### PR TITLE
Recreate Details Fragment, if its been destroyed

### LINKED ISSUE #17444: [regression/8.0.0] [Android] Fix ToolbarUpdatesCorrectlyWhenSwappingMainPageWithAlreadyUsedPage
### Description

Better loading code revealed that ToolbarUpdatesCorrectlyWhenSwappingMainPageWithAlreadyUsedPage is failing on android

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

If a FlyoutPage is reused after being removed, we need to just recreate the DetailsViewFragment

### Issues Fixed

Fixes #17444

### CODE REVIEW

File: src/Controls/tests/DeviceTests/Elements/Toolbar/ToolbarTests.cs [hunk 1]
```diff
@@ -119,27 +119,27 @@ public async Task ToolbarTitle()
 
 		[Theory]
 		[InlineData($"{nameof(FlyoutPage)}WithNavigationPage, {nameof(ContentPage)}, {nameof(FlyoutPage)}WithNavigationPage"
-#if ANDROID || WINDOWS
+#if WINDOWS
```
Comment (affableashish) [inline src/Controls/tests/DeviceTests/Elements/Toolbar/ToolbarTests.cs:122]: If ANDROID is removed from the check, should the Skip comment also be updated?
For eg: "Currently Failing on Windows https://github.com/dotnet/maui/issues/17444"?

**Review by samhouts — APPROVED** [review]
