### PR TITLE
Fix AmbigousMatchException between duplicated types Core and Controls

### LINKED ISSUE #4300: AmbigousMatchException throwing when a control that inherent from Element is instantiated
### Description

During runtime when the code executes the `new SimplePopup();` call, it throws the `System.Reflection.AmbigousMatchException` in the `InitializeComponent` method, I wasn't unable to go footer but looks like that happened during the `SetBinding` phase.

image

Here's a better image from the stack trace:
image

### Steps to Reproduce

Repo: https://github.com/CommunityToolkit/Maui/tree/pj/popup-to-handler

1. Run the MCT sample app
2. On the home page, tap in the last item (Popup)
3. Tap on the first item, (PopupAnchorPage)
4. Tap on the Show button

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.3

### Did you find any workaround?

Create a Csharp page instead.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Avoid AmbigousMatchException between duplicated types in Microsoft.Maui and Microsoft.Maui.Controls. Renamed IElement from Microsoft.Maui.Controls.

There are similar cases like:
- LayoutAlignment (Why not an unique type in Core using the Flags attribute?)

### Issues Fixed

Fixes #4300

### CODE REVIEW

File: src/Core/src/Primitives/LayoutAlignment.cs [hunk 1]
```diff
@@ -1,30 +1,33 @@
...
+﻿using System;
+
+namespace Microsoft.Maui.Primitives
 {
 	// We don't use Microsoft.Maui.Controls.LayoutAlignment directly because it has a Flags attribute, which we do not want
 
 	/// <summary>
 	/// Determines the position and size of an IView when arranged in a parent element
 	/// </summary>
+	[Flags]
```
Comment (StephaneDelcroix) [inline src/Core/src/Primitives/LayoutAlignment.cs:10]: the comment says, literally:
```
// We don't use Microsoft.Maui.Controls.LayoutAlignment directly because it has a Flags attribute, which we do not want
```

Comment (jsuarezruiz) [reply src/Core/src/Primitives/LayoutAlignment.cs]: I missed this comment, updated.

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
>          D:\a\_work\1\s\src\Controls\tests\Core.UnitTests\ResourceDictionaryTests.cs(140,20): error CS1061: 'IElement' does not contain a definition for 'AddResourcesChangedListener' and no accessible extension method 'AddResourcesChangedListener' accepting a first argument of type 'IElement' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Controls\tests\Core.UnitTests\Controls.Core.UnitTests.csproj]
