### PR TITLE
[windows] Fixed CarouselView items rendering

### LINKED ISSUE #12567: Carousel View does not behave properly in Windows
### Description

In Android, Carousel view item takes full-screen width, But in Windows, it takes content width

**Android**
image

**Windows**
image

Note : Not checked in iOS and MacCatalyst

### Steps to Reproduce

1. Run the attached sample
2. Run in Android 
3. Run in Windows
4. See the Difference in the View

### Link to public reproduction project repository

https://github.com/EwaldJebaraj/CarouselViewIssue

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.19041.0

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

### LINKED ISSUE #12850: CarouselView on Windows totally broken
### Description

If loop=False in CarouselView if you change the CollectionView this is not reflected at all on Windows (but works on Android).
If you set loop=True in CarouselView even if you have 1 item in your CollectionView Windows renders it like 20 times. Again, this works on Android.

### Steps to Reproduce

- Get the repo and get the [CarouselViewOnWindowsBroken](https://github.com/rogerbriggen/mauiCarouselViewProblems/tree/CarouselViewOnWindowsBroken) branch
- Start the app
- Click any of the buttons -> On Windows, the UI does not update, on Android it works
- Stop the app

Change loop=True in MainPage.xaml
- Start the app
- See the horrable rending on Windows, on Android it works
- Push the button to add 2 new items
- Now, at least the text is updated even on Windows but still rendered unusable
- Stop the app
Windows_LoopIsTrue_Started

### Link to public reproduction project repository

https://github.com/rogerbriggen/mauiCarouselViewProblems.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 22H2

### Did you find any workaround?

The only thing mostly working is set loop=false and then create a new ObservableCollection everytime something changes and also raise INotifyPropertyChanged for the ObservableCollection.

### Relevant log output

_No response_

### LINKED ISSUE #13057: [Windows] CarouselView Layout is broken
### Description

CarouselView Layout is broken. The item size is wrong.

Windows
image

Android
fhl-result

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/netmaui-movies-app-challenge
2. Launch the App on Windows

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-movies-app-challenge

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 22H2

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #16322: [WinUI] CarouselView layout issues
### Description

This is an extension of issue https://github.com/dotnet/maui/issues/15914

**_Note: The version used is 8.0.0-preview.6 ... not available to select in the dropdown below._**

The control events now fire, (Thank you!) but, there are several "layout" issues that are still present. I created a repo that not only shows the layout peculiarities, but also code workarounds...

The top frame is using the standard CarouselView, and the bottom uses a custom AppendMapper. The templated controls are using a dynamic TemplateSelector to display the child's content.

1. Notice that the top control does not show the first item, and does not remove the horizontal scrollbar even though it is set... HorizontalScrollBarVisibility="Never"
2. If you use the scroll wheel on your mouse, you will notice that the scroll response is not correct. Settings: 
`<LinearItemsLayout
		ItemSpacing="0"
		Orientation="Horizontal"
		SnapPointsAlignment="Center"
		SnapPointsType="{OnPlatform WinUI='Mandatory', Android='MandatorySingle'}"/>`

3. If you horizontally resize the form, all of the items will fail so draw correctly.
4. If you tap the "tabs" to move from an item that is not adjacent to it, it will only move one page at a time.

The templated control relies on the parent ".IsDragging" property. I notice in the code (ScrollViewer) that the "_scrollViewer.ViewChanging" event code is setting both "IsDragging" and "IsScrolling" to true, as opposed to the event args returned, "IsInertial"... this makes a difference to determine if the control actually being scrolled/dragged, or the form is being resized. (Portrait/Lanscape). etc.

The lower frame control corrects these issues.

StedySoft MauiCarouselView

### Steps to Reproduce

Please review the attached repo...

### Link to public reproduction project repository

https://github.com/Stedy59/MauiCarouselView

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK - all

### Did you find any workaround?

Yes, I created a CarouselView using the CollectionView control. 

I added the few missing properties to the collectionview, and created a custom AppendMapper to digest those properties.

The attached repo has the code.

### Relevant log output

_No response_

### Related, should be fixed at the same time
- [x] https://github.com/dotnet/maui/issues/13057
- [x] https://github.com/dotnet/maui/issues/12850
- [x] https://github.com/dotnet/maui/issues/12567
- [ ] https://github.com/dotnet/maui/issues/6356

### PR DESCRIPTION
**Pull request by mauroa**
### Description of Change

Added ArrangeOverride override and changed MeasureOverride in ItemContentControl to not call the base implementation when the ItemHeight and ItemWidth are already defined.

When the height and width of the items are already defined, it's likely that the base.MeasureOverride (WinUI) call reduces the original size, causing issues like the items in a CarouselView not fitting the container, which causes more items to be displayed at once. This fix makes sure that we always return the max height and width between the measured override and the existing items height and width. Also, adding ArrangeOverride from WinUI base class to control the layout correctly and completely on our side.

CarouselView before the fix:

CarouselBroken

CarouselView after the fix:

CarouselFixed

Also added Apium tests to validate that a single item is always shown in the carousel.

- Fixes #12567 
- Fixes #13057
- Fixes #12850

### CODE REVIEW

**Comment by samhouts** [comment]
I wonder if this will also fix these:

https://github.com/dotnet/maui/issues/13057
 https://github.com/dotnet/maui/issues/12850

File: src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs [hunk 1]
```diff
@@ -263,58 +263,43 @@ void UpdateSemanticProperties(IView view)
...
-					WinUIHelpers.CreateThickness(
-						margin.Left + ItemSpacing.Left,
-						margin.Top + ItemSpacing.Top,
-						margin.Right + ItemSpacing.Right,
-						margin.Bottom + ItemSpacing.Bottom);
+			base.ArrangeOverride(size);
 
-				if (CanMeasureContent(frameworkElement))
-					frameworkElement.Measure(wsize);
+			return size;
```
Comment (jknaudt21) [inline src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs:280]: Curious why we are returning this `size`. Shouldn't we return the `base.ArrangeOverride(size)` since we're calling it in a line above?

**Comment by jknaudt21** [comment]
This is awesome! Considering that the control was super broken until now, this is a _**huge**_ improvement.  Some minor things to consider though: 

- Scrolling through the CarouselView flickers a bit and seems to be more sensitive when scrolling in one direction than the other. In the gif below I change scroll directions and the view began flickering. **This was present _before_ this PR** so I doubt  these changes had an effect.
Scroll2
- If I resize my screen, the CarouselView doesn't remain centered/move with the resize. If I resize long enough, I see (and can interact with) the other items in the view. **Testing this out before this PR changes was impossible, however, since the control was broken**
LongResize

File: src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs (hunk 1 above)
Comment (mauroa) [reply src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs:280]: Yeah, that's wrong. Good catch, I'll push the fix together with the windows resizing one

**Comment by mauroa** [comment]
> This is awesome! Considering that the control was super broken until now, this is a _**huge**_ improvement. Some minor things to consider though:
> 
> * Scrolling through the CarouselView flickers a bit and seems to be more sensitive when scrolling in one direction than the other. In the gif below I change scroll directions and the view began flickering. **This was present _before_ this PR** so I doubt  these changes had an effect.
>   Scroll2
> * If I resize my screen, the CarouselView doesn't remain centered/move with the resize. If I resize long enough, I see (and can interact with) the other items in the view. **Testing this out before this PR was impossible because the control was broken**
>   LongResize

I fixed the resizing issue, you can see it in the latest commit

**Comment by mauroa** [comment]
> I wonder if this will also fix these:
> 
> #13057 #12850

@samhouts I just linked the other bugs too, after addressing JD's feedback

**Comment by jknaudt21** [comment]
@mauroa I think there are still a couple of rough edges with the resize changes you pushed.

<details> <summary> Grey blocks appear when resizing and it doesn't work 100% of the time </summary>

Resize2

</details>

<details> <summary> Sometimes a resizing very fast causes the app to crash with an NRE.  </summary> 

This seems to be easier to repro by resizing as soon as the page loads, so it might be that something isn't fully yet initialized? The failure eventually traces to  WindowsMessageManager.uwp.cs. 
NRE

File: src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Windows.cs [hunk 2]
```diff
@@ -521,15 +522,19 @@ void OnCollectionItemsSourceChanged(object sender, NotifyCollectionChangedEventA
...
-				ListViewBase.SizeChanged -= InitialSetup;
+		void OnListViewSizeChanged(object sender, SizeChangedEventArgs e) => Resize(e.NewSize);
 
-				if (_scrollViewer != null)
-					_scrollViewer.SizeChanged -= InitialSetup;
+		void OnScrollViewSizeChanged(object sender, SizeChangedEventArgs e)
+		{
+			//If there's a scroll viewer, it's enough to resize based on its size changed event, so we can avoid two event handlers doing the same
+			ListViewBase.SizeChanged -= OnListViewSizeChanged;
+			Resize(e.NewSize);
```
Comment (jknaudt21) [inline src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Windows.cs:531]: Maybe check that the newSize or that the eventArgs aren't null? This might be the cause of the NRE I saw

**Comment by mauroa** [comment]
> @mauroa I think there are still a couple of rough edges with the resize changes you pushed.
> 
> Grey blocks appear when resizing and it doesn't re-center 100% of the time
> Sometimes resizing the screen very fast causes the app to crash with an NRE.

I think we should track this grey item thing when resizing, as a separate issue to investigate. I can reproduce it before my changes and it probably affects other controls as well, it looks like a refreshing issue. Given this PR fixes three bugs and the refreshing issue is pre-existing, I would say we are safe to go and open a separate issue to track the remaining one.

**Review by jknaudt21 — DISMISSED** [review]
Approving so the fix can go in and then later polish the issue with resizing the screen.

**Review by hartez — APPROVED** [review]
