### PR TITLE
Ensure InvokeAsync(Func<Task>) is properly awaited

### LINKED ISSUE #2313: [Bug] BlazorWebView: WindowsFormsDispatcher.InvokeAsync implementation issues
### Description

`BlazorWebView` has a helper internal class [`WindowsFormsDispatcher`](https://github.com/dotnet/maui/blob/f7566cd6bb095dfdf9079bb61b3932ad7758e785/src/BlazorWebView/src/WindowsForms/WindowsFormsDispatcher.cs#L16), for queueing callbacks as tasks on the UI thread that hosts `WebView2`. I believe I've spotted a potential performance issue and a bug with various `WindowsFormsDispatcher.InvokeAsync` overrides:

#### 1. Redundant allocations of kernel objects and context switching in<br> `async Task WindowsFormsDispatcher.InvokeAsync(Action workItem)`

The current implementation of `WindowsFormsDispatcher.InvokeAsync` uses an override of [`Factory.FromAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskfactory.fromasync?view=net-5.0#System_Threading_Tasks_TaskFactory_FromAsync_System_IAsyncResult_System_Action_System_IAsyncResult__System_Threading_Tasks_TaskCreationOptions_) which accepts `IAsyncResult`. That (most likely) may result in redundant allocations of [`IAsyncResult.AsyncWaitHandle`](https://docs.microsoft.com/en-us/dotnet/api/system.iasyncresult.asyncwaithandle?view=net-5.0). Which, in turn, is an instance of ` ManualResetEvent`, with an underlying Win32 event object. 

[Permalink](https://github.com/dotnet/maui/blob/f7566cd6bb095dfdf9079bb61b3932ad7758e785/src/BlazorWebView/src/WindowsForms/WindowsFormsDispatcher.cs#L65-L78):

```c#
// ...
var asyncResult = _dispatchThreadControl.BeginInvoke(workItem);
await Task.Factory.FromAsync(asyncResult, _dispatchThreadControl.EndInvoke);
```

The further chain of calls can be traced [here](https://github.com/dotnet/winforms/blob/81774abbcbb885fe906f1c0f813e8175eef8705c/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L6890) and [here](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs#L672-L691), where `ThreadPool.RegisterWaitForSingleObject` is called and `AsyncWaitHandle` is passed to it.

Imagine `InvokeAsync` is invoked on the UI thread, which is often the case. The logic initiated by `BeginInvoke` will eventually invoke the desired `action` on the same UI thread, then will call `ManualResetEvent.Set` (for `IAsyncResult.AsyncWaitHandle`) on the same UI thread. That will result in the `ThreadPool.RegisterWaitForSingleObject` callback to be invoked from a pool thread. Which, in turn, will complete the promise-style `task` returned by `Task.FromAsync`, and only then the actual continuation callback for `await  WindowsFormsDispatcher.InvokeAsync(action)` will be queued for execution on the original UI thread (via `SynchronizationContext.Post` of that UI thread). 

This is how far my thought experiment had taken me and I admit I might be wrong in this twisted analysis 🙂 I'm also not a fan of premature optimizations, but I believe this particular workflow can be *greatly* simplified and `ManualResetEvent` allocations / `ThreadPool.RegisterWaitForSingleObject` waits can be completely avoided:

```c#
public static Task InvokeAsync(
    this Control @this,
    Action workItem)
{
    static void Callback(Action workItem, TaskCompletionSource<DBNull> tcs) 
    {
        try
        {
            workItem();
            tcs.TrySetResult(DBNull.Value);
        }
        catch(Exception ex)
        {
            tcs.TrySetException(ex);
        }
    }

    var tcs = new TaskCompletionSource<DBNull>(TaskCreationOptions.RunContinuationsAsynchronously);
    @this.BeginInvoke(Callback, workItem, tcs);
    return tcs.Task;
}        
```

In case such implementation of `InvokeAsync` is invoked and awaited on `WindowsFormsSynchronizationContext`, there will be no context transitions at all.

#### 2. A bug in `async Task WindowsFormsDispatcher.InvokeAsync(Func<Task> workItem)`

[Permalink](https://github.com/dotnet/maui/blob/f7566cd6bb095dfdf9079bb61b3932ad7758e785/src/BlazorWebView/src/WindowsForms/WindowsFormsDispatcher.cs#L65-L78).

All of the above still applies, but here I believe we might also have an actual bug. Imagine the following lambda is provided as `workItem`:

```c#
Func<Task> workItem = static async () => 
{ 
    await Task.Delay(1000); 
    throw new InvalidOperationException(); 
};
```

When we call `await windowDispatcher.InvokeAsync(workItem)` with it,  the awaited call will complete nearly instantly and successfully. That's because `IAsyncResult Control.BeginInvoke(Delegate method)` plays a trick on us here and basically treats `workIteam` as `delegate void method()`, knowing nothing that it's actually an `async Task` method.

One second later, `Task.Delay` completes out-of-band and our `InvalidOperationException` exception is thrown. Because that happens inside an `async Task` method, the exception won't be posted via `WindowsFormsSynchronizationContext.Post` immediately (as it would for an `async void` method), but rather will remain dormant until the `Task` returned by `workItem` is garbage-collected. And even then it could be observed only if there's an active handler for `TaskScheduler.UnobservedTaskException` , otherwise it would be quietly swallowed. At least IIRC, that was the async exception propagation behavior in .NET 4.x. Either way, the exception wouldn't be properly propagated from the above `workItem ` lambda to the caller of `InvokeAsync`.

### Steps to Reproduce

I haven't tried to repro, but see the above analysis.

### Expected Behavior

`await windowDispatcher.InvokeAsync(Func<Task> workItem)` should complete when the task returned by `workItem` has completed. The errors should be properly propagated.

I could propose the following implementation for `await windowDispatcher.InvokeAsync(Func<Task> workItem)` which I believe should work correctly:

```c#
public static Task InvokeAsync(
    this Control @this,
    Func<Task> workItem)
{
    static async void Callback(Func<Task> workItem, TaskCompletionSource<DBNull> tcs) 
    {
        try
        {
            await workItem();
            tcs.TrySetResult(DBNull.Value);
        }
        catch(Exception ex)
        {
            tcs.TrySetException(ex);
        }
    }

    var tcs = new TaskCompletionSource<DBNull>(TaskCreationOptions.RunContinuationsAsynchronously);
    @this.BeginInvoke(Callback, workItem, tcs);
    return tcs.Task;
}        
```

### Actual Behavior

I haven't tried to repro, but see the above analysis.

### Basic Information

- Version with issue: Microsoft.AspNetCore.Components.WebView.WindowsForms v6.0.100-preview.7.1345

NB4: I was participating in a related discussion in [`#4631` at WinForms repo](https://github.com/dotnet/winforms/issues/4631). This might be a good occasion to remind why we need a proper set of `InvokeAsync` APIs for WinForms - tks!

cc @Eilon, @KlausLoeffelmann, @RussKie, @weltkante

### PR DESCRIPTION
**Pull request by pranavkm**
Control.BeginInvoke does not unwrap Tasks returned by delegates. Consequently InvokeAsync that wraps a `Task` will finish as soon as control's dispatching finishes regardless of how long the actual delegate takes. This change updates the WinForms dispatcher to account for completing both the control's dispatching and the completion of the delegate.

Fixes https://github.com/dotnet/maui/issues/2313.

### CODE REVIEW

File: src/BlazorWebView/src/WindowsForms/WindowsFormsDispatcher.cs [hunk 1]
```diff
@@ -72,8 +72,23 @@ public override async Task InvokeAsync(Func<Task> workItem)
...
+							await workItem();
+							tcs.TrySetResult();
+						}
+						catch (Exception ex)
+						{
+							tcs.TrySetException(ex);
+						}
+					};
+
+					var asyncResult = _dispatchThreadControl.BeginInvoke(action, workItem, tcs);
```
Comment (pranavkm) [inline src/BlazorWebView/src/WindowsForms/WindowsFormsDispatcher.cs:90]: Like the issue noted, `BeginInvoke` does not await the operation. Consequently in the current format, the changes to `Index` would result in an exception. Building on the pattern that @noseratio suggested in the issue, we can await both the result of `BeginInvoke` and the completion of the operation.

File: src/BlazorWebView/src/WindowsForms/WindowsFormsDispatcher.cs [hunk 2]
```diff
@@ -120,8 +140,29 @@ public override async Task<TResult> InvokeAsync<TResult>(Func<Task<TResult>> wor
 				}
 				else
 				{
-					var asyncResult = _dispatchThreadControl.BeginInvoke(workItem);
-					return await Task<TResult>.Factory.FromAsync(asyncResult, result => (TResult)_dispatchThreadControl.EndInvoke(result));
+					// See https://github.com/dotnet/winforms/issues/4631 for discussion. `Control.BeginInvoke` in WinForms
+					// does not wait for Tasks returned by the delegate. We will have to simulate this using a TCS and wait for
+					// both execution of `workItem` and the dispatcher to complete it's internal operation.
```
Comment (Eilon) [inline src/BlazorWebView/src/WindowsForms/WindowsFormsDispatcher.cs:145]:
```suggestion
					// both execution of `workItem` and the dispatcher to complete its internal operation.
```

File: src/BlazorWebView/src/WindowsForms/WindowsFormsDispatcher.cs [hunk 3]
```diff
@@ -72,8 +72,28 @@ public override async Task InvokeAsync(Func<Task> workItem)
 				}
 				else
 				{
-					var asyncResult = _dispatchThreadControl.BeginInvoke(workItem);
-					await Task.Factory.FromAsync(asyncResult, _dispatchThreadControl.EndInvoke);
+					// See https://github.com/dotnet/winforms/issues/4631 for discussion. `Control.BeginInvoke` in WinForms
+					// does not wait for Tasks returned by the delegate. We will have to simulate this using a TCS and wait for
+					// both execution of `workItem` and the dispatcher to complete it's internal operation.
```
Comment (Eilon) [inline src/BlazorWebView/src/WindowsForms/WindowsFormsDispatcher.cs:77]:
```suggestion
					// both execution of `workItem` and the dispatcher to complete its internal operation.
```

**Review by Eilon — APPROVED** [review]
Seems to make sense given what we talked about yesterday. Just some comment typos.

File: src/BlazorWebView/src/WindowsForms/WindowsFormsDispatcher.cs [hunk 4]
```diff
@@ -72,8 +72,28 @@ public override async Task InvokeAsync(Func<Task> workItem)
...
+							tcs.TrySetResult();
+						}
+						catch (Exception ex)
+						{
+							tcs.TrySetException(ex);
+						}
+					};
+
+					var asyncResult = _dispatchThreadControl.BeginInvoke(action, workItem, tcs);
+					await Task.WhenAll(tcs.Task, Task.Factory.FromAsync(asyncResult, _dispatchThreadControl.EndInvoke));
```
Comment (noseratio) [inline src/BlazorWebView/src/WindowsForms/WindowsFormsDispatcher.cs:96]: Sorry, I didn't have chance to review this before (as the author of https://github.com/dotnet/maui/issues/2313).

I believe you only need `await tcs.Task` here. 

awaiting `Task.Factory.FromAsync(asyncResult, _dispatchThreadControl.EndInvoke)` in parallel with it is at best redundant. 

cc @Eilon @pranavkm

Comment (pranavkm) [reply src/BlazorWebView/src/WindowsForms/WindowsFormsDispatcher.cs:96]: I wanted to make sure we were awaiting the dispatch in the event there were operations it needed to wrap up after the delegate was executed. By the way, in the case that we're already in the right context, these functions execute inline without this additional overhead. So in the ordinary case, you only pay this extra cost if you're calling from a background thread.
