### PR TITLE
[Android] Fixed Setting a Label visible after having had focus on a InputView will increase the Label's height 

### LINKED ISSUE #29194: [Android][Label] Setting a Label visible after having had focus on a InputView will increase the Label's height
### Description

If you have a Label that is invisible, and then setting it to visible after having had focus on a InputView increases its height. It does not matter if you lose focus on the InputView, and then set the Label visible. However, if you toggle the Label's visibility, and then set focus on InputView, the Label will not increase its height.

Image

### Steps to Reproduce

1. Clone https://github.com/Vetle444/MauiTestApp/tree/vefi/focusFirstIsVisibleTrueExpandingHeight/MauiTestApp
2. Make sure to be on branch: vefi/focusFirstIsVisibleTrueExpandingHeight/MauiTestApp
3. Run app
4. Click Navigate
5. Tap on the Entry
6. Tap on the Switch
7. The Label's height is increased

### Link to public reproduction project repository

https://github.com/Vetle444/MauiTestApp/tree/vefi/focusFirstIsVisibleTrueExpandingHeight/MauiTestApp

### Version with bug

9.0.60 SR6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.50 SR3

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

Override `CreatePlatformView` with a regular `AppCompatTextView` in handler, however, this most likely provokes some bugs 

### Relevant log output

```shell

```

### LINKED ISSUE #29287: I1_Vertical_list_for_Multiple_Rows - Rotating the emulator would cause text to overflow.
### Description

Rotating the Android emulator would cause text to overflow.

Affected case:
I1 - Vertical List for Multiple Rows

Note: 
1. I can repro this issue sometimes on 9.0.60 and 9.0.30 but not on 9.0.0.
2. Sometimes, the text is clipped.

### Steps to Reproduce

1. Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests on android platform.
2. Click I1 -> Vertical List for Multiple Rows.
3. Rotate the android emulator to the right and rotate it back to the original orientation.
4. Observe that the description text overflows inconsistently.

**Actual Behavior:**
The text overflows after rotating the emulator.

Image

**Expected Behavior:**
The text should display normally.

Image

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

Inflight/current - 9.0.70-ci.main.25251.10

### Is this a regression from previous behavior?

Yes, this used to work in 9.0.60 & 9.0.30 & 9.0.0.

### Affected platforms

Android

### PR DESCRIPTION
**Pull request by Ahamed-Ali**
### Root Cause of the issue

- The layout measurements of the TextView may become unstable during initialization. As a result, the GetMaxLineWidth() method can return incorrect values because the `layout` is not fully `initialized`.

### Description of Change

- The fix introduces a validation check using `Layout.Width > 0`. This prevents width calculations during unstable layout transitions and ensures that measurements are only taken when the layout is in a `valid state`. 

### Regressed PR 

- #28215

### Issues Fixed

Fixes #29194 
Fixes #29287 

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Screenshot

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/e0ce4eb5-8edc-4acf-9441-837daf5dbfe7"> | <video src="https://github.com/user-attachments/assets/d1990a5f-ec93-4139-b266-a3318eca9b51"> |

### CODE REVIEW

File: src/Core/src/Platform/Android/MauiTextView.cs [hunk 1]
```diff
@@ -22,8 +22,12 @@ protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
 		{
 			if (MeasureSpec.GetMode(widthMeasureSpec) == MeasureSpecMode.AtMost && Layout is not null)
 			{
-				int maxWidth = (int)Math.Ceiling(GetMaxLineWidth(Layout)) + CompoundPaddingLeft + CompoundPaddingRight;
-				widthMeasureSpec = MeasureSpec.MakeMeasureSpec(maxWidth, MeasureSpecMode.AtMost);
+				// Ensure the Layout is valid and measured before reading LineCount or GetLineWidth(i) to avoid unnecessary calculations.
+				if (Layout.Width > 0)
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/MauiTextView.cs:26]: Can check `Layout.LineCount`? This confirms the Layout actually has content to measure. Is a slightly more robust approach.

File: src/Controls/tests/TestCases.Android.Tests/snapshots/android/LabelShouldSizeProperly.png
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Android.Tests/snapshots/android/LabelShouldSizeProperly.png:1]: This test could potentially fail. Must use the `UITestEntry` from the test controls and the `IsCursorVisible` property to false.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Android/MauiTextView.cs (hunk 1 above)
Comment (Ahamed-Ali) [reply src/Core/src/Platform/Android/MauiTextView.cs:26]: `Layout.LineCount` can return a value even when the layout has not been properly measured or is not in a valid state. In such cases, it may incorrectly treat each character as a separate line. Therefore, checking whether the layout is valid—such as by verifying that `layout.Width > 0`—is a reliable approach before calculating the width.  @jsuarezruiz

File: src/Controls/tests/TestCases.Android.Tests/snapshots/android/LabelShouldSizeProperly.png
Comment (Ahamed-Ali) [reply src/Controls/tests/TestCases.Android.Tests/snapshots/android/LabelShouldSizeProperly.png:1]: I modified the test sample to use `UITestEntry` and set `IsCursorVisible` to false to avoid cursor-related issues in the future. @jsuarezruiz

File: src/Core/src/Platform/Android/MauiTextView.cs [hunk 2]
```diff
@@ -22,8 +22,12 @@ protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
...
+				{
+					int maxWidth = (int)Math.Ceiling(GetMaxLineWidth(Layout)) + CompoundPaddingLeft + CompoundPaddingRight;
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/MauiTextView.cs:28]: Just split the maxWidth variable in more small steps for clarity and
ensure the desired width doesn't exceed the available width from the original spec (use Math.Min).
```
// Calculate the total width needed based on text content plus padding
int contentWidth = (int)Math.Ceiling(GetMaxLineWidth(Layout));
int totalPadding = CompoundPaddingLeft + CompoundPaddingRight;
int requiredWidth = contentWidth + totalPadding;

// Constrain to maximum available width from original spec
int availableWidth = MeasureSpec.GetSize(widthMeasureSpec);
int desiredWidth = Math.Min(requiredWidth, availableWidth);
```

`widthMeasureSpec = MeasureSpec.MakeMeasureSpec(desiredWidth, MeasureSpecMode.AtMost);`

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Android/MauiTextView.cs (hunk 2 above)
Comment (Ahamed-Ali) [reply src/Core/src/Platform/Android/MauiTextView.cs]: I have made the changes. Please let me know if you have any other concerns. @jsuarezruiz

**Review by jsuarezruiz — APPROVED** [review]
