### PR TITLE
[C] use ResourcesChanged to propagate Theme

### LINKED ISSUE #18505: [Android] CollectionVIew scrolling performance on MAUI lags compared to XF
### Description

Given the following layout

```XAML
<ContentPage>
     <CollectionView x:Name="cvGrid" Background="Yellow" HorizontalOptions="Fill"
                             BackgroundColor="Black">
		<CollectionView.ItemTemplate>
			<DataTemplate>
				<Grid BackgroundColor="Purple" ColumnDefinitions="25,25,25,25,25,25,25,25,25,25,25">
					<Label Grid.Column="0" TextColor="White" Text="{Binding Symbol}"></Label>
					<Label Grid.Column="1" TextColor="White" Text="{Binding Symbol}"></Label>
					<Label Grid.Column="2" TextColor="White" Text="{Binding Symbol}"></Label>
					<Label Grid.Column="3" TextColor="White" Text="{Binding Symbol}"></Label>
					<Label Grid.Column="4" TextColor="White" Text="{Binding Symbol}"></Label>
					<Label Grid.Column="5" TextColor="White" Text="{Binding Symbol}"></Label>
					<Label Grid.Column="6" TextColor="White" Text="{Binding Symbol}"></Label>
					<Label Grid.Column="7" TextColor="White" Text="{Binding Symbol}"></Label>
					<Label Grid.Column="8" TextColor="White" Text="{Binding Symbol}"></Label>
					<Label Grid.Column="9" TextColor="White" Text="{Binding Symbol}"></Label>
					<Label Grid.Column="10" TextColor="White" Text="{Binding Symbol}"></Label>
					<Label Grid.Column="11" TextColor="White" Text="{Binding Symbol}"></Label>
				</Grid>
			</DataTemplate>
		</CollectionView.ItemTemplate>
	</CollectionView>
</ContentPage>
```

the performance on XF is much better than MAUI

### Steps to Reproduce

Run the following projects on Android and you'll notice that the scrolling on XF is super smooth compared to MAUI. If you perform really fast scrolling, XF remains smooth whereas MAUI starts to glitch and slow down.

MAUI:
[MauiCollectionView.zip](https://github.com/dotnet/maui/files/13251041/MauiCollectionView.zip)

XF:
[XFCOllectionView.zip](https://github.com/dotnet/maui/files/13251061/XFCOllectionView.zip)

I didn't test this on WinUI/iOS yet but it would be good to validate there as well

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### Related Issues
https://github.com/dotnet/maui/issues/20433
https://github.com/dotnet/maui/issues/19933
https://github.com/dotnet/maui/issues/20797

### LINKED ISSUE #21019: choppy scrolling with CollectionView
### Description

Scrolling of CollectionView is choppy. The scrolling suddenly stops as shown in the video. 
(the light mode video is from honor 9 lite and the dark mode video is from pixel 7a)
(does not affect windows)

https://github.com/dotnet/maui/assets/84516210/91a33b7e-ebc1-4d97-9f4b-ea335ff1b701

https://github.com/dotnet/maui/assets/84516210/6ecf961b-caad-4d9e-9abd-cb891ca14c63

### Steps to Reproduce

build the project and scroll

### Link to public reproduction project repository

https://github.com/AAA1exa8/slowScrolling

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

tested on Android 14 and 9

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change

instead of subscribing to ThemeChanged event, use the ResourcesChanged mechanism of DynamicResource to propagate the change

### Issues Fixed

- related to #8713
- alternative to #19931
- fixes #18505
- fixes #21019

### CODE REVIEW

File: src/Controls/src/Core/Application/Application.cs [hunk 1]
```diff
@@ -101,6 +101,15 @@ public IAppLinks AppLinks
 
 				_singleWindowMainPage = value;
 
+				if (value is not null)
```
Comment (StephaneDelcroix) [inline src/Controls/src/Core/Application/Application.cs:104]: this fixes another bug. resources changed at application level weren't propagated to MainPage

File: src/Controls/src/Core/Shell/Shell.cs [hunk 2]
```diff
@@ -827,10 +827,12 @@ private protected override void OnHandlerChangingCore(HandlerChangingEventArgs a
 				return;
 
 			if (args.NewHandler == null)
+#pragma warning disable CS0618 // Type or member is obsolete
```
Comment (StephaneDelcroix) [inline src/Controls/src/Core/Shell/Shell.cs:830]: well, it's not anymore in this version of the PR, but maybe it should

File: src/Controls/tests/Core.UnitTests/AppThemeTests.cs [hunk 3]
```diff
@@ -34,6 +34,7 @@ public void ThemeChangeUsingSetAppThemeColor()
 			{
 				Text = "Green on Light, Red on Dark"
 			};
+			app.LoadPage(new ContentPage {Content = label});
```
Comment (StephaneDelcroix) [inline src/Controls/tests/Core.UnitTests/AppThemeTests.cs:37]: apotheme propagation REQUIRES that the control is parented, which is fine, as otherwise it wouldn't be on screen

File: Microsoft.Maui-dev.sln [hunk 4]
```diff
@@ -241,7 +241,7 @@ Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "UITest.Appium", "src\TestUt
 EndProject
 Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "UITest.NUnit", "src\TestUtils\src\UITest.NUnit\UITest.NUnit.csproj", "{A307B624-48D4-494E-A70D-5B3CDF6620CF}"
 EndProject
-Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Controls.SourceGen.UnitTests", "src\Controls\tests\SourceGen.UnitTests\Conrtrols.SourceGen.UnitTests\Controls.SourceGen.UnitTests.csproj", "{06747B55-91DB-47F5-B7A2-56526C28A0D3}"
```
Comment (jsuarezruiz) [inline Microsoft.Maui-dev.sln:244]: 😮

File: src/Controls/src/Core/AppThemeBinding.cs [hunk 5]
```diff
@@ -8,10 +8,38 @@ namespace Microsoft.Maui.Controls
...
+			public void Unsubscribe()
+			{
+				((IElementDefinition)_parent).RemoveResourcesChangedListener(OnParentResourcesChanged);
+			}
+		}
+
 		WeakReference<BindableObject> _weakTarget;
 		BindableProperty _targetProperty;
-		bool _attached;
+		// bool _attached;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/AppThemeBinding.cs:40]: It is not used anywhere, I think we can eliminate this variable.

File: src/Controls/src/Core/AppThemeBinding.cs [hunk 6]
```diff
@@ -8,10 +8,38 @@ namespace Microsoft.Maui.Controls
...
+				((IElementDefinition)parent).AddResourcesChangedListener(OnParentResourcesChanged);
+			}
+
+			public static BindableProperty AppThemeProperty = BindableProperty.Create("AppTheme", typeof(AppTheme), typeof(AppThemeBinding), AppTheme.Unspecified,
+				propertyChanged: (bindable, oldValue, newValue) => ((AppThemeProxy)bindable).OnAppThemeChanged());
+			readonly Element _parent;
+
+			public void OnAppThemeChanged()
+			{
+				Binding.Apply(false);
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/AppThemeBinding.cs:27]: I'm curious about the performance impact, especially on CollectionView scrolling. Could we perhaps have an UITest with this example https://github.com/dotnet/maui/issues/18505 where we can display the minimum fps in a Label by scrolling and verifying that the value is greater than n (where n is value higher than before)?

File: src/Controls/src/Core/Application/Application.cs [hunk 7]
```diff
@@ -101,6 +101,15 @@ public IAppLinks AppLinks
...
+					OnParentResourcesChanged(this.GetMergedResources());
+					OnParentResourcesChanged([new KeyValuePair<string, object>("__ApplicationTheme__", _lastAppTheme)]);
+					((IElementDefinition)this).AddResourcesChangedListener(value.OnParentResourcesChanged);
+				} else if (MainPage is not null)
+				{
+					((IElementDefinition)this).RemoveResourcesChangedListener(MainPage.OnParentResourcesChanged);
+				}
 				if (Windows.Count == 1)
 				{
 					Windows[0].Page = value;
```
Comment (mattleibow) [inline src/Controls/src/Core/Application/Application.cs:115]: Is this not triggering the parenting? Maybe if there are no windows - so I wonder if this new logic should be in an else?

File: src/Controls/src/Core/Application/Application.cs (hunk 1 above)
Comment (mattleibow) [reply src/Controls/src/Core/Application/Application.cs:104]: I think if you are just using MainPage, then you get parented to a window during the creating of the UI - so once the app is ready, it calls CreateWindow and assigns the MainPage to the window.

The `_singleWindowMainPage` is just a placeholder while the app is still being constructed. Changing MainPage later literally just replaces the content of the first window:

```cs
Windows[0].Page = value;
```

What you have observed might just be because MainPage really is a delayed construction and assigned. Now this is to say it may be fine what you are doing here, but will it result in a double listener registration once the window is created and the MainPage parented to the window?

File: src/Controls/src/Core/AppThemeBinding.cs [hunk 8]
```diff
@@ -8,10 +8,38 @@ namespace Microsoft.Maui.Controls
 {
 	class AppThemeBinding : BindingBase
 	{
+		class AppThemeProxy : Element
+		{
+			public AppThemeProxy(Element parent, AppThemeBinding binding)
```
Comment (mattleibow) [inline src/Controls/src/Core/AppThemeBinding.cs:13]: I see the `AppThemeBinding` uses a weak reference for the target: `WeakReference<BindableObject> _weakTarget;` Is this now creating a string reference that might cause issues? Maybe the AppThemeBinding does not need to be weak?

File: src/Controls/src/Core/AppThemeBinding.cs [hunk 9]
```diff
@@ -8,10 +8,38 @@ namespace Microsoft.Maui.Controls
...
+			{
+				_parent = parent;
+				Binding = binding;
+				this.SetDynamicResource(AppThemeProperty, "__ApplicationTheme__");
+				((IElementDefinition)parent).AddResourcesChangedListener(OnParentResourcesChanged);
+			}
+
+			public static BindableProperty AppThemeProperty = BindableProperty.Create("AppTheme", typeof(AppTheme), typeof(AppThemeBinding), AppTheme.Unspecified,
```
Comment (mattleibow) [inline src/Controls/src/Core/AppThemeBinding.cs:21]: Will it be more expensive to have a separate proxy Element object with a single extra property vs just adding this to maybe the base Element?

**Review by mattleibow — COMMENTED** [review]
This is looking better than mine with all my extra things, and this looks cleaner to. I tried to cover all the cases of all the things, but just making it work when the theme changes AND the element is parented is better. I tried to make it always work even when there is a floating element.

I also just dumped a bunch of thoughts and questions on this. More trying to see what you were thinking and if there is any gotchas.

**Review by jonathanpeppers — COMMENTED** [review]
This seems to significantly improve `{AppThemeBinding}`. I tested this app on a Pixel 5:

* https://github.com/dotnet/maui/files/13251041/MauiCollectionView.zip

[AppThemeBinding.zip](https://github.com/dotnet/maui/files/14618388/AppThemeBinding.zip)

Before I was seeing:

image

With calling method:

image

(Used `git revert -n 340e53e6`)

Then tried the change in this PR:

image

image

Just compare the %, as the traces have different durations.

Scrolling the sample app, it "feels" better too.

File: src/Controls/src/Core/AppThemeBinding.cs (hunk 8 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Core/AppThemeBinding.cs:13]: the proxy might prevent the AppThemeBinding to GC, but the AppThemeBinding doesn't hold a strong ref to the BO.
in this case, I trust the GC to do the job

File: src/Controls/src/Core/AppThemeBinding.cs [hunk 10]
```diff
@@ -8,10 +8,38 @@ namespace Microsoft.Maui.Controls
 {
 	class AppThemeBinding : BindingBase
 	{
+		class AppThemeProxy : Element
+		{
+			public AppThemeProxy(Element parent, AppThemeBinding binding)
+			{
+				_parent = parent;
+				Binding = binding;
+				this.SetDynamicResource(AppThemeProperty, "__ApplicationTheme__");
```
[the remark this answers is not in the document]
Comment (StephaneDelcroix) [reply src/Controls/src/Core/AppThemeBinding.cs:17]: `__MAUI__MatthewIsAwesome__ApplicationTheme__' ?

File: src/Controls/src/Core/Application/Application.cs (hunk 1 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Core/Application/Application.cs:104]: maybe, but that doesn't work in unit tests

**Review by jonathanpeppers — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]

File: src/Controls/src/Core/AppThemeBinding.cs (hunk 8 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Core/AppThemeBinding.cs:14]: looks like I was wrong
