### PR TITLE
Fix iOS Label being truncated when using Padding

### LINKED ISSUE #28180: Labels with Padding are truncated on IOS
### Description

When a label has a padding assigned, it does not display the complete text on IOS. Without padding, it displays the text properly to its full extend.

### Steps to Reproduce

1. Create a new .NET Maui solution.
2. Change the default page to contain a label with padding and a text that is long enough to need to be wrapped into more than a single line.
3. Remove / add padding to see the issue.

### Link to public reproduction project repository

https://github.com/ollex/maui-label-issue

### Version with bug

9.0.14 SR1.4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

_No response_

### Affected platforms

iOS

### Affected platform versions

IOS 15 and up

### Did you find any workaround?

A workaround is to wrap the label into for example a ContentView with Padding and leave the label's padding at zero.

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by albyrock87**
### Description of Change

Fixes iOS Label being truncated when using padding under some conditions.

### Issues Fixed

Fixes #28180

### CODE REVIEW

**Comment by mattleibow** [comment]
@albyrock87 I see this PR is for a closed issue. Is this a new issue that was introduced or a refinement of the fix? 

Is there a better issue to reference?

**Comment by mattleibow** [comment]
@Dhivya-SF4094 FYI

File: src/Core/src/Platform/iOS/MauiLabel.cs [hunk 1]
```diff
@@ -49,7 +49,7 @@ public override void DrawText(RectangleF rect)
 		RectangleF AlignVertical(RectangleF rect)
 		{
 			var frameSize = Frame.Size;
-			var height = Lines == 1 ? Font.LineHeight : SizeThatFits(frameSize).Height;
+			var height = Lines == 1 ? Font.LineHeight : SizeThatFitsWithinInsets(frameSize).Height;
```
[the remark this answers is not in the document]
Comment (mattleibow) [reply src/Core/src/Platform/iOS/MauiLabel.cs:52]: Maybe we should rename the variable so that this is line hight then?

Comment (mattleibow) [inline src/Core/src/Platform/iOS/MauiLabel.cs:52]: If i understand this PR, this change is just so that this line gets the size without the min clamping?

File: src/Controls/tests/TestCases.HostApp/Issues/Issue28180.xaml.cs [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+{
+	public Issue28180()
+	{
+		InitializeComponent();
+	}
+
+	private void OnToggleClicked(object sender, EventArgs e)
+	{
+		LongTextLabel.Padding = LongTextLabel.Padding == 50 ? 0 : 50;
+		SemanticScreenReader.Announce(ToggleBtn.Text);
```
Comment (mattleibow) [inline src/Controls/tests/TestCases.HostApp/Issues/Issue28180.xaml.cs:14]:
```suggestion
```

**Review by mattleibow — CHANGES_REQUESTED** [review]
Just marking red so I can make sure that this is correct after the PR for the same issue.

**Review by mattleibow — APPROVED** [review]

**Comment by rmarinho** [comment]
Seems this was fixed by https://github.com/dotnet/maui/pull/28081

**Review by rmarinho — APPROVED** [review]
