### PR TITLE
[Android] Fixed TabbedPage bar background visual bug when using gradient stops with transparent colors.

### LINKED ISSUE #12324: TabbedPage Barbackground visual bug when using Linear or Radial GradientBrush
### Description

Whenever you add GradientStop with a Color that has transparency there is a visual bug on the TabBar. Looks like there is a frame behind it with a shadow. Only tested on Android since I dont have access to a iOS Device.

Noted that I place the TabBar on the bottom on android

### Steps to Reproduce

1. Have a Page that inherits from TabbedPage
2. Use this setup as example 
<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage 
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:KortingShoppenApp.Views"
    xmlns:android="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific;assembly=Microsoft.Maui.Controls"
    android:TabbedPage.ToolbarPlacement="Bottom"
    x:Class="YourApp.Pages.MainTabbedPage"
    Title="MainTabbedPage">

    <TabbedPage.BarBackground>
        <RadialGradientBrush >
            <GradientStop Color="#1AFFFF00"
                          Offset="0" />
            <GradientStop Color="Green"
                          Offset="1.0" />
        </RadialGradientBrush>
    </TabbedPage.BarBackground>

    <local:SettingsView Title="Test" IconImageSource="dotnet_bot"/>
</TabbedPage>

image

### Link to public reproduction project repository

None

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SubhikshaSf4851**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause:
The visual separation line appears because of Android’s default elevation shadow on `BottomNavigationView`, which becomes visible when rendered together with transparent gradient backgrounds.
### Description of Change : 
Set the `Elevation` property to `0` in the `BottomNavigationView` on Android to prevent visual separation lines, especially with gradients.

### Issues Fixed

Fixes #12324 

### Tested the behavior in the following platforms

- [x] Windows
- [x] Android
- [x] iOS
- [x] Mac

### Screenshot

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/1ff578e6-315b-4620-a8ba-42ff9e0fb982"> | <video src="https://github.com/user-attachments/assets/2f198bcd-2f0d-493e-8c4e-f0d799b0f231"> |

### CODE REVIEW

File: src/Controls/src/Core/Platform/Android/TabbedPageManager.cs [hunk 1]
```diff
@@ -144,7 +144,9 @@ public virtual void SetElement(TabbedPage tabbedPage)
 					LayoutParameters = new CoordinatorLayout.LayoutParams(AppBarLayout.LayoutParams.MatchParent, AppBarLayout.LayoutParams.WrapContent)
 					{
 						Gravity = (int)GravityFlags.Bottom
-					}
+					},
+					// Set elevation to 0 to prevent visual separation lines, especially with gradients
+					Elevation = 0
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/TabbedPageManager.cs]: Can only set it if the Background is a GradientBrush?

Comment (SubhikshaSf4851) [reply src/Controls/src/Core/Platform/Android/TabbedPageManager.cs]: I have updated the changes

File: src/Controls/src/Core/Platform/Android/TabbedPageManager.cs [hunk 2]
```diff
@@ -594,6 +594,10 @@ public virtual void UpdateBarBackground()
 		{
 			newGradientBrush.Parent = Element;
 			newGradientBrush.InvalidateGradientBrushRequested += OnBarBackgroundChanged;
+			if (_bottomNavigationView is not null && _bottomNavigationView.Elevation > 0)
+			{
+				_bottomNavigationView.Elevation = 0;
+			}
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/TabbedPageManager.cs:600]: Should we store and restore the original elevation value?

Comment (SubhikshaSf4851) [reply src/Controls/src/Core/Platform/Android/TabbedPageManager.cs:600]: Yes, it is needed. I have updated the requested changes

**Comment by SubhikshaSf4851** [comment]
@rmarinho The elevation is set to 0 specifically for GradientBrush backgrounds because the shadow artifact is only visible through transparent areas. For SolidColorBrush, the background is fully opaque and completely hides the shadow regardless of elevation value — so there's no visual difference either way. The restore in the else if is already there as a defensive cleanup for solid colors.

**Review by kubaflo — APPROVED** [review]

**Review by kubaflo — CHANGES_REQUESTED** [review]
Could you please check the ai's suggestions?

**Comment by kubaflo** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong> — <a href="https://github.com/dotnet/maui/commit/1092647a23c2870e0826e71c9233935371f603a1"><code>1092647</code></a> · <strong>Added 26version snapshot</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

**Issue:** #12324 - TabbedPage BarBackground visual bug when using Linear or Radial GradientBrush
**PR:** #32392 - [Android] Fixed TabbedPage bar background visual bug when using gradient stops with transparent colors
**Platforms Affected:** Android
**Files Changed:** 1 implementation, 2 test files, 4 snapshot images

### Key Findings
- **Root cause:** Android's `BottomNavigationView` has a default elevation shadow that becomes visible through transparent areas of gradient backgrounds, creating a visual "separation line" artifact.
- **Fix approach:** In `UpdateBarBackground()`, set `_bottomNavigationView.Elevation = 0` when switching to a GradientBrush background; restore original elevation using `Resource.Dimension.design_bottom_navigation_elevation` when switching back to SolidColorBrush.
- **Edge case gap:** The elevation restore only triggers when switching to `SolidColorBrush`. If BarBackground is set to `null` or another non-gradient brush type, elevation is NOT restored — this is a potential regression.
- **Test is Android-only:** Wrapped in `#if TEST_FAILS_ON_CATALYST` but also only relevant to Android because it uses `AndroidSpecific.TabbedPage.SetToolbarPlacement(Bottom)`.
- **Prior reviewer feedback (jsuarezruiz):** Asked about restoring original elevation — PR author added restore logic reading from `Resource.Dimension.design_bottom_navigation_elevation`.
- **Labels:** `s/agent-reviewed`, `s/agent-changes-requested`, `s/agent-gate-passed`, `s/agent-fix-win` (prior agent run exists but no comment body with phase table found).
- **No prior agent comment** with structured phase table found — running fresh review.

### Implementation Details
```csharp
if (_currentBarBackground is GradientBrush newGradientBrush)
{
    newGradientBrush.Parent = Element;
    newGradientBrush.InvalidateGradientBrushRequested += OnBarBackgroundChanged;
    if (_bottomNavigationView is not null && _bottomNavigationView.Elevation > 0)
    {
        _bottomNavigationView.Elevation = 0;
    }
}
else if (_currentBarBackground is SolidColorBrush && _bottomNavigationView is not null && _bottomNavigationView.Elevation == 0)
{
    _bottomNavigationView.Elevation = _bottomNavigationView.Context.Resources.GetDimension(Resource.Dimension.design_bottom_navigation_elevation);
}
```

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #32392 | Set elevation=0 for GradientBrush, restore for SolidColorBrush | ⏳ PENDING (Gate) | `TabbedPageManager.cs` | Original PR — elevation restore only covers SolidColorBrush case |

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

### Gate Result: ✅ PASSED

**Platform:** Android
**Mode:** Full Verification

- Tests FAIL without fix: ✅
- Tests PASS with fix: ✅

Full verification confirmed by verify-tests-fail-without-fix skill. The screenshot test `Issue12324TabbedPageVisualTest` properly detects the elevation shadow artifact when absent and passes when Elevation=0 is applied to BottomNavigationView.

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #32392 | Set `Elevation=0` for GradientBrush; restore via `Resource.Dimension` for SolidColorBrush | ✅ PASSED (Gate) | `TabbedPageManager.cs` | Only handles GradientBrush; null/other-brush restore gap |
| 1 | try-fix (claude-sonnet-4.6) | Custom `ViewOutlineProvider` returning `outline.SetEmpty()` in `RefreshBarBackground()`; broader: handles ANY transparent brush | ✅ PASS | `TabbedPageManager.cs` | Preserves elevation; no API version guard needed; +54 lines |
| 2 | try-fix (claude-opus-4.6) | Set `OutlineSpotShadowColor`/`OutlineAmbientShadowColor` to transparent; saves/restores originals | ✅ PASS | `TabbedPageManager.cs` | API 28+ only; GradientBrush scope only; +31 lines |

### Cross-Pollination
| Model | Round | New Ideas? | Details |
|-------|-------|------------|---------|
| claude-sonnet-4.6 | 2 | Yes — but marginal | Suggested `BackgroundTintList=null` to bypass Material tinting pipeline; potentially interferes with existing tab color state list handling in TabbedPageManager; not pursued |
| claude-opus-4.6 | 2 | NO NEW IDEAS | Identified elevation/outline/shadow-color as the three complete Android shadow control axes; other ideas have unacceptable side effects |

**Exhausted:** Yes — all three primary Android shadow control mechanisms explored; cross-pollination found no viable new approaches.

**Selected Fix:** Candidate #1 (ViewOutlineProvider) — **Reasoning:** Broader scope (handles any transparent brush, not just GradientBrush), preserves Material Design elevation value, no API version guard required, clean restore semantics. PR fix has edge cases (null BarBackground doesn't restore elevation; transparent SolidColorBrush not covered). Candidate #2 requires API 28+, leaving Android O devices unprotected.

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

## ⚠️ Final Recommendation: REQUEST CHANGES

### Phase Status
| Phase | Status | Notes |
|---|---|---|
| Pre-Flight | ✅ COMPLETE | Issue #12324, Android-only, TabbedPage gradient background shadow artifact |
| Gate | ✅ PASSED | Android — tests FAIL without fix, PASS with fix |
| Try-Fix | ✅ COMPLETE | 2 attempts, 2 passing; alternative fix found |
| Report | ✅ COMPLETE | |

### Summary

PR #32392 fixes a real, verified bug: Android's `BottomNavigationView` elevation shadow bleeds through transparent gradient backgrounds on TabbedPage. The Gate confirmed the PR's tests reliably catch the bug. However, Try-Fix exploration found a **more robust alternative approach** that handles a broader set of cases without modifying the Material Design elevation value.

### Root Cause

Android's `BottomNavigationView` has a default Material Design elevation that casts a shadow. When a `GradientBrush` with transparent color stops is applied as the `BarBackground`, the transparent areas allow the shadow to show through, creating a visible "separation line" artifact.

### Fix Quality — PR's Approach

**Strengths:**
- Simple, minimal change (8 lines)
- Directly targets the root cause (elevation)
- Includes restore logic for SolidColorBrush transitions

**Weaknesses:**
1. **Scope too narrow:** Only zeroes elevation for `GradientBrush`. A `SolidColorBrush` with `Alpha < 1.0` would still show the shadow artifact.
2. **Restore gap:** The restore `else if` only fires when switching to `SolidColorBrush`. Setting `BarBackground = null` or to another non-gradient brush type leaves elevation at 0 permanently.
3. **Elevation side effects:** Setting `Elevation = 0` removes the Material Design shadow entirely, which may affect the component's intended visual design in ways beyond just fixing the transparency artifact.

### Alternative Fix (Candidate #1 — Recommended)

The `ViewOutlineProvider` approach (Attempt 1) is superior:

```csharp
// In RefreshBarBackground():
protected virtual void RefreshBarBackground()
{
    if (IsBottomTabPlacement)
    {
        _bottomNavigationView.UpdateBackground(_currentBarBackground);
        UpdateBottomNavShadowForBackground(_currentBarBackground);
    }
    else
        _tabLayout.UpdateBackground(_currentBarBackground);
}

void UpdateBottomNavShadowForBackground(Brush brush)
{
    if (_bottomNavigationView is null)
        return;

    if (HasTransparentBackground(brush))
    {
        if (_originalBottomNavOutlineProvider is null)
            _originalBottomNavOutlineProvider = _bottomNavigationView.OutlineProvider;
        _bottomNavigationView.OutlineProvider = NoShadowOutlineProvider.Instance;
    }
    else if (_originalBottomNavOutlineProvider is not null)
    {
        _bottomNavigationView.OutlineProvider = _originalBottomNavOutlineProvider;
        _originalBottomNavOutlineProvider = null;
    }
}

static bool HasTransparentBackground(Brush brush)
{
    if (brush is SolidColorBrush solidBrush)
        return solidBrush.Color is { Alpha: < 1.0f };
    if (brush is GradientBrush gradientBrush)
    {
        foreach (var stop in gradientBrush.GradientStops)
            if (stop.Color is { Alpha: < 1.0f })
                return true;
    }
    return false;
}

sealed class NoShadowOutlineProvider : ViewOutlineProvider
{
    internal static readonly NoShadowOutlineProvider Instance = new();
    public override void GetOutline(AView view, Outline outline) => outline.SetEmpty();
}
```

**Why this is better:**
1. **Broader scope:** Handles ANY transparent brush (SolidColorBrush + GradientBrush), not just GradientBrush
2. **Preserves elevation:** Material Design elevation value unchanged — only shadow rendering is suppressed
3. **Clean restore:** Restores to original `OutlineProvider` whenever the brush becomes opaque, regardless of brush type (no null-brush gap)
4. **No API version guard needed:** `ViewOutlineProvider` API is available from API 21+
5. **Co-located with background application:** Fix lives in `RefreshBarBackground()` alongside `UpdateBackground()` — more cohesive

### Try-Fix Summary

| # | Approach | Result | Key Insight |
|---|----------|--------|-------------|
| PR | Elevation=0 for GradientBrush only | ✅ Gate passed | Simple but narrow scope; restore gap for null/other brush |
| 1 | ViewOutlineProvider (empty outline) — broader | ✅ PASS | Preserves elevation; any transparent brush; no API guard |
| 2 | Shadow color transparency (API 28+) | ✅ PASS | Elegant but API 28+ only; misses Android O devices |

### Specific Issues to Address

1. **Restore when `BarBackground = null`** — current PR code doesn't restore elevation when the background is set to null or a non-Solid, non-Gradient brush type
2. **Transparent SolidColorBrush** — should also suppress shadow for a solid color with Alpha < 1
3. **Elevation modification side effects** — consider using `ViewOutlineProvider` to avoid modifying the Material elevation value

### Test Notes

- Test is correctly Android-only (`#if TEST_FAILS_ON_CATALYST`)
- Visual screenshot test (`VerifyScreenshot()`) is an appropriate verification method
- Test page correctly uses `AndroidSpecific.TabbedPage.SetToolbarPlacement(Bottom)` to target the affected code path
- Minor: test file missing newline at end of file

</details>

---

</details>



<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

# PR #32392 Finalization Review

**PR:** [#32392 - [Android] Fixed TabbedPage bar background visual bug when using gradient stops with transparent colors](https://github.com/dotnet/maui/pull/32392)  
**Author:** @SubhikshaSf4851  
**State:** Open | `s/agent-reviewed`, `s/agent-changes-requested`, `s/agent-gate-passed`

---

## Phase 1: Title & Description Review

### 🟡 Title: Needs Minor Update

**Current:** `[Android] Fixed TabbedPage bar background visual bug when using gradient stops with transparent colors.`

**Issues:**
- Trailing period is unconventional for PR titles/commit headlines
- "Fixed" (past tense) is better as "Fix" (imperative, matching git convention)
- Verbose — doesn't surface the key technical change (Elevation = 0)

**Recommended:**
```
[Android] TabbedPage: Fix BottomNavigationView elevation shadow with gradient brush backgrounds
```

---

### ✅ Description: Good Structure — Minor Additions Needed

**Quality Assessment:**

| Dimension | Status | Notes |
|-----------|--------|-------|
| NOTE block | ✅ Present | Required block is at the top |
| Root cause | ✅ Present | Elevation shadow from `BottomNavigationView` visible through transparent gradient colors |
| Description of change | ✅ Present | Sets `Elevation = 0` for gradient brush, restores for solid color brush |
| Issues Fixed | ✅ Present | `Fixes #12324` |
| Platforms Tested | ✅ Present | All four platforms checked |
| Screenshots | ✅ Present | Before/After table (images not loading in preview) |

**What's missing:**
- The description doesn't mention the **elevation restore behavior** (the `else if` branch), which is an important detail for future agents reviewing this code
- No note that the fix is scoped to `IsBottomTabPlacement` implicitly (via `_bottomNavigationView` being null otherwise)

**Recommended additions to description:**

```markdown
### Description of Change

Set the `Elevation` property to `0` on `BottomNavigationView` when a `GradientBrush` is applied as `BarBackground`. When transparent gradient stops are used, Android's default elevation shadow is rendered visibly through the transparent areas, producing an unwanted visual separation line.

When `BarBackground` switches back to a `SolidColorBrush`, the elevation is restored to the system default (`design_bottom_navigation_elevation` resource dimension) since a fully opaque solid color already hides the shadow.

**Note:** This fix only applies to bottom-tab placement on Android (top tab placement uses `TabLayout`, not `BottomNavigationView`, and is unaffected).
```

---

## Phase 2: Code Review

### 🔴 Critical Issues

None.

---

### 🟡 Suggestions

**1. Elevation not restored for `null` or non-`SolidColorBrush` backgrounds**

- **File:** `src/Controls/src/Core/Platform/Android/TabbedPageManager.cs`
- **Location:** Lines 602–605 (the `else if` branch)
- **Problem:** If `BarBackground` changes from a `GradientBrush` to `null`, or to any brush type other than `SolidColorBrush` (e.g., an `ImageBrush`), the elevation remains at `0` indefinitely. The current `else if` only handles `SolidColorBrush`.

```csharp
// Current (incomplete restoration):
else if (_currentBarBackground is SolidColorBrush && _bottomNavigationView is not null && _bottomNavigationView.Elevation == 0)
{
    _bottomNavigationView.Elevation = _bottomNavigationView.Context.Resources.GetDimension(Resource.Dimension.design_bottom_navigation_elevation);
}
```

- **Recommendation:** Restore elevation for any non-gradient background, or check if the previous background was a gradient regardless of what the new one is:

```csharp
// Improved: restore whenever switching away from gradient
else if (_bottomNavigationView is not null && _bottomNavigationView.Elevation == 0)
{
    _bottomNavigationView.Elevation = _bottomNavigationView.Context.Resources.GetDimension(Resource.Dimension.design_bottom_navigation_elevation);
}
```

---

**2. Reviewer's ask to "store and restore" original elevation was not fully addressed**

- **File:** `src/Controls/src/Core/Platform/Android/TabbedPageManager.cs`
- **Context:** The reviewer (@jsuarezruiz) asked: *"Should we store and restore the original elevation value?"* and the author confirmed it was updated. However, the implementation reads from `Resource.Dimension.design_bottom_navigation_elevation` (the system default) rather than storing and restoring the actual original elevation.
- **Problem:** If `BottomNavigationView` had a non-default elevation configured elsewhere (e.g., via a custom style or theme), this would not restore the correct value.
- **Recommendation:** Store the initial elevation before any modification:

```csharp
// In class fields:
float _originalBottomNavElevation = -1f;

// In UpdateBarBackground, before first modification:
if (_originalBottomNavElevation < 0 && _bottomNavigationView is not null)
    _originalBottomNavElevation = _bottomNavigationView.Elevation;

// When restoring:
_bottomNavigationView.Elevation = _originalBottomNavElevation >= 0
    ? _originalBottomNavElevation
    : _bottomNavigationView.Context.Resources.GetDimension(Resource.Dimension.design_bottom_navigation_elevation);
```

---

**3. Missing newline at end of file**

- **Files:**
  - `src/Controls/tests/TestCases.HostApp/Issues/Issue12324.cs`
  - `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue12324.cs`
- **Problem:** Both files are missing a newline at end of file (`\ No newline at end of file` in the diff). This is a style issue that many linting tools flag.
- **Recommendation:** Add a trailing newline to both files.

---

**4. Test platform scope vs. fix scope mismatch**

- **File:** `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue12324.cs`
- **Problem:** The fix is Android-specific (`BottomNavigationView` with gradient), but the test runs on iOS and Windows (only excluding MacCatalyst via `#if TEST_FAILS_ON_CATALYST`). Snapshots are included for Windows, iOS, and iOS-26. On iOS and Windows, `BottomNavigationView` doesn't exist so the fix doesn't apply.
- **Impact:** Low — screenshot tests on non-Android platforms will pass trivially (there's no bug to fix on those platforms), but adding them inflates snapshot surface area.
- **Consideration:** If the intent is to verify the TabbedPage renders correctly on all platforms (not just Android), this is acceptable. If this is Android-specific, add a `[FailsOnPlatform]` attribute or a platform guard in the test.

---

### ✅ Looks Good

- **Root cause identified correctly** — Android's `BottomNavigationView` has a default elevation that casts a Material Design shadow. Transparent gradient colors reveal this shadow as a visual separator line. Setting elevation to `0` removes it.

- **Null guard on `_bottomNavigationView`** — The code correctly checks `_bottomNavigationView is not null` before accessing the property.

- **Guard against redundant assignment** — The `if (_bottomNavigationView.Elevation > 0)` check avoids a redundant assignment when elevation is already 0.

- **UI test structure is correct** — `Issue12324` in `TestCases.Shared.Tests` correctly inherits from `_IssuesUITest`, uses `[Category(UITestCategories.TabbedPage)]`, and uses `VerifyScreenshot()` for visual validation.

- **HostApp page correctly reproduces the bug** — `Issue12324.cs` in HostApp uses `RadialGradientBrush` with a transparent color (`#1AFFFF00`) and sets bottom toolbar placement — exactly the scenario from the issue report.

- **NOTE block is present** — Required artifact-testing block is correctly included at the top of the description.

---

## Summary

| Area | Status | Action Needed |
|------|--------|---------------|
| PR Title | 🟡 Minor issue | Change to imperative voice, remove trailing period |
| Description | ✅ Good | Add detail about elevation restore and placement scope |
| Code: Elevation restore scope | 🟡 Suggestion | Restore elevation for all non-gradient brushes, not just `SolidColorBrush` |
| Code: Store original elevation | 🟡 Suggestion | Store original before modifying to truly restore — not just read resource default |
| Code: Missing newline at EOF | 🟡 Minor | Add trailing newlines to both new `.cs` files |
| Test platform scope | 🟡 Minor | Consider restricting test to Android or document why multi-platform |
| Critical bugs | ✅ None | No blocking issues |

**Overall Verdict:** PR is close to merge-ready. The core fix is correct and well-scoped. The two `🟡` code suggestions (elevation restore for null/other brush types and storing original elevation) are worth addressing before merge as they represent incomplete edge case handling that the reviewer explicitly flagged.

</details>

**Comment by SubhikshaSf4851** [comment]
@kubaflo 
> Concern 1 :  Elevation not restored for null or non-SolidColorBrush backgrounds

I had already verified it and added a reply here: https://github.com/dotnet/maui/pull/32392#issuecomment-3950633559

> Concern 2 : Reviewer's ask to "store and restore" original elevation was not fully addressed

The suggested approach used an extra variable. I checked that as well and avoided introducing it unnecessarily by using design_bottom_navigation_elevation directly.

> Concern 3 : Test platform scope vs. fix scope mismatch

Also, FailsOnPlatform was recommended, but we did not use that attribute in the source.

Other than this, I have updated the valid suggestion.

**Review by kubaflo — APPROVED** [review]
