### PR TITLE
Invalidate shapes changing any property inside the brushes (Fill, Stroke)

### LINKED ISSUE #13891: Changing Shape.Stroke does not update app rendering
### Description

Changing Shape.Stroke does not update app rendering

### Steps to Reproduce

1. Create new MAUI app.
2. Set Windows as target platform.
3. Open MainPage.xaml and replace content of `<ContentPage>` element with 
```
  <VerticalStackLayout>
    <Button x:Name="MyButton" Text="Change color" Margin="4" HorizontalOptions="Start"/>
    <Line x:Name="MyLine" X1="0" X2="150" StrokeThickness="4" HorizontalOptions="Start"/>
  </VerticalStackLayout>
```
4. Open MainPage.xaml.cs and replace implementation with 
```
public partial class MainPage : ContentPage
{
	SolidColorBrush brush;
	Color[] colors = { Colors.Green, Colors.Red, Colors.Blue };
	int colorIndex = -1;

	public MainPage()
	{
		InitializeComponent();
		brush = new SolidColorBrush();
		UpdateBrushColor();

        // Use same brush for Button and Line
		MyLine.Stroke = brush;
        MyButton.Background = brush;
        MyButton.Clicked += (s, e) => UpdateBrushColor();
    }

	void UpdateBrushColor()
	{
		if (++colorIndex >= colors.Length)
			colorIndex = 0;

		brush.Color = colors[colorIndex];
	}
}
```
5. Build and run
6. Click "Change color" button few times.
**Expected**: both button and line will change colors.
**Actual**: only button changes color.

### Link to public reproduction project repository

n/a

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Win 22H2

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Invalidate shapes changing any property inside the brushes (Fill, Stroke).

fix-13891

image

### Issues Fixed

Fixes #13891

### CODE REVIEW

File: src/Controls/tests/DeviceTests/Elements/Shape/ShapeTests.cs [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+				clicked = true;
+				line.Stroke = expected;
+			};
+
+			await PerformClick(button);
+
+			Assert.True(clicked);
+
+			await ValidateHasColor(line, expected, typeof(ShapeViewHandler));
+		}
```
[the remark this answers is not in the document]
Comment (jsuarezruiz) [reply src/Controls/tests/DeviceTests/Elements/Shape/ShapeTests.cs:73]: Sure thing, added a test to validate both properties, `Fill` and `Stroke`.
image

**Review by jonathanpeppers — APPROVED** [review]

**Comment by jsuarezruiz** [comment]
@jonathanpeppers 
I've added more changes because the proxy we used to detect brush changes in Shapes required to detect changes from other events (changes in brush gradientstops etc.). I have also added a new example to validate this.
image

File: src/Core/tests/UnitTests/Views/ShapeTests.cs [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+
+			bool fired = false;
+			shape.PropertyChanged += (sender, e) =>
+			{
+				if (e.PropertyName == nameof(Shape.Stroke))
+					fired = true;
+			};
+
+			stroke.Color = Colors.Green;
+			Assert.True(fired, "PropertyChanged did not fire!");
```
Comment (jonathanpeppers) [inline src/Core/tests/UnitTests/Views/ShapeTests.cs:57]: I think I found an issue in this pattern, if you change this to:
```suggestion
			await Task.Yield();
			GC.Collect();
			GC.WaitForPendingFinalizers();

			stroke.Color = Colors.Green;
			Assert.True(fired, "PropertyChanged did not fire!");
```
Does it fail? I found saving some delegates in a member variable fixes it, but looking how we can do it in a nicer way.

Comment (jonathanpeppers) [reply src/Core/tests/UnitTests/Views/ShapeTests.cs:57]: Follow what I did here to get the above test to pass: https://github.com/dotnet/maui/pull/13997

Comment (jsuarezruiz) [reply src/Core/tests/UnitTests/Views/ShapeTests.cs]: Right, the test was not passing in that case. 
Applied changes to save the EventHandlers in a member field.

image
Now are passing (at least locally).

**Review by mandel-macaque — APPROVED** [review]
