### PR TITLE
[Windows] Fix issues setting Shell TabBar appearance

### LINKED ISSUE #6929: Shell on Windows: Tabbar redraw problems
### Description

The text of the tabbar is sometimes drawn in the wrong color if you click and move the mouse.
click_and_move

Sometimes this happens already at startup. 
1st_Item_wrong_color_after_startup

Also it happens if you change the style the "..." are sometimes drawn in the wrong color.
3dots not visible because of wrong color

Menu is also not styled correctly in dark mode (also note all tabbar items are gone because they switch sometimes back to black in the popout they are correcly white but the background is also white...):
popout wrong styled

### Steps to Reproduce

1. Get project from https://github.com/rogerbriggen/Maui_sHell/tree/ShellErrors_RC2 or use the attached file [Maui_sHell-ShellErrors_RC2.zip](https://github.com/dotnet/maui/files/8646568/Maui_sHell-ShellErrors_RC2.zip)
2. Compile and run for windows
3. Start up the project -> Sometimes the first tabbar text has a different color
4. Move with the mouse over the items click and move -> wrong color
5. Toggle theme on mainpage
6. Move with the mouse over the items 
7. Reduce with of window until you see (or maybe not see because of wrong color ...) -> ... in dark mode most of the time not visible
8. Click on the ... in dark mode: Background of menu is wrong

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 21H1

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #12386: TabBar / Tab colours not working correctly on Windows
### Description

When trying to set the Shell.TabBarForegroundColor or Shell.TabBarUnselectedColor on a TabBar (or Tab) it does not work. In the example shown, the foreground color should be Green but it is still showing as Black and the unselected tab should be Red, but it is showing as Green.

There is no option for Selected tab.

All default styling has been removed in this example by commenting it out.

image

### Steps to Reproduce

1. Create a File > New .Net MAUI App
2. Comment out all default styling (Resources > Styles > Styles.xaml)
3. Create a new TabBar with 2 Tab elements in AppShell.xaml
4. Give each Tab a Title
5. Copy the default ShellContent into each Tab
6. Set Shell.TabBarForegroundColor and Shell.TabBarUnselectedColor on the TabBar

Expected outcome: Foreground text color of any TabBar tabs will be the set color

Actual outcome: Foreground text color of each Tab always remains black.

Also tested by setting the property on the Tab element but still the same result.

### Link to public reproduction project repository

https://github.com/samuelradford/TabBarColorTest.App

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

The tabs are generated from a WinUI template so if you need to workaround this before NET8 you can just replace the template [here](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Platform/Windows/TabbedPage/TabbedPageStyle.xaml) with your own template.

For example I've added this

```XAML
<maui:MauiWinUIApplication.Resources>
	<DataTemplate x:Key="TabBarNavigationViewMenuItem">
		<NavigationViewItem 
            x:Name="navViewItem"
            Content="Monkey" 
            Foreground="Pink" 
            Background="Orange" 
            IsSelected="{Binding IsSelected, Mode=TwoWay}"
            MenuItemsSource="{Binding MenuItemsSource}"
            Icon="{Binding Icon}"
            />
	</DataTemplate>
</maui:MauiWinUIApplication.Resources>
```

Into the Platform/Windows/App.xaml file. 

At this point you could use all the methods you'd use with WinUI to customize values. Generate the ControlTemplate and then modify the VisualState etc.. as needed

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

Windows portion of the following PR
https://github.com/dotnet/maui/pull/15447

#### Priority of how the colors are applied.

The APIs available to us are fairly limiting in scope. Ideally, we would make this all work through the VSM and just use two APIs (IconColor/TitleColor) but for now we are just making these APIs consistent between the platforms. 

The three properties users have to influence the `TabItem` coloring are: `TabBarUnselectedColor`, `TabBarTitleColor`, and `TabBarForegroundColor`

- If the user only sets `Shell.TabBarTitleColor` that will color the `Title` and `Icon` of the selected item. I realize this is a bit weird for TitleColor to change `Icon` color but this is currently how Android works and it's not really worth breaking this until we just introduce new APIs.
- If `Shell.TabBarTitleColor` is not set then the `TitleColor` will match the `TabBarForegroundColor`
- If `TabBarForegroundColor` is set and `TabBarUnselectedColor` isn't set then `TabBarForegroundColor` will be the color used for the text/icon of the selected TabItem
- If `TabBarUnselectedColor` is the only thing set then that will be used for the text/icon color on the unselected Tab Item. 

#### Examples
- `TabBarTitleColor`: Green
  - Selected Icon is Green, Selected Text is Green, Unselected item matches system colors
-  `TabBarForegroundColor`: Blue
  - Selected Icon is Blue, Selected Text is Blue, Unselected item matches system colors
-  `TabBarForegroundColor`: Blue, `TabBarTitleColor`: Green
  - Selected Icon is Blue, Selected Text is Green, Unselected item matches system colors
-  `Shell.ForegroundColor`: Blue, `TabBarTitleColor`: Green (ForegroundColor propagates to TabBarForegroundColor).
  - Selected Icon is Blue, Selected Text is Green, Unselected item matches system colors
-  `TabBarForegroundColor`: Blue, `TabBarTitleColor`: Green, `TabBarUnselectedColor`: Pink
  - Selected Icon is Blue, Selected Text is Green, Unselected text and Icon is `Pink`

#### Breaking changes
- TabbedPage.UnselectedColor and TabbedPage.SelectedColor used to set the color of the tab background but now they just set the color of the text to stay consistent with android/ios
  - users can call `UpdateTopNavigationViewItemBackgroundUnselectedColor` and `UpdateTopNavigationViewItemBackgroundSelectedColor` if they want to set the background colors on the tabs
  
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/12386
Fixes https://github.com/dotnet/maui/issues/6929

### Video

https://github.com/dotnet/maui/assets/5375137/2d987e8b-9746-41dd-b631-486b3bbea8d0

### CODE REVIEW

File: src/Core/src/Platform/Windows/NavigationViewExtensions.cs [hunk 1]
```diff
@@ -50,15 +50,89 @@ public static void UpdateTopNavigationViewItemTextColor(this MauiNavigationView
...
+					navigationView.TopNavArea.Resources["TopNavigationViewItemForegroundSelected"] = brush;
+					navigationView.TopNavArea.Resources["TopNavigationViewItemForegroundSelectedPointerOver"] = brush;
+					navigationView.TopNavArea.Resources["TopNavigationViewItemForegroundSelectedPressed"] = brush;
+					navigationView.TopNavArea.Resources["TopNavigationViewItemForegroundSelectedDisabled"] = brush;
+				}
+
+				navigationView.TopNavArea.RefreshThemeResources();
+			}
+
+			if (navigationView.MenuItemsSource is IList<NavigationViewItemViewModel> items)
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Windows/NavigationViewExtensions.cs:82]: We can move this to a method and reuse it here and updating the selected color.

Comment (PureWeen) [reply src/Core/src/Platform/Windows/NavigationViewExtensions.cs:82]: I don't quite follow. This whole method is about updating the selected text color of a tab item. I don't think it makes sense to separate this logic out from the logic above it.

File: src/Controls/tests/DeviceTests/Elements/Shell/ShellTabBarTests.Windows.cs [hunk 2]
```diff
@@ -0,0 +1,145 @@
...
+using WFrameworkElement = Microsoft.UI.Xaml.FrameworkElement;
+
+
+namespace Microsoft.Maui.DeviceTests
+{
+	[Category(TestCategory.Shell)]
+	public partial class ShellTests
+	{
+		[Fact(DisplayName = "ForegroundColor sets icon and title color sets title")]
+		public async Task ForegroundColorSetsIconAndTitleColorSetsTitle()
```
[the remark this answers is not in the document]
Comment (PureWeen) [reply src/Controls/tests/DeviceTests/Elements/Shell/ShellTabBarTests.Windows.cs:22]: Added some buttons so you can toggle the colors and a video.

**Review by jsuarezruiz — APPROVED** [review]
