### PR TITLE
[CarouselViewHandler2] Fir fox CurrentItem does not work when ItemSpacing is set

### LINKED ISSUE #32048: [CarouselViewHandler2] CurrentItem does not work when ItemSpacing is set
### Description

This now works when PeekAreaInsets is set (thanks to https://github.com/dotnet/maui/pull/29995) but not when ItemSpacing is set

### Steps to Reproduce

[CurrentItem.zip](https://github.com/user-attachments/files/22975818/CurrentItem.zip)

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.110 SR12

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by SyedAbdulAzeemSF4852**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue Details

- CurrentItem does not update when ItemSpacing is set.

### Root Cause

- When ItemSpacing is set on a CarouselView using CV2 (CarouselViewHandler2), the page calculation logic was only considering the container size but ignoring the additional space consumed by ItemSpacing.

### Description of Change

- Updated the page index calculation in LayoutFactory2.cs to include ItemSpacing when determining the current page in the carousel layout. This ensures that CurrentItem updates correctly when spacing is present.

### Issues Fixed
Fixes #32048 

### Validated the behaviour in the following platforms

- [x] Windows
- [x] Android
- [x] iOS
- [x] Mac

### Output
| Before | After |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/81a4529b-049b-4662-be87-90a83cd94a70"> | <video src="https://github.com/user-attachments/assets/9448e421-a065-44aa-846f-3d0af0696de0"> |

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs [hunk 1]
```diff
@@ -343,7 +343,11 @@ public static UICollectionViewLayout CreateCarouselLayout(
 					return;
 				}
 
-				var page = (offset.X + sectionMargin) / (env.Container.ContentSize.Width - sectionMargin * 2);
+				// Calculate page index accounting for ItemSpacing
+				var itemSpacing = itemsView.ItemsLayout is LinearItemsLayout linearLayout ? linearLayout.ItemSpacing : 0;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs:347]: Can you scroll to the very last item and verify CurrentItem updates correctly?

Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs:347]: Can you verify also GridItemsLayout?

File: src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs [hunk 2]
```diff
@@ -343,7 +343,11 @@ public static UICollectionViewLayout CreateCarouselLayout(
...
+
+				var effectiveItemWidth = env.Container.ContentSize.Width - sectionMargin * 2 + itemSpacing;
+				double page = (offset.X + sectionMargin) / effectiveItemWidth;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs:356]: `double page = (offset.X + sectionMargin) / effectiveItemWidth;`

Could effectiveItemWidth be zero? Potential Divide-by-Zero Exception?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs (hunk 1 above)
Comment (SyedAbdulAzeemSF4852) [reply src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs:347]: @jsuarezruiz , I have verified this by scrolling to the last item, and the CurrentItem is updating correctly. For your reference, I’m attaching the video below.


https://github.com/user-attachments/assets/bae2a34b-b6b5-430b-b336-610c6b28688f

Comment (SyedAbdulAzeemSF4852) [reply src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs:347]: @jsuarezruiz , CarouselView.ItemsLayout is explicitly typed as LinearItemsLayout (not the base ItemsLayout type), so it cannot be a GridItemsLayout.

Looking at the CarouselView class definition :

https://github.com/dotnet/maui/blob/12b049528a204874f2c44cde96ce32763943b88a/src/Controls/src/Core/Items/CarouselView.cs#L194-L198

The property type system enforces that only [LinearItemsLayout](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) can be assigned.

File: src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs (hunk 2 above)
Comment (SyedAbdulAzeemSF4852) [reply src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs:356]: @jsuarezruiz ,  Yes, there is a potential divide-by-zero exception that could occur when the container has no width or when the effective item width calculation results in zero or a negative value. To prevent this, I've added a guard to skip the scroll calculation in such cases, avoiding invalid position updates.

**Comment by rmarinho** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Added a guard to prevent invalid layout calculations when the effective item width is zero or negative</strong> · <a href="https://github.com/dotnet/maui/commit/6a473e3c0486870c72b856e4a7c1031d5115ff36"><code>6a473e3</code></a></summary>

---

**Issue:** #32048 - [CarouselViewHandler2] CurrentItem does not work when ItemSpacing is set
**Platforms Affected:** iOS (CV2 / CarouselViewHandler2 only)
**Files Changed:** 1 implementation file, 2 test files

### Issue Summary
When `ItemSpacing` is set on a `CarouselView` using `CarouselViewHandler2` (CV2), the `CurrentItem` property does not update as the user swipes through items. The bug was confirmed reproducible on iOS 9.0.0, 9.0.110, 9.0.120. Fix was user-tested (see issue comment from @mypp74: "Everything works now with the fix.").

### Root Cause (from PR description)
The page index calculation in `LayoutFactory2.cs` only considered the container size but ignored the extra space consumed by `ItemSpacing`. When spacing was set, the effective width per page was larger, causing the wrong page index to be computed in `VisibleItemsInvalidationHandler`.

### Files Changed
- **Fix file:** `src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs` (+11/-1)
- **Test (HostApp):** `src/Controls/tests/TestCases.HostApp/Issues/Issue32048.cs` (+78 new)
- **Test (Shared):** `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue32048.cs` (+30 new)

### PR Discussion Summary
| File:Line | Reviewer | Comment | Status |
|-----------|----------|---------|--------|
| LayoutFactory2.cs:347 | jsuarezruiz | Can you scroll to last item and verify CurrentItem updates Addressed (video provided) |? | 
| LayoutFactory2.cs:347 | jsuarezruiz | Can you verify GridItemsLayout Addressed (CarouselView.ItemsLayout is typed as LinearItemsLayout, not GridItemsLayout) |? | 
| LayoutFactory2.cs:356 | jsuarezruiz | Could effectiveItemWidth be zero? Divide-by-zero risk Addressed (guard added: `if (effectiveItemWidth <= 0) return;`) |? | 
| LayoutFactory2.cs:346 | Copilot | Nitpick: improve comment  Open (minor, not blocking) |clarity | 

**Note:** `jsuarezruiz` submitted CHANGES_REQUESTED but all raised concerns have been addressed in the code. The review state may be stale.

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #32135 | Add `itemSpacing` to `effectiveItemWidth` in VisibleItemsInvalidationHandler; add divide-by-zero    PENDING (Gate) | `LayoutFactory2.cs` (+11/-1) | Original PR |guard |

</details>

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Added a guard to prevent invalid layout calculations when the effective item width is zero or negative</strong> · <a href="https://github.com/dotnet/maui/commit/6a473e3c0486870c72b856e4a7c1031d5115ff36"><code>6a473e3</code></a></summary>

---

**Result PASSED:** 
**Platform:** ios
**Mode:** Full Verification

- Tests FAIL without fix 
- Tests PASS with fix 

Test `Issue32048` correctly detects the bug when the fix is absent and passes when the fix is present.

</details>

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Added a guard to prevent invalid layout calculations when the effective item width is zero or negative</strong> · <a href="https://github.com/dotnet/maui/commit/6a473e3c0486870c72b856e4a7c1031d5115ff36"><code>6a473e3</code></a></summary>

---

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #32135 | Add  to  in VisibleItemsInvalidationHandler; add divide-by-zero guard |  PASS (Gate) | `LayoutFactory2.cs` (+11/-1) | Original PR |

**Exhausted:**  try-fix skipped due to repeated 429 rate-limit errors from AI model API (environment blocker, retried 3 times over ~4 minutes with exponential backoff).No 

**Selected Fix:** PR's  PR's approach is the only validated fix; no alternatives could be explored due to rate limiting.fix

</details>

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Added a guard to prevent invalid layout calculations when the effective item width is zero or negative</strong> · <a href="https://github.com/dotnet/maui/commit/6a473e3c0486870c72b856e4a7c1031d5115ff36"><code>6a473e3</code></a></summary>

---

##  Final Recommendation: APPROVE

### Summary
PR #32135 fixes a bug in `CarouselViewHandler2` (CV2) on iOS where `CurrentItem` did not update when `ItemSpacing` was set. The fix is minimal, correct, and well-tested. Gate verification confirms the tests correctly detect the bug and pass with the fix applied.

### Root Cause
The `VisibleItemsInvalidationHandler` computed the page index using:
```csharp
var page = (offset.X + sectionMargin) / (env.Container.ContentSize.Width - sectionMargin * 2);
```
The denominator is the visible item width, but when `ItemSpacing > 0`, the NSCollectionLayout engine adds `InterGroupSpacing` between groups, meaning each page scrolls by `(itemWidth + itemSpacing)` rather than just `itemWidth`. The denominator was too small, resulting in non-integer page values that failed the `page % 1 > epsilon` guard and prevented `CurrentItem` from being updated.

### Fix Quality
The PR's fix is mathematically sound:
```csharp
var itemSpacing = itemsView.ItemsLayout is LinearItemsLayout linearLayout ? linearLayout.ItemSpacing : 0;
var effectiveItemWidth = env.Container.ContentSize.Width - sectionMargin * 2 + itemSpacing;
if (effectiveItemWidth <= 0)
    return;
double page = (offset.X + sectionMargin) / effectiveItemWidth;
```
-  Correctly accounts for `InterGroupSpacing` in scroll unit calculation
-  Defensive against divide-by-zero (new guard added)
-  Handles case where `ItemsLayout` is not `LinearItemsLayout` (defaults to 0)
-  Minimal surgical change (11 lines added, 1 removed)
-  Reviewer concerns from `jsuarezruiz` all addressed (last-item scroll, GridItemsLayout N/A, divide-by-zero guard)
-  User @mypp74 confirmed fix works in their real project

### Test Quality
-  Both HostApp and Shared.Tests test files added
-  Tests correctly scoped to iOS (`PlatformAffected.iOS`, `#if TEST_FAILS_ON_WINDOWS`)
-  Uses `CarouselView2` (CV2 handler) to target the correct implementation
-  Tests validated: FAIL without fix, PASS with fix (Gate PASSED) 

### Minor Issues (Non-Blocking)
1. **PR title typo**: "Fir fox" should be "Fix  cosmetic onlyfor" 
2. **Copilot comment suggestion** (Line 346): Could clarify why spacing is  nitpick, not blockingadded 

### Reviewer Status
- `jsuarezruiz` submitted CHANGES_REQUESTED but all concerns were addressed in code. The review state is stale.

### Phase Summary
| Phase | Status |
|-------|--------|
| Pre-Flight COMPLETE | | 
| Gate PASSED (ios) | | 
| Fix (try- SKIPPED (rate limit environment blocker) |fix) | 
| Report COMPLETE | |

</details>

</details>

---

</details>



<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

---

<details>

<summary><b>Title: ⚠️ Needs Update</b></summary>

<br>

**Current:** `[CarouselViewHandler2] Fir fox CurrentItem does not work when ItemSpacing is set`

**Issues:**
1. **Typo:** "Fir fox" should be "Fix".
2. **Platform prefix:** The fix is in `Items2/iOS/LayoutFactory2.cs` — the iOS/MacCatalyst-only handler. The title should use `[iOS]` not the handler name per codebase conventions.
3. **Verbosity:** Uses "does not work" which is less precise than the actual behavior.

**Recommended:** `[iOS] CarouselView: Fix CurrentItem not updating when ItemSpacing is set`
</details>

<details>

<summary><b>Description: ✅ Good</b></summary>

<br>

1. **Typo:** "Fir fox" should be "Fix".
2. **Platform prefix:** The fix is in `Items2/iOS/LayoutFactory2.cs` — the iOS/MacCatalyst-only handler. The title should use `[iOS]` not the handler name per codebase conventions.
3. **Verbosity:** Uses "does not work" which is less precise than the actual behavior.
### ✨ Suggested PR Description


> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause

When `ItemSpacing` is set on a `CarouselView` using `CarouselViewHandler2` (CV2 — the iOS/MacCatalyst handler), the `VisibleItemsInvalidationHandler` computed the page index using only the container width:

```csharp
var page = (offset.X + sectionMargin) / (env.Container.ContentSize.Width - sectionMargin * 2);
```

The denominator represents the visible item width. But when `ItemSpacing > 0`, `NSCollectionLayout` applies `InterGroupSpacing` between groups, so each page scroll covers `(itemWidth + itemSpacing)` pixels, not just `itemWidth`. The denominator was too small, producing non-integer page values that failed the `page % 1 > epsilon` guard — `CurrentItem` was never updated.

### Description of Change

Updated `VisibleItemsInvalidationHandler` in `LayoutFactory2.cs` to include `ItemSpacing` when calculating the effective scroll width per page:

```csharp
var itemSpacing = itemsView.ItemsLayout is LinearItemsLayout linearLayout ? linearLayout.ItemSpacing : 0;
var effectiveItemWidth = env.Container.ContentSize.Width - sectionMargin * 2 + itemSpacing;
if (effectiveItemWidth <= 0)
{
    return;
}
double page = (offset.X + sectionMargin) / effectiveItemWidth;
```

The guard `effectiveItemWidth <= 0` prevents a divide-by-zero when the container has no width.

Added UI tests (`Issue32048.cs`) in both `TestCases.HostApp` and `TestCases.Shared.Tests` to reproduce the bug and verify the fix.

### Issues Fixed

Fixes #32048

### Platforms Affected

This fix is scoped to `CarouselViewHandler2` (`Items2/iOS/`), which serves **iOS and MacCatalyst only**. Windows and Android use a separate handler (`Items/`) and are not affected.

### Validated the behaviour in the following platforms

- [x] iOS
- [x] Mac (MacCatalyst)
- [ ] Windows *(not affected)*
- [ ] Android *(not affected)*
</details>

<details>

<summary><b>Code Review: ✅ Passed</b></summary>

<br>

# Code Review — PR #32135

## Code Review Findings

### 🟡 Suggestions

---

**1. Inaccurate platform validation in PR description**
- **File:** PR description (not code)
- **Problem:** The PR claims validation on Windows and Android. The fix is exclusively in `src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs`, which is the iOS/MacCatalyst-only handler. Windows and Android use a completely separate handler (`Items/`) which is unchanged.
- **Recommendation:** Update the validated platforms list to iOS and Mac only; mark Windows and Android as not affected.

---

**2. PR title typo**
- **File:** PR title
- **Problem:** Title reads "Fir fox" — should be "Fix".
- **Recommendation:** Rename to `[iOS] CarouselView: Fix CurrentItem not updating when ItemSpacing is set`

---

**3. Open Copilot review comment — comment clarity (line 346 of LayoutFactory2.cs)**
- **File:** `src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs`, line 346
- **Problem:** The comment "Calculate page index accounting for ItemSpacing" doesn't explain _why_ `itemSpacing` is added to `effectiveItemWidth`. The Copilot reviewer left an unresolved suggestion on this.
- **Current comment:**
  ```csharp
  // Calculate page index accounting for ItemSpacing
  ```
- **Recommended comment:**
  ```csharp
  // Calculate page index, including ItemSpacing because each item's scroll distance
  // consists of its width plus the spacing after it. This ensures paging accounts for
  // both the item width and the space between items.
  ```
- **Severity:** Nitpick — not blocking.

---

**4. Missing trailing newline in test files**
- **Files:**
  - `src/Controls/tests/TestCases.HostApp/Issues/Issue32048.cs` (last line has `\ No newline at end of file`)
  - `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue32048.cs` (same)
- **Recommendation:** Add a trailing newline to both files.
- **Severity:** Minor style issue.

---

**5. `Thread.Sleep` in MacCatalyst test path**
- **File:** `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue32048.cs`, line 23
- **Problem:** Uses `Thread.Sleep(1000)` with an inline `#if MACCATALYST` directive. Per UI testing guidelines, inline `#if` in test methods is discouraged, and `Thread.Sleep` is an anti-pattern.
- **Current code:**
  ```csharp
  #if MACCATALYST
      Thread.Sleep(1000);
  #endif
  ```
- **Context:** In this case there's no screenshot being taken — the test just waits for `CurrentItemChanged` to fire after a scroll. There's no `WaitForElement` equivalent for non-UI state changes, so a sleep may be the only option here. The sleep duration (1 second) is reasonable.
- **Severity:** Minor / acceptable. If a better mechanism becomes available, this should be revisited.

---

### ✅ Looks Good

- **Fix is mathematically correct.** The denominator `effectiveItemWidth = containerWidth - 2*sectionMargin + itemSpacing` correctly models the scroll distance per carousel page when `InterGroupSpacing` is set, matching what UICollectionViewCompositionalLayout does internally.

- **Divide-by-zero guard.** The `if (effectiveItemWidth <= 0) { return; }` guard is a good defensive addition. It handles the edge case when the container has no width during layout initialization.

- **Handles no-spacing case.** When `ItemsLayout` is not a `LinearItemsLayout` or `ItemSpacing == 0`, `itemSpacing` defaults to `0`, preserving the original behavior.

- **Minimal change.** The fix is surgical: 11 lines added, 1 removed in the implementation. No unrelated changes.

- **Tests are correct.** Both HostApp and SharedTests test files correctly exercise the bug scenario using `CarouselView2` (CV2 handler). The test correctly sets `ItemSpacing = 10` and uses `SnapPointsType.MandatorySingle` to ensure deterministic snapping. The `CurrentItemChanged` event handler drives the pass/fail assertion.

- **Test scope is accurate.** `PlatformAffected.iOS` in the HostApp and `#if TEST_FAILS_ON_WINDOWS` in SharedTests correctly scope the test to the affected platforms.

- **Reviewer concerns addressed.** All three review threads from `jsuarezruiz` were addressed: last-item scroll verified (video provided), GridItemsLayout is N/A (CarouselView.ItemsLayout is typed as `LinearItemsLayout`), and divide-by-zero guard was added.
</details>

---

</details>

**Review by kubaflo — CHANGES_REQUESTED** [review]
Test succeeded without a fix - could you please verify?

**Review by kubaflo — APPROVED** [review]
