### PR TITLE
[Windows] Fixes related with Clipping

### LINKED ISSUE #4250: [Windows]Clip property is not working properly in preview 12
### Description

When applying a clip with RoundRectangleGeometry to the content view, exception occur as like below  in windows 

image

**After calling CanvasDrawingSession.CreateLayer, you must close the resulting CanvasActiveLayer before ending the CanvasDrawingSession.**

### Steps to Reproduce

1.Run the attached sample in windows platform 
[ClipSample.zip](https://github.com/dotnet/maui/files/7912599/ClipSample.zip)
2.Click Apply effects button to change the round rectangle
3.Application get crash.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

iOS 15,Android 11,Windows

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fixes related with Clipping on Windows. Fixed exception `"After calling CanvasDrawingSession.CreateLayer, you must close the resulting CanvasActiveLayer before ending the CanvasDrawingSession"` and allow dynamically removing a Clipping.

clipping-windows

To test the changes launch the .NET MAUI Gallery, navigate to the Shapes page and use the Clipping samples.

### Issues Fixed

Fixes #4250

### CODE REVIEW

File: src/Core/src/Platform/Windows/WrapperView.cs [hunk 1]
```diff
@@ -55,6 +55,7 @@ internal set
 
 		public void Dispose()
 		{
+			DisposeClip();
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Windows/WrapperView.cs:58]: Allow dynamically removing an existing Clipping (Set `Clip = null`).

File: src/Core/src/Graphics/ShapeDrawable.cs [hunk 2]
```diff
@@ -109,6 +108,8 @@ void DrawFillPath(ICanvas canvas, RectF dirtyRect, PathF path)
 
 			canvas.SaveState();
 
+			ClipPath(canvas, path);
```
Comment (jsuarezruiz) [inline src/Core/src/Graphics/ShapeDrawable.cs:111]: Fix `CanvasDrawingSession` exception.

**Review by mattleibow — APPROVED** [review]

**Comment by PaulAnderson02** [comment]
Hi @jsuarezruiz ,

I have updated the RC 1 update with the ClipRadiusGallery sample of .NET MAUI sample gallery. Still the corner radius is not set correctly. Only the top left works.

MicrosoftTeams-image
