### PR TITLE
[.Net 10] Shell.SetNavBarVisibilityAnimationEnabled property

### LINKED ISSUE #26994: Shell.NavBarIsVisible="False" briefly displays navigation bar and disappears
### Description

Shell.NavBarIsVisible="False" set on ContentPage always worked but after upgrading to .NET 9 from 8, the navigation bar appears and disappears which create a flickering. It only happens quickly, and it was hard to figure out what it was initially. It doesn't happen when revisiting the page again. I only worked out what was happening from screen recording the app on iPhone and reviewed it at a slow speed. Happens only on iOS.

I've tested with a clean project with sample data and the same issue was confirmed. I only tested with Shell tab bar navigation.

### Steps to Reproduce

1. Create a MAUI project
2. Add TabBar navigation
3. In any page, add Shell.NavBarIsVisible="False"
4. Build the app
5. Switch tab pages on iPhone

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

iOS

### Affected platform versions

iOS 18.1

### Did you find any workaround?

Adding Shell.NavBarIsVisible="False" in AppShell.xaml didn't work but creating custom shell renderer worked as described in the link below.
https://github.com/dotnet/maui/issues/18948#issuecomment-2147582658

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

``` xaml
<Tab Shell.NavBarVisibilityAnimationEnabled="True">
    <ShellContent
                    Title="Home"
                    ContentTemplate="{DataTemplate local:MainPage}"
                    Route="MainPage"/>
</Tab>
```

This PR introduces a new public property: `NavBarVisibilityAnimationEnabled`

For now, the implementation only applies to iOS. If support for Android/Windows is desired in the future, it can be added separately.

NavBarVisibilityAnimationEnabled is a bool property added to Shell. It controls whether the navigation bar's visibility changes are animated. The default value is true to preserve existing behavior.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/26994

### Demo

```C#
public MainPage()
{
	InitializeComponent();
	var setHasNavigationBarSwitch = new Switch() { IsToggled = true };
	setHasNavigationBarSwitch.Toggled += (s, e) => Shell.SetNavBarIsVisible(this, e.Value);
	var setNavigationBarHiddenAnimation = new Switch() { IsToggled = true };
	setNavigationBarHiddenAnimation.Toggled += (s, e) => Shell.SetNavBarVisibilityAnimationEnabled(this, e.Value);

	Content = new VerticalStackLayout
	{
		Spacing = 5,
		Children =
			{
				new HorizontalStackLayout
				{
					Children =
					{
						new Label {
							Text = "NavigationPage.SetHasNavigationBar: ",
						},
						setHasNavigationBarSwitch,
					}
				},
				new HorizontalStackLayout
				{
					Children =
					{
						new Label {
							Text = "Page.NavigationBarHiddenAnimation: ",
						},
						setNavigationBarHiddenAnimation,
					}
				}
			}
	};
}
```

<video src="https://github.com/user-attachments/assets/3a230960-4372-4ec2-b66c-c5d33e3282b0"></video>

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs [hunk 1]
```diff
@@ -775,8 +774,6 @@ public override void WillShowViewController(UINavigationController navigationCon
 						navBarVisible = Shell.GetNavBarIsVisible(element);
 				}
 
-				navigationController.SetNavigationBarHidden(!navBarVisible, true);
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs:778]: Are we sure this doesn't break anything? What's the advantage of removing this line?

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs [hunk 2]
```diff
@@ -692,7 +691,7 @@ bool ShouldPop()
 
 		void UpdateNavigationBarHidden()
 		{
-			SetNavigationBarHidden(!Shell.GetNavBarIsVisible(_displayedPage), true);
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs:695]: Are we sure this doesn't break anything? What's the advantage of removing this line?

**Review by PureWeen — APPROVED** [review]
This is working great!
