### PR TITLE
Trigger InvalidateMeasure event on CollectionView when content size changes (iOS)

### LINKED ISSUE #21141: [iOS] CollectionView item cells do not resize when the content size is changed
### Description

I have collectionview and itemtemplate that can change it's size. Unfortunately, the collectionview item cell do not change it's size.
In Xamarin.Forms this is not an issue

[CollectionViewTest.zip](https://github.com/dotnet/maui/files/14564470/CollectionViewTest.zip)

### Steps to Reproduce

1. Build and Run attached project
2. click on items
3. see the items are not resized

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

nope

### Relevant log output

```shell
no logs
```

### PR DESCRIPTION
**Pull request by albyrock87**
### Description of Change

Problem reported in #21141 has been fixed by #23052 , except for one use case: nested collection view.
The nested `CollectionView` should trigger `MeasureInvalidated` but it's not: it is just triggering `SetNeedsLayout` on the native view.

This PR adds the event triggering so that the parent `TemplatedCell` can react to it.

### Issues Fixed

Fixes #21141

### CODE REVIEW

File: src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs [hunk 1]
```diff
@@ -403,6 +409,13 @@ await CreateHandlerAndAddToWindow<LayoutHandler>(layout, async handler =>
 						? containerHeight
 						: Math.Min(itemsCount * templateHeight, containerHeight);
 
+#if IOS
```
Comment (PureWeen) [inline src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:412]: Should this work on Windows and Android? 

If it currently doesn't and should, would it make sense to open an issue?

Comment (albyrock87) [reply src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:412]: I'd say: it should work on all platforms.
But apparently it only makes an actual difference on iOS (issue author is only talking about such platform).
I can try to make it work on Android, but I'll need some help for the Windows platform.

Comment (PureWeen) [reply src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:412]: More just curious if we should log an issue

If this test currently fails for Android/Windows we can just log an issue saying so and link to it. No need to hold this PR up for Android/Windows.

Comment (albyrock87) [reply src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:412]: Sounds good, I'll file a new issue then.
(Test is failing there)

Comment (albyrock87) [reply src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:412]: Done #24672

**Review by PureWeen — APPROVED** [review]
