### PR TITLE
[C] Fix typo

### LINKED ISSUE #29336: BindableProperty for a BindingBase property doesn't trigger PropertyChanging or PropertyChanged
### Description

I have a custom control layout that is trying to mask a Picker, so my layout class has a Picker as a property. Essentially I'm decorating a Picker with a custom layout. I want to expose the Picker's ItemDisplayBinding property, since I'm still using it, so I'm trying to create a BindableProperty on my custom layout that would set my private Picker instance's ItemDisplayBinding. However, I'm running into the issue where specifically for Binding or BindingBase, the BindableProperty's PropertyChanging and PropertyChanged don't trigger, so I can't use them to set my Picker's ItemDisplayBinding.
I have verified that the accessor is called, and seems to call the SetValue function. I can't step into it however, to be able to verify it actually runs correctly.

### Steps to Reproduce

Repo created and attached, but for quick reference, this is the minimal reproduction code:
```
public class testModel
{
    public string Name { get; set; }
}
public class testPicker : Grid
{
    private Picker pickerInput;

    // Should work, but doesn't
    public static readonly BindableProperty ItemDisplayBindingProperty = BindableProperty.Create(nameof(ItemDisplayBinding), typeof(BindingBase), typeof(testPicker), propertyChanged: (bindable, _, newValue) =>
    {
        if (bindable is testPicker view)
        {
            view.pickerInput.ItemDisplayBinding = (BindingBase)newValue;
        }
    });

    public BindingBase ItemDisplayBinding
    {
        get => (BindingBase)GetValue(ItemDisplayBindingProperty);
        set => SetValue(ItemDisplayBindingProperty, value);
    }

    public testPicker(List<testModel> items)
    {
        pickerInput = new() {ItemsSource = items};
        Add(pickerInput);
    }
}
public class TestPage : ContentPage
{
    private testPicker picker;
    public List<testModel> items =
    [
        new() {Name = "Test1"},
        new() {Name = "Test2"},
        new() {Name = "Test3"},
    ];

    public TestPage()
    {
        picker = new testPicker(items) {ItemDisplayBinding = new Binding("Name")};
        picker.ItemDisplayBinding = new Binding("Name");
        Content = new VerticalStackLayout {Children = {picker}};
    }
}
```
It doesn't have any of the decoration that I want to add to the picker, it's just to show the issue. If you add a breakpoint in the PropertyChanged handler, I'd expect it to be hit when setting the ItemDisplayBinding field. It doesn't, however, and the actual list shows as
```
SimpleTest.testModel
SimpleTest.testModel
SimpleTest.testModel
```
Instead of the expected
```
Test1
Test2
Test3
```

### Link to public reproduction project repository

https://github.com/CristianRRangel/MAUI_BindableProperty_Issue

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

No, this is something new, Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10

### Did you find any workaround?

I am able to make it work by either making ItemDisplayBinding on my testPicker class a simple accessor, like this:
```
public BindingBase ItemDisplayBinding
{
  get => pickerInput.ItemDisplayBinding;
  set => pickerInput.ItemDisplayBinding = value;
}
```
or even by changing the type of my ItemDisplayBinding to be a string and generating a new Binding from that:
```
  public static readonly BindableProperty ItemDisplayBindingProperty = BindableProperty.Create(nameof(ItemDisplayBinding), typeof(string), typeof(testPicker), propertyChanged: (bindable, _, newValue) =>
    {
        if (bindable is testPicker view)
        {
            view.pickerInput.ItemDisplayBinding = new Binding((string)newValue);
        }
    });

    public string ItemDisplayBinding
    {
        get => (string)GetValue(ItemDisplayBindingProperty);
        set => SetValue(ItemDisplayBindingProperty, value);
    }
```

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change

major facepalm

### Issues Fixed

- fixes #29336

### CODE REVIEW

File: src/Controls/src/Core/BindableObject.cs [hunk 1]
```diff
@@ -482,7 +482,7 @@ public void SetValue(BindableProperty property, object value)
 			if (property == null)
 				throw new ArgumentNullException(nameof(property));
 
-			if (value is BindingBase binding && !property.ReturnType.IsAssignableFrom(typeof(BindableProperty)))
+			if (value is BindingBase binding && !property.ReturnType.IsAssignableFrom(typeof(BindingBase)))
```
Comment (StephaneDelcroix) [inline src/Controls/src/Core/BindableObject.cs:485]: when we set BP of type BindingBase, we do not SetBinding, we SetValue. XAML inflators are doing this right, and it only happens when used in code. this is why it was never caught

**Review by rmarinho — DISMISSED** [review]

**Review by PureWeen — APPROVED** [review]
