### PR TITLE
[iOS] Fix SafeArea infinite layout cycle with parent hierarchy walk and pixel-level comparison

### LINKED ISSUE #32586: Layout issue using TranslateToAsync causes infinite property changed cycle on iOS
### Description

After upgrading my app to .NET 10 I found that one page with a custom UI component stopped working, it appeared like the UI had crashed but there were no failing tasks, I have found that after translating a view it causes an infinite property changed cycle, causing the animation task to never complete and the UI of the app to be deadlocked.

I have an extensive write up of this in my reproduction app.

This could potentially be an issue with the way in which my `FooterView` has been implemented, however it is a very simple container style view which I have used extensively since the days of Forms so I doubt it is me. It also works on Android so that points to an issue in the iOS layout engine that gets exposed when applying translations.

### Steps to Reproduce

- Download the sample app
- Follow the instructions to observe the behavior working on net9 & not on net10

### Link to public reproduction project repository

https://github.com/Axemasta/MauiRepros/tree/main/src/TranslateToNet10

### Version with bug

10.0.10

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.120 SR12

### Affected platforms

iOS

### Affected platform versions

All tested

### Did you find any workaround?

It is mentioned in the provided repo, no workarounds that include both the animation and the custom `FooterView`. Either don't use animations or don't use your container view!

### Relevant log output

```shell

```

### LINKED ISSUE #33595: [net10] iOS 18.6 crashing on navigating to a ContentPage with Padding set and Content set to a <Grid RowDefinitions="*,Auto"> with ScrollView on row 0
### Description

With the .NET 10 MAUI, the app is crashing/freezing on iOS 18.6 if you want to navigate to a ContentPage with Padding="5,5,5,5" set and the page also contains in the ContentPage.Content a <Grid RowDefinitions="*,Auto"> which also contains a <ScrollView> on row 0 and any other item on row 1.

### Steps to Reproduce

1. Create new MAUI app with .NET 10 and uncheck "Include sample content"
2. Update packages
3. Create a new page "NewPage.xaml" with the following content:```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp5.NewPage1"
             Padding="5,5,5,5"
             Title="NewPage1">

    <Grid RowDefinitions="*,Auto"
          Padding="0"
          Margin="0">

        <ScrollView Grid.Row="0">

            <VerticalStackLayout Padding="16"
                                 Spacing="12"
                                 Margin="0,0,0,88">
       
                <Label Text="Text 2" FontSize="24"/>
                <Label Text="Text lung..." />
            </VerticalStackLayout>
        </ScrollView>

        <Grid Grid.Row="1"
              Padding="16">
            <Button Text="Continue"
                    HeightRequest="52"
                    CornerRadius="12" />
        </Grid>

    </Grid>
</ContentPage>```

4. On MainPage.xaml.cs, change the content of OnCounterClicked to push in the Navigation stack the new created page: 
```private async void OnCounterClicked(object? sender, EventArgs e)
{
        await Navigation.PushAsync(new NewPage1());
}
```

5. Run the app on an iPhone 16 Pro iOS 18.6 simulator and press the clicked event

### Link to public reproduction project repository

https://github.com/leonardbarbu/mauiapp5

### Version with bug

10.0.30

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.110 SR11

### Affected platforms

iOS

### Affected platform versions

Affected iOS 18.6 on project running from Workload version 10.0.102, SDK 10.0.100, VS 18.2.11408.102, Manifest version 26.2.10191/10.0.100

### Did you find any workaround?

Move padding inside the items of Grid:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp5.NewPage1"
             
             Title="NewPage1">

    <Grid RowDefinitions="*,Auto"
          Padding="0"
          Margin="0">

        <ScrollView Grid.Row="0" Padding="5,5,5,5">

            <VerticalStackLayout Padding="16"
                                 Spacing="12"
                                 Margin="0,0,0,88">
       
                <Label Text="Text 2" FontSize="24"/>
                <Label Text="Text lung..." />
            </VerticalStackLayout>
        </ScrollView>

        <Grid Grid.Row="1" Padding="5,5,5,5">
            <Button Text="Continue"
                    HeightRequest="52"
                    CornerRadius="12" />
        </Grid>

    </Grid>
</ContentPage>
```

### Relevant log output

```shell
No errors, the app just freezes.
```

### LINKED ISSUE #33934: [iOS] TranslateToAsync causes spurious SizeChanged events after animation completion, triggering infinite layout loops
### Description

Note: this is a _critical and show-stopping_ bug for us. We cannot move to Maui10 with this issue, but we _need_ to.

On iOS, `TranslateToAsync()` triggers `SizeChanged` events **after animation completion**. The view's height actually changes by a few pixels (e.g., 307.97 → 310.23). 

Does not occur with `ScaleYTo()` - only `TranslateToAsync()`.

During debugging, observed iOS `MauiView` SafeArea code continuously invalidating parent layouts. Even disabling animations doesn't fully prevent the issue. Blocking production release - no reliable workarounds found.

### Expected Behavior

```
════ ITERATION #1 ════
╔═══ SizeChanged ═══
║ 376.47x307.97, TY:0              // Initial layout
🎬 Animation START
🔄 RESTARTING!                      // Expected restart due to initial layout
════ ITERATION #2 ════
🎬 Animation START
✅ COMPLETE!
🎉 EXIT
```

The animation should complete after the initial layout settles.

### Actual Behavior

```
════ ITERATION #2 ════
🎬 Animation START: 307.97 → 0
✅ COMPLETE!
╔═══ SizeChanged ═══                // EXTRA event AFTER completion
║ 376.47x310.23, TY:0               // Height changed by ~2 pixels!
🔄 RESTARTING!
════ ITERATION #3 ════
🎬 Animation START
✅ COMPLETE!
╔═══ SizeChanged ═══                // Keeps happening!
🔄 RESTARTING!
...                                  // Infinite loop
```

The view height changes slightly after **each** `TranslateToAsync()` completion, causing infinite restarts and UI freezes.

## Version Info

- .NET 10 (SDK 10.0.101)
- iOS (simulator and physical devices)

## Observations

The reproduction uses a restart loop: monitors `SizeChanged` during animation, cancels and restarts if fired. This handles MAUI's late-resolving bindings.

Pattern worked reliably on Android and earlier MAUI versions. On iOS with .NET 10, `TranslateToAsync()` now triggers size changes after completion - creates infinite restart loop.

### Steps to Reproduce

Reproduction project attached: `DialogTestRepro.zip`. This does not reproduce _accurately_ as it does not get the full freeze our full app does, but it's the closest we've been able to get.

1. Build and run on iOS
2. Tap "Show Dialog" 
3. Observe infinite loop in debug output

[DialogTestRepro.zip](https://github.com/user-attachments/files/25143369/DialogTestRepro.zip)

### Link to public reproduction project repository

_No response_

### Version with bug

10.0.30

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

9.0.120 SR12

### Affected platforms

iOS

### Affected platform versions

I don't have the information available at this time. Newer versions though, haven't tested older ones and that's probably an idea.

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### LINKED ISSUE #34042: Infinite Measure Looping on iOS
### Description

I was upgrading our app to dotnet 10 and after testing on iOS, the app froze a lot of places, with no errors reported or anything. 

After some digging i found that with some "magic" configuration (eg. label with font size 18) the app got stuck in some infinite measure loop.

I have tested with 10.0.0, 10.0.10, 10.0.11, 10.0.20, 10.0.30, 10.0.31 and 10.0.40

We have decided to pause our .net 10 upgrade until this is fixed

### Steps to Reproduce

1. pull the code from the repo, run the code on iOS
2. press one of the 3 examples and wait for the quick and dirty loop detector to stop the loop (stopping after 500 size changed) 
3. The app is unresponsive while the loop is running.

### Link to public reproduction project repository

https://github.com/JohnTraDolta/MauiInfiniteMeasureLoopingBug

### Version with bug

10.0.40

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.100 SR10

### Affected platforms

iOS

### Affected platform versions

iOS 26.1

### Did you find any workaround?

Nothing i recommend, but changing Label font size, setting fixed height on labels. Not using GridLength.Auto. 
 

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by PureWeen**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause

`SafeAreaInsetsDidChange` fires repeatedly during iOS animations (e.g., `TranslateToAsync`, bottom sheet transitions) as views move relative to the window. This caused two distinct infinite loop patterns:

1. **Sub-pixel oscillation** (#32586, #33934): Animations produce sub-pixel differences in `SafeAreaInsets` (e.g., `0.0000001pt`). Exact equality fails, triggering `InvalidateAncestorsMeasures` → layout pass → position change → new `SafeAreaInsetsDidChange` → infinite loop.

2. **Parent-child double application** (#33595): A `ContentPage` (implementing `ISafeAreaView`) and its child `Grid` both independently apply safe area adjustments. When the `ContentPage` adjusts its layout for the notch/status bar, it repositions the `Grid`. The `Grid`'s new position fires `SafeAreaInsetsDidChange`, causing it to re-apply its own adjustment — creating a ping-pong loop.

### Description of Change

**Primary fix — `IsParentHandlingSafeArea` (parent hierarchy walk):**

In both `MauiView.ValidateSafeArea` and `MauiScrollView.ValidateSafeArea`, before applying safe area adjustments, we now check whether an ancestor `MauiView` is already applying safe area for the **same edges**. If so, the child skips its own adjustment to avoid double-padding.

The check is **edge-aware**: a parent handling `Top` does not block a child from independently handling `Bottom`. Only overlapping edges cause deferral. The `_parentHandlesSafeArea` result is cached per layout cycle and cleared on `SafeAreaInsetsDidChange`, `InvalidateSafeArea`, and `MovedToWindow`.

**Secondary fix — `EqualsAtPixelLevel`:**

Safe area values are compared at device-pixel resolution (rounding to `1 / ContentScaleFactor`) before deciding whether to trigger a layout invalidation. This absorbs sub-pixel animation noise and prevents the oscillation loops in #32586 and #33934.

**MauiScrollView bug fixes:**
- Inverted condition: `!UpdateContentInsetAdjustmentBehavior()` was incorrectly gating behavior; corrected to `UpdateContentInsetAdjustmentBehavior()`.
- The `_appliesSafeAreaAdjustments` flag now correctly incorporates `!IsParentHandlingSafeArea()`.

**What was removed:**
- The "Window Guard" approach (comparing `Window.SafeAreaInsets` to filter noise) was tried and removed. It was fragile: on macCatalyst with a custom TitleBar, `WindowViewController` repositions content by pushing it down, which changes the view's own `SafeAreaInsets` without changing `Window.SafeAreaInsets`. The guard blocked this legitimate change, causing a 28px content shift regression in CI.

### Issues Fixed
Fixes #32586
Fixes #33934
Fixes #33595
Fixes #34042

### CODE REVIEW

**Comment by PureWeen** [comment]
## Test Results ✅

Successfully fixed the infinite layout cycle! The fix now passes all tests:

### Issue32586 Test (the freeze repro)
- **Before**: App froze indefinitely, test hung forever
- **After**: Test passes ✅

### All SafeAreaEdges Tests  
- **Result**: All passed ✅

## How the Fix Works

The root cause was that `InvalidateMeasure()` sets `_safeAreaInvalidated = true` on ancestor views. This caused `ValidateSafeArea()` to run again on the next `LayoutSubviews` even when safe area values hadn't changed, creating a cycle.

The fix uses a **global generation counter** that increments each time any view invalidates ancestors from `LayoutSubviews`. Each view tracks the generation at which it last invalidated. If asked to layout again at the same generation (we're in a cycle), it skips the invalidation.

This preserves correct SafeArea behavior while breaking the infinite loop.

## Bonus: Test Infrastructure Improvements

Also added resilience fixes to prevent tests from hanging indefinitely when apps freeze:
1. **Process-level timeout** in BuildAndRunHostApp.ps1 (5 minutes)
2. **Property getter timeouts** for GetText/GetAttribute/GetRect/IsSelected
3. **Teardown timeouts** for App.AppState queries

These ensure tests fail gracefully instead of hanging, making it much easier to debug layout issues like this one.

File: src/Core/src/Platform/iOS/MauiView.cs [hunk 1]
```diff
@@ -62,6 +62,18 @@ public abstract class MauiView : UIView, ICrossPlatformLayoutBacking, IVisualTre
...
+		// Used to prevent the same view from triggering multiple ancestor invalidations in a cascade.
+		// When view A invalidates ancestors, it stores the current generation. If it's asked to layout
+		// again before the generation changes (meaning we're in a cycle), it skips invalidation.
+		static int s_safeAreaGeneration;
+
+		// The safe area generation at which this view last triggered ancestor invalidation
+		// from LayoutSubviews. If we've already invalidated for this generation, skip it
+		// to break infinite layout cycles between parent and child views that both respond
+		// to safe area.
+		int _lastSafeAreaInvalidationGeneration = -1;
```
Comment (albyrock87) [inline src/Core/src/Platform/iOS/MauiView.cs]: What about using a byte or a short instead of int given we're only checking by equality?
Interlocked is implicitly `unchecked`.

**Comment by PureWeen** [comment]
Alright @Tamilarasan-Paranthaman @sheiksyedm 

Let me know what you think of this fix

**Comment by PureWeen** [comment]
## 🔬 Fix Approach Comparison — 4 Independent Attempts

We ran 4 independent try-fix attempts, each proposing a **fundamentally different** approach to fix the iOS safe area infinite layout cycle. After retesting with the updated UITests (with `[Order]` attributes and state-reset logic), **only Approach 3 passes all tests**.

### Retest Results (Updated UITests)

| # | Approach | Filters By | Issue32586 (3 tests) | Issue33934 | Overall |
|---|----------|------------|---------------------|------------|---------|
| 1 | Epsilon tolerance | VALUE | ❌ 2/3 | ❌ FAIL | ❌ FAIL |
| 2 | Layout guard | CONTEXT | ❌ 2/3 | ✅ PASS | ⚠️ Partial |
| 3 | **Window-level comparison** | **SOURCE** | **✅ 3/3** | **✅ PASS** | **✅ PASS** |
| 4 | Time-based debounce | TIME | ❌ 2/3 | ❌ FAIL | ❌ FAIL |

**Common failure in approaches 1, 2, 4:** `VerifyFooterPositionRespectsSafeArea` — footer stays ~33pt above screen bottom despite `SafeAreaEdges=None`, proving safe area is still being applied incorrectly.

### ✅ Selected: Approach 3 — Window-Level Safe Area Comparison (applied in `3498ef8`)

All approaches also fix a pre-existing bug in `MauiScrollView.cs` where `_safeAreaInvalidated = true` should be `_safeAreaInvalidated = false` in `ValidateSafeArea()` (the flag was never being cleared after validation).

---

<details>
<summary><strong>✅ Approach 3: Window-Level Comparison (SELECTED — filters by SOURCE)</strong></summary>

### Concept
Compare `Window.SafeAreaInsets` (device-level: status bar, home indicator) in `SafeAreaInsetsDidChange()`. During animations, a view's own `SafeAreaInsets` fluctuate, but `Window.SafeAreaInsets` stay constant. If Window insets haven't changed, the event is animation noise → skip it entirely.

### Why it works
- **#33934**: During `TranslateToAsync`, `Window.SafeAreaInsets` doesn't change → early return → `_safeAreaInvalidated` stays false → no invalidation cascade.
- **#32586**: No rounding = no risk of rounding artifacts on zero values. Animation-induced `SafeAreaInsetsDidChange` is filtered → no spurious invalidation.

### Changes
- **MauiView.cs**: Added `_lastWindowSafeAreaInsets` field, Window comparison in `SafeAreaInsetsDidChange()`, reset in `MovedToWindow()`
- **MauiScrollView.cs**: Same pattern + `_safeAreaInvalidated` bug fix + `MovedToWindow()` reset

### Key code
```csharp
UIEdgeInsets _lastWindowSafeAreaInsets;

public override void SafeAreaInsetsDidChange()
{
    if (Window is not null)
    {
        var windowInsets = Window.SafeAreaInsets;
        if (windowInsets == _lastWindowSafeAreaInsets)
            return;
        _lastWindowSafeAreaInsets = windowInsets;
    }
    _safeAreaInvalidated = true;
    base.SafeAreaInsetsDidChange();
}
```

### Pros
- Semantically clear: filters by the SOURCE of truth for device safe areas
- No magic numbers, no structural changes
- Only genuine safe area events (rotation, keyboard, status bar) pass through
- Keyboard events handled separately via `OnKeyboardWillShow/Hide`

### Cons
- Assumes `Window.SafeAreaInsets` never changes during animations (should hold but is UIKit implementation detail)
- Requires `MovedToWindow()` override to reset cached value

</details>

<details>
<summary><strong>❌ Approach 1: Epsilon-Based Tolerance (FAILED retest — filters by VALUE)</strong></summary>

### Concept
Use epsilon-based tolerance comparison (0.5pt) to absorb sub-pixel noise from animations. Values that differ by less than epsilon are treated as unchanged.

### Retest Result
- **Issue32586**: ❌ `VerifyFooterPositionRespectsSafeArea` failed — footer 33pt short of screen bottom
- **Issue33934**: ❌ Timed out — infinite animation loop not prevented

### Why it failed
Epsilon comparison only filters sub-pixel noise at the value level but doesn't prevent the SafeAreaInsetsDidChange callback from firing and setting `_safeAreaInvalidated = true`. The safe area values can still differ by more than epsilon during animations.

</details>

<details>
<summary><strong>⚠️ Approach 2: Layout Guard (PARTIAL — filters by CONTEXT)</strong></summary>

### Concept
Track when inside `LayoutSubviews()` with `_isInLayoutSubviews` flag. Skip ancestor invalidation during layout passes.

### Retest Result
- **Issue32586**: ❌ `VerifyFooterPositionRespectsSafeArea` failed — footer 33pt short of screen bottom
- **Issue33934**: ✅ PASS — animation completes

### Why it partially failed
The layout guard prevents the infinite cycle (33934 passes) but doesn't prevent safe area values from being applied when they shouldn't be. The flag only gates invalidation, not the safe area calculation itself.

</details>

<details>
<summary><strong>❌ Approach 4: Time-Based Debounce (FAILED retest — filters by TIME)</strong></summary>

### Concept
Coalesce rapid `SafeAreaInsetsDidChange` calls using a 16ms debounce window (~1 frame).

### Retest Result
- **Issue32586**: ❌ `VerifyFooterPositionRespectsSafeArea` failed — footer 33pt short of screen bottom
- **Issue33934**: ❌ Timed out — infinite animation loop not prevented

### Why it failed
Time-based filtering still allows the first SafeAreaInsetsDidChange per frame through, which is enough to trigger the invalidation cycle. The problem isn't rate-of-change but that animation-induced changes shouldn't trigger invalidation at all.

</details>

File: src/Core/src/Platform/iOS/SafeAreaPadding.cs [hunk 2]
```diff
@@ -28,6 +28,23 @@ public CGRect InsetRect(CGRect bounds)
...
+	{
+		var scale = (double)UIScreen.MainScreen.Scale;
+		return RoundToPixel(Left, scale) == RoundToPixel(other.Left, scale)
+			&& RoundToPixel(Right, scale) == RoundToPixel(other.Right, scale)
+			&& RoundToPixel(Top, scale) == RoundToPixel(other.Top, scale)
+			&& RoundToPixel(Bottom, scale) == RoundToPixel(other.Bottom, scale);
+	}
+
+	static double RoundToPixel(double value, double scale)
+		=> Math.Round(value * scale) / scale;
```
Comment (albyrock87) [inline src/Core/src/Platform/iOS/SafeAreaPadding.cs]: Shall we use `MidpointRounding.AwayFromZero` here? it seems more appropriate

Comment (albyrock87) [reply src/Core/src/Platform/iOS/SafeAreaPadding.cs]: Also why don't we simply compare `Math.Round(value * scale, MidpointRounding.AwayFromZero)` without `/ scale` on every value?
Dividing by `scale` doesn't seem relevant for the comparison.

**Comment by kubaflo** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Make IsParentHandlingSafeArea edge-aware to fix parent/child independent edge handling</strong> · <a href="https://github.com/dotnet/maui/commit/eb2be69442a458adc1def59ea11be19d8ffb851e"><code>eb2be69</code></a></summary>

---

**Issue:** #32586, #33934, #33595, #34042 - iOS infinite layout cycle when TranslateToAsync animations trigger SafeAreaInsetsDidChange repeatedly
**Platforms Affected:** iOS (primary)
**Files Changed:** 4 implementation files, 13+ test files, 4 documentation files

### Issue Summary

When `TranslateToAsync` is used on iOS views inside safe area containers, the animation repositions the view relative to the window, which causes `SafeAreaInsetsDidChange` to fire repeatedly. The insets may differ by sub-pixel amounts (e.g., `0.0000001pt`). Since the equality comparison previously used `double` precision, these sub-pixel differences prevented early-exit, triggering layout invalidation → view repositioning → new `SafeAreaInsetsDidChange` → **infinite cycle → app freeze**.

### Fix Approach (Dual Defense)

The PR uses two layers of protection:

1. **Source filtering** (`SafeAreaInsetsDidChange`): Compare `Window.SafeAreaInsets` (stable during animations) AND view-level `SafeAreaInsets`. Only skip if BOTH are unchanged (animation noise). Allow through if either genuinely changed.

2. **Value filtering** (`ValidateSafeArea`): Use `EqualsAtPixelLevel()` to absorb remaining sub-pixel differences that survive the source filter.

3. **Bypass mechanism** (`InvalidateSafeArea` + `InvalidateDescendantSafeAreas`): When `SafeAreaEdges` changes at runtime on a parent, explicitly propagate safe area invalidation to descendants to bypass the Window guard.

4. **Bug fix**: `MauiScrollView.ValidateSafeArea()` had `_safeAreaInvalidated = true` instead of `_safeAreaInvalidated = false` — the flag was never cleared after validation.

5. **Cache reset** in `MovedToWindow()` so new window's safe area is always processed.

### Files Changed

**Fix files (iOS platform):**
- `src/Core/src/Platform/iOS/MauiView.cs` (+54, -2)
- `src/Core/src/Platform/iOS/MauiScrollView.cs` (+57, -9)
- `src/Core/src/Platform/iOS/SafeAreaPadding.cs` (+17) — new `EqualsAtPixelLevel` method
- `src/Core/src/Handlers/View/ViewHandler.iOS.cs` (+29) — `InvalidateDescendantSafeAreas` propagation

**Test files:**
- `src/Controls/tests/TestCases.HostApp/Issues/Issue32586.cs` — main freeze repro test
- `src/Controls/tests/TestCases.HostApp/Issues/Issue33595.cs` — navigation + ScrollView crash test
- `src/Controls/tests/TestCases.HostApp/Issues/Issue33934.xaml/.cs` — bottom sheet animation test
- `src/Controls/tests/TestCases.HostApp/Issues/Issue28986_ParentChildTest.xaml/.cs` — parent/child SafeAreaEdges runtime test
- Corresponding Shared.Tests counterparts for each
- Additional Issue33934 dialog/base files

**Documentation:**
- `.github/instructions/safe-area-debugging.instructions.md` (new, 242 lines)
- `.github/instructions/uitests.instructions.md` (+42)
- `.github/instructions/README.md` (new, 107 lines)
- `.github/copilot-instructions.md` (+7)

### PR Discussion

**Reviewer comments from `albyrock87`** (inline code review):
- Should `MidpointRounding.AwayFromZero` be used in `RoundToPixel`? → **ALREADY USED in final code** ✅
- Don't need to divide by scale for comparison → **Already not dividing by scale** ✅

**Copilot auto-reviewer** raised thread safety concern about `s_safeAreaGeneration` counter — this appears to be from an **earlier iteration** of the PR (generation-counter approach) and is **not present in current code**. The concern does not apply to the current implementation.

**PR description discrepancy**: Description says "Used `ContentScaleFactor` instead of `Window.Screen.Scale`" but actual code uses `UIScreen.MainScreen.Scale`. Minor discrepancy — both are valid, but `ContentScaleFactor` would be the per-view scale while `UIScreen.MainScreen.Scale` is the global screen scale.

### Fix Candidates

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #34024 | Dual defense: Window+View guard in SafeAreaInsetsDidChange + EqualsAtPixelLevel in ValidateSafeArea | ⏳ PENDING (Gate) | 4 impl files | Original PR |

</details>

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Make IsParentHandlingSafeArea edge-aware to fix parent/child independent edge handling</strong> · <a href="https://github.com/dotnet/maui/commit/eb2be69442a458adc1def59ea11be19d8ffb851e"><code>eb2be69</code></a></summary>

---

**Result:** ✅ PASSED
**Platform:** ios
**Mode:** Full Verification
**Test Filter:** Issue32586

- Tests FAIL without fix ✅ (bug correctly detected by tests)
- Tests PASS with fix ✅ (fix correctly resolves the bug)

The Issue32586 tests correctly catch the infinite layout cycle caused by TranslateToAsync animations triggering SafeAreaInsetsDidChange.

</details>

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Make IsParentHandlingSafeArea edge-aware to fix parent/child independent edge handling</strong> · <a href="https://github.com/dotnet/maui/commit/eb2be69442a458adc1def59ea11be19d8ffb851e"><code>eb2be69</code></a></summary>

---

### Fix Candidates

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| 1 | try-fix (claude-sonnet-4.6) | Deferred Ancestor Invalidation — DispatchAsync propagation with snapshot comparison; only propagates if view stable post-animation | ✅ PASS | MauiView.cs, MauiScrollView.cs | Introduces async timing sensitivity |
| 2 | try-fix (claude-opus-4.6) | Streak Counter + EqualsAtPixelLevel — cycle detection via streak counter limiting propagations + pixel rounding | ✅ PASS | MauiView.cs, MauiScrollView.cs, SafeAreaPadding.cs | Smaller diff; streak counter is a heuristic |
| 3 | try-fix (gpt-5.2) | CALayer Transform Detection — Skip safe area invalidation when `CALayer.Transform` is non-identity on any ancestor | ✅ PASS | MauiView.cs, MauiScrollView.cs, SafeAreaPadding.cs | Only targets transform animations; UITest.cs modification needed |
| 4 | try-fix (gpt-5.3-codex) | IView.TranslationX/Y Check — Skip when MAUI virtual translation is non-zero | ❌ FAIL | MauiView.cs, MauiScrollView.cs | Too narrow; test timed out (translation may be 0 while animation still in-flight) |
| 5 | try-fix (gemini-3-pro-preview) | Epsilon Tolerance (0.5pt fixed) — `EqualsWithTolerance` in `ValidateSafeArea` | ✅ PASS | MauiView.cs, MauiScrollView.cs, SafeAreaPadding.cs | Simplest fix; hardcoded 0.5pt may suppress legitimate small inset changes |
| PR | PR #34024 | Dual defense: Window+View guard in SafeAreaInsetsDidChange + EqualsAtPixelLevel in ValidateSafeArea + InvalidateSafeArea bypass + bug fix | ✅ PASS (Gate) | MauiView.cs, MauiScrollView.cs, SafeAreaPadding.cs, ViewHandler.iOS.cs | Original PR |

### Cross-Pollination Round 2

| Model | Response |
|-------|----------|
| claude-sonnet-4.6 | 3 new ideas: Re-entrancy guard; Animation suppression flag in MAUI layer; Window vs. view SafeAreaInsets comparison (similar to PR's approach) |
| claude-opus-4.6 | NEW IDEA: Animation Transaction Grouping — MAUI-layer flag set before AnimateAsync block, cleared in completion callback |
| gpt-5.2 | NEW IDEA: Coalesce/debounce — enqueue single re-validate per run-loop, drop merging during debounce |
| gpt-5.3-codex | NEW IDEA: Reentrancy + generation gate — per-view "update-in-progress" token, coalesced recheck on next layout pass |
| gemini-3-pro-preview | NEW IDEA: `Layer.AnimationKeys` check — suppress when `AnimationKeys` has entries (similar to Attempt 3's transform detection) |

All cross-pollination ideas are either (a) minor variations of existing attempts, (b) require modifications to MAUI animation APIs (out of scope), or (c) were covered by prior exploration.

**Exhausted:** Yes — all 5 models have responded and new ideas are variations of already-explored approaches.

**Selected Fix:** PR's fix — The PR's dual-defense approach is the most semantically correct:
1. Window+View guard correctly identifies animation-noise events by checking the actual device-level safe area (Window.SafeAreaInsets), with a secondary view-level check for repositioning cases like TitleBar.
2. EqualsAtPixelLevel provides a safety net using pixel-resolution comparison (device-adaptive, not fixed-epsilon).
3. InvalidateSafeArea bypass correctly handles runtime SafeAreaEdges changes without being blocked by the Window guard.
4. The pre-existing bug fix (MauiScrollView `_safeAreaInvalidated = true` → `false`) is included and important in its own right.
5. The approach is self-documented — the PR includes safe-area-debugging.instructions.md that explains exactly WHY the dual-level check is needed and what failure modes it avoids.

</details>

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Make IsParentHandlingSafeArea edge-aware to fix parent/child independent edge handling</strong> · <a href="https://github.com/dotnet/maui/commit/eb2be69442a458adc1def59ea11be19d8ffb851e"><code>eb2be69</code></a></summary>

---

## ✅ Final Recommendation: APPROVE

### Summary

PR #34024 fixes a serious iOS infinite layout cycle that caused app freezes when `TranslateToAsync` animations were used with safe area containers. The fix is well-designed, empirically validated by Gate (tests FAIL without it, PASS with it), and independently corroborated by 4 out of 5 try-fix alternatives also finding working solutions.

The **PR's dual-defense approach** is the most semantically correct among all candidates: it filters noise at the source (SafeAreaInsetsDidChange) AND at the value-comparison level (ValidateSafeArea), with proper bypass mechanisms and a bonus pre-existing bug fix.

**One concern**: The PR description doesn't accurately match the implementation (see below). Updating it is recommended before merge.

---

### Root Cause

`TranslateToAsync` on iOS sets a `CALayer` transform on the view, which causes UIKit to fire `SafeAreaInsetsDidChange` on every animation frame. The view's position relative to the window changes, but the **device-level** safe area (status bar, home indicator) doesn't. Because `SafeAreaPadding` used exact `double` equality, sub-pixel floating-point drift (~0.0000001pt) from animation frame rounding was treated as a genuine safe area change, triggering: layout invalidation → repositioning → new `SafeAreaInsetsDidChange` → **infinite cycle → app freeze**.

A secondary bug: `MauiScrollView.ValidateSafeArea()` had `_safeAreaInvalidated = true` instead of `_safeAreaInvalidated = false`, so the flag was never cleared after validation, causing redundant re-runs even when not needed.

---

### Fix Quality

The PR implements a **dual-defense approach**:

1. **Source filtering** (`SafeAreaInsetsDidChange`): Compare `Window.SafeAreaInsets` (device-level, stable during animations) AND view-level `SafeAreaInsets`. Only skip if BOTH are unchanged. This correctly distinguishes animation noise from real events (rotation, keyboard, status bar changes).

2. **Value filtering** (`ValidateSafeArea`): `EqualsAtPixelLevel()` rounds to device pixel resolution using `Math.Round(value * scale, MidpointRounding.AwayFromZero)` before comparing. Absorbs any sub-pixel noise that survives the source filter.

3. **Bypass mechanism** (`InvalidateSafeArea` + `InvalidateDescendantSafeAreas`): When `SafeAreaEdges` changes at runtime, explicitly bypasses the Window guard to propagate invalidation to descendants. This handles the case where the guard would incorrectly block legitimate layout updates.

4. **Bug fix**: `MauiScrollView._safeAreaInvalidated = true` → `false` in `ValidateSafeArea()`.

5. **Cache reset** in `MovedToWindow()` ensures new window safe areas are always processed.

The approach is self-aware: the PR includes `safe-area-debugging.instructions.md` documenting the exact failure modes it guards against (overly-aggressive Window-only guard, semantic mismatch in comparisons), with the PR's own code as the "✅ Correct Approach" example.

---

### Try-Fix Summary

5 alternative approaches were explored:

| # | Approach | Result | Key Insight |
|---|----------|--------|-------------|
| 1 | Deferred propagation (DispatchAsync snapshot) | ✅ PASS | Works but introduces async timing sensitivity |
| 2 | Streak counter + EqualsAtPixelLevel | ✅ PASS | Simpler, but streak counter is a heuristic with edge cases |
| 3 | CALayer Transform Detection | ✅ PASS | Only catches transform animations; modified UITest.cs |
| 4 | IView.TranslationX/Y Check | ❌ FAIL | Too narrow — translation may be 0 mid-animation |
| 5 | Epsilon Tolerance (0.5pt fixed) | ✅ PASS | Simplest, but 0.5pt hardcoded threshold may suppress legitimate small changes |
| PR | Dual Window+View guard + EqualsAtPixelLevel | ✅ PASS (Gate) | Most semantically correct; handles TitleBar repositioning edge case |

**Selected: PR's fix** — semantically grounded, handles known edge cases documented in safe-area-debugging.instructions.md, includes the important bug fix.

---

### PR Description & Title Review

**⚠️ Description has significant inaccuracies vs. the actual implementation:**

#### Title Analysis

**Current:** `[iOS] MauiView: Round SafeArea insets to pixels to fix infinite layout cycle`

**Issue:** The title attributes the fix to "rounding to pixels" only, but the primary defense is the **Window+View dual guard** in `SafeAreaInsetsDidChange()`. The rounding (`EqualsAtPixelLevel`) is a secondary defense.

**Suggested:** `[iOS] MauiView/MauiScrollView: Fix infinite layout cycle from animation-induced SafeArea noise`

#### Description Inaccuracies

| Claim in Description | Actual Implementation |
|---------------------|----------------------|
| "we now round the safe area insets to the nearest device pixel using `ContentScaleFactor`" | Uses `UIScreen.MainScreen.Scale`, NOT `ContentScaleFactor`. Also adds Window+View guard (not just rounding). |
| "Used `ContentScaleFactor` instead of `Window.Screen.Scale` for safer access" | Code uses `UIScreen.MainScreen.Scale` — `ContentScaleFactor` is not used anywhere in the fix. |
| "Reverted previous complex fixes (Window guard, isPropagating guard, cycle-break flag)" | The actual code **HAS** a Window guard (`_lastWindowSafeAreaInsets`) combined with a View guard (`_lastViewSafeAreaInsets`). The description is misleading. |

**Recommended description update** (add to "Description of Change" section):

```markdown
### Description of Change

The fix uses a **dual-defense approach** implemented across `MauiView`, `MauiScrollView`, and `SafeAreaPadding`:

**Layer 1 — Source filtering** (`SafeAreaInsetsDidChange`):
- Caches `Window.SafeAreaInsets` (device-level: stable during animations) and view-level `SafeAreaInsets`
- Skips invalidation only when **both** are unchanged — distinguishing animation noise from genuine changes (rotation, keyboard, status bar events)
- The dual check handles repositioning by `WindowViewController` (TitleBar) that changes view insets without changing Window insets

**Layer 2 — Value filtering** (`ValidateSafeArea`):
- New `SafeAreaPadding.EqualsAtPixelLevel()` rounds values to device pixel resolution using `Math.Round(value * UIScreen.MainScreen.Scale, MidpointRounding.AwayFromZero)` before comparing
- Absorbs any sub-pixel noise that survives the source filter

**Bypass mechanism** (`InvalidateSafeArea` + `InvalidateDescendantSafeAreas`):
- When `SafeAreaEdges` changes at runtime, explicitly propagates invalidation to descendants to bypass the Window guard
- Prevents the guard from blocking legitimate layout updates from parent SafeAreaEdges changes

**Bug fix**: `MauiScrollView.ValidateSafeArea()` had `_safeAreaInvalidated = true` instead of `_safeAreaInvalidated = false` — the flag was never cleared after validation.

**Cache reset** in `MovedToWindow()` ensures new-window safe areas are always processed correctly.
```

---

### Code Review Findings

#### 🟡 Minor Concerns

**1. `UIScreen.MainScreen.Scale` vs `ContentScaleFactor` (SafeAreaPadding.cs:44)**

The PR description says `ContentScaleFactor` was used "for safer access," but the code uses `UIScreen.MainScreen.Scale`. For most iOS/macCatalyst scenarios these are equivalent, but on macCatalyst with external displays, `UIScreen.MainScreen.Scale` returns the main display scale while views on external displays may have different scale factors. Using `ContentScaleFactor` (via the view) would be more accurate. This is a low-severity concern but the description/code inconsistency is worth noting.

**2. `InvalidateDescendantSafeAreas` recursive tree walk (ViewHandler.iOS.cs)**

This method is called every time `SafeAreaEdges` changes at runtime. For deeply nested view hierarchies, this recursive walk could be expensive. However, it only triggers on user-driven runtime changes (not during normal rendering), so in practice this is acceptable. No code change needed, just worth being aware of.

**3. `_lastViewSafeAreaInsets` not compared at pixel level**

In `SafeAreaInsetsDidChange()`, the view-level insets are compared with exact equality (`viewInsets == _lastViewSafeAreaInsets`). However, sub-pixel differences in view-level insets should be filtered the same way as value-level differences. In practice, the secondary `EqualsAtPixelLevel` defense in `ValidateSafeArea` handles this, so this isn't a bug — but it could theoretically allow a few extra `_safeAreaInvalidated = true` assignments per animation.

#### ✅ Looks Good

- The dual-level guard correctly handles the TitleBar repositioning edge case documented in `safe-area-debugging.instructions.md`
- `MovedToWindow()` properly resets both cached insets
- `InvalidateSafeArea()` correctly sets `SetNeedsLayout()` to ensure the layout pass runs
- The `_safeAreaInvalidated = false` bug fix in `MauiScrollView` is correct and important
- `IsConnectingHandler()` guard in `MapSafeAreaEdges` prevents unnecessary tree walks during initial connect
- Code comments are thorough and explain the "why" at each decision point
- Documentation added (`safe-area-debugging.instructions.md`) is high quality and correctly identifies the failure modes
- Test coverage is comprehensive: animation freeze, position correctness, runtime toggling, navigation

</details>

</details>

---

</details>



<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

---

<details>

<summary><b>Title: ✅ Good</b></summary>

<br>

**Current:** `[iOS] MauiView: Round SafeArea insets to pixels to fix infinite layout cycle`
</details>

<details>

<summary><b>Description: ✅ Good</b></summary>

<br>

Description needs updates. See details below.
### ✨ Suggested PR Description


> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause

Two separate but related safe area bugs on iOS:

**1. Infinite layout cycle from animation noise (#32586, #33934)**
`TranslateToAsync` animations cause `SafeAreaInsetsDidChange` to fire repeatedly as the view moves relative to the window. These events carry sub-pixel differences (e.g., `0.0000001pt`) in the reported insets. Because `SafeAreaPadding` uses `double` precision, exact equality checks fail even though the physical pixels are identical. This triggers:
1. `InvalidateAncestorsMeasures`
2. Layout pass
3. Position change
4. New `SafeAreaInsetsDidChange`
5. **Infinite loop → app freeze**

**2. Safe area double-application between parent and child (#33595, #34042)**
When a parent `MauiView` already applies safe area padding for an edge, a nested child or `MauiScrollView` could independently apply the same inset, doubling the padding. This caused `MauiScrollView` to crash on navigation with certain layouts (#33595).

### Description of Change

**Fix 1: Pixel-level equality comparison (MauiView.cs, MauiScrollView.cs, SafeAreaPadding.cs)**

Added `SafeAreaPadding.EqualsAtPixelLevel()` which rounds inset values to the nearest device pixel before comparison. Sub-pixel differences from animation noise that map to the same physical pixel are treated as equal, preventing spurious layout invalidations.

Used `UIScreen.MainScreen.Scale` for the rounding factor.

**Fix 2: Parent-child safe area deduplication (MauiView.cs, MauiScrollView.cs)**

Added `IsParentHandlingSafeArea()` to both `MauiView` and `MauiScrollView`. When a parent is already applying safe area adjustments for a given edge, descendants skip applying their own adjustment for that same edge. The `MauiView` implementation is **edge-aware**: a parent handling only `Top` does not suppress a child's `Bottom` handling (required for #28986 parent-child independence test).

Results cached in `_parentHandlesSafeArea` (invalidated on `SafeAreaInsetsDidChange` / `MovedToWindow`).

**Fix 3: Descendant propagation on SafeAreaEdges change (ViewHandler.iOS.cs)**

Extended `MapSafeAreaEdges` with `InvalidateDescendantSafeAreas()` — a recursive walk of the native subview tree that calls `InvalidateSafeArea()` on every descendant `MauiView` and `MauiScrollView`. This ensures that when a parent's `SafeAreaEdges` changes at runtime, descendants re-evaluate their `IsParentHandlingSafeArea()` result. Skipped on initial `ConnectHandler` since children are not yet in the tree.

**Fix 4: MauiScrollView.ValidateSafeArea() logic bugs**

- Fixed inverted condition: `if (!UpdateContentInsetAdjustmentBehavior())` → `if (UpdateContentInsetAdjustmentBehavior())` (method returns `true` when edges changed and invalidation is needed)
- Fixed incorrect cache clear: `_safeAreaInvalidated = true` → `_safeAreaInvalidated = false` after validation (was defeating the cache on every layout pass)

**Reverted:** Previous complex guards (Window-level insets guard, `_isPropagating` flag, cycle-break flag) in favor of the simpler pixel-rounding approach.

### Key Technical Details

**New APIs (internal):**
- `MauiView.AppliesSafeAreaAdjustments` (property) — queried by descendants to detect parent handling
- `MauiView.InvalidateSafeArea()` — triggers safe area re-evaluation on next layout pass
- `MauiScrollView.InvalidateSafeArea()` — same, for scroll views
- `SafeAreaPadding.EqualsAtPixelLevel(SafeAreaPadding)` — pixel-rounded equality

**Edge-aware vs. coarse deduplication:**
- `MauiView.IsParentHandlingSafeArea()` — edge-aware (only blocks matching edges)
- `MauiScrollView.IsParentHandlingSafeArea()` — coarser (any parent applying adjustments suppresses scroll view)

### Issues Fixed
Fixes #32586
Fixes #33934
Fixes #33595
Fixes #34042

### Platforms Tested
- [x] iOS (Validated with new regression tests for all four issues)
- [ ] Android
- [ ] Windows
- [ ] Mac
</details>

<details>

<summary><b>Code Review: ✅ Passed</b></summary>

<br>

# Code Review Findings — PR #34024

## 🟡 Medium Priority Suggestions

---

### Issue 1: `UIScreen.MainScreen.Scale` is not per-view, may mismatch on external displays

**File:** `src/Core/src/Platform/iOS/SafeAreaPadding.cs`

**Code:**
```csharp
public bool EqualsAtPixelLevel(SafeAreaPadding other)
{
    var scale = (double)UIScreen.MainScreen.Scale;
    ...
}
```

**Problem:** `UIScreen.MainScreen` is a static property that returns the device's main screen. If a MAUI app is extended to an external display (Sidecar, Stage Manager with external monitor on iPadOS), the view may actually live on a different screen with a different scale factor. Using `MainScreen.Scale` in that case would round to the wrong pixel grid. Separately, the description claims `ContentScaleFactor` was used specifically for "safer access" — but the implementation does the opposite.

**Recommendation:** Use the view's own `ContentScaleFactor` instead, passed into the method, or use it directly. E.g.:

```csharp
// In ValidateSafeArea (MauiView.cs):
return oldApplyingSafeAreaAdjustments == _appliesSafeAreaAdjustments &&
       (oldSafeArea.EqualsAtPixelLevel(_safeArea, ContentScaleFactor) || !_appliesSafeAreaAdjustments);

// In SafeAreaPadding.cs:
public bool EqualsAtPixelLevel(SafeAreaPadding other, nfloat scale)
{
    var s = (double)scale;
    ...
}
```

**Severity:** Low in practice (external display scenarios are rare on iPhone/iPad), but the description is factually wrong about which API is used, which should be corrected regardless.

---

### Issue 2: `MauiScrollView.IsParentHandlingSafeArea()` is not edge-aware

**File:** `src/Core/src/Platform/iOS/MauiScrollView.cs`

**Code:**
```csharp
bool IsParentHandlingSafeArea()
{
    if (_parentHandlesSafeArea.HasValue)
        return _parentHandlesSafeArea.Value;

    _parentHandlesSafeArea = this.FindParent(x => x is MauiView mv && mv.AppliesSafeAreaAdjustments) is not null;
    return _parentHandlesSafeArea.Value;
}
```

**MauiView's version (for contrast):**
```csharp
// Edge-aware: a parent handling TOP doesn't block child handling BOTTOM
_parentHandlesSafeArea = this.FindParent(x =>
{
    if (x is not MauiView mv || !mv._appliesSafeAreaAdjustments)
        return false;
    for (int edge = 0; edge < 4; edge++)
    {
        if (GetSafeAreaRegionForEdge(edge) != SafeAreaRegions.None &&
            mv.GetSafeAreaRegionForEdge(edge) != SafeAreaRegions.None)
            return true;
    }
    return false;
}) is not null;
```

**Problem:** `MauiView.IsParentHandlingSafeArea()` is edge-aware — a parent that only handles the TOP safe area edge does not suppress a child's handling of the BOTTOM edge (important for issue #28986). But `MauiScrollView.IsParentHandlingSafeArea()` is coarser: if _any_ parent MauiView is applying any safe area adjustments, the `MauiScrollView` suppresses all of its own adjustments regardless of which edges are involved.

This inconsistency could cause `MauiScrollView` to incorrectly suppress its bottom content inset when a parent only handles the top edge (e.g., status bar padding on a page with a ScrollView for the body content). This is a latent bug that may not be triggered by current tests if the common nesting pattern always has full-edge parents.

**Recommendation:** Apply the same edge-aware logic to `MauiScrollView.IsParentHandlingSafeArea()`, or document why coarser behavior is intentional for scroll views.

---

## ✅ Looks Good

- **Pixel-rounding approach** is correct and elegant: `Math.Round(value * scale, MidpointRounding.AwayFromZero)` gives correct ceil-at-half-pixel behavior aligned with UIKit's own rounding convention.
- **Cache invalidation** is done at all the right points: `SafeAreaInsetsDidChange()`, `MovedToWindow()`, and through the new `InvalidateSafeArea()` internal method.
- **`InvalidateDescendantSafeAreas` in ViewHandler.iOS.cs** correctly recurses the full native subview tree and handles the `MauiView`/`MauiScrollView` dichotomy. Skips descendants of already-invalidated views only implicitly, but since they're all invalidated in a single DFS pass, the outcome is correct.
- **`_safeAreaInvalidated = false`** bug fix in `MauiScrollView.ValidateSafeArea()` is correct: the field should be cleared after validation to prevent repeated re-validation on every layout pass.
- **Inverted condition fix** in `MauiScrollView.ValidateSafeArea()` (`if (UpdateContentInsetAdjustmentBehavior())` instead of `if (!...)`) is correct: the method returns `true` when edges changed, in which case we want to invalidate.
- **Guard on `IsConnectingHandler()`** in `MapSafeAreaEdges` is the right optimization: children aren't in the tree yet during initial connect, so propagation is unnecessary and potentially harmful.
- **Tests cover all four fixed issues** (#32586, #33934, #33595, #28986) with meaningful assertions that would fail under the original infinite-loop or crash conditions.
</details>

---

</details>

**Review by kubaflo — DISMISSED** [review]

**Review by kubaflo — APPROVED** [review]
