### PR TITLE
Fix SafeArea adjustments

### LINKED ISSUE #24246: [iOS] SafeArea arrange insets are currently insetting based on an incorrect Bounds
### Description

The problem we found is that the `MauiView` returns a size from `SizeThatFits` that doesn't include the `SafeAreaInsets`. The arrange pass insets its `Bounds` and passes this value to `CrossPlatformArrange` but the `Bounds` being used is the size of the children not including the `SafeAreaInsets` which means the bounds used for arranging is wrong. 

You can see from the screenshots below that the `VSL` surrounding the the entry gets arranged incorrectly

### Comparison

Given the following `XAML`

```XAML
<ContentPage
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Maui.Controls.Sample.MainPage"
    xmlns:local="clr-namespace:Maui.Controls.Sample"
    xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
    ios:Page.UseSafeArea="false"
    >
    <VerticalStackLayout x:Name="layout" Background="Purple" IgnoreSafeArea="False" VerticalOptions="Start" IsClippedToBounds="True" >
        <Entry x:Name="label" Background="Green" Text="Hello there"></Entry>
    </VerticalStackLayout>
</ContentPage>
```

#### Before

image

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

This PR relates to some issues found here https://github.com/dotnet/maui/pull/22476 when trying to layout a Button when it's inside a layout that is partly inside the safearea.

The problem we found is that the `MauiView` returns a size from `SizeThatFits` that doesn't include the `SafeAreaInsets`. The arrange pass insets its `Bounds` and passes this value to `CrossPlatformArrange` but the `Bounds` being used is the size of the children not including the `SafeAreaInsets` which means the bounds used for arranging is wrong. 

You can see from the screenshots below that the `VSL` surrounding the the entry gets arranged incorrectly

### Comparison

Given the following `XAML`

```XAML
<ContentPage
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Maui.Controls.Sample.MainPage"
    xmlns:local="clr-namespace:Maui.Controls.Sample"
    xmlns:ios="clr-namespace:Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;assembly=Microsoft.Maui.Controls"
    ios:Page.UseSafeArea="false"
    >
    <VerticalStackLayout x:Name="layout" Background="Purple" IgnoreSafeArea="False" VerticalOptions="Start" IsClippedToBounds="True" >
        <Entry x:Name="label" Background="Green" Text="Hello there"></Entry>
    </VerticalStackLayout>
</ContentPage>
```

#### Before

image

#### After

image

### Issues Fixed

Fixes #24246

### CODE REVIEW

File: src/Core/src/Platform/iOS/MauiView.cs [hunk 1]
```diff
@@ -122,12 +139,8 @@ public override void LayoutSubviews()
 			var widthConstraint = bounds.Width;
 			var heightConstraint = bounds.Height;
 
-			// If the SuperView is a MauiView (backing a cross-platform ContentView or Layout), then measurement
-			// has already happened via SizeThatFits and doesn't need to be repeated in LayoutSubviews. But we
-			// _do_ need LayoutSubviews to make a measurement pass if the parent is something else (for example,
-			// the window); there's no guarantee that SizeThatFits has been called in that case.
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/MauiView.cs:128]: I'm not able to confirm the accuracy of this statement.

- Currently SizeThatFits doesn't take into account the safearea so the parent SizeThatFits call might possibly being using an inaccurate size measurement
- I realize in this PR I've added a check for safearea inside `SizeThatFits`, but, the SafeAreaInsets aren't set on a UIView until the first time we reach `LayoutSubViews` so, on initial load the `SizeThatFits` calls are going to be using the wrong layout sizing, so, if we get here and the bounds have changed then we need to rerun the measure pass.

Or I'm wrong :-) 

The problem we're seeing is that if you have a layout like this

```XAML
    <HorizontalStackLayout>
        <Button Text="Button with a longer text to test how the truncating works and see if the image is centered" 
                ImageSource="dotnet_bot_resized.png" Background="LightPink"
                ContentLayout="Top, 10" WidthRequest="200"/>
    </HorizontalStackLayout>
```

The SizeThatFits call will use the size of the screen
And then once we hit `LayoutSubViews` the bounds gets set to (screenheight - safearea) and then we don't redo a measure pass. This leads to the Layout doing an arrange on an improper measure

**Review by mattleibow — APPROVED** [review]
I tested a bunch of things, and it seems to work as I would expect.
