### PR TITLE
Fixed the span text disappeared in label when setting the font attribute on span and setting an implicit style for Label on content page

### LINKED ISSUE #19190: [regression/8.0.3] Setting a style on a label causes spans with FontAttributes to be ignored on Android
### Description

Consider this .NET MAUI 8 XAML:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestAndroidSpans.MainPage">
    <ContentPage.Resources>
        <ResourceDictionary>
            <Style TargetType="Label">
                <Setter Property="TextColor" Value="Black"/>
            </Style>
        </ResourceDictionary>
    </ContentPage.Resources>

    <Label HorizontalOptions="CenterAndExpand" TextColor="Gray" >
        <Label.FormattedText>
            <FormattedString>
                <Span Text="{Binding NotBold}"/>
                <Span Text="{Binding Bold}" FontAttributes="Bold" />
            </FormattedString>
        </Label.FormattedText>
    </Label>
</ContentPage>
```

This generates:
Screenshot_1701706257

Notice that the **Bold** span is ignored.

If the Style is removed, everything works as expected:
Screenshot_1701706383

### Steps to Reproduce

Create a new .NET 8 MAUI app and add the above XAML in the MainPage.xaml. Run the app.  Notice the missing *bold* text

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by NanthiniMahalingam**
### Issue details
When setting the FontAttributes in a Span within a Label, and applying an implicit style to the Label (without specifying the FontSize in the style) from the ContentPage resources, while a global default style for label font size is defined in App.xaml, the default font is not applied correctly. Therefore span text disappeared.

### Root cause
When setting FontAttributes in a Span within a Label, and applying an implicit style to the Label (without specifying the FontSize) from the ContentPage resources, while a global default style for label font size is defined in App.xaml, the default font is not applied because the implicit style does not explicitly define default FontSize.

### Description changes
I retrieved the font size using FontManager.GetFontSize() instead of relying on the default font size from the Label, since font.IsDefault is false when setting FontAttributes in a Span within a Label.

Validated the behaviour in the following platforms
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Reference
https://github.com/dotnet/maui/blob/af78f88526422a6d3415fa7d338736ec38345f17/src/Controls/src/Core/Platform/iOS/Extensions/FormattedStringExtensions.cs#L107

### Test Case
The issue raises when adding the font size style globally in the application's resource file. As a result, I was unable to apply the global style in the host app, and I couldn't find any reference for applying the style globally.

### Issues Fixed

Fixes #19190

### Output images:

| Before  | After  |
|---------|--------|
| |  |

### CODE REVIEW

File: src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs [hunk 1]
```diff
@@ -116,7 +116,7 @@ internal static SpannableString ToSpannableStringNewWay(
 				if (font.IsDefault && defaultFont.HasValue)
 					font = defaultFont.Value;
 				if (!font.IsDefault)
-					spannable.SetSpan(new PlatformFontSpan(context ?? AAplication.Context, font.ToTypeface(fontManager), font.AutoScalingEnabled, (float)font.Size), start, end, SpanTypes.InclusiveInclusive);
+					spannable.SetSpan(new PlatformFontSpan(context ?? AAplication.Context, font.ToTypeface(fontManager), font.AutoScalingEnabled, (float)fontManager.GetFontSize(font).Value), start, end, SpanTypes.InclusiveInclusive);
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs:119]: Could you include a related test?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

**Review by jsuarezruiz — APPROVED** [review]
