### PR TITLE
Fix for Handler not disconnected when removing a non-visible page from the navigation stack

### LINKED ISSUE #29923: Removing page from navigation stack that is not the currently displayed page does not disconnect its handler
### Description

Maybe this is the expected outcome, however, I believe it makes more sense that the framework disconnects the page's handler even though it is not currently displayed, to avoid memory leaks and consistency. 

> Only tested on iOS and Android. 

Image

### Steps to Reproduce

1. Clone https://github.com/Vetle444/MauiTestApp/tree/removePageHandler/MauiTestApp
2. Run app
3. Click either "Test Page Modal" or "Test Page" button
4. Navigate to next page
5. Click "Remove test page 1"
6. Observe that no dialog appears saying that the Handler of Test Page 1 is disconnected.
7. If you do a normal back navigation from Test Page 1, the handler is disconnected, as expected.

### Link to public reproduction project repository

https://github.com/Vetle444/MauiTestApp/tree/removePageHandler/MauiTestApp

### Version with bug

9.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

_No response_

### Did you find any workaround?

Disconnect handler manually

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by praveenkumarkarunanithi**
### Root Cause
When `Navigation.RemovePage()` is used to remove a page from the navigation stack, the handler associated with the removed page is not disconnected. In contrast, methods like `PopAsync()` or `PopModalAsync()` trigger proper cleanup, including handler disconnection.

The `RemovePage()` method modifies the navigation stack without initiating any disposal or disconnection logic for the page's handler. As a result, the Handler property of the removed page remains assigned after removal, which can retain references to platform-specific resources.

Platform implementations do not consistently handle this scenario. On iOS, handler disconnection occur through `ShellSectionRenderer.DisposePage()` for some scenarios only, but this is not invoked as part of `RemovePage()`. On Android and Windows, no corresponding cleanup is performed when removing a page in this way.
 
### Description of Change
This change ensures that when a page is removed from the navigation stack using `RemovePage()`—and the page is not currently visible—its handler is properly disconnected. The fix is implemented in `NavigationProxy.OnRemovePage()`, which provides a centralized and platform-agnostic location for handling page removal. This approach ensures consistent behavior across iOS, Android, and Windows, and correctly manages the page lifecycle by disconnecting the handler at the appropriate time.
 
### Issues Fixed
Fixes #29923 
 
Tested the behaviour in the following platforms
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac
### Screenshots
| Before Issue Fix | After Issue Fix |
|------------------|-----------------|
| <video width="350" alt="withoutfix" src="https://github.com/user-attachments/assets/a53bd18c-dfe7-4d2e-ab62-e7d6b3deff96" /> | <video width="350" alt="withfix" src="https://github.com/user-attachments/assets/30a86e1a-b15d-4802-bab2-8bd7b45bba1c" /> |

### CODE REVIEW

File: src/Controls/src/Core/NavigationProxy.cs [hunk 1]
```diff
@@ -244,6 +244,7 @@ protected virtual void OnRemovePage(Page page)
 			{
 				currentInner.RemovePage(page);
 			}
+			page?.Handler?.DisconnectHandler();
```
Comment (bhavanesh2001) [inline src/Controls/src/Core/NavigationProxy.cs]:
```suggestion
			page?.DisconnectHandlers();
```
Can we call `DisconnectHandlers()` ?, since It walks the visual tree and disconnects all handlers properly.

Comment (praveenkumarkarunanithi) [reply src/Controls/src/Core/NavigationProxy.cs]: yes @bhavanesh2001 , I have updated the fix to use `page?.DisconnectHandlers()` as recommended. I have verified that this approach works correctly across all navigation scenarios and platforms.

**Review by jsuarezruiz — APPROVED** [review]
