### PR TITLE
[Android, iOS] Fix for the Resize method does not dispose the original image, even when disposeOriginal is set to true

### LINKED ISSUE #21886: Multiple bugs in Microsoft.Maui.Graphics.IImage platform specific implementations
### Description

While Prototyping some ImageZoom I was playing around with IImage.Resize and IImage.Downsize on iOS and Android and Windows.

1.  Call to Resize 
`Resize(10, 10, ResizeMode.Fit,true)`

- On Android it returns a Disposed image and original is not disposed.
- On iOS it gives an image but original is not disposed
- On Windows it throws not implemented exception

2.  `image.Downsize(10, 10,true)`

- On Android it gives me an 10 by 10 px image. So it is not keeping the aspect like the call to image.Downsize(10,true)` original image gets disposed

- On iOS original image gets  not disposed returned image is 10 by 7 so it keeps the Aspect somehow. But from my own calculations it should be 10 by 6,15 so here could be a rounding issue?

- On Windows it throws not implemented exception

So [docs ](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/images?view=net-maui-8.0) are wrong and code is just not working.

### Steps to Reproduce

1. Checkout repro
2. Click the Buttons
3. Read the Popups if it does not crash

### Link to public reproduction project repository

https://github.com/Larhei/Maui-Issues/tree/main/PlatformImage

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

_No response_

### Did you find any workaround?

No... Will be a happy coding day for me to implement it by myself.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SyedAbdulAzeemSF4852**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue Details

-  Issue 1 : On both Android and iOS, the Resize method does not dispose of the original image, even when disposeOriginal is set to true.

### Root Cause

- Android, iOS : The original image was not being explicitly disposed, even when the disposeOriginal flag was set to true.

### Description of Change

- Android - Updated the Width and Height properties to handle null _bitmap values gracefully and added logic to dispose of the original image in the Resize method when disposeOriginal is set to true.
- iOS - Added logic to dispose of the original image in the Resize method when disposeOriginal is set to true.

### Issues Fixed
Fixes #21886 (1st issue)

### Validated the behaviour in the following platforms

- [x] Windows
- [x] Android
- [x] iOS
- [x] Mac

### Output
| Platform | Before Fix | After Fix |
|----------|----------|----------|
| Android | <video src="https://github.com/user-attachments/assets/ad4b01a7-4fcd-484d-aafb-b947fab64a31"> | <video src="https://github.com/user-attachments/assets/9e88fa16-2751-4553-aefc-f29f81753d63"> |
|iOS | <video src="https://github.com/user-attachments/assets/2555e0d0-91f4-4ca7-a2d1-c1b5eb46eb28"> | <video src="https://github.com/user-attachments/assets/4081dc10-ba59-4950-be5a-c0e9a6708d35"> |

### CODE REVIEW

File: src/Graphics/src/Graphics/Platforms/iOS/PlatformImage.cs [hunk 1]
```diff
@@ -84,6 +84,12 @@ public IImage Resize(float width, float height, ResizeMode resizeMode = ResizeMo
 				}
 
 				context.Canvas.DrawImage(this, x, y, w, h);
+
+				if (disposeOriginal)
```
Comment (jsuarezruiz) [inline src/Graphics/src/Graphics/Platforms/iOS/PlatformImage.cs:88]: Not required on Windows?

Comment (SyedAbdulAzeemSF4852) [reply src/Graphics/src/Graphics/Platforms/iOS/PlatformImage.cs:88]: @jsuarezruiz , On Windows, the Resize method is currently not implemented. This [PR](https://github.com/dotnet/maui/pull/29138) adds implementations for both the Resize and Downsize methods. After this PR is merged, the Resize method will correctly dispose of the original image when disposeOriginal is set to true.

**Review by jsuarezruiz — APPROVED** [review]
