### PR TITLE
[Android] Fix Flickering issue when calling Navigation.PopAsync

### LINKED ISSUE #13810: Flickering when calling Navigation.PopAsync(false).
### Discussed in https://github.com/dotnet/maui/discussions/13809

<div type='discussions-op-text'>

<sup>Originally posted by **cat0363** March 10, 2023</sup>
The layout of the page is as follows.
Page1 layout:

    <ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                 x:Class="NavigationTest.Page1" 
                 NavigationPage.HasNavigationBar="False" BackgroundColor="Red">  
        <Grid RowDefinitions="44,44,44,44,44,44,*" RowSpacing="0">
            <Button Grid.Row="0" Text="Next" BackgroundColor="Blue" TextColor="White" Clicked="Button_Clicked" />
            <Button Grid.Row="1" Text="Next" BackgroundColor="Blue" TextColor="White" Clicked="Button_Clicked" />
            <Button Grid.Row="2" Text="Next" BackgroundColor="Blue" TextColor="White" Clicked="Button_Clicked" />
            <Button Grid.Row="3" Text="Next" BackgroundColor="Blue" TextColor="White" Clicked="Button_Clicked" />
            <Button Grid.Row="4" Text="Next" BackgroundColor="Blue" TextColor="White" Clicked="Button_Clicked" />
            <Button Grid.Row="5" Text="Next" BackgroundColor="Blue" TextColor="White" Clicked="Button_Clicked" />
        </Grid>
    </ContentPage>

Page2 layout:

    <ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                 x:Class="NavigationTest.Page2"
                 NavigationPage.HasNavigationBar="False" BackgroundColor="White">   
        <Grid RowDefinitions="44,44,44,44,44,44,*" RowSpacing="0">
            <Button Grid.Row="0" Text="Back" BackgroundColor="Blue" TextColor="White" Clicked="Button_Clicked" />
            <Button Grid.Row="1" Text="Back" BackgroundColor="Blue" TextColor="White" Clicked="Button_Clicked" />
            <Button Grid.Row="2" Text="Back" BackgroundColor="Blue" TextColor="White" Clicked="Button_Clicked" />
            <Button Grid.Row="3" Text="Back" BackgroundColor="Blue" TextColor="White" Clicked="Button_Clicked" />
            <Button Grid.Row="4" Text="Back" BackgroundColor="Blue" TextColor="White" Clicked="Button_Clicked" />
            <Button Grid.Row="5" Text="Back" BackgroundColor="Blue" TextColor="White" Clicked="Button_Clicked" />
        </Grid>
    </ContentPage>

Button_Click event on Page1:

    private async void Button_Clicked(object sender, EventArgs e) 
    {
		await Navigation.PushAsync(new Page2(), false);
    }

Button_Click event on Page2:

    private async void Button_Clicked(object sender, EventArgs e) 
    {
        await Navigation.PopAsync(false);
    }

After using NavigationPage to transition from Page1 to Page2, return from Page2 to Page1.
Flickering occurs when returning from Page2 to Page1.

I tried transitioning using the same layout in Xamarin.Forms and .NET MAUI.
The video was tested on Android.
(As for iOS, the build environment has not been prepared, so it cannot be verified.)

[Xamarin.Forms]

https://user-images.githubusercontent.com/125236133/224205354-5d3d65be-7f40-4bbc-88e3-e0ea27ed73c7.mp4

[.NET MAUI]

https://user-images.githubusercontent.com/125236133/224205389-cf666a1a-59b2-47dc-8702-a4788f2a2bee.mp4

No flickering in Xamarin.Forms but flickering in .NET MAUI.

This flickering makes users feel uncomfortable.
I would like to reduce this flickering if possible.
Any good ideas? Thank you.</div>

### PR DESCRIPTION
**Pull request by devanathan-vaithiyanathan**
### Root Cause
The flickering during navigation occurred because, when performing PopAsync, the removed page’s handlers were set to null. This caused flickering as the navigation was processed.

### Description of Change

The fix involves avoiding the removal of page handlers during PopAsync, which eliminates the flickering issue during navigation.

### Issues Fixed

Fixes #13810

### Validated the behaviour in the following platforms
 
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Output Screenshot

**Before**

https://github.com/user-attachments/assets/d61c8903-d495-41bf-8ba6-3a4a0a5e716f

**After**

https://github.com/user-attachments/assets/1bba47ff-d1fd-4f4b-b740-9e1bd3ea00b3

### CODE REVIEW

**Review by rmarinho — APPROVED** [review]

**Comment by rmarinho** [comment]
Seems is making the windows tests fail , I run few times

**Review by rmarinho — DISMISSED** [review]
Seems is making the Windows Device tests fail , I run few times and got same results. Maybe this is causing some side effects on Windows.  But maybe also rebase just to make sure branch is updated with latest .

**Review by PureWeen — CHANGES_REQUESTED** [review]
It looks like the device tests on windows are crashing. 

On CI you can check the logs here to see where it's crashing

image

**Comment by devanathan-vaithiyanathan** [comment]
> > It looks like the device tests on windows are crashing.
> > On CI you can check the logs here to see where it's crashing
> > image
> 
> This is the failing test **NavigatedFiresAfterSwitchingFlyoutItems**.
> 
> ```
> at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
>    at ABI.Microsoft.UI.Xaml.Controls.IContentPresenterMethods.set_Content(IObjectReference _obj, Object value)
>    at Microsoft.UI.Xaml.Controls.ContentPresenter.set_Content(Object value)
>    at Microsoft.Maui.Platform.StackNavigationManager.OnNavigated(Object sender, NavigationEventArgs e)
>    at WinRT._EventSource_global__Microsoft_UI_Xaml_Navigation_NavigatedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, NavigationEventArgs e)
>    at ABI.Microsoft.UI.Xaml.Navigation.NavigatedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
> --- End of stack trace from previous location ---
>    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
>    at ABI.Microsoft.UI.Xaml.Controls.IFrameMethods.GoBack(IObjectReference _obj, NavigationTransitionInfo transitionInfoOverride)
>    at Microsoft.UI.Xaml.Controls.Frame.GoBack(NavigationTransitionInfo transitionInfoOverride)
>    at Microsoft.Maui.Platform.StackNavigationManager.NavigateTo(NavigationRequest args)
>    at Microsoft.Maui.Controls.Handlers.ShellSectionHandler.RequestNavigation(ShellSectionHandler handler, IStackNavigation view, Object arg3)
>    at Microsoft.Maui.CommandMapper`2.<>c__DisplayClass6_0.<Add>b__0(IElementHandler h, IElement v, Object o)
>    at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args)
>    at Microsoft.Maui.CommandMapper.Invoke(IElementHandler viewHandler, IElement virtualView, String property, Object args)
>    at Microsoft.Maui.Handlers.ElementHandler.Invoke(String command, Object args)
>    at Microsoft.Maui.Controls.ShellSection.Microsoft.Maui.IStackNavigation.RequestNavigation(NavigationRequest eventArgs)
>    at Microsoft.Maui.Controls.Handlers.ShellSectionHandler.SyncNavigationStack(Boolean animated, NavigationRequestedEventArgs e)
>    at Microsoft.Maui.Controls.Handlers.ShellSectionHandler.OnNavigationRequested(Object sender, NavigationRequestedEventArgs e)
>    at Microsoft.Maui.Controls.ShellSection.InvokeNavigationRequest(NavigationRequestedEventArgs args)
>    at Microsoft.Maui.Controls.ShellSection.OnPopAsync(Boolean animated)
>    at Microsoft.Maui.Controls.ShellSection.GoToAsync(ShellNavigationRequest request, ShellRouteParameters queryData, IServiceProvider services, Nullable`1 animate, Boolean isRelativePopping)
>    at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass3_0.<<DispatchAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass2_0`1.<<DispatchAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest)
>    at Microsoft.Maui.DeviceTests.ShellTests.<>c__DisplayClass32_0.<<NavigatedFiresAfterSwitchingFlyoutItems>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.Maui.DeviceTests.ControlsHandlerTestBase.<>c__DisplayClass16_1`1.<<CreateHandlerAndAddToWindow>b__1>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.Maui.DeviceTests.ControlsHandlerTestBase.<>c__DisplayClass30_0`1.<<SetupWindowForTests>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.Maui.DeviceTests.ControlsHandlerTestBase.<>c__DisplayClass30_0`1.<<SetupWindowForTests>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass3_0.<<DispatchAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass2_0`1.<<DispatchAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Microsoft.Maui.DeviceTests.ControlsHandlerTestBase.<>c__DisplayClass16_0`1.<<CreateHandlerAndAddToWindow>
> ```

We'll run the DeviceTests using NET9 and provide an update.

**Comment by jfversluis** [comment]
@ygl-rg I think at this point with .NET 9 being close to being released this will be .NET 9 only

**Comment by devanathan-vaithiyanathan** [comment]
> > > It looks like the device tests on windows are crashing.
> > > On CI you can check the logs here to see where it's crashing
> > > image
> > 
> > 
> > This is the failing test **NavigatedFiresAfterSwitchingFlyoutItems**.
> > ```
> > at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
> >    at ABI.Microsoft.UI.Xaml.Controls.IContentPresenterMethods.set_Content(IObjectReference _obj, Object value)
> >    at Microsoft.UI.Xaml.Controls.ContentPresenter.set_Content(Object value)
> >    at Microsoft.Maui.Platform.StackNavigationManager.OnNavigated(Object sender, NavigationEventArgs e)
> >    at WinRT._EventSource_global__Microsoft_UI_Xaml_Navigation_NavigatedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, NavigationEventArgs e)
> >    at ABI.Microsoft.UI.Xaml.Navigation.NavigatedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
> > --- End of stack trace from previous location ---
> >    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
> >    at ABI.Microsoft.UI.Xaml.Controls.IFrameMethods.GoBack(IObjectReference _obj, NavigationTransitionInfo transitionInfoOverride)
> >    at Microsoft.UI.Xaml.Controls.Frame.GoBack(NavigationTransitionInfo transitionInfoOverride)
> >    at Microsoft.Maui.Platform.StackNavigationManager.NavigateTo(NavigationRequest args)
> >    at Microsoft.Maui.Controls.Handlers.ShellSectionHandler.RequestNavigation(ShellSectionHandler handler, IStackNavigation view, Object arg3)
> >    at Microsoft.Maui.CommandMapper`2.<>c__DisplayClass6_0.<Add>b__0(IElementHandler h, IElement v, Object o)
> >    at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args)
> >    at Microsoft.Maui.CommandMapper.Invoke(IElementHandler viewHandler, IElement virtualView, String property, Object args)
> >    at Microsoft.Maui.Handlers.ElementHandler.Invoke(String command, Object args)
> >    at Microsoft.Maui.Controls.ShellSection.Microsoft.Maui.IStackNavigation.RequestNavigation(NavigationRequest eventArgs)
> >    at Microsoft.Maui.Controls.Handlers.ShellSectionHandler.SyncNavigationStack(Boolean animated, NavigationRequestedEventArgs e)
> >    at Microsoft.Maui.Controls.Handlers.ShellSectionHandler.OnNavigationRequested(Object sender, NavigationRequestedEventArgs e)
> >    at Microsoft.Maui.Controls.ShellSection.InvokeNavigationRequest(NavigationRequestedEventArgs args)
> >    at Microsoft.Maui.Controls.ShellSection.OnPopAsync(Boolean animated)
> >    at Microsoft.Maui.Controls.ShellSection.GoToAsync(ShellNavigationRequest request, ShellRouteParameters queryData, IServiceProvider services, Nullable`1 animate, Boolean isRelativePopping)
> >    at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass3_0.<<DispatchAsync>b__0>d.MoveNext()
> > --- End of stack trace from previous location ---
> >    at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass2_0`1.<<DispatchAsync>b__0>d.MoveNext()
> > --- End of stack trace from previous location ---
> >    at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest)
> >    at Microsoft.Maui.DeviceTests.ShellTests.<>c__DisplayClass32_0.<<NavigatedFiresAfterSwitchingFlyoutItems>b__0>d.MoveNext()
> > --- End of stack trace from previous location ---
> >    at Microsoft.Maui.DeviceTests.ControlsHandlerTestBase.<>c__DisplayClass16_1`1.<<CreateHandlerAndAddToWindow>b__1>d.MoveNext()
> > --- End of stack trace from previous location ---
> >    at Microsoft.Maui.DeviceTests.ControlsHandlerTestBase.<>c__DisplayClass30_0`1.<<SetupWindowForTests>b__0>d.MoveNext()
> > --- End of stack trace from previous location ---
> >    at Microsoft.Maui.DeviceTests.ControlsHandlerTestBase.<>c__DisplayClass30_0`1.<<SetupWindowForTests>b__0>d.MoveNext()
> > --- End of stack trace from previous location ---
> >    at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass3_0.<<DispatchAsync>b__0>d.MoveNext()
> > --- End of stack trace from previous location ---
> >    at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass2_0`1.<<DispatchAsync>b__0>d.MoveNext()
> > --- End of stack trace from previous location ---
> >    at Microsoft.Maui.DeviceTests.ControlsHandlerTestBase.<>c__DisplayClass16_0`1.<<CreateHandlerAndAddToWindow>
> > ```
> 
> We'll run the DeviceTests using NET9 and provide an update.

I ran the device tests using the latest MAUI source with our fix and confirmed that the mentioned test passed successfully. Let me know if you have any concerns.

**Review by jsuarezruiz — COMMENTED** [review]
There is a device test failing related with pop navigating.
image

**Review by jsuarezruiz — DISMISSED** [review]
Could review the failing test?

**Comment by devanathan-vaithiyanathan** [comment]
> Could review the failing test?

I reviewed the failing test case by running it on our machine, and it seems to be running fine.

**Review by PureWeen — CHANGES_REQUESTED** [review]
Can you move the `PoppingFlyoutPageDoesntCrash` test to Appium from the Device Tests?

**Comment by Vignesh-SF3580** [comment]
> Can you move the `PoppingFlyoutPageDoesntCrash` test to Appium from the Device Tests?

I have moved the specified test case to Appium. Could you please review it and let me know if you have any concerns?

File: src/Controls/tests/DeviceTests/Elements/FlyoutPage/FlyoutPageTests.cs [hunk 1]
```diff
@@ -46,25 +46,6 @@ void SetupBuilder()
 			});
 		}
 
-		[Theory]
-		[ClassData(typeof(FlyoutPageLayoutBehaviorTestCases))]
```
Comment (PureWeen) [inline src/Controls/tests/DeviceTests/Elements/FlyoutPage/FlyoutPageTests.cs:50]: This test has two different cases that need to be captured in the UITest

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue10274.cs [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+		public void FlyoutPageNavigation()
+		{
+			App.WaitForElement("button");
+			App.Tap("button");
+
+			App.WaitForElement("flyoutPageButton");
+			App.Tap("flyoutPageButton");
+
+			App.WaitForElement("button");
+			VerifyScreenshot();
```
Comment (PureWeen) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue10274.cs:27]: Since the test is just validating if it crashes we don't need to Verify the screen shot

We can just wait for any element on the screen to verify the app hasn't crashed

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/tests/DeviceTests/Elements/FlyoutPage/FlyoutPageTests.cs (hunk 1 above)
Comment (Vignesh-SF3580) [reply src/Controls/tests/DeviceTests/Elements/FlyoutPage/FlyoutPageTests.cs:50]: In the test case `PoppingFlyoutPageDoesntCrash`, the flow involves navigating to the FlyoutPage using PushAsync and then returning to the previous page using PopAsync. Both Push and Pop scenarios have been addressed in the updated test cases. Could you please review the changes and let me know if you have any concerns?

**Review by PureWeen — APPROVED** [review]

File: src/Controls/src/Core/NavigationPage/NavigationPage.cs [hunk 3]
```diff
@@ -402,9 +402,6 @@ void FireAppearing(Page page)
 		void RemoveFromInnerChildren(Element page)
 		{
 			InternalChildren.Remove(page);
-
-			// TODO For NET9 we should remove this because the DisconnectHandlers will take care of it
-			page.Handler = null;
```
Comment (PureWeen) [inline src/Controls/src/Core/NavigationPage/NavigationPage.cs:407]: It looks like this change is causing the winui device tests to crash. 

you can download the crash dump from the artifacts and analyze it inside VS to see the exception. 

image

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/NavigationPage/NavigationPage.cs (hunk 3 above)
Comment (kubaflo) [reply src/Controls/src/Core/NavigationPage/NavigationPage.cs:407]: Hi! @devanathan-vaithiyanathan can you please fix it? It is an annoying bug that would be great to have fixed as soon as possible. I can help you if you want :)

Comment (Vignesh-SF3580) [reply src/Controls/src/Core/NavigationPage/NavigationPage.cs:407]: @PureWeen I have updated the code to include null checks for MauiContext to address the WinUI device test crashes. Could you please review the changes and let me know if you have any further concerns?

File: src/Controls/src/Core/TabbedPage/TabbedPage.Windows.cs [hunk 4]
```diff
@@ -19,7 +19,7 @@ public partial class TabbedPage
 		WFrame? _navigationFrame;
 		bool _connectedToHandler;
 		WFrame NavigationFrame => _navigationFrame ?? throw new ArgumentNullException(nameof(NavigationFrame));
-		IMauiContext MauiContext => this.Handler?.MauiContext ?? throw new InvalidOperationException("MauiContext cannot be null here");
+		IMauiContext? MauiContext => this.Handler?.MauiContext;
```
Comment (PureWeen) [inline src/Controls/src/Core/TabbedPage/TabbedPage.Windows.cs:22]: I think we want to leave the exception

Can you just add a method to check nullability? 

bool HasHandler => this.Handler?.MauiContext is not null

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/TabbedPage/TabbedPage.Windows.cs (hunk 4 above)
Comment (Vignesh-SF3580) [reply src/Controls/src/Core/TabbedPage/TabbedPage.Windows.cs:22]: @PureWeen MauiContext reference is used in multiple places in this file, and I have ensured that null checks are added to prevent exceptions. Do we need to assign this.Handler?.MauiContext based on HasHandler in each place?

Comment (PureWeen) [reply src/Controls/src/Core/TabbedPage/TabbedPage.Windows.cs:22]: I think we need to take a different approach here. 

we should be no longer listening to the SelectionChanged event after the handler is disconnected but it looks like we are

image

Can we try to figure out here why the subscription still exists after disconnect is called?

Comment (Vignesh-SF3580) [reply src/Controls/src/Core/TabbedPage/TabbedPage.Windows.cs]: @PureWeen Upon checking further, the SelectionChanged event was unhooked properly during navigation, but the _navigationFrame.Navigated event was not. Since I am unable to reproduce the exact crash, based on the call stack from the dump files, I suspect that the issue occurs because the Navigated event was not unhooked properly. I have now unhooked the Navigated event correctly. If the Navigated event is properly unhooked during the disconnect handling, it will prevent the UpdateCurrentPageContent method from being called, even when triggered from the selection changing event. Could you please review and share your concerns?

**Review by PureWeen — APPROVED** [review]
Love it!!! Thank you
