### PR TITLE
[Android] Allow to update Entry Background (once established)

### LINKED ISSUE #12212: [Android] Cannot update the Entry Background once established
### Description

Cannot update the Entry Background once established on Android.
en38

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/dotnet-maui-testing-playground
2. Launch the App on Android or Windows.
3. Navigate to the Entry tests.
4. Check the En38 test case.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/dotnet-maui-testing-playground

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #12991: Entry Background Color not Changed when using inside the styles in MainPage.xaml
### Description

 **In Focused state ,Entry Bakcground color not Works  when focusing the entry**

1) Created a class inherited from entry and Assign a BackgroundColor Value in the Constructor.
2) Then , assigned a background Color value inside the styles of VisualStateManager **Focused State**

### Steps to Reproduce

Github Repo link is attached . please kindly check to reproduce the issue.

### Link to public reproduction project repository

https://github.com/Ahamed-Ali/Entry

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Android 9

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #14600: The background color of Entry cannot be switched in the Normal and Focus states.
### Description

If we set the `BackgroundColor` of Entry both on normal and focus status, the BackgroundColor of Entry on `normal` status will replace the color on focus status while the Entry get the focus.

And if we remove the `BackgroundColor` of Entry on normal and set the `BackgroundColor` of Entry on focus status, the  `BackgroundColor` of Entry on focus status will display normally , but after the entry lose focus, the `BackgroundColor` of Entry  is still the color in focus. 

### Steps to Reproduce

1.create a new maui app
2.add the following code to `MainPage.xaml`:

    <StackLayout> 
        <StackLayout.Resources>
            <Style TargetType="Entry">
                <Setter Property="Margin"
                        Value="20, 0" />
                <Setter Property="FontSize"
                        Value="18" />
                <Setter Property="VisualStateManager.VisualStateGroups">
                    <VisualStateGroupList>
                        <VisualStateGroup x:Name="CommonStates">
                            <VisualState x:Name="Normal">
                                
                            </VisualState>
                            <VisualState x:Name="Focused">
                                <VisualState.Setters>
                                    <Setter Property="FontSize"
                                            Value="36" />
                                    <Setter Property="BackgroundColor"
                                            Value="Red" />
                                </VisualState.Setters>
                            </VisualState>
                            <VisualState x:Name="Disabled">
                                <VisualState.Setters>
                                    <Setter Property="BackgroundColor"
                                            Value="Pink" />
                                </VisualState.Setters>
                            </VisualState>
                        </VisualStateGroup>
                    </VisualStateGroupList>
                </Setter>
            </Style>

        </StackLayout.Resources>

        <Label Text="Normal Entry" />
        <Entry />

        <Button Text="test" WidthRequest="200" HorizontalOptions="CenterAndExpand" Margin="20"/>
       
    </StackLayout>

### Link to public reproduction project repository

https://github.com/dotnet/maui/issues/new?assignees=&labels=t%2Fbug&template=bug-report.yml

### Version with bug

6.0.312

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

android 10

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Allow to update Entry Background.

fix-12212

Captura de pantalla 2022-12-20 a las 14 12 46

### Issues Fixed

Fixes #12212 
Fixes #12991
Fixes #14600

### CODE REVIEW

File: src/Core/src/Platform/Android/ViewExtensions.cs [hunk 1]
```diff
@@ -190,9 +190,14 @@ internal static void UpdateBackground(this EditText platformView, IView view)
...
-			var previousDrawable = platformView.Background;
+			if(platformView.Background is LayerDrawable layerDrawable)
+			{
+				platformView.Background = null;
+				layerDrawable.Dispose();
+			}
+
 			var backgroundDrawable = paint!.ToDrawable(platformView.Context);
-			LayerDrawable layer = new LayerDrawable(new Drawable[] { backgroundDrawable!, previousDrawable! });
+			LayerDrawable layer = new LayerDrawable(new Drawable[] { backgroundDrawable!, defaultBackground! });
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/ViewExtensions.cs:200]: Can we pull this background from android resources? This same update method is called by all the picker handlers and the searchbox as well. If we can localize all of this to the extension method and just load this drawable from the android resources then this would all just work and it'd be theme change safe.

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Android/ViewExtensions.cs (hunk 1 above)
Comment (PureWeen) [reply src/Core/src/Platform/Android/ViewExtensions.cs:200]: I think we can pull the drawable for this from this

`ContextCompat.GetDrawable(Context, Resource.Drawable.abc_edit_text_material);`

https://stackoverflow.com/a/62015982

**Comment by jsuarezruiz** [comment]
Added more samples to validate #12991
fix-12991

File: src/Core/src/Platform/Android/ViewExtensions.cs (hunk 1 above)
Comment (PureWeen) [reply src/Core/src/Platform/Android/ViewExtensions.cs:202]: Can we pull this background from android resources? This same update method is called by all the picker handlers and the searchbox as well. If we can localize all of this to the extension method and just load this drawable from the android resources then this would all just work and it'd be theme change safe.

I think we can pull the drawable for this from this

`ContextCompat.GetDrawable(Context, Resource.Drawable.abc_edit_text_material);`

https://stackoverflow.com/a/62015982

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/samples/Controls.Sample/Pages/Controls/EntryPage.xaml.cs [hunk 2]
```diff
@@ -19,9 +20,10 @@ public EntryPage()
 			sldCursorPosition.Maximum = entryCursor.Text.Length;
 			sldCursorPosition.Value = entryCursor.CursorPosition;
 
-
```
Comment (mandel-macaque) [inline src/Controls/samples/Controls.Sample/Pages/Controls/EntryPage.xaml.cs:22]: Keep the diff to the min ;)

File: src/Core/src/Handlers/DatePicker/DatePickerHandler.Android.cs [hunk 3]
```diff
@@ -59,8 +64,11 @@ protected override void DisconnectHandler(MauiDatePicker platformView)
 
 			platformView.ViewAttachedToWindow -= OnViewAttachedToWindow;
 			platformView.ViewDetachedFromWindow -= OnViewDetachedFromWindow;
+
```
Comment (mandel-macaque) [inline src/Core/src/Handlers/DatePicker/DatePickerHandler.Android.cs:67]: Keep the diff to the min ;) 
```suggestion
```

File: src/Core/src/Platform/Android/ViewExtensions.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (mandel-macaque) [reply src/Core/src/Platform/Android/ViewExtensions.cs:202]: Try to avoid the use of !, are we sure this is not null, better wrap on an if that an NRE. What happens is null? do we need the new layer, do we exit the method? Do we create a new later with no drawable contents?

**Review by mandel-macaque — CHANGES_REQUESTED** [review]
Answers needed.

**Review by mandel-macaque — APPROVED** [review]

**Comment by jsuarezruiz** [comment]
Hey @PureWeen, have been refactoring and applying changes to use `Resource.Drawable.abc_edit_text_material` as default value. Could you review it again?. Thanks!

File: src/Core/src/Platform/Android/ViewExtensions.cs [hunk 4]
```diff
@@ -176,31 +176,43 @@ public static void UpdateBackground(this ContentViewGroup platformView, IBorderS
...
-			var previousDrawable = platformView.Background;
-			var backgroundDrawable = paint!.ToDrawable(platformView.Context);
-			LayerDrawable layer = new LayerDrawable(new Drawable[] { backgroundDrawable!, previousDrawable! });
-			platformView.Background = layer;
+			var paint = view.Background;
+
+			Drawable? defaultBackgroundDrawable = null;
+
+			if (platformView.Context != null)
+				defaultBackgroundDrawable = ContextCompat.GetDrawable(platformView.Context, Resource.Drawable.abc_edit_text_material);
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/ViewExtensions.cs:204]: @PureWeen Here we get the default background value.

File: src/Core/src/Handlers/DatePicker/DatePickerHandler.Android.cs [hunk 5]
```diff
@@ -30,6 +31,7 @@ protected override MauiDatePicker CreatePlatformView()
 		protected override void ConnectHandler(MauiDatePicker platformView)
 		{
 			base.ConnectHandler(platformView);
+
```
Comment (PureWeen) [inline src/Core/src/Handlers/DatePicker/DatePickerHandler.Android.cs:34]: Because this file doesn't have any functional changes can we leave this file unchanged?

File: src/Core/src/Handlers/Editor/EditorHandler.Android.cs [hunk 6]
```diff
@@ -60,8 +61,10 @@ protected override void DisconnectHandler(AppCompatEditText platformView)
 			_set = false;
 		}
 
-		public static void MapBackground(IEditorHandler handler, IEditor editor) =>
+		public static void MapBackground(IEditorHandler handler, IEditor editor)
```
Comment (PureWeen) [inline src/Core/src/Handlers/Editor/EditorHandler.Android.cs:64]: Because this file doesn't have any functional changes can we leave this file unchanged?

File: src/Core/src/Handlers/Entry/EntryHandler.Android.cs [hunk 7]
```diff
@@ -68,8 +64,10 @@ protected override void DisconnectHandler(AppCompatEditText platformView)
 			_set = false;
 		}
 
-		public static void MapBackground(IEntryHandler handler, IEntry entry) =>
+		public static void MapBackground(IEntryHandler handler, IEntry entry)
```
Comment (PureWeen) [inline src/Core/src/Handlers/Entry/EntryHandler.Android.cs:67]: Because this file doesn't have any functional changes can we leave this file unchanged?

File: src/Core/src/Handlers/Picker/PickerHandler.Android.cs [hunk 8]
```diff
@@ -1,8 +1,5 @@
 ﻿using System;
-using System.Collections.Specialized;
 using Android.App;
-using Android.Content.Res;
```
Comment (PureWeen) [inline src/Core/src/Handlers/Picker/PickerHandler.Android.cs:4]: Because this file doesn't have any functional changes can we leave this file unchanged?

**Review by PureWeen — CHANGES_REQUESTED** [review]
Looking good! Few comments and then a merge conflict.

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Android/ViewExtensions.cs [hunk 9]
```diff
@@ -176,31 +176,43 @@ public static void UpdateBackground(this ContentViewGroup platformView, IBorderS
...
+
+			var previousDrawable = defaultBackgroundDrawable ?? platformView.Background;
```
[the remark this answers is not in the document]
Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/ViewExtensions.cs:206]: I think the case where `defaultBackgroundDrawable` can be null is if the Context of the native control is null. In case the PlatformView or the Context is null, we should not update anything.

[the remark this answers is not in the document]
Comment (PureWeen) [reply src/Core/src/Platform/Android/ViewExtensions.cs:206]: If that's the case, should we just exit this method early if `platformView.Context` is null? 

I think it'd be really weird/bad if we got here, and the Context was null. 

Maybe we just check for null on the platformView at the top of this method? and then write the rest of the code assuming it's not null?

[the remark this answers is not in the document]
Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/ViewExtensions.cs:207]: Added the Context validation at the top of the method.

File: src/Core/src/Platform/Android/ViewExtensions.cs [hunk 10]
```diff
@@ -190,17 +188,33 @@ internal static void UpdateBackground(this EditText platformView, IView view)
...
-			var backgroundDrawable = paint!.ToDrawable(platformView.Context);
-			LayerDrawable layer = new LayerDrawable(new Drawable[] { backgroundDrawable!, previousDrawable! });
-			platformView.Background = layer;
+			var paint = view.Background;
+
+			Drawable? defaultBackgroundDrawable = ContextCompat.GetDrawable(platformView.Context, Resource.Drawable.abc_edit_text_material);
+
+			var previousDrawable = defaultBackgroundDrawable ?? platformView.Background;
+
+			if (paint.IsNullOrEmpty())
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/ViewExtensions.cs:210]: Can we add `[NotNullWhen(true)]` to this extension method so that we don't need the null forgiveness operator on line 214? and line 215?

File: src/Core/src/Platform/Android/ViewExtensions.cs [hunk 11]
```diff
@@ -190,17 +188,33 @@ internal static void UpdateBackground(this EditText platformView, IView view)
...
+				platformView.Background = previousDrawable;
+			else
+			{
+				var backgroundDrawable = paint!.ToDrawable(platformView.Context);
+				LayerDrawable layer = new LayerDrawable(new Drawable[] { backgroundDrawable!, previousDrawable! });
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/ViewExtensions.cs:215]: if for whatever reason `previousdrawable` is null should we just set this to `backgroundDrawable`?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Android/ViewExtensions.cs (hunk 11 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/ViewExtensions.cs]: Applied the changes.

File: src/Core/src/Graphics/PaintExtensions.cs [hunk 12]
```diff
@@ -20,7 +22,11 @@ public static partial class PaintExtensions
 			return null;
 		}
 
-		public static bool IsNullOrEmpty(this Paint? paint)
+		public static bool IsNullOrEmpty(
+#if !NETSTANDARD
+			[NotNullWhen(true)]
```
Comment (PureWeen) [inline src/Core/src/Graphics/PaintExtensions.cs:27]: If you merge with main I don't think you'll need this if/def anymore

File: src/Core/src/Handlers/Entry/EntryHandler.Android.cs (hunk 7 above)
Comment (PureWeen) [inline src/Core/src/Handlers/Entry/EntryHandler.Android.cs:67]: Am I missing something here? The previous conversation was resolved but this change wasn't removed.

File: src/Core/src/Platform/Android/ViewExtensions.cs [hunk 13]
```diff
@@ -198,17 +197,39 @@ internal static void UpdateBackground(this EditText platformView, IView view)
...
+			if (previousDrawable is null)
+				platformView.Background = backgroundDrawable;
+			else
+			{
+				if (paint.IsNullOrEmpty())
+					platformView.Background = previousDrawable;
+				else
+				{
+
+					LayerDrawable layer = new LayerDrawable(new Drawable[] { backgroundDrawable!, previousDrawable! });
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/ViewExtensions.cs:229]: Can we get rid of the null forgiveness operators here?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Graphics/PaintExtensions.cs (hunk 12 above)
Comment (jsuarezruiz) [reply src/Core/src/Graphics/PaintExtensions.cs:27]: Still is require, because this class is compiled for all the platforms but also in .NET Standard.

File: src/Core/src/Platform/Android/ViewExtensions.cs (hunk 13 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/ViewExtensions.cs:229]: Right, we can remove it in the `previousDrawable` case.

File: src/Core/src/Handlers/Entry/EntryHandler.Android.cs (hunk 7 above)
Comment (jsuarezruiz) [reply src/Core/src/Handlers/Entry/EntryHandler.Android.cs]: Initially in the PR we modified this extension method passing the `defaultBackgroundDrawable` as a parameter. Now and after the last changes, the parameters of this method are exactly the same.

File: src/Core/src/Graphics/PaintExtensions.cs (hunk 12 above)
Comment (PureWeen) [reply src/Core/src/Graphics/PaintExtensions.cs:27]: Peppers added a NotNullWhenAttribute class that's used when you're compiling net7.0 so if you rebase with main this shouldn't be needed

File: src/Core/src/Platform/Android/ViewExtensions.cs [hunk 14]
```diff
@@ -198,17 +197,39 @@ internal static void UpdateBackground(this EditText platformView, IView view)
...
+			if (previousDrawable is null)
+				platformView.Background = backgroundDrawable;
+			else
+			{
+				if (paint.IsNullOrEmpty())
+					platformView.Background = previousDrawable;
+				else
+				{
+
+					LayerDrawable layer = new LayerDrawable(new Drawable[] { backgroundDrawable!, previousDrawable });
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/ViewExtensions.cs:229]: Can we remove all the null forgiveness operators from this code?

line 218 as well?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Android/ViewExtensions.cs (hunk 14 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/ViewExtensions.cs:229]: The `ToDrawable` method extension return a `Drawable?`. In that case we create a `LayerDrawable` setting the default previous Drawable (the default background with the bottom line).

**Review by rmarinho — APPROVED** [review]

File: src/Core/src/Platform/Android/ViewExtensions.cs [hunk 15]
```diff
@@ -198,17 +197,39 @@ internal static void UpdateBackground(this EditText platformView, IView view)
...
 			var padRight = platformView.PaddingRight;
 			var padBottom = platformView.PaddingBottom;
 
-			var previousDrawable = platformView.Background;
+			var paint = view.Background;
+
+			Drawable? defaultBackgroundDrawable = ContextCompat.GetDrawable(platformView.Context, Resource.Drawable.abc_edit_text_material);
+
+			var previousDrawable = defaultBackgroundDrawable ?? platformView.Background;
 			var backgroundDrawable = paint!.ToDrawable(platformView.Context);
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/ViewExtensions.cs:218]: I'm still not quite following the null forgiveness operators on this PR. 

`view.Background` returns `Paint?`

image

It seems unsafe to just add `paint!` here instead dealing with a null paint. 

Looking at `PaintExtensions.ToDrawable` it looks like that can return null, so maybe the input parameter on that extension method should get changed to 

```C#
public static Drawable? ToDrawable(this Paint? paint, Context? context)
```
Then we don't have to add null forgiveness?

I feel like this block of code can be reworked so we null have any null forgiveness operators.

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Android/ViewExtensions.cs (hunk 15 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/ViewExtensions.cs]: I updated the extension method to get the drawable, could you review it again?. Thanks!

File: src/Core/src/Platform/Android/ViewExtensions.cs [hunk 16]
```diff
@@ -198,17 +197,39 @@ internal static void UpdateBackground(this EditText platformView, IView view)
...
+			Drawable? defaultBackgroundDrawable = ContextCompat.GetDrawable(platformView.Context, Resource.Drawable.abc_edit_text_material);
+
+			var previousDrawable = defaultBackgroundDrawable ?? platformView.Background;
+			var backgroundDrawable = paint.ToDrawable(platformView.Context);
+
+			if (previousDrawable is null)
+				platformView.Background = backgroundDrawable;
+			else
+			{
+				if (paint.IsNullOrEmpty())
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/ViewExtensions.cs:224]: Can we change this to

`if (backgroundDrawable is null)` ?

If we do that then we can get rid of the null forgiveness operator on line 229

File: src/Core/src/Platform/Android/ViewExtensions.cs [hunk 17]
```diff
@@ -198,17 +197,39 @@ internal static void UpdateBackground(this EditText platformView, IView view)
...
 
-			var previousDrawable = platformView.Background;
-			var backgroundDrawable = paint!.ToDrawable(platformView.Context);
-			LayerDrawable layer = new LayerDrawable(new Drawable[] { backgroundDrawable!, previousDrawable! });
-			platformView.Background = layer;
+			var paint = view.Background;
+
+			Drawable? defaultBackgroundDrawable = ContextCompat.GetDrawable(platformView.Context, Resource.Drawable.abc_edit_text_material);
+
+			var previousDrawable = defaultBackgroundDrawable ?? platformView.Background;
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/ViewExtensions.cs:217]: Based on our conversation [here](https://github.com/dotnet/maui/pull/12227/files#r1131122599) it seems like we can just get rid of `previousDrawable` yea? Just use `defaultBackgroundDrawable` everywhere instead?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Android/ViewExtensions.cs (hunk 17 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/ViewExtensions.cs:217]: Could simplify the code and normally will work in the same way. But if for any reason trying to get `Resource.Drawable.abc_edit_text_material` fails and we get a null Drawable, all the entries will not show the bottom line. With `previousDrawable` we use the default Drawable used by the AppCompatEditText.

**Review by PureWeen — APPROVED** [review]

**Comment by marshallellis** [comment]
Hey guys ... just checking in on this issue since we updated VS last week and this issue is still happening???

Thank you

Marshall

**Comment by marshallellis** [comment]
I also cannot get this handler to work??? Will turn yellow when it gets focus but not to gray when it loses focus??? The code does get called normally and there is no exception from debugging???

`            handler.PlatformView.FocusChange += (sender, e) =>
            {
                try
                {
                    if (e.HasFocus) 
                    {
                        ((Entry)handler.VirtualView).BackgroundColor = Colors.Yellow;    
                    }
                    else
                    {
                        ((Entry)handler.VirtualView).BackgroundColor = Colors.Gray;
                    }
                }
                catch (Exception E) 
                {
                    //log exception...
                }
            };
`

**Comment by marshallellis** [comment]
Just following up to see if this is really fixed because it is not in my code???
Running: 17.6.0
