### PR TITLE
[Android] FlyoutIsPresented property opens the Flyout

### LINKED ISSUE #8226: Shell.Current.FlyoutIsPresented = true does not toggle the first time on Android
### Description

Shell.Current.FlyoutIsPresented inside a button click event handler toggles flyout only after flyout was manually swiped one time.

### Steps to Reproduce

1. Run the attached example.
2. Tap on the "Toggle Flyout" button.
3. Nothing happens.
4. Swipe flyout manually.
5. Tap on the "Toggle Flyout" button again.
6. Now it works as expected.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

[MauiApp7.zip](https://github.com/dotnet/maui/files/8955500/MauiApp7.zip)

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

`FlyoutIsPresented` property opens the Flyout correctly.

fix-8226

### Issues Fixed

Fixes #8226

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellFlyoutRenderer.cs [hunk 1]
```diff
@@ -183,9 +183,10 @@ protected override bool DrawChild(Canvas canvas, AView child, long drawingTime)
 				canvas.DrawRect(0, 0, Width, Height, _scrimPaint);
 			}
 
-			if (!FlyoutFirstDrawPassFinished && _flyoutContent != null)
+			if (!FlyoutFirstDrawPassFinished && _flyoutContent is not null)
 			{
-				if (child == _flyoutContent?.AndroidView)
+				// If the AndroidView property which is the DrawerLayout is initialized at this point, the Flyout first draw pass finished.
+				if (_flyoutContent?.AndroidView is not null)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellFlyoutRenderer.cs:189]: The original condition is only true after opened the Drawer at least once. For this reason, in the issue the comments share that it works if the menu is opened with a gesture or with the hamburger button at least once but not using directly the `FlyoutIsPresented` property.
The `FlyoutFirstDrawPassFinished` property prevents opening the Drawer before it is initialized with a property change to avoid incorrect states, but at this point, if the DrawerLayout has been initialized and the contents drawn we should be able to initialize it.

**Review by PureWeen — APPROVED** [review]

**Review by jfversluis — APPROVED** [review]

**Comment by criss02-cs** [comment]
Still not working on Android
https://github.com/criss02-cs/ObsidianUI
here is my repository, just run the project on android and you can see that if you click the button he doesn't work

**Comment by NickA55** [comment]
Why file a new issus?  The old issue isn't fixed, it would be a duplicate.  Just reopen https://github.com/dotnet/maui/issues/8226
