### PR TITLE
BackgroundColor should trigger Background

### LINKED ISSUE #2152: [Bug] BackgroundColor doesn't update when applied to Page
### Description

If you try to change the background color on a page after the page has rendered, nothing will happen. The change will be set for the BackgroundPage value, but it will look exactly the same.

### Steps to Reproduce

Run this sample application and click on the button on top to change the background.
[MauiDynamicPageBackground.zip](https://github.com/dotnet/maui/files/7009017/MauiDynamicPageBackground.zip)

When looking at the output, you should see the old page value and the new one,

```
[0:] OldBackgroundColor: [Color: Red=0.31764707, Green=0.16862746, Blue=0.8745098, Alpha=1]
[0:] NewBackgroundColor: [Color: Red=1, Green=1, Blue=1, Alpha=1]
```

But nothing will change in the running app.

### Expected Behavior

The background color would change.

### Actual Behavior

Nothing happens.

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

When updating the BackgroundColor, this has to also trigger an update for Background. This is because Core actually only listens to Background.

Fixes #2152

### Additions made ###

Updating BackgroundColor fires the usual events, but then also calls UpdateValue(Background)

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

File: src/Controls/src/Core/VisualElement.cs [hunk 1]
```diff
@@ -203,7 +203,12 @@ static void OnTransformChanged(BindableObject bindable, object oldValue, object
 
 		public static readonly BindableProperty OpacityProperty = BindableProperty.Create("Opacity", typeof(double), typeof(VisualElement), 1d, coerceValue: (bindable, value) => ((double)value).Clamp(0, 1));
 
-		public static readonly BindableProperty BackgroundColorProperty = BindableProperty.Create("BackgroundColor", typeof(Color), typeof(VisualElement), null);
+		public static readonly BindableProperty BackgroundColorProperty = BindableProperty.Create(nameof(BackgroundColor), typeof(Color), typeof(VisualElement), null,
+			propertyChanged: (bindable, oldvalue, newvalue) =>
+			{
+				if (bindable is VisualElement element)
+					element.Handler?.UpdateValue(nameof(Background));
```
Comment (PureWeen) [inline src/Controls/src/Core/VisualElement.cs:210]: Should this get tied into via the mappers? 

we can use the new RemapToControls stuff to add an entry for "BackgroundColor" and then have that call this UpdateValue call

**Review by jsuarezruiz — APPROVED** [review]

File: src/Controls/src/Core/HandlerImpl/VisualElement/VisualElement.cs [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+		};
+
+		public static void RemapForControls()
+		{
+			ViewHandler.ViewMapper = ControlsViewMapper;
+		}
+
+		public static void MapBackgroundColor(ViewHandler handler, IView view)
+		{
+			handler.UpdateValue(nameof(Background));
```
Comment (mattleibow) [inline src/Controls/src/Core/HandlerImpl/VisualElement/VisualElement.cs:19]: This is the single line that fixes bugs.

File: src/Core/src/Platform/Windows/TextBlockExtensions.cs [hunk 3]
```diff
@@ -66,10 +66,22 @@ public static void UpdateTextDecorations(this TextBlock nativeControl, ILabel la
...
+					else if (inline is Span span)
+					{
+						foreach (var inline2 in span.Inlines)
+						{
+							if (inline2 is Run run2)
+							{
+								run2.Text = run2.Text;
+							}
+						}
+					}
```
Comment (mattleibow) [inline src/Core/src/Platform/Windows/TextBlockExtensions.cs:84]: Fix for HTML in labels for Windows. Some items are Spans which contain Runs.

**Review by PureWeen — APPROVED** [review]
