### PR TITLE
Fixed FlyoutItemIsVisible is not working with bindings

### LINKED ISSUE #24203: FlyoutItemIsVisible is not working with bindings
### Description

I get a build error when trying to using a binding with FlyoutItemIsVisible. I cannot use IsVisible, because that will result in that I cannot navigate to the item with code.

```xml
 <ShellContent
     Title="Home"
     ContentTemplate="{DataTemplate local:MainPage}"
     FlyoutItemIsVisible="{Binding ShowItem}"
     Route="MainPage" />
```

We have this closed issue that is related to this: https://github.com/dotnet/maui/issues/10960

### Steps to Reproduce

1. Clone the linked repo
2. Try to build it

### Link to public reproduction project repository

https://github.com/dhindrik/FlyoutItemVisibleBug

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dhindrik**
### Description of Change
In the property for FlyoutItemIsVisible it used Shell.FlyoutItemIsVisibleProperty which is an attached property in the Shell class. But that will not work when trying to bind to FlyoutItemIsVisible because with bindings it is expected to find FlyoutItemIsVisibleProperty in the BaseShellItem class. 

In the OnFlyoutItemIsVisibleChanged method I called the Shell.SetFlyoutItemIsVisible to update the attached property that was updated directly in the property before.

### Issues Fixed
Fixes #24203

### CODE REVIEW

**Comment by jfversluis** [comment]
Since this introduces new APIs this should go into net9. Can you maybe retarget to the net9.0 branch?

**Comment by dhindrik** [comment]
> Since this introduces new APIs this should go into net9. Can you maybe retarget to the net9.0 branch?

What is the best way to do it? I tried to change the PR, but then a lot of other commits were added to the PR.

It would also be great to have this out before .net 9. But I guess not many people are using it like I want because I did not find any issues with it.

**Comment by dhindrik** [comment]
@jfversluis I think I managed to fix it. It was easier than I thought. Are everything looking correct?

File: src/Controls/src/Core/Shell/BaseShellItem.cs [hunk 1]
```diff
@@ -225,6 +229,11 @@ static void OnIconChanged(BindableObject bindable, object oldValue, object newVa
 			shellItem.FlyoutIcon = (ImageSource)newValue;
 		}
 
+		static void OnFlyoutItemIsVisibleChanged(BindableObject bindable, object oldValue, object newValue)
+		{
+			Shell.SetFlyoutItemIsVisible(bindable, (bool)newValue);
```
Comment (PureWeen) [inline src/Controls/src/Core/Shell/BaseShellItem.cs:234]: Do we need to worry about keeping this synced up if the reverse happens? 

So, if someone has

`<FlyoutItem Shell.FlyoutItemIsVisible="true"`

do we need to set the new BP to match the attached property?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Shell/BaseShellItem.cs (hunk 1 above)
Comment (dhindrik) [reply src/Controls/src/Core/Shell/BaseShellItem.cs:234]: I can fix that, I need to figure out how to install the workloads for .NET 9.

Comment (PureWeen) [reply src/Controls/src/Core/Shell/BaseShellItem.cs:234]: if you're on windows .NET9 shipped with the latest VS PReview
so it'll just install everything you need

Comment (dhindrik) [reply src/Controls/src/Core/Shell/BaseShellItem.cs:234]: I only have Windows on my work computer. But I got it working on my Mac too with some support from Gerald. There was some strange versions of .NET workloads installed. I had to remove .NET and intall it again from scratch. 

But now I had added code so the properties will match. I also added a test page so it will be easier to test it.

**Review by PureWeen — APPROVED** [review]
