### PR TITLE
[Windows] Fixed NRE when clearing ListView after navigating back

### LINKED ISSUE #26498: Issue on Windows - Exception thrown: 'System.NullReferenceException' in Microsoft.Maui.Controls.dll
### Description

I converted a .NET MAUI project from .NET 8.0 to .NET 9.0 and I have an issue on Windows now.

I reproduced the issue on this repository:
https://github.com/Auto72/MauiApp9

Run the App on Windows.

Navigate to MauiPage1 by clicking the Button on the first page. 
Navigate back. 
Navigate again to MauiPage1 by clicking the Button on the first page. 
Click the Clear button.

You get the error:
Exception thrown: 'System.NullReferenceException' in Microsoft.Maui.Controls.dll Object reference not set to an instance of an object.

If you go over the variable, you can see it is not null. The try/catch block doesn't catch this error.

In Android and iOS it works fine.
In .NET 8.0 it used to work fine in Android, iOS and Windows.

Image

### Steps to Reproduce

Run the App on Windows.

Navigate to MauiPage1 by clicking the Button on the first page. 
Navigate back. 
Navigate again to MauiPage1 by clicking the Button on the first page. 
Click the Clear button.

You get the error:
Exception thrown: 'System.NullReferenceException' in Microsoft.Maui.Controls.dll Object reference not set to an instance of an object.

### Link to public reproduction project repository

https://github.com/Auto72/MauiApp9

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No workaround found.

### Relevant log output

```shell
Exception thrown: 'System.NullReferenceException' in Microsoft.Maui.Controls.dll
Object reference not set to an instance of an object.
```

### PR DESCRIPTION
**Pull request by SubhikshaSf4851**
### RootCause:

- The issue arises because the CollectionChanged event of the virtual view was not unwired in the DisconnectHandler method in ListViewRender. As a result, the CollectionChanged event was wired multiple times for each navigation, and it was never unwired. When we use the saved instance, the CollectionChanged event is wired for the second time, while the first one was never unwired. When we clear the item source, the CollectionChanged event is triggered for the first element. Since it was disconnected, we receive the virtual view as null.

### Description Of Change:

- I have unwired the CollectionChanged event in the DisconnectHandler method. 

**Tested the behaviour in the following platforms.**
- [x] Windows

**Issue Fixed:**
Fixes [https://github.com/dotnet/maui/issues/26498](https://github.com/dotnet/maui/issues/26498)

**Before Fix:** 

https://github.com/user-attachments/assets/df22c906-d303-499a-a24f-227c81534e73

**After Fix:**

https://github.com/user-attachments/assets/40d7e34c-a6b8-42b5-ac8c-e97cdd809de9

### CODE REVIEW

**Comment by SubhikshaSf4851** [comment]
@dotnet-policy-service agree company="Syncfusion, Inc."

File: src/Controls/src/Core/Compatibility/Handlers/ListView/Windows/ListViewRenderer.cs [hunk 1]
```diff
@@ -807,6 +807,8 @@ void OnListItemClicked(object sender, ItemClickEventArgs e)
 
 		private protected override void DisconnectHandlerCore()
 		{
+			if (Element != null)
+				((ITemplatedItemsView<Cell>)Element).TemplatedItems.CollectionChanged -= OnCollectionChanged;
```
[the remark this answers is not in the document]
Comment (SubhikshaSf4851) [reply src/Controls/src/Core/Compatibility/Handlers/ListView/Windows/ListViewRenderer.cs]: Yes, the changes work as expected. I have updated the changes in the PR.

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26498.cs [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+		{
+			App.WaitForElement("OpenListViewPage");
+			App.Tap("OpenListViewPage");
+			App.WaitForElement("BackButton");
+			App.Click("BackButton");
+			App.WaitForElement("OpenListViewPage");
+			App.Click("OpenListViewPage");
+			App.WaitForElement("ClearButton");
+			App.Click("ClearButton");
+			VerifyScreenshot();
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26498.cs:26]: Pending snapshots already available in the latest build. Could you commit the images?
image

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26498.cs (hunk 2 above)
Comment (SubhikshaSf4851) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26498.cs]: Since this issue was primarily a crash in the ListView, screenshot verification isn't necessary. Therefore, I have removed the screenshot verification and committed the changes

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26498.cs [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+    public class Issue26498 : _IssuesUITest
+	{
+		public override string Issue => "Null Exception on clearing collection in list view after navigation";
+		public Issue26498(TestDevice device) : base(device)
+		{
+		}
+
+		[Test]
+		[Category(UITestCategories.ListView)]
+		public void Issue26498TestNullExeption()
```
Comment (jfversluis) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26498.cs:16]:
```suggestion
		public void Issue26498TestNullException()
```

**Review by jfversluis — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]
