### PR TITLE
[Android] Fix for SearchHandler retaining previous page SearchView data in pages within Shell sections

### LINKED ISSUE #8716: [Shell][Android] The truth is out there...but not on top tab search handlers
### Description

I have this tab structure in my Shell app:

```xaml
    <TabBar>
       <Tab Title="Domestic"
            Icon="paw.png">
           <ShellContent Title="Cats"
                         ContentTemplate="{DataTemplate views:CatsPage}" />
           <ShellContent Title="Dogs"
                         ContentTemplate="{DataTemplate views:DogsPage}" />
       </Tab>
      ...
    </TabBar>
```

So this gives us a Domestic bottom tab, and Cats and Dogs top tabs (within the Domestic tab).

`CatsPage` has a search handler which searches the cats data:

```xaml
    <Shell.SearchHandler>
        <controls:AnimalSearchHandler Placeholder="Enter search term"
                                      ShowsResults="true"
                                      ItemTemplate="{StaticResource AnimalSearchTemplate}"
                                      Animals="{x:Static data:CatData.Cats}"
                                      SelectedItemNavigationTarget="{x:Type views:CatDetailPage}" />
   </Shell.SearchHandler>
```

It works fine:

Screenshot_1657724057

On `DogsPage` there's also a search handler that searches the dogs data:

```xaml
    <Shell.SearchHandler>
        <controls:AnimalSearchHandler Placeholder="Enter search term"
                                      ShowsResults="true"
                                      ItemTemplate="{StaticResource AnimalSearchTemplate}"
                                      Animals="{x:Static data:DogData.Dogs}"
                                      SelectedItemNavigationTarget="{x:Type views:DogDetailPage}" />
    </Shell.SearchHandler>
```

However, using this search handler searches the cats data:

Screenshot_1657724070

This problem is only occurring for bottom tabs that also contain top tabs. For the elephants/monkeys/bears page the search handlers work as expected.

The problem might also occur on platforms other than Android, but right now in SR2 the app crashes on iOS/MacCatalyst, and on Windows the search handler doesn't template the results.

Repo: [Xaminals.zip](https://github.com/dotnet/maui/files/9103756/Xaminals.zip) 

### Steps to Reproduce

1. Run the attached sample on Android.
2. Navigate to the Dogs top tab and search for dogs data. It searches cats data.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

43

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by BagavathiPerumal**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root cause

The issue occurs because SearchHandler references don't update properly during ShellSection page navigation. While SearchView instances are intentionally preserved for performance, the system failed to synchronize the SearchHandler reference when transitioning between pages. This caused search functionality to continue using the previous page's configuration instead of adopting the current page's settings, resulting in inconsistent search behavior and incorrect UI elements.

### Description of Issue Fix

The fix involves adding a synchronization check that detects when the SearchView's SearchHandler doesn't match the current page's SearchHandler. When a mismatch is detected, the code updates the SearchView with the correct SearchHandler and refreshes the view. This ensures search functionality always reflects the current page context during navigation, preventing inconsistent behavior and UI elements.

Tested the behavior in the following platforms.
 
- [x] Windows
- [x] Mac
- [x] iOS
- [x] Android

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/8716

### Output

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="270" height="600"  src="https://github.com/user-attachments/assets/e7668e19-699e-49eb-a940-d160c1b5a10c"> | <video width="270" height="600"  src="https://github.com/user-attachments/assets/5d5a2d4c-6a5f-40f3-9630-12eb4af2045c"> |

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs [hunk 1]
```diff
@@ -646,6 +646,11 @@ protected virtual void UpdateToolbarItems(AToolbar toolbar, Page page)
 					_searchView.View.LayoutParameters = new LP(LP.MatchParent, LP.MatchParent);
 					_searchView.SearchConfirmed += OnSearchConfirmed;
 				}
+				else if (_searchView.SearchHandler != SearchHandler)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs:668]: Could include here a comment in the code explaining the mismatch?

Comment (BagavathiPerumal) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs:668]: @jsuarezruiz, I have added a comment in the code section based on your suggestion. Please let us know if you have any other queries.

**Review by kubaflo — CHANGES_REQUESTED** [review]
Could you please review the AI's summary?

**Comment by BagavathiPerumal** [comment]
> Could you please review the AI's summary?

I’ve reviewed and updated the changes based on the latest findings. Specifically:

- Added the candidate 8 cleanup step to reset the active Android search UI state before the existing logic.
- Preserved the original mismatch-rebind logic and applied it after the cleanup using LoadView().

**Comment by kubaflo** [comment]
## 🚦 Gate — Test Verification

<details>
<summary>📊 <strong>Expand Full Gate</strong> — <a href="https://github.com/dotnet/maui/commit/fbff9da4d3bc8cc75d2418512388f069a50af383"><code>fbff9da</code></a> · <strong>fix-8716-Changes committed.</strong></summary>

---

### Gate Result: ❌ FAILED

**Platform:** ANDROID

#### Tests Detected

| # | Type | Test Name | Filter |
|---|------|-----------|--------|
| 1 | UITest | Issue8716 | `Issue8716` |

#### Verification

| Step | Expected | Actual | Result |
|------|----------|--------|--------|
| Tests WITHOUT fix | FAIL | FAIL | ✅ |
| Tests WITH fix | PASS | FAIL | ❌ |

#### Fix Files Reverted

- `src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs`

---

#### Per-Test Results

| Type | Test | Without Fix | With Fix |
|------|------|-------------|----------|
| UITest | Issue8716 | FAIL ✅ | FAIL ❌ |

---

**Base Branch:** main | **Merge Base:** a38921ca


---

</details>

**Review by kubaflo — CHANGES_REQUESTED** [review]
Looks like the test is failing

**Comment by BagavathiPerumal** [comment]
> Looks like the test is failing

@kubaflo, I have tested the fix on my local machine in the Android platform, and it is working properly. There are no test-case failures related to this fix in CI for Android as well. However, the test case is failing on iOS and Mac platforms.
 
So, I created a separate issue report for iOS and Mac, and I have restricted the test for those platforms. The test is now enabled only for Android.
 
Please find the issue report for iOS and Mac below.
 
New issue report for Mac and iOS: https://github.com/dotnet/maui/issues/34693

**Review by kubaflo — APPROVED** [review]
