### PR TITLE
[X] do not apply Bindings if DataType doesnt match

### LINKED ISSUE #11956: XamlC resolves x:DataType incorrectly
### Description

This is partly a collection of issues and partly a more specific issue. Not sure if this is 100% a bug in all cases either.

XamlC uses the `x:DataType="<type-name>"` on `<DataTemplate>` to generate type-specific bindings, however, somce times the scope is incorrect or if the XAML is wrong but happens to match there is no exception and just fails silently.

> In debug you can also get these errors using `<_MauiForceXamlCForDebug>true</_MauiForceXamlCForDebug>` but still no warnings or exceptions anywhere.

### Steps to Reproduce

1. Clone https://github.com/mattleibow/maui-bug-repros/tree/repro-xamlc-datatype
2. Run
3. Observe that not all the collection views have items in them

### Link to public reproduction project repository

https://github.com/mattleibow/maui-bug-repros/blob/repro-xamlc-datatype/MauiApp1/MainPage.xaml

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All versions

### Did you find any workaround?

Make sure the `x:DataType` is specified correctly, and on every level of templates.

### Relevant log output

_No response_

### LINKED ISSUE #16021: Binding CollectionView/CarouselView to lists of primitive types doesn't work on Release Builds
### Description

A CollectionView/CarouselView bound to an IList with primitive types doesn't render items on release builds.

Tested on Windows and Android, both don't work.

Debug:
image

Release:
image

### Steps to Reproduce

1. Create a new .NET MAUI project
2. Add a view model with a list property of type List<string> and some elements:
`    internal class MainPageViewModel : BindableObject
    {
        private IList<string> _items = new List<string> { "first value", "second value", "third value" };

        public IList<string> Items
        {
            get { return _items; }
            set { _items = value; OnPropertyChanged(nameof(Items)); }
        }
    }`
3. Bind the view model to MainPage.xaml.cs:
` public partial class MainPage : ContentPage
    {
        MainPageViewModel viewModel = new MainPageViewModel();

        public MainPage()
        {
            InitializeComponent();

            BindingContext = viewModel;
        }
    }`
4. Add a CollectionView to MainPage.xaml, bound to the list in MainPageViewModel:
`			<CollectionView ItemsSource="{Binding Items}">
				<CollectionView.ItemTemplate>
					<DataTemplate>
						<Label Text="{Binding}" />
					</DataTemplate>
				</CollectionView.ItemTemplate>
			</CollectionView>
`
5. Do a release build, observe that nothing is rendered.

### Link to public reproduction project repository

https://github.com/stefanpirkl/bugreport-maui-collectionview-primitive-list-on-release

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10, Android 9 and up

### Did you find any workaround?

Changing the List<string> to a custom model class with a single string property in it.

### Relevant log output

_No response_

### LINKED ISSUE #16414: when I release an APP, it can't display binding data properly, but it will display properly when I run it in debug mode.
### Description

**when I release an APP, it can't display binding data properly in collectionview, but it will display properly when I run it in debug mode.**

### In debug mode!
image
### In release mode
image

### Link to public reproduction project repository

https://github.com/dotnet/maui/

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 11 and higher version

### Did you find any workaround?

No solution has been found

### Relevant log output

```shell
exec_start_elapsed_seconds: 15748 [CONTEXT service_id=218 ]
07-28 02:26:09.653 W/healthd (    0): battery l=100 v=5000 t=25.0 h=2 st=4 c=900000 fc=3000000 cc=10 chg=
07-28 02:26:19.519 E/android.hardware.power.stats@1.0-service-mock(  432): Failed to getEnergyData
07-28 02:26:24.522 D/IntervalStats(  623): Unable to parse usage stats packages: [187, 201, 213, 214, 215, 216]
07-28 02:26:24.522 D/IntervalStats(  623): Unable to parse event packages: [216]
07-28 02:26:47.477 E/WifiScoringParams(  623): Invalid frequency(-1), using 5G as default rssi array
07-28 02:26:51.231 D/WifiNl80211Manager(  623): Scan result ready event
07-28 02:26:51.231 D/WifiNative(  623): Scan result ready event
07-28 02:26:55.451 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=97.98706, y[0]=126.968994, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15796696, downTime=15796696, deviceId=12, source=0x5002, displayId=0, eventId=805936239 }
07-28 02:26:55.556 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=97.98706, y[0]=126.968994, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15796803, downTime=15796696, deviceId=12, source=0x5002, displayId=0, eventId=640063634 }
07-28 02:26:55.570 D/EGL_emulation(23935): app_time_stats: avg=22604.95ms min=3.24ms max=293805.12ms count=13
07-28 02:26:56.195 W/TransactionTracing(  467): Could not find layer id -1
07-28 02:26:56.521 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=222.96753, y[0]=701.97144, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15797767, downTime=15797767, deviceId=12, source=0x5002, displayId=0, eventId=57880318 }
07-28 02:26:56.611 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=222.96753, y[0]=701.97144, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15797858, downTime=15797767, deviceId=12, source=0x5002, displayId=0, eventId=832707767 }
07-28 02:26:56.613 W/OnBackInvokedCallback(23935): OnBackInvokedCallback is not enabled for the application.
07-28 02:26:56.613 W/OnBackInvokedCallback(23935): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
07-28 02:26:56.634 D/EGL_emulation(23935): app_time_stats: avg=12.74ms min=5.18ms max=169.46ms count=44
07-28 02:26:56.635 D/AudioFlinger(  455): mixer(0x73ace68ec9a0) throttle end: throttle time(38)
07-28 02:26:56.643 W/TabLayout(23935): MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
07-28 02:26:57.257 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=417.98584, y[0]=666.90857, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15798503, downTime=15798503, deviceId=12, source=0x5002, displayId=0, eventId=963815105 }
07-28 02:26:57.363 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=420.9851, y[0]=666.90857, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15798609, downTime=15798503, deviceId=12, source=0x5002, displayId=0, eventId=486385341 }
07-28 02:26:57.667 D/EGL_emulation(  833): app_time_stats: avg=57650.95ms min=57650.95ms max=57650.95ms count=1
07-28 02:26:59.371 I/NetworkScheduler.Stats(22803): Task com.google.android.gms/com.google.android.gms.auth.account.be.legacy.AuthCronService started execution. cause:4 exec_start_elapsed_seconds: 15800 [CONTEXT service_id=218 ]
07-28 02:26:59.376 I/NetworkScheduler.Stats(22803): Task com.google.android.gms/com.google.android.gms.auth.account.be.legacy.AuthCronService finished executing. cause:4 result: 1 elapsed_millis: 20 uptime_millis: 19 exec_start_elapsed_seconds: 15800 [CONTEXT service_id=218 ]
07-28 02:27:00.016 D/EGL_emulation(  833): app_time_stats: avg=2348.15ms min=2348.15ms max=2348.15ms count=1
07-28 02:27:01.614 I/logd    (    0): logdr: UID=2000 GID=2000 PID=24014 b tail=0 logMask=99 pid=0 start=0ns deadline=0ns
07-28 02:27:03.086 D/WifiNl80211Manager(  623): Scan result ready event
07-28 02:27:03.087 D/WifiNative(  623): Scan result ready event
07-28 02:27:04.309 W/logd    (    0): SocketClient: write error (Broken pipe)
07-28 02:27:06.732 D/TelephonyManager(  623): requestModemActivityInfo: Sending result to app: ModemActivityInfo{ mTimestamp=15807979 mSleepTimeMs=0 mIdleTimeMs=15665739 mActivityStatsTechSpecificInfo=[{mRat=UNKNOWN,mFrequencyRange=UNKNOWN,mTxTimeMs[]=[0, 0, 0, 0, 0],mRxTimeMs=0}]}
07-28 02:27:06.778 I/netd    (  380): tetherGetStats() -> {[]} <0.81ms>
07-28 02:27:37.681 D/EGL_emulation(  833): app_time_stats: avg=37664.64ms min=37664.64ms max=37664.64ms count=1
07-28 02:27:45.413 D/ControlsListingControllerImpl(  833): Subscribing callback, service count: 0
07-28 02:27:45.452 D/ControlsListingControllerImpl(  833): Unsubscribing callback
07-28 02:27:51.905 I/NetworkScheduler.Stats(22803): Task com.google.android.gms/com.google.android.gms.auth.account.be.legacy.AuthCronService started execution. cause:4 exec_start_elapsed_seconds: 15853 [CONTEXT service_id=218 ]
07-28 02:27:51.912 I/NetworkScheduler.Stats(22803): Task com.google.android.gms/com.google.android.gms.auth.account.be.legacy.AuthCronService finished executing. cause:4 result: 1 elapsed_millis: 22 uptime_millis: 22 exec_start_elapsed_seconds: 15853 [CONTEXT service_id=218 ]
07-28 02:28:00.017 D/EGL_emulation(  833): app_time_stats: avg=22335.18ms min=22335.18ms max=22335.18ms count=1
07-28 02:28:09.659 W/healthd (    0): battery l=100 v=5000 t=25.0 h=2 st=4 c=900000 fc=3000000 cc=10 chg=
07-28 02:28:15.165 D/androidtc(  623): Initializing SystemTextClassifier, type = System
07-28 02:28:15.184 I/ClipboardListener(  833): Clipboard overlay suppressed.
07-28 02:28:15.296 I/ClipboardListener(  833): Clipboard overlay suppressed.
07-28 02:28:17.681 D/EGL_emulation(  833): app_time_stats: avg=17663.19ms min=17663.19ms max=17663.19ms count=1
07-28 02:28:19.519 E/android.hardware.power.stats@1.0-service-mock(  432): Failed to getEnergyData
07-28 02:28:24.522 D/IntervalStats(  623): Unable to parse usage stats packages: [187, 201, 213, 214, 215, 216]
07-28 02:28:24.522 D/IntervalStats(  623): Unable to parse event packages: [216]
07-28 02:28:44.421 I/NetworkScheduler.Stats(22803): Task com.google.android.gms/com.google.android.gms.auth.account.be.legacy.AuthCronService started execution. cause:4 exec_start_elapsed_seconds: 15905 [CONTEXT service_id=218 ]
07-28 02:28:44.432 I/NetworkScheduler.Stats(22803): Task com.google.android.gms/com.google.android.gms.auth.account.be.legacy.AuthCronService finished executing. cause:4 result: 1 elapsed_millis: 26 uptime_millis: 26 exec_start_elapsed_seconds: 15905 [CONTEXT service_id=218 ]
07-28 02:28:44.523 I/.gms.persistent(22803): Background concurrent copying GC freed 172819(8614KB) AllocSpace objects, 2(68KB) LOS objects, 49% free, 9358KB/18MB, paused 1.652ms,115us total 108.571ms
07-28 02:28:45.078 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=67.994385, y[0]=161.96045, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15906323, downTime=15906323, deviceId=12, source=0x5002, displayId=0, eventId=841933445 }
07-28 02:28:45.103 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3d9b000 0x3f3e6c000]
07-28 02:28:45.105 I/BpBinder(  467): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
07-28 02:28:45.108 I/LatencyTracker(  833): ACTION_SHOW_BACK_ARROW latency=29
07-28 02:28:45.109 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3e6c000 0x3f3f3d000]
07-28 02:28:45.125 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f2cbc000 0x3f31ce000]
07-28 02:28:45.131 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f31ce000 0x3f329f000]
07-28 02:28:45.158 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=67.994385, y[0]=161.96045, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15906393, downTime=15906323, deviceId=12, source=0x5002, displayId=0, eventId=106287056 }
07-28 02:28:45.164 I/BpBinder(  467): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
07-28 02:28:45.164 D/ShellBackPreview(  833): Finishing gesture with event action: 1
07-28 02:28:45.164 D/ShellBackPreview(  833): onGestureFinished() mTriggerBack == false
07-28 02:28:45.164 D/ShellBackPreview(  833): BackAnimationController: finishAnimation()
07-28 02:28:45.169 D/EGL_emulation(23935): app_time_stats: avg=4331.36ms min=2.18ms max=108100.73ms count=25
07-28 02:28:45.181 W/TransactionTracing(  467): Could not find layer id -1
07-28 02:28:45.229 W/TransactionTracing(  467): Could not find layer handle 0x7d0c2a4deeb0
07-28 02:28:45.234 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3fb7000 0x3f3fce000]
07-28 02:28:46.385 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=263.9685, y[0]=828.9404, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15907631, downTime=15907631, deviceId=12, source=0x5002, displayId=0, eventId=474816016 }
07-28 02:28:46.498 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=263.9685, y[0]=828.9404, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15907744, downTime=15907631, deviceId=12, source=0x5002, displayId=0, eventId=957263551 }
07-28 02:28:46.500 W/OnBackInvokedCallback(23935): OnBackInvokedCallback is not enabled for the application.
07-28 02:28:46.500 W/OnBackInvokedCallback(23935): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
07-28 02:28:46.522 D/AudioFlinger(  455): mixer(0x73ace68ec9a0) throttle end: throttle time(27)
07-28 02:28:46.549 I/com.acme.mtdapp(23935): Explicit concurrent copying GC freed 15949(724KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5540KB/10MB, paused 484us,73us total 21.198ms
07-28 02:28:46.563 D/TrafficStats(23935): tagSocket(94) with statsTag=0xffffffff, statsUid=-1
07-28 02:28:46.575 D/EGL_emulation(23935): app_time_stats: avg=16.47ms min=3.15ms max=508.07ms count=47
07-28 02:28:46.613 W/TabLayout(23935): MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
07-28 02:28:46.806 I/NotificationService(  623): cancelToast pkg=com.acme.mtdapp token=android.os.BinderProxy@e2d2d3d
07-28 02:28:46.807 W/NotificationService(  623): Toast already cancelled. pkg=com.acme.mtdapp token=android.os.BinderProxy@e2d2d3d
07-28 02:28:46.838 D/CoreBackPreview(  623): Window{64eb2bb u0 Toast}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@1fde331, mPriority=0}
07-28 02:28:46.859 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3d9b000 0x3f3dde000]
07-28 02:28:46.867 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3dde000 0x3f3e21000]
07-28 02:28:46.870 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3e21000 0x3f3e64000]
07-28 02:28:46.883 W/Parcel  (  833): Expecting binder but got null!
07-28 02:28:47.390 I/com.acme.mtdapp(23935): Explicit concurrent copying GC freed 11247(553KB) AllocSpace objects, 8(1056KB) LOS objects, 49% free, 6298KB/12MB, paused 454us,72us total 24.221ms
07-28 02:28:47.740 I/com.acme.mtdapp(23935): Explicit concurrent copying GC freed 6222(266KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 7056KB/13MB, paused 345us,88us total 25.175ms
07-28 02:28:47.790 I/Choreographer(23935): Skipped 56 frames!  The application may be doing too much work on its main thread.
07-28 02:28:47.795 D/EGL_emulation(23935): app_time_stats: avg=239.02ms min=10.05ms max=973.96ms count=5
07-28 02:28:47.821 I/OpenGLRenderer(23935): Davey! duration=1002ms; Flags=0, FrameTimelineVsyncId=371900, IntendedVsync=15908040739078, Vsync=15908057405744, InputEventId=0, HandleInputStart=15908072331000, AnimationStart=15908072366000, PerformTraversalsStart=15908072714400, DrawStart=15909020948700, FrameDeadline=15908090739076, FrameInterval=15908072311800, FrameStartTime=16666666, SyncQueued=15909036152900, SyncStart=15909036499400, IssueDrawCommandsStart=15909037417100, SwapBuffers=15909041112600, FrameCompleted=15909043914300, DequeueBufferDuration=46900, QueueBufferDuration=571700, GpuCompleted=15909042844800, SwapBuffersCompleted=15909043914300, DisplayPresentTime=15796853100700, CommandSubmissionCompleted=15909041112600, 
07-28 02:28:48.062 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=534.9573, y[0]=994.8999, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15909308, downTime=15909308, deviceId=12, source=0x5002, displayId=0, eventId=1068916606 }
07-28 02:28:48.162 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=534.9573, y[0]=953.9099, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15909409, downTime=15909308, deviceId=12, source=0x5002, displayId=0, eventId=858720982 }
07-28 02:28:48.800 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=580.968, y[0]=1086.9489, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15910045, downTime=15910045, deviceId=12, source=0x5002, displayId=0, eventId=421369992 }
07-28 02:28:48.818 D/EGL_emulation(23935): app_time_stats: avg=13.63ms min=3.32ms max=53.35ms count=39
07-28 02:28:48.913 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=580.968, y[0]=1126.9391, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15910160, downTime=15910045, deviceId=12, source=0x5002, displayId=0, eventId=241143331 }
07-28 02:28:49.141 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=580.968, y[0]=1086.9489, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15910386, downTime=15910386, deviceId=12, source=0x5002, displayId=0, eventId=387065391 }
07-28 02:28:49.187 D/EGL_emulation(  833): app_time_stats: avg=109.26ms min=3.41ms max=1968.21ms count=19
07-28 02:28:49.240 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=580.968, y[0]=1126.9391, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15910486, downTime=15910386, deviceId=12, source=0x5002, displayId=0, eventId=242827969 }
07-28 02:28:49.419 D/CoreBackPreview(  623): Window{64eb2bb u0 Toast}: Setting back callback null
07-28 02:28:49.448 W/InputManager-JNI(  623): Input channel object '64eb2bb Toast (client)' was disposed without first being removed with the input manager!
07-28 02:28:49.453 W/NotificationService(  623): Toast already killed. pkg=com.acme.mtdapp token=android.os.BinderProxy@be081a2
07-28 02:28:49.462 W/TransactionTracing(  467): Could not find layer handle 0x7d0c2a4db070
07-28 02:28:49.462 W/TransactionTracing(  467): Could not find layer handle 0x7d0c2a4d9bd0
07-28 02:28:49.823 D/EGL_emulation(23935): app_time_stats: avg=10.34ms min=3.72ms max=36.91ms count=43
07-28 02:28:49.970 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=572.959, y[0]=1034.9615, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15911213, downTime=15911213, deviceId=12, source=0x5002, displayId=0, eventId=870131562 }
07-28 02:28:50.066 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=572.959, y[0]=1075.9515, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15911312, downTime=15911213, deviceId=12, source=0x5002, displayId=0, eventId=208709643 }
07-28 02:28:53.399 I/logd    (    0): logdr: UID=2000 GID=2000 PID=24028 b tail=0 logMask=99 pid=0 start=0ns deadline=0ns
07-28 02:28:56.814 D/TelephonyManager(  623): requestModemActivityInfo: Sending result to app: ModemActivityInfo{ mTimestamp=15918060 mSleepTimeMs=0 mIdleTimeMs=15775817 mActivityStatsTechSpecificInfo=[{mRat=UNKNOWN,mFrequencyRange=UNKNOWN,mTxTimeMs[]=[0, 0, 0, 0, 0],mRxTimeMs=0}]}
07-28 02:28:56.845 I/netd    (  380): tetherGetStats() -> {[]} <1.41ms>
07-28 02:28:57.700 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=40.968018, y[0]=131.96777, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15918946, downTime=15918946, deviceId=12, source=0x5002, displayId=0, eventId=627429904 }
07-28 02:28:57.721 I/BpBinder(  467): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
07-28 02:28:57.722 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3d9b000 0x3f3e6c000]
07-28 02:28:57.730 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3e6c000 0x3f3f3d000]
07-28 02:28:57.736 I/LatencyTracker(  833): ACTION_SHOW_BACK_ARROW latency=34
07-28 02:28:57.739 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f2cbc000 0x3f2d8d000]
07-28 02:28:57.767 D/ShellBackPreview(  833): Finishing gesture with event action: 1
07-28 02:28:57.767 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=40.968018, y[0]=131.96777, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15919009, downTime=15918946, deviceId=12, source=0x5002, displayId=0, eventId=174520467 }
07-28 02:28:57.768 D/ShellBackPreview(  833): onGestureFinished() mTriggerBack == false
07-28 02:28:57.768 I/BpBinder(  467): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
07-28 02:28:57.769 D/ShellBackPreview(  833): BackAnimationController: finishAnimation()
07-28 02:28:57.791 D/EGL_emulation(23935): app_time_stats: avg=250.48ms min=3.79ms max=7207.99ms count=30
07-28 02:28:57.797 W/TransactionTracing(  467): Could not find layer handle 0x7d0c2a4db190
07-28 02:28:58.979 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=276.9873, y[0]=712.96875, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15920224, downTime=15920224, deviceId=12, source=0x5002, displayId=0, eventId=444614357 }
07-28 02:28:59.088 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=276.9873, y[0]=712.96875, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15920333, downTime=15920224, deviceId=12, source=0x5002, displayId=0, eventId=942471326 }
07-28 02:28:59.090 W/OnBackInvokedCallback(23935): OnBackInvokedCallback is not enabled for the application.
07-28 02:28:59.090 W/OnBackInvokedCallback(23935): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
07-28 02:28:59.104 D/EGL_emulation(23935): app_time_stats: avg=20.20ms min=6.61ms max=384.18ms count=38
07-28 02:28:59.109 D/AudioFlinger(  455): mixer(0x73ace68ec9a0) throttle end: throttle time(41)
07-28 02:28:59.125 W/TabLayout(23935): MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
07-28 02:28:59.917 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=81.968994, y[0]=145.96436, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15921163, downTime=15921163, deviceId=12, source=0x5002, displayId=0, eventId=1044377960 }
07-28 02:28:59.937 I/BpBinder(  467): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
07-28 02:28:59.937 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3d9b000 0x3f3e6c000]
07-28 02:28:59.942 I/LatencyTracker(  833): ACTION_SHOW_BACK_ARROW latency=22
07-28 02:28:59.943 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3e6c000 0x3f3f3d000]
07-28 02:28:59.952 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f2cbc000 0x3f2d8d000]
07-28 02:28:59.955 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f2d8d000 0x3f329f000]
07-28 02:29:00.018 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=81.968994, y[0]=145.96436, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15921263, downTime=15921163, deviceId=12, source=0x5002, displayId=0, eventId=634680253 }
07-28 02:29:00.028 D/EGL_emulation(  833): app_time_stats: avg=42346.27ms min=42346.27ms max=42346.27ms count=1
07-28 02:29:00.036 D/ShellBackPreview(  833): Finishing gesture with event action: 1
07-28 02:29:00.038 D/ShellBackPreview(  833): onGestureFinished() mTriggerBack == false
07-28 02:29:00.038 I/BpBinder(  467): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
07-28 02:29:00.041 D/ShellBackPreview(  833): BackAnimationController: finishAnimation()
07-28 02:29:00.066 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3fb7000 0x3f3fce000]
07-28 02:29:00.068 W/TransactionTracing(  467): Could not find layer handle 0x7d0c2a4d7b90
07-28 02:29:00.129 D/EGL_emulation(23935): app_time_stats: avg=29.82ms min=3.59ms max=451.17ms count=26
07-28 02:29:00.160 W/WindowManager(  623): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@10ec4ec
07-28 02:29:00.846 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=350.98022, y[0]=817.9431, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15922091, downTime=15922091, deviceId=12, source=0x5002, displayId=0, eventId=430481822 }
07-28 02:29:00.954 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=350.98022, y[0]=817.9431, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15922200, downTime=15922091, deviceId=12, source=0x5002, displayId=0, eventId=201558745 }
07-28 02:29:00.958 W/OnBackInvokedCallback(23935): OnBackInvokedCallback is not enabled for the application.
07-28 02:29:00.958 W/OnBackInvokedCallback(23935): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
07-28 02:29:01.007 W/TabLayout(23935): MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
07-28 02:29:01.140 D/EGL_emulation(23935): app_time_stats: avg=9.70ms min=3.82ms max=105.83ms count=43
07-28 02:29:01.155 I/NotificationService(  623): cancelToast pkg=com.acme.mtdapp token=android.os.BinderProxy@be081a2
07-28 02:29:01.155 W/NotificationService(  623): Toast already cancelled. pkg=com.acme.mtdapp token=android.os.BinderProxy@be081a2
07-28 02:29:01.178 D/CoreBackPreview(  623): Window{8c3411c u0 Toast}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@cd4a2fa, mPriority=0}
07-28 02:29:01.197 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3d9b000 0x3f3dde000]
07-28 02:29:01.208 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3dde000 0x3f3e21000]
07-28 02:29:01.214 D/goldfish-address-space(  409): claimShared: Ask to claim region [0x3f3e21000 0x3f3e64000]
07-28 02:29:01.221 W/Parcel  (  833): Expecting binder but got null!
07-28 02:29:01.640 I/com.acme.mtdapp(23935): Explicit concurrent copying GC freed 22757(1048KB) AllocSpace objects, 7(924KB) LOS objects, 49% free, 7800KB/15MB, paused 1.338ms,119us total 44.821ms
07-28 02:29:01.857 D/TelephonyManager( 1018): requestModemActivityInfo: Sending result to app: ModemActivityInfo{ mTimestamp=15918060 mSleepTimeMs=0 mIdleTimeMs=15775817 mActivityStatsTechSpecificInfo=[{mRat=UNKNOWN,mFrequencyRange=UNKNOWN,mTxTimeMs[]=[0, 0, 0, 0, 0],mRxTimeMs=0}]}
07-28 02:29:02.002 I/com.acme.mtdapp(23935): Explicit concurrent copying GC freed 7412(306KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 8534KB/16MB, paused 1.214ms,395us total 34.052ms
07-28 02:29:02.031 I/Choreographer(23935): Skipped 51 frames!  The application may be doing too much work on its main thread.
07-28 02:29:02.059 I/OpenGLRenderer(23935): Davey! duration=892ms; Flags=0, FrameTimelineVsyncId=374696, IntendedVsync=15922390738504, Vsync=15922407405170, InputEventId=0, HandleInputStart=15922413211400, AnimationStart=15922413243700, PerformTraversalsStart=15922413554400, DrawStart=15923264793600, FrameDeadline=15922440738502, FrameInterval=15922413191700, FrameStartTime=16666666, SyncQueued=15923277156500, SyncStart=15923277562400, IssueDrawCommandsStart=15923278368900, SwapBuffers=15923282352700, FrameCompleted=15923284055700, DequeueBufferDuration=59200, QueueBufferDuration=581400, GpuCompleted=15923283799500, SwapBuffersCompleted=15923284055700, DisplayPresentTime=15911615360700, CommandSubmissionCompleted=15923282352700, 
07-28 02:29:02.083 I/OpenGLRenderer(23935): Davey! duration=901ms; Flags=0, FrameTimelineVsyncId=374719, IntendedVsync=15922424071836, Vsync=15923274071802, InputEventId=0, HandleInputStart=15923278991100, AnimationStart=15923279012200, PerformTraversalsStart=15923287387700, DrawStart=15923287513000, FrameDeadline=15923307405134, FrameInterval=15923278801800, FrameStartTime=16666666, SyncQueued=15923288007000, SyncStart=15923288417800, IssueDrawCommandsStart=15923293389100, SwapBuffers=15923295844000, FrameCompleted=15923325617000, DequeueBufferDuration=8970800, QueueBufferDuration=755400, GpuCompleted=15923325617000, SwapBuffersCompleted=15923309617200, DisplayPresentTime=15911631555500, CommandSubmissionCompleted=15923295844000, 
07-28 02:29:02.145 D/EGL_emulation(23935): app_time_stats: avg=198.98ms min=13.47ms max=881.80ms count=5
07-28 02:29:02.814 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=577.96875, y[0]=316.9226, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15924060, downTime=15924060, deviceId=12, source=0x5002, displayId=0, eventId=270730090 }
07-28 02:29:03.196 D/EGL_emulation(23935): app_time_stats: avg=40.20ms min=2.99ms max=560.29ms count=20
07-28 02:29:03.371 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=558.9514, y[0]=901.9226, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15924617, downTime=15924060, deviceId=12, source=0x5002, displayId=0, eventId=591270030 }
07-28 02:29:03.546 D/EGL_emulation(  833): app_time_stats: avg=113.68ms min=2.62ms max=1977.72ms count=18
07-28 02:29:03.770 D/CoreBackPreview(  623): Window{8c3411c u0 Toast}: Setting back callback null
07-28 02:29:03.789 W/InputManager-JNI(  623): Input channel object '8c3411c Toast (client)' was disposed without first being removed with the input manager!
07-28 02:29:03.801 W/NotificationService(  623): Toast already killed. pkg=com.acme.mtdapp token=android.os.BinderProxy@765bc87
07-28 02:29:03.813 W/TransactionTracing(  467): Could not find layer handle 0x7d0c2a4deeb0
07-28 02:29:03.814 W/TransactionTracing(  467): Could not find layer handle 0x7d0c2a4db5b0
07-28 02:29:03.815 W/TransactionTracing(  467): Could not find layer handle 0x7d0c2a4d90f0
07-28 02:29:04.246 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=474.97192, y[0]=386.97693, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15925492, downTime=15925492, deviceId=12, source=0x5002, displayId=0, eventId=328479519 }
07-28 02:29:04.352 D/EGL_emulation(23935): app_time_stats: avg=19.54ms min=4.15ms max=184.76ms count=38
07-28 02:29:04.466 W/TransactionTracing(  467): Could not find layer id -1
07-28 02:29:04.768 D/TaplEvents( 1147): TIS / TouchInteractionService.onInputEvent: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=455.9546, y[0]=1189.9237, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=15926011, downTime=15925492, deviceId=12, source=0x5002, displayId=0, eventId=3881432 }
07-28 02:29:05.356 D/EGL_emulation(23935): app_time_stats: avg=7.30ms min=3.75ms max=30.67ms count=50
07-28 02:29:11.145 D/TelephonyManager(  623): requestModemActivityInfo: Sending result to app: ModemActivityInfo{ mTimestamp=15932391 mSleepTimeMs=0 mIdleTimeMs=15785102 mActivityStatsTechSpecificInfo=[{mRat=UNKNOWN,mFrequencyRange=UNKNOWN,mTxTimeMs[]=[0, 0, 0, 0, 0],mRxTimeMs=0}]}
```

### LINKED ISSUE #19357: .NET MAUI CarouselView Items Not Visible in Release Mode
### Description

I have a **CarouselView** for displaying an **ObservableCollection** of type **ImageSource**.
`[ObservableProperty] private ObservableCollection<ImageSource> _workOrderPhotosList = new();
`

An API call gets said images and adds them to the collection. This works fine in **Debug** mode with no issue, images are added to the collection and are displayed correctly. 

In Release mode however, images are added to the collection but they are invisible. I know they are there as the **IndicatorView** populates showing either 1 or more dots, and I can swipe to flick through the collection even though there are no images visible.

Can anybody shed some light on why this may be? I am using Compiled Bindings, as indicated at the top of my XAML:
`x:DataType="viewModels:WorkOrderDetailsViewModel"
`

I have ReSharper installed, so IntelliSense is showing me that the **CarouselView** ItemsSrouce is correctly bound to the **WorkOrderDetailsViewModel**, with the path **WorkOrdersPhotosList**

`ItemsSource="{Binding (WorkOrderDetailsViewModel). Path=WorkOrderPhotosList}"
`

Code if call is successful:
```
if (response.IsSuccessStatusCode)
{
    var jsonResponse = await response.Content.ReadAsStringAsync();
    using JsonDocument doc = JsonDocument.Parse(jsonResponse);

    var imageSources = new ObservableCollection<ImageSource>();
    foreach (var element in doc.RootElement.EnumerateArray())
    {
        var base64Image = element.GetString();
        var imageBytes = Convert.FromBase64String(base64Image);
        var imageSource = ImageSource.FromStream(() => new MemoryStream(imageBytes));
        imageSources.Add(imageSource);
    }

    WorkOrderPhotosList.Clear();
    foreach (var imageSource in imageSources)
    {
        WorkOrderPhotosList.Add(imageSource);
    }
}
```

XAML for **IndicatorView** and **CarouselView** :
```
<IndicatorView x:Name="AttachmentsIndicatorView"
               VerticalOptions="CenterAndExpand"
               HorizontalOptions="Start"
               IndicatorColor="White" 
               IndicatorSize="12" 
               SelectedIndicatorColor="CornflowerBlue" 
               Grid.Row="2"
               Margin="0,-2,0,10"/>

<CarouselView x:Name="CarouselView"
              Grid.Row="3"
              IsVisible="{Binding HasAttachments}"
              ItemsSource="{Binding WorkOrderPhotosList}"
              IndicatorView="AttachmentsIndicatorView"
              Loop="True"
              HeightRequest="200"
              HorizontalScrollBarVisibility="Never"
              VerticalScrollBarVisibility="Never"
              IsScrollAnimated="True"
              IsSwipeEnabled="True"
              IsBounceEnabled="True">
    <CarouselView.ItemTemplate>
        <DataTemplate>
            <Image Source="{Binding .}"
                   Aspect="AspectFill"
                   HeightRequest="200">
                <Image.GestureRecognizers>
                    <TapGestureRecognizer 
                        NumberOfTapsRequired="1"
                        Command="{Binding Source={RelativeSource AncestorType={x:Type viewModels:WorkOrderDetailsViewModel}}, Path=ImageTappedCommand}"
                        CommandParameter="{Binding .}" />
                </Image.GestureRecognizers>
            </Image>
        </DataTemplate>
    </CarouselView.ItemTemplate>
</CarouselView>
```

### Steps to Reproduce

1. Add a CarouselView in XAML to a .NET MAUI project.
2. Bind an ObservableCollection of type ImageSource to its ItemsSource.
3. Attach an IndicatorView to the Carousel.
4. Run solution in debug mode.
5. Run solution in release mode.

**Output**

- **Expected**: Images from collection to display in the CarouselView normally, as they do in debug mode.
- **Actual**: Images are not visible in release mode, but are in debug mode.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13 - API 33

### Did you find any workaround?

https://github.com/dotnet/maui/issues/19357#issuecomment-1900055676

### Relevant log output

_No response_

### LINKED ISSUE #21735: Improve information/experience around x:DataType behaviour in Debug vs Release
### Description

There can be differences in behaviour at runtime in Debug vs Release builds and using `x:DataType`.

For example, take the following view models (Note that they both have a `Text` property):

```csharp
public partial class CorrectViewModel
{
    public string Text { get; set; } = "Correct Value";
}

public partial class ActuallyUsedViewModel
{
    public string Text { get; set; } = "Wrong Value";
}
```

Now with the following XAML:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiApp1"
    x:DataType="local:CorrectViewModel"
    x:Class="MauiApp1.MainPage">

    <Label
        Text="{Binding TextProperty}" />

</ContentPage>
```

If we set the binding context in the page's code behind:

```csharp
this.BindingContext = new ActuallyUsedViewModel();
```

Everything compiles fine.  In a **Debug** build, the label shows the expected text `Wrong Value` despite the incorrect type on the instance assigned to the Binding context.

If you run a **Release** build however, the label has no text.  Presumably the type cast fails at runtime as the instance assigned to the binding context does not match the `x:DataType` specified for this compiled binding, and this does not happen in Debug because there's no XAMLC step and so all the bindings are dynamic.

How do we improve the experience here?

Possibly related / duplicate:
- #20002
- #16414
- #11956
- #16021
- #19357

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Reverted for SR8

https://github.com/dotnet/maui/pull/24046

This should be part of SR9
https://github.com/dotnet/maui/issues/23989

### Description of Change

Make sure the behavior of bindings is consistent accross implementations (compiled/not compiled)

fixes a bunch of issues

### Issues Fixed

- fixes #21735 
- fixes #16414 
- fixes #11956
- fixes #16021
- fixes #19357

### CODE REVIEW

File: src/Controls/src/Core/Binding.cs [hunk 1]
```diff
@@ -120,7 +122,13 @@ internal override void Apply(object context, BindableObject bindObj, BindablePro
 			object src = _source;
 			var isApplied = IsApplied;
 
-			base.Apply(src ?? context, bindObj, targetProperty, fromBindingContextChanged, specificity);
+			var bindingContext = src ?? Context ?? context;
```
Comment (simonrozsival) [inline src/Controls/src/Core/Binding.cs:125]: Previously we didn't include `Context` into the call to `Apply`. Is there a case which we could break with this change?

File: src/Controls/src/Core/Binding.cs [hunk 2]
```diff
@@ -120,7 +122,13 @@ internal override void Apply(object context, BindableObject bindObj, BindablePro
...
+			if (DataType != null && bindingContext != null && !DataType.IsAssignableFrom(bindingContext.GetType()))
+			{
+				bindingContext = null;
```
Comment (simonrozsival) [inline src/Controls/src/Core/Binding.cs:128]: Should we log a warning to make it easier to debug the type mismatch?

File: src/Controls/src/Xaml/MarkupExtensions/BindingExtension.cs [hunk 3]
```diff
@@ -21,12 +21,21 @@ public sealed class BindingExtension : IMarkupExtension<BindingBase>
 
 		BindingBase IMarkupExtension<BindingBase>.ProvideValue(IServiceProvider serviceProvider)
 		{
+			Type bindingXDataType = null;
+			if ((serviceProvider.GetService(typeof(IXamlTypeResolver)) is IXamlTypeResolver typeResolver)
+				&& (serviceProvider.GetService(typeof(IXamlDataTypeProvider)) is IXamlDataTypeProvider dataTypeProvider)
+				&& dataTypeProvider.BindingDataType != null)
+			{
+				typeResolver.TryResolve(dataTypeProvider.BindingDataType, out bindingXDataType);
+			}
```
Comment (simonrozsival) [inline src/Controls/src/Xaml/MarkupExtensions/BindingExtension.cs:30]: Could we move this block of code into the `if (TypedBinding is null)` branch? This lookup is unnecessary when the binding is compiled.

File: src/Controls/src/Xaml/MarkupExtensions/BindingExtension.cs [hunk 4]
```diff
@@ -1,11 +1,11 @@
 using System;
 using System.ComponentModel;
+using System.Linq.Expressions;
 using Microsoft.Maui.Controls.Internals;
 
 namespace Microsoft.Maui.Controls.Xaml
 {
 	[ContentProperty(nameof(Path))]
-	[AcceptEmptyServiceProvider]
 	public sealed class BindingExtension : IMarkupExtension<BindingBase>
```
Comment (simonrozsival) [inline src/Controls/src/Xaml/MarkupExtensions/BindingExtension.cs:9]: If I understand this correctly, this extension now needs to accept two services when the binding isn't compiled but it won't need them when the binding is compiled.

```suggestion
	[RequireService(
		[typeof(IXamlTypeResolver),
		 typeof(IXamlDataTypeProvider)])]
	public sealed class BindingExtension : IMarkupExtension<BindingBase>
```

I think this extension has evolved so much that it is now doing too much. Would it make sense to either have a compiled version of the extension, or have a "simplification" visitor to completely remove it when it is possible to compile the binding?

File: src/Controls/src/Xaml/XamlServiceProvider.cs [hunk 5]
```diff
@@ -27,6 +27,9 @@ internal XamlServiceProvider(INode node, HydrationContext context)
 				IXmlLineInfoProvider = new XmlLineInfoProvider(xmlLineInfo);
 
 			IValueConverterProvider = new ValueConverterProvider();
+
+			if (node is IElementNode elementNode)
+				Add(typeof(IXamlDataTypeProvider), new XamlDataTypeProvider(elementNode));
```
Comment (simonrozsival) [inline src/Controls/src/Xaml/XamlServiceProvider.cs:32]: Will this service be added even when XamlC creates the new XamlServiceProvider instance? And if it is, won't this be added for almost any extension, even if `IXamlDataTypeProvider` is not in its `[RequiredService([...])]`?

Comment (StephaneDelcroix) [reply src/Controls/src/Xaml/XamlServiceProvider.cs:32]: yes, but I think I have a PR that only add the services that are required

File: src/Controls/src/Xaml/MarkupExtensions/BindingExtension.cs (hunk 4 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Xaml/MarkupExtensions/BindingExtension.cs:9]: oh, right, I forgot this was merged. I thought it was still pending

File: src/Controls/src/Xaml/XamlServiceProvider.cs (hunk 5 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Xaml/XamlServiceProvider.cs:32]: going to fix this

File: src/Controls/src/Core/Binding.cs (hunk 2 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Core/Binding.cs:128]: I'm afraid that a warning will make HotReload fail

File: src/Controls/src/Xaml/MarkupExtensions/BindingExtension.cs (hunk 4 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Xaml/MarkupExtensions/BindingExtension.cs:9]: RequireService is net9 only

File: src/Controls/src/Core/Binding.cs (hunk 1 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Core/Binding.cs:125]: this is correct as is

File: src/Controls/src/Xaml/MarkupExtensions/BindingExtension.cs (hunk 4 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Xaml/MarkupExtensions/BindingExtension.cs:9]: but in net9

**Review by simonrozsival — DISMISSED** [review]

File: src/Controls/src/Core/Binding.cs (hunk 2 above)
Comment (drasticactions) [reply src/Controls/src/Core/Binding.cs:128]: If it's something that "works" but is not the correct or preferred way to bind, I rather hot reload not work and tell the user about the issue rather than let it through even though there is a type mismatch that "works" but is wrong. I'm also not sure if warnings in it of themselves would stop hot reload itself or if we could still show the warning and let the action through anyway.

@mgoertz-msft what do you think?

Comment (mgoertz-msft) [reply src/Controls/src/Core/Binding.cs:128]: You would need to ask @etvorun. I'm not sure what the exact condition is for errors/warnings to cause Hot Reload to skip requests. I also thought that HR only looks at these reported from IntelliSense and not build but I could be wrong.

Comment (etvorun) [reply src/Controls/src/Core/Binding.cs:128]: My preference would be to follow WPF, which is to silently ignore bad binding and fire [BindingErrorEventArgs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.xaml.diagnostics.bindingerroreventargs?view=net-maui-8.0). Then extend VS support for [binding diagnostics](https://learn.microsoft.com/en-us/visualstudio/xaml-tools/xaml-data-binding-diagnostics?view=vs-2022) for MAUI. @spadapet is the expert in that area.

Comment (spadapet) [reply src/Controls/src/Core/Binding.cs:128]: I agree with @etvorun. XAML Hot Reload will send the bad binding to the app since XAML parsing is valid (like @mgoertz-msft said). If this code triggers a [BindingFailed](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.xaml.diagnostics.bindingdiagnostics.bindingfailed?view=net-maui-8.0) event, then the UI in Visual Studio and the in-app toolbar will immediately show that a runtime binding failure occurred. Then the user can see a detailed error message and jump the XAML.

image

Comment (StephaneDelcroix) [reply src/Controls/src/Core/Binding.cs:130]: I'm now sending a binding failure in case of mismatch. Recall that this could be transient (as the context might not be set until the parent is), and a transient error shouldn't make HR to fail

**Review by PureWeen — APPROVED** [review]

**Review by PureWeen — CHANGES_REQUESTED** [review]
One the compatibility UI tests pass on this run
https://dev.azure.com/xamarin/public/_build/results?buildId=119409&view=results

let's merge

**Review by PureWeen — APPROVED** [review]

**Comment by AlleSchonWeg** [comment]
Hi @simonrozsival ,
i updated my app to the latest nightly build and now i receive this warnings: 

> Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: Mismatch between the specified x:DataType and the current binding context

Is it possible to add more infos to this warning which can help to find easier the cause? Perhaps the type specified in x:DataType and current BindingContext type which not match?! 

Thank you

**Comment by simonrozsival** [comment]
@AlleSchonWeg thanks for the feedback. What you suggest makes sense. Could you please open a new issue so that we can track it more easily?

**Comment by AlleSchonWeg** [comment]
@simonrozsival 
Issue created: https://github.com/dotnet/maui/issues/24349 😎
