### PR TITLE
[Windows] Fix crash using SwipeView inside CollectionView 

### LINKED ISSUE #6153: System.AccessViolationException when using SwipeView in a CollectionView on Windows
### Description

If a SwipeView is used in a CollectionView, an `System.AccessViolationException` is thrown on Windows this message.

    Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

[Demo project](https://github.com/pekspro/MauiIssues/tree/SwipeOnWindowsCrash)

### Steps to Reproduce

1. Create a new MAUI app.
2. Add this on the main page:

```
    <CollectionView 
                x:Name="ItemsList"
                ItemSizingStrategy="MeasureFirstItem"
                >
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <SwipeView>
                    <SwipeView.LeftItems>
                        <SwipeItems>
                            <SwipeItem Text="Favorite" BackgroundColor="LightGreen" />
                            <SwipeItem Text="Delete" BackgroundColor="LightPink"
                                />
                        </SwipeItems>
                    </SwipeView.LeftItems>
                    <StackLayout HeightRequest="80">
                        <Label Text="Swipe me!" />
                    </StackLayout>
                </SwipeView>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
```

3. Initialize the view in the constructor:

``` C#
	public MainPage()
	{
		InitializeComponent();

		ItemsList.ItemsSource = new string[] { "Hello", "World" }; 
	}
```

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Windows 10.0.17763.0

### Did you find any workaround?

No workaround.

### Relevant log output

_No response_

### LINKED ISSUE #6401: (Windows) RC1 - SwipeView - Attempted to read or write protected memory. This is often an indication that other memory is corrupt
### Description

The SwipeView I've noticed causes an exception on Windows when trying to run the app: 
`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`

On Android, however, SwipeView works perfectly.

Repository:
https://github.com/nacompllo/MauiCollectionView/tree/test/WindowsSwipeView

### Steps to Reproduce

Clone the attached repository and start the Windows application, the detailed exception will be thrown. If you remove SwipeView from the XAML, the app will run normally.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix crash using SwipeView inside CollectionView on Windows.

### Issues Fixed

Fixes #6153 
Fixes #6401

### CODE REVIEW

File: src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs [hunk 1]
```diff
@@ -266,5 +269,14 @@ protected override WSize MeasureOverride(WSize availableSize)
 		{
 			return double.IsInfinity(value) ? 0 : value;
 		}
+
+		bool CanMeasureContent(FrameworkElement frameworkElement)
+		{
+			// Measure the SwipeControl before has loaded causes a crash on the first layout pass
+			if (frameworkElement is SwipeControl swipeControl && !swipeControl.IsLoaded)
```
Comment (Redth) [inline src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs:276]: Is this exclusive to SwipeControl? Should this just check for a `Control` that `IsLoaded` ?

Comment (jsuarezruiz) [reply src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs:276]: A far as I reviewed cannot Measure the SwipeControl with left or right items before is loaded, but, not happens in the rest of the controls.

**Comment by LanceMcCarthy** [comment]
Looking forward to this fix! Thanks Javier.

**Review by Redth — APPROVED** [review]

**Comment by SamuelJames101** [comment]
What .net Version did this come into? As I am using .net 7.0.3 and I can still see the exception on Windows
"Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'" when I have a swipe view in the XAML
