### PR TITLE
[Testing] Added UI Test for manual test C3

### LINKED ISSUE #18896: [Testing] Create UI Test for manual test C3
### Description

Create UI Test for manual test C3.

```
<Grid RowDefinitions="auto,auto,500">
    <Label Grid.Row="0"
           Text="1. Confirm that the ListView below is populated with monkeys and can be scrolled." />
    <Label Grid.Row="1"
           Text="2. The test passes if you are able to see the image, name, and location of each monkey." />
    <RefreshView Grid.Row="2">
        <ListView ItemsSource="{Binding Monkeys}"
                  VerticalScrollBarVisibility="Always">
            <ListView.ItemTemplate>
                <DataTemplate x:DataType="models:Monkey">
                    <ViewCell>
                        <Grid Padding="10">
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="Auto" />
                            </Grid.ColumnDefinitions>
                            <Image Grid.RowSpan="2"
                                   Aspect="AspectFill"
                                   HeightRequest="60"
                                   Source="{Binding ImageUrl}"
                                   WidthRequest="60" />
                            <Label Grid.Column="1"
                                   FontAttributes="Bold"
                                   Text="{Binding Name}" />
                            <Label Grid.Row="1"
                                   Grid.Column="1"
                                   FontAttributes="Italic"
                                   Text="{Binding Location}"
                                   VerticalOptions="End" />
                        </Grid>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </RefreshView>
</Grid>
```

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Added UI Test for manual test C3.

### Issues Fixed

Fixes #18896

### CODE REVIEW

File: src/Controls/tests/UITests/Tests/Issues/Issue18896.cs [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+		public Issue18896(TestDevice device) : base(device)
+		{
+		}
+
+		public override string Issue => "Can scroll ListView inside RefreshView";
+
+		[Test]
+		public async Task Issue18896Test()
+		{
+			this.IgnoreIfPlatforms(new TestDevice[] { TestDevice.Windows },
```
Comment (jsuarezruiz) [inline src/Controls/tests/UITests/Tests/Issues/Issue18896.cs:18]: ListView item images are not loading.

File: src/Controls/tests/UITests/Tests/Issues/Issue18896.cs [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+		{
+		}
+
+		public override string Issue => "Can scroll ListView inside RefreshView";
+
+		[Test]
+		public async Task Issue18896Test()
+		{
+			this.IgnoreIfPlatforms(new TestDevice[] { TestDevice.iOS, TestDevice.Mac },
+				"Currently fails on iOS; see https://github.com/dotnet/maui/issues/18811");
```
Comment (jsuarezruiz) [inline src/Controls/tests/UITests/Tests/Issues/Issue18896.cs:19]: image

**Review by jfversluis — APPROVED** [review]
