### PR TITLE
[NET10] Replace the obsolete RunJavaScriptTextInputPanel 

### LINKED ISSUE #28135: [net10.0] Replace the obsolete RunJavaScriptTextInputPanel
### Description

On net10/0 preview the iOS workload deprecated RunJavaScriptTextInputPanel , so we need to follow up and replace this usage. 

For now ignoring the error for preview 2

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.40 SR4

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

This pull request introduces several enhancements and fixes across the Maui platform, focusing on improving iOS support, adding new functionality to Blazor components, and refining public APIs. Key changes include enabling unsafe code blocks, extending iOS-specific features, and adding user interaction capabilities in Blazor components.

### Changes to iOS-specific functionality:

* Made `UIApplicationExtensions` public and added `GetKeyWindow` and `GetWindow` extension methods to simplify window management in iOS. (`src/Core/src/Platform/iOS/UIApplicationExtensions.cs`, `src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt`, `src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt`) [[1]](diffhunk://#diff-de204b8df39b3aea27c9ff384dc0e1466164f2a743f06cdb598accfddf09d8d4L7-R7) [[2]](diffhunk://#diff-0ccdbe3d9b972e5e6b6dd7ae73f56a75d2854af685ca299ebd8bf1369a5904a9R117-R118) [[3]](diffhunk://#diff-4bccda921f0a12a9db3c89e2882518e77ceacee991bc985c62b21fda4bad086dR119-R120)
* Updated `IOSWebViewManager` to use `GetKeyWindow` instead of deprecated `UIApplication.Windows` for compatibility with iOS 15+ and introduced `ActionStringTrampolineBlock` for handling unmanaged function pointers. (`src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs`) [[1]](diffhunk://#diff-38772534fe574cea1d8b0daaa0d402bcc7532f13adbbade9847ac33b12cffc40L185-L188) [[2]](diffhunk://#diff-38772534fe574cea1d8b0daaa0d402bcc7532f13adbbade9847ac33b12cffc40R210-R246)

### Enhancements to Blazor components:

* Added new buttons (`Decrement` and `Set Value`) to the Blazor sample app, enabling user interactions with JavaScript for confirmation dialogs, prompts, and alerts. (`src/Controls/samples/Controls.Sample/Pages/Blazor/Index.razor`)

### Build and project settings:

* Enabled the `AllowUnsafeBlocks` property in the `Microsoft.AspNetCore.Components.WebView.Maui.csproj` file to allow unsafe code usage. (`src/BlazorWebView/src/Maui/Microsoft.AspNetCore.Components.WebView.Maui.csproj`)

These changes improve compatibility, enhance functionality, and refine user interactions within the Maui platform and Blazor components.

### Issues Fixed

Fixes #28135

### CODE REVIEW

File: src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs [hunk 1]
```diff
@@ -123,10 +124,9 @@ public override void RunJavaScriptConfirmPanel(WKWebView webView, string message
 					cancelAction: _ => completionHandler(false)
 				);
 			}
-
-#pragma warning disable CS0672 // Member overrides obsolete member
-			public override void RunJavaScriptTextInputPanel(
-#pragma warning restore CS0672 // Member overrides obsolete member
+			
+			[Export("webView(_:runJavaScriptTextInputPanelWithPrompt:defaultText:initiatedByFrame:completionHandler:)")]
+			public void RunJavaScriptTextInputPanelWithPrompt(
```
Comment (jsuarezruiz) [inline src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs:129]: in .NET iOS we use: https://github.com/dotnet/macios/blob/29de197d989052903d126581cb768f107d256931/src/webkit.cs#L5032
that is using the deprecated method: https://developer.apple.com/documentation/webkit/webuidelegate/webview(_:runjavascripttextinputpanelwithprompt:defaulttext:initiatedby:)

The new way to go is use: https://developer.apple.com/documentation/webkit/wkuidelegate/webview(_:runjavascripttextinputpanelwithprompt:defaulttext:initiatedbyframe:completionhandler:)

File: src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs [hunk 2]
```diff
@@ -182,10 +186,8 @@ private static void PresentAlertController(
 				if (cancelAction != null)
 					AddCancelAction(controller, () => cancelAction(controller));
 
-#pragma warning disable CA1416, CA1422 // TODO:  'UIApplication.Windows' is unsupported on: 'ios' 15.0 and later
-				GetTopViewController(UIApplication.SharedApplication.Windows.FirstOrDefault(m => m.IsKeyWindow)?.RootViewController)?
+				GetTopViewController(UIApplication.SharedApplication.ConnectedScenes.OfType<UIWindowScene>().SelectMany(scene => scene.Windows).FirstOrDefault(window => window.IsKeyWindow)?.RootViewController)?
 					.PresentViewController(controller, true, null);
-#pragma warning restore CA1416, CA1422
```
Comment (mattleibow) [inline src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs:188]: Does this work if there are no scenes? We have this method: https://github.com/dotnet/maui/blob/f65f1eaad38b7e41d352383479f54b410d637c75/src/Core/src/Platform/iOS/UIApplicationExtensions.cs#L47

We should probably use that as it correctly handles iOS versions and scenes.

**Review by mattleibow — CHANGES_REQUESTED** [review]

**Review by rmarinho — CHANGES_REQUESTED** [review]
Seems tests are failing

https://dev.azure.com/xamarin/public/_build/results?buildId=142178&view=ms.vss-test-web.build-test-results-tab&runId=4160051&resultId=100030&paneView=attachments

```
/_/src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs(16707566): error MT4174: Unable to locate the block to delegate conversion method for the method System.Void Microsoft.AspNetCore.Components.WebView.Maui.IOSWebViewManager/WebViewUIDelegate::RunJavaScriptTextInputPanelWithPrompt(WebKit.WKWebView,Foundation.NSString,Foundation.NSString,WebKit.WKFrameInfo,System.Action`1<Foundation.NSString>)'s parameter #5. [/Users/builder/azdo/_work/_temp/test-dir/BuildWithDiffer1382439389/BuildWithDiffer1382439389.csproj::TargetFramework=net10.0-maccatalyst]
```

File: src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs (hunk 1 above)
Comment (mandel-macaque) [reply src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs:132]: You do not need to create your won binding, this is already present in the dotnet/macios project: https://github.com/dotnet/macios/blob/main/src/webkit.cs#L5920

File: src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs (hunk 2 above)
Comment (jsuarezruiz) [reply src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs]: Modified the code to use the extension method.

**Comment by jsuarezruiz** [comment]
> Seems tests are failing
> 
> https://dev.azure.com/xamarin/public/_build/results?buildId=142178&view=ms.vss-test-web.build-test-results-tab&runId=4160051&resultId=100030&paneView=attachments
> 
> ```
> /_/src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs(16707566): error MT4174: Unable to locate the block to delegate conversion method for the method System.Void Microsoft.AspNetCore.Components.WebView.Maui.IOSWebViewManager/WebViewUIDelegate::RunJavaScriptTextInputPanelWithPrompt(WebKit.WKWebView,Foundation.NSString,Foundation.NSString,WebKit.WKFrameInfo,System.Action`1<Foundation.NSString>)'s parameter #5. [/Users/builder/azdo/_work/_temp/test-dir/BuildWithDiffer1382439389/BuildWithDiffer1382439389.csproj::TargetFramework=net10.0-maccatalyst]
> ```

Should be fixed with the latest changes.

**Review by rmarinho — DISMISSED** [review]

File: src/Core/src/Platform/iOS/UIApplicationExtensions.cs [hunk 3]
```diff
@@ -4,7 +4,7 @@
 
 namespace Microsoft.Maui.Platform
 {
-	internal static class UIApplicationExtensions
+	public static class UIApplicationExtensions
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/UIApplicationExtensions.cs:7]: Why was this made public?

File: src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs (hunk 1 above)
Comment (mattleibow) [reply src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs:132]: I don't see that in .NET 10 preview 5...

Comment (mattleibow) [reply src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs:132]: This new change is coming in the next "big one" so we can't use it.

**Review by mattleibow — CHANGES_REQUESTED** [review]
The magic is to use the fancy code from https://github.com/dotnet/macios/issues/15728#issuecomment-2662677120

Right now this PR still throws if null is used.

I'll update

File: src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs (hunk 1 above)
Comment (mattleibow) [reply src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs:132]: Until XAMCORE 5 is ready, we need this workaround. :(

File: src/Core/src/Platform/iOS/UIApplicationExtensions.cs (hunk 3 above)
Comment (mattleibow) [reply src/Core/src/Platform/iOS/UIApplicationExtensions.cs:7]: It was needed to access methods, but those methods are good enough to expose.

**Review by mattleibow — APPROVED** [review]
LGTM

**Review by dalexsoto — APPROVED** [review]
