### PR TITLE
Weak subscription to CanExecuteChange events

### LINKED ISSUE #16124: `RefreshView` can have a memory leak with a custom `ICommand`
### Description

This problem can be illustrated with a test such as:

https://github.com/dotnet/maui/compare/main...jonathanpeppers:RefreshViewLeak

If you create a custom `ICommand` on something like a singleton `ViewModel`, and use it on a `RefreshView`, the `RefreshView` will live forever.

I think this is lower priority, as the customer samples I've seen use `Command` or `Command<T>`:

https://github.com/dotnet/maui/blob/49d22ac57ce1aeb23546f5b2f8155fa97cf002e3/src/Controls/src/Core/Command.cs#L113-L117

And `WeakEventManager` sidesteps this problem.

If we fix this, it might be worth auditing all properties of type `ICommand`.

### Steps to Reproduce

1. Create a custom `ICommand`
2. Use it on `RefreshView`
3. `RefreshView` lives forever

### Link to public reproduction project repository

https://github.com/dotnet/maui/compare/main...jonathanpeppers:RefreshViewLeak

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

### Did you find any workaround?

Use `Command`.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

This pull request introduces a mechanism for managing and cleaning up command event subscriptions when the lifetime of the `ICommand` instance exceeds that of the XAML element it's assigned to.

Example from the Unit Tests

```C#
var command = new CommandWithoutWeakEventHandler();

// The Button subscribes to "command.CanExecuteChanged", creating a strong reference
// from the command to the Button. If the command outlives the Button,
// this prevents the Button from being garbage collected, resulting in a memory leak.
// Our built-in Command implementation avoids this by using WeakEventManager,
// but custom ICommand implementations that do not use weak event patterns are prone to leaks.
{
	var button = new Button();
	button.Command = command;
}			
```

This largerly comes up with scenarios using static viewmodels or if people are using reference bindings. The key changes include the addition of a `WeakCommandSubscription` class, updates to the `ICommandElement` interface, and new unit tests to verify the functionality.

### Memory Management Enhancements:

* **Added `WeakCommandSubscription` class**: Introduced a new class to manage weak references to command subscriptions, ensuring that event handlers do not prevent garbage collection of associated objects. This includes the `CommandCanExecuteSubscription` inner class for handling `CanExecuteChanged` events. (`src/Controls/src/Core/WeakCommandSubscription.cs`)

* **Updated `ICommandElement` interface**: Added a `CleanupTracker` property to manage the lifecycle of command subscriptions. (`src/Controls/src/Core/ICommandElement.cs`)

* **Integrated `WeakCommandSubscription` in controls**: Implemented the `CleanupTracker` property in multiple controls (`Button`, `ImageButton`, `MenuItem`, `RefreshView`, `SearchBar`) to utilize the new subscription management system. [[1]](diffhunk://#diff-dbeeb2751480e86145429d30dd5ba3975839b5add80775a12791474777cbd5e5R619-R624) [[2]](diffhunk://#diff-efc9658e08fe3b783f24e1b9270bdaff4208083a016aad6990d025937841c2adR291-R298) [[3]](diffhunk://#diff-ebcf373c7c4e142e875e0df46cfb3178a88271085ddfb9d30d49ca95ff864f75R201-R206) [[4]](diffhunk://#diff-2d87a80df0a7988d1f249910b23fc95a072e4df4bd0c92c18ec6f03517cf35b7R159-R164) [[5]](diffhunk://#diff-62df0364fa952ab201982cff6814cc4698acb7ad35109ea8488056f2bbcbcf4fR163-R168)

### Command Handling Improvements:

* **Modified `CommandElement` static class**: Updated `OnCommandChanging` and `OnCommandChanged` methods to use the `CleanupTracker` for disposing of old subscriptions and creating new ones. (`src/Controls/src/Core/CommandElement.cs`)

### Unit Testing Enhancements:

* **New tests for garbage collection**: Added tests to ensure that controls with commands can be garbage collected properly and that weak event handlers are not collected prematurely. (`src/Controls/tests/Core.UnitTests/ButtonUnitTest.cs`)

* **Improved garbage collection helper**: Enhanced the `TestHelpers.Collect` method to force multiple garbage collection cycles and ensure deterministic behavior during testing. (`src/Controls/tests/Core.UnitTests/TestHelpers.cs`)

These changes collectively improve the robustness of command handling in the library while addressing potential memory management issues.

### Concerns 

- Calling Managed code from the finalizer typically isn't recommended. The only purpose of the finalizer is to cleanup `CommandCanExecuteSubscription`. The commandelement itself will cleanup without the finalizer. One approach we could take here would be to track these and then just clean them up every so often. 

### Other Notes

- WPF has a much larger solution to this https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Input/Command/CanExecuteChangedEventManager.cs#L321

### Issues Fixed

Fixes #16124

### CODE REVIEW

File: src/Controls/src/Core/WeakCommandSubscription.cs [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+				if (_commandElement != null && _commandElement.TryGetTarget(out var commandElement))
+				{
+					commandElement.CanExecuteChanged(commandElement, args);
+				}
+				else
+				{
+					Unsubscribe();
+				}
+			}
+		}
```
Comment (pictos) [inline src/Controls/src/Core/WeakCommandSubscription.cs]: I would suggest to not make the `WeakReference` nullable. with that we can simplify the code a little bit.
I don't think the `WeakReference` will prevent something to be collected, but we can test that.
What do you think?

```suggestion
		internal class CommandCanExecuteSubscription
		{
			WeakReference<ICommandElement> _commandElement;
			ICommand? _command;

			public CommandCanExecuteSubscription(ICommandElement commandElement, ICommand command)
			{
				_command = command;
				_commandElement = new WeakReference<ICommandElement>(commandElement);
				_command.CanExecuteChanged += CanExecuteChanged;
			}

			public void Unsubscribe()
			{
				if (_command is null)
				{
					return;
				}
				
				_command.CanExecuteChanged -= CanExecuteChanged;
				_command = null;
			}

			private void CanExecuteChanged(object? arg1, EventArgs args)
			{
				if ( _commandElement.TryGetTarget(out var commandElement))
				{
					commandElement.CanExecuteChanged(commandElement, args);
				}
				else
				{
					Unsubscribe();
				}
			}
		}
```

File: src/Controls/src/Core/WeakCommandSubscription.cs [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+		{
+			Dispose(true);
+			GC.SuppressFinalize(this);
+		}
+
+		protected virtual void Dispose(bool disposing)
+		{					
+			Proxy?.Unsubscribe();
+			Proxy = null;
+		}
```
Comment (mandel-macaque) [inline src/Controls/src/Core/WeakCommandSubscription.cs]: This looks correct, just some information for the reader:

1. disposing can be ignored because the class has not unmanaged resources. 
2. the finalizer is needed because we are unregistering from the event. But trusting the finalizer rather than using the Dispose method will result in a more expensive operation since we will need to qs to clean the object (https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-object-finalize#overriding-the-finalize-method)

File: src/Controls/src/Core/WeakCommandSubscription.cs [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+
+namespace Microsoft.Maui.Controls
+{
+	class WeakCommandSubscription : IDisposable
+	{
+		internal CommandCanExecuteSubscription? Proxy { get; set; }
+		public WeakCommandSubscription(ICommandElement commandElement, ICommand command)
+		{
+			Proxy = new CommandCanExecuteSubscription(commandElement, command);
+		}
```
Comment (mandel-macaque) [inline src/Controls/src/Core/WeakCommandSubscription.cs]: Does the proxy have to be a getter/setter? Do you really need the write API? What happens if a user decides to change the Proxy AND does not call the Unsubscribe in the previous one? It seems that in that case you would be leaking or keeping unwanted references. 

To reduce the chances of a leak I would made both classes IDisposable. To me it looks like you are giving the responsibility of Unsubscribe in the Dispose method to the container of the Proxy rather than the proxy itself which is error prone. 

I would change the API to:
```csharp
class WeakCommandSubscription : IDisposable {
    // other code
		protected virtual void Dispose(bool disposing)
		{					
			Proxy?.Dispose(disposing);
		}
}

internal class CommandCanExecuteSubscription : IDisposable {}
```
With the above design you are guaranteed that any CommandCanExecuteSubscription gets the Unsubscribe called no matter if it was part of a WeakCommandSubscription or not. My train of though is to try and avoid the following scenario:

```csharp
var weak = new WeakCommandSubscription (commandElement, command); // creates Proxy1
var proxy2 = new CommandCanExecuteSubscription(commandElement, command);
weak.Proxy = proxy2;  // the GC no longer will call the Unsubscribe of proxy 1 since it has not finalizer!!!!
```
We should also consider the removal of the write API if it is not needed. But that would not remove the danger of leaking objects.

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/WeakCommandSubscription.cs (hunk 1 above)
Comment (PureWeen) [reply src/Controls/src/Core/WeakCommandSubscription.cs]: Changed

File: src/Controls/src/Core/WeakCommandSubscription.cs (hunk 3 above)
Comment (PureWeen) [reply src/Controls/src/Core/WeakCommandSubscription.cs]: Modified

Let me know if that looks alright

File: src/Controls/src/Core/WeakCommandSubscription.cs (hunk 2 above)
Comment (PureWeen) [reply src/Controls/src/Core/WeakCommandSubscription.cs]: Yea, i'm not a fan of the finalizer path here. My plan is to remove the finalizer for NET10. I'm not sure what else to tie the lifecycle of the Proxy to other than the finalizer right now. 

For NET10 we're going to probably tie the life cycle to the control being attached to the visual tree. So, we will just modify the behavior of CanExecute Changed so that it only is subscribed when you're attached to the visual tree. This is a subtle behavior change so I'd prefer to just wait for NET10

File: src/Controls/src/Core/DepdendentHandle.cs [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+using System.Windows.Input;
+
+namespace System.Runtime;
+
+/// <summary>
+/// A wrapper around ConditionalWeakTable that replicates DependentHandle behavior.
+/// Creates a dependency between a primary object and a dependent object where
+/// the dependent object becomes eligible for collection when the primary is collected.
+/// </summary>
+internal class DependentHandle : IDisposable
```
Comment (PureWeen) [inline src/Controls/src/Core/DepdendentHandle.cs:16]: This type isn't available in NETSTANDARD2_0 :-( 

It was added inside NET6.0

**Review by pictos — APPROVED** [review]

**Comment by Transis-Pedro** [comment]
I've been testing this PR and it solved a lot of leaks.

It's a hit!

Thank you guys

**Review by mattleibow — APPROVED** [review]
