### PR TITLE
[Windows, MAC] - Fix Selected State Not Being Retained in CollectionView Items When PointerOver Is Applied

### LINKED ISSUE #29484: CollectionView Selected state does not work on the selected item when combined with PointerOver.
### Description

This is a repro of issue #19708 that was closed due to being stale.

I am also encountering this issue and have created a sample app with the repro.

I've confirmed that this is an issue on 9.0.14, 9.0.50 and 9.0.70 on Windows. I have not tested it on other platforms.

### Steps to Reproduce

Create a Maui App.
Define a CollectionView on the main page.
Set ItemsSource to a DataTemplate containing a label whose style declares both PointerOver and Selected visual states.
In each visual state, set BackgroundColor.
Set the ItemsSource to a simple list of strings.

Run the app and notice the PointerOver color BackgroundColor is honored but the Selected BackgroundColor is ignored.

### Link to public reproduction project repository

https://github.com/DanTravison/CollectionViewVisualStates

### Version with bug

9.0.70 SR7

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 with .Net 9.0.

### Did you find any workaround?

No.

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by prakashKannanSf3972**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause :
 
The `ChangeVisualState` method does not account for the `Selected` state in its state resolution logic. It prioritizes PointerOver over Selected, and defaults to Normal when no pointer interaction exists—even if the item is selected. This results in inconsistent visual feedback where the Selected state styling is ignored or overridden.

### Description of Change

Enhanced `IsElementInSelectedState`() extension to VisualElement that properly detects if an element is currently in the Selected visual state by inspecting the CurrentState property of all visual state groups.
 
Updated `ChangeVisualState`() to prioritize Selected over PointerOver and Normal:

When an element is enabled, it first checks if the element is in the Selected state

- If the elements with the pointer over them, it applies either the `Selected` or `PointerOver` state, depending on selection status
- If the elements are without the pointer over them, it applies either the `Selected` or `Normal` state, depending on the selection status

This change ensures a consistent visual representation of `selected` items while preserving pointer and focus behavior.

### Issues Fixed

Fixes #29484 

**Tested the behaviour in the following platforms**

- [x] Android
- [x]  Windows
- [x]  iOS
- [x] Mac

### Output

| Before| After|
|--|--|
| <video src="https://github.com/user-attachments/assets/f2f82f55-7501-4560-9b80-162b9f923f0a"> | <video src="https://github.com/user-attachments/assets/88b33563-f165-4271-bf04-97a57305d6ab">
| <video src="https://github.com/user-attachments/assets/2649e2bc-69bc-48a4-b825-0d7169a62c0d"> | <video src="https://github.com/user-attachments/assets/d531d7ac-efee-4e8a-b1f9-7235a303c487"> |

### CODE REVIEW

File: src/Controls/src/Core/VisualElement/VisualElement.cs [hunk 1]
```diff
@@ -1579,13 +1579,17 @@ protected internal virtual void ChangeVisualState()
...
-			{
-				VisualStateManager.GoToState(this, VisualStateManager.CommonStates.PointerOver);
-			}
 			else
 			{
-				VisualStateManager.GoToState(this, VisualStateManager.CommonStates.Normal);
+				bool isSelected = this.IsElementInSelectedState();
+				if (IsPointerOver)
+				{
+					VisualStateManager.GoToState(this, isSelected ? VisualStateManager.CommonStates.Selected : VisualStateManager.CommonStates.PointerOver);
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/VisualElement/VisualElement.cs]: Can simplify it reduced duplicate calls to `VisualStateManager.GoToState`:

```
string targetState = isSelected 
      ? VisualStateManager.CommonStates.Selected 
      : (IsPointerOver ? VisualStateManager.CommonStates.PointerOver : VisualStateManager.CommonStates.Normal);

  VisualStateManager.GoToState(this, targetState);
```

Comment (prakashKannanSf3972) [reply src/Controls/src/Core/VisualElement/VisualElement.cs]: @jsuarezruiz, I have updated the changes as suggested.

**Review by kubaflo — APPROVED** [review]
