### PR TITLE
[Android] Prevent Picker from Gaining Focus on Touch

### LINKED ISSUE #8546: [Android] Picker got triggered when pressing other button in CollectionView entry
### Description

I have a CollectionView where each entry contains a Picker and a Button to remove the entry.

Under certain conditions the Picker opens selection Popup when i am pressing the remove Button.

Reproduceable on Android 11, bug appers not on Windows 10. I am not able to test other platforms.

### Steps to Reproduce

1. Clone https://github.com/Tederean/CollectionViewPickerBug
2. Deploy to Android
3. Tap on Picker in second entry.
4. Select any value or cancel.
5. Press X-Button in same entry.

Expected behaviour: Entry disappears
Actual behaviour: Entry disappears and Picker popup from that entry appears.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #13503: Impossible to leave the picker with a physical keyboard
### Description

Using the arrow keys or the tab key opens the picker list when it has focus. It becomes impossible to leave the drop-down list with physical keyboard attached.

### Steps to Reproduce

Use a physical device or an emulator with DPad activated within a screen with a picker and an entry.

### Link to public reproduction project repository

https://github.com/mhamel/MauiPickerFocusIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

10.0 (Q) - API 29

### Did you find any workaround?

I'll create a custom control with a button and a popup.  At this time, I have no workaround.

### Relevant log output

_No response_

### LINKED ISSUE #15394: MAUI Picker always open up in Android 8 and below
### Description

Navigate from one page to another MAUI Picker always open, with out even selecting it on Android version 8 and below. Easily reproducible in Android Emulator.

### Steps to Reproduce

1. Clone the  repo https://github.com/sujith2ss/test
2. Build and run it on Android 8 device or emulator
3. Click on the Next Button on App
4. See the picker is opened already.

### Link to public reproduction project repository

https://github.com/sujith2ss/test

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8 and below

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #19739: [Android] Pickers reopen when the selected item is re-selected
### Description

Pickers reopen after selecting an item that's already selected. Easy to observe with a picker with only one item.

I suspect the problem comes from the code that reopens the picker on focus change: https://github.com/dotnet/maui/blob/main/src/Core/src/Handlers/Picker/PickerHandler.Android.cs#L94

### Steps to Reproduce

1. Make a new MAUI project
2. Add some pickers to the page. Having multiple ones seems to exacerbate the issue. Also having ones with only one item.
3. Tap on the pickers and re-select the selected item
4. Observe the pickers reopen after selection

### Link to public reproduction project repository

https://github.com/mfeingol/repros/tree/master/PickerFocusRepro

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

A workaround is to do this:

```C#
    class CustomPicker : Picker
    {
        public CustomPicker()
        {
            // Maui: work around https://github.com/dotnet/maui/issues/15394
            this.Focused += (s, e) => this.Unfocus();
        }
    }
```

### Relevant log output

_No response_

### LINKED ISSUE #21704: After selecting an item in the picker, the 'Unfocused' event does not trigger.
### Description

When selecting any item inside the picker, the 'Unfocused' event fails to trigger. Previously, in Xamarin Forms, it worked correctly. However, currently, it functions properly only on iOS. On Android, the event does not occur as expected; upon selecting an item, no action is taken.
image

image

image

### Steps to Reproduce

Create .NET MAUI New Project -> Select .NET 8.0 -> Add Picker Inside Page - > add Event Unfocused -> When select any item inside picker -> Unfocused event not trigger.  

### Link to public reproduction project repository

https://1drv.ms/f/s!Alibu8GDjP9aggKpS2vWOW7lZMxh?e=zt5toB

### Version with bug

8.0.14 SR3.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

_No response_

### Relevant log output

sometime getting this error when select picker-
Android.Views.InflateException: 'Binary XML file line #23 in com.abc.xyz:layout/mtrl_alert_select_dialog_item: Binary XML file line #23 in com.abc.xyz:layout/mtrl_alert_select_dialog_item: Error inflating class TextView'

### LINKED ISSUE #24862: Android - picker on hidden page opens after back navigation
### Description

The app has 3 pages. There is a picker on page 1.
After navigating modal to page 2, then to page 3 and then back to page 2 again, the picker on page 1 opens. Although page 1 is not even visible yet.

### Steps to Reproduce

In the reproduction project:

1. Navigate by clicking the button "Go to first modal page"
2. Navigate by clicking the button "Go to second modal page"
3. Click the button "Go back"
4. The app is now back on the first modal page but shows the picker dialog from main page

### Link to public reproduction project repository

https://github.com/pab6655/maui-modal-nav-picker-repro

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #28121: Picker Focused/Unfocused Events Do Not Fire on Android
### Description

The `Focused` and `Unfocused` events of `Picker` do not fire on Android when the controls gain or lose focus. This issue is only present on Android and works as expected on iOS.

Note: `Focused` only get fired first time

### Steps to Reproduce

1. Create a new .NET MAUI project.
2. Add `Picker` to the XAML layout.
3. Attach event handlers to their Focused and Unfocused events.
4. Run the app on an Android device/emulator.
5. Interact with the controls by tapping to open the picker and dismissing it.
6. Observe that the Focused and Unfocused events do not trigger.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.40 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by bhavanesh2001**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Description of Change
This PR brings `Picker` behavior on Android in line with `DatePicker` and `TimePicker`, in support of the enhancement described in [#8945](https://github.com/dotnet/maui/issues/8945).

Currently, the `Picker`'s platform control is **focusable on touch**, and a lot of custom logic has been implemented to make it work with this focus behavior. However, even with that logic, the platform control does **not lose focus automatically** when the dialog is dismissed — the `Focus` event fires, but the corresponding `Unfocus` event does **not** trigger when the dialog closes. This has led to some weird bugs.

In contrast, both `DatePicker` and `TimePicker` are **not focusable on touch**, so obviously, their `Focused` and `Unfocused` events do **not** fire.

This PR makes `Picker` behave the same way — by making it **non-focusable on Touch**, we avoid the current awkward focus lifecycle and ensure consistent behavior across all picker types, paving the way for future improvements with [#8945](https://github.com/dotnet/maui/issues/8945).

CC @PureWeen 

Supersedes #25319

Related to #8946 
Related to #6252

### Issues Fixed

Fixes #19739
Fixes #8546
Fixes #13503
Fixes #24862
Fixes #28121
Fixes #21704
Fixes #15394

### CODE REVIEW

**Comment by PureWeen** [comment]
Making a note here that we need to validate keyboard interactions and TalkBack to make sure everything works as expected

File: src/Core/src/Platform/Android/PickerManager.cs [hunk 1]
```diff
@@ -18,25 +18,14 @@ internal static class PickerManager
...
-			}
-		}
 
-		public static void OnFocusChanged(bool gainFocus, EditText sender)
-		{
-			if (gainFocus)
-				sender.CallOnClick();
-		}
 
 		static void OnKeyPress(object? sender, AView.KeyEventArgs e)
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/PickerManager.cs]: Can you delete this `OnKeyPress` code? 

This code was initially added [here](https://github.com/xamarin/Xamarin.Forms/pull/4344)

I think your PR here addresses the reason this code was initially added

File: src/Core/src/Platform/Android/PickerManager.cs [hunk 2]
```diff
@@ -18,25 +18,14 @@ internal static class PickerManager
 		public static void Init(EditText editText)
 		{
 			editText.Focusable = true;
+			editText.FocusableInTouchMode= false;
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/PickerManager.cs]: would it be possible to have the datepicker and time picker also call this code? 

someway that we can make sure all three are always working the same?

**Comment by PureWeen** [comment]
We should make sure to maintain this behavior
https://github.com/dotnet/maui/pull/25319#pullrequestreview-2393277222

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue2339.cs [hunk 3]
```diff
@@ -1,7 +1,7 @@
 ﻿using NUnit.Framework;
 using UITest.Appium;
 using UITest.Core;
-
+#if TEST_FAILS_ON_ANDROID
```
Comment (PureWeen) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue2339.cs]: We will probably want to add some extra code to make sure this test still passes

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue2339.cs (hunk 3 above)
Comment (bhavanesh2001) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue2339.cs]: Although I think firing Focus/Unfocus events based on dialog show/dismiss is questionable, I wired up mappers for Focus() and Unfocus() calls to ensure they still work.

File: src/Core/src/Handlers/Picker/PickerHandler.Android.cs [hunk 4]
```diff
@@ -86,25 +84,33 @@ public static void MapVerticalTextAlignment(IPickerHandler handler, IPicker pick
...
 		}
 
-		void OnFocusChange(object? sender, global::Android.Views.View.FocusChangeEventArgs e)
+		internal static void MapFocus(IPickerHandler handler, IPicker picker, object? args)
 		{
-			if (PlatformView == null)
-				return;
-
-			if (e.HasFocus)
+			if (handler.IsConnected() && !picker.IsFocused)
```
Comment (PureWeen) [inline src/Core/src/Handlers/Picker/PickerHandler.Android.cs]: Can we call up to ViewHandler.MapFocus for this code? 
And then we don't need to duplicate any code

All we need is the call to CallOnClick?

File: src/Core/src/Handlers/Picker/PickerHandler.Android.cs [hunk 5]
```diff
@@ -86,25 +84,33 @@ public static void MapVerticalTextAlignment(IPickerHandler handler, IPicker pick
...
+				{
+					handler.PlatformView.Focus(request);
+				}
+
+				handler.PlatformView.CallOnClick();
 			}
-			else if (_dialog != null)
+		}
+
+		internal static void MapUnfocus(IPickerHandler handler, IPicker picker, object? args)
```
Comment (PureWeen) [inline src/Core/src/Handlers/Picker/PickerHandler.Android.cs:96]: Can we call up to ViewHandler.MapUnfocus for this code?
And then we don't need to duplicate any code

File: src/Core/src/Platform/Android/MauiDatePicker.cs [hunk 6]
```diff
@@ -31,6 +32,8 @@ protected MauiDatePicker(IntPtr javaReference, JniHandleOwnership transfer) : ba
 		{
 		}
 
+		protected override IMovementMethod? DefaultMovementMethod => null;
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/MauiDatePicker.cs:37]: Can we comment the three places we are doing this with why we are doing this?

Indicate that according to the docs this MovementMethod is purely related to moving the cursor inside the box but since the text is readonly we remove it to avoid cursor related keyboard navigation?

File: src/Core/src/Handlers/Picker/PickerHandler.Android.cs [hunk 7]
```diff
@@ -86,25 +84,29 @@ public static void MapVerticalTextAlignment(IPickerHandler handler, IPicker pick
...
 		}
 
-		void OnFocusChange(object? sender, global::Android.Views.View.FocusChangeEventArgs e)
+		internal static void MapFocus(IPickerHandler handler, IPicker picker, object? args)
 		{
-			if (PlatformView == null)
-				return;
-
-			if (e.HasFocus)
+			if (handler.IsConnected() && !picker.IsFocused)
```
Comment (PureWeen) [inline src/Core/src/Handlers/Picker/PickerHandler.Android.cs]: Do we need to validate if `IsFocused` is set to true here? 

I think we don't really care do we? 
We just let the call fall through if the user has called "Focus" 

So long as "callOnclick" doesn't cause a second picker to open.

File: src/Core/src/Handlers/Picker/PickerHandler.Android.cs [hunk 8]
```diff
@@ -86,25 +84,29 @@ public static void MapVerticalTextAlignment(IPickerHandler handler, IPicker pick
...
-					OnClick(PlatformView, EventArgs.Empty);
+				ViewHandler.MapFocus(handler, picker, args);
+				handler.PlatformView.CallOnClick();
 			}
-			else if (_dialog != null)
+		}
+
+		internal static void MapUnfocus(IPickerHandler handler, IPicker picker, object? args)
+		{
+			if (handler.IsConnected() && handler is PickerHandler pickerHandler && picker.IsFocused)
```
Comment (PureWeen) [inline src/Core/src/Handlers/Picker/PickerHandler.Android.cs]: similar here
Do we care about checking if picker is focused?

**Review by PureWeen — APPROVED** [review]
