### PR TITLE
[Android] Crash removing item from CarouselView - fix

### LINKED ISSUE #19786: [Android] Crash removing item from CarouselView
### Description

Crash removing item from CarouselView.
image
_NOTE: Using 8.0.5 RC1._

### Steps to Reproduce

1. Download or sync https://github.com/rachelkang/recipeSearch
2. Launch the App on Android.
3. Add a new recipe to your list.
4. Navigate back to your recipe list.
5. Select the added recipe and then tap the remove button.

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

_No response_

### Relevant log output

```shell
0xFFFFFFFFFFFFFFFF in Android.Runtime.RuntimeNativeMethods.monodroid_debugger_unhandled_exception	C#
 	0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:13,5	C#
 	0x1D in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:27,26	C#
 	0x8 in System.ThrowHelper.ThrowArgumentOutOfRange_IndexMustBeLessException	C#
 	0x9 in System.Collections.Generic.List<object>.get_Item	C#
 	0x2 in System.Collections.Generic.List<object>.System.Collections.IList.get_Item	C#
 	0x11 in Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.ElementAt at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\ItemsSources\ObservableItemsSource.cs:228,5	C#
 	0x8 in Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.GetItem at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\ItemsSources\ObservableItemsSource.cs:67,4	C#
 	0x4F in Microsoft.Maui.Controls.Handlers.Items.MauiCarouselRecyclerView.SetCurrentItem at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\MauiCarouselRecyclerView.cs:456,4	C#
 	0xC in Microsoft.Maui.Controls.Handlers.Items.MauiCarouselRecyclerView. at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\MauiCarouselRecyclerView.cs:264,7	C#
 	0x6 in Microsoft.Maui.Dispatching.Dispatcher. at D:\a\_work\1\s\src\Core\src\Dispatching\Dispatcher.Android.cs:24,24	C#
 	0xE in Java.Lang.Thread.RunnableImplementor.Run at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36,6	C#
 	0x8 in Java.Lang.IRunnableInvoker.n_Run at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:84,4	C#
 	0x8 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:26,5	C#
```

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

Fixes https://github.com/dotnet/maui/issues/19786

https://github.com/dotnet/maui/assets/42434498/178d2c54-5d60-4136-bdae-9e35e743a3f4

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs [hunk 1]
```diff
@@ -273,6 +273,11 @@ void CollectionItemsSourceChanged(object sender, System.Collections.Specialized.
 					.Dispatch(() =>
 					{
 
+						if (carouselPosition >= observableItemsSource.Count)
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs:276]: Debugging through this one it seems like the bug here has to do with multiple collection changed events firing. 

If I break point here

image

it fires a bunch every time an item is inserted. 
Either my debugger is being weird or there is something really weird going on 

thoughts?

i think if this collectionchanged event would only fire once this would all work fine as is.

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs (hunk 1 above)
Comment (PureWeen) [reply src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs:276]: I think one of the issues here is with this code

https://github.com/dotnet/maui/blob/aad3c858d8f8c846772e269f2d25b533b2a17200/src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs#L131-L136

During startup we recreate the itemsource a bunch of times (we should only create it once)

But when we do create it more than once the old adapters aren't getting unsubscribed from :( which causes a bunch of CollectionChanged events to fire for each single action

**Review by PureWeen — APPROVED** [review]

**Comment by plppp2001** [comment]
Hi, just a heads up, #22035 just popped up, another issue with carousel view. Just letting you know.

**Comment by SarthakB26** [comment]
+1
