### PR TITLE
Correctly propagate BindingContext in all ContentView scenarios

### LINKED ISSUE #12470: ControlTemplate not propagating the BindingContext correctly
### Description

The bug manifests itself when using a `ContentView` with a custom `ControlTemplate`. For some reason, the `BindingContext` is not propagated to the children created with the `ControlTemplate`. This makes it impossible to use regular data binding in the `ControlTemplate`. For example, let's consider the following trivial scenario:

```xml
<VerticalStackLayout>
    <Label Text="{Binding Text}" />
    <ContentView>
        <ContentView.ControlTemplate>
            <ControlTemplate>
                <Label Text="{Binding Text}" />
            </ControlTemplate>
        </ContentView.ControlTemplate>
    </ContentView>
</VerticalStackLayout>
```

The first `Label` that is placed directly in the `VerticalStackLayout` displays the `Text` property form the `BindingContext` correctly. The second `Label` that is created from the `ControlTemplate` does not display anything at all.

### Steps to Reproduce

1. Run the provided sample project
2. Observe the text of the two `Label`s
- The first `Label` displays the text correctly
- The second `Label` from the `ControlTemplate` is empty

### Link to public reproduction project repository

https://github.com/ivan-todorov-progress/maui-control-template-binding-context-bug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

N/A

### Did you find any workaround?

The workaround is to propagate the `BindingContext` manually, e.g.:

```xml
<ControlTemplate>
    <Label Text="{Binding Text}" BindingContext="{Binding BindingContext, Source={RelativeSource Mode=TemplatedParent}}" />
</ControlTemplate>
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Correctly propagate BindingContext in all ContentView scenarios.

### Issues Fixed

Fixes #12470

### CODE REVIEW

File: src/Controls/src/Core/ContentView.cs [hunk 1]
```diff
@@ -21,12 +21,15 @@ protected override void OnBindingContextChanged()
 		{
 			base.OnBindingContextChanged();
 
-			View content = Content;
+			IView content = Content;
+
+			if (content == null && (this as IContentView)?.PresentedContent is IView presentedContent)
+				content = presentedContent;
+
 			ControlTemplate controlTemplate = ControlTemplate;
```
Comment (mattleibow) [inline src/Controls/src/Core/ContentView.cs:29]: I see templates here... do we have a test for templated and non-templated controls? Just want to make sure that we catch everything.

**Comment by jsuarezruiz** [comment]
Added also a sample in the .NET MAUI Gallery validating the two scenarios: using the ContentView Content and ControlTemplate properties:
image

**Review by hartez — APPROVED** [review]
