### PR TITLE
Avoid Glide target re-use when loading the same image into the same view

### LINKED ISSUE #6783: [Android] Images aren't reloading correctly when you rebind to a CollectionView
https://github.com/dotnet/maui/pull/6739 appears to have fixed the crash but it looks like the images are failing to load when you refresh a CollectionView

1) clone the following repository https://github.com/microsoft/dotnet-podcasts
2) after the images have loaded on the first page navigate to the second tab
3) navigate back to the first tab
4) the CV will be blank. The VM for this first page refreshes the data on the CV every time you navigate back to it
5) if you scroll around a bit or navigate away and then back the images will eventually show back up

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

If all the models and properties are the same, Glide just re-triggers the previous target. 

This causes issues with .NET and Task and async/await, so we set the callback (which is unique on each run) as a fallback image. This effectively makes each request unique so targets are not reused (but still uses the cache).

### Issues Fixed

Fixes #6783

This is potentially the real cause of #6464 so we may need to revisit the eager cleanups

### Testing

Since all the changes are in the java code, you can simply replace the maui.aar in the workload install folders and watch the magic happen.

### CODE REVIEW

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformInterop.java [hunk 1]
```diff
@@ -225,140 +212,110 @@ public static ViewPager2 createShellViewPager(Context context, CoordinatorLayout
...
-    public static void loadImageFromFile(ImageView imageView, String file, ImageLoaderCallback callback)
-    {
-        RequestManager glide = Glide.with(imageView);
+    private static void prepare(RequestBuilder<Drawable> builder, Target<Drawable> target, Boolean cachingEnabled, ImageLoaderCallback callback) {
+        // A special value to work around https://github.com/dotnet/maui/issues/6783 where targets
+        // are actually re-used if all the variables are the same.
+        // Adding this "error image" that will always load a null image makes each request unique,
+        // but does not affect the various caching levels.
+        builder = builder
+            .error(callback);
```
Comment (mattleibow) [inline src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformInterop.java:221]: This is the real-magic. We set the error image as the callback instance so it will always create a unique load path.

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomViewTarget.java [hunk 2]
```diff
@@ -34,10 +35,8 @@ public void onLoadFailed(@Nullable Drawable errorDrawable) {
             return;
         this.completed = true;
 
-        callback.onComplete(false,
-            errorDrawable,
-            () -> { } // TODO: explicitly release image
-        );
+        // trigger the callback out of this target
+        post(() -> callback.onComplete(false, errorDrawable, this::clear));
```
Comment (mattleibow) [inline src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomViewTarget.java:39]: Callbacks have to be on the `post` because if you try load a second image right after the first one, then you are still in the callback because the `TaskCompletionSource.SetResult()` continues on the same thread and thus all the code in C# that follows is effectively in the target still - which is not a Glide-supported operation.

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiGlideModule.java [hunk 3]
```diff
@@ -18,13 +21,16 @@
 public class MauiGlideModule extends AppGlideModule {
     @Override
     public void registerComponents(Context context, Glide glide, Registry registry) {
+        // add custom loaders
         registry.prepend(FontModel.class, FontModel.class, new FontModelLoaderFactory());
         registry.prepend(FontModel.class, Bitmap.class, new FontModelResourceDecoder());
         registry.prepend(InputStream.class, InputStream.class, new GlideInputStreamModelLoaderFactory());
+        // add workaround loader for https://github.com/dotnet/maui/issues/6783
+        registry.prepend(ImageLoaderCallback.class, ImageLoaderCallback.class, new ImageLoaderCallbackModelLoaderFactory());
```
Comment (mattleibow) [inline src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiGlideModule.java:29]: Since we added the callback as a fallback image, to avoid runtime errors in the log about unable to load the callback as an image, we create a dummy model loader that basically returns null.

**Review by Redth — APPROVED** [review]
