### PR TITLE
Account for margins on sizes returned from Editor

### LINKED ISSUE #20126: [MAUI][.NET8] ‘Review’ module jumps repeatedly when editing recipe page.
### Description

‘Review’ module jumps repeatedly when editing recipe page.

### Steps to Reproduce

1. Deploy https://github.com/rachelkang/recipeSearch to Android platform.
2. Click or tap on the 'My Recipes' tab to navigate to the 'My Recipes' page.
3. Click or tap on any Your recipes page.
4. Click or tap on the 'Edit' button.

Actual results:
The ‘Review’ module on the recipe page jumps repeatedly.
Recipe

Expected result:
The page displays normally.

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

Microsoft.Maui.Controls : 8.0.7-nightly.9909+sha.4f32463d01-azdo.8960497
.NET SDK: 8.0.200-preview.23624.5

### Version with bug

8.0.7-nightly.9909

### Is this a regression from previous behavior?

Yes, this is a regression. This issue not repro on 8.0.6+1-sha.87f59a86d4-azdo.8922564.

### Last version that worked well

8.0.6-nightly.9876+sha.abe0025c2d-azdo.8930532

### Affected platforms

Android

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

The Editor control short circuits measuring itself if the user has set EditorAutoSizeOption to Disabled. This ensures that the editor always retains the initial height it was measured with as the user types. The code that was short circuiting the measure wasn't including the margins with the returned size which was causing an infinite loop of confusion as the calling code expected the return value to have margins on it. 

### Issues Fixed

Fixes #20126

Need to verify if this fixes
https://github.com/dotnet/maui/issues/17757

### CODE REVIEW

File: src/Controls/src/Core/Editor/Editor.cs [hunk 1]
```diff
@@ -134,22 +138,38 @@ protected override Size MeasureOverride(double widthConstraint, double heightCon
...
+				Height > 0 &&
+				// If the user has changed the Margin/Width/Height then we need to re-measure
+				_previousWidthRequest == WidthRequest &&
+				_previousHeightRequest == HeightRequest)
 			{
 				if (TheSame(_previousHeightConstraint, heightConstraint) &&
 					TheSame(_previousWidthConstraint, widthConstraint))
 				{
-					return new Size(Width, Height);
+					var desiredSize = new Size(Width + Margin.HorizontalThickness, Height + Margin.VerticalThickness);
```
Comment (mattleibow) [inline src/Controls/src/Core/Editor/Editor.cs:149]: Looks like these 2 code paths are the same?

File: src/Controls/src/Core/Editor/Editor.cs [hunk 2]
```diff
@@ -134,22 +138,38 @@ protected override Size MeasureOverride(double widthConstraint, double heightCon
 		{
 			if (AutoSize == EditorAutoSizeOption.Disabled &&
 				Width > 0 &&
-				Height > 0)
+				Height > 0 &&
+				// If the user has changed the Margin/Width/Height then we need to re-measure
+				_previousWidthRequest == WidthRequest &&
+				_previousHeightRequest == HeightRequest)
```
Comment (mattleibow) [inline src/Controls/src/Core/Editor/Editor.cs:144]: The comment says "changed" but the condition is `==`?

**Comment by PureWeen** [comment]
UI Test failures are unrelated and being resolved by other PRs

**Review by mattleibow — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]
