### PR TITLE
[iOS] Map pin InfoWindowClicked event is never fired

### LINKED ISSUE #13123: [iOS] Map pin InfoWindowClicked event is never fired
### Description

Attempt to use pin.InfoWindowClicked on iOS. The event is never fired when the info window is clicked. Works correctly on Android.

### Steps to Reproduce

1. Open attached repo project and run the app. 
2. Set a breakpoint on the System.Diagnostics line where a message should be printed when the info window is clicked. 
3. Run the app and click on the marker - it will display an info window with some address details.
4. Click on the info window and it simply disappears - the breakpoint is never hit.

### Link to public reproduction project repository

https://github.com/smitha-cgi/InfoWindowTest.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5, 16

### Did you find any workaround?

No

### Relevant log output

```shell
dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
runtimes-windows           7.0.2/7.0.100          VS 17.5.33326.253
maui-windows               7.0.59/7.0.100         VS 17.5.33326.253
maui-maccatalyst           7.0.59/7.0.100         VS 17.5.33326.253
maccatalyst                16.2.1007/7.0.100      VS 17.5.33326.253
maui-ios                   7.0.59/7.0.100         VS 17.5.33326.253
ios                        16.2.1007/7.0.100      VS 17.5.33326.253
maui-android               7.0.59/7.0.100         VS 17.5.33326.253
android                    33.0.26/7.0.100        VS 17.5.33326.253
```

### PR DESCRIPTION
**Pull request by KarthikRajaKalaimani**
### Issue Details:

In Map control the InfoWindowClicked event of Pin is not fired in iOS and MacCatalyst platform. 
        
### Root Cause:

The InfoWindowClicked event is properly implemented in the OnCalloutClicked method and correctly wired to gesture recognizers in AttachGestureToPin, but the custom annotation view creation delegate was not assigned to the MKMapView, causing the gesture recognizers to never be attached to the actual annotation views displayed on the map.

### Description of Change:

I have properly assigned the custom annotation view creation delegate to the MKMapView in the constructor, like in Xamarin.Forms implementation. 

**Tested the behavior in the following platforms.**

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Reference:

N/A

### Issues Fixed:

Fixes #13123  

### Screenshots
| Before  | After  |
|---------|--------|
|   <Video src="https://github.com/user-attachments/assets/cdf94a45-8907-42b9-a3bb-02bb604b7716" width="300" height="600">  |    <Video src="https://github.com/user-attachments/assets/7bd8b4c5-a689-49c5-a7f2-b85b87c4e88f" width="300" height="600">  |

### CODE REVIEW

**Review by jfversluis — CHANGES_REQUESTED** [review]
In the Xamarin.Forms counterpart we also unassign this value, should we do that also here in the `Cleanup`?

**Comment by KarthikRajaKalaimani** [comment]
> In the Xamarin.Forms counterpart we also unassign this value, should we do that also here in the `Cleanup`?

It's not necessary to explicitly clean up GetViewForAnnotation here as we did in Xamarin.Forms.

File: src/Core/maps/src/Platform/iOS/MauiMKMapView.cs [hunk 1]
```diff
@@ -20,6 +20,7 @@ public MauiMKMapView(IMapHandler handler)
 		{
 			_handlerRef = new WeakReference<IMapHandler>(handler);
 			OverlayRenderer = GetViewForOverlayDelegate;
+			base.GetViewForAnnotation = GetViewForAnnotation;
```
Comment (jsuarezruiz) [inline src/Core/maps/src/Platform/iOS/MauiMKMapView.cs:24]: Can include a comment?

```
// Assign custom annotation view delegate to enable gesture recognition on annotation callouts.
```

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13123.cs [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+            App.TapCoordinates(centerX, centerY);
+        }
+
+        private void TapInfoWindow()
+        {
+            var mapElement = App.FindElement("Map");
+            var rect = mapElement.GetRect();
+#if IOS
+            var centerX = rect.X + rect.Width / 2;
+            var infoWindowY = rect.Y + rect.Height / 2 - 30;
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13123.cs]: Could improve that "magic numbers" creating some constants, like `const int InfoWindowOffsetFromCenter = 30;`
But is in the sample, is fine.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13123.cs (hunk 2 above)
Comment (KarthikRajaKalaimani) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13123.cs]: I have added the const integer for center offset.

File: src/Core/maps/src/Platform/iOS/MauiMKMapView.cs (hunk 1 above)
Comment (KarthikRajaKalaimani) [reply src/Core/maps/src/Platform/iOS/MauiMKMapView.cs:24]: > Can include a comment?
> 
> ```
> // Assign custom annotation view delegate to enable gesture recognition on annotation callouts.
> ```

I have added the comment.

**Review by jfversluis — APPROVED** [review]
