### PR TITLE
Making sure FindMauiContext fallbacks to default for the title icon i…

### LINKED ISSUE #21518: NavigationPage.SetTitleIconImageSource Cases crash on iOS
### Description

Setting the TitleIconImageSource property causes the app to crash on iOS.
This works correctly on Android. 

### Steps to Reproduce

1. Create a new MAUI app.
2. Create a NavigationPage and pass a page to it.
3. In the page's constructor  set the TitleICoSource for the navigation page(`NavigationPage.SetTitleIconImageSource(this, "dotnet_bot.png");`)
4. Run. the app on an iOS device and simulator
5. Observe the app crashes after navigating.

### Link to public reproduction project repository

https://github.com/atoghyani/SetTitleIconImageSourceCrash

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2

### Did you find any workaround?

_No response_

### Relevant log output

```shell
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.ImageSourceExtensions.GetPlatformImageAsync(IImageSource imageSource, IMauiContext mauiContext)
   at Microsoft.Maui.ImageSourceExtensions.LoadImage(IImageSource source, IMauiContext mauiContext, Action`1 finished)
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.ParentingViewController.UpdateTitleImage(Container titleViewContainer, ImageSource titleIcon)
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.ParentingViewController.UpdateTitleArea(Page page)
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.CreateViewControllerForPage(Page page)
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.OnPushAsync(Page page, Boolean animated)
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.<ViewDidLoad>b__53_0(Page p)
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2594
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 60
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at SetTitleIconImageSourceCrash.Program.Main(String[] args) in /Users/ariantoghyani/Projects/SetTitleIconImageSourceCrash/SetTitleIconImageSourceCrash/Platforms/iOS/Program.cs:line 13
```

### PR DESCRIPTION
**Pull request by atoghyani**
### Description of Change

Passing a true value to FindMauiContext to make sure context is not null for Title Icon on iOS.
The ImageSource does not have a handler or a parent, so the method will return a null value and causes a crash.

### Issues Fixed

Fixes #21518

### CODE REVIEW

**Review by rmarinho — DISMISSED** [review]
Hi @atoghyani we add a test for this, could be a UITest or Device test I think, if it crashes  with the fix could be easy to reproduce on a test.

**Comment by atoghyani** [comment]
> Hi @atoghyani we add a test for this, could be a UITest or Device test I think, if it crashes with the fix could be easy to reproduce on a test.

Added a Device test for this:

Before:

Simulator Screenshot - iPhone 15 Pro Max - 2024-04-01 at 14 13 54
```    at Microsoft.Maui.ImageSourceExtensions.GetPlatformImageAsync(IImageSource imageSource, IMauiContext mauiContext) in /Users/ariantoghyani/Projects/maui/src/Core/src/ImageSources/ImageSourceExtensions.cs:line 40
   at Microsoft.Maui.ImageSourceExtensions.LoadImage(IImageSource source, IMauiContext mauiContext, Action`1 finished) in /Users/ariantoghyani/Projects/maui/src/Core/src/ImageSources/ImageSourceExtensions.cs:line 25
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.ParentingViewController.UpdateTitleImage(Container titleViewContainer, ImageSource titleIcon) in /Users/ariantoghyani/Projects/maui/src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs:line 1454
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.ParentingViewController.UpdateTitleArea(Page page) in /Users/ariantoghyani/Projects/maui/src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs:line 1432
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.ParentingViewController.HandleChildPropertyChanged(Object sender, PropertyChangedEventArgs e) in /Users/ariantoghyani/Projects/maui/src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs:line 1284
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName) in /Users/ariantoghyani/Projects/maui/src/Controls/src/Core/Element/Element.cs:line 571
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in /Users/ariantoghyani/Projects/maui/src/Controls/src/Core/BindableObject.cs:line 641
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in /Users/ariantoghyani/Projects/maui/src/Controls/src/Core/BindableObject.cs:line 569
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value) in /Users/ariantoghyani/Projects/maui/src/Controls/src/Core/BindableObject.cs:line 474
   at Microsoft.Maui.Controls.NavigationPage.SetTitleIconImageSource(BindableObject bindable, ImageSource value) in /Users/ariantoghyani/Projects/maui/src/Controls/src/Core/NavigationPage/NavigationPage.cs:line 348
   at Microsoft.Maui.DeviceTests.NavigationPageTests.<>c__DisplayClass2_0.<<SettingTitleIconImageSourceDoesntCrash>b__0>d.MoveNext() in /Users/ariantoghyani/Projects/maui/src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs:line 78
--- End of stack trace from previous location ---
   at Microsoft.Maui.DeviceTests.ControlsHandlerTestBase.<>c__DisplayClass16_1`1.<<CreateHandlerAndAddToWindow>b__1>d[[Microsoft.Maui.DeviceTests.Stubs.WindowHandlerStub, Microsoft.Maui.Controls.DeviceTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in /Users/ariantoghyani/Projects/maui/src/Controls/tests/DeviceTests/ControlsHandlerTestBase.cs:line 252
--- End of stack trace from previous location ---
   at Microsoft.Maui.DeviceTests.ControlsHandlerTestBase.<>c__DisplayClass30_0`1.<<SetupWindowForTests>b__0>d[[Microsoft.Maui.DeviceTests.Stubs.WindowHandlerStub, Microsoft.Maui.Controls.DeviceTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in /Users/ariantoghyani/Projects/maui/src/Controls/tests/DeviceTests/ControlsHandlerTestBase.iOS.cs:line 29
--- End of stack trace from previous location ---
   at Microsoft.Maui.DeviceTests.ControlsHandlerTestBase.<>c__DisplayClass30_0`1.<<SetupWindowForTests>b__0>d[[Microsoft.Maui.DeviceTests.Stubs.WindowHandlerStub, Microsoft.Maui.Controls.DeviceTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in /Users/ariantoghyani/Projects/maui/src/Controls/tests/DeviceTests/ControlsHandlerTestBase.iOS.cs:line 86
--- End of stack trace from previous location ---
   at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass3_0.<<DispatchAsync>b__0>d.MoveNext() in /Users/ariantoghyani/Projects/maui/src/Core/src/Dispatching/DispatcherExtensions.cs:line 88
--- End of stack trace from previous location ---
   at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass2_0`1.<<DispatchAsync>b__0>d[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in /Users/ariantoghyani/Projects/maui/src/Core/src/Dispatching/DispatcherExtensions.cs:line 67
--- End of stack trace from previous location ---
   at Microsoft.Maui.DeviceTests.ControlsHandlerTestBase.<>c__DisplayClass16_0`1.<<CreateHandlerAndAddToWindow>b__0>d[[Microsoft.Maui.DeviceTests.Stubs.WindowHandlerStub, Microsoft.Maui.Controls.DeviceTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in /Users/ariantoghyani/Projects/maui/src/Controls/tests/DeviceTests/ControlsHandlerTestBase.cs:line 167
--- End of stack trace from previous location ---
   at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass3_0.<<DispatchAsync>b__0>d.MoveNext() in /Users/ariantoghyani/Projects/maui/src/Core/src/Dispatching/DispatcherExtensions.cs:line 88
--- End of stack trace from previous location ---
   at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass2_0`1.<<DispatchAsync>b__0>d[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in /Users/ariantoghyani/Projects/maui/src/Core/src/Dispatching/DispatcherExtensions.cs:line 67
--- End of stack trace from previous location ---
   at Microsoft.Maui.DeviceTests.NavigationPageTests.SettingTitleIconImageSourceDoesntCrash() in /Users/ariantoghyani/Projects/maui/src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs:line 74
--- End of stack trace from previous location ---
``` 

After:

Simulator Screenshot - iPhone 15 Pro Max - 2024-04-01 at 14 22 26

**Comment by atoghyani** [comment]
@dotnet-policy-service agree

File: src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs [hunk 1]
```diff
@@ -1451,7 +1451,7 @@ void UpdateTitleImage(Container titleViewContainer, ImageSource titleIcon)
 				}
 				else
 				{
-					titleIcon.LoadImage(titleIcon.FindMauiContext(), result =>
+					titleIcon.LoadImage(titleIcon.FindMauiContext(true), result =>
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs:1454]: Seems similar to https://github.com/dotnet/maui/pull/14634, @PureWeen Thoughts?

Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs:1454]: I think you can just use the `MauiContext` that's on this class and call that good

**Review by PureWeen — APPROVED** [review]

**Comment by pratik088** [comment]
How to resolve this issue? I am still having this issue currently on my maui iOS app.
