### PR TITLE
Switches to UIResponder for App/Scene delegates

### LINKED ISSUE #4390: iOS and MacCatalyst MauiApplicationDelegate should derive from UIResponder
### Description

See: https://github.com/xamarin/xamarin-templates/commit/088e308ae7ae3982f04f31a53d32dd4dadb6253c

In order to override things like `BuildMenu`, the app delegate really needs to derive from `UIResponder` instead of `UIApplicationDelegate`, but it should implement `IUIApplicationDelegate`.

 - [ ] Update MauiUIApplicationDelegate to derive from `UIResponder, IUIApplicationDelegate` 
 - [ ] Update the templates if/as necessary (probably need some [Export] attributes for things overridden)

### Steps to Reproduce

.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

.

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Redth**
This is the proper inheritence chain and allows us to use things like overriding the BuildMenu method.

This fixes #4390

### CODE REVIEW

**Review by dalexsoto — APPROVED** [review]
Looks good to me!

File: src/Core/src/Platform/iOS/ApplicationExtensions.cs [hunk 1]
```diff
@@ -35,14 +35,14 @@ public static void CreateNativeWindow(this UIApplicationDelegate nativeApplicati
 				dicts.Add(launchOptions);
 
 			var window = CreateNativeWindow(application, null, dicts.ToArray());
-			if (window is not null)
+			if (window is not null && nativeApplication is UIApplicationDelegate nativeAppDelegate)
 			{
-				nativeApplication.Window = window;
-				nativeApplication.Window.MakeKeyAndVisible();
+				nativeAppDelegate.Window = window;
+				nativeAppDelegate.Window?.MakeKeyAndVisible();
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/ApplicationExtensions.cs:41]: I am wondering if we need this cast. Right now, this code might not actually work because it is NOT this type. I think with objc protocols, we need to use the interface. The reason they do not exist on the C# interfaces is because they are optional. So we should use the _Extensions type:

https://docs.microsoft.com/en-us/dotnet/api/uikit.uiapplicationdelegate_extensions.getwindow?view=xamarin-ios-sdk-12

File: src/Core/src/Platform/iOS/ApplicationExtensions.cs [hunk 2]
```diff
@@ -62,10 +62,10 @@ public static void CreateNativeWindow(this UIWindowSceneDelegate sceneDelegate,
 			}
 
 			var window = CreateNativeWindow(application, scene as UIWindowScene, dicts.ToArray());
-			if (window is not null)
+			if (window is not null && sceneDelegate is UIWindowSceneDelegate windowSceneDelegate)
```
Comment (drasticactions) [inline src/Core/src/Platform/iOS/ApplicationExtensions.cs:65]: If the MAUI Delegate is IUIWindowSceneDelegate and there's a cast check for UIWindowSceneDelegate, would this cast work? Shouldn't it be `IUIWindowSceneDelegate`?

File: src/Core/src/Platform/iOS/ApplicationExtensions.cs (hunk 1 above)
Comment (dalexsoto) [reply src/Core/src/Platform/iOS/ApplicationExtensions.cs:41]: Great catch I missed it, yeah no need for the cast, you have to use the extensions ones, great catch @mattleibow I should not review during calls...

Comment (Redth) [reply src/Core/src/Platform/iOS/ApplicationExtensions.cs]: Should be updated now

File: src/Core/src/Platform/iOS/ApplicationExtensions.cs (hunk 2 above)
Comment (Redth) [reply src/Core/src/Platform/iOS/ApplicationExtensions.cs]: Yeah same as above comment, switched to use Get/SetWindow calls... Thanks for your eyes on this, wanted to be sure this didn't impact hot reload :)

Comment (drasticactions) [reply src/Core/src/Platform/iOS/ApplicationExtensions.cs]: Yep, I think you're good then. I don't think this should impact Hot Reload, as far as I can see.

**Review by drasticactions — APPROVED** [review]

**Comment by mattleibow** [comment]
Just a note that this is a massive breaking change for anyone that has any extension methods or parameters that took the concrete class, but this is definitely a more future-proof interface to use. Should we ever actually use the concrete type for extensions/parameters? It is an iOS protocol afterall.

**Review by mattleibow — APPROVED** [review]

**Comment by Redth** [comment]
Maybe this should be made `virtual`... https://github.com/dotnet/maui/pull/4391/files#diff-2b4bb95e12307423f7126d91b43a1511b68d00535e9f2b5f535af85d7a388333R43

**Review by dalexsoto — APPROVED** [review]
now for reals 👍
