### PR TITLE
[Android] Toolbar overflow menu icon color

### LINKED ISSUE #23563: Unable to set toolbar overflow menu color if not using shell.
### Description

If you are using Shell you can change the toolbar overflow icon on Android to match the Shell foreground color. This feature seems to be fixed with #15612 but that fix only applies to Shell. If you are not using Shell and are using a NavigationPage there does not seem to be a way to apply the color.

Shell (working):
image

NavigationPage (not working):
image

### Steps to Reproduce

1) Add a toolbar to a MAUI page with overflow (secondary) items.

```xaml
<ContentPage.ToolbarItems>
    <ToolbarItem IconImageSource="dotnet_bot.png" Priority="0" />
    <ToolbarItem Text="Some text" Priority="1" />
    <ToolbarItem Text="Menu option 1" Priority="2" Order="Secondary" />
    <ToolbarItem Text="Menu option 2" Priority="3" Order="Secondary" />
    <ToolbarItem Text="Menu option 3" Priority="4" Order="Secondary" />
</ContentPage.ToolbarItems>
```

2) Change the colors of the toolbar icons and text.

```xaml
<Style TargetType="Shell" ApplyToDerivedTypes="True">
    <Setter Property="Shell.BackgroundColor" Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource OffBlack}}" />
    <Setter Property="Shell.ForegroundColor" Value="Purple" />
    <Setter Property="Shell.TitleColor" Value="Orange" />
    <Setter Property="Shell.DisabledColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray950}}" />
    <Setter Property="Shell.UnselectedColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray200}}" />
    <Setter Property="Shell.NavBarHasShadow" Value="False" />
    <Setter Property="Shell.TabBarBackgroundColor" Value="CornflowerBlue" />
    <Setter Property="Shell.TabBarForegroundColor" Value="Orange" />
    <Setter Property="Shell.TabBarTitleColor" Value="Orange" />
    <Setter Property="Shell.TabBarUnselectedColor" Value="DarkOrange" />
</Style>

<Style TargetType="NavigationPage">
    <Setter Property="BarBackgroundColor" Value="CornflowerBlue" />
    <Setter Property="BarTextColor" Value="Orange" />
    <Setter Property="IconColor" Value="Orange" />
</Style>
```

3) If you are using Shell, the overflow icon will change color.
image

if you are not using Shell, the overflow icon will not change color.
image
 
 (If you are using the [reproduction repository](https://github.com/chrisg32/MAUI-Bug-Toolbar-Overflow-Icon-Color) you can switch between Shell and no-Shell in [App.xaml.cs](https://github.com/chrisg32/MAUI-Bug-Toolbar-Overflow-Icon-Color/blob/main/MAUIToolbarDemo/App.xaml.cs).

### Link to public reproduction project repository

https://github.com/chrisg32/MAUI-Bug-Toolbar-Overflow-Icon-Color

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13 - API 33

### Did you find any workaround?

We have not found a work around to this issue. Using shell would require an entire refactor of our application.

### Relevant log output

_No response_

### LINKED ISSUE #29184: Change the more menu button on MAUI ContentPage.ToolbarItems
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Change-the-more-menu-button-on-MAUI-Cont/10850018)._

---
Hello, we are migrating our app from XAMARIN to MAUI, all is going ok, but,  we met a problem: the three button of the ToolbarItems are black and we need them white... no way to have them in white...

We read documentation and googled but no clear info is available.. can you please help me? 

---
#### Feedback Bot on 2/16/2025, 07:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Angelo Lazzari on 3/4/2025, 10:12 PM: 

<p>is there any news on this please? thanks</p>

#### Angelo Lazzari on 3/18/2025, 02:23 AM: 

<p>Hello, news on this? thank you very much</p>

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

The icon color was respected when setting this value directly for the content page `NavigationPage.IconColor="Red"`, but if it was not set there then it has not been picked from its parent navigation page

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/23563
Fixes https://github.com/dotnet/maui/issues/29184

|Before|After|
|--|--|
|||

### CODE REVIEW

File: src/Controls/src/Core/NavigationPage/NavigationPageToolbar.cs [hunk 1]
```diff
@@ -265,7 +265,7 @@ void ApplyChanges(NavigationPage navigationPage)
 		}
 
 		Color GetBarTextColor() => _currentNavigationPage?.BarTextColor;
-		Color GetIconColor() => (_currentPage != null) ? NavigationPage.GetIconColor(_currentPage) : null;
+		Color GetIconColor() => NavigationPage.GetIconColor(_currentPage) ?? NavigationPage.GetIconColor(_currentNavigationPage);
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/NavigationPage/NavigationPageToolbar.cs:268]: "The icon color was respected when setting this value directly for the content page NavigationPage.IconColor="Red", but if it was not set there then it has not been picked from its parent navigation page"

Only happens on Android?

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23563.cs [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+		}
+
+		public override string Issue => "Unable to set toolbar overflow menu color if not using shell";
+
+		[Test]
+		[Category(UITestCategories.Navigation)]
+		public void OverflowIconShouldBeRed()
+		{
+			App.WaitForElement("Label");
+			VerifyScreenshot();
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23563.cs:21]: I know is an Android bug, but, to validate and align the behavior between all platforms, I think this test have sense to run everywhere.

File: src/Controls/src/Core/NavigationPage/NavigationPageToolbar.cs (hunk 1 above)
Comment (kubaflo) [reply src/Controls/src/Core/NavigationPage/NavigationPageToolbar.cs:268]: Yes, but iOS doesn't have this three-dots overflow icon

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23563.cs (hunk 2 above)
Comment (kubaflo) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23563.cs:21]: Yea, I disabled it because iOS doesn't have the overflow icon and I don't know how Windows behaves
Simulator Screenshot - iPhone 16 Pro Max - 2024-10-31 at 14 25 20

Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23563.cs:21]: Snapshots available in the latest build.
image

Could you commit the images?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23563.cs (hunk 2 above)
Comment (kubaflo) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23563.cs:21]: Done :)

**Comment by jsuarezruiz** [comment]
This PR should also fix https://github.com/dotnet/maui/issues/29184

**Review by jfversluis — APPROVED** [review]
