### PR TITLE
Bring back some aspect of ConvertView on TableView and avoid AT_MOST Measure

### LINKED ISSUE #5924: TableView with Picker
### Description

After section an option in the Picker, instead of showing the selection the Label and the Picker disappear from the screen.
image
image

### Steps to Reproduce

Reproduce Project: https://github.com/sretz/Reproduce.TableViewPicker

Code:
```xml
    <TableView Intent="Settings">
        <TableRoot>
            <TableSection Title="Locations">
                <ViewCell>
                    <AbsoluteLayout>
                        <Label Text="Canon: " HorizontalOptions="Start" VerticalOptions="Center" AbsoluteLayout.LayoutBounds="0,0.5" AbsoluteLayout.LayoutFlags="PositionProportional"/>
                        <Picker x:Name="canon" HorizontalOptions="End" VerticalOptions="Center" AbsoluteLayout.LayoutBounds="1,0.5" AbsoluteLayout.LayoutFlags="PositionProportional"/>
                    </AbsoluteLayout>
                </ViewCell>
            </TableSection>
        </TableRoot>
    </TableView>
```

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Andriod Pixel 5 - API 30 (Andriod 11)

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

We started hitting an issue on our legacy tests where the `EntryCell` started causing the ContentPage to get recycled. AFAICT this was caused by our changes here https://github.com/dotnet/maui/pull/19723. That PR disables recycling but we still return the same platformView using our handler recycling. That change was causing `OnAttachedToWindow` to fire twice which appeared to put the `EditText` field into a state where it would leak. 

Disabling `ConvertView` but returning a previously return view appears to cause `ListView` to behave in unexpected way. The comment [here](https://github.com/dotnet/maui/pull/20130/files#diff-5c5e3b1543ba43e0afdad3300dbbe6cff4be664d62ab6bc1b3adadca0b44bae0R91-R108) expands on the platform reasons specifically. It basically comes down to Androids expectation when it calls "getView", if the convertView is null then it needs to return a completely new view that's never been used before, if the convertView isn't null then you're expected to use that view. If you violate that pattern then the state of internal affairs gets out of line.

The main fix, I would say, are the changes to converting `AT_MOST` to `EXACT`. The way we do view recycling is just completely incompatible with how `AT_MOST` works. Ideally we could make `AT_MOST` work but we would need to figure out how to juggle between the random scrap views `Android` creates vs the actual views attached to the window. 

### Issues Fixed

Fixes #5924

### CODE REVIEW

**Comment by PureWeen** [comment]
iOS Failures are unrelated

File: src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs [hunk 1]
```diff
@@ -107,7 +137,10 @@ public override SizeRequest GetDesiredSize(double widthConstraint, double height
 							continue;
 						}
 
-						AView listItem = _adapter.GetView(i, null, Control);
+						var platformView = cell.Handler?.PlatformView as AView;
```
Comment (mattleibow) [inline src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs:140]: Should this be ToPlatform()? If we don't want to create, will it break if it is using a wrapper/container view? Or is that not possible with these views

File: src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs [hunk 2]
```diff
@@ -107,7 +137,10 @@ public override SizeRequest GetDesiredSize(double widthConstraint, double height
...
+						var convertView = (platformView?.Parent as AView) ?? platformView;
```
Comment (mattleibow) [inline src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs:141]: How do we know parent is the right view to use?

File: src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs [hunk 3]
```diff
@@ -107,7 +137,10 @@ public override SizeRequest GetDesiredSize(double widthConstraint, double height
...
+
+						AView listItem = _adapter.GetView(i, convertView, Control);
 						int widthSpec;
```
Comment (mattleibow) [inline src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs:145]: A few lines down, I see an atmost... Is that correct?

**Review by mattleibow — COMMENTED** [review]
Looking good, just some questions on things.

File: src/Controls/samples/Controls.Sample.UITests/Issues/Issue5555.cs [hunk 4]
```diff
@@ -0,0 +1,123 @@
+using System;
+using System.Collections.Generic;
+using System.Threading.Tasks;
+using Microsoft.Maui.Controls;
+
+namespace Maui.Controls.Sample.Issues
+{
+	[Issue(IssueTracker.None, 5555, "Memory leak when SwitchCell or EntryCell", PlatformAffected.iOS)]
+	public class Issue5555 : TestContentPage
```
Comment (jsuarezruiz) [inline src/Controls/samples/Controls.Sample.UITests/Issues/Issue5555.cs:9]: Could with the changes from this PR include the ListView in the `HandlerDoesNotLeak `test?

File: src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs (hunk 2 above)
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs:141]: Should use here an extension method searching a parent of an specific type?

File: src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs [hunk 5]
```diff
@@ -107,7 +137,10 @@ public override SizeRequest GetDesiredSize(double widthConstraint, double height
 							continue;
 						}
 
-						AView listItem = _adapter.GetView(i, null, Control);
+						var platformView = cell.Handler?.PlatformView as AView;
+						var convertView = (platformView?.Parent as AView) ?? platformView;
+
+						AView listItem = _adapter.GetView(i, convertView, Control);
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs:143]: Could this be null?, because the PlatformView and the Parent is null.

File: src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ViewCellRenderer.cs [hunk 6]
```diff
@@ -47,16 +47,25 @@ protected override AView GetCellCore(Cell item, AView convertView, ViewGroup par
 			var view = (IPlatformViewHandler)cell.View.ToHandler(cell.FindMauiContext());
 			cell.View.IsPlatformEnabled = true;
 
-			ViewCellContainer c = view.PlatformView.GetParentOfType<ViewCellContainer>();
+			// If the convertView is null we don't want to return the same view, we need to return a new one.
+			// We should probably do this for ListView as well
+			if (ParentView is TableView)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ViewCellRenderer.cs:52]: Can we create an issue linking to this comment to remember to review the same changes with the ListView?

File: src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs (hunk 2 above)
Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs:141]: I'll add a comment

Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs:141]: I don't think we need to complicate it that much. The cells are only ever added to `ConditionalFocusLayout`. That's the only type that we use inside the TableView

File: src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs (hunk 5 above)
Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewRenderer.cs:143]: `listItem` won't be null but the convertView might. Which is fine if this is the first time the handler is being realized.

File: src/Controls/samples/Controls.Sample.UITests/Issues/Issue5555.cs (hunk 4 above)
Comment (PureWeen) [reply src/Controls/samples/Controls.Sample.UITests/Issues/Issue5555.cs:9]: Yea, this scenario is somewhat specific to being pushed to and then having a layout performed with the app. I'd worry about being inaccurate moving to `HandlerDoesNotLeak`

**Comment by PureWeen** [comment]
Android UITest failure unrelated - HideSoftInputOnTappedPageTest
