### PR TITLE
Fix AdaptiveTriggers

### LINKED ISSUE #7242: [Windows] [Scenario Day] Adaptive Trigger on StackLayout crashes  Windows.
### Description

Following https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/triggers, setting up an adaptive triggers on StackLayout crashes the app. 

 <Style TargetType="StackLayout">
        <Setter Property="VisualStateManager.VisualStateGroups">
            <VisualStateGroupList>
                <VisualStateGroup>
                    <VisualState x:Name="Vertical">
                        <VisualState.StateTriggers>
                            <AdaptiveTrigger MinWindowWidth="0" />
                        </VisualState.StateTriggers>
                        <VisualState.Setters>
                            <Setter Property="Orientation"
                                Value="Vertical" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="Horizontal">
                        <VisualState.StateTriggers>
                            <AdaptiveTrigger MinWindowWidth="800" />
                        </VisualState.StateTriggers>
                        <VisualState.Setters>
                            <Setter Property="Orientation"
                                Value="Horizontal" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateGroupList>
        </Setter>
    </Style>

### Steps to Reproduce

[MauiApp1.zip](https://github.com/drasticactions/Archiverse/files/8710339/MauiApp1.zip)

Download \\ddfiles\Team\XAML\User\chabiss\Maui\MauiApp1.zip
open the app
Run on Windows
Result:
{Microsoft.UI.Xaml.UnhandledExceptionEventArgs} | Microsoft.UI.Xaml.UnhandledExceptionEventArgs
  | ▶ Exception | {"Catastrophic failure (0x8000FFFF (E_UNEXPECTED))"} | System.Exception {System.Runtime.InteropServices.COMException}
  | Handled | false | bool
  | Message | "Microsoft.UI.Xaml.Controls.Frame.NavigationFailed was unhandled." | string

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.22000.194

### Did you find any workaround?

No so far

### Relevant log output

_No response_

### LINKED ISSUE #8492: AdaptiveTriggers not working
### Description

AdaptiveTriggers not working in Maui app or I'm missing some instruction?

### Steps to Reproduce

1. Create MAUI App.
2. Add this code to MainPage and run the app:
[Example.txt](https://github.com/dotnet/maui/files/9033088/Example.txt)

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android & windows 11

### Did you find any workaround?

No.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix AdaptiveTriggers.

```
<Style TargetType="StackLayout">
    <Setter Property="VisualStateManager.VisualStateGroups">
        <VisualStateGroupList>
            <VisualStateGroup>
                <VisualState x:Name="Vertical">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="0" />
                    </VisualState.StateTriggers>
                    <VisualState.Setters>
                        <Setter Property="BackgroundColor"
                        Value="Red"   />
                    </VisualState.Setters>
                </VisualState>
                <VisualState x:Name="Horizontal">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="600" />
                    </VisualState.StateTriggers>
                    <VisualState.Setters>
                        <Setter Property="BackgroundColor"
                        Value="Green"   />
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
        </VisualStateGroupList>
    </Setter>
</Style>
```

ContentPage
fix-8492-cp

NavigationPage
fix-8492

Shell
fix-8492-shell

### Issues Fixed

Fixes #8492 
fixes #7242

### CODE REVIEW

**Review by chabiss — APPROVED** [review]

File: src/Controls/src/Core/AdaptiveTrigger.cs [hunk 1]
```diff
@@ -72,7 +72,15 @@ void AttachEvents()
 			if (_window is not null)
 				_window.PropertyChanged += OnWindowPropertyChanged;
 
-			_page = _window?.Page;
+			var page = _window?.Page;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/AdaptiveTrigger.cs:75]: We can create an extension method with this piece of code.

**Review by mattleibow — CHANGES_REQUESTED** [review]
What happen when shell does a navigation or something that replaces the page occurs? The existing code is not perfect as it attaches to the page size event, but what happens when the window replaced the page?

I wonder if there is some other way we should be doing this - maybe looking up the view hierarchy and getting the first page and then tracking that?

What happens if the view that this trigger is attached to moves from one page to another - like for drag & drop?

**Review by mattleibow — APPROVED** [review]
