### PR TITLE
[Android] Fix WebView in a grid expands beyond it's cell

### LINKED ISSUE #32030: Android - WebView in a grid expands beyond it's cell
### Description

Add a webview with a shaded background to the second row of a three row grid.  The webview expands to cover the full view, hiding the text above the webview and appearing behind the text that should be below it.  
This is the result with 9.0.80 through 9.111 (current) 

Image

This is the result with 9.0.71

Image

### Steps to Reproduce

- Download the reproduction app below and run it.
- From the hamburger menu choose "WebView in Grid".  Note the results.
- Downgrade Maui.Controls (and Maui.Controls.Maps) to 9.0.71
- Run and choose the same menu item, note the results

### Link to public reproduction project repository

https://github.com/czuck/MauiTest.git

### Version with bug

9.0.111 SR11.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.70 SR7

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by devanathan-vaithiyanathan**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue Details
After PR #29234 , the else part was removed to stop the Navigated event from triggering when the WebView had no source.
However, this caused a new issue where rendering a WebView without a source exceeded the layout bounds.

### Root Cause
When the WebView was rendered without a source, the layout logic was not properly handled — causing the WebView to exceed its layout bounds.

### Description of Change

* Reintroduced the else part.
* Added a check to skip the Navigated event when the source is the default (empty).

This fix resolves both the layout overflow and unwanted event trigger issues.

### Issues Fixed

Fixes #32030 

**Tested the behavior in the following platforms.**
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

| Before  | After  |
|---------|--------|
| **Android**<br>  | **Android**<br>  |

### CODE REVIEW

File: src/Core/src/Platform/Android/MauiWebViewClient.cs [hunk 1]
```diff
@@ -96,6 +96,15 @@ public override bool OnRenderProcessGone(WebView? view, RenderProcessGoneDetail?
 		bool NavigatingCanceled(string? url) =>
 			!_handler.TryGetTarget(out var handler) || handler.NavigatingCanceled(url);
 
+		static bool IsBlankNavigation(string? url)
+		{
+			if (string.IsNullOrWhiteSpace(url))
+				return false;
+
+			// Check if URL is about:blank (case insensitive)
+			return string.Equals(url.Trim(), "about:blank", StringComparison.OrdinalIgnoreCase);
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/MauiWebViewClient.cs:108]: Could expand to more variants?

Examples:
- "about:blank#"
- "about:blank/"

Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/MauiWebViewClient.cs:108]: This will be invoked on every Navigation. The impact on performance now is minimal for the current simple string comparison, but take this into account (for example, if think in use URI parsing or more complex stuff).

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Android/MauiWebViewClient.cs (hunk 1 above)
Comment (devanathan-vaithiyanathan) [reply src/Core/src/Platform/Android/MauiWebViewClient.cs:108]: @jsuarezruiz , When the source is null, we set the default WebView source to about:blank. As a result, the OnPageFinished method always receives about:blank as the parameter. Therefore, handling additional variants such as about:blank# or about:blank/ is not necessary in this case.
image

File: src/Core/src/Platform/Android/MauiWebViewClient.cs [hunk 2]
```diff
@@ -96,6 +96,15 @@ public override bool OnRenderProcessGone(WebView? view, RenderProcessGoneDetail?
 		bool NavigatingCanceled(string? url) =>
 			!_handler.TryGetTarget(out var handler) || handler.NavigatingCanceled(url);
 
+		static bool IsBlankNavigation(string? url)
+		{
+			if (string.IsNullOrWhiteSpace(url))
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/MauiWebViewClient.cs:104]: `if (navigate && !IsBlankNavigation(url))`

Based on this:
- url = null → IsBlankNavigation returns false → Navigated fires 
- url = "about:blank" → IsBlankNavigation returns true → Navigated doesn't fire

This could break the fix from #29234 which wanted to prevent events when Source is null

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Android/MauiWebViewClient.cs (hunk 2 above)
Comment (devanathan-vaithiyanathan) [reply src/Core/src/Platform/Android/MauiWebViewClient.cs:104]: @jsuarezruiz ,
`url = null → IsBlankNavigation returns false → Navigated fires`
url should never be null. We’ve modified the source so that if the source is not null, it uses that source; otherwise, it uses "about:blank".
In the OnPageFinished method, url should never be null.

`url = "about:blank" → IsBlankNavigation returns true → Navigated doesn’t fire`
Yes, this is the expected behavior. The PR#[29234](https://github.com/dotnet/maui/pull/29234) resolves the issue where Android triggered the Navigating event with a null source.
With my fix, if the source is null, we set it to "about:blank". When the URL is "about:blank", the Navigating event will not fire.
 
So with the current fix, it resolves both issues #[32030](https://github.com/dotnet/maui/issues/32030) and #[29234](https://github.com/dotnet/maui/pull/29234).

**Review by jsuarezruiz — DISMISSED** [review]
The test **VerifyWebViewStaysWithinGridCell** is failing Android.
`Snapshot different than baseline: VerifyWebViewStaysWithinGridCell.png (2.97% difference)`

Image

**Review by PureWeen — CHANGES_REQUESTED** [review]
VerifyWebViewStaysWithinGridCell is failing

**Comment by devanathan-vaithiyanathan** [comment]
> VerifyWebViewStaysWithinGridCell is failing

@PureWeen , I've modified the test, Let me know any changes needed

**Comment by rmarinho** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>CoPilot suggestion addressed</strong> · <a href="https://github.com/dotnet/maui/commit/c1b297d6c5130fa1f389ff63356c9b8f6dfab84d"><code>c1b297d</code></a></summary>

---

**Issue:** #32030 - Android - WebView in a grid expands beyond its cell
**PR:** #32145 - [Android] Fix WebView in a grid expands beyond it's cell
**Platforms Affected:** Android only
**Files Changed:** 2 implementation files, 3 test files

### Issue Summary

A WebView without a source expands beyond its Grid cell on Android, covering content above and appearing behind content below. This is a regression from 9.0.80 (after PR #29234 removed the else block that loaded `about:blank` for null sources).

**Root Cause (from PR description):**
- PR #29234 removed the `else` part to stop `Navigated` event from firing when WebView had no source
- This caused layout logic to not be properly handled when WebView rendered without a source, causing it to expand beyond grid cell bounds

### PR's Fix Approach

1. **Reintroduce else block** (`WebViewExtensions.cs`): Load `about:blank` when source is null (restores layout handling)
2. **Add `IsBlankNavigation()` helper** (`MauiWebViewClient.cs`): Check if URL equals `"about:blank"`  
3. **Filter Navigated event** (`MauiWebViewClient.cs`): Skip event when `IsBlankNavigation(url)` returns true

This approach resolves both the layout overflow issue (#32030) and preserves the fix from #29234 (no unwanted Navigated events).

### Key Review Feedback

**File: MauiWebViewClient.cs:108 (jsuarezruiz)**
| Reviewer Concern | Author Response | Status |
|------------------|-----------------|--------|
| Should handle URL variants like `about:blank#` or `about:blank/`? | Not necessary - we always set exactly `about:blank` | ✅ Addressed |
| Performance impact of string comparison on every navigation? | Minimal for simple string comparison | ✅ Acknowledged |

**File: MauiWebViewClient.cs:104 (jsuarezruiz)**
| Reviewer Concern | Author Response | Status |
|------------------|-----------------|--------|
| Could break fix from #29234 if url=null causes Navigated to fire | url should never be null - we always set `about:blank` when source is null | ✅ Addressed |

**File: MauiWebViewClient.cs:105 (Copilot)**
| Reviewer Concern | Status |
|------------------|--------|
| `IsBlankNavigation` returns false for null/whitespace URLs - counterintuitive naming | ⚠️ Open - author claims url never null in practice |

### Prior Agent Review

A prior agent review was posted at commit `87777d6`. It found:
- Pre-Flight: Complete
- Gate: **BLOCKED** - test naming mismatch (`VerifyWebViewBoundsWhenSourceSetToNull` vs `VerifyWebViewStaysWithinGridCell.png`)
- Fix/Report: Skipped due to Gate blocker

**Current state:** The test naming mismatch has been **FIXED** - test method is now `VerifyWebViewStaysWithinGridCell()` matching the snapshot `VerifyWebViewStaysWithinGridCell.png`.

### Test Coverage

**Test Type:** UI Test with screenshot verification
**Test Files:**
- `TestCases.HostApp/Issues/Issue32030.cs` - Test page with WebView in 3-row Grid
- `TestCases.Shared.Tests/Tests/Issues/Issue32030.cs` - NUnit test (Android-only, `#if ANDROID`)
- `TestCases.Android.Tests/snapshots/android/VerifyWebViewStaysWithinGridCell.png` - Baseline snapshot

### Fix Candidates

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #32145 | Load `about:blank` when source is null + filter Navigated event for blank URLs | ⏳ PENDING (Gate) | `MauiWebViewClient.cs` (+13), `WebViewExtensions.cs` (+5) | Original PR |

</details>

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>CoPilot suggestion addressed</strong> · <a href="https://github.com/dotnet/maui/commit/c1b297d6c5130fa1f389ff63356c9b8f6dfab84d"><code>c1b297d</code></a></summary>

---

**Result:** ✅ PASSED
**Platform:** android
**Mode:** Full Verification

- Tests FAIL without fix ✅ (screenshot differs - WebView expands beyond grid cell)
- Tests PASS with fix ✅ (WebView correctly constrained to grid cell)

</details>

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>CoPilot suggestion addressed</strong> · <a href="https://github.com/dotnet/maui/commit/c1b297d6c5130fa1f389ff63356c9b8f6dfab84d"><code>c1b297d</code></a></summary>

---

## Phase 3: Try-Fix Results

5 alternative approaches tested on Android. Key finding: content loading (about:blank or LoadData) is required to fix the  pure View measurement fixes do not work.layout 

### Fix Candidates

| # | Approach | Files Changed | Result |
|---|----------|---------------|--------|
| 1 |  + semantic  check in  | WebViewExtensions.cs, MauiWebViewClient.cs |  Pass |
| 2 |  + flag  set in , checked in both callbacks | WebViewExtensions.cs, MauiWebViewClient.cs |  Pass |
| 3 | `RequestLayout()` + `Invalidate()` when source=null (no content load) | WebViewExtensions. Fail |cs | 
| 4 |  + semantic null check in  | WebViewExtensions.cs, MauiWebViewClient.cs |  Pass |
| 5 | Override `OnMeasure` in `MauiWebView` to clamp dimensions | MauiWebView. Fail |cs | 

### Selected Fix

**PR's fix is correct and should be approved.** All three passing alternatives use the same core mechanism (content loading + event filtering), confirming the PR's approach is sound. The PR's `IsBlankNavigation()` URL-based filter is functionally equivalent to the semantic null checks in passing alternatives 1, 2, and 4.

Best alternative: Attempt 2's flag-based `_loadingForLayout` approach is slightly more comprehensive (guards both `OnPageStarted` and `OnPageFinished`), but the PR's simpler `OnPageFinished`-only check is sufficient.

### Key Insights

1. **Content loading is  The Android WebView's Chromium engine must load something (even blank content) before it respects layout constraints. Attempts 3 and 5 proved that pure View measurement fixes are insufficient.mandatory** 

2. **Multiple filtering approaches  The PR's URL string matching (`IsBlankNavigation`) is one valid approach, but semantic `VirtualView.Source == null` checks and flag-based interception both work equally well.work** 

3. **PR's approach is  The two-part fix (load `about:blank` + filter `Navigated` event) is the right pattern. The PR's specific implementation is reasonable and functional.correct** 

### Comparison with PR's Fix

PR's fix: `IsBlankNavigation()` URL string check in `OnPageFinished` only
Best alternative: Attempt 2's flag-based `_loadingForLayout` intercepting in both `OnPageStarted` and `OnPageFinished` (more comprehensive, prevents cookie sync side effects too)

The PR's fix is functionally correct. The reviewer concern about null URL in `IsBlankNavigation` returning false is valid as a code-clarity issue but not a bug risk since `about:blank` is always set before `OnPageFinished` fires.

</details>

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>CoPilot suggestion addressed</strong> · <a href="https://github.com/dotnet/maui/commit/c1b297d6c5130fa1f389ff63356c9b8f6dfab84d"><code>c1b297d</code></a></summary>

---

## Phase 4: Report

### Summary

**Recommendation APPROVE with minor suggestions**: 

PR #32145 correctly fixes the Android WebView layout regression introduced by PR #29234. The fix is minimal, targeted, and empirically verified. Gate testing confirmed tests fail without the fix and pass with it.

---

### Issue Context

**Issue #32030**: Android WebView placed in a Grid cell expands beyond the cell bounds when `Source = null`.

**Root Cause**: PR #29234 removed an `else` block that loaded `about:blank` when source was null. Without any content load, the Android WebView's internal Chromium engine never constrains its viewport to the measured Android View dimensions.

---

### Fix Analysis

The PR makes two changes:

**1. `WebViewExtensions. Reintroduces the `else` block:cs`** 
```csharp
else
{
    platformWebView.LoadUrl("about:blank");
}
```
 Correct. Content loading (even empty/blank) is required to trigger the WebView's internal viewport calculation.

**2. `MauiWebViewClient. Adds `IsBlankNavigation()` helper and URL check in `OnPageFinished`:cs`** 
```csharp
if (IsBlankNavigation(url))
    return;
```
 Correct. Prevents the spurious `Navigated` event from firing when `about:blank` is loaded for layout purposes.

---

### Gate Verification

| Test | Result |
|------|--------|
| Tests FAIL without fix (at merge-base Confirmed |) | 
| Tests PASS with fix (PR HEAD Confirmed |) | 

---

### Try-Fix Summary

5 alternative approaches were tested. 3 passed, 2 failed:

| # | Approach | Result |
|---|----------|--------|
| 1 | Same  + semantic null check (no URL matching) |  Pass |
| 2 | Same  + flag in  |  Pass |  
| 3 | `RequestLayout()` only, no content  Fail |load | 
| 4 |  + semantic null check |  Pass |
| 5 | Override `OnMeasure` in ` Fail |MauiWebView` | 

**Key finding from try-fix**: Content loading is mandatory (attempts 3 and 5 proved pure View fixes don't work). The PR's specific approach is one of several valid implementations.

---

### Code Review Notes

**Minor  `IsBlankNavigation` null handling:**concern 
```csharp
static bool IsBlankNavigation(string? url) =>
    string.Equals(url, "about:blank", StringComparison.OrdinalIgnoreCase);
```
This returns `false` for null URL. The method name implies "is blank" but returns false for null. This was flagged by reviewer `jsuarezruiz`. The PR author's response ("URL is never null since `about:blank` is always set") is reasonable, but the code could be clearer with an explicit null guard or a more accurate method name like `IsAboutBlank`.

This is a minor code-clarity issue, not a bug. The PR can be approved as-is.

**Alternative filtering approach (from try-fix attempt 2):**
A more comprehensive filter would intercept `OnPageStarted` too, preventing cookie sync side effects:
```csharp
// In OnPageStarted
if (handler.VirtualView.Source == null)
{
    _loadingForLayout = true;
    return;
}
```
This is an improvement but not required. The PR's `OnPageFinished`-only filter is sufficient.

---

### Verdict

 ** The fix is correct, minimal, and well-tested. The `IsBlankNavigation` naming could be improved but is not a blocker. All 3 alternative approaches that passed use the same core mechanism (content loading + event filtering), confirming the PR's approach is sound.APPROVE**

</details>

</details>

---

</details>




<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

---

<details>

<summary><b>Title: ✅ Good</b></summary>

<br>

**Current:** `[Android] Fix WebView in a grid expands beyond it's cell`
</details>

<details>

<summary><b>Description: ✅ Good</b></summary>

<br>

Description needs updates. See details below.
### ✨ Suggested PR Description


> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue Details

After PR #29234, the `else` branch in `WebViewExtensions.UpdateSource` was removed to prevent the `Navigated` event from firing when a WebView had no source. However, this introduced a regression where setting a WebView's `Source` to `null` caused the WebView to exceed its layout bounds (e.g., overflow a Grid cell).

### Root Cause

When `Source` is set to `null`, `UpdateSource` skipped the `else` branch that previously triggered a page load. Without any load call, the Android WebView's native layout was not constrained properly, causing it to expand beyond its allocated grid cell bounds.

### Description of Change

- **`WebViewExtensions.cs`:** Reintroduced the `else` branch — when `Source` is `null`, explicitly loads `about:blank` to ensure the Android WebView respects its layout bounds.
- **`MauiWebViewClient.cs`:** Added `IsBlankNavigation()` helper and updated `OnPageFinished` to skip firing the `Navigated` event when the URL is `about:blank`, preventing unwanted navigation events when source is set to null.

### Issues Fixed

Fixes #32030

**Tested the behavior in the following platforms.**
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

| Before  | After  |
|---------|--------|
| **Android**<br>  | **Android**<br>  |
</details>

<details>

<summary><b>Code Review: ✅ Passed</b></summary>

<br>

## Code Review Findings — PR #32145

### 🟡 Suggestions

---

**1. Mixed Indentation in `IsBlankNavigation` Comment**
- **File:** `src/Core/src/Platform/Android/MauiWebViewClient.cs`
- **Problem:** The second line of the XML comment inside `IsBlankNavigation` uses mixed tabs and spaces:
  ```csharp
  static bool IsBlankNavigation(string? url)
  {
      // Null/empty URLs are handled by the early return in OnPageFinished,
      // so we only need to check for the explicit "about:blank" URL   ← mixed indentation
  ```
  The raw diff shows `    \t\t// so we only need to check...` — a mix of spaces and tabs — while surrounding code uses tabs. This is cosmetic but inconsistent.
- **Recommendation:** Use consistent tab-only indentation to match the rest of the file.

---

**2. Missing Trailing Newline in Added `.cs` Files**
- **Files:**
  - `src/Controls/tests/TestCases.HostApp/Issues/Issue32030.cs`
  - `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue32030.cs`
- **Problem:** Both new files are missing a trailing newline (`\ No newline at end of file` in the diff). This is a POSIX convention and most linters flag this.
- **Recommendation:** Add a newline at the end of both files.

---

**3. `#if ANDROID` Wrapping Entire Test File**
- **File:** `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue32030.cs`
- **Problem:** The entire test file is wrapped in `#if ANDROID`. Per guidelines, inline `#if` directives in test code are discouraged. The preferred approach is to let the test infrastructure handle platform filtering via `[Category]` attributes and `[PlatformAffected]` declarations.
  ```csharp
  #if ANDROID         //This is Android specific issue
  ...
  #endif
  ```
  Note: The `[Issue]` attribute in the HostApp already declares `PlatformAffected.Android`, and the `[Category(UITestCategories.WebView)]` is present, so the test would run correctly even without the `#if`. However, wrapping the entire class (not a test method) is a common pattern in this codebase for Android-only issues, so this is a low-severity concern.
- **Recommendation:** Consider removing the `#if ANDROID` wrapper and relying on the platform attribute declarations. If keeping it, move the `#if` to wrap just the class instead of including the `using` directives inside the conditional block.

---

### ✅ Looks Good

- **`WebViewExtensions.cs`:** The `else` branch loading `about:blank` when `Source` is null is clean and minimal. The comment clearly explains why.
- **`MauiWebViewClient.cs` - `IsBlankNavigation` logic:** The guard for `null/empty` (returning `false`) combined with the `about:blank` case-insensitive check is correct. Even though the comment says null/empty is "handled by early return," being defensive here is appropriate.
- **HostApp test page (`Issue32030.cs`):** Well-structured grid setup with clear `AutomationId` values. The test accurately reproduces the issue scenario (start with HTML source, set source to null, verify layout).
- **UI Test flow:** `WaitForElement → Tap → WaitForElement → VerifyScreenshot` is a reasonable pattern for a layout regression test. Waiting for `BottomButton` both before and after the tap ensures the layout has settled before taking the screenshot.
- **Snapshot included:** The baseline screenshot `VerifyWebViewStaysWithinGridCell.png` is committed, which is required for `VerifyScreenshot()` tests.
</details>

---

</details>

**Review by kubaflo — CHANGES_REQUESTED** [review]
Could you please review the AI Summary comment?

**Comment by devanathan-vaithiyanathan** [comment]
> Could you please review the AI Summary comment?

@kubaflo @jfversluis , As per the AI review summary, I have fixed the indentation and added a new line at the end of the file.

**Review by jfversluis — APPROVED** [review]
