### PR TITLE
[Windows] Fix crash on Windows WebView updating the Html Source more than once

### LINKED ISSUE #10438: WebView Crashes when `Source.Html` is updated more than once on Windows
### Description

When updating the Html property of a source for a WebView twice, there's an unhandled win32 exception.

Example:

MainPage.xaml:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="WebViewTest.MainPage">
    <VerticalStackLayout>
        <Button x:Name="btn" WidthRequest="400" HeightRequest="50" Text="Go" Clicked="btn_Clicked" />
        <WebView x:Name="web" WidthRequest="400" HeightRequest="400" Background="blue" />
    </VerticalStackLayout>
</ContentPage>
```

MainPage.xaml.cs:

```
namespace WebViewTest;
public partial class MainPage : ContentPage
{
    HtmlWebViewSource src = new();
    public MainPage()
    {
        InitializeComponent();
        web.Source = src;
    }

    private void btn_Clicked(object sender, EventArgs e)
    {
        Random rnd = new();
        src.Html += $"<h1>Hello World {rnd.Next()}!</h1><br>";
        //src.Html += $"<h1>Hello World {rnd.Next()}!</h1><br>"; // uncommenting this, crashes the program
        //web.Reload(); // not needed
    }
}
```

- Hitting the button as many times as you want works fine
- Uncommenting the 2nd src.Html = ... line causes a crash.

dotnet --version 6.0.401 (the latest VS.NET 2022 seems to offer)

### Steps to Reproduce

1. Create a new Maui application with a button and a webview on it.
2. Assign a HtmlWebViewSource to the webview.
3. Add an event handler that fires when the button is pressed.
4. Have that event handler modify the Html property of the HtmlWebViewSource twice.
5. Watch it crash...

### Link to public reproduction project repository

https://github.com/remopini/WebViewTest

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Win 11 with all current updates

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix crash on Windows WebView updating the Html Source more than once.

fix-webview-source2

To validate the changes, launch the .NET MAUI Gallery on Windows and navigate to the WebView sample. Tap the Update Html Source more than once. Without exceptions, the test has passed. Also, can use the new added Device tests to validate the changes.

image

### Issues Fixed

Fixes #10438

### CODE REVIEW

File: src/Core/src/Platform/Windows/WebViewExtensions.cs [hunk 1]
```diff
@@ -80,5 +79,17 @@ public static void EvaluateJavaScript(this WebView2 webView, EvaluateJavaScriptA
 		{
 			request.RunAndReport(webView.ExecuteScriptAsync(request.Script));
 		}
+
+		internal static bool IsValid(this WebView2 webView)
+		{
+			try
+			{
+				return webView != null && webView.CoreWebView2 != null;
```
Comment (mandel-macaque) [inline src/Core/src/Platform/Windows/WebViewExtensions.cs:87]:
```suggestion
				return webView is not null && webView.CoreWebView2 is not null;
```

File: src/Core/src/Platform/Windows/WebViewExtensions.cs [hunk 2]
```diff
@@ -80,5 +79,17 @@ public static void EvaluateJavaScript(this WebView2 webView, EvaluateJavaScriptA
...
+			}
+			catch (Exception ex) when (ex is ObjectDisposedException || ex is InvalidOperationException)
```
Comment (mandel-macaque) [inline src/Core/src/Platform/Windows/WebViewExtensions.cs:89]: <3

**Review by mandel-macaque — APPROVED** [review]
minor comments.

**Review by mandel-macaque — APPROVED** [review]

**Review by rachelkang — APPROVED** [review]
