### PR TITLE
Fix for TabBar Navigation does not invoke its IQueryAttributable.ApplyQueryAttributes(query)

### LINKED ISSUE #13537: Tabs defined in AppShell.xaml does not invoke its view model's IQueryAttributable.ApplyQueryAttributes(query) implementaion
### Description

When doing shell navigation with `Shell.Current.GoToAsync(state)` in a maui project and the destination page's view model implements `IQueryAttributable`, the implementation of `IQueryAttributable.ApplyQueryAttributes(query)` will be called to pass on query attributes, even when no data is passed into `Shell.Current.GoToAsync(state)`.

However, this behavior is observed to be missing from Tabs defined in `AppShell.xaml`, with view models that also implement `IQueryAttributable` but their implementation of `IQueryAttributable.ApplyQueryAttributes(query)` were not called.

### Steps to Reproduce

For tabs:
1. Create a new MAUI app
2. Define a tab bar in AppShell.xaml with some new `Page`s as its tabs
3. Add view model classes for each of the tabbed pages that would implement `IQueryAttributable`
4. Put breakpoints or console logs in vm's `ApplyQueryAttributes(query)` method
5. Run the app and switch between the tabs

Expected behavior: debugger breaks at `ApplyQueryAttributes(query)`/console log is displayed
Actual behavior: no breakpoints hit/no console logs displayed

For regular page navigation:
6. Add a new page and register its route with `Routing.RegisterRoute(nameof(NewPage), typeof(NewPage));`
7. Add a button to one of the pages with its `Clicked` event handler executing `Shell.Current.GoToAsync(nameof(NewPage))`
8. Repeat step 3 and 4 for the new page
9. Run the app and click on the button

Expected behavior: debugger breaks at `ApplyQueryAttributes(query)`/console log is displayed even though no query attributes are supplied
Actual behavior: matches expectation

### Link to public reproduction project repository

https://github.com/dk-mushiyoke/MauiTabQueryRepro

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 16.2, android 31

### Did you find any workaround?

Not yet

### Relevant log output

_No response_

### LINKED ISSUE #28453: `ShellContent` routes do not call `ApplyQueryAttributes`
### Description

When a page that implements `IQueryAttributable` is registered as route in `ShellContent`, its implementation of `ApplyQueryAttributes` does not get called when the `Shell` navigates to it, either as the default `ShellContent` or if the user clicks the page's flyout item.

This is true regardless of if the `ShellContent` route has any query parameters.

### Steps to Reproduce

1. Create a new MAUI app
2. Change `MainPage` to implement `IQueryAttributable`
3. Put a break point on `ApplyQueryAttributes` (and/or leave the boiler plate `NotImplementedException`)
4. Run the app.

Expected outcome: The breakpoint gets hit and/or the exception is thrown.
Actual outcome: Neither

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.40 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by SuthiYuvaraj**
### Issue Details
While navigating between pages, ApplyQueryAttributes should trigger with data from the navigating page. In the current implementation, navigation using Push and GoToAsync works as expected, but other navigation methods do not trigger ApplyQueryAttributes notifications.

### Root Cause
-**GoToAsync Limitations:** When navigating using PopAsync, PopModalAsync, back navigation, or between FlyoutPages, ApplyQueryAttributes is not triggered. This occurs because QueryAttributes is not correctly set for these navigation types.
-**TabBar Navigation:** Navigating between TabBar items changes the page by updating CurrentItemChanged. However, QueryAttributes is not updated for these item changes, leading to missing attribute notifications.

### Fix Details
-**GoToAsync Fix:** Updated ShellNavigationManager to apply ApplyQueryAttributes when popping, ensuring QueryableAttributes values are set correctly.

-**TabBar Navigation Fix:** Invoked ApplyQueryAttributes within UpdateCurrentState to receive notifications for all ShellItem navigations, ensuring that QueryAttributes are updated consistently across TabBar item changes.

### Issues Fixed
Fixes #13537 
Fixes #28453 

### Output Screenshot
Before Issue Fix | After Issue Fix |
|----------|----------|
|<image width="500" height="250" alt="Before Fix video"  src="https://github.com/user-attachments/assets/54fff46e-6c30-4fb7-82e2-ca37326dd4d1">|<image width="500" height="250" alt="After Fix video"  src="https://github.com/user-attachments/assets/02301a14-848e-4668-a70f-a6c6d469c637" >|

### CODE REVIEW

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
There are unit tests failing:

```
Failed InitialNavigationDoesntSetQueryAttributesProperty [< 1 ms]
Error Message:
Assert.False() Failure
Expected: False
Actual:   True

 Failed SetCurrentItemAddsToShellCollection [1 ms]
  Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at Microsoft.Maui.Controls.Shell.Microsoft.Maui.Controls.IShellController.UpdateCurrentState(ShellNavigationSource source) in /_/src/Controls/src/Core/Shell/Shell.cs:line 936
   at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest) in /_/src/Controls/src/Core/Shell/ShellNavigationManager.cs:line 204
   at Microsoft.Maui.Controls.Shell.<Initialize>g__SetCurrentItem|158_1() in /_/src/Controls/src/Core/Shell/Shell.cs:line 1284
   at Microsoft.Maui.Controls.Shell.<Initialize>b__158_0(Object s, NotifyCollectionChangedEventArgs e) in /_/src/Controls/src/Core/Shell/Shell.cs:line 1217
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
```

**Comment by SuthiYuvaraj** [comment]
> There are unit tests failing:
> 
> ```
> Failed InitialNavigationDoesntSetQueryAttributesProperty [< 1 ms]
> Error Message:
> Assert.False() Failure
> Expected: False
> Actual:   True
> 
>  Failed SetCurrentItemAddsToShellCollection [1 ms]
>   Error Message:
>    System.NullReferenceException : Object reference not set to an instance of an object.
>   Stack Trace:
>      at Microsoft.Maui.Controls.Shell.Microsoft.Maui.Controls.IShellController.UpdateCurrentState(ShellNavigationSource source) in /_/src/Controls/src/Core/Shell/Shell.cs:line 936
>    at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest) in /_/src/Controls/src/Core/Shell/ShellNavigationManager.cs:line 204
>    at Microsoft.Maui.Controls.Shell.<Initialize>g__SetCurrentItem|158_1() in /_/src/Controls/src/Core/Shell/Shell.cs:line 1284
>    at Microsoft.Maui.Controls.Shell.<Initialize>b__158_0(Object s, NotifyCollectionChangedEventArgs e) in /_/src/Controls/src/Core/Shell/Shell.cs:line 1217
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
> ```

Hi @jsuarezruiz , The `UpdateCurrentState` method has been updated with proper null handling. Kindly review it and let us know if you  any concerns.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Sorry, still there is one failing unit tests:

```
Failed InitialNavigationDoesntSetQueryAttributesProperty [< 1 ms]
Error Message:
Assert.False() Failure
Expected: False
Actual:   True
```

**Comment by SuthiYuvaraj** [comment]
> Sorry, still there is one failing unit tests:
> 
> ```
> Failed InitialNavigationDoesntSetQueryAttributesProperty [< 1 ms]
> Error Message:
> Assert.False() Failure
> Expected: False
> Actual:   True
> ```

@jsuarezruiz, The failing unit test case is intended to verify that the query attribute should not be present during the initial loading. However, the bug report confirms this behavior as a valid bug https://github.com/dotnet/maui/issues/13537#issuecomment-1452800073.Therefore, the test case is no longer applicable. Can the failing test case be removed?

**Comment by SuthiYuvaraj** [comment]
> Sorry, still there is one failing unit tests:
> 
> ```
> Failed InitialNavigationDoesntSetQueryAttributesProperty [< 1 ms]
> Error Message:
> Assert.False() Failure
> Expected: False
> Actual:   True
> ```

@jsuarezruiz  , After analyzing the failed test case (`InitialNavigationDoesntSetQueryAttributesProperty`) scenario, I have modified the fix to prevent invoking the `QueryableAttribute` during the initial loading. Kindly review it and share any concerns

File: src/Controls/src/Core/Shell/ShellItem.cs [hunk 1]
```diff
@@ -297,6 +297,14 @@ static void OnCurrentItemChanged(BindableObject bindable, object oldValue, objec
 			{
 				shell.UpdateCurrentState(ShellNavigationSource.ShellSectionChanged);
 			}
+			
+			//For TabBarItems itemchanged will fall in ShellItem class , we need to set the QueryAttributesProperty here
+			ShellContent currentShellContent = shellItem.CurrentItem?.CurrentItem;
+			var existing = (ShellRouteParameters)currentShellContent?.GetValue(ShellContent.QueryAttributesProperty);
+			if(oldValue is not null && newValue is not null && existing is null)
+			{
+			currentShellContent?.SetValue(ShellContent.QueryAttributesProperty, new ShellRouteParameters());
```
Comment (StephaneDelcroix) [inline src/Controls/src/Core/Shell/ShellItem.cs:306]: nit: indentation

File: src/Controls/src/Core/Shell/ShellNavigationManager.cs [hunk 2]
```diff
@@ -309,7 +309,16 @@ public static void ApplyQueryAttributes(Element element, ShellRouteParameters qu
 
 
 			if (baseShellItem is ShellContent)
-				baseShellItem.ApplyQueryAttributes(MergeData(element, filteredQuery, isPopping));
+			{
+				var mergedData = MergeData(element, filteredQuery, isPopping);
+
+				//if we are pop or navigating back, we need to apply the query attributes to the ShellContent
+				if(isPopping)
```
Comment (StephaneDelcroix) [inline src/Controls/src/Core/Shell/ShellNavigationManager.cs:316]: nit: white space

File: src/Controls/src/Core/Shell/Shell.cs [hunk 3]
```diff
@@ -1661,6 +1661,14 @@ static void OnCurrentItemChanged(BindableObject bindable, object oldValue, objec
 			shell.ShellController.AppearanceChanged(shell, false);
 			shell.ShellController.UpdateCurrentState(ShellNavigationSource.ShellItemChanged);
 
+			// If the new ShellItem is a FlyoutItem or a ShellGroupItem, we need to update the QueryAttributes
+			var existing = (ShellRouteParameters)shell.CurrentContent?.GetValue(ShellContent.QueryAttributesProperty);
+            if(oldValue is not null && newValue is not null && (shell.CurrentItem is FlyoutItem || shell.CurrentItem is ShellGroupItem) && existing is null)
```
Comment (StephaneDelcroix) [inline src/Controls/src/Core/Shell/Shell.cs:1666]: do we need to check for oldValue ?

Comment (SuthiYuvaraj) [reply src/Controls/src/Core/Shell/Shell.cs:1666]: Yes @StephaneDelcroix , The `ApplyQueryAttributes trigger` is not required for the initial load; therefore, a null check has been added for the `oldValue`.

File: src/Controls/src/Core/Shell/ShellItem.cs (hunk 1 above)
Comment (SuthiYuvaraj) [reply src/Controls/src/Core/Shell/ShellItem.cs]: I have addressed the indentation issue. Let me know if anything else needs adjustment.

File: src/Controls/src/Core/Shell/ShellNavigationManager.cs (hunk 2 above)
Comment (SuthiYuvaraj) [reply src/Controls/src/Core/Shell/ShellNavigationManager.cs]: I have addressed the whitespace issue. Let me know if anything else needs adjustment.

File: src/Controls/src/Core/Shell/Shell.cs (hunk 3 above)
Comment (jsuarezruiz) [inline src/Controls/src/Core/Shell/Shell.cs:1666]: This is a condition with a lot of checks. Not required but, we could improve the readability with small changes:

```
bool isRelevantShellItem = shell.CurrentItem is FlyoutItem || shell.CurrentItem is ShellGroupItem;
bool isNewValueDifferent = oldValue is not null && newValue is not null && existing is null;

if (isNewValueDifferent && isRelevantShellItem)
```

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13537.cs [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+		{
+			App.WaitForElement("HomePageTestLabel");
+			App.Tap("PushAsyncButton");
+			App.WaitForElement("InnerPageTestLabel");
+			App.Tap("PopAsyncButton");
+			var result = App.WaitForElement("HomePageTestLabel").GetText();
+			Assert.That(result , Is.EqualTo("Issue13537HomePage QueryAttribute is triggered"));
+		}
+
+#if !MACCATALYST
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13537.cs:32]: Why we avoid this test on Catalyst?

File: src/Controls/src/Core/Shell/Shell.cs (hunk 3 above)
Comment (SuthiYuvaraj) [reply src/Controls/src/Core/Shell/Shell.cs]: Hi @jsuarezruiz  , I have modified the condition based on your suggestion. Kindly review and let me know if you have any concern.

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13537.cs (hunk 4 above)
Comment (SuthiYuvaraj) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13537.cs]: Hi @jsuarezruiz  , `App.TapBackArrow` does not actually tap the back arrow button. Instead, it taps the first tab element on the screen because both elements share the same accessibility identifier. To address this, Catalyst has been ignored, and appropriate comments have been added.

**Comment by PureWeen** [comment]
@SuthiYuvaraj can you rebase this one to net10?

**Comment by StephaneDelcroix** [comment]
when merged, merge additional tests from https://github.com/dotnet/maui/pull/33006

**Review by StephaneDelcroix — APPROVED** [review]
