### PR TITLE
[Bug] Fix Grid cells not honoring MaxWidth

### LINKED ISSUE #7366: MaximumWidthRequest property behaves differently in Windows and Android
### Description

Inner Grid has a MaximumWidthRequest of 600, and is placed inside an outer Grid with a blue background.

On Windows it looks as desired:
image

Shrink the window and it's still fine:
image

On Android it is wrong:
image

### Steps to Reproduce

New project.

This goes inside the ContentPage:
```
    <Grid BackgroundColor="Blue">
        <Grid MaximumWidthRequest="600" BackgroundColor="White">
            <ScrollView>
                <VerticalStackLayout 
                    Spacing="25" 
                    Padding="30,0" 
                    VerticalOptions="Center">

                    <Image
                        Source="dotnet_bot.png"
                        SemanticProperties.Description="Cute dot net bot waving hi to you!"
                        HeightRequest="200"
                        HorizontalOptions="Center" />

                    <Label 
                        Text="You will rejoice to hear that no disaster has accompanied the commencement of an enterprise which you have regarded with such evil forebodings. I arrived here yesterday; and my first task is to assure my dear sister of my welfare, and increasing confidence in the success of my undertaking."
                        SemanticProperties.HeadingLevel="Level1"
                        FontSize="32"
                        HorizontalOptions="Center" />

                    <Label 
                        Text="Welcome to .NET Multi-platform App UI"
                        SemanticProperties.HeadingLevel="Level2"
                        SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                        FontSize="18"
                        HorizontalOptions="Center" />

                    <Button 
                        x:Name="CounterBtn"
                        Text="Click me"
                        SemanticProperties.Hint="Counts the number of times you click"
                        Clicked="OnCounterClicked"
                        HorizontalOptions="Center" />

                </VerticalStackLayout>
            </ScrollView>
        </Grid>
    </Grid>
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

Bind MaximumWidthRequest to a view model readonly property that returns Min(600, screenVirtualWidth).

### Relevant log output

_No response_

### LINKED ISSUE #15785: Label wordwrap does not honor container MaxWidth
### Description

PR #15022 fixes MaxRequestWidth and MaxRequestHeight and works mostly great! However, it seems a Label with WordWrap inside a container such as a Grid with MaximumWidthRequest, does not play along.

### Steps to Reproduce

Consider the following XAML:

```xaml
<Grid BackgroundColor="LightBlue" MaximumWidthRequest="600" Padding="10">
  <Label FontSize="20" 
         Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sodales eros nec massa facilisis venenatis. Sed fermentum porta diam eu pulvinar. Cras ornare ligula id finibus tincidunt. Sed sagittis aliquam neque sit amet commodo. Sed eget velit tortor. Nam ac fringilla leo, sit amet egestas quam. Praesent finibus sem ac nisi elementum sollicitudin. "
         LineBreakMode="WordWrap" />
</Grid>
```

On iOS (and MacOS) in portrait this looks fine (enforced by device width):

Simulator Screenshot - iPhone 14 - 2023-06-21 at 15 26 30

In landscape things fall apart:

Simulator Screenshot - iPhone 14 - 2023-06-21 at 15 26 33

On Android the behavior is exactly the opposite. Portrait mode doesn't look great:

Screenshot_1687420702

Landscape mode is fine:

Screenshot_1687420709

### Link to public reproduction project repository

https://github.com/zwikk/maui-playground/tree/main/Source/MauiNet8Test

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16, Android, MacOS

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jknaudt21**
### Problem
When computing the size of a cell, Grid would run into trouble depending on the platform when given MaxWidth.

On Android, the grid's children would often look at the screen's max width (even if that meant looking at the wrong orientation) and ignore the dimensions passed to the grid object.

On iOS, the grid's children would compute their width when `SizeThatFits` was called. This call was done without taking into account MaxWidth

### Solution
When calculating the dimension constraints for a view, we take into account the MaxWidth and MaxHeight as long as they are smaller than the already established constraints. 

| Before  | After | 
| --- | --- | 
| image| image |
| image|  image |
(Windows was working fine, so no changes were needed) 
### Issues Fixed
Fixes #15785
Fixes #7366

### Remaining Work 
- [x] Write tests
- [x] Figure out why Android's MaxWidth beats out the screen's width
- [x] Add android screenshots

### CODE REVIEW

File: src/Controls/tests/DeviceTests/Elements/Layout/LayoutTests.cs [hunk 1]
```diff
@@ -236,5 +236,46 @@ async Task FlexLayoutInStackLayoutDoesNotCycle(IStackLayout root)
...
+
+			await InvokeOnMainThreadAsync(async () =>
+			{
+				await CreateHandlerAsync<LabelHandler>(label);
+				await CreateHandlerAsync<LayoutHandler>(grid);
+
+				await AttachAndRun(grid, (handler) => { });
+			});
+
+			Assert.True(label.Width <= grid.MaximumHeightRequest);
```
Comment (hartez) [inline src/Controls/tests/DeviceTests/Elements/Layout/LayoutTests.cs:276]: Looks like these are comparing the wrong values?

**Review by hartez — CHANGES_REQUESTED** [review]

File: src/Controls/tests/DeviceTests/Elements/Layout/LayoutTests.cs (hunk 1 above)
Comment (jknaudt21) [reply src/Controls/tests/DeviceTests/Elements/Layout/LayoutTests.cs:276]: Doh. Sloppy copy paste

**Review by hartez — APPROVED** [review]

**Comment by Toine-db** [comment]
Hello Guys,

Thanks for the fix, but please merge this fix to the .Net 7 version as well. 
We currently need to put migration projects on hold because of this issue that otherwise would be finished within weeks, and new migrations won't be started anymore because of this.
This is waiting for the .Net8 release really comes at a bad time because currently other development environments are also being considered, waiting a few months for .Net8 is really (too) long for our department.

Please consider copying the three lines of code to the .Net7 version.

Kind Regards,

FYI: using preview versions (like for .Net8) for production releases is really a no-go for us :-(
