### PR TITLE
[X] Properly restore styleValue after ClearValue

### LINKED ISSUE #4617: Clearing BindableProperty causes styles properties to disappear
### Description

Clearing BindableProperty causes styles properties to disappear

### Steps to Reproduce

1. Open build and run attached app.
2. Click on Clear Background button
**Actual**: buttons background color changes to white
**Expected**: no change in background color as they come from style
**Note**: this  breaks XAML Hot Reload. If you first add Background="Red" and then undo we end up with white background color rather than reverring to styles color.

[MauiApp11.zip](https://github.com/dotnet/maui/files/8043401/MauiApp11.zip)

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change

Some values from DynamicResource set from Style weren't cached, and we
had no value to fallback to after a ClearValue. This fixes the issue.

- fixes #4617

### CODE REVIEW

**Review by Redth — APPROVED** [review]

File: src/Controls/tests/Core.UnitTests/StyleTests.cs [hunk 1]
```diff
@@ -983,5 +983,31 @@ public async Task ApplyAndRemoveStyleOffMainThreadShouldNotCrash()
 
 			await Task.WhenAll(tasks);
 		}
+
+		[Test]
+		//https://github.com/dotnet/maui/issues/4617
+		public void ClearValueShouldntUnapplyStyles()
```
Comment (jsuarezruiz) [inline src/Controls/tests/Core.UnitTests/StyleTests.cs:989]: :heart:

**Review by jsuarezruiz — APPROVED** [review]
