### PR TITLE
[iOS] Fix: ActivityIndicator IsRunning ignores IsVisible when set to true

### LINKED ISSUE #28968: [iOS] [ActivityIndicator] `IsRunning` ignores `IsVisible` when set to `true`
### Description

The `ActivityIndicator` behaves differently on iOS compared to Android.

On **Android**, both `IsRunning` and `IsVisible` must be `true` for the indicator to be shown and animated. Otherwise, it remains hidden.

On **iOS**, the behavior is inconsistent:

| Initial State                        | Change Applied             | Expected Result           | Actual Result             | ✅ / ❌ |
|-------------------------------------|----------------------------|---------------------------|----------------------------|--------|
| `IsRunning = false`, `IsVisible = false` | Set `IsRunning = true`      | Not visible                | **Visible**                | ❌     |
| `IsRunning = false`, `IsVisible = false` | Set `IsVisible = true`      | Not visible                | Not visible                | ✅     |
| `IsRunning = true`, `IsVisible = true`   | Set `IsRunning = false`     | Not visible                | Not visible                | ✅     |
| `IsRunning = true`, `IsVisible = true`   | Set `IsVisible = false`     | Not visible                | Not visible                | ✅     |

There should be a unified behavior where a change in either `IsRunning` or `IsVisible` triggers a check of **both** properties. The indicator should only be shown if **both `IsRunning` and `IsVisible` are `true`**.

I discovered this issue because the indicator remains rendered in my app even when `IsVisible` is set to `false`. In my case, a 1dp-sized `ActivityIndicator` blinks in the top-left corner of the layout after transitioning from `IsRunning = true`, `IsVisible = true` to `IsVisible = false`. I believe this could be addressed by properly synchronizing the visibility logic.

This behavior started after updating MAUI from **9.0.40** to **9.0.60** (I had to skip **9.0.50** due to a bug in CommunityToolkit dialogs that broke my app’s login flow).

<details>
<summary> iOS recording </summary>

Image

Setting only IsRunning = true on iOS causes the ActivityIndicator to become visible, ignoring the value of IsVisible. This contradicts expected behavior and differs from Android, where both IsRunning and IsVisible must be true for the indicator to appear.

</details>

### Steps to Reproduce

1. Create a new MAUI 9 app
2. Add to MainPage a new ActivityIndicator (IsRunning false, IsVisible false)
3. Set the IsRunning for ActivityIndicator to true (this should not work)

### Link to public reproduction project repository

https://github.com/Domik234/Issue-MauiActivityIndicatorBehavior-iOS

### Version with bug

9.0.60 SR6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.40 SR4

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

Setting both properties should be enough. (IsRunning and IsVisible values should be always the same for proper behavior)

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by bhavanesh2001**
### Description of Change

On iOS, the `ActivityIndicator` becomes visible even when `IsVisible = false` and `IsRunning = true`, effectively ignoring the `IsVisible` property.

**Root Cause**

Visibility is not being correctly mapped in iOS.

By default, `IsVisible` is `true` for all elements, so we must explicitly manage visibility based on the `IsRunning` value — especially since it's expected that the `ActivityIndicator` is hidden by default.

The current implementation seems to work because `IsRunning` defaults to `false`, which calls `StopAnimating()` and hides the native control. However, if `HidesWhenStopped` is set to `false`, the control remains visible without animating — which is incorrect.

To fix this, we explicitly update the visibility inside the `IsRunning` mapper, just as it's done on Android.

<table>
  <tr>
<th>Before Fix</th>
<th>After Fix</th>
</tr>
<tr>
<td>

https://github.com/user-attachments/assets/19482315-e5ba-4c4e-af2a-2e883d6eef35

</td>
<td>

https://github.com/user-attachments/assets/9c05750d-d7ef-445c-9c65-64e6e142cc45

</td>
</tr>
</table>

### Issues Fixed

Closes #28968

### CODE REVIEW

**Comment by bhavanesh2001** [comment]
```xaml
  <VerticalStackLayout VerticalOptions="Center" HorizontalOptions="Center"> 
                <ActivityIndicator HorizontalOptions="Center" x:Name="busy"> 
                    <ActivityIndicator.Triggers>
                        <DataTrigger TargetType="ActivityIndicator" 
                            Binding="{Binding Source={x:Reference isRunningSwitch}, Path=IsToggled}" 
                            Value="True">
                             <Setter Property="IsRunning" Value="True" />
                        </DataTrigger>
                        <DataTrigger TargetType="ActivityIndicator" 
                            Binding="{Binding Source={x:Reference isVisibleSwitch}, Path=IsToggled}" 
                            Value="True"> 
                            <Setter Property="IsVisible" Value="True" /> 
                        </DataTrigger> 
                        <DataTrigger TargetType="ActivityIndicator" 
                            Binding="{Binding Source={x:Reference isRunningSwitch}, Path=IsToggled}" 
                            Value="False"> 
                            <Setter Property="IsRunning" Value="False" /> 
                        </DataTrigger> 
                        <DataTrigger TargetType="ActivityIndicator" 
                            Binding="{Binding Source={x:Reference isVisibleSwitch}, Path=IsToggled}" 
                            Value="False"> <Setter Property="IsVisible" Value="False" /> 
                        </DataTrigger> 
                    </ActivityIndicator.Triggers> 
                </ActivityIndicator> 
                <Switch x:Name="isRunningSwitch" HorizontalOptions="Center" /> 
                <Label Text="Toggle IsRunning" HorizontalOptions="Center" /> 
                <Switch x:Name="isVisibleSwitch" IsToggled="True" HorizontalOptions="Center" /> 
                <Label Text="Toggle IsVisible" HorizontalOptions="Center" />
</VerticalStackLayout>
```

File: src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs [hunk 1]
```diff
@@ -6,12 +6,26 @@ public static class ActivityIndicatorExtensions
...
 
+		private static bool GetActivityIndicatorVisibility(IActivityIndicator activityIndicator)
+		{
+			if (activityIndicator.Visibility == Visibility.Visible)
+			{
+				return !activityIndicator.IsRunning;
+			}
+			else
+			{
+				return true;
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs:25]: Could include a comment here adding some details?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Could you include a Device Test for iOS checking the IsAnimating  property of the UIActivityIndicatorView  using the `ActivityIndicator` `IsRunning`  and `IsVisible` properties? https://github.com/dotnet/maui/blob/ef1ec07908eda7b7bf9979fbbf9c374fbe7f2acf/src/Core/tests/DeviceTests/Handlers/ActivityIndicator/ActivityIndicatorHandlerTests.iOS.cs

File: src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs (hunk 1 above)
Comment (bhavanesh2001) [reply src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs:27]: Done

**Comment by bhavanesh2001** [comment]
@jsuarezruiz  I added  a device test. Please run the pipelines.

**Comment by bhavanesh2001** [comment]
@Domik234 As I mentioned. `HidesWhenStopped = false` will result in a visible activity indicator ,but it wont animate(wont spin). This is not expected.

**Comment by Domik234** [comment]
@bhavanesh2001 Sorry, I was hasty. I was re-reading if I didn't missed and before I was able to edit, you answered. 😀

File: src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs [hunk 2]
```diff
@@ -6,12 +6,28 @@ public static class ActivityIndicatorExtensions
 	{
 		public static void UpdateIsRunning(this UIActivityIndicatorView activityIndicatorView, IActivityIndicator activityIndicator)
 		{
-			if (activityIndicator.IsRunning)
+			activityIndicatorView.Hidden = GetActivityIndicatorVisibility(activityIndicator);
+
+			if (activityIndicator.IsRunning && !activityIndicatorView.Hidden)
```
Comment (Domik234) [inline src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs:11]: Can be value from `GetActivityIndicatorVisibility(activityIndicator);` saved to variable, applied to `acitvityIndicatorView.Hidden` and then reused in following if to limit Obj-C calls?

Comment (bhavanesh2001) [reply src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs:11]: I think we are fine here. Because this is assigned when there is a change in `IsVisible` or `IsRunning` and we need to update `Hidden`  according to changes made.

**Comment by bhavanesh2001** [comment]
@jsuarezruiz  Please run pipelines on this.

File: src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs [hunk 3]
```diff
@@ -22,7 +22,7 @@ public partial class ActivityIndicatorHandler : IActivityIndicatorHandler
 		{
 			[nameof(IActivityIndicator.Color)] = MapColor,
 			[nameof(IActivityIndicator.IsRunning)] = MapIsRunning,
-#if __ANDROID__
+#if __ANDROID__ || IOS || MACCATALYST
 			// Android does not have the concept of IsRunning, so we are leveraging the Visibility
```
[the remark this answers is not in the document]
Comment (bhavanesh2001) [reply src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs]: Yep. Updated !

**Comment by bhavanesh2001** [comment]
@jfversluis Could you run pipelines.

File: src/Core/tests/DeviceTests/Handlers/ActivityIndicator/ActivityIndicatorHandlerTests.cs [hunk 4]
```diff
@@ -7,6 +7,36 @@ namespace Microsoft.Maui.DeviceTests
 	[Category(TestCategory.ActivityIndicator)]
 	public partial class ActivityIndicatorHandlerTests : CoreHandlerTestBase<ActivityIndicatorHandler, ActivityIndicatorStub>
 	{
+#if !WINDOWS // On Windows, the platform control will return IsActive as true even when the control is not visible.
+		[Theory(DisplayName = "IsRunning Should Respect IsVisible")]
```
Comment (bhavanesh2001) [inline src/Core/tests/DeviceTests/Handlers/ActivityIndicator/ActivityIndicatorHandlerTests.cs:11]: Everything works as expected . But GetNativeIsRunning() seems to return true even when control is not visible. The UI test already covers this scenario.

https://github.com/user-attachments/assets/9445b71f-906d-4e6d-a95d-dd00287389ce

**Comment by devanathan-vaithiyanathan** [comment]
@bhavanesh2001 , Adding the fix in the below places appears to resolve the issue with minimal code changes. Do you think more code changes are necessary?
image

**Comment by bhavanesh2001** [comment]
> @bhavanesh2001 , Adding the fix in the below places appears to resolve the issue with minimal code changes. Do you think more code changes are necessary? image

I think It's necessary to map and handle Visiibility like I did in the PR changes
```csharp
#if __ANDROID__ || IOS || MACCATALYST
			// Since Visibility and IsRunning are dependent on each other, we handle Visibility explicitly.
			[nameof(IActivityIndicator.Visibility)] = MapIsRunning,
#endif
```
Based on the above changes, I think if I initialize the `ActivityIndicator` with `IsVisible = false` and `IsRunning = true`, and later change `IsVisible` to `true`, the indicator won't be shown—even though at that point both `IsVisible` and `IsRunning` are `true`.

You can test and experiment with `IsVisible` and `IsRunning` using the sample code I included in the initial comments.

**Comment by devanathan-vaithiyanathan** [comment]
> > @bhavanesh2001 , Adding the fix in the below places appears to resolve the issue with minimal code changes. Do you think more code changes are necessary? image
> 
> I think It's necessary to map and handle Visiibility like I did in the PR changes
> 
> ```cs
> #if __ANDROID__ || IOS || MACCATALYST
> 			// Since Visibility and IsRunning are dependent on each other, we handle Visibility explicitly.
> 			[nameof(IActivityIndicator.Visibility)] = MapIsRunning,
> #endif
> ```
> 
> Based on the above changes, I think if I initialize the `ActivityIndicator` with `IsVisible = false` and `IsRunning = true`, and later change `IsVisible` to `true`, the indicator won't be shown (or it will be shown but wont animate)—even though at that point both `IsVisible` and `IsRunning` are `true`.
> 
> You can test and experiment with `IsVisible` and `IsRunning` using the sample code I included in the initial comments.

Yes @bhavanesh2001 , the mentioned scenario is working fine with my fix. The StartAnimate method is being called from the LayoutSubviews
Here is the demo video 

https://github.com/user-attachments/assets/6a3018ee-2475-41e5-9a09-5d282868428d

**Comment by bhavanesh2001** [comment]
@devanathan-vaithiyanathan I think with my changes, we can remove the animation logic from `LayoutSubviews`. Also, I  tried to follow the approach we're already using in the Android case. But feel free to open a PR with your changes as an alternative to this one, so the team can choose the approach they'd prefer to go with.

**Comment by jingo0** [comment]
@bhavanesh2001 Will this be addressed in .NET 9, or is it planned for .NET 10?

**Comment by bhavanesh2001** [comment]
> @bhavanesh2001 Will this be addressed in .NET 9, or is it planned for .NET 10?

@jingo0 I'm not sure, But if you're facing an issue due to this, you can easily work your way around it.

You can bind `IsVisible` and `IsEnabled` to one property so that it hides and shows without any issues.

**Comment by ghost** [comment]
Thanks for the patch — any update on merge status or further changes needed to get this landed? @jsuarezruiz @StephaneDelcroix

**Comment by development-jantar** [comment]
@jfversluis I think this is all done, just review is needed. Any chance this could be in next SR for MAUI?

**Comment by rmarinho** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Apply AI summary ActivityIndicator fixes</strong> · <a href="https://github.com/dotnet/maui/commit/6eb61a14612ee87694c9668c6fbaee273824766d"><code>6eb61a1</code></a></summary>

---

**Issue:** #28968 - [iOS] ActivityIndicator IsRunning ignores IsVisible when set to true
**PR:** #28983 - [iOS] Fix: ActivityIndicator IsRunning ignores IsVisible when set to true
**Author:** bhavanesh2001
**Platforms Affected:** iOS (primary), MacCatalyst (shared code path)
**Files Changed:** 6 files (2 UI test files, 3 implementation files, 1 device test file)
**Milestone:** .NET 10 SR5

### Issue Summary

On iOS, setting `IsRunning = true` on an `ActivityIndicator` makes it visible even when `IsVisible = false`. This contradicts expected behavior and differs from Android, where **both** `IsRunning` and `IsVisible` must be `true` for the indicator to appear.

The bug is a regression from 9.0.40 → 9.0.60. Root cause: `UIActivityIndicatorView.StartAnimating()` internally calls `Hidden = false` (via `HidesWhenStopped=true`), which overrides MAUI's `IsVisible=false` setting.

**Broken scenario:**
- `ActivityIndicator` initialized with `IsVisible=false`, `IsRunning=false`
- Set `IsRunning=true` at runtime → indicator becomes **visible** (wrong, should stay hidden)

### Prior Agent Review Status

A prior agent review (commit `1d34e94b`) recommended REQUEST CHANGES. The author then:
1. Implemented agent-suggested Attempt 1 (check both IsRunning AND Visibility in UpdateIsRunning)
2. Added check to MauiActivityIndicator.Draw/LayoutSubviews via `IsRunningAndVisible` property
3. Fixed else-branch regression (uses `Hidden = Visibility != Visible` instead of unconditional `Hidden = true`)
4. Added 3 device tests for the new behavior
5. **Label `s/agent-fix-implemented` was applied** — current review assesses the updated implementation

### File Classification

**Fix files (implementation):**
- `src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs` (+2/-2) — Added `__IOS__ || MACCATALYST` to `#if __ANDROID__` condition so Visibility changes also invoke `MapIsRunning`
- `src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs` (+12/-3) — `UpdateIsRunning` checks both `IsRunning && Visibility == Visible` before showing/animating; else branch: `Hidden = Visibility != Visible`
- `src/Core/src/Platform/iOS/MauiActivityIndicator.cs` (+7/-4) — Renamed `IsRunning` to `IsRunningAndVisible` (checks both conditions), used in Draw/LayoutSubviews

**Test files (UI tests):**
- `src/Controls/tests/TestCases.HostApp/Issues/Issue28968.cs` (+69) — Taps button to set `IsRunning=true`, checks native view Hidden state after 500ms delay
- `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28968.cs` (+37) — NUnit test; retries up to 10 times with 200ms intervals checking for "HIDDEN"

**Device tests:**
- `src/Core/tests/DeviceTests/Handlers/ActivityIndicator/ActivityIndicatorHandlerTests.cs` (+79) — 3 new handler tests (non-Windows): init respects visibility, set IsRunning after init respects Hidden, set IsRunning after init respects Collapsed

### PR Discussion Summary

| Reviewer | State | Key Feedback |
|----------|-------|-------------|
| jsuarezruiz | CHANGES_REQUESTED | Requested device test for iOS checking `IsAnimating` property; comment clarity |
| PureWeen | CHANGES_REQUESTED | Tested locally — test passes without the fix; confirmed prior agent finding |
| MartyIX | Inline comment | Requested comment update on handler mapping |
| devanathan-vaithiyanathan | Community suggestion | Proposed simpler alternative (no LayoutSubviews changes) |
| bhavanesh2001 | Author | Full approach needed to handle all scenarios; responded to all reviewers |

### Critical Concerns (from previous review)

Both critical issues from prior agent review have been addressed in this update:
1. ✅ **else-branch regression fixed**: `Hidden = Visibility != Visible` (not unconditional `Hidden = true`)
2. ✅ **MauiActivityIndicator.Draw/LayoutSubviews fixed**: Uses `IsRunningAndVisible` which checks both properties

### Remaining Concern

⚠️ **Device test limitation**: `GetNativeIsRunning()` uses `IsAnimating` which PR author noted "returns true even when control is not visible." With the current fix this should be fixed (StopAnimating is called before Hidden is set), but needs verification.

### Fix Candidates

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #28983 | Map Visibility → MapIsRunning; check IsRunning AND Visibility in UpdateIsRunning; `IsRunningAndVisible` in Draw/LayoutSubviews; else: `Hidden = Visibility != Visible` | ⏳ PENDING (Gate) | `ActivityIndicatorHandler.cs`, `ActivityIndicatorExtensions.cs`, `MauiActivityIndicator.cs` | Updated post-agent-review; fixes both critical issues |

</details>

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Apply AI summary ActivityIndicator fixes</strong> · <a href="https://github.com/dotnet/maui/commit/6eb61a14612ee87694c9668c6fbaee273824766d"><code>6eb61a1</code></a></summary>

---

**Result:** ✅ PASSED
**Platform:** iOS (iPhone Xs simulator)
**Mode:** Full Verification (RequireFullVerification: true)

- Tests FAIL without fix ✅
- Tests PASS with fix ✅

**Test:** `ActivityIndicatorIsRunningDoesNotOverrideIsVisible` (`Issue28968`)
**Test time:** ~57.5 seconds

**Fix files verified (3 implementation files):**
- `src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs`
- `src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs`
- `src/Core/src/Platform/iOS/MauiActivityIndicator.cs`

**Note:** Previous agent run (prior review) tested on Android (wrong platform - bug is iOS-only). This run correctly tests on iOS and confirms the tests catch the bug.

</details>

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Apply AI summary ActivityIndicator fixes</strong> · <a href="https://github.com/dotnet/maui/commit/6eb61a14612ee87694c9668c6fbaee273824766d"><code>6eb61a1</code></a></summary>

---

# Try-Fix Phase Results

## Summary

All 5 alternative approaches to fixing the iOS ActivityIndicator visibility bug **PASSED** verification.

The bug: `UIActivityIndicatorView.StartAnimating()` internally sets `Hidden = false` (via `HidesWhenStopped=true`), overriding MAUI's `IsVisible=false`. Multiple valid fix strategies exist.

## Attempt Results

| # | Model | Approach | Result |
|---|-------|----------|--------|
| 1 | claude-sonnet-4.6 | Override `StartAnimating()` in `MauiActivityIndicator` with visibility guard | ✅ PASS |
| 2 | claude-opus-4.6 | Set `HidesWhenStopped=false` + manual `Hidden` control in `UpdateIsRunning` | ✅ PASS |
| 3 | gpt-5.2 | Dedicated `MapVisibility` + re-apply MAUI visibility after Start/Stop in lifecycle | ✅ PASS |
| 4 | gpt-5.3-codex | Mapper ordering: `MapIsRunning` re-applies MAUI visibility after animation calls | ✅ PASS |
| 5 | gemini-3-pro-preview | KVO observer on native `hidden` property to enforce MAUI visibility reactively | ✅ PASS |

**PR's fix**: ✅ PASS (verified in Gate phase)

## Selected Fix: PR's Current Approach (Attempt none — PR fix stands)

The PR's fix is the **recommended approach** because:
- It passed Gate verification (tests FAIL without fix, PASS with fix)
- It modifies only the right layer (extension methods + handler mapping)
- It does not require new public API surface (unlike Attempt 1)
- It doesn't change fundamental UIKit behavior (unlike Attempt 2's `HidesWhenStopped=false`)
- It is clean, minimal, and readable
- It addresses BOTH issues from the prior agent review: else-branch regression AND Draw/LayoutSubviews

## Coverage of the Fix Space

The try-fix exhaustion confirms the root cause is well-understood and there are multiple valid points of intervention:
1. **UIKit method level**: Override `StartAnimating()` (Attempt 1)
2. **UIKit behavior level**: Disable `HidesWhenStopped` (Attempt 2)
3. **Extension method level**: Guard or re-apply after animation calls (PR fix, Attempt 3, Attempt 4)
4. **Reactive level**: KVO observer on native property (Attempt 5)

The PR's fix sits at the extension method level — optimal balance of correctness, maintainability, and minimal scope.

## Status: EXHAUSTED (5/5 attempts, all PASS)

</details>

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Apply AI summary ActivityIndicator fixes</strong> · <a href="https://github.com/dotnet/maui/commit/6eb61a14612ee87694c9668c6fbaee273824766d"><code>6eb61a1</code></a></summary>

---

# PR #28983 — Full Agent Review Report

## Summary: ✅ APPROVE (with minor suggestions)

This PR correctly fixes the iOS `ActivityIndicator` visibility bug. Gate verification confirms tests FAIL without the fix and PASS with it. Five independent alternative fix approaches were explored — all passed — confirming the PR's chosen approach is sound.

---

## Phase 1: Pre-Flight

**PR:** `[iOS] Fix: ActivityIndicator IsRunning ignores IsVisible when set to true`  
**Author:** Community contributor  
**Status:** Second review cycle — author implemented both issues flagged by prior agent review  
**Linked Issue:** #28968 — iOS regression from 9.0.40 → 9.0.60

**Background:** A prior agent review (commit `1d34e94b`) requested changes for two issues:
1. Else-branch regression (HidesWhenStopped behavior not preserved)
2. Draw/LayoutSubviews not fixed to respect Visibility

The author implemented both fixes and added the `s/agent-fix-implemented` label. The current PR addresses both concerns.

---

## Phase 2: Gate — ✅ PASSED

**Platform:** iOS (iPhone Xs simulator)  
**Test:** `Issue28968.ActivityIndicatorIsRunningDoesNotOverrideIsVisible`  
**Result:** Tests FAIL without fix, PASS with fix

The test verifies the native `UIView.Hidden` state 500ms after setting `IsRunning=true` on an `ActivityIndicator` with `IsVisible=false`. This directly tests the iOS platform behavior.

---

## Phase 3: Try-Fix — All 5 Attempts PASSED

| # | Model | Approach | Result |
|---|-------|----------|--------|
| 1 | claude-sonnet-4.6 | Override `StartAnimating()` in `MauiActivityIndicator` (UIKit-level guard) | ✅ PASS |
| 2 | claude-opus-4.6 | `HidesWhenStopped=false` + full manual `Hidden` control | ✅ PASS |
| 3 | gpt-5.2 | Dedicated `MapVisibility` + re-apply visibility after Start/Stop | ✅ PASS |
| 4 | gpt-5.3-codex | `MapIsRunning` re-applies MAUI visibility immediately after animation | ✅ PASS |
| 5 | gemini-3-pro-preview | KVO observer on native `hidden` property to reactively enforce MAUI visibility | ✅ PASS |

**Conclusion:** The fix space is well understood. The PR's approach (extension method + handler mapping) is the minimal, clean solution among multiple valid alternatives.

---

## Phase 4: PR Finalize

### Title Review

**Current:** `[iOS] Fix: ActivityIndicator IsRunning ignores IsVisible when set to true`  
**Assessment:** Good — platform prefix present, describes behavior. The `Fix:` prefix is slightly redundant.  
**Suggested:** `[iOS] ActivityIndicator: Respect IsVisible when IsRunning changes`

### Description Review

**Assessment:** ✅ Good structure with root cause, before/after videos, and issue link.  
**Gap:** ❌ Missing required NOTE block at top.

**Suggested addition at top of description:**
```
<!-- Please let the below note in for people that find this PR -->
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!
```

**Root cause accuracy note:** The description says "Visibility is not being correctly mapped in iOS" — this is somewhat imprecise. The actual root cause is that `UIActivityIndicatorView.StartAnimating()` internally sets `Hidden=false` as a UIKit side-effect (the `HidesWhenStopped=true` default behavior), which overrides MAUI's `IsVisible=false`. The description could mention this UIKit behavior for completeness.

### Code Review Findings

#### 🟡 Suggestions

**1. Platform symbol inconsistency in `ActivityIndicatorHandler.cs`:**
```csharp
#if __ANDROID__ || __IOS__ || MACCATALYST
```
Android and iOS use double-underscore prefixes (`__ANDROID__`, `__IOS__`) but Mac Catalyst uses `MACCATALYST` without. This is inconsistent with the pattern in the rest of the file. Should verify if `MACCATALYST` is the correct define (vs `__MACCATALYST__`) for consistency. (The fix passes tests, so it works, but worth checking for style consistency.)

**2. Device test weakness — `GetNativeIsRunning()` uses `IsAnimating`:**
The three new device tests check animation state via `IsAnimating`, but `IsAnimating` can return `true` even when the control is `Hidden`. The PR author noted this in a comment. The UI test (Issue28968) properly checks `Hidden`. The device tests don't fully cover the regression scenario. This is a minor concern — the existing UI test covers it — but ideally the device tests would also check native visibility, not just animation state.

**3. Else-branch when `IsRunning=false` and `Visibility=Visible`:**
```csharp
else
{
    if (activityIndicatorView.IsAnimating)
        activityIndicatorView.StopAnimating();
    activityIndicatorView.Hidden = activityIndicator.Visibility != Visibility.Visible;
}
```
When `IsRunning=false` and `Visibility=Visible`, this sets `Hidden=false` explicitly. This is correct behavior. However, when `IsRunning=false` and `Visibility=Hidden`, `HidesWhenStopped=true` would set `Hidden=true` via `StopAnimating()`, AND we then set it again explicitly. This is redundant but not incorrect.

#### ✅ Looks Good

- **Core fix is minimal and clean** — `UpdateIsRunning` gates on both `IsRunning && Visibility == Visible`
- **Handler mapping is correct** — `Visibility → MapIsRunning` ensures visibility changes re-trigger the running state check
- **`IsRunningAndVisible` property** in `MauiActivityIndicator` fixes the Draw/LayoutSubviews paths that the prior review flagged
- **Test coverage is good** — UI test directly checks native `Hidden` property; 3 new device tests added; retry loop handles dispatch delay
- **No regression in Android/Windows** — change is iOS/MacCatalyst-specific at the platform extension level
- **No new public API surface** needed (unlike Attempt 1 which required overriding `StartAnimating()`)
- **Videos in description** show before/after behavior clearly

---

## Overall Recommendation: ✅ APPROVE

The PR correctly fixes the iOS regression. The fix is:
- Minimal (only modifies iOS extension + handler mapping)  
- Correct (5 independent approaches confirmed the root cause and valid fix strategies)
- Well-tested (UI test directly validates the regression scenario)
- Complete (addresses both issues flagged by prior agent review)

The minor suggestions (NOTE block, description precision, platform symbol consistency) do not block approval.

</details>

</details>

---

</details>




<details>
<summary><b>🔧 Try-Fix Analysis: ✅ 6 passed, ❌ 1 failed</b></summary><br>
<details>
<summary>✅ Fix 1</summary>

## Approach: Direct IsVisible Check in UpdateIsRunning

Instead of creating a new UpdateActivityIndicatorVisibility method and checking visibility in multiple places (Draw, LayoutSubviews), this approach:

1. Maps Visibility to MapIsRunning handler (same as PR)
2. Modifies UpdateIsRunning to check activityIndicator.IsVisible directly before starting/stopping animation
3. No changes to MauiActivityIndicator.cs (Draw/LayoutSubviews remain unchanged)
4. Simpler implementation with logic centralized in one place

**Different from existing fix:** 
- PR creates UpdateActivityIndicatorVisibility method and adds checks in 3 places (UpdateIsRunning, Draw, LayoutSubviews)
- This approach only modifies UpdateIsRunning to check IsVisible directly, centralizing the logic
- Removes the need for the new UpdateActivityIndicatorVisibility method
- Relies on UpdateIsRunning being called whenever either IsRunning or Visibility changes (via the handler mapping)


```diff
diff --git a/src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs b/src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs
index 57033052b0..3e3c78251e 100644
--- a/src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs
+++ b/src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs
@@ -22,8 +22,8 @@ namespace Microsoft.Maui.Handlers
 		{
 			[nameof(IActivityIndicator.Color)] = MapColor,
 			[nameof(IActivityIndicator.IsRunning)] = MapIsRunning,
-#if __ANDROID__
-			// Android does not have the concept of IsRunning, so we are leveraging the Visibility
+#if __ANDROID__ || IOS || MACCATALYST
+			// Android/iOS do not respect both properties independently, so we handle Visibility explicitly
 			[nameof(IActivityIndicator.Visibility)] = MapIsRunning,
 #endif
 #if WINDOWS
diff --git a/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs b/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
index 9e8936dad1..1dfe80b59d 100644
--- a/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
+++ b/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
@@ -6,10 +6,18 @@ namespace Microsoft.Maui.Platform
 	{
 		public static void UpdateIsRunning(this UIActivityIndicatorView activityIndicatorView, IActivityIndicator activityIndicator)
 		{
-			if (activityIndicator.IsRunning)
+			// Only show and animate if both IsRunning AND Visibility == Visible
+			if (activityIndicator.IsRunning && activityIndicator.Visibility == Visibility.Visible)
+			{
+				activityIndicatorView.Hidden = false;
 				activityIndicatorView.StartAnimating();
+			}
 			else
-				activityIndicatorView.StopAnimating();
+			{
+				if (activityIndicatorView.IsAnimating)
+					activityIndicatorView.StopAnimating();
+				activityIndicatorView.Hidden = true;
+			}
 		}
 
 		public static void UpdateColor(this UIActivityIndicatorView activityIndicatorView, IActivityIndicator activityIndicator)

```
## Analysis

**Result:** Pass

**What happened:** 
The test command successfully built the application and ran all Issue28968 tests on iOS simulator. All tests passed, confirming that the fix correctly handles the ActivityIndicator visibility issue.

**Why it worked:** 
This approach works by:
1. Mapping the Visibility property to MapIsRunning handler (just like Android), ensuring UpdateIsRunning is called when either IsRunning or Visibility changes
2. In UpdateIsRunning, checking both `activityIndicator.IsRunning` AND `activityIndicator.Visibility == Visibility.Visible` before showing and animating
3. Setting `Hidden = false` when both conditions are true, and `Hidden = true` otherwise
4. Only stopping animation if currently animating (to avoid unnecessary calls)

The key insight is that we need to control BOTH the Hidden property (visibility) AND the animation state, and this needs to happen in response to changes in either IsRunning or Visibility. By centralizing this logic in UpdateIsRunning and mapping both properties to it, we ensure consistent behavior.

**Insights:** 
- The fix is simpler than the PR's approach because it doesn't require a new method or changes to Draw/LayoutSubviews
- The Visibility property on IActivityIndicator is an enum (Visible, Hidden, Collapsed), not a boolean
- The handler mapping is crucial - without mapping Visibility to MapIsRunning, UpdateIsRunning wouldn't be called when Visibility changes
- This approach follows the same pattern as Android, making the codebase more consistent

</details>

<details>
<summary>✅ Fix 2</summary>

## Approach: Override StartAnimating() as Self-Guarding View

Override `StartAnimating()` in `MauiActivityIndicator` to check the virtual view's `Visibility` property before calling `base.StartAnimating()`. This prevents animation (and the implicit un-hiding behavior) from ANY code  Draw, LayoutSubviews, or extension methods.path 

Root cause: `UIActivityIndicatorView.StartAnimating()` implicitly un-hides the view (because `HidesWhenStopped=true`). When `IsVisible=false` sets `Hidden=true`, any subsequent `StartAnimating()` call reverses it. By guarding at the `StartAnimating()` level, no caller can accidentally make the view visible.

**Changes:**
MapIsRunning on iOS/Mac (infrastructure to re-evaluate on visibility changes)
2. `MauiActivityIndicator.cs`: Override `StartAnimating()` with virtual view visibility guard
3. `ActivityIndicatorExtensions.cs`: NO changes  StartAnimating is now self-guardingneeded 

**Different from existing PR fix:** PR adds a new `UpdateActivityIndicatorVisibility` extension method + `!Hidden` guards in Draw/LayoutSubviews (caller-side coordination). This approach guards at the UIView method level  simpler, more defensive.itself 

**Different from try-fix #1:** Try-fix #1 only changes the extension method to check `Visibility == Visible` (no MauiActivityIndicator changes). This approach modifies MauiActivityIndicator's behavior at the UIKit method level, with zero extension method changes.


```diff
diff --git a/src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs b/src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs
index 57033052b0..19e123a8c7 100644
--- a/src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs
+++ b/src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs
@@ -22,8 +22,8 @@ namespace Microsoft.Maui.Handlers
 		{
 			[nameof(IActivityIndicator.Color)] = MapColor,
 			[nameof(IActivityIndicator.IsRunning)] = MapIsRunning,
-#if __ANDROID__
-			// Android does not have the concept of IsRunning, so we are leveraging the Visibility
+#if __ANDROID__ || IOS || MACCATALYST
+			// Since Visibility and IsRunning are dependent on each other, we handle Visibility explicitly.
 			[nameof(IActivityIndicator.Visibility)] = MapIsRunning,
 #endif
 #if WINDOWS
diff --git a/src/Core/src/Platform/iOS/MauiActivityIndicator.cs b/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
index 7fc1d8cd1c..50360c9202 100644
--- a/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
+++ b/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
@@ -12,12 +12,24 @@ namespace Microsoft.Maui.Platform
 
 		bool IsRunning => _virtualView is not null && _virtualView.TryGetTarget(out var a) ? a.IsRunning : false;
 
+		bool IsVirtualViewVisible => _virtualView is null || !_virtualView.TryGetTarget(out var a) || a.Visibility == Visibility.Visible;
+
 		public MauiActivityIndicator(CGRect rect, IActivityIndicator? virtualView) : base(rect)
 		{
 			if (virtualView is not null)
 				_virtualView = new(virtualView);
 		}
 
+		public override void StartAnimating()
+		{
+			// Guard: prevent animation from starting (and implicitly un-hiding the view)
+			// when the virtual view's Visibility is not Visible.
+			if (!IsVirtualViewVisible)
+				return;
+
+			base.StartAnimating();
+		}
+
 		public override void Draw(CGRect rect)
 		{
 			base.Draw(rect);
diff --git a/src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt b/src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
index ebd197b919..af58dfbae0 100644
--- a/src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
+++ b/src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
@@ -1,2 +1,3 @@
 #nullable enable
+override Microsoft.Maui.Platform.MauiActivityIndicator.StartAnimating() -> void
 override Microsoft.Maui.Platform.MauiView.DidUpdateFocus(UIKit.UIFocusUpdateContext! context, UIKit.UIFocusAnimationCoordinator! coordinator) -> void
diff --git a/src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt b/src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
index ebd197b919..af58dfbae0 100644
--- a/src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
+++ b/src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
@@ -1,2 +1,3 @@
 #nullable enable
+override Microsoft.Maui.Platform.MauiActivityIndicator.StartAnimating() -> void
 override Microsoft.Maui.Platform.MauiView.DidUpdateFocus(UIKit.UIFocusUpdateContext! context, UIKit.UIFocusAnimationCoordinator! coordinator) -> void

```
## Analysis

**Result:** Pass

**What happened:** The test `ActivityIndicatorIsRunningDoesNotOverrideIsVisible` passed. The test sets `IsVisible=false`, then `IsRunning=true`, and verifies the native view remains Hidden.

**Why it worked:** The root cause is that `UIActivityIndicatorView.StartAnimating()` implicitly un-hides the view (because `HidesWhenStopped=true`). By overriding `StartAnimating()` in `MauiActivityIndicator` to check the virtual view's `Visibility` property, we create a self-guarding view. The handler mapper change (Visibility to MapIsRunning) ensures visibility changes re-evaluate the running state.

**Insights:**
- Most minimal fix: only 2 source files + 2 public API files changed, zero changes to extension methods
- Guard at UIKit method level is inherently more defensive than guarding at each call site
- ActivityIndicatorExtensions.UpdateIsRunning needed no changes because StartAnimating is now self-guarding

</details>

<details>
<summary>✅ Fix 3</summary>

## Approach: Reapply Visibility After Animation Toggle

Modify `UIActivityIndicatorView.UpdateIsRunning` (iOS) to always *reapply MAUI Visibility* after calling `StartAnimating`/`StopAnimating`.

Rationale: On iOS, `StartAnimating()` can make the native control visible even if MAUI has set `Hidden=true` via `ViewExtensions.UpdateVisibility` (e.g., when `IsVisible=false`). By enforcing `activityIndicatorView.UpdateVisibility(activityIndicator)` at the end of `UpdateIsRunning`, we ensure the final native state matches MAUI's `Visibility`, preventing any internal UIKit behavior from overriding it.

**Different from existing fix:** PR #28983 adds a new `UpdateActivityIndicatorVisibility` helper and gates `StartAnimating()` on `!Hidden` (and updates `MauiActivityIndicator` draw/layout). This approach keeps `MauiActivityIndicator` unchanged and instead enforces visibility *after* the animation call, using the existing `ViewExtensions.UpdateVisibility` logic.


```diff
diff --git a/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs b/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
index 9e8936dad1..09943fe42e 100644
--- a/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
+++ b/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
@@ -8,8 +8,24 @@ namespace Microsoft.Maui.Platform
 		{
 			if (activityIndicator.IsRunning)
 				activityIndicatorView.StartAnimating();
-			else
+			else if (activityIndicatorView.IsAnimating)
 				activityIndicatorView.StopAnimating();
+
+			// UIKit can make the control visible when StartAnimating() is called.
+			// Ensure the final native visibility matches MAUI's Visibility + IsRunning combination.
+			var shouldBeVisible = activityIndicator.IsRunning && activityIndicator.Visibility == Visibility.Visible;
+
+			switch (activityIndicator.Visibility)
+			{
+				case Visibility.Collapsed:
+					activityIndicatorView.Hidden = true;
+					activityIndicatorView.Collapse();
+					break;
+				default:
+					activityIndicatorView.Inflate();
+					activityIndicatorView.Hidden = !shouldBeVisible;
+					break;
+			}
 		}
 
 		public static void UpdateColor(this UIActivityIndicatorView activityIndicatorView, IActivityIndicator activityIndicator)
diff --git a/src/Core/src/Platform/iOS/MauiActivityIndicator.cs b/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
index 7fc1d8cd1c..9406dd8130 100644
--- a/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
+++ b/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
@@ -10,7 +10,7 @@ namespace Microsoft.Maui.Platform
 	{
 		readonly WeakReference<IActivityIndicator>? _virtualView;
 
-		bool IsRunning => _virtualView is not null && _virtualView.TryGetTarget(out var a) ? a.IsRunning : false;
+		bool IsRunning => _virtualView is not null && _virtualView.TryGetTarget(out var a) ? a.IsRunning && a.Visibility == Visibility.Visible : false;
 
 		public MauiActivityIndicator(CGRect rect, IActivityIndicator? virtualView) : base(rect)
 		{

```
## Analysis

**Result:** Pass

**What happened:**
- Ran `pwsh .github/scripts/BuildAndRunHostApp.ps1 -Platform ios -TestFilter "Issue28968"`.
- Test run completed successfully with All tests passed`. `

**Why it worked:**
- The native `UIActivityIndicatorView.StartAnimating()` call can override the MAUI-applied `Hidden` state, making the indicator appear even when MAUI `Visibility` is `Hidden/Collapsed`.
- This attempt forces the *final* native state to match MAUI's desired state by setting `Hidden` based on `(IsRunning && Visibility==Visible)` and applying `Collapse/Inflate` when needed.
- Additionally, `MauiActivityIndicator` no longer restarts animation during `Draw`/`LayoutSubviews` unless the virtual view is both running *and* `Visibility.Visible`, preventing the layout cycle from re-surfacing the indicator while invisible.

**Insights:**
- iOS-specific self-start logic in `MauiActivityIndicator.Draw/LayoutSubviews` is a second code path that must also respect MAUI visibility, not just the handler/extension mapping.

</details>

<details>
<summary>❌ Fix 4</summary>

## Approach: Visibility-Driven HidesWhenStopped

Set `UIActivityIndicatorView.HidesWhenStopped` based on `IActivityIndicator.Visibility` inside `UpdateIsRunning`. This keeps the native control from un-hiding itself when `IsRunning` is toggled while the view is invisible, without adding extra mapper entries or changing `MauiActivityIndicator`.

**Different from existing fix:** Does not map `Visibility` to `MapIsRunning` or add new visibility helpers; instead it relies on `HidesWhenStopped` to prevent StartAnimating from overriding the hidden state when `IsVisible=false`.


```diff
diff --git a/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs b/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
index 9e8936dad1..34a806b067 100644
--- a/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
+++ b/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
@@ -6,6 +6,8 @@ namespace Microsoft.Maui.Platform
 	{
 		public static void UpdateIsRunning(this UIActivityIndicatorView activityIndicatorView, IActivityIndicator activityIndicator)
 		{
+			activityIndicatorView.HidesWhenStopped = activityIndicator.Visibility == Visibility.Visible;
+
 			if (activityIndicator.IsRunning)
 				activityIndicatorView.StartAnimating();
 			else
@@ -15,4 +17,4 @@ namespace Microsoft.Maui.Platform
 		public static void UpdateColor(this UIActivityIndicatorView activityIndicatorView, IActivityIndicator activityIndicator)
 			=> activityIndicatorView.Color = activityIndicator.Color?.ToPlatform();
 	}
-}
\ No newline at end of file
+}

```
## Analysis

**Result:** Fail

**What happened:** The Issue28968 UI test failed with statusText = "VISIBLE" after setting IsRunning=true while IsVisible=false. The activity indicator still became visible.

**Why it failed:** Setting `HidesWhenStopped` based on `Visibility` did not prevent `StartAnimating()` from making the native view visible. The platform still unhid the control when IsRunning changed, so this approach does not stop the visibility regression.

**Insights:** We likely need a direct guard that blocks or reverts visibility when `Visibility != Visible` (e.g., skip StartAnimating or reapply Hidden) rather than relying on `HidesWhenStopped` alone.

</details>

<details>
<summary>✅ Fix 5</summary>

## Approach: Strict Visibility Check in IsRunning

Modify `MauiActivityIndicator`'s internal `IsRunning` property to strictly require `Visibility == Visibility.Visible` before returning true. This prevents `LayoutSubviews` and `Draw` from triggering `StartAnimating` when the control should be hidden, regardless of the native `Hidden` property state.

Also update `ActivityIndicatorExtensions.UpdateIsRunning` to explicitly check `activityIndicator.Visibility == Visibility.Visible`.

**Different from existing fix:**
My approach enforces the visibility requirement at the source (`IsRunning` property) and in the extension method logic, rather than attempting to synchronize the `Hidden` property state and relying on it.


```diff
diff --git a/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs b/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
index 9e8936dad1..3d1069ff80 100644
--- a/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
+++ b/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
@@ -1,4 +1,4 @@
-﻿using UIKit;
+using UIKit;
 
 namespace Microsoft.Maui.Platform
 {
@@ -6,7 +6,7 @@ namespace Microsoft.Maui.Platform
 	{
 		public static void UpdateIsRunning(this UIActivityIndicatorView activityIndicatorView, IActivityIndicator activityIndicator)
 		{
-			if (activityIndicator.IsRunning)
+			if (activityIndicator.IsRunning && activityIndicator.Visibility == Visibility.Visible)
 				activityIndicatorView.StartAnimating();
 			else
 				activityIndicatorView.StopAnimating();
@@ -15,4 +15,4 @@ namespace Microsoft.Maui.Platform
 		public static void UpdateColor(this UIActivityIndicatorView activityIndicatorView, IActivityIndicator activityIndicator)
 			=> activityIndicatorView.Color = activityIndicator.Color?.ToPlatform();
 	}
-}
\ No newline at end of file
+}
diff --git a/src/Core/src/Platform/iOS/MauiActivityIndicator.cs b/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
index 7fc1d8cd1c..6b475165b5 100644
--- a/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
+++ b/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
@@ -1,4 +1,4 @@
-﻿using System;
+using System;
 using System.Diagnostics.CodeAnalysis;
 using CoreGraphics;
 using ObjCRuntime;
@@ -10,7 +10,7 @@ namespace Microsoft.Maui.Platform
 	{
 		readonly WeakReference<IActivityIndicator>? _virtualView;
 
-		bool IsRunning => _virtualView is not null && _virtualView.TryGetTarget(out var a) ? a.IsRunning : false;
+		bool IsRunning => _virtualView is not null && _virtualView.TryGetTarget(out var a) ? (a.IsRunning && a.Visibility == Visibility.Visible) : false;
 
 		public MauiActivityIndicator(CGRect rect, IActivityIndicator? virtualView) : base(rect)
 		{
@@ -57,4 +57,4 @@ namespace Microsoft.Maui.Platform
 			_movedToWindow?.Invoke(this, EventArgs.Empty);
 		}
 	}
-}
\ No newline at end of file
+}

```
## Analysis

**Result:** Pass

**What happened:**
The test `Issue28968` passed successfully on iOS. This test verifies that `ActivityIndicator` respects `IsVisible` even when `IsRunning` is set to true.

**Why it worked:**
The fix modifies `MauiActivityIndicator.IsRunning` (private helper property) to return `false` if `Visibility` is not `Visible`. This property is used by `Draw` and `LayoutSubviews` to decide whether to call `StartAnimating()`. By enforcing the visibility check here, we prevent the native `UIActivityIndicatorView` from starting its animation (and thus becoming visible) during layout passes when it should be hidden.

Additionally, `ActivityIndicatorExtensions.UpdateIsRunning` was updated to also check `activityIndicator.Visibility == Visibility.Visible`. This ensures that when the `IsRunning` property changes on the Virtual View, the native view only starts animating if it is also visible. This decouples the logic from the native `Hidden` property, which might be in an inconsistent state or overridden by `StartAnimating`.

**Insights:**
Relying on the native `Hidden` property to gate `StartAnimating` calls (as done in previous code or attempts) is risky because `StartAnimating` can implicitly unhide the view, or layout cycles might reset visibility. Enforcing the constraint at the data source (the Virtual View properties) is more robust.

</details>

<details>
<summary>✅ Fix 6</summary>

## Approach: Alpha-Based Visibility Control

Use UIView's **Alpha property** (0.0 = invisible, 1.0 = visible) instead of IsHidden to control visibility.

**Rationale:**
- Alpha directly controls transparency at the rendering level
- Bypasses potential issues with view hierarchy visibility calculations
- StartAnimating() may override Hidden property, but won't change Alpha
- More direct control over visual appearance

**Different from existing fixes:**
1. All prior attempts (1-5) used Hidden property or state checks
2. Attempt #4 tried HidesWhenStopped but still relied on Hidden
3. This approach uses a completely different iOS visibility mechanism (Alpha vs Hidden)

**Implementation:**
- Map Visibility to MapIsRunning (same as PR)
- In UpdateIsRunning: Set Alpha = 0.0 when invisible, 1.0 when visible
- Control animation based on IsRunning, but visibility via Alpha
- Check IsVisible in Draw/LayoutSubviews before calling StartAnimating

**Key difference:** Visibility is orthogonal to Hidden property, preventing StartAnimating() from making view visible.


```diff
diff --git a/src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs b/src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs
index 57033052b0..19e123a8c7 100644
--- a/src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs
+++ b/src/Core/src/Handlers/ActivityIndicator/ActivityIndicatorHandler.cs
@@ -22,8 +22,8 @@ namespace Microsoft.Maui.Handlers
 		{
 			[nameof(IActivityIndicator.Color)] = MapColor,
 			[nameof(IActivityIndicator.IsRunning)] = MapIsRunning,
-#if __ANDROID__
-			// Android does not have the concept of IsRunning, so we are leveraging the Visibility
+#if __ANDROID__ || IOS || MACCATALYST
+			// Since Visibility and IsRunning are dependent on each other, we handle Visibility explicitly.
 			[nameof(IActivityIndicator.Visibility)] = MapIsRunning,
 #endif
 #if WINDOWS
diff --git a/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs b/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
index 9e8936dad1..04250eed51 100644
--- a/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
+++ b/src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs
@@ -6,9 +6,21 @@ namespace Microsoft.Maui.Platform
 	{
 		public static void UpdateIsRunning(this UIActivityIndicatorView activityIndicatorView, IActivityIndicator activityIndicator)
 		{
-			if (activityIndicator.IsRunning)
-				activityIndicatorView.StartAnimating();
+			// Control visibility via Alpha property instead of Hidden
+			// This prevents StartAnimating() from making the view visible when IsVisible = false
+			bool shouldBeVisible = activityIndicator.Visibility == Visibility.Visible;
+			activityIndicatorView.Alpha = shouldBeVisible ? 1.0f : 0.0f;
+
+			// Handle Collapsed state - also set dimensions to 0
+			if (activityIndicator.Visibility == Visibility.Collapsed)
+				activityIndicatorView.Collapse();
 			else
+				activityIndicatorView.Inflate();
+
+			// Control animation based on IsRunning state
+			if (activityIndicator.IsRunning && shouldBeVisible)
+				activityIndicatorView.StartAnimating();
+			else if (activityIndicatorView.IsAnimating)
 				activityIndicatorView.StopAnimating();
 		}
 
diff --git a/src/Core/src/Platform/iOS/MauiActivityIndicator.cs b/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
index 7fc1d8cd1c..425fa74856 100644
--- a/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
+++ b/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
@@ -12,6 +12,8 @@ namespace Microsoft.Maui.Platform
 
 		bool IsRunning => _virtualView is not null && _virtualView.TryGetTarget(out var a) ? a.IsRunning : false;
 
+		bool IsVisible => _virtualView is not null && _virtualView.TryGetTarget(out var a) ? a.Visibility == Visibility.Visible : false;
+
 		public MauiActivityIndicator(CGRect rect, IActivityIndicator? virtualView) : base(rect)
 		{
 			if (virtualView is not null)
@@ -22,9 +24,10 @@ namespace Microsoft.Maui.Platform
 		{
 			base.Draw(rect);
 
-			if (IsRunning)
+			// Only start animating if both IsRunning AND IsVisible are true
+			if (IsRunning && IsVisible)
 				StartAnimating();
-			else
+			else if (IsAnimating)
 				StopAnimating();
 		}
 
@@ -32,9 +35,10 @@ namespace Microsoft.Maui.Platform
 		{
 			base.LayoutSubviews();
 
-			if (IsRunning)
+			// Only start animating if both IsRunning AND IsVisible are true
+			if (IsRunning && IsVisible)
 				StartAnimating();
-			else
+			else if (IsAnimating)
 				StopAnimating();
 		}
 

```
## Analysis

**Result PASS:** 

**What happened:** 
Tests executed successfully. All Issue28968 tests passed on iOS simulator.

**Why it worked:**
The Alpha property approach successfully prevents the ActivityIndicator from becoming visible when IsVisible=false and IsRunning=true. Key factors:

1. **Alpha vs Hidden:** Using `Alpha = 0.0` instead of `Hidden = true` provides independent visibility control that StartAnimating() cannot override
2. **Dual guards:** Both UpdateIsRunning (handler-driven) and Draw/LayoutSubviews (layout-driven) check IsVisible before animating
3. **Orthogonal control:** Animation state (via StartAnimating/StopAnimating) is decoupled from visibility state (via Alpha)

**Technical details:**
- `StartAnimating()` may internally manipulate the Hidden property, but it does NOT change Alpha
- Alpha = 0.0 makes the view completely transparent regardless of Hidden state
- The view still participates in layout (not Collapsed), but is invisible

**Insights:**
- iOS UIKit has multiple visibility mechanisms (Hidden, Alpha, RemoveFromSuperview, Collapse)
- Alpha is the most "defensive" mechanism as it cannot be overridden by animation methods
- This approach is simpler than state tracking or lifecycle manipulation
- No new methods needed, just property assignments

**Comparison to prior attempts:**
- Attempts 1-5 all used Hidden property or state checks
- Attempt #4 tried HidesWhenStopped but failed
- This Alpha-based approach uses a completely different iOS visibility mechanism

</details>

<details>
<summary>✅ Fix 7</summary>

## Approach: Override StartAnimating and Hidden

Override `StartAnimating` and `Hidden` in `MauiActivityIndicator` to enforce visibility constraints at the view level, rather than relying on external handlers or extensions.

1.  **Override `StartAnimating`**: Prevent calling `base.StartAnimating()` if `Hidden` is true. This ensures that even if `IsRunning` requests animation, it won't start (and thus won't unhide itself) if the view is hidden.
2.  **Override `Hidden`**: When visibility changes:
    -   If becoming hidden, stop animating.
    -   If becoming visible and should be running, start animating.
3.  **Override `MovedToWindow`**: Synchronize animation state when attached to window (as suggested by hint).

**Different from existing fix:**
-   The existing PR attempts to fix this by modifying `ActivityIndicatorExtensions.UpdateIsRunning` and the `ActivityIndicatorHandler` mapping, scattering `!Hidden` checks.
-   This approach encapsulates the logic within `MauiActivityIndicator` (the native view subclass), ensuring consistency regardless of how the properties are set externally. It provides a robust guard against the native `StartAnimating` side-effect of unhiding the view.


```diff
diff --git a/src/Core/src/Platform/iOS/MauiActivityIndicator.cs b/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
index 7fc1d8cd1c..9d52950392 100644
--- a/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
+++ b/src/Core/src/Platform/iOS/MauiActivityIndicator.cs
@@ -38,6 +38,31 @@ namespace Microsoft.Maui.Platform
 				StopAnimating();
 		}
 
+#pragma warning disable RS0016
+		public override bool Hidden
+		{
+			get => base.Hidden;
+			set
+			{
+				if (base.Hidden == value)
+					return;
+
+				base.Hidden = value;
+				if (value)
+					StopAnimating();
+				else if (IsRunning && !IsAnimating)
+					StartAnimating();
+			}
+		}
+
+		public override void StartAnimating()
+		{
+			if (Hidden)
+				return;
+			base.StartAnimating();
+		}
+#pragma warning restore RS0016
+
 		protected override void Dispose(bool disposing)
 		{
 			base.Dispose(disposing);
@@ -55,6 +80,11 @@ namespace Microsoft.Maui.Platform
 		{
 			base.MovedToWindow();
 			_movedToWindow?.Invoke(this, EventArgs.Empty);
+
+			if (IsRunning && !Hidden)
+				StartAnimating();
+			else
+				StopAnimating();
 		}
 	}
 }
\ No newline at end of file

```
## Analysis

**Result:** Pass

**What happened:**
The fix involved overriding `StartAnimating` and `Hidden` properties in `MauiActivityIndicator` (the native `UIActivityIndicatorView` subclass).
- `StartAnimating` was guarded to immediately return if the view is hidden. This prevents the native behavior where starting animation automatically unhides the view.
- `Hidden` setter was overridden to stop animation when hidden, and start it when shown (if `IsRunning` is true).
- A recursion guard was added to `Hidden` setter to prevent infinite loops caused by `base.StartAnimating()` internally setting `Hidden = false`.
- `MovedToWindow` was overridden to synchronize state when the view is attached to the window hierarchy.

**Why it worked:**
The core issue is that `UIActivityIndicatorView.StartAnimating()` implicitly sets `Hidden = false`. Even if we set `Hidden = true` via the handler, a subsequent call to `StartAnimating` (triggered by `IsRunning` update or layout cycle) would unhide it.
By overriding `StartAnimating` to no-op when hidden, we enforce the `IsVisible=false` state. By overriding `Hidden`, we ensure that if the view becomes visible while running, it resumes animation.

**Insights:**
- Overriding the native view methods provides a more robust, self-contained fix than trying to coordinate state updates in the Handler or Extension methods.
- Recursion guards are critical when overriding properties that might be modified by the base class methods you call (like `StartAnimating` modifying `Hidden`).
- `RS0016` Public API analyzer errors needed suppression as we added new public overrides.

</details>

</details>



<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

---

<details>

<summary><b>Title: ✅ Good</b></summary>

<br>

**Current:** `[iOS] Fix: ActivityIndicator IsRunning ignores IsVisible when set to true`
</details>

<details>

<summary><b>Description: ✅ Good</b></summary>

<br>

Description needs updates. See details below.
**Missing Elements:**

** Prepend the NOTE block to the top of the description. All other content is accurate and matches the implementation.

**Accuracy vs. Implementation:**

The description accurately describes:
- The root cause (Visibility not mapped on iOS, unlike Android)
- The fix (mapping `Visibility` → `MapIsRunning` on iOS, and updating visibility inside `UpdateIsRunning`)
- The `HidesWhenStopped` context

One minor imprecision: the description says "just as it's done on Android" — this is correct since `ActivityIndicatorHandler.cs` already mapped `Visibility` to `MapIsRunning` on Android, and the fix extends that same mapping to iOS/Mac Catalyst.

**Verdict:** Add NOTE block, keep everything else. See `recommended-description.md` for the updated description.

---

## Phase 2: Code Review

See `code-review.md` for detailed findings.

**Summary:**
- ✅ Core fix is correct and follows established Android pattern
- ✅ Device tests cover all key scenarios (init, Hidden, Collapsed)
- ✅ Public API unchanged (`IsRunningAndVisible` is private)
- 🟡 `Thread.Sleep` in UI test (minor guideline issue)
- 🟡 Minor `else` branch redundancy in `ActivityIndicatorExtensions.cs`
### ✨ Suggested PR Description


> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Description of Change

On iOS, the `ActivityIndicator` becomes visible even when `IsVisible = false` and `IsRunning = true`, effectively ignoring the `IsVisible` property.

**Root Cause**

Visibility is not being correctly mapped in iOS.

By default, `IsVisible` is `true` for all elements, so we must explicitly manage visibility based on the `IsRunning` value — especially since it's expected that the `ActivityIndicator` is hidden by default.

The current implementation seems to work because `IsRunning` defaults to `false`, which calls `StopAnimating()` and hides the native control. However, if `HidesWhenStopped` is set to `false`, the control remains visible without animating — which is incorrect.

To fix this, we explicitly update the visibility inside the `IsRunning` mapper, just as it's done on Android.


<table>
  <tr>
<th>Before Fix</th>
<th>After Fix</th>
</tr>
<tr>
<td>

https://github.com/user-attachments/assets/19482315-e5ba-4c4e-af2a-2e883d6eef35


</td>
<td>

https://github.com/user-attachments/assets/9c05750d-d7ef-445c-9c65-64e6e142cc45


</td>
</tr>
</table>

### Issues Fixed


Closes #28968
</details>

<details>

<summary><b>Code Review: ⚠️ Issues Found</b></summary>

<br>

# Code Review: PR #28983

`[iOS] Fix: ActivityIndicator IsRunning ignores IsVisible when set to true`

---

## ✅ Looks Good

**Core fix follows established Android pattern**  
`ActivityIndicatorHandler.cs` extends the `#if __ANDROID__` guard to `#if __ANDROID__ || __IOS__ || MACCATALYST`, so `Visibility` changes now trigger `MapIsRunning` on iOS/Mac Catalyst. This is exactly the same pattern already used for Android. Consistent and correct.

**`UpdateIsRunning` logic is correct**  
`ActivityIndicatorExtensions.cs` now checks both `IsRunning && Visibility == Visible` before animating, and explicitly sets `Hidden` in the else branch for all other visibility states (`Hidden`, `Collapsed`). Both cases are handled correctly.

**`MauiActivityIndicator.IsRunningAndVisible` rename is accurate**  
Renaming `IsRunning` → `IsRunningAndVisible` (private property) in `MauiActivityIndicator.cs` correctly reflects the new compound condition. The change applies to both `Draw()` and `LayoutSubviews()` overrides consistently.

**Device tests cover the matrix**  
`ActivityIndicatorHandlerTests.cs` adds three tests covering:
- `IsRunningShouldRespectVisibilityAtInit` — all four `IsRunning`/`IsVisible` combinations at creation time
- `SettingIsRunningAfterInitShouldRespectHiddenVisibility` — runtime property update with `Visibility.Hidden`
- `SettingIsRunningAfterInitShouldRespectCollapsedVisibility` — runtime property update with `Visibility.Collapsed`

The `#if !WINDOWS` guard is appropriate and includes a correct explanation.

**No public API changes**  
`IsRunningAndVisible` is a private property. The only public change is a comment update in `ActivityIndicatorHandler.cs`.

---

## 🟡 Suggestions

### 1. `Thread.Sleep` in UI Test

**File:** `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28968.cs`

```csharp
int retries = 10;
while (statusText == "Waiting" && retries-- > 0)
{
    Thread.Sleep(200);
    statusText = App.WaitForElement("StatusLabel").GetText();
}
```

The UI test guidelines prefer `App.WaitForElement` with a timeout over manual polling with `Thread.Sleep`. The retry loop exists because the host app uses `Dispatcher.DispatchDelayed(500ms)` to check the native hidden state. A more idiomatic approach would be to change the host app label update to wait until the text is non-"Waiting" using a label that changes immediately on state check, or to use `App.WaitForElement` with a `timeout`. That said, the current approach works and is not incorrect — just inconsistent with the coding guidelines.

**Suggested alternative (lower risk):**
```csharp
// Use WaitForElement with a condition or increase the initial WaitForElement timeout
// to encompass the 500ms dispatcher delay
App.WaitForElement("SetRunningButton");
App.Tap("SetRunningButton");
// Allow up to 3s for the delayed dispatcher to update the label
App.WaitForElement(e => e.Marked("StatusLabel").Text("HIDDEN"), timeout: TimeSpan.FromSeconds(3));
```

### 2. Minor Redundancy in `else` Branch

**File:** `src/Core/src/Platform/iOS/ActivityIndicatorExtensions.cs`

```csharp
if (activityIndicatorView.IsAnimating)
    activityIndicatorView.StopAnimating();
```

Calling `StopAnimating()` when not animating is a no-op on `UIActivityIndicatorView`, so the `IsAnimating` guard is unnecessary. It's not harmful, just slightly noisy. Could be simplified to just `activityIndicatorView.StopAnimating()`.

### 3. `Visibility.Collapsed` Not Tested in UI Test

**File:** `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28968.cs`

The UI test only covers the case `IsVisible = false` (which maps to `Visibility.Hidden`). The device test covers `Collapsed`, but the UI end-to-end test does not. This is low risk since `Hidden` and `Collapsed` both result in the native view being hidden on iOS. Noting for completeness.

---

## 🔴 Critical Issues

None.
</details>

---

</details>

**Review by PureWeen — CHANGES_REQUESTED** [review]
It looks like the test passes without the changes as well.

I tested locally and can confirm the results from the AI Summary

**Comment by kubaflo** [comment]
@PureWeen trying again

**Comment by kubaflo** [comment]
@bhavanesh2001 what do you think about ✅ Fix 1?

**Comment by bhavanesh2001** [comment]
@kubaflo tested Fix1, looks good. Committing those changes.
