### PR TITLE
[MacOS] Fixed NullReferenceException when using ImagePaint

### LINKED ISSUE #19642: [graphics] PlatformCanvas.DrawImageCallback throws System.NullReferenceException when using ImagePaint on Mac/iOS
### Description

when using canvas from platform drawables, like in Maui 8.0 `GraphicsViewDemos`, whenever ImagePain is used on iOS/Mac (works on Android implementation), platform throws:
```console
Object reference not set to an instance of an object. (System.NullReferenceException)
   at Microsoft.Maui.Graphics.Platform.PlatformCanvas.DrawImageCallback(CGContext context)
   at CoreGraphics.CGPattern.DrawCallback(IntPtr voidptr, IntPtr cgcontextptr) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/CoreGraphics/CGPattern.cs:line 144
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at GraphicsViewDemos.Program.Main(String[] args) in /Users/blazejewicz/develop/maui-samples/8.0/UserInterface/Views/GraphicsViewDemos/GraphicsViewDemos/Platforms/MacCatalyst/Program.cs:line 13
```

so here:
https://github.com/dotnet/maui/blob/39440043ce9f69f0c8f275bc5a4dd083bdae1c7e/src/Graphics/src/Graphics/Platforms/MaciOS/PlatformCanvas.cs#L644
`_fillImage` is already released and null.

### Steps to Reproduce

1. Go to Maui samples
2. open `GraphicsViewDemos`
3. open `Image paint demo` page

Should render downsized bot image (as on Android), instead it crashes (image is drawn, but app crashes due to null pointer)

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/issues/336

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

Mac OS 14, iOS 15

### Did you find any workaround?

no

### Relevant log output

```shell
https://github.com/dotnet/maui-samples/issues/336#issuecomment-1873323734
```

### PR DESCRIPTION
**Pull request by NirmalKumarYuvaraj**
### Issue Details:
NullReferenceException is thrown when rendering image paint in Mac and iOS platforms.

### Root Cause:
"The _fillImage is set to null after the canvas is restored, but the DrawImageCallback is called after restoring the canvas. As a result, a NRE (Null Reference Exception) is thrown.

### Description of Change:
Introduced a new variable to store the _fillImage value and added a null check before calling the ToPlatformImage(). The image is drawn inversely so removed the transformation logic.

Reference:
https://github.com/dotnet/maui/blob/17a8b5a23aabbc10d01b5477cc1220c3135ecd46/src/Graphics/src/Graphics/Platforms/MaciOS/PlatformCanvas.cs#L740-L742

Validated the behaviour in the following platforms

- [x] Android
- [ ] Windows
- [x] iOS
- [x] Mac

### Issues Fixed

Fixes #19642

### Output

| Before | After |
| ------ | ----- |
|image| image|

### CODE REVIEW

File: src/Graphics/src/Graphics/Platforms/MaciOS/PlatformCanvas.cs [hunk 1]
```diff
@@ -766,7 +775,8 @@ private void FillWithImage(nfloat x, nfloat y, Action drawingAction)
 			transform.Multiply(currentTransform);
 			transform.Multiply(new CGAffineTransform(1.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f));
 
-			var pattern = new CGPattern(_fillPatternRect, transform, _fillImage.Width, _fillImage.Height, CGPatternTiling.NoDistortion, true, DrawImageCallback);
+			var imageToDraw = _fillImage;
```
Comment (NirmalKumarYuvaraj) [inline src/Graphics/src/Graphics/Platforms/MaciOS/PlatformCanvas.cs:778]: This is the change to resolve the NRE.

File: src/Graphics/src/Graphics/Platforms/MaciOS/PlatformCanvas.cs [hunk 2]
```diff
@@ -657,19 +670,15 @@ private void DrawImageCallback(CGContext context)
 #else
 				var cgImage = platformImage.CGImage;
 #endif
```
Comment (NirmalKumarYuvaraj) [inline src/Graphics/src/Graphics/Platforms/MaciOS/PlatformCanvas.cs:672]: This draws the image but inversed in view. The inverse logic is also handled before this method is called. So removed the duplication. Referred DrawPatternCallback().

File: src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ImagePaintShouldBeDrawn.png
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ImagePaintShouldBeDrawn.png:1]: Should the pattern start at 0,0?

Comment (NirmalKumarYuvaraj) [reply src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ImagePaintShouldBeDrawn.png:1]: @jsuarezruiz , For Windows and Mac platforms, the image and pattern are rendered in the same place, even though the x and y positions are passed as 0,0. The canvas draws them in the exact same location (slightly to the right of center).

image

Comment (jsuarezruiz) [reply src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ImagePaintShouldBeDrawn.png:1]: I think we need to create another issue and add a link to it with a comment in the test. We can keep it for now in this way until review the position issue.

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19642.cs [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+{
+	public Issue19642(TestDevice testDevice) : base(testDevice)
+	{
+	}
+
+	public override string Issue => "NullReferenceException when using ImagePaint on Mac/iOS";
+
+	[Test]
+	[Category(UITestCategories.GraphicsView)]
+	public void ImagePaintShouldBeDrawn()
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19642.cs:18]: Pending snapshot on Mac:
image
Could you commit it?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

**Review by mattleibow — CHANGES_REQUESTED** [review]
Is it possible to revert the changes that are not really part of the fix. I worry about conflicts with a change all over the file. Keep the fixes to the area that is being changed and hopefully we get there.

Otherwise, this PR is looking good. I see the `FillWithPattern` also has this issue and it also makes a temp copy.

**Comment by NirmalKumarYuvaraj** [comment]
> Is it possible to revert the changes that are not really part of the fix. I worry about conflicts with a change all over the file. Keep the fixes to the area that is being changed and hopefully we get there.
> 
> Otherwise, this PR is looking good. I see the `FillWithPattern` also has this issue and it also makes a temp copy.

@mattleibow , I have updated the code changes. please let me know if you have any concerns.

**Review by kubaflo — CHANGES_REQUESTED** [review]
Could you please review the AI's summary?

**Review by kubaflo — APPROVED** [review]
