### PR TITLE
Fix ArcSegment rendering

### LINKED ISSUE #6128: ArcSegments are rendered as straight lines
### Description

`ArcSegment` is rendered as straight line inside path geometries:

Here's a simple example:
```       
<Path
    Data="M 0,0 A 50,50 0 0 0 100,0"
    Stroke="Red"
    StrokeThickness="3"
    Aspect="Uniform"
    WidthRequest="100"
    HeightRequest="100"
/>
```
It should look like this:

image

But it looks like this:
image

Here is the same path with with the extended XAML notation:

```
<Path
    Stroke="Red"
    StrokeThickness="3"
    Aspect="Uniform"
    WidthRequest="100"
    HeightRequest="100">
    <Path.Data>
        <PathGeometry>
            <PathGeometry.Figures>
                <PathFigure IsClosed="False"
                    StartPoint="0,0">
                    <PathFigure.Segments>
                        <PathSegmentCollection>
                            <ArcSegment Point="100,0" Size="50,50" />
                        </PathSegmentCollection>
                    </PathFigure.Segments>
                </PathFigure>
            </PathGeometry.Figures>
        </PathGeometry>
    </Path.Data>
</Path>
```

### Steps to Reproduce

You can reproduce it with any of the 2 code snippets above.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

All

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix ArcSegment rendering.

Before
image
After
image

### Issues Fixed

Fixes #6128

### CODE REVIEW

File: src/Controls/src/Core/Shapes/PathGeometry.cs [hunk 1]
```diff
@@ -89,14 +90,25 @@ public override void AppendPath(PathF path)
 
 		void AddArc(PathF path, ArcSegment arcSegment, double density)
 		{
-			path.AddArc(
```
Comment (mattleibow) [inline src/Controls/src/Core/Shapes/PathGeometry.cs:92]: Doesn't AddArc work? Why are we working with lists pf points instead of letting the OS/framework do this?

**Review by mattleibow — DISMISSED** [review]

File: src/Controls/src/Core/Shapes/PathGeometry.cs (hunk 1 above)
Comment (mattleibow) [reply src/Controls/src/Core/Shapes/PathGeometry.cs:92]: I think we should fix it in graphics instead of working around it here.

Comment (jsuarezruiz) [reply src/Controls/src/Core/Shapes/PathGeometry.cs:92]: I agree. To include a fix soon (in this case, this problem is impacting a partner), do you mind if we merge this fix, open issue in Maui Graphics and as soon as we update Graphics with the fix we update this part?

**Review by Redth — APPROVED** [review]

File: src/Controls/src/Core/Shapes/PathGeometry.cs (hunk 1 above)
Comment (mattleibow) [reply src/Controls/src/Core/Shapes/PathGeometry.cs:92]: No problem! Help the partner out 🤗 Maybe link to an issue or the PR fix here for historical information.
