### PR TITLE
[Android & iOS] Use the correct colors by themes with Alerts on Android and iOS

### LINKED ISSUE #6092: The prompts displayed by DisplayAlert do not follow the theme set
### Description

The prompts displayed by DisplayAlert do not adhere to the theme set by using `Application.Current.UserAppTheme`.

image

### Steps to Reproduce

1. Set the theme to dark using `Application.Current.UserAppTheme = AppTheme.Dark;`
2. Send a DisplayAlert on the main page on Android. The theme will not be respected and it will use the default light theme.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30, Android 11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Use the correct colors by themes with Alerts on Android and iOS.

Light
image

Dark
image

### Issues Fixed

Fixes #6092

### CODE REVIEW

File: src/Core/src/Platform/Android/ApplicationExtensions.cs [hunk 1]
```diff
@@ -60,5 +62,24 @@ public static Bundle ToBundle(this IPersistedState? state)
 
 			return userInfo;
 		}
+
+		public static void UpdateNightMode(this IApplication application)
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/ApplicationExtensions.cs:66]: Main change on Android.

File: src/Core/src/Platform/iOS/ApplicationExtensions.cs [hunk 2]
```diff
@@ -125,5 +126,29 @@ public static NSUserActivity ToUserActivity(this IPersistedState? state, string
 
 			return userActivity;
 		}
+
+		public static void UpdateUserInterfaceStyle(this IApplication application)
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/ApplicationExtensions.cs:130]: Main change on iOS.

File: src/Core/src/Hosting/LifecycleEvents/AppHostBuilderExtensions.Android.cs [hunk 3]
```diff
@@ -76,7 +78,13 @@ static void OnConfigureWindow(IAndroidLifecycleBuilder android)
...
 					if (IPlatformApplication.Current is IPlatformApplication platformApplication)
 					{
-						platformApplication.Application?.ThemeChanged();
+						var application = platformApplication.Application;
+
+						if (application is not null)
+						{
+							application.UpdateNightMode();
+							application.ThemeChanged();
+						}
```
Comment (mandel-macaque) [inline src/Core/src/Hosting/LifecycleEvents/AppHostBuilderExtensions.Android.cs:87]: Since they are methods, why not use:
```suggestion
						application?.UpdateNightMode();
						application?.ThemeChanged();
```

If I am not misspend the IL with the if will add a extra bool to the stack, but honestly FELL FREE TO IGNORE this comment.

File: src/Core/src/Platform/iOS/PageViewController.cs [hunk 4]
```diff
@@ -28,7 +27,13 @@ public override void TraitCollectionDidChange(UITraitCollection? previousTraitCo
...
 			{
 				var application = handler.GetRequiredService<IApplication>();
-				application?.ThemeChanged();
+
+				if (application is not null)
+				{
+					application.UpdateUserInterfaceStyle();
+
+					application.ThemeChanged();
+				}
```
Comment (mandel-macaque) [inline src/Core/src/Platform/iOS/PageViewController.cs:36]: Same comment

**Review by mandel-macaque — APPROVED** [review]
LGTM

File: src/Core/src/Hosting/LifecycleEvents/AppHostBuilderExtensions.Android.cs (hunk 3 above)
Comment (jsuarezruiz) [reply src/Core/src/Hosting/LifecycleEvents/AppHostBuilderExtensions.Android.cs]: You are right. Changed.

File: src/Core/src/Platform/Android/ApplicationExtensions.cs (hunk 1 above)
Comment (rmarinho) [inline src/Core/src/Platform/Android/ApplicationExtensions.cs:66]: Should this be called inside ThemeChanged so if the theme changes this gets updated also? Seems this way it will only run initially.

File: src/Core/src/Platform/iOS/ApplicationExtensions.cs [hunk 5]
```diff
@@ -125,5 +126,29 @@ public static NSUserActivity ToUserActivity(this IPersistedState? state, string
...
+		{
+			if (application is null)
+				return;
+
+			var currentViewController = WindowStateManager.Default.GetCurrentUIViewController(false);
```
Comment (rmarinho) [inline src/Core/src/Platform/iOS/ApplicationExtensions.cs:135]: If I have multiple windows don't I want to update the theme in all windows and not just the active one?

File: src/Core/src/Platform/iOS/PageViewController.cs [hunk 6]
```diff
@@ -28,6 +27,8 @@ public override void TraitCollectionDidChange(UITraitCollection? previousTraitCo
 			if (CurrentView?.Handler is ElementHandler handler)
 			{
 				var application = handler.GetRequiredService<IApplication>();
+
+				application?.UpdateUserInterfaceStyle();
```
Comment (rmarinho) [inline src/Core/src/Platform/iOS/PageViewController.cs:31]: Like above, should this be inside ThemeChanged?

File: src/Core/src/Platform/Android/ApplicationExtensions.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/ApplicationExtensions.cs:66]: Is invoked every time the theme changes here https://github.com/dotnet/maui/blob/17bb272bebaa227687447a44d8f54df3b0b66efc/src/Core/src/Hosting/LifecycleEvents/AppHostBuilderExtensions.Android.cs#L83

Do you mean to invoke it inside the `ThemeChanged` method? ThemeChanged fires the RequestedThemeChanged event from the .NET MAUI Application. I could move it inside but we would have to either use compiler directives or create a service or similar and use the interface from Application.

File: src/Core/src/Platform/iOS/ApplicationExtensions.cs (hunk 5 above)
Comment (rmarinho) [reply src/Core/src/Platform/iOS/ApplicationExtensions.cs:135]: What happens if I have 2 windows?

**Review by rmarinho — APPROVED** [review]

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz please test with 2 windows on maccatalyst see if it updates in both.

Yes, it updates both.

From Light:
Captura de pantalla 2023-03-02 a las 13 39 36

To Dark:
Captura de pantalla 2023-03-02 a las 13 37 17

**Review by jfversluis — APPROVED** [review]

**Comment by everythingbytesnz** [comment]
How do I upgrade my version of MAUI to use this fix? I can't see which nuget packages to upgrade or install in my .NET solution.
