### PR TITLE
[Windows] Correctly size the ImageButton BitmapImage

### LINKED ISSUE #4913: ImageButton Image not scaling down by Width- and HeightRequest
### Description

When an ImageButton is sized by using the Width- and HeighRequest, the image inside is not sized down as well, but instead cropped. This means, that only a part of the image is visible inside the button.

P. S.: I don't know which MAUI version I am using. I have the VS2022 version *17.2.0 Preview* installed.

### Steps to Reproduce

Add the following line of code to the example Maui-App:
```C#
 <ImageButton
                Source="dotnet_bot.png"
                WidthRequest="40"
                HeightRequest="40" />
```

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 (OS build 19044.1526)

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Correctly size the Windows ImageButton BitmapImage.

image

### Issues Fixed

Fixes #4913

### CODE REVIEW

File: src/Core/src/Platform/Windows/ButtonExtensions.cs [hunk 1]
```diff
@@ -171,9 +171,13 @@ void OnImageOpened(object sender, RoutedEventArgs e)
 							{
 								// do the actual resize
 								var imageSourceSize = actualImageSource.GetImageSourceSize(platformButton);
-								nativeImage.Width = imageSourceSize.Width;
-								nativeImage.Height = imageSourceSize.Height;
+
+								nativeImage.Width = button.Width > 0 ? platformButton.ActualWidth : imageSourceSize.Width;
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Windows/ButtonExtensions.cs:175]: If ImageButton HeightRequest and WidthRequest properties have been set we use that values on the image. Otherwise, the height and width of the original image size is used.

**Review by mattleibow — COMMENTED** [review]
What happens when the the button changes size? Also, is this possible to be tested?

File: src/Core/src/Platform/Windows/ButtonExtensions.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Windows/ButtonExtensions.cs]: Applied changes to use `Primitives.Dimension.Unset`, also added a sample:
fix-imagebutton-size

Is working correctly and also resize as expected.

**Review by rachelkang — APPROVED** [review]
