### PR TITLE
Ensure OnMeasure always calls SetMeasuredDimension in ShellPageContainer

### LINKED ISSUE #13152: IllegalStateException: ShellPageContainer#onMeasure() did not set the measured dimension by calling setMeasuredDimenstion()
### Description

I've seen this report sporadically in the wild (via AppCenter) but I haven't yet been able to reproduce.

May be related to #10776 ?

Is it possible for there to be a case where `Child.NativeView` is not an `Android.Views.View` (or becomes null?) during a layout cycle? Perhaps `SetMeasuredDimension` should always be called regardless of `Child.PlatformView`?

https://github.com/dotnet/maui/blob/50e28913c29c780fb1d012e1d23bc9a9ece2ec64/src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellPageContainer.cs#L50-L58

### Steps to Reproduce

pending

### Link to public reproduction project repository

pending

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8.1, 9, 10

### Did you find any workaround?

_No response_

### Relevant log output

```shell
android.view.View.measure View.java:22298
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild CoordinatorLayout.java:795
com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild HeaderScrollingViewBehavior.java:100
com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild AppBarLayout.java:2253
androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure CoordinatorLayout.java:866
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.FrameLayout.onMeasure FrameLayout.java:185
android.view.View.measure View.java:22286
android.widget.LinearLayout.measureVertical LinearLayout.java:975
android.widget.LinearLayout.onMeasure LinearLayout.java:702
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.FrameLayout.onMeasure FrameLayout.java:185
android.view.View.measure View.java:22286
androidx.drawerlayout.widget.DrawerLayout.onMeasure DrawerLayout.java:1156
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.LinearLayout.measureChildBeforeLayout LinearLayout.java:1539
android.widget.LinearLayout.measureHorizontal LinearLayout.java:1184
android.widget.LinearLayout.onMeasure LinearLayout.java:704
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.FrameLayout.onMeasure FrameLayout.java:185
androidx.appcompat.widget.ContentFrameLayout.onMeasure ContentFrameLayout.java:145
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.FrameLayout.onMeasure FrameLayout.java:185
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.FrameLayout.onMeasure FrameLayout.java:185
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.LinearLayout.measureChildBeforeLayout LinearLayout.java:1539
android.widget.LinearLayout.measureVertical LinearLayout.java:823
android.widget.LinearLayout.onMeasure LinearLayout.java:702
android.view.View.measure View.java:22286
android.view.ViewGroup.measureChildWithMargins ViewGroup.java:6668
android.widget.FrameLayout.onMeasure FrameLayout.java:185
com.android.internal.policy.DecorView.onMeasure DecorView.java:837
android.view.View.measure View.java:22286
android.view.ViewRootImpl.performMeasure ViewRootImpl.java:2646
android.view.ViewRootImpl.measureHierarchy ViewRootImpl.java:1674
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:1933
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1558
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:7463
android.view.Choreographer$CallbackRecord.run Choreographer.java:1041
android.view.Choreographer.doCallbacks Choreographer.java:847
android.view.Choreographer.doFrame Choreographer.java:774
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:1027
android.os.Handler.handleCallback Handler.java:809
android.os.Handler.dispatchMessage Handler.java:102
android.os.Looper.loop Looper.java:166
android.app.ActivityThread.main ActivityThread.java:7555
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:469
com.android.internal.os.ZygoteInit.main ZygoteInit.java:963
```
```

### PR DESCRIPTION
**Pull request by BioTurboNick**
### Description of Change

Android documentation (https://developer.android.com/reference/android/view/View#setMeasuredDimension(int,%20int)) says `SetMeasuredDimension` must be called prior to exiting `OnMeasure`. Currently, `ShellPageContainer` allows a condition where this contract may be violated, leading to rare run-time exceptions (See #13152, #10776).

It seems that this pattern existed at one point for `PageContainer`, but has since changed to always call this method.

~Android docs say that calling the base `OnMeasure` method is sufficient. I'm not aware of other design considerations, so I just picked that one to submit.~ Corrected this to the pattern I observed in other MAUI code, to use `MeasureSpec.GetSize` to call `SetMeasuredDimension`.

### Issues Fixed

Fixes #13152, #10776

### CODE REVIEW

**Review by mandel-macaque — APPROVED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellPageContainer.cs [hunk 1]
```diff
@@ -54,6 +54,8 @@ protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
 				aView.Measure(widthMeasureSpec, heightMeasureSpec);
 				SetMeasuredDimension(aView.MeasuredWidth, aView.MeasuredHeight);
 			}
+			else
+				SetMeasuredDimension(MeasureSpec.GetSize(widthMeasureSpec), MeasureSpec.GetSize(heightMeasureSpec));
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellPageContainer.cs:58]: I think here we can just pass in `SetMeasuredDimension(0,0)` 

If the PlatformView isn't present we don't really need/want this to measure out to anything. This is most likely happening during a weird limbo state where the view is being removed or changed out.

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellPageContainer.cs (hunk 1 above)
Comment (BioTurboNick) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellPageContainer.cs]: Done!

Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellPageContainer.cs]: Perfect! Thank You!

**Review by PureWeen — APPROVED** [review]

**Comment by espenrl** [comment]
@BioTurboNick will this one be backported to .NET 7?

**Comment by Noobicle** [comment]
@BioTurboNick Sorry to bother you. Did you find a workaround or catch for this?

**Comment by BioTurboNick** [comment]
> @BioTurboNick Sorry to bother you. Did you find a workaround or catch for this?

Sorry, I have not, but I haven't put a lot of effort into it b/c it seems to be a rare enough scenario. Not even sure anyone notices it, I haven't gotten feedback related to it from users.

**Comment by Noobicle** [comment]
@BioTurboNick No need for apologies. It's mostly me being a bit obsessed with closing bugs :D. Hopefully I'll get away with it :).

Thank you.

**Comment by cjonstrup** [comment]
Im also looking for a workaround :-)

Thanks

**Comment by dartasen** [comment]
@PureWeen Any chance we can get a backport for .NET 7 ? This is a pretty annoying bug, especially because it happens a lot while navigating back and forth with customized titleview.
