### PR TITLE
[iOS] Back-navigation with swipe-back navigates back twice - fix

### LINKED ISSUE #28446: [iOS] Back-navigation with swipe-back navigates back twice
### Description

When using swipe-back to navigate backwards, the back-navigation occurs twice. 

Image

### Steps to Reproduce

1. Clone https://github.com/Vetle444/MauiTestApp/tree/swipeBackBug (swipeBackbug branch)
2. Run app
3. Click navigate
4. Click navigate again, so you are at page 2
5. Initiate a swipe-back
6. Observe that after you have been navigated back using swipe-back, you get navigated back again

Expected outcome: You land at Page 1 after swipe-back
Actual outcome: You land at Main Page after swipe-back

### Link to public reproduction project repository

https://github.com/Vetle444/MauiTestApp/tree/swipeBackBug

### Version with bug

9.0.50 SR5

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.40 SR4

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
## Description

I've made changes to iOS special back navigation in this PR: https://github.com/dotnet/maui/pull/24003, but didn't account for the siwpe gesture that behaves differently that the callout-menu-click navigation

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/28446
Fixes https://github.com/dotnet/maui/issues/28572

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/033e476b-3296-4686-983a-afeb8fcf59c6" width="300px"/>|<video src="https://github.com/user-attachments/assets/65efeb4c-d9a6-42f6-b084-8ad71b2b77e3" width="300px"/>|

### CODE REVIEW

**Review by mattleibow — CHANGES_REQUESTED** [review]
Is it possible to write a UI test for this? I think that the swipe gestures should work?

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs [hunk 1]
```diff
@@ -610,6 +610,7 @@ public override void PushViewController(UIViewController viewController, bool an
 
 		public override UIViewController PopViewController(bool animated)
 		{
+			_popRequested = true;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs:613]: Could you include an UITest based on https://github.com/Vetle444/MauiTestApp/tree/swipeBackBug?
Can use `App.SwipeLeftToRight();` in the test.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs (hunk 1 above)
Comment (kubaflo) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs:613]: Unfortunately, it doesn't work for this iOS-specific-swipe-back gesture

**Comment by kubaflo** [comment]
> Is it possible to write a UI test for this? I think that the swipe gestures should work?

`App.SwipeLeftToRight();` doesn't work :/

**Comment by jfversluis** [comment]
Author of the issue confirms this seems to fix it: https://github.com/dotnet/maui/issues/28446#issuecomment-2743060497

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/28572?reload=1

**Review by PureWeen — DISMISSED** [review]

**Review by jsuarezruiz — APPROVED** [review]

**Comment by kubaflo** [comment]
@sheiksyedm I believe this should help :) https://github.com/dotnet/maui/pull/28644
