### PR TITLE
[Windows]Fixed the ViewExtensions RotateYTo and RotateXTo with length 0 crashes

### LINKED ISSUE #18420: [Windows]ViewExtensions RotateYTo and RotateXTo with length 0 crashes on Windows
### Description

When using RotateYTo or RotateXTo with a length of 0, the app crashes on Windows, but not on Android.

There is no crash with other ViewExtension methods (translation, scaling, other rotations), only these two.

### Steps to Reproduce

1. Create new .NET MAUI App
2. In MainPage.xaml.cs OnCounterClicked, add `CounterBtn.RotateXTo(10, 0);`
3. Start app & click button, the app should crash

### Link to public reproduction project repository

https://github.com/HubbleCommand/ReproApp

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

Use a non-zero timeout i.e. 1, which creates the same visual effect.

### Relevant log output

```shell
Exception thrown: 'System.ArgumentException' in WinRT.Runtime.dll
```

### PR DESCRIPTION
**Pull request by Ahamed-Ali**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause of the issue

- When RotateYTo is dynamically updated with a duration of 0, it causes the value calculation in Tweener class to result in NaN. This NaN value is then passed to the UpdatedTransformation method on Windows, where the subtraction between the PlaneProjection's Rotation property and the MAUI rotation leads to an ArgumentException.

https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Tweener.cs#L124 

### Description of Change

- If the calculated value is NaN, a defensive check is added to prevent invalid transformations from being applied. This ensures that when any rotation value is NaN (Not a Number), it is skipped. On subsequent updates, a valid value will be used, allowing the transformation to proceed as expected.

### Issues Fixed

Fixes #18420

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Screenshot

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/a4cbab59-14a3-4d2e-9a15-1bd547c2fdc7"> | <video src="https://github.com/user-attachments/assets/186e40ba-b79f-4934-a613-1da47c8c82f4"> |

### CODE REVIEW

File: src/Core/src/Platform/Windows/TransformationExtensions.cs [hunk 1]
```diff
@@ -37,6 +37,10 @@ public static void UpdateTransformation(this FrameworkElement frameworkElement,
 				// rotation values are set, but the aforementioned functionality will be lost.
 				if (Math.Abs(view.RotationX) != 0 || Math.Abs(view.RotationY) != 0)
```
Comment (MartyIX) [inline src/Core/src/Platform/Windows/TransformationExtensions.cs]: Is there any reason this is not 
```suggestion
				if (Math.Abs(rotationX) != 0 || Math.Abs(rotationY) != 0)
```
?

File: src/Core/src/Platform/Windows/TransformationExtensions.cs [hunk 2]
```diff
@@ -37,6 +37,10 @@ public static void UpdateTransformation(this FrameworkElement frameworkElement,
...
 				{
+					if (double.IsNaN(rotationX) || double.IsNaN(rotationY) || double.IsNaN(rotation))
+					{
+						return;
+					}
```
Comment (MartyIX) [inline src/Core/src/Platform/Windows/TransformationExtensions.cs]: btw: Given your patch, is it safe to pass NaN here: https://github.com/dotnet/maui/blob/8c38d34c6a014f575c82291e588ab85ec0fa42cd/src/Core/src/Platform/Windows/TransformationExtensions.cs#L59 ?

File: src/Controls/tests/TestCases.HostApp/Issues/Issue18420.cs [hunk 3]
```diff
@@ -0,0 +1,35 @@
+﻿namespace Maui.Controls.Sample.Issues;
+
+[Issue(IssueTracker.Github, 18420, "[Windows]ViewExtensions RotateYTo and RotateXTo with length 0 crashes on Windows", PlatformAffected.UWP)]
```
Comment (MartyIX) [inline src/Controls/tests/TestCases.HostApp/Issues/Issue18420.cs]:
```suggestion
[Issue(IssueTracker.Github, 18420, "[Windows] ViewExtensions RotateYTo and RotateXTo with length 0 crashes on Windows", PlatformAffected.UWP)]
```

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18420.cs [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+using UITest.Appium;
+using UITest.Core;
+
+namespace Microsoft.Maui.TestCases.Tests.Issues;
+
+public class Issue18420 : _IssuesUITest
+{
+	public Issue18420(TestDevice device) : base(device) { }
+
+	public override string Issue => "[Windows]ViewExtensions RotateYTo and RotateXTo with length 0 crashes on Windows";
```
Comment (MartyIX) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18420.cs]:
```suggestion
	public override string Issue => "[Windows] ViewExtensions RotateYTo and RotateXTo with length 0 crashes on Windows";
```

File: src/Core/src/Platform/Windows/TransformationExtensions.cs (hunk 1 above)
Comment (Ahamed-Ali) [reply src/Core/src/Platform/Windows/TransformationExtensions.cs]: Now, I have reused the local variable @MartyIX

File: src/Core/src/Platform/Windows/TransformationExtensions.cs (hunk 2 above)
Comment (Ahamed-Ali) [reply src/Core/src/Platform/Windows/TransformationExtensions.cs]: Yes, it's safe to pass NaN in this case because no mathematical operations are performed on it, so no exception occurs. A valid value will be updated during the subsequent continuous updates. @MartyIX

File: src/Controls/tests/TestCases.HostApp/Issues/Issue18420.cs (hunk 3 above)
Comment (Ahamed-Ali) [reply src/Controls/tests/TestCases.HostApp/Issues/Issue18420.cs]: updated

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18420.cs (hunk 4 above)
Comment (Ahamed-Ali) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18420.cs]: updated

**Review by jfversluis — APPROVED** [review]
