### PR TITLE
[Android] Fix issue creating ColorStateLists from extension methods

### LINKED ISSUE #6727: Enabling CheckBox does not change visual state
### Description

If a checkbox is enabled, you can toggle the checkbox, but the visual state is still grayed out (like disabled).
Screenshot_20220502-084913 (002)

### Steps to Reproduce

1. Create new Maui App
2. Replace MainPage.xaml with

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:telerikDataControls="clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.Maui.Controls.Compatibility"
             xmlns:telerikChart="clr-namespace:Telerik.XamarinForms.Chart;assembly=Telerik.Maui.Controls.Compatibility"
             xmlns:telerikListView="clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.Maui.Controls.Compatibility"
             x:Class="MauiApp1.MainPage">

    <VerticalStackLayout>
        <CheckBox CheckedChanged="CheckBox_CheckedChanged"/>
        <CheckBox x:Name="Cb2" IsEnabled="False" />
    </VerticalStackLayout>
</ContentPage>

```

and MainPage.xaml.cs with

```
namespace MauiApp1;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}

    private void CheckBox_CheckedChanged(object sender, CheckedChangedEventArgs e)
    {
		Cb2.IsEnabled = true;
    }
}
```

4. Deploy App
5. Toggle first checkbox, second checkbox is now enabled (and working) but still grayed out

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 7 and later, Windows 10/11

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix issue with Android CheckBox colors.

Disabled
Screenshot_1653642321

Normal
Screenshot_1653642324

Before these changes, The CheckBox disabled color was the same as enabled.

### CODE REVIEW

**Review by PureWeen — CHANGES_REQUESTED** [review]
I don't think this fix is correct. If a user wants to express different colors for different states then they have to use a VSM.  Forcing the disabled color to be its own color apart from the colors specified on the control makes it impossible for a user to style the checkbox when it's "disabled". See from this example here against this PR.

I feel like we need to detect if a user has attached a VSM or not. Which I think is how WinUI works. So if the user hasn't attached a VSM then we could make it work like this. I think we did something like that for button in XF. Not to say we should do that with this PR but I don't think this PR is correct given the current design of the system. The original bug might be an issue with the VSM. The default styles in our template should cause the color to change when the checkbox state changes

image

**Comment by Symbai** [comment]
> Forcing the disabled color to be its own color apart from the colors specified on the control makes it impossible for a user to style the checkbox when it's "disabled"

I second this. I am running into a lot of issues with trying to change colors because there are so many "hardcoded" colors in the controls. This is a huge problem when a developer, like me, works with a custom background color.

**Comment by jsuarezruiz** [comment]
> I don't think this fix is correct. If a user wants to express different colors for different states then they have to use a VSM. Forcing the disabled color to be its own color apart from the colors specified on the control makes it impossible for a user to style the checkbox when it's "disabled". See from this example here against this PR.
> 
> I feel like we need to detect if a user has attached a VSM or not. Which I think is how WinUI works. So if the user hasn't attached a VSM then we could make it work like this. I think we did something like that for button in XF. Not to say we should do that with this PR but I don't think this PR is correct given the current design of the system. The original bug might be an issue with the VSM. The default styles in our template should cause the color to change when the checkbox state changes
> 
> image

Mnn, should we continue with the changes detecting if use VS, or not?. At least, we must leave the changes in src/Core/src/Platform/Android/ColorStateListExtensions.cs to get that extensions working as expected.

**Comment by jsuarezruiz** [comment]
I have removed the association with issue #6727  and updated the title. This PR still have sense to fix issues in the extension methods used to create ColorStateLists.

@PureWeen Could you review it again?. Thanks.

**Comment by mattleibow** [comment]
> Mnn, should we continue with the changes detecting if use VS, or not?. At least, we must leave the changes in src/Core/src/Platform/Android/ColorStateListExtensions.cs to get that extensions working as expected.

I see what you mean. If the user adds a checkbox and does nothing else, the color should be platform defaults. Then setting a background color would tell me to only set the enabled state as I would expect the OS to gray out the control by default when disabled.

Now if there is a VSM set, then I would expect that to take precedence.

This is the same issue for all controls as I think they all go gray.

**Comment by jsuarezruiz** [comment]
Applied some changes to fix https://github.com/dotnet/maui/issues/6727
Currently, we use the Color property value in the normal and disabled states. So, no visual differences enabling or disabling the CheckBox. I include some changes to use the Color property when disabling the control but applying a small change in the opacity of the color. Have sense?

fix-6727-droid

**Comment by Symbai** [comment]
> but applying a small change in the opacity of the color

That's a very common solution on WPF, much better than before although personally I would reduce the opacity even further from 0.75 to 0.6 or 0.5. For end user it should be very noticeably if a control is disabled or not and I got better experience with lower opacity values. Especially if you got several of these controls in a list and not just two on a blank page like in your GIF.

**Review by rmarinho — CHANGES_REQUESTED** [review]
The problem is if on Disable state i pass a color you are always changing it to 0.75 opacity. So we are preventing the user to set correct color.
I think we can do it if no color is set (we are using the default color) , otherwise the disableColor =  color set by the user

**Review by rmarinho — APPROVED** [review]

**Comment by PureWeen** [comment]
> > Mnn, should we continue with the changes detecting if use VS, or not?. At least, we must leave the changes in src/Core/src/Platform/Android/ColorStateListExtensions.cs to get that extensions working as expected.
> 
> I see what you mean. If the user adds a checkbox and does nothing else, the color should be platform defaults. Then setting a background color would tell me to only set the enabled state as I would expect the OS to gray out the control by default when disabled.
> 
> Now if there is a VSM set, then I would expect that to take precedence.
> 
> This is the same issue for all controls as I think they all go gray.

I don't think this is the same for all controls. For example on iOS and WinUI we overwrite every single state when you set a color

image

image

This is where it'd be nice to have some sort of state based understanding in the interface layer. Without that, inside core we just have to blow away the color for all states because we have no context that the user wants a color set. 

If we want to go the WPF/WinUI route that's going to be a bigger change at the controls layer where we force users to use the VSM in order to set colors in all states except Normal. Which I think is how WinUI and those work.

File: src/Core/src/Platform/Android/CheckBoxExtensions.cs [hunk 1]
```diff
@@ -23,28 +23,30 @@ public static void UpdateIsChecked(this AppCompatCheckBox platformCheckBox, IChe
...
 
-			var tintList = ColorStateListExtensions.CreateCheckBox(tintColor);
-
-			var tintMode = PorterDuff.Mode.SrcIn;
+				tintColor = color.ToPlatform();
+			}
 
-			CompoundButtonCompat.SetButtonTintList(platformCheckBox, tintList);
-			CompoundButtonCompat.SetButtonTintMode(platformCheckBox, tintMode);
+			return ColorStateListExtensions.CreateSwitch(tintColor, tintColor, tintColor);
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/CheckBoxExtensions.cs:49]: Should this be CreateCheckbox?

**Review by PureWeen — CHANGES_REQUESTED** [review]

**Review by PureWeen — APPROVED** [review]
