### PR TITLE
Still measure children if size is known on CV

### LINKED ISSUE #7562: MeasureFirstItem makes items disappear on Android
### Description

I have a `CollectionView` where `ItemSizingStrategy` is set to `MeasureFirstItem`. The properties of the times are changed some time of the `CollectionView` is loaded. Somehow, this makes some items become invisible on Android. It works fine on Windows.

Originally, my list looks like this:

image

Then, the two first items should be changed to green. But the second one just disappears:

image

In Windows it's works fine:

image

It's very strange :-)

### Steps to Reproduce

1. Create a new Maui app.
2. Change `MainPage.xaml` to:

``` XAML
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:v="clr-namespace:MauiIssues"
             x:Class="MauiIssues.MainPage"
             >
    <Grid>
        <CollectionView ItemsSource="{Binding Issues}" ItemSizingStrategy="MeasureFirstItem">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Grid>
                        <Label Text="{Binding Title, Mode=OneWay}"
                            TextColor="Red"
                            IsVisible="{Binding IsRed}"
                                />

                        <Label Text="{Binding Title, Mode=OneWay}"
                            TextColor="Green"
                            IsVisible="{Binding IsGreen}}"
                                />
                    </Grid>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </Grid>
</ContentPage>
```

3. Change `MainPage.cs` to:

``` C#
using System.Collections.ObjectModel;

namespace MauiIssues;

public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();

        BindingContext = this;
    }

    public class Issue : BindableObject
    {
        public string Title { get; set; }
        public bool IsRed { get; set; } = true;
        public bool IsGreen => !IsRed;

        public void MakeGreen()
        {
            IsRed = false;
            OnPropertyChanged(nameof(IsGreen));
            OnPropertyChanged(nameof(IsRed));
        }
    }

    public ObservableCollection<Issue> Issues { get; } = new ObservableCollection<Issue>();

    protected async override void OnAppearing()
    {
        base.OnAppearing();

        Issues.Add(new Issue { Title = "Issue 1" });
        Issues.Add(new Issue { Title = "Issue 2" });
        Issues.Add(new Issue { Title = "Issue 3" });

        await Task.Delay(4000);

        Issues[0].MakeGreen();
        Issues[1].MakeGreen();
    }
}
```
Run the project in Android.

Full sample code: https://github.com/pekspro/MauiIssues/tree/7562_MeasureFirstItem_makes_items_disappear

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Windows 10.0.17763.0, Android 11

### Did you find any workaround?

Removing `ItemSizingStrategy="MeasureFirstItem"` solves the problem.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

On Android, even you if you already know the size your children, you still need to call "measure" so it can update its internal bookkeeping. If the layout cycle was caused by the measure on the child being invalidated, then it's going to expect its `OnMeasure` call to happen. This is also important if for some reason the "Firstitem" size gets updated and reused cells need to be remeasured. Android requires you to call "measure" so it can update its MeasuredWidth and MeasuredHeight values to use during arrange. 

### Issues Fixed

Fixes #7562

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/Android/ItemContentView.cs [hunk 1]
```diff
@@ -83,26 +83,39 @@ protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
...
+
+				SetMeasuredDimension(w, h);
 				return;
 			}
 
 			int pixelWidth = MeasureSpec.GetSize(widthMeasureSpec);
 			int pixelHeight = MeasureSpec.GetSize(heightMeasureSpec);
 
-			var width = MeasureSpec.GetMode(widthMeasureSpec) == MeasureSpecMode.Unspecified
+			var widthSpec = MeasureSpec.GetMode(widthMeasureSpec) == MeasureSpecMode.Unspecified
```
Comment (mattleibow) [inline src/Controls/src/Core/Handlers/Items/Android/ItemContentView.cs:109]: I think this was correct before. This code is using the measure spec to get the pixel width and then convert to independent width. The spec was the source value, this is now just the width in dip.

**Review by mattleibow — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]

File: src/Controls/src/Core/Handlers/Items/Android/ItemContentView.cs (hunk 1 above)
Comment (PureWeen) [reply src/Controls/src/Core/Handlers/Items/Android/ItemContentView.cs:109]: I don't think there's a behavior change here
I was just renaming things
