### PR TITLE
Fix Flyout memory leak

### LINKED ISSUE #33355: Android: Memoryleaks when using FlyoutPage with NavigationPages
### Description

In Android (didn't test on Windows/IOS/MAC) my app is crashing cause of memory leaks in Maui when using a FlyoutPage with NavigationPages.
Navigating to different pages like this, causes memory increase and eventually the app becomes slow and unusable.

Weird thing is:
When I change `masterPage.Detail = new NavigationPage(page);` in `NavigationService.cs` to `masterPage.Detail = page;` no memory leaks seem to happen. But then the "hamburger menu" is missing in the FlyoutPage which is needed in my app.

### Steps to Reproduce

1. Run the App on an android device
2. Click the button to navigate to DetailPage1
3. In DetailPage1 click the button to navigate to DetailPage2
4. Wait a few seconds and the nuget package from https://github.com/AdamEssenmacher/MemoryToolkit.Maui "displays" all the leaks from DetailPage1 in an Alert popup
5. In DetailPage2 click the button to navigate to DetailPage1
6. Wait a few seconds and the nuget package from https://github.com/AdamEssenmacher/MemoryToolkit.Maui "displays" all the leaks from DetailPage1 in an Alert popup

Image

### Link to public reproduction project repository

https://github.com/3sRykaert/MauiMemoryleak

### Version with bug

10.0.20

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up (didn't test on other platforms)

### Did you find any workaround?

No

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by pictos**
### Issues Fixed

Fixes #33355

### Description of Change

This report has the goal to provide a detailed progress on the solution of the memory-leak

The test consists doing 100 navigations between 2 pages, as the image below suggest

image

Running the gc-dump on the desired objects this is what I found.

> BaseLine is the dump when the app starts.

|                                      |         |              |                |                          |
| ------------------------------------ | ------- | ------------ | -------------- | ------------------------ |
| Object Type                          | Count   | Size (Bytes) | Expected Count | Status                   |
| **Page2**                            | **100** | 84,000       | 1              | ❌ **LEAKED** (99 extra)  |
| **PageHandler**                      | **103** | 9,888        | 4              | ❌ **LEAKED** (99 extra)  |
| **StackNavigationManager**           | **102** | 16,320       | 1              | ❌ **LEAKED** (101 extra) |
| **StackNavigationManager.Callbacks** | **102** | 5,712        | 1              | ❌ **LEAKED** (101 extra) |
| **NavigationViewFragment**           | **102** | 5,712        | ~2             | ❌ **LEAKED** (100 extra) |

So the first fix was to call `Disconnect` handler, on the `previousDetail` during the `FlyoutPage.Detail_set`. The PageChanges and Navigated events will not see this, since this `set` is not considered a navigation in .Net Maui.

After that we see the following data

|                                      |         |              |                        |              |
| ------------------------------------ | ------- | ------------ | ---------------------- | ------------ |
| Object Type                          | Count   | Size (Bytes) | vs Baseline            | Status       |
| **Page2**                            | **100** | 84,000       | Same                   | ❌ **LEAKED** |
| **PageHandler**                      | **103** | 9,888        | Same                   | ❌ **LEAKED** |
| **StackNavigationManager**           | **102** | 16,320       | Same                   | ❌ **LEAKED** |
| **StackNavigationManager.Callbacks** | **1**   | 56           | ✅ **FIXED!** (was 102) | ✅ **Good!**  |
| **NavigationViewFragment**           | **102** | 5,712        | Same                   | ❌ **LEAKED** |

So, calling the Disconnect handler will fix the leak at `StackNavigationManager.Callbacks`. Next step was to investigate the `StackNavigationManager` and see what's holding it.

On `StackNavigationManager` I see lot of object that should be cleaned up in order to release other references from it. After cleaning it up the result is

|   |   |   |   |   |
|---|---|---|---|---|
|Object Type|Count|Size (Bytes)|vs Baseline|Status|
|**Page2**|**1**|840|✅ **FIXED!** (was 100)|✅ **Perfect!**|
|**PageHandler**|**4**|384|✅ **FIXED!** (was 103)|✅ **Perfect!**|
|**StackNavigationManager**|**102**|16,320|❌ Still leaking (was 102)|❌ **Unchanged**|
|**StackNavigationManager.Callbacks**|**1**|56|✅ Fixed (was 102)|✅ **Good!**|
|**NavigationViewFragment**|**102**|5,712|❌ Still leaking (was 102)|❌ **Unchanged**|

So something is still holding the `StackNavigationManager` and `NavigationViewFragment` so I changed the approach and found that `NavigationViewFragment` is holding everything and after fixing that, cleaning it up on `Destroy` method. here's the result

|   |   |   |   |   |
|---|---|---|---|---|
|Object Type|Count|Size (Bytes)|vs Previous|Status|
|**Page2**|**1**|840|✅ Same|✅ **Perfect!**|
|**PageHandler**|**4**|384|✅ Same|✅ **Perfect!**|
|**StackNavigationManager**|**1**|160|🎉 **FIXED!** (was 102)|🎉 **FIXED!**|
|**StackNavigationManager.Callbacks**|**1**|56|✅ Same|✅ **Perfect!**|
|**NavigationViewFragment**|**102**|5,712|⚠️ Still present|⚠️ **Remaining**|

With that there's still the leak of `NavigationViewFragment`, looking at the graph the something on Android side is holding it, there's no root into managed objects, as far the gcdump can tell. I tried to cleanup the `FragmentManager`, `NavController` and so on but without success (maybe I did it wrong). 

There's still one instance of page 2, somehow it lives longer, I don't think it's a leak object because since its value is 1. For reference the Page2 graph is
```
Page2 (1 instance)
 └── PageHandler
     └── EventHandler<FocusChangeEventArgs>
         └── IOnFocusChangeListenerImplementor (Native Android)
             └── UNDEFINED

```

Looking into www I found that android caches those Fragments, sadly in our case we don't reuse them. The good part is each object has only 56 bytes, so it shouldn't be a big deal, I believe we can take the improvements made by this PR and keep an eye on that, maybe that's fixed when moved to Navigation3 implementation.

### CODE REVIEW

File: src/Controls/src/Core/FlyoutPage/FlyoutPage.cs [hunk 1]
```diff
@@ -76,6 +76,7 @@ public Page Detail
 				{
 					previousDetail.SendNavigatedFrom(
 						new NavigatedFromEventArgs(destinationPage: value, NavigationType.Replace));
+					previousDetail.Handler?.DisconnectHandler();
```
Comment (PureWeen) [inline src/Controls/src/Core/FlyoutPage/FlyoutPage.cs]: can we somehow call this from the flyoutviewhandler?

File: src/Core/src/Platform/Android/Navigation/StackNavigationManager.cs [hunk 2]
```diff
@@ -496,7 +496,10 @@ void SetNavHost(NavHostFragment? navHost)
 				return;
 
 			if (_navHost is MauiNavHostFragment oldHost)
+			{
 				oldHost.StackNavigationManager = null;
+				oldHost.Dispose();
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/Navigation/StackNavigationManager.cs]: Ideally we aren't calling disposed on managed instances, this usually just disconnects managed from unmanaged and can hide unmanaged leaks

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/FlyoutPage/FlyoutPage.cs (hunk 1 above)
Comment (pictos) [reply src/Controls/src/Core/FlyoutPage/FlyoutPage.cs]: Inside the `Flyout.Handler.DisconnectHandler`?

Comment (pictos) [reply src/Controls/src/Core/FlyoutPage/FlyoutPage.cs]: I tried here, but I couldn't make it work. For some reason the `VirtualView.Detail.Handler` is null there, so it's too late. Do you mind to keep it as it's right now?

For .NET 11 there's a plan to migrate to Navigation3, this can be addressed there, right?

File: src/Core/src/Platform/Android/Navigation/NavigationViewFragment.cs [hunk 3]
```diff
@@ -87,8 +87,14 @@ public override void OnResume()
 
 		public override void OnDestroy()
 		{
+			if (_currentView is not null)
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/Navigation/NavigationViewFragment.cs]: I think we can get rid of this block and only need the code that sets the nav manager to null

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Android/Navigation/NavigationViewFragment.cs (hunk 3 above)
Comment (pictos) [reply src/Core/src/Platform/Android/Navigation/NavigationViewFragment.cs]: After removing this block, the leak gets worse. You can see the stats in the table 

| Object Type | Before | Current | Change | Status |
|-------------|--------|---------|--------|--------|
| **Page2** | 1 | **21** | +2000% | 🚨 **MAJOR REGRESSION** |
| **PageHandler** | 4 | **24** | +500% | 🚨 **MAJOR REGRESSION** |
| **StackNavigationManager** | 1 | **1** | No change | ✅ **Still good** |
| **Callbacks** | 1 | **1** | No change | ✅ **Still good** |
| **NavigationViewFragment** | 102 | **102** | No change | ⚠️ **Still present** |

**Review by PureWeen — APPROVED** [review]
