### PR TITLE
[C] remove listener on changing MainPage

### LINKED ISSUE #21495: Bugzilla44166 now failing after ThemeResourcesChange fix
### Description

- open Microsoft.Maui.LegacyControlGallery.slnf
- run android gallery
- navigate to 44166
- click go
- click previous
- click GC

"Success" never shows up

rollback this PR
https://github.com/dotnet/maui/pull/21229

repeat steps
Success shows up

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change

[C] remove listener on changing MainPage
avoid leaking

### Issues Fixed

- fixes #21495

### CODE REVIEW

File: src/Controls/src/Core/Application/Application.cs [hunk 1]
```diff
@@ -99,17 +99,20 @@ public IAppLinks AppLinks
 
 				OnPropertyChanging();
 
+				if (MainPage is not null)
+				{
+					((IElementDefinition)this).RemoveResourcesChangedListener(MainPage.OnParentResourcesChanged);
+				}
+
 				_singleWindowMainPage = value;
```
Comment (StephaneDelcroix) [inline src/Controls/src/Core/Application/Application.cs:107]: this is actually setting MainPage, so listener was never removed on the previous MainPage

**Comment by PureWeen** [comment]
https://dev.azure.com/xamarin/public/_build/results?buildId=112415&view=results

**Review by jsuarezruiz — APPROVED** [review]

**Review by Redth — APPROVED** [review]

**Comment by PureWeen** [comment]
Failing tests unrelated
https://dev.azure.com/xamarin/public/_build/results?buildId=112415&view=results

The main test this is targeting has been fixed.
