### PR TITLE
Fix CollectionView not displaying header or footers

### LINKED ISSUE #14557: CollectionView Header & Footer not showing
### Description

When trying to add any content inside a Header/Footer to a CollectionView, it is not being displayed. Only happens in Windows. Works well for Android and iOS.

### Steps to Reproduce

Create new project
Add CollectionView with a ItemsSource
Add a Header/Footer to the CollectionView

        <CollectionView x:Name="collectionview"
                        ItemsSource="{Binding Monkeys}">            
            <CollectionView.Header>
            <VerticalStackLayout BackgroundColor="LightGray">
                    <Label Margin="10,0,0,0"
                           Text="Monkeys"
                           FontSize="12"
                           FontAttributes="Bold" />
                </VerticalStackLayout>
            </CollectionView.Header>
            <CollectionView.Footer>
                <VerticalStackLayout BackgroundColor="LightGray">
                    <Label Margin="10,0,0,0"
                           Text="Friends of Xamarin Monkey"
                           FontSize="12"
                           FontAttributes="Bold" />
                </VerticalStackLayout>
            </CollectionView.Footer>
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    ...
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>

image

### Link to public reproduction project repository

https://github.com/sesitosvdx/CollectionViewHeaderFooterWindowsBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows10.0.19041.0

### Did you find any workaround?

https://github.com/dotnet/maui/issues/14557#issuecomment-1650647976

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jknaudt21**
### Problem

The footer and header's of a CollectionView would not display on Windows. 

This was happening because they were created as `WrapperControl` in ViewToHandlerConverter.cs , and when being initialized they didn't have parents (although they should!). This, in turn, prevents them from getting the appropriate MauiContext when calling `view.FindMauiContext()`. Without the context, they can't render.

The reason _why_ they ended up having no parents was because we make a call to `ClearLogicalChildren` when updating an ItemsSource. This was made to prevent memory leaks but had the unintended side effect of not rendering the headers and footers. https://github.com/dotnet/maui/pull/13530
 
### Solution
We ensure to only clear up the items in the ItemSource of the CollectionView. That way any logical child that should persist is not wiped, and can thereby render correctly.

#### Before & After
I'm using an empty collection view with a footer and header
<details> <summary> Sample code </summary> 

```xaml
    <VerticalStackLayout>
        <CollectionView MaximumWidthRequest="300">
            <CollectionView.Header>
                <Button BackgroundColor="AliceBlue" Text="Foo"/>
            </CollectionView.Header>
            <CollectionView.Footer>
                <Button Text="Bar" TextColor="Red" />
            </CollectionView.Footer>
        </CollectionView>
    </VerticalStackLayout>
```  
</details>

| Before | After |
| -- | -- |
| (Nothing rendered)  |  image | 
### Issues Fixed

Fixes #14557

### Remaining work

- [x] Write a test

### CODE REVIEW

**Comment by samhouts** [comment]
Paging @jonathanpeppers for memory leaks implications

File: src/Controls/src/Core/Handlers/Shell/Windows/ViewToHandlerConverter.cs [hunk 1]
```diff
@@ -53,7 +53,9 @@ public WrapperControl(View view)
 				_view = view;
 				_view.MeasureInvalidated += OnMeasureInvalidated;
 
-				FrameworkElement = view.ToPlatform(view.FindMauiContext()!);
+				// If we don't find the MauiContext and instead return the default, the view won't display
+				// Header and footers of a CollectionView don't have a parent when they're created (which is used to get the context), yet they still need to be displayed
+				FrameworkElement = view.ToPlatform(view.FindMauiContext(true)!);
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Shell/Windows/ViewToHandlerConverter.cs:58]: I feel like they should have a parent. Do they eventually have a parent? I think `CV.AddLogicalChild(Header)` should probably get called before we reach this point in the code, so I wonder if the header/footer aren't getting added as LC of the CV.

If this is a timing issue then we could put this code [here](https://github.com/dotnet/maui/pull/16870/files#diff-183f2ec157ab30b0ca65ae80a72e2910eeda7ce07cc3a7c5c3a5fdadd85bf1dfR63-R69)

Or possibly listen to "view.ParentSet" and once that Parent is set then set the FE

**Review by PureWeen — DISMISSED** [review]

**Review by hartez — DISMISSED** [review]

**Comment by jknaudt21** [comment]
Got spooked on memory leaks so I bolstered the current memory leak test.
image

**Review by hartez — DISMISSED** [review]

File: src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs [hunk 2]
```diff
@@ -174,14 +174,13 @@ protected virtual void CleanUpCollectionViewSource()
...
-			if (ListViewBase?.Header is View header)
-				VirtualView?.AddLogicalChild(header);
-
-			if (ListViewBase?.Footer is View footer)
-				VirtualView?.AddLogicalChild(footer);
+			// Remove all children inside the ItemsSource
+			foreach (var item in ListViewBase.GetChildren<ItemContentControl>())
+			{
+				var element = item.GetVisualElement();
+				VirtualView?.RemoveLogicalChild(element);
```
Comment (hartez) [inline src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs:182]: If `VirtualView` is `null`, there's no reason to iterate over all the children. Can you check it once before iterating?

**Review by hartez — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs (hunk 2 above)
Comment (jknaudt21) [reply src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs]: Done

**Review by hartez — DISMISSED** [review]

**Comment by rmarinho** [comment]
image

Failing tests on android

**Comment by jknaudt21** [comment]
> Failing tests on android

So this seems to be a new bug. The Android collection view leaks if it has a header or footer :(

File: src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs [hunk 3]
```diff
@@ -47,6 +47,8 @@ public async Task ItemsSourceDoesNotLeak()
 			WeakReference weakReference = null;
 			var collectionView = new CollectionView
 			{
+				Header = new Label { Text = "Header" },
+				Footer = new Label { Text = "Footer" },
```
Comment (jonathanpeppers) [inline src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:51]: Can you put `#if !ANDROID` around these two lines with a comment what's going on for now?

Comment (jknaudt21) [reply src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:51]: The test passes

File: src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs [hunk 4]
```diff
@@ -75,7 +77,7 @@ public async Task ItemsSourceDoesNotLeak()
 			await AssertionExtensions.WaitForGC(weakReference);
 			Assert.False(weakReference.IsAlive, "ObservableCollection should not be alive!");
 			Assert.NotNull(logicalChildren);
-			Assert.True(logicalChildren.Count <= 3, "_logicalChildren should not grow in size!");
+			Assert.True(logicalChildren.Count <= 5, "_logicalChildren should not grow in size!");
```
Comment (jonathanpeppers) [inline src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:80]: Then you'd need `3` for `ANDROID` and `5` for the other platforms, too.

File: src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs (hunk 3 above)
Comment (jonathanpeppers) [reply src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:51]: Oh it's a random other test, I would ignore it here, then.

Comment (jonathanpeppers) [reply src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:51]: I don't see how changing Windows-only code would break Android tests?

Comment (jknaudt21) [reply src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:55]: I made the test more robust in by adding the header and footer. In doing so it turns out that Android is leaking

Comment (jknaudt21) [reply src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:55]: Created this issue to follow up on Android: https://github.com/dotnet/maui/issues/16961

File: src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs [hunk 5]
```diff
@@ -45,8 +45,15 @@ public async Task ItemsSourceDoesNotLeak()
 
 			IList logicalChildren = null;
 			WeakReference weakReference = null;
+
+			// Recently discovered that Android CollectionView is leaking when given a header or footer
+			// See:
```
Comment (jonathanpeppers) [inline src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:50]: Maybe forgot link? Otherwise, looks good for now. 👍

Comment (jknaudt21) [reply src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs]: Whoops :P

File: src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs [hunk 6]
```diff
@@ -325,5 +325,7 @@ bool CanMeasureContent(FrameworkElement frameworkElement)
 
 			return true;
 		}
+
+		internal VisualElement GetVisualElement() => _renderer?.VirtualView as VisualElement;
```
Comment (mattleibow) [inline src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs:329]: Is this not `_visualElement`? I see it is set to that in `void Realize()`.

Comment (jknaudt21) [reply src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs]: Oh would you look at that. You're right! I was looking higher up in `UpdateIsSelected()` and there `renderer?.VirtualView` was used. I made the fix and this PR still works 👍

**Review by hartez — APPROVED** [review]
