### PR TITLE
Fix WebView2 Runtime download link for Blazor MAUI

### LINKED ISSUE #6421: MAUI Blazor template (WinUI 3) does not display WebView2 Runtime download link
### Description

The WinUI 3 WebView2 element displays a download link for the WebView2 Runtime when it is not installed. However, the MAUI Blazor template displays a blank purple screen under the same conditions.

**WinUI 3 WebView2 element**:
WinUI WebView2 screenshot

**Blazor MAUI template**:
MAUI Blazor screenshot

### Steps to Reproduce

1. Create a new project from the ".NET MAUI Blazor App" template (`maui-blazor`)
2. Follow [these steps](https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview) to publish the app
3. Install the app on a machine without the WebView2 Runtime installed.
4. Launch the app

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Tested on Windows 10, version 1809 (without WebView2 runtime installed)

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by MackinnonBuck**
### Description of Change

The WinUI 3 `WebView2` control displays a download link for the WebView2 Runtime when it is not installed on the host machine. However, the `BlazorWebView` control (which wraps the WinUI 3 `WebView2` control on Blazor MAUI Windows) did not display the link under the same conditions. This PR fixes the bug that prevented the link from displaying.

Before:
before

After:
after

### Issues Fixed

Fixes #6421

### CODE REVIEW

File: src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs [hunk 1]
```diff
@@ -177,27 +177,46 @@ protected override void NavigateCore(Uri absoluteUri)
...
-			await _webview.EnsureCoreWebView2Async();
+
+			try
+			{
+				_coreWebView2Environment = await CoreWebView2Environment.CreateWithOptionsAsync(
+					browserExecutableFolder: args.BrowserExecutableFolder,
+					userDataFolder: args.UserDataFolder,
+					options: args.EnvironmentOptions)
+					.AsTask()
+					.ConfigureAwait(true);
```
Comment (TanayParikh) [inline src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs:206]: nit;

```suggestion
					options: args.EnvironmentOptions)
						.AsTask()
						.ConfigureAwait(true);
```
```suggestion
					options: args.EnvironmentOptions)
					.AsTask()
					.ConfigureAwait(true);
```

**Review by TanayParikh — APPROVED** [review]
:shipit:

**Review by mattleibow — APPROVED** [review]

File: src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs [hunk 2]
```diff
@@ -177,27 +177,46 @@ protected override void NavigateCore(Uri absoluteUri)
...
+				// This type of exception is thrown when the WebView2 Runtime is not installed.
+				return false;
+			}
+			finally
+			{
+				// This method needs to be invoked even if the WebView2 Runtime is not installed,
+				// since it is reponsible for creating the warning label and WebView2 Runtime
+				// download link.
+				await _webview.EnsureCoreWebView2Async();
+			}
```
Comment (SteveSandersonMS) [inline src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs:219]: I expect this pattern is fine, but it does mean now that if `CreateWithOptionsAsync` throws something other than a `FileNotFoundException`, we'll now still call `EnsureCoreWebView2Async` whereas previously we wouldn't have done.

No idea if that could confuse matters (e.g., by surfacing a different and less obvious exception).

One option would be to eliminate the `finally` block and have two calls to `EnsureCoreWebView2Async` - one inside the `catch`, and the other after the `try`/`catch` entirely.

**Review by SteveSandersonMS — APPROVED** [review]

File: src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs (hunk 1 above)
Comment (MackinnonBuck) [reply src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs:206]: These lines are already indented one extra level - does this suggestion follow our decided conventions? I'm not implying it doesn't, but this would be different than how the formatting was before the change (and how the formatting is in a syntactically similar location later in the method).
