### PR TITLE
[iOS] Fixed Collection View header and footer update

### LINKED ISSUE #19379: Not able to update CollectionView header
### Description

I want to update the CollectionView header using a button, it works as expected on NET Maui Android but not on iOS.

This is the app working as expected on Android:

| Android |
| ------------- |
| <video src="https://github.com/dotnet/maui/assets/43689290/75e5b6e9-aa82-4d1f-9ed9-b21127e3fa34" width=180 height=392> |

but it doesn't change on iOS:

| iOS |
| ------------- |
| <video src="https://github.com/juniorsaraviao/MauiSample8/assets/43689290/41e2ae8b-92c6-47b4-8e39-0b5e030ba8ec" width=180 height=392> |

### Steps to Reproduce

1. Clone the project [link](https://github.com/juniorsaraviao/MauiSample8/tree/master).
2. Execute it on iOS Simulators or iPhones.
3. Tap the button Update the CollectionView header.

### Link to public reproduction project repository

https://github.com/juniorsaraviao/MauiSample8/tree/master

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.2 and above

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

Fixed Collection View header and footer update

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/19379

https://github.com/dotnet/maui/assets/42434498/6b2432d1-6b75-413e-8134-ccc2392dd001

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Added UITest.

File: src/Controls/src/Core/Handlers/Items/CollectionViewHandler.cs [hunk 1]
```diff
@@ -29,6 +29,8 @@ public CollectionViewHandler(PropertyMapper mapper = null) : base(mapper ?? Mapp
 			[Controls.ItemsView.IsVisibleProperty.PropertyName] = MapIsVisible,
 			[Controls.ItemsView.ItemsUpdatingScrollModeProperty.PropertyName] = MapItemsUpdatingScrollMode,
 			[StructuredItemsView.HeaderTemplateProperty.PropertyName] = MapHeaderTemplate,
+			[StructuredItemsView.HeaderProperty.PropertyName] = MapHeaderTemplate,
+			[StructuredItemsView.FooterProperty.PropertyName] = MapFooterTemplate,
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items/CollectionViewHandler.cs:33]: Shouldn't this be added to StructuredItemsViewHandler also? 
Or in theory it should be added there and can be removed here.

**Review by rmarinho — APPROVED** [review]
