### PR TITLE
Fix iOS Page Background issue

### LINKED ISSUE #1255: [Bug] Background is wrong color
### Description

Page background should be purple.

```xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MyFive.MainPage"
             BackgroundColor="{DynamicResource PageBackgroundColor}">

    <VerticalStackLayout Spacing="10">
        <BoxView WidthRequest="40" HeightRequest="40" Color="Black"/>
        <BoxView WidthRequest="40" HeightRequest="40" Color="Black"/>
        <BoxView WidthRequest="40" HeightRequest="40" Color="Black"/>
        <BoxView WidthRequest="40" HeightRequest="40" Color="Black"/>
        <BoxView WidthRequest="40" HeightRequest="40" Color="Black"/>
        <BoxView WidthRequest="40" HeightRequest="40" Color="Black"/>
    </VerticalStackLayout>
</ContentPage>

```

```xaml
<Application xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
			 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			 xmlns:local="clr-namespace:MyFive"
			 x:Class="MyFive.App">
    <Application.Resources>
        <ResourceDictionary>
            <Color x:Key="PageBackgroundColor">#512bdf</Color>
            <Color x:Key="PrimaryTextColor">White</Color>

            <Style TargetType="Label">
                <Setter Property="TextColor" Value="{DynamicResource PrimaryTextColor}" />
                <Setter Property="FontFamily" Value="OpenSansRegular" />
            </Style>

            <Style TargetType="Button">
                <Setter Property="TextColor" Value="{DynamicResource PrimaryTextColor}" />
                <Setter Property="FontFamily" Value="OpenSansRegular" />
                <Setter Property="BackgroundColor" Value="#2b0b98" />
            </Style>

        </ResourceDictionary>
    </Application.Resources>
</Application>
```

[Archive.zip](https://github.com/dotnet/maui/files/6635136/Archive.zip)

From https://github.com/dotnet/maui/pull/1253

Screen Shot 2021-06-10 at 8 11 25 PM

### Basic Information

- Version with issue: ci-main.4144

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

If a solid color is used, instead of creating a CALayer to apply the color, the `BackgroundColor` property of UIView is used directly.

- fix #1255 

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)

#### Does this PR touch anything that might affect accessibility?
- No

### CODE REVIEW

**Review by hartez — APPROVED** [review]

File: src/Core/src/Platform/iOS/ViewExtensions.cs [hunk 1]
```diff
@@ -63,13 +62,28 @@ public static void UpdateBackground(this UIView nativeView, IView view)
...
-			if (backgroundLayer != null)
+				if (backgroundColor == null)
+					nativeView.BackgroundColor = ColorExtensions.BackgroundColor;
+				else
+					nativeView.BackgroundColor = backgroundColor.ToNative();
+
+				return;
+			}
+
+			if (paint is GradientPaint gradientPaint)
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/ViewExtensions.cs:77]: Maybe this should be an else type thing instead just in case we add new types. I am dreaming of that image brush world.

**Review by mattleibow — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/iOS/ViewExtensions.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/iOS/ViewExtensions.cs]: Yes, I also want that ImageBrush!. Apply the changes.
