### PR TITLE
[Android] Fixed NullReferenceException in app with TabBar after returning from minimized state

### LINKED ISSUE #34720: NullReferenceException in app with TabBar after returning from minimized state
### Description

Reproduced on Android 9 with MAUI10 sample demo with sample data.

### Steps to Reproduce

See video.

Steps:
1) open demo, click "Projects" (i.e. open Project Detail page),
2) click "Manage Meta" on TabBar,
3) click Android Back on bottom,
4) app is minimized,
5) click app icon - open app from minimized state.

Result:
InnerException	{"Object reference not set to an instance of an object."}	System.Exception {System.NullReferenceException}

Expected:
Opened  "Manage Meta" page or first "Dashboard" page.

===
Note:
In my app I use Navigation.PushAsync() to open "detail" page, so the other exception is raised:
InnerException	{"Page must not already have a parent."}	System.Exception {System.InvalidOperationException}

https://github.com/user-attachments/assets/7f797d4c-a3fb-4f52-8943-0b61da0cb318

### Link to public reproduction project repository

_No response_

### Version with bug

10.0.50

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by NirmalKumarYuvaraj**
### Root cause
When the app resumes from a minimized state, the `CollectionView` on MainPage re-evaluates its bindings. The `SelectionChangedCommand` fires with a `null` `SelectedProject`, calling NavigateToProject(null), which returns `null`. The `AsyncRelayCommand` generated by RelayCommand tries to await/check this null Task internally in `AwaitAndThrowIfFailed`, causing the `NullReferenceException`.

### Description of Change

This pull request makes a minor improvement to the `NavigateToProject` command in the `MainPageModel` to ensure it always returns a `Task`, even when the input is null. This helps maintain consistency and prevents potential issues with null returns.

### Issues Fixed

Fixes #34720

### CODE REVIEW

File: src/Templates/src/templates/maui-mobile/PageModels/MainPageModel.cs [hunk 1]
```diff
@@ -156,7 +156,7 @@ private Task AddTask()
 
 	[RelayCommand]
 	private Task? NavigateToProject(Project project)
```
Comment (dartasen) [inline src/Templates/src/templates/maui-mobile/PageModels/MainPageModel.cs:158]:
```suggestion
	private Task NavigateToProject(Project project)
```

**Review by kubaflo — APPROVED** [review]
