### PR TITLE
[iOS] SwipeView Closes when Content Changes - right and bottom - fix

### LINKED ISSUE #32033: SwipeView Closes when Content Changes even with SwipeBehaviorOnInvoked="RemainOpen" (iOS only)
### Description

This is a reopen of https://github.com/dotnet/maui/issues/29086

If you use SwipeView in a collection view item template, and its command results in changing the content of the view, the swipeview collapses! even when the SwipeBehaviorOnInvoked="RemainOpen".
This happens only on right and bottom items:

https://github.com/user-attachments/assets/eb17fe1b-446d-4637-ab00-ed1456e2f219

The issue was fixed by @kubaflo  in 9.0.100-ci.main.25403.2, https://github.com/dotnet/maui/pull/30182 but it was not merged. 
Sample: https://github.com/darrabam/SwipeViewBugMAUI

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.111 SR11.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

_No response_

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Description of Change

A correction to this pr https://github.com/dotnet/maui/pull/29088 that fixes this comment https://github.com/dotnet/maui/pull/29088#issuecomment-2996822522

### Issues Fixed

Fixes https://github.com/dotnet/maui/pull/29088#issuecomment-2996822522
Fixes https://github.com/dotnet/maui/issues/32033

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/d28d31b7-241a-43fd-832f-d8ac8abdf202" width="300px"/>|<video src="https://github.com/user-attachments/assets/c788d2d1-5227-48b3-a2ad-ae1093823057" width="300px"/>|

### CODE REVIEW

File: src/Core/src/Platform/iOS/MauiSwipeView.cs [hunk 1]
```diff
@@ -807,20 +807,19 @@ void SwipeToThreshold(bool animated = true)
 				Animate(completeAnimationDuration, 0.0, UIViewAnimationOptions.CurveEaseIn,
 					() =>
 					{
-						_swipeOffset = GetSwipeThreshold();
-						double swipeThreshold = _swipeOffset;
+						_swipeOffset = Math.Abs(GetSwipeThreshold());
+						if(_swipeDirection == SwipeDirection.Left || _swipeDirection == SwipeDirection.Up)
+							_swipeOffset = -_swipeOffset;
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/MauiSwipeView.cs:808]: Could you include a comment here? Something like "If the user swiped left or up, we need a negative offset to move content in the correct direction on the screen."

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Could include a test?

**Comment by jsuarezruiz** [comment]
@kubaflo, I think a rebase might have gone wrong here, mind taking a quick look?

**Comment by darrabam** [comment]
@kubaflo The fix didn't make it to 9.0.90.

**Comment by darrabam** [comment]
@kubaflo @PureWeen Somehow this fix hasn't move to 9.0.100 or 9.0.110. Would you please fix this issue in the latest release?

I hate to release my app using 9.0.100-ci.main.25403.2 😕

**Comment by kubaflo** [comment]
Hi, @darrabam I see your problem :/ This PR hasn't been merged yet. That's why this fix is not in the public MAUI release yet

**Comment by darrabam** [comment]
@jfversluis Could you please merge this PR? I've tested 10.0.0-ci.net10.25524.17 and confirm that it fixes the issue.

**Review by jfversluis — APPROVED** [review]
