### PR TITLE
Blazor Hybrid CSS Hot Reload Fixes

### LINKED ISSUE #7479: BlazorWebView on Windows Forms locks CSS files while the app is running
Hot reload for CSS doesn't work for WinForms apps because the files are locked while the app is running, so you can't save changes to them.

### Repro

1.	Run a WinForms blazor app
2.	Open wwwroot\css\app.css
3.	Try to save the file. It will prompt to save as since the file is locked.

### LINKED ISSUE #9197: CSS hot reload fails in .NET MAUI Blazor app after 2nd edit
Repro steps:

- VS: 17.3 P6
- Create a new .NET MAUI Blazor app
- Edit app.css
- Save to hot reload the change
- Edit app.css again

Expected result: 2nd edit is successfully applied

Actual result:

- No UI update
- Error in Hot Reload output window: "Applying changes to app.css failed. The process cannot access the file 'C:\Users\user\source\repos\MauiApp1\MauiApp1\wwwroot\css\app.css' because it is being used by another process."

Process Explorer shows that the app is holding onto the file:
image

@TanayParikh @mkArtakMSFT @mcumming 

This issue is similar to the [CSS hot reload issue with WinForms](https://github.com/dotnet/maui/issues/7479), but the behavior is different and the way Blazor handles the file stream is different on .NET MAUI which should avoid the [WebView2 locking issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2513). In this case it seems like Blazor or .NET MAUI may be the culprit.

### PR DESCRIPTION
**Pull request by TanayParikh**
Adds [AutoCloseOnReadCompleteStream](https://github.com/dotnet/maui/commit/8dd13168f91933db0938cb36ac5c9fe3bdcd420e) to close out the content stream upon read completion.

Fixes https://github.com/dotnet/maui/issues/7479

---

If the stream content is supplemented by the static hot reload manager, ensures the initial stream is closed out.

Fixes https://github.com/dotnet/maui/issues/9197

### CODE REVIEW

File: src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs [hunk 1]
```diff
@@ -83,15 +83,8 @@ protected override async Task HandleWebResourceRequest(CoreWebView2WebResourceRe
...
-				// NOTE: This is stream copying is to work around a hanging bug in WinRT with managed streams.
-				// See issue https://github.com/microsoft/CsWinRT/issues/670
-				var memStream = new MemoryStream();
-				content.CopyTo(memStream);
-				var ms = new InMemoryRandomAccessStream();
-				await ms.WriteAsync(memStream.GetWindowsRuntimeBuffer());
-
 				var headerString = GetHeaderString(headers);
-				eventArgs.Response = _coreWebView2Environment!.CreateWebResourceResponse(ms, statusCode, statusMessage, headerString);
+				eventArgs.Response = _coreWebView2Environment!.CreateWebResourceResponse(content.AsRandomAccessStream(), statusCode, statusMessage, headerString);
```
Comment (TanayParikh) [inline src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs:87]: This change is already in `main`: https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs#L83-L88

Not sure why GitHub is explicitly displaying it here given the effective 0 diff.

File: src/BlazorWebView/src/SharedSource/AutoCloseOnReadCompleteStream.cs [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+
+		public override bool CanSeek => _baseStream.CanSeek;
+
+		public override bool CanWrite => _baseStream.CanWrite;
+
+		public override long Length => _baseStream.Length;
+
+		public override long Position { get => _baseStream.Position; set => _baseStream.Position = value; }
+
+		public override void Flush() => _baseStream?.Flush();
```
Comment (campersau) [inline src/BlazorWebView/src/SharedSource/AutoCloseOnReadCompleteStream.cs:26]:
```suggestion
		public override void Flush() => _baseStream.Flush();
```

File: src/BlazorWebView/src/SharedSource/AutoCloseOnReadCompleteStream.cs [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+			}
+
+			return bytesRead;
+		}
+
+		public override long Seek(long offset, SeekOrigin origin) => _baseStream.Seek(offset, origin);
+
+		public override void SetLength(long value) => _baseStream.SetLength(value);
+
+		public override void Write(byte[] buffer, int offset, int count) => _baseStream?.Write(buffer, offset, count);
```
Comment (campersau) [inline src/BlazorWebView/src/SharedSource/AutoCloseOnReadCompleteStream.cs:44]:
```suggestion
		public override void Write(byte[] buffer, int offset, int count) => _baseStream.Write(buffer, offset, count);
```

File: src/BlazorWebView/src/SharedSource/AutoCloseOnReadCompleteStream.cs [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+		public override void Flush() => _baseStream?.Flush();
+
+		public override int Read(byte[] buffer, int offset, int count)
+		{
+			var bytesRead = _baseStream.Read(buffer, offset, count);
+
+			if (bytesRead == 0)
+			{
+				_baseStream.Close();
+			}
```
Comment (javiercn) [inline src/BlazorWebView/src/SharedSource/AutoCloseOnReadCompleteStream.cs:35]: I do not think this check is correct. You might receive a `0` count or an empty buffer and those will result in `_baseStream.Read` returning 0.

Would it work if instead we compare the current position against the length of the stream? We should be able to leverage here the fact that we are dealing with files on disk.

Comment (TanayParikh) [reply src/BlazorWebView/src/SharedSource/AutoCloseOnReadCompleteStream.cs:35]: Hmm that's what I initially had, but it necessitated a bit more complexity to avoid accessing the properties of a closed out stream. I did this based on:

> The total number of bytes read into the buffer. This can be less than the number of bytes requested if that many bytes are not currently available, or zero (0) if the end of the stream has been reached.

https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-6.0#system-io-stream-read(system-byte()-system-int32-system-int32)

> Implementations return the number of bytes read. The implementation will block until at least one byte of data can be read, in the event that no data is available. [Read](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-6.0) returns 0 only when there is no more data in the stream and no more is expected (such as a closed socket or end of file). An implementation is free to return fewer bytes than requested even if the end of the stream has not been reached.

Based on this, I believe this should be fine as-is?

Comment (TanayParikh) [reply src/BlazorWebView/src/SharedSource/AutoCloseOnReadCompleteStream.cs:35]: I guess the empty buffer is still potentially problematic here, but that almost seems like an issue in the callee. Maybe we just throw an exception in this case?

Comment (javiercn) [reply src/BlazorWebView/src/SharedSource/AutoCloseOnReadCompleteStream.cs:35]: Could you not keep track of whether you closed the underlying stream already? Would it also not throw before you get to this check in the call to Read if the internal stream was already closed?

Comment (javiercn) [reply src/BlazorWebView/src/SharedSource/AutoCloseOnReadCompleteStream.cs:35]: I am somewhat fine with the additional info provided; those are the types of things that are great comments to add in the code to give context on why that might be Ok to do.

Are there other APIs on the stream that a caller can call instead of just Read that might bypass the check?

Comment (TanayParikh) [reply src/BlazorWebView/src/SharedSource/AutoCloseOnReadCompleteStream.cs:35]: > Are there other APIs on the stream that a caller can call instead of just Read that might bypass the check?

As far as I can tell this should be sufficient as it'll serve as the marker for the end-of-stream is reached on read. I've done some basic testing locally and things are working as expected.

cc/ @yildirimcagri this is a workaround we're implementing for https://github.com/MicrosoftEdge/WebView2Feedback/issues/2513. Essentially wrapping the stream and closing it out when the read is completed. Wanted to get your thoughts on this approach and see if you had any concerns?

**Review by javiercn — APPROVED** [review]
