### PR TITLE
[iOS] Fix indicator dots not rendering when using indicator size with shadow

### LINKED ISSUE #31140: [iOS, Catalyst] IndicatorView – Applying IndicatorSize with Shadow causes some indicators to be invisible
### Description

When setting both the IndicatorSize property and applying a Shadow to an IndicatorView, some of the indicator dots fail to render. 

| Expected Output | Actual Output |
|-----------------|---------------|
|Image|Image

### Steps to Reproduce

1. Run the attached sample [MauiApp7 5.zip](https://github.com/user-attachments/files/21748174/MauiApp7.5.zip)
2. Set IndicatorSize and Shadow for the IndicatorView.

Expected Result:
All indicator dots should be visible and displayed correctly, regardless of IndicatorSize or Shadow settings.

Actual Result:
Some indicator dots are missing or invisible when Shadow is applied together with IndicatorSize.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.90 SR9

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

macOS, iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Shalini-Ashokan**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue Details
Setting both the IndicatorSize property and applying a Shadow to an IndicatorView causes some indicator dots to fail to render properly on iOS.

### Root Cause
The transform is only applied to direct subviews, while actual indicator dots are nested deeper. This causes a mismatch where dots don't scale properly and shadows fail to render correctly.

### Description of Change

Changed `MauiPageControl.UpdateIndicatorSize()` on iOS/MacCatalyst to apply the scale transform to each direct subview individually (the indicator dots) rather than the `UIPageControl` container itself. This ensures shadows render correctly alongside the scaled dots.

Additionally added a `_lastAppliedIndicatorSize` cache field (with a `IndicatorSizeTolerance = 0.001` constant) to skip redundant transform re-application when `LayoutSubviews()` is called with an unchanged `IndicatorSize`. This prevents unnecessary work during frequent layout passes (device rotation, keyboard appearance, etc.).

**Key change:**
- **Before:** `Transform = newTransform;` (whole UIPageControl scaled as a unit)
- **After:** `foreach (var view in Subviews) { view.Transform = newTransform; }` (each dot scaled individually)

Validated the behavior in the following platforms
 
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac
 
### Issues Fixed
  
Fixes #31140 

### Output  ScreenShot

| Before  | After  |
|---------|--------|
|  31140-before |  31140-After |

### CODE REVIEW

File: src/Core/src/Platform/iOS/MauiPageControl.cs [hunk 1]
```diff
@@ -68,8 +68,13 @@ public void UpdateIndicatorSize()
...
 			float scale = (float)IndicatorSize / DefaultIndicatorSize;
 			var newTransform = CGAffineTransform.MakeScale(scale, scale);
-
-			Transform = newTransform;
+			if (Subviews.Length > 0)
+			{
+				foreach (var view in Subviews)
+				{
+					view.Transform = newTransform;
+				}
```
[the remark this answers is not in the document]
Comment (Shalini-Ashokan) [reply src/Core/src/Platform/iOS/MauiPageControl.cs]: I have modified the changes as per your suggestion.

File: src/Core/src/Platform/iOS/MauiPageControl.cs [hunk 2]
```diff
@@ -68,8 +68,10 @@ public void UpdateIndicatorSize()
 
 			float scale = (float)IndicatorSize / DefaultIndicatorSize;
 			var newTransform = CGAffineTransform.MakeScale(scale, scale);
-
-			Transform = newTransform;
+			foreach (var view in Subviews)
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/MauiPageControl.cs:76]: Since `UpdateIndicatorSize()` is called from `LayoutSubviews()`, it could be called frequently during:
- Device rotation
- Keyboard appearance/dismissal
- Parent view layout changes

Could we detect if there are changes in the size?

```
double _lastAppliedIndicatorSize = -1;

if (Math.Abs(IndicatorSize - _lastAppliedIndicatorSize) < 0.001)
     return;
```

_NOTE: Can create a tolerance constant._

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/iOS/MauiPageControl.cs (hunk 2 above)
Comment (Shalini-Ashokan) [reply src/Core/src/Platform/iOS/MauiPageControl.cs:76]: @jsuarezruiz, I have updated the code section based on your suggestions.

**Comment by rmarinho** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong> — <a href="https://github.com/dotnet/maui/commit/9a94b10955270308ed96e2f259136329673e369a"><code>9a94b10</code></a> · <strong>Resaved the images</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

**Issue:** #31140 - [iOS, Catalyst] IndicatorView – Applying IndicatorSize with Shadow causes some indicators to be invisible
**PR:** #31463 - [iOS] Fix indicator dots not rendering when using indicator size with shadow
**Author:** Shalini-Ashokan (community contributor)
**Platforms Affected:** iOS, MacCatalyst
**Files Changed:** 1 fix file, 2 test files, 5 snapshot files (PNG baselines)

### Issue Summary
When setting both `IndicatorSize` and `Shadow` on an `IndicatorView`, some indicator dots fail to render on iOS/MacCatalyst. Root cause: `UpdateIndicatorSize()` applied the scale transform to the `UIPageControl` itself (`Transform = newTransform`), but the actual indicator dots are nested deeper in the view hierarchy, so applying the transform at the parent level caused rendering issues when combined with shadows.

### Fix Description
The fix changes `Transform = newTransform` (parent-level) to iterate over `Subviews` and apply the transform to each direct subview individually. Also adds a `_lastAppliedIndicatorSize` field and tolerance check (`IndicatorSizeTolerance = 0.001`) to avoid redundant updates when `UpdateIndicatorSize()` is called frequently from `LayoutSubviews()`.

### Key Reviewer Feedback
| File:Line | Reviewer | Feedback | Status |
|-----------|----------|----------|--------|
| MauiPageControl.cs:76 | Copilot | Remove unnecessary `Subviews.Length > 0` null check — `foreach` handles empty collections | ✅ ADDRESSED |
| MauiPageControl.cs:76 | jsuarezruiz (CHANGES_REQUESTED) | Add tolerance check to avoid frequent re-apply from `LayoutSubviews()` | ✅ ADDRESSED |

**Note:** jsuarezruiz submitted CHANGES_REQUESTED review, but both requested changes were addressed in subsequent commits. Reviewer re-ran CI pipelines after changes, suggesting acceptance.

### File Classification
- **Fix files:** `src/Core/src/Platform/iOS/MauiPageControl.cs` (+10/-1)
- **Test files:** 
  - `src/Controls/tests/TestCases.HostApp/Issues/Issue31140.cs` (+66)
  - `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue31140.cs` (+22)
- **Snapshot files:** 5 PNG baseline snapshots added/updated

### Prior Agent Review
Prior agent review detected (from PR comments). Gate phase passed. Try-Fix phase was SKIPPED due to API rate limiting in prior session. This session will complete the mandatory Try-Fix phase.

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #31463 | Apply transform to each subview individually instead of parent UIPageControl; add `_lastAppliedIndicatorSize` tolerance guard (0.001) | ⏳ PENDING (Gate) | `MauiPageControl.cs` (+10/-1) | Original PR fix |

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

### Gate Result: ✅ PASSED

**Platform:** ios
**Mode:** Full Verification (RequireFullVerification)

- Tests FAIL without fix: ✅ (tests correctly catch the bug)
- Tests PASS with fix: ✅ (fix correctly resolves the bug)

The test `VerifyAllIndicatorDotsShowShadowsWhenIndicatorSize` correctly verifies the bug is present without the fix and absent with it.

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #31463 | Apply `CGAffineTransform.MakeScale` to each direct `Subview` via `foreach`; add `_lastAppliedIndicatorSize` tolerance guard (0.001) | ✅ PASS (Gate) | `MauiPageControl.cs` (+10/-1) | Original PR fix, includes perf guard |
| 1 | claude-sonnet-4.6 | Use `UIPageControl.PreferredIndicatorImage` — create a custom-sized circle image at the desired diameter to avoid transforms entirely | ❌ FAIL | `MauiPageControl.cs` | Dots overlap: `preferredIndicatorImage` doesn't adjust center-to-center spacing |
| 2 | claude-opus-4.6 | Use `Layer.SublayerTransform = CATransform3D.MakeScale(scale, scale, 1)` — 3D layer transform propagates through all sublayers including shadow wrappers | ✅ PASS | `MauiPageControl.cs` (+5/-2) | No tolerance guard; simpler but missing perf optimization |

### Cross-Pollination
| Model | Round | New Ideas? | Details |
|-------|-------|------------|---------|
| claude-sonnet-4.6 | 2 | No | "NO NEW IDEAS" — three attempts cover meaningful architectural categories |
| claude-opus-4.6 | 2 | No | "NO NEW IDEAS" — remaining variants are equivalent to or share same limitations as existing attempts |

**Exhausted:** Yes (both models said NO NEW IDEAS after round 1)

### Fix Comparison

| Criterion | PR's Fix | Attempt 2 (Layer.SublayerTransform) |
|-----------|----------|--------------------------------------|
| Tests pass | ✅ | ✅ |
| Lines changed | +10/-1 | +5/-2 |
| Performance guard | ✅ (`_lastAppliedIndicatorSize` tolerance) | ❌ Missing |
| Codebase consistency | ✅ Uses `CGAffineTransform` (already in file) | ⚠️ Requires new `using CoreAnimation;` |
| Explicitness | ✅ Clear which views are transformed | ⚠️ Transforms ALL sublayers including any unrelated ones |
| Reviewer feedback addressed | ✅ Both jsuarezruiz suggestions incorporated | ❌ Tolerance guard missing |

**Selected Fix:** PR's fix — despite Attempt 2 being slightly simpler in lines of code, the PR's fix is more complete:
1. Includes the `_lastAppliedIndicatorSize` tolerance guard addressing the key reviewer concern (perf impact from `LayoutSubviews()` calls)
2. Uses `CGAffineTransform` consistent with the existing file style
3. Is more targeted — applies only to the `Subviews` of the control rather than all CA sublayers
4. Incorporates all reviewer feedback (both Copilot and jsuarezruiz suggestions)

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

## ✅ Final Recommendation: APPROVE

### Phase Status
| Phase | Status | Notes |
|---|---|---|
| Pre-Flight | ✅ COMPLETE | iOS/MacCatalyst issue, 1 fix file, 2 test files, 5 snapshots |
| Gate | ✅ PASSED | ios — tests FAIL without fix, PASS with fix |
| Try-Fix | ✅ COMPLETE | 2 attempts: 1 pass (Attempt 2), 1 fail (Attempt 1); PR's fix selected |
| Report | ✅ COMPLETE | |

### Summary
PR #31463 fixes a rendering bug in `IndicatorView` on iOS/MacCatalyst where indicator dots become invisible when both `IndicatorSize` and `Shadow` are set. The fix is minimal, correct, and all reviewer feedback has been addressed. Gate verification confirmed tests fail without the fix and pass with it. Independent try-fix exploration confirmed the PR's approach is correct and the most complete solution.

### Root Cause
`MauiPageControl.UpdateIndicatorSize()` was applying the scale transform to the `UIPageControl` itself (`Transform = newTransform`). When a `Shadow` is applied, iOS renders indicator dots in nested subviews that don't properly inherit transforms from the parent control, causing some dots to disappear. The fix applies the transform to each direct subview individually, ensuring dots remain visible regardless of shadow layer insertion.

### Fix Quality
The fix is:
- **Minimal** — 1 implementation file, +10/-1 lines
- **Correct** — Gate verified tests FAIL without fix, PASS with fix
- **Performance-conscious** — `_lastAppliedIndicatorSize` tolerance guard (0.001) prevents redundant transforms during frequent `LayoutSubviews()` calls (device rotation, keyboard, etc.) — directly addressing jsuarezruiz's review concern
- **Consistent with codebase style** — `foreach (var view in Subviews)` matches the existing pattern used by `UpdateCornerRadius()` in the same class; uses `CGAffineTransform` already present in the file

### Try-Fix Findings
Two independent approaches were explored:
- **Attempt 1** (`PreferredIndicatorImage`): ❌ FAIL — spacing between dots is fixed by UIPageControl's internal layout, causing heavy overlap at large sizes
- **Attempt 2** (`Layer.SublayerTransform`): ✅ PASS — but lacks the `_lastAppliedIndicatorSize` tolerance guard, missing the performance optimization already in the PR

Both models confirmed "NO NEW IDEAS" in cross-pollination. **PR's fix is the best candidate** — it passes tests AND includes the performance optimization Attempt 2 lacks.

### Reviewer Feedback Status
- ✅ Copilot: Remove unnecessary `Subviews.Length > 0` null check — **addressed** (just `foreach` over `Subviews`)
- ✅ jsuarezruiz (CHANGES_REQUESTED): Add tolerance guard to avoid frequent re-apply from `LayoutSubviews()` — **addressed** via `_lastAppliedIndicatorSize` field with `IndicatorSizeTolerance = 0.001` constant

### Test Coverage
- HostApp page (`Issue31140.cs`) demonstrates exact bug reproduction: CarouselView with IndicatorView using `IndicatorSize=30` and Shadow
- Automated test (`VerifyAllIndicatorDotsShowShadowsWhenIndicatorSize`) uses screenshot comparison with `AutomationId="carouselview"`
- Snapshot baselines added for all 4 platforms (iOS, Android, Windows, Mac)
- `PlatformAffected.iOS` correctly scopes the issue attribute

### Title & Description
- **Title**: `[iOS] Fix indicator dots not rendering when using indicator size with shadow` — accurate
- **Description**: Explains issue, root cause, change description, before/after screenshots
- **Required NOTE block**: ✅ Present
- **Issue link**: `Fixes #31140` ✅

</details>

---

</details>




<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

# PR #31463 Finalization Review

**PR:** [#31463 – [iOS] Fix indicator dots not rendering when using indicator size with shadow](https://github.com/dotnet/maui/pull/31463)
**Author:** @Shalini-Ashokan
**Issue:** [#31140 – IndicatorView – Applying IndicatorSize with Shadow causes some indicators to be invisible](https://github.com/dotnet/maui/issues/31140)
**Changed files:** 14 (1 core fix, 2 test files, 11 snapshot images)

---

## Phase 1: Title & Description

### ✅ Title: Good – Minor Enhancement Possible

**Current:** `[iOS] Fix indicator dots not rendering when using indicator size with shadow`

**Assessment:** The title accurately captures the platform, the symptom, and the trigger condition. The issue also affects MacCatalyst per the original bug report, but `[iOS]` is acceptable as the primary platform. No change required.

**Optional improvement (not required):**
```
[iOS/Catalyst] IndicatorView: Fix dots invisible when IndicatorSize and Shadow are combined
```

---

### 🟡 Description: Good Structure, Two Inaccuracies

**Quality assessment:**
- NOTE block: ✅ Present at top
- Root cause: ⚠️ Present but imprecise (see below)
- Description of change: ⚠️ Present but uses incorrect term "recursively"
- Issues Fixed: ✅ `Fixes #31140`
- Platforms tested: ✅ All four checked
- Before/after screenshots: ✅ Included

**Inaccuracies to correct:**

1. **"Applied transforms recursively"** — The fix iterates over `Subviews` (direct children, one level only). There is no recursion. Should say "applied transforms to each direct subview" or "applied transforms individually to each indicator subview."

2. **"traverse the view hierarchy"** — Same issue; the traversal is only one level deep (`foreach (var view in Subviews)`), not a full hierarchy traversal.

3. **Missing mention of `_lastAppliedIndicatorSize` optimization** — The PR also adds a perf guard (`_lastAppliedIndicatorSize` field + tolerance constant `IndicatorSizeTolerance`) to avoid redundantly reapplying transforms on every `LayoutSubviews()` call. This is a meaningful part of the change that should be documented.

**Suggested description update (targeted additions, not a full rewrite):**

Replace the "Description of Change" section content with:

```markdown
### Description of Change

Changed `MauiPageControl.UpdateIndicatorSize()` on iOS/MacCatalyst to apply the scale transform to each direct subview individually (the indicator dots) rather than the `UIPageControl` container itself. This ensures shadows render correctly alongside the scaled dots.

Additionally added a `_lastAppliedIndicatorSize` cache field (with a `IndicatorSizeTolerance = 0.001` constant) to skip redundant transform re-application when `LayoutSubviews()` is called with an unchanged `IndicatorSize`. This prevents unnecessary work during frequent layout passes (device rotation, keyboard appearance, etc.).

**Key change:**
- **Before:** `Transform = newTransform;` (whole UIPageControl scaled as a unit)
- **After:** `foreach (var view in Subviews) { view.Transform = newTransform; }` (each dot scaled individually)
```

**NOTE block:** ✅ Already present and correct.

---

## Phase 2: Code Review

### 🔴 Critical Issue – `_lastAppliedIndicatorSize` Guard May Miss New Indicator Dots

**File:** `src/Core/src/Platform/iOS/MauiPageControl.cs`

**Problem:**
The `_lastAppliedIndicatorSize` early-exit guard prevents transforms from being applied to *newly created* indicator subviews when the page/indicator count changes (but `IndicatorSize` stays the same).

**Sequence that triggers the bug:**
1. Set `IndicatorSize = 30`, `IndicatorCount = 3` → `UpdateIndicatorSize()` runs, applies transform to 3 subviews, sets `_lastAppliedIndicatorSize = 30`.
2. Add 2 more carousel items → `UpdateIndicatorCount()` is called → `UpdatePages(5)` → system triggers `LayoutSubviews()`.
3. `UpdateIndicatorSize()` is called → `Math.Abs(30 - 30) < 0.001` → **returns early without applying the transform to the 2 new subviews.**

The 2 new dots would render at the default size (not `IndicatorSize`), causing visual inconsistency — or possibly the same shadow-invisibility bug the PR is trying to fix.

**Recommendation:** The guard should also check whether the number of subviews that have been transformed matches the current `Subviews.Length`:

```csharp
int _lastAppliedSubviewCount = 0;

public void UpdateIndicatorSize()
{
    if (IndicatorSize == 0 || IndicatorSize == DefaultIndicatorSize)
        return;

    bool sizeUnchanged = Math.Abs(IndicatorSize - _lastAppliedIndicatorSize) < IndicatorSizeTolerance;
    bool countUnchanged = Subviews.Length == _lastAppliedSubviewCount;

    if (sizeUnchanged && countUnchanged)
        return;

    float scale = (float)IndicatorSize / DefaultIndicatorSize;
    var newTransform = CGAffineTransform.MakeScale(scale, scale);
    foreach (var view in Subviews)
    {
        view.Transform = newTransform;
    }

    _lastAppliedIndicatorSize = IndicatorSize;
    _lastAppliedSubviewCount = Subviews.Length;
}
```

---

### 🟡 Suggestion – `PlatformAffected.iOS` in Issue Attribute vs. Also-Affected macOS/Catalyst

**File:** `src/Controls/tests/TestCases.HostApp/Issues/Issue31140.cs`

```csharp
[Issue(IssueTracker.Github, 31140, "...", PlatformAffected.iOS)]
```

The original issue report (`#31140`) lists **macOS and iOS** as affected platforms. The snapshot images include both `mac/` and `ios/` directories, confirming both are tested. The `PlatformAffected` attribute is informational, but setting it to only `iOS` understates the scope. Consider `PlatformAffected.iOS | PlatformAffected.macOS` (or a broader value if available).

---

### 🟡 Suggestion – No End-of-File Newline in HostApp Issue File

**File:** `src/Controls/tests/TestCases.HostApp/Issues/Issue31140.cs`

The patch shows `\ No newline at end of file` at the end. While minor, it is inconsistent with other files in the repo. A trailing newline should be added.

---

### ✅ Positive Observations

- **Core fix is correct:** Applying the transform to each direct subview (`Subviews`) rather than the `UIPageControl` itself is the right approach for making shadows interact correctly with scaled indicator dots.
- **Tolerance constant:** Using `IndicatorSizeTolerance = 0.001` instead of a magic number is clean and maintainable.
- **Snapshot tests added for all platforms:** Android, iOS, Mac, and Windows snapshots are all present, giving good visual regression coverage.
- **Test structure is clean:** `Issue31140` test class follows the established pattern — inherits `_IssuesUITest`, uses `[Category(UITestCategories.IndicatorView)]`, no unnecessary setup/teardown.
- **Before/after screenshots in PR description** clearly demonstrate the fix.
- **Review feedback incorporated:** The null-length check was removed per reviewer suggestion (`Subviews.Length > 0` guard before foreach), and the `_lastAppliedIndicatorSize` optimization was added per reviewer request.

---

## Summary

| Area | Status | Notes |
|------|--------|-------|
| Title | ✅ Good | Accurate; platform prefix correct |
| Description – NOTE block | ✅ Present | |
| Description – Root cause | ⚠️ Imprecise | Says "nested deeper"; real issue is transform on container vs. individual dots |
| Description – Change description | ⚠️ Inaccurate | "recursively" is wrong; no mention of `_lastAppliedIndicatorSize` |
| Description – Issues Fixed | ✅ Present | `Fixes #31140` |
| Description – Platforms tested | ✅ All checked | |
| Code – Core fix logic | ✅ Correct | Applying to Subviews rather than `this` |
| Code – `_lastAppliedIndicatorSize` | 🔴 Bug risk | Guard bypasses transform on new indicator dots when count changes |
| Code – `PlatformAffected` attribute | 🟡 Minor | iOS-only but macOS also affected |
| Code – EOF newline | 🟡 Minor | Missing in HostApp issue file |

</details>

**Review by kubaflo — CHANGES_REQUESTED** [review]
Could you please apply the ai's suggestions?

**Comment by Shalini-Ashokan** [comment]
> Could you please apply the ai's suggestions?

@kubaflo, I have addressed all three suggestions: 

1.  Updated the PR "Description of Change" to accurately reflect the implementation details. 
2.  Verified the early-exit guard concern — it's not a real bug since UIPageControl.Subviews contains a single container view, and UIKit's transform inheritance automatically scales all children including dots added later, so re-applying on new items isn't needed. 
3.  Added a newline at end of file and updated PlatformAffected.iOS to PlatformAffected.iOS | PlatformAffected.macOS

File: src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyAllIndicatorDotsShowShadowsWhenIndicatorSize.png
Comment (MartyIX) [inline src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyAllIndicatorDotsShowShadowsWhenIndicatorSize.png:1]: Shouldn't the left circle be blue here?

**Review by kubaflo — APPROVED** [review]

**Review by kubaflo — APPROVED** [review]
