### PR TITLE
[iOS] Shell page title fix

### LINKED ISSUE #20199: [iOS] Page titles do not appear until navigating when pushing a modal page at startup
### Description

On iOS, if you push a modal page onto the navigation stack at startup, page title are not displayed until navigating.

<br>
**❌ Figure: A modal page is pushed at startup, when it is popped the page title in Shell is not displayed. After navigating, the title is displayed.**

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Push a modal page during startup (e.g., in `AppShell.xaml.cs` overriding `OnAppearing`)
3. Run on iOS
4. Pop the page that is pushed at startup
5. Observe bug 🐞
6. Navigate to another page
7. Observe that title is now displayed
8. Navigate back
9. Observe that title is now displayed

### Link to public reproduction project repository

https://github.com/matt-goldman/ios-modal-title-bug

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

Shell page title fix - setting the shell page's toolbar title in the `ViewDidLoad` method

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/20199

|Before|After|
|--|--|
|<video src="https://github.com/dotnet/maui/assets/42434498/60bac422-3e82-4aa1-bc64-5707b6303e74" />|<video src="https://github.com/dotnet/maui/assets/42434498/08f4ad53-b434-40f9-bcae-651c1e6507d1" />|

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Added pending test snapshot.

**Review by dustin-wojciechowski — DISMISSED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs [hunk 1]
```diff
@@ -113,9 +113,12 @@ public override void ViewDidLoad()
 			tracker.IsRootPage = true;
 			tracker.ViewController = this;
 
+			_tracker = tracker;
 			if (ShellSection.CurrentItem != null)
+			{
 				tracker.Page = ((IShellContentController)ShellSection.CurrentItem).GetOrCreateContent();
-			_tracker = tracker;
+				NavigationItem.Title = _shellContext.Shell.Toolbar.Title;
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs:120]: I think the bug with this one is that Disappearing is never fired on the root page.

Like if you set a break point on disapearing

```C#
	public class Issue20199Page : ContentPage {

		protected override void OnAppearing()
		{
			base.OnAppearing();
		}

		protected override void OnDisappearing()
		{
			base.OnDisappearing();
		}
	}
```

disappearing never fires

if we get disappearing to fire (or perhaps get appearing to not fire)
That should fix the title

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs [hunk 2]
```diff
@@ -114,8 +114,10 @@ public override void ViewDidLoad()
 			tracker.ViewController = this;
 
 			if (ShellSection.CurrentItem != null)
+			{
 				tracker.Page = ((IShellContentController)ShellSection.CurrentItem).GetOrCreateContent();
-			_tracker = tracker;
+				_tracker = tracker;
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs:119]: Is this change still correct to have?

Comment (kubaflo) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs]: Right! No need for this one

**Review by PureWeen — APPROVED** [review]

**Review by dustin-wojciechowski — APPROVED** [review]
