### PR TITLE
[iOS] Fix ListView Scrolled event not triggering

### LINKED ISSUE #22630: ListView Scrolled event is not triggered
### Description

On iOS the ListView.Scrolled event is not triggered anymore in version 8.0.40 (used to work in 8.0.21).
On Android it is still working.

### Steps to Reproduce

Use this xaml:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ListViewScroll.MainPage">

    <Grid RowDefinitions="Auto,*">
        <SearchBar/>
        <ListView Grid.Row="1" Scrolled="ListView_Scrolled">
            <ListView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>Item 1</x:String>
                    <x:String>Item 2</x:String>
                    <x:String>Item 3</x:String>
                    <x:String>Item 4</x:String>
                    <x:String>Item 5</x:String>
                    <x:String>Item 6</x:String>
                    <x:String>Item 7</x:String>
                    <x:String>Item 8</x:String>
                    <x:String>Item 9</x:String>
                    <x:String>Item 10</x:String>
                    <x:String>Item 11</x:String>
                    <x:String>Item 12</x:String>
                    <x:String>Item 13</x:String>
                    <x:String>Item 14</x:String>
                    <x:String>Item 15</x:String>
                    <x:String>Item 16</x:String>
                    <x:String>Item 17</x:String>
                    <x:String>Item 18</x:String>
                    <x:String>Item 19</x:String>
                    <x:String>Item 20</x:String>
                    <x:String>Item 21</x:String>
                    <x:String>Item 22</x:String>
                    <x:String>Item 23</x:String>
                    <x:String>Item 24</x:String>
                    <x:String>Item 25</x:String>
                    <x:String>Item 26</x:String>
                    <x:String>Item 27</x:String>
                    <x:String>Item 28</x:String>
                    <x:String>Item 29</x:String>
                </x:Array>
            </ListView.ItemsSource>
        </ListView>
    </Grid>
</ContentPage>
```

And then in the codebehind something like this:
```
namespace ListViewScroll;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}

	void ListView_Scrolled(System.Object sender, Microsoft.Maui.Controls.ScrolledEventArgs e)
	{
		Console.WriteLine("ListView_Scrolled is called");
	}
}
```

On iOS the ListView_Scrolled is not called, but on Android it is.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.21 SR4.1

### Affected platforms

iOS

### Affected platform versions

iOS 17.4.1

### Did you find any workaround?

When using a CollectionView instead of a ListView, it does work.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix ListView Scrolled event not triggering on iOS.

### Issues Fixed

Fixes #22630

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/ListViewRenderer.cs [hunk 1]
```diff
@@ -1276,7 +1276,7 @@ public override void Scrolled(UIScrollView scrollView)
 					return;
 
 				var args = new ScrolledEventArgs(scrollView.ContentOffset.X, scrollView.ContentOffset.Y);
-				if (!_list.TryGetTarget(out var list))
+				if (_list.TryGetTarget(out var list))
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/ListViewRenderer.cs:1279]: Changes applied fixing https://github.com/dotnet/maui/issues/20025
Mistake in comparison.

**Review by rmarinho — APPROVED** [review]
