### PR TITLE
[iOS] Setting background color on the Searchbar - fix

### LINKED ISSUE #23325: Setting background color on the Searchbar does nothing on iOS
### Description

Setting background color on the Searchbar does nothing on iOS. It works fine on Android.

### Steps to Reproduce

Run the solution in Android simulator. Note that the top bar is black and the search bar is white.
image

Run the solution in iOS. Note that the search bar is dark grey and barely visible.
image

### Link to public reproduction project repository

https://github.com/JRPMike/Maui_SearchStylingIssue.git

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS17

### Did you find any workaround?

No. 

### Relevant log output

_No response_

### LINKED ISSUE #24100: Initial value for the SearchHandler background color ignored on page first appearance
### Description

The SearchHandler background color property, for the search input field, is ignored when a shell page is initially loaded. Navigating away from the page and returning then displays the correct color.

Given the following markup:
```
<Shell.SearchHandler>
    <SearchHandler Placeholder="Enter search term" BackgroundColor="Red">
    </SearchHandler>
</Shell.SearchHandler>
```
You would expect the search input to have a background color of Red but this property is ignored...
initial-page-load

After navigating away from the page and returning the background color is rendered correctly...
after-navigating-back

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Add a 'SearchHandler' to a page like so:
```
<Shell.SearchHandler>
    <SearchHandler Placeholder="Enter search term" BackgroundColor="Red">
    </SearchHandler>
</Shell.SearchHandler>
```
3. Add another page and a means to navigate between the two, such as tabs.
4. Launch app and observe the background color is ignored.
5. Navigate to the second page.
6. Return to the original page and observe the background color is now applied.

Expected outcome:
The background color should be applied to the search input on initial load.

Actual outcome:
The background color is ignored until returning to the page after it's initial load.

### Link to public reproduction project repository

https://github.com/andy-cox/maui-searchhandler-background-color/tree/net9.0

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.5

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/23325
Fixes https://github.com/dotnet/maui/issues/24100

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/SearchHandlerAppearanceTracker.cs [hunk 1]
```diff
@@ -165,6 +165,7 @@ void UpdateSearchBarBackgroundColor(UITextField textField)
 			if (_defaultBackgroundColor == null)
 				_defaultBackgroundColor = backgroundView.BackgroundColor;
 			backgroundView.BackgroundColor = backGroundColor.ToPlatform();
+			textField.BackgroundColor= backGroundColor.ToPlatform();
```
Comment (dartasen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/SearchHandlerAppearanceTracker.cs:168]:
```suggestion
			textField.BackgroundColor = backGroundColor.ToPlatform();
```

**Review by mattleibow — DISMISSED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/SearchHandlerAppearanceTracker.cs [hunk 2]
```diff
@@ -165,6 +165,7 @@ void UpdateSearchBarBackgroundColor(UITextField textField)
 			if (_defaultBackgroundColor == null)
 				_defaultBackgroundColor = backgroundView.BackgroundColor;
 			backgroundView.BackgroundColor = backGroundColor.ToPlatform();
+			textField.BackgroundColor = backGroundColor.ToPlatform();
```
Comment (pictos) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/SearchHandlerAppearanceTracker.cs:168]: can't this `backGroundColor` be cached at one filed and reused? Something like

```suggestion
			var backgroundColor = backGroundColor.ToPlatform();
			backgroundView.BackgroundColor = backgroundColor;
			textField.BackgroundColor = backgroundColor;
```

**Comment by aheubusch** [comment]
@kubaflo @PureWeen I think I see another bug. Once a custom BackgroundColor has been set its not possible to return to the default color (`searchHandler.BackgroundColor = null;`). Infact it will cause a NRE in line 168 (`backGroundColor.ToPlatform()`).
Proposed change to line 154
```csharp
if (backGroundColor == null)
{
	_hasCustomBackground = false;
	
	backgroundView.Layer.CornerRadius = 0;
	backgroundView.ClipsToBounds = false;
	backgroundView.BackgroundColor = _defaultBackgroundColor;
	textField.BackgroundColor = _defaultBackgroundColor;
	
	return;
}
```

**Review by mattleibow — APPROVED** [review]
@kubaflo not sure if you had thoughts or observed exceptions when setting back to null?

https://github.com/dotnet/maui/pull/23355#issuecomment-2379965420

That is technically a separate issue and you have probs fixed it already :)
