### PR TITLE
Check to see if Image Should Reload When Attached

### LINKED ISSUE #14471: [Android] Image can disappear when going back to the page.
### Description

First things first please rename the title of this issue to the more correct one as I didn't know how to title it.

I'm experiencing a problem, might be xaml or shell related. The images dissapear when moving between tabs. If I have Image with its source set on the page on the moment the app is building and debugging it will stay there when changing tabs but when Image is loaded on runtime like when I pull data from API (being binded), (Or add image url in xaml and hot reload) it will dissapear when changing tabs. 

When I switched .net run time for all platforms from .net 7 to .net 6 it seems to fix it so the issue might be related to that somehow? That's the only discovery I've made so far. Also this issue doesn't seem to persist on other platforms at least it doesn't on Windows. I don't have any apple devices.

Video shows that when adding an image before hand works fine when switching tabs. But there is a bug when adding an image in runtime. This doesn't happen on .net 6.

https://user-images.githubusercontent.com/84880432/230725995-6d84f679-5c5e-4861-92ec-254bb72f8bd4.mp4

### Steps to Reproduce

1. Make fresh project
2. Try to add picture on runtime and switch tabs.

### Link to public reproduction project repository

https://github.com/ziomek64/TabBarPhotoTest

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

Use maui on .net 6

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

This is a simplified down version of https://github.com/dotnet/maui/pull/23830. Glide monitors the life cycle of the fragment that it is contained in. If the fragment is paused or stopped it will dispose of the bitmap and set the drawable on the image to null.  This PR checks to see if an ImageView should have a drawable when it's being reattached to the window. If it should, then it refires the image loading code so that `Glide` can reload the image. 

We should fix this more completely in the Glide layer, but, for now this will at least fix a really nasty bug with images. 

### Issues Fixed
Fixes #14471

### CODE REVIEW

**Review by mattleibow — APPROVED** [review]

File: src/Core/src/Platform/ImageSourcePartLoader.cs [hunk 1]
```diff
@@ -28,6 +28,12 @@ public partial class ImageSourcePartLoader
 		IImageSourceServiceProvider? _imageSourceServiceProvider;
 #endif
 
+		#if ANDROID
+		// This is a temporary workaround for Android so that images don't just keep vanishing
+		// We will have a better fix in the next release that's better integrated with Glide
+		internal bool CheckForImageLoadedOnAttached { get; set; }
+		#endif
```
Comment (mattleibow) [inline src/Core/src/Platform/ImageSourcePartLoader.cs:35]: Can we get an issue assigned to something so this does not haunt us forever?
