### PR TITLE
Fix XAML C# expression setter generation for read-only properties

### LINKED ISSUE #34075: XAML C# expression tries to assign a value to the read-only properties, but it should be based on the binding mode
### Description

XAML C# expression tries to assign a value to the read-only properties, but it should be based on the binding mode.

Try binding a ViewModel's Command property to the Button or a getter-only property to the Label.

**Command:**

```cs
private RelayCommand? incrementCommand;
public IRelayCommand IncrementCommand => incrementCommand ??= new RelayCommand(new Action(Increment));

[ObservableProperty]
public partial string CountText { get; private set; } = "Current count: 0";
```

**XAML:**

```xml
<Button Command="{IncrementCommand}" />
<Label Text="{CountText}" />
```

But ends up in a build error.

Error message: Property or indexer 'MainViewModel.IncrementCommand' cannot be assigned to -- it is read only.

It seems that it tries to assign a value to the read-only Command property. In general, command properties are intended to be read-only, featuring only a getter.

### Steps to Reproduce

Try binding a getter-only, like Command, property in XAML using a C# expression.

### Link to public reproduction project repository

Easy to reproduce.

### Version with bug

10.0.40

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

Revert to the classic Binding extension.

### Relevant log output

```shell
The Property or indexer 'MainViewModel.IncrementCommand' cannot be assigned to -- it is read only.
The property or indexer 'MainViewModel.CountText' cannot be used in this context because the set accessor is inaccessible.
```

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

## Description

Fixes #34075

The XAML source generator was generating setter assignments (e.g., `__source.ReadOnlyText = __value`) for getter-only properties when using C# expression bindings like `{ReadOnlyText}`. This caused CS0200 build errors at compile time.

### Root Cause

`ExpressionAnalyzer.IsSimplePropertyChain()` only checks whether the expression is syntactically a simple property chain (member access, identifier), but does not verify whether the terminal property actually has a public setter. So `{ReadOnlyText}` where `ReadOnlyText` is `string ReadOnlyText => "Hello"` was incorrectly marked as settable.

### Fix

Added `IsExpressionWritable()` in `SetPropertyHelpers.cs` that walks the property chain on the `dataType` symbol and checks whether the terminal property has a public, non-init setter. The setter lambda is only generated when both the syntactic check (`IsSettable`) and the semantic check (`IsExpressionWritable`) pass.

### Changes

- `src/Controls/src/SourceGen/SetPropertyHelpers.cs` — Added `IsExpressionWritable()` helper and gated setter generation on it
- `src/Controls/tests/Xaml.UnitTests/Issues/Maui34075.*` — Regression test with getter-only properties bound via C# expressions

### Testing

- New `.sgen.xaml` test inflates successfully via SourceGen with read-only property bindings
- Existing `NullConditionalSettable` test (two-way binding to writable properties) still passes
- Existing `TwoWayDecimalBinding_UIToVM` test still passes (setter works for writable properties)

### CODE REVIEW

File: src/Controls/src/SourceGen/SetPropertyHelpers.cs [hunk 1]
```diff
@@ -917,4 +917,73 @@ static bool IsTwoWayByDefault(IFieldSymbol bpFieldSymbol)
...
+		var expr = expression.Trim();
+
+		// Strip leading dot prefix (e.g., ".Name" → "Name"), but avoid the ".." range operator
+		if (expr.StartsWith(".", StringComparison.Ordinal) &&
+			!expr.StartsWith("..", StringComparison.Ordinal))
+			expr = expr.Substring(1);
+
+		// Strip "BindingContext." prefix (e.g., "BindingContext.Name" → "Name")
+		if (expr.StartsWith("BindingContext.", StringComparison.Ordinal))
+			expr = expr.Substring("BindingContext.".Length);
```
Comment (jonathanpeppers) [inline src/Controls/src/SourceGen/SetPropertyHelpers.cs]: Should this somehow check if it is actually `BindableObject.BindingContext`?

You could have a POCO that has `public Person BindingContext;`

**Review by jonathanpeppers — DISMISSED** [review]
Besides the one question, looks good to me.

File: src/Controls/src/SourceGen/SetPropertyHelpers.cs (hunk 1 above)
Comment (StephaneDelcroix) [reply src/Controls/src/SourceGen/SetPropertyHelpers.cs]: if the XAML isn't inheriting from BO... technically, yes

**Review by jonathanpeppers — APPROVED** [review]
