### PR TITLE
IllegalArgumentException when changing number of tabbar pages - fix

### LINKED ISSUE #18251: IllegalArgumentException .NET MAUI 8 RC 2
### Description

In an .NET MAUI app I tried to compile using 8 RC 2. Compile works fine but get a:

IllegalArgumentException
Maximum number of items supported by BottomNavigationView is 5. Limit can be checked with BottomNavigationView#getMaxItemCount()

I have a a TabBar with 14 lines. It works fine on .NET MAUI 7 (Android shows 4 and wraps/creates a menu list (three dots above each other) to expand, as per specification.  

Apparently, the wrapping does not work in .NET 8

### Steps to Reproduce

Create a Tabbar with more than 5 lines (or perhaps as many as 14) Compile and run.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

Android

### Affected platform versions

Android 13 (have not tested on prior versions

### Did you find any workaround?

No

### Relevant log output

```shell
Stack trace captured by Sentry:

com.google.android.material.navigation.NavigationBarMenu in addInternal at line 67
androidx.appcompat.view.menu.MenuBuilder in add at line 478
mono.java.lang.RunnableImplementor in n_run
mono.java.lang.RunnableImplementor in run at line 31
android.os.Handler in handleCallback at line 942
android.os.Handler in dispatchMessage at line 99
android.os.Looper in loopOnce at line 226
android.os.Looper in loop at line 313
android.app.ActivityThread in main at line 8757
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 571
com.android.internal.os.ZygoteInit in main at line 1067
```

Full stacktrace:

```
Java.Lang.IllegalArgumentException: Maximum number of items supported by BottomNavigationView is 5. Limit can be checked with BottomNavigationView#getMaxItemCount()
   at Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 19992
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 867
   at AndroidX.AppCompat.View.Menu.MenuBuilder.Add(Int32 group, Int32 id, Int32 categoryOrder, ICharSequence title) in C:\a\_work\1\s\generated\androidx.appcompat.appcompat\obj\Release\net6.0-android\generated\src\AndroidX.AppCompat.View.Menu.MenuBuilder.cs:line 810
   at Android.Views.IMenuExtensions.Add(IMenu self, Int32 groupId, Int32 itemId, Int32 order, String title) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.IMenu.cs:line 187
   at Microsoft.Maui.Controls.Platform.BottomNavigationViewUtils.SetupMenu(IMenu menu, Int32 maxBottomItems, List`1 items, Int32 currentIndex, BottomNavigationView bottomView, IMauiContext mauiContext) in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\BottomNavigationViewUtils.cs:line 107
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
   at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:line 84
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 26
  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: Maximum number of items supported by BottomNavigationView is 5. Limit can be checked with BottomNavigationView#getMaxItemCount()
	at com.google.android.material.navigation.NavigationBarMenu.addInternal(NavigationBarMenu.java:67)
	at androidx.appcompat.view.menu.MenuBuilder.add(MenuBuilder.java:478)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.n_onClick(Native Method)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.onClick(ButtonHandler_ButtonClickListener.java:31)
	at android.view.View.performClick(View.java:7506)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29334)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: Maximum number of items supported by BottomNavigationView is 5. Limit can be checked with BottomNavigationView#getMaxItemCount()
	at com.google.android.material.navigation.NavigationBarMenu.addInternal(NavigationBarMenu.java:67)
	at androidx.appcompat.view.menu.MenuBuilder.add(MenuBuilder.java:478)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.n_onClick(Native Method)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.onClick(ButtonHandler_ButtonClickListener.java:31)
	at android.view.View.performClick(View.java:7506)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29334)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/18251

|Before|After|
|--|--|
|<video src="https://github.com/dotnet/maui/assets/42434498/5c30cd52-da19-4162-8de4-bd2a62ba67e4" width="300px"/>|<video src="https://github.com/dotnet/maui/assets/42434498/a5b4ebc8-82fd-44ef-bc8c-f16d2e036ddc" width="300px"/>|

### CODE REVIEW

File: src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs [hunk 1]
```diff
@@ -73,10 +73,7 @@ internal static void UpdateEnabled(bool tabEnabled, IMenuItem menuItem)
 		{
 			Context context = mauiContext.Context;
 
-			while (items.Count < menu.Size())
-			{
-				menu.RemoveItem(menu.GetItem(menu.Size() - 1).ItemId);
-			}
+			menu.Clear();
```
Comment (PureWeen) [inline src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs:76]: Need to verify this change against
https://github.com/dotnet/maui/commit/16a3972f6941a174d2df7b385613bda2955e6e66#diff-1787c6c4f33d04c0dd8bceddf563be45c136658b564e5a6be28161f37b79adc5R75-R80

Where I originally modified this. 

Make sure the issue fixed by that PR doesn't resurface here

Comment (PureWeen) [reply src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs:76]: I think the idea is that we don't want to completely clear the menu and then re-add because then it causes a shuffling to happen visually
So, the point of walking backwards was to just sync the list, instead of just clear and re-add
I think will still need the old code but a variation of it

**Review by jfversluis — CHANGES_REQUESTED** [review]
Seem to be some tests failing although it seems like a detail with whitespace or something

> Assert.Equal() Failure: Values differ\nExpected: Tab 1\nActual:   Tab 1

File: src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs (hunk 1 above)
Comment (kubaflo) [reply src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs]: @PureWeen I've added a commit. Let me know what you think

File: src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs [hunk 2]
```diff
@@ -104,6 +104,8 @@ internal static void UpdateEnabled(bool tabEnabled, IMenuItem menuItem)
 			if (showMore)
 			{
 				var moreString = context.Resources.GetText(Resource.String.overflow_tab_title);
+				if (menu.Size() == maxBottomItems)
```
Comment (rmarinho) [inline src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs:107]: maybe we can grab menu.Size() only once here

File: src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs [hunk 3]
```diff
@@ -104,6 +104,8 @@ internal static void UpdateEnabled(bool tabEnabled, IMenuItem menuItem)
...
+					menu.RemoveItem(menu.GetItem(menu.Size() - 1).ItemId);
```
Comment (PureWeen) [inline src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs:108]: I feel like in this else check we need to see if we've hit the "more" item and then remove iit if we do
https://github.com/dotnet/maui/pull/22589/files#diff-1787c6c4f33d04c0dd8bceddf563be45c136658b564e5a6be28161f37b79adc5R94-R99

like, if the user has 6 items it'll be
0,1,2,3,more

if they go down to 5 items then I think the more tab won't swap in the correct 5th item

And then instead of "Removing" this item. Can we retrieve the item using the MoreTabId to see if it was still added?

Comment (kubaflo) [reply src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs]: @PureWeen you're right

<video src="https://github.com/dotnet/maui/assets/42434498/0a0d85d5-ec51-4947-8d7b-745ac8b3e0b9" width="300px"/>

File: src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs [hunk 4]
```diff
@@ -94,16 +94,27 @@ internal static void UpdateEnabled(bool tabEnabled, IMenuItem menuItem)
 				else
 				{
 					menuItem = menu.GetItem(i);
-					SetMenuItemTitle(menuItem, item.title);
-					loadTasks.Add(SetMenuItemIcon(menuItem, item.icon, mauiContext));
+					if (menuItem.ItemId != i)
+					{
+						menu.RemoveItem(MoreTabId);
```
Comment (PureWeen) [inline src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs:99]:
```suggestion
						menu.RemoveItem(menuItem.ItemId);
```

File: src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs [hunk 5]
```diff
@@ -94,16 +94,27 @@ internal static void UpdateEnabled(bool tabEnabled, IMenuItem menuItem)
...
+					{
+						SetMenuItemTitle(menuItem, item.title);
+						loadTasks.Add(SetMenuItemIcon(menuItem, item.icon, mauiContext));
+					}
 				}
 
 				menuItems.Add(menuItem);
 			}
 
 			if (showMore)
```
[the remark this answers is not in the document]
Comment (kubaflo) [reply src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs:112]: This causes a crash

File: src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs [hunk 6]
```diff
@@ -94,16 +94,27 @@ internal static void UpdateEnabled(bool tabEnabled, IMenuItem menuItem)
...
 
 				menuItems.Add(menuItem);
 			}
 
-			if (showMore)
+			var menuSize = menu.Size();
+			if (showMore && menu.GetItem(menuSize - 1).ItemId != MoreTabId)
 			{
 				var moreString = context.Resources.GetText(Resource.String.overflow_tab_title);
+				if (menuSize == maxBottomItems)
```
Comment (PureWeen) [inline src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs:116]: Do we still need these two lines of code?

Comment (kubaflo) [reply src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs:116]: I have a crash without them :/

Comment (PureWeen) [reply src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs:116]: yea, ok, I guess I could see some scenarios where that might happen

Like, if you have 5 items and then add a 6th
It'll need to transition that 5th item to a more tab

**Review by jsuarezruiz — APPROVED** [review]

**Review by jfversluis — APPROVED** [review]

**Comment by jfversluis** [comment]
Another @kubaflo original, thank you so much for this!
