### PR TITLE
[C] Replace value with same specificity

### LINKED ISSUE #17357: [regression/8.0.0-preview.7.8842] `ArgumentException` on OnPropertyChanged
### Description

Going from .NET 8 Preview 6 -> RC 1 I've observed the following issue on **one** of my ViewModels. 

I have a `IsBlinking` property that calls `OnPropertyChanged` from [.NET Community Toolkit](https://github.com/CommunityToolkit/dotnet) MVVM. Whenever `OnPropertyChanged` gets called, it throws the following stacktrace.

```
 System.ArgumentException: An item with the same key has already been added. Key: Microsoft.Maui.Controls.SetterSpecificity (Parameter 'key')
   at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
   at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.Setter.Apply(BindableObject target, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.TriggerBase.OnConditionChanged(BindableObject bindable, Boolean oldValue, Boolean newValue)
   at Microsoft.Maui.Controls.BindingCondition.OnBoundPropertyChanged(BindableObject bindable, Object oldValue, Object newValue)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget)
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__50_0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(String propertyName)
   ```
   
   Unfortunately, I can't easily reproduce this in a sample project, but the problem resolves itself when downgrading back to Preview 6. 

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

[8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

Wrap in try/catch?

### Relevant log output

_No response_

### LINKED ISSUE #17391: [regression/8.0.0-rc.1.9171] [MAUI] The App crashes after pulling up and then pulling down the RefreshView C6 page
### Description

[MAUI] The App crashes after pulling down and then pulling up the RefreshView C6 page
Note: This bug not repro on iOS target. 

### Steps to Reproduce

1.Deploy https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests to Windows.
2.Click or tap on category 'C' for 'RefreshView'.
3.Click or tap on test 'C6'.
4. Pull up and pull down the page to initiate a refresh.

**Result: App crash** 
C6

### Link to public reproduction project repository

https://devdiv.visualstudio.com/Pkgs/_git/VS.TestAssets.Xaml?path=/Assets/Projects/ManualMauiTests

### Version with bug

[8.0.0-rc.1.9171](https://github.com/dotnet/maui/releases/tag/8.0.0-rc.1.9171)

### Is this a regression from previous behavior?

Yes, this used to work in MAUI

### Last known working version

[8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842)

### Affected platforms

Android

### Affected platform versions

Android API33

### LINKED ISSUE #17427: [net8] Exception after setting `BindingContext`
### Description

Project was working fine while using `net7`, just switched to `net8` and I`m getting this exception now on a specific `Page` when setting the `BindingContext`. Tested `Android` and `Windows`, both throwing the same issue,

image

Exception
An item with the same key has already been added. Key: Microsoft.Maui.Controls.SetterSpecificity (Parameter 'key').

>    at System.Collections.Generic.SortedList`2[[Microsoft.Maui.Controls.SetterSpecificity, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Add(SetterSpecificity key, Object value)

App is using `DependencyInjection`  and there are two `Pages` having the same `ViewModel`.

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell
at System.Collections.Generic.SortedList`2[[Microsoft.Maui.Controls.SetterSpecificity, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Add(SetterSpecificity key, Object value)
   at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 286
   at Microsoft.Maui.Controls.Setter.Apply(BindableObject target, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\Setter.cs:line 77
   at Microsoft.Maui.Controls.VisualStateManager.GoToState(VisualElement visualElement, String name) in D:\a\_work\1\s\src\Controls\src\Core\VisualStateManager.cs:line 110
   at Microsoft.Maui.Controls.VisualElement.ChangeVisualState() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1482
   at Microsoft.Maui.Controls.View.ChangeVisualState() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 182
   at Microsoft.Maui.Controls.VisualElement.OnIsEnabledPropertyChanged(BindableObject bindable, Object oldValue, Object newValue) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1554
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 611
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 539
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 444
   at Microsoft.Maui.Controls.VisualElement.set_IsEnabled(Boolean value) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 618
   at Syncfusion.Maui.Inputs.SfNumericEntry.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 609
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 539
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 444
   at Microsoft.Maui.Controls.BindableObjectExtensions.RefreshPropertyValue(BindableObject self, BindableProperty property, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 23
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.Controls.IPropertyPropagationController.PropagatePropertyChanged(String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1632
   at Microsoft.Maui.Controls.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children) in D:\a\_work\1\s\src\Controls\src\Core\Internals\PropertyPropagationExtensions.cs:line 32
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.Controls.IPropertyPropagationController.PropagatePropertyChanged(String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1637
   at Microsoft.Maui.Controls.VisualElement.OnIsEnabledPropertyChanged(BindableObject bindable, Object oldValue, Object newValue) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1556
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 611
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 539
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 444
   at Microsoft.Maui.Controls.BindableObjectExtensions.RefreshPropertyValue(BindableObject self, BindableProperty property, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 23
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.Controls.IPropertyPropagationController.PropagatePropertyChanged(String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1632
   at Microsoft.Maui.Controls.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children) in D:\a\_work\1\s\src\Controls\src\Core\Internals\PropertyPropagationExtensions.cs:line 32
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.Controls.IPropertyPropagationController.PropagatePropertyChanged(String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1637
   at Microsoft.Maui.Controls.VisualElement.OnIsEnabledPropertyChanged(BindableObject bindable, Object oldValue, Object newValue) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1556
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 611
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 539
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 163
   at Microsoft.Maui.Controls.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 78
   at Microsoft.Maui.Controls.Binding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\Binding.cs:line 137
   at Microsoft.Maui.Controls.BindableObject.ApplyBindings(Boolean skipBindingContext, Boolean fromBindingContextChanged) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 629
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 332
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 219
   at Microsoft.Maui.Controls.Grid.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Layout\Grid.cs:line 353
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 219
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 219
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 219
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.ContentView.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\ContentView\ContentView.cs:line 33
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 219
   at Microsoft.Maui.Controls.Grid.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Layout\Grid.cs:line 353
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 219
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 219
   at Microsoft.Maui.Controls.Grid.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Layout\Grid.cs:line 353
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 219
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 219
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 219
   at Microsoft.Maui.Controls.Grid.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Layout\Grid.cs:line 353
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.TemplatedView.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\TemplatedView\TemplatedView.cs:line 72
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 219
   at Microsoft.Maui.Controls.ContentView.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\ContentView\ContentView.cs:line 23
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.TemplatedView.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\TemplatedView\TemplatedView.cs:line 72
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 219
   at Microsoft.Maui.Controls.ContentView.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\ContentView\ContentView.cs:line 23
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 219
   at Microsoft.Maui.Controls.Grid.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Layout\Grid.cs:line 353
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Syncfusion.Maui.Core.SfView.UpdateBindingContextToChild(BindableObject view)
   at Syncfusion.Maui.Core.SfView.OnBindingContextChanged()
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 333
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.TemplatedPage.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\TemplatedPage.cs:line 43
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 43
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.Page.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Page\Page.cs:line 334
   at Microsoft.Maui.Controls.ContentPage.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\ContentPage\ContentPage.cs:line 44
   at Microsoft.Maui.Controls.BindableObject.BindingContextPropertyChanged(BindableObject bindable, Object oldvalue, Object newvalue) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 649
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 611
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 539
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 444
   at Microsoft.Maui.Controls.BindableObject.set_BindingContext(Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 54
   at PrintCostCalculator3d.Views.ModernCalculatorPage..ctor(CalculatorPageViewModel viewModel) in D:\VS\GitHub\3dPrintCostCalculatorMaui\src\PrintCostCalculator3d\Views\ModernCalculatorPage.xaml.cs:line 10
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Extensions.DependencyInjection.ServiceProvider.ServiceAccessor, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetOrAdd(ServiceIdentifier key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType) in D:\a\_work\1\s\src\Core\src\MauiContext.cs:line 68
   at Microsoft.Maui.Controls.ShellContent.<>c__DisplayClass19_0.<Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent>b__0() in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellContent.cs:line 76
   at Microsoft.Maui.Controls.ElementTemplate.CreateContent() in D:\a\_work\1\s\src\Controls\src\Core\ElementTemplate.cs:line 86
   at Microsoft.Maui.Controls.Internals.DataTemplateExtensions.CreateContent(DataTemplate self, Object item, BindableObject container) in D:\a\_work\1\s\src\Controls\src\Core\DataTemplateExtensions.cs:line 23
   at Microsoft.Maui.Controls.ShellContent.Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent() in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellContent.cs:line 81
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellSectionRenderer.cs:line 124
   at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_inflater, IntPtr native_container, IntPtr native_savedInstanceState) in C:\a\_work\1\s\generated\androidx.fragment.fragment\obj\Release\net6.0-android\generated\src\AndroidX.Fragment.App.Fragment.cs:line 2031
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 367
```

### LINKED ISSUE #17776: Calling SetBinding after setting a constant value crashes
### Description

If I set a binding on a control in code behind after a constant value has been set, the application crashes with an ArgumentException: An item with the same key has already been added. Key: Microsoft.Maui.Controls.SetterSpecificity (Parameter 'key')

This is new behavior in .NET 8 as I cannot reproduce this with .NET 7. We use this heavily in our quite large application with many user controls and for us it is almost a blocker for migration to .NET 8. There might be a workaround but it's difficult to spot all the instances this is happening. We are really looking forward to 8 as we are dealing with a lot of bugs in 7 that are really slowing us down.

### Steps to Reproduce

1. Create a File -> New MAUI App
2. Replace the content of OnCounterClicked in MainPage.xaml.cs with this:

```
// if CounterBtn already has a binding set on BackgroundColor, this sequence crashes immediately, otherwise it crashes the second time it's called
CounterBtn.BackgroundColor = Colors.Coral;            
CounterBtn.SetBinding(BackgroundColorProperty, new Binding(nameof(BackgroundColor), source: this));
```
4. Run the app (verified on Windows)
3. Click the "Click me" button twice. The second time the app will crash.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

All

### Did you find any workaround?

No. Even clearing the binding or setting the property to null doesn't help.

### Relevant log output

_No response_

### LINKED ISSUE #17832: Regression: AppThemeBinding and VisualStates results in "An item with the same key has already been added"
### Description

Something that was working in NET7, which do not work anymore in NET8.
Related to https://github.com/dotnet/maui/issues/16960

Combining Binding on a Control, the same binding in the Control's Triggers and setting a VisualState with AppThemeBinding results in the error: 
"An item with the same key has already been added. Key: Microsoft.Maui.Controls.SetterSpecificity (Parameter 'key')"

and the stack trace:
   at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
   at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.Setter.Apply(BindableObject target, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.VisualStateManager.GoToState(VisualElement visualElement, String name)
   at Microsoft.Maui.Controls.VisualElement.ChangeVisualState()
   at Microsoft.Maui.Controls.View.ChangeVisualState()
   at Microsoft.Maui.Controls.VisualElement.SetPointerOver(Boolean value, Boolean callChangeVisualState)
   at Microsoft.Maui.Controls.View.<CheckPointerOver>b__22_0(Boolean result)
   at Microsoft.Maui.Controls.PointerGestureRecognizer.<>c__DisplayClass61_0.<SetupForPointerOverVSM>b__0(Object s, PointerEventArgs e)
   at Microsoft.Maui.Controls.PointerGestureRecognizer.SendPointerEntered(View sender, Func`2 getPosition, PlatformPointerEventArgs platformArgs)
   at Microsoft.Maui.Controls.Platform.GesturePlatformManager.<>c__DisplayClass47_0.<OnPgrPointerEntered>b__0(View view, PointerGestureRecognizer recognizer)
   at Microsoft.Maui.Controls.Platform.GesturePlatformManager.HandlePgrPointerEvent(PointerRoutedEventArgs e, Action`2 SendPointerEvent)
   at Microsoft.Maui.Controls.Platform.GesturePlatformManager.OnPgrPointerEntered(Object sender, PointerRoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.Input.PointerEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)

### Steps to Reproduce

Paste the following XAML in an empty project's MainPage.xaml:

` <CheckBox x:Name="_checkBox" />
 <Entry Text="ABC"
        WidthRequest="120"
        IsReadOnly="{Binding IsChecked, Source={x:Reference _checkBox}}">
   <VisualStateManager.VisualStateGroups>
     <VisualStateGroupList>
       <VisualStateGroup>
         <VisualState x:Name="Normal" />
         <VisualState x:Name="PointerOver">
           <VisualState.Setters>
             <Setter Property="Background"
                     Value="{AppThemeBinding Dark=Green, Light=Red}" />
           </VisualState.Setters>
         </VisualState>
       </VisualStateGroup>
     </VisualStateGroupList>
   </VisualStateManager.VisualStateGroups>
   <Entry.Triggers>
     <DataTrigger TargetType="{x:Type Entry}"
                  Binding="{Binding IsChecked, Source={x:Reference _checkBox}}"
                  Value="True">
       <Setter Property="Background"
               Value="Green" />
     </DataTrigger>
   </Entry.Triggers>
 </Entry>`

-Run the application.
-Mouse Over the Entry and then mouse out
-Check the CheckBox
-Mouse Over the Entry and then mouse out
-Mouse Over the Entry and exception is raised

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

no

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change

We don't have a test for that

### Issues Fixed

- fixes #17357
- fixes #17391
- fixes #17427
- fixes #17832
- fixes #17776

### CODE REVIEW

File: src/Controls/src/Core/BindableObject.cs [hunk 1]
```diff
@@ -283,7 +283,7 @@ internal void SetBinding(BindableProperty targetProperty, BindingBase binding, S
 			{
 				var kvp = context.Values.Last();
 				context.Values.Remove(kvp.Key);
-				context.Values.Add(SetterSpecificity.FromBinding, kvp.Value);
+				context.Values[SetterSpecificity.FromBinding] = kvp.Value;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/BindableObject.cs:286]: To test it can use any Style with a Binding property?

**Review by PureWeen — APPROVED** [review]

File: src/Controls/src/Core/BindableObject.cs (hunk 1 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Core/BindableObject.cs:286]: In this case, without a test case, we do not know if the issue is related setter and style. that hypothesis was only me guessing. So I can't add a test for this issue as we don't know what the issue is.

What we have is a stack trace, and we can (and did) fix the code so that error no longer fire
