### PR TITLE
[Windows] Handle non-seekable streams in `PlatformImage.FromStream` (take 2)

### LINKED ISSUE #18954: [Windows] `PlatformImage.FromStream` crash
### Description

trying to get an image from the web as an IImage like this:

```
var imageUrl = "https://source.unsplash.com/random";
var stream = await new HttpClient().GetStreamAsync(imageUrl);
var img = PlatformImage.FromStream(stream);
```

crashes the app on Windows with the following Exception:

```
   at System.IO.WindowsRuntimeStreamExtensions.AsRandomAccessStream(Stream stream)
   at Microsoft.Maui.Graphics.Platform.PlatformImage.<>c__DisplayClass18_0.<<FromStream>b__0>d.MoveNext()
   at Microsoft.Maui.Graphics.Platform.AsyncPump.Run[T](Func`1 asyncMethod)
   at Microsoft.Maui.Graphics.Platform.PlatformImage.FromStream(Stream stream, ImageFormat format)
   at MyApp.Pages.MainPage.<OnMounted>d__6.MoveNext() in C:\dev\MyApp\MainPage.cs:line 64
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1914
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

`Cannot use the specified Stream as a Windows Runtime IRandomAccessStream because this Stream does not support seeking.`

Works fine on Android

Repro:
[MauiApp1.zip](https://github.com/dotnet/maui/files/13440716/MauiApp1.zip)

### Steps to Reproduce

1. create maui app
2. use PlatformImage.FromStream
3. run on windows

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by MartyIX**
Alternative to #23626. This PR uses the `RecyclableMemoryStreamManager` to decrease allocations.

### Description of Change

`AsRandomAccessStream` throws `NotSupportedException` when the stream is not seekable. This PR is a simple workaround for it.

The second commit adds an optimization. The idea is to remove `AsyncPump` (introduced in https://github.com/dotnet/Microsoft.Maui.Graphics/commit/45979232d6deb180c3988158cf8d98a5ecdd8f7f and merged to MAUI in https://github.com/dotnet/maui/pull/8739) which does not seem to be necessary at all. I have tested the change with parallel loading of images and it did not break for me. But then again I don't really know why `AsyncPump` was introduced in the first place. This commit is an alternative to #23624 approach and the improvement should be the same as in that PR: https://github.com/dotnet/maui/pull/23624#issue-2410733071 (9 seconds -> 1.3 seconds for a batch of images containing ~100 images).

### Test

Tested with provided sample code that reads images in parallel to make sure it works: https://gist.github.com/MartyIX/2513b1853ad8537a4d31b62c251115ad

animation

### Issues Fixed

Fixes #18954

### CODE REVIEW

File: src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs [hunk 1]
```diff
@@ -153,10 +154,38 @@ public IImage ToImage(int width, int height, float scale = 1f)
...
+			CanvasBitmap bitmap;
+
+			if (stream.CanSeek)
+			{
+				global::Windows.Foundation.IAsyncOperation<CanvasBitmap> bitmapAsync = CanvasBitmap.LoadAsync(creator, stream.AsRandomAccessStream());
+				bitmap = bitmapAsync.AsTask().GetAwaiter().GetResult();
+			}
+			else
+			{
+				byte[] bytes = ArrayPool<byte>.Shared.Rent(100 * 1024); // 100 kB.
```
Comment (jonathanpeppers) [inline src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs:172]: Can `stream.Length` be used here? Or will that throw an exception in some cases?

File: src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs [hunk 2]
```diff
@@ -153,10 +154,38 @@ public IImage ToImage(int width, int height, float scale = 1f)
...
+
+				try
+				{
+					using MemoryStream memoryStream = new(bytes);
+					stream.CopyTo(memoryStream);
+					memoryStream.Seek(0, SeekOrigin.Begin);
+
+					global::Windows.Foundation.IAsyncOperation<CanvasBitmap> bitmapAsync = CanvasBitmap.LoadAsync(creator, memoryStream.AsRandomAccessStream());
+					bitmap = bitmapAsync.AsTask().GetAwaiter().GetResult();
```
Comment (jonathanpeppers) [inline src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs:181]: This is certainly a bit better than just doing `new MemoryStream()` each time, and probably "good enough". If non-seekable streams didn't work at all before, I would go with this.

The only problematic part now:
1. Any image _larger_ than 100kb
2. `MemoryStream` will throw away the `byte[]` and create a new, larger one
3. `MemoryStream` might do this multiple times as it continues to read. I believe the behavior is it will keep creating new `byte[]` 2x larger each try.

File: src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs (hunk 1 above)
Comment (jonathanpeppers) [reply src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs:172]: Yeah, just a random web search, certain streams will throw `NotSupportedException`:
* https://stackoverflow.com/q/3373579

**Review by jonathanpeppers — DISMISSED** [review]
This looks good to me 👍, I triggered CI.

File: src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs (hunk 2 above)
Comment (jonathanpeppers) [reply src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs:181]: The only way I know is to recycle `MemoryStream` like we do here:
* https://github.com/dotnet/android-tools/blob/main/src/Microsoft.Android.Build.BaseTasks/MemoryStreamPool.cs

But this loses the benefit that `ArrayPool.Shared.Rent()` also shares the array pool with the BCL.

If I find another reason to bring over our `MemoryStreamPool`, I'll update this in the future to use it.

Comment (albyrock87) [reply src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs:181]: Is this an option we could evaluate?
https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream

Comment (jonathanpeppers) [reply src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs:181]: I saw that one (it showed up a few years after the Xamarin.Android one), but I haven't had a chance to try it.

I wonder if some of their default settings are suitable for mobile:
* https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/blob/e29a28387da9018fa9605a1dcb3f7a0435aa9974/src/RecyclableMemoryStreamManager.cs#L52

Either one would probably work for this case on Windows.

Comment (albyrock87) [reply src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs:181]: The issue is on windows here, so I was thinking about using this on `WINDOWS` only.

Comment (albyrock87) [reply src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs]: For the record: https://github.com/dotnet/runtime/issues/22428#issuecomment-1478585251

File: src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs [hunk 3]
```diff
@@ -153,10 +157,29 @@ public IImage ToImage(int width, int height, float scale = 1f)
...
 			if (creator == null)
+			{
 				throw new Exception("No resource creator has been registered globally or for this thread.");
+			}
+
+			CanvasBitmap bitmap;
+
+			if (stream.CanSeek)
+			{
+				global::Windows.Foundation.IAsyncOperation<CanvasBitmap> bitmapAsync = CanvasBitmap.LoadAsync(creator, stream.AsRandomAccessStream());
```
Comment (mattleibow) [inline src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs:170]:
```suggestion
				var bitmapAsync = CanvasBitmap.LoadAsync(creator, stream.AsRandomAccessStream());
```

File: src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs [hunk 4]
```diff
@@ -153,10 +157,29 @@ public IImage ToImage(int width, int height, float scale = 1f)
...
+				bitmap = bitmapAsync.AsTask().GetAwaiter().GetResult();
+			}
+			else
+			{
+				using var memoryStream = recyclableMemoryStreamManager.GetStream();
+				stream.CopyTo(memoryStream);
+				memoryStream.Seek(0, SeekOrigin.Begin);
+
+				global::Windows.Foundation.IAsyncOperation<CanvasBitmap> bitmapAsync = CanvasBitmap.LoadAsync(creator, memoryStream.AsRandomAccessStream());
```
Comment (mattleibow) [inline src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs:179]:
```suggestion
				var bitmapAsync = CanvasBitmap.LoadAsync(creator, memoryStream.AsRandomAccessStream());
```

File: eng/NuGetVersions.targets [hunk 5]
```diff
@@ -128,6 +128,10 @@
         Update="Microsoft.Extensions.Primitives"
         Version="$(MicrosoftExtensionsPrimitivesVersion)"
     />
+    <PackageReference
+        Update="Microsoft.IO.RecyclableMemoryStream"
+        Version="$(MicrosoftIoRecyclableMemoryStreamVersion)"
+    />
```
[the remark this answers is not in the document]
Comment (mattleibow) [reply eng/NuGetVersions.targets:134]: I think it is OK.

**Review by mattleibow — COMMENTED** [review]
This is looking good!

Is it possible to create a test for this? You can fake a readonly stream with something like this: https://github.com/mono/SkiaSharp/blob/main/tests/Tests/Utils/NonSeekableReadOnlyStream.cs

**Review by mattleibow — APPROVED** [review]
Amazing!
