### PR TITLE
[iOS & Mac] Fixed IndicatorView Size doesnt update dynamically

### LINKED ISSUE #31064: [iOS, Catalyst] IndicatorView.IndicatorSize does not update dynamically at runtime
### Description

The IndicatorSize property of IndicatorView does not reflect changes when updated dynamically at runtime on iOS.

| Expected Output | Actual Output |
|-----------------|---------------|
| <video width="200" height="150" controls src="https://github.com/user-attachments/assets/e7d347fd-cd89-4e1f-a6e3-a21d75af06a1"></video> | <video width="200" height="150" controls src="https://github.com/user-attachments/assets/d6ba6f2f-c9f2-4dfc-a4a6-cb4ddbe9ec94"></video>|

### Steps to Reproduce

1. Run the attached sample [IndicatorSizeSample.zip](https://github.com/user-attachments/files/21663573/IndicatorSizeSample.zip)
2. Change the IndicatorSize and observe the difference.

Expected Behavior:
The indicators in the IndicatorView should resize according to the value entered in the Entry at runtime.

Actual Behavior:
On iOS, the indicators remain at their initial size and do not reflect changes made at runtime.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.90 SR9

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

macOS, iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by SubhikshaSf4851**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause:
When the IndicatorSize changed, the layout wasn’t updated, so the new size didn’t appears

### Description of Change
Changed the UpdateIndicatorSize method in UIPageControlExtensions.cs to call InvalidateMeasure(), ensuring that the indicator view is properly remeasured and updated when its size changes.

### Issues Fixed

Fixes #31064 

### Tested the behaviour in the following platforms :

- [x] Windows
- [x] Android
- [x] iOS
- [x] mac

### Screenshot

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/891d33a7-6221-470f-9b9e-066512784296"> | <video src="https://github.com/user-attachments/assets/526f4058-85b9-4585-89ed-f665eba3b7d9"> |

### CODE REVIEW

File: src/Core/src/Platform/iOS/UIPageControlExtensions.cs [hunk 1]
```diff
@@ -19,7 +19,7 @@ public static void UpdateIndicatorShape(this MauiPageControl pageControl, IIndic
 		public static void UpdateIndicatorSize(this MauiPageControl pageControl, IIndicatorView indicatorView)
 		{
 			pageControl.IndicatorSize = indicatorView.IndicatorSize;
-			pageControl.LayoutSubviews();
+			pageControl.InvalidateMeasure();
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/UIPageControlExtensions.cs:22]: Here, can check if the size actually changed before calling `InvalidateMeasure()`.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/iOS/UIPageControlExtensions.cs (hunk 1 above)
Comment (SubhikshaSf4851) [reply src/Core/src/Platform/iOS/UIPageControlExtensions.cs:22]: @jsuarezruiz The UpdateIndicatorSize method is invoked through the mapper only, but the mapper won’t be triggered if the same value is set again. Please let me know if you have any other concerns.

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue31064.cs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+{
+	public Issue31064(TestDevice testDevice) : base(testDevice)
+	{
+	}
+
+	public override string Issue => "Indicator view size should update dynamically";
+
+	[Test]
+	[Category(UITestCategories.IndicatorView)]
+	public void Issue31064IndicatorViewSizeUpdatesDynamically()
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue31064.cs:17]: Pending snapshot on Windows:
image
Could you commit it?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue31064.cs (hunk 2 above)
Comment (SubhikshaSf4851) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue31064.cs:17]: @jsuarezruiz I have committed the snapshot

**Comment by rmarinho** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Updated windows snapshot</strong> · <a href="https://github.com/dotnet/maui/commit/489c2441b24edfb09900d2f662dd62ae9ef45d85"><code>489c244</code></a></summary>

---

**Issue:** #31064 - [iOS, Catalyst] IndicatorView.IndicatorSize does not update dynamically at runtime
**PR:** #31129 - [iOS & Mac] Fixed IndicatorView Size doesnt update dynamically
**Author:** SubhikshaSf4851 (community/Syncfusion partner)
**Platforms Affected:** iOS, MacCatalyst
**Files Changed:** 1 implementation file, 2 test files, 4 snapshot files

### Issue Summary
`IndicatorView.IndicatorSize` property does not reflect changes when updated dynamically at runtime on iOS/MacCatalyst. The indicators remain at their initial size. The issue was filed by a Syncfusion team member and marked as `s/verified`.

### Fix Summary
In `UIPageControlExtensions.cs`, `UpdateIndicatorSize` previously called `pageControl.LayoutSubviews()` synchronously. This updated the control internally but did not propagate the remeasure up to ancestor views in the MAUI layout hierarchy. The fix replaces this with `pageControl.InvalidateMeasure()`, which calls `SetNeedsLayout()` and then `InvalidateAncestorsMeasures()` to properly trigger a full re-layout cycle.

### Files Changed
- **Fix file**: `src/Core/src/Platform/iOS/UIPageControlExtensions.cs` (+1 -1)
- **Test HostApp**: `src/Controls/tests/TestCases.HostApp/Issues/Issue31064.cs` (+54)
- **Test Shared**: `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue31064.cs` (+23)
- **Snapshots**: iOS, Android, Mac, Windows (4 binary PNG files added)

### PR Discussion
| File:Line | Reviewer Says | Author Says | Status |
|-----------|---------------|-------------|--------|
| UIPageControlExtensions.cs:22 | "Check if size actually changed before calling `InvalidateMeasure()`" (jsuarezruiz) | "Mapper won't trigger if same value is set again, so check is redundant" (author) | ⚠️ UNRESOLVED thread |
| Issue31064.cs:17 | "Pending snapshot on Windows - can you commit it?" (jsuarezruiz) | "I have committed the snapshot" (author) | ✅ RESOLVED |

### Potential Concerns
- `UpdateIndicatorShape` still uses `pageControl.LayoutSubviews()` (unchanged) — possible inconsistency with `UpdateIndicatorSize` which now uses `InvalidateMeasure()`. Should `UpdateIndicatorShape` also use `InvalidateMeasure()`?
- Test's `[Issue]` attribute marks only `PlatformAffected.iOS`, but issue title and labels include both iOS and MacCatalyst.
- Test is screenshot-based (`VerifyScreenshot()`) - snapshot files are present for all platforms.

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #31129 | Replace `LayoutSubviews()` with `InvalidateMeasure()` in `UpdateIndicatorSize` | ⏳ PENDING (Gate) | `UIPageControlExtensions.cs` (+1 -1) | Original PR |

</details>

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Updated windows snapshot</strong> · <a href="https://github.com/dotnet/maui/commit/489c2441b24edfb09900d2f662dd62ae9ef45d85"><code>489c244</code></a></summary>

---

**Result:** ✅ PASSED
**Platform:** ios
**Mode:** Full Verification

- Tests FAIL without fix ✅ (issue is detected)
- Tests PASS with fix ✅ (fix works)

Test: `Issue31064IndicatorViewSizeUpdatesDynamically` (Category: IndicatorView)

</details>

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Updated windows snapshot</strong> · <a href="https://github.com/dotnet/maui/commit/489c2441b24edfb09900d2f662dd62ae9ef45d85"><code>489c244</code></a></summary>

---

# Fix Exploration Results

**Total Attempts:** 5  
**Passed:** 2 (PR fix confirmed via Gate + 2 alternatives)  
**Failed:** 3  

## Fix Candidates

| # | Model | Approach | Result | Notes |
|---|-------|----------|--------|-------|
| [Gate] | N/A | PR fix: `InvalidateMeasure()` only | ✅ PASS | Cleanest: 1 line. MAUI ancestor propagation via `InvalidateAncestorsMeasures()`. |
| 1 | claude-sonnet-4.5 | `UpdateIndicatorSize() + SetNeedsLayout() + Superview?.SetNeedsLayout()` | ✅ PASS | 3 lines. Applies transform explicitly then notifies parent via UIKit. Works but more verbose. |
| 2 | claude-opus | `Superview?.InvalidateMeasure()` in MauiPageControl | ❌ FAIL | 2.54% visual diff. Calling InvalidateMeasure on a UIView ancestor (not MauiPageControl itself) doesn't trigger the right path. |
| 3 | gpt-5.2 | `SetNeedsLayout()` only | ❌ FAIL | 2.54% visual diff. UIKit-only invalidation without MAUI ancestor propagation is insufficient. |
| 4 | gpt-5.2-codex | `SetNeedsLayout() + LayoutIfNeeded() + Superview?.SetNeedsLayout()` | ❌ FAIL | 2.54% visual diff. LayoutIfNeeded is synchronous but doesn't reach MAUI layout hierarchy. |
| 5 | gemini | `UpdateIndicatorSize() + InvalidateMeasure()` | ✅ PASS | 2 lines. Redundant: UpdateIndicatorSize is already called via LayoutSubviews inside InvalidateMeasure cycle. |

## Cross-Pollination Round

Three additional models were queried for new ideas. Model 1 suggested `InvalidateArrange()`, `SizeToFit()`, `Handler?.VirtualView?.InvalidateMeasure()`, etc. Models 2-3 indicated the solution space was adequately covered. No new viable alternatives identified.

## Best Fix Selection

**Selected: PR's fix (`InvalidateMeasure()`) is the optimal solution.**

Rationale:
- **Cleanest** (1 line vs 2-3 for alternatives)
- **Idiomatic** – uses the canonical MAUI invalidation path
- **Propagates correctly** – `InvalidateMeasure()` calls `SetNeedsLayout()` AND `InvalidateAncestorsMeasures()`, ensuring the full MAUI hierarchy re-measures
- **Gate confirmed** it passes the actual UI test
- No redundant operations (unlike Attempt 5 which applies transform twice)

The key insight: `InvalidateMeasure()` on a `UIView` (that doesn't implement `IPlatformMeasureInvalidationController`) falls into the `else` branch of `ViewExtensions.InvalidateMeasure()`, calling both `SetNeedsLayout()` and `InvalidateAncestorsMeasures()`. This walks up MAUI parent views calling `InvalidateMeasure(isPropagating: true)`, triggering a full re-measure that picks up the new indicator size.

## Pattern Learned

Fixes that only used UIKit APIs (`SetNeedsLayout`, `LayoutIfNeeded`) consistently failed (2.54% visual diff) because they don't reach the MAUI layout hierarchy. Any fix must involve the MAUI `InvalidateMeasure()` path to propagate layout invalidation up through MAUI parent views.

</details>

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Updated windows snapshot</strong> · <a href="https://github.com/dotnet/maui/commit/489c2441b24edfb09900d2f662dd62ae9ef45d85"><code>489c244</code></a></summary>

---

# PR #31129 Review Report

**PR:** [iOS & Mac] Fixed IndicatorView Size doesnt update dynamically  
**Issue:** #31064 – `[iOS, Catalyst] IndicatorView.IndicatorSize does not update dynamically at runtime`  
**Platforms:** iOS + MacCatalyst (fix) | Android + Windows (unaffected, snapshots only)

---

## Recommendation: ✅ APPROVE (with minor suggestions)

The fix is correct, minimal, and well-tested. Gate passed on iOS. All alternative fix approaches explored during try-fix confirmed that `InvalidateMeasure()` is the optimal solution.

---

## Phase 1: Pre-Flight

**Root cause confirmed:** `UIPageControlExtensions.UpdateIndicatorSize` called `LayoutSubviews()` after updating `IndicatorSize`. This applied the `CGAffineTransform` scale on the native control but did NOT propagate the size change up through the MAUI layout hierarchy. Parent views retained their stale measured size for the child, so the indicator dots appeared unchanged at runtime.

**Fix:** Replace `LayoutSubviews()` with `InvalidateMeasure()` (1-line change in `UIPageControlExtensions.cs`).

**Why `InvalidateMeasure()` works:** On a `UIView` that doesn't implement `IPlatformMeasureInvalidationController`, `InvalidateMeasure()` falls into the `else` branch of `ViewExtensions.InvalidateMeasure()`, calling both `SetNeedsLayout()` AND `InvalidateAncestorsMeasures()`. The latter walks up MAUI parent views calling `InvalidateMeasure(isPropagating: true)`, triggering a full re-measure cycle that picks up the new indicator size.

**Existing reviewer thread:** `jsuarezruiz` asked about adding a size-change guard. Author's response was correct — the mapper system prevents same-value calls. Thread is technically moot but remains unresolved in GitHub.

---

## Phase 2: Gate ✅ PASSED

**Platform:** iOS  
**Test:** `Issue31064IndicatorViewSizeUpdatesDynamically`  
**Category:** `UITestCategories.IndicatorView`

| Run | State | Result |
|-----|-------|--------|
| Baseline (revert fix) | `LayoutSubviews()` | ❌ FAIL – screenshot mismatch (indicators not resized) |
| With fix | `InvalidateMeasure()` | ✅ PASS |

Tests correctly fail without the fix and pass with the fix. Gate is fully validated.

---

## Phase 3: Try-Fix Exploration

5 alternative approaches explored. Key findings:

| Approach | Result | Notes |
|----------|--------|-------|
| PR fix: `InvalidateMeasure()` | ✅ PASS (Gate) | Cleanest, 1 line, idiomatic |
| `UpdateIndicatorSize() + SetNeedsLayout() + Superview?.SetNeedsLayout()` | ✅ PASS | 3 lines, more verbose |
| `UpdateIndicatorSize() + InvalidateMeasure()` | ✅ PASS | 2 lines, redundant transform |
| `Superview?.InvalidateMeasure()` | ❌ FAIL (2.54%) | Wrong target |
| `SetNeedsLayout()` only | ❌ FAIL (2.54%) | No MAUI ancestor propagation |
| `SetNeedsLayout() + LayoutIfNeeded() + Superview?.SetNeedsLayout()` | ❌ FAIL (2.54%) | UIKit-only, no MAUI hierarchy |

**Pattern:** Any fix that doesn't reach the MAUI ancestor hierarchy fails. The PR's `InvalidateMeasure()` is the simplest correct solution. The 3-line alternative (Attempt 1) also works but is redundant.

**Cross-pollination round:** 3 models queried. No new viable approaches identified beyond the 5 explored.

---

## Code Review (pr-finalize)

### 🟡 Suggestions (Non-blocking)

1. **`PlatformAffected` should include MacCatalyst**
   - `Issue31064.cs` HostApp: `PlatformAffected.iOS` → `PlatformAffected.iOS | PlatformAffected.MacCatalyst`
   - The PR title says `[iOS & Mac]` and a Mac snapshot is included, but the attribute only marks iOS

2. **`UpdateIndicatorShape` inconsistency**
   - `UpdateIndicatorShape` in the same file still calls `LayoutSubviews()` directly
   - If `IndicatorShape` changes at runtime, the same bug may manifest
   - Recommend a follow-up PR to apply the same fix

3. **Title grammar**
   - "Fixed IndicatorView Size doesnt update dynamically" → "IndicatorView: Fix IndicatorSize not updating dynamically at runtime"

4. **Missing newlines** at end of both new test files (cosmetic)

### ✅ Looks Good

- Fix is minimal and correct (1 line)
- `InvalidateMeasure()` is the idiomatic MAUI invalidation API
- Snapshots provided for all 4 platforms
- No breaking changes
- UI test design is sound and provides clear regression coverage

---

## Summary

| Phase | Result |
|-------|--------|
| Pre-Flight | ✅ Complete |
| Gate (iOS) | ✅ PASSED |
| Try-Fix | ✅ Complete (PR fix confirmed as optimal) |
| Code Review | ✅ Minor suggestions only |

**Final recommendation: APPROVE.** The fix is correct, minimal, well-tested, and has been empirically validated both in Gate and through exploration of 5 alternative approaches. Minor suggestions (PlatformAffected, follow-up for UpdateIndicatorShape) are non-blocking.

</details>

</details>

---

</details>



<details>
<summary><b>🔧 Try-Fix Analysis: ✅ 2 passed, ❌ 3 failed</b></summary><br>
<details>
<summary>✅ Fix 1</summary>

## Approach 1: Apply Transform in MauiPageControl and Use SetNeedsLayout on Parent

Instead of fixing in UIPageControlExtensions.UpdateIndicatorSize (extension method), fix directly in MauiPageControl by:
1. Calling `UpdateIndicatorSize()` (the method on MauiPageControl) immediately after setting IndicatorSize in the extension
2. Calling `pageControl.SetNeedsLayout()` to schedule a layout pass

**Different from PR's fix:** PR uses `InvalidateMeasure()` which propagates up through the MAUI hierarchy.
This approach calls `UpdateIndicatorSize()` immediately (no waiting for LayoutSubviews) AND also calls SetNeedsLayout() for a follow-up. We additionally call `pageControl.Superview?.SetNeedsLayout()` to make the parent also re-layout.

Key difference: We directly apply the CGAffineTransform immediately (sync) instead of waiting for the async layout cycle.


```diff
diff --git a/src/Core/src/Platform/iOS/UIPageControlExtensions.cs b/src/Core/src/Platform/iOS/UIPageControlExtensions.cs
index a89bdf1d92..902373536d 100644
--- a/src/Core/src/Platform/iOS/UIPageControlExtensions.cs
+++ b/src/Core/src/Platform/iOS/UIPageControlExtensions.cs
@@ -19,7 +19,9 @@ namespace Microsoft.Maui.Platform
 		public static void UpdateIndicatorSize(this MauiPageControl pageControl, IIndicatorView indicatorView)
 		{
 			pageControl.IndicatorSize = indicatorView.IndicatorSize;
-			pageControl.LayoutSubviews();
+			pageControl.UpdateIndicatorSize();
+			pageControl.SetNeedsLayout();
+			pageControl.Superview?.SetNeedsLayout();
 		}
 
 		public static void UpdateHideSingle(this UIPageControl pageControl, IIndicatorView indicatorView)

```
## Analysis: Approach PASSED 

The fix works because calling `pageControl.UpdateIndicatorSize()` directly applies the `CGAffineTransform` scale immediately (synchronously), 
without waiting for the layout cycle. Combined with `SetNeedsLayout()` on both the page control and its superview, 
the parent layout is triggered to redraw.

**Why it worked:** `MauiPageControl.UpdateIndicatorSize()` computes `(float)IndicatorSize / DefaultIndicatorSize` and applies a CGAffineTransform. 
Calling this directly means the transform is applied immediately before the screenshot is taken. The `SetNeedsLayout()` calls 
ensure the view hierarchy refreshes properly.

**Comparison to PR fix:** The PR uses `InvalidateMeasure()` which propagates through the full MAUI hierarchy (SetNeedsLayout + ancestors). 
This approach is more targeted - it applies the transform immediately AND notifies the direct parent.

**Potential concern:** This approach calls `UpdateIndicatorSize()` immediately AND also calls `SetNeedsLayout()` which will call `LayoutSubviews()` 
again async (which will call `UpdateIndicatorSize()` a second time). Minor redundancy. The PR fix is cleaner.

</details>

<details>
<summary>❌ Fix 2</summary>

## Approach 2: Fix in MauiPageControl.LayoutSubviews() - Notify superview after transform change

Instead of fixing the extension method, make `MauiPageControl.LayoutSubviews()` notify the MAUI layout system
after applying the transform. When the transform changes, call `this.InvalidateMeasure()` on the superview
to propagate the measure invalidation up.

**Different from PR fix and Attempt 1:** This puts the fix inside MauiPageControl itself,
making the control self-aware of when it changes size and automatically notifying the layout system.
The extension method stays as-is (with LayoutSubviews() call).


```diff
diff --git a/src/Core/src/Platform/iOS/MauiPageControl.cs b/src/Core/src/Platform/iOS/MauiPageControl.cs
index 66dfa2f845..8fd35408c3 100644
--- a/src/Core/src/Platform/iOS/MauiPageControl.cs
+++ b/src/Core/src/Platform/iOS/MauiPageControl.cs
@@ -70,6 +70,7 @@ namespace Microsoft.Maui.Platform
 			var newTransform = CGAffineTransform.MakeScale(scale, scale);
 
 			Transform = newTransform;
+			Superview?.InvalidateMeasure();
 		}
 
 		public void UpdatePosition()

```
## Analysis:  (2.54% visual difference in screenshot)FAILED 

Calling `Superview?.InvalidateMeasure()` from within `MauiPageControl.UpdateIndicatorSize()` causes a different visual result.
The screenshot was 2.54% different from the baseline. This suggests the layout settles differently.

**Why it failed:** Calling `InvalidateMeasure()` on the superview after applying the transform doesn't go through the same
MAUI layout propagation as calling `pageControl.InvalidateMeasure()` on the page control itself.
The PR fix calls `InvalidateMeasure()` ON the page control, which then calls `SetNeedsLayout()` + propagates to ancestors.
This approach calls `InvalidateMeasure()` on the SUPERVIEW, which skips the self-invalidation step.
The visual result differs slightly, possibly due to different layout settle timing.

**Learning:** The fix needs to be applied to the page control itself (not just the superview) to ensure proper propagation.

</details>

<details>
<summary>❌ Fix 3</summary>

## Approach 3: SetNeedsLayout only (no MAUI propagation)

Replace LayoutSubviews() with just SetNeedsLayout() in UpdateIndicatorSize extension.
This schedules the layout in the next run loop without the overhead of propagating through the MAUI hierarchy.

**Different from PR fix:** PR uses InvalidateMeasure() which propagates to ancestors.  
This approach only calls SetNeedsLayout() on the control itself - minimal change.
**Different from Attempt 1:** No direct UpdateIndicatorSize() call.
**Different from Attempt 2:** No ancestor invalidation.


```diff
diff --git a/src/Core/src/Platform/iOS/UIPageControlExtensions.cs b/src/Core/src/Platform/iOS/UIPageControlExtensions.cs
index a89bdf1d92..3d246b4131 100644
--- a/src/Core/src/Platform/iOS/UIPageControlExtensions.cs
+++ b/src/Core/src/Platform/iOS/UIPageControlExtensions.cs
@@ -19,7 +19,7 @@ namespace Microsoft.Maui.Platform
 		public static void UpdateIndicatorSize(this MauiPageControl pageControl, IIndicatorView indicatorView)
 		{
 			pageControl.IndicatorSize = indicatorView.IndicatorSize;
-			pageControl.LayoutSubviews();
+			pageControl.SetNeedsLayout();
 		}
 
 		public static void UpdateHideSingle(this UIPageControl pageControl, IIndicatorView indicatorView)

```
## Analysis:  (2.54% visual difference)FAILED 

SetNeedsLayout() alone is insufficient. The visual output differs by 2.54% from the snapshot.

**Why it failed:** SetNeedsLayout() schedules an async layout pass that applies the Transform, 
but it does NOT propagate to MAUI ancestors. The parent view doesn't know the child changed size 
and doesn't remeasure, so the indicator view doesn't get proper space allocation.

**Learning:** The fix MUST include ancestor propagation. SetNeedsLayout() on the control alone is not enough.
The MAUI ancestor remeasure (InvalidateAncestorsMeasures()) is critical to get the right layout.

</details>

<details>
<summary>❌ Fix 4</summary>

## Approach 4: Explicit LayoutSubviews on superview after SetNeedsLayout

Call SetNeedsLayout() on the page control AND call LayoutIfNeeded() to force the layout synchronously,
then call SetNeedsLayout() on the superview to trigger parent re-layout.

This is different from the PR fix (which uses InvalidateMeasure with ancestor propagation)
and different from attempt 1 (which calls UpdateIndicatorSize directly).

The key idea: force a synchronous layout pass using LayoutIfNeeded(), 
then trigger the parent to also update via Superview.SetNeedsLayout().


```diff
diff --git a/src/Core/src/Platform/iOS/UIPageControlExtensions.cs b/src/Core/src/Platform/iOS/UIPageControlExtensions.cs
index a89bdf1d92..f19f2009c5 100644
--- a/src/Core/src/Platform/iOS/UIPageControlExtensions.cs
+++ b/src/Core/src/Platform/iOS/UIPageControlExtensions.cs
@@ -19,7 +19,9 @@ namespace Microsoft.Maui.Platform
 		public static void UpdateIndicatorSize(this MauiPageControl pageControl, IIndicatorView indicatorView)
 		{
 			pageControl.IndicatorSize = indicatorView.IndicatorSize;
-			pageControl.LayoutSubviews();
+			pageControl.SetNeedsLayout();
+			pageControl.LayoutIfNeeded();
+			pageControl.Superview?.SetNeedsLayout();
 		}
 
 		public static void UpdateHideSingle(this UIPageControl pageControl, IIndicatorView indicatorView)

```
## Analysis:  (2.54% visual difference)FAILED 

SetNeedsLayout() + LayoutIfNeeded() + Superview.SetNeedsLayout() still produces 2.54% difference.

**Why it failed:** Even with synchronous layout (LayoutIfNeeded()), the MAUI ancestor propagation is missing.
The superview's SetNeedsLayout() schedules layout but since it's not going through InvalidateMeasure,
the MAUI layout engine doesn't do a full remeasure of the parent.

**Key insight:** The 2.54% difference seems to be a consistent visual artifact when MAUI ancestor
propagation is missing. The only approaches that work are those that go through InvalidateMeasure()
which calls InvalidateAncestorsMeasures().

</details>

<details>
<summary>✅ Fix 5</summary>

## Approach 5: Apply transform directly then call InvalidateMeasure (two-phase approach)

Apply the Transform directly in the extension method (bypassing LayoutSubviews cycle for immediate effect),
then call InvalidateMeasure() to propagate to ancestors - but this time do it with proper coding.

Key difference from PR fix: We call MauiPageControl.UpdateIndicatorSize() (to apply Transform immediately)
before calling InvalidateMeasure(). The PR just calls InvalidateMeasure() and lets the transform be 
applied asynchronously in the next LayoutSubviews cycle.

This eliminates any visual delay and makes the layout more predictable.
Different from Attempt 1: No Superview?.SetNeedsLayout() extra call.


```diff
diff --git a/src/Core/src/Platform/iOS/UIPageControlExtensions.cs b/src/Core/src/Platform/iOS/UIPageControlExtensions.cs
index a89bdf1d92..2f240029d1 100644
--- a/src/Core/src/Platform/iOS/UIPageControlExtensions.cs
+++ b/src/Core/src/Platform/iOS/UIPageControlExtensions.cs
@@ -19,7 +19,8 @@ namespace Microsoft.Maui.Platform
 		public static void UpdateIndicatorSize(this MauiPageControl pageControl, IIndicatorView indicatorView)
 		{
 			pageControl.IndicatorSize = indicatorView.IndicatorSize;
-			pageControl.LayoutSubviews();
+			pageControl.UpdateIndicatorSize();
+			pageControl.InvalidateMeasure();
 		}
 
 		public static void UpdateHideSingle(this UIPageControl pageControl, IIndicatorView indicatorView)

```
## Analysis: PASSED 

Applying UpdateIndicatorSize() directly (for immediate transform) + InvalidateMeasure() for ancestor propagation works.

**Why it works:** The approach has two phases:
1. Apply the Transform immediately via UpdateIndicatorSize() - ensures visual update is instant
2. Call InvalidateMeasure() which calls SetNeedsLayout() + propagates to MAUI ancestors

**Comparison to PR fix:** The PR fix only calls InvalidateMeasure() (1 line). 
This approach calls UpdateIndicatorSize() first (applies transform immediately) then InvalidateMeasure()
(applies it again asynchronously + propagates ancestors). The transform is applied twice but idempotent.

**Conclusion:** More complex than the PR fix with no real benefit - the extra UpdateIndicatorSize() call
is redundant since InvalidateMeasure()->SetNeedsLayout()->LayoutSubviews() will call it again anyway.
PR fix is simpler and equally correct.

</details>

</details>



<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

---

<details>

<summary><b>Title: ✅ Good</b></summary>

<br>

**Current:** `[iOS & Mac] Fixed IndicatorView Size doesnt update dynamically`
</details>

<details>

<summary><b>Description: ⚠️ Needs Update</b></summary>

<br>

- Grammar error: "doesnt" → "doesn't"
- Tense: "Fixed" should be "Fix" (imperative is standard for commit messages)
- Platform tag: `[iOS & Mac]` is non-standard — use `[iOS]` since the fix is in `Platform/iOS/` (which covers both iOS and MacCatalyst by convention)
### ✨ Suggested PR Description


> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause

When `IndicatorSize` changes at runtime on iOS/MacCatalyst, `UpdateIndicatorSize` was calling `pageControl.LayoutSubviews()` directly. This is a UIKit-level layout pass that only affects the native view's internal subview layout — it does not propagate the size change through the MAUI layout system. As a result, the parent view was never told the IndicatorView's desired size had changed, so the visual size remained stale.

### Description of Change

In `UIPageControlExtensions.cs`, replaced the `LayoutSubviews()` call in `UpdateIndicatorSize` with `InvalidateMeasure()`. This correctly signals the MAUI layout engine to re-measure and re-arrange the indicator view, ensuring the updated `IndicatorSize` is reflected in the UI.

**File changed:** `src/Core/src/Platform/iOS/UIPageControlExtensions.cs`

```csharp
// Before
pageControl.LayoutSubviews();

// After
pageControl.InvalidateMeasure();
```

This is an iOS/MacCatalyst-only change — the same code path handles both platforms since `.iOS.cs` files compile for both.

### Issues Fixed

Fixes #31064

### Platforms Tested

The fix applies to iOS and MacCatalyst. UI tests run cross-platform and snapshot baselines have been added for all platforms.

- [x] iOS
- [x] Mac Catalyst
- [ ] Android (not affected by this change)
- [ ] Windows (not affected by this change)
</details>

<details>

<summary><b>Code Review: ✅ Passed</b></summary>

<br>

# Code Review — PR #31129

## 🟡 Suggestions

### 1. `UpdateIndicatorShape` still uses `LayoutSubviews()` — potential inconsistency

**File:** `src/Core/src/Platform/iOS/UIPageControlExtensions.cs`

The same `UIPageControlExtensions` class has an `UpdateIndicatorShape` method that still calls `LayoutSubviews()` directly:

```csharp
public static void UpdateIndicatorShape(this MauiPageControl pageControl, IIndicatorView indicatorView)
{
    pageControl.IsSquare = !indicatorView.IsCircleShape();
    pageControl.LayoutSubviews();  // ← same pattern as the bug being fixed
}
```

If the fix for `UpdateIndicatorSize` is to use `InvalidateMeasure()` because `LayoutSubviews()` bypasses the MAUI layout system, then `UpdateIndicatorShape` likely has the same issue when shape changes at runtime. Consider updating it for consistency, or confirm it isn't affected (e.g., if shape changes don't alter the measured size).

---

### 2. `[Issue]` attribute marks `PlatformAffected.iOS` only — issue also affects MacCatalyst

**File:** `src/Controls/tests/TestCases.HostApp/Issues/Issue31064.cs` (line 3)

```csharp
[Issue(IssueTracker.Github, "31064", "Indicator view size should update dynamically", PlatformAffected.iOS)]
```

The issue title and description in GitHub (#31064) explicitly mention both iOS and Catalyst. Marking only `PlatformAffected.iOS` may cause the test to be skipped on MacCatalyst. Consider using `PlatformAffected.iOS | PlatformAffected.macOS` (or the appropriate MacCatalyst constant) if the test should also validate the fix on Mac.

---

### 3. Missing newline at end of test files

**Files:**
- `src/Controls/tests/TestCases.HostApp/Issues/Issue31064.cs`
- `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue31064.cs`

Both files are missing a trailing newline (`\ No newline at end of file` in the diff). This is a minor style issue but common in the repo — add a newline to the last line of each file.

---

## ✅ Looks Good

- **Core fix is minimal and correct.** Replacing `LayoutSubviews()` with `InvalidateMeasure()` is the right approach — it routes the size change through the MAUI measure/arrange cycle instead of bypassing it at the UIKit layer.
- **UI test covers the scenario.** The test taps the button to trigger a runtime `IndicatorSize` change and verifies via screenshot — this directly validates the fix.
- **Snapshot images added for all platforms.** iOS, Mac, Android, and Windows baselines are committed, which prevents future snapshot test failures.
- **Review comment about duplicate calls was addressed.** The reviewer's concern about checking if size changed before calling `InvalidateMeasure()` was correctly dismissed — the mapper only fires on value changes, so redundant calls aren't a problem.
</details>

---

</details>

**Review by kubaflo — APPROVED** [review]
