### PR TITLE
[C] fix a leak in VSG

### LINKED ISSUE #21389: Memoryleak VisualstateManager in ButtonStyle on Android
### Description

When creating an explicite Button Style in Styles.xaml like this.

` <Style x:Key="MyButtonStyle" TargetType="Button">
     <Setter Property="VisualStateManager.VisualStateGroups">
         <VisualStateGroupList>
             <VisualStateGroup x:Name="CommonStates">
                 <VisualState x:Name="Normal" />
                 <VisualState x:Name="Pressed">
                 </VisualState>
                 <VisualState x:Name="Disabled">
                 </VisualState>
             </VisualStateGroup>
         </VisualStateGroupList>
     </Setter>
 </Style>`

And referencing it on any ContentenPage like this
`<Button 
    x:Name="PART_MyButton"
    Style="{StaticResource MyButtonStyle}"
    Text="Welcome to .NET MAUI!"
    VerticalOptions="Center" 
    HorizontalOptions="Center" />`

The ContentPage never get garbage collected on Android.

### Steps to Reproduce

1. Checkout the code
2. Start the App on Android
3. Navigate to Leak by pressing Button "Leak"
4. Navigate back
5. Hit GC Button multiple Time to force GC

### Link to public reproduction project repository

https://github.com/Larhei/Maui-Issues/tree/main/VisualStateLeak

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

Moving the Style to ContentPage.Resources will stop the leak, but with will force me to copy my styles in multiple locations.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change

[C] fix a leak in VSG

### Issues Fixed

- fixes #21389

### CODE REVIEW

File: src/Controls/src/Core/VisualStateManager.cs [hunk 1]
```diff
@@ -378,7 +379,7 @@ public VisualStateGroup()
 		/// <include file="../../docs/Microsoft.Maui.Controls/VisualStateGroup.xml" path="//Member[@MemberName='CurrentState']/Docs/*" />
 		public VisualState CurrentState { get; internal set; }
 
-		internal VisualElement VisualElement { get; set; }
+		internal WeakReference<VisualElement> VisualElement { get; set; }
```
Comment (jonathanpeppers) [inline src/Controls/src/Core/VisualStateManager.cs:382]: Just an idea to make the code cleaner, you could keep the property unchanged and make the backing field a `WeakReference<VisualElement>`. Then the property getter could do null check and `TryGetValue()`.

File: src/Controls/src/Core/AdaptiveTrigger.cs [hunk 2]
```diff
@@ -61,7 +61,7 @@ void AttachEvents()
 		{
 			DetachEvents();
 
-			_visualElement = VisualState?.VisualStateGroup?.VisualElement;
+			VisualState?.VisualStateGroup?.VisualElement.TryGetTarget(out _visualElement);
```
Comment (jonathanpeppers) [inline src/Controls/src/Core/AdaptiveTrigger.cs:64]: Does this need a null check for `VisualElement` here?

**Review by jonathanpeppers — DISMISSED** [review]
Just had some minor comments. Overall, looks good. 👍

**Review by mattleibow — APPROVED** [review]
