### PR TITLE
[iOS] Tab Selected Icon Color not changing if using Font icons - fix

### LINKED ISSUE #8244: IOS: Custom font icon is not rendered in a shell tabbar tab
### Description

Did attach some screenshots and a code sample. 
 
android_emul_sample
Screenshot 2022-06-22 at 16 52 40

[MauiApp3.zip](https://github.com/dotnet/maui/files/8959517/MauiApp3.zip)

### Steps to Reproduce

1. It's all in the sample code.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #12250: (Un)SelectedTabColor do not work for TabbedPage icons (FontImageSource) on iOS
### Description

When using a font (FontImageSource) for tab icon, TabbedPage does not apply (Un)SelectedTabColor properties, on iOS.
However, the colors are properly applied to tab titles. 
Also, no issue when using an image (png) for the icon.
No issue on Android.

On this example, Tab1 uses an image, Tab2 uses a font:
Screenshot_1671633286

Similar issues:
https://github.com/dotnet/maui/issues/6043
https://github.com/dotnet/maui/issues/6718
https://github.com/xamarin/Xamarin.Forms/issues/8556

### Steps to Reproduce

1. Create a maui app, both for android and ios
2. Add a TabbedPage, and use either image or font for tab icons.
3. Set (Un)SelectedTabColor properties on TabbedPage
4. Observe colors, both on android and ios, both for image and font icons.

### Link to public reproduction project repository

https://github.com/tranb3r/Issues/tree/main/MauiAppTabbedPageIconColor

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1

### Did you find any workaround?

Use an image instead of a font.

### Relevant log output

_No response_

### LINKED ISSUE #20866: Font Icons in Shell Tabs not showing in iOS
### Description

Font Icons are not showing in iOS builds in Shell Tabs but they are working in Android - this is the same issue as reported in #4774

### Steps to Reproduce

Create MAUI app
Add relevant icon ttf file to app
Create shell, add icons to tabs via tabbar
Run on iOS local device

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

6.0

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

Setting the FontImageSource Colour works but then it would need updating on selection to have selected and unselected different colours

### Relevant log output

_No response_

### LINKED ISSUE #22032: iOS : Shell FlyoutItem Tab Selected Icon Color not changing if using Font icons
### Description

Shell FlyoutItem Tab Selected Icon Color not changing if using Font image source in iOS.
Only the Title color is changing 

### Steps to Reproduce

Shell FlyoutItem Tab Selected Icon Color not changing if using Font image source in iOS.
Only the Title color is changing 

### Link to public reproduction project repository

na

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS All versions

### Did you find any workaround?

No

### Relevant log output

```shell
na
```

### LINKED ISSUE #23174: TabbedPage doesn't change icon colour
### Description

The TabbedPage doesn't change the icon colour as the tabs are selected/unselected. The title text changes ok.

Using a PNG, instead of an Icon works too, and the colour changes in sync with the title text.

This was working on Xamarin.Forms and works on Android .NET Maui with some tweaks.

### Steps to Reproduce

Create a new maui app.
Add fontawesome
Add a tabbed page with content and set the title and icon for each.
See reproduction project for details.

### Link to public reproduction project repository

https://github.com/richaplinvs/reproduction-projects/tree/main/maui/TabbedSelectionIssue

### Version with bug

9.0.0-preview.4.10690

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 17.4, Android Api 33

### Did you find any workaround?

On Android changing the position of the toolbar: 

    On<Microsoft.Maui.Controls.PlatformConfiguration.Android>().SetToolbarPlacement(ToolbarPlacement.Bottom);

or  tab colours:

    UnselectedTabColor = Colors.Red;
    SelectedTabColor = Colors.Orange;
    BarBackgroundColor = Colors.HotPink;

On iOS use the OnAppearing/OnDisappearing in each of the tabs content page to set the colour. This requires creating a new instance of FontImageSource each time because the Color property cannot be set on it's own.

    var IconImage = new FontImageSource() { FontFamily = "FontAwesomeProSolid", Glyph = FontAwesome.FontAwesomeIcons.Pencil, Size = 25, Color = Colors.Gray };         
    if(selectedTab)
    {
        IconImage.Color = Colors.Red;
    }
    IconImageSource = IconImage;

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Description

In iOS development, `UIImage.RenderingMode` is an enumeration used to define how images are rendered when drawn on the screen. Here are the main rendering modes provided by UIImage:

`.automatic`:
- This is the default mode. The system automatically determines how to render the image based on the context.
- Typically, it will render template images in a way that they can adapt to different color styles, such as when used in navigation bars, tab bars, and buttons. If the image has an alpha channel, it may use a tint color.
- If the image does not have an alpha channel or is not marked as a template image, it will render the original image.

`.alwaysOriginal`:
- This mode renders the image as it is, without applying any modifications like tint color.
- It's useful when you want to display the image in its original form, regardless of where it's used.
- For example, if you have an icon with specific colors that you want to remain unchanged when placed in a button or tab bar, you should use .alwaysOriginal.

`.alwaysTemplate`:

- This mode treats the image as a template, meaning that the image will be rendered using the tint color provided by the view it's displayed in.
- It's commonly used for icons in toolbars, tab bars, or buttons where you want the icon to adopt the tint color of the control (e.g., to match the app's theme or user-selected appearance).
- For example, if you set an image view's tintColor to red, an image with .alwaysTemplate will render in red.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/22032
Fixes https://github.com/dotnet/maui/issues/12250
Fixes https://github.com/dotnet/maui/issues/20866
Fixes https://github.com/dotnet/maui/issues/23174
Fixes https://github.com/dotnet/maui/issues/8244
Closes https://github.com/dotnet/maui/pull/24721

|Before|After|
|--|--|
|<video src="https://github.com/dotnet/maui/assets/42434498/060058ab-659d-4cc7-8c7d-f43b5f76db63" width="300px"/>|<video src="https://github.com/dotnet/maui/assets/42434498/fb3d2b77-e55b-4be9-8f80-444d7b150dd7" width="300px"/>|

### CODE REVIEW

File: src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs [hunk 1]
```diff
@@ -38,7 +38,7 @@ public static partial class ImageSourceExtensions
 			var image = UIGraphics.GetImageFromCurrentImageContext();
 			UIGraphics.EndImageContext();
 
-			return image.ImageWithRenderingMode(UIImageRenderingMode.AlwaysOriginal);
+			return image.ImageWithRenderingMode(UIImageRenderingMode.Automatic);
```
Comment (PureWeen) [inline src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs:41]: @mattleibow thoughts?

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22032.cs [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+		[Test]
+		[Category(UITestCategories.TabbedPage)]
+		public async Task SelectedTabIconShouldChangeColor()
+		{
+			App.WaitForElement("button");
+
+			App.Click("button");
+
+			await Task.Delay(500);
```
Comment (PureWeen) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22032.cs:21]: instead of a delay can we `WaitForElement` on a control inside the switched tab?

Comment (kubaflo) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22032.cs:21]: Sure!

**Review by PureWeen — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]
