### PR TITLE
 [Android] Editor and Entry don't update placeholder and text color on theme change - fix

### LINKED ISSUE #30602: [Android] Editor and Entry don't update placeholder and text color on theme change
### Description

When switching between light and dark theme at runtime, the Editor and Entry controls do not update their placeholder or text colors to reflect the new theme. This leads to readability issues, such as light text on a light background or dark text on a dark background.

### Steps to Reproduce

1. Use Editor and Entry controls in a .NET MAUI app.
2. Run the app in light mode and observe the text and placeholder colors.
3. Change the app's theme to dark mode at runtime using App.Current.UserAppTheme = AppTheme.Dark;
4. Observe that the text and placeholder colors do not update accordingly.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.82 SR8.2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

_No response_

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/30602

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/3e26317c-f6da-4caa-882b-f7773da6a432" width="300px"></video>|<video src="https://github.com/user-attachments/assets/f3ee2774-fdb8-4a52-a82f-594462fda828" width="300px"></video>|

### CODE REVIEW

File: src/Controls/src/Core/InputView/InputView.cs [hunk 1]
```diff
@@ -71,6 +71,27 @@ internal InputView()
...
 		}
 
+		private protected override void OnHandlerChangingCore(HandlerChangingEventArgs args)
+		{
+			base.OnHandlerChangingCore(args);
+
+			if (Application.Current is null)
+				return;
+
+			if (args.NewHandler is null)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/InputView/InputView.cs]: You're only unsubscribing when NewHandler is null, but you should unsubscribe whenever there's an OldHandler

```
if (args.OldHandler is not null)
        Application.Current.RequestedThemeChanged -= OnRequestedThemeChanged;
```

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue30603.cs [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+	public override string Issue => "[Android] Editor and Entry don't update placeholder and text color on theme change";
+
+	[Test]
+	[Category(UITestCategories.Editor)]
+	[Category(UITestCategories.Entry)]
+	public void EditorAndEntryInputFieldsShouldChangeColorsOnAppThemeChange()
+	{
+		App.WaitForElement("changeThemeButton");
+		App.Tap("changeThemeButton");
+		VerifyScreenshot();
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue30603.cs:20]: Could be also interesting to modify the test to set the system theme.
Can do it using https://github.com/dotnet/maui/blob/7d232dc0b6028c470dc5aa486516ca76a9fd95ce/src/TestUtils/src/UITest.Appium/HelperExtensions.cs#L1677

File: src/Core/src/Platform/Android/EditTextExtensions.cs [hunk 3]
```diff
@@ -41,10 +42,18 @@ public static void UpdateTextColor(this EditText editText, ITextStyle entry)
...
 		public static void UpdateTextColor(this EditText editText, Graphics.Color textColor)
 		{
-			if (textColor != null)
+			if (textColor is not null && PlatformInterop.CreateEditTextColorStateList(editText.TextColors, textColor.ToPlatform()) is ColorStateList c)
+				editText.SetTextColor(c);
+			else
 			{
-				if (PlatformInterop.CreateEditTextColorStateList(editText.TextColors, textColor.ToPlatform()) is ColorStateList c)
-					editText.SetTextColor(c);
+				var typedValue = new TypedValue();
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/EditTextExtensions.cs:50]: Can you include a couple of comments here? Like, `// Fallback to system default color`

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

**Review by jfversluis — APPROVED** [review]
