### PR TITLE
Fix NullReferenceException when binding to Dictionary<Enum, object> with x:DataType

### LINKED ISSUE #13856: MAUI - XAML - Object reference not set to an instance of an object - reproducable, not same as #8249
### Description

If you have a Dictionary with an self created enum as key, and try to bind this to an entry element in xaml, you can not start this app, nor does the intellisense nor the compiler give you any meaningful errormessage, you only get a "Object reference not set to an instance of an object" in the error list.

If you change from Dictionary<yourEnum, yourObject> to Dictionary<string, yourObject> it runs like a charme.

### Steps to Reproduce

1. Create a new .NET Maui 7.0 Project in Visual Studio 2022
2. Add a public enum to the mainpage.xaml.cs:
public enum UserSetting
    {
        BrowserInvisible,
        GlobalWaitForElementsInBrowserInSek,
        TBD,

    }
3. Add a public Dictionary<yourEnum, typeYouLike> to the mainpage.xaml.cs
private Dictionary<UserSetting, object> _userSettings;

    public Dictionary<UserSetting, object> UserSettings
    {
        get { return _userSettings; }
        set
        {
            _userSettings = value;
        }
    }
4. Initialize your Dictionary in the mainpage constructor:
public MainPage()
	{
        UserSettings = new Dictionary<UserSetting, object>
        {
            { UserSetting.TBD, "pups" }
        };

        InitializeComponent();
        
        BindingContext = this;
        
    }
5. Add the DataType to the contentpage of the mainpage.xaml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestXamlBindings.MainPage"
             xmlns:settings="clr-namespace:TestXamlBindings"
             x:DataType="settings:MainPage">
6. Add an "entry" element somewhere on the mainpage.xaml with Text bound to the Dictionary:
<Entry AutomationId="GlobalWaitForElementsInBrowserInSek"
                       Text="{Binding UserSettings[TBD]}"
                       ToolTipProperties.Text="0-20"
                       Placeholder="10"
                       Keyboard="Numeric" />
7. BUG:
you can not start this app, nor does the intellisense nor the compiler give you any meaningful errormessage, you only get a "Object reference not set to an instance of an object" in the error list.

**8. Why is this a bug:
- If you change from Dictionary<yourEnum, yourObject> to Dictionary<string, yourObject> it runs like a charme**
- If you get rid of the "DataType" in the .xaml, the intellisense won't find the Binding, nor will the program find it at runtime

### Link to public reproduction project repository

https://github.com/Quasimodo6/TestXamlBindings

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

nope, i have wasted days and days on this *$!"§*$!** xaml bindings and red hours over hours in stackoverflow and other sources, without any success. finally i decided to start a clean new project and check, if it is a problem in front of the monitor or behind ;)
turns out: it simply doesn't work as expected.

### Relevant log output

```shell
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler		Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.	TestXamlBindings	C:\Users\*****\*****\Visual Studio Projects\TestXamlBindings\MainPage.xaml	1
```

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

## Description

Fixes #13856

### Problem
Using `x:DataType` with a binding to `Dictionary<CustomEnum, object>` like `{Binding UserSettings[TBD]}` caused a NullReferenceException at compile time in XamlC.

### Root Cause
XamlC's `SetPropertiesVisitor.cs` only supported `int`, `string`, and `object` indexer parameter types. When encountering an enum type, it failed to find a matching indexer and returned `null`, causing a NullReferenceException when trying to access properties on the null indexer.

### Solution
- **XamlC (SetPropertiesVisitor.cs)**: Added support for finding indexers with enum parameter types and emitting enum constant values via IL
- **SourceGen (CompiledBindingMarkup.cs)**: Added support for enum indexer parameter types in the binding path parser

### SetPropertiesVisitor.cs
- Added enum indexer detection when looking for property indexers
- Updated type validation to allow enum indexer types
- Added code to emit enum constant values as IL instructions

### CompiledBindingMarkup.cs  
- Added enum indexer support in `TryParsePath` method
- When an enum indexer is found, generates the fully qualified enum member reference

### Test Fixes
- Fixed pre-existing test failure in `Maui32879Tests.cs` (updated expected output to include `#pragma warning disable CS0219`)

## Tests Added
- `Maui13856.xaml` + `Maui13856.xaml.cs` - XamlC unit test that verifies compilation succeeds
- `Maui13856Tests.cs` - SourceGen unit test that verifies no errors are generated

## Test Results
- All 117 SourceGen.UnitTests pass
- All Xaml.UnitTests binding and indexer tests pass

### CODE REVIEW

File: src/Controls/tests/SourceGen.UnitTests/Maui13856Tests.cs [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+		// Verify that a source file was generated
+		var generatedSource = result.Results
+			.SelectMany(r => r.GeneratedSources)
+			.FirstOrDefault(s => s.HintName.Contains("xsg.cs", System.StringComparison.Ordinal));
+
+		Assert.True(generatedSource.SourceText != null, "Expected generated source file with xsg.cs extension");
+		var generatedCode = generatedSource.SourceText.ToString();
+
+		// Verify the binding path is in the generated code (even if using runtime binding fallback)
+		Assert.Contains("UserSettings[TBD]", generatedCode, System.StringComparison.Ordinal);
```
Comment (simonrozsival) [inline src/Controls/tests/SourceGen.UnitTests/Maui13856Tests.cs]: I don't think this assert should be here. Ideally we'll drop the unnecessary markup extension instantiation at some point (#31614). I think this assert should look for `.UserSettings[global::Test.UserSetting.TBD]` instead.

Comment (simonrozsival) [reply src/Controls/tests/SourceGen.UnitTests/Maui13856Tests.cs]: (although that might currently fail due to #32905)

Comment (StephaneDelcroix) [reply src/Controls/tests/SourceGen.UnitTests/Maui13856Tests.cs]: Done — updated the assertion to check for `UserSettings[global::Test.UserSetting.TBD]` instead. Also added a diagnostic + early return when the enum member is not found, so typo'd enum keys now produce a compile-time error instead of generating invalid C#.
