### PR TITLE
[Android, Windows] Fixed App.Current.PageDisappearing not raised when a page is popped

### LINKED ISSUE #14092: App.Current.PageDisappearing is not raised when a page is popped from the navigation stack.
### Description

App.Current.PageDisappearing is not raised when a page is popped from the navigation stack.

### Steps to Reproduce

1. Create a File->New MAUI app.
2. Replace the constructor in App.xaml.cs with this:
```csharp
public partial class App : Application
{
	public App()
	{
		InitializeComponent();
		//MainPage = new AppShell();
		MainPage = new NavigationPage(new MainPage());

        App.Current.PageAppearing += Current_PageAppearing;
        App.Current.PageDisappearing += Current_PageDisappearing;
	}

    private void Current_PageDisappearing(object sender, Page e)
    {
        Debug.WriteLine($"Current_PageDisappearing {e}");
    }

    private void Current_PageAppearing(object sender, Page e)
    {
        Debug.WriteLine($"Current_PageAppearing {e}");
    }
}
```
3. Replace the click-handler in MainPage.xaml.cs with this:
```csharp
    private void OnCounterClicked(object sender, EventArgs e)
    {
        App.Current.MainPage.Navigation.PushAsync(new ContentPage { Title="Child Page"});
    }
```
4. Run the app.
5. Look at the debug output from the new `Current_PageDisappearing` and `Current_PageAppearing` event handlers.
6. Observe that MainPage and NavigationPage are reported as appearing.
```
[0:] Current_PageAppearing MauiPopNavigationBug.MainPage
[0:] Current_PageAppearing Microsoft.Maui.Controls.NavigationPage
```
8. Tap the button.
9. Observe `MainPage` disappears and `ContentPage` appears.
```
[0:] Current_PageDisappearing MauiPopNavigationBug.MainPage
[0:] Current_PageAppearing Microsoft.Maui.Controls.ContentPage
```
10. Tap the back button
11. [BUG] Observe the ContentPage is popped, the MainPage appearing event is raised but the ContentPage PageDisappearing event is not raised.
```
[0:] Current_PageAppearing MauiPopNavigationBug.MainPage
```

### Link to public reproduction project repository

https://github.com/Keflon/MauiPopNavigationBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, I was *not* able test on other platforms

### Affected platform versions

All current / latest.

### Did you find any workaround?

Subscribe to the following events:

```csharp
App.Current.DescendantAdded += CurrentApplication_DescendantAdded;
App.Current.DescendantRemoved += CurrentApplication_DescendantRemoved;
```
Do something like this:
```csharp
private void CurrentApplication_DescendantAdded(object sender, ElementEventArgs e)
{
    if (e.Element is Page cp)
    {
        cp.Disappearing += PageDisappearing;
        cp.Appearing += PageAppearing;
    }
}

private async void CurrentApplication_DescendantRemoved(object sender, ElementEventArgs e)
{
    if (e.Element is Page cp)
    {
        cp.Appearing -= PageAppearing;

        await Task.Yield();     // Reason: The disappearing event was/is raised after the DescendantRemoved event.
        cp.Disappearing -= PageDisappearing;
    }
}

```
The PageAppearing and PageDisappearing events are correctly raised.  

The above is not tested, however it is a subset of working `CurrentApplication_DescendantAdded` and `CurrentApplication_DescendantRemoved` implementations found here: https://github.com/Keflon/Maui.MvvmZero/blob/eada8a7059fadc248de13456b3be627373384bd8/Maui.MvvmZero/Implementation/PageServiceZero.cs  

### Relevant log output

```shell
[0:] Current_PageAppearing MauiPopNavigationBug.*
[0:] Current_PageDisappearing MauiPopNavigationBug.*
```

### PR DESCRIPTION
**Pull request by Vignesh-SF3580**
### Issue Detail
App.Current.PageDisappearing is not raised when a page is popped using PopAsync/PopToRootAsync

### Root Cause
The navigation stack was not updated correctly when the Disappearing event was invoked. The page was removed from the stack before the event was triggered. Since the page was already removed, its parent was set to null, and as a result, the Disappearing event was not invoked.

### Description of change
Modified the logic to trigger the Disappearing event before removing the page from the stack, which resolves the issue.

### Reference
On iOS, [Disappearing](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.Legacy.cs#L44) event is invoked first then the page is [removed](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.Legacy.cs#L65) from the stack.
In PopModalAsync also, [Disappearing](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.cs#L220) invoked first then [Removed](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.cs#L241) from stack.

Attached is a reference showing the order of events before and after the fix.
image

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/14092

### Screenshots

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="300" height="600"  src="https://github.com/user-attachments/assets/2be733d1-729e-4cc4-96e4-7f4a3f160345"> | <video width="300" height="600"  src="https://github.com/user-attachments/assets/99f4db25-8e41-4cb8-a0c8-d227b07c4bee">) |

### CODE REVIEW

**Review by bhavanesh2001 — COMMENTED** [review]
Won’t the same issue happen with `PopToRoot` too?

https://github.com/dotnet/maui/blob/8e875b73fd7a1500fc012559cf66118f2bbfd633/src/Controls/src/Core/NavigationPage/NavigationPage.cs#L817-L835

**Review by mattleibow — DISMISSED** [review]
I think this is good, but @PureWeen may have thoughts.

Also, the issue title says Android and iOS, but this looks to affect all platforms? Shoould we remove the platform-specific naming?

**Review by bhavanesh2001 — APPROVED** [review]

File: src/Controls/src/Core/NavigationPage/NavigationPage.cs [hunk 1]
```diff
@@ -783,6 +783,7 @@ protected async override Task<Page> OnPopAsync(bool animated)
 				await Owner.SendHandlerUpdateAsync(animated,
 					() =>
 					{
+						Owner.FireDisappearing(currentPage);
```
Comment (PureWeen) [inline src/Controls/src/Core/NavigationPage/NavigationPage.cs:787]: Can you rebase this PR and make sure that the doc you have here holds true?

image

It seems like this PR is going to change the ordering of Navigating and disappearing

Also, why is the Parent null? 
The parent shouldn't really ever be null when we're firing Disappearing and Navigating

**Review by PureWeen — CHANGES_REQUESTED** [review]

**Comment by Vignesh-SF3580** [comment]
> I think this is good, but @PureWeen may have thoughts.
> 
> Also, the issue title says Android and iOS, but this looks to affect all platforms? Shoould we remove the platform-specific naming?

@mattleibow The issue is reproducible on Android and Windows only. On iOS and macOS, the [Disappearing](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.Legacy.cs#L44) event is triggered first before the page is [removed](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.Legacy.cs#L65) from the stack, so the issue does not occur there.

File: src/Controls/src/Core/NavigationPage/NavigationPage.cs (hunk 1 above)
Comment (Vignesh-SF3580) [reply src/Controls/src/Core/NavigationPage/NavigationPage.cs:787]: @PureWeen I have rebased the PR and verified that the documented behavior reflects the correct order.
Regarding the Parent being null — this was due to the page being removed from the stack earlier via [RemoveFromInnerChildren](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.cs#L786), which also cleared the [parent](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Element/Element.cs#L614). I have updated the implementation to address this, and the Parent is now correctly retained when Disappearing and Navigating are fired.

**Review by PureWeen — CHANGES_REQUESTED** [review]
@Vignesh-SF3580 do we need to change the order on this one too?

protected override Task OnPushAsync(Page root, bool animated)
			{
				if (Owner.InternalChildren.Contains(root))
					return Task.CompletedTask;

				var previousPage = Owner.CurrentPage;

				return Owner.SendHandlerUpdateAsync(animated,
					() =>
					{
						Owner.PushPage(root);
					},
					() =>
					{
						Owner.SendNavigating(previousPage);
						Owner.FireDisappearing(previousPage);
						Owner.FireAppearing(root);
					},

**Comment by Vignesh-SF3580** [comment]
> @Vignesh-SF3580 do we need to change the order on this one too?
> 
> protected override Task OnPushAsync(Page root, bool animated) { if (Owner.InternalChildren.Contains(root)) return Task.CompletedTask;
> 
> ```
> 			var previousPage = Owner.CurrentPage;
> 
> 			return Owner.SendHandlerUpdateAsync(animated,
> 				() =>
> 				{
> 					Owner.PushPage(root);
> 				},
> 				() =>
> 				{
> 					Owner.SendNavigating(previousPage);
> 					Owner.FireDisappearing(previousPage);
> 					Owner.FireAppearing(root);
> 				},
> ```

@PureWeen When navigating from Page1 to Page2 using PushAsync, the current navigation order is as follows on all platforms, and it appears to be correct.

- Page1.Disappearing
- App.Current.PageDisappearing
- Page2.Appearing
- App.Current.PageAppearing
- Page1.NavigatedFrom
- Page2.NavigatedTo

When a [page is pushed](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.cs#L872), the [CurrentPage](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.Legacy.cs#L228) is updated. Once the CurrentPage changes, the [Disappearing](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.cs#L530) and [Appearing](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.cs#L533) events are triggered first, followed by the [Navigated](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.cs#L882) events. Do we need to make any changes to this order?

**Comment by PureWeen** [comment]
> > @Vignesh-SF3580 do we need to change the order on this one too?
> > protected override Task OnPushAsync(Page root, bool animated) { if (Owner.InternalChildren.Contains(root)) return Task.CompletedTask;
> > ```
> > 			var previousPage = Owner.CurrentPage;
> > 
> > 			return Owner.SendHandlerUpdateAsync(animated,
> > 				() =>
> > 				{
> > 					Owner.PushPage(root);
> > 				},
> > 				() =>
> > 				{
> > 					Owner.SendNavigating(previousPage);
> > 					Owner.FireDisappearing(previousPage);
> > 					Owner.FireAppearing(root);
> > 				},
> > ```
> 
> @PureWeen When navigating from Page1 to Page2 using PushAsync, the current navigation order is as follows on all platforms, and it appears to be correct.
> 
> * Page1.Disappearing
> * App.Current.PageDisappearing
> * Page2.Appearing
> * App.Current.PageAppearing
> * Page1.NavigatedFrom
> * Page2.NavigatedTo
> 
> When a [page is pushed](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.cs#L872), the [CurrentPage](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.Legacy.cs#L228) is updated. Once the CurrentPage changes, the [Disappearing](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.cs#L530) and [Appearing](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.cs#L533) events are triggered first, followed by the [Navigated](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/NavigationPage/NavigationPage.cs#L882) events. Do we need to make any changes to this order?

yea, let's not hold up this PR on this conversation

Can you investigate if we should move the "Owner.SendNavigating" call up before the pushpage? 

I'm wondering if PushAsync should get changed to 


```C#
			protected override Task OnPushAsync(Page root, bool animated)
			{
				if (Owner.InternalChildren.Contains(root))
					return Task.CompletedTask;

				var previousPage = Owner.CurrentPage;

				return Owner.SendHandlerUpdateAsync(animated,
					() =>
					{
					       // Move the SendNavigating here so that it's fired prior to the stack being modified
						Owner.SendNavigating(previousPage);
						Owner.PushPage(root);
					},
					() =>
					{
						Owner.FireDisappearing(previousPage);
						Owner.FireAppearing(root);
					},
					() =>
					{
						Owner.SendNavigated(previousPage, NavigationType.Push);
						Owner?.Pushed?.Invoke(Owner, new NavigationEventArgs(root));
					});
			}
```

**Review by PureWeen — APPROVED** [review]
