### PR TITLE
Fix Switch Off Track Color - Fixes #10099

### LINKED ISSUE #10099: Toggle button OnColor for Off state not working in iOS, also VisualStateManager is also not working.
### Description

I want to change the OnColor and ThumbColor of the Switch control according to the On/Off state. 

In MAUI Switch control's OnColor property and ThumbColor properties are not working for iOS if handled from code behind. And it does not work properly in both Android & iOS in XAML using VisualStateManager. 

### 1. Using VisualStateManager (Does not work in Android or iOS) 
```html
<Switch IsToggled = "True" >
    <VisualStateManager.VisualStateGroups >
        < VisualStateGroup x:Name="CommonStates">
            <VisualState x:Name="On">
                <VisualState.Setters>
                    <Setter Property = "ThumbColor"
                            Value="MediumSpringGreen" />
                    <Setter Property = "OnColor"
                            Value="MediumSpringGreen" />
                </VisualState.Setters>
            </VisualState>
            <VisualState x:Name="Off">
                <VisualState.Setters>
                    <Setter Property = "ThumbColor"
                            Value="Red" />
                </VisualState.Setters>
            </VisualState>
        </VisualStateGroup>
    </VisualStateManager.VisualStateGroups>
</Switch>
```

<hr/>

### 2. Handled from code behind class, it does not work in iOS, in Android works fine. In iOS when changing the Switch state to Off it does not change the OnColor and ThumbColor like it does in Android. 
```html
void OnSiteToggle_Toggled(System.Object sender, Microsoft.Maui.Controls.ToggledEventArgs e)
{
    if (e.Value)
    {
        OnSiteToggle.OnColor = Color.FromArgb("#7C5FDF");
        OnSiteToggle.ThumbColor = Color.FromArgb("#512BD4");
    }
    else
    {
        OnSiteToggle.OnColor = Color.FromArgb("#969696");
        OnSiteToggle.ThumbColor = Color.FromArgb("#DFD8F7");
    }
}
```

### Steps to Reproduce

1. Create a new .Net Maui project 
2. Take a switch control on the page 
3. Try to change the OnColor and ThumbColor properties of Switch control based on the ON/OFF state. 

Follow the attached project to reproduce the reported bug. Maui

### Link to public reproduction project repository

https://github.com/divyesh008/MauiLabel_Bug.git

### Version with bug

6.0.400

### Last version that worked well

6.0.400

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15, Android 10, 11 and up 

### Did you find any workaround?

No, not yet

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tj-devel709**
Fixes #10099

The customer points out that when a switch track color is set, the switch is turned on, then when the switch is turned off, the switch track color stays on which is not the expected behavior. See below:

## Adjusted Behavior
After the fix from this PR, the switch works as expected:

| iOS | Android |
| :-: | :-: |
|  |  |

Customer reported issues in both android and iOS when using the VisualStateManager, but android worked fine for me without any fixes as shown above

### CODE REVIEW

**Comment by tj-devel709** [comment]
Needs tests 😋

File: src/Core/src/Platform/iOS/SwitchExtensions.cs [hunk 1]
```diff
@@ -7,6 +7,9 @@ namespace Microsoft.Maui.Platform
 {
 	public static class SwitchExtensions
 	{
+		static UIColor? OffTrackColor;
+		static bool HasSwitched;
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/SwitchExtensions.cs:11]: How does this static field work with multiple controls?

Comment (tj-devel709) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs:11]: It works okay with multiple controls since share this default off track color. But there are some discrepancies with Dark mode which I am addressing now!

File: src/Core/src/Platform/iOS/SwitchExtensions.cs [hunk 2]
```diff
@@ -17,17 +17,20 @@ public static void UpdateTrackColor(this UISwitch uiSwitch, ISwitch view)
...
-				uIView = uiSwitch.Subviews[0].Subviews[0].Subviews[0];
+			if (!view.IsOn)
+			{
+				// iOS 13+ uses the UIColor.SecondarySystemFill to support Light and Dark mode
+				// else, use the RGBA equivalent of UIColor.SecondarySystemFill in Light mode
+				uIView.BackgroundColor = OperatingSystem.IsIOSVersionAtLeast(13) ? UIColor.SecondarySystemFill : UIColor.FromRGBA(120, 120, 128, 40);
+			}
 
-			if (view.TrackColor != null)
+			else if (view.TrackColor is not null)
```
Comment (mandel-macaque) [inline src/Core/src/Platform/iOS/SwitchExtensions.cs:29]: if you have if, else if without an else, that else if is in reality an if, for example:
```cs
if (condition) {
} else if (condition2) {
}
```
is the same to the more elegant:
```cs
if (condition) {
}
if (condition2) {
}
```

File: src/Core/src/Platform/iOS/SwitchExtensions.cs [hunk 3]
```diff
@@ -42,13 +45,10 @@ public static void UpdateThumbColor(this UISwitch uiSwitch, ISwitch view)
...
 		{
-			UIView uIView;
 			if (OperatingSystem.IsIOSVersionAtLeast(13) || OperatingSystem.IsTvOSVersionAtLeast(13))
-				uIView = uISwitch.Subviews[0].Subviews[0];
+				return uISwitch.Subviews[0].Subviews[0];
 			else
-				uIView = uISwitch.Subviews[0].Subviews[0].Subviews[0];
-
-			return uIView;
+				return uISwitch.Subviews[0].Subviews[0].Subviews[0];
```
Comment (mandel-macaque) [inline src/Core/src/Platform/iOS/SwitchExtensions.cs:51]: This looks 🐟 , if I understand correctly you are trying to set the tint color, the UISwitch API already provides methods/properties for that:
* https://developer.apple.com/documentation/uikit/uiswitch/1623684-thumbtintcolor?language=objc
* https://developer.apple.com/documentation/uikit/uiswitch/1623687-ontintcolor?language=objc

AFAIK those properties are what your are trying to do and simplify the need for checking the version of the OS.

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/iOS/SwitchExtensions.cs (hunk 3 above)
Comment (mandel-macaque) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs:51]: Talking with @tj-devel709  there is no public API for what he wants and this is the only possible solution (we talked about a diff approach with layers) there is a possible crash with the way the code is written. If apple decides to change the tree view of the widget (go back to 2 for example) the code would be getting a NRE. Since accessing the tree is like accessing the private implementation of the widget the code should be written to protect MAUI from that (better to have a bug about colors than a NRE crash).

File: src/Core/src/Platform/iOS/SwitchExtensions.cs (hunk 2 above)
Comment (hartez) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs:29]: > if you have if, else if without an else, that else if is in reality an if, for example:
> 
> ```cs
> if (condition) {
> } else if (condition2) {
> }
> ```
> 
> is the same to the more elegant:
> 
> ```cs
> if (condition) {
> }
> if (condition2) {
> }
> ```

Those are not equivalent. In the first example, at _most_ one of those code blocks can run. In the second, _both_ of them can run if both `condition` and `condition2` are true.

And also TJ's point about not evaluating `condition2`.

File: src/Core/src/Platform/iOS/SwitchExtensions.cs (hunk 3 above)
Comment (hartez) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs:51]: What @mandel-macaque said - make this return `null` if the track isn't found, and null-check after line 20 above.

**Review by hartez — DISMISSED** [review]
Let's guard against NREs here.

**Comment by tj-devel709** [comment]
I added the NRE checks fine, but the tests that I added started failing again locally for other reasons. I am looking into it some more, but it seems that the UIView that I get into my test is different (different handle at least) and the colors that were set are not set for the argument passed into my test. Visually, things work as expected though..

File: src/Core/src/Platform/iOS/SwitchExtensions.cs [hunk 4]
```diff
@@ -10,24 +10,31 @@ public static class SwitchExtensions
 		public static void UpdateIsOn(this UISwitch uiSwitch, ISwitch view)
 		{
 			uiSwitch.SetState(view.IsOn, true);
+			uiSwitch.UpdateTrackColor(view);
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/SwitchExtensions.cs:13]: I think the way we want to trigger this is from the Handler not from the extension method. 

For example, like this

image

The reason being, if someone were to add a `mapper` for the `TrackColor` property than we'd want any requests to update that property to pass through the mapper.

Comment (PureWeen) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs:13]: @mattleibow thoughts on my comments?

@tj-devel709 indicated that you had him move it into the extension method to keep handlers thin.  I think for cases like this the handler is what contains the logic flow and the extensions themselves shouldn't have side effects. 

Plus, if the `UpdateIsOn` extension method calls `UpdateTrackColor` that will bypass the user if the user has setup their own mapper for `MapTrackColor`

Comment (mattleibow) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs:13]: I think I meant don't call the handler.UpdateValue but rather call the extension method - or copy the line that we need.

Otherwise, changing the value and then updates the handler and then back into a mapper. It jumps all over the place. Rather go from handler, then to extension and stay there.

Not sure what side effects there are with calling the mappers from a mapper and may result in weirdness. Unless you think that is OK?

**Review by mattleibow — DISMISSED** [review]

File: src/Core/src/Platform/iOS/SwitchExtensions.cs (hunk 4 above)
Comment (PureWeen) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs:13]: > How have we done other things where one property affects others?

I don't know if we've been consistent but typically any time the value of X means Y needs to be re-evaluated then I will trigger the update of Y through the mapper. 

Because let's say someone does this

```C#
SwitchHandler.Mapper.ModifyMapper("TrackColor", <my_cide>)
```

If we call `MapTrackColor` from `MapIsOn` that now bypasses the `ModifyMapper` code that the user wants running every time the `TrackColor` is changed. 

We have this a few places in the code.

image

image

image

And then cases where we want to refire mappers from OnLoaded

image

Comment (mattleibow) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs:13]: Yeah, I suppose you convinced me :)

File: src/Core/src/Platform/iOS/SwitchExtensions.cs [hunk 5]
```diff
@@ -40,20 +47,17 @@ public static void UpdateThumbColor(this UISwitch uiSwitch, ISwitch view)
...
-				uIView = uISwitch.Subviews[0].Subviews[0];
+				return uISwitch.Subviews?[0]?.Subviews?[0];
 			else
-				uIView = uISwitch.Subviews[0].Subviews[0].Subviews[0];
-
-			return uIView;
+				return uISwitch.Subviews?[0]?.Subviews?[0]?.Subviews?[0];
 		}
 
-		internal static UIColor? GetOffTrackColor(this UISwitch uISwitch)
```
[the remark this answers is not in the document]
Comment (mattleibow) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs:54]: If it is not used then we probs should.

File: src/Core/src/Platform/iOS/SwitchExtensions.cs [hunk 6]
```diff
@@ -40,20 +47,17 @@ public static void UpdateThumbColor(this UISwitch uiSwitch, ISwitch view)
...
-			UIView uIView;
 			if (OperatingSystem.IsIOSVersionAtLeast(13) || OperatingSystem.IsTvOSVersionAtLeast(13))
-				uIView = uISwitch.Subviews[0].Subviews[0];
+				return uISwitch.Subviews?[0]?.Subviews?[0];
 			else
-				uIView = uISwitch.Subviews[0].Subviews[0].Subviews[0];
-
-			return uIView;
+				return uISwitch.Subviews?[0]?.Subviews?[0]?.Subviews?[0];
 		}
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/SwitchExtensions.cs:56]: Do these views have names or something? Also, what happens if there are no subviews - but it is not null, will the `[0]` throw an index out of bounds?

File: src/Core/src/Platform/iOS/SwitchExtensions.cs (hunk 4 above)
Comment (mattleibow) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs:13]: Sorry @tj-devel709 seems Shane is the most powerful Ween today. Also, not sure if the order matters @PureWeen? Should we have some sort of UpdateValue-Before-UpdateControl policy?

File: src/Core/src/Platform/iOS/SwitchExtensions.cs [hunk 7]
```diff
@@ -10,24 +10,31 @@ public static class SwitchExtensions
...
-				uIView = uiSwitch.Subviews[0].Subviews[0].Subviews[0];
+			if (uIView is null)
+				return;
 
-			if (view.TrackColor != null)
+			if (!view.IsOn)
+			{
+				// iOS 13+ uses the UIColor.SecondarySystemFill to support Light and Dark mode
+				// else, use the RGBA equivalent of UIColor.SecondarySystemFill in Light mode
+				uIView.BackgroundColor = OperatingSystem.IsIOSVersionAtLeast(13) ? UIColor.SecondarySystemFill : UIColor.FromRGBA(120, 120, 128, 40);
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/SwitchExtensions.cs:30]: Can we move this color into a static field so that we can find it again?

File: src/Core/src/Platform/iOS/SwitchExtensions.cs (hunk 6 above)
Comment (mandel-macaque) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs:56]: The views do no have any names, whips is annoying. But we can work around it, @tj-devel709 we can use a FirstOrDefault from Line to solve what @mattleibow mentioned. FirstOrDefault in an empty collection will be null, so we do null null null

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/iOS/SwitchExtensions.cs (hunk 4 above)
Comment (tj-devel709) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs]: @mattleibow @PureWeen it looks like from the examples above, updateValue comes first so I followed that order here!

**Comment by tj-devel709** [comment]
@PureWeen @mattleibow @mandel-macaque This one should be good now!

File: src/Core/src/Platform/iOS/SwitchExtensions.cs (hunk 6 above)
Comment (PureWeen) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs]: @mandel-macaque are we concerned about the overhead of using LINQ here at all?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/iOS/SwitchExtensions.cs (hunk 6 above)
Comment (mandel-macaque) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs]: LINQ is indeed not a good idea. We can always add a helper method like this:
```csharp
public static T FirstOrDefaultNoLinq<T> (T[] items)
{
	return items switch {
		[var i, ..] => i,
		[] => default,
	};
}
```
Does not use LINQ, is a little evil, but should work.

File: src/Core/src/Platform/iOS/SwitchExtensions.cs [hunk 8]
```diff
@@ -40,20 +48,17 @@ public static void UpdateThumbColor(this UISwitch uiSwitch, ISwitch view)
 				uiSwitch.ThumbTintColor = thumbColor?.ToPlatform();
 		}
 
-		internal static UIView GetTrackSubview(this UISwitch uISwitch)
+		internal static UIView? GetTrackSubview(this UISwitch uISwitch)
 		{
-			UIView uIView;
 			if (OperatingSystem.IsIOSVersionAtLeast(13) || OperatingSystem.IsTvOSVersionAtLeast(13))
-				uIView = uISwitch.Subviews[0].Subviews[0];
+				return uISwitch.Subviews?.FirstOrDefault()?.Subviews?.FirstOrDefault();
```
[the remark this answers is not in the document]
Comment (mandel-macaque) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs:54]: I'm going to agree, there is nothing nice we can do. Sometimes code has to be ugly and work.

[the remark this answers is not in the document]
Comment (tj-devel709) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs]: @mandel-macaque and @PureWeen  updated! Thanks for the idea!

File: src/Core/src/Platform/iOS/SwitchExtensions.cs [hunk 9]
```diff
@@ -51,14 +51,23 @@ public static void UpdateThumbColor(this UISwitch uiSwitch, ISwitch view)
...
-				return uISwitch.Subviews?.FirstOrDefault()?.Subviews?.FirstOrDefault()?.Subviews?.FirstOrDefault();
+				return uISwitch.Subviews?.FirstOrDefaultNoLinq()?.Subviews?.FirstOrDefaultNoLinq()?.Subviews?.FirstOrDefaultNoLinq();
 		}
 
 		internal static UIColor? GetTrackColor(this UISwitch uISwitch)
 		{
 			return uISwitch.GetTrackSubview()?.BackgroundColor;
 		}
+
+		internal static T? FirstOrDefaultNoLinq<T>(this T[] items)
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/SwitchExtensions.cs:64]: can you move this into ArrayExtensions?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/iOS/SwitchExtensions.cs (hunk 9 above)
Comment (tj-devel709) [reply src/Core/src/Platform/iOS/SwitchExtensions.cs]: @PureWeen When I move this to ArrayExtensions as is, I get this error: "Error CS0518: Predefined type 'System.Index' is not defined or imported(CS0518) (Core)". I'm not sure why as it appears that this is an error I could get prior to having C#8 but we are in the same project. 

I changed the implementation to something that I don't believe is worse, but let me know if there is a better solution to this?

File: src/Core/src/Extensions/ArrayExtensions.cs [hunk 10]
```diff
@@ -64,5 +64,7 @@ public static T[] RemoveAt<T>(this T[] self, int index)
 		/// <param name="self">The array to retrieve the last item from.</param>
 		/// <returns>An object of type <typeparamref name="T"/> that is the last item in the collection.</returns>
 		public static T Last<T>(this T[] self) => self[self.Length - 1];
+
+		internal static T? FirstOrDefaultNoLinq<T>(this T[] items) => items is null || items.Length == 0 ? default : items[0];
```
Comment (PureWeen) [inline src/Core/src/Extensions/ArrayExtensions.cs:68]: @mandel-macaque any complaints?

Comment (mandel-macaque) [reply src/Core/src/Extensions/ArrayExtensions.cs:68]: Looks good, but I am surprise the compiler is not printing a warning with nullability enabled saying something like 'items is not set as nullable'. I think we probably want to do something like:
```suggestion
		internal static T? FirstOrDefaultNoLinq<T>(this T[]? items) => items is null || items.Length == 0 ? default : items[0];
```
Right?

**Review by mandel-macaque — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]
