### PR TITLE
Fix updating Windows resources at runtime

### LINKED ISSUE #4356: Calling ClearValue if a color is null on WinUI is incorrect behavior
### Description

https://github.com/dotnet/maui/blob/8966710cc2f7908087b54fea5a0258992e79858c/src/Core/src/Platform/Windows/ViewExtensions.cs#L155

If a property is set via a `TemplateBinding` or a `ThemeResource` inside a ControlTemplate then calling ClearValue will just reset the property to the DP default

If the color is null then `UpdateProperty` should just do nothing

### Steps to Reproduce

Call UpdateProperty on a Control inside ControlTemplate with a null color and you'll see it doesn't actually revert to a relevant default value

For example, when setting the TabBar we are setting the background on the following control that's set via a `ThemeResource`

https://github.com/microsoft/microsoft-ui-xaml/blob/991c831e4ac5b58591621f904c2f94f5a9a5bc4f/dev/NavigationView/NavigationView.xaml#L281

If the user sets the color back to null then clearing that DP doesn't re-instate the ThemeResource

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

WinUI

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #5084: Triggers not working
### Description

I had a data trigger in my app that I couldn't get working in a DataTemplate. I decided to check I understood triggers by following the [examples in the Maui Documentation](url).

The very first example did not work in Windows or Android. This was a simple example with an entry that should have turned yellow when it got focus. There was no visual change when it received focus.

### Steps to Reproduce

1. In a new project add the following XAML code to a view (this code is taken directly from the docs):

```
<Entry Placeholder="Enter name">
    <Entry.Triggers>
        <Trigger TargetType="Entry"
                 Property="IsFocused"
                 Value="True">
            <Setter Property="BackgroundColor"
                    Value="Yellow" />
            <!-- Multiple Setter elements are allowed -->
        </Trigger>
    </Entry.Triggers>
</Entry>
```

2. Run the project and navigate to the page with the entry on.
3. Focus on the entry.
4. It does not turn yellow.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

NA

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #7803: Unable to un-set values on Windows
### Description

If you set a button border width and then try unset it - either via setting to -1 or calling ClearValue - does not do the correct thing.

It calls ClearValue in the handler, but this actually clears the ThemeResource set via the WASDK framework.

Related to
 - #4356
 - #5084

And related to:
 - https://github.com/microsoft/microsoft-ui-xaml/issues/5457
 - https://github.com/microsoft/microsoft-ui-xaml/issues/4443
 - https://github.com/microsoft/microsoft-ui-xaml/issues/4651
 - https://dev.azure.com/microsoft/OS/_workitems/edit/39897009/

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #7820: Updating WinUI properties via resources does not take effect
### Description

Setting certain properties on Windows does not directly update the control but rather the resources. For example, Button.BorderWidth. As a result, the property makes no visible change until something triggers the OS theme to change.

The reason this happens is that properties are set in the styles using `{ThemeResource}` which is _just_ a `{StaticResource}` tied to a theme. This means that it is _just_ a read once thing - unless the theme changes.

There is a workaround and that is to toggle the theme, but a "real fix" is coming in https://dev.azure.com/microsoft/OS/_workitems/edit/39897009/

This fix I believe for the interim will basically trigger theme updates without requiring the toggling of the theme. However, the end result is basically the same, the theme is refreshed for he entire control. This totally can change but for now this will make things work.

Related to:
 - #7803
 - #4356
 - #5084

And related to WASDK:
 - https://github.com/microsoft/microsoft-ui-xaml/issues/5457
 - https://github.com/microsoft/microsoft-ui-xaml/issues/4443
 - https://github.com/microsoft/microsoft-ui-xaml/issues/4651

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All

### Did you find any workaround?

There is a workaround and that is to get the native control and toggle the RequestedTheme. 

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

This PR is a workaround for the underlying issue that updating a resource that is applied with a `{ThemeResource}` does not take affect because it is actually a `{StaticResource}` in disguise.

There is a more real fix coming with https://dev.azure.com/microsoft/OS/_workitems/edit/39897009

But, for now the workaround is to trigger a "theme change" and that applies the new theme resources. The real fix is also going to do this, but without requiring changing properties.

### Issues Fixed

 - Fixes #7820
 - Fixes #5084
 - Fixes #4356
 - Fixes #7803

### CODE REVIEW

File: src/Core/src/Platform/Windows/FrameworkElementExtensions.cs [hunk 1]
```diff
@@ -324,5 +324,19 @@ internal static void SetApplicationResource(this FrameworkElement frameworkEleme
...
+
+			// Workaround for https://github.com/dotnet/maui/issues/7820
+			nativeView.RequestedTheme = nativeView.ActualTheme switch
+			{
+				ElementTheme.Dark => ElementTheme.Light,
+				_ => ElementTheme.Dark
+			};
+
+			nativeView.RequestedTheme = previous;
+		}
```
Comment (mattleibow) [inline src/Core/src/Platform/Windows/FrameworkElementExtensions.cs:340]: This is the real "fix" here and is basically a workaround with a still-workaround-but-not-totally fix coming in the core Windows App SDK.

**Review by hartez — APPROVED** [review]

**Comment by sjb-sjb** [comment]
It would be really handy to have an easy way to systematically convert resources into (efficient) properties. That way users could customize the control far more dynamically. It would be nice if this were built in or if there were a better/faster way to do it than the workaround.
