### PR TITLE
Remove excess check in iOS input transparency checks

### LINKED ISSUE #18716: [regression/8.0.3] [iOS] [SDK 17] Touch events are not working on WebView when a PDF is displayed.
### Description

With iOS Sdk 17 / XCode 15, the WebView on iOS doesn't respond to any touch events (no zoom or scroll is possible) with PDF file. Works fine with any other html content.

### Steps to Reproduce

1. Create a new Maui App
2. Add a web view control under a Grid Element to the Xaml
```
        <Grid>
            <WebView Grid.Row="0" x:Name="WebView"
                Source="https://www.africau.edu/images/default/sample.pdf">
             </WebView>
       </Grid>
```
4. Launch the App on iOS (16 or 17)

Actual:
PDF file is rendered but no touch events are working on WebView (No scroll, no Zoom).

Expected:
Should be able to zoom or scroll.

Notes:
- Rendering a webpage works fine without any issue (e.g. www.bing.com)
- This worked fine before updating to Microsoft.iOS SDK / XCode 15 for SDK 17
- Tested on .Net Maui Workload (8.0.0-rc.2.9511, 8.0.0-rc.2.9530) and both are impacted.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.0-rc.2.9511

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.2.9373

### Affected platforms

iOS

### Affected platform versions

iOS (All versions)

### Did you find any workaround?

No :(

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

Fix issue that does not allow scrolling in WebView with PDF on iOS.

Initially, I started by checking the status of the WebView: if internal UIScrollView scrolling was enabled, if the assigned size was correct, etc. Everything is fine so let's go check the hierarchy. It was interesting that the problem does not appear without a Layout as a parent. Reviewing I realized that the problem comes from the changes applied in https://github.com/dotnet/maui/pull/17286 related to InputTransparent. Applied changes to keep the InputTransparent working and fix the issue.

### Issues Fixed

Fixes #18716

### CODE REVIEW

File: src/Core/src/Platform/iOS/LayoutView.cs [hunk 1]
```diff
@@ -37,14 +37,6 @@ public override void WillRemoveSubview(UIView uiview)
 				return null;
 			}
 
-			if (!result.UserInteractionEnabled)
-			{
-				// If the child also has user interaction disabled (IOW the child is InputTransparent),
-				// then we also want to exclude it from the hit testing.
-
-				return null;
-			}
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/LayoutView.cs:46]: I am not sure why I added this, but it was a long time ago and I did an exhaustive set of tests in this PR at the same time I added this code: https://github.com/dotnet/maui/pull/17286

As far as I can see, this does not look like it is needed as this code path never seems to be hit with other controls - even when the WrapperView is being used.

At this point, I am going to have to rely on the set of tests to validate that this change is fine.

**Review by mattleibow — APPROVED** [review]

**Review by mattleibow — CHANGES_REQUESTED** [review]

**Review by mattleibow — APPROVED** [review]
