### PR TITLE
[Android] Fix bidirectional scrolling on Android

### LINKED ISSUE #2768: [Bug] Scrollview is not scrolling vertically
### Description
Can't able to scroll vertically even when ScrollView.Orientation is **Both** and the content height is greater than the scrollview height.

### Steps to Reproduce
1. Set scrollview orientation as Both.
2. Have a Content with size greater than scrollview Size.

### Expected Behavior
Scrollview should be scrollable vertically as well as Horizontally.

### Actual Behavior
Scrollview is scrolling horizontally only.

### Basic Information
- Version with issue: Preview 8
- Platform Target Frameworks: 
  - Android: API 29

### Reproduction Link
[ScrollingIssue.zip](https://github.com/dotnet/maui/files/7256558/ScrollingIssue.zip)

### LINKED ISSUE #5759: Cannot scroll vertically when Orientation is Both
### Description

On Android I can scroll horizontally, but not vertically. I tried click-drag and mousewheel on an API 30 emulator.

Source: https://github.com/davidortinau/ControlGallery/

image

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ControlGallery.Pages.LabelPage"
             Title="Label">

    <ContentPage.Content>
        <ScrollView Orientation="Both">
            <StackLayout Padding="{OnPlatform iOS='30,60,30,30', Default='30,30,0,30'}">

                <Label LineBreakMode="NoWrap" LineHeight="1.4">
                    <Label.FormattedText>
                        <FormattedString>
                            <Span Text="Font name: OpenSans Regular &#10;"/>
                            <Span Text="Version: 1.00  &#10;"/>
                            <Span Text="Digitally Signed, TrueType Outlines &#10;"/>
                            <Span Text="abcdefghijklmnopqrstuvwxyz "/>
                            <Span Text="abcdefghijklmnopqrstuvwxyz &#10;" TextTransform="Uppercase"/>
                            <Span Text="1234567890.:,;'+-*/=  &#10;"/>
                            <Span Text="12 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="12"/>
                            <Span Text="18 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="18"/>
                            <Span Text="24 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="24"/>
                            <Span Text="36 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="36"/>
                            <Span Text="48 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="48"/>
                            <Span Text="60 The quick brown fox jumps over the lazy dog. 1234567890 &#10;" FontSize="60"/>
                            <Span Text="72 The quick brown fox jumps over the lazy dog. 1234567890 " FontSize="72" >
                                <Span.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding TapCommand}" CommandParameter="https://google.com" />
                                </Span.GestureRecognizers>
                            </Span>
                        </FormattedString>
                    </Label.FormattedText>                    
                </Label>

                <Label Text="Unicode linebreaks"
                       Style="{StaticResource Headline}" />
                <BoxView Style="{StaticResource HRule}"/>
                <!-- Unicode line feed character -->
                <Label Text="First line &#10; Second line" />

                <Label Text="Property Element linebreaks"
                       Style="{StaticResource Headline}" />
                <BoxView Style="{StaticResource HRule}"/>
                <!-- Property element syntax -->
                <Label>
                    <Label.Text>
                        First line
                        Second line
                        Third Line
                    </Label.Text>
                </Label>

                <Label Text="CharacterSpacing=10"
                       Style="{StaticResource Headline}" />
                <BoxView Style="{StaticResource HRule}"/>
                <Label Text="Character spaced text"
       CharacterSpacing="10" />

                <Label Text="TextTransform=Uppercase"
                       Style="{StaticResource Headline}" />
                <BoxView Style="{StaticResource HRule}"/>
                <Label Text="This text will be displayed in uppercase."
       TextTransform="Uppercase" />

                <Label Text="LineBreakMode &amp; LineHeight"
                       Style="{StaticResource Headline}" />
                <BoxView Style="{StaticResource HRule}"/>
                <Label Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. In facilisis nulla eu felis fringilla vulputate. Nullam porta eleifend lacinia. Donec at iaculis tellus."
       LineBreakMode="WordWrap"
       LineHeight="1.8" />

                <Label Text="HTML"
                       Style="{StaticResource Headline}" />
                <BoxView Style="{StaticResource HRule}"/>
                <Label BackgroundColor="Yellow" 
                       Text="This is &lt;strong style=&quot;color:red&quot;&gt;HTML&lt;/strong&gt; text."
       TextType="Html"  />

                <Label Text="FormattedText &amp; Spans"
                       Style="{StaticResource Headline}" />
                <BoxView Style="{StaticResource HRule}"/>

                <Label LineBreakMode="WordWrap">
                    <Label.FormattedText>
                        <FormattedString>
                            <Span Text="Red Bold, " TextColor="Red" FontAttributes="Bold" />
                            <Span Text="default, " Style="{DynamicResource BodyStyle}">
                                <Span.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding TapCommand}" />
                                </Span.GestureRecognizers>
                            </Span>
                            <Span Text="italic small." FontAttributes="Italic" FontSize="Small" />
                        </FormattedString>
                    </Label.FormattedText>
                </Label>

                <!--<Label Text="XAML Hot Reload connected and working, unless I make a layout change"
                       FontSize="12"
                       TextColor="Red"
                       WidthRequest="100"
                       HeightRequest="100"
                       Padding="10"
                       Margin="50"
                       MaxLines="3"
                       LineBreakMode="TailTruncation"
                       FontAttributes="Italic"
                       TextDecorations="Underline"
                       VerticalTextAlignment="End"
                       HorizontalTextAlignment="Start"
                       />-->


                <Label Text="App Text Styles"
                       Style="{StaticResource Headline}" />
                <BoxView Style="{StaticResource HRule}"/>

                <Label Text="Large Title"
                       Style="{StaticResource LargeTitle}"/>
                <Label Text="30px, OpenSansSemiBold, #000000" 
                       Style="{StaticResource TypographyMeta}"/>

                <Label Text="Title 1"
                       Style="{StaticResource Title1}"/>
                <Label Text="26px, OpenSansSemiBold, #000000" 
                       Style="{StaticResource TypographyMeta}"/>

                <Label Text="Headline"
                       Style="{StaticResource Headline}"/>
                <Label Text="17px, OpenSansSemiBold, #000000" 
                       Style="{StaticResource TypographyMeta}"/>

                <Label Text="Body"/>
                <Label Text="17px, OpenSansRegular, #000000" 
                       Style="{StaticResource TypographyMeta}"/>

                <Label Text="Subhead"
                       StyleClass="Subhead"/>
                <Label Text="15px, OpenSansRegular, #000000" 
                       Style="{StaticResource TypographyMeta}"/>

                <Label Text="Footnote"
                       StyleClass="Footnote"/>
                <Label Text="13px, OpenSansRegular, #000000" 
                       Style="{StaticResource TypographyMeta}"/>

                <Label Text="Text Color Styles"
                       Style="{StaticResource Headline}" />
                <BoxView Style="{StaticResource HRule}"/>
                <Label Text="Regular"/>
                <Label Text="Secondary" Style="{StaticResource Secondary}"/>
                <Label Text="Error" StyleClass="Error"/>
                <Label Text="Warning" StyleClass="Warning"/>
                <Label Text="Disabled" StyleClass="Disabled"/>

                <Label Text="Default Styles"
                       Style="{StaticResource Headline}" />
                <BoxView Style="{StaticResource HRule}"/>
                <Label Text="TitleStyle" Style="{DynamicResource TitleStyle}"/>
                <Label Text="SubtitleStyle" Style="{DynamicResource SubtitleStyle}"/>
                <Label Text="BodyStyle" Style="{DynamicResource BodyStyle}"/>
                <Label Text="CaptionStyle" Style="{DynamicResource CaptionStyle}"/>
                <Label Text="ListItemTextStyle" Style="{DynamicResource ListItemTextStyle}"/>
                <Label Text="ListItemDetailTextStyle" Style="{DynamicResource ListItemDetailTextStyle}"/>


            </StackLayout>
        </ScrollView>

    </ContentPage.Content>
</ContentPage>
```

### Steps to Reproduce

Run the Label control page

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #7811: Vertical scrolling in <ScrollView Orientation="Both"> not working
### Discussed in https://github.com/dotnet/maui/discussions/7796

<div type='discussions-op-text'>

<sup>Originally posted by **usa-** June  6, 2022</sup>
I start VS 2022 version 17.3.0 preview 1.1 (the latest one).
I create a new “.NET MAUI App” project.
In the MainPage.xaml file, I change the code inside the ContentPage element to the following:

```
    <ScrollView Orientation="Both">
        <Image Source="dotnet_bot.png" HeightRequest="1000" WidthRequest="1000" Aspect="AspectFit" />
    </ScrollView>
```

In the code-behind file, MainPage.xaml.cs, I delete the OnCounterClicked function.
In the debug destination drop-down list, I select the Android Emulator.
I run the application.
Expected behavior: I am able to scroll the image both vertically and horizontally.
Actual behavior: I am able to scroll the image only horizontally.</div>

### LINKED ISSUE #7979: [Android/iOS] Scrollview Direction=Both not working with Label as the content
### Description

Setting Orientation=Both in scrollview only works horizontally for android, and doesn't work at all on iOS (see #7933).

```xml
 <Grid Grid.Row="1">
            <Border x:Name="LogsBorder"
                    Stroke="WhiteSmoke"
                    StrokeThickness="2">
                <Border.StrokeShape>
                    <RoundRectangle CornerRadius="20" />
                </Border.StrokeShape>
                <ScrollView Orientation="Both" >
                    <!-- <Editor x:Name="Logs" -->
                    <!--         FontSize="13" -->
                    <!--         IsReadOnly="True" -->
                    <!--         AutoSize="TextChanges" -->
                    <!--         HorizontalOptions="Fill" -->
                    <!--         VerticalOptions="Fill"/> -->
                    <Label x:Name="Logs"
                           FontSize="13"
                           Margin="5,0"
                           LineBreakMode="WordWrap"/>
                </ScrollView>
            </Border>

            <Button x:Name="Refresh"
                    Text="Refresh"
                    VerticalOptions="End"
                    Margin="0,0,0,15"
                    HorizontalOptions="Center"
                    Clicked="OnRefreshClicked"/>
        </Grid>
```

image

### Steps to Reproduce

Steps to Reproduce
Clone: https://github.com/roubachof/MetroLog/tree/maui

* Run MetroLogSmaple.Maui on Android.
* Click on the Show Logs button.
* Hit Refresh, till it fills the space.
* Try to scroll vertically

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android API 31

### Did you find any workaround?

Nope

### Relevant log output

_No response_

### LINKED ISSUE #9000: ScrollView‘s HorizontalScrollBar is not visible and ScrollView cannot scroll horizontally
### Description

`ScrollView`‘s `HorizontalScrollBar` is not visible and ScrollView cannot scroll horizontally.

### Steps to Reproduce

1.create a maui app;
2.add the following code in `MainPage.xaml`

      <ScrollView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" VerticalScrollBarVisibility="Always" HorizontalScrollBarVisibility="Always">
        <StackLayout>
            <Image
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                 WidthRequest="800"                
                 />

        </StackLayout>
    </ScrollView>

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 10.0

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

On android , we use 2 native scrollviews to handle bidirectional scrolling. The HorizontalScrollView was always laying on the available height, but we want the vertical scroll to work on it's parent we need to use the scrollview content height and not the default available height 

### Issues Fixed

Fixes #2768
Fixes #5759
Fixes #7811
Fixes #9000
Related to #7979 android part only
Related to #13187 android part only

### CODE REVIEW

File: src/Core/src/Platform/Android/MauiScrollView.cs [hunk 1]
```diff
@@ -187,9 +187,14 @@ protected override void OnLayout(bool changed, int left, int top, int right, int
 		{
 			base.OnLayout(changed, left, top, right, bottom);
 
-			if (_hScrollView != null && _hScrollView.Parent == this)
+			if (_hScrollView != null && _hScrollView.Parent == this && _content != null)
```
Comment (mandel-macaque) [inline src/Core/src/Platform/Android/MauiScrollView.cs:190]:
```suggestion
			if (_hScrollView?.Parent == this && _content is not null)
```
We can simplify the if, right? null is not this

**Review by mandel-macaque — APPROVED** [review]
Nit: is not a blocker, but please update the if before you land.

File: src/Core/src/Platform/Android/MauiScrollView.cs [hunk 2]
```diff
@@ -187,9 +187,14 @@ protected override void OnLayout(bool changed, int left, int top, int right, int
...
 			{
-				_hScrollView.Layout(0, 0, right - left, bottom - top);
+				double scrollViewContentHeight = _content.Height;
+				var hScrollViewHeight = bottom - top;
+				//if we are scrolling both ways we need to layout our MauiHorizontalScrollView with more than the available height
+				//so it's parent the NestedScrollView can scroll vertically
```
Comment (samhouts) [inline src/Core/src/Platform/Android/MauiScrollView.cs:195]:
```suggestion
				//so its parent the NestedScrollView can scroll vertically
```

File: src/Core/src/Platform/Android/MauiScrollView.cs [hunk 3]
```diff
@@ -187,9 +187,14 @@ protected override void OnLayout(bool changed, int left, int top, int right, int
 		{
 			base.OnLayout(changed, left, top, right, bottom);
 
-			if (_hScrollView != null && _hScrollView.Parent == this)
+			if (_hScrollView != null && _hScrollView.Parent == this && _content != null)
 			{
-				_hScrollView.Layout(0, 0, right - left, bottom - top);
+				double scrollViewContentHeight = _content.Height;
+				var hScrollViewHeight = bottom - top;
+				//if we are scrolling both ways we need to layout our MauiHorizontalScrollView with more than the available height
```
Comment (samhouts) [inline src/Core/src/Platform/Android/MauiScrollView.cs:194]:
```suggestion
				//if we are scrolling both ways we need to lay out our MauiHorizontalScrollView with more than the available height
```

File: src/Core/src/Platform/Android/MauiScrollView.cs (hunk 2 above)
Comment (samhouts) [reply src/Core/src/Platform/Android/MauiScrollView.cs:195]: phew, glad i was here.

**Review by samhouts — APPROVED** [review]

**Comment by rmarinho** [comment]
@jsuarezruiz  I added a gallery example on #13657 . I will also see if I can add device tests tomorrow

**Review by hartez — APPROVED** [review]
