### PR TITLE
[iOS][Shell]Tab becomes blank after specific navigation pattern - fix

### LINKED ISSUE #29798: [iOS][Shell] Tab becomes blank after specific navigation pattern
### Description

When a user navigates to a page via a tab, then taps the already selected tab to pop the navigation stack (expected behavior), and then navigates to that page again, navigating back (either by tapping the tab again or using the back button) results in the tab page being cleared or appearing empty.

Image

### Steps to Reproduce

1. Clone https://github.com/Vetle444/MauiTestApp/tree/tabPageClears
2. Make sure to be on branch: tabPageClears
3. Run app
4. Navigate to test page
5. Click the first tab
6. Navigate to test page
7. Click back
8. Tab is cleared
9. You can also click on the tab to clear the tab

### Link to public reproduction project repository

https://github.com/Vetle444/MauiTestApp/tree/tabPageClears

### Version with bug

9.0.70 SR7

### Is this a regression from previous behavior?

Yes

### Last version that worked well

9.0.40

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### LINKED ISSUE #30280: [iOS] Back navigation via re-selection of the active tab results in shell content being completely blank upon revisit from another tab
### Description

After upgrading to MAUI 9, we noticed that screen content was being cleared, seemingly at random. It was then determined that the root cause is a difference in navigation behavior between navigating back to the previous screen via the top left navigation arrow vs re-selecting the active tab. The navigation arrow sends a ".." path to pop the view, whereas the back button navigates to the full URI path of the view. 

### Steps to Reproduce

1. Pull the provided public repository [(https://github.com/kmk-irc/MauiApp99)](https://github.com/kmk-irc/MauiApp99)
2. Build and run the app in an iOS simulator or on an iOS device.
3. The "Main Page" tab should be pre-selected.
4. Select "Go to subview" to navigate to a child page
5. Select the "Main Page" tab to navigate back to the previous screen.
6. Select the "Second Page" tab.
7. Go back to the "Main Page" tab.

**Expected to happen**
Screen contents appear as expected.

**What actually happens**
Screen content is completely blank.

### Link to public reproduction project repository

https://github.com/kmk-irc/MauiApp99

### Version with bug

9.0.30 SR3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18.5

### Did you find any workaround?

The only workaround we were able to find is to effectively disable back navigation via tab re-selection. One way to do that is the following. 

`public AppShell()
{
    InitializeComponent();

    Routing.RegisterRoute(nameof(AllOrdersPage), typeof(AllOrdersPage));
    Routing.RegisterRoute(nameof(LoginPage), typeof(LoginPage));
    Routing.RegisterRoute(nameof(LoggedOutPage), typeof(LoggedOutPage));
    Routing.RegisterRoute(nameof(NotificationOptionsPage), typeof(NotificationOptionsPage));
    Routing.RegisterRoute(nameof(OrderDetailsPage), typeof(OrderDetailsPage));
    Routing.RegisterRoute(nameof(PatientDetailPage), typeof(PatientDetailPage));
    Routing.RegisterRoute(nameof(ViewPdfPage), typeof(ViewPdfPage));

    Navigating += OnNavigating;
}

private void OnNavigating(object sender, ShellNavigatingEventArgs e)
{
    if (DeviceInfo.Platform == DevicePlatform.iOS)
    {
        var currentTab = mainTabBar.CurrentItem.Title;
        var targetRoute = e.Target.Location.OriginalString;

        if (currentTab == "Order Summary" && targetRoute == "//main/DetailsPage")
        {
            e.Cancel();
        }
    }
}`

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/29798
Fixes https://github.com/dotnet/maui/issues/30280

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/78b02f40-cb32-447e-97ee-344ee23ee68a" width="300px"/>| <video src="https://github.com/user-attachments/assets/41a4e059-ebc5-4894-8e28-cf769885afe1" width="300px"/>|

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs [hunk 1]
```diff
@@ -70,7 +70,7 @@ void IAppearanceObserver.OnAppearanceChanged(ShellAppearance appearance)
 		ShellSection _shellSection;
 		bool _ignorePopCall;
 
-		bool _popRequested;
+		internal bool popRequested;
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs]: Can you change this to a full property instead of a field? 

I'd rather not mark fields anything but private

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs [hunk 2]
```diff
@@ -109,7 +107,37 @@ public bool ShouldPopItem(UINavigationBar _, UINavigationItem __)
...
+			// Ensure we have enough pages and navigation items
+			if (pages.Count == 0 || NavigationBar.Items.Length == 0)
+				return true;
+
+			// Bounds check: ensure we have a valid index for pages array
+			int targetIndex = NavigationBar.Items.Length - 1;
+			if (targetIndex < 0 || targetIndex >= pages.Count)
+				return true;
+
+			_shellSection.SyncStackDownTo(pages[targetIndex]);
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs:130]: Can directly use:
` _shellSection.SyncStackDownTo(_shellSection.Stack[targetIndex]);`
 And avoid the memory allocation from `ToList()`?

Comment (jsuarezruiz) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs:130]: From line 119

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs [hunk 3]
```diff
@@ -109,7 +107,37 @@ public bool ShouldPopItem(UINavigationBar _, UINavigationItem __)
 		[Export("navigationBar:didPopItem:")]
 		[Internals.Preserve(Conditional = true)]
 		bool DidPopItem(UINavigationBar _, UINavigationItem __)
-			=> _popRequested || SendPop();
+		{
+			// Check for null references
+			if (_shellSection?.Stack == null || NavigationBar?.Items == null)
```
Comment (rmarinho) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs]:
```suggestion
			if (_shellSection?.Stack is null || NavigationBar?.Items is null)
```

File: src/Controls/src/Core/Shell/ShellSection.cs [hunk 4]
```diff
@@ -111,6 +111,32 @@ void IShellSectionController.SendInsetChanged(Thickness inset, double tabThickne
 			_lastTabThickness = tabThickness;
 		}
 
+		internal void SyncStackDownTo(Page page)
+		{
+			if (_navStack.Count <= 1)
+				throw new Exception("Nav Stack consistency error");
```
Comment (rmarinho) [inline src/Controls/src/Core/Shell/ShellSection.cs]:
```suggestion
			if (_navStack.Count <= 1)
			{
				throw new Exception("Nav Stack consistency error");
			}
```

File: src/Controls/src/Core/Shell/ShellSection.cs [hunk 5]
```diff
@@ -111,6 +111,32 @@ void IShellSectionController.SendInsetChanged(Thickness inset, double tabThickne
...
+
+			var oldStack = _navStack;
+
+			int index = oldStack.IndexOf(page);
+			_navStack = new List<Page> { null };
```
Comment (rmarinho) [inline src/Controls/src/Core/Shell/ShellSection.cs]: Why we do this `new List<Page> { null };` with null?

File: src/Controls/src/Core/Shell/ShellSection.cs [hunk 6]
```diff
@@ -111,6 +111,32 @@ void IShellSectionController.SendInsetChanged(Thickness inset, double tabThickne
...
+
+			for (int i = 1; i <= index; i++)
+			{
+				_navStack.Add(oldStack[i]);
+			}
+
+			for (int i = index + 1; i < oldStack.Count; i++)
+				oldStack[i].SendDisappearing();
```
Comment (rmarinho) [inline src/Controls/src/Core/Shell/ShellSection.cs]:
```suggestion
			for (int i = index + 1; i < oldStack.Count; i++)
			{
				oldStack[i].SendDisappearing();
			}
```

Comment (rmarinho) [reply src/Controls/src/Core/Shell/ShellSection.cs]: Should this loop be reversed? start with last?

File: src/Controls/src/Core/Shell/ShellSection.cs [hunk 7]
```diff
@@ -111,6 +111,32 @@ void IShellSectionController.SendInsetChanged(Thickness inset, double tabThickne
...
+
+			UpdateDisplayedPage();
+
+			for (int i = index + 1; i < oldStack.Count; i++)
+				RemovePage(oldStack[i]);
```
Comment (rmarinho) [inline src/Controls/src/Core/Shell/ShellSection.cs]:
```suggestion
			for (int i = index + 1; i < oldStack.Count; i++)
			{
				RemovePage(oldStack[i]);
			}
```

Comment (rmarinho) [reply src/Controls/src/Core/Shell/ShellSection.cs]: Can't we do this in the loop above?

**Review by rmarinho — COMMENTED** [review]
Just small questions and updates

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs (hunk 2 above)
Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs:130]: The contents of `_shellSection.Stack` is going to change throughout the method so we need to keep a copy of it for the for loop after line 130.

So we might as well just use pages here because we need to allocate the shallow copy of the list anyway.

```C#
for (int i = pages.Count - 1; i >= NavigationBar.Items.Length; i--)
			{
				var page = pages[i];
				if (page != null)
					DisposePage(page);
			}
```

File: src/Controls/src/Core/Shell/ShellSection.cs (hunk 5 above)
Comment (PureWeen) [reply src/Controls/src/Core/Shell/ShellSection.cs]: Because that's Shell :-) 

The first "page" in the shells navigation stack is null. 
It's kind of odd
It annoys people
We should probably fix it

But it is what it is for now.

File: src/Controls/src/Core/Shell/ShellSection.cs (hunk 7 above)
Comment (PureWeen) [reply src/Controls/src/Core/Shell/ShellSection.cs]: We want to call `UpdateDisplayedPage();` Before calling `RemovePage` this way the new page has been initialized into the stack before we start removing pages. The ordering here is important

- call disappearing on each page so that the correct page is in an "appeared" state
- UpdateDisplayedPage so current page becomes "UnDisplayed" in the logic
- now that all ceremony of removing the oldpages is done. Let's call RemovePage

It's the same ordering for each method in here that removes a page

```C#
async void IShellSectionController.SendPopping(Task poppingCompleted)
		{
			if (_navStack.Count <= 1)
				throw new Exception("Nav Stack consistency error");

			var page = _navStack[_navStack.Count - 1];

			_navStack.Remove(page);
			UpdateDisplayedPage();

			await poppingCompleted;

			RemovePage(page);

			(Parent?.Parent as IShellController)?.UpdateCurrentState(ShellNavigationSource.Pop);
		}
```

So I didn't really want to mess with it

**Review by rmarinho — APPROVED** [review]
