### PR TITLE
[ios/catalyst] fix leak in NavigationPage

### LINKED ISSUE #20119: Page-level memory leak in NavigationPage on iOS
### Description

NavigationPages are on iOS are not garbage collected after being removed.

Page-level leaks are serious, as they prevent child elements (in this case, whole child pages) from being collected as well.

### Steps to Reproduce

1) Set Application.Current.MainPage to a NavigationPage
2) Swap Application.Current.MainPage with a different page
3) Force GC runs
4) Observe navigation page (and its children) never collected

### Link to public reproduction project repository

https://github.com/AdamEssenmacher/iOSNavigationPageLeak.Maui

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2

### Did you find any workaround?

Calling `DisconnectHandler()` on the NavigationPage's Handler before removing it from use will prevent the navigation page and its children from leaking.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Fixes: https://github.com/dotnet/maui/issues/20119

PR #13833 fixed a leak in child pages of a `NavigationPage`, but it appears there are several cycles that would prevent the `NavigationPage` itself from going away.

So, if you did something like this:

    // The original NavigationPage & children leak
    Application.Current.MainPage = new NavigationPage(new Page1());
    Application.Current.MainPage = new Page2();

I could reproduce the same problem in a new device test.

The cycles (and solutions) are:

1. `NavigationPage` -> `NavigationRenderer` -> `ParentingViewController` -> `NavigationPage`

    * Solution: make `_child` a `WeakReference`

2. `NavigationPage` -> `MenuItemTracker` -> `NavigationPage`

    * Solution: make `_target` a `WeakReference`, and `_additionalTargets` a `List<WeakReference>`

3. `NavigationPage` -> `MenuItemTracker.CollectionChanged` -> `NavigationPage`

    * Solution: subscribe/unsubscribe in `WillMoveToParentViewController`

After these changes the sample app works, and the new device test passes.

### CODE REVIEW

File: src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs [hunk 1]
```diff
@@ -303,9 +303,33 @@ TabbedPage CreateTabbedPage(string title) => new TabbedPage()
 			});
 		}
 
-		[Fact(DisplayName = "NavigationPage Does Not Leak")]
+		[Fact(DisplayName = "Does Not Leak")]
```
Comment (jsuarezruiz) [inline src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs:306]: Pass on iOS but is failing on Windows:
`Reference to Microsoft.Maui.Controls.NavigationPage (type Microsoft.Maui.Controls.NavigationPage is still alive.`
We could create a specific issue to review the leak on Windows and ignore the test on this platform for now.

Comment (jonathanpeppers) [reply src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs:306]: Let me just spend a minute to see if I can fix Windows, too.

File: src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs [hunk 2]
```diff
@@ -303,9 +303,37 @@ TabbedPage CreateTabbedPage(string title) => new TabbedPage()
 			});
 		}
 
-		[Fact(DisplayName = "NavigationPage Does Not Leak")]
+		[Fact(DisplayName = "Does Not Leak"
+#if WINDOWS
+			, Skip = "Failing"
+#endif
```
Comment (jonathanpeppers) [inline src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs:309]: I didn't figure out Windows yet:

image

So I think it's related to one of these lines:

https://github.com/dotnet/maui/blob/8e97f320c59b05ebf3cf09667ea2f6550c7de983/src/Core/src/Platform/Windows/StackNavigationManager.cs#L44

https://github.com/dotnet/maui/blob/8e97f320c59b05ebf3cf09667ea2f6550c7de983/src/Core/src/Platform/Windows/StackNavigationManager.cs#L208

But it's also possible this only fails in tests and not real apps.

**Review by PureWeen — APPROVED** [review]
