### PR TITLE
Change iOS SetNeedsLayout propagation mechanism

### LINKED ISSUE #24996: Changing Translation of an element causes Maui in iOS to constantly run Measure & ArrangeChildren (likely cause of brutal iOS Layout performance issues)
### Description

Maui provides very poor Layout performance on iOS during translations (eg. custom animations, scrolling, or collection view type systems), and I believe I have now found the cause. Hopefully there is an easy workaround or solution. I am open to any suggestions.

This is likely also the cause of the generally poor scrolling and CollectionView performance in iOS as both will also likely depend on translation changes to function, and thus also be subject to these endless re-measures and re-arranges.

## PROBLEM
In a working system, adjusting the translation of an element should NEVER provoke a re-measure/re-layout/re-arrange of the object or all its children. That is the whole point of translation. It is supposed to be a fast and efficient way to adjust the position of something WITHOUT re-doing every measurement and layout.

This is working in Android/Windows. Adjusting the translation of an element does NOT provoke a re-layout/re-arrange of the object or all children. No re-measure or arrange occurs on translation change.

However, in iOS `ArrangeChildren` is being run on every single translation change. And `Measure` is being run extremely often as well provoked by only translation changes (though not quite as often).

This is brutalizing the performance in iOS as any translation change leads to continuous re-layouts and re-measures of all children of the translated object starting from its parent and propagating down through the entire child hierarchy.

## DEMONSTRATION PROJECT

This is demonstrated through the bug project here: https://github.com/jonmdev/iOSTranslationArrangeBug

The project is created in only two files:

[CAbsoluteLayout.cs ](https://github.com/jonmdev/iOSTranslationArrangeBug/blob/main/iOSTranslationArrangeBug/CAbsoluteLayout.cs) - This is a derived class of AbsoluteLayout to implement a custom layout manager so we can see the layouts on debug when they happen through the overrides of `Measure` and `ArrangeChildren`. The custom layout manager is just a simplified copy and paste from Maui's [AbsoluteLayoutManager.cs](https://github.com/dotnet/maui/blob/main/src/Core/src/Layouts/AbsoluteLayoutManager.cs). No special changes.

[App.xaml.cs ](https://github.com/jonmdev/iOSTranslationArrangeBug/blob/main/iOSTranslationArrangeBug/App.xaml.cs) - This is just a simple C# project that adds a few of these Custom Absolute Layout elements to the screen and starts oscillating the position of one. It creates a hierarchy of, by styleId names:

```
"Scroll Window" (AbsoluteLayout)
==="Scroll Content" (AbsoluteLayout)
======Child Abs 0 (AbsoluteLayout)
=========Border
======Child Abs 1 (AbsoluteLayout)
=========Border
======Child Abs 2 (AbsoluteLayout)
=========Border
```

"Scroll Content" is the moved object. In iOS, we will see how arranges and measures are spammed as its translation changes from its parent ("Scroll Window") all the way down through the hierarchy.

### RESULT

One can see if you run this in Windows/Android there are NO ongoing lines showing `Measure` or `ArrangeChildren` are being run (as expected). You will get on project load only once or twice something like:

```
[0:] MEASURE CHILDREN OF: Scroll Window NUM CHILDREN 1
[0:] MEASURE CHILDREN OF: Scroll Content NUM CHILDREN 3
[0:] MEASURE CHILDREN OF: Child Abs 0 NUM CHILDREN 1
[0:] MEASURE CHILDREN OF: Child Abs 1 NUM CHILDREN 1
[0:] MEASURE CHILDREN OF: Child Abs 2 NUM CHILDREN 1
[0:] ARRANGE CHILDREN OF: Scroll Window NUM CHILDREN 1
[0:] ARRANGE CHILDREN OF: Scroll Content NUM CHILDREN 3
[0:] ARRANGE CHILDREN OF: Child Abs 0 NUM CHILDREN 1
[0:] ARRANGE CHILDREN OF: Child Abs 1 NUM CHILDREN 1
[0:] ARRANGE CHILDREN OF: Child Abs 2 NUM CHILDREN 1
```

This is normal behavior in Android/Windows.

However, in iOS, these outputs are spammed on a continuous basis as the translation keeps changing. You will get an infinite number of such re-measurements and re-arranges. The arranges occur on literally every single Translation change while the measures occur only at certain points of the oscillation (unclear why).

In general, manipulating the translations in iOS of anything in the real world with complex hierarchies is extremely costly and nothing runs as smoothly as it should even on high end iOS devices. This is likely why. 

We cannot afford to be re-arranging the whole hierarchy every time a translation occurs and this should not be happening.

## CAUSE / SOLUTION?

Is there any obvious cause or solution that comes to mind? 

Any workaround or solution (or ideas) would be very appreciated.

### Steps to Reproduce

1) Load the bug project. 
2) Run in Windows/Android. See there is no `ArrangeChildren` or `Measure` being run on an ongoing basis.
3) Run in iOS and see these functions are running on a continuous basis as the translation is changed.

### Link to public reproduction project repository

https://github.com/jonmdev/iOSTranslationArrangeBug

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

iOS

### PR DESCRIPTION
**Pull request by albyrock87**
### Description of Change

I've been asked to split #25664 into separate PR.

This is the first piece which aims to change the way we propagate `SetNeedsLayout` by doing that only when MAUI commands.

- The bug I'm solving with this PR is caused by this unwanted propagation when `SetNeedsLayout` is being invoked by iOS
- Moving the propagation to InvalidateMeasure will enable third party libraries to remove the workarounds they've done to propagate `SetNeedsLayout` and don't care about propagation anymore

This also enables us to receive a `SetNeedsLayout` in `TemplatedCell` which will allow us to resize the cell without relaying on `MeasureInvalidated` cross platform event propagation.
There will be a follow-up PR to tackle this.

### Issues Fixed

Fixes #24996

### CODE REVIEW

File: src/Controls/tests/DeviceTests/Elements/CarouselView/CarouselViewTests.cs [hunk 1]
```diff
@@ -147,7 +147,10 @@ await CreateHandlerAndAddToWindow<CarouselViewHandler>(carouselView, async (hand
 				Assert.False(data.IsCollectionChangedEventEmpty);
 			});
 
-			carouselView.Handler?.DisconnectHandler();
+			await InvokeOnMainThreadAsync(() =>
```
[the remark this answers is not in the document]
Comment (albyrock87) [reply src/Controls/tests/DeviceTests/Elements/CarouselView/CarouselViewTests.cs:150]: This is just a device test which randomly fails due to the fact it may run on a background thread. I came across it and it was a quick fix to do.

File: src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt [hunk 2]
```diff
@@ -339,4 +339,4 @@ virtual Microsoft.Maui.Controls.Handlers.Items2.ItemsViewController2<TItemsView>
 virtual Microsoft.Maui.Controls.Handlers.Items2.ItemsViewController2<TItemsView>.UpdateVisibility() -> void
 virtual Microsoft.Maui.Controls.Handlers.Items2.ItemsViewDelegator2<TItemsView, TViewController>.GetVisibleItemsIndex() -> (bool VisibleItems, int First, int Center, int Last)
 virtual Microsoft.Maui.Controls.Handlers.Items2.ItemsViewHandler2<TItemsView>.UpdateLayout() -> void
-override Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer.MovedToWindow() -> void
+*REMOVED*override Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer.SetNeedsLayout() -> void
```
Comment (rmarinho) [inline src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt:342]: I think we can t do this on main right?

Comment (albyrock87) [reply src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt:342]: It's not really "removed": that method is still in the base class so we're not doing a real breaking change here.
Am I missing something?

File: src/Core/src/Platform/iOS/MauiScrollView.cs [hunk 3]
```diff
@@ -1,14 +1,39 @@
...
+
+		public override CGSize ContentSize
+		{
+			get => base.ContentSize;
+			set
+			{
+				base.ContentSize = value;
+
+				// If the ContentSize changed, we need to invalidate the measure of the ScrollView
+				if (_lastContentSize != value)
```
Comment (rmarinho) [inline src/Core/src/Platform/iOS/MauiScrollView.cs:31]: Ok the test that is failing is Issue14557 with CollectionView2 , basically one should not use a CollectionView inside a ScrollView, but what this shows is that with something that will a very large ContentSize can cause infinite loop here.

**Review by rmarinho — DISMISSED** [review]
HeaderAndFooterRender failing with CollectionView2 https://dev.azure.com/xamarin/public/_build/results?buildId=130764&view=ms.vss-test-web.build-test-results-tab&runId=3507758&resultId=100038&paneView=debug

File: src/Core/src/Platform/iOS/MauiScrollView.cs (hunk 3 above)
Comment (albyrock87) [reply src/Core/src/Platform/iOS/MauiScrollView.cs]: This has been solved in #26763 and this PR has been rebased.

File: src/Core/src/Platform/iOS/ViewExtensions.cs [hunk 4]
```diff
@@ -284,14 +284,70 @@ static void UpdateBackgroundLayers(this CALayer[] layers, string layerName, CGRe
...
+					superviewMauiPlatformLayout.InvalidateMeasure(isPropagating: true);
+				}
+				else
+				{
+					superview.SetNeedsLayout();
+				}
+
+				// Potential improvement: if the MAUI view (superview here) is constrained to a fixed size, we could stop propagating
+				// when doing this, we must pay attention to a scenario where a non-fixed-size view becomes fixed-size
+				if (superview is PageView or UIScrollView)
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/ViewExtensions.cs:342]: What happens if the scroll view is in a VSL? Technically it has infinite size. Evil, but it can't explode.

File: src/Core/src/Platform/iOS/MauiScrollView.cs [hunk 5]
```diff
@@ -71,12 +82,23 @@ public override CGSize SizeThatFits(CGSize size)
 			return contentSize;
 		}
 
-		public override void SetNeedsLayout()
+		// overriding this method so it does not automatically scroll large UITextFields
+		// while the KeyboardAutoManagerScroll is scrolling.
+		public override void ScrollRectToVisible(CGRect rect, bool animated)
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/MauiScrollView.cs:87]: nit: maybe move this method back down to reduce/clean the diff.

File: src/Core/src/Platform/iOS/MauiScrollView.cs [hunk 6]
```diff
@@ -6,8 +6,11 @@
 
 namespace Microsoft.Maui.Platform
 {
-	public class MauiScrollView : UIScrollView, IUIViewLifeCycleEvents
+	public class MauiScrollView : UIScrollView, IUIViewLifeCycleEvents, IMauiPlatformView
 	{
+		[UnconditionalSuppressMessage("Memory", "MEM0002", Justification = IUIViewLifeCycleEvents.UnconditionalSuppressMessage)]
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/MauiScrollView.cs:11]: nit: move this back down to reduce diff.

**Review by mattleibow — COMMENTED** [review]
I think I just had 1 question.

File: src/Core/src/Platform/iOS/ViewExtensions.cs (hunk 4 above)
Comment (albyrock87) [reply src/Core/src/Platform/iOS/ViewExtensions.cs:342]: @mattleibow the `MauiScrollView` will invalidate itself.
CV1 and CV2 do the same.

```
				// When the content size changes, we need to adjust the scrollable area size so that the content can fit in it.
				if (ContentSize != contentSize)
				{
					ContentSize = contentSize;

					// Invalidation stops at `UIScrollViews` for performance reasons,
					// but when the content size changes, we need to invalidate the ancestors
					// in case the ScrollView is configured to grow/shrink with its content.
					this.InvalidateAncestorsMeasures();
				}
```

File: src/Controls/src/Core/Compatibility/Handlers/iOS/VisualElementRenderer.cs [hunk 7]
```diff
@@ -93,5 +93,22 @@ void OnSizeChanged(object? sender, EventArgs e)
...
+		}
+
+		void IMauiPlatformView.InvalidateMeasure(bool isPropagating) => SetNeedsLayout();
+
+		public override void MovedToWindow()
+		{
+			base.MovedToWindow();
+			if (_invalidateParentWhenMovedToWindow)
+			{
+				_invalidateParentWhenMovedToWindow = false;
```
Comment (mattleibow) [inline src/Controls/src/Core/Compatibility/Handlers/iOS/VisualElementRenderer.cs:109]: Why set to false here? What happens if we remove from the UI and then add it back? This logic will no longer fire? Or is that intentional?

File: src/Core/src/Platform/iOS/IMauiPlatformView.cs [hunk 8]
```diff
@@ -0,0 +1,7 @@
+namespace Microsoft.Maui.Platform;
+
+internal interface IMauiPlatformView
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/IMauiPlatformView.cs:3]: nit: this is very general and I am not 100% certain we won't need this name for a more general thing. Maybe this can be `IMauiMeasurePlatformView` instead? Thoughts?

**Review by mattleibow — COMMENTED** [review]
super nit as this is an internal type, but if you are still pushing changes then maybe consider this?

File: src/Core/src/Platform/iOS/IMauiPlatformView.cs (hunk 8 above)
Comment (albyrock87) [reply src/Core/src/Platform/iOS/IMauiPlatformView.cs:3]: You're right.. some other ideas:
- `IMeasureInvalidatablePlatformView`
- `IMeasureInvalidationController`

**Comment by mattleibow** [comment]
Is this image change expected? Also, the after still looks wrong because if the image button has no height, then why is the image small? The image was always small, but now it is less weird with all the space. Still wrong, but better wrong? 

image

**Comment by albyrock87** [comment]
> Is this image change expected? Also, the after still looks wrong because if the image button has no height, then why is the image small? The image was always small, but now it is less weird with all the space. Still wrong, but better wrong?

@mattleibow this is the Windows one, so it looked correct to me.

image

The image has no height, true, but it also has `WidthRequest="50"` where the default aspect is `AspectFit`, so that's why the image is small, because it keeps the original aspect while matching the requested width.

**Review by mattleibow — DISMISSED** [review]

**Review by PureWeen — CHANGES_REQUESTED** [review]
- For the PageView type can we just do something possibly a little silly until we address the "potential improvement" comment? Like, just add an internal property on `MauiView` that can be used to do the same thing?  My worry here is that in some cases users are probably inheriting from `ContentView` and providing their own type for the PageHandler. So, if we just set something inside the `SetVirtualView` part of the PageHandler that enables the same short circuiting that won't break anyone. If we're going to change the type here, we'd probably want to do that through a new handler.

- I wonder if we can just get rid of the `InvalidateMeasure` on IPlatformMeasureInvalidationController
  - AFAICT the only types that benefits from this are ScrollView/CollectionView. Everyone else just calls SetNeedsLayout from this
  - for ScrollView can the code that's in there just move to an override of `SetNeedsLayout` ? 
  - For collectionView we could just special case it inside  "InvalidateAncestorsMeasures"  for now since it is the only outlier. I would just be curious as we implement the code for optimizing propagation if this also becomes somewhat unnecessary. We're already special casing UIScrollView inside `InvalidateAncestorsMeasures` so once we evolve this solution a bit then we can hopefully shed these special cases a bit?

File: src/Core/src/Platform/iOS/ViewExtensions.cs [hunk 9]
```diff
@@ -274,14 +274,70 @@ static void UpdateBackgroundLayers(this CALayer[] layers, string layerName, CGRe
...
+			var childMauiPlatformLayout = child as IPlatformMeasureInvalidationController;
+
+			while (true)
 			{
-				platformView.Superview?.SetNeedsLayout();
+				// We verify the presence of a Window to prevent scenarios where an invalidate might propagate up the view hierarchy  
+				// to a SuperView that has already been disposed. Accessing such a disposed view would result in a crash (see #24032).  
+				// This validation is only possible using `IMauiPlatformView`, as it provides a way to schedule an invalidation when the view is moved to window.  
+				// For other cases, we accept the risk since avoiding it could lead to the layout not being updated properly.
+				if (childMauiPlatformLayout != null && child.Window is null)
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/ViewExtensions.cs:307]:
```suggestion
				if (childMauiPlatformLayout is not null && child.Window is null)
```

**Comment by albyrock87** [comment]
@PureWeen 

> just set something inside the `SetVirtualView` part of the `PageHandler` that enables the same short circuiting

As per our conversation, this has been implemented through a new `internal bool IsPage { get; set; }` property on `ContentView`. `PageView` has been removed.

> I wonder if we can just get rid of the `InvalidateMeasure` on IPlatformMeasureInvalidationController

I don't think we can do this, let me explain.

> for ScrollView can the code that's in there just move to an override of SetNeedsLayout ?

`UIScrollView` natively triggers `SetNeedsLayout` *a lot* of times when the user scrolls, that doesn't mean we have to invalidate our measure constraint cache, so we need to differentiate between MAUI invalidation and native invalidation which is the exact root cause of #24996 issue.

> AFAICT the only types that benefits from this are ScrollView/CollectionView. Everyone else just calls SetNeedsLayout from this

This made me think, so I've looked again at `MauiView` and you're right: I'm just calling `SetNeedsLayout()`, but now I think I should move `InvalidateCacheConstraints` from `SetNeedsLayout` to `InvalidateMeasure` so that's what I've done in the last commit.
Now I'm curious to see if this passes the tests: I have many failures locally, even on `main` so I can't verify them all.

File: src/Core/src/Platform/iOS/ImageViewExtensions.cs [hunk 10]
```diff
@@ -87,15 +87,15 @@ internal static CGSize SizeThatFitsImage(
 			double constrainedWidth = Math.Min(contentWidth, constraints.Width);
 			double constrainedHeight = Math.Min(contentHeight, constraints.Height);
 
-			double widthRatio = constrainedWidth / imageSize.Width;
-			double heightRatio = constrainedHeight / imageSize.Height;
+			double widthRatio = constrainedWidth / contentWidth;
+			double heightRatio = constrainedHeight / contentHeight;
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/ImageViewExtensions.cs:91]: These 2 appear to just be used by the if block, so maybe it can move inside?

Comment (mattleibow) [inline src/Core/src/Platform/iOS/ImageViewExtensions.cs:91]: To confirm what I am thinking, this is the size used to determine the size of the control, so you are including the padding in here because iOS does not have a [padding concept?

But, as @PureWeen mentioned - should it be used in the aspect ratio calculations? Maybe it should be added on after the size calculations? For example, if I have a landscape image, but massive padding on top/bottom that makes it become a portrait scale. Will it cause issues with stretch?

Maybe I am thinking wrong here?

**Review by mattleibow — COMMENTED** [review]
Added 2 questions.

File: src/Core/src/Platform/iOS/ImageViewExtensions.cs (hunk 10 above)
Comment (albyrock87) [reply src/Core/src/Platform/iOS/ImageViewExtensions.cs]: Good call, I've updated the algorithm as follows:

- Remove padding from constraints
- Compute desired size on reduced constraints
- Add padding back

**Review by PureWeen — APPROVED** [review]
