### PR TITLE
Fix incorrect clipping using RoundRectangleGeometry

### LINKED ISSUE #6260: Clipping is still not working
### Description

https://github.com/dotnet/maui/pull/5224

Still the above discussed issue is present in RC 1.

I have updated the RC 1 update with the ClipRadiusGallery sample of .NET MAUI sample gallery. Still the corner radius is not set correctly. Only the top left works.

MicrosoftTeams-image

### Steps to Reproduce

Run the .NET MAUI Sample gallery.
Choose the ClipRadiusGallery sample

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Windows 19041

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix incorrect clipping using **RoundRectangleGeometry**.

Fixes #6260

Before
clipping-rounded-issue

After
clipping-rounded-fix

### CODE REVIEW

File: src/Controls/src/Core/Shapes/RoundRectangleGeometry.cs [hunk 1]
```diff
@@ -109,5 +111,24 @@ Geometry GetRoundRectangleGeometry()
 
 			return roundedRectGeometry;
 		}
+
+		public override void AppendPath(Graphics.PathF path)
+		{
+			double density = 1.0d;
+#if ANDROID
+			density = DeviceDisplay.MainDisplayInfo.Density;
```
Comment (rmarinho) [inline src/Controls/src/Core/Shapes/RoundRectangleGeometry.cs:119]: Why do we only want this for Android ?

Comment (jsuarezruiz) [reply src/Controls/src/Core/Shapes/RoundRectangleGeometry.cs:119]: Hey Rui, we talked about this, could you take a look again?. Thanks!

**Review by Redth — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]
