### PR TITLE
[iOS] Implement iOS Platform Specifics

### LINKED ISSUE #5856: Platform Specifics are not working
### Description

Defined Platform Specifics are not working on .NET MAUI.

Android
- [ ] Button UseDefaultPadding and UseDefaultShadow.
- [x] [Entry ImeOptions.](https://github.com/dotnet/maui/pull/5831)
- [x] ~~ImageButton IsShadowEnabled, ShadowColor and ShadowRadius.~~ With the new Shadows API we can achieve the same effect also on all platforms.
- [x] ListView IsFastScrollEnabled.
- [x] NavigationPage BarHeight.
- [x] ~~Page SendDisappearingEventOnPause, SendAppearingEventOnResume and ShouldPreserveKeyboardOnResume.~~ With the new lifecycle events API we can achieve the same.
- [x] [Application WindowSoftInputModeAdjust.](https://github.com/dotnet/maui/pull/5831)
- [x] SwipeView SwipeTransitionMode.
- [x] TabbedPage IsSwipePagingEnabled.
- [x] TabbedPage IsSmoothScrollEnabled.
- [x] ~~ViewCell IsContextActionsLegacyModeEnabled.~~ No longer necessary.
- [x] ~~VisualElement Elevation.~~  With the new ZIndex property can achieve something similar.
- [x] [WebView MixedContentMode, EnableZoomControls and DisplayZoomControls.](https://github.com/dotnet/maui/pull/5831)

iOS
- [x] ~~Application EnableAccessibilityScalingForNamedFontSizes.~~ No longer necessary.
- [x] Cell DefaultBackgroundColor.
- [x] [DatePicker UpdateMode.](https://github.com/dotnet/maui/pull/5879)
- [x] [Entry CursorColor.](https://github.com/dotnet/maui/pull/5879)
- [x] [Entry AdjustsFontSizeToFitWidth.](https://github.com/dotnet/maui/pull/5879)
- [x] FlyoutPage ApplyShadow.
- [x] ContentPage ModalPresentationStyle.
- [x] [NavigationPage PrefersLargeTitles.](https://github.com/dotnet/maui/pull/5879)
- [x] [NavigationPage IsNavigationBarTranslucent.](https://github.com/dotnet/maui/pull/5879)
- [x] ListView GroupHeaderStyle, RowAnimationsEnabled and SeparatorStyle.
- [x] ~~Application  HandleControlUpdatesOnMainThread.~~ No longer necessary.
- [x] Application PanGestureRecognizerShouldRecognizeSimultaneously.
- [x] NavigationPage HideNavigationBarSeparator and StatusBarTextColorMode.
- [x] Page UseSafeArea
- [ ] PrefersHomeIndicatorAutoHidden, PrefersStatusBarHidden and PreferredStatusBarUpdateAnimation. (https://github.com/dotnet/maui/issues/19970)
- [x] [Picker UpdateMode.](https://github.com/dotnet/maui/pull/5879)
- [x] [ScrollView ShouldDelayContentTouches.](https://github.com/dotnet/maui/pull/5879)
- [x] [SearchBar SearchBarStyle.](https://github.com/dotnet/maui/pull/5879)
- [x] SwipeView SwipeTransitionMode.
- [x] TabbedPage TranslucencyMode.
- [x] [TimePicker UpdateMode.](https://github.com/dotnet/maui/pull/5879)
- [x] ~~VisualElement  IsShadowEnabled, ShadowColor, ShadowOpacity and ShadowRadius.~~ With the new Shadows API we can achieve the same effect also on all platforms.
- [x] ~~VisualElement IsLegacyColorModeEnabled.~~ No longer necessary.
- [x] VisualElement BlurEffect and CanBecomeFirstResponder.
- [x] https://github.com/dotnet/maui/issues/12823

Windows
- [x] Application ImageDirectory.
- [ ] FlyoutPage CollapseStyle and CollapsedPaneWidth. While in Xamarin.Forms we used a custom control called FlyoutPageControl where we included properties to manage this Platform Specifics, in .NET MAUI we use RootNavigationView https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.navigationview?view=winui-3.0 without this options without customize the control.
- [x] [InputView DetectReadingOrderFromContent.](https://github.com/dotnet/maui/pull/5855)
- [x] ListView SelectionMode.
- [x] Page ToolbarPlacement.
- [x] [RefreshView RefreshPullDirection.](https://github.com/dotnet/maui/pull/5855)
- [x] [SearchBar IsSpellCheckEnabled.](https://github.com/dotnet/maui/pull/5855)
- [ ] TabbedPage HeaderIconsEnabled.  (https://github.com/dotnet/maui/issues/19969)
 - [x] [VisualElement AccessKey, AccessKeyPlacement, AccessKeyHorizontalOffset and AccessKeyVerticalOffset.](https://github.com/dotnet/maui/pull/5855)
- [x] ~~VisualElement IsLegacyColorModeEnabled.~~ No longer necessary.
- [ ] WebView ExecutionMode. We need to review this case. In Xamarin.Forms we was using Windows.UI.Xaml.Controls.WebView where we can define if hosts HTML content on the UI thread or on a non-UI thread. https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webviewexecutionmode?view=winrt-22000. However, in .NET MAUI we use Microsoft.UI.Xaml.Controls.Webview2 without this option. (see https://github.com/dotnet/maui/issues/6963)
- [ ] WebView IsJavaScriptAlertEnabled. (see https://github.com/dotnet/maui/issues/6963)

More information: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/

### Steps to Reproduce

Verified with the .NET MAUI Gallery.

To verify it just download https://github.com/davidbritch/dotnet-maui-samples/tree/main/PlatformIntegration/PlatformSpecifics
Launch the App in any platform and test any samples.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Windows SDK 10.0.17134.0, Android 11, iOS 15

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Implement iOS Platform Specifics.
- Entry CursorColor.
- Entry AdjustsFontSizeToFitWidth.
- SearchBar SearchBarStyle.
- DatePicker UpdateMode.
- Picker UpdateMode.
- TimePicker UpdateMode.

Fixes (partially) #5856

### CODE REVIEW

File: src/Controls/src/Core/Platform/iOS/Extensions/TextExtensions.cs [hunk 1]
```diff
@@ -1,14 +1,23 @@
...
+﻿using Microsoft.Maui.Controls.Internals;
 using UIKit;
+using Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;
+using Specifics = Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific.Entry;
 
 namespace Microsoft.Maui.Controls.Platform
 {
 	public static class TextExtensions
 	{
+		public static void UpdateCursorColor(this UITextField textField, Entry entry)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/iOS/Extensions/TextExtensions.cs:10]: Entry Cursor Color on iOS https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/entry-cursor-color

File: src/Controls/src/Core/Platform/iOS/Extensions/SearchBarExtensions.cs [hunk 2]
```diff
@@ -1,13 +1,16 @@
...
-using UIKit;
+﻿using UIKit;
 using Microsoft.Maui.Controls.Internals;
+using Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;
 
 namespace Microsoft.Maui.Controls.Platform
 {
 	public static class SearchBarExtensions
 	{
+		public static void UpdateSearchBarStyle(this UISearchBar uiSearchBar, SearchBar searchBar)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/iOS/Extensions/SearchBarExtensions.cs:9]: SearchBar style on iOS https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/searchbar-style

File: src/Controls/src/Core/HandlerImpl/DatePicker/DatePicker.iOS.cs [hunk 3]
```diff
@@ -0,0 +1,13 @@
+﻿using Microsoft.Maui.Controls.Platform;
+using Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;
+
+namespace Microsoft.Maui.Controls
+{
+	public partial class DatePicker
+	{
+		public static void MapUpdateMode(DatePickerHandler handler, DatePicker datePicker)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/HandlerImpl/DatePicker/DatePicker.iOS.cs:8]: DatePicker item selection on iOS https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/datepicker-selection

File: src/Controls/src/Core/HandlerImpl/Picker/Picker.iOS.cs [hunk 4]
```diff
@@ -0,0 +1,13 @@
+﻿using Microsoft.Maui.Controls.Platform;
+using Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;
+
+namespace Microsoft.Maui.Controls
+{
+	public partial class Picker
+	{
+		public static void MapUpdateMode(PickerHandler handler, Picker picker)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/HandlerImpl/Picker/Picker.iOS.cs:8]: Picker Item Selection on iOS https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/picker-selection

File: src/Controls/src/Core/HandlerImpl/TimePicker/TimePicker.iOS.cs [hunk 5]
```diff
@@ -0,0 +1,13 @@
+﻿using Microsoft.Maui.Controls.Platform;
+using Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific;
+
+namespace Microsoft.Maui.Controls
+{
+	public partial class TimePicker
+	{
+		public static void MapUpdateMode(TimePickerHandler handler, TimePicker timePicker)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/HandlerImpl/TimePicker/TimePicker.iOS.cs:8]: TimePicker item selection on iOS https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/timepicker-selection

File: src/Controls/src/Core/HandlerImpl/Entry/Entry.iOS.cs [hunk 6]
```diff
@@ -2,6 +2,16 @@
 {
 	public partial class Entry
 	{
+		public static void MapCursorColor(EntryHandler handler, Entry entry)
+		{
+			Platform.TextExtensions.UpdateCursorColor(handler.PlatformView, entry);
+		}
+
+		public static void MapAdjustsFontSizeToFitWidth(EntryHandler handler, Entry entry)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/HandlerImpl/Entry/Entry.iOS.cs:10]: Entry Font Size on iOS https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/entry-font-size

**Review by mattleibow — COMMENTED** [review]
Looking decent. Have not tested yet.

**Review by rmarinho — COMMENTED** [review]
Didn't test it all yet but here some that didn't work for me: can you take a look @jsuarezruiz  ? 

Blur - doesn’t work
Picker - doesn’t work 
SafeArea - doesn’t work
 Slider Update on tap - doesn’t work 
 Hide Status bar - doesn’t work 
TimePicker - doesn’t work

**Comment by rmarinho** [comment]
Can we also add this to the gallery, we might need to inject the ICommand to go back

**Comment by rmarinho** [comment]
Also the PR descriptions says Windows, but it's iOS

**Comment by rmarinho** [comment]
Ok finished review everything, here's what works and doesn't work..

```
Blur - doesn’t work
DatePicker - works 
AdjustFont - works 
VisualElement - ? 
Flyout Page - works
Hide Home - ?  
Large titles - seems it doesn’t work
 Listview - works
  ListView/cell - works 
  Modal form sheet - seems can’t get it to work 	 
Navigation - IsNavigationBarTranslucent doesn’t work
Pan gesture - yes 
Picker - doesn’t work 
SafeArea - doesn’t work
ScrollView touches - works 
SearchBar Style - works
 Slider Update on tap - doesn’t work 
 Hide Status bar - doesn’t work 
SwipeView - works
TimePicker - doesn’t work 
NavigationPage Translucent tab - doesn’t work
TabbedPage translucent - doesn’t work
```

**Review by rmarinho — APPROVED** [review]
Fixed the pickers, everything less the NavigationBar translucent seem to be working

File: src/Core/src/Handlers/DatePicker/DatePickerHandler.MacCatalyst.cs [hunk 7]
```diff
@@ -13,6 +13,8 @@ protected override UIDatePicker CreatePlatformView()
 			;
 		}
 
+		internal bool UpdateImmediately { get; set; }
```
[the remark this answers is not in the document]
Comment (rmarinho) [reply src/Core/src/Handlers/DatePicker/DatePickerHandler.MacCatalyst.cs]: Yeah makes sense since there's no "Done" button for this on catalyst

[the remark this answers is not in the document]
Comment (mattleibow) [reply src/Core/src/Handlers/DatePicker/DatePickerHandler.MacCatalyst.cs]: What about the other mac catalyst platforms? Is this not needed on iOS?

[the remark this answers is not in the document]
Comment (rmarinho) [reply src/Core/src/Handlers/DatePicker/DatePickerHandler.MacCatalyst.cs]: i m not sure i follow

[the remark this answers is not in the document]
Comment (mattleibow) [reply src/Core/src/Handlers/DatePicker/DatePickerHandler.MacCatalyst.cs]: I mean you set the value to true in 1 file, but there are 3 pickers each with 2 files mac/ios.
