### PR TITLE
[controls] fix memory leak with Grid Row/ColumnDefinitions

### LINKED ISSUE #15860: .Net Maui 7 and 8 Preview Android Performing a full GC + Crash Collection View Back Forward
### Description

After using the app for 1- 2 minutes back and forward (Shell) to a collectionView Page with Observable Collection I receive "Performing a full GC" than a i get a crash in .Net Maui 7 and 8 Preview Android in any Physical device : Google Pixel 6, etc Performing a full GC + Crash

I saw some similar issue reports but they are closed as solved and i can't comment.

IOS works without problems.

### Steps to Reproduce

-

### Link to public reproduction project repository

https://github.com/lucianparvu/MauiApp16.App

### Version with bug

7

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

-

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #15986: Pages retained in memory when using DynamicResource Grid style
### Description

In a .NET MAUI Shell app running on Windows it looks like pages referencing DynamicResource Grid styles are held in memory after navigating to and then away from the page. This results in an increase in memory over time as pages are opened and closed.

### Steps to Reproduce

Setup 
1. Create new Maui app. File -> New Solution -> Maui App
2. Add the following style to `Styles.xaml`:
```
<Style x:Key="GridContainer" TargetType="Grid">
    <Setter Property="Grid.RowDefinitions" Value="Auto,*" />
    <Setter Property="Grid.ColumnDefinitions" Value="*,Auto" />
</Style>
```
3. Create two new MAUI ContentPages `StyledPage` and `UnstyledPage`
4. Add a `Grid` element to both of the newly created pages
   4a. To the `StyledPage` add:
   ```
   <Grid Style="{DynamicResource GridContainer}">
    <Label 
        Grid.Row="0" Grid.ColumnSpan="2"
        Text="This is the first row"
        VerticalOptions="Center" 
        HorizontalOptions="Center" />
    <Label 
        Grid.Row="1" Grid.ColumnSpan="2"
        Text="This is the second row"
        VerticalOptions="Center" 
        HorizontalOptions="Center" />
   </Grid>
   ```
   4b. To the `UnstyledPage` add:
   ```
   <Grid RowDefinitions="Auto, *" ColumnDefinitions="*, Auto">
    <Label 
        Grid.Row="0" Grid.ColumnSpan="2"
        Text="This is the first row"
        VerticalOptions="Center" 
        HorizontalOptions="Center" />
    <Label
        Grid.Row="1" Grid.ColumnSpan="2"
        Text="This is the second row"
        VerticalOptions="Center" 
        HorizontalOptions="Center" />
   </Grid>
   ```
3. Add a Button to the `MainPage` with a clicked event `await Navigation.PushAsync(new StyledPage());`
4. Add a Button to the `MainPage` with a clicked event `await Navigation.PushAsync(new UnstyledPage());`
5. Add a Button to the `MainPage` with a clicked event `GC.Collect();`

Testing
1. Run the app targeting Windows
2. Navigate to the `StyledPage`
3. Click the back button
4. Click the `GC Collect` button
5. Take a snapshot of the memory usage
6. Navigate to the `UnstyledPage`
7. Click the back button
8. Click the `GC Collect` button
9. Take a snapshot of the memory usage
10. Repeat as many times as necessary

Result: Looking at the memory usage snapshots the number of instances of `StyledPage` in memory increases with the number of times the page has been opened. 

image

image

Expected: The page should no longer exist in memory after navigating away, the number of instances in memory should not increase as the page is repeatedly opened. This works correctly for the `UnstyledPage`.

### Link to public reproduction project repository

https://github.com/duffh/MauiStylesMemoryLeakTestApp

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Fixes: https://github.com/dotnet/maui/issues/15860
Fixes: https://github.com/dotnet/maui/issues/15986

In a customer's app, they have the setup:

    
    <Style TargetType="Grid" x:Key="GridStyleWithColumnDefinitions">
        <Setter Property="ColumnDefinitions" Value="18,*"/>
    </Style>

Then a page with:

    <Grid Style="{StaticResource GridStyleWithColumnDefinitions}" />

Navigating forward & back from this page would show that the entire `Page` would live forever! What is interesting, is simply removing the Grid's `Style` solved the problem?!?

I narrowed this down to a unit test:

    [Fact]
    public async Task ColumnDefinitionDoesNotLeak()
    {
        // Long-lived column, like from a Style in App.Resources
        var column = new ColumnDefinition();
        WeakReference reference;

        {
            var grid = new Grid();
            grid.ColumnDefinitions.Add(column);
            reference = new(grid);
        }

        await Task.Yield();
        GC.Collect();
        GC.WaitForPendingFinalizers();

        Assert.False(reference.IsAlive, "Grid should not be alive!");
    }

https://github.com/dotnet/maui/blob/cda3eb3381cfb686567ed05e3eb8e8f26c02d785/src/Controls/src/Core/Layout/Grid.cs#L20

`Grid` subscribes to `DefinitionCollection<T>.ItemSizeChanged`, and in this case the `DefinitionCollection<T>` lived indefinitely in an application-wide `ResourceDictionary`.

The simplest solution is to make the `ItemSizeChanged` event use `WeakEventManager` as was done for other events like `Application.RequestedThemeChanged`:

https://github.com/dotnet/maui/blob/cda3eb3381cfb686567ed05e3eb8e8f26c02d785/src/Controls/src/Core/Application/Application.cs#L221-L225

Since MAUI owns the property, we can use the simple solution here.

This is one issue solved in the customer app, but I will need to retest the app in #15860 to see if there are further issues.

### CODE REVIEW

File: src/Controls/src/Core/DefinitionCollection.cs [hunk 1]
```diff
@@ -101,13 +102,15 @@ public void RemoveAt(int index)
 			OnItemSizeChanged(this, EventArgs.Empty);
 		}
 
-		public event EventHandler ItemSizeChanged;
+		public event EventHandler ItemSizeChanged
+		{
+			add => _weakEventManager.AddEventHandler(value);
+			remove => _weakEventManager.RemoveEventHandler(value);
+		}
```
Comment (jonathanpeppers) [inline src/Controls/src/Core/DefinitionCollection.cs:109]: There are some existing tests that check this event still fires:

https://github.com/dotnet/maui/blob/cda3eb3381cfb686567ed05e3eb8e8f26c02d785/src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs#L77-L78

https://github.com/dotnet/maui/blob/cda3eb3381cfb686567ed05e3eb8e8f26c02d785/src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs#L98-L99

**Comment by jonathanpeppers** [comment]
I did some testing and I think this does actually fix: https://github.com/dotnet/maui/issues/15860

File: src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs [hunk 2]
```diff
@@ -184,5 +186,45 @@ public void ColumnDefinitionsGetBindingContext()
...
 		}
+
+		[Fact]
+		public async Task ColumnDefinitionDoesNotLeak()
+		{
+			// Long-lived column, like from a Style in App.Resources
+			var column = new ColumnDefinition();
+			WeakReference reference;
+
+			{
```
Comment (rachelkang) [inline src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs:197]: I'm a bit confused by this syntax - what do the brackets do here? Should there be a condition or something else prefacing this code block?

File: src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs [hunk 3]
```diff
@@ -184,5 +186,45 @@ public void ColumnDefinitionsGetBindingContext()
...
+		}
+
+		[Fact]
+		public async Task RowDefinitionDoesNotLeak()
+		{
+			// Long-lived row, like from a Style in App.Resources
+			var row = new RowDefinition();
+			WeakReference reference;
+
+			{
```
Comment (rachelkang) [inline src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs:217]: same question here

File: src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs [hunk 4]
```diff
@@ -184,5 +186,45 @@ public void ColumnDefinitionsGetBindingContext()
...
+				var grid = new Grid();
+				grid.ColumnDefinitions.Add(column);
+				reference = new(grid);
+			}
+
+			await Task.Yield();
+			GC.Collect();
+			GC.WaitForPendingFinalizers();
+
+			Assert.False(reference.IsAlive, "Grid should not be alive!");
```
Comment (rachelkang) [inline src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs:207]: Can you help me understand what's going on behind the scenes here? What are the "pending finalizers" in WaitForPendingFinalizers?

File: src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs (hunk 2 above)
Comment (jonathanpeppers) [reply src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs:197]: The `{ }` puts `var grid` out of scope at the end of the block, so you can no longer access `grid` after the closing brace. It's like a mini-method/function.

I might have been able to set it `null` instead, but this way is probably better.

**Comment by rachelkang** [comment]
> The simplest solution is to make the ItemSizeChanged event use WeakEventManager as was done for other events

How does that work exactly? How does using WeakEventManager solve the issue of the DefinitionCollection<T> living indefinitely?

(not reviewing, just asking questions to learn)

File: src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs (hunk 4 above)
Comment (jonathanpeppers) [reply src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs:207]: Because the GC is not deterministic... It can be hard to write a test to check for a memory leak.

Through trial and error, I've found this works reliably (at least in .NET 6+):

* `await Task.Yield()` - a simple way to get the second half of the test on a different thread
* `GC.Collect()` - runs the GC, but it's not 100% what it decides actually clean up.
* `GC.WaitForPendingFinalizers()`, waits on any finalizers like `~` you can define in classes. It's possible we could remove this call and the test still pass.

All this work is to force the GC to run and cleanup `var grid`, and assert it is gone at the end.

In the past, though... We had to do weird things like this for Xamarin apps:

* https://github.com/xamarin/java.interop/commit/220b87fbbb8d986c2c8951757aa3ea45d8e7e7eb

**Comment by jonathanpeppers** [comment]
> How does using WeakEventManager solve the issue of the DefinitionCollection living indefinitely?

When you make a C# event:

```csharp
class Child {
    public event EventHandler MyEvent;
```

If you are inside a class `Parent` and do:

```csharp
child.MyEvent += this.OnMyEvent; // let's say this is inside the Parent's constructor

void OnMyEvent(object sender, EventArgs e) { }
```

The `child` now has a "strong" reference to the parent. If you put a breakpoint and looked at `child.MyEvent` the `EventHandler` has a `Target` property that points to the parent. This feels kind of backwards in the design of these two types: `Parent` should have a strong reference to `Child` like a `List<Child> Children { get; set; }`, but we now have the reverse, too. This is a general problem with all C# events.

`WeakEventManager` holds a `WeakReference` to the subscriber instead:

https://github.com/dotnet/maui/blob/ed18303d2490715c564dd49b02b8d89b0a1003e5/src/Core/src/WeakEventManager.cs#L157

A `WeakReference` is a special type that allows the subscriber to be collected by the GC. You can access `WeakReference.IsAlive` or `WeakReference.Target` will return `null` if the object is gone.

So now `Grid` has a strong reference to the `DefinitionCollection` via `Grid.ColumnDefinitions`, but `DefinitionCollection` only have a weak reference back to the `Grid`.

File: src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs (hunk 2 above)
Comment (rachelkang) [reply src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs:197]: interesting, thanks for explaining!

File: src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs (hunk 4 above)
Comment (rachelkang) [reply src/Controls/tests/Core.UnitTests/Layouts/GridLayoutTests.cs:207]: gotcha, thanks for elaborating!

**Comment by rachelkang** [comment]
Interesting! Learned so much, thanks :)

> This is a general problem with all C# events.

Would you say this design was intentional or more of an oversight? Is there anything that is generally _good_ about the child having a strong reference to the parent?

**Comment by jonathanpeppers** [comment]
I think C# events have been like this since .NET Framework 1.0. Back then there was only WinForms, no WPF or MVVM patterns. Most events were used for things like `Button.Click`. It seems like it would harder to create memory leaks with only WinForms. It was definitely better than if you wrote an app back then in C++.

There is an api proposal about making "weak events" a thing:

* https://github.com/dotnet/runtime/issues/61517

**Review by haritha-mohan — APPROVED** [review]

**Comment by jonathanpeppers** [comment]
@rachelkang I wrote down some of the comments here for the future. Should be useful to us and customers:

https://github.com/dotnet/maui/wiki/Memory-Leaks

I didn't write a section about circular references in iOS/Catalyst yet. There is unfortunately more I need to add here...

**Review by hartez — APPROVED** [review]
