### PR TITLE
[iOS] Changing carousel view orientation with disabled loop - fix

### LINKED ISSUE #28523: [CarouselView] Different behavior on iOS and Android when Loop = False
### Description

when loop = false and when the device is oriented in landscape mode, the display is different under iOS and Android

Image

Image

### Steps to Reproduce

[Loop.zip](https://github.com/user-attachments/files/19350120/Loop.zip)

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.50 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

When the device orientation changes, the ViewDidLayoutSubviews method is triggered. Inside this method, _carouselViewLoopManager.CenterIfNeeded(CollectionView, IsHorizontal) is called. This eventually leads to CollectionView.ReloadData(), which ensures proper sizing adjustments when the orientation changes.

However, if the carousel view is not looping, _carouselViewLoopManager.CenterIfNeeded is not invoked. To fix this, I call _carouselViewLoopManager.CenterIfNeeded inside TraitCollectionDidChange when the carousel view does not have looping enabled.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/28523

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/98243f29-758f-4ff4-bba9-22c526f445ae" width="300px"/>|<video src="https://github.com/user-attachments/assets/187587af-8689-4161-a0be-ba77c6185d68" width="300px"/>|

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs [hunk 1]
```diff
@@ -32,6 +32,20 @@ public class CarouselViewController : ItemsViewController<CarouselView>
 
 		bool _isRotating;
 
+		public override void TraitCollectionDidChange(UITraitCollection previousTraitCollection)
+		{
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs:36]: let s say the initial view is horizontal, and then I rotate to vertical, don t I still need to reload the data?

Comment (kubaflo) [reply src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs:36]: We want to reload the data. And it will reload because previousTraitCollection.VerticalSizeClass would be `compact` and TraitCollection.VerticalSizeClass `regular`

**Review by mattleibow — APPROVED** [review]
