### PR TITLE
Fix setting bottom tab icon title

### LINKED ISSUE #12105: Shell Tabbar doesn't behave correctly when changing tab icon image (through binding or style triggers)
### Description

Changing the App Shell tab icon using style triggers or through property binding causes the tab bar icon to behave incorrectly:

1) Icon image changing mechanism starts to work after few initial clicks on tab bar icon.
2) There is a strange icon shuffling/rearranging animation on tab icon change. See: https://github.com/dotnet/maui/issues/11520
3) Tabbarselected color isn't maintained correctly when tab bar icon is being changed. It requires additional click to switch to correct state.

### Steps to Reproduce

1. Change Tab Icon Image through Style triggers or property binding

f.i:

<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MauiIssueRepro.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiIssueRepro"
    Shell.FlyoutBehavior="Disabled">

    <Shell.Resources>
        <Style x:Key="BrowseTab1" TargetType="Tab">
            <Style.Triggers>
                <Trigger TargetType="Tab" Property="IsChecked" Value="False">
                    <Setter Property="Icon" Value="radio_off.png" />
                </Trigger>
                <Trigger TargetType="Tab" Property="IsChecked" Value="True">
                    <Setter Property="Icon" Value="radio_on.png" />
                </Trigger>
            </Style.Triggers>
        </Style>
        <Style x:Key="BrowseTab2" TargetType="Tab">
            <Style.Triggers>
                <Trigger TargetType="Tab" Property="IsChecked" Value="False">
                    <Setter Property="Icon" Value="radio_off.png" />
                </Trigger>
                <Trigger TargetType="Tab" Property="IsChecked" Value="True">
                    <Setter Property="Icon" Value="radio_on.png" />
                </Trigger>
            </Style.Triggers>
        </Style>
        <Style x:Key="BrowseTab3" TargetType="Tab">
            <Style.Triggers>
                <Trigger TargetType="Tab" Property="IsChecked" Value="False">
                    <Setter Property="Icon" Value="radio_off.png" />
                </Trigger>
                <Trigger TargetType="Tab" Property="IsChecked" Value="True">
                    <Setter Property="Icon" Value="radio_on.png" />
                </Trigger>
            </Style.Triggers>
        </Style>
    </Shell.Resources>

    <TabBar>
        <Tab
            Title="Quotations"
            Icon="radio_off.png"
            Style="{StaticResource BrowseTab1}">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" Route="MainPage1" />
        </Tab>
        <Tab
            Title="Logout"
            Icon="radio_off.png"
            Style="{StaticResource BrowseTab2}">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" Route="MainPage2" />
        </Tab>
        <Tab
            Title="Timer"
            Icon="radio_off.png"
            Style="{StaticResource BrowseTab3}">
            <ShellContent ContentTemplate="{DataTemplate local:MainPage}" Route="MainPage3" />
        </Tab>
    </TabBar>

</Shell>

### Link to public reproduction project repository

https://github.com/MK1985/MauiShellTabBarIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android SDK 30-33

### Did you find any workaround?

Didn't find any

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

Since the beginning, Shell has always just reset the entire bottom nav menu whenever the icon/title has changed. I'm guessing this was a quick make-it-work scenario when `Shell` was first built. This PR just updates the modified tab icon/title so we don't see a reshuffling behavior when text/images are changed. If Tabs are removed/added the icons also won't reshuffle anymore. 

### Issues Fixed
Fixes #12105

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs [hunk 1]
```diff
@@ -369,32 +373,60 @@ protected virtual void OnMoreSheetDismissed(object sender, EventArgs e)
...
+				}
 
-				var menuItem = _bottomView.Menu.FindItem(index);
-				UpdateShellSectionEnabled(content, menuItem);
-			}
-			else if (e.PropertyName == BaseShellItem.TitleProperty.PropertyName ||
-				e.PropertyName == BaseShellItem.IconProperty.PropertyName)
-			{
-				SetupMenu();
+				if (menuItem != null)
```
Comment (mandel-macaque) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs:397]: is not over !=

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs [hunk 2]
```diff
@@ -406,12 +438,43 @@ protected virtual void OnTabReselected(ShellSection shellSection)
 
 		protected virtual void SetupMenu(IMenu menu, int maxBottomItems, ShellItem shellItem)
 		{
+			if (_menuSetup)
+			{
+				if (_updateMenuItemIcon != null &&
+					_updateMenuItemSource != null &&
```
Comment (mandel-macaque) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs:444]: Same, is not

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs [hunk 3]
```diff
@@ -406,12 +438,43 @@ protected virtual void OnTabReselected(ShellSection shellSection)
...
+					_bottomView.IsAlive() &&
+					_bottomView?.IsAttachedToWindow == true)
```
Comment (mandel-macaque) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs:446]: This is quite strange. You have a _bottonView.IsAlive () followed by a _bottonView?.IsAttachedToWindow. Either the first call can throw a NRE or the second call does not need the ?. I would make more sense to do:
```suggestion
					_bottomView?.IsAlive() &&
					_bottomView?.IsAttachedToWindow == true)
```

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs [hunk 4]
```diff
@@ -406,12 +438,43 @@ protected virtual void OnTabReselected(ShellSection shellSection)
...
+					_updateMenuItemSource = null;
+					_updateMenuItemIcon = null;
+
+					UpdateShellSectionIcon(shellSection, menuItem);
+					return;
+				}
+				else if (_updateMenuItemTitle != null &&
+					_updateMenuItemSource != null &&
+					_bottomView.IsAlive() &&
+					_bottomView?.IsAttachedToWindow == true)
```
Comment (mandel-macaque) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs:459]: What is the diff between the following to if statements:

Previous one:
```csharp
				if (_updateMenuItemIcon != null &&
					_updateMenuItemSource != null &&
					_bottomView.IsAlive() &&
					_bottomView?.IsAttachedToWindow == true)
```
This:
```csharp
				else if (_updateMenuItemTitle != null &&
					_updateMenuItemSource != null &&
					_bottomView.IsAlive() &&
					_bottomView?.IsAttachedToWindow == true)
```
The diff is just the first part of the clause, I'm not sure how expensive are the method calls, but a null check is very cheap, you can merge both to something similar to:
```csharp
if (updateMenuItemSource != null &&
 	_bottomView?.IsAlive() &&
 	_bottomView?.IsAttachedToWindow == true) {
    if (_updateMenuItemSource != null) {
      // update here
    } else if (_updateMenuItemTitle != null) {
     // update here
   }
}
```

File: src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs [hunk 5]
```diff
@@ -39,6 +40,31 @@ internal static void UpdateEnabled(bool tabEnabled, IMenuItem menuItem)
...
+			(string title, ImageSource icon, bool tabEnabled) item,
+			IMenu menu,
+			int index,
+			int currentIndex,
+			BottomNavigationView bottomView,
+			IMauiContext mauiContext,
+			out IMenuItem menuItem)
+		{
+			Task returnValue;
+			using (var title = new Java.Lang.String(item.title))
```
Comment (mandel-macaque) [inline src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs:53]:
```suggestion
			using var title = new Java.Lang.String(item.title);
```
And remove not needed indentation.

File: src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs [hunk 6]
```diff
@@ -88,12 +118,17 @@ internal static void UpdateEnabled(bool tabEnabled, IMenuItem menuItem)
 
 			if (loadTasks.Count > 0)
 				await Task.WhenAll(loadTasks);
+		}
 
-			foreach (var menuItem in menuItems)
-				menuItem.Dispose();
+		internal static void SetMenuItemTitle(IMenuItem menuItem, string title)
+		{
+			using (var jTitle = new Java.Lang.String(title))
```
Comment (mandel-macaque) [inline src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs:125]:
```suggestion
			using var jTitle = new Java.Lang.String(title);
```
And remove not needed indentation

File: src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs [hunk 7]
```diff
@@ -109,8 +144,13 @@ static async Task SetMenuItemIcon(IMenuItem menuItem, ImageSource source, IMauiC
...
 				context.Context);
 
-			if (menuItem.IsAlive() && result is not null)
-				menuItem.SetIcon(result.Value);
+			if (menuItem.IsAlive())
+			{
+				if (result is not null)
+					menuItem.SetIcon(result.Value);
+				else
+					menuItem.SetIcon(null);
```
Comment (mandel-macaque) [inline src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs:152]: this can be made much simpler:
```suggestion
				menuItem.SetIcon(result?.Value);
```
A single line will have the same effect.

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs (hunk 3 above)
Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs:446]: Added `[NotNullWhen(true)]` to `IsAlive` so we can make the compiler happy with regards to the nullability checking

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs (hunk 4 above)
Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs]: Yea it's probably a micro-optimization but I just didn't want any of this code to run if both `_updateMenuItemIcon ` and `_updateMenuItemTitle ` are null. 

I shifted it around a bit to have left stuff but still left a check in for those two so that the if statement can get short circuited before calling things on `BottomView` which will traverse the bridge

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs [hunk 8]
```diff
@@ -406,12 +438,41 @@ protected virtual void OnTabReselected(ShellSection shellSection)
 
 		protected virtual void SetupMenu(IMenu menu, int maxBottomItems, ShellItem shellItem)
 		{
+			if ((_updateMenuItemIcon is not null || _updateMenuItemTitle is not null) &&
+				_menuSetup &&
+				_updateMenuItemSource is not null &&
+				_bottomView.IsAlive() &&
+				_bottomView.IsAttachedToWindow == true)
```
Comment (mandel-macaque) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs:445]: Unless IsAttachedToWindows does some magic, we do not need the "=="
```suggestion
				_bottomView.IsAttachedToWindow)
```

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs [hunk 9]
```diff
@@ -406,12 +438,41 @@ protected virtual void OnTabReselected(ShellSection shellSection)
...
+				}
+			}
+
 			if (DisplayedPage == null)
 				return;
 
 			if (ShellItemController.ShowTabs)
 			{
 				_menuSetup = true;
+
```
Comment (mandel-macaque) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs:475]: At least in the iOS team we try to make the diffs as small as possible:
```suggestion
```

File: src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs [hunk 10]
```diff
@@ -48,29 +72,33 @@ internal static void UpdateEnabled(bool tabEnabled, IMenuItem menuItem)
...
+			while (items.Count < menu.Size())
+			{
+				menu.RemoveItem(menu.GetItem(menu.Size() - 1).ItemId);
+			}
+
 			int numberOfMenuItems = items.Count;
 			bool showMore = numberOfMenuItems > maxBottomItems;
 			int end = showMore ? maxBottomItems - 1 : numberOfMenuItems;
 
-
```
Comment (mandel-macaque) [inline src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs:56]: Same, smaller diffs == less work v(even when is just a space)

File: src/Core/src/Platform/Android/JavaObjectExtensions.cs [hunk 11]
```diff
@@ -14,15 +15,15 @@ public static bool IsDisposed(this global::Android.Runtime.IJavaObject obj)
...
+		public static bool IsAlive([NotNullWhen(true)] this Java.Lang.Object? obj)
 		{
 			if (obj == null)
 				return false;
 
 			return !obj.IsDisposed();
 		}
 
-		public static bool IsAlive(this global::Android.Runtime.IJavaObject? obj)
+		public static bool IsAlive([NotNullWhen(true)] this global::Android.Runtime.IJavaObject? obj)
```
Comment (mandel-macaque) [inline src/Core/src/Platform/Android/JavaObjectExtensions.cs:26]: <3

File: src/Core/src/Platform/Android/JavaObjectExtensions.cs [hunk 12]
```diff
@@ -14,15 +15,15 @@ public static bool IsDisposed(this global::Android.Runtime.IJavaObject obj)
 			return obj.Handle == IntPtr.Zero;
 		}
 
-		public static bool IsAlive(this Java.Lang.Object? obj)
+		public static bool IsAlive([NotNullWhen(true)] this Java.Lang.Object? obj)
```
Comment (mandel-macaque) [inline src/Core/src/Platform/Android/JavaObjectExtensions.cs:18]: <3

File: src/Core/src/Platform/Android/JavaObjectExtensions.cs (hunk 11 above)
Comment (mandel-macaque) [inline src/Core/src/Platform/Android/JavaObjectExtensions.cs:26]: @PureWeen This looks like an unrelated change to the one of the PR. Is a GOOD change but adding it in this PR could put you in a bad situation. Imaging that you have to revert this commit because it introduced a bug, it will also remove this GOOD but unrelated changed. I would move it to a new smaller PR just with the use of the attribute because:

1. Will allow you to revert
2. Will give better history and a better context for the change.
3. The rest of the team will lear about the attr.

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]
