### PR TITLE
[Windows] Fix unwanted corner radius in Shell flyout items

### LINKED ISSUE #17414: Default stylings for controls does not work!
### Description

By default, I mean that I have completely turned off styling by not loading the Styles.xaml and Colors.xaml in App.xaml. Supposedly with ALL styling left to the defaults of the controls, some defaults are being set that should not be. Case in point, where is the corner radius coming from in the flyout menu?

image

I had also opened an issue, There is no way to set the text color of a Switch control #8965, a long time ago and @jfversluis unilaterally closed the issue by telling me to go write some platform-specific code. This is truly a poor way to run things. When customers open issues, it is not acceptable to simply close them because MS doesn't want to do something. I have ranted MANY times that you guys thought that the xamarin rewrite would satisfy everyone, but you have screwed the desktop community completely. Why can't a Switch control be styled?

So, some controls have styling that cannot be overcome without a TON of work on the customer's behalf. We, the customers, are under tight enough deadlines as it is to make this stuff work without having to resort to billions of lines of platform-specific code to make things work. If that were the case, who needs MAUI??????? EVERYTHING WAS EASILY STYLABLE IN WPF!!!

### Steps to Reproduce

1. Create new unmodified Maui app
2. Comment out the loading of  Colors and Styles:
```
<ResourceDictionary.MergedDictionaries>
    <!--<ResourceDictionary Source="Resources/Styles/Colors.xaml" />
    <ResourceDictionary Source="Resources/Styles/Styles.xaml" />-->
</ResourceDictionary.MergedDictionaries>
```
3. Set `FlyoutBehavior="Flyout"`
4. Run this VERY simple app...

### Link to public reproduction project repository

_No response_

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

Nooooooooooooooooooooooooo

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Shalini-Ashokan**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue Details
Shell flyout items on Windows display unwanted corner radius styling when no explicit styling is applied.

### Root Cause
NavigationView's RootSplitView container has a corner radius applied by default in the WinUI control template, which creates visual inconsistency.

### Description of Change
Modified the default corner radius to zero by explicitly setting `RootSplitView.CornerRadius = new Microsoft.UI.Xaml.CornerRadius(0)` in the MauiNavigationView.OnApplyTemplate() method.

Validated the behavior in the following platforms
 
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac
 
### Issues Fixed
  
Fixes #17414 

### Output  ScreenShot

| Before  | After  |
|---------|--------|
| Before-Fix |  After-Fix |

### CODE REVIEW

File: src/Core/src/Platform/Windows/MauiNavigationView.cs [hunk 1]
```diff
@@ -134,6 +134,8 @@ protected override void OnApplyTemplate()
 			// It causes the content to not be flush up against the title bar
 			PaneContentGrid.Margin = new WThickness(0, 0, 0, 0);
 			UpdateMenuItemsContainerHeight();
+			RootSplitView.CornerRadius = new UI.Xaml.CornerRadius(0);
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Windows/MauiNavigationView.cs:137]: Could be possible to apply the fix in the NavigationView Resources? https://github.com/dotnet/maui/blob/d9ba88443396f42e582d63877ab318f3e57aac9f/src/Core/src/Platform/Windows/Styles/WindowRootViewStyle.xaml#L68
In that way, developers that would like to keep the previous behavior or override it, can do easily just creating single resources and not require to override classes.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Windows/MauiNavigationView.cs (hunk 1 above)
Comment (Shalini-Ashokan) [reply src/Core/src/Platform/Windows/MauiNavigationView.cs:137]: @jsuarezruiz, Thank you for the suggestion! After investigating WinUI's [NavigationView](https://github.com/microsoft/microsoft-ui-xaml/blob/b1db15715bfead9fe8ad2e7f78b0172589225e69/src/controls/dev/NavigationView/NavigationView.xaml#L7) template, I found that [RootSplitView](https://github.com/microsoft/microsoft-ui-xaml/blob/b1db15715bfead9fe8ad2e7f78b0172589225e69/src/controls/dev/NavigationView/NavigationView.xaml#L289) uses the `OverlayCornerRadius` resource key directly, and changing this global key would affect all overlay scenarios. Since there's no specific resource key for NavigationView's RootSplitView CornerRadius, the C# approach ensures we only target our specific NavigationView instance without impacting other UI elements.

**Review by jsuarezruiz — APPROVED** [review]
