### PR TITLE
[Android] Fix crash on Picker with null and fix up handler to not use INCC

### LINKED ISSUE #8377: Java.Lang.NullPointerExceptionon picker if property bound to ItemDisplayBinding is null
### Description

On Android if you tap on a picker and one of the items in the bound list returns null for the ItemDisplayBinding then the application crashes.

### Steps to Reproduce

1. Launch attached project on Android: https://github.com/ajphall/PickerCrash
2. Tap the picker
3. Crash 

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

_No response_

### Relevant log output

```shell
[AndroidRuntime] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
[AndroidRuntime] 	at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:454)
[AndroidRuntime] 	at android.widget.ArrayAdapter.getView(ArrayAdapter.java:416)
[AndroidRuntime] 	at android.widget.AbsListView.obtainView(AbsListView.java:2410)
[AndroidRuntime] 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
[AndroidRuntime] 	at android.widget.ListView.onMeasure(ListView.java:1323)
[AndroidRuntime] 	at android.view.View.measure(View.java:25671)
[AndroidRuntime] 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6987)
[AndroidRuntime] 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[AndroidRuntime] 	at android.view.View.measure(View.java:25671)
[AndroidRuntime] 	at com.android.internal.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:146)
[AndroidRuntime] 	at com.android.internal.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:71)
[AndroidRuntime] 	at android.view.View.measure(View.java:25671)
[AndroidRuntime] 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6987)
[AndroidRuntime] 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[AndroidRuntime] 	at android.view.View.measure(View.java:25671)
[AndroidRuntime] 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6987)
[AndroidRuntime] 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[AndroidRuntime] 	at android.view.View.measure(View.java:25671)
[AndroidRuntime] 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6987)
[AndroidRuntime] 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[AndroidRuntime] 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:776)
[AndroidRuntime] 	at android.view.View.measure(View.java:25671)
[AndroidRuntime] 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3744)
[AndroidRuntime] 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2493)
[AndroidRuntime] 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2795)
[AndroidRuntime] 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2206)
[AndroidRuntime] 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8763)
[AndroidRuntime] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
[AndroidRuntime] 	at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
[AndroidRuntime] 	at android.view.Choreographer.doFrame(Choreographer.java:1049)
[AndroidRuntime] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:938)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:233)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:8068)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
**Java.Lang.NullPointerException:** 'Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference'
```

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

- Fix crash on Android Picker with null ItemDisplayBinding.
- Removed INCC subscriptions inside handlers because these will cause memory leaks. The INCC changes should propagate from the VirtualView via a call to MapItems not inside the handler.
- https://github.com/dotnet/maui/issues/8845

fix-8377

### Issues Fixed

Fixes #8377

### CODE REVIEW

**Comment by rmarinho** [comment]
Is it possible to add a device test?

File: src/Core/src/Core/Extensions/IPickerExtension.cs [hunk 1]
```diff
@@ -6,9 +6,9 @@ namespace Microsoft.Maui
 	public static class IPickerExtension
 	{
 		public static string[] GetItemsAsArray(this IPicker picker)
-			=> Enumerable.Range(0, picker.GetCount()).Select(i => picker.GetItem(i)).ToArray();
+			=> Enumerable.Range(0, picker.GetCount()).Select(picker.GetItem).ToArray();
```
Comment (PureWeen) [inline src/Core/src/Core/Extensions/IPickerExtension.cs:9]: Cant this be converted away from Linq?

**Review by hartez — APPROVED** [review]
