### PR TITLE
Fixed the RealParent Warning shown issue

### LINKED ISSUE #23050: Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
### Description

Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui

### Steps to Reproduce

I'm reporting the bug as instructed by the Application Output

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell
Thread started:  #19
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Thread started: <Thread Pool> #305
Thread started: <Thread Pool> #306
2024-06-14 01:31:19.551411+0100 App.Sign[83286:8791825] //TabBar/HomePage/D_FAULT_PolicyPage16
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
2024-06-14 01:31:22.122925+0100 App.Sign[83286:8791825] //TabBar/HomePage/D_FAULT_PolicyPage16/D_FAULT_IdentityPage17
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
2024-06-14 01:31:24.329648+0100 App.Sign[83286:8791825] //TabBar/HomePage/D_FAULT_PolicyPage16
Thread started:  #307
Thread finished: <Thread Pool> #293
Thread finished: <Thread Pool> #305
Thread started:  #308
Thread started:  #309
Thread started:  #310
Thread started:  #311
Thread started:  #312
Thread started:  #313
Thread started:  #314
Thread started:  #315
Thread started:  #316
Thread started:  #317
Thread started:  #318
Thread started:  #319
Thread started: <Thread Pool> #320
Thread started:  #321
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Thread started: <Thread Pool> #322
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: '(null)' cannot be converted to type 'Syncfusion.Maui.Core.BadgeType'
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Microsoft.Maui.Controls.Element: Warning: The RealParent on Microsoft.Maui.Controls.Shapes.RoundRectangle has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui
Thread started:  #323
Thread started:  #324
Thread started:  #325
2024-06-14 01:33:49.373138+0100 App.Sign[83286:8791825] 
Unhandled Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1[[Sign.Api.Models.Core.ActivityData, Sign.Api.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 index)
   at System.Collections.ObjectModel.Collection`1[[Sign.Api.Models.Core.ActivityData, Sign.Api.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].System.Collections.IList.get_Item(Int32 index)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.ElementAt(Int32 index)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.get_Item(Int32 index)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.get_Item(NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetSizeForItem(NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewDelegator`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.ReorderableItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetSizeForItem(UICollectionView collectionView, UICollectionViewLayout layout, NSIndexPath indexPath)
   at UIKit.UICollectionView.InsertItems(NSIndexPath[] indexPaths) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UICollectionView.g.cs:line 478
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.<>c__DisplayClass42_0.<Add>b__0(UICollectionView c)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.Update(Action`1 update, NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.Add(NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.CollectionChanged(NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.<>c__DisplayClass38_0.<CollectionChanged>b__0()
   at Foundation.NSAsyncActionDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 150
--- End of stack trace from previous location ---
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2594
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 60
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at App.Sign.Program.Main(String[] args) in /Users/snufff/Projects/Sign/MAUI.App.Sign/MAUI.App.Sign/Platforms/iOS/Program.cs:line 13
2024-06-14 01:33:49.381410+0100 App.Sign[83286:8791825] Unhandled managed exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (System.ArgumentOutOfRangeException)
   at System.Collections.Generic.List`1[[Sign.Api.Models.Core.ActivityData, Sign.Api.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 index)
   at System.Collections.ObjectModel.Collection`1[[Sign.Api.Models.Core.ActivityData, Sign.Api.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].System.Collections.IList.get_Item(Int32 index)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.ElementAt(Int32 index)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.get_Item(Int32 index)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.get_Item(NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetSizeForItem(NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewDelegator`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.ReorderableItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetSizeForItem(UICollectionView collectionView, UICollectionViewLayout layout, NSIndexPath indexPath)
   at UIKit.UICollectionView.InsertItems(NSIndexPath[] indexPaths) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UICollectionView.g.cs:line 478
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.<>c__DisplayClass42_0.<Add>b__0(UICollectionView c)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.Update(Action`1 update, NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.Add(NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.CollectionChanged(NotifyCollectionChangedEventArgs args)
   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.<>c__DisplayClass38_0.<CollectionChanged>b__0()
   at Foundation.NSAsyncActionDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 150
--- End of stack trace from previous location ---
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2594
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 60
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at App.Sign.Program.Main(String[] args) in /Users/snufff/Projects/Sign/MAUI.App.Sign/MAUI.App.Sign/Platforms/iOS/Program.cs:line 13

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10e8136d5 - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x10e7b20de - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x10e9acb08 - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : sigabrt_signal_handler.cold.1
	0x10e813010 - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : mono_runtime_setup_stat_profiler
	0x127f37fdd - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x0 - Unknown
	0x128405d30 - /Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib : abort
	0x10df9b0a7 - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libxamarin-dotnet-debug.dylib : xamarin_unhandled_exception_handler
	0x10e8b0ce4 - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : mono_invoke_unhandled_exception_hook
	0x10e7b1cdf - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : mono_handle_exception_internal
	0x10e7afd25 - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : mono_handle_exception
	0x10e827b09 - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : interp_throw
	0x10e825c5c - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : interp_throw_ex_general
	0x10e81fe85 - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : mono_interp_exec_method
	0x10e814f63 - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : interp_runtime_invoke
	0x10e8fb2d8 - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : mono_runtime_invoke_checked
	0x10e902c1b - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : mono_runtime_exec_main_checked
	0x10e767742 - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libmonosgen-2.0.dylib : mono_jit_exec
	0x10dfaebea - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/libxamarin-dotnet-debug.dylib : xamarin_main
	0x1027d3794 - /Users/snufff/Library/Developer/CoreSimulator/Devices/720B152D-9442-4AF9-97F9-7C56CA7A7FBA/data/Containers/Bundle/Application/57AAABE1-B6BF-4717-B6A4-62E6FF0F5CD0/App.Sign.app/App.Sign : main
	0x10b22c3e0 - Unknown
	0x203142366 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x12844714a):0x12844713a  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
0x12844714a  73 08 48 89 c7 e9 cc 99 ff ff c3 90 90 90 b8 53  s.H............S
0x12844715a  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 b4 99  ...I....s.H.....
0x12844716a  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...........I....

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
```

### PR DESCRIPTION
**Pull request by Ahamed-Ali**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root Cause of the issue

- When navigating from a first page (with a button) to a second page containing controls like Image, Label, or Border, a warning occurs if properties such as StrokeShape, Image.Source, or Label.FormattedText are bound to values from a ViewModel that was implemented as a static (singleton) instance.

For example, if a StrokeShape is created and stored statically, it is instantiated only once during the first navigation. On subsequent navigations, the same instance is reused. Since elements like StrokeShape maintain a reference to their previous parent, reusing the same instance causes conflicts and triggers warnings due to improper parent-child relationships.

### Description of Change

- Accesses RealParent in a safe way to prevent warnings from occurring when the parent has already been removed or collected. 

### Issues Fixed

Fixes #23050 

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Screenshot

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/eaa822b1-0c4c-4eff-bf8d-4e3b6c5227f0"> | <video src="https://github.com/user-attachments/assets/7b7aac0b-d1d5-48e5-ab88-a68cf992e8d7"> |

### CODE REVIEW

File: src/Controls/src/Core/Element/Element.cs [hunk 1]
```diff
@@ -397,7 +399,7 @@ void SetParent(Element value)
 
 			if (_parentOverride == null)
 			{
-				OnParentChangingCore(Parent, value);
+				OnParentChangingCore(ParentOverride ?? GetRealParent(false), value);
```
[the remark this answers is not in the document]
Comment (Ahamed-Ali) [reply src/Controls/src/Core/Element/Element.cs]: Optimized the fix based on suggestion

File: src/Controls/src/Core/Element/Element.cs [hunk 2]
```diff
@@ -333,30 +333,32 @@ internal Element ParentOverride
...
-				{
-					Application.Current?
-						.FindMauiContext()?
-						.CreateLogger<Element>()?
-						.LogWarning($"The RealParent on {this} has been Garbage Collected. This should never happen. Please log a bug: https://github.com/dotnet/maui");
-				}
-
 				return null;
 			}
+			if (_realParent.TryGetTarget(out var parent))
```
Comment (MartyIX) [inline src/Controls/src/Core/Element/Element.cs]: Isn't it the safest to store

```cs
var realParent = _realParent;
if (realParent is null) { return null;}
if (...) 
...
```
?

I believe that `if (_realParent.TryGetTarget(out var parent))` can still lead to NRE because `_realParent` can become null at any moment.

File: src/Controls/src/Core/Element/Element.cs [hunk 3]
```diff
@@ -333,30 +333,32 @@ internal Element ParentOverride
 		}
 
 		WeakReference<Element> _realParent;
-		/// <summary>For internal use by .NET MAUI.</summary>
-		[EditorBrowsable(EditorBrowsableState.Never)]
-		public Element RealParent
+		Element GetRealParent(bool logWarningIfParentHasBeenCollected = true)
 		{
-			get
+			if (_realParent is null)
```
Comment (PureWeen) [inline src/Controls/src/Core/Element/Element.cs]: Inline with @MartyIX 's comment can we just do all this in an if statement?

something like

```C#
if (_realParent is WeakRef wr &&  wr.TryGetTarget(out var parent))
```

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Element/Element.cs (hunk 3 above)
Comment (MartyIX) [reply src/Controls/src/Core/Element/Element.cs]: Perhaps the syntax

```cs
if (_realParent is {} wr &&  wr.TryGetTarget(out var parent))`
```

is even better as `_realParent`'s type can get changed and this might be missed then. I know it's unlikely but I find it a good rule of thumb to avoid getting burn.

**Review by PureWeen — CHANGES_REQUESTED** [review]
Can you review the changes here as well https://github.com/dotnet/maui/pull/30291 and see if the test is relevant.
Just pull over whatever changes seem correct into this PR

Copilot made a good point about nulling out the weakref as well since that's going to lead to repetative logging messages when retrieving the parent

File: src/Controls/src/Core/Element/Element.cs (hunk 3 above)
Comment (Ahamed-Ali) [reply src/Controls/src/Core/Element/Element.cs]: If we check whether _realParent is null and its type in a single if statement, it may still fall into the else block when _realParent is null, causing unintended logging. Therefore, it's better to check for null separately and return early. @PureWeen

**Comment by Ahamed-Ali** [comment]
> Can you review the changes here as well #30291 and see if the test is relevant. Just pull over whatever changes seem correct into this PR
> 
> Copilot made a good point about nulling out the weakref as well since that's going to lead to repetative logging messages when retrieving the parent

I have included the valid changes from the Copilot PR into this PR, specifically addressing the `clearing` of the weak reference when the target object has been collected. 

Additionally, I have included the tests from the Copilot PR. While the test passes both with and without the fix—since the warning issue, based on investigation, occurs in a static element during random multiple navigations—the test is still valid for verifying the RealParent. Therefore, I have included it. @PureWeen

File: src/Controls/src/Core/Element/Element.cs [hunk 4]
```diff
@@ -333,30 +333,39 @@ internal Element ParentOverride
...
```
Comment (PureWeen) [inline src/Controls/src/Core/Element/Element.cs]: Just for an over abundance of caution can we just store `_realParent` to a local variable and use that throughout the method? 

I'm not sure how possible this is but, let's say in theory the UI Thread gets paused after this if statement and it clears out the `_realParent` and then something ends up setting it to null.

That probably won't happen but we might as well just guard for it

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Element/Element.cs [hunk 5]
```diff
@@ -333,30 +333,39 @@ internal Element ParentOverride
 		}
 
 		WeakReference<Element> _realParent;
-		/// <summary>For internal use by .NET MAUI.</summary>
-		[EditorBrowsable(EditorBrowsableState.Never)]
-		public Element RealParent
+		Element GetRealParent(bool logWarningIfParentHasBeenCollected = true)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Element/Element.cs]: Because can return null, maybe a better name for the method would be `TryGetRealParent`

Comment (jsuarezruiz) [inline src/Controls/src/Core/Element/Element.cs]: Not sure if possible, but, if this method might be called from multiple threads, consider adding synchronization around the `_realParent` assignment.

`readonly object _realParentLock = new object();`

File: src/Controls/tests/Core.UnitTests/ElementTests.cs [hunk 6]
```diff
@@ -313,5 +313,62 @@ public void ChildRemoved()
 			root.Children.Remove(child);
 			Assert.True(removed);
 		}
+
+		[Fact]
+		public void RealParent_ReturnsNullAfterParentGarbageCollected()
```
Comment (jsuarezruiz) [inline src/Controls/tests/Core.UnitTests/ElementTests.cs:318]: Can include another test?
- RealParent_ReturnsNull_WhenNoParentSet

and maybe something like:
- RealParent_IsThreadSafe_WhenAccessedConcurrently

**Review by jsuarezruiz — DISMISSED** [review]

File: src/Controls/src/Core/Element/Element.cs (hunk 4 above)
Comment (Ahamed-Ali) [reply src/Controls/src/Core/Element/Element.cs]: I have stored _realParent in a local variable and used it within the method.  @PureWeen

File: src/Controls/src/Core/Element/Element.cs (hunk 5 above)
Comment (Ahamed-Ali) [reply src/Controls/src/Core/Element/Element.cs]: I have renamed the method to TryGetRealParent. @jsuarezruiz

File: src/Controls/tests/Core.UnitTests/ElementTests.cs (hunk 6 above)
Comment (Ahamed-Ali) [reply src/Controls/tests/Core.UnitTests/ElementTests.cs:318]: I have included the relevant tests @jsuarezruiz

File: src/Controls/src/Core/Element/Element.cs (hunk 5 above)
Comment (Ahamed-Ali) [reply src/Controls/src/Core/Element/Element.cs]: I think storing _realParent in a local variable is sufficient to handle this scenario. @jsuarezruiz 
 
https://github.com/dotnet/maui/pull/30156#discussion_r2177256986

File: src/Controls/src/Core/Element/Element.cs [hunk 7]
```diff
@@ -397,7 +406,7 @@ void SetParent(Element value)
 
 			if (_parentOverride == null)
 			{
-				OnParentChangingCore(Parent, value);
+				OnParentChangingCore(ParentOverride ?? realParent, value);
```
Comment (PureWeen) [inline src/Controls/src/Core/Element/Element.cs]: At this point is it ok to just call "Parent" ? 

In theory "TryGetRealParent" on line 398 will have set the weakreference to null if it's been collected so we won't get a logging message at this point right?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Element/Element.cs (hunk 7 above)
Comment (Ahamed-Ali) [reply src/Controls/src/Core/Element/Element.cs]: Yes, I have updated the `Parent` directly @PureWeen

**Review by PureWeen — APPROVED** [review]
