### PR TITLE
Fix crash using BackButtonBehavior and navigating to root

### LINKED ISSUE #10514: BackbuttonBehavior with custom command throws 'Object reference not set to an instance of an object' exception.
### Description

When I override the back button behavior using a RelayCommand in a ViewModel an exception is being thrown:
'Object reference not set to an instance of an object'.

I can set a breakpoint at `await Shell.Current.GoToAsync("..");` and after the command has been executed the exception occurs.

### Steps to Reproduce

1. Create a new Maui App
2. Add CommunityToolkit MVVM nuget package
3. Create a Viewmodel for a i.e. details page
4. Create a Contentpage and set the viewmodel as binding context
5. In the viewmodel create a relay command for the back operation (await Shell.Current.GoToAsync("..");)
6. In the contentpage override the backbuttonbehavior and bind the command to the viewmodels "BackCommand"
7. In Mainpage change the button clicked eventhandler to navigate to the details page (Shell.Current.GoToAsync(nameof(DetailsPage));)
8. Register the route for the detailspage
9. Register the details page and viewmodel in mauiprogram (builder.Services.Add...)

The main page will be registered as a singleton, the details page and viewmodel as transient.

Start the app, klick the button to go to the details page. Click the back button... then boom ;)

### Link to public reproduction project repository

https://github.com/FM1973/RepoBackButtonBehavior.git

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

No

### Relevant log output

```shell
Resolved pending breakpoint at 'DetailsViewModel.cs:16,1' to void RepoBackButtonBehavior.Viewmodels.DetailsViewModel.<Back>d__0.MoveNext () [0x0000f].
[Choreographer] Skipped 278 frames!  The application may be doing too much work on its main thread.
[OpenGLRenderer] Davey! duration=4646ms; Flags=0, IntendedVsync=70079283607535, Vsync=70083916940683, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=70083927350700, AnimationStart=70083927366900, PerformTraversalsStart=70083927477000, DrawStart=70083927641400, SyncQueued=70083927789300, SyncStart=70083928224200, IssueDrawCommandsStart=70083928271200, SwapBuffers=70083929047600, FrameCompleted=70083930328700, DequeueBufferDuration=514600, QueueBufferDuration=459500, GpuCompleted=0, 
**System.NullReferenceException:** 'Object reference not set to an instance of an object.'
```

### LINKED ISSUE #11401: NullReferenceException from ShellToolbar OnBackButtonCanExecuteChanged
### Description

In a ContentPage I added a BackButtonBehavior to Call a Command in my ViewModel to call

 await Shell.Current.Navigation.PopToRootAsync(false);

The shell pops to root which is nice. But after this I get a  NullReferenceException from

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.ShellToolbar.<UpdateBackbuttonBehavior>g__OnBackButtonCanExecuteChanged|11_1(Object sender, EventArgs e)
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.<set_ExecutionTask>g__MonitorTask|26_0(AsyncRelayCommand this, Task task)
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at Program.Main(String[] args) in //Program.cs:line 14

The root page of the shell does not have a BackButtonBehavior. Only the page I navigated from contains a BackButtonBehavior.

By looking at the code of UpdateBackbuttonBehavior in ShellToolbar I would see the following issue.
If someone calls NotifyCanExecuteChanged after navigating to a page containing no BackButtonBehavior it can happen that _backButtonBehavior is null in OnBackButtonCanExecuteChanged.

### Steps to Reproduce

1. Create a new Shell App
2. Navigate to a Contentpage containing a BackButtonBehavior from root page.
3. In Backcommand await Shell.Current.Navigation.PopToRootAsync(false);
4. Force Invocation of CanExecute of the Command that Handled the Back Press and still the _backButtonCommand in ShellToolbar

### Link to public reproduction project repository

none

### Version with bug

6.0.486

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS and android

### Did you find any workaround?

Clearing the Command Binding from the BackButtonBehavior during OnNavigatingFrom in my ContetnPage

protected override void OnNavigatingFrom(NavigatingFromEventArgs args)
{
    // Remark: Work around for nullpointer during use of BackButtonBehaviour.
    var behaviour = Shell.GetBackButtonBehavior(this);
    behaviour?.ClearValue(BackButtonBehavior.CommandProperty);
}

causes a OnBackButtonPropertyChanged in ShellToolbar and this unsubscribes the OnBackButtonCanExecuteChanged handler throwing the exception.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix crash using BackButtonBehavior and navigating to root.

`ShellToolbar` had a bunch of excess code for figuring out changes to the `Command` property on `BackButtonBehavior`. All of that code is already inside `BackButtonBehavior` so I just deleted it. 

### Issues Fixed

Fixes #11401 
Fixes #10514

### CODE REVIEW

File: src/Controls/src/Core/ShellToolbar.cs [hunk 1]
```diff
@@ -166,7 +166,7 @@ void OnBackButtonPropertyChanged(object sender, System.ComponentModel.PropertyCh
 			void OnBackButtonCanExecuteChanged(object sender, EventArgs e)
 			{
 				BackButtonEnabled =
-					_backButtonCommand.CanExecute(_backButtonBehavior.CommandParameter);
+					_backButtonCommand != null && _backButtonCommand.CanExecute(_backButtonBehavior?.CommandParameter);
```
Comment (PureWeen) [inline src/Controls/src/Core/ShellToolbar.cs:169]: Can you add tests here? https://github.com/dotnet/maui/blob/cc8a118b51cd2fe9af0dc9d87933d49b4576080e/src/Controls/tests/Core.UnitTests/ShellTests.cs#L1328

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/ShellToolbar.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/ShellToolbar.cs:169]: Added.
Captura de pantalla 2022-11-22 a las 12 21 49

Comment (PureWeen) [reply src/Controls/src/Core/ShellToolbar.cs:169]: I don't know if the test is quite covering the scenario here.  If I breakpoint the offending code the test never triggers that code

image

File: src/Controls/src/Core/ShellToolbar.cs [hunk 2]
```diff
@@ -166,7 +166,7 @@ void OnBackButtonPropertyChanged(object sender, System.ComponentModel.PropertyCh
 			void OnBackButtonCanExecuteChanged(object sender, EventArgs e)
```
Comment (PureWeen) [inline src/Controls/src/Core/ShellToolbar.cs:166]: I think the issue might be related to these being local functions. Can you move all of these so they are class instance methods opposed to local functions?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/ShellToolbar.cs [hunk 3]
```diff
@@ -140,37 +135,20 @@ void UpdateBackbuttonBehavior()
...
+		}
 
-			void OnBackButtonCanExecuteChanged(object sender, EventArgs e)
-			{
-				BackButtonEnabled =
-					_backButtonCommand.CanExecute(_backButtonBehavior.CommandParameter);
-			}
+		void OnBackButtonCommandPropertyChanged(object? sender, PropertyChangedEventArgs e)
+		{
+			ApplyChanges();
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/ShellToolbar.cs:148]: `ApplyChanges` update if the back button is enabled or not but also the title, or Platform Specifics, maybe we can only update here the stuff related with the back button?

Comment (PureWeen) [reply src/Controls/src/Core/ShellToolbar.cs:148]: Yea, I thought about that. My concern is that things will get missed because there are related pieces of logic and trying to be too precise with what gets re-evaluated will miss things. Especially as logic is added in the future. 

For example, this code here look at the button visibility for toolbar visibility

image

 `ApplyChanges` only fires property changes to the platform if those values have changed so for the most part, it should be a light amount of work to re-evaluate.

**Review by PureWeen — APPROVED** [review]

**Review by rachelkang — APPROVED** [review]
LGTM! Confirmed this fixes the 2 issues referenced as well
