### PR TITLE
Setting binding on Label doesn't set text to incoming binding

### LINKED ISSUE #16636: [regression/8.0.0-preview.7.8842] Bug: Multiple platforms Editor & Entry Two Way binding to text
1) Create an editor
2) Bind its text property to attached BindingContext ViewModel
3) Enter some text into the editor
4) Change the text value in the viewModel

Expected Results:
Views editors text updates

Actual Results:
Views editor keeps old text. However, I can see that the getter is hit indicating the view does come up for it. Backing field for text binding is also correctly set.

The issue is reproducible on MacCatalyst, iOS And Android. @drasticactions has also confirmed on WinUI

Previously working in .Net 7

Repo: https://github.com/SamuelJames101/EditorAndEntryBugNet8

### LINKED ISSUE #16720: [regression/8.0.0-preview.7.8842] Binding Issue: Multiple platform Slider control 'Value'
### Description

Slider control ValueProperty will not update using a bound property.

### Steps to Reproduce

1. Create a Slider
2. Bind its Value property to a BindableProperty
3. Slider value remains at 0

### Link to public reproduction project repository

https://github.com/Stedy59/StedySoft.BindingIssues.1

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK - all, Android API 34

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #16721: [regression/8.0.0-preview.7.8842] Binding Issue: Multiple platform CheckBox control 'IsChecked'
### Description

CheckBox control IsCheckedProperty will not update using a bound property.

### Steps to Reproduce

Create a Checkbox
Bind its IsChecked property to a BindableProperty
Checkbox IsChecked remains at initial value

### Link to public reproduction project repository

https://github.com/Stedy59/StedySoft.BindingIssues.4

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK - all, Android API 34

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #16722: [regression/8.0.0-preview.7.8842] Binding Issue: Multiple platform Label control - Multiple properties
### Description

Label control Text, TextColor will not update using a bound properties.

### Steps to Reproduce

Create a Label Control OR load a ControlTemplate with a Label Control as a child
Set the Text/Text Color values during creation OR bound via 'TemplateBinding'
Bind its Text/Text Color properties to BindableProperties
Label  Text/Text Color will not update after the BindableProperties are updated

### Link to public reproduction project repository

https://github.com/Stedy59/StedySoft.BindingIssues.3

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK - all, Android API 34

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #16723: [regression/8.0.0-preview.7.8842] Binding Issue: Multiple platform - Binding a property after an animation fails
### Description

**Clock Example** - After applying the control template, I modify the clock hands by rotating them to the current time. Then bind the RotationProperty.
`
_ = this.Dispatcher.Dispatch(() => {
    DateTime dt = DateTime.Now;
    new Animation {
        { 0, 1, new Animation(v => this._imgClockHour.Rotation = v, 0, 30 * (dt.Hour % 12) + 0.5 * dt.Minute) },
        { 0, 1, new Animation(v => this._imgClockMinute.Rotation = v, 0, 6 * dt.Minute + 0.1 * dt.Second) },
        { 0, 1, new Animation(v => this._imgClockSecond.Rotation = v, 0, 6 * dt.Second + 0.006 * dt.Millisecond) }
    }.Commit(
	this,
	"CurrentTimeAnimation",
	length: (uint)TimeSpan.FromSeconds(1.5).TotalMilliseconds,
	easing: Easing.SinOut,
	finished: async (v, c) => {
			_ = this._imgClockHour.Bind(Image.RotationProperty, path: "HourAngle", source: ClockManager.Current);
			_ = this._imgClockMinute.Bind(Image.RotationProperty, path: "MinuteAngle", source: ClockManager.Current);
			_ = this._imgClockSecond.Bind(Image.RotationProperty, path: "SecondAngle", source: ClockManager.Current);
		await ClockManager.Current.StartAsync();
	});
});

`

### Steps to Reproduce

Expected outcome is that the RotationProperty would bind to the backing bindable.

### Link to public reproduction project repository

https://github.com/Stedy59/StedySoft.BindingIssues.2

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK - all, Android API 34

### Did you find any workaround?

For this example yes... but many others in my Framework would require linking the PropertyChanged event for every property effected. That is not feasible nor appropriate.

### Relevant log output

_No response_

### LINKED ISSUE #16859: Binding of Entry control seems to break after entering text in Entry
### Description

When using an Entry control in a page with a Binding to an `ObservableProperty` of type `string` in a ViewModel, updating its `Text` content from that ViewModel works. After editing the Entry in the app (using the keyboard), the entry seems to stop "listening" to the ObservableProperty - its Text value cannot be set anymore from the ViewModel. To demontrate this see the animation below, where we added three Entries to show the effect: all Entries update each other via the Binding and the Button, but as soon as some text is entered manually in an entry, it no longer updates via the Binding.

repro-binding
__

### Steps to Reproduce

1. Create an empty .NET MAUI project
2. Add one or more `Entry` controls to a page (e.g. the MainPage)
3. Bind their Text to a property of the MainPage's `ViewModel`
4. Add a button to that Page
5. Let that button update the value of the Binding
6. Run the app
7. Click the button (and see that it works)
8. Edit the text of one of the Entry controls
9. Click the button again and see that the text of the edited Entry no longer updates

### Link to public reproduction project repository

https://github.com/ppluijten/dotnet-maui-binding-issue-repro

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13, SDK 33

### Did you find any workaround?

Not yet

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

Fix `SetBinding` so it will replace any `manual` value set by a user.

Fixes #16723
Fixes #16722
Fixes #16720
Fixes #16721
Fixes #16636
Fixes #16859

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
not a bug, the manual value has precedence over the binding, even if set after

File: src/Controls/tests/Core.UnitTests/LabelTests.cs [hunk 1]
```diff
@@ -178,6 +178,15 @@ public void EntryCellYAlignBindingMatchesVerticalTextAlignmentBinding()
 			Assert.Equal(TextAlignment.End, labelVerticalTextAlignment.VerticalTextAlignment);
 		}
 
+		[Fact]
+		public void OriginalLabelTextNotUpdatingAfterBindingIsSet()
+		{
```
Comment (jsuarezruiz) [inline src/Controls/tests/Core.UnitTests/LabelTests.cs:183]: The test was added to validate that this scenario fails?.
Captura de pantalla 2023-08-03 a las 16 25 15

**Review by rmarinho — APPROVED** [review]
