### PR TITLE
[iOS] Fixed memory leak with PopToRootAsync when using TitleView

### LINKED ISSUE #28201: NavigationPage.TitleView causes memory leak with PopToRootAsync
### Description

It seems if I add `NavigationPage.TitleView` into a `ContentPage`'s XAML, the page will never be destroyed if it's popped from the navigation stack with `PopToRootAsync`, leading to an accumulation of pages in memory. It is destroyed if I use `PopAsync` instead. It is also destroyed with `PopToRootAsync` if I remove the `NavigationPage.TitleView`.

### Steps to Reproduce

1. Create a new Maui app project in Visual Studio (.NET 9)
2. Modify `App.xaml.cs`, `MainPage.xaml.cs`, and `MainPage.xaml` with the below snippets
3. Start the app in an iOS simulator (mine is iPhone 15 iOS 18.1). If you click Push, Pop, Push, Pop, etc. you will notice that after 10-20 repetitions "Destroyed" is logged to the console (as many as the number of unloaded pages), indicating that the pages were destroyed.
4. Restart the app. If you click Push, Pop To Root, Push, Pop To Root, etc. you will not see "Destroyed" even after many repetitions. (unless you accidentally clicked Pop)
5. (optional) Remove the `NavigationPage.TitleView`, and if you repeat step 4 you will see that now "Destroyed" is being logged.

**MainPage.xaml** (and replace MauiApp7 in x:Class with your project name)
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp7.MainPage">
    <NavigationPage.TitleView>
        <Label>Test</Label>
    </NavigationPage.TitleView>
    <ScrollView>
        <VerticalStackLayout
            Padding="30,0"
            Spacing="25">
            <Image
                Source="dotnet_bot.png"
                HeightRequest="185"
                Aspect="AspectFit"
                SemanticProperties.Description="dot net bot in a hovercraft number nine" />

            <Label
                Text="Hello, World!"
                Style="{StaticResource Headline}"
                SemanticProperties.HeadingLevel="Level1" />

            <Label
                Text="Welcome to &#10;.NET Multi-platform App UI"
                Style="{StaticResource SubHeadline}"
                SemanticProperties.HeadingLevel="Level2"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I" />

            <Button
                x:Name="PushBtn"
                Text="Push" 
                Clicked="OnPushClicked"
                HorizontalOptions="Fill" />

            <Button
                x:Name="PopBtn"
                Text="Pop" 
                Clicked="OnPopClicked"
                HorizontalOptions="Fill" />

            <Button
                x:Name="PopToRootBtn"
                Text="Pop To Root" 
                Clicked="OnPopToRootClicked"
                HorizontalOptions="Fill" />
        </VerticalStackLayout>
    </ScrollView>
</ContentPage>
```

**MainPage.xaml.cs**
```c#
public partial class MainPage : ContentPage
{
    public MainPage()
    {
        Console.WriteLine("Created");
        InitializeComponent();
    }

    ~MainPage()
    {
        Console.WriteLine("Destroyed");
    }

    private void OnPushClicked(object sender, EventArgs e)
    {
        Navigation.PushAsync(new MainPage(), true);
    }

    private void OnPopClicked(object sender, EventArgs e)
    {
        if (Navigation.NavigationStack.Count > 0)
            Navigation.PopAsync(true);
    }

    private void OnPopToRootClicked(object sender, EventArgs e)
    {
        Navigation.PopToRootAsync(true);
    }
}
```

**App.xaml.cs**
```c#
public partial class App : Application
{
    public App()
    {
        InitializeComponent();
    }

    protected override Window CreateWindow(IActivationState? activationState)
    {
        return new Window(new NavigationPage(new MainPage()));
    }
}
```

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.40 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 18.1

### Did you find any workaround?

Use `PopAsync` instead

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Vignesh-SF3580**
### Issue Detail
When navigating using PushAsync and PopToRootAsync, the destructor was not invoked when using PopToRootAsync.
 
### Root Cause
The TitleView was not properly disposed when using PopToRootAsync.
 
### Description of Change
Resolved the issue by disposing the TitleView using Disconnect, similar to PopAsync.

Reference: https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs#L345

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/28201

### Screenshots

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="300" height="600"  src="https://github.com/user-attachments/assets/23f571a4-f6f9-4978-b6d8-0a334b2dd593"> | <video width="300" height="600"  src="https://github.com/user-attachments/assets/0c7e5202-bf49-4fbd-98b1-3028c1cbc8c8">) |

### CODE REVIEW

**Comment by bhavanesh2001** [comment]
The title is bit confusing. Does the leak has something to do with `TitleView`?

File: src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs [hunk 1]
```diff
@@ -310,11 +310,26 @@ protected virtual async Task<bool> OnPopToRoot(Page page, bool animated)
 
 			var task = GetAppearedOrDisappearedTask(page);
 
-			PopToRootViewController(animated);
+			var poppedControllers = PopToRootViewController(animated);
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs:313]: A this point, this method should be responsible for managing the cleanup of the ViewController that is currently at the top of the view controller stack. It ensures proper disposal of resources if the user action leads to a view being removed from the visual stack. I think inside this method, we should ensure we dispose the TitleView if exists.

Something like:
`NavigationItem.TitleView.Dispose();`

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Could you review if can include a test inside the `MemoryTests.cs` class to verify that popping a Page using TitleView does not leak?

Can use the `PagesDoNotLeak` as reference.

**Comment by Vignesh-SF3580** [comment]
> The title is bit confusing. Does the leak has something to do with `TitleView`?

Yes, the destructor is not invoked when using PopToRootAsync with TitleView. However, it is invoked properly when TitleView is not used.

**Comment by Vignesh-SF3580** [comment]
> Could you review if can include a test inside the `MemoryTests.cs` class to verify that popping a Page using TitleView does not leak?
> 
> Can use the `PagesDoNotLeak` as reference.

@jsuarezruiz The issue is only reproduced when using TitleView through a XAML file and does not occur when using it through C# code. Therefore, I added a UI test to verify this issue.
I couldn't find a reference for including a new XAML file in a MemoryTest. Could you please share your suggestions on how to handle this?

File: src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs (hunk 1 above)
Comment (Vignesh-SF3580) [reply src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs:313]: @jsuarezruiz  In PopToRootViewController, the removal and disposal of controllers are restricted by the [_ignorePopCall](https://github.com/dotnet/maui/blob/main/src/Compatibility/Core/src/iOS/Renderers/NavigationRenderer.cs#L120) variable. Removing _ignorePopCall resolves the issue, as the removed controllers are disposed of in the [RemoveViewControllers](https://github.com/dotnet/maui/blob/main/src/Compatibility/Core/src/iOS/Renderers/NavigationRenderer.cs#L660) method. However, I am unsure if removing _ignorePopCall could break any existing behaviors, as the same approach is followed in [Xamarin](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs#L111).
Therefore, I applied the fix by calling Disconnect, referring to the approach used in [PopViewAsync](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs#L345). Could you please review and share your thoughts?

**Review by StephaneDelcroix — APPROVED** [review]
