### PR TITLE
[iOS] Fix Border Content clipping issues

### LINKED ISSUE #6986: Issue in Clipping Images in Border
### Description

1)Images are not perfectly fit as expected....In Android, Images are perfectly clipped without CornerRadius Only, but In Windows Images are not cropped correctly i.e see the below differences between android and windows

In Android without CornerRadius Works perfect 
image

 In Windows without CornerRadius not work as expected

image

2) Likewise by giving Corner Radius , Images are not perfectly fit in both android and windows, see the screenshots below

In Android by Giving Corner Radius, there is small gap in top and left side
image

In Windows by Giving Corner Radius, Images are not totally clipped inside the border

image

                                     

### Steps to Reproduce

1.Unzip the below project , I gave Corner Radius . Check with Corner Radius and also without Corner Radius in both Android and windows

[SampleGridCheck.zip](https://github.com/dotnet/maui/files/8661910/SampleGridCheck.zip)

2. Run the Project

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 9.0 and Windows10.0.19041.0

### Did you find any workaround?

No

### Relevant log output

```shell
No
```

### LINKED ISSUE #7521: [Bug] Strange Border with StrokeThickness and Clipped Content
### Description

Hello,

Borders StrokeThickness does not have the same width between iOS and Android.

Android seems to not have a perfect interior line rounded 
iOS seems ok, but it put an extract padding on the left image

PS: Right Image has a negative padding to see the clip issue, but it's a known issue #7576 #6986
--------------------------Android------------------------------------------------------------ iOS-------------------------
Screenshot 2022-05-27 at 17 26 03

### Steps to Reproduce

1. Create a new Border
2. Put as a Content a Grid with some stuff in it (Images ,etc..)
3. Use a RoundRectangle as Border.StrokeShape with different CornerRadius to see the result.

--------------------------iOS------------------------------------------- Android-------------------------
Screenshot 2022-05-27 at 13 08 20
````
                <Border StrokeThickness="20"
                        Stroke="Silver"
                        Background="White"
                        Margin="0"
                        Padding="0">
                    <Border.StrokeShape>
                        <RoundRectangle CornerRadius="30" />
                    </Border.StrokeShape>
                    <Grid HeightRequest="30" BackgroundColor="Green">
                        <StackLayout Orientation="Horizontal">
                            <Frame Padding="0" HasShadow="false"
                                   BackgroundColor="Maroon"
                                   CornerRadius="20"
                                   HeightRequest="40"
                                   WidthRequest="40" VerticalOptions="Center" >
                            </Frame>
                            <Label Text="Parameters"
                                   VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"
                                   FontSize="Medium" FontFamily="Bold"
                                   HorizontalTextAlignment="Center" VerticalTextAlignment="Center" />
                            <Frame Padding="0" HasShadow="false" CornerRadius="0" Margin="0,0,-20,0"
                                   BackgroundColor="Blue"
                                   HeightRequest="40"
                                   WidthRequest="40" VerticalOptions="Center" >
                            </Frame>
                        </StackLayout>
                    </Grid>
                </Border>
````

### Expected Behavior
Screenshot 2022-05-27 at 17 22 38

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

MAUI 6.0.312

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #9081: Border does not occupy all the space in a grid cell
### Description

We are migrating XF to Maui, converting Frame to Border. However Border does not occupy the same space as a frame.

### Steps to Reproduce

New maui project, replace MainPage content with the below code, and run
You will see the 2 border controls have extra margins to height (border on the right), and width (border below).
To compensate we can set margin to a negative value, but that value would be different per platform.

            var grid = new Grid()
            {
                RowSpacing = 1,
                ColumnSpacing = 1,
                BackgroundColor = Colors.LightGray
            };

            grid.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));
            grid.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));
            grid.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));
            grid.ColumnDefinitions.Add(new ColumnDefinition(GridLength.Star));

            grid.RowDefinitions.Add(new RowDefinition(GridLength.Star));
            grid.RowDefinitions.Add(new RowDefinition(GridLength.Star));
            grid.RowDefinitions.Add(new RowDefinition(GridLength.Star));
            grid.RowDefinitions.Add(new RowDefinition(GridLength.Star));

            Content = grid;

            var frame = new Frame()
            {
                BorderColor = Colors.Red,
                BackgroundColor = Colors.White,
                VerticalOptions = LayoutOptions.Fill,
                HorizontalOptions = LayoutOptions.Fill,
                CornerRadius = 0,
                Content = new Label { Text = "Frame" }
            };

            Grid.SetRow(frame, 1);
            Grid.SetColumn(frame, 1);

            grid.Children.Add(frame);

            var border1 = new Border
            {
                StrokeShape = new Rectangle(),
                Stroke = Colors.Red,
                BackgroundColor = Colors.White,
                VerticalOptions = LayoutOptions.Fill,
                HorizontalOptions = LayoutOptions.Fill,
                Content = new Label { Text = "Border" }
            };

            Grid.SetRow(border1, 1);
            Grid.SetColumn(border1, 2);

            grid.Children.Add(border1);

            var border2 = new Border
            {
                StrokeShape = new Rectangle(),
                Stroke = Colors.Red,
                BackgroundColor = Colors.White,
                VerticalOptions = LayoutOptions.Fill,
                HorizontalOptions = LayoutOptions.Fill,
                Content = new Label { Text = "Border" }
            };

            Grid.SetRow(border2, 2);
            Grid.SetColumn(border2, 1);

            grid.Children.Add(border2);

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15

### Did you find any workaround?

Set margin to a negative value

### Relevant log output

_No response_

### LINKED ISSUE #9952: Border control for image with rounded corners doesnt work on iOS
### Description

On iOS it looks like this
Screen Shot 2022-09-06 at 11 52 38 AM

On Android it looks like this.
Screen Shot 2022-09-06 at 11 53 35 AM

### Steps to Reproduce

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TabDemo.MainPage">
        <VerticalStackLayout VerticalOptions="Center">
            <Border WidthRequest="280">
                <Border.StrokeShape>
                    <RoundRectangle CornerRadius="20" />
                </Border.StrokeShape>
                <Image Aspect="AspectFit"   Source="image.png" />
            </Border>
        </VerticalStackLayout>
</ContentPage>

### Link to public reproduction project repository

https://github.com/ignaciofuentes/Border-Rounded-Corner-Image-Issue

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #10478: [MacCatalyst] Image clipping with border not working
### Description

Image clipping with border not working as expected.

Android
Captura de Pantalla 2022-10-04 a las 10 52 45

Catalyst
Captura de Pantalla 2022-10-04 a las 11 02 12

### Steps to Reproduce

1. Download https://github.com/jsuarezruiz/netmaui-surfing-app-challenge
2. Launch the App on macOS.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/netmaui-surfing-app-challenge

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monterey

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #10724: Border Clipping Issue in [iOS & macOS]
### Description

Images are not Clipped correctly as expected in iOS and macOS

**iOS**
image

**macOS**
image

### Steps to Reproduce
` <Border VerticalOptions="Center" HorizontalOptions="Center" HeightRequest="100" WidthRequest="100" Stroke="red" StrokeThickness="4">
            <Border.StrokeShape>
                <RoundRectangle CornerRadius="50"/>
            </Border.StrokeShape>
            <Border.Content>
                <Grid>
                    <Image Source="avatar1.png" Aspect="AspectFill"  />
                </Grid>
            </Border.Content>
        </Border>`

The below repository contains the sample

### Link to public reproduction project repository

https://github.com/Ahamed-Ali/AvatarView/tree/main

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iPhone 13 Pro Max(iOS 15.5) & Mac Catalyst-15.4.454

### Did you find any workaround?

NA

### Relevant log output

```shell
NA
```

### LINKED ISSUE #11152: [iOS] Entry in Border - strange corner round.
### Description

```xaml
 <VerticalStackLayout>
        <Label Text="Input" x:Name="InputLabel" Style="{StaticResource InputLabelStyle}"/>
        
        <Border Stroke="{StaticResource BackgroundOutline}" StrokeThickness="1" HeightRequest="52" >
            <Border.StrokeShape>
                <RoundRectangle CornerRadius="16" />
            </Border.StrokeShape>
            <Entry x:Name="InputContext" BackgroundColor="{StaticResource BackgroundLight}" Placeholder="Placeholder text" 
                          Margin="8"/> 
        </Border>
       
        <Label Text="Error" x:Name="Error" Style="{StaticResource InputErrorLabelStyle}"/>
    </VerticalStackLayout>
```

Screenshot 2022-11-07 at 18 19 01

left top corner of Entry is rounded. but why?

### Steps to Reproduce

try to do
```xaml
 <VerticalStackLayout>
        <Label Text="Input" x:Name="InputLabel" Style="{StaticResource InputLabelStyle}"/>
        
        <Border Stroke="{StaticResource BackgroundOutline}" StrokeThickness="1" HeightRequest="52" >
            <Border.StrokeShape>
                <RoundRectangle CornerRadius="16" />
            </Border.StrokeShape>
            <Entry x:Name="InputContext" BackgroundColor="{StaticResource BackgroundLight}" Placeholder="Placeholder text" 
                          Margin="8"/> 
        </Border>
       
        <Label Text="Error" x:Name="Error" Style="{StaticResource InputErrorLabelStyle}"/>
    </VerticalStackLayout>
```

### Link to public reproduction project repository

no

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #12580: MAUI: border not clip image
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI:-border-not-clip-image/10236263)._

---
[severity:It bothers me. A fix would be nice]

I have a situation on MAUI.
I display Image inside Border - RoundRectangle. On android, Image display correctly. However, if I run on windows platform, image will be stretched out of border.
please show me how to fix this

---
#### Feedback Bot on 22/12/2022, 02:40 AM: 

(private comment, text removed)
#### Sigma Li (CSI Interfusion Inc) [MSFT] on 23/12/2022, 07:53 AM: 

(private comment, text removed)
#### Hoai Truong on 24/12/2022, 03:01 PM: 

(private comment, text removed)
#### Feedback Bot on 27/12/2022, 10:38 AM: 

(private comment, text removed)
#### Hoai Truong on 29/12/2022, 03:38 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### LINKED ISSUE #13011: Border StrokeThickness decreases Height on Android
### Description

When creating a border on android and setting StrokeThickness, the border StrokeThickness is subtracted from the height. It seems like the size of the child changes correctly, but then instead of applying the stroke to the actual border of the border, the stroke is put inside the child.
Maybe this could be the root cause for some reported clipping issues as well, because the stroke is placed incorrectly.

### Steps to Reproduce

1. Create 2 borders next to each other with same HeightRequest
2. Set Stroke to any visible color
3. Set StrokeThickness to 1 in one and to 10 in the other 
4. The borders will have a different height on android, but the same on iOS

### Link to public reproduction project repository

https://github.com/borrmann/StrokeThicknessBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #13388: Border.StrokeShape clips content on Android, not iOS
### Description

The XAML markup behaves unexpectedly on iOS;

```xaml
<Border
    Stroke="Blue"
    StrokeThickness="5"
    WidthRequest="200"
    HeightRequest="200">
    <Border.StrokeShape>
        <Ellipse />
    </Border.StrokeShape>
    <Image Source="llama.jpg" Aspect="Fill" />
</Border>
```

### Android
This is what I would expect, nice clipped image in coloured border.
image

### iOS
This looks wrong - no clipping and size of image is not taking into account clip properly.
image

### Steps to Reproduce

1. Create a new project.
2. Add a border with circular stroke, and image within it.
3. Observe different output between Android and iOS.

### Link to public reproduction project repository

https://github.com/RobTF/mauiplay/tree/master/EllipseIssue

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

Not really, using `Border.Clip` like so gives a closer effect, but the image does not size correctly (leaving small white gaps at the edges).

```xaml
<Border
    Stroke="Blue"
    StrokeThickness="5"
    WidthRequest="200"
    HeightRequest="200">
    <Border.Clip>
        <EllipseGeometry RadiusX="100" RadiusY="100" Center="100,100" />
    </Border.Clip>
    <Border.StrokeShape>
        <Ellipse />
    </Border.StrokeShape>
    <Image
        Source="llama.jpg"
        Aspect="Fill" />
</Border>
```

Gives;
image

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix Border Content clipping issues.

fix-clipping-ios-1
fix-clipping-ios-2

### Issues Fixed

Fixes #6986
Fixes #10724 
Fixes #7521
Fixes #10478
Fixes #12580
Fixes #9952
Fixes #9081
Fixes #13388
Fixes #13011
Fixes #11152

### CODE REVIEW

**Review by PureWeen — CHANGES_REQUESTED** [review]
Testing with the original posters `XAML` and the results seem off

```XAML
 <VerticalStackLayout>
        <Border StrokeThickness="20"
                            Stroke="Silver"
                            Background="White"
                            Margin="0"
                            Padding="0">
            <Border.StrokeShape>
                <RoundRectangle CornerRadius="30" />
            </Border.StrokeShape>
            <Grid HeightRequest="30" BackgroundColor="Green">
                <StackLayout Orientation="Horizontal">
                    <Frame Padding="0" HasShadow="false"
                                       BackgroundColor="Maroon"
                                       CornerRadius="20"
                                       HeightRequest="40"
                                       WidthRequest="40" VerticalOptions="Center" >
                    </Frame>
                    <Label Text="Parameters"
                                       VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"
                                       FontSize="Medium" FontFamily="Bold"
                                       HorizontalTextAlignment="Center" VerticalTextAlignment="Center" />
                    <Frame Padding="0" HasShadow="false" CornerRadius="0" Margin="0,0,-20,0"
                                       BackgroundColor="Blue"
                                       HeightRequest="40"
                                       WidthRequest="40" VerticalOptions="Center" >
                    </Frame>
                </StackLayout>
            </Grid>
        </Border>
    </VerticalStackLayout>
```
image

**Comment by jsuarezruiz** [comment]
> Testing with the original posters `XAML` and the results seem off
> 
> ```
>  <VerticalStackLayout>
>         <Border StrokeThickness="20"
>                             Stroke="Silver"
>                             Background="White"
>                             Margin="0"
>                             Padding="0">
>             <Border.StrokeShape>
>                 <RoundRectangle CornerRadius="30" />
>             </Border.StrokeShape>
>             <Grid HeightRequest="30" BackgroundColor="Green">
>                 <StackLayout Orientation="Horizontal">
>                     <Frame Padding="0" HasShadow="false"
>                                        BackgroundColor="Maroon"
>                                        CornerRadius="20"
>                                        HeightRequest="40"
>                                        WidthRequest="40" VerticalOptions="Center" >
>                     </Frame>
>                     <Label Text="Parameters"
>                                        VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"
>                                        FontSize="Medium" FontFamily="Bold"
>                                        HorizontalTextAlignment="Center" VerticalTextAlignment="Center" />
>                     <Frame Padding="0" HasShadow="false" CornerRadius="0" Margin="0,0,-20,0"
>                                        BackgroundColor="Blue"
>                                        HeightRequest="40"
>                                        WidthRequest="40" VerticalOptions="Center" >
>                     </Frame>
>                 </StackLayout>
>             </Grid>
>         </Border>
>     </VerticalStackLayout>
> ```
> 
> image

Tested with Catalyst and the result is the same as Android. Weird, will do more tests.

**Comment by rmarinho** [comment]
Windows seems doesn't render the frames..

image

**Comment by rmarinho** [comment]
IMG_1642

on IOS is almost fine, theres some white background

**Review by PureWeen — CHANGES_REQUESTED** [review]
My last comment run on iOS was incorrect. I'm not sure why I got that result. 

What I'm curious about now is some of the math and results here. I'm not super strong in this area so I'm probably missing something

## iOS

I don't quite understand why we're multiplying the line width by 2. From the docs the line width straddles the path

https://developer.apple.com/documentation/coregraphics/1455270-cgcontextsetlinewidth?language=objc

> The default line width is 1 unit. When stroked, the line straddles the path, with half of the total width on either side.

So, instead of doubling the width should we be increasing the width/height so we don't have to multiply by 2?

The iOS results don't seem quite correct because the blue frame is a rectangle but it's getting a circle cut out of it. It seems like that blue should be filling all this space.

image

### Android
The issue I'm seeing with Android should probably be a new issue. If it is indeed an issue.

If you look at android it seems like the way the path works is the same as iOS. 

image

The path of the border overlaps the surrounding grid which is basically what @rmarinho seems to have noticed here
https://github.com/dotnet/maui/pull/10964#issuecomment-1329344568

You can also see that the full height of the `Border` is 70 dp but due to the border not filling in that space you end up with white space. 

image


It feels like
- Android needs to be fixed so the width/height of the border bounds is increased by another `BorderWidth` of size
- iOS should do the same and the stroke thickness shouldn't be multiplied by 2

File: src/Core/src/Platform/iOS/MauiCALayer.cs [hunk 1]
```diff
@@ -311,7 +311,8 @@ void DrawBorder(CGContext ctx)
 			if (IsBorderDashed())
 				ctx.SetLineDash(_strokeDashOffset * _strokeThickness, _strokeDash);
 
-			ctx.SetLineWidth(_strokeThickness);
+			// The Stroke is inner and we are clipping the outer, for that reason, we use the double to get the correct value.
+			ctx.SetLineWidth(2 * _strokeThickness);
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/MauiCALayer.cs:315]: Added here a comment to explain why we multiply by 2.

File: src/Controls/src/Core/HandlerImpl/RoundRectangle.Impl.cs [hunk 2]
```diff
@@ -32,5 +33,37 @@ public override PathF GetPath()
...
+			{
+				Frame = viewBounds;
+			}
+
+			var path = GetInnerPath(strokeWidth);
+
+			return path;
+		}
+
+		internal PathF GetInnerPath(float strokeWidth)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/HandlerImpl/RoundRectangle.Impl.cs:49]: We was clipping using the Border shape. That is correct in many cases but not always. Using a RoundRectangle, the Corner Radius value is not the same in the inner or outer. We want in this case user the inner value. For that reason, added a new method returning the same shape but with different radius.

**Comment by jsuarezruiz** [comment]
> > Testing with the original posters `XAML` and the results seem off
> > ```
> >  <VerticalStackLayout>
> >         <Border StrokeThickness="20"
> >                             Stroke="Silver"
> >                             Background="White"
> >                             Margin="0"
> >                             Padding="0">
> >             <Border.StrokeShape>
> >                 <RoundRectangle CornerRadius="30" />
> >             </Border.StrokeShape>
> >             <Grid HeightRequest="30" BackgroundColor="Green">
> >                 <StackLayout Orientation="Horizontal">
> >                     <Frame Padding="0" HasShadow="false"
> >                                        BackgroundColor="Maroon"
> >                                        CornerRadius="20"
> >                                        HeightRequest="40"
> >                                        WidthRequest="40" VerticalOptions="Center" >
> >                     </Frame>
> >                     <Label Text="Parameters"
> >                                        VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"
> >                                        FontSize="Medium" FontFamily="Bold"
> >                                        HorizontalTextAlignment="Center" VerticalTextAlignment="Center" />
> >                     <Frame Padding="0" HasShadow="false" CornerRadius="0" Margin="0,0,-20,0"
> >                                        BackgroundColor="Blue"
> >                                        HeightRequest="40"
> >                                        WidthRequest="40" VerticalOptions="Center" >
> >                     </Frame>
> >                 </StackLayout>
> >             </Grid>
> >         </Border>
> >     </VerticalStackLayout>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > image
> 
> Alright, I think the key piece of information I was missing here is that you need to rebase to see these results. If I rebase this PR to main then I get the incorrect layout described here.
> 
> Here it is running on catalyst with everything rebased to main
> 
> image

Ok, thanks for the details. Let me test it.

**Comment by jsuarezruiz** [comment]
Added more samples to validate #9081
Captura de pantalla 2023-01-27 a las 14 25 10

File: src/Controls/src/Core/HandlerImpl/RoundRectangle.Impl.cs [hunk 3]
```diff
@@ -36,5 +37,39 @@ public override PathF GetPath()
 
 			return path;
 		}
+
+		PathF IRoundRectangle.InnerPathForBounds(Rect viewBounds, float strokeWidth)
+		{
+			if (HeightRequest < 0 && WidthRequest < 0)
+			{
+				Frame = viewBounds;
```
Comment (hartez) [inline src/Controls/src/Core/HandlerImpl/RoundRectangle.Impl.cs:45]: The Frame should not be set here; this will cause re-layouts. And GetInnerPath should not use the Width and Height properties, because those will not be set before the first layout pass has completed. See #12326 and #12356 for more info.

**Review by hartez — CHANGES_REQUESTED** [review]

**Comment by KSemenenko** [comment]
@jsuarezruiz  Is there any chance that this fix will be available in the NET 7.200 version?

**Comment by hartez** [comment]
Just ran the sample gallery from this PR, and it looks like it's clipping the items on the first page:
Simulator Screen Shot - iPhone 12 Pro - 2023-02-15 at 13 22 46

**Comment by jsuarezruiz** [comment]
> Just ran the sample gallery from this PR, and it looks like it's clipping the items on the first page:
> Simulator Screen Shot - iPhone 12 Pro - 2023-02-15 at 13 22 18

Working on changes. Detected the issue. This PR is before these changes https://github.com/dotnet/maui/pull/12356
and for the clipping is still using the old Shapes sizing approach setting the Frame etc. This is wrong and require changes. 

This PR is marked as Draft while updating the code.

**Comment by jsuarezruiz** [comment]
> > Just ran the sample gallery from this PR, and it looks like it's clipping the items on the first page:
> > Simulator Screen Shot - iPhone 12 Pro - 2023-02-15 at 13 22 18
> 
> Working on changes. Detected the issue. This PR is before these changes #12356 and for the clipping is still using the old Shapes sizing approach setting the Frame etc. This is wrong and require changes.
> 
> This PR is marked as Draft while updating the code.

Ready to another review. Applied changes and tested with the original issue sample:
Captura de pantalla 2023-02-20 a las 13 52 20

Of course, with the .NET MAUI gallery:
Captura de pantalla 2023-02-20 a las 13 48 18

And with the specific sample to validate the Border clipping possibilities (with different shapes, stroke width etc).
fix-border-clip-ios

**Comment by hartez** [comment]
If I open the "Border Stroke Options" page and update each Label to have a HeightRequest of 50, I get this, which seems wrong:
Simulator Screen Shot - iPhone 12 Pro - 2023-02-22 at 16 02 44

**Review by hartez — CHANGES_REQUESTED** [review]
Border widths still look wrong for iOS on the Border Stroke Options page.

File: src/Controls/samples/Controls.Sample/Pages/Core/BorderGalleries/BorderClipPlayground.xaml.cs [hunk 4]
```diff
@@ -0,0 +1,94 @@
+﻿using System;
+using Microsoft.Maui;
+using Microsoft.Maui.Controls;
+using Microsoft.Maui.Controls.Shapes;
+using Microsoft.Maui.Graphics;
```
Comment (mandel-macaque) [inline src/Controls/samples/Controls.Sample/Pages/Core/BorderGalleries/BorderClipPlayground.xaml.cs:5]: Lets add nullability to this file.

File: src/Controls/samples/Controls.Sample/Pages/Core/BorderGalleries/BorderClipPlayground.xaml.cs [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+		void UpdateBorderShape()
+		{
+			CornerRadiusLayout.IsVisible = BorderShapePicker.SelectedIndex == 1;
+
+			UpdateBorder();
+		}
+
+		void UpdateBorder()
+		{
+			Shape borderShape = null;
```
Comment (mandel-macaque) [inline src/Controls/samples/Controls.Sample/Pages/Core/BorderGalleries/BorderClipPlayground.xaml.cs:50]:
```suggestion
			Shape? borderShape = null;
```

File: src/Controls/samples/Controls.Sample/Pages/Core/BorderGalleries/BorderClipPlayground.xaml.cs [hunk 6]
```diff
@@ -0,0 +1,94 @@
...
+
+			BorderView.StrokeThickness = BorderWidthSlider.Value;
+		}
+
+		void UpdateCornerRadius()
+		{
+			UpdateBorder();
+		}
+
+		Color GetColorFromString(string value)
```
Comment (mandel-macaque) [inline src/Controls/samples/Controls.Sample/Pages/Core/BorderGalleries/BorderClipPlayground.xaml.cs:79]:
```suggestion
		Color GetColorFromString(string? value)
```

File: src/Controls/samples/Controls.Sample/Pages/Core/BorderGalleries/BorderPlayground.xaml.cs [hunk 7]
```diff
@@ -101,7 +108,25 @@ void UpdateBackground()
...
 		void UpdateContentBackground()
 		{
-			BorderContent.BackgroundColor = ContentBackgroundCheckBox.IsChecked ? Color.FromArgb("#99FF0000") : Colors.Transparent;
+			if (BorderView.Content is View content)
+				content.BackgroundColor = ContentBackgroundCheckBox.IsChecked ? Color.FromArgb("#99FF0000") : Colors.Transparent;
+		}
+
+		void UpdateBorderContent()
+		{
+			View content = null;
```
Comment (mandel-macaque) [inline src/Controls/samples/Controls.Sample/Pages/Core/BorderGalleries/BorderPlayground.xaml.cs:117]:
```suggestion
			View? content = null;
```

File: src/Core/src/Platform/iOS/ContentView.cs [hunk 8]
```diff
@@ -105,7 +110,7 @@ public override void SetNeedsLayout()
 
 			var child = Subviews[0];
 
-			if (child.Layer == null || child.Layer.Sublayers == null)
+			if (child.Layer == null)
```
Comment (mandel-macaque) [inline src/Core/src/Platform/iOS/ContentView.cs:113]:
```suggestion
			if (child.Layer is null)
```

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

File: src/Controls/samples/Controls.Sample/Pages/Core/BorderGalleries/BorderClipPlayground.xaml.cs (hunk 4 above)
Comment (jsuarezruiz) [reply src/Controls/samples/Controls.Sample/Pages/Core/BorderGalleries/BorderClipPlayground.xaml.cs:5]: Added

**Review by mandel-macaque — APPROVED** [review]

**Comment by jsuarezruiz** [comment]
> Border widths still look wrong for iOS on the Border Stroke Options page.

Seems that this will be fixed by https://github.com/dotnet/maui/pull/14114
Let's review it again after merge 14114 and rebase here.

**Review by rmarinho — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]

**Review by hartez — CHANGES_REQUESTED** [review]
Looks like there's still an Android issue.

File: src/Controls/samples/Controls.Sample/Pages/Core/BorderGalleries/BorderLayout.xaml [hunk 9]
```diff
@@ -0,0 +1,55 @@
+﻿<?xml version="1.0" encoding="utf-8" ?>
```
[the remark this answers is not in the document]
Comment (jsuarezruiz) [reply src/Controls/samples/Controls.Sample/Pages/Core/BorderGalleries/BorderLayout.xaml:1]: Can reproduce it. Your issue is the same as https://github.com/dotnet/maui/issues/13011
Working on a fix to that too.

[the remark this answers is not in the document]
Comment (jsuarezruiz) [reply src/Controls/samples/Controls.Sample/Pages/Core/BorderGalleries/BorderLayout.xaml:1]: Applied changes to fix https://github.com/dotnet/maui/issues/13011.

Before
image

After
fix-border-stroke-droid

And tested the mentioned sample with the changes.

fix-border-stroke-droid-2

**Review by hartez — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]

**Comment by breenbob** [comment]
Would be massively in favour of a backport of these fixes!

**Comment by jcsnider** [comment]
Couldn't agree more, for whatever it's worth.

**Comment by jrahma** [comment]
I am still having the problem. Hope the fix will be available soon.

**Comment by darshanio** [comment]
> Would be massively in favour of a backport of these fixes!

Agree.
Hope we get the fix soon in .Net 7.

**Comment by KSemenenko** [comment]
I feel it will be .NET 8 preview 7 or so
