### PR TITLE
Wire up WindowOverlay to the Window Density

### LINKED ISSUE #5334: IWindow.VisualDiagnosticsOverlay.Density is always 1
### Description

IWindow.VisualDiagnosticsOverlay.Density is always 1

### Steps to Reproduce

1. Make sure your Windows display settings are set to something different than 100%.
2. Create new MAUI app targeting Windows.
3. Replace MainPage.xaml and *.cs with the attached ones.
4. Build and run app. Click on a button
Actual: test appears which states that density is 1
Expected: density should match your OS settings, i.e. should be the same as reported by WinUI.
Note: View.Bounds are reported in MAUI units. With wrong density we cannot convert it to pixels which is needed for XAML Live Preview
[MainPage.xaml.zip](https://github.com/dotnet/maui/files/8262629/MainPage.xaml.zip)

image

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Redth**
The VisualDiagnostics' WindowOverlay was implemented before we introduced a better API for dealing with display density, but we never hooked that new API up to VisualDiagnostics.

The fix is simple here, just defer to the Window's display density to get the correct value from the WindowOverlay.

This fixes #5334

### CODE REVIEW

File: src/Core/src/WindowOverlay/WindowOverlay.cs [hunk 1]
```diff
@@ -69,7 +69,7 @@ public bool IsVisible
 		}
 
 		/// <inheritdoc/>
-		public float Density { get; internal set; } = 1;
+		public float Density => Window?.RequestDisplayDensity() ?? 0f;
```
Comment (etvorun) [inline src/Core/src/WindowOverlay/WindowOverlay.cs:72]: 1f would be a better fallback value than 0f

Comment (Redth) [reply src/Core/src/WindowOverlay/WindowOverlay.cs:72]: Do you want the likely wrong value in the fallback or a value you know indicates it’s incorrect and you can choose 1f if you want in that case?

Comment (etvorun) [reply src/Core/src/WindowOverlay/WindowOverlay.cs:72]: We'll have to fall back to 1 anyway:) Given that a) this is public API and b) this value is likely to be used in calcs like uitsPerPixel = 1/Density then returning 0 is likely to cause divided-by-0.

But if you believe 0 is better than 1 then I can live with that :)

Comment (mattleibow) [reply src/Core/src/WindowOverlay/WindowOverlay.cs:72]: I agree that density should be 1 because some platforms do not support this, so will always return 1. The only reason for the null check if there is no window, so it is better to be consistent and just return 1.

Comment (Redth) [inline src/Core/src/WindowOverlay/WindowOverlay.cs:72]:
```suggestion
		public float Density => Window?.RequestDisplayDensity() ?? 1f;
```

**Review by etvorun — APPROVED** [review]
