### PR TITLE
Hide FlyoutIcon when FlyoutBehavior set to disabled

### LINKED ISSUE #9037: Custom FlyoutIcon visible although FlyoutBehavior set to disabled on Android an IOS
### Description

When I add a custom FlyoutIcon to shell, the icon is visible on a page although I´ve set Shell.FlyoutBehavior="Disabled" on the page and inside shellContent.
This happens on Android (v12 in my case) and iOS (15 in my case).
When you toch the icon on iOS, nothing happens...
When you do the same an Andoid an error occurs (No drawer view found with gravity LEFT).

When I remove the custom icon, all works as expected (hamburger menu not being displayed).

### Steps to Reproduce

1. Create a new maui app
2. Create a shell with some shell contents
3. For one shell content set Shell.FlyoutBehavior="Disabled"
4. Set this shell content as the first item (start page)
5. Add a custom FlyoutIcon (FlyoutIcon="flyout_icon.png")
6. Start the app and the icon is being displayed although it shouldn´t
7. Stop the app and remove the custom icon
6. Start the app and the hamburger menu icon is not being displayed as it sould

Expected: The custom flyout icon should not be displayed on pages with Shell.FlyoutBehavior="Disabled"
Actual outcome: The custom flyout is being displayed on pages with Shell.FlyoutBehavior="Disabled"

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15, Android 12

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

The restrictions have been added to make sure that the custom icon is displayed only when the flyoutBehavior is equal FlyoutBehavior.Flyout on Android and iOS

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/9037

https://github.com/dotnet/maui/assets/42434498/2c6e08d7-3429-4b65-b621-45d191e90d89

### CODE REVIEW

**Comment by dustin-wojciechowski** [comment]
Looks good, just noticing that no changes were needed for this to work on Windows
20087_part1
20087_part2

**Comment by kubaflo** [comment]
> Looks good, just noticing that no changes were needed for this to work on Windows 20087_part1 20087_part2

I unfortunately cannot say anything about the windows behavior because I don't have a windows device

**Review by dustin-wojciechowski — DISMISSED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs [hunk 1]
```diff
@@ -331,13 +331,16 @@ void UpdateLeftToolbarItems()
...
 
-				if (image != null)
+				if (_flyoutBehavior == FlyoutBehavior.Flyout)
 				{
-					icon = result?.Value;
-				}
-				else if (String.IsNullOrWhiteSpace(text) && IsRootPage && _flyoutBehavior == FlyoutBehavior.Flyout)
-				{
-					icon = DrawHamburger();
+					if (image != null)
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs:336]: Would it make sense to move all the code below this to a separate method?

And then before we call `LoadImage` we can just check the flyout behavior? If it's set to Flyout then we just call the separate method with a `null` icon?

With this path, it seems like we're going to be loading an image that we never use.

**Review by PureWeen — CHANGES_REQUESTED** [review]

**Review by PureWeen — DISMISSED** [review]

**Comment by jsuarezruiz** [comment]
Rebased and added pending UITest snapshots.

**Review by jsuarezruiz — APPROVED** [review]

**Review by jsuarezruiz — DISMISSED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20166.cs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+namespace Microsoft.Maui.TestCases.Tests.Issues;
+public class Issue20166 : _IssuesUITest
+{
+	public Issue20166(TestDevice device)
+	: base(device) { }
+
+	public override string Issue => "Custom FlyoutIcon visible although FlyoutBehavior set to disabled";
+
+	[Test]
+	public void ShouldHideCustomFlyoutIconWhenNavigatingToPageWithDisabledFlyout()
```
Comment (PureWeen) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20166.cs:14]: Can you add a category to this one?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20166.cs (hunk 2 above)
Comment (kubaflo) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20166.cs:15]: Done

File: src/Controls/tests/TestCases.HostApp/Issues/Issue20166.cs [hunk 3]
```diff
@@ -0,0 +1,24 @@
+﻿using System;
```
Comment (PureWeen) [inline src/Controls/tests/TestCases.HostApp/Issues/Issue20166.cs:1]: Can you rename this file to Issue20166.xaml.cs?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.HostApp/Issues/Issue20166.cs (hunk 3 above)
Comment (kubaflo) [reply src/Controls/tests/TestCases.HostApp/Issues/Issue20166.cs]: Done

**Review by PureWeen — APPROVED** [review]

**Comment by PureWeen** [comment]
Test failures are unrelated
