### PR TITLE
[macOS/iOS] Fix RequestedThemeChanged event

### LINKED ISSUE #10055: Application.Current.RequestedThemeChanged has not be triggered on Mac
### Description

Event Application.Current.RequestedThemeChanged is not be triggered on mac after I changed my mac theme.

### Steps to Reproduce

```c#
public partial class App : Application
{
    ILogger<App> Logger;  
    
      
    public App()
    {
        InitializeComponent();
        
        MainPage = new AppShell();
    
        var loggerFactory = LoggerFactory.Create(
            builder => builder
                        // add console as logging target
                        .AddConsole()
                        // add debug output as logging target
                        .AddDebug()
                        // set minimum level to log
                        .SetMinimumLevel(LogLevel.Debug)
        );
  
        Logger = loggerFactory.CreateLogger<App>();
  
        Current.RequestedThemeChanged += Current_RequestedThemeChanged;
    }

    private void Current_RequestedThemeChanged(object sender, AppThemeChangedEventArgs e)
    {
        Console.WriteLine("Hi");
        Logger.LogInformation("Info message");
    }
}

```

The method has never been called after i changed my mac's theme.
I Debug with my MAC.

### Link to public reproduction project repository

NA

### Version with bug

6.0.408

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 12.5.1

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #10310: App.Current.RequestedThemeChanged doesn't fire
### Description

App.Current.RequestedThemeChanged doesn't fire IF the new UserAppTheme resolves to the current theme.

Example:

When the current theme is "Unspecified" and "Light", the event will ONLY fire when the user changes to "Dark". 
When the current theme is "Light, the event will ONLY fire when the user changes to "Dark". Changing to "Unspecified" is equivalent to "Light" and thus won't fire the event.

I believe it should fire. I have 2 different UI controls that listen for theme change events and when it doesn't fire one may say "Light" while the other says "Unspecified" on the same screen. 

image

### Steps to Reproduce

do the things described

### Link to public reproduction project repository

https://github.com/davidortinau/ControlGallery

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS, I was *not* able test on other platforms

### Affected platform versions

latest

### Did you find any workaround?

haven't tried

### Relevant log output

_No response_

### LINKED ISSUE #11005: App.Current.RequestedThemeChanged never fires
### Description

I am trying to subscribe to system theme changes as per the docs here : https://learn.microsoft.com/en-us/dotnet/maui/user-interface/system-theme-changes

The event never fires. 

We don't use AppThemeBinding for our theming so we want to be able to react to Light / Dark mode changes using this event. 

### Steps to Reproduce

Create a new MAUI app. Subscribe to the event in App.Xaml.cs and set a breakpoint. 

The breakpoint is never hit. 

image

### Link to public reproduction project repository

No need, just do a new app

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Android 11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #11119: AppThemeBinding not working well on macOS
### Description

AppThemeBinding is not dynamic on the mac. When I change the system theme while the app is running, the text colours do not change. AppThemeBinding only works when the application is launched then the colours are selected correctly.

https://user-images.githubusercontent.com/23263384/200120468-77f4031b-c77f-4f4e-b492-d86dd504024e.mp4

AppShell.xaml
image

image

### Steps to Reproduce

1. Create a new .Net MAUI App
2. Change the text colour of any lebel to `TextColor="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource White}}"`
3. When the application is running change the system themes and watch for the bug

### Link to public reproduction project repository

https://github.com/piotreksda/testMauiApp

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 12.6

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix **RequestedThemeChanged** event using Shell on macOS/iOS.

fix-macos-themes

We use the page controller to detect theme changes thanks to `traitCollectionDidChange`. However, with Shell this doesn't work and the default project template uses Shell. This PR applies changes to detect changes in themes also using Shell.

### Issues Fixed

Fixes #10055
Fixes #10310
Fixes #11005
Fixes #11119

### CODE REVIEW

**Comment by piotreksda** [comment]
When will the changes be available in the .net 6 stable version?

**Comment by jfversluis** [comment]
> When will the changes be available in the .net 6 stable version?

This will probably not land in .NET 6 as it introduces new APIs and thus breaking changes. This will become available in .NET 8 or if we decide this is crucial in .NET 7 maybe.

**Review by jfversluis — APPROVED** [review]

**Comment by Hurricane31337** [comment]
> > When will the changes be available in the .net 6 stable version?
> 
> This will probably not land in .NET 6 as it introduces new APIs and thus breaking changes. This will become available in .NET 8 or if we decide this is crucial in .NET 7 maybe.

Please at least make this change in .NET 7. This is not a new feature but a crucial fix for developing macOS apps using .NET MAUI.

I am currently developing a MAUI application that I intend to ship to macOS only (cross platform to be flexible) and my current experience is that its Dark Mode capabilities are completely unusable without this fix and I would never ship my app in its current state.

How could it be better to keep it in its current state "to not break things"? Currently this part of the macOS target is completely broken anyways! 😃

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs [hunk 1]
```diff
@@ -130,7 +130,21 @@ public override void ViewSafeAreaInsetsDidChange()
...
+		public override void TraitCollectionDidChange(UITraitCollection previousTraitCollection)
+		{
+			base.TraitCollectionDidChange(previousTraitCollection);
+
+			var currentItem = ShellSection.CurrentItem;
+
+			if (!_renderers.ContainsKey(currentItem))
+				return;
+
+			var currentItemHandler = _renderers[currentItem];
```
Comment (mandel-macaque) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs:142]: We cna do a little better than this. If you noticed (and I believe this is a dict) you are doing  a look up twice. You can reduce that with the TryGetValue method:
```suggestion
			if (!_renderers.TryGetValue(currentItem, out var currentItemHandler))
				return;
```
You'll get the same out var and you'll remove the extra lookup.

**Review by mandel-macaque — DISMISSED** [review]
Small possible improvement

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs [hunk 2]
```diff
@@ -130,7 +130,19 @@ public override void ViewSafeAreaInsetsDidChange()
...
+		public override void TraitCollectionDidChange(UITraitCollection previousTraitCollection)
+		{
+			base.TraitCollectionDidChange(previousTraitCollection);
+
+			var currentItem = ShellSection.CurrentItem;
 
+			if (!_renderers.TryGetValue(currentItem, out var currentItemHandler))
+				return;
+
+			var application = currentItemHandler.GetRequiredService<IApplication>();
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs:142]: Can you just get it from `_shellContext` ? 

`_shellContext.Shell.FindMauiContext().Services`

Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs:142]: Can you just get it from `_shellContext` ? 

`_shellContext.Shell.FindMauiContext().Services`

**Review by PureWeen — DISMISSED** [review]

**Review by mandel-macaque — APPROVED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs (hunk 2 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootRenderer.cs]: Changed, could you review it again?. Thanks.

**Review by mattleibow — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]

**Comment by mattleibow** [comment]
This will be superseded by https://github.com/dotnet/maui/pull/13510. However, this PR is more backport friendly and we can get the fix in sooner until @PureWeen runs all the tests.

This PR is very hard to test because our UI tests are not yet ready to run and this is an OS event.
