### PR TITLE
[iOS] Shell/NavigationPage TitleView

### LINKED ISSUE #5063: [Spec] Shell/NavigationPage TitleView
# NavigationPage/Shell TitleView

Utilize our current LayoutOptions to indicate how you want a TitleView to layout on the screen. All work done here should be generalized so that it applies to Navigation.TitleView as well

These will have no effect as they only apply to cases where the parent is a stack layout
```
StartAndExpand
CenterAndExpand
EndAndExpand
FillAndExpand
```

Realistically users should only need to use Center and Fill

#### VerticalOptions
When used it will center the rendered view inside the given title view container so that the margin above and below the content appear equal

####  HorizontalOptions
Centered on the device screen. View will have a width equal to measured content

#### VerticalOptions
This is the current behavior. The Layout will just layout inside all available vertical space. In a perfect world if the measured height of the supplied layout exceeds the min height of the navigation bar then the navigation bar should be resized to match the height of the TitleView. If this is extremely difficult to get working we can look at doing that for a second PR.

####  HorizontalOptions
This will cause the title view to take up the entire width of the header on the device. So the titleview layout will overlap the backbutton, hamburger, etc...  We can detect this layout option and just not render toolbaritems/hamburger/etc..

#### VerticalOptions
View will measure vertically to the size of the content and will layout against the top edge of the allotted TitleView space.

####  HorizontalOptions
View will measure horizontally to the size of the content and will layout against the left edge of the allotted TitleView space. For example on iOS this will just cause the view to layout against the hamburger

#### VerticalOptions
View will measure vertically to the size of the content and will layout against the bottom edge of the allotted TitleView space.

####  HorizontalOptions
View will measure horizontally to the size of the content and will layout against the right edge of the allotted TitleView space. For example on iOS this will just cause the view to layout against the hamburger
Template level control of the entire experience.

## Additional Work to look at while implementing these changes
- Shell needs to allow the TitleView to be settable at all levels #4650
- If the measured height of the titleview exceeds the navigation bar min height than the navigationbar should resize to the measured content

## XAML Example

This will center the title vertically within the given titleview space and horizontally on the device screen
```xaml
<Shell.TitleView>
     <StackLayout HorizontalOptions="Center" VerticalOptions="Center">
          <Label Text="Title"  />
     </StackLayout>
</Shell.TitleView>
```
***

# Difficulty :  medium

### LINKED ISSUE #9333: Unnecessary Margin in TitleView
### Description

When using the NavigationPage.TitleView there is a margin in all sides that is not required as Title bar should be from the edge to the edge just like the standard title bar.

Here is the screenshot:

362B7A84-EEA8-40C3-B81F-E4DF696DCEA9_1_201_a

### Steps to Reproduce

```
<NavigationPage.TitleView>
    <Grid Margin="0" RowSpacing="0" ColumnSpacing="0" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" BackgroundColor="Yellow" ColumnDefinitions="*,Auto,Auto">
        <Label Grid.Column="0" Text="البيانات" Padding="20" HorizontalOptions="Start" VerticalOptions="Center" />

        <Image Grid.Column="1" WidthRequest="40" HeightRequest="40" Margin="5,5,10,5" VerticalOptions="Center">
        <Image.Source>
            <FontImageSource FontFamily="FontSolid" Glyph="&#xf1e1;" />
        </Image.Source>
        </Image>

        <Image Grid.Column="2" WidthRequest="40" HeightRequest="40" Margin="5,5,10,5" VerticalOptions="Center">
        <Image.Source>
            <FontImageSource FontFamily="FontSolid" Glyph="&#xf107;" />
        </Image.Source>
        </Image>
    </Grid>
</NavigationPage.TitleView>

```

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Latest

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #19231: [iOS] Wrong default left/right margin in the navigation bar on iOS
### Description

When I use a navigation bar on a screen on iOS, it shows as a "left and right margin" by default.

I attach image of the error:
image

On Windows it does not set this left/right margin by default:
image

On Android just set the left margin by default.
I created another issue for the left margin in Android: #18843 
image

### Steps to Reproduce

1. Create a new MAUI project.
2. Change the creation of the MainPage as NavigationPage on App.xaml.cs (If it is created as AppShell).
3. Register MainPage view in MauiProgram.cs
4. Add NavigationPage.TitleView in MainPage.xaml.
5. Launch the application and see the error.

### Link to public reproduction project repository

[Link to the repository](https://github.com/MADSENSE/MADSENSE.MAUI.Sample.App/tree/default-margin-navigationBar-ios)

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.3

### Did you find any workaround?

I couldn't find anything.

### PR DESCRIPTION
**Pull request by kubaflo**
Fixes https://github.com/dotnet/maui/issues/9333
Fixes https://github.com/dotnet/maui/issues/19231
Fixes https://github.com/dotnet/maui/issues/5063

## Current behavior
 Layout options have no effect on the title view. The content inside the `titleView` behaves as it has both `HorizontalOptions` and `VerticalOptions` set to `Fill`. Also, notice that there's a horizontal margin that cannot be removed even with setting the negative values to margin eg. `Margin="-20,0"` (https://github.com/dotnet/maui/issues/19231)

### Currently
Screenshot 2024-03-02 at 14 58 41

## Proposed behavior https://github.com/dotnet/maui/issues/5063
Utilizes our current LayoutOptions to indicate how you want a TitleView to layout on the screen and removes the default horizontal margin so that we can customize it.

```
<NavigationPage.TitleView>
    <HorizontalStackLayout BackgroundColor="red">
        <Label VerticalOptions="Center" Text="Navigation page's title"/>
        <Image Source="dotnet_bot.png" Scale="0.8"/>
    </HorizontalStackLayout>
</NavigationPage.TitleView>
```

### `Default` - (horizontal and vertical options set to fill implicitly)

Screenshot 2024-03-02 at 15 00 41

### `HorizontalOptions="Start"`
Screenshot 2024-03-02 at 15 02 14

### `HorizontalOptions="Center"`
Screenshot 2024-03-02 at 15 04 44

### `HorizontalOptions="End"`
Screenshot 2024-03-02 at 15 05 47

### `VerticalOptions="Start"`
Screenshot 2024-03-02 at 15 09 49

### `VerticalOptions="Center"`
Screenshot 2024-03-02 at 15 07 58

### `VerticalOptions="End"`
Screenshot 2024-03-02 at 15 06 56

### `VerticalOptions="Start"` `HorizontalOptions="Start"`
Screenshot 2024-03-02 at 15 15 30

### `VerticalOptions="Center"` `HorizontalOptions="Center"`
Screenshot 2024-03-02 at 15 14 42

### `VerticalOptions="End"` `HorizontalOptions="End"`
Screenshot 2024-03-02 at 15 15 07

## Remarks
I didn't implement anything that changes the behavior when additional toolbar items are added. For example, if there's a back button the title view places itself to the right of this button. It is because I'm not sure what is the desired behavior. On one hand, it looks weird that when we want to center the title it is moved to the right, but on the other, it is the default iOS's behavior and I believe a future discussion should be made https://github.com/xamarin/Xamarin.Forms/issues/4848
Screenshot 2024-03-02 at 16 10 55

### CODE REVIEW

**Comment by Pastajello** [comment]
Oh my, never knew I'd see a fix from the issue I suffered 4 years ago in X.F. days! Are there any plans to add it to .net 8 SR 4? (hopefully)

**Review by idzson — APPROVED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs [hunk 1]
```diff
@@ -1765,6 +1766,7 @@ class Container : UIView
 			IPlatformViewHandler _child;
 			UIImageView _icon;
 			bool _disposed;
+			const int SystemMargin = 16;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs:1769]: Could you include a comment with a link to the Apple docs or similar?

File: src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs [hunk 2]
```diff
@@ -1796,6 +1798,44 @@ public Container(View view, UINavigationBar bar) : base(bar.Bounds)
...
+				// A margin of private class `UINavigationButton` is different from custom view
+				if (!UIDevice.CurrentDevice.CheckSystemVersion(11, 0) && screenWidth < 375)
+				{
+					// 3.5 and 4 inch
+					spacer.Width += 8;
+				}
+				else if (screenWidth >= 414)
+				{
+					// 5.5 inch
+					spacer.Width -= 4;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs:1828]: Have you done tests with 6.1" and 6.7" simulators or devices?

**Review by PureWeen — CHANGES_REQUESTED** [review]
can you retarget this for net9?

**Comment by kubaflo** [comment]
> can you retarget this for net9?

Yep, I think it is a good idea

**Comment by TheXenocide** [comment]
> > can you retarget this for net9?
> 
> Yep, I think it is a good idea

Is there no chance we can get this fix in a patch release for .NET 8? Preferably sooner than later? I'm wrestling with this issue at the moment and would really appreciate a fix but we only use LTS versions for production apps.

**Comment by TheXenocide** [comment]
I also can't use this code directly in our app because too many pieces are internal for me to drop this in as a replacement renderer.

**Comment by Felix-Dev** [comment]
@kubaflo Any update on this PR? What is blocking progress here?

**Comment by kubaflo** [comment]
Hi, @Felix-Dev it is not up to me what will happen with this pr

**Comment by Felix-Dev** [comment]
@PureWeen What is blocking this PR from being merged? The "requested changes" seems to have been adressed by @kubaflo. We are interested in seeing this change land in MAUI. Thanks!

**Comment by jbeacham** [comment]
This is also affecting us, an app with millions of users being forced to migrate to MAUI. Huge gaps on either end of the nav bar if we try to do any other color. Any update? Any workaround? @PureWeen

**Comment by jbeacham** [comment]
@kubaflo It looks like 2 failing checks. Anything you're familiar with so this can get merged?

**Comment by kubaflo** [comment]
@jbeacham Hi!, It's not up to me when and if PRs get merged, but I will rebase this one and solve conflicts :)

**Comment by amirvenus** [comment]
I seem to have a similar issue on android too

**Comment by dainius-r** [comment]
@kubaflo thanks for PR, have you noticed similar PR for Android, or maybe some workaround?

**Comment by kubaflo** [comment]
@dainius-r regarding the left margin: https://github.com/dotnet/maui/pull/20967
When it comes to LayoutOptions, I think they are respected on Android

```
<NavigationPage.TitleView>
    <HorizontalStackLayout HorizontalOptions="End" BackgroundColor="red">
        <Label VerticalOptions="Center"
                Text="Navigation page's title"/>
        <Image Source="dotnet_bot.png"
                Scale="0.8"/>
    </HorizontalStackLayout>
</NavigationPage.TitleView>
```

**Comment by dainius-r** [comment]
@kubaflo many thanks, that's my issue I was lookin for https://github.com/dotnet/maui/pull/20967

**Comment by YZahringer** [comment]
Any update on this PR? What is blocking progress here?

**Review by jfversluis — APPROVED** [review]
