### PR TITLE
[iOS, Mac] Fix for Background set to Transparent doesn't have the same behavior as BackgroundColor Transparent

### LINKED ISSUE #22769: Background set to Transparent doesn't have the same behavior as BackgroundColor = Transparent
### Description

In my attempt to make my modal page transparent, I found this issue where `Background = Transparent` doesn't have the desired effect, but `BackgroundColor = Transparent` does have. They should have the same behavior, no?

With `Background = "Transparent"`:

<image src= "https://github.com/dotnet/maui/assets/20712372/d433bec6-2fd6-4920-95b1-9716cfe4ff3e" width=400/>

With `BackgroundColor= "Transparent"`:

<image src= "https://github.com/dotnet/maui/assets/20712372/fa070465-43dd-4df1-81c8-179793610297" width=400/>

### Steps to Reproduce

1. Open the repro project
2. Click on the button to do a Modal Navigation
3. You can't see the underline page (If using Background = Transparent)

### Link to public reproduction project repository

https://github.com/pictos/BackgroundTransparentIssue

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

Use BackgroundColor instead

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by HarishwaranVijayakumar**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue Details

- Setting a modal page’s background to transparent does not produce the same result as using BackgroundColor="Transparent".

### Root Cause of the issue

- In the ControlsModalWrapper, only the BackgroundColor property is checked — the Background property isn’t considered. Therefore, the page continues to use the UIModalPresentationStyle.FullScreen mode.

### Description of Change
**Transparency detection improvements:**

* Added internal static method `Brush.HasTransparency(Brush background)` to reliably detect transparency in both `SolidColorBrush` and `GradientBrush` types.

**Modal presentation logic update:**

* Updated `ControlsModalWrapper` constructor to use `Brush.HasTransparency ` for determining if a modal page should use `OverFullScreen` presentation style, ensuring correct handling of transparent backgrounds set via the `Background` property.

### Issues Fixed

Fixes #22769 

### Tested the behaviour in the following platforms

- [x] - Windows 
- [x] - Android
- [x] - iOS
- [x] - Mac

### Output
| Before | After |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/f90704db-9d8f-4667-9986-59a9c741531d"> | <video src="https://github.com/user-attachments/assets/81200022-417d-4918-818b-55046add231f"> |

### CODE REVIEW

File: src/Controls/src/Core/Brush/Brush.cs [hunk 1]
```diff
@@ -116,6 +116,29 @@ public static bool IsNullOrEmpty(Brush brush)
 			return brush == null || brush.IsEmpty;
 		}
 
+		internal static bool HasTransparency(Brush background)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Brush/Brush.cs:120]: Can include a TODO comment to make it public in the future (.NET 11)?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Brush/Brush.cs (hunk 1 above)
Comment (HarishwaranVijayakumar) [reply src/Controls/src/Core/Brush/Brush.cs:120]: @jsuarezruiz, I have included the comment

File: src/Controls/src/Core/Brush/Brush.cs [hunk 2]
```diff
@@ -116,6 +116,30 @@ public static bool IsNullOrEmpty(Brush brush)
 			return brush == null || brush.IsEmpty;
 		}
 
+		// TODO: Make this method public in .NET 11
+		internal static bool HasTransparency(Brush background)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Brush/Brush.cs:120]: Could include some unit tests? Unit tests covering SolidColorBrush with alpha, GradientBrush with opaque and mixed stops, and null/empty brushes to lock behavior

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Brush/Brush.cs (hunk 2 above)
Comment (HarishwaranVijayakumar) [reply src/Controls/src/Core/Brush/Brush.cs:120]: @jsuarezruiz, I have added the unit test.

**Comment by rmarinho** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Modified the test</strong> · <a href="https://github.com/dotnet/maui/commit/94d8641d100e60d50a1a0a8b762a5af4a6842086"><code>94d8641</code></a></summary>

---

**Issue:** #22769 - Background set to Transparent doesn't have the same behavior as BackgroundColor Transparent
**PR:** #32245 - [iOS, Mac] Fix for Background set to Transparent doesn't have the same behavior as BackgroundColor Transparent
**Author:** HarishwaranVijayakumar (Syncfusion partner contributor)
**Platforms Affected:** iOS, MacCatalyst (fix is in `Platform/iOS/ControlsModalWrapper.cs`)
**Files Changed:** 2 implementation files, 6 test files

### Issue Summary

When setting a modal page's background using `Background = "Transparent"` (the `Brush`-based property), the modal page does NOT become transparent — the underlying page is not visible through it. However, when using `BackgroundColor = "Transparent"` (the `Color`-based property), the modal page correctly becomes transparent. These two properties should have the same behavior.

The bug is iOS/macOS-specific because the fix is in `ControlsModalWrapper` which handles modal presentation style selection on those platforms.

### Root Cause (from PR description)

In `ControlsModalWrapper`, only `BackgroundColor` was checked to determine whether the modal should use `UIModalPresentationStyle.OverFullScreen` (which allows transparency). The `Background` brush property was never consulted. Since a transparent `Brush` doesn't propagate to `BackgroundColor`, the modal continued to use `FullScreen` presentation style, which doesn't allow transparency.

### Fix Approach

1. **`Brush.cs`**: Added `internal static bool HasTransparency(Brush background)` that checks:
   - For `SolidColorBrush`: checks if `Color.Alpha < 1`
   - For `GradientBrush`: checks if any `GradientStop.Color.Alpha < 1`
   - Null/empty brush returns false

2. **`ControlsModalWrapper.cs`**: Updated constructor logic:
   - If `Background` brush is non-null/empty, use `Brush.HasTransparency(modalBackground)` 
   - Otherwise fall back to the original `BackgroundColor?.Alpha < 1` check

### Files Changed

**Fix files:**
- `src/Controls/src/Core/Brush/Brush.cs` (+24/-0) - New `HasTransparency` method
- `src/Controls/src/Core/Platform/iOS/ControlsModalWrapper.cs` (+10/-2) - Check both Background and BackgroundColor

**Test files:**
- `src/Controls/tests/Core.UnitTests/LinearGradientBrushTests.cs` (+57) - Unit tests for `HasTransparency`
- `src/Controls/tests/Core.UnitTests/RadialGradientBrushTests.cs` (+57) - Unit tests for `HasTransparency`
- `src/Controls/tests/Core.UnitTests/SolidColorBrushTests.cs` (+23) - Unit tests for `HasTransparency`
- `src/Controls/tests/TestCases.HostApp/Issues/Issue22769.cs` (+84) - HostApp UI test page
- `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22769.cs` (+24) - NUnit UI test
- Snapshot PNG files (iOS, Android, Mac, Windows)

### Reviewer Feedback

| Thread | Reviewer | Request | Author Response | Status |
|--------|----------|---------|-----------------|--------|
| Brush.cs:120 | jsuarezruiz | Add TODO comment to make public in .NET 11 | Added `// TODO: Make this method public in .NET 11` | ✅ RESOLVED |
| Brush.cs:120 | jsuarezruiz | Add unit tests (SolidColorBrush alpha, GradientBrush opaque/mixed, null/empty) | Added 3 test files | ⚠️ NOT RESOLVED (thread not closed) |

### Fix Candidates

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #32245 | Add `Brush.HasTransparency()` method; update `ControlsModalWrapper` to check `Background` brush first, fallback to `BackgroundColor` | ⏳ PENDING (Gate) | `Brush.cs` (+24), `ControlsModalWrapper.cs` (+10/-2) | Original PR |

</details>

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Modified the test</strong> · <a href="https://github.com/dotnet/maui/commit/94d8641d100e60d50a1a0a8b762a5af4a6842086"><code>94d8641</code></a></summary>

---

**Result:** ✅ PASSED
**Platform:** ios
**Mode:** Full Verification

- Tests FAIL without fix ✅
- Tests PASS with fix ✅

**Test:** `ModalPageBackgroundShouldBeTransparent` (Issue22769)
**Fix Files Reverted:** `src/Controls/src/Core/Brush/Brush.cs`, `src/Controls/src/Core/Platform/iOS/ControlsModalWrapper.cs`

</details>

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Modified the test</strong> · <a href="https://github.com/dotnet/maui/commit/94d8641d100e60d50a1a0a8b762a5af4a6842086"><code>94d8641</code></a></summary>

---

# Fix Phase: Try-Fix Results

## Summary

4 alternative fix approaches were tested (attempts 2-5). All passed.

## Selected Fix

Selected Fix: PR's Approach — `Brush.HasTransparency()` in Brush.cs + check in ControlsModalWrapper constructor

Exhausted: No — 4 of 4 alternatives passed

## Fix Candidates

| Attempt | Approach | Files Changed | Result | Notes |
|---------|----------|---------------|--------|-------|
| PR | `Brush.HasTransparency()` static method in Brush.cs + check in ControlsModalWrapper constructor | Brush.cs + ControlsModalWrapper.cs | ✅ PASS (Gate) | Adds reusable API to Brush with TODO for .NET 11 |
| Attempt 2 | Inline `IsBrushTransparent()` helper in ControlsModalWrapper.cs only | ControlsModalWrapper.cs | ✅ PASS | Encapsulated, no Brush.cs changes |
| Attempt 3 | Minimal SolidColorBrush-only inline check in constructor | ControlsModalWrapper.cs | ✅ PASS | Simpler but incomplete (no GradientBrush support) |
| Attempt 4 | Explicit if/else branching (SolidColorBrush + GradientBrush with foreach) | ControlsModalWrapper.cs | ✅ PASS | No helper method needed |
| Attempt 5 | Private static helper `IsPageBackgroundTransparent()` + Background property subscription | ControlsModalWrapper.cs | ✅ PASS | Most complete: fixes constructor + dynamic property updates |

## Key Technical Finding

`GradientStopCollection` does not support LINQ `.Any()` extension methods — a `foreach` loop must be used. All attempts that handle GradientBrush correctly use a foreach loop.

## Recommendation

**Approve the PR** with the existing approach. The PR's design decision to put the logic in Brush.cs (with future public API intent) is sound architectural thinking, even if ControlsModalWrapper-only alternatives also work.

</details>

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Modified the test</strong> · <a href="https://github.com/dotnet/maui/commit/94d8641d100e60d50a1a0a8b762a5af4a6842086"><code>94d8641</code></a></summary>

---

# Phase 4: Report — PR #32245

## Summary

**PR:** [#32245](https://github.com/dotnet/maui/pull/32245) — [iOS, Mac] Fix for Background set to Transparent doesn't have the same behavior as BackgroundColor Transparent  
**Author:** @HarishwaranVijayakumar (Syncfusion partner)  
**Issue:** Fixes #22769  
**Verdict:** ✅ **RECOMMEND APPROVE** (with minor suggestions)

---

## Phase Results

| Phase | Result | Notes |
|-------|--------|-------|
| Pre-Flight | ✅ Complete | Community/Syncfusion partner PR, well-structured |
| Gate | ✅ PASSED | Tests fail without fix, pass with fix on iOS |
| Fix (try-fix) | ✅ 4/4 PASS | All alternative approaches validated |
| PR Finalize | ✅ Good | Minor description inaccuracy found |

---

## What the PR Does

**Bug:** Setting `Background = "Transparent"` on a modal `ContentPage` on iOS/Mac didn't produce the same transparent presentation as `BackgroundColor = "Transparent"`. The modal appeared with a white/opaque background instead of showing the content underneath.

**Root Cause:** `ControlsModalWrapper` constructor (iOS-only) only checked `BackgroundColor` when deciding whether to use `UIModalPresentationStyle.OverFullScreen`. The `Background` brush property was ignored entirely.

**Fix:**
1. Added `internal static bool HasTransparency(Brush background)` to `Brush.cs` — checks `SolidColorBrush.Color.Alpha < 1` and iterates `GradientBrush` stops for any with `Alpha < 1`
2. Updated `ControlsModalWrapper` constructor: when `Background` brush is set, checks it via `HasTransparency`; falls back to `BackgroundColor?.Alpha < 1` if `Background` is null/empty (backward compatible)

---

## Gate Verification

Tests verified on **iOS** platform:
- ✅ **Without fix**: `ModalPageBackgroundShouldBeTransparent()` FAILS (screenshot comparison fails — modal is opaque)
- ✅ **With fix**: Test PASSES (modal shows underlying content through transparent background)

---

## Try-Fix Exploration

4 alternative approaches all succeeded, confirming the fix logic is sound:

| # | Approach | Different From PR | Result |
|---|----------|-------------------|--------|
| 2 | Inline `IsBrushTransparent()` helper in ControlsModalWrapper only (no Brush.cs) | No Brush.cs API change | ✅ PASS |
| 3 | Minimal SolidColorBrush-only check in constructor | Ignores GradientBrush | ✅ PASS |
| 4 | Explicit if/else branching with foreach | No helper method | ✅ PASS |
| 5 | Static `IsPageBackgroundTransparent()` + Background property subscription | Also handles dynamic Background changes | ✅ PASS |

**Key finding:** `GradientStopCollection` doesn't support LINQ `.Any()` — a foreach loop is required. The PR correctly uses foreach.

**Best approach:** PR's approach (putting logic in `Brush.cs` with TODO to make public in .NET 11) is the right architectural choice, enabling future reuse across the framework.

---

## Code Review Findings

### ✅ Strong Points
- `Brush.IsNullOrEmpty` guard ensures backward compatibility (BackgroundColor path preserved)
- Comprehensive unit tests in 3 brush test files (SolidColorBrush, LinearGradient, RadialGradient)
- UI tests added for all 4 platforms with committed screenshot snapshots
- Forward-thinking TODO comment for making API public in .NET 11

### 🟡 Minor Issues (Non-Blocking)

1. **Extra blank line in `HasTransparency`** — cosmetic only, inside method body after opening `{`
2. **Description says `Brush.IsTransparent` but code is `Brush.HasTransparency`** — needs update before merge
3. **Test files missing trailing newlines** — `LinearGradientBrushTests.cs`, `RadialGradientBrushTests.cs`, `SolidColorBrushTests.cs`, `Issue22769.cs` all end without `\n`
4. **Empty "Output" table in PR description** — before/after images not provided

### 🔴 No Critical Issues

---

## Unresolved Review Thread

Reviewer @jsuarezruiz requested unit tests — these have been added but the review thread was **not marked as resolved**. The reviewer should mark it resolved or confirm the tests are satisfactory.

---

## Recommendation

**✅ APPROVE** with these pre-merge requests:

1. Update PR description: change `Brush.IsTransparent` → `Brush.HasTransparency`
2. Remove or fill the empty "Output" table
3. Ask reviewer @jsuarezruiz to resolve the unit tests review thread
4. Optional: Remove blank line in `HasTransparency`, add trailing newlines to test files

The fix is correct, well-tested, backward-compatible, and from a Syncfusion partner contributor. Merging is appropriate once the description inaccuracy is fixed.

</details>

</details>

---

</details>



<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

---

<details>

<summary><b>Title: ✅ Good</b></summary>

<br>

**Current:** `[iOS, Mac] Fix for Background set to Transparent doesn't have the same behavior as BackgroundColor Transparent`
</details>

<details>

<summary><b>Description: ✅ Good</b></summary>

<br>

- "Fix for" prefix is verbose and adds no information value
- The title is too long and essentially repeats the issue title verbatim
- Doesn't describe *what* was done (the key insight: OverFullScreen presentation style now respects `Background` property)
### ✨ Suggested PR Description


> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!


### Issue Details

- Setting a modal page's background to transparent does not produce the same result as using `BackgroundColor="Transparent"`.

### Root Cause of the issue

- In `ControlsModalWrapper`, only the `BackgroundColor` property was checked — the `Background` (brush) property was not considered. Therefore, the page continued to use `UIModalPresentationStyle.FullScreen` even when `Background = Brush.Transparent` was set.

### Description of Change
**Transparency detection improvements:**

* Added internal static method `Brush.HasTransparency(Brush background)` to reliably detect transparency in both `SolidColorBrush` and `GradientBrush` types.

**Modal presentation logic update:**

* Updated `ControlsModalWrapper` constructor to use `Brush.HasTransparency` for determining if a modal page should use `OverFullScreen` presentation style, ensuring correct handling of transparent backgrounds set via the `Background` property.
* Falls back to checking `BackgroundColor` when no `Background` brush is set.


### Issues Fixed


Fixes #22769 

### Tested the behaviour in the following platforms

- [x] - Windows 
- [x] - Android
- [x] - iOS
- [x] - Mac
</details>

<details>

<summary><b>Code Review: ✅ Passed</b></summary>

<br>

# Code Review — PR #32245

## Summary

3 minor issues found. No critical bugs. The core implementation is logically correct.

---

## 🟡 Minor Issues

### 1. Method name mismatch in PR description

**File:** PR description (not code)  
**Problem:** The description states the method is `Brush.IsTransparent(Brush background)` but the actual method name in code is `Brush.HasTransparency(Brush background)`.  
**Recommendation:** Update the description to use the correct method name `HasTransparency`.

---

### 2. Missing newline at end of files

**Files:**
- `src/Controls/tests/Core.UnitTests/SolidColorBrushTests.cs`
- `src/Controls/tests/Core.UnitTests/LinearGradientBrushTests.cs`
- `src/Controls/tests/Core.UnitTests/RadialGradientBrushTests.cs`
- `src/Controls/tests/TestCases.HostApp/Issues/Issue22769.cs`

**Problem:** All four files end without a trailing newline (`\ No newline at end of file` in diff).  
**Recommendation:** Add a trailing newline to each file. This is a minor style inconsistency but can cause diff noise in future edits.

---

### 3. Inconsistent access modifier in HostApp test page

**File:** `src/Controls/tests/TestCases.HostApp/Issues/Issue22769.cs`  
**Problem:** `Issue22769_MainPage` is `internal` but `Issue22769_ContentPage` is `public`. Since both are inner test helper classes, they should share the same access modifier.  
**Recommendation:** Make `Issue22769_ContentPage` `internal` to match `Issue22769_MainPage`.

```csharp
// Current
public class Issue22769_ContentPage : ContentPage  // ← should be internal

// Recommended
internal class Issue22769_ContentPage : ContentPage
```

---

## ✅ Looks Good

- **`Brush.HasTransparency` logic** is correct: handles null brush (returns false), null Color on SolidColorBrush (safe via `?.`), null GradientStops (guarded explicitly), and correctly iterates stops for any transparent color.
- **`ControlsModalWrapper` fallback logic** is well structured: checks `Background` brush first, falls back to `BackgroundColor` if no brush is set — matches user-expected priority.
- **Unit test coverage** is thorough: all three brush types (Solid, Linear, Radial) tested with null, empty, opaque, transparent, semi-transparent, and mixed cases.
- **`TODO` comment** (`// TODO: Make this method public in .NET 11`) is appropriate for planning a future public API.
- **UI test** uses `VerifyScreenshot()` for cross-platform visual validation with snapshots committed for all 4 platforms.
- **Platform scope** is correct: the bug and fix are in `Platform/iOS/ControlsModalWrapper.cs` — the `[iOS, Mac]` title tag is accurate.
</details>

---

</details>

**Review by kubaflo — APPROVED** [review]
