### PR TITLE
Fixed Android's StreamImageSourceService.LoadDrawableAsync()

### LINKED ISSUE #14052: Only the original thread that created a view hierarchy can touch its view
### Description

I seem to have an unhandled exception in Android when showing images on a page. The error is:

Android.Util.AndroidRuntimeException: 'Only the original thread that created a view hierarchy can touch its views.'

image

### Steps to Reproduce

Open the project in the repository below.
Run the project and click the "Image Error" button.
This will open a page which downloads some images from a web API.
Scroll up and down the page a few times. Eventually the error will occur.

### Link to public reproduction project repository

https://github.com/williambuchanan2/MauiNavigation

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and 13

### Did you find any workaround?

No. Unable to proceed with project so this is a blocking problem.

### Relevant log output

_No response_

### LINKED ISSUE #15397: ImageSource.FromStream Leads to Crash
### Description

If you use an Image and populate it source trough ImageSource.FromStream and you have a sort of android service wich keeps the mainactivity somehow alive than if you start and close the app it leads to an crash

I found this out by diagnosing the callstack and trying to reproduce it with a clean project with only the services and the mainpage with a image in combination with ImageSource fromstream.

i added the log, callstack and a repoduction repo
[callStack.txt](https://github.com/dotnet/maui/files/11627092/callStack.txt)
[exception.txt](https://github.com/dotnet/maui/files/11627094/exception.txt)
[debugLog.txt](https://github.com/dotnet/maui/files/11627095/debugLog.txt)

### Steps to Reproduce

1. Create Maui Project
2. Create A Service wich is sticky and wont get terminated on app close and keeps the root activity alive
3. Create on the main page the image and the code that loads an imagefrom memorystream
4. Start the app
5. Wait untill Foreground service starts
6. Close App (Really Closing via dismissing the frame)
7. Open the app again

Experienced behaviour: App runs smoothly
Observed behaviour: App crashes

### Link to public reproduction project repository

[Reproduction project](https://github.com/DeepWorksStudios/ReproductionProjectBug15397_ImageSourceFromStream)

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Any Api Level

### Did you find any workaround?

Yes via using the HandlerChanged event
i added the solution in the repo aswell in mainpage.cs

### Relevant log output

```shell
Start debugging Android application ...
Forwarding debugger port 8879
Detecting existing process
> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.companyname.reproductionprojectbug_imagesourcefromstream/crc64ec1f2e46cb2b668f.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.companyname.reproductionprojectbug_imagesourcefromstream/crc64ec1f2e46cb2b668f.MainActivity }
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/ReproductionProjectBug_ImageSourceFromStream.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Mono.Android.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Runtime.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Java.Interop.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Runtime.InteropServices.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Collections.dll [External]
Resolved pending breakpoint for 'Android.Runtime.JNIEnv.RegisterJniNatives(System.IntPtr, System.Int32, System.IntPtr, System.IntPtr, System.Int32)' to /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:127 [0x00000].
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Threading.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Threading.Thread.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Diagnostics.StackTrace.dll [External]
Loaded assembly: data-0xa7b0c020 [External]
Loaded assembly: data-0xa7b24040 [External]
Loaded assembly: data-0xa2bd1e60 [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/netstandard.dll [External]
[ourcefromstrea] Late-enabling -Xcheck:jni
[ourcefromstrea] Using CollectorTypeCC GC.
[ProcessState] Binder ioctl to enable oneway spam detection failed: Invalid argument
[CompatibilityChangeReporter] Compat change id reported: 171979766; UID 10183; state: ENABLED
[ziparchive] Unable to open '/data/app/~~8tlV5wnEuvt8eMkwzyK8TQ==/com.companyname.reproductionprojectbug_imagesourcefromstream-VggzvcV1Dx5h9-zSuNjjSw==/base.dm': No such file or directory
[ziparchive] Unable to open '/data/app/~~8tlV5wnEuvt8eMkwzyK8TQ==/com.companyname.reproductionprojectbug_imagesourcefromstream-VggzvcV1Dx5h9-zSuNjjSw==/base.dm': No such file or directory
[nativeloader] Configuring classloader-namespace for other apk /data/app/~~8tlV5wnEuvt8eMkwzyK8TQ==/com.companyname.reproductionprojectbug_imagesourcefromstream-VggzvcV1Dx5h9-zSuNjjSw==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~8tlV5wnEuvt8eMkwzyK8TQ==/com.companyname.reproductionprojectbug_imagesourcefromstream-VggzvcV1Dx5h9-zSuNjjSw==/lib/arm:/data/app/~~8tlV5wnEuvt8eMkwzyK8TQ==/com.companyname.reproductionprojectbug_imagesourcefromstream-VggzvcV1Dx5h9-zSuNjjSw==/base.apk!/lib/armeabi-v7a, permitted_path=/data:/mnt/expand:/data/user/0/com.companyname.reproductionprojectbug_imagesourcefromstream
[GraphicsEnvironment] ANGLE Developer option for 'com.companyname.reproductionprojectbug_imagesourcefromstream' set to: 'default'
[GraphicsEnvironment] Neither updatable production driver nor prerelease driver is supported.
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[debug-app-helper] Checking if libmonodroid was unpacked to /data/app/~~8tlV5wnEuvt8eMkwzyK8TQ==/com.companyname.reproductionprojectbug_imagesourcefromstream-VggzvcV1Dx5h9-zSuNjjSw==/lib/arm/libmonodroid.so
[debug-app-helper] Native libs extracted to /data/app/~~8tlV5wnEuvt8eMkwzyK8TQ==/com.companyname.reproductionprojectbug_imagesourcefromstream-VggzvcV1Dx5h9-zSuNjjSw==/lib/arm, assuming application/android:extractNativeLibs == true
[debug-app-helper] Setting up for DSO lookup in app data directories
[debug-app-helper] Added filesystem DSO lookup location: /data/app/~~8tlV5wnEuvt8eMkwzyK8TQ==/com.companyname.reproductionprojectbug_imagesourcefromstream-VggzvcV1Dx5h9-zSuNjjSw==/lib/arm
[debug-app-helper] Using runtime path: /data/app/~~8tlV5wnEuvt8eMkwzyK8TQ==/com.companyname.reproductionprojectbug_imagesourcefromstream-VggzvcV1Dx5h9-zSuNjjSw==/lib/arm
[debug-app-helper] checking directory: `/data/user/0/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/lib`
[debug-app-helper] directory does not exist: `/data/user/0/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/lib`
[debug-app-helper] Checking whether Mono runtime exists at: /data/user/0/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/libmonosgen-2.0.so
[debug-app-helper] Checking whether Mono runtime exists at: /data/app/~~8tlV5wnEuvt8eMkwzyK8TQ==/com.companyname.reproductionprojectbug_imagesourcefromstream-VggzvcV1Dx5h9-zSuNjjSw==/lib/arm/libmonosgen-2.0.so
[debug-app-helper] Mono runtime found at: /data/app/~~8tlV5wnEuvt8eMkwzyK8TQ==/com.companyname.reproductionprojectbug_imagesourcefromstream-VggzvcV1Dx5h9-zSuNjjSw==/lib/arm/libmonosgen-2.0.so
[ourcefromstrea] Attempt to remove non-JNI local reference, dumping thread
[DOTNET] JNI_OnLoad: JNI_OnLoad in pal_jni.c
[DOTNET] GetOptionalClassGRef: optional class com/android/org/conscrypt/OpenSSLEngineImpl was not found
[monodroid] Creating public update directory: `/data/user/0/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__`
[ourcefromstrea] Attempt to remove non-JNI local reference, dumping thread
[monodroid-debug] Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=127.0.0.1:8879,server=y,embedding=1
[monodroid-assembly] open_from_bundles: failed to load assembly ReproductionProjectBug_ImageSourceFromStream.dll
[monodroid-gc] GREF GC Threshold: 46080
[monodroid-assembly] open_from_bundles: failed to load assembly Mono.Android.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Java.Interop.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.InteropServices.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.Thread.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.StackTrace.dll
[ourcefromstrea] Attempt to remove non-JNI local reference, dumping thread
[monodroid-assembly] open_from_bundles: failed to load assembly netstandard.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Linq.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Linq.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.Concurrent.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Collections.Concurrent.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:423 [0x00000].
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Json.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Text.Json.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encodings.Web.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Text.Encodings.Web.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.ComponentModel.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Maui.Controls.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.ObjectModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.ObjectModel.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Maui.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Graphics.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Essentials.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Abstractions.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Maui.Graphics.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Maui.Essentials.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Extensions.Logging.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.TypeConverter.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.ComponentModel.TypeConverter.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.Uri.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Private.Uri.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Loader.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Runtime.Loader.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:418 [0x00000].
[monodroid-assembly] open_from_bundles: failed to load assembly System.Memory.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Memory.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.Lightweight.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.ILGeneration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Primitives.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Reflection.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Core.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.Core.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.Abstractions.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Extensions.DependencyInjection.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Console.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Console.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Xaml.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.Abstractions.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Debug.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Maui.Controls.Xaml.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Extensions.Configuration.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Extensions.Configuration.Abstractions.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Extensions.Logging.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Extensions.Logging.Debug.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.AppCompat.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.Google.Android.Material.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.SwipeRefreshLayout.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.AppCompat.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.Google.Android.Material.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.SwipeRefreshLayout.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Fragment.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Activity.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.ViewModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.Common.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.SavedState.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.Fragment.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.Activity.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.Lifecycle.ViewModel.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.Lifecycle.Common.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.SavedState.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.DrawerLayout.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CustomView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Navigation.Runtime.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.DrawerLayout.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.CustomView.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.Navigation.Runtime.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Net.Primitives.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Net.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Options.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Extensions.Options.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Extensions.DependencyInjection.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.Tracing.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Diagnostics.Tracing.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Xml.ReaderWriter.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.Xml.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Private.Xml.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encoding.Extensions.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Text.Encoding.Extensions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly en-GB/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en-GB/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Numerics.Vectors.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Numerics.Vectors.dll [External]
[ourcefromstrea] Explicit concurrent copying GC freed 72420(3360KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2063KB/4111KB, paused 83us,43us total 17.862ms
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.RegularExpressions.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Text.RegularExpressions.dll [External]
Thread started:  #2
Thread started:  #3
Thread started:  #4
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Json.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.DataContractSerialization.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Xml.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Serialization.Primitives.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Runtime.Serialization.Json.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Private.DataContractSerialization.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Runtime.Serialization.Xml.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Runtime.Serialization.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly en-GB/System.Private.DataContractSerialization.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en-GB/System.Private.DataContractSerialization.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en/System.Private.DataContractSerialization.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en/System.Private.DataContractSerialization.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.RecyclerView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CardView.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.RecyclerView.dll [External]
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.CardView.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Loader.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.Loader.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Compatibility.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Maui.Controls.Compatibility.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Window.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.Window.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CoordinatorLayout.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.CoordinatorLayout.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.LiveData.Core.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.Lifecycle.LiveData.Core.dll [External]
[ourcefromstrea] Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
[ourcefromstrea] Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.ViewPager2.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.ViewPager2.dll [External]
[CompatibilityChangeReporter] Compat change id reported: 171228096; UID 10183; state: ENABLED
[TabLayout] MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.Runtime.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.Lifecycle.Runtime.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.ViewPager.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Xamarin.AndroidX.ViewPager.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Net.Http.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Net.Http.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Security.Cryptography.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Security.Cryptography.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.DiagnosticSource.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Diagnostics.DiagnosticSource.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.NonGeneric.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Collections.NonGeneric.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Net.Requests.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Net.Requests.dll [External]
Thread started: .NET Timer #5
Thread started: <Thread Pool> #6
Thread started: .NET ThreadPool Gate #7
Thread started: <Thread Pool> #8
[SurfaceFactory] [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@bd3c12f
[ViewRootImpl[MainActivity]] hardware acceleration = true, sRendererEnabled = true, forceHwAccelerated = false
[BufferQueueConsumer] [](id:18ab00000000,api:0,p:-1,c:6315) connect: controlledByApp=false
[BLASTBufferQueue] [ViewRootImpl[MainActivity]#0] constructor()
[hw-ProcessState] Binder ioctl to enable oneway spam detection failed: Invalid argument
[BufferQueueProducer] [ViewRootImpl[MainActivity]#0(BLAST Consumer)0](id:18ab00000000,api:1,p:6315,c:6315) connect: api=1 producerControlledByApp=true
[ion] ioctl c0044901 failed with code -1: Invalid argument
Thread started: <Thread Pool> #9
[OpenGLRenderer] fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
[OpenGLRenderer] fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
[monodroid-assembly] open_from_bundles: failed to load assembly System.IO.Compression.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.IO.Compression.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Primitives.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/Microsoft.Extensions.Primitives.dll [External]
[monodroid-assembly] Shared library 'liblog' not loaded, p/invoke '__android_log_print' may fail
[DOTNET] Foreground task is running...
Thread started:  #10
[DOTNET] Foreground task is running...
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Intrinsics.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Runtime.Intrinsics.dll [External]
[DOTNET] Foreground task is running...
[DOTNET] Foreground task is running...
[monodroid-assembly] open_from_bundles: failed to load assembly System.Xml.XmlSerializer.dll
Loaded assembly: /data/data/com.companyname.reproductionprojectbug_imagesourcefromstream/files/.__override__/System.Xml.XmlSerializer.dll [External]
Thread started: <Thread Pool> #11
Thread started: <Thread Pool> #12
[DOTNET] Foreground task is running...
[DOTNET] Foreground task is running...
[DOTNET] Foreground task is running...
[BufferQueueProducer] [ViewRootImpl[MainActivity]#0(BLAST Consumer)0](id:18ab00000000,api:1,p:6315,c:6315) disconnect: api 1
[BLASTBufferQueue] [ViewRootImpl[MainActivity]#0] destructor()
[BufferQueueConsumer] [ViewRootImpl[MainActivity]#0(BLAST Consumer)0](id:18ab00000000,api:0,p:-1,c:6315) disconnect
[BLASTBufferQueue] releaseBufferCallbackThunk bufferId:27122718474246 framenumber:3 blastBufferQueue is dead
[View] [Warning] assignParent to null: this = DecorView@1e1d17e[MainActivity]
[DOTNET] Foreground task is running...
[DOTNET] Foreground task is running...
[DOTNET] Background task is running...
[DOTNET] Foreground task is running...
[DOTNET] Background task is running...
[DOTNET] Foreground task is running...
[TabLayout] MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
[ViewRootImpl[MainActivity]] hardware acceleration = true, sRendererEnabled = true, forceHwAccelerated = false
[BufferQueueConsumer] [](id:18ab00000001,api:0,p:-1,c:6315) connect: controlledByApp=false
[BLASTBufferQueue] [ViewRootImpl[MainActivity]#1] constructor()
[BufferQueueProducer] [ViewRootImpl[MainActivity]#1(BLAST Consumer)1](id:18ab00000001,api:1,p:6315,c:6315) connect: api=1 producerControlledByApp=true
Thread started:  #13
[DOTNET] Background task is running...
[DOTNET] Foreground task is running...
**System.ObjectDisposedException:** 'Cannot access a closed Stream.'

[DOTNET] Background task is running...
```

### PR DESCRIPTION
**Pull request by jstedfast**
### Description of Change

The original issue is that images were being loaded/set on the Image control in a non-UI thread causing an unhandled exception stating, "Only the original thread that created a view hierarchy can touch its view".

Android's StreamImageSourceService.LoadDrawableAsync() incorrectly had a ConfigureAwait(false) on an awaited call to get the image data stream which meant that the subsequent LoadImageFromStream() call would not happen on the original thread.

As added precaution, modified MauiCustomViewTarget.java to post view.setImageDrawable() calls to the main (UI) thread as well.

### Issues Fixed

Fixes #14052
Fixes #15397

### CODE REVIEW

**Comment by Redth** [comment]
@jonathanpeppers @mattleibow I seem to recall some issues with using post on the android side previously, does that sound familiar at all?

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomViewTarget.java [hunk 1]
```diff
@@ -27,7 +27,7 @@ public MauiCustomViewTarget(@NonNull ImageView view, ImageLoaderCallback callbac
 
     @Override
     protected void onResourceCleared(@Nullable Drawable placeholder) {
-		this.view.setImageDrawable(placeholder);
+		post(() -> this.view.setImageDrawable(placeholder));
```
Comment (jonathanpeppers) [inline src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomViewTarget.java:30]: Found the docs on this callback:

https://bumptech.github.io/glide/javadocs/490/com/bumptech/glide/request/target/CustomViewTarget.html

It doesn't say what thread this is on, but it must be the main thread because `view.setImageDrawable` would throw? 

Reviewing some examples on GitHub:

* https://github.com/CzBiX/v2ex-android/blob/f6a79a91b84ae8030930231d965845798c4ce0a8/app/src/main/java/com/czbix/v2ex/parser/AsyncImageGetter.java#L196-L198
* https://github.com/signalapp/Signal-Android/blob/2cef06cd6ef2ed70fdab3fcb525df9909f18aa5a/app/src/main/java/org/thoughtcrime/securesms/util/AvatarUtil.java#L71-L74

I don't think we need this `post()`, did it fix something when you added it?

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomViewTarget.java [hunk 2]
```diff
@@ -46,11 +46,13 @@ public void onResourceReady(@NonNull Drawable resource, @Nullable Transition<? s
             return;
         this.completed = true;
 
-        // set the image
-        this.view.setImageDrawable(resource);
+        post(() -> {
+            // set the image
+            this.view.setImageDrawable(resource);
```
Comment (jonathanpeppers) [inline src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomViewTarget.java:51]: This change to `post()` might be OK, did this fix something?

**Review by jonathanpeppers — COMMENTED** [review]
I think the main thing missing here is some kind of test.

Can we add a test to this file?

https://github.com/dotnet/maui/blob/main/src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomViewTarget.java (hunk 2 above)
Comment (jstedfast) [reply src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomViewTarget.java:51]: Removing the ConfigureAwait(false) from StreamImageSourceService.Android.cs seemed to have worked by itself. The post() changes didn't fix anything on their own (i.e. I tested adding back the ConfigureAwait(false) and ended up with errors again).

**Comment by jstedfast** [comment]
I'll work on adding a test today

**Comment by Redth** [comment]
@jstedfast this looks potentially related: #14128 

Could you maybe validate your changes against that repro too?

**Comment by jstedfast** [comment]
@Redth yea, that definitely looks related. I'll test it to verify.

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomViewTarget.java (hunk 1 above)
Comment (jstedfast) [reply src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomViewTarget.java]: It did not fix anything specific, no. I think that, technically, only the ConfigureAwait(false) removal is needed. The post() calls were suggested changes that might help make MAUI more robust against this type of problem if customers did things on other threads.

**Comment by jstedfast** [comment]
@Redth I have confirmed that issue #14128 is a duplicate and is fixed by this change.

**Comment by jstedfast** [comment]
I've been unable to get the DeviceTests to build or run. Would anyone else be willing to write the test(s) for this?

File: src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomViewTarget.java (hunk 2 above)
Comment (mattleibow) [reply src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomViewTarget.java:51]: Maybe we don't need this anymore then? Is there any fears that there are related issues?

**Review by mattleibow — COMMENTED** [review]
How come the tests are not catching this? Are we missing something in the core device tests that we should be adding this?

**Review by mattleibow — COMMENTED** [review]
How come the tests are not catching this? Are we missing something in the core device tests that we should be adding this?

**Comment by jstedfast** [comment]
Any chance we can get this merged?

/cc @Redth @jonathanpeppers

**Comment by jonathanpeppers** [comment]
Can we add a test? https://github.com/dotnet/maui/pull/14109#pullrequestreview-1351628139

**Comment by jonathanpeppers** [comment]
We should be able to add a test here that loads an image from an `EmbeddedResource` as a `Stream`:

https://github.com/dotnet/maui/blob/main/src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs

Previously, any `Image` using a `Stream` would break? Correct?

**Comment by mattleibow** [comment]
Does the test fail without your changes? Was the issue also related to setting the property from a background thread, or if the stream went to the background thread? Maybe the task should be `Source = ImageSource.FromStream(() => Task.Run(() => stream))`?

I do know we have images in our sample that I am sure load, but we do basic things.

File: src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs [hunk 3]
```diff
@@ -46,5 +47,28 @@ public async Task ImageWithUndefinedSizeAndWithBackgroundSetRenders()
...
 			});
 		}
+
+		[Fact]
+		public async Task ImageSetFromStreamRenders()
+		{
+			SetupBuilder();
+			var layout = new VerticalStackLayout();
+
+			var stream = File.OpenRead("red.png");
```
Comment (jonathanpeppers) [inline src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs:57]: This looks like it would attempt to open `/red.png` on Android and fail. This file from the other test looks like it is an `AndroidResource`.

    System.IO.FileNotFoundException : Could not find file '/red.png'.

This could only work if you added an entry to the `.csproj` as an `EmbeddedResource`, and use `Assembly.GetManifestResourceStream()`. There isn't a way to load loose files on Android, because apps remain compressed on disk.

Comment (jstedfast) [reply src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs]: ah, thanks.

**Comment by jstedfast** [comment]
@mattleibow The customer sample did not set the stream in a background thread - they set it in the main thread.

**Comment by jstedfast** [comment]
Argh, not sure why it's getting a null stream for the embedded image when run on the bots but not locally. Doesn't seem to make sense :(

File: src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs [hunk 4]
```diff
@@ -46,5 +47,28 @@ public async Task ImageWithUndefinedSizeAndWithBackgroundSetRenders()
...
 			});
 		}
+
+		[Fact]
+		public async Task ImageSetFromStreamRenders()
+		{
+			SetupBuilder();
+			var layout = new VerticalStackLayout();
+
+			var stream = GetType().Assembly.GetManifestResourceStream("Microsoft.Maui.DeviceTests.Resources.Images.red-embedded.png");
```
Comment (jonathanpeppers) [inline src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs:57]: Then you can use `GetManifestResourceStream("red-embedded.png")`.

You might want to put `using`, too:

```suggestion
			using var stream = GetType().Assembly.GetManifestResourceStream("red-embedded.png");
```

File: src/Controls/tests/DeviceTests/Controls.DeviceTests.csproj [hunk 5]
```diff
@@ -19,6 +19,9 @@
 
   <ItemGroup>
     <MauiImage Include="Resources\Images\*" />
+    <MauiImage Remove="Resources\Images\red-embedded.png" />
+    <None Remove="Resources\Images\red-embedded.png" />
+    <EmbeddedResource Include="Resources\Images\red-embedded.png" />
```
Comment (jonathanpeppers) [inline src/Controls/tests/DeviceTests/Controls.DeviceTests.csproj:24]: @jstedfast try putting:
```suggestion
    <EmbeddedResource Include="Resources\Images\red-embedded.png" LogicalName="red-embedded.png" />
```

**Comment by jstedfast** [comment]
Still getting failures. It looks like the failures are only on iOS.

Is there something specifically different about iOS that embedded resources would be named differently or somehow not embedded, perhaps?

**Comment by jonathanpeppers** [comment]
@mattleibow do you know?
```
System.ArgumentNullException : ArgumentNull_Generic Arg_ParamName_Name, ctx

Stack trace
   at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle(INativeObject self, String argumentName)
   at CoreAnimation.CALayer.RenderInContext(CGContext ctx)
   at Microsoft.Maui.DeviceTests.AssertionExtensions.ToBitmap(UIView view, IMauiContext mauiContext)
   at Microsoft.Maui.DeviceTests.AssertionExtensions.AssertContainsColor(UIView view, UIColor expectedColor, IMauiContext mauiContext, Nullable`1 tolerance)
   at Microsoft.Maui.DeviceTests.ImageTests.&lt;&gt;c__DisplayClass2_0.&lt;&lt;ImageSetFromStreamRenders&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Maui.Dispatching.DispatcherExtensions.&lt;&gt;c__DisplayClass3_0.&lt;&lt;DispatchAsync&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Maui.Dispatching.DispatcherExtensions.&lt;&gt;c__DisplayClass2_0`1.&lt;&lt;DispatchAsync&gt;b__0&gt;d[[System.Boolean, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Maui.DeviceTests.ImageTests.ImageSetFromStreamRenders()
--- End of stack trace from previous location ---
```
The stream isn't `null` or this stacktrace would be a lot different.

File: src/Core/src/ImageSources/StreamImageSourceService/StreamImageSourceService.Android.cs [hunk 6]
```diff
@@ -21,7 +21,7 @@ public partial class StreamImageSourceService
 				Stream? stream = null;
 				try
 				{
-					stream = await streamImageSource.GetStreamAsync(cancellationToken).ConfigureAwait(false);
+					stream = await streamImageSource.GetStreamAsync(cancellationToken);
```
Comment (PureWeen) [inline src/Core/src/ImageSources/StreamImageSourceService/StreamImageSourceService.Android.cs:24]: Do we still need this?

Comment (jstedfast) [reply src/Core/src/ImageSources/StreamImageSourceService/StreamImageSourceService.Android.cs:24]: Yes. This is the actual fix.

Comment (jstedfast) [reply src/Core/src/ImageSources/StreamImageSourceService/StreamImageSourceService.Android.cs:24]: Nope, the post() fix by itself does not fix this. In fact, this change by itself works even without the post() change.

Comment (jonathanpeppers) [inline src/Core/src/ImageSources/StreamImageSourceService/StreamImageSourceService.Android.cs:24]: So the `ImageSetFromStreamRenders` test above fails unless we have this change?

**Review by jonathanpeppers — APPROVED** [review]
LGTM, assuming the new test verifies the fix.

File: src/Core/src/ImageSources/StreamImageSourceService/StreamImageSourceService.Android.cs (hunk 6 above)
Comment (jstedfast) [reply src/Core/src/ImageSources/StreamImageSourceService/StreamImageSourceService.Android.cs:24]: yes

**Comment by janseris** [comment]
When is this released?

**Comment by PureWeen** [comment]
If we backport this, we should regenerate the android file
