### PR TITLE
[Android] System Fonts fix

### LINKED ISSUE #19556: Android Systemfonts (light/black etc.) not working
### Description

If i set sans-serif-black,  sans-serif-light etc. to the FontFamily property of a label all text looks the same. 
image

The same code in XF:
image

### Steps to Reproduce

Xaml:
```XAML
  <ScrollView>
    <StackLayout Padding="30,0"
                         Spacing="0">
      <!--<Image Source="dotnet_bot.png"
             HeightRequest="185"
             Aspect="AspectFit"
             SemanticProperties.Description="dot net bot in a race car number eight monospace" />-->
      <Label Text="NET Multi-platform App UI monospace"
             FontFamily="monospace"
             SemanticProperties.HeadingLevel="Level1" />
      <Label Text=".NET Multi-platform App UI sans-serif-condensed"
             FontFamily="sans-serif-condensed"
             SemanticProperties.HeadingLevel="Level2"
             SemanticProperties.Description="Welcome to dot net Multi platform App U I sans-serif-condensed" />
      <Label Text=".NET Multi-platform App UI sans-serif-condensed-light"
             FontFamily="sans-serif-condensed-light"
             SemanticProperties.HeadingLevel="Level2"
             SemanticProperties.Description="Welcome to dot net Multi platform App U I sans-serif-condensed-light" />
      <Label Text=".NET Multi-platform App UI serif"
             FontFamily="serif"
             SemanticProperties.HeadingLevel="Level2"
             SemanticProperties.Description="Welcome to dot net Multi platform App U I serif " />
      <Label Text=".NET Multi-platform App UI sans-serif"
             FontFamily="sans-serif"
             SemanticProperties.HeadingLevel="Level2"
             SemanticProperties.Description="Welcome to dot net Multi platform App U I sans-serif" />
      <Label Text=".NET Multi-platform App UI sans-serif-black"
             FontFamily="sans-serif-black"
             SemanticProperties.HeadingLevel="Level2"
             SemanticProperties.Description="Welcome to dot net Multi platform App U I sans-serif-black" />
      <Label Text=".NET Multi-platform App UI sans-serif-light"
             FontFamily="sans-serif-light"
             SemanticProperties.HeadingLevel="Level2"
             SemanticProperties.Description="Welcome to dot net Multi platform App U I sans-serif-light" />
      <Label Text=".NET Multi-platform App UI sans-serif-medium"
             FontFamily="sans-serif-medium"
             SemanticProperties.HeadingLevel="Level2"
             SemanticProperties.Description="Welcome to dot net Multi platform App U I sans-serif-medium" />
      <Button x:Name="CounterBtn"
              Text="Click me"
              FontFamily="sans-serif-condensed"
              SemanticProperties.Hint="Counts the number of times you click"
              Clicked="OnCounterClicked"
              HorizontalOptions="Fill" />
    </StackLayout>
  </ScrollView>
```

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.6-nightly.9889

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 34

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/19556

|Before|After|
|--|--|
|||

### CODE REVIEW

File: src/Controls/tests/UITests/Tests/Issues/Issue19556.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+    [Test]
+	public void SystemFontsShouldRenderCorrectly()
+	{
+		this.IgnoreIfPlatforms(new TestDevice[] { TestDevice.iOS, TestDevice.Mac, TestDevice.Windows });
+
+		_ = App.WaitForElement("label");
+
+		// The test passes if fonts are correctly rendered
+		VerifyScreenshot();
```
Comment (jsuarezruiz) [inline src/Controls/tests/UITests/Tests/Issues/Issue19556.cs:23]: Waiting CI to pass tests and generate the reference snapshot.

**Comment by AlleSchonWeg** [comment]
Hi,
thank you for fixing my issue ;)
But this should work also on API < 28. I know you using a `Typeface.Create` which is only available above 28. In XF it works below 28. So i'm not sure if this is the correct overload-
Thank you

File: src/Core/src/Fonts/FontManager.Android.cs [hunk 2]
```diff
@@ -171,7 +172,28 @@ public FontSize GetFontSize(Font font, float defaultFontSize = 0)
...
+				{
+					{ "-light", FontWeight.Light },
+					{ "-medium", FontWeight.Medium },
+					{ "-black", FontWeight.Black }
+					// Add more styles as needed
+				};
+
+				if (!string.IsNullOrWhiteSpace(fontFamily))
+				{
+					foreach (var fontWeight in fontWeightMap.Keys)
```
Comment (jonathanpeppers) [inline src/Core/src/Fonts/FontManager.Android.cs:186]: Can you iterate over `fontWeightMap` instead? Instead of `.Keys`?

File: src/Core/src/Fonts/FontManager.Android.cs [hunk 3]
```diff
@@ -171,7 +172,28 @@ public FontSize GetFontSize(Font font, float defaultFontSize = 0)
...
+					{
+						if (fontFamily.EndsWith(fontWeight, StringComparison.OrdinalIgnoreCase))
+						{
+							return Typeface.Create(result, (int)fontWeightMap[fontWeight], italic);
```
Comment (jonathanpeppers) [inline src/Core/src/Fonts/FontManager.Android.cs:190]: Then you wouldn't need to do a dictionary lookup here, you could call `.Value` on the key pair.

File: src/Core/src/Fonts/FontManager.Android.cs [hunk 4]
```diff
@@ -171,7 +172,28 @@ public FontSize GetFontSize(Font font, float defaultFontSize = 0)
...
 
 			if (OperatingSystem.IsAndroidVersionAtLeast(28))
+			{
+				var fontWeightMap = new Dictionary<string, FontWeight>
+				{
+					{ "-light", FontWeight.Light },
+					{ "-medium", FontWeight.Medium },
+					{ "-black", FontWeight.Black }
+					// Add more styles as needed
+				};
```
Comment (jonathanpeppers) [inline src/Core/src/Fonts/FontManager.Android.cs:182]: Can we make this dictionary `static readonly`? Then we wouldn't create a new one on each call.

String keyed dictionaries should also use `StringComparer.Ordinal` (or `StringComparer.OrdinalIgnoreCase` if casing doesn't matter).

Comment (kubaflo) [reply src/Core/src/Fonts/FontManager.Android.cs:182]: Good idea! Thanks!

File: src/Core/src/Fonts/FontManager.Android.cs (hunk 2 above)
Comment (kubaflo) [reply src/Core/src/Fonts/FontManager.Android.cs:186]: Sure!

**Comment by kubaflo** [comment]
@jonathanpeppers I've added a commit with your suggested changes. Thanks for the tips!

File: src/Controls/tests/UITests/Tests/Issues/Issue19556.cs (hunk 1 above)
Comment (jonathanpeppers) [reply src/Controls/tests/UITests/Tests/Issues/Issue19556.cs:23]: @jsuarezruiz how do we get the screenshot? this looks ok to merge now otherwise.

**Review by jonathanpeppers — DISMISSED** [review]
LGTM, if the test & screenshot are working. 👍

File: src/Controls/tests/UITests/Tests/Issues/Issue19556.cs (hunk 1 above)
Comment (rmarinho) [reply src/Controls/tests/UITests/Tests/Issues/Issue19556.cs:23]: Right now, you need to go to the UITest run https://dev.azure.com/xamarin/public/_build/results?buildId=110953&view=ms.vss-test-web.build-test-results-tab&runId=2620968&resultId=100163&paneView=debug
And check the failed test . 
Screenshot 2024-03-13 at 16 17 21

Then go to the Attachments and download the image for the test SystemFontsShouldRenderCorrectly
Screenshot 2024-03-13 at 16 18 18

Comment (rmarinho) [reply src/Controls/tests/UITests/Tests/Issues/Issue19556.cs:23]: SystemFontsShouldRenderCorrectly

**Review by rmarinho — APPROVED** [review]
