### PR TITLE
[Android] Fix crash in GraphicsView when using TapGestureRecognizer

### LINKED ISSUE #34296: TapGestureRecognizer on GraphicsView causes a crash on Android devices
### Description

A TapGestureRecognizer attached to a GraphicsView can cause an Android app to crash when the GraphicsView is tapped.  This started to occur in Microsoft.Maui.Controls version 10.0.40 and occurs in 10.0.41 as well (version 10.0.31 worked fine).

It only seems to be an issue on physical Android devices (e.g. Samsung Galaxy A10 with Android 11, Nokia 310 with Android 10) and not on Android emulators.  iOS devices and Windows seem unaffected by the issue.

### Steps to Reproduce

1. Create a new .NET MAUI App.
2. Create a simple **GraphicsView**, e.g.
```csharp
public partial class CircularGraphicsView : IDrawable
{
	public void Draw(ICanvas canvas, RectF rectangle)
	{
		float size = Math.Min(rectangle.Width, rectangle.Height);
		float radius = size / 2;
		PointF centre = new(radius, radius);

		// Draw a filled circle
		canvas.FillColor = Colors.Purple;
		canvas.FillCircle(centre, radius);
	}
}
```
3. Replace the contents of the **MainPage.xaml** with the simple **GraphicsView** and attach a **TapGestureRecognizer**, e.g.
```xml
	<Grid BackgroundColor="White">
		<VerticalStackLayout>
			<GraphicsView Drawable="{Binding CircularGraphicsView}" WidthRequest="100" HeightRequest="100" Margin="0,0,1,0">
				<GraphicsView.GestureRecognizers>
					<TapGestureRecognizer Tapped="CircularGraphicsView_Tapped" NumberOfTapsRequired="1" />
				</GraphicsView.GestureRecognizers>
			</GraphicsView>
		</VerticalStackLayout>
	</Grid>

```
3. Add a TapGestureRecognizer event handler in **MainPage.xaml.cs** (which won't be called because the app crashes when the GraphicsView is tapped).

Expected behaviour: the TapGestureRecognizer event handler should be called when the GraphicsView is tapped.
Actual behaviour: the app crashes.

### Link to public reproduction project repository

https://github.com/Tim-Rasmussen/GraphicsViewTapGestureRecognizer.git

### Version with bug

10.0.40

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

10.0.30

### Affected platforms

Android

### Affected platform versions

We've only been able to test on Android 11 and 10 devices but it may happen on later versions.

### Did you find any workaround?

The workaround is to use the GrahicsView **StartInteraction** event in place of the TapGestureRecognizer but the latter event seems to fire later than the former which makes the workaround unusable in our commercial app which has GraphicsViews within a **CollectionView** (each CollectionView item has an attached TapGestureRecognizer which fires before the GraphicsView StartInteraction event but we need to intercept the GraphicsView being tapped).

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by jpd21122012**
### Description of Change

Fixes a crash on Android when using `TapGestureRecognizer` with `GraphicsView`.

### Root Cause

`PlatformTouchGraphicsView.TouchesMoved` assumed that `_lastMovedViewPoints`
always contained at least one element.

In certain touch event sequences (triggered when a TapGestureRecognizer is attached),
`_lastMovedViewPoints` could be empty while `points.Length == 1`,
leading to an IndexOutOfRangeException.

### Fix

Added a length check before accessing `_lastMovedViewPoints[0]`
to prevent out-of-range access.

### Verified Scenarios

- TapGestureRecognizer no longer causes a crash
- Tap events fire correctly
- Drag interaction remains functional
- Multitouch does not crash

Fixes #34296

### CODE REVIEW

File: src/Core/src/Platform/Android/PlatformTouchGraphicsView.cs [hunk 1]
```diff
@@ -89,7 +89,7 @@ public void TouchesMoved(PointF[] points)
 		{
 			if (!_dragStarted)
 			{
-				if (points.Length == 1)
+				if (points.Length == 1 && _lastMovedViewPoints.Length == 1)
```
Comment (sheiksyedm) [inline src/Core/src/Platform/Android/PlatformTouchGraphicsView.cs]: @jpd21122012  Instead of _lastMovedViewPoints.Length == 1, consider using_lastMovedViewPoints.Length > 0. This is more robust for the multi-touch scenario where a user starts with 2 fingers (TouchesBegan sets _lastMovedViewPoints.Length = 2) and then lifts one finger.

Comment (jpd21122012) [reply src/Core/src/Platform/Android/PlatformTouchGraphicsView.cs]: Good point — updated to use _lastMovedViewPoints.Length > 0 to better handle the multi-touch scenario where a gesture starts with multiple fingers and one is lifted.

**Review by PureWeen — APPROVED** [review]
