### PR TITLE
[Android] Fix Entry issues with Keyboard using IsPassword

### LINKED ISSUE #10407: [Android12-API31] Entry: changing IsPassword false to true, does not show the numbers, when Keyboard attribute is "Numeric"
### Description

I have a functionallity in an App, that allows to change a PIN number. Next to every Entry (OldPIN, NewPIN & ConfirmPIN) there is a show/hide button that toggles IsPassword attribute (false/true) of the corresponding Entry. In the case of an Entry with the Keyboard attribute = Numeric, when the attribute IsPassword changes from true to false, the Entry control stays showing the passwords chars instead of the PIN's numbers.

### Steps to Reproduce

1. Create an Empty MAUI project.
2. Set the content of **MainPage.xaml** whith this xaml:

```
    <ScrollView>
        <VerticalStackLayout Spacing="10" Padding="10" HorizontalOptions="FillAndExpand">
            
            <HorizontalStackLayout Spacing="10">
                <!--Stays as password char after first toogle-->
                <Button Text="Entry1: numeric" Clicked="ToggleEntry1_Clicked"/>
                <Entry x:Name="Entry1" Text="1234" Keyboard="Numeric" />
            </HorizontalStackLayout>
            
            <HorizontalStackLayout Spacing="10">
                <!--OK-->
                <Button Text="Entry2: text" Clicked="ToggleEntry2_Clicked"/>
                <Entry x:Name="Entry2" Text="Abc - + 123" Keyboard="Text" />
            </HorizontalStackLayout>
            
        </VerticalStackLayout>
    </ScrollView>
```

3. Enter this event handlers on the **MainPage.xaml.cs**:

```
private void ToggleEntry1_Clicked(object sender, EventArgs e)
{
    Entry1.IsPassword = !Entry1.IsPassword;
}

private void ToggleEntry2_Clicked(object sender, EventArgs e)
{
    Entry2.IsPassword = !Entry2.IsPassword;
}
```

### Link to public reproduction project repository

https://github.com/leoderja/MauiApp1_EntryIsPassword

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android12 (not tested on MacOS/iOS)

### Did you find any workaround?

No workarounds

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix Entry issues with Keyboard using IsPassword on Android

fix-entry-password-keyboard

image

### Issues Fixed

Fixes #10407

### CODE REVIEW

File: src/Core/src/Platform/Android/EditTextExtensions.cs [hunk 1]
```diff
@@ -280,16 +280,17 @@ internal static void SetInputType(this EditText editText, ITextInput textInput)
...
-			var nativeInputTypeToUpdate = keyboard.ToInputType();
+
+			editText.InputType = keyboard.ToInputType();
 
 			if (keyboard is not CustomKeyboard)
 			{
-				// TODO: IsSpellCheckEnabled handling must be here.
-
-				if ((nativeInputTypeToUpdate & InputTypes.TextFlagNoSuggestions) != InputTypes.TextFlagNoSuggestions)
+				if ((editText.InputType & InputTypes.TextFlagNoSuggestions) != InputTypes.TextFlagNoSuggestions)
```
Comment (mandel-macaque) [inline src/Core/src/Platform/Android/EditTextExtensions.cs:288]: Can we do a HasFlag instead?

File: src/Core/src/Platform/Android/EditTextExtensions.cs [hunk 2]
```diff
@@ -300,15 +301,12 @@ internal static void SetInputType(this EditText editText, ITextInput textInput)
 
 			if (textInput is IEntry entry && entry.IsPassword)
 			{
-				if ((nativeInputTypeToUpdate & InputTypes.ClassText) == InputTypes.ClassText)
-					nativeInputTypeToUpdate |= InputTypes.TextVariationPassword;
-
-				if ((nativeInputTypeToUpdate & InputTypes.ClassNumber) == InputTypes.ClassNumber)
-					nativeInputTypeToUpdate |= InputTypes.NumberVariationPassword;
+				if ((editText.InputType & InputTypes.ClassText) == InputTypes.ClassText)
```
Comment (mandel-macaque) [inline src/Core/src/Platform/Android/EditTextExtensions.cs:304]: Same.

File: src/Core/src/Platform/Android/EditTextExtensions.cs [hunk 3]
```diff
@@ -300,15 +301,12 @@ internal static void SetInputType(this EditText editText, ITextInput textInput)
...
+					editText.InputType |= InputTypes.TextVariationPassword;
+				if ((editText.InputType & InputTypes.ClassNumber) == InputTypes.ClassNumber)
```
Comment (mandel-macaque) [inline src/Core/src/Platform/Android/EditTextExtensions.cs:306]: Same.

**Review by mandel-macaque — CHANGES_REQUESTED** [review]
Lets move to use HasFlag to make the code more readable for the future 'us'

File: src/Core/src/Platform/Android/EditTextExtensions.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Android/EditTextExtensions.cs]: Sure, changed.

File: src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.Android.cs [hunk 4]
```diff
@@ -15,6 +15,46 @@ namespace Microsoft.Maui.DeviceTests
 {
 	public partial class EntryHandlerTests
 	{
+		[Theory(DisplayName = "Validates Keyboard updates correctly using IsPassword")]
+		[InlineData(nameof(Keyboard.Text), false)]
+		[InlineData(nameof(Keyboard.Numeric), true)]
+		public async Task ValidateKeyboardUpdatesCorrectly(string keyboardName, bool expected)
```
Comment (rachelkang) [inline src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.Android.cs:21]: Not sure if my suggestion here is the best, but it would be great to reword the test name to more clearly reflect what the test does

```suggestion
		public async Task ValidateNumericKeyboardUpdatesCorrectlyWithIsPassword(string keyboardName, bool expected)
```

File: src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.Android.cs [hunk 5]
```diff
@@ -15,6 +15,46 @@ namespace Microsoft.Maui.DeviceTests
 {
 	public partial class EntryHandlerTests
 	{
+		[Theory(DisplayName = "Validates Keyboard updates correctly using IsPassword")]
+		[InlineData(nameof(Keyboard.Text), false)]
+		[InlineData(nameof(Keyboard.Numeric), true)]
```
Comment (rachelkang) [inline src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.Android.cs:20]: I'm thinking we can just change this to a Fact if it's only testing the numeric keyboard. OR if you want this test to be more thorough, keep it as a Theory, test ALL keyboards generally, and make sure the expected keyboard is returned for each case so that the expected value is true for every test case.

```suggestion
		[Fact]
```

File: src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.Android.cs [hunk 6]
```diff
@@ -15,6 +15,46 @@ namespace Microsoft.Maui.DeviceTests
...
+			button.Clicked += delegate
+			{
+				entry.IsPassword = !entry.IsPassword;
+				clicked = true;
+			};
+
+			await PerformClick(button); // IsPassword = true
+			Assert.True(clicked);
+
+			await PerformClick(button); // IsPassword = false
```
Comment (rachelkang) [inline src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.Android.cs:53]: Wondering if we actually need the button interaction logic - is it enough maybe to just switch IsPassword to true?

**Review by rachelkang — COMMENTED** [review]
Left a couple nitpick comments on the test, but otherwise LGTM!

**Review by mandel-macaque — APPROVED** [review]

File: src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.Android.cs (hunk 5 above)
Comment (jsuarezruiz) [reply src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.Android.cs:20]: Want to detect that works as expected with a Numeric keyboard but, the result is different with a Text keyboard.

File: src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.Android.cs (hunk 6 above)
Comment (jsuarezruiz) [reply src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.Android.cs:53]: Yeah, you are right. This is just replicating the scenario from the issue but is not 100% necessary.

**Review by rachelkang — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]
