### PR TITLE
[iOS] SwipeGestureRecognizer: Fix swipe direction detection on rotated views

### LINKED ISSUE #15280: Swipe gestures attached to rotated controls are rotated on Android
### Description

If you have a SwipeGestureRecognizer attached to an object with a rotation set to anything other than 0, the gesture registers relative to the object's rotation on Android. For example, you might have to swipe down to trigger a swipe left. The swipe gesture behaves as expected on Windows.

### Steps to Reproduce

Using the below sample, watch as the gesture direction rotates every time the image itself rotates.

XAML
```
<Image
     x:Name="BotImage"
     Source="dotnet_bot.png"
     SemanticProperties.Description="Cute dot net bot waving hi to you!"
     HeightRequest="400"
     HorizontalOptions="Center" >
     <Image.GestureRecognizers>
          <SwipeGestureRecognizer Direction="Up" Swiped="SwipeGestureRecognizer_Swiped" Threshold="20"/>
          <SwipeGestureRecognizer Direction="Down" Swiped="SwipeGestureRecognizer_Swiped" Threshold="20"/>
          <SwipeGestureRecognizer Direction="Left" Swiped="SwipeGestureRecognizer_Swiped" Threshold="20"/>
          <SwipeGestureRecognizer Direction="Right" Swiped="SwipeGestureRecognizer_Swiped" Threshold="20"/>
     </Image.GestureRecognizers>
</Image>

<Label x:Name="MessageBack" Text="Try a swipe" FontSize="32" HorizontalOptions="Center" />
```

C#
```
private void SwipeGestureRecognizer_Swiped(object sender, SwipedEventArgs e)
{
     MessageBack.Text = $"Swiped {e.Direction.ToString().ToUpper()}. Try again.";
     BotImage.Rotation += 90;
}
```

### Link to public reproduction project repository

https://github.com/bat-kin/MauiBug

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by BagavathiPerumal**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Root cause

The issue occurs on iOS because UISwipeGestureRecognizer reports swipe directions relative to the view’s local coordinate space. When a control is rotated, the recognizer’s concept of directions (Left/Right/Up/Down) rotates along with the view. As a result, the reported SwipedEventArgs.Direction does not match the user’s physical swipe direction on the screen. For example, with a 90° clockwise rotation, a physical left swipe may be reported as “Up.”

Related Android PR: https://github.com/dotnet/maui/pull/21547

### Description of Issue Fix

The fix involves implementing rotation-aware swipe gesture direction transformation on iOS to ensure gestures work correctly on rotated views. The solution adds a TransformSwipeDirectionForRotation() method that normalizes rotation angles and applies direction mapping for 90°, 180°, and 270° rotations with a 45° tolerance. This method uses switch expressions to efficiently transform swipe directions so they correspond to screen coordinates rather than view coordinates. The implementation preserves original directions for non-cardinal rotations and maintains backward compatibility with non-rotated views while providing intuitive gesture behavior regardless of view orientation.

Tested the behavior in the following platforms.
 
- [x] Windows (not affected — fix is iOS-only)
- [x] Mac (not affected — fix is iOS-only)
- [x] iOS
- [x] Android (already fixed in https://github.com/dotnet/maui/pull/21547)

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/15280

### Output
| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="270" height="600"  src="https://github.com/user-attachments/assets/0fb2a186-4aad-44f3-9ed7-a2a8f2eae6c2"> | <video width="270" height="600"  src="https://github.com/user-attachments/assets/cc71ef92-7821-4a1b-be3b-d7670e34be68"> |

### CODE REVIEW

File: src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs [hunk 1]
```diff
@@ -36,34 +38,65 @@ public bool OnSwipe(float x, float y)
...
+
+			if (Math.Abs(rotation) < 0.01)
+			{
+				return (correctedX, correctedY);
+			}
+
+			rotation = rotation % 360;
+			if (rotation < 0) rotation += 360;
+
+			var radians = rotation * Math.PI / 180.0;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs]: Should also validate for NaN or Infinity.

File: src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs [hunk 2]
```diff
@@ -36,34 +38,65 @@ public bool OnSwipe(float x, float y)
...
 
 			return result;
 		}
 
+		(float x, float y) TransformSwipeCoordinatesWithRotation(float x, float y, double rotation)
+		{
+			var correctedX = x; 
+			var correctedY = y;  
+
+			if (Math.Abs(rotation) < 0.01)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs]: Can you add a comment here? Or, create a constant with the 0.01 value and give a descriptive name to it.

File: src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs [hunk 3]
```diff
@@ -36,34 +38,65 @@ public bool OnSwipe(float x, float y)
...
+			{
+				return (correctedX, correctedY);
+			}
+
+			rotation = rotation % 360;
+			if (rotation < 0) rotation += 360;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs]: Did the same (similar) on iOS:
`var normalizedRotation = ((rotation % 360) + 360) % 360;`
Have sense to create some reusable extension methods?

File: src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs [hunk 4]
```diff
@@ -36,34 +38,65 @@ public bool OnSwipe(float x, float y)
...
 				result = true;
 			}
 
 			return result;
 		}
 
+		(float x, float y) TransformSwipeCoordinatesWithRotation(float x, float y, double rotation)
+		{
+			var correctedX = x; 
+			var correctedY = y;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs]: Never are modified, cn use directly x and y.

File: src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.iOS.cs [hunk 5]
```diff
@@ -226,6 +226,50 @@ static void ProcessRecognizerHandlerTap(
 
 		}
 
+		static SwipeDirection TransformSwipeDirectionForRotation(SwipeDirection direction, double rotation)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.iOS.cs]: Could include some unit tests to the added transformations methods?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs (hunk 1 above)
Comment (BagavathiPerumal) [reply src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs]: I have added validation checks for both NaN and Infinity to handle edge cases.

File: src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs (hunk 2 above)
Comment (BagavathiPerumal) [reply src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs]: I have introduced a named constant for 0.01 with a descriptive name and added a comment for clarity.

File: src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs (hunk 3 above)
Comment (BagavathiPerumal) [reply src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs]: I have created a reusable extension method for rotation normalization to keep the logic consistent across platforms.

File: src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs (hunk 4 above)
Comment (BagavathiPerumal) [reply src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs]: I have updated the code to use x and y directly since they are not modified.

File: src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.iOS.cs (hunk 5 above)
Comment (BagavathiPerumal) [reply src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.iOS.cs]: @jsuarezruiz, I have added unit tests for the transformation methods to verify their correctness under various scenarios.

File: src/Controls/src/Core/Internals/SwipeGestureExtensions.cs [hunk 6]
```diff
@@ -0,0 +1,110 @@
...
+		const double RotationThreshold = 0.01;
+
+		/// <summary>
+		/// Normalizes a rotation angle to be within the range [0, 360)
+		/// </summary>
+		/// <param name="rotation">The rotation angle in degrees</param>
+		/// <returns>The normalized rotation angle in the range [0, 360)</returns>
+		internal static double NormalizeRotation(this double rotation)
+		{
+			return ((rotation % 360) + 360) % 360;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Internals/SwipeGestureExtensions.cs:17]: Can include validation to  invalid rotation values (NaN/Infinity)?

Comment (jsuarezruiz) [reply src/Controls/src/Core/Internals/SwipeGestureExtensions.cs:17]:
```
if (double.IsNaN(rotation) || double.IsInfinity(rotation))
            return 0.0;
```

File: src/Controls/tests/Core.UnitTests/Gestures/SwipeGestureRecognizerTests.cs [hunk 7]
```diff
@@ -117,5 +117,45 @@ public void SwipedEventDirectionMatchesTotalYTestWithFlags()
...
+
+			Assert.Equal(expected, result);
+		}
+
+		[Theory]
+		[InlineData(SwipeDirection.Up, 180.0, SwipeDirection.Down)]
+		[InlineData(SwipeDirection.Right, 180.0, SwipeDirection.Left)]
+		[InlineData(SwipeDirection.Down, 180.0, SwipeDirection.Up)]
+		[InlineData(SwipeDirection.Left, 180.0, SwipeDirection.Right)]
+		public void TransformSwipeDirectionForRotation_180Degree_ReturnsCorrectDirection(
```
Comment (jsuarezruiz) [inline src/Controls/tests/Core.UnitTests/Gestures/SwipeGestureRecognizerTests.cs:139]: Include edge cases like

```
[InlineData(SwipeDirection.Up, double.NaN, SwipeDirection.Up)]
[InlineData(SwipeDirection.Right, double.PositiveInfinity, SwipeDirection.Right)]
[InlineData(SwipeDirection.Down, double.NegativeInfinity, SwipeDirection.Down)]
```

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Internals/SwipeGestureExtensions.cs (hunk 6 above)
Comment (BagavathiPerumal) [reply src/Controls/src/Core/Internals/SwipeGestureExtensions.cs:17]: @jsuarezruiz, When invalid rotation values like NaN or Infinity are passed to the methods, the NormalizeRotation() method processes these values and returns NaN. However, this doesn't break the functionality because both transformation methods have built-in safety mechanisms.
 
In the TransformSwipeCoordinatesWithRotation() method, the coordinates are validated by the AreCoordinatesValid() method. When the transformed coordinates contain NaN or Infinity values, this validation catches them and returns the original coordinates unchanged.
 
In the TransformSwipeDirectionForRotation() method, when the rotationRounded variable contains NaN or Infinity, the rotationSteps calculation naturally results in zero, which corresponds to "no rotation" in the switch statement.
 
The original direction is returned unchanged, which is exactly the right behavior for invalid rotation inputs. So even though NormalizeRotation() processes NaN or infinity values and returns NaN, the normalized value returning infinity or NaN doesn't affect the actual result. The code works properly for edge cases like NaN and Infinity values for rotation because the existing validation mechanisms ensure safe fallback behavior.

File: src/Controls/tests/Core.UnitTests/Gestures/SwipeGestureRecognizerTests.cs (hunk 7 above)
Comment (BagavathiPerumal) [reply src/Controls/tests/Core.UnitTests/Gestures/SwipeGestureRecognizerTests.cs:139]: I have added the testcases for infinity and NaN value based on your suggestion.

**Comment by BagavathiPerumal** [comment]
> ## 🤖 AI Summary
> 📊 **Expand Full Review**
> **🔍 Pre-Flight — Context & Validation**
> 📝 **Review Session** — **fix-15280-Added testcases for the Infinity and NaN value.** · [`0a3359f`](https://github.com/dotnet/maui/commit/0a3359f172fdabf228ae54240924ecd7190b0977)
> **Issue:** #15280 - Swipe gestures attached to rotated controls are rotated on Android **Platforms Affected:** Android (primary), iOS (also addressed in PR) **Files Changed:** 3 implementation files, 3 test files
> 
> ### Issue Summary
> When a `SwipeGestureRecognizer` is attached to a view with a non-zero `Rotation` property, the swipe direction detection uses the view's local coordinate space (rotated) rather than the screen coordinate space. For example, when a view is rotated 90°, swiping left physically triggers a "Down" swipe event. The bug is marked Android-only in the issue, but the PR also fixes iOS. Windows was not affected.
> 
> ### Key Findings
> * Author is a community contributor (Syncfusion partner)
> * Reviewer `jsuarezruiz` did a thorough review, all feedback was addressed
> * One unresolved thread remains: reviewer asked for explicit NaN/Infinity validation in `NormalizeRotation()` but author explained the existing safety mechanisms handle it implicitly. Reviewer has not explicitly closed the thread.
> * All previous review threads from earlier rounds are marked as "outdated" (PR was updated to address them)
> 
> ### Files Changed
> **Implementation files:**
> 
> * `src/Controls/src/Core/Internals/SwipeGestureExtensions.cs` (+110, new) — shared extension methods for rotation transforms
> * `src/Controls/src/Core/Platform/Android/SwipeGestureHandler.cs` (+16/-4) — Android swipe coordinate transformation
> * `src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.iOS.cs` (+11/-1) — iOS swipe direction transformation
> 
> **Test files:**
> 
> * `src/Controls/tests/Core.UnitTests/Gestures/SwipeGestureRecognizerTests.cs` (+65) — unit tests for transformation methods
> * `src/Controls/tests/TestCases.HostApp/Issues/Issue15280.cs` (+70, new) — UI test host app page
> * `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue15280.cs` (+27, new) — UI test
> 
> ### Reviewer Feedback Summary
> Reviewer	Comment	Status
> jsuarezruiz	NaN/Infinity validation for coordinates	✅ Addressed (added `AreCoordinatesValid`)
> jsuarezruiz	Named constant for 0.01 threshold	✅ Addressed (`RotationThreshold` constant)
> jsuarezruiz	Create reusable extension methods (rotation normalization)	✅ Addressed (`SwipeGestureExtensions.cs`)
> jsuarezruiz	Use x and y directly (no unused variables)	✅ Addressed
> jsuarezruiz	Add unit tests for transformation methods	✅ Addressed
> jsuarezruiz	Edge case tests for NaN/Infinity rotation in unit tests	✅ Addressed
> jsuarezruiz	NaN/Infinity validation in `NormalizeRotation()` itself	⚠️ Open thread - author argues existing safety mechanisms handle it implicitly
> ### Edge Cases from Discussion
> * [ ]  NaN/Infinity rotation values → Author claims existing validation handles this; reviewer not fully satisfied
> * [ ]  Rotations not at cardinal angles (not 90°/180°/270°) → TransformSwipeDirectionForRotation returns original direction for non-cardinal rotations (within 45° tolerance)
> 
> ### Test Type
> Both **Unit Tests** and **UI Tests** are included.
> 
> ### Fix Candidates
> #	Source	Approach	Test Result	Files Changed	Notes
> PR	PR #30878	Add `SwipeGestureExtensions` with rotation matrix transform (Android) and direction mapping (iOS). Apply transform before swipe detection.	⏳ PENDING (Gate)	6 files (+299/-5)	Original PR
> **🚦 Gate — Test Verification**
> 📝 **Review Session** — **fix-15280-Added testcases for the Infinity and NaN value.** · [`0a3359f`](https://github.com/dotnet/maui/commit/0a3359f172fdabf228ae54240924ecd7190b0977)
> **Result:** ❌ FAILED **Platform:** android **Mode:** Full Verification
> 
> * Tests FAIL without fix ❌ (tests PASSED — don't detect the bug)
> * Tests PASS with fix ❌ (tests FAILED — fix introduces a regression)
> 
> ### Test Run Details
> **Run 1 (WITHOUT fix):** Build succeeded. Tests PASSED.
> 
> * `SwipeLeftToRight` → "Swiped: RIGHT" ✓
> * `SwipeRightToLeft` (after 90° rotation) → gets "Swiped: LEFT" ✓
> * **Problem:** Tests should FAIL here because the bug should be present
> 
> **Run 2 (WITH fix):** Build succeeded. Tests FAILED.
> 
> * `SwipeLeftToRight` → "Swiped: RIGHT" ✓
> * `SwipeRightToLeft` (after 90° rotation) → got "Swiped: UP" ✗ (expected "Swiped: LEFT")
> * **Problem:** The fix makes things WORSE
> 
> ### Root Cause Analysis
> Investigation of the Android gesture code reveals a fundamental flaw in the PR's fix:
> 
> **`InnerGestureListener.StartScrolling()` passes screen-space coordinates to `OnSwipe`:**
> 
> ```cs
> float totalX = e2.RawX - _lastX;   // RawX = screen absolute X
> float totalY = e2.RawY - _lastY;   // RawY = screen absolute Y
> return _scrollDelegate(totalX, totalY, e2.PointerCount) || _swipeDelegate(totalX, totalY);
> ```
> 
> `RawX`/`RawY` are screen-absolute coordinates (not view-local). The delta is already in screen space. This means **no rotation transformation is needed** — the gesture detection works correctly without any fix.
> 
> **The PR's fix incorrectly applies a rotation matrix** to values that are already in screen coordinates, causing a correct LEFT swipe to be transformed into UP:
> 
> * Input: `totalX = -488` (right-to-left), `totalY ≈ 0`, rotation = 90°
> * After fix: `transformedX = -488 * cos(90°) - 0 * sin(90°) = 0`, `transformedY = -488 * sin(90°) = -488`
> * Result: detected as UP instead of LEFT
> 
> ### Conclusion
> The Gate has **FAILED**:
> 
> 1. The fix is fundamentally incorrect — it transforms already-correct screen-space coordinates
> 2. The fix introduces a **regression**: swipe detection on rotated views was working correctly before; the fix breaks it
> 3. The PR's premise (that Android reports gesture deltas in view-local coordinates) appears to be incorrect for this code path since `RawX`/`RawY` are screen-relative
> 
> **Fix Candidates Update:**
> 
> #	Source	Approach	Test Result	Files Changed	Notes
> PR	PR #30878	Apply rotation matrix transform to `RawX`/`RawY` deltas before swipe detection	❌ FAIL (Gate)	6 files (+299/-5)	Fix is wrong: deltas already in screen space
> **🔧 Fix — Analysis & Comparison**
> 📝 **Review Session** — **fix-15280-Added testcases for the Infinity and NaN value.** · [`0a3359f`](https://github.com/dotnet/maui/commit/0a3359f172fdabf228ae54240924ecd7190b0977)
> **Skipped:** Gate FAILED — try-fix phase is only run when Gate passes.
> 
> The Gate phase confirmed that:
> 
> 1. Tests PASS without the PR's fix (the PR's fix is not needed to make tests pass)
> 2. Tests FAIL with the PR's fix (the fix introduces a regression)
> 
> Since the Gate did not pass, no independent fix exploration was performed.
> 
> ### Fix Candidates
> #	Source	Approach	Test Result	Files Changed	Notes
> PR	PR #30878	Rotation matrix transform on `RawX`/`RawY` deltas	❌ FAIL (Gate)	6 files	Fix incorrect: deltas already in screen space
> **Exhausted:** N/A (skipped — Gate failed) **Selected Fix:** None — PR's fix fails tests and introduces regression
> 
> **📋 Report — Final Recommendation**
> 📝 **Review Session** — **fix-15280-Added testcases for the Infinity and NaN value.** · [`0a3359f`](https://github.com/dotnet/maui/commit/0a3359f172fdabf228ae54240924ecd7190b0977)
> ## ⚠️ Final Recommendation: REQUEST CHANGES
> ### Summary
> PR #30878 attempts to fix issue #15280 (swipe gestures on rotated controls behaving incorrectly on Android). The PR adds a `SwipeGestureExtensions` class with rotation matrix transformation methods and applies them in both Android's `SwipeGestureHandler` and iOS's `GesturePlatformManager`. The Gate phase revealed that the fix is **fundamentally incorrect** and actually introduces a regression.
> 
> ### Root Cause (Issue)
> The original issue reports that when a view is rotated, swipe gesture direction detection becomes incorrect on Android. The reporter claims a physical left swipe on a 90°-rotated view triggers an "Up" swipe event.
> 
> ### Why the PR's Fix is Wrong
> The PR's fix is based on an incorrect assumption: it assumes Android's gesture system reports deltas in **view-local coordinates** (rotated). However, investigation of the actual code path shows:
> 
> **In `InnerGestureListener.StartScrolling()`:**
> 
> ```cs
> float totalX = e2.RawX - _lastX;   // e2.RawX = screen-absolute X
> float totalY = e2.RawY - _lastY;   // e2.RawY = screen-absolute Y
> _swipeDelegate(totalX, totalY);     // Passes to OnSwipe()
> ```
> 
> `RawX`/`RawY` are **screen-absolute coordinates** that are NOT affected by view rotation. The deltas are already in screen space. No transformation is needed.
> 
> The PR applies a rotation matrix to these screen-space values, which corrupts them:
> 
> * A physical right-to-left swipe (`totalX = -488, totalY ≈ 0`) on a view rotated 90°
> * After transformation: `transformedX ≈ 0, transformedY = -488` → detected as **UP** instead of LEFT
> * **This is the regression confirmed by the test failure**
> 
> ### Gate Results
> Check	Expected	Actual
> Tests FAIL without fix	✅	❌ PASS (tests work fine without fix)
> Tests PASS with fix	✅	❌ FAIL (fix introduces regression)
> ### Issues with the PR
> 1. **Incorrect fix**: The rotation transformation is applied to values that are already in screen-space coordinates, introducing a regression
> 2. **Test design**: The UI test relies on chaining swipes where the first swipe triggers rotation — this is fragile and hard to reason about; consider using a pre-rotated view instead
> 3. **Unresolved reviewer thread**: `jsuarezruiz` asked for explicit NaN/Infinity validation in `NormalizeRotation()` — author's argument that existing mechanisms handle it is reasonable, but the thread is unresolved
> 4. **Missing newline at end of files**: Several new files are missing a trailing newline (`\n`)
> 
> ### Recommendations
> 1. **Investigate the actual root cause**: Since `RawX`/`RawY` are screen-relative, the swipe detection should already work correctly on rotated views. The author should verify whether the original bug actually exists in current code or whether it was fixed in a different way
> 2. **If the bug is real**: Identify the actual code path where view-local coordinates are used (it may not be in `InnerGestureListener.StartScrolling()`) and fix only that
> 3. **Fix the test**: The test should start with a pre-rotated view (set `Rotation = 90` in constructor) rather than relying on rotation as a side effect of the first swipe
> 4. **Revise the transformation direction**: If rotation transforms are needed (for a different code path), verify the correct direction using unit tests against actual device behavior
> 
> ### Code Quality Notes
> * The `SwipeGestureExtensions` class is well-structured with proper XML documentation, named constants, and reusable extension methods — good pattern for a fix if the underlying approach were correct
> * Unit tests for the transformation methods are comprehensive (including NaN/Infinity edge cases)
> * The iOS fix uses a different approach (direction mapping) from the Android fix (coordinate transformation) — conceptually cleaner but also needs verification
> 
> 📋 **Expand PR Finalization Review**

I’ve updated the changes based on the review comments. Specifically:

- Removed all Android rotation-transform logic from SwipeGestureHandler.cs, since swipe deltas already use screen-space (RawX/RawY) coordinates and the transformation introduced regressions. This behavior is already correctly handled by below mentioned PR, which computes swipe deltas in screen space, making any additional rotation adjustment unnecessary.

  Related Android PR: https://github.com/dotnet/maui/pull/21547

- Updated SwipeGestureExtensions.cs to retain only the shared iOS-related helpers by keeping NormalizeRotation() and TransformSwipeDirectionForRotation(), while removing Android-only coordinate-transform utilities.
- Updated unit tests in SwipeGestureRecognizerTests.cs by removing Android coordinate-transform test cases and keeping only the direction-mapping tests relevant to the iOS fix.

**Comment by BagavathiPerumal** [comment]
> ## 📋 PR Finalization Review
> Title: ✅ Good
> 
> **Current:** `[iOS] SwipeGestureRecognizer: Fix swipe direction detection on rotated views`
> 
> Description: ✅ Good
> 
> Description needs updates. See details below.
> 
> ### ✨ Suggested PR Description
> > [!NOTE]
> > Are you waiting for the changes in this PR to be merged?
> > It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!
> 
> ### Root Cause
> On iOS, `UISwipeGestureRecognizer` reports swipe directions relative to the view's **local coordinate space**. When a control is rotated (e.g., 90° clockwise), the recognizer's sense of Up/Down/Left/Right rotates with the view. This means a physical left swipe on a 90°-rotated view is reported as "Up" — not "Left" — causing `SwipedEventArgs.Direction` to not match the user's actual swipe direction on screen.
> 
> The same issue was previously fixed on Android in PR #21547. This PR applies the equivalent fix to iOS.
> 
> ### Description of Change
> Adds rotation-aware swipe direction transformation for iOS:
> 
> **New file: `SwipeGestureExtensions.cs`** (`src/Controls/src/Core/Internals/`)
> 
> * `NormalizeRotation(double)` — normalizes any rotation angle to `[0, 360)`
> * `TransformSwipeDirectionForRotation(SwipeDirection, double)` — maps the recognizer-reported direction to the correct screen-space direction for cardinal rotations (0°, 90°, 180°, 270°) with a 45° tolerance. Non-cardinal rotations pass through unchanged.
> 
> **Modified: `GesturePlatformManager.iOS.cs`**
> 
> * When `view.Rotation != 0`, the reported swipe direction is passed through `TransformSwipeDirectionForRotation` before raising `SendSwiped`.
> 
> **New unit tests: `SwipeGestureRecognizerTests.cs`**
> 
> * 90° clockwise mapping (Up→Right, Right→Down, Down→Left, Left→Up)
> * 180° mapping (Up→Down, Right→Left, etc.)
> * Invalid rotation values (NaN, ±Infinity) return original direction
> 
> **New UI test: `Issue15280.cs`**
> 
> * HostApp page and Appium test that validates correct swipe direction reporting after view rotation
> 
> ### Issues Fixed
> Related to #15280 (originally reported for Android; this PR extends the fix to iOS)
> 
> ### Platforms Tested
> * [ ]  Windows (not affected — fix is iOS-only)
> * [ ]  Mac (not affected — fix is iOS-only)
> * [x]  iOS ✅
> * [ ]  Android (already fixed in [Android pan fixes #21547](https://github.com/dotnet/maui/pull/21547))
> 
> Code Review: ⚠️ Issues Found

I’ve updated the changes based on the review comments. Specifically:
 

- Added an explicit double.IsFinite(rotation) guard in SwipeGestureExtensions.TransformSwipeDirectionForRotation(...) so NaN / Infinity return the original direction.
- Simplified GesturePlatformManager.iOS.cs to always route through TransformSwipeDirectionForRotation(...) instead of branching on view. Rotation != 0.
- Added missing 270° unit test coverage in SwipeGestureRecognizerTests.cs.
- Fixed the missing trailing newline in SwipeGestureRecognizerTests.cs.
- Updated Issue15280 metadata and text in both HostApp and UITest files to reflect the iOS-specific scope of this PR.

**Comment by kubaflo** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong> — <a href="https://github.com/dotnet/maui/commit/078e9848226548b89ee48b8c2560e9822fc45869"><code>078e984</code></a> · <strong>fix-15280-Changes Updated.</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

**Issue:** #15280 - Swipe gestures attached to rotated controls are rotated on Android (and iOS)
**PR:** #30878 - [iOS] SwipeGestureRecognizer: Fix swipe direction detection on rotated views
**Author:** BagavathiPerumal (community, Syncfusion partner)
**Platforms Affected:** iOS (primary for this PR); Android already fixed in PR #21547
**Files Changed:** 2 implementation files, 3 test files

### Key Findings
- **Root Cause:** UISwipeGestureRecognizer on iOS reports swipe directions relative to the view's local coordinate space. When a view is rotated, direction transforms rotate with it, so a physical left swipe on a 90° clockwise rotated view is reported as "Up".
- **Fix Approach:** New `SwipeGestureExtensions.TransformSwipeDirectionForRotation()` method that maps detected direction → screen direction using the view's `Rotation` property. Rounds to nearest 90° increment (±45° tolerance). New `NormalizeRotation()` extension method for [0,360) normalization.
- **Integration point:** `GesturePlatformManager.iOS.cs` calls transform before `SendSwiped()`.
- **Related Android fix:** PR #21547 already merged, same concept applied to iOS here.
- **Prior Agent Review Found:** Yes — a prior agent review was posted by the PR author on 2026-02-25 with labels `s/agent-reviewed`, `s/agent-approved`, `s/agent-gate-failed`, `s/agent-suggestions-implemented`, `s/agent-fix-pr-picked`.
  - Gate had previously failed (label: `s/agent-gate-failed`).
- **Reviewer Feedback (jsuarezruiz) — all addressed:**
  1. NaN/Infinity validation in `NormalizeRotation()` → Added `double.IsFinite()` check in `TransformSwipeDirectionForRotation()`
  2. Named constant for `0.01` (Android file) → Addressed
  3. Create reusable extension methods → Done via `SwipeGestureExtensions.cs`
  4. Use `x`/`y` directly in Android → Addressed
  5. Unit tests for transformation methods → Added in `SwipeGestureRecognizerTests.cs`
  6. Edge case tests (NaN/Infinity) → Added
- **Open inline comment:** `jsuarezruiz` asked for explicit NaN/Infinity handling in `NormalizeRotation()` — author responded that `TransformSwipeDirectionForRotation()` already checks `double.IsFinite(rotation)` before calling `NormalizeRotation()`, so the guard exists at the call site.
- **UI Test:** `Issue15280.cs` tests swipe left and right on a non-rotated image at page load (image starts at 0° rotation). The test does NOT test the actual rotated behavior scenario.
- **Unit Tests:** Cover 90°, 180°, 270° rotations for all 4 directions, plus NaN/Infinity edge cases.
- **Missing test coverage:** The `RotationX` and `RotationY` properties are not handled (only `Rotation` / Z-axis). The UI test does NOT test the core bug scenario (swiping on a rotated view).

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #30878 | Add `TransformSwipeDirectionForRotation()` in `SwipeGestureExtensions.cs`; call from `GesturePlatformManager.iOS.cs` | ⏳ PENDING (Gate) | `SwipeGestureExtensions.cs` (new), `GesturePlatformManager.iOS.cs` (+4 lines) | Original PR |

Result: ✅ COMPLETE

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

### Gate Result: ✅ PASSED

**Platform:** iOS (iPhone 11 Pro simulator)
**Mode:** Full Verification

- Tests FAIL without fix: ✅ (confirmed — bug detected)
- Tests PASS with fix: ✅ (confirmed — fix works)

**Fix files verified:**
- `src/Controls/src/Core/Internals/SwipeGestureExtensions.cs` (new file)
- `src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.iOS.cs`

**Notes:** Base branch merge base `f6314b55`. SwipeGestureExtensions.cs is a new file — reverting it removed the transform, confirming it is required for the fix. No errors during verification.

Result: ✅ COMPLETE

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #30878 | New  + call in  |  PASSED (Gate) | 2 files | Original  platform-specific transform |PR 
| 1 | try-fix (claude-opus-4.6-1m) | Rotation compensation inside  (shared code) |  PASS | 1 file | Moves transform to shared layer; eliminates iOS-specific code |
| 2 | try-fix (claude-sonnet-4.6) | Replace UISwipeGestureRecognizer with UIPanGestureRecognizer +  (window-space velocity) |  PASS | 1 file | Eliminates bug at  no rotation math needed |source 
| 3 | try-fix (gpt-5.3-codex) | Pre-rotate  at registration time based on views rotation |  PASS | 1 file | Inverse transform at recognizer creation; callback sends original MAUI direction unchanged |
| 4 | try-fix (gemini-3-pro-preview) | Use native  (CATransform3D) of the ContainerView to get actual rotation angle via  |  PASS | 1 file | Ground-truth native transform; handles accumulated transforms |
| 5 | try-fix (claude-sonnet-4.6) | Attach UISwipeGestureRecognizer to superview (unrotated ancestor) + screen-space touch bounds check PASS | 1 file | Architectural fix; no rotation math; complex (deferred attach, dictionary tracking) | | 

### Cross-Pollination
| Model | Round | New Ideas? | Details |
|-------|-------|------------|---------|
| claude-opus-4.6-1m | 2 | No | Solution space covered by 4 categories |
 ran as Attempt 5) |
 merged into Attempt 5) |
 merged into Attempt 5) |
| claude-opus-4.6-1m | 3 | No | All 5 categories exhausted |
| claude-sonnet-4.6 | 3 | Yes | UIPan + ConvertPoint direction-vector transform (variant of Attempt 2; round 3 max reached, not run) |

**Exhausted:** Yes (Round 3 max reached)

**Selected Fix:** PR #30878

tolerance, guards NaN/Infinity, and preserves backward compatibility. Alternatives are either more complex (attempts 4, 5), change gesture recognizer type (attempt 2), affect all platforms unnecessarily (attempt 1), or don't handle dynamic rotation (attempt 3).**Reason:** The PR's fix is the most minimal and well-scoped: a new extension class + 4-line change in the iOS platform manager. It fixes only the iOS codepath (correctly scoped to the affected platform), handles 0/90/180/rotations with 270

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

## ✅ Final Recommendation: APPROVE

### Phase Status
| Phase | Status | Notes |
|---|---|---|
| Pre-Flight | ✅ COMPLETE | Issue #15280, iOS swipe direction bug on rotated views |
| Gate | ✅ PASSED | iOS (iPhone 11 Pro simulator) — tests FAIL without fix, PASS with fix |
| Try-Fix | ✅ COMPLETE | 5 attempts, all 5 passing; 3 cross-pollination rounds |
| Report | ✅ COMPLETE | |

### Summary

PR #30878 fixes a real, verified iOS bug where `UISwipeGestureRecognizer` reports directions in the view's local coordinate space. When a MAUI view has `Rotation` set (e.g., 90° clockwise), a physical left swipe is reported as "Up". The PR adds rotation-aware direction compensation that maps the detected direction back to screen coordinates before firing `SwipedEventArgs`.

The Gate confirmed the fix works empirically: tests **fail without** the fix and **pass with** it. Five independent alternative approaches were explored by 4 AI models — all passed — confirming the PR's fix is correct and that multiple valid implementations exist. The PR's approach is the **most appropriate choice** among all candidates.

### Root Cause

`UISwipeGestureRecognizer` is attached to the view being swiped, and UIKit reports its `Direction` in that view's **local coordinate space**. When the view has a `Rotation` applied (via MAUI's `View.Rotation` property which maps to `UIView.Transform`), UIKit's coordinate system rotates along with the view. The result: a user swipes left physically, but UIKit reports the gesture as "Up" (for a 90° CW rotated view). Android had the same bug and was fixed in PR #21547.

### Fix Quality

**Strengths:**
- ✅ **Minimal and focused**: Only 2 files changed — a new 72-line helper class and 4 lines in the iOS platform manager
- ✅ **Well-scoped**: Fix is iOS-only in platform-specific code; doesn't affect Android/Windows/MacCatalyst
- ✅ **Edge case handling**: Guards against `double.IsFinite()` (NaN/Infinity rotation values)
- ✅ **Tolerance-based**: Rounds to nearest 90° with ±45° tolerance — reasonable for real-world rotations
- ✅ **Backward compatible**: 0° rotation fast-paths with no transformation
- ✅ **Reviewer feedback addressed**: All prior reviewer comments (NaN/Infinity, named constants, reusable extension, unit tests) implemented
- ✅ **Unit tests**: 16 new unit tests covering all rotation angles and edge cases
- ✅ **UI test**: `Issue15280.cs` verifies end-to-end behavior on device

**Limitations (acceptable):**
- ⚠️ **Only handles Z-axis rotation**: `RotationX`/`RotationY` properties are not handled — this is acceptable since the `Rotation` property is the 2D in-plane rotation that matches the UISwipeGestureRecognizer behavior
- ⚠️ **Reads MAUI property, not native transform**: Uses `view.Rotation` rather than `Layer.Transform` — adequate since `View.Rotation` directly maps to `UIView.Transform` for simple rotations
- ⚠️ **UI test doesn't test rotated scenario directly**: The UI test only tests a non-rotated image's swipe; however, the unit tests cover the rotation math, and the Gate verified the full scenario

**Alternative approaches explored (all passed):**
| # | Approach | Why PR's fix is preferred |
|---|----------|--------------------------|
| 1 | Fix in shared `SendSwiped()` | Would apply transform on all platforms unnecessarily; Android has its own fix |
| 2 | UIPanGestureRecognizer + VelocityInView(null) | Changes gesture recognizer type — potential behavioral differences (threshold, timing, multi-touch) |
| 3 | Pre-rotate direction at registration | Doesn't handle dynamic rotation changes after registration |
| 4 | CATransform3D angle extraction | More complex, reads deeper UIKit internals unnecessarily |
| 5 | Attach to superview | Architecturally clean but significantly more complex; harder to maintain |

### Selected Fix: PR #30878 ✅

The PR's fix is the most appropriate: minimal, well-scoped, handles the real use cases, with proper edge case guards and comprehensive tests. All reviewer feedback has been addressed. **Recommend APPROVE.**

</details>

---

</details>



<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

# PR #30878 Finalization Review

**PR:** [#30878 - [iOS] SwipeGestureRecognizer: Fix swipe direction detection on rotated views](https://github.com/dotnet/maui/pull/30878)
**Author:** @BagavathiPerumal
**Fixes:** [#15280](https://github.com/dotnet/maui/issues/15280)

---

## Phase 1: Title & Description

### ✅ Title: Good — Keep As-Is

**Current:** `[iOS] SwipeGestureRecognizer: Fix swipe direction detection on rotated views`

This title accurately describes the platform scope (iOS), the component (SwipeGestureRecognizer), and the behavior fixed (swipe direction detection on rotated views). No change needed.

---

### ✅ Description: Good Quality — Minor Additions Suggested

**Quality assessment:**
| Dimension | Status | Notes |
|-----------|--------|-------|
| NOTE block | ✅ Present | Correctly placed at top |
| Root cause | ✅ Present | Well-explained (UISwipeGestureRecognizer uses local coordinate space) |
| Fix description | ✅ Present | Describes `TransformSwipeDirectionForRotation()` and the 45° tolerance |
| Issues Fixed | ✅ Present | `Fixes #15280` |
| Platform scope | ✅ Present | Clearly notes iOS-only fix with references to related Android PR #21547 |
| Accuracy | ✅ Matches diff | Description aligns with actual implementation |
| Output screenshots | ❌ Missing | Output table exists but images are empty (not uploaded) |

**Assessment:** The description is technically accurate and well-structured. The root cause and fix sections are informative. The only issue is the "Output" table at the bottom has no screenshots (empty image references).

**Recommended action:** Remove the empty Output table or add actual before/after screenshots. Everything else should be preserved.

---

## Phase 2: Code Review

### 🟡 Suggestions

---

**1. UI test does not test the rotation scenario (the actual bug)**

- **File:** `src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue15280.cs`
- **Problem:** The test performs `SwipeLeftToRight` and `SwipeRightToLeft` on the image while it is at 0° rotation. The bug being fixed involves swipe direction correctness *after* the view is rotated. Although each swipe in the handler increments `_botImage.Rotation += 90`, the test verifies swipe results at 0° and 90° respectively — but doesn't assert that the *rotated* view correctly maps physical swipe directions.

  Specifically:
  - First `SwipeLeftToRight` → image at 0°, expects "RIGHT" ✅ (trivially correct even without the fix)
  - First `SwipeRightToLeft` → image is now at 90° (rotated after first swipe), expects "LEFT" — this is where the fix matters, but only one rotation step is tested

  A more complete test would cover swipe behavior at multiple rotation angles (90°, 180°, 270°) with assertions for each.

- **Recommendation:** Consider expanding the test to perform additional swipes and verify the reported direction is consistently the physical screen direction, not the rotated view's local direction. This would serve as a true regression test for the bug.

---

**2. Unnecessary `partial` modifier on HostApp page**

- **File:** `src/Controls/tests/TestCases.HostApp/Issues/Issue15280.cs`
- **Problem:** The class is declared `public partial class Issue15280` but there is no associated XAML file (the page is built entirely in C#). The `partial` keyword has no effect here.
- **Recommendation:** Remove `partial` → `public class Issue15280 : ContentPage`

---

### ✅ Looks Good

- **Correct direction mapping logic:** All rotation cases (90°, 180°, 270°) apply the correct coordinate transformation. Verified:
  - 90° CW: Up→Right, Right→Down, Down→Left, Left→Up ✅
  - 180°: Up→Down, Right→Left, Down→Up, Left→Right ✅
  - 270° CW: Up→Left, Right→Up, Down→Right, Left→Down ✅

- **Edge case handling:** Non-finite rotation values (`NaN`, `±Infinity`) are guarded upfront and return the original direction. Non-cardinal angles (outside 45° tolerance of a cardinal) also pass through unmodified. Both behaviors are correct and tested.

- **Correct 360°/0° boundary:** When rotation ≈ 360° (e.g., 355°), `rotationRounded` resolves to 360 and `rotationSteps = (int)(360/90) % 4 = 0`, so no transformation is applied — correctly treating 360° as 0°.

- **Clean integration in platform manager:** `GesturePlatformManager.iOS.cs` change is minimal — one extra line calling the transform method before `SendSwiped`. No behavioral changes for non-rotated views.

- **Good unit test coverage:** All four directions are tested for 90°, 180°, and 270° rotations, plus the invalid-input cases. This thoroughly validates `TransformSwipeDirectionForRotation()`.

- **Shared utility class is appropriately placed:** `SwipeGestureExtensions` lives in `Core/Internals/` making it accessible to unit tests without platform-specific infrastructure. Its logic is purely mathematical and has no iOS dependency.

- **Backward compatibility:** Non-rotated views (0°) take the `0 => direction` path — identical to the pre-fix behavior.

---

## Summary

| Category | Status |
|----------|--------|
| Title | ✅ Keep as-is |
| Description | ✅ Good — remove empty Output image table |
| Code correctness | ✅ Logic is correct |
| Unit test coverage | ✅ Comprehensive |
| UI test coverage | 🟡 Only tests 0° and one rotation step; does not fully exercise the bug scenario |
| Minor style | 🟡 `partial` keyword unnecessary on HostApp page |

**Overall verdict:** The core fix is correct and well-designed. The two suggestions above are non-blocking but improve test quality and code clarity. The PR is in good shape for merge subject to reviewer discretion on the test coverage depth.

</details>

**Review by kubaflo — APPROVED** [review]
