### PR TITLE
[Windows] Fix setting flyout width (#19068)

### LINKED ISSUE #19068: Setting Shell.FlyoutWidth in code-behind on Windows throws ArgumentOutOfRangeException
### Description

Attempting to set the FlyoutWidth in C# on Windows throws:

```System.ArgumentOutOfRangeException: 'Non-negative number required. Arg_ParamName_Name'```

### Steps to Reproduce

Add the following to a button click event:
```
Shell.Current.FlyoutWidth = 260;
```

Actual: throws ArgumentOutOfRangeException
Expected: FlyoutWidth is adjusted to the specified value

### Link to public reproduction project repository

https://github.com/molesmoke/MauiTestApp/tree/flyoutwidth

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

Setting FlyoutWidth in xaml first appears to avoid the exception

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by molesmoke**
PaneContentGrid width/height will be zero if the flyout has not yet been shown

### Description of Change

Ensures a valid size is calculated for the PaneContentGrid if the flyout has not been shown

### Issues Fixed

Fixes #19068

### CODE REVIEW

**Comment by mattleibow** [comment]
Are you able to add some device tests?

**Comment by jeremy-visionaid** [comment]
> Are you able to add some device tests?

@mattleibow Basically, no. Although I was able to get the Controls.DeviceTests project to build by removing the non-Windows and profiling projects from the solution filter, I can't for the life of me get the unit tests to run. 

I was able to verify for myself that it fixed the crash by altering Maui.Controls.Sample, but it doesn't look to me like the following puts the project in a usable state to run the unit tests:

`dotnet cake --target=VS --workloads=global --windows`

Is there perhaps some documentation on how to run the tests that I'm missing?

The "Tests" output window is plastered with errors (17.9.0 Preview 1.1), and I wasn't able to get it to run from the command line either with dotnet test.

```
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectDataImpl.<GetRemoteMachineAddressAsync>d__36.MoveNext()
```

```
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo) in /_/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:line 406
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyOperationManager.cs:line 223
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyDiscoveryManager.cs:line 149
System.InvalidOperationException: The provided manager was not found in any slot.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ParallelOperationManager`3.ClearCompletedSlot(TManager completedManager)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ParallelOperationManager`3.RunNextWork(TManager completedManager) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/Parallel/ParallelOperationManager.cs:line 265
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.Parallel.ParallelProxyDiscoveryManager.HandlePartialDiscoveryComplete(IProxyDiscoveryManager proxyDiscoveryManager, Int64 totalTests, IEnumerable`1 lastChunk, Boolean isAborted) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/Parallel/ParallelProxyDiscoveryManager.cs:line 200
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.Parallel.ParallelDiscoveryEventsHandler.HandleDiscoveryComplete(DiscoveryCompleteEventArgs discoveryCompleteEventArgs, IEnumerable`1 lastChunk) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/Parallel/ParallelDiscoveryEventsHandler.cs:line 75
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyDiscoveryManager.cs:line 156
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyDiscoveryManager.cs:line 177
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The provided manager was not found in any slot.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ParallelOperationManager`3.ClearCompletedSlot(TManager completedManager)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ParallelOperationManager`3.RunNextWork(TManager completedManager) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/Parallel/ParallelOperationManager.cs:line 265
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.Parallel.ParallelProxyDiscoveryManager.HandlePartialDiscoveryComplete(IProxyDiscoveryManager proxyDiscoveryManager, Int64 totalTests, IEnumerable`1 lastChunk, Boolean isAborted) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/Parallel/ParallelProxyDiscoveryManager.cs:line 200
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.Parallel.ParallelDiscoveryEventsHandler.HandleDiscoveryComplete(DiscoveryCompleteEventArgs discoveryCompleteEventArgs, IEnumerable`1 lastChunk) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/Parallel/ParallelDiscoveryEventsHandler.cs:line 75
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyDiscoveryManager.cs:line 189
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.Parallel.ParallelProxyDiscoveryManager.<>c__DisplayClass27_0.<DiscoverTestsOnConcurrentManager>b__0() in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/Parallel/ParallelProxyDiscoveryManager.cs:line 313
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: The provided manager was not found in any slot.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ParallelOperationManager`3.ClearCompletedSlot(TManager completedManager)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ParallelOperationManager`3.RunNextWork(TManager completedManager) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/Parallel/ParallelOperationManager.cs:line 265
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.Parallel.ParallelProxyDiscoveryManager.HandlePartialDiscoveryComplete(IProxyDiscoveryManager proxyDiscoveryManager, Int64 totalTests, IEnumerable`1 lastChunk, Boolean isAborted) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/Parallel/ParallelProxyDiscoveryManager.cs:line 200
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.Parallel.ParallelDiscoveryEventsHandler.HandleDiscoveryComplete(DiscoveryCompleteEventArgs discoveryCompleteEventArgs, IEnumerable`1 lastChunk) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/Parallel/ParallelDiscoveryEventsHandler.cs:line 75
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyDiscoveryManager.cs:line 189
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.Parallel.ParallelProxyDiscoveryManager.<>c__DisplayClass27_0.<DiscoverTestsOnConcurrentManager>b__0() in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/Parallel/ParallelProxyDiscoveryManager.cs:line 313
   at System.Threading.Tasks.Task.Execute()<---

```

**Comment by PureWeen** [comment]
@jeremy-visionaid you can't run the device tests through Text Explorer :-( 

You have to use the Visual Runner. So, set the Device TEsts as your startup project and just launch it like you would any maui app.

**Comment by jeremy-visionaid** [comment]
@PureWeen That's great thanks, definitely the article I was missing. However, even now knowing the article title, I wasn't able to find it from the other salient pages - or google. Maybe a hyperlink here or there might make that one a bit easier to find?

https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md
https://github.com/dotnet/maui/wiki/Testing

Excluding them from Test Explorer discovery if somehow possible would also be good (since the unit tets work from there, but the device tests don't). Still, in hindsight, I probably should have figured it out on my own 😅

I've updated the commit with a device test that would otherwise crash without the guard.

File: src/Core/src/Platform/Windows/RootNavigationView.cs [hunk 1]
```diff
@@ -329,7 +329,7 @@ void UpdateFlyoutPaneSize()
 			if (PaneContentGrid == null)
 				return;
 
-			var newSize = new Size(OpenPaneLength, PaneContentGrid.ActualHeight - PaneContentGrid.RowDefinitions[1].Height.Value);
+			var newSize = new Size(OpenPaneLength, Math.Max(PaneContentGrid.ActualHeight - PaneContentGrid.RowDefinitions[1].Height.Value, 0));
```
Comment (PureWeen) [inline src/Core/src/Platform/Windows/RootNavigationView.cs:332]: Is there any reason to let this continue if we know the layout hasn't occurred yet? 

would something like this work?

This code is going to have to run a second time with correct values once the flyout is opened so it seems like we shouldn't really set anything quite yet. 

```C#
			var newHeight = PaneContentGrid.ActualHeight - PaneContentGrid.RowDefinitions[1].Height.Value;
			if (newHeight < 0)
				return;

			var newSize = new Size(OpenPaneLength, newHeight);
```

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Windows/RootNavigationView.cs (hunk 1 above)
Comment (jeremy-visionaid) [reply src/Core/src/Platform/Windows/RootNavigationView.cs:332]: Yeah, I was debating whether to go with the early return or the more minimal change. I prefer the early return myself, since I think it's technically better, but ironically thought the more minimal change was likely to be accepted. At the end of the day I just want my app not to crash, so I'm happy to change it.

**Review by PureWeen — APPROVED** [review]
