### PR TITLE
[Windows, Mac] Fixed Disappearing event not triggered when closing a window with a modal page

### LINKED ISSUE #19675: Win: Disappearing event is not be occurred on the modal page when the second window close
### Description

Please look at the Reproduce part.

### Steps to Reproduce

1. open the sln file using vs2022
2. set the break point on the ModalPage_Disappearing method of ModalPage.xaml.cs
3. f5 to run the app
4. click the "Open Window" Button
5. click the "Open Modal" Button
6. close the Window (not click the "Close Modal" Button)

result:
ModalPage_Disappearing is not be occurred

expect:
ModalPage_Disappearing can be occurred

### Link to public reproduction project repository

https://github.com/jingliancui/ModalDisappearIssue

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Win 11 19041

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Vignesh-SF3580**
### Issue Detail
When a page is pushed using PushModalAsync and the window is then closed, the Disappearing event for the pushed page is not triggered.

### Root Cause
The Disappearing event was only triggered when the ModalStack count was zero during window closure. When pushing the page, stack count was greater than zero, which results in restricting the Disappearing event.

### Description of Change
Modified the logic to trigger the Disappearing event for the last page in the stack when closing the window, which resolves the issue.

### Reference:
In PopModalAsync, the [Disappearing](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.cs#L220) event is triggered for the [LastPage](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.cs#L205) in the stack. The same logic is now applied when closing the window.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/19675

### Screenshots

Mac:
| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="300" height="600"  src="https://github.com/user-attachments/assets/f54d18d2-cae7-4f68-8819-f91fb1e8eb77"> | <video width="300" height="600"  src="https://github.com/user-attachments/assets/6d4eaef8-d485-42ec-85af-9832f7f6e660">) |

Windows:
| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="300" height="600"  src="https://github.com/user-attachments/assets/ca74cdf6-b60a-4bf1-b322-3efc4c44876c"> | <video width="300" height="600"  src="https://github.com/user-attachments/assets/2a42c053-a193-4216-98bc-2e124d52d1cc">) |

### CODE REVIEW

File: src/Controls/tests/DeviceTests/Elements/Modal/ModalTests.cs [hunk 1]
```diff
@@ -556,6 +556,28 @@ await CreateHandlerAndAddToWindow(window, async () =>
 			});
 		}
 
+#if WINDOWS || MACCATALYST
```
Comment (jsuarezruiz) [inline src/Controls/tests/DeviceTests/Elements/Modal/ModalTests.cs:559]: Why is not running in the rest of the platforms?

File: src/Controls/src/Core/Window/Window.cs [hunk 2]
```diff
@@ -431,7 +431,13 @@ void SendWindowAppearing()
 		void SendWindowDisppearing()
 		{
 			if (Navigation.ModalStack.Count == 0)
+			{
 				Page?.SendDisappearing();
+			}
+			else if (Navigation.ModalStack.Count > 0)
+			{
+				Navigation.ModalStack[Navigation.ModalStack.Count - 1]?.SendDisappearing();
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Window/Window.cs:439]: Can use `Navigation.ModalStack[^1];`

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/DeviceTests/Elements/Modal/ModalTests.cs (hunk 1 above)
Comment (Vignesh-SF3580) [reply src/Controls/tests/DeviceTests/Elements/Modal/ModalTests.cs:559]: @jsuarezruiz This issue only occurs when closing the window, which is a scenario supported on Windows and MacCatalyst. On Android and iOS, the concept of closing a window does not exist in the same way, so this behavior cannot be reproduced or tested on those platforms. For this reason, the test is limited to Windows and MacCatalyst.

File: src/Controls/src/Core/Window/Window.cs (hunk 2 above)
Comment (Vignesh-SF3580) [reply src/Controls/src/Core/Window/Window.cs]: @jsuarezruiz I’ve updated the code based on your suggestion. Please let me know if you have any further concerns.

File: src/Controls/src/Core/Window/Window.cs [hunk 3]
```diff
@@ -431,7 +431,13 @@ void SendWindowAppearing()
 		void SendWindowDisppearing()
 		{
 			if (Navigation.ModalStack.Count == 0)
+			{
 				Page?.SendDisappearing();
+			}
+			else if (Navigation.ModalStack.Count > 0)
+			{
+				Navigation.ModalStack[^1]?.SendDisappearing();
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Window/Window.cs:439]: Sorry, will require to update this for net standard 2.0:

```
/Users/builder/azdo/_work/1/s/src/Controls/src/Core/Window/Window.cs(439,27): error CS0518: Predefined type 'System.Index' is not defined or imported [/Users/builder/azdo/_work/1/s/src/Controls/src/Core/Controls.Core.csproj::TargetFramework=netstandard2.0]
/Users/builder/azdo/_work/1/s/src/Controls/src/Core/Window/Window.cs(439,27): error CS0656: Missing compiler required member 'System.Index..ctor' [/Users/builder/azdo/_work/1/s/src/Controls/src/Core/Controls.Core.csproj::TargetFramework=netstandard2.0]
    2 Error(s)
```

```
if (Navigation.ModalStack.Count > 0)
{
    Navigation.ModalStack[Navigation.ModalStack.Count - 1]?.SendDisappearing();
}
```

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

**Review by jsuarezruiz — APPROVED** [review]
