### PR TITLE
[iOS/Catalyst] Fixed Editor placeholder position based on alignment

### LINKED ISSUE #18282: [iOS, Mac] The editor placeholder can't able to changed, It's default placed at center
### Description

The editor placeholder position can't able to change, It's default placed at center.
It's occurs in the .NET 8.0 version.
And I attach the sample.

Mac:
Screenshot 2023-10-24 at 1 41 10 PM

iOS:
Simulator Screenshot - iPhone 14 Pro Max - 2023-10-24 at 13 53 19

[EditorSample.zip](https://github.com/dotnet/maui/files/13112260/EditorSample.zip)

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16.4 (simulator)

### Did you find any workaround?

No

### Relevant log output

```shell
NA
```

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fixed iOS Editor placeholder position based on alignment.

image

### Issues Fixed

Fixes #18282

### CODE REVIEW

File: src/Core/src/Platform/iOS/MauiTextView.cs [hunk 1]
```diff
@@ -127,7 +127,8 @@ MauiLabel InitPlaceholderLabel()
 			{
 				BackgroundColor = UIColor.Clear,
 				TextColor = ColorExtensions.PlaceholderColor,
-				Lines = 0
+				Lines = 0,
+				VerticalAlignment = UIControlContentVerticalAlignment.Top
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/MauiTextView.cs:131]: `_placeholderLabel ` VerticalAlignment is Center default. The `UpdatePlaceholderLabelFrame `method update the placeholder UILabel Frame (position) taking into account the size and the UIEdgeInsets.

**Review by rmarinho — APPROVED** [review]
