### PR TITLE
Fix blurry FontImageSource icons in iOS Tab Bar and buttons

### LINKED ISSUE #6043: [RC1] - iOS FontImageSource in AppShell TabBar Pixelation
### Description

When using FontImageSource as the Icon source in the TabBar, the resulting icons in the TabBar are heavilly pixelated. So much so that it's fairly pointless to use font icons in iOS. 

This works great in Android and allows for great flexiblity when using the AppShell.

See below screenshots for reference

| iOS | Android |
| :-: | :-: |
|  |  |

[Reproduction Repo ](https://github.com/RichardMarsh/Maui.Test)

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Add a icon font to the resource folder and include in app start up
3. Setup app shell to use a TabBar and add several ShellContent entries
4. Set the ShellConent Icon property to FontImageSource and use glyphs from the font icons added earlier

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #14728: FontImageSource blurry on IOS in button and imagebutton
### Description

When I use a FontImageSource for a button or an imagebutton the icon is blurry on ios.
Using the same FontImageSource in an image is rendered correctly.

### Steps to Reproduce

1. Start the app
2. Click on button "Icons"

### Link to public reproduction project repository

https://github.com/FM1973/RefreshGridRepo.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ISO 14+

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by japarson**
### Description of Change
We are not properly scaling the iOS icons:
```C#
var scale = destinationContext.Window?.Screen?.Scale ?? 1;
```

The issue here is that on the first render, the Window is null, so we use a scale of 1 instead of e.g., 3. We can instead get the Window and scale through `MauiContext`. In the tab bar, we weren't using a scale at all.

image

### Issues Fixed
Fixes #6043
Fixes #14728

### CODE REVIEW

File: src/Core/src/Platform/Tizen/ImageSourcePartExtensions.cs [hunk 1]
```diff
@@ -1,30 +1,41 @@
...
 using System.Threading.Tasks;
+using Microsoft.Extensions.DependencyInjection;
 using NView = Tizen.NUI.BaseComponents.View;
 using TImage = Tizen.NUI.BaseComponents.ImageView;
 
 namespace Microsoft.Maui.Platform
 {
 	public static class ImageSourcePartExtensions
 	{
-		public static async Task<IImageSourceServiceResult<MauiImageSource>?> UpdateSourceAsync(this IImageSourcePart image, NView destinationContext, IImageSourceServiceProvider services, Action<MauiImageSource?> setImage, CancellationToken cancellationToken = default)
```
Comment (japarson) [inline src/Core/src/Platform/Tizen/ImageSourcePartExtensions.cs:11]: @PureWeen Was it necessary to match the API here? Tizen doesn't looks like it uses a scale. I jsut wanted to be consistent.

File: src/Core/src/Platform/Windows/ImageSourcePartExtensions.cs [hunk 2]
```diff
@@ -22,17 +23,21 @@ internal static class ImageSourcePartExtensions
...
 			events?.LoadingStarted();
 			image.UpdateIsLoading(true);
 
 			try
 			{
-				var service = services.GetRequiredImageSourceService(imageSource);
+				var imageSourceServiceProvider = mauiContext.Services.GetRequiredService<IImageSourceServiceProvider>();
+				var imageSourceService = imageSourceServiceProvider.GetRequiredImageSourceService(imageSource);
 
 				var scale = destinationContext.XamlRoot?.RasterizationScale ?? 1;
```
Comment (japarson) [inline src/Core/src/Platform/Windows/ImageSourcePartExtensions.cs:39]: @PureWeen Windows doesn't get scale from the Window. Should it be changed?

**Comment by japarson** [comment]
@jknaudt21 Can you point out any documentation that needs to be added?

File: src/Core/src/Platform/Windows/ImageSourcePartExtensions.cs (hunk 2 above)
Comment (japarson) [reply src/Core/src/Platform/Windows/ImageSourcePartExtensions.cs:39]: Possibly related? https://github.com/dotnet/maui/issues/1000

**Comment by jknaudt21** [comment]
> @jknaudt21 Can you point out any documentation that needs to be added?

Not really. A lot of Maui.Platform doesn't get displayed in the [docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.platform?view=net-maui-7.0) (don't know why), so there's nothing here that stands out. 

That being said, you could always take the opportunity to document UpdateSourceAsync 😋

**Review by jknaudt21 — DISMISSED** [review]
Looks good to me! Aside from seeing if Windows should also receive the same fix (you already mentioned this in the comments), my only recommendation would be to add a test to check that that image's scale matches that of the IMauiContext. Not sure if that's even possible, but might we worth a try.

**Comment by mattleibow** [comment]
I think I also had a start with this, but no idea what state it is in: https://github.com/dotnet/maui/pull/14807/files

One difference I see is that I used an optional window method, so I am wondering if there are situations where there is no window yet.

Also, does this respond to density/scaling changes? Like on macOS you update the display scale?

**Comment by PureWeen** [comment]
> One difference I see is that I used an optional window method, so I am wondering if there are situations where there is no window yet.
> 

I don't think so, the `MauiContext` you use for this stuff only comes into existence if there's a window. 

We could still keep the code in place here

https://github.com/dotnet/maui/pull/16864/files#diff-a209ad18263c1c3effbd89b25fff7dbe248270890bb057f2564180cb0b7550b5L32

That defaults to one if no windows is set though.

Maybe it can log a warnings?

> Also, does this respond to density/scaling changes? Like on macOS you update the display scale?

Not really sure how to achieve this right now. Image does this because we inherit from UIImageView but we can't inherit from UIButton. Perhaps we just need to wrap all our UIButtons so we can get life cycle events from them.

File: src/Core/src/ImageSources/ImageSourceExtensions.cs [hunk 3]
```diff
@@ -49,7 +49,8 @@ static async Task LoadImageResult(Task<IImageSourceServiceResult<PlatformImage>?
 				return Task.FromResult<IImageSourceServiceResult<PlatformImage>?>(null);
 
 #if IOS || MACCATALYST
-			return imageSourceService.GetImageAsync(imageSource);
+			var scale = mauiContext.GetPlatformWindow().Screen.Scale;
```
Comment (mattleibow) [inline src/Core/src/ImageSources/ImageSourceExtensions.cs:52]: Should we use the `GetDisplayDensity()` extension method, then we can use it in all the platforms.

File: src/Core/src/PublicAPI/net-ios/PublicAPI.Shipped.txt [hunk 4]
```diff
@@ -2795,7 +2795,6 @@ static Microsoft.Maui.Platform.ImageViewExtensions.Clear(this UIKit.UIImageView!
 static Microsoft.Maui.Platform.ImageViewExtensions.UpdateAspect(this UIKit.UIImageView! imageView, Microsoft.Maui.IImage! image) -> void
 static Microsoft.Maui.Platform.ImageViewExtensions.UpdateIsAnimationPlaying(this UIKit.UIImageView! imageView, Microsoft.Maui.IImageSourcePart! image) -> void
 static Microsoft.Maui.Platform.ImageViewExtensions.UpdateSource(this UIKit.UIImageView! imageView, UIKit.UIImage? uIImage, Microsoft.Maui.IImageSourcePart! image) -> void
-static Microsoft.Maui.Platform.ImageViewExtensions.UpdateSourceAsync(this UIKit.UIImageView! imageView, Microsoft.Maui.IImageSourcePart! image, Microsoft.Maui.IImageSourceServiceProvider! services, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken)) -> System.Threading.Tasks.Task<Microsoft.Maui.IImageSourceServiceResult<UIKit.UIImage!>?>!
```
Comment (mattleibow) [inline src/Core/src/PublicAPI/net-ios/PublicAPI.Shipped.txt:2798]: We cannot modify the shipped APIs - a tool does that.

Also, this means a breaking change so we need to avoid that at all costs at this point.

File: src/Core/src/Platform/Android/ImageSourcePartExtensions.cs [hunk 5]
```diff
@@ -11,7 +12,7 @@ public static class ImageSourcePartExtensions
 		public static async Task<IImageSourceServiceResult?> UpdateSourceAsync(
 			this IImageSourcePart image,
 			View destinationContext,
-			IImageSourceServiceProvider services,
+			IMauiContext? mauiContext,
```
Comment (mattleibow) [inline src/Core/src/Platform/Android/ImageSourcePartExtensions.cs:15]: Is there a reason for this API change? It is a public/braking API so we should avoid it. Also, using a maui context makes it a bit harder to unit test with custom services.

File: src/Core/src/Platform/Windows/ImageSourcePartExtensions.cs (hunk 2 above)
Comment (mattleibow) [reply src/Core/src/Platform/Windows/ImageSourcePartExtensions.cs:39]: Windows has a `GetDisplayDensity()` that gets the display using the HWND, so maybe using that is better?

**Review by mattleibow — COMMENTED** [review]
Looks OK generally, maybe some thoughts:
 - we should probably avoid API shanges
 - Maybe use the ubiquitous `GetDisplayDensity()` on all platform windows to get the density as it is a uniform API and supports windows' unique features.

**Comment by jfversluis** [comment]
@japarson you're still OK processing the feedback and taking this home? If not, please let us know so we can look at it! Thanks!

File: src/Core/src/Platform/iOS/SliderExtensions.cs [hunk 6]
```diff
@@ -47,10 +48,13 @@ public static async Task UpdateThumbImageSourceAsync(this UISlider uiSlider, ISl
 		{
 			var thumbImageSource = slider.ThumbImageSource;
 
+			uiSlider.GetDisplayDensity();
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/SliderExtensions.cs:51]: Does this do anything?

File: src/Core/src/ImageSources/FontImageSourceService/FontImageSourceService.Windows.cs [hunk 7]
```diff
@@ -24,13 +24,19 @@ public partial class FontImageSourceService
 
 			try
 			{
+				// TODO: The DPI not working as the view is not respecting the
+				//       value, so just reset to 1 to keep the correct size.
+				scale = 1;
```
Comment (mattleibow) [inline src/Core/src/ImageSources/FontImageSourceService/FontImageSourceService.Windows.cs:29]: Maybe we need a comment to link to https://github.com/dotnet/maui/issues/1000

**Review by mattleibow — COMMENTED** [review]
looks good.

File: src/Core/src/ImageSources/ImageSourceServiceResultManager.cs [hunk 8]
```diff
@@ -24,11 +43,31 @@ public CancellationToken BeginLoad()
...
 			CompleteLoad((IDisposable?)result);
 
 			IsResolutionDependent = result?.IsResolutionDependent ?? false;
+
+#if IOS || MACCATALYST || WINDOWS
+			CurrentResolution = uiContext.GetDisplayDensity();
+#endif
+		}
+
+		public bool RequiresReload(PlatformView uiContext)
```
Comment (mattleibow) [inline src/Core/src/ImageSources/ImageSourceServiceResultManager.cs:57]: I wonder if we should have an overload that takes a IMauiContext so we can get the window density instead of the view stuff. I am thinking in Windows where a view does not have a Window property...

File: src/Core/src/Platform/iOS/SliderExtensions.cs (hunk 6 above)
Comment (japarson) [reply src/Core/src/Platform/iOS/SliderExtensions.cs:51]: I copied this line from Matt's PR. It calculates the density like so: https://github.com/dotnet/maui/blob/8289030e528cbc7737a35e61a91d978d6cb4b829/src/Core/src/Platform/iOS/ViewExtensions.cs#L911-L912

In theory, I think it does something. I can remove the change if you want.

**Review by PureWeen — APPROVED** [review]

File: src/Core/src/ImageSources/ImageSourceServiceResultManager.cs (hunk 8 above)
Comment (japarson) [reply src/Core/src/ImageSources/ImageSourceServiceResultManager.cs:57]: Will address in a future PR.
