### PR TITLE
Avoid notify changes from a null or disposed control

### LINKED ISSUE #5848: App Crash From Multiple Theme Switches
### The Issue

The problem here is that the `AppThemeBinding` works by subscribing to a global WeakEventManager. So any label/page/etc... that subscribes to this will theoretically be GC'd at some point but until that happens you're going to see events getting fired against the page that's no longer reachable. The exception in this issue is coming from the Labels on the ItemsPage. 

I've attached a simplified repro to show what's happening. 
- open repo
- set a break point inside the `AppendToMapping` if statement
- click the button that pushes a page
- click the back button
- change the theme
- the break point will now get hit for the label that's on the second page. 

[If you check the stack trace you'll see it's being generated from the WeakEventManager that's part of the AppThemeBinding](https://github.com/dotnet/maui/blob/92e876e4842443b50b5bf0d6a7edbea46de2e646/src/Controls/src/Core/AppThemeBinding.cs#L12)

[AppThemeBinding.zip](https://github.com/dotnet/maui/files/8445664/AppThemeBinding.zip)

I think in Forms we didn't hit this issue mainly becausewe were super aggressive about disposing of rendererswe added tons of if (View.IsAlive()) checks every where just in case a property changed event fired at a weird point in time

### Description

This is something that I ran across from changing style and theme multiple times on one page in Android.
Switching theme and going back to the same detail page multiple times causes the app to crash.
I've attached a sample project to try and demonstrate the issue.

[MauiFlyout.zip](https://github.com/dotnet/maui/files/8421697/MauiFlyout.zip)

### Steps to Reproduce

Steps for reproducing the bug in Android:
1. Open the flyout menu.
2. Click Browse.
3. Click on the first item to go to its detail page.
4. Click the back button.
5. Open the flyout menu.
6. Click About.
7. Click the switch to change the theme.
8. Repeat steps 1-7. Repeating these steps ~6-7 times causes the app to crash.

https://user-images.githubusercontent.com/29716444/161850326-18bd1ff8-b012-402a-b237-e97035b90f65.mp4

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Avoid notify changes from a null or disposed control. In Xamarin.Forms we was doing something similar but, instead of having something centralized, we did it in different Renderers https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs#L148

### Issues Fixed

Fixes #5848

### CODE REVIEW

File: src/Core/src/PropertyMapper.cs [hunk 1]
```diff
@@ -31,6 +31,9 @@ protected virtual void SetPropertyCore(string key, Action<IElementHandler, IElem
 
 		protected virtual void UpdatePropertyCore(string key, IElementHandler viewHandler, IElement virtualView)
 		{
+			if (!viewHandler.CanUpdateProperty())
```
Comment (rmarinho) [inline src/Core/src/PropertyMapper.cs:34]: Who is calling this if theres no view ?

Comment (jsuarezruiz) [reply src/Core/src/PropertyMapper.cs:34]: For example, AppThemeBinding invoke the method to apply a property. That will use the UpdateValue method from ElementHandler and a Mapper finally will invoke a MapProperty method. Inside that method we use the platform view but, that view could be disposed (GC fires and collects the Android view).

**Comment by jsuarezruiz** [comment]
Applied changes based on a team meeting feedback:
- We don't call DisconnectHandler if the view is disposed.
- Moved the verification to know if a property can be updated from an extension to the PropertyMapper class.

@PureWeen Could you review it when you can?. Thanks.

**Review by rmarinho — APPROVED** [review]

**Review by rmarinho — CHANGES_REQUESTED** [review]
Tests are failing 

image

**Review by rmarinho — APPROVED** [review]
