### PR TITLE
Revert "Remove unused functions (#20029)"

### LINKED ISSUE #20049: [Nightly] Removed EnumerableExtensions break MAUI Xaml Hot Reload
### Description

image

https://github.com/dotnet/maui/pull/20029

These functions were very much used by XAML Hot Reload. Now, if you launch an app with XAML Hot Reload enabled, it will crash. If you want to get rid of this implementation (which is internal, and used for debug tooling) by obsoleting it, or offering an alternative, then that's fine. But you can't break the API.

### Steps to Reproduce

Run the MAUI Source projects or use the newest nightly build with XAML Hot Reload enabled.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by drasticactions**
This reverts commit b4bc1c85e5b2deb19a75cf35ab8b12e916f1c1e9.

This code was used by XAML Hot Reload, which is injected into an MAUI Application after the fact. The code for it is not contained within this repo, so it's not represented as being "used," but it is very much part of the API we need.

### Description of Change

Revert the commit to add back the needed methods.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/20049

### CODE REVIEW

**Comment by symbiogenesis** [comment]
In that case, the IndexOf function should ideally receive the same 4 lines of code as in this commit:

https://github.com/dotnet/maui/pull/19963

It may help speed up HotReload performance.

**Comment by drasticactions** [comment]
> In that case, the IndexOf function should ideally receive the same 4 lines of code as in PR #19963
> 
> It may help improve HotReload performance and memory usage.

Sure, I'm happy to switch it to a new method. But the removed method was accessed in code currently shipping in Visual Studio (for several releases), and that PR broke a shipping product. That method should be labeled obsolete instead of removed, so it won't retroactively break Visual Studio. 

Right now, I just want to make sure we don't break customers.

File: src/Core/src/Extensions/EnumerableExtensions.cs [hunk 1]
```diff
@@ -20,6 +20,29 @@ public static void ForEach<T>(this IEnumerable<T> enumeration, Action<T> action)
 			}
 		}
 
+		/// <summary>
+		///
```
Comment (jsuarezruiz) [inline src/Core/src/Extensions/EnumerableExtensions.cs:24]: Empty documentation

Comment (drasticactions) [reply src/Core/src/Extensions/EnumerableExtensions.cs:24]: This is reverting the already existing code.

**Review by mattleibow — COMMENTED** [review]
Is it possible to add some notes in the code that we should not delete this? An unused internal method is hard to not delete...

**Review by mattleibow — APPROVED** [review]

**Comment by rmarinho** [comment]
Yeah just to add that this is an Internal api and that's why removing didn't broke the PublicAPI . But  I agree we should add a some comment saying why this is used and mark ir as Obsolete in a next PR, can we do that @drasticactions ? 
We could also try design a better public api for this and obsolete this one on net9

**Comment by drasticactions** [comment]
@rmarinho @mattleibow I've made a new PR to add the tags https://github.com/dotnet/maui/pull/20068
