### PR TITLE
[Android] Correctly render shadow navigating back

### LINKED ISSUE #4480: Shadows disappear after navigating to different page
### Description

Shadow added to grid, when I navigate to another page then go back, the shadow is gone.
_(only tested android)_

https://user-images.githubusercontent.com/6544051/152245747-2854379e-4c71-4f4b-a8a2-e2a669fca3b2.mp4

### Steps to Reproduce

Repo -
[ShadowRepo.zip](https://github.com/dotnet/maui/files/7990382/ShadowRepo.zip)
 

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Correctly render **shadow** navigating back. 

To test it, you can uncomment the Shadow from the Gallery MainPage, navigate to anywhere and then navigate back. If the shadow is rendering navigating back, the test has passed.

### Issues Fixed

Fixes #4480

### CODE REVIEW

File: src/Core/src/Platform/Android/WrapperView.cs [hunk 1]
```diff
@@ -37,6 +38,8 @@ protected override void OnDetachedFromWindow()
 		{
 			base.OnDetachedFromWindow();
 
+			_invalidateShadow = true;
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/WrapperView.cs:41]: This is the main change fixing the issue.

**Review by Redth — APPROVED** [review]
