### PR TITLE
[Windows] CarouselViewHandler

### LINKED ISSUE #3460: [Windows] CarouselView not rendering
### Description

On Windows, the CarouselView is not rendering anything.

image

### Steps to Reproduce

Use the attached sample:
[FoodDeliveryApp.zip](https://github.com/dotnet/maui/files/7569879/FoodDeliveryApp.zip)

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.17134.0

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #4088: [Windows] CarouselView not rendering
### Description

CarouselView not rendering
image

### Steps to Reproduce

1. Download [ControlGallery.zip](https://github.com/dotnet/maui/files/7854034/ControlGallery.zip)
2. Try to navigate to the "CarouselView sample".

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 1909

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Implement CarouselViewHandler on Windows.

image
image

_NOTE: In the screenshots there are some Layout issues that we need to review but unrelated with this PR._

- fix https://github.com/dotnet/maui/issues/3460
- fix https://github.com/dotnet/maui/issues/4088

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)

#### Does this PR touch anything that might affect accessibility?
- No

### CODE REVIEW

**Review by rmarinho — COMMENTED** [review]
It's not working very well, but i guess we can commit the basic and they fix the issues

File: src/Controls/src/Core/Handlers/Items/CarouselViewHandler.cs [hunk 1]
```diff
@@ -18,18 +13,14 @@ public CarouselViewHandler(PropertyMapper mapper = null) : base(mapper ?? Carous
 
 		public static PropertyMapper<CarouselView, CarouselViewHandler> CarouselViewMapper = new PropertyMapper<CarouselView, CarouselViewHandler>(ViewMapper)
 		{
-			[Controls.ItemsView.ItemsSourceProperty.PropertyName] = MapItemsSource,
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items/CarouselViewHandler.cs:21]: I think we don't want to remove these mappers

**Review by rmarinho — APPROVED** [review]
