### PR TITLE
Resize star rows/columns _only_ during Arrange, if necessary

### LINKED ISSUE #8126: [WinUI] Error deploying Sample.SingleProject in MainPage.xaml, "A cycle occurred while laying out the GUI."
### Description

If you launch the Maui Sample with the current main (as of https://github.com/dotnet/maui/commit/4d36514b656fed60e495ba1f83a34b4dbb4697d6) the Sample.SingleProject app will throw an exception when running on WinUI when the app starts. I believe this is due to some change in ScrollView

MicrosoftTeams-image

If I remove this Grid, the app loads fine. If I remove the ScollView and put the original Xaml back, it also loads fine. But with both, it blows up on a cycle error.

### Steps to Reproduce

Deploy the Sample.SingleProject app from Main (https://github.com/dotnet/maui/commit/4d36514b656fed60e495ba1f83a34b4dbb4697d6)

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

WinUI

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change

To get #7514 working, we added a re-measure for the Grid during Arrange to get the * rows/columns to lay out at the new size. But re-measuring in some circumstances on Windows causes a layout cycle. 

These changes skip the re-measuring and simply expand the * rows/columns as appropriate when the Grid is set to Fill and the Arrange destination exceeds the DesiredSize. 

### Issues Fixed

Fixes #8126

### CODE REVIEW

File: src/Core/src/Layouts/GridLayoutManager.cs [hunk 1]
```diff
@@ -707,6 +712,65 @@ void EnsureFinalMeasure()
 
 				return available + cellRowsHeight;
 			}
+
+			public void AdjustStarsForArrange(Size targetSize)
```
Comment (rmarinho) [inline src/Core/src/Layouts/GridLayoutManager.cs:716]: Do we need to add a public method in a SR ?

File: src/Core/src/Layouts/GridLayoutManager.cs [hunk 2]
```diff
@@ -28,11 +28,33 @@ public override Size Measure(double widthConstraint, double heightConstraint)
...
+			// to adjust it later if the size is no longer infinity
+
+			// Then we need to loop through all star defs and starasauto defs and mark them as not having a size
+			// then run resolve star rows and resolve star columns again 
+
+			// and then we should be good.
+
+			// This should be pretty easy to write unit tests for
+
+			// Once we have that in place and verify that it works for Windows, check to make sure that this is functional for iOS as well (I don't think it used this feature anyway)
```
Comment (mattleibow) [inline src/Core/src/Layouts/GridLayoutManager.cs:56]: Is this still needed? :)

**Review by mattleibow — APPROVED** [review]

File: src/Core/src/Layouts/GridLayoutManager.cs (hunk 2 above)
Comment (hartez) [reply src/Core/src/Layouts/GridLayoutManager.cs]: Removed.
