### PR TITLE
[iOS] Don't apply mask to UIScrollView so the content doesn't get masked out

### LINKED ISSUE #7524: Border does not grow when editor inside it grows
### Description

Given the following XAML

```
 <Border Stroke="Black" StrokeThickness="2" StrokeShape="RoundRectangle 20" Padding="10" HorizontalOptions="Center" VerticalOptions="Center">
        <Editor WidthRequest="200" Placeholder="Text here" AutoSize="TextChanges"></Editor>
    </Border>
```
If you enter a new line the border will not grow in iOS.

### Steps to Reproduce

Enter the  XAML in Description in a content page. Run the project on iOS. Enter text and press enter key.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #8923: ScrollView inside border is not working in Mac and iOS
### Description

In latest MAUI update, ScrollView inside Border is not working properly in Mac and iOS. The content that is outside the scroll ViewPort on initial loading is not showing after scrolling. Please refer the video

https://user-images.githubusercontent.com/92788387/180431952-663246c2-5074-47e2-a393-15b30b4deff7.mov

### Steps to Reproduce

1. Run the attached sample in mac or ios.
2. On scrolling, the content of scroll view will be hidden.
[Test11.zip](https://github.com/dotnet/maui/files/9167415/Test11.zip)

The issue version is -6.0.419(latest) 
Note: In issue template, v6.0.408 is showing as the latest.

### Version with bug

6.0.408 (current)

### Last version that worked well

6.0.400

### Affected platforms

iOS, macOS

### Affected platform versions

MacOS Monterey v12.1, iOS 13

### Did you find any workaround?

No

### Relevant log output

```shell
NA
```

### LINKED ISSUE #14091: ScrollView inside Border does not render offscreen content after scroll. iOS only.
### Description

A ScrollView inside a Border does not render content that is scrolled into view. 
The content takes up space, so is measured, it just doesn't render.
iOS screenshot.
image

### Steps to Reproduce

1. Create a File->New MAUI app.
2. In MainPage.xaml
   1. Wrap the ScrollView in a Border
   2. Add enough content (e.g. Labels) to the end of the VerticalStackLayout
3. Build and run the app for iOS.

## Expected behaviour
Scrolling content into view ought to render the content.

## Actual behaviour
Content that is scrolled into view is not rendered on the iOS platform.

### Link to public reproduction project repository

https://github.com/Keflon/MauiScrollViewBug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Simulator 16.2; iPhone X 16.3.1.  Probably others.

### Did you find any workaround?

Do not wrap a ScrollView in a Border if targeting iOS.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

On iOS the border platform view `ContainerView` is always applying a Mask using its frame to the child content. This prevents the UIScrollView to proper render its own content because some of it gets masked out.
The fix for now is wrap the platform view `UIScrollView` on the handler in a container when it's inside a `Border`.

Here's some code to test the example:

```
<Border WidthRequest="200" HeightRequest="500" VerticalOptions="Center" HorizontalOptions="Center"
            Stroke="Blue"
            StrokeThickness="4"
            Padding="20"
            Background="LightGray">
        <Border.StrokeShape>
             <RoundRectangle CornerRadius="50,50,50,50" />
        </Border.StrokeShape>
        <ScrollView Padding="10" BackgroundColor="Yellow">
            <Label HeightRequest="1000" HorizontalOptions="Fill" Background="GreenYellow"/>
        </ScrollView>
</Border>
```
iPhone
Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-21 at 14 45 57

Android
MicrosoftTeams-image

### Issues Fixed

Fixes #8923
Fixes #14091
Fixes #7524

### CODE REVIEW

File: src/Core/src/Platform/iOS/ContentView.cs [hunk 1]
```diff
@@ -116,6 +116,13 @@ void SetClip()
 			if (Subviews.Length == 0)
 				return;
 
+			var child = Subviews[0];
+
+			if (child is MauiScrollView mauiScrollView)
+			{
+				return;
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/ContentView.cs:123]: Without use paddings, the same example:
image

Will not be clipped on iOS/macOS by the Border shape, and the UIScrollView will overlay the round corners of the Border. I understand that avoiding the scroll is an important issue, but maybe we have another option. Wrapping the ScrollView if it is a child of a Border and clipping the wrapper instead the ScrollView?

Comment (rmarinho) [reply src/Core/src/Platform/iOS/ContentView.cs:123]: Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-21 at 15 36 36

ok on iOS looks like this

**Comment by rmarinho** [comment]
Ok now using the container seems to work better, but the clip is not right there yet. But this can be fixed by #10964

Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-21 at 16 31 37

**Review by mandel-macaque — APPROVED** [review]

**Comment by rmarinho** [comment]
Applying the changes from the other PR the #10964 it seems perfect.

Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-21 at 16 37 48

**Review by jsuarezruiz — APPROVED** [review]
