### PR TITLE
[iOS] Fix ShellContent Title Does Not Update at Runtime

### LINKED ISSUE #26049: [iOS/Mac] ShellContent Title Does Not Update at Runtime
### Description

The issue occurs when the title of ShellContent does not update dynamically at runtime. Even after modifying the Title property of ShellContent via button click, the title remains unchanged in the UI.

### Steps to Reproduce

Create a TabBar with nested ShellContent items.
Add a button that changes the Title of the ShellContent when clicked.
Run the app.
Click the "Change Title" button.

AppShell.xaml
```
<TabBar AutomationId="TabBar">
    <Tab Title="Nested Tabs" AutomationId="tabbar">
        <ShellContent x:Name="tab" Title="Home">
            <ContentPage>
                <StackLayout HorizontalOptions="Center" Spacing="30">
                    <Button Text="Change Title" AutomationId="ChangeShellContentTitle" VerticalOptions="Center" HorizontalOptions="Center" WidthRequest="100" HeightRequest="40" Clicked="OnButtonClicked"/>
                </StackLayout>
            </ContentPage>
        </ShellContent>

        <ShellContent Title="Settings">
            <ContentPage>
                <Label Text="This is Settings page"/>
            </ContentPage>
        </ShellContent>
    </Tab>
</TabBar>

```

AppShell.xaml.cs
```
private void OnButtonClicked(object sender, EventArgs e)
{
    tab.Title = "New Title";
}
```

Expected Behavior: The title of the ShellContent (tab) should change to "New Title" when the button is clicked.

Actual Behavior: The title remains as "Home" and does not update when the button is clicked.

### Link to public reproduction project repository

[ShellContentTitleIssue](https://github.com/devanathan-vaithiyanathan/ShellContentTitleIssue)

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 18.0, mac 15.1

### Did you find any workaround?

Not yet.

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by devanathan-vaithiyanathan**
### Root cause
The issue occurred because the ShellContent title did not update dynamically in response to property changes. On iOS, real-time updates were not reflected as the Title property changes were not being observed.

### Description of Change

Implemented dynamic title updates for ShellContent by subscribing to the PropertyChanged event. This ensures that any changes to the Title property are observed and updated in real-time, resolving the issue where the title did not reflect updates dynamically.

### Issues Fixed

Fixes #26049 

### Tested the behaviour in the following platforms
 
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Output Screenshot
| Before  | After  |
|---------|--------|
|  <video src="https://github.com/user-attachments/assets/a2bde6b3-a7c6-4bf4-bbfe-ee6c4ac374d5" width="320" height="640" controls></video>   |   <video src="https://github.com/user-attachments/assets/b101e2f1-d235-4fed-91ff-674f0d2c8b68" width="320" height="640" controls></video>   |

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootHeader.cs [hunk 1]
```diff
@@ -200,6 +200,10 @@ public override void ViewDidLoad()
 
 			UpdateSelectedIndex();
 			ShellSection.PropertyChanged += OnShellSectionPropertyChanged;
+			foreach (var shellContent in ShellSectionController.GetItems())
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootHeader.cs:203]: This isn't going to work when items are added or removed.

When an item is removed or added `OnShellSectionItemsChanged` is called which calls `ReloadData` at which point I think your event subscription here will be out of sync.

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootHeader.cs (hunk 1 above)
Comment (devanathan-vaithiyanathan) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootHeader.cs:203]: I have modified the code to address the ShellSection items changes. Please review and let me know

**Comment by jsuarezruiz** [comment]
@devanathan-vaithiyanathan Could you fix the conflict? Thanks in advance.

**Comment by devanathan-vaithiyanathan** [comment]
> @devanathan-vaithiyanathan Could you fix the conflict? Thanks in advance.

 I have resolved the conflicts

**Review by PureWeen — DISMISSED** [review]
Can you add a couple scenarios here

- Add a shellcontent dynamically
- you're able to update the title of that new tab
- remove that shellcontent
- you're able to update the title of an exising tab

**Comment by devanathan-vaithiyanathan** [comment]
> Can you add a couple scenarios here
> 
> * Add a shellcontent dynamically
> * you're able to update the title of that new tab
> * remove that shellcontent
> * you're able to update the title of an exising tab

As per suggestion, I have modified the test. Please let me know if you have any concerns

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26049.cs [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+		public void VerifyFirstShellContentTitle()
+		{
+			App.WaitForElement("ChangeShellContentTitle");
+			App.Click("ChangeShellContentTitle");
+			VerifyScreenshot();
+		}
+
+		[Test, Order(2)]
+		[Category(UITestCategories.Shell)]
+		public void VerifyNewlyAddedShellContentTitle()
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26049.cs:27]: Pending macOS snapshots. Already available in the latest build:
image
Could you commit the images?

**Review by jsuarezruiz — DISMISSED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26049.cs (hunk 2 above)
Comment (devanathan-vaithiyanathan) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26049.cs:27]: I have added mac snapshot. Please let me know if you any concerns

**Comment by jfversluis** [comment]
Failing test unrelated

**Review by jfversluis — APPROVED** [review]
