### PR TITLE
Don’t call NSAttributedString with HTML from a background thread

### LINKED ISSUE #25946: iOS App crashes on iOS 18 when placing html label in carousel view with > 2 elements
### Description

iOS App crashes on iOS 18 when placing html label in carousel view with > 2 elements

### Steps to Reproduce

1. Use iOS 18 device or simulator
2. Place html label in carousel view
3. Add 3 or more items to it
4. Swipe to second element
5. App crashes

### Link to public reproduction project repository

https://github.com/thisisthekap/carousel-bug-repro

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18

### Did you find any workaround?

No workaround other than replacing html label with something else.

### Relevant log output

```shell
ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Expected dequeued view to be returned to the collection view in preparation for display. When the collection view's data source is asked to provide a view for a given index path, ensure that a single view is dequeued and returned to the collection view. Avoid dequeuing views without a request from the collection view. For retrieving an existing view in the collection view, use -[UICollectionView cellForItemAtIndexPath:] or -[UICollectionView supplementaryViewForElementKind:atIndexPath:]. Dequeued view: <Microsoft_Maui_Controls_Handlers_Items_HorizontalCell: 0x10671f640; baseClass = UICollectionViewCell; frame = (786 0; 393 754.333); layer = <CALayer: 0x6000008ac800>>; Collection view: <Microsoft_Maui_Controls_Handlers_Items_MauiCollectionView: 0x107235000; baseClass = UICollectionView; frame = (0 0; 393 754.333); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x600000c80900>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x6000008144a0>; contentOffset: {250, 0}; contentSize: {1179, 754.33333333333326}; adjustedContentInset: {0, 0, 0, 0}; layout: <Microsoft_Maui_Controls_Handlers_Items_CarouselViewLayout: 0x110814c30>; dataSource: <Microsoft_Maui_Controls_Handlers_Items_CarouselViewController: 0x110814020>>
Native stack trace:
	0   CoreFoundation                      0x00000001804b70ec __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018008ede8 objc_exception_throw + 72
	2   Foundation                          0x0000000180e73aa8 _userInfoForFileAndLine + 0
	3   UIKitCore                           0x00000001851ae220 __43-[UICollectionView _updateVisibleCellsNow:]_block_invoke.444 + 136
	4   UIKitCore                           0x0000000185a9b60c -[_UICollectionViewSubviewManager removeAllDequeuedViewsWithEnumerator:] + 188
	5   UIKitCore                           0x00000001851adce8 -[UICollectionView _updateVisibleCellsNow:] + 4000
	6   UIKitCore                           0x00000001851b2af0 -[UICollectionView layoutSubviews] + 284
	7   UIKitCore                           0x000000018601c0c4 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2404
	8   QuartzCore                          0x000000018b06ceb0 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 432
	9   QuartzCore                          0x000000018b077c34 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 124
	10  QuartzCore                          0x000000018afacc58 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 464
	11  QuartzCore                          0x000000018afdb468 _ZN2CA11Transaction6commitEv + 652
	12  QuartzCore                          0x000000018afdc9bc _ZN2CA11Transaction25flush_as_runloop_observerEb + 68
	13  UIKitCore                           0x0000000185aa14dc _UIApplicationFlushCATransaction + 48
	14  UIKitCore                           0x00000001859d2944 __setupUpdateSequence_block_invoke_2 + 352
	15  UIKitCore                           0x0000000185030388 _UIUpdateSequenceRun + 76
	16  UIKitCore                           0x00000001859d22e8 schedulerStepScheduledMainSection + 168
	17  UIKitCore                           0x00000001859d1720 runloopSourceCallback + 80
	18  CoreFoundation                      0x000000018041b324 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
	19  CoreFoundation                      0x000000018041b26c __CFRunLoopDoSource0 + 172
	20  CoreFoundation                      0x000000018041aa2c __CFRunLoopDoSources0 + 324
	21  CoreFoundation                      0x00000001804150b0 __CFRunLoopRun + 788
	22  CoreFoundation                      0x0000000180414960 CFRunLoopRunSpecific + 536
	23  UIFoundation                        0x0000000184c0c53c -[NSHTMLReader _loadUsingWebKit] + 1416
	24  UIFoundation                        0x0000000184c0d064 -[NSHTMLReader attributedString] + 20
	25  UIFoundation                        0x0000000184b90b60 _NSReadAttributedStringFromURLOrDataCommon + 2760
	26  UIFoundation                        0x0000000184b8ca6c _NSReadAttributedStringFromURLOrData + 180
	27  UIFoundation                        0x0000000184b8c950 -[NSAttributedString(NSAttributedStringUIFoundationAdditions) initWithData:options:documentAttributes:error:] + 144
	28  libxamarin-dotnet-debug.dylib       0x0000000106454a14 xamarin_dyn_objc_msgSend + 160
	29  libmonosgen-2.0.dylib               0x0000000106c58a88 do_icall + 368
	30  libmonosgen-2.0.dylib               0x0000000106c572f4 do_icall_wrapper + 356
	31  libmonosgen-2.0.dylib               0x0000000106c4bd44 mono_interp_exec_method + 2836
	32  libmonosgen-2.0.dylib               0x0000000106c498e4 interp_runtime_invoke + 244
	33  libmonosgen-2.0.dylib               0x0000000106b62af0 mono_jit_runtime_invoke + 1116
	34  libmonosgen-2.0.dylib               0x0000000106d1dc3c mono_runtime_invoke_checked + 148
	35  libmonosgen-2.0.dylib               0x0000000106d21d00 mono_runtime_invoke + 544
	36  libxamarin-dotnet-debug.dylib       0x000000010644bb70 xamarin_invoke_trampoline + 5516
	37  libxamarin-dotnet-debug.dylib       0x0000000106453b04 xamarin_arch_trampoline + 148
	38  libxamarin-dotnet-debug.dylib       0x00000001064548e8 xamarin_arm64_common_trampoline + 64
	39  UIKitCore                           0x00000001851a660c __112-[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:]_block_invoke + 48
	40  UIKitCore                           0x000000018601100c +[UIView(Animation) performWithoutAnimation:] + 68
	41  UIKitCore                           0x00000001851a5b4c -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 756
	42  UIKitCore                           0x00000001851a89e0 -[UICollectionView _prefetchItemsForPrefetchingContext:] + 380
	43  UIKitCore                           0x00000001851aad50 -[UICollectionView _updatePrefetchedCells:] + 144
	44  UIKitCore                           0x00000001851ab068 -[UICollectionView _updateCycleIdleUntil:] + 464
	45  UIKitCore                           0x00000001856b1ac0 ___UIUpdateCycleNotifyIdle_block_invoke + 620
	46  libdispatch.dylib                   0x00000001801774ec _dispatch_call_block_and_release + 24
	47  libdispatch.dylib                   0x0000000180178de0 _dispatch_client_callout + 16
	48  libdispatch.dylib                   0x0000000180187c60 _dispatch_main_queue_drain + 1272
	49  libdispatch.dylib                   0x0000000180187758 _dispatch_main_queue_callback_4CF + 40
	50  CoreFoundation                      0x000000018041ae3c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
	51  CoreFoundation                      0x0000000180415534 __CFRunLoopRun + 1944
	52  CoreFoundation                      0x0000000180414960 CFRunLoopRunSpecific + 536
	53  GraphicsServices                    0x0000000190183b10 GSEventRunModal + 160
	54  UIKitCore                           0x0000000185aa2b40 -[UIApplication _run] + 796
	55  UIKitCore                           0x0000000185aa6d38 UIApplicationMain + 124
	56  libxamarin-dotnet-debug.dylib       0x00000001064131e4 xamarin_UIApplicationMain + 60
	57  libmonosgen-2.0.dylib               0x0000000106c58a54 do_icall + 316
	58  libmonosgen-2.0.dylib               0x0000000106c572f4 do_icall_wrapper + 356
	59  libmonosgen-2.0.dylib               0x0000000106c4bd44 mono_interp_exec_method + 2836
	60  libmonosgen-2.0.dylib               0x0000000106c498e4 interp_runtime_invoke + 244
	61  libmonosgen-2.0.dylib               0x0000000106b62af0 mono_jit_runtime_invoke + 1116
	62  libmonosgen-2.0.dylib               0x0000000106d1dc3c mono_runtime_invoke_checked + 148
	63  libmonosgen-2.0.dylib               0x0000000106d2521c mono_runtime_exec_main_checked + 116
	64  libmonosgen-2.0.dylib               0x0000000106bb6d78 mono_jit_exec + 364
	65  libxamarin-dotnet-debug.dylib       0x0000000106453984 xamarin_main + 2324
	66  carousel-bug-repro                  0x00000001052a247c main + 72
	67  dyld                                0x0000000105dc1410 start_sim + 20
	68  ???                                 0x0000000105b02274 0x0 + 4390396532

   at Foundation.NSAttributedString..ctor(NSData data, NSDictionary options, NSDictionary& resultDocumentAttributes, NSError& error) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/Foundation/NSAttributedString.g.cs:line 233
   at Foundation.NSAttributedString..ctor(NSData data, NSAttributedStringDocumentAttributes options, NSDictionary& resultDocumentAttributes, NSError& error) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/Foundation/NSAttributedString.g.cs:line 247
   at Foundation.NSAttributedString..ctor(NSData data, NSAttributedStringDocumentAttributes documentAttributes, NSError& error) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAttributedString.cs:line 61
   at Microsoft.Maui.Platform.LabelExtensions.UpdateTextHtml(UILabel platformLabel, ILabel label)
   at Microsoft.Maui.Controls.Platform.LabelExtensions.UpdateText(UILabel platformLabel, Label label)
   at Microsoft.Maui.Controls.Label.MapText(ILabelHandler handler, Label label)
   at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass2_0`2[[Microsoft.Maui.Controls.Label, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ILabelHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ReplaceMapping>b__0(ILabelHandler h, Label v, Action`2 p)
   at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass1_0`2[[Microsoft.Maui.Controls.Label, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ILabelHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ModifyMapping>g__newMethod|0(IElementHandler handler, IElement view)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.ILabel, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ILabelHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILabel, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiLabel, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILabel, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiLabel, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler)
   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ViewExtensions.ToHandler(IView view, IMauiContext context)
   at Microsoft.Maui.Controls.Handlers.Items.TemplateHelpers.GetHandler(View view, IMauiContext context)
   at Microsoft.Maui.Controls.Handlers.Items.TemplatedCell.Bind(DataTemplate template, Object bindingContext, ItemsView itemsView)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.CarouselView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].UpdateTemplatedCell(TemplatedCell cell, NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.CarouselView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetCell(UICollectionView collectionView, NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.CarouselViewController.GetCell(UICollectionView collectionView, NSIndexPath indexPath)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
   at carousel_bug_repro.Program.Main(String[] args) in /path-to-repository/carousel-bug-repro/carousel-bug-repro/Platforms/iOS/Program.cs:line 12
Native stack trace:
	0   CoreFoundation                      0x00000001804b70ec __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000018008ede8 objc_exception_throw + 72
	2   Foundation                          0x0000000180e73aa8 _userInfoForFileAndLine + 0
	3   UIKitCore                           0x00000001851ae220 __43-[UICollectionView _updateVisibleCellsNow:]_block_invoke.444 + 136
	4   UIKitCore                           0x0000000185a9b60c -[_UICollectionViewSubviewManager removeAllDequeuedViewsWithEnumerator:] + 188
	5   UIKitCore                           0x00000001851adce8 -[UICollectionView _updateVisibleCellsNow:] + 4000
	6   UIKitCore                           0x00000001851b2af0 -[UICollectionView layoutSubviews] + 284
	7   UIKitCore                           0x000000018601c0c4 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2404
	8   QuartzCore                          0x000000018b06ceb0 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 432
	9   QuartzCore                          0x000000018b077c34 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 124
	10  QuartzCore                          0x000000018afacc58 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 464
	11  QuartzCore                          0x000000018afdb468 _ZN2CA11Transaction6commitEv + 652
	12  QuartzCore                          0x000000018afdc9bc _ZN2CA11Transaction25flush_as_runloop_observerEb + 68
	13  UIKitCore                           0x0000000185aa14dc _UIApplicationFlushCATransaction + 48
	14  UIKitCore                           0x00000001859d2944 __setupUpdateSequence_block_invoke_2 + 352
	15  UIKitCore                           0x0000000185030388 _UIUpdateSequenceRun + 76
	16  UIKitCore                           0x00000001859d22e8 schedulerStepScheduledMainSection + 168
	17  UIKitCore                           0x00000001859d1720 runloopSourceCallback + 80
	18  CoreFoundation                      0x000000018041b324 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
	19  CoreFoundation                      0x000000018041b26c __CFRunLoopDoSource0 + 172
	20  CoreFoundation                      0x000000018041aa2c __CFRunLoopDoSources0 + 324
	21  CoreFoundation                      0x00000001804150b0 __CFRunLoopRun + 788
	22  CoreFoundation                      0x0000000180414960 CFRunLoopRunSpecific + 536
	23  UIFoundation                        0x0000000184c0c53c -[NSHTMLReader _loadUsingWebKit] + 1416
	24  UIFoundation                        0x0000000184c0d064 -[NSHTMLReader attributedString] + 20
	25  UIFoundation                        0x0000000184b90b60 _NSReadAttributedStringFromURLOrDataCommon + 2760
	26  UIFoundation                        0x0000000184b8ca6c _NSReadAttributedStringFromURLOrData + 180
	27  UIFoundation                        0x0000000184b8c950 -[NSAttributedString(NSAttributedStringUIFoundationAdditions) initWithData:options:documentAttributes:error:] + 144
	28  libxamarin-dotnet-debug.dylib       0x0000000106454a14 xamarin_dyn_objc_msgSend + 160
	29  libmonosgen-2.0.dylib               0x0000000106c58a88 do_icall + 368
	30  libmonosgen-2.0.dylib               0x0000000106c572f4 do_icall_wrapper + 356
	31  libmonosgen-2.0.dylib               0x0000000106c4bd44 mono_interp_exec_method + 2836
	32  libmonosgen-2.0.dylib               0x0000000106c498e4 interp_runtime_invoke + 244
	33  libmonosgen-2.0.dylib               0x0000000106b62af0 mono_jit_runtime_invoke + 1116
	34  libmonosgen-2.0.dylib               0x0000000106d1dc3c mono_runtime_invoke_checked + 148
	35  libmonosgen-2.0.dylib               0x0000000106d21d00 mono_runtime_invoke + 544
	36  libxamarin-dotnet-debug.dylib       0x000000010644bb70 xamarin_invoke_trampoline + 5516
	37  libxamarin-dotnet-debug.dylib       0x0000000106453b04 xamarin_arch_trampoline + 148
	38  libxamarin-dotnet-debug.dylib       0x00000001064548e8 xamarin_arm64_common_trampoline + 64
	39  UIKitCore                           0x00000001851a660c __112-[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:]_block_invoke + 48
	40  UIKitCore                           0x000000018601100c +[UIView(Animation) performWithoutAnimation:] + 68
	41  UIKitCore                           0x00000001851a5b4c -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 756
	42  UIKitCore                           0x00000001851a89e0 -[UICollectionView _prefetchItemsForPrefetchingContext:] + 380
	43  UIKitCore                           0x00000001851aad50 -[UICollectionView _updatePrefetchedCells:] + 144
	44  UIKitCore                           0x00000001851ab068 -[UICollectionView _updateCycleIdleUntil:] + 464
	45  UIKitCore                           0x00000001856b1ac0 ___UIUpdateCycleNotifyIdle_block_invoke + 620
	46  libdispatch.dylib                   0x00000001801774ec _dispatch_call_block_and_release + 24
	47  libdispatch.dylib                   0x0000000180178de0 _dispatch_client_callout + 16
	48  libdispatch.dylib                   0x0000000180187c60 _dispatch_main_queue_drain + 1272
	49  libdispatch.dylib                   0x0000000180187758 _dispatch_main_queue_callback_4CF + 40
	50  CoreFoundation                      0x000000018041ae3c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
	51  CoreFoundation                      0x0000000180415534 __CFRunLoopRun + 1944
	52  CoreFoundation                      0x0000000180414960 CFRunLoopRunSpecific + 536
	53  GraphicsServices                    0x0000000190183b10 GSEventRunModal + 160
	54  UIKitCore                           0x0000000185aa2b40 -[UIApplication _run] + 796
	55  UIKitCore                           0x0000000185aa6d38 UIApplicationMain + 124
	56  libxamarin-dotnet-debug.dylib       0x00000001064131e4 xamarin_UIApplicationMain + 60
	57  libmonosgen-2.0.dylib               0x0000000106c58a54 do_icall + 316
	58  libmonosgen-2.0.dylib               0x0000000106c572f4 do_icall_wrapper + 356
	59  libmonosgen-2.0.dylib               0x0000000106c4bd44 mono_interp_exec_method + 2836
	60  libmonosgen-2.0.dylib               0x0000000106c498e4 interp_runtime_invoke + 244
	61  libmonosgen-2.0.dylib               0x0000000106b62af0 mono_jit_runtime_invoke + 1116
	62  libmonosgen-2.0.dylib               0x0000000106d1dc3c mono_runtime_invoke_checked + 148
	63  libmonosgen-2.0.dylib               0x0000000106d2521c mono_runtime_exec_main_checked + 116
	64  libmonosgen-2.0.dylib               0x0000000106bb6d78 mono_jit_exec + 364
	65  libxamarin-dotnet-debug.dylib       0x0000000106453984 xamarin_main + 2324
	66  carousel-bug-repro                  0x00000001052a247c main + 72
	67  dyld                                0x0000000105dc1410 start_sim + 20
	68  ???                                 0x0000000105b02274 0x0 + 4390396532
```

### PR DESCRIPTION
**Pull request by kubaflo**
According to Apple's documentation: https://developer.apple.com/documentation/foundation/nsattributedstring/1524613-initwithdata

> Don’t call this method from a background thread if the options dictionary includes the [NSDocumentTypeDocumentAttribute](https://developer.apple.com/documentation/uikit/nsdocumenttypedocumentattribute) attribute with a value of [NSHTMLTextDocumentType](https://developer.apple.com/documentation/uikit/nshtmltextdocumenttype). If you do, the method tries to synchronize with the main thread, fails, and times out. Calling it from the main thread works, but can still time out if the HTML contains references to external resources. The HTML import mechanism is meant for implementing something like markdown (that is, text styles, colors, and so on), not for general HTML import.

Also, it seems to be a common problem among Apple developers:
https://forums.developer.apple.com/forums/thread/115405

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/25946

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/21af7336-8df7-44a1-aa8f-4a27d2cf2579" width="300px"/>|<video width="300px" src="https://github.com/user-attachments/assets/449c911a-0ceb-4d26-a086-88be87dee3c3" />|

### CODE REVIEW

**Comment by kubaflo** [comment]
I now noticed that the crash happens with `CarouselView1` only when swiping between more than 2 items, but in the case of `CarouselView2` the app crashes instantly when `CarouselView2` has more than 1 item

```
<CarouselView Grid.Row="1">
    <CarouselView.ItemsSource>
        <x:Array Type="{x:Type x:String}">
            <x:String>Item1</x:String>
            <x:String>Item2</x:String>
        </x:Array>
    </CarouselView.ItemsSource>
    <CarouselView.ItemTemplate>
        <DataTemplate>
            <VerticalStackLayout Background="Red">
                <Label Text="Hello"/>
                <Label Text="{Binding .}"
                        TextType="Html"/>
            </VerticalStackLayout>
        </DataTemplate>
    </CarouselView.ItemTemplate>
</CarouselView>
```

**Comment by kubaflo** [comment]
Ohh I just bumped into a scaling issue with ListView/CollectionView1 and CollectionView1 after changes in this PR:

For the following code: 
```
<Grid RowDefinitions="*,*">
    <CollectionView>
        <CollectionView.ItemsSource>
            <x:Array Type="{x:Type x:String}">
                <x:String>Item1</x:String>
                <x:String>Item1</x:String>
                <x:String>Item1</x:String>
            </x:Array>
        </CollectionView.ItemsSource>
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <VerticalStackLayout>
                    <Label Text="Hello"/>
                    <Label Text="{Binding .}"
                            TextType="Html"/>
                </VerticalStackLayout>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>

    <StackLayout Grid.Row="1">
        <BindableLayout.ItemsSource>
            <x:Array Type="{x:Type x:String}">
                <x:String>Item1</x:String>
                <x:String>Item1</x:String>
                <x:String>Item1</x:String>
            </x:Array>
        </BindableLayout.ItemsSource>
        <BindableLayout.ItemTemplate>
            <DataTemplate>
                <VerticalStackLayout>
                    <Label Text="Hello"/>
                    <Label Text="{Binding .}"
                            TextType="Html"/>
                </VerticalStackLayout>
            </DataTemplate>
        </BindableLayout.ItemTemplate>
    </StackLayout>
</Grid>
```
I have a cell scaling issue


@rmarinho do you maybe have idea why it happens?

**Review by rmarinho — CHANGES_REQUESTED** [review]
Nop, not from the top of my mind, can we rebase, see if it's still a issue and also add a test case for this ?

**Comment by kubaflo** [comment]
> Nop, not from the top of my mind, can we rebase, see if it's still a issue and also add a test case for this ?

I've rebased, but the issue is still there without using `MainQueue.DispatchAsync`
However, I'm not sure if it is a correct fix, because it still regresses the height of HTML text in listView and cv

**Review by rmarinho — DISMISSED** [review]
Failing tests on iOS not related

File: src/Core/src/Platform/iOS/LabelExtensions.cs [hunk 1]
```diff
@@ -88,9 +88,16 @@ internal static void UpdateTextHtml(this UILabel platformLabel, ILabel label)
 			};
 
 			NSError nsError = new();
-#pragma warning disable CS8601
-			platformLabel.AttributedText = new NSAttributedString(text, attr, ref nsError);
-#pragma warning restore CS8601
+			CoreFoundation.DispatchQueue.MainQueue.DispatchAsync(() =>
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/LabelExtensions.cs:91]: I might not be following your description quite right but should we check if we're on a background thread before dispatching?

File: src/Core/src/Platform/iOS/LabelExtensions.cs [hunk 2]
```diff
@@ -88,9 +88,16 @@ internal static void UpdateTextHtml(this UILabel platformLabel, ILabel label)
...
+			{
+				platformLabel.AttributedText = new NSAttributedString(text, attr, ref nsError);
+				if (label.Handler is ILabelHandler labelHandler)
+				{
+					labelHandler.UpdateValue(nameof(ILabel.TextColor));
+					labelHandler.UpdateValue(nameof(ILabel.Font));
+				}
+				label.InvalidateMeasure();
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/LabelExtensions.cs:99]: What happens if we don't include this?

**Review by PureWeen — DISMISSED** [review]

File: src/Core/src/Platform/iOS/LabelExtensions.cs (hunk 2 above)
Comment (kubaflo) [reply src/Core/src/Platform/iOS/LabelExtensions.cs:99]: Without `label.InvalidateMeasure();` the label doesn't render

File: src/Core/src/Platform/iOS/LabelExtensions.cs (hunk 1 above)
Comment (kubaflo) [reply src/Core/src/Platform/iOS/LabelExtensions.cs:91]: With something like this:

```c#
NSError nsError = new();
if (NSThread.IsMain)
{
	platformLabel.AttributedText = new NSAttributedString(text, attr, ref nsError);
	if (label.Handler is ILabelHandler labelHandler)
	{
		labelHandler.UpdateValue(nameof(ILabel.TextColor));
		labelHandler.UpdateValue(nameof(ILabel.Font));
	}
	label.InvalidateMeasure();
}
else
{
	CoreFoundation.DispatchQueue.MainQueue.DispatchAsync(() =>
	{
		platformLabel.AttributedText = new NSAttributedString(text, attr, ref nsError);
		if (label.Handler is ILabelHandler labelHandler)
		{
			labelHandler.UpdateValue(nameof(ILabel.TextColor));
			labelHandler.UpdateValue(nameof(ILabel.Font));
		}
		label.InvalidateMeasure();
	});
}
```

The list view/collection view with the HTML label looks right, but the app crashes when using the collection view
Screenshot 2024-12-14 at 00 59 02

**Comment by kubaflo** [comment]
> <Grid RowDefinitions="*,*">
>     <CollectionView>
>         <CollectionView.ItemsSource>
>             <x:Array Type="{x:Type x:String}">
>                 <x:String>Item1</x:String>
>                 <x:String>Item1</x:String>
>                 <x:String>Item1</x:String>
>             </x:Array>
>         </CollectionView.ItemsSource>
>         <CollectionView.ItemTemplate>
>             <DataTemplate>
>                 <VerticalStackLayout>
>                     <Label Text="Hello"/>
>                     <Label Text="{Binding .}"
>                             TextType="Html"/>
>                 </VerticalStackLayout>
>             </DataTemplate>
>         </CollectionView.ItemTemplate>
>     </CollectionView>
> 
>     <StackLayout Grid.Row="1">
>         <BindableLayout.ItemsSource>
>             <x:Array Type="{x:Type x:String}">
>                 <x:String>Item1</x:String>
>                 <x:String>Item1</x:String>
>                 <x:String>Item1</x:String>
>             </x:Array>
>         </BindableLayout.ItemsSource>
>         <BindableLayout.ItemTemplate>
>             <DataTemplate>
>                 <VerticalStackLayout>
>                     <Label Text="Hello"/>
>                     <Label Text="{Binding .}"
>                             TextType="Html"/>
>                 </VerticalStackLayout>
>             </DataTemplate>
>         </BindableLayout.ItemTemplate>
>     </StackLayout>
> </Grid>

I tested and this is fixed with this PR: https://github.com/dotnet/maui/pull/25664 But, I believe @albyrock87 divided it into smaller ones

File: src/Core/src/Platform/iOS/LabelExtensions.cs (hunk 1 above)
Comment (mattleibow) [reply src/Core/src/Platform/iOS/LabelExtensions.cs:91]: Maybe use a local function to avoid code duplication.

File: src/Controls/src/Core/Label/Label.iOS.cs [hunk 3]
```diff
@@ -38,13 +38,6 @@ public static void MapMaxLines(ILabelHandler handler, Label label)
 
 		static void MapFormatting(ILabelHandler handler, Label label)
```
Comment (mattleibow) [inline src/Controls/src/Core/Label/Label.iOS.cs:39]: I feel like I wrote this code and overengineered this. It appears there is just 1 usage of the MapFormatting method, and it was already weird. Maybe this should just be merged with the MapText or UpdateText?

File: src/Core/src/Platform/iOS/LabelExtensions.cs (hunk 1 above)
Comment (mattleibow) [reply src/Core/src/Platform/iOS/LabelExtensions.cs:91]: Will the async cause issues because that would be unexpected? Will DispatchSync work/have issues/locking?

File: src/Core/src/Platform/iOS/LabelExtensions.cs [hunk 4]
```diff
@@ -88,9 +88,16 @@ internal static void UpdateTextHtml(this UILabel platformLabel, ILabel label)
...
-			platformLabel.AttributedText = new NSAttributedString(text, attr, ref nsError);
-#pragma warning restore CS8601
+			CoreFoundation.DispatchQueue.MainQueue.DispatchAsync(() =>
+			{
+				platformLabel.AttributedText = new NSAttributedString(text, attr, ref nsError);
+				if (label.Handler is ILabelHandler labelHandler)
+				{
+					labelHandler.UpdateValue(nameof(ILabel.TextColor));
+					labelHandler.UpdateValue(nameof(ILabel.Font));
+				}
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/LabelExtensions.cs:98]: Not sure if using handlers here is expected... Not sure if that is bad or good, but in my mind all the handler things happen in the handler or close to it. This is a few methods away now so may be surprising.

**Review by mattleibow — CHANGES_REQUESTED** [review]
Added some comment, but I just want to check. How do we know this is on a background thread? All UIKit operations are on a main thread - in fact, all of our handlers are on a main thread.

Something has gone horribly wrong if a handler mapper is updating the UI from a background thread. Where did it switch and why? 

I assume this only happens in CV, so this may be some weird case where the CV is moving to a background thread... to update the UI? Feels very sus.

**Comment by jfversluis** [comment]
@kubaflo some comments!

**Comment by kubaflo** [comment]
@mattleibow I've refactored a bit

**Comment by mattleibow** [comment]
@kubaflo I cant repro this with CV2:

image

But with CV1, the crash is:

> {Expected dequeued view to be returned to the collection view in preparation for display. When the collection view's data source is asked to provide a view for a given index path, ensure that a single view is dequeued and returned to the collection view. Avoid dequeuing views without a request from the collection view. For retrieving an existing view in the collection view, use -[UICollectionView cellForItemAtIndexPath:] or -[UICollectionView supplementaryViewForElementKind:atIndexPath:]. Dequeued view: <Microsoft_Maui_Controls_Handlers_Items_CarouselTemplatedCell: 0x103e3c750; baseClass = UICollectionViewCell; frame = (900 0; 300 300); layer = <CALayer: 0x60000050cea0>>; Collection view: <Microsoft_Maui_Controls_Handlers_Items_MauiCollectionView: 0x106cad400; baseClass = UICollectionView; frame = (0 0; 300 300); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x600000c81830>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x6000004ab3a0>; contentOffset: {1218, 0}; contentSize: {2700, 300}; adjustedContentInset: {0, 0, 0, 0}; layout: <Microsoft_Maui_Controls_Handlers_Items_CarouselViewLayout: 0x103d55c20>; dataSource: <Microsoft_Maui_Controls_Handlers_Items_CarouselViewController: 0x103d560b0>>}

**Comment by mattleibow** [comment]
Investigating this and the threrad is right, just sometimes (always) it crashes. It makes no sense. The thread, dispatch queue and operation queue are all the main ones.

This does not happen with CV2 so I am a bit annoyed as to why. It might be the layout differences.

File: src/Core/src/Platform/iOS/LabelExtensions.cs (hunk 1 above)
Comment (mattleibow) [reply src/Core/src/Platform/iOS/LabelExtensions.cs:91]: It is already on the main thread and main queue. Not sure why it fails. At this point the crash is more of an issue.

File: src/Core/src/Platform/iOS/LabelExtensions.cs (hunk 2 above)
Comment (mattleibow) [reply src/Core/src/Platform/iOS/LabelExtensions.cs:97]: Yeah, this is basically a Post for android. Puts it at the top of the queue - after the layout has run.

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
I moved the dispatch into Controls where the rest of the HTML things are done. One day (in my dreams) we are going to have a separate HTML label and I can just delete everything.

But for now, this is really strage.

I could only repro the crash with CV1, but who knows... So this should now be safe for CV1 and CV2. The dispatch is not abou threads or queues but rather ordering or maybe something is happening in the string init that is messing with the layout or the containing animation.

Regardless, this should be safe to merge as it is just a "post the update for after the layout".

**Comment by mattleibow** [comment]
Running UI tests because I want to make sure nothing else is weird.

**Review by mattleibow — APPROVED** [review]
