### PR TITLE
Fix `DisplayAlert` to properly pass the `cancel` parameter to `DisplayAlertAsync`

### LINKED ISSUE #31473: Page.DisplayAlert(title, message, accept, cancel, flowDirection) is causing ArgumentNullException
### Description

`Page.DisplayAlert(string title, string message, string accept, string cancel, FlowDirection flowDirection)` is causing an ArgumentNullException when using maui 10 preview 7.

### Steps to Reproduce

1. Call Page.DisplayAlert(string title, string message, string accept, string cancel, FlowDirection flowDirection)
2. Experience ArgumentNullEception

### Link to public reproduction project repository

_No response_

### Version with bug

10.0.0-preview.7

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.100 SR10

### Affected platforms

iOS, Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by thisisthekap**
### Description of Change

Fixed ArgumentNullException in `Page.DisplayAlert(string title, string message, string accept, string cancel, FlowDirection flowDirection)`.

### Issues Fixed

Fixes #31473

### CODE REVIEW

File: src/Controls/src/Core/Page/Page.cs [hunk 1]
```diff
@@ -350,7 +350,7 @@ public Task DisplayAlert(string title, string message, string cancel, FlowDirect
 		/// <inheritdoc cref="DisplayAlertAsync(string, string, string, string, FlowDirection)"/>
 		[Obsolete("Use DisplayAlertAsync instead")]
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Page/Page.cs:351]: A quick note, This is an **[Obsolete]** method marked for removal. Users are explicitly directed to use `DisplayAlertAsync` instead, so, the change fixes a bug in code that should ideally not be used.

**Review by jfversluis — APPROVED** [review]

File: src/Controls/src/Core/Page/Page.cs (hunk 1 above)
Comment (thisisthekap) [reply src/Controls/src/Core/Page/Page.cs:351]: I am aware that this method is marked for removal. But as it is used (e.g. by https://github.com/PrismLibrary/Prism), we need to make sure that the method works properly.
