### PR TITLE
Fix some Layout update bugs

### LINKED ISSUE #2196: [Bug] [HotReload] Removing all or the last view in a layout does not refresh the tree
### Description

If I have a layout with some elements in and the remove them one by one in xaml, they disappear - except for the last one. I can also see this when I delete everything, the LVT does not refresh.

They disappear for the app and a refresh of the tree corrects it.

Not sure if this is our bad code or something missing in the IDE? @drasticactions 

### Steps to Reproduce

```xaml
<Grid>
    <Label Text="One" />
    <Label Text="Two" />
</Grid>
```

Delete both labels and save. The LVT should not update.

### Screenshots

not-cleaning

### LINKED ISSUE #2198: [Bug] Adding views in HR does not respect index and appends
### Description

Inserting a view in a layout appends it on the UI, but seems to be correct in the LVT.

### Screenshots

insert-order

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

This PR ensures that clearing a layout using `Clear()` calls `VisualDiagnostics.OnChildRemoved` for each item. It also make sure to use the Insert operation when inserting views.

 - Fixes #2196
 - Fixes #2198

### Additions made ###

More tests.

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

File: src/Controls/src/Core/Layout/Layout.cs [hunk 1]
```diff
@@ -101,18 +101,21 @@ public virtual void Add(IView child)
...
+				VisualDiagnostics.OnChildAdded(this, element, _children.Count - 1);
 			}
 
 			AddToHandler(_children.Count, child);
 		}
 
 		public void Clear()
 		{
-			foreach (var child in this)
+			for (var index = Count - 1; index >= 0; index--)
```
Comment (mattleibow) [inline src/Controls/src/Core/Layout/Layout.cs:112]: DO the remove in reverse so as to avoid potential shuffling.

File: src/Controls/src/Core/Xaml/Diagnostics/VisualDiagnostics.cs [hunk 2]
```diff
@@ -19,7 +18,11 @@ public static void RegisterSourceInfo(object target, Uri uri, int lineNumber, in
 				sourceInfos.Add(target, new XamlSourceInfo(uri, lineNumber, linePosition));
 		}
 
-		internal static void OnChildAdded(Element parent, Element child)
+		[EditorBrowsable(EditorBrowsableState.Never)]
+		public static XamlSourceInfo GetXamlSourceInfo(object obj) =>
+			sourceInfos.TryGetValue(obj, out var sourceinfo) ? sourceinfo : null;
+
+		public static void OnChildAdded(Element parent, Element child)
```
Comment (mattleibow) [inline src/Controls/src/Core/Xaml/Diagnostics/VisualDiagnostics.cs:25]: @Redth I made the add and remove public. No more reflection!

File: src/Controls/src/Core/Layout/Layout.cs [hunk 3]
```diff
@@ -96,23 +96,27 @@ public virtual void Add(IView child)
...
 
 			if (child is Element element)
 			{
 				element.Parent = this;
-				VisualDiagnostics.OnChildAdded(this, element);
+				VisualDiagnostics.OnChildAdded(this, element, index);
 			}
 
-			AddToHandler(_children.Count, child);
+			AddToHandler(index, child);
```
Comment (mattleibow) [inline src/Controls/src/Core/Layout/Layout.cs:108]: @hartez I am not sure which is correct. Previously, adding the first item would report that it added at index 1, which is incorrect I think?

Actually, all the adds would be one ahead, so the second view would be position 2 - or 3rd...

File: src/Controls/src/Core/Layout/Layout.cs [hunk 4]
```diff
@@ -147,7 +151,7 @@ public void Insert(int index, IView child)
 				VisualDiagnostics.OnChildAdded(this, element);
 			}
 
-			AddToHandler(index, child);
+			InsertIntoHandler(index, child);
```
Comment (mattleibow) [inline src/Controls/src/Core/Layout/Layout.cs:154]: Fix for #2198

File: src/Controls/src/Core/Layout/Layout.cs [hunk 5]
```diff
@@ -96,23 +96,27 @@ public virtual void Add(IView child)
...
 		public void Clear()
 		{
-			foreach (var child in this)
+			for (var index = Count - 1; index >= 0; index--)
 			{
-				if (child is Element element)
+				if (this[index] is Element element)
+				{
 					element.Parent = null;
+					VisualDiagnostics.OnChildRemoved(this, element, index);
```
Comment (mattleibow) [inline src/Controls/src/Core/Layout/Layout.cs:118]: Fixes  #2196

File: src/Controls/src/Core/Layout/Layout.cs (hunk 3 above)
Comment (hartez) [reply src/Controls/src/Core/Layout/Layout.cs:108]: Your version here is correct.

**Review by hartez — APPROVED** [review]
