### PR TITLE
[Windows] Implement SearchBar CancelButtonColor on Windows

### LINKED ISSUE #13507: Setting SearchBar CancelButtonColor doesn't work on Windows
### Description

If I set the CancelButtonColor on a SearchBar element to a different color like Yellow it works as expected on Android, as seen here (red box added for emphasis):

image

But on Windows the color doesn't get applied, as seen here (red box added for emphasis):

image

I found this while working on #11948, I'd like this issue to be assigned to me as well.

### Steps to Reproduce

1. Create a File > New .NET MAUI App (reproes with either .NET 6 or .NET 7)
2. Open MainPage.xaml, and add a SearchBar element like so:

`<SearchBar CancelButtonColor="Yellow" WidthRequest="200" Text="Foo" />`

3. Run the app in Windows
4. Set focus to the SearchBar and inspect the color of the cancel button (the 'x')

Expected: It's Yellow
Actual: It's the default (usually black)

### Link to public reproduction project repository

Not Needed

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Implement SearchBar **CancelButtonColor** on Windows. Checking new issues and adding label, I've seen that 13507 happens basically because it's not implemented. This PR implement the changes in the CancelButtonColor proprerty.
image

To validate the changes cacn use the SearchBar sample from the .NET MAUI Gallery or the added tests.
image

### Issues Fixed

Fixes #13507

### CODE REVIEW

File: src/Core/src/Platform/Windows/SearchBarExtensions.cs [hunk 1]
```diff
@@ -132,5 +132,35 @@ public static void UpdateIsTextPredictionEnabled(this AutoSuggestBox platformCon
...
+		internal static void UpdateCancelButtonColor(this AutoSuggestBox platformControl, ISearchBar searchBar)
+		{
+			var cancelButton = platformControl.GetDescendantByName<Button>("DeleteButton");
+
+			if (cancelButton == null)
+				return;
+
+			var cancelButtonColor = searchBar.CancelButtonColor?.ToPlatform();
+
+			if (cancelButtonColor == null)
```
Comment (PureWeen) [inline src/Core/src/Platform/Windows/SearchBarExtensions.cs:152]: `is`

File: src/Core/src/Platform/Windows/SearchBarExtensions.cs [hunk 2]
```diff
@@ -132,5 +132,35 @@ public static void UpdateIsTextPredictionEnabled(this AutoSuggestBox platformCon
...
+			{
+				cancelButton.Resources.RemoveKeys(CancelButtonColorKeys);
+				cancelButton.Foreground = null;
```
Comment (PureWeen) [inline src/Core/src/Platform/Windows/SearchBarExtensions.cs:155]: Can we create a version of `ButtonExtensions.UpdateTextColor` that takes the resourcekeys as a parameter?  It seems like we're duplicating the logic here that we already have there. 

I also noticed that in `ButtonExtensions.UpdateTextColor`  we clear the property whereas here it's setting foreground to null. 

I'm guessing the `ButtonExtensions` one is more correct?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Windows/SearchBarExtensions.cs [hunk 3]
```diff
@@ -132,5 +132,35 @@ public static void UpdateIsTextPredictionEnabled(this AutoSuggestBox platformCon
...
+			"TextControlButtonForeground",
+			"TextControlButtonForegroundPointerOver",
+			"TextControlButtonForegroundPressed",
+		};
+
+		internal static void UpdateCancelButtonColor(this AutoSuggestBox platformControl, ISearchBar searchBar)
+		{
+			var cancelButton = platformControl.GetDescendantByName<Button>("DeleteButton");
+
+			if (cancelButton == null)
```
Comment (mandel-macaque) [inline src/Core/src/Platform/Windows/SearchBarExtensions.cs:147]:
```suggestion
			if (cancelButton is null)
```

File: src/Core/src/Platform/Windows/SearchBarExtensions.cs (hunk 1 above)
Comment (mandel-macaque) [inline src/Core/src/Platform/Windows/SearchBarExtensions.cs:152]:
```suggestion
			if (cancelButtonColor is null)
```

**Review by mandel-macaque — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Windows/SearchBarExtensions.cs (hunk 2 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Windows/SearchBarExtensions.cs]: Is a good idea. I have created a new extension method in `ButtonExtensions `and reuse it with the Button and in this case with the SearchBar clear button.

File: src/Core/src/Platform/Windows/ButtonExtensions.cs [hunk 4]
```diff
@@ -107,27 +107,32 @@ public static void UpdateTextColor(this ButtonBase platformButton, ITextStyle bu
 		}
 
 		public static void UpdateTextColor(this ButtonBase platformButton, Color textColor)
+		{
+			platformButton.UpdateTextColor(textColor, TextColorResourceKeys);
+		}
+
+		public static void UpdateTextColor(this ButtonBase platformButton, Color textColor, string[] resourceKeys)
```
Comment (PureWeen) [inline src/Core/src/Platform/Windows/ButtonExtensions.cs:114]: Can we leave this `internal` ? I don't think we need to make this public.

**Review by PureWeen — DISMISSED** [review]

File: src/Core/src/Platform/Windows/ButtonExtensions.cs (hunk 4 above)
Comment (jsuarezruiz) [reply src/Core/src/Platform/Windows/ButtonExtensions.cs]: Changed, could you review it again?. Thnx!

**Review by mandel-macaque — APPROVED** [review]

File: src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.Windows.cs [hunk 5]
```diff
@@ -8,6 +8,34 @@ namespace Microsoft.Maui.DeviceTests
...
+			};
+
+			searchBar.Focus();
+
+			await InvokeOnMainThreadAsync(async () =>
+			{
+				var searchBarHandler = CreateHandler(searchBar);
+				await searchBarHandler.PlatformView.AttachAndRun(async () =>
+				{
+					await AssertionExtensions.Wait(() => searchBarHandler.PlatformView.FocusState != UI.Xaml.FocusState.Unfocused);
```
Comment (rachelkang) [inline src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.Windows.cs:32]: hmm... what is the reason for checking this?

**Review by rachelkang — APPROVED** [review]
Had a small question about a line in the tests, but otherwise LGTM! happy colors :)

File: src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.Windows.cs (hunk 5 above)
Comment (jsuarezruiz) [reply src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.Windows.cs:32]: The `CancelButton` only appears when the SearchBar has text and the focus. For that reason, here, we wait until be sure that the native control is focused.

**Review by rmarinho — APPROVED** [review]

**Comment by jsuarezruiz** [comment]
@PureWeen Could I get your feedback here?. Thanks!

**Review by rmarinho — APPROVED** [review]

**Comment by MSLukeWest** [comment]
@rmarinho You should also remove this line, or at least the reference to this now closed issue:

https://github.com/dotnet/maui/blob/50f9024081aa65c6b65bdde20c68bdb4bcd53e16/src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.cs#L125
