### PR TITLE
CollectionView Items display issue when Header is resized on iOS

### LINKED ISSUE #12429: CollectionView Items display issue when Header is resized on iOS
### Description

When the size of a CollectionView Header increases, it's displayed on top of Items, on iOS.
No issue on Android.

In this example, when clicking on the Add button, a row is added to the Header of the CollectionView (above the line), in order to increase the size of the Header. On Android, the Items (below the row) move down accordingly. On iOS, the Header size increases and is displayed on top of Items.

 

### Steps to Reproduce

1. Create a Maui app
2. Add a CollectionView with HeaderTemplate
3. Increase size of Header and observe what happens

### Link to public reproduction project repository

https://github.com/tranb3r/Issues/tree/main/MauiAppCollectionViewHeaderResize

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1

### Did you find any workaround?

no

### Relevant log output

_No response_

### LINKED ISSUE #20538: On iOS, CollectionView Header size changed causes overlap
### Description

If I initialize a CollectionView Header, and then it gets bigger, the header content overlaps the CollectionView items on iOS. Works fine on Android. 

On iOS, in the CollectionView Header, if I have Label(s) and their default text fits on a single line, but then I populate these Labels with text that takes up two or more lines and the text needs to wrap, the header does not resize and the header overlaps the items.

### Steps to Reproduce

1. Create a new MAUI App
2. Add a CollectionView with a Header that has a VerticalStackLayout and labels inside it that are named. Make the default values for the Labels in the header something short, I used "--"
3. Have a button that on Clicked changes the Label text with something that will wrap.
4. Observe on iOS that the Label text will overlap the items. On Android it works as expected.

image

### Link to public reproduction project repository

https://github.com/billreiss/CollectionViewOverlappingIssue

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2

### Did you find any workaround?

No I have tried several things, I haven't found anything that works.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/20538
Fixes https://github.com/dotnet/maui/issues/12429

|Before|After|
|--|--|
|<video src="https://github.com/dotnet/maui/assets/42434498/44facc31-dc07-42ee-a834-c1dd9f603254" width="300px"/>|<video src="https://github.com/dotnet/maui/assets/42434498/566be397-8460-401a-81b3-b0435f3ba263" width="300px"/>|

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs [hunk 1]
```diff
@@ -46,6 +46,16 @@ protected override void Dispose(bool disposing)
 					_footerViewFormsElement.MeasureInvalidated -= OnFormsElementMeasureInvalidated;
 				}
 
+				if (_headerUIView is MauiView hv)
+				{
+					hv.LayoutChanged += HeaderView_LayoutChanged;
```
Comment (PureWeen) [inline src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs:51]: What if you subscribe to SizeChanged on the header/footer xplat elements?

Comment (kubaflo) [reply src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs]: When I try to do the following: 
`_headerViewFormsElement.SizeChanged += _headerViewFormsElement_SizeChanged;`

`_headerViewFormsElement_SizeChanged` never triggers

File: src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs [hunk 2]
```diff
@@ -239,5 +260,15 @@ internal void UpdateLayoutMeasurements()
 			if (_footerViewFormsElement != null)
 				HandleFormsElementMeasureInvalidated(_footerViewFormsElement);
 		}
+
+		private void HeaderView_LayoutChanged(object sender, EventArgs e)
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs:264]:
```suggestion
		void HeaderViewLayoutChanged(object sender, EventArgs e)
```

We don't use the private and try avoid using _ on method naming

Comment (kubaflo) [reply src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs]: Fixed

File: src/Core/src/Platform/iOS/MauiView.cs [hunk 3]
```diff
@@ -174,5 +175,13 @@ public override void MovedToWindow()
 			base.MovedToWindow();
 			_movedToWindow?.Invoke(this, EventArgs.Empty);
 		}
+
+		[UnconditionalSuppressMessage("Memory", "MEM0001", Justification = IUIViewLifeCycleEvents.UnconditionalSuppressMessage)]
+		internal event EventHandler? LayoutChanged;
```
[the remark this answers is not in the document]
Comment (kubaflo) [reply src/Core/src/Platform/iOS/MauiView.cs:180]: This event needs to be internal 
Screenshot 2024-06-13 at 01 30 53

[the remark this answers is not in the document]
Comment (mattleibow) [reply src/Core/src/Platform/iOS/MauiView.cs:180]: I think the "proxy" event for `MovedToWindow` is just because it is an explicit interface event.

File: src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs [hunk 4]
```diff
@@ -46,6 +46,16 @@ protected override void Dispose(bool disposing)
 					_footerViewFormsElement.MeasureInvalidated -= OnFormsElementMeasureInvalidated;
 				}
 
+				if (_headerUIView is MauiView hv)
+				{
+					hv.LayoutChanged -= HeaderViewLayoutChanged;
+				}
```
Comment (mattleibow) [inline src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs:52]: If we are now watching the actual method that is doing layout, do we still need the original `_footerViewFormsElement.MeasureInvalidated`? The code seems to end up calling the same `HandleFormsElementMeasureInvalidated` method.

File: src/Core/src/Platform/iOS/MauiView.cs [hunk 5]
```diff
@@ -134,6 +134,7 @@ public override void LayoutSubviews()
 			}
 
 			CrossPlatformArrange(bounds);
+			OnLayoutChanged();
```
Comment (mattleibow) [inline src/Core/src/Platform/iOS/MauiView.cs:137]: Maybe this should be renamed to match the method. Also, no need to have the method, just invoke the event directly. Maybe use a name of `ArrangingSubviews` or even just `OnLayoutSubviews` since it is internal. I see `MovedToWindow` got away with the same name because it was an explicit interface member.

**Review by mattleibow — COMMENTED** [review]
I am just wondering about the fact that now we have 2 events that are triggering the layout code when the first did not work. Is there a reason for both?

File: src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs (hunk 4 above)
Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs:52]: IS grabbing the element for footer and header not the all view right? some still need for each one .

File: src/Core/src/Platform/iOS/MauiView.cs (hunk 5 above)
Comment (kubaflo) [reply src/Core/src/Platform/iOS/MauiView.cs]: I changed to invoke the event directly

**Review by PureWeen — CHANGES_REQUESTED** [review]
We should revisit if this is needed once we test on net9 with CollectionViewHandler2 and once we merge this PR https://github.com/dotnet/maui/pull/23052

**Comment by jsuarezruiz** [comment]
@kubaflo Could you rebase and fix the conflicts? Thanks in advance.

**Comment by kubaflo** [comment]
@jsuarezruiz Rui has cherry-picked commits from this PR to this PR: https://github.com/dotnet/maui/pull/25157

But I think we can keep the UT test in this PR. What do you think?

**Comment by kubaflo** [comment]
> We should revisit if this is needed once we test on net9 with CollectionViewHandler2 and once we merge this PR #23052

@PureWeen you were right!
But I think we can include the UI test from this PR. What do you think?

File: src/Core/src/Platform/iOS/MauiView.cs [hunk 6]
```diff
@@ -137,7 +137,7 @@ public override void LayoutSubviews()
 			}
 
 			CrossPlatformArrange(bounds);
-			OnLayoutChanged();
```
Comment (rmarinho) [inline src/Core/src/Platform/iOS/MauiView.cs:140]: Do we still need this change @kubaflo  or just the test?

Comment (kubaflo) [reply src/Core/src/Platform/iOS/MauiView.cs]: @rmarinho just the test. I forgot to remove this part. Fixed now :)

**Comment by kubaflo** [comment]
@rmarinho it turned out that I had to make some changes to fix it. So, it is not only a UI test now

**Comment by rmarinho** [comment]
Seems is failing for CV2

**Comment by kubaflo** [comment]
@rmarinho Luckily, it is only because the iOS screenshot need to be updated. Could you please /azp?

**Review by rmarinho — CHANGES_REQUESTED** [review]
Seems the tests are failing for CV2 HeaderShouldNotCollapseWithItems

**Comment by kubaflo** [comment]
@rmarinho hmm, locally it works well with the following change:
Screenshot 2024-12-19 at 14 52 52

Maybe let's try run tests again

**Comment by rmarinho** [comment]
> @rmarinho hmm, locally it works well with the following change: Screenshot 2024-12-19 at 14 52 52
> 
> Maybe let's try run tests again

Still failing. 
https://dev.azure.com/xamarin/public/_build/results?buildId=131698&view=ms.vss-test-web.build-test-results-tab&runId=3557296&resultId=100092&paneView=attachments

**Comment by kubaflo** [comment]
@rmarinho so this is actually not working on CV2. I will try to get to the bottom of why it doesn't work. But in the meantime can we merge this fix for cv1?

**Comment by kubaflo** [comment]
@rmarinho I've added `[FailsOnMacWhenRunningOnXamarinUITest("This is not working for CV2 yet")]`, so that a PR that fixes it for CV2 will only have to remove it

**Comment by kubaflo** [comment]
Hi @rmarinho! Could it be merged so I can proceed with this one? https://github.com/dotnet/maui/pull/27076

**Review by rmarinho — APPROVED** [review]
