### PR TITLE
iOS Keyboard Scrolling Improvements and UITests (not from fork)

### LINKED ISSUE #17559: iOS Keyboard Scrolling UITesting
It is important to add different scenarios to the UITests to confirm that the keyboard scrolling when clicking an entry or editor on iOS is working properly and help prevent regressions in the future.

Some important scenarios to test include the following:

- [ ] Scrolling when clicking entries in different positions of the screen.
- [ ] Scrolling when clicking editors in different positions of the screen.
- [ ] Click on a MauiCommunityToolkit-type popup and make sure the external scrolling interacts well with our scrolling.
- [ ] Click inside an entry and then pressing next to go into the next editor without closing the keyboard.
- [ ] Click inside an entry and then continuously going into other entries with the next button without closing the keyboard.
- [ ] Click into a Collectionview entry.
- [ ] Click into a tableview entry.
- [ ] Click into a listview entry.
- [ ] Multiple ScrollView hierarchy. 

It is also important to consider that all the scenarios above should be run in the following four different configurations as well since these affect the way scrolling occurs:
* Using iOS Large Titles with a scrollable page
* Not using iOS Large Titles with a scrollable page
* Using iOS Large Titles with a non-scrollable page
* Not using iOS Large Titles with a non-scrollable page

### LINKED ISSUE #17588: iOS Keyboard Scrolling - Entry Next Editor
### Description

If you click an entry in iOS, the keyboard comes up as expected. If you press the next button on the keyboard to go into the following editor, the screen does not scroll quite enough to see the carat in the editor.

### Steps to Reproduce

Set up the following xaml:

```xaml
<Grid RowDefinitions="100,100,100,100" RowSpacing="25">
        <Entry Placeholder="First Entry" AutomationId="Entry1" Background="lightgray" ReturnType="Next" Grid.Row="0"/>
        <Entry Placeholder="Second Entry" AutomationId="Entry2" Background="lightgray" ReturnType="Next" Grid.Row="1"/>
        <Entry Placeholder="Third Entry" AutomationId="Entry3" Background="lightgray" ReturnType="Next" Grid.Row="2"/>
        <Editor Placeholder="Editor" AutomationId="Editor" Background="lightgray" Grid.Row="3"/>
</Grid>
```

1. Click an entry.
2. After the keyboard comes up, press the next button on the keyboard until the editor is focused.
3. Observe the keyboard not coming up high enough.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #18354: iOS Keyboard Scrolling with Star-sized grid row
### Description

When you have a top level grid that has a row with the size of '*' and we click an entry or editor that requires the screen to scroll with the keyboard, the star sized row will expand and the entry or editor will not come up high enough. 

An example of the xaml for this is as follows:

```xaml
<Grid RowDefinitions="40,*,40,40, 40">
    <Button Grid.Row="0" Background="blue" Text="Print CollectionView Height" Pressed="Button_Pressed"/>

    <Button Grid.Row="2" Background="blue" Text="Print CollectionView Height" Pressed="Button_Pressed"/>

    <Editor x:Name="myEditor" Grid.Row="3" BackgroundColor="MediumSeaGreen" Placeholder="Send Chat" 
        PlaceholderColor="White" TextColor="White"/>

    <Button Grid.Row="4" Text="Fill collection"/>
</Grid>
```

It appears that the star sized row is absorbing the height of the safe area. If we add `IgnoreSafeArea="True"` to the top level grid, the star sized row is the expanded size the entire time (before and after scrolling) and the entry or editor will be scrolled to correctly.

https://github.com/dotnet/maui/assets/50846373/cbcfb45d-f1da-46d8-8d39-983ec821bfab

### Steps to Reproduce

1. Create a xaml page with a top level grid.
2. Add a row with the star size above an editor or entry towards the bottom of the page.
3. Deploy the app and click the entry or editor at the bottom of the page.
4. Observe that the height of the star-sized row becomes larger and the entry or editor does not come quite high enough.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

Adding `IgnoreSafeArea="True"` to the top level grid seems to fix the issue for now

### Relevant log output

_No response_

### LINKED ISSUE #19245: [iOS] Hardware keyboard in FormSheet disturbs content sizing
### Description

When using a FormSheet on iOS in combination with a hardware keyboard the content gets pushed down upon Entry focus. Seems like the contentsizing doesn't work properly in this situation. Tested on iPad 10th Generation in simulator.

ReproFormSheet

### Steps to Reproduce

1. Run the reproduction project on iPad 10th Generation in Simulator (landscape)
2. Make sure Hardware keyboard is toggled on in Simulator: (I/O > Keyboard > Connect Hardware Keyboard)
3. Focus the Entry field
4. Notice content gets pushed down

### Link to public reproduction project repository

https://github.com/Mittchel/FormSheetSample

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS17, iOS 16.4

### Did you find any workaround?

Didn't find a workaround yet, scrollview doesn't seem to help. Currently stepped away from FormSheets to mitigate the issue. 

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tj-devel709**
# Description of Change

Note: recreating [this PR](https://github.com/dotnet/maui/pull/16201) from a branch not in my fork for sake of UITests Issue.

### Grid with Star Row Resizing

When there is a grid at the top-level of the content page, and there is at least one star-sized row, the grid would resize when the keyboard came up. This was due to safe-area of the grid on the bottom no longer needing to size down for the bottom SafeAreaInset since the grid was raised higher than the bottom of the device. To handle this, logic was added so that we can call the scrolling code again after the grid (or other view) expands. 

<details> 
<summary> 

#### Grid with Star Row Resizing Example (click me!) 

</summary>

| Before | After |
| -- | -- |
| <video width="300" src="https://github.com/dotnet/maui/assets/50846373/62fa0604-a2b8-4dce-88c4-ac2fb8d0556a"> | <video width="300" src="https://github.com/dotnet/maui/assets/50846373/1813b511-083d-46eb-a8ad-f1016da95fe3"> |

```xaml
    <Grid RowDefinitions="40,*,40,40, 40">
        <Button Grid.Row="0" Background="blue" Text="Print CollectionView Height"/>

        <TableView Background="lightblue" x:Name="ColView" Grid.Row="1"/>

        <Button Grid.Row="2" Background="blue" Text="Print CollectionView Height"/>
        <Editor
            x:Name="myEditor"
            Grid.Row="3"
            BackgroundColor="MediumSeaGreen"
            Placeholder="Send Chat"
            PlaceholderColor="White"
            TextColor="White"/>

        <Button Grid.Row="4" Text="Fill collection"/>
    </Grid>
```

</details> 

---

### Scrolling animation glitch

There was a small glitch in the scrolling animation. While we are computing the animation speed the keyboard will use to come up, the screen would sometimes scroll a little after it making it a tad jumpy. Since we no longer need the automatic delay in the `AdjustPositionDebounce` method since the cursor location logic is moved to later in the process, I found that this delay was causing the small jump in the animation. 

<details> 
<summary> 

#### Scrolling animation glitch Example (click me!)

</summary>

| After |
| -- | 
 | <video width="300" src="https://github.com/dotnet/maui/assets/50846373/d379b12a-68ef-4dfa-ae50-aa31162db4f0"> |

</details> 

---

### Next Return Key fix

When we have an entry with the ReturnType of 'Next' and we press that next button to go into an editor, the editor would sometimes not come up high enough. This was due to the additional AccessoryView that is added to the keyboard for editors in Maui. When we hit this scenario of switching between an editor and entry, we should recalculate to see if the keyboard changed sizes.

---

# UITests

 Testing the iOS Keyboard scenarios is difficult as there are many different scenarios. I created some UITests that can help keep track of the verification that scrolling is happening correctly. 

It is important to note that most of the iOS Scrolling UITests are run with four different configurations:
* Using iOS Large Titles with a scrollable page
* Not using iOS Large Titles with a scrollable page
* Using iOS Large Titles with a non-scrollable page
* Not using iOS Large Titles with a non-scrollable page

<details> 
<summary> 

#### Example of the Large Titles and Small Titles respectively (click me!) 

</summary>

| Large Titles | Small Titles |
| -- | -- |
|  |  |

</details> 

<details> 
<summary> 

#### Testing multiple editors in different locations (click me!) 

</summary>

https://github.com/dotnet/maui/assets/50846373/7a76b9a7-3b5d-4575-8b96-3b3524bd20b0

</details> 

<details> 
<summary> 

#### Testing multiple entries in different locations (click me!)

</summary>

https://github.com/dotnet/maui/assets/50846373/09fa1966-f7dd-4392-b56f-5408e9816e5e

</details> 

<details> 
<summary>

#### Testing entry next button to editor (click me!)

</summary>

https://github.com/dotnet/maui/assets/50846373/1191659d-a4a3-4aba-9bb7-6894b6656dba

</details> 

<details> 
<summary> 

#### Testing grid with star row resizing (click me!) 

</summary>

https://github.com/dotnet/maui/assets/50846373/2d9f1354-8d83-4c1b-a508-7fdabe0db391

</details> 

### Issues Fixed

Fixes #17588
Fixes #17559
Fixes #18354
Fixes #19245

### CODE REVIEW

**Comment by MalmoIt** [comment]
Any progress on this?

File: src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs [hunk 1]
```diff
@@ -608,6 +694,35 @@ internal static nfloat FindKeyboardHeight()
 		return window.Frame.Height - kbSize.Height;
 	}
 
+	// In the case we have PrefersLargeTitles set to true, the UINavigationBar
+	// has additional height that collapses when scrolling. Try to remove
+	// this collapsable height difference from the calculated move distance.
+	static nfloat AdjustForLargeTitles(nfloat move, UIScrollView superScrollView, UINavigationController navController)
+	{
+		var navBarCollapsedHeight = 44;
+		var minPageMoveToCollapseNavBar = 52;
```
Comment (tj-devel709) [inline src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs:703]: I wonder if these values can change with the device - probably better to see if I can get values instead of hard coding

**Comment by tj-devel709** [comment]
> Any progress on this?

Back on it now :)

File: src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs [hunk 2]
```diff
@@ -627,6 +696,39 @@ internal static nfloat FindKeyboardHeight()
...
+	// In the case we have PrefersLargeTitles set to true, the UINavigationBar
+	// has additional height that collapses when scrolling. Try to remove
+	// this collapsable height difference from the calculated move distance.
+	static nfloat AdjustForLargeTitles(nfloat move, UIScrollView superScrollView, UINavigationController navController)
+	{
+		// These values are not publicly available but can be tested.
+		// It is possible that these can change in the future.
+		var navBarCollapsedHeight = 44;
+		var navBarExpandedHeight = 96;
+
```
Comment (tj-devel709) [inline src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs:708]: See what the Large Title Navigation bar looks like in horizontal

Comment (tj-devel709) [reply src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs]: Fixed in horizontal mode as well as for ipad!

**Comment by andyzukunft** [comment]
Is this accessible with a nightly nuget?

**Review by emaf — CHANGES_REQUESTED** [review]
I've been testing how swift behaves and it seems to scroll till the bottom of the control instead of the cursor position. Also, when the keyboard is up, you can't keep scrolling till the end of the scroll view so in some cases your text can end up under the keyboard.

Keyboard over text when editor is the last item + scrolling to the cursor position instead of end of the control:
<video width="300" src="https://github.com/dotnet/maui/assets/3286258/b5feed00-849f-48bf-ac24-e1a6d1f55100">

Can't scroll to last item when keyboard is opened because one of the first ones:
<video width="300" src="https://github.com/dotnet/maui/assets/3286258/86f1ee2c-daba-4c4a-9141-f5b13afbe5c1
">

Swift sample: 
<video width="300" src="https://github.com/dotnet/maui/assets/3286258/49c51270-738a-4528-908b-6b1d83a5d60a">

**Review by emaf — DISMISSED** [review]
I'm approving after chatting with @PureWeen and @tj-devel709. Both issues I mentioned are known and will be tackled in a separate PR as this one contains great fixes and improvements we want to get merged!

File: src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs [hunk 3]
```diff
@@ -276,17 +277,48 @@ internal static async Task AdjustPositionDebounce()
 
 		var entranceCount = DebounceCount;
 
-		await Task.Delay(10);
+		// If we are going to a new view that has an InputAccessoryView
```
Comment (PureWeen) [inline src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs:280]: If I'm following this code correctly it looks like we've eliminated the `Task.Delay(10)` from the original code. Is that intentional?  All of the added delays are inside `if` statements so there's a possibility that we'll just get directly to the `AdjustPosition` without any debouncing happening.

**Review by PureWeen — CHANGES_REQUESTED** [review]

**Comment by NielsKnaap** [comment]
@tj-devel709 is there any progress on this PR?

File: src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs (hunk 3 above)
Comment (tj-devel709) [reply src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs:280]: Hey @PureWeen, sorry! Yeah I did remove the Task.Delay that happened every time. It was not consistent (some times things would need a longer delay - over 10 ms for editors some times). I tried upping it for everything, but also realized that removing this delay caused the scrolling animation with the keyboard to be much smoother. Also without it, there are usually two calls to the AdjustPosition (one from the entry/editor being focused and one from the keyboard coming up), but the scrolling requested for each work together. I instead changed this "always delay" to only be delays for things that need it like changing InputAccessoryViews.

**Review by PureWeen — APPROVED** [review]

**Comment by rjhind** [comment]
Will this make it in to the next bug fix release of Maui?
