### PR TITLE
Correctly expand rows/columns when grid padding

### LINKED ISSUE #16815: [regression/8.0.0-preview.6.8686] Grid with padding column misalignment
### Description

When a grid has left/right padding set and column definition is set to *,Auto, if the content of the * column is close to the end of the column, the column set to 'Auto' is misaligned to the left. If the grid is set with no left/right paddings, alignments stay correct. See the attached video which shows the issue.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp3.MainPage">

    <ScrollView>
        <VerticalStackLayout >
            <!-- Notice the left and right paddings are set -->
            <Grid Padding="20,0,20,0">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="Auto"/>
                </Grid.ColumnDefinitions>
                <!-- If the text lenght is not long enough, alignment is correct -->
                <Label
                    Grid.Column="0"
                    Text="This text is OK"
                    HorizontalTextAlignment="Start"
                    HorizontalOptions="Start"
                    VerticalTextAlignment="Center"
                    VerticalOptions="Center"
                    FontSize="15"/>
                <Image
                    WidthRequest="40"
                    HeightRequest="40"
                    Source="dotnet_bot.png"
                    BackgroundColor="Olive"
                    Grid.Column="1"
                    HorizontalOptions="End"/>
            </Grid>
            <!-- Notice the left and right paddings are set -->
            <Grid Padding="20,0,20,0"
                BackgroundColor="AliceBlue">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="Auto"/>
                </Grid.ColumnDefinitions>
                <!-- Modify the text length until the point where the alignment of the 'Auto' column is broken. Will depend on the device screen width -->
                <Label
                    BackgroundColor="Violet"
                    Grid.Column="0"
                    Text="Modify the text length until the point "
                    HorizontalTextAlignment="Start"
                    HorizontalOptions="Start"
                    VerticalTextAlignment="Center"
                    VerticalOptions="Center"
                    FontSize="15"/>
                <Image
                    WidthRequest="40"
                    HeightRequest="40"
                    Source="dotnet_bot.png"
                    BackgroundColor="Olive"
                    Grid.Column="1"
                    HorizontalOptions="End"/>
            </Grid>
            <!--The padding of the grid is 0, the issue is not reproducible here-->
            <Grid Padding="0,20,0,20"
                BackgroundColor="AliceBlue">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="Auto"/>
                </Grid.ColumnDefinitions>
                <!-- Modify the text length to see that the alignment of the 'Auto' column stays correct. -->
                <Label
                    BackgroundColor="Violet"
                    Grid.Column="0"
                    Text="Modify the text length to see that the align"
                    HorizontalTextAlignment="Start"
                    HorizontalOptions="Start"
                    VerticalTextAlignment="Center"
                    VerticalOptions="Center"
                    FontSize="15"/>
                <Image
                    WidthRequest="40"
                    HeightRequest="40"
                    Source="dotnet_bot.png"
                    BackgroundColor="Olive"
                    Grid.Column="1"
                    HorizontalOptions="End"/>
            </Grid>
        </VerticalStackLayout>
    </ScrollView>
</ContentPage>
```

https://github.com/dotnet/maui/assets/86722749/d892a57b-7182-4d31-a4a9-9c32b60a68c8

### Steps to Reproduce

1. Create a grid with left/right padding and two columns, "*, Auto". Add a label in the '*' column. Fix the size of the element in the 'Auto' column. 
2. Depending on the size of the screen, modify the text so it 'barely' fits in a single row (see attached video).

Expected result: the content in the 'Auto' column is aligned to the 'end'.
Current result: the content in the 'Auto' column is misaligned and slightly moved to the left.

### Link to public reproduction project repository

https://github.com/JordiCasas/GridPaddingIssue

### Version with bug

[8.0.0-preview.6.8686](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.6.8686)

### Is this a regression from previous behavior?

Yes, this used to work in MAUI

### Last version that worked well

[8.0.0-preview.5.8529](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.5.8529)

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #18160: [regression/7.0.0] Label measuring seems to break the parent layout width
### Description

The Red Grid In layout below should Fill horizontally but in some scenarios it leaves extra space to the right as can be seen in the image below.

The Yellow Label seems to be the problem since the Red Grid's width kind of follows the Label's width affecting the rest of its children (the Label should also Fill horizontally):

```
    <Grid
        Padding="20"
        BackgroundColor="Blue">

        <Grid BackgroundColor="Red" Padding="5">
            <Label
                BackgroundColor="Yellow"
                Text="This label should always fill"
                FontSize="28"
                HorizontalOptions="Fill"
            />

            <Button Text="Fill Button" VerticalOptions="Center" />
        </Grid>
    </Grid>
```

This is how it looks in an iPhone 14 Pro Max where it can be seen that the right padding is bigger than the left one:
Simulator Screenshot - iPhone 14 Pro Max - 2023-10-18 at 18 54 55

This is how it behaves when changing the label text using the hot reload:
issue5 1

### Steps to Reproduce

1. Open the linked project
2. Run on iPhone 14 Pro Max

Reproducing in other iOS and Android devices can be easily done by changing the label text length using the hot reload as shown in the gif above.

### Link to public reproduction project repository

https://github.com/dirivero/MauiMeasuringIssue

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

iOS, Android

### Affected platform versions

_No response_

### Did you find any workaround?

Adding an empty `<Rectangle  />` next to the label fixes the problem.

This behavior is also observed in .NET 7 latest.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

When expanding star definitions, the `targetSize` parameter contains the padding (which is removed). 
However, the calculation for the the `GridMinimum[Width|Height]()` also has the padding which also needs to be removed.

If the padding is not removed, then as soon as the grid width/height reaches the point where the "extra padding" is, then there is a fail fast path in `ExpandStars` which determines that there is no difference in size so skips the calculations for the star expansion. It also appears that the parameter with the "extra padding" (`currentSize`) is _just_ used for this fail fast path.

### Issues Fixed

Fixes #16815
Fixes #18160

### CODE REVIEW

File: src/Core/tests/UnitTests/Layouts/GridLayoutManagerTests.cs [hunk 1]
```diff
@@ -2949,6 +2949,71 @@ public void StarRowsAccountForPadding(double top, double bottom)
...
+		// and then that size is used to calculate cell sizes, we need to
+		// remove the padding as the cells are not placed in the padding.
+		// This means the issue appears when:
+		//   grid width = view widths + (2 * padding)
+		[Theory, Category(GridStarSizing)]
+		[InlineData(40, 21, 24)]
+		[InlineData(39, 20, 23)]
+		[InlineData(38, 19, 22)]
+		[InlineData(37, 18, 21)]
+		public void StarRowsCalculateCorrectlyWhenGridWidthNearsMinWidth(double gridWidth, double v0W, double v1X)
```
Comment (hartez) [inline src/Core/tests/UnitTests/Layouts/GridLayoutManagerTests.cs:2963]:
```suggestion
		public void StarRowsCalculateCorrectlyWhenGridWidthNearsMinWidth(double widthConstraint, double view0ExpectedWidth, double view1ExpectedX)
```

File: src/Core/tests/UnitTests/Layouts/GridLayoutManagerTests.cs [hunk 2]
```diff
@@ -2949,6 +2949,71 @@ public void StarRowsAccountForPadding(double top, double bottom)
...
+			AssertArranged(view0, new Rect(paddingL, 0, v0W, heights));
+			AssertArranged(view1, new Rect(v1X, 0, viewWidth, heights));
+		}
+
+		[Theory, Category(GridStarSizing)]
+		[InlineData(40, 21, 24)]
+		[InlineData(39, 20, 23)]
+		[InlineData(38, 19, 22)]
+		[InlineData(37, 18, 21)]
+		public void StarColsCalculateCorrectlyWhenGridHeightNearsMinHeight(double gridHeight, double v0H, double v1Y)
```
Comment (hartez) [inline src/Core/tests/UnitTests/Layouts/GridLayoutManagerTests.cs:2992]:
```suggestion
		public void StarColsCalculateCorrectlyWhenGridHeightNearsMinHeight(double heightConstraint, double view0ExpectedHeight, double view1ExpectedY)
```

**Review by hartez — CHANGES_REQUESTED** [review]
Looks good, just make the test parameters clearer.

**Review by jsuarezruiz — APPROVED** [review]

**Review by emaf — APPROVED** [review]

**Review by hartez — APPROVED** [review]
