### PR TITLE
Use the TextColor value to set the ClearButton color on the Entry

### LINKED ISSUE #13432: Entry ClearButton not taking color of text/hard to see
### Description

image

The clear button isn't taking a color cue from the text color. 

I found some notes about this in the Xamarin.Forms github, but I'm not sure if that's actively used for anything or just an archive.

https://github.com/xamarin/Xamarin.Forms/pull/12391
https://github.com/xamarin/Xamarin.Forms/pull/14766

### Steps to Reproduce

Make an entry with a black or near-black background color and light text color, the 'x' for the clear button is not readily visible.

### Link to public reproduction project repository

n/a

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 9.0, API 28

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Use the TextColor value to set the ClearButton color on the Entry. Reviewing issues I realized that 13432 was already fixed in Xamarin.Forms and we have not migrated the changes to .NET MAUI https://github.com/xamarin/Xamarin.Forms/pull/12391

To test the changes can use the added sample to the .NET MAUI Entry samples.

Android
image

iOS
image

image

### Issues Fixed

Fixes #13432

### CODE REVIEW

**Comment by jfversluis** [comment]
How hard would it be to make these two separate things? 

I definitely can see myself wanting the clear button to be red, but not my text. Since we now have the opportunity to add new APIs, unlike Forms, why not add a new property to allow for setting the clear button color separately?

**Comment by jsuarezruiz** [comment]
> How hard would it be to make these two separate things?
> 
> I definitely can see myself wanting the clear button to be red, but not my text. Since we now have the opportunity to add new APIs, unlike Forms, why not add a new property to allow for setting the clear button color separately?

@Redth Thoughts?

File: src/Core/src/Platform/iOS/TextFieldExtensions.cs [hunk 1]
```diff
@@ -176,7 +177,61 @@ static UITextPosition GetSelectionEnd(UITextField textField, IEntry entry, UITex
...
+			}
+		}
+
+		internal static UIImage? GetClearButtonTintImage(UIImage image, UIColor color)
+		{
+			var size = image.Size;
+
+			UIGraphics.BeginImageContextWithOptions(size, false, UIScreen.MainScreen.Scale);
+
+			if (UIGraphics.GetCurrentContext() == null)
```
Comment (mandel-macaque) [inline src/Core/src/Platform/iOS/TextFieldExtensions.cs:217]:
```suggestion
			if (UIGraphics.GetCurrentContext() is null)
```

So close ;)

**Review by mandel-macaque — APPROVED** [review]
Approving with a minor thing
