### PR TITLE
[Android] Support for images inside HTML label

### LINKED ISSUE #21044: Label with HTML TextType does not display images on Android
### Description

On the Android platform, a `Label` with `TextType=Html` that contains img tags does not render the image. This works perfectly well on iOS. I understand that it is ideal to use an Image control to display images, however, this is not an option in my use case.

The label displays comments fetched from an API and the comments usually contain emoji images embedded within as seen in the attached screenshot, but they are rendered as blank boxes.

I think it is important to mention that the mobile app I'm working on is an adaptation of an old native Android app with the same features, and in the native Android version, these images are rendered just fine.

image

### Steps to Reproduce

1. Create a `ContentView`
2. Add a `Label` with `TextType=Html`
3. Bind Html content containing an `img` tag with an absolute url to an emoji in the `src` attribute to the `Text` of the `Label`.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

```
    <Label TextType="Html">
        <![CDATA[
            <h1>Hello World</h1>
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7invFYnW6Ntqiibf_nRumE0-BilpyjTMJTDVEtXbPHw&s" alt="eiffel">
            <img src="https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RWCZER?ver=1433&q=90&m=6&h=195&w=348&b=%23FFFFFFFF&l=f&o=t&aim=true" alt="eiffel">
        ]]>
    </Label>
```

|Before|After|
|--|--|
|||

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/21044

### CODE REVIEW

File: src/Core/src/Platform/Android/ImageGetter.cs
Comment (kubaflo) [inline src/Core/src/Platform/Android/ImageGetter.cs:1]: This class could be potentially moved to this file: `maui/src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformInterop.java` to improve performance if this PR makes sense

**Comment by jsuarezruiz** [comment]
Affecting only Android, and being a different behavior from other platforms, should it be a Platform Specific? 
cc @PureWeen

File: src/Core/src/Platform/Android/TextViewExtensions.cs [hunk 1]
```diff
@@ -21,12 +21,17 @@ public static void UpdateTextHtml(this TextView textView, ILabel label)
 			var text = label.Text ?? string.Empty;
 			var htmlText = WebUtility.HtmlDecode(text);
 
-			if (OperatingSystem.IsAndroidVersionAtLeast(24))
-				textView.SetText(Html.FromHtml(htmlText, FromHtmlOptions.ModeCompact), BufferType.Spannable);
-			else
+			void SetTextHtml()
+			{
+				if (OperatingSystem.IsAndroidVersionAtLeast(24))
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/TextViewExtensions.cs:26]: I know images already works on iOS and this change align the behavior. Not sure about the Windows behavior, did you try?

Comment (kubaflo) [reply src/Core/src/Platform/Android/TextViewExtensions.cs:26]: I don't have a Windows device. Maybe you could have a look at it, please?

**Comment by kubaflo** [comment]
## 🔍 Manual Testing Review — PR #21679

### Test Setup
Rebuilt and deployed the HostApp on both **Android emulator** and **iOS simulator** (iPhone Xs) using the XAML-based test page from the PR description:

```xml
<Label TextType="Html"><![CDATA[
    <h1>Hello World</h1>
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7invFYnW6Ntqiibf_nRumE0-BilpyjTMJTDVEtXbPHw&s" alt="eiffel">
    <img src="https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RWCZER?ver=1433&q=90&m=6&h=195&w=348&b=%23FFFFFFFF&l=f&o=t&aim=true" alt="dotnet">
]]></Label>
```

### Results

| Platform | Images Rendered | Notes |
|----------|:-:|-------|
| **iOS** (iPhone Xs, iOS 18.5) | ✅ | Images display correctly out-of-the-box (iOS handles HTML img natively) |
| **Android** (API 34 emulator) | ✅ | Images load and display after async download via the new `ImageGetter` — **confirms the fix works** |

### Code Review Notes

**What the PR does well:**
- ✅ Clean `Html.IImageGetter` implementation with async download + cache
- ✅ Generation tracking via `ConditionalWeakTable` to prevent stale callbacks from overwriting newer text
- ✅ Sensible limits: 10 MB per image, 50-entry cache, 30s timeout
- ✅ Proper error handling with `Log.Warn` diagnostics

**Observations / things to consider:**
1. **Static `HttpClient` & cache** — `s_httpClient` and `s_cache` are `static`, meaning they persist for the app lifetime. This is fine for most apps, but very image-heavy HTML labels could accumulate memory. The 50-entry eviction helps but recycled `Bitmap` objects may still hold native memory briefly.
2. **`WebUtility.HtmlDecode` on the full HTML** — This decodes `&amp;` → `&` etc. before passing to `Html.FromHtml`. For most cases this is correct, but if the HTML itself contains entities intentionally (e.g., `&lt;code&gt;`), double-decoding could alter content. Worth verifying with edge-case HTML.
3. **No cancellation on navigation** — If a user navigates away while images are downloading, the `LoadImageAsync` fire-and-forget will still complete and cache. Not a bug, but something to be aware of.
4. **Missing test coverage** — The PR adds no automated UI test for this scenario. Consider adding a test in `TestCases.HostApp/Issues/` + `TestCases.Shared.Tests/Tests/Issues/` to prevent regression.

### Verdict
✅ **Fix confirmed working** on both platforms. The approach is solid and well-structured. Would recommend adding a UI test before merge.

**Comment by kubaflo** [comment]
## 📋 Pre-Merge Review — PR #21679

### Title/Description
- **Title** is clear: `[Android] Support for images inside HTML label` ✅
- **Description** needs the required NOTE block for testing PR builds
- **Root cause** not explained in description — Android's `Html.FromHtml()` was called without an `Html.IImageGetter`, so `` tags rendered as empty boxes

### Code Review (2 files changed, +154/-4)

**`ImageGetter.cs`** (new file)
- ✅ Clean `Html.IImageGetter` implementation with async HTTP download
- ✅ Shared static `HttpClient` (no per-request allocation)
- ✅ `BitmapDrawable(Resources, bitmap)` — density-aware constructor
- ✅ Bounded cache (50-entry LRU with bitmap recycling)
- ✅ Sensible limits: 10 MB per image, 30s timeout
- ✅ `async Task` instead of `async void` (safer exception handling)
- ✅ Concurrent fetch deduplication via `s_inFlight`
- ✅ Error logging with `Log.Warn` for diagnostics

**`TextViewExtensions.cs`** (modified)
- ✅ Passes `ImageGetter` to `Html.FromHtml()` on both API 24+ and legacy code paths
- ✅ Generation tracking via `ConditionalWeakTable` prevents stale image-load callbacks

### Items to Address Before Merge
1. ⚠️ **Missing NOTE block** in PR description (required for all PRs)
2. ⚠️ **Missing UI test** — No automated test for HTML image rendering. Should add `Issue21044` HostApp page + NUnit test to prevent regression
3. ℹ️ **No PublicAPI changes needed** — `ImageGetter` is `internal`

### Manual Testing Results
- ✅ **iOS**: Images display correctly (native behavior)
- ✅ **Android**: Images load and render after async download — **fix confirmed working**

### Verdict
✅ Code is solid and well-structured. Address the missing test coverage and NOTE block before merge.
