### PR TITLE
[Windows] Fix memory leak w/ main window

### LINKED ISSUE #24102: [Windows] MauiWinUIWindow leak
### Description

On WinUI, MauiWinUIWindow seems to leak.

### Steps to Reproduce

There is a repro attached. Run the application, every time you click the only button on the main page, it will go through the steps:
 - Create a new MauiWinUIWindow.
 - Activate() it.
 - Add it to WeakReference.
 - Close() it.
 - Run GC.
 - Count the WeakReferences that IsAlive = true.
 - Repeat.
 
Memory usage goes up. The count of alive MauiWinUIWindow instances is 100%.

On our end we integrated the DeviceTests in our code, and are relying on "CreateHandlerAndAddToWindow" a lot. In the MAUI repo, there are about 50 such tests, but we are going past 120 and now after 2 to 3 runs, the app would crash. Normally with win32 exceptions, sorts of Access Violation or "not enough memory to perform the operation" when native Windows libraries seem to deal with window allocation.

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/WinUIMultipleWindowsLeak

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.80 SR8

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Foda**
### Description of Change

Fix memory leak w/ main window by unsubscribing to events.

### Issues Fixed

Fixes #24102

### CODE REVIEW

File: src/Core/src/Platform/Windows/MauiWinUIWindow.cs [hunk 1]
```diff
@@ -87,6 +87,9 @@ private void OnClosedPrivate(object sender, UI.Xaml.WindowEventArgs args)
 		{
 			OnClosed(sender, args);
 
+			Activated -= OnActivated;
```
Comment (Foda) [inline src/Core/src/Platform/Windows/MauiWinUIWindow.cs:90]: After a bunch of trial and error, this was the solution to getting the weak reference to be marked not-alive.

**Comment by jingliancui** [comment]
hi, if this fix pass this issue sample app? https://github.com/dotnet/maui/issues/24140

**Review by jfversluis — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]
