### PR TITLE
[listview] fixes for various null/empty DataTemplate

### LINKED ISSUE #11203: Changing `<DataTemplate/>` contents can give a runtime exception
### Description

I was testing this app: https://github.com/ionixjunior/YellowClone/tree/migracao_maui/YellowClone

In `MyTripsView.xaml`, if you comment out the `<ViewCell/>`:

image

In this case, I was going to type a new `<TextCell Text="{Binding Name}" />`, but it hit this issue before I was able to.

If I run the app with an empty `<DataTemplate/>`, it runs fine. Then I'm able to *add* a new `<TextCell/>` or `<ViewCell/>` and hot reload them. It only fails when you remove a working cell.

Full stack trace is:
```
System.InvalidCastException
  Message=Specified cast is not valid.
 	0xFFFFFFFFFFFFFFFF in Android.Runtime.JNIEnv.monodroid_debugger_unhandled_exception	C#
 	0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:12,5	C#
 	0x26 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:430,26	C#
 	0x39 in Android.Runtime.DynamicMethodNameCounter.21	C#
 	0x39 in Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a	C#
 	0x74 in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:12320,4	C#
 	0x2D in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:93,6	C#
 	0x69 in Android.Views.ViewGroup.Layout at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.ViewGroup.cs:3369,5	C#
 	0x1F in Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer<Microsoft.Maui.Controls.ListView>.OnLayout at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Android\VisualElementRenderer.cs:54,6	C#
 	0x8 in Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnLayout at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\ListView\Android\ListViewRenderer.cs:298,4	C#
 	0x10 in Android.Views.ViewGroup.n_OnLayout_ZIIII at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.ViewGroup.cs:3655,4	C#
 	0x11 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:429,5	C#
 	0x39 in Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a	C#
 	0x74 in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:12320,4	C#
 	0x2D in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:93,6	C#
 	0x69 in Android.Views.ViewGroup.Layout at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.ViewGroup.cs:3369,5	C#
 	0xD4 in Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler at D:\a\_work\1\s\src\Core\src\Handlers\ViewHandlerExtensions.Android.cs:131,4	C#
 	0x2 in Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer<Microsoft.Maui.Controls.ListView>.Microsoft.Maui.IViewHandler.PlatformArrange at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\VisualElementRenderer.cs:230,4	C#
 	0x1F in Microsoft.Maui.Controls.VisualElement.ArrangeOverride at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:124,4	C#
 	0x2 in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:116,4	C#
 	0x5A in Microsoft.Maui.Layouts.LayoutExtensions.ArrangeContent at D:\a\_work\1\s\src\Core\src\Layouts\LayoutExtensions.cs:174,4	C#
 	0x9 in Microsoft.Maui.Controls.ContentPage.Microsoft.Maui.IContentView.CrossPlatformArrange at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\ContentPage.Impl.cs:35,4	C#
 	0x22 in Microsoft.Maui.Platform.ContentViewGroup.OnLayout at D:\a\_work\1\s\src\Core\src\Platform\Android\ContentViewGroup.cs:92,4	C#
 	0x10 in Android.Views.ViewGroup.n_OnLayout_ZIIII at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.ViewGroup.cs:3655,4	C#
 	0x11 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:429,5	C#
```
(sorry VS copied this funny)

### Steps to Reproduce

1. Run YellowClone (change to `net7.0` if you want latest MAUI version)
2. Click the hamburger menu and go to My Trips
3. Comment out the `<ViewCell/>`

### Link to public reproduction project repository

https://github.com/ionixjunior/YellowClone/tree/migracao_maui/YellowClone

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

all

### Did you find any workaround?

Rebuild the app, not using XAML hot reload.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jonathanpeppers**
### Description of Change

Fixes #11203

The following breaks XAML Hot Reload:

1. Setup a working `ListView` and `DataTemplate`

2. Delete the `DataTemplate`'s body (as if I'm about to type a completely new view there).

3. Trigger a XAML Hot Reload. This can happen automatically if you just pause typing.

4. MAUI crashes at runtime:

```
in Android.Views.ViewGroup.Layout at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.ViewGroup.cs:3369,5
in Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer<Microsoft.Maui.Controls.ListView>.OnLayout at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Android\VisualElementRenderer.cs:54,6
in Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnLayout at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\ListView\Android\ListViewRenderer.cs:298,4
```

You can also create this problem in C#, like I did in a unit test:

    listView.ItemTemplate = new DataTemplate(() => /* valid template */);
    listView.ItemTemplate = new DataTemplate(); // broken
    listView.ItemTemplate = new DataTemplate(() => null); //broken

I could also get a slightly different crash:

    System.InvalidCastException: Specified cast is not valid.
    at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ActivateContent(Int32 index, Object item)

The "invalid cast" appears to be due to the changes in c57858f. It returns a `new Label()` in some cases, which does not work with a `ListView`. You need a `Cell` instead of `View` in that case.

The fixes appear to be in two places:

* `VisualElementRenderer.OnLayout`: use `is`, also simplifies the code

* `TemplatedItemsList.ActivateContent` : use `is` and call the default data template.

Now my tests pass, and I can't reproduce the issue in XAML Hot Reload either!

Manually testing, I'm able to alternative commenting out the two XAML elements:

image

image

This didn't work before.

### Issues Fixed

Fixes: https://github.com/dotnet/maui/issues/11203

### CODE REVIEW

File: src/Controls/src/Core/TemplatedItemsList.cs [hunk 1]
```diff
@@ -534,8 +534,14 @@ public DataTemplate SelectDataTemplate(object item)
...
-			TItem content = ItemTemplate != null ? (TItem)ItemTemplate.CreateContent(item, _itemsView) : _itemsView.CreateDefault(item);
-
+			if (ItemTemplate?.CreateContent(item, _itemsView) is TItem content)
+			{
+				// content is valid
+			}
+			else
+			{
+				content = _itemsView.CreateDefault(item);
+			}
```
Comment (mandel-macaque) [inline src/Controls/src/Core/TemplatedItemsList.cs:544]: Why don't you negate the if so that it is more clear, looks strange to have an empty {}
```suggestion
			if (!(ItemTemplate?.CreateContent(item, _itemsView) is TItem content))
			{
				// content is not valid, use the defaul
				content = _itemsView.CreateDefault(item);
			}
```

**Review by mandel-macaque — APPROVED** [review]
Looks good, maybe invert the if (I'm not a UI developer)

File: src/Controls/src/Core/TemplatedItemsList.cs (hunk 1 above)
Comment (jonathanpeppers) [reply src/Controls/src/Core/TemplatedItemsList.cs:544]: So I think I can use the new C# feature `is not`:
```code
if (ItemTemplate?.CreateContent(item, _itemsView) is not TItem content)
```
Let me just test it locally.

**Review by jsuarezruiz — APPROVED** [review]

**Review by rmarinho — CHANGES_REQUESTED** [review]
Failing test on iOS 

```
NavigatingBackViaBackButtonFiresNavigatedEvent
```

**Comment by jonathanpeppers** [comment]
@rmarinho what test is this?

I can't even find it in the repo:
```
> git grep NavigatingBackViaBackButtonFiresNavigatedEvent
# nothing
```

I don't see how the latest commit broke it c1133aaf7fd2fb8afe9d90c8c7177651c1f5be47, as it should produce identical C# code.

It was green before, so is this broken by a change in main?

**Comment by PureWeen** [comment]
> @rmarinho what test is this?
> 
> I can't even find it in the repo:
> 
> ```
> > git grep NavigatingBackViaBackButtonFiresNavigatedEvent
> # nothing
> ```
> 
> I don't see how the latest commit broke it [c1133aa](https://github.com/dotnet/maui/commit/c1133aaf7fd2fb8afe9d90c8c7177651c1f5be47), as it should produce identical C# code.
> 
> It was green before, so is this broken by a change in main?

@jonathanpeppers CI merges main before running tests. It looks like main broke with one of the merges from yesterday. Taking a look now

**Comment by jonathanpeppers** [comment]
@rmarinho so maybe we can merge this one? It seems like it should be an improvement, adding `is` checks.

**Comment by mandel-macaque** [comment]
@rmarinho @PureWeen there is a way (I made it work) to ensure that vsts use the commit of the PR and not the merge with main. It has its pros an cons. But you can do that and then make the merge block if it is not updated with main

**Review by rmarinho — APPROVED** [review]
