### PR TITLE
[iOS] Double dash in input field crash fix

### LINKED ISSUE #15937: [iOS] Issue when using BindableLayout and Entry/Editor
### Description

I'm using a StackLayout with `BindableLayout.ItemsSource` to show Entry or Editor.
However, the app throws an exception:

`System.ArgumentNullException: Value cannot be null. (Parameter 'fromPosition')`
Screenshot 2023-06-29 at 18 44 52

### Steps to Reproduce

1. Create a .NET Maui project.
2. Add the following XAML code.

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiSample.MainPage">

    <ScrollView>
        <VerticalStackLayout
            Spacing="25"
            Padding="30,0"
            VerticalOptions="Center">


            <StackLayout Margin="10"
                         VerticalOptions="Center"
                         BindableLayout.ItemsSource="{Binding CustomList}">
                <BindableLayout.ItemTemplate>
                    <DataTemplate>
                        <Grid Margin="0,0,0,20"
                              Padding="0"
                              RowSpacing="0"
                              ColumnSpacing="0">
                            <Entry Text="{Binding Name}"
                                   MaxLength="{Binding MaxLength}"
                                   Keyboard="{Binding KeyboardType}"/>

                            <!--Same issue using Editor-->
                            <!--<Editor Text="{Binding Name}"
                                   MaxLength="{Binding MaxLength}"
                                   Keyboard="{Binding KeyboardType}"/>-->
                        </Grid>
                    </DataTemplate>
                </BindableLayout.ItemTemplate>
            </StackLayout>

            <Image
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="200"
                HorizontalOptions="Center" />

            <Label
                Text="Hello, World!"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32"
                HorizontalOptions="Center" />

            <Label
                Text="Welcome to .NET Multi-platform App UI"
                SemanticProperties.HeadingLevel="Level2"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                FontSize="18"
                HorizontalOptions="Center" />

            <Button
                x:Name="CounterBtn"
                Text="Click me"
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Center" />

        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
```

3. Add the following code behind

```c#
using System.Collections.ObjectModel;

namespace MauiSample;

public class CustomItem
{
    public string Name { get; set; }
    public double MaxLength { get; set; }
    public Keyboard KeyboardType { get; set; }
}

public partial class MainPage : ContentPage
{
	int count = 0;
	public ObservableCollection<CustomItem> CustomList { get; set; }

	public MainPage()
	{
		InitializeComponent();
		CustomList = new ObservableCollection<CustomItem>();
		AddCustomItems();
        BindingContext = this;
    }

	void AddCustomItems()
	{
		CustomList.Clear();

        for (int i = 0; i < 10; i++)
        {
            CustomList.Add(new CustomItem
            {
                MaxLength = 10,
                KeyboardType = Keyboard.Email,
                Name = "my value: " + i
            });
        }


  //      CustomList.Add(new CustomItem { Name = "Test1", MaxLength = 20, KeyboardType = Keyboard.Email });
		//CustomList.Add(new CustomItem { Name = "Test2", MaxLength = 30, KeyboardType = Keyboard.Plain });
		//CustomList.Add(new CustomItem { Name = "Test3", MaxLength = 10, KeyboardType = Keyboard.Numeric });
		//CustomList.Add(new CustomItem { Name = "Test4", MaxLength = 23, KeyboardType = Keyboard.Default });
    }

	private void OnCounterClicked(object sender, EventArgs e)
	{
		count++;

		if (count == 1)
			CounterBtn.Text = $"Clicked {count} time";
		else
			CounterBtn.Text = $"Clicked {count} times";

		SemanticScreenReader.Announce(CounterBtn.Text);
	}
}
```

4. Run the project and the app will crash.

### Link to public reproduction project repository

https://github.com/juniorsaraviao/MauiSample

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.2 and up

### Did you find any workaround?

No

### Relevant log output

```shell
Unhandled Exception:
System.ArgumentNullException: Value cannot be null. (Parameter 'fromPosition')
   at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName)
   at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle(INativeObject self, String argumentName)
   at UIKit.UITextField.GetTextRange(UITextPosition fromPosition, UITextPosition toPosition)
   at Microsoft.Maui.Platform.TextInputExtensions.SetTextRange(IUITextInput platformView, Int32 start, Int32 selectedTextLength)
   at Microsoft.Maui.Controls.Platform.TextExtensions.UpdateText(UITextField textField, InputView inputView)
   at Microsoft.Maui.Controls.Entry.MapText(IEntryHandler handler, Entry entry)
   at Microsoft.Maui.Controls.Entry.MapText(EntryHandler handler, Entry entry)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.Controls.Entry, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.EntryHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IEntry, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiTextField, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.EntryHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IEntry, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiTextField, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.ScrollViewHandler.UpdateContentView(IScrollView scrollView, IScrollViewHandler handler)
   at Microsoft.Maui.Handlers.ScrollViewHandler.MapContent(IScrollViewHandler handler, IScrollView scrollView)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IScrollViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIScrollView, Microsoft.iOS, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIScrollView, Microsoft.iOS, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler)
   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ViewExtensions.ToHandler(IView view, IMauiContext context)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.SetPageRenderer(Page page, ShellContent shellContent)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.LoadRenderers()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.ViewDidLoad()
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiSample.Program.Main(String[] args) in /Users/juniorsaraviao/Projects/MauiSample/Platforms/iOS/Program.cs:line 13
```

### LINKED ISSUE #19954: Issue when using BindableLayout and Entry/Editor with special characters
@jfversluis ... I am also running into this issue.  
Using net8.0-ios...  This is currently halting my port to MAUI from going to production.  It is very weird as the only way I can reliably reproduce it is this:
high level app UI>>>:   List page with drill down to detail page.

---updated this to simplify after what I found:
To replicate follow this:
1) start at list and drill down to a detail page
2) click on a field to bring up the Keyboard/Picker/any iOS native UI
3) navigate back to list page... and then go into detail page again.

Looking at the call stack below... it seems to occur on a UITextView... drilling in... 
YOU ARE NOT GOING TO BELIEVE THIS... 
my field is populated from a DB and it has a double dash -- in it... 
- what the system does is the first time, there is no issues... is displays the double dash as 2 characters...
- if you click on ANY field to bring up the keyboard... in my case, I consider it dirty and save as I navigate back.
- it then converts that double dash to a special long dash
- next time in, it barfs with the error below as it tries to show the special character.

SOO... after all this... it seems it is definitely a result of having some special characters in a field... in combination with having previously brought up a keyboard/Picker/ any type of iOS native dialog
P.S.> I tested Char(10) and Char(13) and no issues with them...  I don't know how many other types of special character combinations exist...
regardless... this needs to be fixed.

```
Value cannot be null. (Parameter 'fromPosition') 
----------    
at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/ThrowHelper.cs:line 28    
at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle(INativeObject self, String argumentName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/INativeObject.cs:line 42    
at UIKit.UITextView.GetTextRange(UITextPosition fromPosition, UITextPosition toPosition) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UITextView.g.cs:line 565    
at Microsoft.Maui.Platform.TextInputExtensions.SetTextRange(IUITextInput platformView, Int32 start, Int32 selectedTextLength)    
at Microsoft.Maui.Controls.Platform.TextExtensions.UpdateText(IUITextInput textInput, InputView inputView, Boolean isEditing)    
at Microsoft.Maui.Controls.Platform.TextExtensions.UpdateText(UITextView textView, InputView inputView)    
at Microsoft.Maui.Controls.Editor.MapText(IEditorHandler handler, Editor editor)    
at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass2_0`2[[Microsoft.Maui.Controls.Editor, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IEditorHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ReplaceMapping>b__0(IEditorHandler h, Editor v, Action`2 p)    
at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass1_0`2[[Microsoft.Maui.Controls.Editor, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IEditorHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ModifyMapping>g__newMethod|0(IElementHandler handler, IElement view)    
at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IEditor, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IEditorHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)    
at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)    
at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property)    
at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property)    
at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)    
at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)    
at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)    
at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity)    
at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget)    
at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__50_0()    
at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)    
at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.PropertyChanged(Object sender, PropertyChangedEventArgs args)    
at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)    
at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(PropertyChangedEventArgs e)    
at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(String propertyName)    
at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.SetProperty[WODetails](WODetails& field, WODetails newValue, String propertyName)    
at SOSMobile.WorkOrders.WorkOrderDetailViewModel.set_WOInfo(WODetails value) in C:\Source\net8\SOSMobile\Features\WorkOrders\WorkOrderDetailViewModel.cs:line 40    
at SOSMobile.WorkOrders.WorkOrderDetailViewModel.RefreshData() in C:\Source\net8\SOSMobile\Features\WorkOrders\WorkOrderDetailViewModel.cs:line 138 

```

_Originally posted by @ppereira-serviceonsites in https://github.com/dotnet/maui/issues/15937#issuecomment-1870322116_

### LINKED ISSUE #20439: [iOS] Double dash in Entry or Editor crashes the app if iOS device has Smart Punctuation turned on
### Description

I found a situation where landing on a page that hosts Entry (or Editor) with a Text property set to double dash will crash the app.

Given there is a page (PageN) somewhere in the app that hosts an Entry (or an Editor) with a Text property set to double dash  

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="DoubleDashCrash.DoubleDashCrashPage"
             Title="Double Dash Crash Page">

    <Editor
        Text="--"
        BackgroundColor="Yellow"
        VerticalOptions="Center" 
        HorizontalOptions="Center" />
    
</ContentPage>

```
Given there is another page (PageA) with an Entry (or Editor) that will be visited before PageN.

Here are steps that lead to a crash:

1. Visit PageA and simply TAP inside the Entry. No need to type anything, just TAP inside.
2. Visit PageN. The app crashes.

If you do NOT TAP then the app doesn't crash
If you reverse the above order and first visit the page with an Entry set to double dash then the app doesn't crash
If you turn OFF Smart Punctuation in the phone's Settings then the app doesn't crash
If you do not have double dash in the Text property of the PageN then the app doesn't crash

While investigating this strange behavior I found out that when the Smart Punctuation setting is turned on, iOS is attempting to convert two adjacent dashes `--`   into   a single character, so called "em dash" or a "long dash", ASCII code151. I suspect this might be the reason why the app crashes, however I was hoping that MAUI should be capable of recognizing this condition and handling it gracefully. 

Similar issue is described in #19954 but here, I believe, I found exact steps to reproduce this bug.

https://github.com/dotnet/maui/assets/36049508/4ca64693-0275-4981-8d61-8b8b3be8c578

### Steps to Reproduce

1. On the device go to  Settings > General > Keyboards. Turn "Smart Punctuation" to ON (it's the default anyway)
2. Open the repo, run the DoubleDashCrash project for iOS
3. On the Home page simply tap inside the Editor control.
4. Open Flyout menu, tap "Double Dash Crash". This should open another page with a single Entry box with Text property set to "--". 
5. The app will crash now

### Link to public reproduction project repository

https://github.com/MichaelShapiro/MauiBugs/tree/master/DoubleDashCrash

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

No

### Relevant log output

```shell
C:\WINDOWS\system32>dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maccatalyst                17.2.8004/8.0.100      VS 17.8.34511.84
maui-windows               8.0.3/8.0.100          VS 17.8.34511.84
ios                        17.2.8004/8.0.100      VS 17.8.34511.84
android                    34.0.43/8.0.100        VS 17.8.34511.84
```

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

Using the length of the text based on the value from the iOS's text input rather than a control. It is because of the system's autocorrection that converts some combinations of characters into other symbols.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/20439
Fixes https://github.com/dotnet/maui/issues/19954
Fixes https://github.com/dotnet/maui/issues/15937

|Before|After|
|--|--|
|<video src="https://github.com/dotnet/maui/assets/42434498/f6f1d252-3022-4591-9b80-597a8e6ccc2b"/>|<video src="https://github.com/dotnet/maui/assets/42434498/5a3fec83-10fa-4c19-9a23-9a911211a720" />|

### CODE REVIEW

File: src/Controls/src/Core/Platform/iOS/Extensions/TextExtensions.cs [hunk 1]
```diff
@@ -50,8 +56,8 @@ static void UpdateText(this IUITextInput textInput, InputView inputView, bool is
 			{
 				// Re-calculate the cursor offset position if the text was modified by a Converter.
 				// but if the text is being set by code, let's just move the cursor to the end.
-				var cursorOffset = newText.Length - oldText.Length;
-				var cursorPosition = isEditing ? textInput.GetCursorPosition(cursorOffset) : newText.Length;
+				var cursorOffset = newTextLength - oldText.Length;
+				var cursorPosition = isEditing ? textInput.GetCursorPosition(cursorOffset) : newTextLength;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/iOS/Extensions/TextExtensions.cs:60]: There are some cursor position tests failing on macOS:
image

Comment (jsuarezruiz) [reply src/Controls/src/Core/Platform/iOS/Extensions/TextExtensions.cs:60]: Example: 
image

**Review by jsuarezruiz — COMMENTED** [review]
Could you take a look to the failing tests? Let me know, If you want me to check them myself.

**Comment by kubaflo** [comment]
@jsuarezruiz Sorry for the late response - I was pretty busy lately :)
I've added a new commit that fixes the tests and the bug

File: src/Controls/src/Core/Platform/iOS/Extensions/TextExtensions.cs (hunk 1 above)
Comment (kubaflo) [reply src/Controls/src/Core/Platform/iOS/Extensions/TextExtensions.cs:63]: I added a commit that fixes that

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz Sorry for the late response - I was pretty busy lately :) I've added a new commit that fixes the tests and the bug 

Don't worry, thanks for all your contributions. That test are passing now.

**Review by jsuarezruiz — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]
