### PR TITLE
[iOS] Fixed picker title's color

### LINKED ISSUE #19191: Picker TitleColor not working on iOS
### Description

When setting the TitleColor in the Picker control, the color is always Black

### Steps to Reproduce

1. Create a new MAUI app
2. Add a Picker control on the MainPage, setting the Title and TitleColor
3. Run and observe

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

Not a workaround, but having no items in the source of the picker, opening it, then closing it does apply the TitleColor. Selecting an item, then clearing it does not have the same outcome (applying the TitleColor as does closing the picker without items).

### Relevant log output

```shell
This still does not work in the latest Nightly build
```

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

Before this change, the title of the picker hasn't been styled because of the UpdatePicker method. When the selected index was equal to -1 the platformPicker.AttributedPlaceholder has been overridden by platformPicker.Text 

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/19191

https://github.com/dotnet/maui/assets/42434498/fff5a683-baa6-4549-93a1-deb9e89c544e

### CODE REVIEW

File: src/Core/src/Platform/iOS/PickerExtensions.cs [hunk 1]
```diff
@@ -38,14 +38,19 @@ internal static void UpdateAttributedPlaceholder(this MauiPicker platformPicker,
 			platformPicker.AttributedPlaceholder = nsAttributedString;
 		}
 
+		internal static void UpdatePickerTitle(this MauiPicker platformPicker, IPicker picker)
+		{
+			platformPicker.UpdateAttributedPlaceholder(new NSAttributedString(picker.Title ?? string.Empty, null, picker?.TitleColor?.ToPlatform()));
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/PickerExtensions.cs:43]: Why not use the existing `SetTitleColor` method?

**Review by jsuarezruiz — COMMENTED** [review]
The title color was not initialized or updated once the property changed? If it is in both cases, we must review [this test](https://github.com/dotnet/maui/blob/6295ed8aba7b62fdb5014fd30f46f38f885b9dcd/src/Core/tests/DeviceTests/Handlers/Picker/PickerHandlerTests.iOS.cs#L14) and determine why it has not shown the issue so far. If it is the second case, a new test must be included.

I can help managing the tests.

File: src/Core/src/Platform/iOS/PickerExtensions.cs (hunk 1 above)
Comment (kubaflo) [reply src/Core/src/Platform/iOS/PickerExtensions.cs:28]: I refactored it a bit in the latest commit. Let me know if it makes sense :)

Comment (jsuarezruiz) [reply src/Core/src/Platform/iOS/PickerExtensions.cs:28]: LGTM. Could you include an UI Test?

Comment (kubaflo) [reply src/Core/src/Platform/iOS/PickerExtensions.cs:28]: Added. I wonder if I can add screenshots for the UI tests so that you don't have to?

File: src/Controls/tests/UITests/snapshots/ios/PickerTitleShouldBeRed.png
Comment (jsuarezruiz) [inline src/Controls/tests/UITests/snapshots/ios/PickerTitleShouldBeRed.png:1]: Not related with the TitleColor issue and the fix, but the alignment behavior is different on iOS compared with the rest of the platforms.

File: src/Core/src/Platform/iOS/PickerExtensions.cs [hunk 2]
```diff
@@ -7,45 +7,35 @@ namespace Microsoft.Maui.Platform
...
 		internal static void UpdatePicker(this MauiPicker platformPicker, IPicker picker, int? newSelectedIndex = null)
 		{
 			var selectedIndex = newSelectedIndex ?? picker.SelectedIndex;
 
-			// Revert to placeholder/title if nothing selected
-			platformPicker.Text = selectedIndex == -1
-				? (picker.Title ?? string.Empty)
-				: picker.GetItem(selectedIndex);
+			if (selectedIndex != -1)
+			{
```
Comment (rmarinho) [inline src/Core/src/Platform/iOS/PickerExtensions.cs:36]: if we clear the items collection dont we need. to set it back to `string.empty` ?

Comment (kubaflo) [reply src/Core/src/Platform/iOS/PickerExtensions.cs:36]: You're right! Fixed

**Review by mattleibow — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]
