### PR TITLE
Fix for CarouselView doesnot scroll corresponding to ItemsUpdatingScrollMode when collection modified 

### LINKED ISSUE #25991: [Windows] - CarouselView reverts to displaying 1st item in collection when collection modified
### Description

I have a CarouselView which uses an ObservableCollection<> as it's ItemSource. The CarouselView appears to behave correctly when scrolling through the collection - but if an item gets added to the collection, the CarouselView reverts to showing the first item in the ItemSource collection.

I would have expected the CarouselView to stay on the item that was displayed (unless of course if it gets removed from the underlying collection in ItemSource, in which case I guess showing the first item is valid?).

Android appears to function correctly.

### Steps to Reproduce

Create a data type to store. As an example I'm using a Person class:

```
namespace MauiTestApp.Classes
{
	public class Person
	{
		public string FirstName { get; set; }
	}
}
```

And a TestPage:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:classes="clr-namespace:MauiTestApp.Classes;assembly=MauiTestApp"
						 x:Class="MauiTestApp.TestPage">
	<CarouselView x:Name="TheCarouselView">
		<CarouselView.ItemTemplate>
			<DataTemplate x:DataType="classes:Person">
				<StackLayout>
					<Label Text="{Binding FirstName}"  FontAttributes="Bold" />
					<Grid ColumnDefinitions="Auto, Auto, Auto">
						<Button Grid.Column="0" Text="Back" Clicked="OnBack_Clicked" />
						<Button Grid.Column="1" Text="Add" Clicked="OnAdd_Clicked" />
						<Button Grid.Column="2" Text="Next" Clicked="OnNext_Clicked" />
					</Grid>
				</StackLayout>
			</DataTemplate>
		</CarouselView.ItemTemplate>
	</CarouselView>
</ContentPage>
```

And the code behind:
```
using MauiTestApp.Classes;
using System.Collections.ObjectModel;

namespace MauiTestApp;

public partial class TestPage : ContentPage
{

	private ObservableCollection<Person> _people = new ObservableCollection<Person>() { new Person() { FirstName = "Person 1" }, new Person() { FirstName = "Person 2" } };

	public TestPage()
	{
		InitializeComponent();
	}
	protected override void OnAppearing()
	{
		base.OnAppearing();

		TheCarouselView.Loop = false;
		TheCarouselView.ItemsSource = _people;
	}

	private void OnAdd_Clicked(object sender, EventArgs e)
	{
		_people.Add(new Person() { FirstName = "Another Person" });
	}

	private void OnBack_Clicked(object sender, EventArgs e)
	{
		int currentIndex = _people.IndexOf(TheCarouselView.CurrentItem as Person);
		if (currentIndex > 0)
			TheCarouselView.ScrollTo(currentIndex - 1);
	}

	private void OnNext_Clicked(object sender, EventArgs e)
	{
		int currentIndex = _people.IndexOf(TheCarouselView.CurrentItem as Person);
		if (currentIndex < _people.Count - 1)
			TheCarouselView.ScrollTo(currentIndex + 1);
	}
}

```
When showing the page, initially Person 1 is shown, click Next which will move to Person 2. Then click Add - this adds a person called "Another Person".  I would have expected Person 2 to still be displayed, but instead Person 1 gets shown.

### Link to public reproduction project repository

https://github.com/Mark-NC001/CarouselViewIssue

### Version with bug

8.0.93 SR9.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by SuthiYuvaraj**
### Issue Details
**Behavior in windows:**  When modifying the collection, the CarouselView scrolls to display the first item. This is the expected behavior when considering the ItemsUpdatingScrollMode.
**Android and iOS:** While updating the collection, ItemsUpdatingScrollMode is not respected, causing the current position to deviate from the expected behavior for keeping items in view.

### Root Cause
**Android:** In the MauiCarouselRecyclerView, the ItemsUpdatingScrollMode is not applied during the ItemsCollectionChanged event. As a result, the CarouselView maintains the position of the previously scrolled item.
**iOS and Mac:** In the CarouselViewController, the collection update ignores the ItemsUpdatingScrollMode, and the current position remains unchanged, irrespective of the scroll mode settings.

### Fix Details
**Android:** Updated the MauiCarouselRecyclerView to adjust the carousel position based on the ItemsUpdatingScrollMode during collection updates.
**iOS and Mac:** Incorporated the ItemsUpdatingScrollMode into the collection update logic to ensure the position is updated appropriately according to the specified scroll mode.

### Issues Fixed
Fixes #25991

### Output Screenshot
Before Issue Fix | After Issue Fix |
|----------|----------|
|<video width="200" height="200" alt="Before Fix video" src="https://github.com/user-attachments/assets/dba71821-97c7-44ae-b5a6-0d5d0c709f77">|<video width="200" height="200" alt="After Fix video" src="https://github.com/user-attachments/assets/1130fb81-b47e-4576-bb73-f04ac3752720">

### CODE REVIEW

**Comment by SuthiYuvaraj** [comment]
Hi  @jsuarezruiz, We have fixed the issue. On Windows, ItemsUpdatingScrollMode is considered during collection updates. For Android and iOS, we have implemented code changes to ensure consistent behavior across all platforms and test cases for this issue are already included in the [26160](https://github.com/dotnet/maui/pull/26160) PR

File: src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs [hunk 1]
```diff
@@ -331,14 +331,28 @@ void CollectionViewUpdating(object sender, NotifyCollectionChangedEventArgs e)
...
+			int targetPosition;
 			if (_positionAfterUpdate == -1)
 			{
 				return;
 			}
 
 			_gotoPosition = -1;
 
-			var targetPosition = _positionAfterUpdate;
+			// We need to update the position while modifying the collection.
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs:342]: I think we might want for clear read refactor this on this one method ?

File: src/Controls/src/Core/Handlers/Items2/iOS/CarouselViewController2.cs [hunk 2]
```diff
@@ -254,14 +254,28 @@ void CollectionViewUpdating(object sender, NotifyCollectionChangedEventArgs e)
...
 				return;
 			}
 
 			//_gotoPosition = -1;
 
-			var targetPosition = _positionAfterUpdate;
+			// We need to update the position while modifying the collection.
+			if (ItemsView.ItemsUpdatingScrollMode == ItemsUpdatingScrollMode.KeepItemsInView)
+			{
+				targetPosition = 0;
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items2/iOS/CarouselViewController2.cs:268]: won t this always scroll to the first position ?

Comment (SuthiYuvaraj) [reply src/Controls/src/Core/Handlers/Items2/iOS/CarouselViewController2.cs:268]: > won t this always scroll to the first position ?

Yes, based on the [documentation](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/carouselview/scrolling?view=net-maui-9.0#control-scroll-position-when-new-items-are-added) and behavior of the Windows platform, we implemented code changes to update the `scrollposition` according to the `ItemsUpdatingScrollMode`. When `ItemsUpdatingScrollMode` is set to `KeepItemsInView`, the scroll position will adjust to the first item in view. To maintain the scrolled index, `KeepScrollOffset` should be used instead.

File: src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs (hunk 1 above)
Comment (SuthiYuvaraj) [reply src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs:342]: > I think we might want for clear read refactor this on this one method ?

Hi @rmarinho  , Not clear about your concern.Are you suggesting improvements to the method's implementation itself, or are you referring to enhancing the comments we've added to this method?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
There are some CarouselView tests failing:

**Issue12574Test**
```
   at UITest.Appium.HelperExtensions.Wait(Func`1 query, Func`2 satisfactory, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 2107
   at UITest.Appium.HelperExtensions.WaitForAtLeastOne(Func`1 query, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 2124
   at UITest.Appium.HelperExtensions.WaitForElement(IApp app, String marked, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency, Nullable`1 postTimeout) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 651
   at Microsoft.Maui.TestCases.Tests.Issues.CarouselViewLoopNoFreeze.Issue12574Test() in /_/src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CarouselViewUITests.LoopNoFreeze.cs:line 44
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Issue10300Test**
```
   at UITest.Appium.HelperExtensions.Wait(Func`1 query, Func`2 satisfactory, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 2107
   at UITest.Appium.HelperExtensions.WaitForAtLeastOne(Func`1 query, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 2124
   at UITest.Appium.HelperExtensions.WaitForElement(IApp app, String marked, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency, Nullable`1 postTimeout) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 651
   at Microsoft.Maui.TestCases.Tests.Issues.CarouselViewRemoveAt.Issue10300Test() in /_/src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CarouselViewUITests.RemoveAt.cs:line 25
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by SuthiYuvaraj** [comment]
> There are some CarouselView tests failing:
> 
> **Issue12574Test**
> 
> ```
>    at UITest.Appium.HelperExtensions.Wait(Func`1 query, Func`2 satisfactory, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 2107
>    at UITest.Appium.HelperExtensions.WaitForAtLeastOne(Func`1 query, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 2124
>    at UITest.Appium.HelperExtensions.WaitForElement(IApp app, String marked, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency, Nullable`1 postTimeout) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 651
>    at Microsoft.Maui.TestCases.Tests.Issues.CarouselViewLoopNoFreeze.Issue12574Test() in /_/src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CarouselViewUITests.LoopNoFreeze.cs:line 44
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
> ```
> 
> **Issue10300Test**
> 
> ```
>    at UITest.Appium.HelperExtensions.Wait(Func`1 query, Func`2 satisfactory, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 2107
>    at UITest.Appium.HelperExtensions.WaitForAtLeastOne(Func`1 query, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 2124
>    at UITest.Appium.HelperExtensions.WaitForElement(IApp app, String marked, String timeoutMessage, Nullable`1 timeout, Nullable`1 retryFrequency, Nullable`1 postTimeout) in /_/src/TestUtils/src/UITest.Appium/HelperExtensions.cs:line 651
>    at Microsoft.Maui.TestCases.Tests.Issues.CarouselViewRemoveAt.Issue10300Test() in /_/src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CarouselViewUITests.RemoveAt.cs:line 25
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
> ```

Hi @jsuarezruiz , The above-mentioned two issues are unrelated to our fix. Additionally, the timeout exception is not reproducible locally. Can we try re-running the tests once more?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Could you include an UITest to validate all the values for the **ItemsUpdatingScrollMode** property?

```
using System.Collections.ObjectModel;

namespace Maui.Controls.Sample.Issues
{
	[Issue(IssueTracker.Github, 25991, "CarouselView reverts to displaying 1st item in collection when collection modified", PlatformAffected.UWP)]
	public class Issue25991 : ContentPage
	{
		public class Issue25991Model
		{
			public string Text { get; set; }
		}

		ObservableCollection<Issue25991Model> _collection = new ObservableCollection<Issue25991Model>()
		{
			new Issue25991Model() { Text = "Item 1" },
			new Issue25991Model() { Text = "Item 2" }
		};

		Label InfoLabel { get; set; }
		CarouselView TestCarouselView { get; set; }

		public Issue25991()
		{
			StackLayout mainStackLayout = new StackLayout();
			mainStackLayout.Margin = new Thickness(5);

			Label labelInstructions = new Label()
			{
				AutomationId = "WaitForStubControl",
				Text = "Instructions:\nThe CarouselView contains Item 1 and Item 2. It will initially show the first page, Item 1.\n" +
				"Click the 'Scroll to Item 2' button, and the CarouselView will correctly show Item 2.\n" +
				"Click 'Add Item', which will add a new Item record to the collection.\n" +
				"The CarouselView must stay in the Item 2."
			};
			mainStackLayout.Add(labelInstructions);

			InfoLabel = new Label()
			{
				AutomationId = "InfoLabel",
			};

			mainStackLayout.Add(InfoLabel);

			TestCarouselView = new CarouselView()
			{
				ItemsUpdatingScrollMode = ItemsUpdatingScrollMode.KeepScrollOffset,
				ItemsSource = _collection,
				Loop = false
			};

			TestCarouselView.ItemTemplate = new DataTemplate(() =>
			{
				StackLayout stackLayout = new StackLayout();
				Label nameLabel = new Label();
				nameLabel.SetBinding(Label.TextProperty, "Text");
				nameLabel.FontSize = 25;
				nameLabel.TextColor = Colors.Red;
				stackLayout.Children.Add(nameLabel);
				return stackLayout;
			});

			TestCarouselView.CurrentItemChanged += OnTestCarouselViewCurrentItemChanged;
			mainStackLayout.Add(TestCarouselView);

			Button scrollToPerson2Button = new Button()
			{
				AutomationId = "ScrollToPerson2Button",
				Text = "Scroll to Item 2"
			};
			scrollToPerson2Button.Clicked += OnScrollToPerson2ButtonClicked;
			mainStackLayout.Add(scrollToPerson2Button);

			Button addItemButton = new Button()
			{
				AutomationId = "AddItemButton",
				Text = "Add Item",
			};
			addItemButton.Clicked += OnAddButtonClicked;
			mainStackLayout.Add(addItemButton);


			HorizontalStackLayout buttonsStackLayout = new HorizontalStackLayout();
			Button keepItemsInViewButton = new Button()
			{
				AutomationId = "KeepItemsInViewButton",
				Text = "keepItemsInView",
			};
			keepItemsInViewButton.Clicked += OnKeepItemsInViewButtonClicked;
			buttonsStackLayout.Add(keepItemsInViewButton);
			Button keepScrollOffsetButton = new Button()
			{
				AutomationId = "KeepScrollOffsetButton",
				Text = "KeepScrollOffset",
			};
			keepScrollOffsetButton.Clicked += OnKeepScrollOffsetButtonClicked;
			buttonsStackLayout.Add(keepScrollOffsetButton);
			Button keepLastItemInViewButton = new Button()
			{
				AutomationId = "KeepLastItemInViewButton",
				Text = "KeepLastItemInView",
			};
			keepLastItemInViewButton.Clicked += OnKeepLastItemInViewButtonClicked;
			buttonsStackLayout.Add(keepLastItemInViewButton);
			mainStackLayout.Add(buttonsStackLayout);

			Content = mainStackLayout;
		}

		void OnTestCarouselViewCurrentItemChanged(object sender, CurrentItemChangedEventArgs e)
		{
			InfoLabel.Text = TestCarouselView.Position.ToString();
		}

		void OnScrollToPerson2ButtonClicked(object sender, EventArgs e)
		{
			TestCarouselView.ScrollTo(1);
		}

		void OnAddButtonClicked(object sender, EventArgs e)
		{
			_collection.Add(new Issue25991Model()
			{
				Text = "Item " + (_collection.Count + 1),
			});
		}

		void OnKeepItemsInViewButtonClicked(object sender, EventArgs e)
		{
			TestCarouselView.ItemsUpdatingScrollMode = ItemsUpdatingScrollMode.KeepItemsInView;
		}

		void OnKeepScrollOffsetButtonClicked(object sender, EventArgs e)
		{
			TestCarouselView.ItemsUpdatingScrollMode = ItemsUpdatingScrollMode.KeepScrollOffset;
		}

		void OnKeepLastItemInViewButtonClicked(object sender, EventArgs e)
		{
			TestCarouselView.ItemsUpdatingScrollMode = ItemsUpdatingScrollMode.KeepLastItemInView;
		}
	}
}
```

**Comment by SuthiYuvaraj** [comment]
> Could you include an UITest to validate all the values for the **ItemsUpdatingScrollMode** property?
> 
> ```
> using System.Collections.ObjectModel;
> 
> namespace Maui.Controls.Sample.Issues
> {
> 	[Issue(IssueTracker.Github, 25991, "CarouselView reverts to displaying 1st item in collection when collection modified", PlatformAffected.UWP)]
> 	public class Issue25991 : ContentPage
> 	{
> 		public class Issue25991Model
> 		{
> 			public string Text { get; set; }
> 		}
> 
> 		ObservableCollection<Issue25991Model> _collection = new ObservableCollection<Issue25991Model>()
> 		{
> 			new Issue25991Model() { Text = "Item 1" },
> 			new Issue25991Model() { Text = "Item 2" }
> 		};
> 
> 		Label InfoLabel { get; set; }
> 		CarouselView TestCarouselView { get; set; }
> 
> 		public Issue25991()
> 		{
> 			StackLayout mainStackLayout = new StackLayout();
> 			mainStackLayout.Margin = new Thickness(5);
> 
> 			Label labelInstructions = new Label()
> 			{
> 				AutomationId = "WaitForStubControl",
> 				Text = "Instructions:\nThe CarouselView contains Item 1 and Item 2. It will initially show the first page, Item 1.\n" +
> 				"Click the 'Scroll to Item 2' button, and the CarouselView will correctly show Item 2.\n" +
> 				"Click 'Add Item', which will add a new Item record to the collection.\n" +
> 				"The CarouselView must stay in the Item 2."
> 			};
> 			mainStackLayout.Add(labelInstructions);
> 
> 			InfoLabel = new Label()
> 			{
> 				AutomationId = "InfoLabel",
> 			};
> 
> 			mainStackLayout.Add(InfoLabel);
> 
> 			TestCarouselView = new CarouselView()
> 			{
> 				ItemsUpdatingScrollMode = ItemsUpdatingScrollMode.KeepScrollOffset,
> 				ItemsSource = _collection,
> 				Loop = false
> 			};
> 
> 			TestCarouselView.ItemTemplate = new DataTemplate(() =>
> 			{
> 				StackLayout stackLayout = new StackLayout();
> 				Label nameLabel = new Label();
> 				nameLabel.SetBinding(Label.TextProperty, "Text");
> 				nameLabel.FontSize = 25;
> 				nameLabel.TextColor = Colors.Red;
> 				stackLayout.Children.Add(nameLabel);
> 				return stackLayout;
> 			});
> 
> 			TestCarouselView.CurrentItemChanged += OnTestCarouselViewCurrentItemChanged;
> 			mainStackLayout.Add(TestCarouselView);
> 
> 			Button scrollToPerson2Button = new Button()
> 			{
> 				AutomationId = "ScrollToPerson2Button",
> 				Text = "Scroll to Item 2"
> 			};
> 			scrollToPerson2Button.Clicked += OnScrollToPerson2ButtonClicked;
> 			mainStackLayout.Add(scrollToPerson2Button);
> 
> 			Button addItemButton = new Button()
> 			{
> 				AutomationId = "AddItemButton",
> 				Text = "Add Item",
> 			};
> 			addItemButton.Clicked += OnAddButtonClicked;
> 			mainStackLayout.Add(addItemButton);
> 
> 
> 			HorizontalStackLayout buttonsStackLayout = new HorizontalStackLayout();
> 			Button keepItemsInViewButton = new Button()
> 			{
> 				AutomationId = "KeepItemsInViewButton",
> 				Text = "keepItemsInView",
> 			};
> 			keepItemsInViewButton.Clicked += OnKeepItemsInViewButtonClicked;
> 			buttonsStackLayout.Add(keepItemsInViewButton);
> 			Button keepScrollOffsetButton = new Button()
> 			{
> 				AutomationId = "KeepScrollOffsetButton",
> 				Text = "KeepScrollOffset",
> 			};
> 			keepScrollOffsetButton.Clicked += OnKeepScrollOffsetButtonClicked;
> 			buttonsStackLayout.Add(keepScrollOffsetButton);
> 			Button keepLastItemInViewButton = new Button()
> 			{
> 				AutomationId = "KeepLastItemInViewButton",
> 				Text = "KeepLastItemInView",
> 			};
> 			keepLastItemInViewButton.Clicked += OnKeepLastItemInViewButtonClicked;
> 			buttonsStackLayout.Add(keepLastItemInViewButton);
> 			mainStackLayout.Add(buttonsStackLayout);
> 
> 			Content = mainStackLayout;
> 		}
> 
> 		void OnTestCarouselViewCurrentItemChanged(object sender, CurrentItemChangedEventArgs e)
> 		{
> 			InfoLabel.Text = TestCarouselView.Position.ToString();
> 		}
> 
> 		void OnScrollToPerson2ButtonClicked(object sender, EventArgs e)
> 		{
> 			TestCarouselView.ScrollTo(1);
> 		}
> 
> 		void OnAddButtonClicked(object sender, EventArgs e)
> 		{
> 			_collection.Add(new Issue25991Model()
> 			{
> 				Text = "Item " + (_collection.Count + 1),
> 			});
> 		}
> 
> 		void OnKeepItemsInViewButtonClicked(object sender, EventArgs e)
> 		{
> 			TestCarouselView.ItemsUpdatingScrollMode = ItemsUpdatingScrollMode.KeepItemsInView;
> 		}
> 
> 		void OnKeepScrollOffsetButtonClicked(object sender, EventArgs e)
> 		{
> 			TestCarouselView.ItemsUpdatingScrollMode = ItemsUpdatingScrollMode.KeepScrollOffset;
> 		}
> 
> 		void OnKeepLastItemInViewButtonClicked(object sender, EventArgs e)
> 		{
> 			TestCarouselView.ItemsUpdatingScrollMode = ItemsUpdatingScrollMode.KeepLastItemInView;
> 		}
> 	}
> }
> ```

Hi @jsuarezruiz ,We have added the UITest cases to validate all the values for the `ItemsUpdatingScrollMode` property. Let us know if any further modifications are needed.

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25991.cs [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+		public Issue25991(TestDevice device)
+			: base(device)
+		{ }
+
+		public override string Issue => "CarouselView reverts to displaying first item in collection when collection modified";
+
+		[Test]
+		[Category(UITestCategories.CarouselView)]
+		public void Issue25991Test()
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25991.cs:21]: The test is failing on Windows:

```
Assert.That(actual, Is.EqualTo(expected))
String lengths are both 1. Strings differ at index 0.
Expected: "1"
But was:  "0"
```

File: src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs [hunk 4]
```diff
@@ -354,6 +357,16 @@ int GetPositionWhenAddingItems(int carouselPosition, int currentItemPosition)
 			return currentItemPosition != -1 ? currentItemPosition : carouselPosition;
 		}
 
+		private int GetTargetPosition()
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs:360]: These tests are failing on iOS:
image

Could verify if are related with the changes?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs (hunk 4 above)
Comment (SuthiYuvaraj) [reply src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs:360]: Yes @jsuarezruiz  , The testcase failure is related to my code changes 
Issue8964 - As `ItemsUpdatingScrollMode.KeepItemsInView` is the default behavior; it scrolls to the first item when the collection is modified. The flickering issue occurs when using `KeepScrollOffset`. Hence, this case has been ignored on iOS, and a separate issue report has been logged. 
Issue Link : https://github.com/dotnet/maui/issues/27773

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25991.cs (hunk 3 above)
Comment (jsuarezruiz) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25991.cs:21]: Retrying.

File: src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs [hunk 5]
```diff
@@ -267,6 +267,16 @@ void CollectionItemsSourceChanged(object sender, System.Collections.Specialized.
 				return;
 			}
 
+			// While Modifying the collection we should consider the ItemsUpdatingScrollMode to update the position
+			if (Carousel.ItemsUpdatingScrollMode == ItemsUpdatingScrollMode.KeepLastItemInView)
+			{
+				carouselPosition = count - 1;
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs:273]: What if count is 0? this will be trying t scroll to -1 ?

File: src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs [hunk 6]
```diff
@@ -354,6 +357,16 @@ int GetPositionWhenAddingItems(int carouselPosition, int currentItemPosition)
...
+		{
+			return ItemsView.ItemsUpdatingScrollMode switch
+			{
+				ItemsUpdatingScrollMode.KeepItemsInView => 0,
+				ItemsUpdatingScrollMode.KeepLastItemInView => ItemsSource.ItemCount - 1,
```
Comment (rmarinho) [inline src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs:365]: Same here what happens if ItemCount is 0 ?

**Review by rmarinho — CHANGES_REQUESTED** [review]

**Review by rmarinho — APPROVED** [review]

**Review by rmarinho — CHANGES_REQUESTED** [review]
Test is failing on windows, Mac and Android..

https://dev.azure.com/xamarin/public/_build/results?buildId=137724&view=ms.vss-test-web.build-test-results-tab&runId=3894113&resultId=100015&paneView=debug

**Comment by SuthiYuvaraj** [comment]
> Test is failing on windows, Mac and Android..
> 
> https://dev.azure.com/xamarin/public/_build/results?buildId=137724&view=ms.vss-test-web.build-test-results-tab&runId=3894113&resultId=100015&paneView=debug

Hi @rmarinho, I have updated the code changes. Let me know if anyother concerns.

File: src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs [hunk 7]
```diff
@@ -267,13 +267,30 @@ void CollectionItemsSourceChanged(object sender, System.Collections.Specialized.
 				return;
 			}
 
+			// While Modifying the collection we should consider the ItemsUpdatingScrollMode to update the position
+			if (Carousel.ItemsUpdatingScrollMode == ItemsUpdatingScrollMode.KeepLastItemInView)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs:271]: Can simplify it:

```
if (Carousel.ItemsUpdatingScrollMode == ItemsUpdatingScrollMode.KeepLastItemInView)
    carouselPosition = (count == 0) ? 0 : count - 1;
else if (Carousel.ItemsUpdatingScrollMode == ItemsUpdatingScrollMode.KeepItemsInView)
    carouselPosition = 0;
```

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8964.cs [hunk 8]
```diff
@@ -1,4 +1,5 @@
-﻿#if TEST_FAILS_ON_CATALYST && TEST_FAILS_ON_WINDOWS && TEST_FAILS_ON_ANDROID //The Position property now functions correctly on Android and Windows, issue: https://github.com/dotnet/maui/issues/15443. Note that on Catalyst, swipe and drag options are not supported in Appium.
+﻿#if TEST_FAILS_ON_CATALYST && TEST_FAILS_ON_WINDOWS && TEST_FAILS_ON_ANDROID && TEST_FAILS_ON_IOS //The Position property now functions correctly on Android and Windows, issue: https://github.com/dotnet/maui/issues/15443. Note that on Catalyst, swipe and drag options are not supported in Appium.
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8964.cs:1]: Now, on Catalyst, the Appium drag actions should be supported. However, probably you will get the same result than on iOS. But, to avoid future confusion, could update the comment?

File: src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs (hunk 7 above)
Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs:271]: I think is better to keep as is to better understand the different positions we want

**Review by rmarinho — DISMISSED** [review]

**Review by jsuarezruiz — COMMENTED** [review]
I am going to re-run the Windows UITests. The test CarouselViewPositionFromVisibilityChangeTest is failing and seems that could be related with the changes.
image

File: src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs (hunk 7 above)
Comment (SuthiYuvaraj) [reply src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs:271]: Hi @jsuarezruiz , I agree with that. Keeping it as it is will provide better clarity in understanding the different positions we want to define.

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8964.cs (hunk 8 above)
Comment (SuthiYuvaraj) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8964.cs]: I have modified the comments; kindly review the changes and let me know if you have any concerns.

**Review by rmarinho — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]
Ok, It's ok for the Flight branch
