### PR TITLE
[Android] Update the adapter used by RecyclerViewScrollListener

### LINKED ISSUE #6328: CarouselView Position property not updating after changing ItemsSource
### Description

When you set `Loop="False"` and change the ItemsSource through binding (directly in code not tested), the `Position` property is not updated when swiping through items.

When you set `Loop="True"`, it works as expected.

There is something weird; when you re-apply the binding of the original collection that was bound at first startup, it magically works again 🤷‍♂️

On windows the `Position` property doesn't work _at all_, iOS seems fine.

### Steps to Reproduce

1. Download this repro project
[CarouselViewPositionBug.zip](https://github.com/dotnet/maui/files/8524501/CarouselViewPositionBug.zip)

2. Start debugging in an emulator and start swiping, you'll see it'll work as expected.

3. Click on `Category 1` and start swiping again, you'll see the position remains 0.

4. Click on `Category 0` and you'll see it magically works again

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 5.0 and up, Windows latest

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #6457: App crashes when changing CarouselView Loop property at runtime
### Description

When you have `Loop="True"` defined on a `CarouselView` in XAML, and you change it while debugging to `Loop="False"` and do one swipe, the app crashes.

Not sure if this really is a bug, or this has something to do with Hot Reload.

But due to #6328, I find it worthy to mention it anyway.

Sometimes it gives this exception:

`Java.Lang.IndexOutOfBoundsException
  Message=Inconsistency detected. Invalid view holder adapter positionTemplatedItemViewHolder{2931e3f position=15 id=-1, oldPos=-1, pLpos:-1 no parent} crc645d80431ce5f73f11.MauiCarouselRecyclerView{7e3cfb5 VFED..... ........ 0,0-480,534}, adapter:crc645d80431ce5f73f11.CarouselViewAdapter_2@213f7ab, layout:androidx.recyclerview.widget.LinearLayoutManager@8d6a697, context:crc64e40959fc36668bf1.MainActivity@91f982b`

And sometimes it gives this exception:

`Java.Lang.IndexOutOfBoundsException
  Message=Inconsistency detected. Invalid item position 6(offset:6).state:16384 crc645d80431ce5f73f11.MauiCarouselRecyclerView{36293e1 VFED..... ........ 0,201-480,830}, adapter:crc645d80431ce5f73f11.CarouselViewAdapter_2@1ac7153, layout:androidx.recyclerview.widget.LinearLayoutManager@59e6963, context:crc64b52dfc50fa3ba884.MainActivity@963ea9c`

### Steps to Reproduce

1. Download this repro project
[CarouselViewPositionBug.zip](https://github.com/dotnet/maui/files/8524501/CarouselViewPositionBug.zip)

2. Open `MainPage.xaml` and CTRL+F for `ItemSwiper`.

3. Change `Loop="False"` to `Loop="True"`.

4. Start debugging.

5. Change `Loop="True"` to `Loop="False"`.

6. Swipe and observe the crash.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 5.0 and up

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #6521: CarouselView crashes with Loop="True"
### Description

Creating a CarouselView and setting Loop="True" causes a Java.Lang.IllegalStateException exception:

Java.Lang.IllegalStateException
  Message=The specified child already has a parent. You must call removeView() on the child's parent first.

Setting Loop="False" it works as expected

Please see attached example.

[CarouselViewIssue.zip](https://github.com/dotnet/maui/files/8567573/CarouselViewIssue.zip)
.

### Steps to Reproduce

1. Create new .Net Maui App (Preview)
2. Update MainPage.xaml to include a CarouselView with Loop="True" parameter.
3. Add Content to the CarouselView
`
   <CarouselView.ItemsSource>
                <x:Array Type="{x:Type ContentView}">
                    <ContentView>
                        <StackLayout BackgroundColor="Blue" />
                    </ContentView>
                    <ContentView>
                        <StackLayout BackgroundColor="Red" />
                    </ContentView>
                </x:Array>
            </CarouselView.ItemsSource>
`
5. Run the app
6. Crashes
7. Set the Loop parameter to Loop="False"
8. Run the app
9. Works as expected.

      

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Only tested on Android 11 - API 30

### Did you find any workaround?

Only to use Loop=False, but I would like it to loop.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

When the ItemsSource/Adapter was changing we weren't updating the reference on the scrollviewer so we could't get the right position.

Did some other cleanup

### Issues Fixed

Fixes #6328 
Fixes #6457

Use the following page to test - Make sure position changes on load, then change categor on top, position should reset to 0,  and swipe again to see if position updates properly. 

```
	public partial class CarouselDemo : ContentPage
	{
		Color GetColor(int page) => page switch
		{
			0 => Colors.DarkRed,
			1 => Colors.DarkGreen,
			2 => Colors.DarkBlue,
			3 => Colors.DarkOrange,
			4 => Colors.DarkOliveGreen,
			_ => null
		};

		public CarouselDemo()
		{
			List<Category> categories = new List<Category>();

			for (int cat = 0; cat < 4; cat++)
			{
				var category = new Category()
				{
					Col = cat,
					Name = $"Category {cat}"
				};

				for (int page = 0; page < 5; page++)
				{
					var items = new List<Item>();

					for (int col = 0; col < 5; col++)
					{
						for (int row = 0; row < 6; row++)
						{
							items.Add(new Item()
							{
								Name = $"Categ {cat}, page {page}",
								Col = col,
								Row = row,
								Color = GetColor(page)
							});
						}
					}

					category.Items.Add(new Pager<Item>(page, items));
				}

				categories.Add(category);
			}

			Categories.Add(new Pager<Category>(0, categories));

			CurrentCategory = Categories[0][0];

			BindingContext = this;
			InitializeComponent();
		}

		public List<Pager<Category>> Categories { get; } = new List<Pager<Category>>();

		private Category currentCategory;
		public Category CurrentCategory
		{
			get => currentCategory;
			set
			{
				currentCategory = value;
				OnPropertyChanged();
			}
		}

		private void CategBtn_Clicked(object sender, EventArgs e)
		{
			if (sender is Button b && b.BindingContext is Category cat)
				CurrentCategory = cat;
		}
	}
	public abstract class BaseClass
	{
		public int Row { get; set; }
		public int Col { get; set; }

		public string Name { get; set; }
	}
	public class Category : BaseClass
	{
		public List<Pager<Item>> Items { get; } = new List<Pager<Item>>();
	}
	public class Item : BaseClass
	{
		public Color Color { get; set; }
	}
	public class Pager<T> : List<T>
	{
		public Pager(int page, IEnumerable<T> items) : base(items)
		{
			PageIndex = page;
		}

		public int PageIndex { get; }
	}
```

XAML

```
  <ContentPage.Resources>

        <DataTemplate x:Key="CategView">
            <Grid BindableLayout.ItemsSource="{Binding}" ColumnSpacing="5"
                  ColumnDefinitions="*,*,*,*">

                <BindableLayout.ItemTemplate>

                    <DataTemplate>

                        <Button x:Name="CategBtn"
                                Grid.Column="{Binding Col}"
                                Background="DarkRed"
                                Clicked="CategBtn_Clicked"
                                CornerRadius="0"
                                FontSize="16"
                                LineBreakMode="WordWrap"
                                Text="{Binding Name}" />

                    </DataTemplate>

                </BindableLayout.ItemTemplate>
            </Grid>
        </DataTemplate>

        <DataTemplate x:Key="ItemView">
            <Grid BindableLayout.ItemsSource="{Binding}"
                  ColumnDefinitions="*,*,*,*,*"
                  ColumnSpacing="5"
                  RowDefinitions="*,*,*,*,*,*"
                  RowSpacing="5">

                <BindableLayout.ItemTemplate>

                    <DataTemplate>

                        <Button Grid.Row="{Binding Row}"
                                Grid.Column="{Binding Col}"
                                Background="{Binding Color}"
                                CornerRadius="0"
                                FontSize="14"
                                LineBreakMode="WordWrap"
                                Text="{Binding Name}"
                                TextColor="White" />

                    </DataTemplate>

                </BindableLayout.ItemTemplate>

            </Grid>
        </DataTemplate>

    </ContentPage.Resources>

    <Grid RowDefinitions="Auto,0.25*,*" RowSpacing="5">

        <Label FontSize="24"
               HorizontalTextAlignment="Center"
               TextColor="Green"
               VerticalTextAlignment="Center">
            <Label.Text>
                <MultiBinding StringFormat="Position: {0}">
                    <Binding Path="Position"
                             Source="{x:Reference ItemSwiper}" />
                </MultiBinding>
            </Label.Text>
        </Label>

        <CarouselView Grid.Row="1"
                      ItemTemplate="{StaticResource CategView}"
                      ItemsSource="{Binding Categories}"
                      Loop="False">

            <CarouselView.ItemsLayout>
                <LinearItemsLayout Orientation="Horizontal"
                                   SnapPointsAlignment="Start"
                                   SnapPointsType="MandatorySingle" />
            </CarouselView.ItemsLayout>

        </CarouselView>

        <CarouselView x:Name="ItemSwiper"
                      Grid.Row="2"
                      Background="Yellow"
                      ItemTemplate="{StaticResource ItemView}"
                      ItemsSource="{Binding CurrentCategory.Items}"
                      Loop="False">

            <CarouselView.ItemsLayout>
                <LinearItemsLayout Orientation="Horizontal"
                                   SnapPointsAlignment="Start"
                                   SnapPointsType="MandatorySingle" />
            </CarouselView.ItemsLayout>

        </CarouselView>

    </Grid>
    ```

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/Android/Adapters/ItemsViewAdapter.cs [hunk 1]
```diff
@@ -43,11 +43,7 @@ protected virtual TItemsViewSource CreateItemsSource()
 
 		protected virtual void ItemsViewPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs property)
 		{
-			if (property.Is(Microsoft.Maui.Controls.ItemsView.ItemsSourceProperty))
```
Comment (hartez) [inline src/Controls/src/Core/Handlers/Items/Android/Adapters/ItemsViewAdapter.cs:46]: Why are we no longer updating the ItemsSource when it changes?

**Review by hartez — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Handlers/Items/Android/Adapters/ItemsViewAdapter.cs (hunk 1 above)
Comment (rmarinho) [reply src/Controls/src/Core/Handlers/Items/Android/Adapters/ItemsViewAdapter.cs:46]: The mapper does this

**Review by hartez — APPROVED** [review]
