### PR TITLE
Fix RefreshView specificity on IsRefreshing

### LINKED ISSUE #16910: [regression/8.0.0] - RefreshView does not hide spinner when IsRefreshing set to false.
### Description

The `RefreshView` control does not hide the spinner after the refresh operation completes and `IsRefreshing` is set to false. Same code worked fine in .NET 7.

### Steps to Reproduce

1. Clone this repo https://github.com/RobTF/mauiplay/tree/net8/CollectionViewIssue
2. Run on Android
3. Tap "Go to test page"
4. Pull to refresh
5. Observe refresh spinner does not disappear.

### Link to public reproduction project repository

https://github.com/RobTF/mauiplay/tree/net8/CollectionViewIssue

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Android

### Affected platform versions

Android 13, Android 14

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

Fixes specificity on RefreshView 

this is work to get https://github.com/dotnet/maui/issues/16654 fixed

### Issues Fixed

Fixes #16910

### CODE REVIEW

File: src/Controls/tests/DeviceTests/Elements/RefreshView/RefreshViewTests.cs [hunk 1]
```diff
@@ -20,6 +25,164 @@ void SetupBuilder()
 				});
 			});
 		}
+
+
+// 		[Fact(DisplayName = "IsRefreshing binding works")]
```
Comment (mattleibow) [inline src/Controls/tests/DeviceTests/Elements/RefreshView/RefreshViewTests.cs:30]: We need to track this in an issue and get it working to RC 2

**Review by mattleibow — APPROVED** [review]
