### PR TITLE
`Size` and `SizeF` should not throw on `NaN`

### LINKED ISSUE #16571: "System.ArgumentException: NaN is not a valid value for height" from `Rect.Size` getter
### Description

Very many reports in the wild of this issue from AppCenter. the stack doesn't include any of my code, though it didn't happen until I started implementing LayoutManager overrides (though, oddly, I never overrode anything for AbsoluteLayout).

Nearest I can figure is that somewhere a NaN is slipping in, and then later Rect.Size() is tripping over it, which builds a new Size object from the width and height on demand.

So either Rect needs to be made impossible to have a NaN Width/Height so that this condition can be caught and prevented at the source, or the Size getter needs to return some other valid value when the Width or Height is NaN. Getters should not throw exceptions.

```
Microsoft.Maui.Graphics.Size..ctor(Double width, Double height)
Microsoft.Maui.Graphics.Rect.get_Size()
Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds)
Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds)
Microsoft.Maui.Layouts.AbsoluteLayoutManager.ArrangeChildren(Rect bounds)
Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Rect bounds)
Microsoft.Maui.Platform.LayoutViewGroup.OnLayout(Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b)
Android.Views.ViewGroup.n_OnLayout_ZIIII(IntPtr , IntPtr , Boolean , Int32 , Int32 , Int32 , Int32 )
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V , IntPtr , IntPtr , Boolean , Int32 , Int32 , Int32 , Int32 )
```

### Steps to Reproduce

I do not know how to reproduce it.

### Link to public reproduction project repository

n/a

### Version with bug

7.0.81

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 11, 12, 13

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

The other primitives are fine with `NaN`:

* `Point`
* `PointF`
* `Rect`
* `RectF`

In fact, `Rect.Size` may throw because the `Rect` handles `NaN` but the `Size` instance does not.

### Issues Fixed

Fixes #16571

Possible alternative:

- https://github.com/dotnet/maui/pull/18971

### CODE REVIEW

File: src/Graphics/src/Graphics/Size.cs [hunk 1]
```diff
@@ -10,93 +10,62 @@ namespace Microsoft.Maui.Graphics
...
-
 		public static readonly Size Zero;
 
 		public Size(double size = 0)
 		{
-			if (double.IsNaN(size))
-				throw new ArgumentException("NaN is not a valid value for size");
-			_width = size;
-			_height = size;
+			Width = size;
```
Comment (jsuarezruiz) [inline src/Graphics/src/Graphics/Size.cs:17]: Could we include some unit tests accepting NaN values to cover any unexpected change/behavior in the future?

**Comment by jsuarezruiz** [comment]
Related PR https://github.com/dotnet/maui/pull/18971

**Review by PureWeen — APPROVED** [review]
