### PR TITLE
[Android] Fix SwipeItemView size issues

### LINKED ISSUE #6018: SwipeView custom items are not rendering
### Description

_Visual Studio Version 17.2.0 Preview 3.0_

https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/swipeview#custom-swipe-items
This documentation samples shows custom content in the swipable side-menu. 
Normal item is` <SwipeItem>`
Custom item is `<SwipeItemView>`

Anything that I put into `<SwipeItemView>` is not rendered.

Expected behavior: `<SwipeItemView>` content is rendered

_**Please fix the problem as soon as possible. I thought I could finally ship test apps to our clients when the RC 1 blog post says cross-platform development ready but this whole feature is missing.**_

### Steps to Reproduce

New MAUI app from template with some quick SwipeView tests in MainPage.
[MauiApp1.zip](https://github.com/dotnet/maui/files/8476860/MauiApp1.zip)

Run on Sony Xperia 5 Android 11 API 30

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (API 30)

### Did you find any workaround?

no

### Relevant log output

_No response_

### LINKED ISSUE #10065: SwipeItemView does not work
### Description

In my application, I am unable to swipe and see the swipe item.  I am using SwipeItemView to define a custom swipe button.  When I swipe, the normally displayed view that I swipe on moves just a little bit, not enough to display the swipe item or even the area that it should take up.  The official swipe demo app does slide the swiped display, but does NOT display the custom SwipeItemView.  All the other swipe demos appear to work correctly.

Swiping in the direction that should reveal the swipe item does NOT display the swipe item.

Although I am getting slightly different results than the swipe demo, for a fix, I would suggest starting with the demo and get it working property.  The demo I am referring to is the official Maui demo app for swipe views, specifically the portion with Custom SwipeViewItem demo.  Specifically
https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/Views/SwipeViewDemos

Tested on Android 9 (Android Open Source Project).  I did not test on other platforms.

Same xaml layout works correctly in Xamarin.Forms

### Steps to Reproduce

Download https://github.com/dotnet/maui-samples from Github and unzip or clone repo locally.
Open SwpieViewDemos solution in Visual Studio
Run it, deploying to Android device or emulator (I used Android device running Android 9)
Tap on **SwipView custom SwipeItem**
Swipe on either button.

BUG: SwipeItemView does not display.

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/6.0/UserInterface/Views/SwipeViewDemos

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 9

### Did you find any workaround?

I have not tried a work around.  The only thing I can think of is to try to use a SwipeItem instead of SwipeItemView.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix SwipeItemView size issues on Android.

image

### Issues Fixed

Fixes #10065
Fixes #6018

### CODE REVIEW

File: src/Core/src/Platform/Android/MauiSwipeView.cs [hunk 1]
```diff
@@ -665,6 +665,12 @@ List<AView> GetNativeSwipeItems()
 
 		void UpdateSwipeItemViewLayout(ISwipeItemView swipeItemView)
 		{
+			if (swipeItemView?.Handler is not IPlatformViewHandler handler)
+				return;
+
+			var swipeItemSize = GetSwipeItemSize(swipeItemView);
+			handler.LayoutVirtualView(0, 0, (int)swipeItemSize.Width, (int)swipeItemSize.Height);
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/MauiSwipeView.cs:672]: This is the main change. 

`View.Arrange(new Rectangle(Point.Zero, size));`

Doesn't seem to work as expected.

**Review by hartez — APPROVED** [review]

**Comment by AswinPG** [comment]
When can we expect a release with this fix... :)

**Review by rmarinho — APPROVED** [review]
