### PR TITLE
Preserve the correct binding context for menu items

### LINKED ISSUE #5382: Command bound with MenuFlyoutItem is not getting executed, whereas Clicked event is working fine
### Description

Defined a Menu structure in a Content page and added Command to the MenuFlyoutItem, but the Command is not getting executed when invoked. Whereas Clicked event is working fine.

Note: BindingContext is set to the instance of the ViewModel type.

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Add the menu structure to the ContentPage as shown below
3. Define a ViewModel with a Command in it
4. Bound the MenuFlyoutItem to the Command in the ViewModel
5. Set the BindingContext of the ContentPage to the instance of the ViewModel
6. Update the Application MainPage to a NavigationPage containing this ContentPage
7. Build and run the project on any of the supported target platforms (have tried with Android and Windows)
8. Invoke the  menu to trigger the Command, but it's not getting executed

```xml
<ContentPage.MenuBarItems>
    <MenuBarItem Text="File">
        <MenuFlyoutItem Command="{Binding TestCommand}" Text="Test" />
    </MenuBarItem>
</ContentPage.MenuBarItems>
```
App.xaml.cs
```cs
MainPage = new NavigationPage(new MainPage());
```

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 31.0, Windows SDK 10.0.19041

### Did you find any workaround?

Nope (For now Clicked event works fine, executing the command method from there).

### Relevant log output

```shell
NA
```

### PR DESCRIPTION
**Pull request by mattleibow**
### Issues Fixed

Fixes #5382

### CODE REVIEW

**Comment by PureWeen** [comment]
> @PureWeen This PR is currently wrong because now adding the children to the menubar directly does not update parents.

That's "fine" :-) The `MenuBar` doesn't really support direct items being added and we don't really expose any direct points for users to do this. If users want global `MenuItems` than they just add them to the top most page.

File: src/Controls/src/Core/MenuBar.cs [hunk 1]
```diff
@@ -41,19 +37,24 @@ public void Add(IMenuBarItem item)
...
+				if (this.Contains(menuBarItem))
+					Remove(menuBarItem);
+
+				Insert(i, menuBarItem);
 			}
-		}
 
-		internal void ReplaceWith(IList<MenuBarItem> menuBarItems)
-		{
-			Clear();
```
Comment (PureWeen) [inline src/Controls/src/Core/MenuBar.cs:54]: This was really supposed to just be temporary and might be causing some additional unknown weirdness.

**Review by hartez — APPROVED** [review]
