### PR TITLE
[iOS] PullToRefresh activity indicator improvements - fix

### LINKED ISSUE #20723: PullToRefresh activity indicator hidden behind header in CollectionView
### Description

I'm using a CollectionView which is wrapped into a RefreshView in order to benefit from the PullToRefresh capability. This is working fine as long as I'm not using a header in my CollectionView.
However, if I'm using a header and pull down on top to refresh my collection, the activity indicator is hidden behind the header instead of being shown on top.

| CollectionView without header | CollectionView with header |
|:-:|:-:|
| PullToRefresh_withoutHeader|PullToRefresh_withHeader|

### Steps to Reproduce

1. Run the sample app from the reproduction repository
2. Use PullToRefresh

### Link to public reproduction project repository

https://github.com/metalium84/dotnet-maui-refreshview-bug

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17

### Did you find any workaround?

Unfortunately not.

### Relevant log output

_No response_

### LINKED ISSUE #24960: [iOS] RefreshView indicator not displayed when IsRefreshing is manually set to true and collectionView is at the top
### Description

The `RefreshView` indicator is not displayed when `IsRefreshing` is set to `true` manually (a filter change, ...) and if the `CollectionView` is already at the top.

If the `CollectionView` is scrolled, setting the value to `true` will scroll the `CollectionView` to the top and the indicator will be displayed.

On Android, everything's fine wherever you are in the `CollectionView`

https://github.com/user-attachments/assets/bd00bb69-5e27-4f42-a3c0-7732cfc7b11b

The indicator position is treated by https://github.com/dotnet/maui/issues/20723

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

https://github.com/taenito/maui-issues/tree/main/MauiAppRefreshViewManuallyIndicatorHidden

### Version with bug

9.0.30 SR3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/20723
Fixes https://github.com/dotnet/maui/issues/24960

|Before|After|
|--|--|
|<video src="https://github.com/dotnet/maui/assets/42434498/8d22c195-66fd-4be9-aace-53fe05006526" width="300px"/>|<video src="https://github.com/dotnet/maui/assets/42434498/a2217bd2-a5b5-410f-9479-4ac61c6b80e4" width="300px"/>|
|<video src="https://github.com/user-attachments/assets/88dcbf6b-479c-4e92-85fb-feaf01c63695" width="300px"/>|<video src="https://github.com/user-attachments/assets/c4cf916c-090e-4b4c-8caf-1ecb3a926e64" width="300px"/>|

The same issue happens with CV2
https://github.com/dotnet/maui/pull/20824#issuecomment-2707891709

```xaml
<Grid RowDefinitions="*">
    <RefreshView IsRefreshing="False">
        <CollectionView>
            <CollectionView.Header>
                <ContentView HeightRequest="200"
                                BackgroundColor="Green"/>
            </CollectionView.Header>
            <CollectionView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>Item 1</x:String>
                    <x:String>Item 2</x:String>
                    <x:String>Item 3</x:String>
                </x:Array>
            </CollectionView.ItemsSource>
        </CollectionView>
    </RefreshView>
</Grid>
```

### CODE REVIEW

File: src/Controls/tests/UITests/Tests/Issues/Issue20723.cs [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+		public async Task IndicatorShouldNotBeCoveredByHeader()
+		{
+			this.IgnoreIfPlatforms(new TestDevice[] { TestDevice.Android, TestDevice.Mac, TestDevice.Windows });
+			_ = App.WaitForElement("refreshView");
+
+			App.ScrollUp("refreshView", swipePercentage: 1);
+			await Task.Delay(500);
+
+			//The test passes if the activity indicator is above the header
+			VerifyScreenshot();
```
Comment (jsuarezruiz) [inline src/Controls/tests/UITests/Tests/Issues/Issue20723.cs:25]: `ValidateScreenshot ` will compare the screenshots pixel by pixel. Taking into account the animation of the position of the loading indicator as well as the rotation of the indicator itself, I would say that it would be better to create a device test to validate that it is within a range as well as the size.

Comment (kubaflo) [reply src/Controls/tests/UITests/Tests/Issues/Issue20723.cs:25]: You're right this test will probably fail in most of the cases. However, I'm not sure if the device test will be useful in this case. Maybe we should just not write a test for this issue?

Comment (jsuarezruiz) [reply src/Controls/tests/UITests/Tests/Issues/Issue20723.cs:25]: Yeah, i think in this case have sense a tests checking Frames etc. Take a look to the `GetRect `extension method used in UITests. Let me know if need help with something.

Comment (jsuarezruiz) [reply src/Controls/tests/UITests/Tests/Issues/Issue20723.cs:25]: image
The snapshot, with the loading indicator is not a valid option.

Also, can bind the status to a Label, and check in the test the text value Example: "Loading", "Not Loading".

Comment (kubaflo) [reply src/Controls/tests/UITests/Tests/Issues/Issue20723.cs:25]: I'm not sure how to get frames of this indicator in any other way than using XPath
Screenshot 2024-04-16 at 19 32 26

**Comment by taenito** [comment]
Any news on this bug? This is one of the latest bugs preventing us from publishing our application.

**Comment by kubaflo** [comment]
Here we go again lol. Hi, @metalium84  @taenito The MAUI team's priorities are not up to me, but you can have this fix in your app by following this @jfversluis's video if it is a major blocker for your migration https://www.youtube.com/watch?v=B2FOBjZKm9k&t=301s&pp=ygUWZ2VyYWxkIG1hdWkgcHIgdGVzdGluZw%3D%3D

**Comment by jfversluis** [comment]
> Here we go again lol. Hi, @metalium84 @taenito The MAUI team's priorities are not up to me, but you can have this fix in your app by following this @jfversluis's video if it is a major blocker for your migration https://www.youtube.com/watch?v=B2FOBjZKm9k&t=301s&pp=ygUWZ2VyYWxkIG1hdWkgcHIgdGVzdGluZw%3D%3D

If you do test this out and let us know if this works for you that will give us more confidence that this is a right fix and we can merge it sooner. So please let us know, thanks!

**Comment by taenito** [comment]
I tested the branch and the loader is no longer hidden behind the header.

We still have a lot of bugs with the `RefreshView` on iOS (I will open news issues) but for me, this MR works well for the given issue.

**Comment by kubaflo** [comment]
@taenito cool! Thanks for confirming it!

**Comment by kubaflo** [comment]
Hi, @taenito I've also added a commit that fixes your second issue https://github.com/dotnet/maui/issues/24960

**Comment by kubaflo** [comment]
This PR solves the same issue with CV2:
<video src="https://github.com/user-attachments/assets/589cc0f8-6f7d-415c-9513-b66062b3f712"/>

**Comment by mattyjjpearce** [comment]
Hi - any update on this fix. Still not been reviewed by the looks of it?

**Review by jfversluis — APPROVED** [review]
