### PR TITLE
[Catalyst] Fix Scrollbar does not align with FlowDirection change in ScrollView

### LINKED ISSUE #30095: [Catalyst] Scrollbar does not align with FlowDirection change in ScrollView
### Description

When setting FlowDirection=RightToLeft on a ScrollView in a .NET MAUI app running on Mac Catalyst, the scrollbar remains on the right side (LTR position) and does not move to the left as expected for RTL layouts. This issue occurs especially when changing the at runtime.

https://github.com/user-attachments/assets/00b653c6-2872-4f7c-825f-bd500148b88c

### Steps to Reproduce

1. Run the attached sample [ScrollViewOrientation 4.zip](https://github.com/user-attachments/files/20837182/ScrollViewOrientation.4.zip)
2. Change the FlowDirection as RightToLeft .
3. Observe the ScrollBar Position.

Actual Behavior:
On Mac Catalyst, the scrollbar remains on the right side even after setting FlowDirection to RightToLeft at runtime

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by devanathan-vaithiyanathan**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue details
On MacCatalyst, when flowdirection is change, the scrollbar stays at initial position doesn't update correctly, especially during runtime changes

### Description of Change

On Mac Catalyst, the scrollbar doesn't update based on FlowDirection changes at runtime, even in native macOS. As a workaround for this native limitation, the scroll indicators are toggled to force a refresh and reflect the correct direction.

### Issues Fixed

Fixes #30095 

### Regarding test case
For this case, it's not possible to write a test because the scrollbar does not appear during initial loading. It only becomes visible when a scroll action is performed, and even then, it remains visible only for a few seconds. 

**Tested the behavior in the following platforms.**
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

| Before  | After  |
|---------|--------|
| **Mac**<br> <video src="https://github.com/user-attachments/assets/c8c17464-8f53-4ccf-9054-da12ac424ddf" width="600" height="300"> | **Mac**<br> <video src="https://github.com/user-attachments/assets/758acfa0-3bdd-4fc8-bc26-c5101e319d51" width="600" height="300"> |

### CODE REVIEW

File: src/Core/src/Platform/iOS/MauiScrollView.cs [hunk 1]
```diff
@@ -58,6 +58,20 @@ public override void LayoutSubviews()
 				// arrangement with an adjusted starting point and recalculating the content offset.
 				if (_previousEffectiveUserInterfaceLayoutDirection != EffectiveUserInterfaceLayoutDirection)
 				{
+					// In mac platform, Scrollbar is not updated based on FlowDirection, so resetting the scroll indicators
+					// It's a native limitation; to maintain platform consistency, a hack fix is applied to show the Scrollbar based on the FlowDirection.
+					if (OperatingSystem.IsMacCatalyst() && _previousEffectiveUserInterfaceLayoutDirection is not null)
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/iOS/MauiScrollView.cs:63]: Could you include a related test?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/iOS/MauiScrollView.cs (hunk 1 above)
Comment (devanathan-vaithiyanathan) [reply src/Core/src/Platform/iOS/MauiScrollView.cs:63]: @jsuarezruiz , Adding a UI test in this case is not working properly because the scrollbar only appears during scrolling and disappears after a few seconds. It doesn't show during initial loading.

**Review by jsuarezruiz — APPROVED** [review]
