### PR TITLE
[Android] Fix issue clipping ImageButton

### LINKED ISSUE #5948: [mauipalooza] ImageButton isn't clipping on Android
### Description

```xaml
<ImageButton WidthRequest="64" HeightRequest="64"
                        Background="{StaticResource BlueGradient}"
                        Source="arrow_swap.png"
                             Grid.RowSpan="2"
                             VerticalOptions="Center"
                             HorizontalOptions="Center">
                    <ImageButton.Clip>
                        <EllipseGeometry RadiusX="32"
                                         RadiusY="32"
                                         Center="32,32"/>
                    </ImageButton.Clip>
                </ImageButton>
```

Screenshot_1649517397

https://github.com/davidortinau/dotnet-airlines

### Steps to Reproduce

Run the sample on Android

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

An earlier PR fixed the positioning of the EllipseGeometry so the Clip renders correctly, but does not apply to the background. This PR adds changes to include the background when Clipping.

Before
Screenshot_1654252278

After
Screenshot_1654252198

### Issues Fixed

Fixes #5948

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
> This can't go to net6.0, needs to go to main cc: @Redth

Changed to main, is correct?

**Comment by hartez** [comment]
@jsuarezruiz Needs to be targeted to net6.0 branch.

File: src/Core/src/Handlers/ImageButton/ImageButtonHandler.cs [hunk 1]
```diff
@@ -33,7 +33,7 @@ public partial class ImageButtonHandler : IImageButtonHandler
 			[nameof(IButtonStroke.StrokeColor)] = MapStrokeColor,
 			[nameof(IButtonStroke.CornerRadius)] = MapCornerRadius,
 			[nameof(IImageButton.Padding)] = MapPadding,
-#if WINDOWS
+#if ANDROID || WINDOWS
 			[nameof(IImageButton.Background)] = MapBackground,
 #endif
```
Comment (mattleibow) [inline src/Core/src/Handlers/ImageButton/ImageButtonHandler.cs:38]: What is the reason for this again on Android? I see the base view does all the same work:

image

Comment (rmarinho) [reply src/Core/src/Handlers/ImageButton/ImageButtonHandler.cs:38]: It's because we take the ImageMapper that already has a MapBackground that overrides this,

**Review by rmarinho — APPROVED** [review]
