### PR TITLE
Fix: Null Reference Exception in ShellContentFragment.Destroy

### LINKED ISSUE #29712: NullReferenceException in ShellContentFragment.Destroy When _shellContext Is Null
### Description

A System.NullReferenceException occurs in the ShellContentFragment.Destroy method when the _shellContext field is null. This happens during the destruction of a fragment, causing the app to crash.

**Stack Trace:**

```
System.NullReferenceException: Object reference not set to an instance of an object
        at Microsoft.Maui.Controls.Platform.Compatibility.ShellContentFragment.Destroy()(unknown)
        at Microsoft.Maui.Controls.Platform.Compatibility.ShellContentFragment.OnDestroy()(unknown)
        at AndroidX.Fragment.App.Fragment.n_OnDestroy(IntPtr jnienv, IntPtr native__this)(unknown)
        at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)(unknown)
```

### Steps to Reproduce

I was unable to reproduce

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.50 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9 and up

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by postalservice14**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Description of Change

This PR fixes a null reference exception in the ShellContentFragment.Destroy method for Android. The issue occurred when attempting to call RemoveAppearanceObserver on a possibly null ShellContext. The fix adds a null-conditional operator to safely access ShellContext before invoking the method.

### Issues Fixed

Fixes #29712

### CODE REVIEW

**Review by rmarinho — COMMENTED** [review]
I think using "as" seems better in this case.

Can we add a test?

**Comment by farneman** [comment]
@rmarinho, @jsuarezruiz, @StephaneDelcroix or @tj-devel709 What can we do to help get this moving? Our app is seeing increased problems as a result of this root issue so we'd really like to get it solved. 

It doesn't appear most of the checks on the PR ever reported in—how can those be restarted?

**Comment by nbuchert** [comment]
We have experienced this issue as well in our first .NET 9/MAUI app release 10 days ago.
According to Google this is especially related to devices with 3-4 GB RAM.
Is there any expected release date for this fix, as we are having 650+ users that are experiencing this crash?

**Comment by MartyIX** [comment]
> What can we do to help get this moving?

I believe that this is what needs to be done: https://github.com/dotnet/maui/pull/29713#pullrequestreview-2875414224

**Comment by postalservice14** [comment]
> > What can we do to help get this moving?
> 
> I believe that this is what needs to be done: [#29713 (review)](https://github.com/dotnet/maui/pull/29713#pullrequestreview-2875414224)

@MartyIX I asked for help on the testing here: https://github.com/dotnet/maui/pull/29713#discussion_r2112296920.

I wasn't sure how to test it and couldn't find any existing tests around that behavior to modify.  Would appreciate some help in that area if someone has the expertise.

**Comment by MartyIX** [comment]
@jsuarezruiz @rmarinho Would you help with the test please?

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz @rmarinho Would you help with the test please?

Yes, let me assigned to the PR to include tests.

**Comment by jsuarezruiz** [comment]
> > @jsuarezruiz @rmarinho Would you help with the test please?
> 
> Yes, let me assigned to the PR to include tests.

@postalservice14 Could you try adding something like?

```
[Fact(DisplayName = "ShellContentFragment.Destroy handles null _shellContext gracefully")]
public async Task ShellContentFragmentDestroyHandlesNullShellContext()
{
	SetupBuilder();

	var shell = await CreateShellAsync(shell =>
	{
		shell.Items.Add(new TabBar()
		{
			Items =
			{
				new ShellContent()
				{
					Route = "Item1",
					Content = new ContentPage { Title = "Page 1" }
				},
				new ShellContent()
				{
					Route = "Item2", 
					Content = new ContentPage { Title = "Page 2" }
				},
			}
		});
	});

	await CreateHandlerAndAddToWindow<ShellHandler>(shell, async (handler) =>
	{
		await OnLoadedAsync(shell.CurrentPage);
		await OnNavigatedToAsync(shell.CurrentPage);

		// Navigate to trigger fragment creation
		await shell.GoToAsync("//Item2");
		await OnNavigatedToAsync(shell.CurrentPage);

		// Test normal destruction - should work without issues
		await shell.GoToAsync("//Item1");
		await OnNavigatedToAsync(shell.CurrentPage);

		// Test null context scenario
		var exception = Record.Exception(() => 
		{
			// Create fragment with null context - this should not throw
			Page page = new ContentPage();
			var fragment = new ShellContentFragment((IShellContext)null, page);
          
			// Dispose the fragment which calls Destroy internally
			// This validates the null-conditional operators in Destroy method
			fragment.Dispose();
		});

		// Verify no exception was thrown - validates (_shellContext?.Shell as IShellController)?.RemoveAppearanceObserver(this);
		Assert.Null(exception);
	});
}
```

Here: https://github.com/dotnet/maui/blob/3f5adff66fb7e0e53a9cd6d749763927374d3164/src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Android.cs#L4

**Comment by postalservice14** [comment]
@dotnet-policy-service agree company="Ramsey Solutions"

**Review by mattleibow — DISMISSED** [review]

**Review by jsuarezruiz — APPROVED** [review]

**Comment by jsuarezruiz** [comment]
Running the failed Android UITest again, but is not related with the changes.

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellContentFragment.cs [hunk 1]
```diff
@@ -173,7 +173,7 @@ void Destroy()
 			// to avoid the navigation `TaskCompletionSource` to be stuck forever.
 			AnimationFinished?.Invoke(this, EventArgs.Empty);
 
-			((IShellController)_shellContext.Shell).RemoveAppearanceObserver(this);
+			(_shellContext?.Shell as IShellController)?.RemoveAppearanceObserver(this);
```
Comment (PureWeen) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellContentFragment.cs:182]: Can we also add a check on this destroy method so that it only runs once?

It's fine to leave this code but I just worry that this destroy method is being called twice which might just manifest as a different problem down the road

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellContentFragment.cs (hunk 1 above)
Comment (jsuarezruiz) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellContentFragment.cs:182]: Let me check it.

Comment (jsuarezruiz) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellContentFragment.cs:182]: @postalservice14 

Could you include a variable:

`bool _destroyed;`

and update the Destroy method like:

```
void Destroy()
 {
 	if (_destroyed)
 		return;

 	_destroyed = true;
          ...
```

In that way we include a guard check to ensure the Destroy method only runs once, similar to the existing `_disposed` pattern. This prevents any potential issues if the method is called from both `OnDestroy()` and `Dispose()`.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellContentFragment.cs (hunk 1 above)
Comment (postalservice14) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellContentFragment.cs:182]: @jsuarezruiz sure thing.  Done!

**Review by jsuarezruiz — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]
