### PR TITLE
[X] Optimize OnPlatform element syntax

### LINKED ISSUE #5583: XamlC should optimize OnPlatform
### Description

In the .NET Podcasts app, it has the following XAML:

https://github.com/microsoft/dotnet-podcasts/blob/00be1bb25b6940fee77f0e7b711a04dea2358ced/src/Mobile/Controls/HeaderControl.xaml#L9-L32

```xml
            <OnPlatform x:TypeArguments="View">
                <On Platform="UWP, macOS">
                    <Grid RowDefinitions="*, auto">
                        <SearchBar x:Name="searchBar"
                                   HorizontalOptions="Start"
                                   WidthRequest="460"
                                   Text="{Binding TextToSearch, Source={x:Reference selfMediaElementView}}"
                                   SearchCommand="{Binding SearchCommand, Source={x:Reference selfMediaElementView}}" />
                        <Label Text="See All Categories"
                               Style="{StaticResource BodyLLabelStyle}"
                               TextColor="{StaticResource Primary}"
                               Grid.Row="1"
                               HorizontalOptions="End"
                               Margin="0,0,30,0"
                               IsVisible="{Binding ShowSearchCategories, Source={x:Reference selfMediaElementView}}"
                               FontSize="16">
                            <Label.GestureRecognizers>
                                <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped" />
                            </Label.GestureRecognizers>
                        </Label>
                    </Grid>
                </On>
                <On Platform="Android,iOS">
                    <Grid ColumnDefinitions="*,*"
                          Margin="16,12">
                        <Image Source="{AppThemeBinding Light=logo_header_horizontal.png,Dark=logo_color_horizontal_darkmode.png}"
                               HeightRequest="34"
                               WidthRequest="125"
                               VerticalOptions="Center"
                               HorizontalOptions="Start" />
                        <Image Source="search.png"
                               Grid.Column="1"
                               VerticalOptions="Center"
                               HorizontalOptions="End"
                               HeightRequest="20"
                               WidthRequest="20">
                            <Image.GestureRecognizers>
                                <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped" />
                            </Image.GestureRecognizers>
                        </Image>
                    </Grid>
                </On>
            </OnPlatform>
```

When building the app for `Android`, I'm still seeing the controls inside the `<On Platform="UWP, macOS">` clause get created and properties set on them. For example, the `SearchBar` is only used in `UWP, macOS`, but in my compiled Android app I see:

```C#
private void InitializeComponent()
{
	ReferenceExtension referenceExtension = new ReferenceExtension();
	BindingExtension bindingExtension = new BindingExtension();
	ReferenceExtension referenceExtension2 = new ReferenceExtension();
	BindingExtension bindingExtension2 = new BindingExtension();
	SearchBar searchBar = new SearchBar();
```

This pattern is used in 3 places in the .NET Podcasts app:

1. The above
2. The [`Player`](https://github.com/microsoft/dotnet-podcasts/blob/00be1bb25b6940fee77f0e7b711a04dea2358ced/src/Mobile/Controls/Player.xaml#L17-L46) control
3. The [`ShowDetailPage`](https://github.com/microsoft/dotnet-podcasts/blob/00be1bb25b6940fee77f0e7b711a04dea2358ced/src/Mobile/Pages/ShowDetailPage.xaml#L70-L73).

We should optimize this pattern so when building for Android, the other platforms' controls are not created.

cc @StephaneDelcroix @jonathanpeppers 

### Steps to Reproduce

1. `git clone https://github.com/microsoft/dotnet-podcasts.git`
2. cd dotnet-podcasts/src/Mobile
3. `dotnet build Microsoft.NetConf2021.Maui.csproj -t:Run -c Release -f net6.0-android -r android-arm64`
4. Inspect the IL of `HeaderControl.InitializeComponent()`

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
- fixes (but reverted) #5583

### CODE REVIEW

File: src/Controls/src/Xaml/XamlNode.cs [hunk 1]
```diff
@@ -151,7 +151,7 @@ public override void Accept(IXamlNodeVisitor visitor, INode parentNode)
 			{
 				foreach (var node in Properties.Values.ToList())
 					node.Accept(visitor, this);
-				foreach (var node in CollectionItems)
+				foreach (var node in CollectionItems.ToList())
```
Comment (eerhardt) [inline src/Controls/src/Xaml/XamlNode.cs:154]: It might be good to add a comment here saying why this is needed.

(minor) If it is just to copy the contents so the `foreach` doesn't fail if elements are added/removed, it is usually better to just call `ToArray()` instead.

File: src/Controls/src/Xaml/SimplifyOnPlatformVisitor.cs [hunk 2]
```diff
@@ -26,60 +54,87 @@ public void Visit(ValueNode node, INode parentNode)
...
+				}
+			}
 
-			if (   node.Properties.TryGetValue(new XmlName("", target), out INode targetNode)
-				|| node.Properties.TryGetValue(new XmlName("", nameof(OnPlatformExtension.Default)), out targetNode))
+			//`<OnPlatform>` elements
+			if (node.XmlType.Name == "OnPlatform" && node.XmlType.NamespaceUri == XamlParser.MauiUri)
 			{
-				if (!ApplyPropertiesVisitor.TryGetPropertyName(node, parentNode, out XmlName name))
+				var onNode = GetOnNode(node, Target) ?? GetDefault(node);
```
Comment (eerhardt) [inline src/Controls/src/Xaml/SimplifyOnPlatformVisitor.cs:90]: `onNode` can be null here, right? Is it safe to pass it into `ApplyPropertiesVisitor.TryGetPropertyName`?

File: src/Controls/src/Xaml/SimplifyOnPlatformVisitor.cs [hunk 3]
```diff
@@ -26,60 +54,87 @@ public void Visit(ValueNode node, INode parentNode)
...
+
+				//Property node
+				if (   ApplyPropertiesVisitor.TryGetPropertyName(node, parentNode, out XmlName name)
+					&& parentNode is IElementNode parentEnode)
+				{
+					if (onNode != null)
+						parentEnode.Properties[name] = onNode;
+					else
+						parentEnode.Properties.Remove(name);
```
Comment (eerhardt) [inline src/Controls/src/Xaml/SimplifyOnPlatformVisitor.cs:99]: One thing I just noticed is that we add these attributes to the InitializeComponent() method:

```C#
[GeneratedCode("Microsoft.Maui.Controls.SourceGen", "1.0.0.0")]
[MemberNotNull("selfMediaElementView")]
[MemberNotNull("searchBar")]
private void InitializeComponent()
{
```

However, we are removing the initialization of some of these fields, for example the `searchBar` field in the Podcasts Header control. I'm not sure how to handle this though.... Thoughts?

File: src/Controls/src/Xaml/SimplifyOnPlatformVisitor.cs (hunk 2 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Xaml/SimplifyOnPlatformVisitor.cs:90]: yes, it's safe, but it'll return false

File: src/Controls/src/Xaml/SimplifyOnPlatformVisitor.cs (hunk 3 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Xaml/SimplifyOnPlatformVisitor.cs:99]: this is generated by our SourceGen which is a different beast. but should indeed be fixed

**Comment by jonathanpeppers** [comment]
@StephaneDelcroix is this one we can revive in .NET 7/MAUI?

Is there even anything left? Maybe just a merge conflict?

**Comment by StephaneDelcroix** [comment]
@jonathanpeppers we need to uplift the source generator to use the same parser as the compiler, so it can skip field generation for the x:Names that have been removed

**Comment by StephaneDelcroix** [comment]
@eerhardt finally spent the time to skip generation of fields for removed nodes in CodeBehindGenerator. could you look at this again ?

File: src/Controls/src/Xaml/SimplifyOnPlatformVisitor.cs (hunk 3 above)
Comment (StephaneDelcroix) [reply src/Controls/src/Xaml/SimplifyOnPlatformVisitor.cs:106]: there. see latest commit

File: src/Controls/src/SourceGen/CodeBehindGenerator.cs [hunk 4]
```diff
@@ -463,33 +465,75 @@ static void GenerateCssCodeBehind(ProjectItem projItem, SourceProductionContext
...
+			string? target = null;
+			targetFramework = targetFramework.Trim();
+			if (targetFramework.Contains("-android"))
+				target = "Android";
+			if (targetFramework.Contains("-ios"))
+				target = "iOS";
+			if (targetFramework.Contains("-macos"))
+				target = "macOS";
+			if (targetFramework.Contains("-maccatalyst"))
+				target = "MacCatalyst";
```
Comment (jonathanpeppers) [inline src/Controls/src/SourceGen/CodeBehindGenerator.cs:488]: A customer could actually put `net7.0-Android`... And things still work fine.

Should we use `StringComparison.OrdinalIgnoreCase` for all of these cases?

File: src/Controls/src/SourceGen/CodeBehindGenerator.cs [hunk 5]
```diff
@@ -463,33 +465,75 @@ static void GenerateCssCodeBehind(ProjectItem projItem, SourceProductionContext
...
+			if (target == null)
+				return;
```
Comment (jonathanpeppers) [inline src/Controls/src/SourceGen/CodeBehindGenerator.cs:490]: Is `tizen` an option?

File: src/Controls/src/SourceGen/Controls.SourceGen.csproj [hunk 6]
```diff
@@ -9,6 +9,11 @@
     <IsPackable>false</IsPackable>
     <NoWarn>$(NoWarn);NU5128;</NoWarn>
   </PropertyGroup>
+  <PropertyGroup  >
```
Comment (jonathanpeppers) [inline src/Controls/src/SourceGen/Controls.SourceGen.csproj:12]:
```suggestion
  <PropertyGroup>
```

File: src/Controls/src/Xaml/SimplifyOnPlatformVisitor.cs [hunk 7]
```diff
@@ -8,10 +9,37 @@ class SimplifyOnPlatformVisitor : IXamlNodeVisitor
...
 		{
-			TargetFramework = targetFramework;
+
+			if (string.IsNullOrEmpty(targetFramework))
+				return;
+
+#if NETSTANDARD2_0
+			if (targetFramework.Contains("-android"))
+#else
+			if (targetFramework.Contains("-android", StringComparison.Ordinal))
```
Comment (jonathanpeppers) [inline src/Controls/src/Xaml/SimplifyOnPlatformVisitor.cs:19]: If you wanted, I think `IndexOf("-android", StringComparison.OrdinalIgnoreCase) != -1` should work for `NETSTANDARD2_0` and you could remove `#if`.

File: src/Controls/src/SourceGen/CodeBehindGenerator.cs (hunk 4 above)
Comment (StephaneDelcroix) [reply src/Controls/src/SourceGen/CodeBehindGenerator.cs:488]: I don't think we have StringComparison options in netstandard2.0, and afaik, analysers should be ns2.0

File: src/Controls/src/SourceGen/CodeBehindGenerator.cs (hunk 5 above)
Comment (StephaneDelcroix) [reply src/Controls/src/SourceGen/CodeBehindGenerator.cs:490]: we mimic the optimisation done on the parsers, there's no tine case there

**Review by jonathanpeppers — APPROVED** [review]
