### PR TITLE
Applying visibility change to child controls

### LINKED ISSUE #19139: IsVisible false is not propagated to child controls
### Description

If `IsVisible="False"` is set on a `Grid` then the child controls still return `true` for `IsVisible`.

On iOS this creates a bug as the keyboard "Next" button focus the invisible `Entry` an let the user type text into it.

### Steps to Reproduce

1. Create a new MAUI 8 app
2. Open `MainPage.xaml.cs` and replace the content with:
```C#
namespace MauiApp1
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
        }

        private void HiddenEntry2Focused(object sender, FocusEventArgs e)
        {
            Console.WriteLine("Hidden entry: IsVisible: " + hiddenEntry2.IsVisible);
        }

        private void Entry3Focused(object sender, FocusEventArgs e)
        {
            Console.WriteLine("Hidden entry: IsVisible: " + hiddenEntry2.IsVisible);
        }
    }
}
```
4. Open `MainPage.xaml` and replace the content with
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">
    <ScrollView>
        <VerticalStackLayout Padding="30,0" Spacing="25">
            <Entry Placeholder="entry1" ReturnType="Next"/>

            <Grid IsVisible="False">
                <Entry x:Name="hiddenEntry2" Placeholder="hiddenEntry2" ReturnType="Next" Focused="HiddenEntry2Focused"/>
            </Grid>

            <Entry Placeholder="entry3" ReturnType="Next" Focused="Entry3Focused"/>
        </VerticalStackLayout>
    </ScrollView>
</ContentPage>
```
5. Run the App on iOS
6. Tap into the first entry and tap on the next button.

Result: Keyboard is shown for the hidden entry.

Maui8IosVisibilityIssue

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #23573: [iOS/Mac] CollectionView is not shown when parent IsVisible is switched to true
### Description

Copy from https://github.com/dotnet/maui/issues/16304

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #28012: The header in a collectionview does not resize if you hide the content
### Description

If I have a collectionview with a header and the header container control has the "IsVisible" property bound to a boolean property in the ViewModel, when the boolean property is set to "false", the header content disappears but the space does not compress.
If on the contrary, in addition to the container I also set the "IsVisible" property of the content (e.g. an Image), the header content disappears and the header space compresses

### Steps to Reproduce

- Create a page with a collectionview
- In the collectionView insert a header with a VerticalStackLayout
- In the VerticalStackLayout insert an image
- Set the "IsVisible" property of the VerticalStackLayout in binding with a boolean in the ViewModel.
- Use a Switch to set the boolean so as to display or not the image
- The image disappears but the header space does not compress

### Link to public reproduction project repository

https://github.com/acaliaro/MauiAppCollectionViewHeaderProblem

### Version with bug

9.0.40 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 18.2.1, Android 35

### Did you find any workaround?

By setting the IsVisible of the image as well, the header resizes correctly

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

Applying visibility change to child controls

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/19139
Fixes https://github.com/dotnet/maui/issues/23573
Fixes #28012

https://github.com/dotnet/maui/assets/42434498/5d8254f2-6fd5-4798-a909-e131efbd3c65

### CODE REVIEW

**Review by jsuarezruiz — COMMENTED** [review]
@tj-devel709 Could we include a device or ui tests here?

**Review by rmarinho — DISMISSED** [review]
This will need more description about the change and maybe some discussion first. I m not sure we want to add this to our public API. 

Also this would need device and unit tests for the new api

**Comment by kubaflo** [comment]
@rmarinho there was a short discussion in this issue https://github.com/dotnet/maui/issues/19139
Hmmm if the changes of `IsEnabled` or `Input transparent` propagate to child controls then that should be the case with `isVisible` Of course it is my opinion and I'm happy to find out why it might not be a good idea. 

I will write tests once there is a decision on whether this change makes sense or not.

**Comment by tj-devel709** [comment]
I added [this PR](https://github.com/dotnet/maui/pull/20160) here to address specifically with the [next entry capability.](https://github.com/dotnet/maui/issues/19139) I don't think we will need this PR (in regards to the next entry issue), but it could possibly be helpful for a different scenario!

File: src/Controls/tests/Core.UnitTests/GridTests.cs [hunk 1]
```diff
@@ -2394,6 +2394,17 @@ public void MinimumHeightRequestInAutoCells()
 			Assert.Equal(boxRow0Column1.MinimumHeightRequest, boxRow0Column1.Height);
 		}
 
+		[Fact]
+		public void ShouldPropagateVisibilityToChildren()
```
Comment (mattleibow) [inline src/Controls/tests/Core.UnitTests/GridTests.cs:2398]: Could we move this to VisualElementTests? Maybe also add the full combo of tests, with maybe 2 and 3 levels of nesting.

```cs
var root = new Grid();
var nested = new Grid();
var child = new Button();
```

and then have a matrix of how this should propagate.

```cs
[InlineData(false, true, true, false, false, false)]
public void IsVisiblePropagates(bool root, bool nested, bool child, bool expectedRoot, bool expectedNested, bool expectedChild)
```

This way we can confirm all the combinations are as expected and they are never going to break by some external logic.

Comment (mattleibow) [reply src/Controls/tests/Core.UnitTests/GridTests.cs:2398]: I would also add a test to make sure we can un-set:

```cs
var button = new Button();
var grid = new Grid { button };

grid.IsVisible = false;
Aseert.False(button.IsVisible);

grid.IsVisible = true;
Aseert.True(button.IsVisible);
```


I would also add a test to make sure we can un-set:

```cs
var button = new Button { IsVisible = false };
var grid = new Grid { button };

grid.IsVisible = false;
Aseert.False(button.IsVisible);

// button stays hidden if it was explicitly set
grid.IsVisible = true;
Aseert.False(button.IsVisible);
```


I would also add a test to make sure we can un-set:

```cs
var button = new Button { IsVisible = false };
var grid = new Grid { button };

// everything is hidden
grid.IsVisible = false;
Aseert.False(button.IsVisible);

// make buttin visible, but it should not appear
button.IsVisible = true;
Aseert.False(button.IsVisible);

// even when the grid is visible, the button is not
grid.IsVisible = true;
Aseert.False(button.IsVisible);
```

**Review by mattleibow — COMMENTED** [review]
Looking good, we just need a bunch more tests for a good few combinations so we can ensure we don't break somerthing later on and all things stay working as expected.

**Comment by mattleibow** [comment]
Can you rebase?

File: src/Controls/tests/Core.UnitTests/GridTests.cs (hunk 1 above)
Comment (kubaflo) [reply src/Controls/tests/Core.UnitTests/GridTests.cs:2398]: Thanks! I will try to do it tomorrow

Comment (kubaflo) [reply src/Controls/tests/Core.UnitTests/GridTests.cs]: Hi @mattleibow I've written the tests and they are passing except the last one. However, it failed when I replaced `IsVisible` with `IsEnabled`. In my opinion it is a correct behavior. In that way, we can prepare the element to be visible when a parent is visible. What do you think?

```
		public void ButtonShouldBeVisibleWhenExplicitlySetWhenParentIsVisible()
		{
			var button = new Button { IsVisible = false };
			var grid = new Grid { button };

			// everything is hidden
			grid.IsVisible = false;
			Assert.False(button.IsVisible);

			// make buttin visible, but it should not appear
			button.IsVisible = true;
			Assert.False(button.IsVisible);

			// button appears when parent appears
			grid.IsVisible = true;
			Assert.True(button.IsVisible);
		}
```

This test will pass with the current implementation

Comment (mattleibow) [reply src/Controls/tests/Core.UnitTests/GridTests.cs]: Ah, maybe I had a type. Thanks for checking and doing the right thing :) Tests are cool so now it is working as expected.

**Comment by mattleibow** [comment]
Now the question is... Is this a breaking change for a SR that means it should wait for net9.0? Or is it OK and people need to be aware of the change?

File: src/Controls/src/Core/VisualElement/VisualElement.cs [hunk 2]
```diff
@@ -1667,6 +1715,13 @@ void IPropertyPropagationController.PropagatePropertyChanged(string propertyName
 		protected void RefreshIsEnabledProperty() =>
 			this.RefreshPropertyValue(IsEnabledProperty, _isEnabledExplicit);
 
+		/// <summary>
+		/// This method must always be called if some event occurs and the value of
+		/// the <see cref="IsVisibleCore"/> property will change.
+		/// </summary>
+		protected void RefreshIsVisibleProperty() =>
```
Comment (mattleibow) [inline src/Controls/src/Core/VisualElement/VisualElement.cs:1722]: For a service release, maybe this should be `protected internal` for now. In net9.0 we can make it public.

Comment (kubaflo) [reply src/Controls/src/Core/VisualElement/VisualElement.cs:1722]: I think it is a good idea

**Comment by jsuarezruiz** [comment]
@kubaflo Could you rebase and fix the conflicts?. Thanks.
Let me know if can help with something.

**Comment by kubaflo** [comment]
@jsuarezruiz done :)

**Comment by rmarinho** [comment]
Uff needs rebase again

**Comment by kubaflo** [comment]
@rmarinho rebased

File: src/Controls/tests/Core.UnitTests/VisualElementTests.cs [hunk 3]
```diff
@@ -323,5 +323,79 @@ public void WidthAndHeightRequestPropagateToHandler()
...
+		public void ButtonShouldBeVisibleWhenExplicitlySetWhenParentIsVisible()
+		{
+			var button = new Button { IsVisible = false };
+			var grid = new Grid { button };
+
+			// everything is hidden
+			grid.IsVisible = false;
+			Assert.False(button.IsVisible);
+
+			// make buttin visible, but it should not appear
```
[the remark this answers is not in the document]
Comment (kubaflo) [reply src/Controls/tests/Core.UnitTests/VisualElementTests.cs]: Thanks!

**Review by mattleibow — DISMISSED** [review]

**Comment by mattleibow** [comment]
Hmmm, the new api in there... Should that be internal for now and protected for net10?

@PureWeen @rmarinho

**Comment by kubaflo** [comment]
@mattleibow that's a good idea! I've made this an internal method

File: src/Controls/src/Core/VisualElement/VisualElement.cs [hunk 4]
```diff
@@ -1740,6 +1788,13 @@ void IPropertyPropagationController.PropagatePropertyChanged(string propertyName
 		protected void RefreshIsEnabledProperty() =>
 			this.RefreshPropertyValue(IsEnabledProperty, _isEnabledExplicit);
 
+		/// <summary>
+		/// This method must always be called if some event occurs and the value of
+		/// the <see cref="IsVisibleCore"/> property will change.
+		/// </summary>
+		internal void RefreshIsVisibleProperty() =>
```
Comment (mattleibow) [inline src/Controls/src/Core/VisualElement/VisualElement.cs:1795]: Make `IsVisibleCore` and `RefreshIsVisibleProperty` visible in .NET 10

Comment (mattleibow) [reply src/Controls/src/Core/VisualElement/VisualElement.cs:1795]: Issue to track for .NET 10 https://github.com/dotnet/maui/issues/27739

**Comment by jfversluis** [comment]
`Issue1549.ResourcesInNonXFBaseClassesAreFound()` unit test fails is that one relevant?

**Comment by kubaflo** [comment]
@jfversluis  Because of how propagation works I had to modify the test

**Review by jfversluis — APPROVED** [review]

**Comment by maonaoda** [comment]
@kubaflo 
Something seems wrong

```
Unhandled Exception:
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.List1.Enumerator[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNextRare()
at System.Collections.Generic.List1.Enumerator[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
at Microsoft.Maui.Controls.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:line 29
at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.Controls.IPropertyPropagationController.PropagatePropertyChanged(String propertyName) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1781
at Microsoft.Maui.Controls.VisualElement.OnIsVisibleChanged(Boolean oldValue, Boolean newValue) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1535
at Microsoft.Maui.Controls.VisualElement.<>c.<.cctor>b__435_6(BindableObject bindable, Object oldvalue, Object newvalue) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/VisualElement/VisualElement.cs:line 276
at Microsoft.Maui.Controls.BindableObject.OnBindablePropertySet(BindableProperty property, Object original, Object value, Boolean didChange, Boolean willFirePropertyChanged) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/BindableObject.cs:line 676
at Microsoft.Maui.Controls.Element.OnBindablePropertySet(BindableProperty property, Object original, Object value, Boolean changed, Boolean willFirePropertyChanged) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/Element/Element.cs:line 642
at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/BindableObject.cs:line 663
at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/BindableObject.cs:line 591
at Microsoft.Maui.Controls.Internals.TypedBinding2[[Mti.Carada.Kenshin.ViewModels.ConsultationHistoryPageViewModel, Mti.Carada.Kenshin, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/TypedBinding.cs:line 325
at Microsoft.Maui.Controls.Internals.TypedBinding2[[Mti.Carada.Kenshin.ViewModels.ConsultationHistoryPageViewModel, Mti.Carada.Kenshin, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Apply(Boolean fromTarget) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/TypedBinding.cs:line 167
at Microsoft.Maui.Controls.Internals.TypedBinding2.PropertyChangedProxy[[Mti.Carada.Kenshin.ViewModels.ConsultationHistoryPageViewModel, Mti.Carada.Kenshin, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<OnPropertyChanged>b__16_0() in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/TypedBinding.cs:line 506
at Microsoft.Maui.Dispatching.Dispatcher.<>c__DisplayClass9_0.<DispatchImplementation>b__0() in /Users/wangyk/Projects/Practice/my_maui/src/Core/src/Dispatching/Dispatcher.iOS.cs:line 21
at CoreFoundation.DispatchQueue.static_dispatcher_to_managed(IntPtr context) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/CoreFoundation/Dispatch.cs:line 379
at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61
at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
at Mti.Carada.Kenshin.Program.Main(String[] args) in /Users/wangyk/Projects/Carada/kenshin-app-maui/Mti.Carada.Kenshin/Platforms/iOS/Program.cs:line 15
2025-02-28 11:19:18.763430+0800 Mti.Carada.Kenshin[53310:3897398] Received unhandled Objective-C exception that was marshalled from a managed exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
at System.Collections.Generic.List1.Enumerator[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNextRare()
at System.Collections.Generic.List1.Enumerator[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
at Microsoft.Maui.Controls.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:line 29
at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.Controls.IPropertyPropagationController.PropagatePropertyChanged(String propertyName) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1781
at Microsoft.Maui.Controls.VisualElement.OnIsVisibleChanged(Boolean oldValue, Boolean newValue) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1535
at Microsoft.Maui.Controls.VisualElement.<>c.<.cctor>b__435_6(BindableObject bindable, Object oldvalue, Object newvalue) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/VisualElement/VisualElement.cs:line 276
at Microsoft.Maui.Controls.BindableObject.OnBindablePropertySet(BindableProperty property, Object original, Object value, Boolean didChange, Boolean willFirePropertyChanged) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/BindableObject.cs:line 676
at Microsoft.Maui.Controls.Element.OnBindablePropertySet(BindableProperty property, Object original, Object value, Boolean changed, Boolean willFirePropertyChanged) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/Element/Element.cs:line 642
at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/BindableObject.cs:line 663
at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/BindableObject.cs:line 591
at Microsoft.Maui.Controls.Internals.TypedBinding2[[Mti.Carada.Kenshin.ViewModels.ConsultationHistoryPageViewModel, Mti.Carada.Kenshin, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/TypedBinding.cs:line 325
at Microsoft.Maui.Controls.Internals.TypedBinding2[[Mti.Carada.Kenshin.ViewModels.ConsultationHistoryPageViewModel, Mti.Carada.Kenshin, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Apply(Boolean fromTarget) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/TypedBinding.cs:line 167
at Microsoft.Maui.Controls.Internals.TypedBinding2.PropertyChangedProxy[[Mti.Carada.Kenshin.ViewModels.ConsultationHistoryPageViewModel, Mti.Carada.Kenshin, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<OnPropertyChanged>b__16_0() in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/TypedBinding.cs:line 506
at Microsoft.Maui.Dispatching.Dispatcher.<>c__DisplayClass9_0.<DispatchImplementation>b__0() in /Users/wangyk/Projects/Practice/my_maui/src/Core/src/Dispatching/Dispatcher.iOS.cs:line 21
at CoreFoundation.DispatchQueue.static_dispatcher_to_managed(IntPtr context) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/CoreFoundation/Dispatch.cs:line 379
at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61
at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
at Mti.Carada.Kenshin.Program.Main(String[] args) in /Users/wangyk/Projects/Carada/kenshin-app-maui/Mti.Carada.Kenshin/Platforms/iOS/Program.cs:line 15
```

**Comment by maonaoda** [comment]
I think, added
`
(this as IPropertyPropagationController)?.PropagatePropertyChanged(IsVisibleProperty.PropertyName);
`
may affect the control that changes the child element through ItemsSource

**Comment by kubaflo** [comment]
> @kubaflo Something seems wrong
> 
> ```
> Unhandled Exception:
> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
> at System.Collections.Generic.List1.Enumerator[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNextRare()
> at System.Collections.Generic.List1.Enumerator[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
> at Microsoft.Maui.Controls.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:line 29
> at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.Controls.IPropertyPropagationController.PropagatePropertyChanged(String propertyName) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1781
> at Microsoft.Maui.Controls.VisualElement.OnIsVisibleChanged(Boolean oldValue, Boolean newValue) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1535
> at Microsoft.Maui.Controls.VisualElement.<>c.<.cctor>b__435_6(BindableObject bindable, Object oldvalue, Object newvalue) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/VisualElement/VisualElement.cs:line 276
> at Microsoft.Maui.Controls.BindableObject.OnBindablePropertySet(BindableProperty property, Object original, Object value, Boolean didChange, Boolean willFirePropertyChanged) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/BindableObject.cs:line 676
> at Microsoft.Maui.Controls.Element.OnBindablePropertySet(BindableProperty property, Object original, Object value, Boolean changed, Boolean willFirePropertyChanged) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/Element/Element.cs:line 642
> at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/BindableObject.cs:line 663
> at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/BindableObject.cs:line 591
> at Microsoft.Maui.Controls.Internals.TypedBinding2[[XXX.ViewModels.ConsultationHistoryPageViewModel, XXX, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/TypedBinding.cs:line 325
> at Microsoft.Maui.Controls.Internals.TypedBinding2[[XXX.ViewModels.ConsultationHistoryPageViewModel, XXX, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Apply(Boolean fromTarget) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/TypedBinding.cs:line 167
> at Microsoft.Maui.Controls.Internals.TypedBinding2.PropertyChangedProxy[[XXX.ViewModels.ConsultationHistoryPageViewModel, XXX, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<OnPropertyChanged>b__16_0() in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/TypedBinding.cs:line 506
> at Microsoft.Maui.Dispatching.Dispatcher.<>c__DisplayClass9_0.<DispatchImplementation>b__0() in /Users/wangyk/Projects/Practice/my_maui/src/Core/src/Dispatching/Dispatcher.iOS.cs:line 21
> at CoreFoundation.DispatchQueue.static_dispatcher_to_managed(IntPtr context) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/CoreFoundation/Dispatch.cs:line 379
> at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61
> at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
> at XXX.Program.Main(String[] args) in /Users/wangyk/Projects/app-maui/XXX/Platforms/iOS/Program.cs:line 15
> 2025-02-28 11:19:18.763430+0800 XXX[53310:3897398] Received unhandled Objective-C exception that was marshalled from a managed exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
> at System.Collections.Generic.List1.Enumerator[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNextRare()
> at System.Collections.Generic.List1.Enumerator[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
> at Microsoft.Maui.Controls.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(String propertyName, Element element, IEnumerable children) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:line 29
> at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.Controls.IPropertyPropagationController.PropagatePropertyChanged(String propertyName) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1781
> at Microsoft.Maui.Controls.VisualElement.OnIsVisibleChanged(Boolean oldValue, Boolean newValue) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/VisualElement/VisualElement.cs:line 1535
> at Microsoft.Maui.Controls.VisualElement.<>c.<.cctor>b__435_6(BindableObject bindable, Object oldvalue, Object newvalue) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/VisualElement/VisualElement.cs:line 276
> at Microsoft.Maui.Controls.BindableObject.OnBindablePropertySet(BindableProperty property, Object original, Object value, Boolean didChange, Boolean willFirePropertyChanged) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/BindableObject.cs:line 676
> at Microsoft.Maui.Controls.Element.OnBindablePropertySet(BindableProperty property, Object original, Object value, Boolean changed, Boolean willFirePropertyChanged) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/Element/Element.cs:line 642
> at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/BindableObject.cs:line 663
> at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/BindableObject.cs:line 591
> at Microsoft.Maui.Controls.Internals.TypedBinding2[[XXX.ViewModels.ConsultationHistoryPageViewModel, XXX, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/TypedBinding.cs:line 325
> at Microsoft.Maui.Controls.Internals.TypedBinding2[[XXX.ViewModels.ConsultationHistoryPageViewModel, XXX, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Apply(Boolean fromTarget) in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/TypedBinding.cs:line 167
> at Microsoft.Maui.Controls.Internals.TypedBinding2.PropertyChangedProxy[[XXX.ViewModels.ConsultationHistoryPageViewModel, XXX, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<OnPropertyChanged>b__16_0() in /Users/wangyk/Projects/Practice/my_maui/src/Controls/src/Core/TypedBinding.cs:line 506
> at Microsoft.Maui.Dispatching.Dispatcher.<>c__DisplayClass9_0.<DispatchImplementation>b__0() in /Users/wangyk/Projects/Practice/my_maui/src/Core/src/Dispatching/Dispatcher.iOS.cs:line 21
> at CoreFoundation.DispatchQueue.static_dispatcher_to_managed(IntPtr context) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/CoreFoundation/Dispatch.cs:line 379
> at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61
> at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
> at XXX.Program.Main(String[] args) in /Users/wangyk/Projects/app-maui/XXX/Platforms/iOS/Program.cs:line 15
> ```

Can you provide a sample so that I can try to reproduce it? Thanks!

**Comment by maonaoda** [comment]
@kubaflo 
Please see https://github.com/dotnet/maui/issues/28162
and you can also see that the bug size of CollectionView`s Header was not solved.

**Comment by bmacombe** [comment]
> Now the question is... Is this a breaking change for a SR that means it should wait for net9.0? Or is it OK and people need to be aware of the change?

@mattleibow @kubaflo I think this is causing me issues in 9.0.50, we have some layout logic that depends on knowing the actually Set value of IsVisible, like the original behavior. I don't see how I can get the _isVisibleExplicit value even after the .net 10 changes
