### PR TITLE
Fix a few places we almost properly check for null

### LINKED ISSUE #10517: Strange code fragments
### Description

Hello,
I am not sure whether it is correct to tell you about strange fragments in the code here, but I think it is better to post the information at least here.
I downloaded sources of the [6.0.424 version](https://github.com/dotnet/maui/releases/tag/6.0.424) and found some strange fragments in code. I'm not sure if there are any real problems, but the code is really suspicious.

1. Possible null dereference in [AdaptiveTrigger.AttachEvents](https://github.com/dotnet/maui/blob/28ecaba81599b063d2ae2ae934b71f66e327bc8d/src/Controls/src/Core/AdaptiveTrigger.cs#L69):

>   void AttachEvents()
>   {
> 	DetachEvents();
> 
> 	_visualElement = VisualState?.VisualStateGroup?.VisualElement;
> 	if (_visualElement is not null)
> 		_visualElement.PropertyChanged += OnVisualElementPropertyChanged;
> 
> 	_window = _visualElement.Window;
> 	if (_window is not null)
> 		_window.PropertyChanged += OnVisualElementPropertyChanged;
> 
> 	_page = _window.Page;         // <=
> 	if (_page is not null)
> 		_page.SizeChanged += OnPageSizeChanged;
>   }

2. Useless call in [GradientBrushParser.Parse](https://github.com/dotnet/maui/blob/28ecaba81599b063d2ae2ae934b71f66e327bc8d/src/Controls/src/Core/BrushTypeConverter.cs#L139):

> 
> if (part.Equals(Rgb, StringComparison.OrdinalIgnoreCase)
> 	|| part.Equals(Rgba, StringComparison.OrdinalIgnoreCase)
> 	|| part.Equals(Hsl, StringComparison.OrdinalIgnoreCase)
> 	|| part.Equals(Hsla, StringComparison.OrdinalIgnoreCase))
> {
> 	part.Trim();                                                  // <=
> 	var colorString = new StringBuilder(part);
> 
> 	colorString.Append('(');

3. Suspicious property access in [FormattedString.OnCollectionChanged](https://github.com/dotnet/maui/blob/28ecaba81599b063d2ae2ae934b71f66e327bc8d/src/Controls/src/Core/FormattedString.cs#L44):

> foreach (object item in e.OldItems)
> {
> 	var bo = item as Span;
> 	bo.Parent = null;           // <=
> 	if (bo != null)
> 	{
> 		bo.PropertyChanging -= OnItemPropertyChanging;
> 		bo.PropertyChanged -= OnItemPropertyChanged;
> 	}
> 
> }

4. Suspicious property access in [ListView.SetupContent](https://github.com/dotnet/maui/blob/28ecaba81599b063d2ae2ae934b71f66e327bc8d/src/Controls/src/Core/ListView.cs#L449):

> base.SetupContent(content, index);
> if (content is ViewCell viewCell && viewCell.View != null && HasUnevenRows)
> 	viewCell.View.ComputedConstraint = LayoutConstraint.None;
> 
> if (content != null)
> 	_logicalChildren.Add(content);
> 
> content.Parent = this;
> VisualDiagnostics.OnChildAdded(this, content);

5. Suspicious property access in [ShellChromeGallery constructor](https://github.com/dotnet/maui/blob/28ecaba81599b063d2ae2ae934b71f66e327bc8d/src/Controls/samples/Controls.Sample/Pages/Core/ShellGalleries/ShellChromeGallery.cs#L37):

> if (AppShell != null)
> {
> 	flyoutBehavior.SelectedIndex = (int)AppShell.FlyoutBehavior;
> 	flyoutHeaderBehavior.SelectedIndex = (int)AppShell.FlyoutHeaderBehavior;
> }
> else
> {
> 	flyoutBehavior.SelectedIndex = 1;
> 	flyoutHeaderBehavior.SelectedIndex = 0;
> }
> 
> AppShell.FlyoutBackdrop = SolidColorBrush.Pink; // <=

Perhaps this code doesn't lead to any issues (for now, at least), but it looks quite dangerous. I found these fragments with PVS-Studio C# analyzer.

### Steps to Reproduce

I am not sure if I can fill this text area correctly for my issue :)

### Link to public reproduction project repository

https://github.com/dotnet/maui

### Version with bug

6.0.424

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

-

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Redth**
### Description of Change

There were a few places we weren't fully checking for null, or rather we checked for null for some operations but not others directly around or after.  This should cause a few less null ref exceptions.

Fixes #10517

### CODE REVIEW

File: src/Controls/src/Core/FormattedString.cs [hunk 1]
```diff
@@ -41,9 +41,9 @@ void OnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
 				foreach (object item in e.OldItems)
 				{
 					var bo = item as Span;
-					bo.Parent = null;
 					if (bo != null)
 					{
+						bo.Parent = null;
```
Comment (campersau) [inline src/Controls/src/Core/FormattedString.cs:46]: Maybe also fix line 59? (That's why I personally prefer the `if (a is X x)` style instead of `as`.)

**Review by PureWeen — APPROVED** [review]
