### PR TITLE
Fix issue with template processing

### LINKED ISSUE #27055: Maui template with sample content is missing the handler registrations
### Description

The preprocessor code in the template is removing the code instead of ignoring it.

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

The template is processing the actual code

Fixes https://github.com/dotnet/maui/issues/27055

### CODE REVIEW

**Review by rmarinho — DISMISSED** [review]
Is it possible to add a test? also can you create a issue associated with this?

**Comment by Eilon** [comment]
> Is it possible to add a test? also can you create a issue associated with this?

Unfortunately the template tests only create, build, and maybe publish the templates. None of the tests *run* the apps built by the template. It's certainly possible (somehow), but we don't do it at this time. I think you'd need to do that in order to test this?

**Comment by mattleibow** [comment]
We could check the new template for the line

**Comment by Eilon** [comment]
> We could check the new template for the line

We could... but that's pretty random. Why check this one thing but not anything else?

File: src/Templates/src/templates/maui-mobile/MauiProgram.cs [hunk 1]
```diff
@@ -20,9 +20,11 @@ public static MauiApp CreateMauiApp()
 			.ConfigureSyncfusionToolkit()
 			.ConfigureMauiHandlers(handlers =>
 			{
+//-:cnd:noEmit
 #if IOS || MACCATALYST
```
Comment (mattleibow) [inline src/Templates/src/templates/maui-mobile/MauiProgram.cs:24]: The tests are failing because I think the CV2 is not in the blank maui app, should it be used in all templates, or just when using the sample content?

**Comment by Eilon** [comment]
> What else can we check? We would have to set up a template and then run it and then somehow communicate with the running ap to determine which handler is in use.

Yeah I think that's the only meaningful way to test it. I'm not at all saying it's easy: it's probably _not_.

A pattern I've seen before is to:

1. Instantiate the template (`dotnet new <stuff>`)
2. Add a little bit of instrumentation to it to make the app more 'inspectable', so like add `TestInspector.cs` to it that has magic code to 'test' things in the app (say, a check to make sure the right handler is actually registered, or that a font is installed, or that all controls have accessible descriptions, etc.)
3. Run the app
4. Have the test call into the `TestInspector.cs` functions to verify stuff

But if the test is just to check that the template output contains a string, I wouldn't even bother. It's not verifying the code is correct or even executed at all, let alone if it has the desired effect in the running app. And on top of that it's a very fragile test because a lot of changes that could be _good_ changes could cause this test to fail (say we change MAUI to have this be built-in and not needed in the template, this test could start failing, even though there's nothing wrong).

**Review by jsuarezruiz — DISMISSED** [review]

**Review by PureWeen — APPROVED** [review]
