### PR TITLE
Don't set editor action to handled

### LINKED ISSUE #5724: Entry field Enter does not always move to next field
### Additional Notes
- Good Summary of behavior:  https://github.com/dotnet/maui/issues/5724#issuecomment-1165282553
- `XF` implemented the forward motion [manually](https://github.com/xamarin/Xamarin.Forms/blob/d7d5e01a7435f2fd055485959df8708c03911f67/Xamarin.Forms.Platform.Android/Renderers/EntryRenderer.cs#L92). On `Android` the forward behavior happens automatically so I'm curious why this behavior doesn't work automatically. Ideally, we can just make it work opposed to having to implement our own focus search code. 
  - It looks like `Next` fails to work because for `OnEditorAction` we set `e.Handled` to true for everything so `Android` doesn't fall back to its default behavior ever

### Description

On a screen with multiple entry fields the treatment of the enter key is inconsistent. What I've seen so far:

On Android, if `ReturnType` is set to `Next` the on screen key appearance changes to a 'Tab' icon and clicking it does nothing. If `ReturnType="Done"` the icon changes to an "Enter" icon and clicking it calls the Completed action. In neither case does it advance focus to the next field. 

On Windows pressing the enter key calls `OnCompleted` whether `ReturnType` is set to `Done` or `Next` and the the focus switches to the next field if `ReturnType` is set to `Next` (and not `Done`) all of which seems correct.

Xamarin Forms acts like Windows (above) except that pressing enter in a field where `ReturnType="Done"` causes the field to be unfocused rather than focusing on the next field as `Next` would.

### Steps to Reproduce

1. Unzip the project in [Simple-Entry.zip](https://github.com/dotnet/maui/files/8393572/Simple-Entry.zip)
2. Compile and run the program on Android
3. Select the first field
4. Click on the on screen keyboard button to advance to the next field
5. Note that nothing happens (no call of OnCompleted, no change in focus)

Here's what you should see (the blue virtual key is the one you should click on):
 
Simple-Entry

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11, Windows 10 

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #8302: [Android] [Entry] Keyboard is still shown after return/done action
### Description

Keyboard should hide after return is pressed

https://user-images.githubusercontent.com/26333327/175521785-349848ce-8ff9-4758-bcce-d8c5d908da5e.mp4

### Steps to Reproduce

Create entry
Focus entry
Tap return

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

ALL

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #10858: [Android] Keyboard is not dismissed after tapping "Enter"
### Description

When editing an Entry, the virtual keyboard is not dismissed after tapping the "Enter" button:
maui_entry_bug
This behaviour does not occur on iOS.

### Steps to Reproduce

1. Create a new .NET MAUI project
2. Add an entry
3. Tap into the entry control, type some text and tap "Enter"
4. The keyboard does not disappear, it remains visible until the back button is pressed

### Link to public reproduction project repository

https://github.com/owl-guy/EditorExample

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

At some point super early in the life of `XF` the "Handled" option on the `EditorAction` event was being set to `true`. This basically causes `Androids` default behavior to not run, which automatically handles closing the keyboard if your `ReturnType` is set to `Complete` and it handles moving to the next field automatically.  In `XF` we just kept building custom solutions since we were setting `Handled` to true. We basically recreated the `keyboard close` and then `next focus` behavior ourselves. 

- This PR has no effect if the user is using an attached keyboard. With an attached keyboard the enter key always moves to the next field which is the desired behavior for accessibility and expectation from the user purposes. If you have a use case or want to be hostile to keyboard users, then you can subscribe to the EditorAction event for the platform view on `Entry` and set the `Handled` property to true

### Issues Fixed

Fixes #5724
Fixes #10858
Fixes #8302

### CODE REVIEW

File: src/Core/src/Platform/Android/KeyboardManager.cs [hunk 1]
```diff
@@ -2,36 +2,38 @@
...
+using Android.Views;
 using Android.Views.InputMethods;
 using Android.Widget;
+using AndroidX.Core.View;
 using AView = Android.Views.View;
 
-namespace Microsoft.Maui.Controls.Platform
+namespace Microsoft.Maui.Platform
 {
 	internal static class KeyboardManager
```
Comment (PureWeen) [inline src/Core/src/Platform/Android/KeyboardManager.cs:13]: Moved this to `Core` so that we can use it from `AssertionExtensions`

File: src/Core/src/Handlers/Entry/EntryHandler.Android.cs [hunk 2]
```diff
@@ -169,7 +169,7 @@ void OnEditorAction(object? sender, EditorActionEventArgs e)
 				}
 			}
 
-			e.Handled = true;
```
Comment (PureWeen) [inline src/Core/src/Handlers/Entry/EntryHandler.Android.cs:172]: This is the only SDK change

**Review by rachelkang — APPROVED** [review]
