### PR TITLE
Fix BlazorWebView tests on Windows

### LINKED ISSUE #16187: [Windows, Blazor] Review currently failing Windows tests
### Description

As part of https://github.com/dotnet/maui/pull/15629 I've skipped the tests listed below. All of these tests were failing on the original PR. We don't necessarily need to fix these issues for .NET8 but we should establish if we *should* fix these for .NET8 or just fix the tests themselves. 

**BlazorWebView**
- [ ] BlazorWebViewUsesStartPath
- [ ] BlazorWebViewLogsRequests

### PR DESCRIPTION
**Pull request by Eilon**
It seems that the test sometimes waits for an event that already happened, so it doesn't see it happen, and fails. I added a check to evaluate the state of the test to see if it doesn't need to wait for the event and allows the test to continue.

Fixes #16187

### CODE REVIEW

**Review by jknaudt21 — APPROVED** [review]

File: src/BlazorWebView/tests/MauiDeviceTests/HandlerTestBase.cs [hunk 1]
```diff
@@ -27,6 +27,10 @@ public void EnsureHandlerCreated(Action<MauiAppBuilder> additionalCreationAction
 			var appBuilder = MauiApp
 				.CreateBuilder();
 
+			appBuilder.Services.AddSingleton<IDispatcherProvider>(svc => TestDispatcher.Provider);
```
Comment (Eilon) [inline src/BlazorWebView/tests/MauiDeviceTests/HandlerTestBase.cs:30]: This was to fix some issue that only happens in some environments. I updated this setup code to match what other tests do.

File: src/BlazorWebView/tests/MauiDeviceTests/WebViewHelpers.Windows.cs [hunk 2]
```diff
@@ -42,7 +42,16 @@ public static async Task WaitForWebViewReady(WebView2 wv2)
 
 			if (!domLoaded)
 			{
-				throw new Exception($"Waited {MaxWaitTimes * WaitTimeInMS}ms but couldn't get CoreWebView2.DOMContentLoaded to complete.");
+				// It's possible that the DOMContentLoaded event won't fire because it's already loaded by the time we got here. To check
+				// for that, we inspect an arbitrary custom HTML element attribute to see if we can find it. If we can find it, then surely
+				// the DOM content is loaded, so we can continue with the test.
+				var testHtmlLoadedAttributeValue = await wv2.CoreWebView2.ExecuteScriptAsync("(document.head.attributes['testhtmlloaded']?.value === 'true')");
```
Comment (Eilon) [inline src/BlazorWebView/tests/MauiDeviceTests/WebViewHelpers.Windows.cs:48]: This is the actual fix.

**Review by jsuarezruiz — APPROVED** [review]

**Review by surayya-MS — APPROVED** [review]

**Review by SteveSandersonMS — APPROVED** [review]
I understand the `DOMContentLoaded` fix but don't know what the other changes are for. It sounds like you know what you're doing though.

**Comment by Eilon** [comment]
> I understand the `DOMContentLoaded` fix but don't know what the other changes are for. It sounds like you know what you're doing though.

The other fixes were to simply make the tests work on Windows at all. These tests previously never ran on Windows (MAUI tests only ran on Android/iOS devices). At some point various MAUI test projects were updated to work on Windows, but not the Blazor ones. Part of the changes in this PR are to bring the Blazor tests up-to-date with other MAUI tests (I just copied their setup code).

**Comment by Eilon** [comment]
@SteveSandersonMS said:

> ... It sounds like you know what you're doing though.

The highest compliment 😁 But maybe I have you fooled??
