### PR TITLE
System.MissingMethodException in PropertyPropagationExtensions fix

### LINKED ISSUE #28450: System.MissingMethodException: 'Method not found: void Microsoft.Maui.Controls.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(string,Microsoft.Maui.Controls.Element,System.Collections.IEnumerable)'
### Description

**When i try to Open the popup in .net maui i got this error** 

```
"System.MissingMethodException: 'Method not found: void Microsoft.Maui.Controls.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(string,Microsoft.Maui.Controls.Element,System.Collections.IEnumerable)'"


[monodroid-assembly] open_from_bundles: failed to load bundled assembly Xamarin.Google.Crypto.Tink.Android.dll
[monodroid-assembly] open_from_bundles: the assembly might have been uploaded to the device with FastDev instead
Loaded assembly: /data/data/com.goyalbrosandco.tiaerpapp/files/.__override__/x86_64/Xamarin.Google.Crypto.Tink.Android.dll [External]
[monodroid-assembly] open_from_bundles: failed to load bundled assembly Xamarin.AndroidX.Security.SecurityCrypto.dll
[monodroid-assembly] open_from_bundles: the assembly might have been uploaded to the device with FastDev instead
Loaded assembly: /data/data/com.goyalbrosandco.tiaerpapp/files/.__override__/x86_64/Xamarin.AndroidX.Security.SecurityCrypto.dll [External]
[monodroid-assembly] open_from_bundles: failed to load bundled assembly Xamarin.AndroidX.Navigation.UI.dll
[monodroid-assembly] open_from_bundles: the assembly might have been uploaded to the device with FastDev instead
Loaded assembly: /data/data/com.goyalbrosandco.tiaerpapp/files/.__override__/x86_64/Xamarin.AndroidX.Navigation.UI.dll [External]
[HWUI] Unknown dataspace 0
Thread started: <Thread Pool> #10
Thread started: <Thread Pool> #11
[Choreographer] Skipped 105 frames!  The application may be doing too much work on its main thread.
[andco.tiaerpapp] Background concurrent mark compact GC freed 1878KB AllocSpace bytes, 1(20KB) LOS objects, 49% free, 4879KB/9759KB, paused 1.512ms,6.805ms total 43.179ms
[andco.tiaerpapp] Compiler allocated 5174KB to compile void android.view.ViewRootImpl.performTraversals()
[EGL_emulation] Opening libGLESv1_CM_emulation.so
[EGL_emulation] Opening libGLESv2_emulation.so
[andco.tiaerpapp] Compiler allocated 5417KB to compile void android.view.ViewRootImpl.performTraversals()
[HWUI] Failed to initialize 101010-2 format, error = EGL_SUCCESS
[Gralloc4] mapper 4.x is not supported
[SurfaceSyncGroup] Failed to receive transaction ready in 1000ms. Marking SurfaceSyncGroup(wmsSync-VRI[MainActivity]#0) as ready
[SurfaceSyncGroup] Failed to receive transaction ready in 1000ms. Marking SurfaceSyncGroup(VRI[MainActivity]#1) as ready
Thread started: <Thread Pool> #12
[HWUI] Davey! duration=3500ms; Flags=1, FrameTimelineVsyncId=1924786, IntendedVsync=24730640819296, Vsync=24732390819226, InputEventId=0, HandleInputStart=24732395735300, AnimationStart=24732395803900, PerformTraversalsStart=24732414918000, DrawStart=24732690041200, FrameDeadline=24730657485962, FrameInterval=24732394677000, FrameStartTime=16666666, SyncQueued=24732871979000, SyncStart=24732872348800, IssueDrawCommandsStart=24732876681600, SwapBuffers=24733856902300, FrameCompleted=24734141370300, DequeueBufferDuration=494200, QueueBufferDuration=900900, GpuCompleted=24734141370300, SwapBuffersCompleted=24734126627300, DisplayPresentTime=0, CommandSubmissionCompleted=24733856902300, 
[Choreographer] Skipped 108 frames!  The application may be doing too much work on its main thread.
[ho] Opted out of usage reporting
[ho] Opted out of usage reporting
[HWUI] Davey! duration=1872ms; Flags=0, FrameTimelineVsyncId=1924856, IntendedVsync=24732440819224, Vsync=24734240819152, InputEventId=0, HandleInputStart=24734248526600, AnimationStart=24734248564600, PerformTraversalsStart=24734249601300, DrawStart=24734249937800, FrameDeadline=24734357485814, FrameInterval=24734247417200, FrameStartTime=16666666, SyncQueued=24734249961200, SyncStart=24734330525000, IssueDrawCommandsStart=24734330692300, SwapBuffers=24734356202700, FrameCompleted=24734394045000, DequeueBufferDuration=850900, QueueBufferDuration=445700, GpuCompleted=24734393804800, SwapBuffersCompleted=24734394045000, DisplayPresentTime=0, CommandSubmissionCompleted=24734356202700, 
[ProfileInstaller] Installing profile for com.goyalbrosandco.tiaerpapp
[EGL_emulation] app_time_stats: avg=51.93ms min=21.79ms max=202.93ms count=19
[EGL_emulation] app_time_stats: avg=45.59ms min=29.79ms max=62.77ms count=17
[andco.tiaerpapp] Explicit concurrent mark compact GC freed 1451KB AllocSpace bytes, 21(740KB) LOS objects, 49% free, 5279KB/10MB, paused 778us,24.990ms total 108.101ms
[WindowOnBackDispatcher] OnBackInvokedCallback is not enabled for the application.
[WindowOnBackDispatcher] Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
[Choreographer] Skipped 54 frames!  The application may be doing too much work on its main thread.
[HWUI] Davey! duration=1056ms; Flags=0, FrameTimelineVsyncId=1925479, IntendedVsync=24735824152422, Vsync=24735890819086, InputEventId=0, HandleInputStart=24735899671300, AnimationStart=24735899713500, PerformTraversalsStart=24736730595500, DrawStart=24736743122500, FrameDeadline=24736807485716, FrameInterval=24735899644600, FrameStartTime=16666666, SyncQueued=24736746108800, SyncStart=24736807809300, IssueDrawCommandsStart=24736808431400, SwapBuffers=24736837644800, FrameCompleted=24736942404200, DequeueBufferDuration=33300, QueueBufferDuration=614600, GpuCompleted=24736942404200, SwapBuffersCompleted=24736935701500, DisplayPresentTime=4, CommandSubmissionCompleted=24736837644800, 
[EGL_emulation] app_time_stats: avg=95.76ms min=16.90ms max=367.76ms count=10
[andco.tiaerpapp] Explicit concurrent mark compact GC freed 554KB AllocSpace bytes, 0(0B) LOS objects, 49% free, 5488KB/10MB, paused 632us,6.116ms total 26.151ms
**System.MissingMethodException:** 'Method not found: void Microsoft.Maui.Controls.Internals.PropertyPropagationExtensions.PropagatePropertyChanged(string,Microsoft.Maui.Controls.Element,System.Collections.IEnumerable)'
```

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

10.0.0-preview.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.30 SR3

### Affected platforms

Android

### Affected platform versions

Android-15 API version-35 ,IOS,Windows

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

I've added an overload to PropagatePropertyChanged to avoid potential breaks for callers such as the MCT  and to maintain backward compatibility, since the original method was internal. 

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/28450

### CODE REVIEW

File: src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs [hunk 1]
```diff
@@ -8,7 +8,7 @@ namespace Microsoft.Maui.Controls.Internals
 	/// <include file="../../../docs/Microsoft.Maui.Controls.Internals/PropertyPropagationExtensions.xml" path="Type[@FullName='Microsoft.Maui.Controls.Internals.PropertyPropagationExtensions']/Docs/*" />
 	public static class PropertyPropagationExtensions
 	{
-		internal static void PropagatePropertyChanged(string propertyName, Element element, IReadOnlyList<IVisualTreeElement> children)
```
Comment (pictos) [inline src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:11]: we can keep this one and add an overload that accepts IEnumerable, this overload can forward to this implementation. What do you think?

Comment (kubaflo) [reply src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:11]: Love it. I've added a commit. Could you please take a look?

**Review by jsuarezruiz — DISMISSED** [review]

**Review by pictos — APPROVED** [review]

File: src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs [hunk 2]
```diff
@@ -8,6 +8,14 @@ namespace Microsoft.Maui.Controls.Internals
 	/// <include file="../../../docs/Microsoft.Maui.Controls.Internals/PropertyPropagationExtensions.xml" path="Type[@FullName='Microsoft.Maui.Controls.Internals.PropertyPropagationExtensions']/Docs/*" />
 	public static class PropertyPropagationExtensions
 	{
+		internal static void PropagatePropertyChanged(string propertyName, Element element, IEnumerable children)
```
Comment (PureWeen) [inline src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:11]: Can we mark this obsolete?

File: src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs [hunk 3]
```diff
@@ -8,6 +8,14 @@ namespace Microsoft.Maui.Controls.Internals
...
+		{
+			if (children == null)
+				return;
+
+			PropagatePropertyChanged(propertyName, element, children.OfType<IVisualTreeElement>().ToList());
+		}
+
 		internal static void PropagatePropertyChanged(string propertyName, Element element, IReadOnlyList<IVisualTreeElement> children)
```
Comment (PureWeen) [inline src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:19]: Can we remove internal from this one?

**Review by PureWeen — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs (hunk 3 above)
Comment (pictos) [reply src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:21]: removing the internal would for this to be merged on .net 10, no?

Comment (mattleibow) [reply src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:21]: yeah, this will have to go into net10.

But, is there a reason for this to be IReadOnlyList instead of `IEnumerable <IVisualTreeElement>`? The result is the same as we are just calling `ToArray`

**Review by mattleibow — APPROVED** [review]

File: src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs (hunk 3 above)
Comment (mattleibow) [reply src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs:21]: I see all the other overloads take `Element`, so why does this need to be `IVisualTreeElement`?

**Comment by GitOguz** [comment]
When is this available?
