### PR TITLE
[Windows] Implemented the Resize and Downsize functions in the W2DImage class

### LINKED ISSUE #16767: Resize and Downsize function in W2DImage class is not implemented on windows
### Description

	public IImage Resize(float width, float height, ResizeMode resizeMode = ResizeMode.Fit,
			bool disposeOriginal = false)
		{
			throw new NotImplementedException();
		}

### Steps to Reproduce

	public IImage Resize(float width, float height, ResizeMode resizeMode = ResizeMode.Fit,
			bool disposeOriginal = false)
		{
			throw new NotImplementedException();
		}

### Link to public reproduction project repository

_No response_

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19041.0

### Did you find any workaround?

No

### Relevant log output

```shell
Not Implemented Exception
```

### LINKED ISSUE #28725: [Windows] ImagePaint is not rendering in View
### Description

ImagePaint is not rendering in View. This is working fine in Android platform.

Actual Output:

Image

Expected output:
Image should be drawn in the canvas instead of white background.

### Steps to Reproduce

1. Run the sample in windows 

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/9.0/UserInterface/Views/GraphicsViewDemos

### Version with bug

9.0.50 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by HarishwaranVijayakumar**
### Root Cause of the issue

- There is no implementation for the Resize and Downsize methods in the PlatformImage class on Windows.

### Description of Change

- Implemented a Resize and Downsize method in the PlatformImage class on Windows.

### Issues Fixed

Fixes #16767 
Closes #29205

### Tested the behaviour in the following platforms

- [x] - Windows
- [x] - Android
- [ ] - Mac
- [ ] - iOS

### Output

| Before Fix | After Fix |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/ea916092-bed9-4806-892e-fd9f04d90995"> | <video src="https://github.com/user-attachments/assets/31cc2e94-bbb0-4f61-ab1f-6e483a4035d8"> |

### CODE REVIEW

File: src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs [hunk 1]
```diff
@@ -51,40 +51,82 @@ public IImage Downsize(float maxWidthOrHeight, bool disposeOriginal = false)
...
+			using var renderTarget = new CanvasRenderTarget(_creator, canvasWidth, canvasHeight, _bitmap.Dpi);
+
+			using (var drawingSession = renderTarget.CreateDrawingSession())
+			{
+				drawingSession.DrawImage(_bitmap, new global::Windows.Foundation.Rect(drawX, drawY, drawWidth, drawHeight));
+			}
+
+			using (var resizedStream = new InMemoryRandomAccessStream())
+			{
+				AsyncPump.Run(async () => await renderTarget.SaveAsync(resizedStream, CanvasBitmapFileFormat.Png));
```
[the remark this answers is not in the document]
Comment (jsuarezruiz) [reply src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs:80]: Could you do some tests without `AsyncPump.Run`? Can lead to thread blocking issues.

[the remark this answers is not in the document]
Comment (HarishwaranVijayakumar) [reply src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs]: @MartyIX, As suggested I have modified the code

File: src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs [hunk 2]
```diff
@@ -51,40 +51,85 @@ public IImage Downsize(float maxWidthOrHeight, bool disposeOriginal = false)
...
+			using var renderTarget = new CanvasRenderTarget(_creator, canvasWidth, canvasHeight, _bitmap.Dpi);
+
+			using (var drawingSession = renderTarget.CreateDrawingSession())
+			{
+				drawingSession.DrawImage(_bitmap, new global::Windows.Foundation.Rect(drawX, drawY, drawWidth, drawHeight));
+			}
+
+			using (var resizedStream = new InMemoryRandomAccessStream())
+			{
+				renderTarget.SaveAsync(resizedStream, CanvasBitmapFileFormat.Png)
```
Comment (jsuarezruiz) [inline src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs:80]: I understand why you use `GetAwaiter().GetResult()` here but, could avoid it? I think you can refactor the code to use a `ManualResetEventSlim` that will signal when the operation completes. Requires to set up a completion callback on the async operation and waits for the signal that the operation is complete.

```
var saveCompletedEvent = new ManualResetEventSlim(false);

saveCompletedEvent.Wait();
```

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs (hunk 2 above)
Comment (HarishwaranVijayakumar) [reply src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs]: @jsuarezruiz As suggested, I have made the changes.

Comment (jsuarezruiz) [reply src/Graphics/src/Graphics/Platforms/Windows/PlatformImage.cs]: Try to prevents UI thread deadlocks and have a better async exception handling.

**Review by jsuarezruiz — APPROVED** [review]
