### PR TITLE
Make Add/Remove Logical public

### LINKED ISSUE #3745: DynamicResource not working for inner views
### Description

We have created a simple custom control that has multiple inner views. DynamicResource only works for the main custom control view and does not work for inner views.

Find the code for simple custom control implementation. We have implemented IVisualTreeElement also. 

```
 public class ViewExt : View, IContentView, IVisualTreeElement
    {
        public Grid ParentGrid { get; set; }
        public ViewExt()
        {
            ParentGrid = new Grid();
        }
        public View BackgroundContent
        {
            get { return (View)this.GetValue(BackgroundContentProperty); }
            set { this.SetValue(BackgroundContentProperty, value); }
        }

        public static readonly BindableProperty BackgroundContentProperty =
           BindableProperty.Create(nameof(BackgroundContent), typeof(View), typeof(ViewExt), null, propertyChanged: OnBackgroundContentPropertyChanged);

        private static void OnBackgroundContentPropertyChanged(BindableObject bindable, object oldValue, object newValue)
        {
            if(newValue is View view && bindable is ViewExt view1)
            {
                view1.ParentGrid.Children.Add(view);
            }
        }

        IReadOnlyList<IVisualTreeElement> IVisualTreeElement.GetVisualChildren()
        {
            List<Element> _logicalChildren = new();
           
            if (BackgroundContent != null)
                _logicalChildren.Add(BackgroundContent);

            return _logicalChildren.AsReadOnly();
        }

        object IContentView.Content
        {
            get
            {
                return ParentGrid;
            }
        }

        IView? IContentView.PresentedContent
        {
            get
            {
                return ParentGrid;
            }
        }

        Thickness IPadding.Padding
        {
            get
            {
                return new Thickness(0);
            }
        }

        Size IContentView.CrossPlatformMeasure(double widthConstraint, double heightConstraint)
        {
            return this.MeasureContent(widthConstraint, heightConstraint);
        }

        Size IContentView.CrossPlatformArrange(Rectangle bounds)
        {
            this.ArrangeContent(bounds);
            return bounds.Size;
        }
    }
```

```
 <VerticalStackLayout x:Name="layout">
        <VerticalStackLayout.Resources>
            <Grid Background="yellow" x:Key="bg">
                <Label Text="Background" HorizontalOptions="Center"/>
            </Grid>
            <Grid Background="red" x:Key="bg1">
                <Label Text="Background" HorizontalOptions="Center"/>
            </Grid>
        </VerticalStackLayout.Resources>

     <!--Not working-->
        <local:ViewExt >
            <local:ViewExt.BackgroundContent>
                <local:ViewExt BackgroundContent="{DynamicResource bg1}"/>
            </local:ViewExt.BackgroundContent>
        </local:ViewExt>
        
        <!--Working-->
        <local:ViewExt BackgroundContent="{DynamicResource bg}"/>

</VerticalStackLayout>

```

### Steps to Reproduce
[DynamicResourceSample.zip](https://github.com/dotnet/maui/files/7703201/DynamicResourceSample.zip)

1. Run the sample. 
2. Set the break point in C# OnBackgroundContentPropertyChanged method. 
3. See the break point not hit for inner view BackgroundContent change. 
4. Breakpoint hit only for outer view property change alone. 

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10

### Did you find any workaround?

**StaticResource working**

 <local:ViewExt >
            <local:ViewExt.BackgroundContent>
                <local:ViewExt BackgroundContent="{StaticResource bg1}"/>
            </local:ViewExt.BackgroundContent>
        </local:ViewExt>

**DynamicResource not working**

<local:ViewExt >
            <local:ViewExt.BackgroundContent>
                <local:ViewExt BackgroundContent="{DynamicResource bg1}"/>
            </local:ViewExt.BackgroundContent>
        </local:ViewExt>

### Relevant log output

_No response_

### LINKED ISSUE #15760: [regression/8.0.0-preview.5.8529] Cannot interact with RadioButton on iOS in a Popup
### Description

When putting `RadioButton`s in a toolkit Popup, I cannot interact with them on net8.0-ios. net8.0-android works fine. Other UI elements work fine, so this appears to be just `RadioButton` on net8.0-ios 

### Steps to Reproduce

Run this app with net8.0 on iOS, touch the button to launch the popup, and try to interact with the UI elements.

https://github.com/dotnet/maui/assets/41873/86531bab-fff0-4d21-90fe-7a84e741d237

### Link to public reproduction project repository

https://github.com/davidortinau/bug-radiobutton

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

7.0.49

### Affected platforms

iOS

### Affected platform versions

iOS 16.4

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

```
~Microsoft.Maui.Controls.Element.AddLogicalChild(Microsoft.Maui.Controls.Element element) -> void
~Microsoft.Maui.Controls.Element.InsertLogicalChild(int index, Microsoft.Maui.Controls.Element element) -> void
~Microsoft.Maui.Controls.Element.RemoveLogicalChild(Microsoft.Maui.Controls.Element element) -> bool
Microsoft.Maui.Controls.Element.ClearLogicalChildren() -> void
```

- Adds a set of APIs (AddLogicalChild, RemoveLogicalChild, ClearLogicalChildren, InsertLogicalChild) to streamline our setup of parent/child relationships and also allow for outside developers to opt into the benefits of becoming a logical child.

- Expose a set of public APIs on `Element` that allow users to add/remove logical children to any `Element`.  There are a number of features we have that rely on `LogicalChildren`: LiveVisualTree, HotReload, Style propagation, etc.  The `LogicalChildren` structure is currently closed off from the outside world. If someone implements a custom control based off of `Element`, there's not really an easy way for them to setup `LogicalChildren`. This makes it almost impossible for 3rd party controls to setup a proper hierarchy that will benefit from LiveVisualTree, HotReload, Style propagation, BC propagation, etc.

- Rework internal code to use these new APIs

### Examples

For example, the MCT has a `popup` control that lives on a `Page`. Because that popup can't add itself to the `LogicalChidlren` of a `Page` the `popup` control doesn't work with Hot Reload or Live Visual Tree

https://github.com/CommunityToolkit/Maui/issues/1168

```C#
var page = new ContentPage()
{
	Content = new VerticalStackLayout()
};

var customControl = new MyCustomControl();
page.AddLogicalChild(customControl);
```

fixes #3745
fixes #15760

### CODE REVIEW

File: src/Controls/src/Core/Element/Element.cs [hunk 1]
```diff
@@ -291,43 +274,67 @@ public Element Parent
...
+					// TODO Add test for switching parents
+					if (RealParent is not null && RealParent != value)
+					{
+						RealParent.RemoveLogicalChild(this);
+					}
 
-					if (value != null && (RealParent is Layout || RealParent is IControlTemplated))
-						Application.Current?.FindMauiContext()?.CreateLogger<Element>()?.LogWarning($"{this} is already a child of {RealParent}. Remove {this} from {RealParent} before adding to {value}.");
+					if (!value.LogicalChildrenInternalBackingStore.Contains(this))
+						value.AddLogicalChild(this);
```
Comment (PureWeen) [inline src/Controls/src/Core/Element/Element.cs:290]: @StephaneDelcroix are these changes ok? I'm trying to simplify and standardize the whole LogicalChildren and Parent setup so it all just operates with a consistent set of rules. 

This PR causes `ParentSetOnNullChildBindingContext` to fail

This feels like an inaccurate test to me.

image

If I've established a parent/child relationship between two `Element`'s then I feel like the BC at that point should propagate from the parent to the child. 

All this test is really validating, is that if you create a relationship from a child to a parent, that child isn't automatically added to the `LogicalChildren` and thus the BC won't propagate.

I'm hoping (maybe with incorrect assumptions) that once there's been a parent/child relationship established that the child will automatically get added into the parent's logical children. Which generally just makes everything like hot reload/live visual tree just work without having to custom connect all the relationships.

thoughts?

File: src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs [hunk 2]
```diff
@@ -143,7 +143,7 @@ public async Task CollectionViewCanSizeToContent(CollectionViewSizingTestCase te
 					await WaitForUIUpdate(frame, collectionView);
 					frame = collectionView.Frame;
 
-#if WINDOWS
+#if WINDOWS || ANDROID
```
Comment (PureWeen) [inline src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs:146]: This PR adds a slightly longer delay to [`OnLoaded`](https://github.com/dotnet/maui/pull/16046/files) this gives Android a little more time to run an `OnMeasure` loop. Because of this, `Android` also needs this wait.

File: src/Controls/src/Core/BindableObject.cs [hunk 3]
```diff
@@ -264,17 +264,12 @@ public static void SetInheritedBindingContext(BindableObject bindable, object va
...
 				SetInheritedBindingContext(buttonBehavior, BindingContext);
 
 			if (Shell.GetSearchHandler(this) is SearchHandler searchHandler)
 				SetInheritedBindingContext(searchHandler, BindingContext);
-
-			if (Shell.GetTitleView(this) is View titleView)
-				SetInheritedBindingContext(titleView, BindingContext);
-
-			if (FlyoutBase.GetContextFlyout(this) is BindableObject contextFlyout)
-				SetInheritedBindingContext(contextFlyout, BindingContext);
```
Comment (mattleibow) [inline src/Controls/src/Core/BindableObject.cs:277]: This was not a view before and may not be part of the visual tree. Is this change expected?

File: src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.cs [hunk 4]
```diff
@@ -157,7 +157,7 @@ async Task SyncPlatformModalStackAsync()
 					}
 
 					var page = await PopModalPlatformAsync(animated);
-					page.Parent = null;
+					page.Parent?.RemoveLogicalChild(page);
```
Comment (mattleibow) [inline src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.cs:160]: Is this the same thing? The code is maybe better but are you setting `Parent = null` still? Would a reverse operation extension be worth something:

```cs
page.RemoveFromLogicalParent();
```

```cs
void RemoveFromLogicalParent(this Element element)
{
  if (element.Parent is Element parent) {
    parent.RemoveLogicalChild(element);
    element.Parent = null;
  }
}
```

Comment (mattleibow) [reply src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.cs:160]: Or is this already happening because `RemoveLogicalChild` calls `OnChildRemoved`? And that appears to set the parent to null.

File: src/Controls/src/Core/Shell/Shell.cs [hunk 5]
```diff
@@ -837,7 +803,7 @@ public Shell()
 			Navigation = new NavigationImpl(this);
 			Route = Routing.GenerateImplicitRoute("shell");
 			Initialize();
-			InternalChildren.CollectionChanged += OnInternalChildrenCollectionChanged;
+			//InternalChildren.CollectionChanged += OnInternalChildrenCollectionChanged;
```
Comment (mattleibow) [inline src/Controls/src/Core/Shell/Shell.cs:806]:
```suggestion
```

File: src/Controls/src/Core/VisualElement/VisualElement.Platform.cs [hunk 6]
```diff
@@ -40,7 +40,7 @@ public partial class VisualElement
 			{
 				// My handler is still set but the window handler isn't set.
 				// This means I'm starting to detach from the platform window
-				// So we wait for the platform detatch events to fire before calling 
+				// So we wait for the platform detach events to fire before calling
```
Comment (mattleibow) [inline src/Controls/src/Core/VisualElement/VisualElement.Platform.cs:43]: detatatatatach

**Review by mattleibow — COMMENTED** [review]
This is looking really good - makes me so happy to remove all the internal magic!

File: src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.cs (hunk 4 above)
Comment (PureWeen) [reply src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.cs:160]: > Or is this already happening because `RemoveLogicalChild` calls `OnChildRemoved`? And that appears to set the parent to null.

Yes, `RemoveLogicalChild` takes care of setting the parent to null. 

I actually have another branch from this PR where setting the parent literally just routes to `AddLogicalChild` and `RemoveLogicalChild`. I tried doing that with this PR but ran into some issues because `TableView` and `ListView` are setup in a really weird way :-/ 

I have a branch that does this, which I'm hoping to get in for NET8 to just try and standardize everything. But we'll see

image

File: src/Controls/src/Core/Items/ItemsView.cs [hunk 7]
```diff
@@ -109,12 +109,12 @@ public int RemainingItemsThreshold
 		}
 
 		/// <include file="../../../docs/Microsoft.Maui.Controls/ItemsView.xml" path="//Member[@MemberName='AddLogicalChild']/Docs/*" />
-		public void AddLogicalChild(Element element) =>
-			AddLogicalChildInternal(element);
+		public new void AddLogicalChild(Element element) =>
+			base.AddLogicalChild(element);
```
[the remark this answers is not in the document]
Comment (PureWeen) [reply src/Controls/src/Core/Items/ItemsView.cs]: ALL GONE!!!!!!

**Review by mattleibow — APPROVED** [review]
