### PR TITLE
[HybridWebView] Add support for async .NET methods

### LINKED ISSUE #25968: Calling a method that returns `Task` from JS will throw
### Description

The calls from JS are all synchronous and this makes it hard to do anything that requires async code.

### Steps to Reproduce

TODO

### Link to public reproduction project repository

N/A

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

This PR makes the call from JS into .NET be able to support async methods (return `Task` or `Task<T>`)

This PR has a fair bit of things moving around because of the async and the fact that I wanted to make the code flow the same on all the platforms. The code was getting a bit nested, so I broke things out into methods.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/25968

### CODE REVIEW

File: src/Core/src/Platform/Android/MauiHybridWebViewClient.cs [hunk 1]
```diff
@@ -147,5 +148,116 @@ internal void Disconnect()
 		{
 			_handler.SetTarget(null);
 		}
+
+		private class DotNetInvokeAsyncStream : Stream
```
Comment (mattleibow) [inline src/Core/src/Platform/Android/MauiHybridWebViewClient.cs:152]: I probably over engineered this, but I am using pipes to allow myself to read and write. I probably could simplify this and just block, but this appears to work.

File: src/Core/src/Platform/Android/MauiHybridWebViewClient.cs [hunk 2]
```diff
@@ -147,5 +148,116 @@ internal void Disconnect()
...
+				ArgumentOutOfRangeException.ThrowIfNegative(count, nameof(count));
+				ArgumentOutOfRangeException.ThrowIfGreaterThan(offset + count, buffer.Length, nameof(count));
+				if (_isDisposed)
+				{
+					throw new ObjectDisposedException(nameof(DotNetInvokeAsyncStream));
+				}
+
+				var bytesRead = 0;
+
+				var readResult = _pipe.Reader.ReadAsync().ConfigureAwait(false).GetAwaiter().GetResult();
```
Comment (Eilon) [inline src/Core/src/Platform/Android/MauiHybridWebViewClient.cs:211]: How dangerous is this?

File: src/Core/src/Platform/Android/MauiHybridWebViewClient.cs [hunk 3]
```diff
@@ -147,5 +148,116 @@ internal void Disconnect()
...
+
+				_pipe = new Pipe(new PipeOptions(
+					pauseWriterThreshold: PauseThreshold,
+					resumeWriterThreshold: ResumeThreshold,
+					useSynchronizationContext: false));
+
+				StartReading();
+			}
+
+			private async void StartReading()
```
Comment (Eilon) [inline src/Core/src/Platform/Android/MauiHybridWebViewClient.cs:188]: This async void concerns me if the stream throws. I'm imagining a scenario where the method being invoked throws an exception from a property getter and then this crashes the whole process or something?

File: src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.iOS.cs [hunk 4]
```diff
@@ -137,82 +138,90 @@ public SchemeHandler(HybridWebViewHandler webViewHandler)
 
 			[Export("webView:startURLSchemeTask:")]
 			[SupportedOSPlatform("ios11.0")]
-			public void StartUrlSchemeTask(WKWebView webView, IWKUrlSchemeTask urlSchemeTask)
+			public async void StartUrlSchemeTask(WKWebView webView, IWKUrlSchemeTask urlSchemeTask)
```
Comment (Eilon) [inline src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.iOS.cs:141]: `async void` alert

**Comment by HelloooJoe** [comment]
Any ETA when with this be available in .NET MAUI? Either in preview or other?

File: src/Core/src/Platform/Android/MauiHybridWebViewClient.cs (hunk 3 above)
Comment (mattleibow) [reply src/Core/src/Platform/Android/MauiHybridWebViewClient.cs]: fixed

File: src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.iOS.cs (hunk 4 above)
Comment (mattleibow) [reply src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.iOS.cs:145]: added a comment. this is ok as this method is an event and there is a "completed" method you call once you are done.

File: src/Core/src/Platform/Android/MauiHybridWebViewClient.cs (hunk 2 above)
Comment (mattleibow) [reply src/Core/src/Platform/Android/MauiHybridWebViewClient.cs]: Seems to work, and looks to be the only way.

**Review by tj-devel709 — APPROVED** [review]

**Comment by mattleibow** [comment]
Test failures unrelated to this PR
