### PR TITLE
[Android] Fix crash using Shadows on ListView ViewCell

### LINKED ISSUE #8252: Shadow crashes the app when used on root element of a ViewCell
### Description

Application crashes when setting a `Shadow` on the root element of a `ViewCell`.
DotNet version: 6.0.400-preview.22301.10

### Steps to Reproduce

Set a shadow on the root element of a `ViewCell` like in the example below. I've tested with `Border` and `Image` with the same result.

```
        <ListView ItemsSource="{Binding Automations}">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <Border>
                            <Border.Shadow>
                                <Shadow />
                            </Border.Shadow>
                        </Border>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
```

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

Yes, if you wrap the `Border` within a `Grid`, then everything works as expected.

```
                <ViewCell>
                    <Grid>
                        <Border>
                            <Border.Shadow>
                                <Shadow />
                            </Border.Shadow>
                        </Border>
                    </Grid>
                </ViewCell>
```

### Relevant log output

```shell
[.ifthisthenwha] runtime.cc:677] JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethodA called with pending exception android.runtime.JavaProxyThrowable: Microsoft.Maui.Platform.ToPlatformException: Microsoft.Maui.Controls.Handlers.Compatibility.ViewCellRenderer found for Microsoft.Maui.Controls.ViewCell is incompatible
[.ifthisthenwha] runtime.cc:677]  ---> Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[.ifthisthenwha] runtime.cc:677]    at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:line 12324
[.ifthisthenwha] runtime.cc:677]    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 35
[.ifthisthenwha] runtime.cc:677]    at Android.Views.ViewGroup.AddView(View child) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-32/mcw/Android.Views.ViewGroup.cs:line 1999
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Controls.Handlers.Compatibility.ViewCellRenderer.ViewCellContainer.AddView(View child) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\ListView\Android\ViewCellRenderer.cs:line 271
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Controls.Handlers.Compatibility.ViewCellRenderer.ViewCellContainer..ctor(Context context, IPlatformViewHandler view, ViewCell viewCell, View parent, BindableProperty unevenRows, BindableProperty rowHeight) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\ListView\Android\ViewCellRenderer.cs:line 144
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Controls.Handlers.Compatibility.ViewCellRenderer.GetCellCore(Cell item, View convertView, ViewGroup parent, Context context) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\ListView\Android\ViewCellRenderer.cs:line 54
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Controls.Handlers.Compatibility.CellRenderer.GetCell(Cell item, View convertView, ViewGroup parent, Context context) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\ListView\Android\CellRenderer.cs:line 71
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Controls.Handlers.Compatibility.CellRenderer.CreatePlatformElement() in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\ListView\Android\CellRenderer.cs:line 37
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Handlers.ElementHandler`2[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].OnCreatePlatformElement() in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandlerOfT.cs:line 46
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Handlers.ElementHandler.CreatePlatformElement() in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 96
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 52
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 64
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 20
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 98
[.ifthisthenwha] runtime.cc:677]   --- End of managed Java.Lang.IllegalStateException stack trace ---
[.ifthisthenwha] runtime.cc:677] java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5247)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.addView(ViewGroup.java:5076)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.addView(ViewGroup.java:5016)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.addView(ViewGroup.java:4988)
[.ifthisthenwha] runtime.cc:677] 	at crc64e1fb321c08285b90.ListViewAdapter.n_getView(Native Method)
[.ifthisthenwha] runtime.cc:677] 	at crc64e1fb321c08285b90.ListViewAdapter.getView(ListViewAdapter.java:100)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:224)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.AbsListView.obtainView(AbsListView.java:2398)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.ListView.makeAndAddView(ListView.java:2067)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.ListView.fillDown(ListView.java:793)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.ListView.fillSpecific(ListView.java:1504)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.ListView.layoutChildren(ListView.java:1802)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.AbsListView.onLayout(AbsListView.java:2195)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at crc64e1fb321c08285b90.ListViewRenderer.n_onLayout(Native Method)
[.ifthisthenwha] runtime.cc:677] 	at crc64e1fb321c08285b90.ListViewRenderer.onLayout(ListViewRenderer.java:71)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at crc6452ffdc5b34af3a0f.LayoutViewGroup.n_onLayout(Native Method)
[.ifthisthenwha] runtime.cc:677] 	at crc6452ffdc5b34af3a0f.LayoutViewGroup.onLayout(LayoutViewGroup.java:63)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at crc6452ffdc5b34af3a0f.ContentViewGroup.n_onLayout(Native Method)
[.ifthisthenwha] runtime.cc:677] 	at crc6452ffdc5b34af3a0f.ContentViewGroup.onLayout(ContentViewGroup.java:71)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at crc640ec207abc449b2ca.ShellPageContainer.n_onLayout(Native Method)
[.ifthisthenwha] runtime.cc:677] 	at crc640ec207abc449b2ca.ShellPageContainer.onLayout(ShellPageContainer.java:54)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
[.ifthisthenwha] runtime.cc:677] 	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
[.ifthisthenwha] runtime.cc:677] 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2172)
[.ifthisthenwha] runtime.cc:677] 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:953)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677] 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:798)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3684)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
[.ifthisthenwha] runtime.cc:677] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
[.ifthisthenwha] runtime.cc:677] 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
[.ifthisthenwha] runtime.cc:677] 	at android.view.Choreographer.doFrame(Choreographer.java:780)
[.ifthisthenwha] runtime.cc:677] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
[.ifthisthenwha] runtime.cc:677] 	at android.os.Handler.handleCallback(Handler.java:938)
[.ifthisthenwha] runtime.cc:677] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[.ifthisthenwha] runtime.cc:677] 	at android.os.Looper.loopOnce(Looper.java:201)
[.ifthisthenwha] runtime.cc:677] 	at android.os.Looper.loop(Looper.java:288)
[.ifthisthenwha] runtime.cc:677] 	at android.app.ActivityThread.main(ActivityThread.java:7839)
[.ifthisthenwha] runtime.cc:677] 	at java.lang.reflect.Method.invoke(Native Method)
[.ifthisthenwha] runtime.cc:677] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[.ifthisthenwha] runtime.cc:677] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[.ifthisthenwha] runtime.cc:677] 
[.ifthisthenwha] runtime.cc:677]   --- End of managed Java.Lang.IllegalStateException stack trace ---
[.ifthisthenwha] runtime.cc:677] java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5247)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.addView(ViewGroup.java:5076)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.addView(ViewGroup.java:5016)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.addView(ViewGroup.java:4988)
[.ifthisthenwha] runtime.cc:677] 	at crc64e1fb321c08285b90.ListViewAdapter.n_getView(Native Method)
[.ifthisthenwha] runtime.cc:677] 	at crc64e1fb321c08285b90.ListViewAdapter.getView(ListViewAdapter.java:100)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:224)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.AbsListView.obtainView(AbsListView.java:2398)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.ListView.makeAndAddView(ListView.java:2067)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.ListView.fillDown(ListView.java:793)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.ListView.fillSpecific(ListView.java:1504)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.ListView.layoutChildren(ListView.java:1802)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.AbsListView.onLayout(AbsListView.java:2195)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at crc64e1fb321c08285b90.ListViewRenderer.n_onLayout(Native Method)
[.ifthisthenwha] runtime.cc:677] 	at crc64e1fb321c08285b90.ListViewRenderer.onLayout(ListViewRenderer.java:71)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at crc6452ffdc5b34af3a0f.LayoutViewGroup.n_onLayout(Native Method)
[.ifthisthenwha] runtime.cc:677] 	at crc6452ffdc5b34af3a0f.LayoutViewGroup.onLayout(LayoutViewGroup.java:63)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at crc6452ffdc5b34af3a0f.ContentViewGroup.n_onLayout(Native Method)
[.ifthisthenwha] runtime.cc:677] 	at crc6452ffdc5b34af3a0f.ContentViewGroup.onLayout(ContentViewGroup.java:71)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at crc640ec207abc449b2ca.ShellPageContainer.n_onLayout(Native Method)
[.ifthisthenwha] runtime.cc:677] 	at crc640ec207abc449b2ca.ShellPageContainer.onLayout(ShellPageContainer.java:54)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
[.ifthisthenwha] runtime.cc:677] 	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
[.ifthisthenwha] runtime.cc:677] 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2172)
[.ifthisthenwha] runtime.cc:677] 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:953)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677] 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:798)
[.ifthisthenwha] runtime.cc:677] 	at android.view.View.layout(View.java:23143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewGroup.layout(ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3684)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3143)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
[.ifthisthenwha] runtime.cc:677] 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
[.ifthisthenwha] runtime.cc:677] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
[.ifthisthenwha] runtime.cc:677] 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
[.ifthisthenwha] runtime.cc:677] 	at android.view.Choreographer.doFrame(Choreographer.java:780)
[.ifthisthenwha] runtime.cc:677] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
[.ifthisthenwha] runtime.cc:677] 	at android.os.Handler.handleCallback(Handler.java:938)
[.ifthisthenwha] runtime.cc:677] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[.ifthisthenwha] runtime.cc:677] 	at android.os.Looper.loopOnce(Looper.java:201)
[.ifthisthenwha] runtime.cc:677] 	at android.os.Looper.loop(Looper.java:288)
[.ifthisthenwha] runtime.cc:677] 	at android.app.ActivityThread.main(ActivityThread.java:7839)
[.ifthisthenwha] runtime.cc:677] 	at java.lang.reflect.Method.invoke(Native Method)
[.ifthisthenwha] runtime.cc:677] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[.ifthisthenwha] runtime.cc:677] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[.ifthisthenwha] runtime.cc:677] 
[.ifthisthenwha] runtime.cc:677]    --- End of inner exception stack trace ---
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 113
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 142
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Controls.Handlers.Compatibility.CellFactory.GetCell(Cell item, View convertView, ViewGroup parent, Context context, View view) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\ListView\Android\CellFactory.cs:line 20
[.ifthisthenwha] runtime.cc:677]    at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewAdapter.GetView(Int32 position, View convertView, ViewGroup parent) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\ListView\Android\ListViewAdapter.cs:line 331
[.ifthisthenwha] runtime.cc:677]    at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_(IntPtr jnienv, IntPtr native__this, Int32 position, IntPtr native_convertView, IntPtr native_parent) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-32/mcw/Android.Widget.BaseAdapter.cs:line 538
[.ifthisthenwha] runtime.cc:677]   at android.view.View crc64e1fb321c08285b90.ListViewAdapter.n_getView(int, android.view.View, android.view.ViewGroup) (ListViewAdapter.java:-2)
[.ifthisthenwha] runtime.cc:677]   at android.view.View crc64e1fb321c08285b90.ListViewAdapter.getView(int, android.view.View, android.view.ViewGroup) (ListViewAdapter.java:100)
[.ifthisthenwha] runtime.cc:677]   at android.view.View android.widget.HeaderViewListAdapter.getView(int, android.view.View, android.view.ViewGroup) (HeaderViewListAdapter.java:224)
[.ifthisthenwha] runtime.cc:677]   at android.view.View android.widget.AbsListView.obtainView(int, boolean[]) (AbsListView.java:2398)
[.ifthisthenwha] runtime.cc:677]   at android.view.View android.widget.ListView.makeAndAddView(int, int, boolean, int, boolean) (ListView.java:2067)
[.ifthisthenwha] runtime.cc:677]   at android.view.View android.widget.ListView.fillDown(int, int) (ListView.java:793)
[.ifthisthenwha] runtime.cc:677]   at android.view.View android.widget.ListView.fillSpecific(int, int) (ListView.java:1504)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.ListView.layoutChildren() (ListView.java:1802)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.AbsListView.onLayout(boolean, int, int, int, int) (AbsListView.java:2195)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(boolean, int, int, int, int) (SwipeRefreshLayout.java:689)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void crc64e1fb321c08285b90.ListViewRenderer.n_onLayout(boolean, int, int, int, int) (ListViewRenderer.java:-2)
[.ifthisthenwha] runtime.cc:677]   at void crc64e1fb321c08285b90.ListViewRenderer.onLayout(boolean, int, int, int, int) (ListViewRenderer.java:71)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void crc6452ffdc5b34af3a0f.LayoutViewGroup.n_onLayout(boolean, int, int, int, int) (LayoutViewGroup.java:-2)
[.ifthisthenwha] runtime.cc:677]   at void crc6452ffdc5b34af3a0f.LayoutViewGroup.onLayout(boolean, int, int, int, int) (LayoutViewGroup.java:63)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void crc6452ffdc5b34af3a0f.ContentViewGroup.n_onLayout(boolean, int, int, int, int) (ContentViewGroup.java:-2)
[.ifthisthenwha] runtime.cc:677]   at void crc6452ffdc5b34af3a0f.ContentViewGroup.onLayout(boolean, int, int, int, int) (ContentViewGroup.java:71)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void crc640ec207abc449b2ca.ShellPageContainer.n_onLayout(boolean, int, int, int, int) (ShellPageContainer.java:-2)
[.ifthisthenwha] runtime.cc:677]   at void crc640ec207abc449b2ca.ShellPageContainer.onLayout(boolean, int, int, int, int) (ShellPageContainer.java:54)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(androidx.coordinatorlayout.widget.CoordinatorLayout, android.view.View, int) (HeaderScrollingViewBehavior.java:148)
[.ifthisthenwha] runtime.cc:677]   at boolean com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(androidx.coordinatorlayout.widget.CoordinatorLayout, android.view.View, int) (ViewOffsetBehavior.java:43)
[.ifthisthenwha] runtime.cc:677]   at boolean com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(androidx.coordinatorlayout.widget.CoordinatorLayout, android.view.View, int) (AppBarLayout.java:2172)
[.ifthisthenwha] runtime.cc:677]   at void androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(boolean, int, int, int, int) (CoordinatorLayout.java:953)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.FrameLayout.layoutChildren(int, int, int, int, boolean) (FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.FrameLayout.onLayout(boolean, int, int, int, int) (FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.LinearLayout.setChildFrame(android.view.View, int, int, int, int) (LinearLayout.java:1829)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.LinearLayout.layoutVertical(int, int, int, int) (LinearLayout.java:1673)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.LinearLayout.onLayout(boolean, int, int, int, int) (LinearLayout.java:1582)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.FrameLayout.layoutChildren(int, int, int, int, boolean) (FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.FrameLayout.onLayout(boolean, int, int, int, int) (FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void androidx.drawerlayout.widget.DrawerLayout.onLayout(boolean, int, int, int, int) (DrawerLayout.java:1263)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.LinearLayout.setChildFrame(android.view.View, int, int, int, int) (LinearLayout.java:1829)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.LinearLayout.layoutHorizontal(int, int, int, int) (LinearLayout.java:1818)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.LinearLayout.onLayout(boolean, int, int, int, int) (LinearLayout.java:1584)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.FrameLayout.layoutChildren(int, int, int, int, boolean) (FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.FrameLayout.onLayout(boolean, int, int, int, int) (FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.FrameLayout.layoutChildren(int, int, int, int, boolean) (FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.FrameLayout.onLayout(boolean, int, int, int, int) (FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.FrameLayout.layoutChildren(int, int, int, int, boolean) (FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.FrameLayout.onLayout(boolean, int, int, int, int) (FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.LinearLayout.setChildFrame(android.view.View, int, int, int, int) (LinearLayout.java:1829)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.LinearLayout.layoutVertical(int, int, int, int) (LinearLayout.java:1673)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.LinearLayout.onLayout(boolean, int, int, int, int) (LinearLayout.java:1582)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.FrameLayout.layoutChildren(int, int, int, int, boolean) (FrameLayout.java:332)
[.ifthisthenwha] runtime.cc:677]   at void android.widget.FrameLayout.onLayout(boolean, int, int, int, int) (FrameLayout.java:270)
[.ifthisthenwha] runtime.cc:677]   at void com.android.internal.policy.DecorView.onLayout(boolean, int, int, int, int) (DecorView.java:798)
[.ifthisthenwha] runtime.cc:677]   at void android.view.View.layout(int, int, int, int) (View.java:23143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewGroup.layout(int, int, int, int) (ViewGroup.java:6412)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewRootImpl.performLayout(android.view.WindowManager$LayoutParams, int, int) (ViewRootImpl.java:3684)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewRootImpl.performTraversals() (ViewRootImpl.java:3143)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewRootImpl.doTraversal() (ViewRootImpl.java:2126)
[.ifthisthenwha] runtime.cc:677]   at void android.view.ViewRootImpl$TraversalRunnable.run() (ViewRootImpl.java:8653)
[.ifthisthenwha] runtime.cc:677]   at void android.view.Choreographer$CallbackRecord.run(long) (Choreographer.java:1037)
[.ifthisthenwha] runtime.cc:677]   at void android.view.Choreographer.doCallbacks(int, long, long) (Choreographer.java:845)
[.ifthisthenwha] runtime.cc:677]   at void android.view.Choreographer.doFrame(long, int, android.view.DisplayEventReceiver$VsyncEventData) (Choreographer.java:780)
[.ifthisthenwha] runtime.cc:677]   at void android.view.Choreographer$FrameDisplayEventReceiver.run() (Choreographer.java:1022)
[.ifthisthenwha] runtime.cc:677]   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:938)
[.ifthisthenwha] runtime.cc:677]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
[.ifthisthenwha] runtime.cc:677]   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:201)
[.ifthisthenwha] runtime.cc:677]   at void android.os.Looper.loop() (Looper.java:288)
[.ifthisthenwha] runtime.cc:677]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7839)
[.ifthisthenwha] runtime.cc:677]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
[.ifthisthenwha] runtime.cc:677]   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:548)
[.ifthisthenwha] runtime.cc:677]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1003)
[.ifthisthenwha] runtime.cc:677] 
[.ifthisthenwha] runtime.cc:677]     in call to CallObjectMethodA
[.ifthisthenwha] runtime.cc:677]     from android.view.View crc64e1fb321c08285b90.ListViewAdapter.n_getView(int, android.view.View, android.view.ViewGroup)
[libc] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 23688 (.ifthisthenwhat), pid 23688 (.ifthisthenwhat)
```

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix crash using Shadows on Android ListView ViewCell.

### Issues Fixed

Fixes #8252

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ViewCellRenderer.cs [hunk 1]
```diff
@@ -268,8 +268,16 @@ public void DisconnectHandler()
 
 			public override void AddView(AView child)
 			{
-				base.AddView(child);
-				_currentView = child;
+				if (child.Parent is WrapperView wrapperView)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ViewCellRenderer.cs:271]: With shadows, the View is wrapped with a container, WrapperView, and for that reason the view already has a Parent.

**Review by rmarinho — APPROVED** [review]

**Comment by rmarinho** [comment]
Do we have the same issue with collectionView ?

**Comment by jsuarezruiz** [comment]
> Do we have the same issue with collectionView ?

I think so, I am going to review it.
