### PR TITLE
Fix Flyout and TitleView Offset Measurements

### LINKED ISSUE #11679: [iOS] Spacing between `Header` and `FlyoutItems` on iOS only
### Description

When I'm running my app on iOS, I get a space between the `HeaderTemplate` and the first `FlyoutItem`.
Running the same project on Android is working fine.

```cs
<Shell.FlyoutHeader>
        <Grid
            HeightRequest="92"
            BackgroundColor="{AppThemeBinding Light={StaticResource Gray800}, Dark={StaticResource Gray200}}"
            >
            <Label
                Text="Just a simple header"
                TextColor="{AppThemeBinding Light={StaticResource Black}, Dark={StaticResource White}}"
                />
        </Grid>
    </Shell.FlyoutHeader>

    <FlyoutItem
        Title="MainpPage" 
        >
        <ShellContent
            ContentTemplate="{DataTemplate local:MainPage}"
            Route="DashboardPage"
            />
    </FlyoutItem>
```

iOS 

Android

Screenshot_1669531325

### Steps to Reproduce

1. User the repro provided
2. Run on Android and iOS
3. Compare both flyout menus

### Link to public reproduction project repository

https://github.com/AndreasReitberger/ReproScrollingIssueModal

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16, haven't tried any older version

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

Rework the Shell Flyout Templates/TitleView to mesh with .NET MAUI layout rules.  The measuring and arranging of the templates needed to adjust for how margins are applied with the new layout system. This PR also streamlines the measuring/arranging so it's more part of the lifecycle instead of just randomly calling "remeasure" at different points in time hoping you'll eventually end up with things measured correctly. 

This also decouples the `Margin` property from the `SafeArea`. Instead of applying the safe area to the margin we just apply the safe area to the container views if the user hasn't indicated they want to control the margins. 

TitleView and Flyout Templates use the same platform containers which is why this PR addresses both.

### Issues Fixed

Fixes #11679

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/UIContainerView.cs [hunk 1]
```diff
@@ -13,6 +13,8 @@ public class UIContainerView : UIView
 		IPlatformViewHandler _renderer;
 		UIView _platformView;
 		bool _disposed;
+		private double _measuredHeight;
```
Comment (rmarinho) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/UIContainerView.cs:16]:
```suggestion
	double _measuredHeight;
```

Comment (rmarinho) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/UIContainerView.cs:16]:
```suggestion
		double _measuredHeight;
```

File: src/Controls/src/Core/HandlerImpl/Toolbar/Toolbar.Android.cs [hunk 2]
```diff
@@ -31,8 +31,6 @@ public partial class Toolbar
 				if (_platformTitleView != null)
 					_platformTitleView.Child = null;
 
-				_platformTitleViewHandler?.DisconnectHandler();
```
Comment (mattleibow) [inline src/Controls/src/Core/HandlerImpl/Toolbar/Toolbar.Android.cs:34]: I see these have been removed, is this not needed or we don't need these events to fire anymore?

File: src/Controls/src/Core/HandlerImpl/Toolbar/Toolbar.Android.cs [hunk 3]
```diff
@@ -213,7 +195,6 @@ public Container(Context context) : base(context)
 			{
 				set
 				{
-					_child?.DisconnectHandler();
```
Comment (mattleibow) [inline src/Controls/src/Core/HandlerImpl/Toolbar/Toolbar.Android.cs:216]: And the child is no longer getting the events.

File: src/Controls/src/Core/HandlerImpl/Toolbar/Toolbar.Android.cs (hunk 2 above)
Comment (PureWeen) [reply src/Controls/src/Core/HandlerImpl/Toolbar/Toolbar.Android.cs:34]: There are a couple annoying players here. 

1) `TitleView` could probably use a `Templated` version so a new xplat view gets created for different `Toolbar` instances
2) It's annoying that `Shell` creates different `Toolbars` in the first place. Like, on shell when you push a page it recreates an entire coordinatorlayout with a new toolbar. When you navigate through tabs it creates a new toolbar for each tab. 

So, the `TitleView` might get reused if you're specifying the `TitleView` on the `Shell` itself, then the view/handler will get moved to a different `Toolbar` so we don't want to disconnect the handler here.

File: src/Controls/src/Core/HandlerImpl/Toolbar/Toolbar.Android.cs (hunk 3 above)
Comment (PureWeen) [reply src/Controls/src/Core/HandlerImpl/Toolbar/Toolbar.Android.cs:216]: Same comment from here https://github.com/dotnet/maui/pull/12480/files#r1134288780

Plus, some of this code isn't really as relevant currently because we have more places where `handlers` will get disconnected. 

1) If the `MauiContext` gest changed the handler will disconnect
2) if a new handler is set on a `virtualview` the previous handler will get disconnected. 

That second one wasn't really the case when this was originally written so we don't aggressively need to disconnect here.

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutLayoutManager.cs [hunk 4]
```diff
@@ -352,8 +383,36 @@ public void OnScrolled(nfloat contentOffsetY)
...
+		double MeasuredHeaderViewHeightWithNoMargin
+		{
+			get
+			{
+				if (HeaderView is not null)
+					return HeaderView.MeasuredHeight;
+
+				return HeaderView?.MeasuredHeight ?? 0;
+			}
+		}
```
[the remark this answers is not in the document]
Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutLayoutManager.cs:395]: 👍

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutLayoutManager.cs [hunk 5]
```diff
@@ -352,8 +383,36 @@ public void OnScrolled(nfloat contentOffsetY)
...
+		double HeaderMinimumHeight
+		{
+			get
+			{
+				if (HeaderView is null ||
+					HeaderView.View.MinimumHeightRequest == -1 ||
+					HeaderView.View.MinimumHeightRequest == Dimension.Unset)
+				{
+					if (_context.Shell.FlyoutHeaderBehavior == FlyoutHeaderBehavior.CollapseOnScroll)
+						return 56;
```
[the remark this answers is not in the document]
Comment (PureWeen) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutLayoutManager.cs:406]: Moved to a constant and added a comment. That's the value the original `Shell` author used so I just didn't change it. It's based on the height of the `Toolbar` on `Android.  With this PR users can change the value now if they want to via MinHeightRequest.

**Review by rmarinho — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]
