### PR TITLE
[Android] Fix issues rendering gradients and CornerRadius on Button

### LINKED ISSUE #5930: [mauipalooza] CornerRadius not working on Button
### Description

iOS:
Screen Shot 2022-04-08 at 5 55 52 PM

Android:
Screen Shot 2022-04-09 at 10 14 29 AM

```xaml
<Button Text="Get Started"
                HeightRequest="70"
                Margin="40"
                FontSize="21"
                FontFamily="OpenSansSemiBold"
                Clicked="Button_Clicked"
                CornerRadius="7"
                Background="{StaticResource BlueGradient}"
                >
        </Button>
```

https://github.com/davidortinau/dotnet-airlines

### Steps to Reproduce

Run this on iOS or Mac.

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android, iOS, macOS

### Affected platform versions

15.4, API 30

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #5950: [mauipalooza] Button background doesn't render gradient
### Description

This is only happening on Android. The button background is a gradient, but doesn't render.

Screenshot_1649517645

```xaml
<Button Text="Find Flights"
                HeightRequest="70"
                FontSize="21"
                FontFamily="OpenSansSemiBold" CornerRadius="7"
                Background="{StaticResource BlueGradient}"/>
```

From styles:
```xaml
<LinearGradientBrush x:Key="BlueGradient" EndPoint="1,0">
        <GradientStop Color="#3784DE"
                          Offset="1.0" />
        <GradientStop Color="#7BD2FD"
                          Offset="0.1" />
    </LinearGradientBrush>
```

iOS for comparison:
Simulator Screen Shot - iPhone 13 Pro - 2022-04-08 at 18 00 53

### Steps to Reproduce

Run https://github.com/davidortinau/dotnet-airlines

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix issues rendering gradients and corner radius on Android Button.

image

### Issues Fixed

Fixes #5950
Fixes #5930

### CODE REVIEW

File: src/Core/src/Platform/Android/ButtonExtensions.cs [hunk 1]
```diff
@@ -6,22 +6,50 @@ namespace Microsoft.Maui.Platform
...
+		public static void UpdateBackground(this MaterialButton platformView, IButton button)
 		{
-			if (buttonStroke.StrokeColor is Color stroke)
-				platformButton.StrokeColor = ColorStateListExtensions.CreateButton(stroke.ToPlatform());
+			var background = button.Background;
+
+			if (background is SolidPaint)
+				platformView.UpdateBackground(background);
+			else
+				platformView.UpdateBorderDrawable(button);
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/ButtonExtensions.cs:16]: Why do we have this issue? Basically because we have implemented Handlers, in this specific case the Button in different phases and we have not detected this problem with tests. We initially implement the Background property using an **AppCompatButton**. Subsequently, by implementing properties related to the Border (BorderWidth, etc) we change the type of native control to use for a **MaterialButton**.

The MaterialButton requires **BackgroundTintList** to be set to null in order to render a custom background. If a custom background is set, a Drawable is used where the background is drawn and, if there is a border, use the Drawabable too. Otherwise, the BackgroundColor property and the StrokeWidth etc properties of the MaterialButton itself are used.

**Review by Redth — APPROVED** [review]
