### PR TITLE
Make sure ImageButton always has a background

### LINKED ISSUE #22603: Button/ImageButton RippleEffect not working in some cases
### Description

This PR (https://github.com/dotnet/maui/pull/22298) should fix the ripple effect on android. It works in almost every case but there are some cases which don't work.

### Steps to Reproduce

Open repro app. The first three image buttons are not working.

image

[MauiApp9.zip](https://github.com/dotnet/maui/files/15416861/MauiApp9.zip)

### Link to public reproduction project repository

_No response_

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

The OS does not specify a background so we need to make sure there is a transparent background to get the ripple and border.

We can't really test ripple and we can't really test a null background vs a transparent background as they are supposed to look exactly the same.

The original issue was observing a lack of ripple on white, but this is because the ripple is white. In traditional buttons, there is a `RippleColor` property on the platform view. However, on image buttons, the control is just an image view so does not have any ripple effects - we are adding it. It will have to be a separate platform effect to add a ripple color property.

See https://github.com/dotnet/maui/issues/22805

### Issues Fixed

Fixes #22603

**Before**

> Notice the lack of a ripple on the top right button

[before.webm](https://github.com/dotnet/maui/assets/1096616/2257685e-bb33-4b0e-98a6-8478014aa70d)

**After**

Now the top right button has a ripple

[after.webm](https://github.com/dotnet/maui/assets/1096616/2ac1e79e-fde8-400d-be42-8aabbce01dca)

<details>

<summary>DEMO CODE</summary>

```xaml
  <Grid ColumnDefinitions="*,*">

      <VerticalStackLayout Padding="30"
                           Spacing="10"
                           Background="White"
                           Grid.Column="0">
          <Label Text="NULL Background"
                 TextColor="Gray"/>
          <ImageButton Aspect="Center"
                       CornerRadius="8"
                       HeightRequest="80"
                       WidthRequest="80"
                       Source="{FontImage FontFamily='Ionicons', Glyph='&#xF32B;', Color='DarkOrange', Size='60'}"/>
          <Label Text="TRANSPARENT Background"
                 TextColor="Gray"/>
          <ImageButton Background="Transparent"
                       Aspect="Center"
                       CornerRadius="8"
                       WidthRequest="80"
                       HeightRequest="80"
                       Source="{FontImage FontFamily='Ionicons', Glyph='&#xF32B;', Color='DarkOrange', Size='60'}"/>
          <Label Text="WHITE Background"
                 TextColor="Gray"/>
          <ImageButton Background="White"
                       Aspect="Center"
                       CornerRadius="8"
                       WidthRequest="80"
                       HeightRequest="80"
                       Source="{FontImage FontFamily='Ionicons', Glyph='&#xF32B;', Color='DarkOrange', Size='60'}"/>
          <Label Text="COLOR Background"
                 TextColor="Gray"/>
          <ImageButton Background="DarkSlateGray"
                       Aspect="Center"
                       CornerRadius="8"
                       WidthRequest="80"
                       HeightRequest="80"
                       Source="{FontImage FontFamily='Ionicons', Glyph='&#xF32B;', Color='DarkOrange', Size='60'}"/>
      </VerticalStackLayout>

      <VerticalStackLayout Padding="30"
                           Spacing="10"
                           Background="Black"
                           Grid.Column="1">
          <Label Text="NULL Background"
                 TextColor="Gray"/>
          <ImageButton Aspect="Center"
                       CornerRadius="8"
                       HeightRequest="80"
                       WidthRequest="80"
                       Source="{FontImage FontFamily='Ionicons', Glyph='&#xF32B;', Color='DarkOrange', Size='60'}"/>
          <Label Text="TRANSPARENT Background"
                 TextColor="Gray"/>
          <ImageButton Background="Transparent"
                       Aspect="Center"
                       CornerRadius="8"
                       WidthRequest="80"
                       HeightRequest="80"
                       Source="{FontImage FontFamily='Ionicons', Glyph='&#xF32B;', Color='DarkOrange', Size='60'}"/>
          <Label Text="WHITE Background"
                 TextColor="Gray"/>
          <ImageButton Background="White"
                       Aspect="Center"
                       CornerRadius="8"
                       WidthRequest="80"
                       HeightRequest="80"
                       Source="{FontImage FontFamily='Ionicons', Glyph='&#xF32B;', Color='DarkOrange', Size='60'}"/>
          <Label Text="COLOR Background"
                 TextColor="Gray"/>
          <ImageButton Background="DarkSlateGray"
                       Aspect="Center"
                       CornerRadius="8"
                       WidthRequest="80"
                       HeightRequest="80"
                       Source="{FontImage FontFamily='Ionicons', Glyph='&#xF32B;', Color='DarkOrange', Size='60'}"/>
      </VerticalStackLayout>

  </Grid>

```

</details>

### CODE REVIEW

File: src/Core/src/Platform/Android/ImageButtonExtensions.cs [hunk 1]
```diff
@@ -76,7 +77,9 @@ internal static void UpdateButtonStroke(this ShapeableImageView platformView, IB
 
 		internal static void UpdateButtonBackground(this ShapeableImageView platformView, IImageButton button)
 		{
-			platformView.UpdateMauiRippleDrawableBackground(button,
+			platformView.UpdateMauiRippleDrawableBackground(
+				button.Background ?? new SolidPaint(Colors.Transparent), // transparent to force some background
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Android/ImageButtonExtensions.cs:81]: Should we use the same default color applied to Button?

**Comment by Syed-RI** [comment]
Do you have any before and after video of the effect?

File: src/Core/src/Platform/Android/ImageButtonExtensions.cs (hunk 1 above)
Comment (mattleibow) [reply src/Core/src/Platform/Android/ImageButtonExtensions.cs:81]: Not sure this ever was the case, so it may be a breaking change?

**Comment by mattleibow** [comment]
I added a video for the ripple, a bit hard to see as modern Androids have a very subtle ripple. But, I also opened an issue for a platform specific property: https://github.com/dotnet/maui/issues/22805

File: src/Core/src/Platform/Android/ImageButtonExtensions.cs (hunk 1 above)
Comment (mattleibow) [reply src/Core/src/Platform/Android/ImageButtonExtensions.cs:81]: Let me test OG net8 and see. I am sure I have always seen transparent because this is not a button, it is an image view. I will also test net7.

Comment (mattleibow) [reply src/Core/src/Platform/Android/ImageButtonExtensions.cs:81]: I tested OG 8.0.3 and there is no background. Same with 7.0.101+4.

**Review by jsuarezruiz — APPROVED** [review]
issue-22603

**Comment by MauiUIui** [comment]
This might have just created this bug: #23119
