### PR TITLE
Fix the BackgroundColor to Background update

### LINKED ISSUE #4143: Custom theme ResourceDictionary not working
I've copied code that largly the same as i have in a xamarin.forms app. But it isn't working.

When the app loads, in the `app.xaml.cs` `OnStart` method it triggers and app theme initialiser method. That method checks what theme the app should be set as _(light/ dark or OS)_. Once it knows what it needs to be set to it then set the `Application.Current.Resources` with the right themes ResourceDictionary. But nothing happens - 
image

It should be changing the background colour - 
image

Both light and dark theme has different colours - 
image

### Steps to Reproduce

repo -
[repo.zip](https://github.com/dotnet/maui/files/7872565/repo.zip)
 

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

android 11

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #4335: AppThemeBinding not working (p11/p12)
### Description

See -> https://github.com/microsoft/dotnet-podcasts/issues/36

Basically the app theme doesn't seem to apply the theme across the board.

### Steps to Reproduce

1.) Download .net podcast app and run on any platform and see

### Version with bug

Preview 11

### Last version that worked well

Preview 10

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

Nope

### Relevant log output

_No response_

### LINKED ISSUE #4516: [Android 11] Behavior does not modify properties of attached object when modification occurs in an EventHandler
### Description

I have implemented a behavior which automatically subscribes the attached VisualElement to AppThemeChanged event, and modify its property (BackgroundColor in this case) accordingly. However when the device theme is changed, the BackgroundColor property is not set. The reason why I use such a roundabout way to do AppThemeBinding is because our app is entirely written in C#, and we need to use SetDynamicResource inside Behaviors. 
```cs
public class TestBehavior : Behavior<VisualElement>
{
  private VisualElement? _attachedView;
  
  protected override void OnAttachedTo(VisualElement bindable)
  {
	  base.OnAttachedTo(bindable);
	  if (Application.Current is not null)
	  {
                                _attachedView = bindable;
		  switch (Application.Current.RequestedTheme)
		  {
			  case OSAppTheme.Dark:
				  _attachedView.BackgroundColor = Colors.White;
				  break;
			  default:
				  _attachedView.BackgroundColor = Colors.Black;
				  break;
		  }
  
		  
		  Application.Current.RequestedThemeChanged += OnAppThemeChanged;
  
	  }
  
  }
  
  protected override void OnDetachingFrom(VisualElement bindable)
  {
	  base.OnDetachingFrom(bindable);
	  if (Application.Current is not null)
	  {
		  Application.Current.RequestedThemeChanged -= OnAppThemeChanged;
  
	  }
  }
  
  
  private void OnAppThemeChanged(object? s, AppThemeChangedEventArgs e)
  {
	  Device.BeginInvokeOnMainThread(() =>
	  {
		  if (_attachedView is not null)
		  {
			  switch (e.RequestedTheme)
			  {
				  case OSAppTheme.Dark:
					  _attachedView.BackgroundColor = Colors.White;
					  break;
				  default:
					  _attachedView.BackgroundColor = Colors.Black;
					  break;
			  }
		  }
  
	  });
  }
}
```

### Steps to Reproduce
I have Attached a sample of a Behavior object which would change the BackgroundColor of the attached element based on the current app theme. You can reproduce this bug by creating any visual element, add the Behavior to its list of Behaviors. The visual will not be modified when app theme is changed. 

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

I can use trigger to do something like this, however that has its own issues/bugs, and is more convoluted overall. 

### Relevant log output

_No response_

### LINKED ISSUE #5380: BackgroundColor not changed
### Description

I have created a new MAUI project (preview 14) and I have modified (created) the following three files:

`MainPage.xaml`:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiAppRelativeSource.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}">

    <ScrollView>
        <Grid RowSpacing="25" RowDefinitions="Auto,Auto,Auto,Auto,*"
              Padding="{OnPlatform iOS='30,60,30,30', Default='30'}">

            <Label 
                Text="{Binding IsGreen}"
                Grid.Row="0"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32"
                HorizontalOptions="Center" />

            <Entry Text="" Grid.Row="1">
                <Entry.Triggers>
                    <DataTrigger TargetType="Entry"
                                 Binding="{Binding Path=IsGreen}"
                                 Value="False">
                        <Setter Property="BackgroundColor" Value="Red" />
                    </DataTrigger>
                    <DataTrigger TargetType="Entry"
                                 Binding="{Binding Path=IsGreen}"
                                 Value="True">
                        <Setter Property="BackgroundColor" Value="Green" />
                    </DataTrigger>
                </Entry.Triggers>
            </Entry>

            <Button 
                Text="Click me"
                FontAttributes="Bold"
                Grid.Row="3"
                Command="{Binding ChangeColorCommand}"
                HorizontalOptions="Center" />
        </Grid>
    </ScrollView>
</ContentPage>
```

`MainPageViewModel.cs` (added to the project)

```cs
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace MauiAppRelativeSource.ViewModels;

internal class MainPageViewModel : INotifyPropertyChanged
{
    public bool isGreen { get; set; }

    public bool IsGreen
    {
        get
        {
            return isGreen;
        }
        set
        {
            isGreen = value;
            OnPropertyChanged();
        }
    }

    public Command ChangeColorCommand { get; }

    public MainPageViewModel()
    {
        ChangeColorCommand = new Command(() => {
            IsGreen = !IsGreen;
        });
    }

    public event PropertyChangedEventHandler PropertyChanged;

    protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
    {
        PropertyChangedEventHandler handler = PropertyChanged;
        if (handler != null)
            handler(this, new PropertyChangedEventArgs(propertyName));
    }
}
```

`MainPage.xaml.cs`:

```cs
using MauiAppRelativeSource.ViewModels;

namespace MauiAppRelativeSource;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();

		// Intentionally assigned here. In my app, the view model is obtained using DI.
		this.BindingContext = new MainPageViewModel();
	}
}
```

### Steps to Reproduce

1. Run the attached app: [MauiAppRelativeSource.zip](https://github.com/dotnet/maui/files/8284797/MauiAppRelativeSource.zip)
1. Click the `Click me` button
1. `<Entry>` should be green, it's red

    image

Some sort of https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/relative-bindings has to be added but I tried many options and I failed every single time.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No.

### Relevant log output

_No response_

### LINKED ISSUE #5681: [Bug] BackgroundColor of ContentPage not being updated on AppThemeBinding update
### Description

BackgroundColor of ContentPage does not update on app theme change, while most other colors do.

### Steps to Reproduce

1. Checkout this repo: https://github.com/MyLastWish/-MauiBackgroundColorBug
2. Run project.
3. When clicking the button it will update text color, but not page's backgroundColor.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android API 30, Windows 10 Educational

### Did you find any workaround?

No.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

The reason setting the BackgroundColor of a Page did not update the Background was due to the "inheritance" of the handlers. The PageHandler effectively inherits from ViewHandler, however, we remap some things in Controls and this caused an issue because we used the wrong type.

The VisualElement.RemapForControls assumed that all VisualElements are Views, and this is not true for the case of Page. However, this is true for the case of IView.

### Issues Fixed

- Fixes #5681
- Fixes #4335
- Fixes #4143
- Fixes #4516
- Fixes #5380

### CODE REVIEW

**Review by jsuarezruiz — APPROVED** [review]

**Comment by mattleibow** [comment]
I see @jsuarezruiz  did this, but in another way: https://github.com/dotnet/maui/pull/5706

Not sure if changing to IView is good or bad? @PureWeen ?

File: src/Controls/src/Core/HandlerImpl/VisualElement/VisualElement.cs [hunk 1]
```diff
@@ -6,18 +6,19 @@ namespace Microsoft.Maui.Controls
...
 		/// <include file="../../../../docs/Microsoft.Maui.Controls/VisualElement.xml" path="//Member[@MemberName='ControlsVisualElementMapper']/Docs" />
-		public static IPropertyMapper<IView, IViewHandler> ControlsVisualElementMapper = new PropertyMapper<View, IViewHandler>(Element.ControlsElementMapper)
-		{
-			[nameof(BackgroundColor)] = MapBackgroundColor,
-		};
+		public static IPropertyMapper<IView, IViewHandler> ControlsVisualElementMapper =
+			new PropertyMapper<IView, IViewHandler>(Element.ControlsElementMapper)
+			{
+				[nameof(BackgroundColor)] = MapBackgroundColor,
+			};
```
Comment (mattleibow) [inline src/Controls/src/Core/HandlerImpl/VisualElement/VisualElement.cs:13]: This is the actual fix: `View` -> `IView`

File: src/Core/src/Handlers/ContentView/ContentViewHandler.cs [hunk 2]
```diff
@@ -15,17 +15,19 @@ namespace Microsoft.Maui.Handlers
...
-		};
+			};
 
-		public static CommandMapper<IPicker, IContentViewHandler> CommandMapper = new(ViewCommandMapper)
-		{
-		};
+		public static CommandMapper<IContentView, IContentViewHandler> CommandMapper =
+			new(ViewCommandMapper)
+			{
+			};
```
Comment (mattleibow) [inline src/Core/src/Handlers/ContentView/ContentViewHandler.cs:30]: This was a special find.

Comment (StephaneDelcroix) [reply src/Core/src/Handlers/ContentView/ContentViewHandler.cs:30]: why do you need the braces ?

**Review by StephaneDelcroix — APPROVED** [review]
no tests ?

**Comment by mattleibow** [comment]
Still working on that.

**Comment by rachelkang** [comment]
I changed the Page BackgroundColor to Background in the template styles - should we change that back with this fix? Or should either work fine now?

**Comment by PureWeen** [comment]
@rachelkang I would change it back. Since setting Background makes BackgroundColor unusable it's unfortunately confusing if we're setting Background in our styles and they go to set BackgroundColor

**Review by javiercn — APPROVED** [review]
Blazor related changes look good.

Can't comment on other changes!

File: src/Core/src/Handlers/ContentView/ContentViewHandler.cs [hunk 3]
```diff
@@ -15,17 +15,17 @@ namespace Microsoft.Maui.Handlers
...
+			{
+				[nameof(IContentView.Content)] = MapContent,
 #if TIZEN
-			[nameof(IContentView.Background)] = MapBackground,
+				[nameof(IContentView.Background)] = MapBackground,
 #endif
-		};
+			};
 
-		public static CommandMapper<IPicker, IContentViewHandler> CommandMapper = new(ViewCommandMapper)
```
Comment (mattleibow) [inline src/Core/src/Handlers/ContentView/ContentViewHandler.cs:26]: oops for the IPicker :(

**Comment by pedromcrocha** [comment]
in https://github.dev/dotnet/maui/blob/main/src/Controls/src/Core/Compatibility/Handlers/VisualElementRenderer.cs
around line 175
where it is 
#if IOS
		protected virtual void SetBackgroundColor(Color? color)
#else
		protected virtual void UpdateBackgroundColor()
#endif
		{
			if (Element != null)
				ViewHandler.MapBackground(this, Element);
		}

shouldn't be

#if IOS
		protected virtual void SetBackgroundColor(Color? color)
#else
		protected virtual void UpdateBackgroundColor()
#endif
		{
			if (Element != null)
				**_ViewHandler.MapBackgroundColor(this, Element);_**
		}
