### PR TITLE
[iOS] Fix for Left SwipeView Items Conflict with Shell Menu Swipe Gesture

### LINKED ISSUE #26933: Left SwipeView Items Conflict with Shell Menu Swipe Gesture on iOS
### Description

On iOS devices, when a SwipeView is used and the left swipe gesture is triggered within it, the Shell's native menu swipe gesture (from the left) intercepts the swipe and opens the Shell menu.
Note: While fixing this issue enable the following UITest in HostApp: Issue 9088  

https://github.com/user-attachments/assets/79873e73-be3b-4433-b40e-a150008fd7e6

### Steps to Reproduce

1. Run the Application on IOS [Issue9088Sample.zip](https://github.com/user-attachments/files/18296741/Issue9088Sample.zip)
2. Swipe from the left side of the screen.
3. Instead of executing the left swipe action in the SwipeView, the Shell menu opens. 

Expected Behavior:
Swiping from the left inside the SwipeView should trigger the left swipe item’s action without opening the Shell menu.

Actual Behavior:
Swiping from the left in the SwipeView causes the Shell menu to open, instead of executing the swipe action defined within the SwipeView.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Tamilarasan-Paranthaman**
### Root Cause of the issue 

- When swiping to the left in the SwipeView, the shell flyout gesture intercepts the SwipeView gesture and causes the shell flyout to open.
 
### Description of Change

- I resolved the issue by identifying if the view is a MauiSwipeView. If it is, I restricted the touch interaction in the shell flyout, allowing the SwipeView touch gestures to work as expected.

### Issues Fixed

Fixes #26933

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Screenshot

| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/f3173109-afae-4923-b5d5-f9827c4a770a"> | <video   src="https://github.com/user-attachments/assets/2a257126-224b-4bce-a641-a509e1ab2add"> |

### Reference from Xamarin

https://github.com/xamarin/Xamarin.Forms/blob/2f8f4864a4d289dc89a6228e2ca9d6a49993e365/Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutRenderer.cs#L85

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutRenderer.cs [hunk 1]
```diff
@@ -94,11 +94,14 @@ touch.View is MPVolumeView ||
...
 		{
 			if (view == null)
+			{
 				return false;
+			}
 
-			// TODO MAUI
-			//if (view is SwipeView)
-			//return true;
+			if (view is MauiSwipeView)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutRenderer.cs:101]: In Xamarin.Forms, the SwipeViewRenderer manage this cases, enabling/disabling parent gestures while the SwipeView is capturing the touch events https://github.com/xamarin/Xamarin.Forms/blob/2f8f4864a4d289dc89a6228e2ca9d6a49993e365/Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs#L1508
Could review it, and apply a similar approach with the handler?

**Review by jsuarezruiz — DISMISSED** [review]

File: src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutRenderer.cs (hunk 1 above)
Comment (Tamilarasan-Paranthaman) [reply src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutRenderer.cs:101]: @jsuarezruiz, I have resolved the issue where the Shell flyout gesture intercepts the SwipeView gesture on iOS. However, it seems the provided code reference to Xamarin.Forms on Android.

Upon reviewing the Xamarin.Forms implementation for iOS in the SwipeViewRenderer, I observed the relevant logic:
https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.iOS/Renderers/SwipeViewRenderer.cs#L851

A similar approach has already been included into .NET MAUI within MauiSwipeView.iOS (the platformView of SwipeView on iOS):
https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/iOS/MauiSwipeView.cs#L516
 
The fix I implemented is based on the ShellFlyoutRenderer logic in Xamarin.Forms:
https://github.com/xamarin/Xamarin.Forms/blob/2f8f4864a4d289dc89a6228e2ca9d6a49993e365/Xamarin.Forms.Platform.iOS/Renderers/ShellFlyoutRenderer.cs

However, I noticed that the equivalent logic is currently absent in the ShellFlyoutRenderer implementation for iOS in .NET MAUI.

**Review by PureWeen — APPROVED** [review]
