### PR TITLE
[Windows] Fix for Argument Exception raised when the GetStringSize method of ICanvas called with default font

### LINKED ISSUE #20419: Bug in ICanvas.GetStringSize when called with default font
### Description

System.ArgumentException: Value does not fall in expected range when calling ICanvas.GetStringSize from the Draw method of an IDrawable.

### Steps to Reproduce

1. Create a New MAUI app.
2. To the displayed ContentPage, place a GraphicsView control.
3. Set the drawable to an IDrawable somewhere in your code with an overridden Draw function.
4. In the Draw function, place the following:
`Font font = new();
var stringSize = canvas.GetStringSize("MyString", font, 32);`

This code will produce the error.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

I traced the actual bug to where ICanvasTextFormatMethods.set_FontWeight is called from the CanvasTextFormat constructor is called. The parameterless Font() constructor uses a Weight of 400 and this appears to be the problem. Calling new Font(string.Empty, 100) appears to work as the Weight is a value that works with the constructor for CanvasTextFormat.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SyedAbdulAzeemSF4852**
### Issue Details

- Argument Exception raised when the GetStringSize method of ICanvas called with default font.

### Root Cause

- The Weight property of the FontWeight class, used when creating a CanvasTextFormat object, only accepts values in the range of 1 to 999. However, when the GetStringSize method is called using the default font, its weight is 0. Assigning this value causes an ArgumentException because it falls outside the expected range.

### Description of Change

- Before assigning the font's weight to the Weight property of the FontWeight class while creating a CanvasTextFormat object, clamped the font's Weight value using Math.Clamp to ensure it stays within the valid range of 1 to 999.

- Reference :  [FontWeight Struct](https://learn.microsoft.com/en-us/uwp/api/windows.ui.text.fontweight?view=winrt-22621)

### Validated the behaviour in the following platforms

- [x] Windows
- [x] Android
- [x] iOS
- [x] Mac

### Issues Fixed
Fixes #20419 

### Output
| Before Fix | After Fix |
|----------|----------|
|  |  |

### CODE REVIEW

File: src/Graphics/src/Graphics/Platforms/Windows/PlatformStringSizeService.cs [hunk 1]
```diff
@@ -28,7 +29,8 @@ public SizeF GetStringSize(string value, IFont font, float textSize, HorizontalA
 			{
 				FontFamily = font.Name,
 				FontSize = textSize,
-				FontWeight = new FontWeight { Weight = (ushort)font.Weight },
+				// Ensure font weight stays within the valid range (1–999) to avoid runtime errors
+				FontWeight = new FontWeight { Weight = (ushort)Math.Clamp(font.Weight, 1, 999) },
```
Comment (jsuarezruiz) [inline src/Graphics/src/Graphics/Platforms/Windows/PlatformStringSizeService.cs:33]: We need the same approach in different classes. Can create an extension method and reuse it.

Comment (rmarinho) [reply src/Graphics/src/Graphics/Platforms/Windows/PlatformStringSizeService.cs:33]: should we add a extension method to parse this?

**Review by jsuarezruiz — DISMISSED** [review]

**Review by PureWeen — APPROVED** [review]
