### PR TITLE
[Android] Removing outdated menu items as Android can delete them after switching activities

### LINKED ISSUE #24357: [Android] Toolbar item icon and text disappears when reopening from recent applications.
### Description

Upon returning to foreground, previously drawn ToolbarItems of NavigationPage disappear. Looking at title shifted to the left, buttons are completely removed from layout.
Debugger shows that all ToolbarItems present in IList of NavigationPage

_Similar bug marked as closed, but definetely repros today (https://github.com/dotnet/maui/issues/11552)_

### Steps to Reproduce

1. Add Navigation Page
2. Add ToolbarItems in constructor of ContentPage
3. Use android "back" button to put app into backgound.
4. Return app to foreground

```
public partial class MainPage : ContentPage
{
	
	public MainPage()
	{
		InitializeComponent();

		ToolbarItems.Add(new(null, "bug", () => { CounterBtn.Text = $"Bugt button clicked"; }));
		ToolbarItems.Add(new(null, "contacts", () => { CounterBtn.Text = $"Person button clicked"; }));
	}
}
```

### Link to public reproduction project repository

https://github.com/SergTomcat/MAUI8_BugDemo2

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10-14

### Did you find any workaround?

Override OnAppearing method of every page with toolbar, clear items and readd them.

```
protected override void OnAppearing()
{
	base.OnAppearing();
	
	var tb = ToolbarItems.ToArray();
        ToolbarItems.Clear();
        foreach (var item in tb) 
                ToolbarItems.Add(item);
}
```

It plugs the hole, but require to be included in everypage, not mentioning additional perfomance overhead.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by VitalyKnyazev**
### Description of Change

When updating toolbar items first removing outdated menu items as Android can sometimes delete them after switching activities (releasing resources under memory pressure?).

### Issues Fixed

Fixes #24357

### CODE REVIEW

File: src/Controls/src/Core/Platform/Android/Extensions/ToolbarExtensions.cs [hunk 1]
```diff
@@ -232,9 +232,23 @@ public static void UpdateMenuItems(this AToolbar toolbar,
...
-			var context = mauiContext.Context;
 			var menu = toolbar.Menu;
 
+			// menu items can be deleted by Android after switching activities, removing outdated menu items first
+			if (menu != null)
+			{
+				var clonedPreviousMenuItems = previousMenuItems.ToArray();
+				foreach (var previousMenuItem in clonedPreviousMenuItems)
+				{
+					var item = menu.FindItem(previousMenuItem.ItemId);
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/Extensions/ToolbarExtensions.cs:243]: Can directly: `if (menu.FindItem(previousMenuItem.ItemId) == null)`

File: src/Controls/src/Core/Platform/Android/Extensions/ToolbarExtensions.cs [hunk 2]
```diff
@@ -232,9 +232,23 @@ public static void UpdateMenuItems(this AToolbar toolbar,
 			if (sortedToolbarItems == null || previousMenuItems == null)
 				return;
 
-			var context = mauiContext.Context;
 			var menu = toolbar.Menu;
 
+			// menu items can be deleted by Android after switching activities, removing outdated menu items first
+			if (menu != null)
+			{
+				var clonedPreviousMenuItems = previousMenuItems.ToArray();
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/Extensions/ToolbarExtensions.cs:240]: Can reduce the memory allocation and copying overhead of `ToArray()` iterating backwards through the collection.

`for (int i = previousMenuItems.Count - 1; i >= 0; i--)`

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Could we include a test? Can move App to background etc using Appium using `App.BackgroundApp()`.

File: src/Controls/src/Core/Platform/Android/Extensions/ToolbarExtensions.cs (hunk 2 above)
Comment (VitalyKnyazev) [reply src/Controls/src/Core/Platform/Android/Extensions/ToolbarExtensions.cs]: Hi @jsuarezruiz, thank you for the suggestions, updated PR.
I have never added tests like this and creating test environment will take forever, not sure I can do that.

File: src/Controls/src/Core/Platform/Android/Extensions/ToolbarExtensions.cs [hunk 3]
```diff
@@ -232,9 +232,22 @@ public static void UpdateMenuItems(this AToolbar toolbar,
...
+			// menu items can be deleted by Android after switching activities, removing outdated menu items first
+			if (menu != null)
+			{
+				for (var j = previousMenuItems.Count - 1; j >= 0; j--)
+				{
+					var previousMenuItem = previousMenuItems[j];
+					if (menu.FindItem(previousMenuItem.ItemId) == null)
+					{
+						previousMenuItem.Dispose();
+						previousMenuItems.Remove(previousMenuItem);
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/Extensions/ToolbarExtensions.cs:246]: `previousMenuItems.RemoveAt(j);`

Use `RemoveAt(j)` instead of `Remove(previousMenuItem)`.  Remove() which has to search the collection for the item while RemoveAt(j) directly removes at the index we already know, eliminating the search operation.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Could we include a test here? Can create an UITest based on the issue sample and use the methods https://github.com/dotnet/maui/blob/acd2a942312384638febe821cbf49b10201d0e7f/src/TestUtils/src/UITest.Appium/HelperExtensions.cs#L1446 to move the app to background and then to foreground.

Let me know if can help with something!

**Comment by jsuarezruiz** [comment]
> Could we include a test here? Can create an UITest based on the issue sample and use the methods
> 
> https://github.com/dotnet/maui/blob/acd2a942312384638febe821cbf49b10201d0e7f/src/TestUtils/src/UITest.Appium/HelperExtensions.cs#L1446
> 
> to move the app to background and then to foreground.
> Let me know if can help with something!

@VitalyKnyazev Would you like to include the tests yourself? If you don’t have time, just let me know, I’d be happy to add them for you!

**Comment by VitalyKnyazev** [comment]
Hi @jsuarezruiz, I have tried App.BackgroundApp but still getting the toolbar item via App.WaitForElement(AppiumQuery.ByXPath("//android.widget.Button[@content-desc='ToolbarItem1']")).
It is not always possible to reproduce the issue, I could only reliably do it while debugging my app which is quite heavyweight.

**Review by jsuarezruiz — APPROVED** [review]
