### PR TITLE
[iOS] - Fixed ImageSource.FromFile fails when image in subfolder

### LINKED ISSUE #22887: Microsoft.Maui.Controls.ImageSource.FromFile fails in iOS when image in subfolder
### Description

We have some PNGs that we display via a ViewModel. The property on the ViewModel is an ImageSource

Most of the images live directly under Resources/Images but some are in a subfolder called "signal". All the images have the Build Action of MauiImage

In the ViewModel we load those images into the ImageSource like this:

`this.Image = Microsoft.Maui.Controls.ImageSource.FromFile("signal/red_hexagon1.png");`

In Android this works fine. In iOS it does not work and we see the following error message in the Output window

> [0:] Microsoft.Maui.FileImageSourceService: Warning: Unable to load image file 'Signal/red_hexagon.png'.
> 
> System.InvalidOperationException: Unable to load image file.
>    at Microsoft.Maui.FileImageSourceService.GetImageAsync(IFileImageSource imageSource, Single scale, CancellationToken cancellationToken)

If I move the image into root of "Resources/Images" the image loads fine.

This fails on both the Device (iOS 17.4.1) and Simulator (iPhone 15 iOS 17.4)

It works fine on Android

### Steps to Reproduce

Call Microsoft.Maui.Controls.ImageSource.FromFile on iOS with an Image in a sub folder of Resources/Images

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.4.x

### Did you find any workaround?

Move image to the root.

### Relevant log output

```shell
[0:] Microsoft.Maui.FileImageSourceService: Warning: Unable to load image file 'Signal/red_hexagon.png'.

System.InvalidOperationException: Unable to load image file.
   at Microsoft.Maui.FileImageSourceService.GetImageAsync(IFileImageSource imageSource, Single scale, CancellationToken cancellationToken)
```

### PR DESCRIPTION
**Pull request by NirmalKumarYuvaraj**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Description of Change

This pull request addresses an issue where `ImageSource.FromFile` fails to load images from subfolders on iOS. The changes include adding a new test case and image asset to verify the fix, and updating the image loading logic to ensure images in subfolders are handled correctly.

**iOS Image Loading Fix:**

* Updated `ImageSourceExtensions.GetPlatformImage` to use only the file name (without path or extension) when loading images from the app bundle, improving compatibility with images placed in subfolders.

**Tests and Assets:**

* Added a new image asset `dotnet_bot_red.png` in a subfolder and configured it as a `MauiImage` in the project file to support the new test case.
* Introduced a test page `Issue22887` that attempts to load an image from a subfolder to verify the fix.
* Added a UI test for `Issue22887` (guarded for Windows) to ensure the image loads correctly from a subfolder.

Validated the behaviour in the following platforms

- [x] Android
- [ ] Windows
- [x] iOS
- [x] Mac

### Issues Fixed

Fixes #22887

### Output
| Before| After|
|--|--|
| <video src="https://github.com/user-attachments/assets/7b74d9bf-4dd6-4802-a190-d5731e2b6afb"> | <video src="https://github.com/user-attachments/assets/add28530-23ef-4700-a438-a4d019b69640"> |

### CODE REVIEW

File: src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs [hunk 1]
```diff
@@ -59,8 +59,8 @@ public static partial class ImageSourceExtensions
 
 		internal static UIImage? GetPlatformImage(this IFileImageSource imageSource)
 		{
-			var filename = imageSource.File;
-			return UIImage.FromBundle(filename) ?? UIImage.FromFile(filename);
+			var fileName = Path.GetFileNameWithoutExtension(imageSource.File);
```
Comment (MartyIX) [inline src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs]: Do I understand it right that folders are ignored and the file names must be unique?

Perhaps it's worth a comment explaining it a bit.

Comment (NirmalKumarYuvaraj) [reply src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs]: @MartyIX , I have added the comment. please let me know if you have any concerns.

Comment (MartyIX) [reply src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs]: Thank you. And the other part of the question? I mean what would happen if there were two images of the same name in different folders? Is that forbidden?

Comment (NirmalKumarYuvaraj) [reply src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs]: @MartyIX , It will throw the below error message on compilation. Both Nested scneario and seperate folder scenario.

Error message :
`One or more duplicate file names were detected.  All image output filenames must be unique: dotnet_bot_red (Resources/Images/subfolder/subfolder/dotnet_bot_red.png)",`

Screenshot 2025-08-21 at 7 12 15 PM

File: src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs [hunk 2]
```diff
@@ -59,8 +59,10 @@ public static partial class ImageSourceExtensions
 
 		internal static UIImage? GetPlatformImage(this IFileImageSource imageSource)
 		{
-			var filename = imageSource.File;
-			return UIImage.FromBundle(filename) ?? UIImage.FromFile(filename);
+			// Extract filename without path/extension to handle cases where imageSource.File contains subdirectories.
+			// UIImage.FromBundle() expects just the base filename, while the full path would cause bundle lookup to fail.
+			var fileName = Path.GetFileNameWithoutExtension(imageSource.File);
```
Comment (jsuarezruiz) [inline src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs]: `GetFileNameWithoutExtension` removes the path and extension, while `UIImage.FromBundle` will work, `UIImage.FromFile` will fail. 
Can maintain two variables, one with the extension:

```
var fileName = Path.GetFileName(imageSource.File); // Keep extension
var fileNameWithoutExt = Path.GetFileNameWithoutExtension(imageSource.File);
```

Use bundle first without extension, and then from file.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs (hunk 2 above)
Comment (NirmalKumarYuvaraj) [reply src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs]: @jsuarezruiz , UIImage.FromFile() works fine with GetFileNameWithoutExtension. Please let me know if you have any concerns.

image

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22887.cs [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+	}
+
+	public override string Issue => "Microsoft.Maui.Controls.ImageSource.FromFile fails in iOS when image in subfolder";
+
+
+	[Test]
+	[Category(UITestCategories.Image)]
+	public void ImageShouldLoadFromSubfolder()
+	{
+		App.WaitForElement("ImageView", timeoutMessage: "Image is not rendered in the view");
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22887.cs:22]: Test only checks if image loads, not if it's the correct image. Could add a `VerifyScreenshot` in this case?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22887.cs (hunk 3 above)
Comment (NirmalKumarYuvaraj) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22887.cs:22]: @jsuarezruiz , modified the test case. Please let me know if you have any concerns.

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22887.cs [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+	public Issue22887(TestDevice testDevice) : base(testDevice)
+	{
+	}
+
+	public override string Issue => "Microsoft.Maui.Controls.ImageSource.FromFile fails in iOS when image in subfolder";
+
+
+	[Test]
+	[Category(UITestCategories.Image)]
+	public void ImageShouldLoadFromSubfolder()
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22887.cs:20]: Pending snapshots for Mac and Android.

Image

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22887.cs (hunk 4 above)
Comment (NirmalKumarYuvaraj) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22887.cs:20]: @jsuarezruiz , I have added the pending snapshots. please let me know if you have any concerns.

**Comment by rmarinho** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong> — <a href="https://github.com/dotnet/maui/commit/21795871c02eb57eaa3f9714a20cc276024602aa"><code>2179587</code></a> · <strong>Addressed AI summary concerns</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Added test snapshots</strong> · <a href="https://github.com/dotnet/maui/commit/d9b43ed72d2cb5f036b5dde3a448b5d4844e9371"><code>d9b43ed</code></a></summary>


**Issue:** #22887 - Microsoft.Maui.Controls.ImageSource.FromFile fails in iOS when image in subfolder
**Platforms Affected:** iOS (primary), also validated on Android and Mac
**Files Changed:** 1 fix file, 4 test/asset files, 3 snapshots

### Issue Summary
When using `ImageSource.FromFile("subfolder/image.png")` on iOS with images in a subdirectory of `Resources/Images` (added as `MauiImage`), the image fails to load with:
> `Unable to load image file 'Signal/red_hexagon.png'`

Root cause: `UIImage.FromBundle()` on iOS does not support subdirectory paths — it expects only the base filename. The original code passed the full path (e.g., `subfolder/image.png`) directly, causing bundle lookup to fail.

### Fix Files
| File | Change |
|------|--------|
| `src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs` | `GetPlatformImage`: now strips path/extension before calling `UIImage.FromBundle` |

### Test Files
| File | Change |
|------|--------|
| `TestCases.HostApp/Issues/Issue22887.cs` | New test page: loads image from `subfolder/dotnet_bot_red.png` |
| `TestCases.HostApp/Controls.TestCases.HostApp.csproj` | Added `MauiImage` entry for subfolder image asset |
| `TestCases.HostApp/Resources/Images/subfolder/dotnet_bot_red.png` | New test image asset |
| `TestCases.Shared.Tests/Tests/Issues/Issue22887.cs` | New UI test (guarded `#if TEST_FAILS_ON_WINDOWS`) |
| Snapshots (iOS, Android, Mac) | Screenshot baselines |

### Key Fix
```csharp
// Before:
var filename = imageSource.File;
return UIImage.FromBundle(filename) ?? UIImage.FromFile(filename);

// After:
var fileName = Path.GetFileNameWithoutExtension(imageSource.File);
return UIImage.FromBundle(fileName) ?? UIImage.FromFile(fileName);
```

### Reviewer Disagreements / Concerns
| File:Line | Reviewer | Comment | Status |
|-----------|----------|---------|--------|
| `ImageSourceExtensions.cs:65` | `copilot-pull-request-reviewer` | `UIImage.FromFile()` needs full filename with extension; fallback with no extension will fail. Suggested: `UIImage.FromFile(imageSource.File)` | ⚠️ UNRESOLVED |
| `ImageSourceExtensions.cs:64` | `jsuarezruiz` | Use two variables — one with extension for `FromFile`, one without for `FromBundle` | ⚠️ UNRESOLVED |
| `ImageSourceExtensions.cs:64` | `MartyIX` | What if two images have the same name in different folders? | ✅ RESOLVED (compile error prevents duplicates) |
| `Issue22887.cs:22` | `jsuarezruiz` | Test only checks if image loads, not the correct image; add `VerifyScreenshot()` | ✅ RESOLVED |
| `Issue22887.cs:20` | `jsuarezruiz` | Pending snapshots for Mac and Android | ✅ RESOLVED |

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #31258 | Strip path+extension from filename before `UIImage.FromBundle`, use same stripped name for `UIImage.FromFile` fallback | ⏳ PENDING (Gate) | `ImageSourceExtensions.cs` (+4, -2) | Original PR |


**Issue:** #22887 - Microsoft.Maui.Controls.ImageSource.FromFile fails in iOS when image in subfolder
**PR:** #31258 - [iOS] Fixed ImageSource.FromFile fails when image in subfolder
**Author:** NirmalKumarYuvaraj (Syncfusion partner, community contribution)
**Platforms Affected:** iOS (primary), also validated on Android and Mac
**Files Changed:** 1 fix file, 4 test/asset files, 3 snapshots

### Issue Summary
When using `ImageSource.FromFile("subfolder/image.png")` on iOS with images in a subdirectory of `Resources/Images` (added as `MauiImage`), the image fails to load. Root cause: `UIImage.FromBundle()` on iOS does not support subdirectory paths — it expects only the base filename without path or extension (iOS flattens the folder structure when bundling MauiImage assets).

### Fix Files
| File | Change |
|------|--------|
| `src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs` | `GetPlatformImage`: uses `Path.GetFileNameWithoutExtension` before calling both `UIImage.FromBundle` and `UIImage.FromFile` |

### Test Files
| File | Change |
|------|--------|
| `TestCases.HostApp/Issues/Issue22887.cs` | New test page: loads image from `subfolder/dotnet_bot_red.png` |
| `TestCases.HostApp/Controls.TestCases.HostApp.csproj` | Added `MauiImage` entry for subfolder image asset |
| `TestCases.HostApp/Resources/Images/subfolder/dotnet_bot_red.png` | New test image asset |
| `TestCases.Shared.Tests/Tests/Issues/Issue22887.cs` | New UI test (`ImageShouldLoadFromSubfolder`), guarded `#if TEST_FAILS_ON_WINDOWS` |
| Snapshots (iOS, Android, Mac) | Screenshot baselines added |

### Key Code Change
```csharp
// Before:
var filename = imageSource.File;
return UIImage.FromBundle(filename) ?? UIImage.FromFile(filename);

// After:
// Extract filename without path/extension to handle cases where imageSource.File contains subdirectories.
// UIImage.FromBundle() expects just the base filename, while the full path would cause bundle lookup to fail.
var fileName = Path.GetFileNameWithoutExtension(imageSource.File);
return UIImage.FromBundle(fileName) ?? UIImage.FromFile(fileName);
```

### Reviewer Concerns
| File:Line | Reviewer | Comment | Status |
|-----------|----------|---------|--------|
| `ImageSourceExtensions.cs:65` | `copilot-pull-request-reviewer` | `UIImage.FromFile()` needs full filename with extension; fallback with no extension will fail. Suggested: `UIImage.FromFile(imageSource.File)` | ⚠️ DISPUTED by author |
| `ImageSourceExtensions.cs:64` | `jsuarezruiz` | Use two variables — one with extension for `FromFile`, one without for `FromBundle` | ⚠️ DISPUTED by author |
| `ImageSourceExtensions.cs:64` | `MartyIX` | What if two images have the same name in different folders? | ✅ RESOLVED (compile error prevents duplicates) |
| `Issue22887.cs:22` | `jsuarezruiz` | Add `VerifyScreenshot()` | ✅ RESOLVED |

### Prior Agent Review
A prior agent review exists. Gate PASSED (tests fail without fix, pass with fix on iOS). Try-Fix was blocked by API rate limits (incomplete). Recommendation was REQUEST CHANGES due to UIImage.FromFile fallback issue.

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #31258 | Strip path+extension from filename before `UIImage.FromBundle`, use same stripped name for `UIImage.FromFile` fallback | ⏳ PENDING (Gate) | `ImageSourceExtensions.cs` (+4, -2) | Original PR — UIImage.FromFile fallback concern unresolved |

---

**Issue:** #22887 - Microsoft.Maui.Controls.ImageSource.FromFile fails in iOS when image in subfolder
**PR:** #31258 - [iOS] Fixed ImageSource.FromFile fails when image in subfolder
**Author:** NirmalKumarYuvaraj (Syncfusion partner, community contribution)
**Platforms Affected:** iOS (primary), also validated on Android and Mac; Windows excluded
**Files Changed:** 1 fix file, 4 test/asset files, 3 snapshot baselines

### Issue Summary

When calling `ImageSource.FromFile("subfolder/image.png")` on iOS with images stored in a subdirectory of `Resources/Images` (configured as `MauiImage`), the image fails to load with:
```
Microsoft.Maui.FileImageSourceService: Warning: Unable to load image file 'Signal/red_hexagon.png'.
System.InvalidOperationException: Unable to load image file.
```

Root cause: iOS flattens MauiImage assets into the app bundle root. `UIImage.FromBundle()` therefore requires just the base filename without subdirectory prefix or extension. Passing the full relative path (e.g., `"subfolder/image.png"`) causes bundle lookup to fail.

**Key behavioral note:** Duplicate filenames across folders are prevented at compile-time with a build error, so stripping the path is safe.

### Current Fix (Updated)

```csharp
// Before:
var filename = imageSource.File;
return UIImage.FromBundle(filename) ?? UIImage.FromFile(filename);

// After:
var file = imageSource.File;
// On iOS/MacCatalyst, MauiImage assets are flattened into the app bundle root.
// UIImage.FromBundle() therefore requires just the base filename without path or extension.
var bundleName = Path.GetFileNameWithoutExtension(file);
return UIImage.FromBundle(bundleName) ?? UIImage.FromFile(file);
```

**Important:** The `UIImage.FromFile()` fallback uses `file` (original path with extension), addressing the prior reviewer concern about the extension being stripped from `FromFile`.

### Files Changed

| File | Type | Change |
|------|------|--------|
| `src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs` | Fix | `GetPlatformImage`: use `bundleName` (no path/ext) for `FromBundle`, original `file` for `FromFile` fallback |
| `TestCases.HostApp/Issues/Issue22887.cs` | Test | New test page loading image from `subfolder/dotnet_bot_red.png` |
| `TestCases.HostApp/Controls.TestCases.HostApp.csproj` | Test | Added `MauiImage` entry for subfolder image |
| `TestCases.HostApp/Resources/Images/subfolder/dotnet_bot_red.png` | Asset | New test image |
| `TestCases.Shared.Tests/Tests/Issues/Issue22887.cs` | Test | UI test `ImageShouldLoadFromSubfolder` with `VerifyScreenshot()`, guarded `#if TEST_FAILS_ON_WINDOWS` |
| Snapshots (iOS, Android, Mac) | Baseline | Screenshot baselines added |

### Reviewer Concerns

| File:Line | Reviewer | Comment | Status |
|-----------|----------|---------|--------|
| `ImageSourceExtensions.cs:65` | `copilot-pull-request-reviewer` | `UIImage.FromFile()` needs full filename with extension | ✅ ADDRESSED — current code uses `UIImage.FromFile(file)` with original path |
| `ImageSourceExtensions.cs:64` | `jsuarezruiz` | Use two variables — one with ext for `FromFile`, one without for `FromBundle` | ✅ ADDRESSED — current code uses `bundleName` for bundle, `file` for fallback |
| `ImageSourceExtensions.cs:64` | `MartyIX` | What if two images have the same name in different folders? | ✅ RESOLVED — build error prevents duplicates |
| `Issue22887.cs` | `jsuarezruiz` | Add `VerifyScreenshot()` | ✅ RESOLVED |
| `Issue22887.cs` | `jsuarezruiz` | Add Mac/Android snapshots | ✅ RESOLVED |

### Prior Agent Review

A prior agent review exists (in PR summary comment). Key findings:
- Gate ✅ PASSED on iOS (tests fail without fix, pass with fix)
- Try-Fix was **incomplete** (blocked by API rate limits)
- Recommendation was REQUEST CHANGES due to UIImage.FromFile fallback stripping extension

**Note:** The author appears to have addressed the UIImage.FromFile fallback concern since the prior review. The current code uses `UIImage.FromFile(file)` (original path) rather than `UIImage.FromFile(fileName)` (stripped). This is a meaningful improvement.

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #31258 | Use `Path.GetFileNameWithoutExtension(file)` for `UIImage.FromBundle`, use original `file` for `UIImage.FromFile` fallback | ⏳ PENDING (Gate) | `ImageSourceExtensions.cs` (+6/-2) | Addresses reviewer concerns about fallback extension |

Result: ✅ COMPLETE

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Added test snapshots</strong> · <a href="https://github.com/dotnet/maui/commit/d9b43ed72d2cb5f036b5dde3a448b5d4844e9371"><code>d9b43ed</code></a></summary>


**Result:** ✅ PASSED
**Platform:** iOS
**Mode:** Full Verification

- Tests FAIL without fix ✅ (correctly catches the bug)
- Tests PASS with fix ✅ (fix resolves the issue)

**Test:** `ImageShouldLoadFromSubfolder`
**Execution time:** ~16.68s per run
**Device:** iOS Simulator


### Gate Result: ✅ PASSED

**Platform:** iOS
**Mode:** Full Verification

- Tests FAIL without fix: ✅ (correctly catches the bug)
- Tests PASS with fix: ✅ (fix resolves the issue)

**Test:** `ImageShouldLoadFromSubfolder` (Issue22887)
**Device:** iOS Simulator (iPhone 11 Pro)
**Fix File:** `src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs`

---

### Gate Result: ✅ PASSED

**Platform:** ios
**Mode:** Full Verification

- Tests FAIL without fix: ✅ — `ImageShouldLoadFromSubfolder` failed (image not rendered, assertion error at Issue22887.cs:22)
- Tests PASS with fix: ✅ — `ImageShouldLoadFromSubfolder` passed

**Test:** `ImageShouldLoadFromSubfolder` (Issue22887)
**Fix File:** `src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs`

The test correctly catches the bug: without the fix, `UIImage.FromBundle("subfolder/dotnet_bot_red")` fails because iOS bundle lookup doesn't support subdirectory paths. With the fix, `UIImage.FromBundle("dotnet_bot_red")` succeeds because the path is stripped.

Result: ✅ PASSED

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Added test snapshots</strong> · <a href="https://github.com/dotnet/maui/commit/d9b43ed72d2cb5f036b5dde3a448b5d4844e9371"><code>d9b43ed</code></a></summary>


**Result:** ✅ PASSED
**Platform:** iOS
**Mode:** Full Verification

- Tests FAIL without fix ✅ (correctly catches the bug)
- Tests PASS with fix ✅ (fix resolves the issue)

**Test:** `ImageShouldLoadFromSubfolder`
**Execution time:** ~16.68s per run
**Device:** iOS Simulator


### Gate Result: ✅ PASSED

**Platform:** iOS
**Mode:** Full Verification

- Tests FAIL without fix: ✅ (correctly catches the bug)
- Tests PASS with fix: ✅ (fix resolves the issue)

**Test:** `ImageShouldLoadFromSubfolder` (Issue22887)
**Device:** iOS Simulator (iPhone 11 Pro)
**Fix File:** `src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs`

---

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| 1 | try-fix (claude-opus-4.6-1m) | Progressive fallback: try full path with  first, then strip directory via  (keeps extension) if separator present |  PASS | `ImageSourceExtensions.cs` (+17/-2) | More defensive; tries original path first |
| 2 | try-fix (claude-sonnet-4.6) | NSBundle PathForResource:  +  |  PASS | `ImageSourceExtensions.cs` (+15/-2) | Uses iOS native API; most semantically explicit |
| 3 | try-fix (gpt-5.3-codex) | Service-level fallback in : when path contains /, split and retry with base filename |  PASS | `FileImageSourceService.iOS.cs` | Different fix  service layer |location 
| 4 | try-fix (gemini-3-pro-preview) | Safe trailing fallback: try original path first, then if not rooted and contains separator, retry  |  PASS | `ImageSourceExtensions.cs` (+6) |  preserves all existing behavior, targeted fallback only |Safest 
| PR | PR #31258 |  for , original  for  fallback |  PASS (Gate) | `ImageSourceExtensions.cs` (+6/-2) | Simplest; directly addresses root cause; reviewer concerns addressed |

### Cross-Pollination
| Model | Round | New Ideas? | Details |
|-------|-------|------------|---------|
| claude-opus-4.6-1m | 2 | No | NO NEW IDEAS |
| claude-sonnet-4.6 | 2 | Yes | MSBuild build-time resource  out of scope; compile-time error already prevents ambiguity |manifest 
| gpt-5.3-codex | 2 | Yes | NSBundle.PathsForResources enumeration then  variation of Attempt 2, not substantially different |filter 

**Exhausted:** Yes (all 4 models run; new ideas are minor variations or out-of-scope)

### Fix Selection Analysis
| Criterion | PR Fix | Attempt 1 | Attempt 4 (Gemini) |
|-----------|--------|-----------|-------------------|
| Simplicity Fewest lines (+6/- Most verbose (+17/-2 Minimal (+6) |) | 2) |  | 
| Backward compatibility  uses original path |  |  Tries original first  tries original before fallback |Best  | 
| Root cause addressed Directly strips subfolder prefix Handles it Handles it | |  |  | 
| Code clarity Clean with comment | Verbose Clear | |  | 
| Reviewer concerns met Both Copilot + jsuarezruiz | N/A | N/A | | 

**Selected Fix:** PR's  simplest correct solution that directly addresses the root cause. The author has already incorporated reviewer feedback (using original `file` for `UIImage.FromFile` fallback). All 4 independent try-fix attempts confirm the approach is correct. The Gemini approach is slightly safer for edge cases involving non-MauiImage bundled resources, but the PR fix is cleaner overall.fix

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

<details>
<summary>📝 <strong>Review Session</strong> — <strong>Added test snapshots</strong> · <a href="https://github.com/dotnet/maui/commit/d9b43ed72d2cb5f036b5dde3a448b5d4844e9371"><code>d9b43ed</code></a></summary>


## ⚠️ Final Recommendation: REQUEST CHANGES

### Summary
PR #31258 fixes `ImageSource.FromFile` failing on iOS when the image file lives in a subfolder of `Resources/Images`. The core fix is correct — `UIImage.FromBundle()` on iOS does not support subdirectory paths in filenames, so stripping the path+extension resolves the bundle lookup failure. Tests pass with the fix applied and fail without it (verified on iOS simulator).

However, there is a **critical correctness issue** with the `UIImage.FromFile()` fallback that was flagged by two reviewers but not properly addressed.

### Root Cause
iOS bundles all `MauiImage` assets as flat files in the app bundle (subdirectory structure is discarded). `UIImage.FromBundle("subfolder/dotnet_bot_red.png")` fails because the bundle doesn't know about the path prefix. Stripping to just the base name (`"dotnet_bot_red"`) makes the lookup succeed.

### Fix Quality
The fix correctly addresses the `UIImage.FromBundle()` call. However, the `UIImage.FromFile()` fallback now also uses the stripped filename (no extension, no path), which breaks the fallback for raw file images (images not added as `MauiImage` assets):

```csharp
// Current (broken fallback):
var fileName = Path.GetFileNameWithoutExtension(imageSource.File);
return UIImage.FromBundle(fileName) ?? UIImage.FromFile(fileName); // UIImage.FromFile("image") - fails

// Correct fix:
var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(imageSource.File);
return UIImage.FromBundle(fileNameWithoutExtension) ?? UIImage.FromFile(imageSource.File); // UIImage.FromFile("subfolder/image.png") - works
```

This was flagged by `copilot-pull-request-reviewer` and `jsuarezruiz` but dismissed by the author without addressing the core concern. The test only validates MauiImage bundle assets, not the `UIImage.FromFile` fallback path.

### Required Changes
1. **Fix `UIImage.FromFile` fallback**: Use `imageSource.File` (full path with extension) instead of `fileName` (stripped name)
2. **Update comment**: Clarify that only `UIImage.FromBundle` needs the stripped name
3. **Minor**: Add newline at end of both `Issue22887.cs` files

### Title Suggestion
`[iOS] Fix ImageSource.FromFile loading images from subfolders` (remove dash, use imperative tense)

### Platform Notes
- Fix is iOS/MacCatalyst only (correct — Android doesn't have this bundle lookup issue)
- Tests cover iOS, Android, Mac ✅
- Windows guarded with `#if TEST_FAILS_ON_WINDOWS` (links to separate issue #31256) ✅

### Gate Result
✅ Tests FAIL without fix, PASS with fix (iOS simulator, full verification)

### Try-Fix
⚠️ Skipped — API rate limit prevented alternative exploration. PR's fix validated by Gate only.


Final Recommendation: REQUEST CHANGES## 

### Phase Status
| Phase | Status | Notes |
|---|---|---|
| Pre-Flight COMPLETE | Issue #22887, 1 fix file, 4 test/asset files, 3 snapshots | | 
| Gate PASSED | iOS  tests FAIL without fix, PASS with fix |simulator  | 
| Try-Fix COMPLETE | 6 attempts (all PASS), cross-pollination exhausted (3 rounds) |  | 
| Report COMPLETE | | | 

### Summary

PR #31258 fixes `ImageSource.FromFile("subfolder/image.png")` failing on iOS when images are in subdirectories of `Resources/Images`. The root cause is correctly identified: iOS `UIImage.FromBundle()` does not support subdirectory  MauiImage flattens all assets into the app bundle root. The fix direction is correct.paths 

However, **the `UIImage.FromFile()` fallback is broken** in the PR's current implementation, and a better alternative was found via try-fix that addresses the exact concern raised (but dismissed) by two code reviewers.

### Root Cause

iOS `UIImage.FromBundle("subfolder/dotnet_bot_red.png")` fails because MauiImage flattens subdirectory images into the app bundle root. The bundle contains `dotnet_bot_red.png`, not `subfolder/dotnet_bot_red.png`. Stripping the path prefix (and optionally extension) before passing to `FromBundle` resolves the lookup.

### Fix  PR's Current ImplementationQuality 

```csharp
// PR's current fix (PROBLEMATIC):
var fileName = Path.GetFileNameWithoutExtension(imageSource.File);
return UIImage.FromBundle(fileName) ?? UIImage.FromFile(fileName);
//                                              ^^^^^^^^
//                                              UIImage.FromFile("dotnet_bot_ no extension!red") 
//                                              This will fail for any physical file path
```

**Issue:** `UIImage.FromBundle()` correctly uses the stripped name (Apple  asset catalog names have no extension). BUT `UIImage.FromFile()` is a filesystem API that requires a complete path with extension. Passing a stripped filename (`"dotnet_bot_red"` instead of `"subfolder/dotnet_bot_red.png"`) means the fallback will silently fail for:convention 
- Images downloaded to app sandbox
- Images in app documents folder  
- Any image that isn't a MauiImage bundle asset

This was flagged by **two reviewers** (`copilot-pull-request-reviewer` and `jsuarezruiz`) but the author provided a screenshot showing their specific test worked and dismissed the concern. The test only exercises the `UIImage.FromBundle` path (because MauiImage assets ARE in the bundle), so the broken `UIImage.FromFile` fallback is not caught.

### Better Fix (Candidate # try-fix)1 

```csharp
// Correct fix (Candidate #1):
var file = imageSource.File;
// FromBundle uses the asset catalog which only needs the base filename (no path or extension).
// FromFile uses the filesystem and needs the original path with extension.
var bundleName = Path.GetFileNameWithoutExtension(file);
return UIImage.FromBundle(bundleName) ?? UIImage.FromFile(file);
```

This is exactly what both reviewers suggested. It:
-  Fixes the `FromBundle` lookup (strip path+extension for asset catalog)
-  Preserves the correct `FromFile` fallback (full original path with extension)
-  Is minimal (same structure as the PR, just correct for `FromFile`)
-  Tests pass with this fix on iOS

### Required Changes

**In `src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs`:**
```diff
-       var fileName = Path.GetFileNameWithoutExtension(imageSource.File);
-       return UIImage.FromBundle(fileName) ?? UIImage.FromFile(fileName);
+       var file = imageSource.File;
+       // FromBundle uses the asset catalog which only needs the base filename (no path or extension).
+       // FromFile uses the filesystem and needs the original path with extension.
+       var bundleName = Path.GetFileNameWithoutExtension(file);
+       return UIImage.FromBundle(bundleName) ?? UIImage.FromFile(file);
```

### Gate Result
 Tests FAIL without fix (confirms bug repro), PASS with fix (confirms fix  iOS simulatorworks) 

### Try-Fix Summary
6 independent alternatives explored (all PASS). Cross-pollination exhausted in 3 rounds. Selected fix: Candidate #1 (simplest, most semantically correct, directly matches reviewer feedback). 

Selected Fix: Candidate #1 (try-fix)

### Other Notes
- The test () uses  
- Windows is guarded  with reference to issue #31256 
- Image name uniqueness across subfolders is enforced at compile time (MartyIX's concern resolved)

---

## ✅ Final Recommendation: APPROVE

### Phase Status
| Phase | Status | Notes |
|---|---|---|
| Pre-Flight | ✅ COMPLETE | Issue #22887, iOS ImageSource.FromFile subfolder failure |
| Gate | ✅ PASSED | iOS — tests fail without fix, pass with fix |
| Try-Fix | ✅ COMPLETE | 4 attempts, all 4 passing; PR fix selected |
| Report | ✅ COMPLETE | |

### Summary

PR #31258 fixes a real iOS bug where `ImageSource.FromFile("subfolder/image.png")` fails to load images stored in subdirectories of `Resources/Images`. The fix is correct, well-tested, and the author has already addressed all prior reviewer concerns.

**Key improvement since prior agent review:** The prior review flagged that `UIImage.FromFile()` was incorrectly using `Path.GetFileNameWithoutExtension` (stripping the extension). The author has since updated the code to use the original `file` path for `UIImage.FromFile()`, while still using the stripped `bundleName` for `UIImage.FromBundle()`. This directly addresses both the Copilot reviewer suggestion and jsuarezruiz's requested changes.

### Root Cause

iOS flattens MauiImage assets into the app bundle root (no subdirectory structure is preserved). `UIImage.FromBundle("subfolder/image")` fails because the bundle lookup doesn't recognize the directory prefix. The fix strips the path (and extension) before calling `FromBundle`, while preserving the original path for the `FromFile` fallback (used for images not in the asset catalog).

### Fix Quality

**Current fix (post-reviewer-feedback update):**
```csharp
var file = imageSource.File;
// On iOS/MacCatalyst, MauiImage assets are flattened into the app bundle root.
// UIImage.FromBundle() therefore requires just the base filename without path or extension.
var bundleName = Path.GetFileNameWithoutExtension(file);
return UIImage.FromBundle(bundleName) ?? UIImage.FromFile(file);
```

✅ **Correct** — `UIImage.FromBundle(bundleName)` uses stripped name for asset catalog lookup  
✅ **Correct** — `UIImage.FromFile(file)` uses original path for filesystem fallback  
✅ **Simple** — minimal 6-line addition with clear comment  
✅ **Safe** — duplicate filenames prevented at compile time (build error)  
✅ **Well-tested** — UI test with `VerifyScreenshot()` and snapshots for iOS/Android/Mac  

### Try-Fix Comparison

All 4 independent approaches (claude-opus, claude-sonnet, gpt-codex, gemini) confirmed the core fix is correct. None found a simpler or more correct solution than the PR's approach. The PR fix was selected as the best candidate.

### Remaining Concerns

⚠️ **`jsuarezruiz` still has active CHANGES_REQUESTED** — however, the code changes they requested have been incorporated:
- `UIImage.FromBundle` now uses `bundleName` (no path/ext)
- `UIImage.FromFile` now uses `file` (original path with extension)
- `VerifyScreenshot()` added to test
- Snapshots for Android and Mac added

The reviewer may not have re-reviewed after the author's updates. This is a human decision on re-approval.

⚠️ **`kubaflo` CHANGES_REQUESTED** "apply AI suggestions" — the Copilot suggestion to use `UIImage.FromFile(imageSource.File)` has been applied (the current code uses `UIImage.FromFile(file)` which is equivalent).

The code changes themselves are correct and all reviewer concerns have been technically addressed.

Result: ✅ APPROVE
Selected Fix: PR

</details>

---

</details>




<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

# PR #31258 Finalization Review

**PR:** [#31258 – [iOS] - Fixed ImageSource.FromFile fails when image in subfolder](https://github.com/dotnet/maui/pull/31258)  
**Author:** @NirmalKumarYuvaraj (Syncfusion community)  
**Branch:** `fix-22887` → `main`  
**Files changed:** 8 (+66 / -2)  
**Fixes:** [#22887](https://github.com/dotnet/maui/issues/22887)

---

## Phase 1: Title & Description Review

### 🟡 Title: Needs Minor Update

**Current:** `[iOS] - Fixed ImageSource.FromFile fails when image in subfolder`

**Issues:**
- The dash after `[iOS]` is not conventional in this repo (e.g., `[iOS] Fix ...` not `[iOS] - Fix ...`)
- "Fixed" should be the imperative "Fix" (commit message convention)
- The fix also applies to **MacCatalyst** (the code comment explicitly says "iOS/MacCatalyst") – title only says `[iOS]`

**Recommended:**
```
[iOS/MacCatalyst] Fix ImageSource.FromFile failing when image is in subfolder
```

---

### ✅ Description: Good – Keep With NOTE Block

The existing description is clear and accurate. It covers the root cause, what changed, test assets added, and which platforms were tested.

**Required elements check:**

| Element | Status |
|---------|--------|
| NOTE block at top | ✅ Present |
| Description of Change | ✅ Present and accurate |
| Issues Fixed (`Fixes #22887`) | ✅ Present |
| Platforms tested matrix | ✅ Present (Android ✅, iOS ✅, Mac ✅, Windows ❌ with linked tracking issue) |

**No description rewrite needed.** The description matches the implementation accurately.

---

## Phase 2: Code Review

### Core Fix (`src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs`)

```csharp
// Before:
var filename = imageSource.File;
return UIImage.FromBundle(filename) ?? UIImage.FromFile(filename);

// After:
var file = imageSource.File;
// On iOS/MacCatalyst, MauiImage assets are flattened into the app bundle root.
// UIImage.FromBundle() therefore requires just the base filename without path or extension.
var bundleName = Path.GetFileNameWithoutExtension(file);
return UIImage.FromBundle(bundleName) ?? UIImage.FromFile(file);
```

**Assessment:** The fix is correct. On iOS/MacCatalyst, the `MauiImage` build task flattens all images (regardless of source subfolder) into the root of the app bundle. `UIImage.FromBundle()` therefore cannot find them using a path like `"subfolder/image.png"` — it needs just `"image"`. The fallback to `UIImage.FromFile(file)` is preserved for actual filesystem paths (e.g., downloaded images or documents directory paths), correctly using the full original path.

---

### 🔴 Critical Issues

*None.*

---

### 🟡 Suggestions

**1. `[Issue]` attribute missing `PlatformAffected` in HostApp page**

In `src/Controls/tests/TestCases.HostApp/Issues/Issue22887.cs`:
```csharp
// Current (3 args):
[Issue(IssueTracker.Github, 22887, "Microsoft.Maui.Controls.ImageSource.FromFile fails in iOS when image in subfolder")]

// Recommended (4 args, consistent with other issue pages):
[Issue(IssueTracker.Github, 22887, "Microsoft.Maui.Controls.ImageSource.FromFile fails in iOS when image in subfolder", PlatformAffected.iOS)]
```
Most `[Issue]`-attributed HostApp pages include the `PlatformAffected` fourth argument to indicate the affected platform(s).

**2. Title contains MacCatalyst-affecting fix under an iOS-only label**

The code comment in the fix explicitly reads:  
`// On iOS/MacCatalyst, MauiImage assets are flattened into the app bundle root.`  
The snapshots include a `mac/` (MacCatalyst) snapshot as well. The PR title should reflect this:  
`[iOS/MacCatalyst] Fix ImageSource.FromFile failing when image is in subfolder`

**3. Edge case: filename collision across subfolders**

`Path.GetFileNameWithoutExtension` strips the subfolder path. This means if an app has both `subfolder1/icon.png` and `subfolder2/icon.png`, both would resolve to `"icon"` in `UIImage.FromBundle`. However, this is an inherent limitation of iOS's flat bundle asset model (MauiImage already flattens at build time), not a regression introduced by this fix. Worth documenting as a known limitation.

---

### ✅ Looks Good

- **Fix logic is sound:** Using `Path.GetFileNameWithoutExtension` correctly strips both the directory path and the extension — both are needed since `UIImage.FromBundle` in a flat bundle requires just the asset name.
- **Fallback is preserved correctly:** `UIImage.FromFile(file)` still uses the full original path, which is correct for actual filesystem image access (e.g., cached downloads, app container).
- **Fix is well-commented:** The added comment explains the iOS/MacCatalyst bundle flattening behavior, which is non-obvious.
- **Test coverage is good:** UI test with snapshot images for Android, iOS, and Mac are included. The test page uses `AutomationId` properly.
- **Windows exclusion is properly justified:** `#if TEST_FAILS_ON_WINDOWS` with a link to the tracking issue ([#31256](https://github.com/dotnet/maui/issues/31256)) is the correct pattern.
- **No regression risk for existing images:** Images at the root level also get `Path.GetFileNameWithoutExtension` applied (e.g., `"image.png"` → `"image"`), and `UIImage.FromBundle("image")` works just as well as `UIImage.FromBundle("image.png")`.
- **Code style:** The rename of `filename` → `file` (for the raw value) and introduction of `bundleName` makes the intent clear.

---

## Summary

| Area | Status | Notes |
|------|--------|-------|
| Title | 🟡 Update recommended | Remove dash, use imperative, add MacCatalyst |
| Description | ✅ Good | Keep as-is; NOTE block present |
| Core fix | ✅ Correct | Proper use of `Path.GetFileNameWithoutExtension` + fallback |
| Test implementation | ✅ Good | HostApp page + UI test with snapshots |
| `[Issue]` attribute | 🟡 Minor | Missing `PlatformAffected` 4th argument |
| Platform coverage | ✅ Good | Android, iOS, Mac tested; Windows tracked separately |
| Breaking changes | ✅ None | Behavior change is strictly additive fix; root-level images unaffected |

**Overall verdict: Ready for merge with minor title cleanup.**

</details>

File: src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs [hunk 5]
```diff
@@ -59,8 +59,10 @@ public static partial class ImageSourceExtensions
...
+			return UIImage.FromBundle(fileName) ?? UIImage.FromFile(fileName);
```
[the remark this answers is not in the document]
Comment (NirmalKumarYuvaraj) [reply src/Core/src/ImageSources/iOS/ImageSourceExtensions.cs]: Invalid suggestion. Check https://github.com/dotnet/maui/pull/31258#discussion_r2299936711

**Review by kubaflo — CHANGES_REQUESTED** [review]
Hi! Could you please apply the AI's suggestions?

**Comment by NirmalKumarYuvaraj** [comment]
@kubaflo , Addressed AI review summary concerns. Please let me know if you have any concerns

**Review by kubaflo — APPROVED** [review]
