### PR TITLE
Fix Android FormattedText and related platforms

### LINKED ISSUE #6801: Label sometimes displays hugely wrong font size and spacing
### Description

As shown in the attached repro sample, "theLabel.FormattedText" is set twice; once after init and then again after 2 seconds.

Even though the Label font size settings is not changed and even though the same FormattedText is used, after 2 seconds the label text changes significantly when it should not.  This is a regression (XF did not have this issue) and manifests in many different ways.  The repro just shows one such example.

[layoutbug8.zip](https://github.com/dotnet/maui/files/8618486/layoutbug8.zip)

### Steps to Reproduce

1. Compile and run the sample under Android 11
2. notice the label layout/size change completely after 2 seconds - even though nothing should change.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

no, and similar strange things happen using different layouts.

### Relevant log output

_No response_

### LINKED ISSUE #7220: Android FormattedText and LineHeights are not correct
### Description

The calculation of the line heights are wrong because they capture the initial state of the `TextView.Paint` - often bfore the text is sized. This result in the line height be calculated from the small font size, and then not updated once the font size is updated.

I found this while working on #6801

### Steps to Reproduce

```xaml
<Label x:Name="theLabel" VerticalOptions="Center" HorizontalOptions="FillAndExpand"
        BackgroundColor="Red"
        LineHeight="1" FontSize="35" />
```

```cs
var formattedText = new FormattedString();
formattedText.Spans.Add(new Span { Text = "test1" });
formattedText.Spans.Add(new Span { Text = "\n" });
formattedText.Spans.Add(new Span { Text = "test2" });
theLabel.FormattedText = formattedText;
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

 - #6801  - Initialize the span font size to `NaN`  
   This initial value of `NaN` (or could be 0) indicates to the layout engine that the size must come from the Label.  
   If we return a value in `IFontElement.FontSizeDefaultValueCreator()`, then there is no way of knowing that the size was not actually set since this marks the `BindableProperty` as "set". The reason it works after an update is because on the second time around, the span is not yet attached to the view (see #5587) and as a result there is no maui context and the value falls back to `0` which triggers the use of the label's font size.  
   If the size is `NaN`, it falls back to the "default font size" which is not really "default" but actually "fallback" - the font size of the label.
 - #7220 - Correctly apply span values to spans  
   The previous implementation captured the `TextView.Paint` and used that as the base line height, but like the previous issue, the paint is before any Label font sizes are set.  
   We never actually want to use this as if the line height of the label is different to the label of the span (span's font size is larger), then the span's line height is ignored.

### Issues Fixed

 - Fixes #6801
 - Fixes #7220

### Pictures!

| | Initial | Update | 
| -: | :-: | :-: |
| Before | image | image |
| #6801 | image | image |
| #7220 | image | image |

### CODE REVIEW

File: src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs [hunk 1]
```diff
@@ -53,46 +71,43 @@ public static SpannableString ToSpannableString(this FormattedString formattedSt
...
-
+					spannable.SetSpan(new FontSpan(font, fontManager, context), start, end, SpanTypes.InclusiveInclusive);
+
+				// TextDecorations
+				var textDecorations = span.IsSet(Span.TextDecorationsProperty)
+					? span.TextDecorations
+					: defaultTextDecorations;
+				if (textDecorations.HasFlag(TextDecorations.Strikethrough))
+					spannable.SetSpan(new StrikethroughSpan(), start, end, SpanTypes.InclusiveInclusive);
+				if (textDecorations.HasFlag(TextDecorations.Strikethrough))
```
Comment (campersau) [inline src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs:107]:
```suggestion
				if (textDecorations.HasFlag(TextDecorations.Underline))
```

Comment (mattleibow) [reply src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs:107]: Oops, thanks!

File: src/Controls/src/Core/Span.cs [hunk 2]
```diff
@@ -159,7 +159,7 @@ void IFontElement.OnFontSizeChanged(double oldValue, double newValue)
 		}
 
 		double IFontElement.FontSizeDefaultValueCreator() =>
-			this.GetDefaultFontSize();
+			double.NaN;
```
Comment (mattleibow) [inline src/Controls/src/Core/Span.cs:162]: This is the only "breaking" change, but anyone using this value without it being set by the user is getting a wrong value. I could use `0`?

**Review by Redth — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]

File: src/Controls/src/Core/Span.cs (hunk 2 above)
Comment (mattleibow) [reply src/Controls/src/Core/Span.cs:162]: It is, sort of. The method returns 14 if the span is attached and 0 if not. The issue with these default value functions is that it sets the value as if the user set it.

So the OG issue is that the label font was set to a big size, and then the font remains small because by the time the label is rendered the framework overrides the big with the default of 14.

So if you do:

```cs
// in ctor
var firstSpan = new Span();
var firstSize = span.FontSize; // <- 0

var secondSpan = new Span();
var label = new Label {
    FontSIze = 100,
    FormattedText = new FormattedString { secondSpan }
};

// after rendering
var secondSize = secondSpan.FontSize; // <- 14
```

In both cases, you did not set a font size on the span, and in the second you actually set a size on the label. And that size is not used.

The NaN is a way to tell the rest of the framework that no size has been set, so keep looking.
