### PR TITLE
Fixed Footer not displayed at the Bottom When EmptyView in CV2

### LINKED ISSUE #28604: Footer Not Displayed at the Bottom When EmptyView is Active in CV2
### Description

When the EmptyView is active in the CollectionView, the Footer/Footer Template is not displayed at the bottom as expected. Instead, it appears misaligned or is not rendered properly.  

https://github.com/user-attachments/assets/ac3138d5-20b8-4d58-8122-b28398d860c6

### Steps to Reproduce

1. Launch the application [EmptyViewSample.zip](https://github.com/user-attachments/files/19447151/EmptyViewSample.zip)
2. Select Header/header template, Footer/footer template , EmptyView(string).
3. Observe that the Footer/Footer Template is not displayed at the bottom as expected. 

Expected Behavior:

The Footer should remain visible and positioned at the bottom of the CollectionView, even when the EmptyView is active.
 
Actual Behavior:

The Footer is not displayed at the bottom when the EmptyView is active.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.50 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

macOS, iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### LINKED ISSUE #28605: EmptyViewTemplate Does Not Apply HeightRequest and WidthRequest, Causing Header and Footer to Be Invisible in CV2
### Description

When the EmptyViewTemplate is active in the CollectionView, the Header and Footer are not visible. Initially, this issue appeared when setting HeightRequest and WidthRequest in the EmptyViewTemplate, as the values were not applied, preventing proper resizing. Additionally, even without setting HeightRequest and WidthRequest, the Header and Footer remain invisible.

However, the EmptyView itself respects these properties and resizes correctly. When HeightRequest and WidthRequest are explicitly set in the EmptyView, the Header and Footer become visible. But without explicitly setting these values, the Header and Footer do not appear.

https://github.com/user-attachments/assets/1171fd36-0197-4a41-b945-7f9b7167059d

### Steps to Reproduce

1. Launch the Application  [EmptyViewSample.zip](https://github.com/user-attachments/files/19447797/EmptyViewSample.zip)
2. Select EmptyViewTemplate(View with size), Header/header template and Footer/Footer template.
3. Observe that header and footer is not visible.
4. Select EmptyViewTemplate (View) , Header/header template and Footer/Footer template. Observe that header and footer is not visible.
5. Select EmptyView(view) , Header/header template and Footer/Footer template. Observe that header and footer is not visible.

Expected Behavior:

- The Header and Footer should always be visible, regardless of whether HeightRequest and WidthRequest are explicitly set for the EmptyView and EmptyViewTemplate.
- The EmptyViewTemplate should adjust its size based height and width values.

Actual Behavior:

- When EmptyViewTemplate with and without explicitly setting HeightRequest and WidthRequest, the Header and Footer are not visible.
- The EmptyViewTemplate should not adjust its size based on  HeightRequest and WidthRequest values.
- When EmptyView without explicitly setting HeightRequest and WidthRequest, the Header and Footer are not visible.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.50 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

iOS, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Dhivya-SF4094**
### Issue Detail:

When the EmptyView is active in the CollectionView, the Footer/Footer Template is not displayed at the bottom as expected.

### Root Cause

When the EmptyView is active in CollectionView, the layout logic does not correctly position the Footer/FooterTemplate. The existing implementation fails to adjust the footer's position relative to the EmptyView, leading to improper alignment. This happens because the LayoutEmptyView method does not account for the footer's placement when the CollectionView is empty.
 
When footer is given as string,  footer is not being properly tagged with FooterTag when it is created or updated. Without the tag, the CollectionView cannot identify the Footer view during layout calculations, which causes the footerView to be null in the LayoutEmptyView method.

### Description of Change
In ItemsViewController.cs, the LayoutEmptyView() method was updated to return a CGRect.Empty when the EmptyView is not properly initialized, ensuring correct layout calculations for the EmptyView.
In StructuredItemsViewController.cs, the LayoutEmptyView() method was overridden to adjust the footer’s position. When the EmptyView is visible, and if the EmptyView has no height, the footer is aligned to the bottom of the CollectionView's content.
The footer’s position is updated using ViewWithTag(FooterTag), ensuring that it remains correctly rendered at the bottom.
Also by adding the cell.Tag property in the UpdateDefaultSupplementaryView method, the Footer and Header is explicitly tagged with FooterTag. 

Validated the behaviour in the following platforms
- [ ] Android
- [ ] Windows
- [x] iOS
- [x] Mac

### Issues Fixed:

Fixes #28604 
Fixes #28605

### Screenshots
**Header and Footer as String**
| Before  | After  |
|---------|--------|
|   |     |

**Header and Footer as View**
| Before  | After  |
|---------|--------|
|   |     |

**Header and Footer as Template**
| Before  | After  |
|---------|--------|
|   |     |

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs [hunk 1]
```diff
@@ -88,9 +88,8 @@ public override void ViewWillLayoutSubviews()
 				{
 					RemeasureLayout(_footerViewFormsElement);
 				}
-
-				UpdateHeaderFooterPosition();
 			}
+			UpdateHeaderFooterPosition();
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs:92]: Is this change necessary? Shouldn't invoke `UpdateHeaderFooterPosition`  if `hasHeaderOrFooter` is true?

File: src/Controls/tests/TestCases.HostApp/Issues/Issue28604.cs [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+        {
+            AutomationId = "CollectionView",
+            ItemsSource = ViewModel.ItemList,
+            EmptyView = "EmptyView",
+            Header = new StackLayout
+            {
+                Children =
+                    {
+                        new Label
+                        {
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.HostApp/Issues/Issue28604.cs:26]: Can set the BackgroundColor? In this way, we not only verify the position of the header/footer, also the size with the snapshot comparison.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.HostApp/Issues/Issue28604.cs (hunk 2 above)
Comment (Dhivya-SF4094) [reply src/Controls/tests/TestCases.HostApp/Issues/Issue28604.cs:27]: @jsuarezruiz Updated test sample.

File: src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs (hunk 1 above)
Comment (Dhivya-SF4094) [reply src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs]: @jsuarezruiz, Updated the condition by modifying the hasHeaderOrFooter value to properly account for the presence of a Header or Footer in the ItemsView. Could you please review the fix once.

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28604.cs [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+    {
+    }
+    public override string Issue => "Footer Not Displayed at the Bottom When EmptyView is Active in CV2";
+
+    [Test]
+    [Category(UITestCategories.CollectionView)]
+    public void FooterShouldDisplayAtBottomOfEmptyView()
+    {
+        App.WaitForElement("CollectionView");
+        VerifyScreenshot();
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28604.cs:20]: Pending snapshots, already available in the latest build:
image
Could you commit the images?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28604.cs (hunk 3 above)
Comment (Dhivya-SF4094) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28604.cs:20]: @jsuarezruiz Added the images.

**Review by rmarinho — DISMISSED** [review]

**Review by jsuarezruiz — DISMISSED** [review]

**Review by PureWeen — APPROVED** [review]
