### PR TITLE
IndexOf() stackOverflow fix (#20083)

### LINKED ISSUE #21991: Maui app run with Exception Unhandled "System.StackOverflowException: 'Exception of type 'System.StackOverflowException' was thrown.'" when change maui control to 8.0.40-nightly.10537
### Description

Maui app run with Exception Unhandled "System.StackOverflowException: 'Exception of type 'System.StackOverflowException' was thrown.'" when change maui control to 8.0.40-nightly.10537

Binlogging: [BuildLoggin.zip](https://github.com/dotnet/maui/files/15071991/BuildLoggin.zip)

### Steps to Reproduce

1. Add maui-nightly "https://pkgs.dev.azure.com/xamarin/public/_packaging/maui-nightly/nuget/v3/index.json" feed to your local Nuget.config file. 
2. Created Maui project or use https://github.com/rachelkang/recipeSearch project.
3. Open .csproject file replace the package version for **Microsoft.Maui.Controls** & **Microsoft.Maui.Controls.Compatibility** to **8.0.40-nightly.10537+sha.b0e562e532-azdo.9451576**
4. Wait for package loading to complete, then run with windows machine, or android device.
image

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

Nightly /8.0.40-nightly.10537+sha.b0e562e532-azdo.9451576 /8.0.40-nightly.10539+sha.be17057ee6-azdo.9453171
### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.20 SR4/ 8.0.40-nightly.10515+sha.d6a3c50c93-azdo.9437127

### Affected platforms

Android, Windows

### Relevant log output

```shell
Expecption Unhandled
System.StackOverflowException
  HResult=0x800703E9
  Message=Exception of type 'System.StackOverflowException' was thrown.

Microsoft.Maui.dll!Microsoft.Maui.EnumerableExtensions.IndexOf<Microsoft.VisualStudio.DesignTools.MauiTap.WindowContext>(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.DesignTools.MauiTap.WindowContext> enumerable, System.Func<Microsoft.VisualStudio.DesignTools.MauiTap.WindowContext, bool> predicate)	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.EnumerableExtensions.IndexOf<Microsoft.VisualStudio.DesignTools.MauiTap.WindowContext>(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.DesignTools.MauiTap.WindowContext> enumerable, System.Func<Microsoft.VisualStudio.DesignTools.MauiTap.WindowContext, bool> predicate)	Unknown
 	[The 1 frame(s) above this were repeated 5655 times]	
 	Microsoft.Maui.Controls.HotReload.Forms.dll!Microsoft.VisualStudio.DesignTools.MauiTap.ElementSelectionManager.RegisterWindow(Microsoft.Maui.IWindow window)	Unknown
 	Microsoft.Maui.Controls.HotReload.Forms.dll!Microsoft.VisualStudio.DesignTools.MauiTap.ElementSelectionManager.Initialize()	Unknown
 	Microsoft.Maui.dll!Microsoft.Maui.Dispatching.Dispatcher.DispatchImplementation.AnonymousMethod__0()	Unknown
 	Microsoft.InteractiveExperiences.Projection.dll!ABI.Microsoft.UI.Dispatching.DispatcherQueueHandler.Do_Abi_Invoke(nint thisPtr)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference _obj, Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
>	MauiApp5.dll!MauiApp5.WinUI.Program.Main(string[] args) Line 31	C#
```

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

A small correction to this PR: https://github.com/dotnet/maui/pull/20083 that fixes the StackOverflow exception

Screenshot 2024-04-21 at 13 34 51

Screenshot 2024-04-21 at 13 46 06

### Issues Fixed

Fixes https://github.com/dotnet/maui/pull/20083
Fixes #21991

### CODE REVIEW

**Comment by symbiogenesis** [comment]
I would change lines 150-153 to the following and leave everything else unchanged.

```csharp
if (enumerable is List<T> list)
{
	var predicateNew = new Predicate<T>(predicate);
	return list.FindIndex(predicateNew);
}
```

**Comment by kubaflo** [comment]
> This won't fix it. There is an infinite recursive loop. Sorry about that! Good catch.
> 
> I would replace lines 150-153 with the following and leave everything else unchanged.
> 
> ```cs
> if (enumerable is List<T> list)
> {
> 	var listPredicate = new Predicate<T>(predicate);
> 	return list.FindIndex(listPredicate);
> }
> 
> if (enumerable is T[] array)
> {
> 	var arrayPredicate = new Predicate<T>(predicate);
> 	return Array.FindIndex(array, arrayPredicate);
> }
> ```

The solution that I'm proposing fixes it - I tested it

**Comment by symbiogenesis** [comment]
> > This won't fix it. There is an infinite recursive loop. Sorry about that! Good catch.
> > I would replace lines 150-153 with the following and leave everything else unchanged.
> > ```cs
> > if (enumerable is List<T> list)
> > {
> > 	var listPredicate = new Predicate<T>(predicate);
> > 	return list.FindIndex(listPredicate);
> > }
> > 
> > if (enumerable is T[] array)
> > {
> > 	var arrayPredicate = new Predicate<T>(predicate);
> > 	return Array.FindIndex(array, arrayPredicate);
> > }
> > ```
> 
> The solution that I'm proposing fixes it - I tested it

I think testing more would show that it still isn't fixed, because the self-referential call. The code I propose should also fix it, with no other changes on any lines.

**Comment by kubaflo** [comment]
> > > This won't fix it. There is an infinite recursive loop. Sorry about that! Good catch.
> > > I would replace lines 150-153 with the following and leave everything else unchanged.
> > > ```cs
> > > if (enumerable is List<T> list)
> > > {
> > > 	var listPredicate = new Predicate<T>(predicate);
> > > 	return list.FindIndex(listPredicate);
> > > }
> > > 
> > > if (enumerable is T[] array)
> > > {
> > > 	var arrayPredicate = new Predicate<T>(predicate);
> > > 	return Array.FindIndex(array, arrayPredicate);
> > > }
> > > ```
> > 
> > 
> > The solution that I'm proposing fixes it - I tested it
> 
> I think testing more would show that it still isn't fixed, because the self-referential call. The code I propose should fix it, with no other changes on any lines.

Yep, your fix works

File: src/Core/src/Extensions/EnumerableExtensions.cs [hunk 1]
```diff
@@ -147,9 +147,16 @@ public static int IndexOf<T>(this IEnumerable<T> enumerable, Func<T, bool> predi
 				throw new ArgumentNullException(nameof(enumerable));
 			}
 
-			if (enumerable is IList<T> list)
+			if (enumerable is List<T> list)
```
Comment (jsuarezruiz) [inline src/Core/src/Extensions/EnumerableExtensions.cs:150]: Could we include some unit tests?

**Review by rmarinho — CHANGES_REQUESTED** [review]
Yeah, since it passed the first time, would be great to add a test to reproduce the issue so it doesn't happen again

**Comment by symbiogenesis** [comment]
Added them here:

https://github.com/dotnet/maui/pull/21978

**Comment by kubaflo** [comment]
@rmarinho so can we please merge these 2 PRs since it is annoying that we cannot debug now without making these changes to the source code
