### PR TITLE
[C] 2W bindings always apply

### LINKED ISSUE #16849: [regression/8.0.0-preview.1.7762] TwoWay Binding does not work when value is changed from the source ViewModel
### Description

I have Entry and Text property with TwoWay Binding. When I change the property in the ViewModel the UI of the Entry is not updated. Even though the example is with Entry I think there is a major issue with the TwoWay Binding because I am observing this issue in multiple controls.

I've tested the my code against the latest changes in net 8 and the issue persists.

### Steps to Reproduce

1. Run the project.
2. Change the text in the Entry.
3. Click the Button that sets the Text of the Entry to empty in the ViewModel.
4. Notice how the text in the Entry itself is not changed.

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/MauiBindingIssue

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change

don't ask me why, that's how it is

### Issues Fixed

- fixes #16849

### CODE REVIEW

File: src/Controls/tests/Core.UnitTests/BindingUnitTests.cs [hunk 1]
```diff
@@ -2308,5 +2308,35 @@ public void NullRefWithDefaultCtor()
...
+			Assert.Equal("foo", vm.Text);
+			vm.Text = "bar";
+			Assert.Equal("bar", entry.Text);
+			vm.Text = string.Empty;
+			Assert.Equal(string.Empty, entry.Text);
+		}
+
+		[Fact]
+		//https://github.com/dotnet/maui/issues/16849
+		public void ManualValueDoesntClearWayBinding()
```
Comment (samhouts) [inline src/Controls/tests/Core.UnitTests/BindingUnitTests.cs:2329]:
```suggestion
		public void ManualValueDoesntClearTwoWayBinding()
```

**Review by samhouts — DISMISSED** [review]

**Review by rmarinho — APPROVED** [review]
