### PR TITLE
[Windows] Fix issues drawing brushes in Frame

### LINKED ISSUE #5490: Frame Background not working on Windows
### Description

The Background property of a frame doesn't work on Windows. It works on Android.

### Steps to Reproduce

1) Create a new MAUI project

2) In MainPage.xaml, replace the Label on Row 0 with this:
```
      <Frame Grid.Row="0"
             WidthRequest="100"
             HeightRequest="100"
             BorderColor="Red"
             Background="Purple"/>
```

3) Start on Windows, you'll only see a red border.

4) Start on Android, you'll see a purple box with a red border as expected

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows Version	10.0.19044 Build 19044

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix issues drawing brushes in Frame on Windows (not rendering).

### Issues Fixed

Fixes #5490

### CODE REVIEW

File: src/Controls/src/Core/Compatibility/Handlers/Windows/FrameRenderer.cs [hunk 1]
```diff
@@ -67,16 +67,7 @@ protected override void OnElementPropertyChanged(object sender, PropertyChangedE
...
-			// because the background would protrude through the border if the corners are rounded
-			// as the background would be applied to the renderer's FrameworkElement
-			Color backgroundColor = Element.BackgroundColor;
-
-			if (Control != null)
-			{
-				Control.Background = backgroundColor.IsDefault() ?
-					new Microsoft.UI.Xaml.Media.SolidColorBrush((global::Windows.UI.Color)Resources["SystemAltHighColor"]) : backgroundColor.ToPlatform();
-			}
+			UpdateBackground();
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Compatibility/Handlers/Windows/FrameRenderer.cs:70]: With this changes we render correctly the Background brush (also the background color).

File: src/Controls/src/Core/Platform/Windows/Extensions/BrushExtensions.cs [hunk 2]
```diff
@@ -47,6 +47,7 @@ public static WBrush ToBrush(this Brush brush)
 			{
 				var wRadialGradientBrush = new WRadialGradientBrush()
 				{
+					GradientOrigin = new WPoint(radialGradientBrush.Center.X, radialGradientBrush.Center.Y),
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Windows/Extensions/BrushExtensions.cs:50]: This changes are to fix a mistake creating the RadialGradientBrush.

Before
radialbrush-before
After
radialbrush-after

**Review by Redth — APPROVED** [review]
