### PR TITLE
Fix RelayCommand binding inference for On*Async patterns

### LINKED ISSUE #34029: SourceGen warning MAUIG2045 with RelayCommand and Async postfix
### Description

The latest 10.0.40 release has a regression bug where the XAML source generator doesn't play nice with the source generator of CommunityToolkit.Mvvm.

Consider the following viewmodel where the command DoSomethingCommand is generated:

```
public partial class MainViewModel : ObservableObject
{
  [RelayCommand]
  private Task DoSomethingAsync()
  {
    return Task.CompletedTask;
  }
}
```

And the following XAML button binding the command:

```
<Button  Command="{Binding DoSomethingCommand}" />
```

Enable SourceGen in csproj:

```
<MauiXamlInflator>SourceGen</MauiXamlInflator>
```

With MAUI 10.0.40 the following build warning is emitted:
```
Warning MAUIG2045 : Binding: Property "DoSomethingCommand" not found on "global::xx.MainViewModel". The binding will use slower reflection-based binding at runtime. If this property is generated by another source generator, consider reporting this at https://github.com/dotnet/maui/issues to help us improve source generator interoperability.
```

With warning-as-error, this results in an error.

### Steps to Reproduce

1. Clone the repro project
2. Build
3. Observe the build error (TreatWarningsAsError is enabled)

### Link to public reproduction project repository

https://github.com/zwikk/maui-playground/tree/main/Source/SourceGenCommand

### Version with bug

10.0.40

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

10.0.30

### Affected platforms

iOS, Android, macOS

### Affected platform versions

Any

### Did you find any workaround?

There are 3 workarounds I know of.

- Remove the Async suffix
- Disable SourceGen
- Revert back to 10.0.30

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

## Summary
- fix RelayCommand inference for generated command properties when source methods use `On*`, `*Async`, or `On*Async` naming
- prevent MAUIG2045 false positives for compiled bindings that target those generated command properties
- add regression coverage in BindingSourceGen and SourceGen unit tests

## Related issues
- Fixes #34029
- Duplicate issue #34086 was closed in favor of #34029

## Validation
- `dotnet test src/Controls/tests/BindingSourceGen.UnitTests/Controls.BindingSourceGen.UnitTests.csproj --filter "RelayCommandTests.DetectsRelayCommandMethodWithOnPrefixAndAsyncSuffix"`
- `dotnet test src/Controls/tests/SourceGen.UnitTests/SourceGen.UnitTests.csproj --filter "BindingDiagnosticsTests.BindingToRelayCommandGeneratedFromOnAsyncMethod_DoesNotReportPropertyNotFound"`

### CODE REVIEW

File: src/Controls/src/BindingSourceGen/ITypeSymbolExtensions.cs [hunk 1]
```diff
@@ -68,31 +68,59 @@ public static bool TryGetRelayCommandPropertyType(this ITypeSymbol symbol, strin
...
+			var methods = GetAllMethods(symbol, candidateMethodName);
+			foreach (var method in methods)
 			{
-				// Try to find the ICommand interface type
-				var icommandType = compilation.GetTypeByMetadataName("System.Windows.Input.ICommand");
-				if (icommandType != null)
+				// Check if the method has the RelayCommand attribute
+				var hasRelayCommand = method.GetAttributes().Any(attr =>
+					attr.AttributeClass?.Name == "RelayCommandAttribute" ||
+					attr.AttributeClass?.ToDisplayString() == "CommunityToolkit.Mvvm.Input.RelayCommandAttribute");
```
Comment (jonathanpeppers) [inline src/Controls/src/BindingSourceGen/ITypeSymbolExtensions.cs:84]: This feels odd that we have to hardcode names from another library. Would another library appear that has a similar pattern?

Is the real fix, there needs to be some attribute (something?) that RelayCommandAttribute opts into for this behavior? Something more general-purpose?

**Review by jonathanpeppers — APPROVED** [review]
Heard the problem is there isn't a way to "order" source generators, so we have a few hacks with known generators.

We can probably find better solution down the road.
