### PR TITLE
[Android, iOS] Fix for Shell flyout navigation fires NavigatedTo before Loaded event

### LINKED ISSUE #29428: `Shell.CurrentState` doesn't match `Shell.CurrentPage` when `Page.NavigatedTo` is called using a relative route
### Description

As the title says. Note, they DO match when a global/`ShellContent` route is used.

### Steps to Reproduce

1. Clone the reproduction repository https://github.com/bzd3y/ShellNavigation.git
2. Run the application and wait for it to start
3. Add a breakpoint at `MauiProgram.cs:26`
4. Click the button on "Home"/`MainPage`. It will navigate to `MainPage2`
5. View the values of the variables in the handler method using the debugger
6. Stop debugging, restart the application and use the `ShellContent` routes from the flyout menu to see that the values all match

### Link to public reproduction project repository

https://github.com/bzd3y/ShellNavigation.git

### Version with bug

9.0.60 SR6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

No.

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by praveenkumarkarunanithi**
### Root Cause
The issue was isolated to Shell flyout navigation, where the NavigatedTo event fired before the Loaded event—violating the expected lifecycle order. This did not occur with other navigation methods like `GoToAsync`.

The root cause lies in `Shell.SendNavigated()`, which triggers `CurrentPage.SendNavigatedTo()` immediately after navigation, without verifying if the page has fully loaded. On Windows, this is correctly deferred using `fe.OnLoaded(FirePendingNavigationFinished)` at `StackNavigationManager.cs`, ensuring `NavigatedTo` fires only after the page is ready. However, iOS and Android lack this deferment, leading to premature event dispatching.
 
### Description of Change
The solution adds a deferred `NavigatedTo` event mechanism at the Shell level to ensure consistent behavior across all platforms. A new private method `PropagateSendNavigatedTo()` replaces the direct `SendNavigatedTo()` call in `Shell.SendNavigated()`.

This method checks if the current page is already loaded. If loaded, it immediately fires the NavigatedTo event. If not loaded, it waits for the Loaded event before firing NavigatedTo, ensuring proper event order.

The deferred timing disrupted Android's flyout observer chain, so `CurrentContent?.EvaluateDisconnect()` was added to **restore Android flyout functionality** after the NavigatedTo event.

The fix maintains backward compatibility and only affects Shell flyout navigation timing. It includes proper event cleanup to prevent memory leaks and provides cross-platform consistency that matches the reliable behavior already present in Windows.
 
### Issues Fixed
Fixes #29428  - [Issue reporter comment](https://github.com/dotnet/maui/issues/29428#issuecomment-2876946628)

### Fix Reference
A similar approach can be seen in [ModalNavigationManager](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.cs#L411).
 
Tested the behaviour in the following platforms
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Output Video
Before Issue Fix | After Issue Fix |
|----------|----------|
|<video width="40" height="60" alt="Before Fix" src="https://github.com/user-attachments/assets/1f512775-b65c-4f8f-8bf0-519b1d288e73">|<video width="50" height="40" alt="After Fix" src="https://github.com/user-attachments/assets/2c6188af-223f-4df6-b471-0f233840d8c1">|

### CODE REVIEW

File: src/Controls/src/Core/Shell/Shell.cs [hunk 1]
```diff
@@ -1596,7 +1596,7 @@ void SendNavigated(ShellNavigatedEventArgs args)
 			}
 
 			_previousPage?.SendNavigatedFrom(new NavigatedFromEventArgs(CurrentPage, navigationType));
-			CurrentPage?.SendNavigatedTo(new NavigatedToEventArgs(_previousPage));
+			PropagateSendNavigatedTo();
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Shell/Shell.cs:1703]: There are a couple of related test failing:
image
Could you review it locally to verify if are related with the changes?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Shell/Shell.cs (hunk 1 above)
Comment (praveenkumarkarunanithi) [reply src/Controls/src/Core/Shell/Shell.cs:1703]: @jsuarezruiz , I've reviewed the failing tests locally, and they were related to the recent changes. The issues have now been resolved, and the branch has been updated with the necessary fixes.

File: src/Controls/src/Core/Shell/Shell.cs [hunk 2]
```diff
@@ -1605,6 +1605,37 @@ void SendNavigated(ShellNavigatedEventArgs args)
...
+				void OnCurrentPageLoaded(object sender, EventArgs e)
+				{
+					if (sender is Page page)
+					{
+						page.Loaded -= OnCurrentPageLoaded;
+						page.SendNavigatedTo(new NavigatedToEventArgs(_previousPage));
+
+						// Restore flyout behavior observers after deferred NavigatedTo timing
+						// Android requires this call to maintain flyout functionality
+						CurrentContent?.EvaluateDisconnect();
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Shell/Shell.cs]: The comment says "Android requires this call" but there's no platform check. This might have unintended side effects on iOS?

File: src/Controls/src/Core/Shell/Shell.cs [hunk 3]
```diff
@@ -1605,6 +1605,37 @@ void SendNavigated(ShellNavigatedEventArgs args)
...
+			}
+
+			// On Windows, the Loaded event has already fired (IsLoaded=true), so SendNavigatedTo runs immediately without altering the flow.
+			if (CurrentPage.IsLoaded)
+			{
+				CurrentPage.SendNavigatedTo(new NavigatedToEventArgs(_previousPage));
+			}
+			else
+			{
+				void OnCurrentPageLoaded(object sender, EventArgs e)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Shell/Shell.cs]: If the page is removed/disposed before Loaded fires, the event handler will never be unsubscribed.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Controls/src/Core/Shell/Shell.cs (hunk 2 above)
Comment (praveenkumarkarunanithi) [reply src/Controls/src/Core/Shell/Shell.cs]: @jsuarezruiz Addressed in the latest commit by wrapping `EvaluateDisconnect`() with `#if ANDROID` to ensure it only executes on Android.

File: src/Controls/src/Core/Shell/Shell.cs (hunk 3 above)
Comment (praveenkumarkarunanithi) [reply src/Controls/src/Core/Shell/Shell.cs]: @jsuarezruiz  The implementation now properly unsubscribes the `Loaded` event handler in `SendNavigating` when navigating away before the page loads, preventing potential memory leaks in scenarios where pages are removed or disposed before the `Loaded` event fires.

**Review by kubaflo — DISMISSED** [review]

**Comment by praveenkumarkarunanithi** [comment]
> ## 🤖 AI Summary
> 📊 **Expand Full Review**
> **🔍 Pre-Flight — Context & Validation**
> 📝 **Review Session** — **Merge branch 'dotnet:main' into 29428-fix** · [`4af501e`](https://github.com/dotnet/maui/commit/4af501ea7710c2bf86da67f1dc787d6522e7639d)
> **Issue:** #29428 - Shell flyout navigation fires NavigatedTo before Loaded event **Platforms Affected:** iOS, Android **Files Changed:** 1 implementation file (`Shell.cs`), 2 test files
> 
> ### Problem Summary
> When using Shell flyout navigation (selecting items from the flyout menu), the `NavigatedTo` event fires **before** the `Loaded` event on iOS and Android. This violates the expected page lifecycle order where `Loaded` should fire before `NavigatedTo`.
> 
> **Key finding from issue reporter:**
> 
> > "It looks like the `Page.NavigatedTo` event gets triggered before the handler does its mapping as well as before `Page.Loaded` is triggered."
> 
> This issue is **specific to Shell flyout navigation** - other navigation methods like `GoToAsync` work correctly.
> 
> ### Platform Analysis
> * **Windows:** Already handles this correctly by deferring `NavigatedTo` via `OnLoaded(FirePendingNavigationFinished)` in `StackNavigationManager.cs`
> * **iOS/Android:** Missing this deferment mechanism, causing premature event dispatch
> 
> ### PR Discussion Highlights
> **Reviewer Concerns:**
> 
> File:Line	Reviewer Says	Author Response	Status
> Shell.cs:1622	If the page is removed/disposed before Loaded fires, the event handler will never be unsubscribed	Added unsubscribe in when navigating away before page loads	RESOLVED
> Shell.cs:1631	The comment says 'Android requires this call' but there's no platform check. This might have unintended side effects on iOS?	Wrapped with	RESOLVED
> Shell.cs:1625	Test failures related to changes	Reviewed and resolved locally, branch updated RESOLVED	
> Shell.cs:1635	Copilot nitpick: local function should be declared before usage	Not MINOR	addressed
> ### Fix Candidates
> #	Source	Approach	Test Result	Files Changed	Notes
> PR	PR #30757	Defer via - checks if page is loaded; if not, subscribes to event first	PASS (Gate)	`Shell.cs` (+51/-10), test files	Original PR. Android-specific `EvaluateDisconnect()` call to restore flyout observer chain
> **🚦 Gate — Test Verification**
> 📝 **Review Session** — **Merge branch 'dotnet:main' into 29428-fix** · [`4af501e`](https://github.com/dotnet/maui/commit/4af501ea7710c2bf86da67f1dc787d6522e7639d)
> **Result PASSED :** **Platform:** android **Mode:** Full Verification
> 
> * Tests **FAIL** without fix (bug present without Shell.cs changes)
> * Tests **PASS** with fix (bug fixed with Shell.cs changes)
> 
> ### Details
> The verify-tests-fail-without-fix skill ran a full verification cycle on Android:
> 
> 1. **Without Fix (Reverted Shell.cs to merge base):**
>    
>    * Tests correctly detected the bug
>    * Event order was incorrect: `NavigatedTo` fired before `Loaded`
> 2. **With Fix (PR branch):**
>    
>    * Tests passed successfully
>    * Event order is correct: `Loaded` fires before `NavigatedTo`
> 
> **Conclusion:** The tests properly validate the fix and catch the bug when present.
> 
> **🔧 Fix — Analysis & Comparison**
> 📝 **Review Session** — **Merge branch 'dotnet:main' into 29428-fix** · [`4af501e`](https://github.com/dotnet/maui/commit/4af501ea7710c2bf86da67f1dc787d6522e7639d)
> ### Fix Candidates
> #	Source	Approach	Test Result	Files Changed	Notes
> 1	try-fix (claude-sonnet-4.5)	DispatchDelayed(50ms) to defer NavigatedTo PASS	Shell.cs (+20/-1)	Works but uses arbitrary 50ms timing	
> 2	try-fix (claude-opus-4.6)	Self-unsubscribing Loaded event closure PASS	Shell.cs (+15/-1)	Deterministic, minimal code, captures state in closure	
> 3	try-fix (gpt-5.2)	ConditionalWeakTable to track pending NavigatedTo per page PASS	Shell.cs (+53/-2)	Handles multiple navigations, uses external state table	
> 4	try-fix (gpt-5.2-codex)	Dispatcher polling until FAIL	Shell.cs (+31/-1)	IsLoaded=true doesn't guarantee Loaded event fired	IsLoaded
> 5	try-fix (gemini-3-pro-preview)	Platform-specific: #if WINDOWS uses IsLoaded, others use Loaded event PASS	Shell.cs (+38/-1)	Acknowledges platform differences explicitly	
> 6	try-fix (gpt-5.2)	Wait for Page.Appearing event (Round FAIL	Shell.cs	NavigatedTo never fired within test window	2)
> 7	try-fix (gpt-5.2-codex)	Hook PageViewController.Appeared native lifecycle (Round FAIL	Shell.cs, PageViewController.cs	Build errors: MEM0001, RS0016	2)
> PR	PR #30757	Named method PropagateSendNavigatedTo + field _navigationType + cleanup in SendNavigating + Android EvaluateDisconnect PASS (Gate)	Shell.cs (+51/-10)	Original PR - comprehensive with cleanup and Android fix	
> **Exhausted:** Yes - All 5 models consulted across 3 rounds
> 
> **Selected Fix:** PR's fix - Most complete solution with memory leak prevention and Android-specific flyout restoration
> 
> **📋 Report — Final Recommendation**
> 📝 **Review Session** — **Merge branch 'dotnet:main' into 29428-fix** · [`4af501e`](https://github.com/dotnet/maui/commit/4af501ea7710c2bf86da67f1dc787d6522e7639d)
> Final Recommendation: REQUEST CHANGES##
> 
> ### Summary
> PR #30757 fixes the Shell flyout navigation event ordering issue on iOS and Android (NavigatedTo now fires after Loaded). The fix is architecturally sound and the tests validate the event ordering. However, a **critical bug** was found during code review: `NavigatedToEventArgs.PreviousPage` will always be `null` on iOS/Android due to `_previousPage` being nulled before the deferred Loaded callback executes.
> 
> **Gate PASSED (Android) - Tests correctly fail without fix, pass with fix :** **Fix Exploration:** 4 passing alternatives found, PR's approach selected as most complete **Code Critical issue found - `_previousPage` null regressionReview:**
> 
> ## Phase Results
> Phase	Status	Key Findings
> **Pre-Flight COMPLETE	Issue affects iOS/Android only, specific to Shell flyout navigation	**
> **Gate PASSED	Tests fail without fix, pass with fix (Android platform)	**
> **Fix COMPLETE	5 models explored, 4 passing alternatives, PR's fix selected as most complete	**
> **Report COMPLETE	Request changes - critical PreviousPage regression needs fix	**
> ## Root Cause (of original issue)
> `NavigatedTo`.
> 
> Windows already handles this correctly via `fe.OnLoaded(FirePendingNavigationFinished)` in `StackNavigationManager.cs`.
> 
> ## Critical Issue Found in Code Review
> **`_previousPage` is null in deferred `NavigatedToEventArgs`:**
> 
> In `SendNavigated()`, `_previousPage` is set to null immediately after `PropagateSendNavigatedTo()` returns:
> 
> ```cs
> PropagateSendNavigatedTo();  // subscribes to Loaded event (async deferred path)
> _previousPage = null;         // nulled immediately after!
> ```
> 
> When `OnCurrentPageLoaded` fires asynchronously, `_previousPage` is already `null`:
> 
> ```cs
> page.SendNavigatedTo(new NavigatedToEventArgs(_previousPage, _navigationType));
> // _previousPage == null here for iOS/Android deferred path!
> ```
> 
> On Windows, `IsLoaded == true` so it fires immediately (before `_previousPage = correct behavior. But iOS/Android always use the deferred path when navigating via flyout, so `NavigatedToEventArgs.PreviousPage` will **always be null**, regressing from the original behavior.null`)
> 
> **Fix:** Capture `_previousPage` in `PropagateSendNavigatedTo()` before it's nulled, or store as local field.
> 
> ## Fix Quality
> The PR's deferred `NavigatedTo` mechanism is the right approach and was chosen above 4 alternatives for being the most complete solution. The critical bug only affects `NavigatedToEventArgs.PreviousPage` and is a one-line fix. All other aspects of the PR are excellent:
> 
> * Memory leak prevention (cleanup in `SendNavigating`)
> * `#if ANDROID` guard on `EvaluateDisconnect`
> * Tests validate event ordering correctly
> * Matches `ModalNavigationManager` pattern
> 
> ## Title & Description
> * Title needs minor polish (remove "Fix for" prefix)
> * Description needs NOTE block prepended
> * Description content itself is excellent quality
> 
> ## Recommendation
> **REQUEST CHANGES** - Fix the `_previousPage` null bug (one-line change), add NOTE block, update title. The core approach is correct and approved by a human reviewer (kubaflo). Once this null regression is fixed, the PR is ready to merge.
> 
> 📋 **Expand PR Finalization Review**
> Title: ✅ Good
> 
> **Current:** `[Android, iOS] Fix for Shell flyout navigation fires NavigatedTo before Loaded event`
> 
> Description: ✅ Good
> 
> Description needs updates. See details below.
> 
> ### ✨ Suggested PR Description
> # Recommended Description for PR #30757
> > [!NOTE]
> > Are you waiting for the changes in this PR to be merged?
> > It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!
> 
> ### Root Cause
> The issue was isolated to Shell flyout navigation, where the NavigatedTo event fired before the Loaded event—violating the expected lifecycle order. This did not occur with other navigation methods like `GoToAsync`.
> 
> The root cause lies in `Shell.SendNavigated()`, which triggers `CurrentPage.SendNavigatedTo()` immediately after navigation, without verifying if the page has fully loaded. On Windows, this is correctly deferred using `fe.OnLoaded(FirePendingNavigationFinished)` at `StackNavigationManager.cs`, ensuring `NavigatedTo` fires only after the page is ready. However, iOS and Android lack this deferment, leading to premature event dispatching.
> 
> ### Description of Change
> The solution adds a deferred `NavigatedTo` event mechanism at the Shell level to ensure consistent behavior across all platforms. A new private method `PropagateSendNavigatedTo()` replaces the direct `SendNavigatedTo()` call in `Shell.SendNavigated()`.
> 
> This method checks if the current page is already loaded. If loaded, it immediately fires the NavigatedTo event. If not loaded, it waits for the Loaded event before firing NavigatedTo, ensuring proper event order.
> 
> The deferred timing disrupted Android's flyout observer chain, so `CurrentContent?.EvaluateDisconnect()` was added (wrapped in `#if ANDROID`) to **restore Android flyout functionality** after the NavigatedTo event.
> 
> The fix maintains backward compatibility and only affects Shell flyout navigation timing. It includes proper event cleanup in `SendNavigating` to prevent memory leaks and provides cross-platform consistency that matches the reliable behavior already present in Windows.
> 
> ### Fix Reference
> A similar approach can be seen in [ModalNavigationManager](https://github.com/dotnet/maui/blob/main/src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.cs#L411).
> 
> ### Issues Fixed
> Fixes #29428 - [Issue reporter comment](https://github.com/dotnet/maui/issues/29428#issuecomment-2876946628)
> 
> ### Platforms Tested
> * [x]  Android
> * [x]  Windows
> * [x]  iOS
> * [x]  Mac
> 
> Code Review: ⚠️ Issues Found
> 
> # Code Review — PR #30757
> **File reviewed:** `src/Controls/src/Core/Shell/Shell.cs`
> 
> ## 🔴 Critical Issues
> ### `NavigatedToEventArgs.PreviousPage` is always `null` in deferred path
> * **File:** `src/Controls/src/Core/Shell/Shell.cs`
> * **Lines:** 1667–1668 and 1699
> 
> **Problem:** In `SendNavigated()`, `_previousPage` is set to `null` immediately after `PropagateSendNavigatedTo()` returns:
> 
> ```cs
> _previousPage?.SendNavigatedFrom(new NavigatedFromEventArgs(CurrentPage, _navigationType));
> PropagateSendNavigatedTo();  // If !IsLoaded → subscribes CurrentPage.Loaded += OnCurrentPageLoaded
> _previousPage = null;         // ← Set to null immediately (line 1668)
> ```
> 
> When `OnCurrentPageLoaded` fires asynchronously (after the page loads):
> 
> ```cs
> void OnCurrentPageLoaded(object sender, EventArgs e)
> {
>     if (sender is Page page)
>     {
>         page.Loaded -= OnCurrentPageLoaded;
>         page.SendNavigatedTo(new NavigatedToEventArgs(_previousPage, _navigationType));
>         // ↑ _previousPage is null here! Already cleared at line 1668.
>     }
> }
> ```
> 
> **Impact:** `NavigatedToEventArgs.PreviousPage` will **always be `null`** for Android and iOS Shell flyout navigation (the deferred path). On Windows, `IsLoaded` is already `true` so `SendNavigatedTo` fires synchronously before `_previousPage = null` — Windows is unaffected.
> 
> **This is a regression:** Before this PR, `PreviousPage` was correctly passed. Any user code that reads `e.PreviousPage` in a `NavigatedTo` handler will receive `null` on Android/iOS Shell flyout navigation after this PR.
> 
> **Recommendation:** Capture `_previousPage` into a local variable before it's nulled, and close over it in the deferred handler:
> 
> ```cs
> void PropagateSendNavigatedTo()
> {
>     if (CurrentPage is null)
>         return;
> 
>     var previousPage = _previousPage; // capture before _previousPage is nulled
>     var navigationType = _navigationType;
> 
>     if (CurrentPage.IsLoaded)
>     {
>         CurrentPage.SendNavigatedTo(new NavigatedToEventArgs(previousPage, navigationType));
>     }
>     else
>     {
>         CurrentPage.Loaded += OnCurrentPageLoaded;
> 
>         void OnCurrentPageLoaded(object sender, EventArgs e)
>         {
>             if (sender is Page page)
>             {
>                 page.Loaded -= OnCurrentPageLoaded;
>                 page.SendNavigatedTo(new NavigatedToEventArgs(previousPage, navigationType));
>                 // Note: using local captures, not instance fields
> #if ANDROID
>                 CurrentContent?.EvaluateDisconnect();
> #endif
>             }
>         }
>     }
> }
> ```
> 
> Alternatively (minimal change): move `_previousPage = null` to AFTER `PropagateSendNavigatedTo()` captures the value — but this is more fragile. The local-capture approach is cleaner and removes the need for the `_navigationType` instance field as well.
> 
> ## 🟡 Suggestions
> ### 1. `_navigationType = default` only reset in deferred path (inconsistent)
> In `OnCurrentPageLoaded`, `_navigationType = default` is called after sending the event. But in the immediate path (`CurrentPage.IsLoaded == true`), no reset occurs. Functionally harmless since `_navigationType` is always overwritten at the start of `SendNavigated`, but inconsistent.
> 
> If the local-capture approach above is adopted, `_navigationType` can remain a local variable in `SendNavigated` and the instance field can be removed entirely — cleaner and avoids the inconsistency.
> 
> ### 2. `OnCurrentPageLoaded` declared after its use (style)
> `OnCurrentPageLoaded` is a method declared on the class after `PropagateSendNavigatedTo`, but it's referenced (subscribed) inside `PropagateSendNavigatedTo`. This is valid C# but an unresolved copilot nitpick noted in the review comments. If refactored to a local function (as recommended above), this issue disappears naturally.
> 
> ## ✅ Looks Good
> * **Memory leak prevention:** `SendNavigating` correctly unsubscribes `Loaded` handler when navigating away before page loads (lines 1755–1759). This covers the case where a user navigates rapidly before the destination page loads.
> * **`#if ANDROID` guard on `EvaluateDisconnect()`:** Correctly platform-specific. This was added based on reviewer feedback from @jsuarezruiz and is confirmed in the current diff.
> * **UI test coverage:** `Issue29428.cs` records event order via label text and asserts `"Loaded called first then NavigatedTo called"` — directly validates the fix.
> * **`OnDisappearing` resets label:** The test page resets the label on disappear, so re-navigating to the page doesn't carry stale state.
> * **Approach alignment:** Mirrors the `ModalNavigationManager` pattern (`OnLoaded` deferred callback), which is the established codebase idiom.
> * **All prior reviewer concerns resolved:** The `#if ANDROID` guard and `SendNavigating` cleanup were added after @jsuarezruiz's review comments.

All concerns raised in the AI Agent summary have been addressed. The suggested local-function approach was evaluated but cannot be used because `SendNavigating` requires explicit unsubscription (`CurrentPage.Loaded -= OnCurrentPageLoaded`) to avoid memory leaks, which would not be possible if the handler were scoped as a local function.

**Comment by kubaflo** [comment]
## 🤖 AI Summary


<details>
<summary>📊 <strong>Expand Full Review</strong> — <a href="https://github.com/dotnet/maui/commit/0facf6ee893a04d105b4fca82ffb6986ae43fd51"><code>0facf6e</code></a> · <strong>Merge remote-tracking branch 'origin/29428-fix-update' into 29428-fix</strong></summary>

---

<details>
<summary><strong>🔍 Pre-Flight — Context & Validation</strong></summary>

---

**Issue:** #29428 - Shell flyout navigation fires NavigatedTo before Loaded event
**PR:** #30757 - [Android, iOS] Fix for Shell flyout navigation fires NavigatedTo before Loaded event
**Platforms Affected:** Android, iOS (Windows already handles this correctly)
**Files Changed:** 1 implementation (`Shell.cs` +58/-10), 2 test files (new UI test)

### Key Findings
- Shell flyout navigation fires `NavigatedTo` before `Loaded` on iOS/Android only
- Windows already defers via `fe.OnLoaded(FirePendingNavigationFinished)` in `StackNavigationManager.cs`
- Root cause: `Shell.SendNavigated()` calls `CurrentPage.SendNavigatedTo()` immediately without checking if page is loaded
- PR adds `PropagateSendNavigatedTo()` to defer the event until after `Loaded` fires
- Prior agent review found `_previousPage` null regression - fixed in latest commits via `_pendingPreviousPage`/`_pendingNavigationType` fields
- Prior reviewer concerns (jsuarezruiz) addressed: `#if ANDROID` guard on `EvaluateDisconnect()` + `SendNavigating` cleanup to prevent memory leaks
- Author confirmed all prior reviewer comments resolved

### Prior Agent Review Summary (March 2026)
- Pre-Flight: ✅ COMPLETE
- Gate: ✅ PASSED (Android) 
- Try-Fix: ✅ COMPLETE (5 models, 4 passing alternatives; PR's fix selected)
- Report: ⚠️ REQUEST CHANGES (due to `_previousPage` null regression)
- Author has since fixed the null regression using `_pendingPreviousPage`/`_pendingNavigationType` capture approach

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #30757 | `PropagateSendNavigatedTo()` with `_pendingPreviousPage`/`_pendingNavigationType` capture + `#if ANDROID` `EvaluateDisconnect()` + `SendNavigating` cleanup | ⏳ PENDING (Gate) | `Shell.cs` (+58/-10) | Updated to fix _previousPage null regression |

### Result: ✅ COMPLETE


**Issue:** #29428 - `Shell.CurrentState` doesn't match `Shell.CurrentPage` when `Page.NavigatedTo` is called using a relative route
**PR:** #30757 - [Android, iOS] Fix for Shell flyout navigation fires NavigatedTo before Loaded event
**Platforms Affected:** Android, iOS (Windows already had a fix via StackNavigationManager)
**Files Changed:** 1 implementation (`Shell.cs`), 2 test files (`Issue29428.cs` in HostApp and SharedTests)

### Prior Agent Review
A prior agent review was found in PR comments (review based on commit `4af501e`). That review:
- Phase Pre-Flight: ✅ COMPLETE
- Phase Gate: ✅ PASSED (Android)
- Phase Try-Fix: ✅ COMPLETE (5 models, 4 passing alternatives)
- Phase Report: ✅ COMPLETE — Requested changes due to critical bug: `_previousPage` would be null in deferred callback

**Status of prior critical bug:**  
The prior review found that `NavigatedToEventArgs.PreviousPage` would always be `null` on iOS/Android due to `_previousPage` being nulled before the deferred `Loaded` callback executes.  
**The current code FIXES this** via `_pendingPreviousPage = _previousPage` (captured before nulling) in `PropagateSendNavigatedTo()`. This was addressed in the `29428-fix-update` branch merged on 2026-03-04.

### Key Findings
- **Root Cause**: `Shell.SendNavigated()` fired `CurrentPage.SendNavigatedTo()` before the page was loaded on iOS/Android. Windows handled this correctly via `StackNavigationManager`.
- **Fix**: `PropagateSendNavigatedTo()` checks `CurrentPage.IsLoaded` — if loaded, fires immediately; otherwise defers via `Loaded` event handler.
- **Memory Leak Prevention**: `SendNavigating()` unsubscribes `OnCurrentPageLoaded` if navigating away before page loads.
- **Android Flyout Fix**: `EvaluateDisconnect()` is called after deferred `NavigatedTo` on Android (wrapped in `#if ANDROID`).
- **PreviousPage Capture**: `_pendingPreviousPage` and `_pendingNavigationType` capture state before `_previousPage = null`.
- **Test**: UI test verifies "Loaded called first then NavigatedTo called" via Shell flyout navigation.
- **Reviewer comment (jsuarezruiz)** noted `#if ANDROID` was later added (resolved) and memory leak concern (resolved with unsubscribe in `SendNavigating`).

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #30757 | `PropagateSendNavigatedTo()` defers via `Loaded` event + `_pendingPreviousPage/Type` + Android `EvaluateDisconnect` | ⏳ PENDING (Gate) | `Shell.cs` (+58/-10) | Original PR — now includes fix for null PreviousPage regression |

---

**Issue:** #29428 - Shell.CurrentState doesn't match Shell.CurrentPage when Page.NavigatedTo is called (Shell flyout navigation fires NavigatedTo before Loaded event)
**PR:** #30757 - [Android, iOS] Fix for Shell flyout navigation fires NavigatedTo before Loaded event
**Platforms Affected:** Android, iOS (Windows already handled correctly)
**Files Changed:** 1 implementation (`Shell.cs`, +58/-10), 2 test files (HostApp + SharedTests)
**Author:** praveenkumarkarunanithi (Syncfusion partner)
**PR State:** Open, not merged — updated 2026-03-16 (today)

---

### Problem Summary

When using Shell flyout navigation, the `NavigatedTo` event fires **before** the `Loaded` event on iOS and Android. This violates the expected page lifecycle order.

- **Specific to:** Shell flyout navigation (`ShellItemChanged`, `ShellSectionChanged`, `ShellContentChanged`)
- **Not affected:** `GoToAsync`, Push/Pop navigation
- **Windows:** Already correct — uses `fe.OnLoaded(FirePendingNavigationFinished)` in `StackNavigationManager.cs`
- **Android/iOS:** Missing deferment mechanism → premature `NavigatedTo` dispatch

### Prior Agent Review (commit 4af501e)

A prior agent review was found. Key findings:
- **Gate:** PASSED — tests fail without fix, pass with fix (Android)
- **Critical Bug Found:** `_previousPage` was null in deferred `NavigatedToEventArgs` — `_previousPage` was nulled before the deferred `Loaded` callback fired
- **Recommendation:** REQUEST CHANGES — fix the null regression

### Current State (commit 0facf6ee — updated since prior review)

The author has **addressed the critical bug** from the prior review:
- Added `_pendingPreviousPage` and `_pendingNavigationType` fields
- `PropagateSendNavigatedTo()` now captures `_previousPage` into `_pendingPreviousPage` before it's nulled
- `OnCurrentPageLoaded` uses `_pendingPreviousPage` (not `_previousPage`) — null regression fixed

### Key Design Elements

1. **`PropagateSendNavigatedTo()`** — checks `IsLoaded`:
   - If loaded → fires `SendNavigatedTo` immediately (Windows path)
   - If not loaded → subscribes to `Loaded` event, captures `_pendingPreviousPage`
2. **`OnCurrentPageLoaded`** — fires `SendNavigatedTo` with pending args, cleans up
3. **`#if ANDROID` guard** on `CurrentContent?.EvaluateDisconnect()` — only Android needs this
4. **Memory leak prevention** in `SendNavigating()` — unsubscribes handler if navigating away before page loads
5. **Instance fields promoted** — `navigationType` (local) → `_navigationType` (field) to support deferred access

### PR Discussion Highlights

| File | Reviewer | Concern | Resolution |
|------|----------|---------|------------|
| Shell.cs:1622 | jsuarezruiz | Page removed before Loaded fires — handler never unsubscribed | Added cleanup in `SendNavigating` ✅ |
| Shell.cs:1631 | jsuarezruiz | Comment says Android-only but no platform check | Wrapped with `#if ANDROID` ✅ |
| Shell.cs:1625 | jsuarezruiz | Test failures related to changes | Fixed locally, branch updated ✅ |
| Shell.cs | copilot | Nitpick: local function order | Not addressed (minor, outdated) |
| Prior agent | Agent | `_previousPage` null regression | Fixed with `_pendingPreviousPage` fields ✅ |

### Fix Candidates (initial)

| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #30757 | `PropagateSendNavigatedTo()` — defers via `Loaded` event if page not loaded; uses `_pendingPreviousPage`/`_pendingNavigationType` to fix null regression; `#if ANDROID` for `EvaluateDisconnect` | ⏳ PENDING (Gate) | `Shell.cs` (+58/-10), 2 test files | Updated from prior review — null bug fixed |

</details>

---

<details>
<summary><strong>🚦 Gate — Test Verification</strong></summary>

---

### Gate Result: ✅ PASSED

**Platform:** android
**Mode:** Full Verification

- Tests FAIL without fix: ✅
- Tests PASS with fix: ✅

### Details

Full verification completed successfully on Android (emulator-5554).

**Test:** `Issue29428` — `ShellFlyoutNavigationEventOrderShouldBeCorrect`

**Without fix (Shell.cs reverted to merge-base `f6314b55`):**
- Build succeeded on attempt 2 (first attempt had a transient ADB install failure: `NullPointerException` in `PackageManagerService.freeStorage`, unrelated to the fix)
- Tests **FAILED** with exit code 1 ✅ — confirms the bug is present without the fix

**With fix (Shell.cs restored from HEAD):**
- Build succeeded in ~405 seconds
- NUnit ran 1 test: `Issue29428(Android)` → **Passed** ✅
- `Test Run Successful. Passed: 1`

**Conclusion:** The test `Issue29428.ShellFlyoutNavigationEventOrderShouldBeCorrect` correctly catches the regression introduced by missing the fix in `Shell.cs`, and passes once the fix is applied. The PR's fix is validated end-to-end.

**Detailed report:** `CustomAgentLogsTmp/PRState/30757/PRAgent/gate/verify-tests-fail/verification-report.md`


### Gate Result: ✅ PASSED

**Platform:** android
**Mode:** Full Verification

- Tests FAIL without fix: ✅
- Tests PASS with fix: ✅

---

### Gate Result: ✅ PASSED

**Platform:** Android
**Mode:** Full Verification

- Tests FAIL without fix: ✅ (bug correctly detected — NavigatedTo fired before Loaded)
- Tests PASS with fix: ✅ (fix resolves the issue)

### Details

Both builds completed cleanly. The test `ShellFlyoutNavigationEventOrderShouldBeCorrect` in `Issue29428.cs`:
- **Without fix (Shell.cs reverted):** Test FAILED — NavigatedTo fired before Loaded
- **With fix (PR's Shell.cs):** Test PASSED — Loaded fires before NavigatedTo

Result: PR #30757 tests correctly catch the bug and validate the fix.

Result: PASSED

</details>

---

<details>
<summary><strong>🔧 Fix — Analysis & Comparison</strong></summary>

---

### Gate Result: ✅ PASSED

**Platform:** android
**Mode:** Full Verification

- Tests FAIL without fix: ✅
- Tests PASS with fix: ✅

### Details

Full verification completed successfully on Android (emulator-5554).

**Test:** `Issue29428` — `ShellFlyoutNavigationEventOrderShouldBeCorrect`

**Without fix (Shell.cs reverted to merge-base `f6314b55`):**
- Build succeeded on attempt 2 (first attempt had a transient ADB install failure: `NullPointerException` in `PackageManagerService.freeStorage`, unrelated to the fix)
- Tests **FAILED** with exit code 1 ✅ — confirms the bug is present without the fix

**With fix (Shell.cs restored from HEAD):**
- Build succeeded in ~405 seconds
- NUnit ran 1 test: `Issue29428(Android)` → **Passed** ✅
- `Test Run Successful. Passed: 1`

**Conclusion:** The test `Issue29428.ShellFlyoutNavigationEventOrderShouldBeCorrect` correctly catches the regression introduced by missing the fix in `Shell.cs`, and passes once the fix is applied. The PR's fix is validated end-to-end.

**Detailed report:** `CustomAgentLogsTmp/PRState/30757/PRAgent/gate/verify-tests-fail/verification-report.md`


### Gate Result: ✅ PASSED

**Platform:** android
**Mode:** Full Verification

- Tests FAIL without fix: ✅
- Tests PASS with fix: ✅

---

# Try-Fix Attempts — PR #30757

## Status: ✅ COMPLETE

### Fix Candidates
| # | Source | Approach | Test Result | Files Changed | Notes |
|---|--------|----------|-------------|---------------|-------|
| PR | PR #30757 | `PropagateSendNavigatedTo()` — defer via `Loaded` event if not loaded; `_pendingPreviousPage`/`_pendingNavigationType` fields to prevent null regression; `#if ANDROID` EvaluateDisconnect; cleanup in SendNavigating | ✅ PASSED (Gate) | `Shell.cs` (+58/-10) | Original PR — null bug fixed in latest commit |
| 1 | try-fix (claude-opus-4.6) | Fix in `Page.SendNavigatedTo()` — defer via `Loaded` event at the Page layer, not Shell; 1 new field `_deferredNavigatedToHandler`; no `#if ANDROID` needed; broader fix (all nav containers) | ✅ PASS | `Page.cs` (+35/-0) | Different layer from PR; cleaner; fixes more than just Shell flyout |
| 2 | try-fix (claude-sonnet-4.6) | Closure-based deferral in Shell.cs — inline lambda captures `previousPage`/`currentPage`/`navigationType` as locals; 1 instance field `_cleanupPendingLoadedHandler` (Action) for cleanup; no named methods; no `#if ANDROID` | ✅ PASS | `Shell.cs` (+37/-2) | Fewer fields than PR (1 vs 3); cleaner closure captures; no Android special-casing |
| 3 | try-fix (gpt-5.3-codex) | Shell-local dispatcher deferral — `DispatchDelayed` retries until `IsLoaded`; no Loaded event subscription; no pending instance fields; no Page.cs changes | ✅ PASS | `Shell.cs` | No event subscription; polling via dispatcher; simpler state but timing-dependent |
| 4 | try-fix (gemini-3-pro-preview) | `ConditionalWeakTable<Page, NavigatedToEventArgs>` — static table stores pending args per-page; static handler fires `SendNavigatedTo` on `Loaded`; also flushes pending if nav-away occurs before load | ✅ PASS | `Shell.cs` (+62/-2) | No instance fields on Shell; memory-safe (weak refs); more complex but robust edge case handling |
| 5 | try-fix (claude-sonnet-4.6) | HandlerChanged hook → chain to Loaded — subscribes to `HandlerChanged` first (native view attachment), then chains to `Loaded`; zero new instance fields; self-cleaning via `page != CurrentPage` check | ✅ PASS | `Shell.cs` (+68/-2) | Two-stage deferral; no instance fields; clean but more complex chain |

### Cross-Pollination

| Model | Round | New Ideas? | Details |
|-------|-------|------------|---------|
| claude-opus-4.6 | 2 | Yes | Platform ShellSectionHandler — delay nav-complete signal until native view attached |
| claude-sonnet-4.6 | 2 | Yes | Hook Page.OnHandlerChanged — defer until Handler is non-null |
| gpt-5.3-codex | 2 | Yes | Queue pending NavigatedTo, flush from HandlerChanged/WindowChanged hook |
| gemini-3-pro-preview | 2 | Yes | Platform ShellFlyoutRenderer — dispatch after OnAttachedToWindow/ViewDidAppear |
| claude-opus-4.6 | 3 | **NO NEW IDEAS** | Design space exhausted across all three axes |
| claude-sonnet-4.6 | 3 | Yes | IShellSectionController pipeline gate — variation of existing patterns |
| gpt-5.3-codex | 3 | Yes | FIFO queue with attached behavior — variation of ConditionalWeakTable |
| gemini-3-pro-preview | 3 | Yes | Handler CommandMapper intercept — variation of HandlerChanged approach |

**Exhausted:** Yes — Max 3 rounds reached; remaining Round 3 ideas are variations of already-explored patterns.

---

### Best Fix Selection

**Selected Fix: PR's fix (#30757)**

| Criterion | PR Fix | Best Alternative (Attempt 2) |
|-----------|--------|------------------------------|
| Tests pass | ✅ | ✅ |
| Android EvaluateDisconnect | ✅ Yes (`#if ANDROID`) | ❌ Missing |
| Memory leak prevention | ✅ Cleanup in SendNavigating | ✅ Cleanup via Action field |
| State clarity | ✅ Named fields + methods | ✅ Closure captures |
| Code complexity | Medium (3 fields, 2 methods) | Lower (1 field, inline lambda) |
| Codebase style | ✅ Consistent with Shell.cs patterns | ✅ Also acceptable |

**Reason:** The PR's fix is the only candidate that includes `CurrentContent?.EvaluateDisconnect()` (under `#if ANDROID`), which the PR description explicitly states is needed to restore Android flyout observer chain after deferred timing. The test validates event ordering but does NOT test flyout re-opening after navigation — so alternatives passing tests doesn't prove Android flyout correctness. PR's fix is the most complete and production-ready solution.

</details>

---

<details>
<summary><strong>📋 Report — Final Recommendation</strong></summary>

---

### Gate Result: ✅ PASSED

**Platform:** android
**Mode:** Full Verification

- Tests FAIL without fix: ✅
- Tests PASS with fix: ✅

### Details

Full verification completed successfully on Android (emulator-5554).

**Test:** `Issue29428` — `ShellFlyoutNavigationEventOrderShouldBeCorrect`

**Without fix (Shell.cs reverted to merge-base `f6314b55`):**
- Build succeeded on attempt 2 (first attempt had a transient ADB install failure: `NullPointerException` in `PackageManagerService.freeStorage`, unrelated to the fix)
- Tests **FAILED** with exit code 1 ✅ — confirms the bug is present without the fix

**With fix (Shell.cs restored from HEAD):**
- Build succeeded in ~405 seconds
- NUnit ran 1 test: `Issue29428(Android)` → **Passed** ✅
- `Test Run Successful. Passed: 1`

**Conclusion:** The test `Issue29428.ShellFlyoutNavigationEventOrderShouldBeCorrect` correctly catches the regression introduced by missing the fix in `Shell.cs`, and passes once the fix is applied. The PR's fix is validated end-to-end.

**Detailed report:** `CustomAgentLogsTmp/PRState/30757/PRAgent/gate/verify-tests-fail/verification-report.md`


### Gate Result: ✅ PASSED

**Platform:** android
**Mode:** Full Verification

- Tests FAIL without fix: ✅
- Tests PASS with fix: ✅

</details>

---

</details>




<details>
<summary>📋 <strong>Expand PR Finalization Review</strong></summary>

# PR #30757 Finalization Review

**PR:** [Android, iOS] Fix for Shell flyout navigation fires NavigatedTo before Loaded event  
**Author:** praveenkumarkarunanithi  
**Base Branch:** main  
**Files Changed:** 3 (Shell.cs, Issue29428.cs × 2)  
**Labels:** platform/android, platform/ios, community ✨, partner/syncfusion  

---

## Phase 1: Title & Description

### ⚠️ Title: Needs Minor Update

**Current:** `[Android, iOS] Fix for Shell flyout navigation fires NavigatedTo before Loaded event`  
**Recommended:** `[Android, iOS] Shell: Defer NavigatedTo until after Loaded for flyout navigation`

**Rationale:**
- "Fix for" is redundant noise in a commit headline — the PR being merged already implies a fix
- The recommended title follows the `[Platform] Component: What changed` formula
- "Defer NavigatedTo until after Loaded" describes the action taken, which is more searchable and meaningful in `git log`

---

### ⚠️ Description: Good Quality — Only Missing NOTE Block

**Quality Assessment:**

| Dimension | Rating | Notes |
|-----------|--------|-------|
| Structure | ✅ | Clear sections: Root Cause, Description of Change, Issues Fixed, Fix Reference |
| Technical depth | ✅ | Explains the mechanism, Android-specific workaround, cross-platform context |
| Accuracy | ✅ | Matches actual diff — PropagateSendNavigatedTo, OnCurrentPageLoaded, EvaluateDisconnect |
| Completeness | ✅ | Platform checklist, issue link, prior-art reference (ModalNavigationManager) |
| NOTE block | ❌ | Missing — required for artifact testers |

**Action:** Prepend the NOTE block to the top. Preserve the rest as-is.

**Required addition (prepend to top of description):**

```markdown
<!-- Please let the below note in for people that find this PR -->
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!
```

---

## Phase 2: Code Review

### 🟡 Medium: Pending State Not Cleared on Early Navigation

**File:** `src/Controls/src/Core/Shell/Shell.cs`  
**Method:** `SendNavigating()`

When the user navigates away before the current page has loaded, the code correctly unsubscribes the `Loaded` event handler:

```csharp
if (CurrentPage != null && !CurrentPage.IsLoaded)
{
    CurrentPage.Loaded -= OnCurrentPageLoaded;
}
```

However, `_pendingPreviousPage` and `_pendingNavigationType` are **not cleared** at the same point. These fields are only reset inside `OnCurrentPageLoaded`, which now won't fire. If the next `PropagateSendNavigatedTo` call lands in the `IsLoaded == true` branch (fast navigation on Windows), the stale pending fields remain in memory until `OnCurrentPageLoaded` eventually doesn't fire — meaning `_pendingPreviousPage` holds a `Page` reference that may delay GC of that page object.

**Recommendation:** Clear the pending fields alongside the unsubscribe:

```csharp
if (CurrentPage != null && !CurrentPage.IsLoaded)
{
    CurrentPage.Loaded -= OnCurrentPageLoaded;
    _pendingPreviousPage = null;
    _pendingNavigationType = default;
}
```

---

### 🟡 Medium: Instance Fields Shared Across Rapid Navigations

**File:** `src/Controls/src/Core/Shell/Shell.cs`

The fix promotes what was a local variable (`navigationType`) into instance fields (`_navigationType`, `_pendingPreviousPage`, `_pendingNavigationType`). With rapid or interrupted navigation (e.g., navigating to Page 2 before it fully loads, then immediately navigating to Page 3), `_pendingPreviousPage` and `_pendingNavigationType` from the first navigation are overwritten before `OnCurrentPageLoaded` can consume them. The `SendNavigating` cleanup only unsubscribes the handler on the *current* page at that moment — if the page reference has already changed, the stale handler may remain subscribed.

This scenario is unlikely in practice for flyout navigation, but it could produce `NavigatedTo` firing with incorrect `PreviousPage` or double-firing in edge cases.

**Recommendation:** Consider a guard in `OnCurrentPageLoaded` that compares `page` (the sender) to `CurrentPage` before firing `SendNavigatedTo`. If `page != CurrentPage`, the event is stale and should be discarded silently:

```csharp
void OnCurrentPageLoaded(object sender, EventArgs e)
{
    if (sender is Page page)
    {
        page.Loaded -= OnCurrentPageLoaded;
        
        // Guard: discard if page is no longer current (rapid navigation occurred)
        if (page != CurrentPage)
        {
            _pendingPreviousPage = null;
            _pendingNavigationType = default;
            return;
        }
        
        page.SendNavigatedTo(new NavigatedToEventArgs(_pendingPreviousPage, _pendingNavigationType));
        _pendingPreviousPage = null;
        _pendingNavigationType = default;
#if ANDROID
        CurrentContent?.EvaluateDisconnect();
#endif
    }
}
```

---

### ✅ Looks Good

- **Pattern correctness:** The deferred-firing pattern matches the existing `ModalNavigationManager` approach (referenced in PR description) and the Windows `StackNavigationManager.cs` approach, which already correctly defers via `OnLoaded`. Consistency is maintained.
- **Event cleanup:** `page.Loaded -= OnCurrentPageLoaded` is correctly placed at the top of `OnCurrentPageLoaded` before any other logic, preventing double-fire.
- **Android workaround:** The `#if ANDROID CurrentContent?.EvaluateDisconnect()` call is appropriately guarded to Android-only and placed after `SendNavigatedTo` completes.
- **Null guard in `PropagateSendNavigatedTo`:** Early return on `CurrentPage is null` prevents NREs.
- **Capture order:** `_pendingPreviousPage = _previousPage` is captured *before* `_previousPage = null` runs in `SendNavigated()`. The field ordering and method call order are correct.
- **UI test quality:** Test uses the correct pattern — HostApp page tracks event order in a label, test reads the label text. The assertion `"Loaded called first then NavigatedTo called"` directly validates the fix.
- **`OnDisappearing` resets label:** The test page clears the event label on disappear, allowing re-navigation to retest cleanly.
- **Category:** `[Category(UITestCategories.Shell)]` is appropriate and only one category is applied.

---

## Summary

| Area | Status | Action Required |
|------|--------|-----------------|
| Title | ⚠️ Minor update | Change to action-based phrasing (remove "Fix for") |
| Description | ⚠️ Add NOTE block | Prepend required NOTE block; keep existing content |
| Core fix logic | ✅ Correct | No changes needed |
| Pending state cleanup | 🟡 Improvement | Clear `_pendingPreviousPage`/`_pendingNavigationType` in `SendNavigating` unsubscribe block |
| Rapid-navigation guard | 🟡 Improvement | Add `page != CurrentPage` guard in `OnCurrentPageLoaded` |
| Tests | ✅ Good | Correct pattern, proper automation IDs, clean assertion |

**Overall verdict:** The fix is sound and well-implemented. The two medium findings are defensive improvements that increase robustness for edge cases but do not block the core fix from working correctly for the reported scenario. Adding the NOTE block and addressing the pending-state cleanup before merge is recommended.

</details>

**Review by kubaflo — APPROVED** [review]
