### PR TITLE
[Windows, Android] Resolved issue with dynamic Header/Footer reassignment in CollectionView.

### LINKED ISSUE #27959: [Windows, Android] Toggling Header/Footer in CollectionView Dynamically is not working
### Description

When dynamically toggling the header or footer in a CollectionView by setting it to null and then re-assigning it not working in Windows and Android.

https://github.com/user-attachments/assets/d213e419-666e-4811-bac3-a30b4e6ed593

https://github.com/user-attachments/assets/8412adb0-410a-49c0-a93f-5f72fd12ede1

### Steps to Reproduce

1. Run the given Sample - [Issue25724.zip](https://github.com/user-attachments/files/18907573/Issue25724.zip)
2. Tap the "Toggle Header" button to hide the header.
3. Tap the "Toggle Header" button again to show the header.
4. The header does not toggle; no action occurs.

## Windows Issue:

Problem: After tapping the "Toggle Header" or "Toggle Footer" buttons, the header or footer text gets removed (empties), but it does not return after toggling again. This results in the header/footer not being restored.
**Expected Result:** 
The header/footer should toggle correctly, with the text being displayed when the header/footer is shown.
**Actual Result:** 
After toggling, the header or footer text remains empty and does not return to its original state.

## Android Issue:

Problem: On Android, tapping either the "Toggle Header" or "Toggle Footer" buttons has no effect. The header and footer are not hidden or shown when the buttons are clicked.
**Expected Result:** 
The header/footer should toggle visibility when the corresponding button is tapped.
**Actual Result:** 
Tapping the "Toggle Header" or "Toggle Footer" button does not trigger any changes in the UI.

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.40 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

Android, Windows

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### LINKED ISSUE #28351: [Android] Header and Footer Not Visible in CollectionView When EmptyView is Selected First
### Description

When using a CollectionView in a MAUI application, there is an issue where the Header and Footer are not visible if the EmptyView is selected first. The expected behavior is that the HeaderTemplate and FooterTemplate should be displayed regardless of the order in which the EmptyView and header/footer options are selected.

https://github.com/user-attachments/assets/0e6eefa0-9182-4d65-9d9f-7247b853b114

### Steps to Reproduce

1. Launch the application on Android  [CollectionViewTestBedSample 5.zip](https://github.com/user-attachments/files/19210183/CollectionViewTestBedSample.5.zip)
2. Tap the EmptyView/EmptyViewTemplate button to navigate to the CollectionView Control Page.
3. Tap the Options toolbar item to navigate to the Options Page, then select  EmptyView first and then select Header/footer . Observe that the Header/footer is not displayed.

Expected Behavior: 
The Header and Footer should be visible along with the EmptyView.

Actual Behavior: 
The Header and Footer are not visible when the EmptyView is selected first. However, if the Header and Footer are selected first and then the EmptyView is selected, the header and footer are displayed correctly

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.40 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by prakashKannanSf3972**
### Issue Details

When HeaderTemplate and FooterTemplate are used without EmptyView, assigning null and non-null values to the header and footer at runtime does not trigger a proper UI update.

### Root Cause

The OnPropertyChanged event triggers notifyDataChanged only for the header and footer but does not account for changes in HeaderTemplate and FooterTemplate.

### Description of Change

Enhanced the logic to include HeaderTemplate and FooterTemplate in notifyDataChanged, ensuring correct UI updates during runtime.

### Issue Details

When either HeaderTemplate and FooterTemplate or Header and Footer are used with EmptyView, assigning null and non-null values to the header and footer at runtime does not trigger a proper UI update.

### Root Cause

In the EmptyViewAdapter, the header and footer properties were handled independently. During runtime updates, the newly assigned header and footer values were not properly reassigned within the EmptyViewAdapter, causing the updates to be missed.

### Description of Change

Reassigned the updated header and footer values within the EmptyViewAdapter and ensured NotifyDataSetChanged() is triggered to reflect the changes at runtime.

### Issue Details 

Assigning null to the header and footer at runtime correctly clears them. However, reassigning the previous instance leads to a COM exception.

### Root Cause

The existing handlers associated with the Header and Footer, along with their descendants, remain connected. As a result, reassigning the same instance to both the Header and Footer at runtime leads to a COM exception.

### Description of Change

Invoked the cleanup method to ensure that the Header/Footer and its child elements properly disconnect all handlers, preventing any lingering references and avoiding the COM exception.

**Tested the behaviour in the following platforms**

- [x] Android
- [x]  Windows
- [x]  iOS
- [x] Mac

### Issues Fixed

Fixes #27959 
Fixes #28337
Fixes #28351 

### Output

| Before| After|
|--|--|
| <video src="https://github.com/user-attachments/assets/c53058fa-d2bb-4b32-a4ae-a55bbd9a5b60"> | <video src="https://github.com/user-attachments/assets/9c78a91d-86f9-4b23-9622-3303406f7603">
| <video src="https://github.com/user-attachments/assets/1075f82f-68cf-4f93-ab27-7317bfe1f6ae"> | <video src="https://github.com/user-attachments/assets/20520fa7-969f-408f-b040-1d8f5c46f0fa"> |

### CODE REVIEW

File: src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs [hunk 1]
```diff
@@ -631,5 +635,33 @@ void RemoveScrollListener()
...
 		}
+
+		void UpdateEmptyViewHeaderAndFooterState()
+		{
+			if (ItemsView is StructuredItemsView structuredItemsView)
+			{
+				bool headerOrFooterChanged = false;
+				if (_emptyViewAdapter.Header != structuredItemsView.Header || _emptyViewAdapter.HeaderTemplate != structuredItemsView.HeaderTemplate)
+				{
+					_emptyViewAdapter.Header = structuredItemsView.Header;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs:646]: This logic is repeated with header and footer. Can simplify it creating method like:

```
bool UpdateViewAdapter(ref object currentProperty, object newProperty, ref DataTemplate currentTemplate, DataTemplate newTemplate)
{
    bool propertyChanged = false;

    if (currentProperty != newProperty || currentTemplate != newTemplate)
    {
        currentProperty = newProperty;
        currentTemplate = newTemplate;
        propertyChanged = true;
    }

    return propertyChanged;
}
```

Then use it like:

```
headerOrFooterChanged |= UpdateAdapterProperties(
            ref _emptyViewAdapter.Header,
            structuredItemsView.Header,
            ref _emptyViewAdapter.HeaderTemplate,
            structuredItemsView.HeaderTemplate);
```

And same with footer.

File: src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs [hunk 2]
```diff
@@ -631,5 +635,33 @@ void RemoveScrollListener()
 			ClearOnScrollListeners();
 			RecyclerViewScrollListener = null;
 		}
+
+		void UpdateEmptyViewHeaderAndFooterState()
+		{
+			if (ItemsView is StructuredItemsView structuredItemsView)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs:641]: Can verify directly if:

```
if(_emptyViewAdapter is null)
     return;
```

Comment (prakashKannanSf3972) [reply src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs]: I have modified the suggested changes.

File: src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs [hunk 3]
```diff
@@ -631,5 +635,35 @@ void RemoveScrollListener()
...
 		}
+
+		void UpdateEmptyViewHeaderAndFooterState()
+		{
+			if (ItemsView is not StructuredItemsView structuredItemsView || _emptyViewAdapter is null)
+			{
+				return;
+			}
+
+			bool headerOrFooterChanged = false;
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs]: Can simplify it a little bit just creating two variables:
```
bool headerChanged = _emptyViewAdapter.Header != structuredItemsView.Header ||
 _emptyViewAdapter.HeaderTemplate != structuredItemsView.HeaderTemplate;

bool footerChanged = _emptyViewAdapter.Footer != structuredItemsView.Footer ||
 _emptyViewAdapter.FooterTemplate != structuredItemsView.FooterTemplate;
```

File: src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs [hunk 4]
```diff
@@ -631,5 +635,35 @@ void RemoveScrollListener()
...
+			if (_emptyViewAdapter.Header != structuredItemsView.Header || _emptyViewAdapter.HeaderTemplate != structuredItemsView.HeaderTemplate)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs]: `if (headerChanged)`

File: src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs [hunk 5]
```diff
@@ -631,5 +635,35 @@ void RemoveScrollListener()
...
+			{
+				_emptyViewAdapter.Header = structuredItemsView.Header;
+				_emptyViewAdapter.HeaderTemplate = structuredItemsView.HeaderTemplate;
+				headerOrFooterChanged = true;
+			}
+
+			if (_emptyViewAdapter.Footer != structuredItemsView.Footer || _emptyViewAdapter.FooterTemplate != structuredItemsView.FooterTemplate)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs]: `if (footerChanged)`

File: src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs [hunk 6]
```diff
@@ -631,5 +635,35 @@ void RemoveScrollListener()
...
+			{
+				_emptyViewAdapter.Footer = structuredItemsView.Footer;
+				_emptyViewAdapter.FooterTemplate = structuredItemsView.FooterTemplate;
+				headerOrFooterChanged = true;
+			}
+
+			if (headerOrFooterChanged)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs]: `if (headerChanged || footerChanged)`

**Comment by prakashKannanSf3972** [comment]
@jsuarezruiz, I have updated the changes as suggested.

**Review by kubaflo — CHANGES_REQUESTED** [review]
Could you please resolve conflicts?

**Review by kubaflo — CHANGES_REQUESTED** [review]
Could you please resolve conflicts?

**Review by kubaflo — APPROVED** [review]
