### PR TITLE
[Windows] Fix for NavigationPage transitions still animating when passing animated false to PushAsync or PopAsync

### LINKED ISSUE #11808: WinUI: NavigationPage transitions still animate when passing `animated: false` to PushAsync/PopAsync
### Description

When using `PushAsync` and `PopAsync` with no parameters or when passing `animated: true`, the page transitions animate from side to side as expected. However, when passing `animated: false`, a different vertical animation still occurs on Windows 10.

### Steps to Reproduce

1. Create a new MAUI app
2. Replace `MainPage = new AppShell()` with `MainPage = new NavigationPage(new MainPage())` in App.xaml.cs
3. Add a second content page and write event handlers in the code behind to allow navigating between the two pages with `App.Current.MainPage.Navigation.PushAsync/PopAsync` and pass `animated: false` to those methods.

Expected behavior: There is no transition animation, and the new page appears instantly.

Actual behavior: The new page slides up from the bottom of the screen.

### Link to public reproduction project repository

https://github.com/ArrowCase/TestMauiTransition

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

For some reason, if the first page is removed from the navigation stack after awaiting the `PushAsync` call, there is no longer an animation for the transition.

```cs
Page firstPage = App.Current.MainPage.Navigation.NavigationStack[^1];
await App.Current.MainPage.Navigation.PushAsync(new SecondPage(), animated: false);
App.Current.MainPage.Navigation.RemovePage(firstPage);
```

Obviously, this is not a real workaround.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SyedAbdulAzeemSF4852**
> [!NOTE]
> Are you waiting for the changes in this PR to be merged?
> It would be very helpful if you could [test the resulting artifacts](https://github.com/dotnet/maui/wiki/Testing-PR-Builds) from this PR and let us know in a comment if this change resolves your issue. Thank you!

### Issue Details 

- When using PushAsync and PopAsync with no parameters or when passing animated: true, the page transitions animate from side to side as expected. However, when passing animated: false, a different vertical animation still occurs on Windows.

### Root Cause

- In StackNavigationManager.cs, the GetNavigationTransition method returns null when args.Animated is false. In WinUI, this causes the Frame to fall back to its default NavigationThemeTransition, resulting in a page refresh animation even when animation is intended to be disabled.
- As documented by [Microsoft](https://learn.microsoft.com/en-us/windows/apps/design/motion/page-transitions#:~:text=Note%3A%20A%20Frame%20automatically%20uses%20NavigationThemeTransition%20to%20animate%20navigation%20between%20two%20pages.%20By%20default%2C%20the%20animation%20is%20page%20refresh.), Frame applies this transition by default if no custom one is provided.
- Hence, returning null does not suppress the animation, causing the page to slide up on Windows.

### Description of Change

- [`src/Core/src/Platform/Windows/StackNavigationManager.cs`](diffhunk://#diff-bacfb8be7525ddd50f1f01c8fca339533e09abf8131e14f4f49fceefbfb0407dL123-R125): Updated the `GetNavigationTransition` method to return a `SuppressNavigationTransitionInfo` object instead of `null` when navigation is not animated. This ensures a consistent handling of non-animated transitions.
- About [SuppressNavigationTransitionInfo](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.animation.suppressnavigationtransitioninfo?view=winrt-26100#:~:text=can%20use%20SuppressNavigationTransitionInfo%20in%20the%20place%20of%20other%20NavigationTransitionInfo%20subtypes%20when%20you%20want%20to%20avoid%20playing%20any%20animation%20during%20navigation.)

### Issues Fixed
Fixes #11808 

### Validated the behaviour in the following platforms

- [x] Windows
- [x] Android
- [x] iOS
- [x] Mac

### Output
| Before | After |
|----------|----------|
| <video src="https://github.com/user-attachments/assets/b72438d1-2cdc-4997-9731-0515f7fafb94"> | <video src="https://github.com/user-attachments/assets/b748a7eb-b7cd-4fe8-8bd0-0987749f71b9"> |

### CODE REVIEW

File: src/Core/src/Platform/Windows/StackNavigationManager.cs [hunk 1]
```diff
@@ -120,7 +120,9 @@ protected virtual Type GetDestinationPageType() =>
 		protected virtual NavigationTransitionInfo? GetNavigationTransition(NavigationRequest args)
 		{
 			if (!args.Animated)
-				return null;
+			{
+				return new SuppressNavigationTransitionInfo();
```
Comment (jsuarezruiz) [inline src/Core/src/Platform/Windows/StackNavigationManager.cs]: Creating a new SuppressNavigationTransitionInfo object on every non-animated navigation could be optimized. Can create a static readonly field and reuse it?

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]

File: src/Core/src/Platform/Windows/StackNavigationManager.cs (hunk 1 above)
Comment (SyedAbdulAzeemSF4852) [reply src/Core/src/Platform/Windows/StackNavigationManager.cs]: @jsuarezruiz , As suggested, optimized the creation of SuppressNavigationTransitionInfo by introducing a static readonly instance (s_suppressTransition). This avoids unnecessary object allocations during non-animated navigations.

**Review by kubaflo — APPROVED** [review]
