### PR TITLE
[Android] Fixed the Incorrect Text Color Applied to Selected Tab in TabbedPage

### LINKED ISSUE #28838: Incorrect Text Color Applied to Selected Tab in TabbedPage on Android
### Issue: 
When setting only the `UnselectedTabColor` on a TabbedPage, the selected tab's text color incorrectly adopts the unselected tab color on Android. 

### Expected Behavior: 
If `UnselectedTabColor` is set, it should apply only to the `unselected` tabs. The selected tab should retain the default selected tab text color, unless explicitly overridden. 

### Actual issue image

Image

### Expected image

Image

### Steps to Reproduce

Get the sample here and deploy

[TabbedPageTextColorIssue.zip](https://github.com/user-attachments/files/19645138/TabbedPageTextColorIssue.zip)

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.50 SR5

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 33

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Ahamed-Ali**
### Issue

- When setting only the `UnselectedTabColor` on a TabbedPage, the selected tab's text color incorrectly adopts the unselected tab color on Android. 

### Root Cause of the issue

- The text colors for selected and unselected tabs were not handled correctly.

### Description of Change

- Implemented proper handling of text colors for both selected and unselected tabs to ensure correct behavior in both default and explicitly defined color scenarios.

### Issues Fixed

Fixes #28838 

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Screenshot

| Before Issue Fix | After Issue Fix |
|----------|----------|
|   |     |

### CODE REVIEW

File: src/Controls/src/Core/Platform/Android/TabbedPageManager.cs [hunk 1]
```diff
@@ -635,22 +635,27 @@ protected virtual ColorStateList GetItemTextColorStates()
 			}
 			else
 			{
+				// UnSelected tabs TextColor
 				if (barItemColor is not null)
```
Comment (jsuarezruiz) [inline src/Controls/src/Core/Platform/Android/TabbedPageManager.cs:639]: Here we repeat some code and can just create a new method:

```
int GetItemTextColor(Color? customColor, OriginalTabTextColors? originalColors)
{
    return customColor?.ToPlatform().ToArgb() ?? originalColors?.DefaultColor ?? 0;
}
```
To get a cleaner version: 
```
// UnSelected tabs TextColor
  defaultColor = GetItemTextColor(barItemColor, _originalTabTextColors);

  // Selected tabs TextColor
  checkedColor = GetItemTextColor(barSelectedItemColor, _originalTabTextColors);
```

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28838.cs [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+    public Issue28838(TestDevice device) : base(device) { }
+
+    public override string Issue => "Incorrect Text Color Applied to Selected Tab in TabbedPage on Android";
+
+    [Test]
+    [Category(UITestCategories.TabbedPage)]
+    public void DefaultSelectedTabTextColorShouldApplyProperly()
+    {
+        App.WaitForElement("Tab1");
+        VerifyScreenshot();
```
Comment (jsuarezruiz) [inline src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28838.cs:17]: Pending snapshots in Android, Mac and Windows. Trigger a build.

File: src/Controls/src/Core/Platform/Android/TabbedPageManager.cs (hunk 1 above)
Comment (Ahamed-Ali) [reply src/Controls/src/Core/Platform/Android/TabbedPageManager.cs]: Thanks for the feedback. I have optimized the code as suggested @jsuarezruiz

File: src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28838.cs (hunk 2 above)
Comment (Ahamed-Ali) [reply src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28838.cs:17]: I have added the pending snapshots.

**Review by jsuarezruiz — APPROVED** [review]
