### PR TITLE
[C] implicit style VSM do not override Manual value

### LINKED ISSUE #18103: [regression/8.0.0] Button background does not override implicit visualstate style
### Description

If you create an implicit style with VisualStateGroups, they are no longer overriden in Net 8.
In the sample repo i created an implicit style for all buttons that sets the background to green when visualState is Normal.
I then add a button and override the background to be orange.

In Net7 the button appears orange - this is expected.
In Net8 the button stays green meaning I can no longer override the background color.

### Steps to Reproduce

1. Download repo
2. Run on both net7 and net8 and see the difference - in Net7 it is orange, but in Net8 it is green.

### Link to public reproduction project repository

https://github.com/Zack-G-I-T/ImplicitStyleIssue

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change

[C] implicit style VSM do not override Manual value

### Issues Fixed

- fixes #18103

### CODE REVIEW

File: src/Controls/src/Core/SetterSpecificity.cs [hunk 1]
```diff
@@ -66,8 +66,12 @@ public SetterSpecificity(int style, int id, int @class, int type) : this(0, 0, 0
 
 		public int CompareTo(SetterSpecificity other)
 		{
-			//VSM setters somehow supersedes Styles
-			if (Vsm != other.Vsm)
+			//VSM setters win over Manual value, except for implicit style VSMs
+			if (Vsm != other.Vsm && (
+				   Style != 0 && Style <= StyleImplicit + 99 && other.Manual <= 0
```
Comment (Redth) [inline src/Controls/src/Core/SetterSpecificity.cs:71]: What is the significance of these number values?  Is there any documentation or explanation for what these mean?

Comment (StephaneDelcroix) [reply src/Controls/src/Core/SetterSpecificity.cs:71]: comments on line 33 and following

**Comment by StephaneDelcroix** [comment]
@Redth magic numbers are gone

**Review by Redth — APPROVED** [review]
