### PR TITLE
Workaround Multiple Calls to Activate

### LINKED ISSUE #7894: App Lifecycle event OnResume called more than once.
### Description

The application lifecycle event OnResume is called more than once when an application is minimised/stopped and then resumed.

image

image

### Steps to Reproduce

1. Create a new project using the ".NET MAUI App" template.
2. Edit App.xaml.cs
3. Add within the partial class the following:
```csharp
	private int ResumeCount = 0;
```
4. Add an override method for OnResume:
```csharp
	protected override void OnResume()
	{
		base.OnResume();
		ResumeCount++;
		System.Diagnostics.Debug.WriteLine("{0}: Restarted {1}", DateTimeOffset.UtcNow, ResumeCount);
	}
```
5. Build and launch in debug (Windows Machine):
6. Minimise the app
7. Restore the app
8. In the debug output window, there will be 2 debug statements indicating:
Restarted 1
Restarted 2

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Android 21.0, Windows 10.0.17763.0

### Did you find any workaround?

_No response_

### Relevant log output

```shell
09/06/2022 13:29:24 +00:00: Restarted 1
09/06/2022 13:29:24 +00:00: Restarted 2
```

> VS bug [#1778056](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1778056)

### Depends on
- [ ] https://github.com/microsoft/microsoft-ui-xaml/issues/7343

### LINKED ISSUE #14142: Blazor Hybrid Windows: Window was already activated when minimize and restore from taskbar
### Description

I have a Blazor Hybrid app, debugging in Windows. I'm running against maui main.

 If I minimize the app and then try to restore it again by clicking on the icon in the taskbar, I get an instacrash:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Window was already activated
  Source=Microsoft.Maui.Controls
  StackTrace:
   at Microsoft.Maui.Controls.Window.Microsoft.Maui.IWindow.Activated() in C:\src\github\maui\src\Controls\src\Core\HandlerImpl\Window\Window.Impl.cs:line 491
   at Microsoft.Maui.LifecycleEvents.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__2_2(Window window, WindowActivatedEventArgs args) in C:\src\github\maui\src\Core\src\Hosting\LifecycleEvents\AppHostBuilderExtensions.Windows.cs:line 32
   at Microsoft.Maui.MauiWinUIWindow.<>c__DisplayClass7_0.<OnActivated>b__1(OnActivated del) in C:\src\github\maui\src\Core\src\Platform\Windows\MauiWinUIWindow.cs:line 51
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[TDelegate](IServiceProvider services, Action`1 action) in C:\src\github\maui\src\Core\src\LifecycleEvents\LifecycleEventServiceExtensions.cs:line 31
   at Microsoft.Maui.MauiWinUIWindow.OnActivated(Object sender, WindowActivatedEventArgs args) in C:\src\github\maui\src\Core\src\Platform\Windows\MauiWinUIWindow.cs:line 51
   at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args)
```

### Steps to Reproduce

1. File > New MAUI Blazor
2. Run in Windows
3. Minimize
4. Restore
5. 💥

### Link to public reproduction project repository

try vigilant guide

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

7.0 (current)

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

windows10.0.19041.0

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

This works around https://github.com/microsoft/microsoft-ui-xaml/issues/7343

### Issues Fixed
Fixes #14142
Fixes #7894

### CODE REVIEW

File: src/Core/src/Platform/Windows/MauiWinUIWindow.cs [hunk 1]
```diff
@@ -178,6 +199,11 @@ internal void UpdateTitleOnCustomTitleBar()
 
 		[DllImport("user32.dll", SetLastError = true)]
 		static extern int DestroyIcon(IntPtr hIcon);
+
+		internal void SetWindow(IWindow window)
```
Comment (PureWeen) [inline src/Core/src/Platform/Windows/MauiWinUIWindow.cs:203]: The lifecycle hooks all reached the xplat window by iterating over the static applications windows. This doesn't work very well for the tests because the tests run their own stubbed app that windows get attached to. This removes the need to resort to static scope in order to get from the platform window to the xplat window

**Review by rmarinho — APPROVED** [review]
